import type { DateRangeInputLabels } from '@cuberoot/timer-ui';

export type SupportedLanguage = 'en' | 'zh';

export const COPY = {
  en: {
    account: 'Account',
    accountDetail: 'Use the same CubeRoot email or phone as the website. Sign-in opens the secure system browser.',
    actionFailed: 'That did not work. Your existing data was kept.',
    saveFailed: (count: number) => count === 1
      ? 'One solve is waiting to be saved. Try again to keep it.'
      : `${count} solves are waiting to be saved. Try again to keep them.`,
    saveRetryFailed: 'Still not saved. Try again.',
    saveSessionMissing: 'The original session was deleted. This solve is still waiting to be saved.',
    all: 'All',
    authError: 'Account sign-in is temporarily unavailable. Try again.',
    ao5: 'ao5',
    ao12: 'ao12',
    best: 'Best',
    bestBo3: 'best bo3',
    bestMo3: 'best mo3',
    battleAdmin: 'Room management',
    battleAllFinished: 'Round complete',
    battleAttempts: (count: number) => `${count} attempts`,
    battleBest: (value: string) => `Best ${value}`,
    battleClearHistory: 'Clear battle history',
    battleClearHistoryConfirm: 'Clear all local battle history from this device?',
    battleCopyCode: 'Copy room code',
    battleCopyInvite: 'Copy invite link',
    battleCreateRoom: 'Create room',
    battleCubeHolder: (player: number) => `Cube: Player ${player}`,
    battleCurrentRound: (round: number) => `Round ${round}`,
    battleInviteCopied: 'Room code copied',
    battleIdentity: 'Identity',
    battleHistory: 'History and statistics',
    battleJoinRoom: 'Join room',
    battleKick: 'Remove',
    battleKickConfirm: (name: string) => `Remove ${name} from this room?`,
    battleLeaveRoom: 'Leave room',
    battleLiveRound: 'Live',
    battleLoadingRoom: 'Loading room…',
    battleLocalTitle: 'Local battle',
    battleKeyBindings: 'Player keys',
    battleKeyName: (key: string) => key === ' ' ? 'Space' : key,
    battleName: 'Nickname',
    battleNamePlaceholder: 'Cuber',
    battleNextRound: 'Next round',
    battleNoScramble: 'Preparing scramble…',
    battleNoHistory: 'Completed battle rounds will appear here.',
    battleNoOtherPlayers: 'No other players are in this room.',
    battleOnlineTitle: 'Online battle',
    battleOnlineUnavailable: 'Online battle is unavailable in this app host.',
    battlePhase: (phase: string) => ({
      idle: 'Waiting', ready: 'Ready', inspecting: 'Inspecting', solving: 'Solving', done: 'Done',
    } as Record<string, string>)[phase] ?? phase,
    battlePlayer: (player: number) => `Player ${player}`,
    battlePressKey: 'Press a key…',
    battleReady: 'Ready',
    battleRoomCode: 'Room code',
    battleRoomCodePlaceholder: '4 digits',
    battleRoundLabel: (round: number) => `Round ${round}`,
    battleScore: (score: number) => `${score} wins`,
    battleSearchIdentity: 'Nickname, WCA name, or WCA ID',
    battleScanToJoin: 'Scan to join',
    battleSearchingIdentity: 'Searching WCA people…',
    battleSkipWaiting: 'Skip waiting — next round',
    battleShowQr: 'Invite QR',
    battleSharedCubeDetail: 'Pass one connected smart cube between players. It advances after each completed solve.',
    battleSmartCube: 'Shared smart cube',
    battleSmartCubeOnly333: 'Shared smart-cube timing is available only for 3×3.',
    battleStartTogether: 'Start all',
    battleSyncStart: 'Synchronized start',
    battleTransferAdmin: 'Make host',
    battleTransferAdminConfirm: (name: string) => `Make ${name} the room host?`,
    battleWaitingPlayers: 'Waiting for players',
    battleWinner: 'Winner',
    battleWins: (count: number) => `${count} wins`,
    battleYou: 'You',
    checking: 'Checking',
    clearCompetition: 'Clear competition',
    clearFilters: 'Clear filters',
    clearSearch: 'Clear search',
    clear: 'Clear',
    close: 'Close',
    competition: 'Competition',
    competitionListFailed: 'Could not load competitions.',
    competitionListLoading: 'Loading competitions…',
    competitionScramblesFailed: 'Could not load this competition’s rounds and groups.',
    competitionScramblesLoading: 'Loading rounds and groups…',
    count: 'count',
    current: 'current',
    colorModeCn: 'CN',
    colorModeDual: 'Dual',
    colorModeQuad: 'Quad',
    colorModeSingle: 'Single',
    colorSubset: 'Color subset',
    connect: 'Connect',
    connectingBluetooth: 'Connecting…',
    copied: 'Copied',
    copiedScramble: 'Scramble copied',
    connectBluetooth: 'Connect Bluetooth device',
    comment: 'Comment',
    chooseSession: 'Choose…',
    corruptDetail: 'CubeRoot will not replace invalid data. Import a valid backup to recover.',
    corruptTitle: 'Local data needs attention',
    cubeState: 'Cube state after this scramble',
    data: 'Data',
    dataCount: 'solves stored on this device',
    date: 'Date',
    dateFrom: 'Start date',
    dateRange: 'Date range',
    dateTo: 'End date',
    clearDateRange: 'Clear date range',
    calendarClearDate: 'Clear date',
    calendarChooseDate: 'Choose date',
    calendarPreviousMonth: 'Previous month',
    calendarNextMonth: 'Next month',
    calendarYear: 'Year',
    calendarMonth: 'Month',
    calendarMonthOption: (month: number) => [
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ][month - 1] ?? '',
    calendarWeekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const,
    calendarToday: 'Today',
    calendarDate: (year: number, month: number, day: number) => {
      const monthName = [
        'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
        'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
      ][month - 1] ?? '';
      return `${monthName} ${day}, ${year}`;
    },
    delete: 'Delete',
    deleteAccount: 'Delete account',
    deleteConfirm: 'Delete this solve?',
    deletedSolve: 'Solve deleted',
    deletedLastSolve: 'Deleted last solve',
    difficulty: 'Difficulty',
    difficultyFilter: 'Difficulty filter',
    disconnectBluetooth: 'Disconnect smart cube',
    dnf: 'DNF',
    emptyHistory: 'Your solves will appear here after you stop the timer.',
    filters: 'Filters',
    tags: 'Tags',
    exportData: 'Export backup',
    exportSuccess: 'Backup prepared.',
    fullSite: 'Full website',
    fullSiteDetail: 'Open the complete CubeRoot site when you need tools that are not bundled in the app.',
    finishAttemptFirst: 'Finish or cancel the current attempt before changing timer controls.',
    generatingScramble: 'Generating scramble…',
    group: 'Group',
    groupOption: (group: string) => `Group ${group}`,
    history: 'History',
    historyMatches: (count: number) => `${count} matches`,
    hideExtras: 'Hide extras',
    holdTime: 'Hold to start',
    holdToArm: 'Hold to start',
    importData: 'Import backup',
    importConfirm: (incoming: number, current: number) => `Import ${incoming} solves and replace the current ${current}? You can undo this once from Settings.`,
    importSuccess: 'Backup imported.',
    importTooLarge: 'This backup is larger than 10 MB and was not opened.',
    inspection: 'Inspection',
    keepHolding: 'Keep holding',
    language: 'Language',
    light: 'Light',
    loadingReal: 'Loading real competition scrambles…',
    localDataNotSynced: 'Your timer records remain safely on this device. Cloud sync is not enabled yet.',
    manageAccount: 'Manage account',
    merge: 'Merge',
    mergeAriaLabel: 'Merge all 3×3-family scrambles',
    mergeHelp: 'On draws by difficulty from the whole 3×3 family; off uses only this event.',
    method: 'Method',
    maxSeconds: 'Max (s)',
    mean: 'mean',
    minSeconds: 'Min (s)',
    manual: 'Manual',
    manualOption: 'Manual input',
    manualPasteHint: 'Paste scrambles above — one per line',
    manualScrambles: 'Manual scrambles',
    localRandom: 'Local random scramble',
    my: 'Me',
    more: 'More',
    moreActions: 'More actions',
    moveToSession: 'Move to session',
    newScramble: 'New scramble',
    noEventScrambles: 'This competition has no scrambles for the current event.',
    noMatchingCompetitions: 'No matching competitions.',
    noInspection: 'Off',
    noHistoryMatches: 'No solves match these filters.',
    offline: 'Offline',
    online: 'Online',
    onePlayer: '1 player',
    optimalScramble: 'Optimal scramble',
    ollCase: 'OLL case',
    previousScramble: 'Previous scramble',
    players: (count: number) => `${count}P`,
    pllCase: 'PLL case',
    openTimes: 'Open times and statistics',
    openFullSite: 'Open cuberoot.me',
    openFullTimer: 'Open the full web timer',
    privacy: 'Privacy policy',
    puzzle: 'Puzzle',
    penalty: 'Penalty',
    releaseToStart: 'Release to start',
    retry: 'Try again',
    real: 'Real',
    realOption: 'WCA real',
    realScrambleEmpty: 'No real competition scrambles match this source.',
    realScrambleFailed: 'Could not load real competition scrambles. Try again.',
    realScrambleRange: 'Real-scramble range',
    round: 'Round',
    random: 'Random',
    randomOption: 'Random state',
    replace: 'Replace',
    nextScramble: 'Next scramble',
    save: 'Save',
    searchCompetition: 'Search competition',
    searchHistory: 'Search comment or scramble',
    showAllStats: 'Show all stats',
    single: 'time',
    seconds15: '15 seconds',
    settings: 'Settings',
    signIn: 'Sign in',
    signedInAs: 'Signed in as',
    signingIn: 'Opening sign-in…',
    signOut: 'Sign out of this app',
    scrambleSource: 'Scramble source',
    scrambleLengthRange: 'Scramble length range',
    scrambleCorrection: 'Back to scramble',
    scrambleCorrectionCopied: 'Copied the scramble',
    scrambleCorrectionTitle: 'Off the scramble path. These moves lead back to the same scrambled state; the solve still records the original scramble.',
    scrambleMismatch: 'Doesn’t match',
    scrambleReady: 'Scrambled',
    scrambleUnsupported: 'This puzzle is listed exactly like the website, but its shared scramble provider has not been migrated yet.',
    solved: 'solved',
    statsChangeColumn: (current: string) => `Change stats column, currently ${current}`,
    statsCustomPlaceholder: 'Custom ao',
    statsCustomSize: 'Custom ao size',
    support: 'Support',
    subX: 'Sub-X',
    tools: 'Tools',
    solves: 'Solves',
    system: 'System',
    smartCubeConnected: (name: string) => `${name} connected.`,
    smartCubeDisconnected: 'Smart cube disconnected.',
    smartCubeError: 'Could not connect to the smart cube. Wake it, keep it nearby, and try again.',
    smartCubeOnly333: 'Smart-cube automatic timing is available only for supported 3×3 events.',
    stage: 'Stage',
    stepRange: 'Step range',
    tapToStop: 'Tap to stop',
    theme: 'Theme',
    threeByThree: '3×3 cube',
    timer: 'Timer',
    timerTitle: 'Timer',
    timerHint: 'Touch and hold, then release. Press Space when using a keyboard.',
    times: 'Times',
    title: 'CubeRoot',
    undoImport: 'Undo last import',
    undo: 'Undo',
    undoImportConfirm: 'Restore the data from before the last import?',
    undoImportSuccess: 'Previous data restored.',
    unindexedCompetition: 'This competition is not in the stage-difficulty index yet; Full and Length remain available.',
    version: 'Version',
    worst: 'worst',
    dark: 'Dark',
  },
  zh: {
    account: '账号',
    accountDetail: '使用与网站相同的 CubeRoot 邮箱或手机号。登录会打开安全的系统浏览器。',
    actionFailed: '操作失败，原有数据已保留。',
    saveFailed: (count: number) => `${count} 条成绩正在等待保存，请点击重试保留。`,
    saveRetryFailed: '仍未保存，请再次重试。',
    saveSessionMissing: '原计时分组已被删除，本次成绩仍在等待保存。',
    all: '全部',
    authError: '账号登录暂时不可用，请重试。',
    ao5: 'ao5',
    ao12: 'ao12',
    best: '最佳',
    bestBo3: 'bo3 最佳',
    bestMo3: 'mo3 最佳',
    battleAdmin: '房间管理',
    battleAllFinished: '本轮完成',
    battleAttempts: (count: number) => `${count} 次`,
    battleBest: (value: string) => `最佳 ${value}`,
    battleClearHistory: '清除对战记录',
    battleClearHistoryConfirm: '确定清除此设备上的全部本地对战记录吗？',
    battleCopyCode: '复制房间码',
    battleCopyInvite: '复制邀请链接',
    battleCreateRoom: '创建房间',
    battleCubeHolder: (player: number) => `魔方：玩家 ${player}`,
    battleCurrentRound: (round: number) => `第 ${round} 轮`,
    battleInviteCopied: '已复制房间码',
    battleIdentity: '身份',
    battleHistory: '历史与统计',
    battleJoinRoom: '加入房间',
    battleKick: '移出',
    battleKickConfirm: (name: string) => `确定将 ${name} 移出房间吗？`,
    battleLeaveRoom: '离开房间',
    battleLiveRound: '进行中',
    battleLoadingRoom: '正在加载房间…',
    battleLocalTitle: '本地对战',
    battleKeyBindings: '玩家按键',
    battleKeyName: (key: string) => key === ' ' ? '空格' : key,
    battleName: '昵称',
    battleNamePlaceholder: '魔友',
    battleNextRound: '下一轮',
    battleNoScramble: '正在准备打乱…',
    battleNoHistory: '完成一轮对战后，记录会显示在这里。',
    battleNoOtherPlayers: '房间里暂无其他玩家。',
    battleOnlineTitle: '联机对战',
    battleOnlineUnavailable: '当前 App 宿主暂不支持联机对战。',
    battlePhase: (phase: string) => ({
      idle: '等待', ready: '已准备', inspecting: '观察中', solving: '计时中', done: '已完成',
    } as Record<string, string>)[phase] ?? phase,
    battlePlayer: (player: number) => `玩家 ${player}`,
    battlePressKey: '请按键…',
    battleReady: '准备',
    battleRoomCode: '房间码',
    battleRoomCodePlaceholder: '4 位数字',
    battleRoundLabel: (round: number) => `第 ${round} 轮`,
    battleScore: (score: number) => `${score} 胜`,
    battleSearchIdentity: '昵称、WCA 姓名或 WCA ID',
    battleScanToJoin: '扫码加入',
    battleSearchingIdentity: '正在搜索 WCA 选手…',
    battleSkipWaiting: '不等了，直接开下一轮',
    battleShowQr: '邀请二维码',
    battleSharedCubeDetail: '多人轮流使用同一颗已连接的智能魔方，每位玩家完成后自动交给下一位。',
    battleSmartCube: '共享智能魔方',
    battleSmartCubeOnly333: '共享智能魔方自动计时仅支持三阶。',
    battleStartTogether: '同时开始',
    battleSyncStart: '同时起表',
    battleTransferAdmin: '设为房主',
    battleTransferAdminConfirm: (name: string) => `确定将房主转让给 ${name} 吗？`,
    battleWaitingPlayers: '等待其他玩家',
    battleWinner: '胜者',
    battleWins: (count: number) => `${count} 胜`,
    battleYou: '我',
    checking: '检查中',
    clearCompetition: '清除比赛',
    clearFilters: '清空筛选',
    clearSearch: '清空搜索',
    clear: '清除',
    close: '关闭',
    competition: '比赛',
    competitionListFailed: '无法加载比赛列表。',
    competitionListLoading: '正在加载比赛…',
    competitionScramblesFailed: '无法加载该比赛的轮次与组别。',
    competitionScramblesLoading: '正在加载轮次与组别…',
    count: '总数',
    current: '当前',
    colorModeCn: '六色',
    colorModeDual: '双色',
    colorModeQuad: '四色',
    colorModeSingle: '单色',
    colorSubset: '底色子集',
    connect: '连接',
    connectingBluetooth: '正在连接…',
    copied: '已复制',
    copiedScramble: '已复制打乱',
    connectBluetooth: '连接蓝牙设备',
    comment: '备注',
    chooseSession: '选择分组…',
    corruptDetail: 'CubeRoot 不会覆盖无效数据。请导入有效备份进行恢复。',
    corruptTitle: '本地数据需要处理',
    cubeState: '这条打乱后的魔方状态',
    data: '数据',
    dataCount: '条记录保存在本机',
    date: '日期',
    dateFrom: '开始日期',
    dateRange: '日期范围',
    dateTo: '结束日期',
    clearDateRange: '清除日期范围',
    calendarClearDate: '清除日期',
    calendarChooseDate: '选择日期',
    calendarPreviousMonth: '上个月',
    calendarNextMonth: '下个月',
    calendarYear: '年份',
    calendarMonth: '月份',
    calendarMonthOption: (month: number) => `${month}月`,
    calendarWeekdays: ['一', '二', '三', '四', '五', '六', '日'] as const,
    calendarToday: '今天',
    calendarDate: (year: number, month: number, day: number) => `${year}年${month}月${day}日`,
    delete: '删除',
    deleteAccount: '注销账号',
    deleteConfirm: '确定删除这条记录吗？',
    deletedSolve: '已删除成绩',
    deletedLastSolve: '已删除最后一次成绩',
    difficulty: '难度',
    difficultyFilter: '难度过滤',
    disconnectBluetooth: '断开智能魔方',
    dnf: 'DNF',
    emptyHistory: '停表后，记录会显示在这里。',
    filters: '筛选',
    tags: '标签',
    exportData: '导出备份',
    exportSuccess: '备份已准备好。',
    fullSite: '完整网站',
    fullSiteDetail: '需要 App 尚未内置的工具时，再打开完整 CubeRoot 网站。',
    finishAttemptFirst: '请先结束或取消当前计时，再更改计时选项。',
    generatingScramble: '正在生成打乱…',
    group: '组别',
    groupOption: (group: string) => `${group} 组`,
    history: '记录',
    historyMatches: (count: number) => `${count} 条匹配`,
    hideExtras: '收起',
    holdTime: '启动按住时间',
    holdToArm: '按住开始',
    importData: '导入备份',
    importConfirm: (incoming: number, current: number) => `将导入 ${incoming} 条记录并替换当前 ${current} 条记录。可在设置中撤销一次，确定继续吗？`,
    importSuccess: '备份已导入。',
    importTooLarge: '备份超过 10 MB，未打开。',
    inspection: '观察时间',
    keepHolding: '继续按住',
    language: '语言',
    light: '浅色',
    loadingReal: '正在加载比赛真题…',
    localDataNotSynced: '计时记录仍安全保存在本机；云同步尚未开放。',
    manageAccount: '管理账号',
    merge: '合并',
    mergeAriaLabel: '合并 3×3 全族真题',
    mergeHelp: '开启后，从整个 3×3 族的真题中按难度取题；关闭后只取当前项目。',
    method: '方法',
    maxSeconds: '最长 (秒)',
    mean: '平均',
    minSeconds: '最短 (秒)',
    manual: '手动',
    manualOption: '手动输入',
    manualPasteHint: '在上方「打乱来源」粘贴打乱,每行一条',
    manualScrambles: '手动输入打乱',
    localRandom: '本地随机打乱',
    my: '我的',
    more: '更多',
    moreActions: '更多操作',
    moveToSession: '移到分组',
    newScramble: '换一个打乱',
    noEventScrambles: '该比赛没有当前项目的打乱。',
    noMatchingCompetitions: '没有匹配的比赛。',
    noInspection: '关闭',
    noHistoryMatches: '没有匹配的成绩。',
    offline: '离线',
    online: '在线',
    onePlayer: '1人',
    optimalScramble: '最优打乱',
    ollCase: 'OLL 公式',
    previousScramble: '上一个打乱',
    players: (count: number) => `${count}人`,
    pllCase: 'PLL 公式',
    openTimes: '打开成绩与统计',
    openFullSite: '打开 cuberoot.me',
    openFullTimer: '打开完整网页版计时器',
    privacy: '隐私政策',
    puzzle: '项目',
    penalty: '罚时',
    releaseToStart: '松开开始',
    retry: '重试',
    real: '真题',
    realOption: 'WCA 真题',
    realScrambleEmpty: '当前来源没有匹配的 WCA 真题。',
    realScrambleFailed: '无法加载比赛真题，请重试。',
    realScrambleRange: '真题范围',
    round: '轮次',
    random: '随机',
    randomOption: '随机状态',
    replace: '替换',
    nextScramble: '下一个打乱',
    save: '保存',
    searchCompetition: '搜索比赛',
    searchHistory: '搜索注释或打乱',
    showAllStats: '显示全部统计',
    single: '单次',
    seconds15: '15 秒',
    settings: '设置',
    signIn: '登录',
    signedInAs: '当前账号',
    signingIn: '正在打开登录…',
    signOut: '退出此 App',
    scrambleSource: '打乱来源',
    scrambleLengthRange: '打乱长度范围',
    scrambleCorrection: '拧回原打乱',
    scrambleCorrectionCopied: '已复制原打乱',
    scrambleCorrectionTitle: '拧歪了。这些步骤会从魔方当前状态回到同一个打乱状态；成绩仍记录原打乱。',
    scrambleMismatch: '与打乱不符',
    scrambleReady: '打乱已就绪',
    scrambleUnsupported: '此项目已与网站使用同一清单，但共享打乱提供器尚未迁移完成。',
    solved: '成功',
    statsChangeColumn: (current: string) => `更改统计列，当前 ${current}`,
    statsCustomPlaceholder: '自定义 ao',
    statsCustomSize: '自定义 ao 大小',
    support: '联系支持',
    subX: '阈值占比',
    tools: '工具',
    solves: '次数',
    system: '跟随系统',
    smartCubeConnected: (name: string) => `${name} 已连接。`,
    smartCubeDisconnected: '智能魔方已断开。',
    smartCubeError: '无法连接智能魔方。请唤醒魔方、保持靠近后重试。',
    smartCubeOnly333: '智能魔方自动计时只支持已适配的三阶类项目。',
    stage: '阶段',
    stepRange: '步数范围',
    tapToStop: '轻触停止',
    theme: '主题',
    threeByThree: '三阶魔方',
    timer: '计时',
    timerTitle: '计时器',
    timerHint: '触摸并按住，松开开始。连接键盘时可用空格键。',
    times: '成绩',
    title: 'CubeRoot',
    undoImport: '撤销上次导入',
    undo: '撤销',
    undoImportConfirm: '恢复到上次导入前的数据吗？',
    undoImportSuccess: '已恢复导入前的数据。',
    unindexedCompetition: '该比赛的阶段难度库尚未更新；整体与打乱长度仍可使用。',
    version: '版本',
    worst: '最差',
    dark: '深色',
  },
} as const;

export function dateRangeInputLabels(language: SupportedLanguage): DateRangeInputLabels {
  const copy = COPY[language];
  return {
    dateInput: {
      clearDate: copy.calendarClearDate,
      chooseDate: copy.calendarChooseDate,
      previousMonth: copy.calendarPreviousMonth,
      nextMonth: copy.calendarNextMonth,
      year: copy.calendarYear,
      month: copy.calendarMonth,
      monthOption: copy.calendarMonthOption,
      weekdays: copy.calendarWeekdays,
      today: copy.calendarToday,
      calendarDate: copy.calendarDate,
    },
    dateRange: copy.dateRange,
    startDate: copy.dateFrom,
    endDate: copy.dateTo,
    clearDateRange: copy.clearDateRange,
  };
}

export function preferredLanguage(): SupportedLanguage {
  return navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en';
}
