import { createHash } from 'node:crypto';

interface GetuiConfig { appId: string; appKey: string; masterSecret: string }
export function getuiConfig(appId: string): GetuiConfig | null {
  const prefix = appId === 'me.cuberoot.app' ? 'GETUI_' : appId === 'me.cuberoot.app.debug' ? 'GETUI_DEBUG_' : null;
  if (!prefix || process.env.RECORD_PUSH_ENABLED !== '1') return null;
  const values = ['APP_ID', 'APP_KEY', 'MASTER_SECRET'].map(key => process.env[prefix + key]?.trim());
  return values.every(Boolean) ? { appId: values[0]!, appKey: values[1]!, masterSecret: values[2]! } : null;
}

interface Reply { code: number; data?: Record<string, unknown> }
const tokens = new Map<string, { token: string; expires: number }>();
async function request(config: GetuiConfig, path: string, body: unknown, token?: string): Promise<Reply> {
  const response = await fetch(`https://restapi.getui.com/v2/${encodeURIComponent(config.appId)}${path}`, {
    method: 'POST', headers: { 'Content-Type': 'application/json', ...(token ? { token } : {}) },
    body: JSON.stringify(body), signal: AbortSignal.timeout(12_000),
  });
  if (!response.ok) throw new Error(`getui HTTP ${response.status}`);
  const reply = await response.json() as Reply;
  if (typeof reply.code !== 'number') throw new Error('getui invalid response');
  return reply;
}

async function tokenFor(config: GetuiConfig): Promise<string> {
  const cached = tokens.get(config.appId);
  if (cached && cached.expires > Date.now() + 60_000) return cached.token;
  const timestamp = String(Date.now());
  const sign = createHash('sha256').update(config.appKey + timestamp + config.masterSecret).digest('hex');
  const reply = await request(config, '/auth', { appkey: config.appKey, timestamp, sign });
  if (reply.code !== 0 || typeof reply.data?.token !== 'string' || !Number.isFinite(Number(reply.data.expire_time))) {
    throw new Error(`getui auth ${reply.code}`);
  }
  tokens.set(config.appId, { token: reply.data.token, expires: Number(reply.data.expire_time) });
  return reply.data.token;
}

export function recordPushPayload(input: { clientId: string; requestId: string; title: string; excerpt: string; link: string; notificationId: number }) {
  // Only public competition URLs generated by our record service may leave the API.
  if (!/^\/(?:zh\/)?wca\/comp\/[A-Za-z0-9]+(?:\?[^#\s]*)?$/.test(input.link)) throw new Error('Invalid record push link');
  const notification = {
    title: Array.from(input.title).slice(0, 32).join(''),
    body: Array.from(input.excerpt || input.title).slice(0, 100).join(''),
    click_type: 'url', url: `https://cuberoot.me${input.link}`,
    notify_id: (input.notificationId % 2_147_483_646) + 1,
  };
  return { request_id: input.requestId, audience: { cid: [input.clientId] },
    settings: { ttl: 3_600_000 }, push_message: { notification },
    push_channel: { android: { ups: { notification } } } };
}

export async function sendRecordPush(appId: string, input: Parameters<typeof recordPushPayload>[0]): Promise<void> {
  const config = getuiConfig(appId);
  if (!config) throw new Error('getui not configured');
  const payload = recordPushPayload(input);
  let reply = await request(config, '/push/single/cid', payload, await tokenFor(config));
  if (reply.code === 10001) {
    tokens.delete(config.appId);
    reply = await request(config, '/push/single/cid', payload, await tokenFor(config));
  }
  if (reply.code !== 0) throw new Error(`getui push ${reply.code}`);
  const statuses = Object.values(reply.data ?? {}).flatMap(task =>
    task && typeof task === 'object' ? Object.values(task) : []);
  if (!statuses.some(status => status === 'successed_online' || status === 'successed_offline')) {
    throw new Error('getui did not accept recipient');
  }
}
