/** Only public competition links generated by the record service may be pushed. */
export function recordPushUrl(link: string): string {
  if (!/^\/(?:zh\/)?wca\/comp\/[A-Za-z0-9]+(?:\?[^#\s]*)?$/.test(link)) throw new Error('Invalid record push link');
  return `https://cuberoot.me${link}`;
}
