import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import LangToggle from '../../components/LangToggle';
import { LangCtx, L, type Lang } from './_intro/Lang';
import { useDocumentTitle } from '../../utils/useDocumentTitle';
import './algorithm_intro.css';

const ACCENT = '#F0A04B';

export default function Min2PhasePage() {
  const { i18n } = useTranslation();
  const lang: Lang = i18n.language.startsWith('zh') ? 'zh' : 'en';

  useDocumentTitle('min2phase', 'min2phase');

  return (
    <LangCtx.Provider value={lang}>
      <div className="algo-page" style={{ ['--accent' as string]: ACCENT }}>
        <div className="algo-page-bg" />
        <div className="algo-page-inner">
          <div className="algo-page-topbar">
            <Link to="/code/algorithms" className="algo-page-back">← /code/algorithms</Link>
            <LangToggle variant="inline" />
          </div>

          <header className="algo-page-head">
            <div className="algo-page-tag">
              <L zh="实用化改进" en="Practical refinement" />
            </div>
            <h1 className="algo-page-title">min2phase</h1>
            <p className="algo-page-sub">
              <L
                zh="Shuang Chen (cs0x7f) 的 Java 实现,把 Kociemba 二阶段往实用方向推到极致:对称压缩让剪枝表小一个数量级,Huge 剪枝表给 phase1 更准的下界,phase1 解里提前找最短 phase2 总解。csTimer / TNoodle 用的就是它。"
                en="Shuang Chen (cs0x7f)'s Java implementation pushes Kociemba two-phase to its practical limit. Symmetry compression shrinks tables by an order of magnitude, huge prune tables tighten phase-1 lower bounds, and the search interleaves phase-1 candidates with phase-2 to minimise total length. It's what csTimer and TNoodle ship."
              />
            </p>
          </header>

          {/* ─────────────── 1. 项目身份 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">01</span>
              <h2 className="algo-section-title"><L zh="项目身份" en="Project identity" /></h2>
            </div>
            <p>
              <L
                zh={<><strong>min2phase</strong> 由中国魔方选手 <strong>陈霜 (Shuang Chen, GitHub: cs0x7f)</strong> 编写,GPLv3 + MIT 双授权。仓库名 <code>cs.min2phase</code>,包路径直接刻在源码 package 里。最早的公开记录可追溯到 2010 年代初的中文魔方论坛,长期作为 csTimer / TNoodle 等社区工具的内置求解器存在,2023 年依旧由作者更新维护。</>}
                en={<><strong>min2phase</strong> is written by Chinese speedcuber <strong>Shuang Chen (Chen Shuang, GitHub: cs0x7f)</strong> and released under dual GPLv3 + MIT. The Java package is literally <code>cs.min2phase</code>. The earliest public traces go back to Chinese cubing forums in the early 2010s; it has long been the bundled solver behind csTimer and TNoodle, and the upstream is still actively maintained by the author as of 2023.</>}
              />
            </p>
            <p>
              <L
                zh="同样是 Kociemba 二阶段,min2phase 跟原版相比的优势不是算法骨架变了,而是工程把每一处都拧到了极限:剪枝表用对称类压缩到几百 KB,启动时间一两百毫秒,平均出解 0.8 ms,平均步数 19~20.6 (取决于探测次数)。csTimer 把它编进浏览器后,WCA 选手每个本地计时器跑出来的打乱基本都是它给的。"
                en="The algorithmic skeleton is still Kociemba's two-phase. What sets min2phase apart is that every engineering knob has been turned to its limit: prune tables compressed by symmetry classes into a few hundred KB, ~200 ms startup, ~0.8 ms average solve, average length 19–20.6 moves depending on probe budget. After csTimer compiles it to JS in the browser, virtually every scramble a WCA-aware local timer hands you was generated by this solver."
              />
            </p>
            <div className="algo-callout">
              <div className="algo-callout-tag"><L zh="范围" en="Scope" /></div>
              <p>
                <L
                  zh="本页讲的是 3x3 的二阶段求解器。min2phase 在 csTimer 内还衍生出 222/4x4/5x5/sq1/skewb 等独立 solver(全部 cs0x7f 出品),底层思路相似但参数表完全独立,本页不展开。"
                  en="This page is about the 3x3 two-phase solver. Inside csTimer, cs0x7f also wrote standalone solvers for 2x2 / 4x4 / 5x5 / Square-1 / Skewb with the same family of tricks; their tables are different and out of scope here."
                />
              </p>
            </div>
          </section>

          {/* ─────────────── 2. 跟原版 Kociemba 的差异 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">02</span>
              <h2 className="algo-section-title"><L zh="跟原版 Kociemba 的 5 个核心差异" en="Five core differences vs vanilla Kociemba" /></h2>
            </div>
            <p>
              <L
                zh="Herbert Kociemba 1992 年的二阶段算法把 3x3 求解分成 G0→G1→solved 两步:phase1 把魔方拉进子群 ⟨U,R²,F²,D,L²,B²⟩ (棱方向归零、角方向归零、UD 中层 4 棱归位),phase2 在子群内部把剩下的置换排好。原始实现的剪枝表是稠密表,需要几十 MB 内存;搜索找到第一个 phase1 解就直接接 phase2,得到的总长度并不一定最短。min2phase 在保留同样阶段划分的前提下做了五点改造。"
                en="Herbert Kociemba's 1992 algorithm splits the 3x3 solve into G0→G1→solved. Phase 1 forces the cube into the subgroup ⟨U,R²,F²,D,L²,B²⟩ (zero edge orientation, zero corner orientation, four UD-slice edges in their layer). Phase 2 finishes the permutation inside that subgroup. The original implementation uses dense prune tables of tens of MB, and feeds the first phase-1 solution straight into phase-2, which is not necessarily globally shortest. min2phase keeps the same split but rebuilds five things."
              />
            </p>
            <table className="algo-table">
              <thead>
                <tr>
                  <th><L zh="维度" en="Aspect" /></th>
                  <th><L zh="原版 Kociemba" en="Vanilla Kociemba" /></th>
                  <th><L zh="min2phase" en="min2phase" /></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><L zh="剪枝表存储" en="Prune-table storage" /></td>
                  <td><L zh="稠密二维 raw 坐标表,数十 MB" en="Dense raw-coord arrays, tens of MB" /></td>
                  <td><L zh="对称类压缩 + 4 比特紧凑存储,合计约 1 MB" en="Sym-class compressed, 4-bit packed, ~1 MB total" /></td>
                </tr>
                <tr>
                  <td><L zh="启发式下界" en="Heuristic lower bound" /></td>
                  <td><L zh="UDSliceTwist / UDSliceFlip 二选一" en="UDSliceTwist or UDSliceFlip alone" /></td>
                  <td><L zh="三表 max:UDSliceTwist + UDSliceFlip + TwistFlip" en="Max of three: UDSliceTwist + UDSliceFlip + TwistFlip" /></td>
                </tr>
                <tr>
                  <td><L zh="多轴 + 反向" en="Multi-axis + inverse" /></td>
                  <td><L zh="单轴,正向" en="Single axis, forward only" /></td>
                  <td><L zh="3 个 G1 轴 × 正/反向 = 6 个朝向并行" en="3 G1 axes × forward / inverse = 6 orientations in parallel" /></td>
                </tr>
                <tr>
                  <td><L zh="phase1↔phase2 交错" en="Phase 1 ↔ Phase 2 interleaving" /></td>
                  <td><L zh="第一个 phase1 解就接 phase2" en="Commits to first phase-1 solution" /></td>
                  <td><L zh="按总长度迭代,allowShorter + pre-move 不断回探" en="Iterates on total length with allowShorter + pre-moves" /></td>
                </tr>
                <tr>
                  <td><L zh="预制移 (pre-scramble)" en="Pre-scramble" /></td>
                  <td><L zh="无" en="None" /></td>
                  <td><L zh="MAX_PRE_MOVES=20,共轭等价绕开盲点" en="MAX_PRE_MOVES=20, conjugate-equivalent re-roots" /></td>
                </tr>
              </tbody>
            </table>
            <p>
              <L
                zh={<>这 5 项叠加的结果:在同样的 maxDepth=21 约束下,平均出解时间 <strong>0.8 ms</strong> (full-init),平均步数 <strong>20.6</strong>;放开 probeMin=10000 后平均步数 <strong>18.63</strong>,直逼最优解 (实测 god's number = 20)。</>}
                en={<>Stacked together: at maxDepth=21 the full-init average is <strong>0.8 ms</strong> per solve at average length <strong>20.6</strong>; raising probeMin to 10000 brings the average down to <strong>18.63</strong> moves, within striking distance of the proven 20-move God's number.</>}
              />
            </p>
          </section>

          {/* ─────────────── 3. CubieCube vs CoordCube ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">03</span>
              <h2 className="algo-section-title"><L zh="两层数据结构:CubieCube vs CoordCube" en="Two layers: CubieCube vs CoordCube" /></h2>
            </div>
            <p>
              <L
                zh={<><strong>CubieCube</strong> 是块级表示:8 个角块 + 12 个棱块,每个块有 (位置, 朝向)。代码里就是两个数组:</>}
                en={<><strong>CubieCube</strong> is the cubie-level representation: 8 corners + 12 edges, each carrying (position, orientation). In code it is literally two arrays:</>}
              />
            </p>
            <pre className="algo-code">{`// CubieCube.java
byte[] ca = {0, 1, 2, 3, 4, 5, 6, 7};               // 8 corners
byte[] ea = {0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22}; // 12 edges

// ca[i] = orientation << 3 | position
// ea[i] = position << 1 | orientation`}</pre>
            <p>
              <L
                zh={<>每个 byte 把位置和朝向打包进同一个字节:角块朝向 0~2 占 2 位,位置 0~7 占 3 位;棱块朝向 0~1 占 1 位,位置 0~11 占 4 位。块乘法 (一个魔方状态作用在另一个上) 完全是组合数学:</>}
                en={<>Each byte packs both fields: corners have 2 bits of twist (0–2) and 3 bits of slot (0–7); edges have 1 bit of flip and 4 bits of slot. Composing two CubieCubes (acting one cube state on another) is just permutation algebra:</>}
              />
            </p>
            <pre className="algo-code">{`// Corner multiplication: prod = a * b
static void CornMult(CubieCube a, CubieCube b, CubieCube prod) {
    for (int corn = 0; corn < 8; corn++) {
        int oriA = a.ca[b.ca[corn] & 7] >> 3;
        int oriB = b.ca[corn] >> 3;
        prod.ca[corn] = (byte) (a.ca[b.ca[corn] & 7] & 7
                              | (oriA + oriB) % 3 << 3);
    }
}`}</pre>
            <p>
              <L
                zh={<>CubieCube 表达力完整但每一步搜索都做 8+12 次乘法太慢。<strong>CoordCube</strong> 是它的"坐标化"投影:把一个魔方状态压成几个整数 (twist / flip / slice 等),每个坐标都有一张预算好的 "move table" (这个坐标在 18 个动作下会跳到哪)。搜索时不再算 byte 数组,直接查表:</>}
                en={<>CubieCube is complete but doing 8+12 byte-array multiplications per node is too slow. <strong>CoordCube</strong> is its coordinate projection: collapse a cube state into a handful of integers (twist / flip / slice / …), and precompute, for each coordinate, where every one of the 18 moves takes it. Search then becomes table lookups instead of array ops:</>}
              />
            </p>
            <pre className="algo-code">{`// CoordCube.java — every coordinate gets a move table
static char[][] UDSliceMove = new char[N_SLICE][N_MOVES];   // 495  × 18
static char[][] TwistMove   = new char[N_TWIST_SYM][N_MOVES]; // 324  × 18 (sym-compressed)
static char[][] FlipMove    = new char[N_FLIP_SYM][N_MOVES];  // 336  × 18
static char[][] CPermMove   = new char[N_PERM_SYM][N_MOVES2]; // 2768 × 10
static char[][] EPermMove   = new char[N_PERM_SYM][N_MOVES2]; // 2768 × 10
static char[][] MPermMove   = new char[N_MPERM][N_MOVES2];    // 24   × 10`}</pre>
            <p>
              <L
                zh="表名 SYM 后缀的是对称类压缩版,raw 表的 char 数组下标是原始坐标值。整张表的 cell 值都是 char (16 bit),足够装下 sym-coord 的 (class<<3 | sym) 编码。"
                en="Names ending in SYM are symmetry-compressed versions; raw tables are indexed by the raw coordinate value. Each cell stores a char (16 bits) — wide enough for the (class<<3 | sym) packing used by sym-coords."
              />
            </p>
          </section>

          {/* ─────────────── 4. 六个核心坐标 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">04</span>
              <h2 className="algo-section-title"><L zh="6 个核心坐标" en="The six core coordinates" /></h2>
            </div>
            <p>
              <L
                zh={<>坐标的核心思想:把完整 3x3 状态空间 4.3×10¹⁹ 按某种等价关系切片,每一片用一个 int 编号,且这个编号在 18 个动作下的转移可以预算好。min2phase 用 6 个:</>}
                en={<>The point of coordinates: slice the full 4.3×10¹⁹-state space along some equivalence and label each slice with one integer, such that the 18 moves' action on the label is precomputable. min2phase uses six of them:</>}
              />
            </p>
            <table className="algo-table">
              <thead>
                <tr>
                  <th><L zh="坐标" en="Coord" /></th>
                  <th className="num"><L zh="基数" en="Size" /></th>
                  <th><L zh="含义" en="Meaning" /></th>
                  <th><L zh="阶段" en="Phase" /></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><code>Twist</code></td>
                  <td className="num">2187 = 3<sup>7</sup></td>
                  <td><L zh="8 个角块的朝向 (7 个独立)" en="Orientation of 8 corners (7 independent)" /></td>
                  <td>P1</td>
                </tr>
                <tr>
                  <td><code>Flip</code></td>
                  <td className="num">2048 = 2<sup>11</sup></td>
                  <td><L zh="12 个棱块的朝向 (11 个独立)" en="Orientation of 12 edges (11 independent)" /></td>
                  <td>P1</td>
                </tr>
                <tr>
                  <td><code>UDSlice</code></td>
                  <td className="num">495 = C(12,4)</td>
                  <td><L zh="FL/FR/BL/BR 4 棱在 E 层的位置,不管它们之间排列" en="Position of FL/FR/BL/BR among 12 edges, ignoring permutation among themselves" /></td>
                  <td>P1</td>
                </tr>
                <tr>
                  <td><code>CPerm</code> / <code>EPerm</code></td>
                  <td className="num">40320 = 8!</td>
                  <td><L zh="UD 层 8 角 / 8 棱的置换" en="Permutation of 8 corners / 8 UD-layer edges" /></td>
                  <td>P2</td>
                </tr>
                <tr>
                  <td><code>MPerm</code></td>
                  <td className="num">24 = 4!</td>
                  <td><L zh="E 层 4 棱在自己层内的置换" en="Permutation of the 4 E-slice edges within E layer" /></td>
                  <td>P2</td>
                </tr>
                <tr>
                  <td><code>CComb</code> (Parity+Pos)</td>
                  <td className="num">140 = 70 × 2</td>
                  <td><L zh="URF/UFL/ULB/UBR 4 角块的位置 (70) 加棱奇偶 (×2)" en="Position of 4 U-layer corners (70) × edge parity (×2)" /></td>
                  <td>P2</td>
                </tr>
              </tbody>
            </table>
            <p>
              <L
                zh={<>Phase 1 的目标:让 Twist、Flip、UDSlice 三个坐标同时归 0。这等价于"角朝向归零 + 棱朝向归零 + 4 个 E 棱位于 E 层"——刚好就是 G1 子群定义。Phase 2 在 G1 内继续把 CPerm/EPerm/MPerm 归 0。</>}
                en={<>Phase 1 wants Twist, Flip and UDSlice all simultaneously zero — equivalently, zero corner-orientation, zero edge-orientation, and four E-slice edges back in the E layer. That is exactly the G1 subgroup definition. Phase 2 then drives CPerm/EPerm/MPerm to zero inside G1.</>}
              />
            </p>
            <p>
              <L
                zh={<><code>Parity</code> 不是独立坐标,是判奇偶用的辅助位;cs0x7f 把它编进了 <code>CComb</code> 的高位 (70 个位置 × 2 个奇偶 = 140),省一张表。</>}
                en={<><code>Parity</code> is not a free coordinate; cs0x7f folds it into the high bit of <code>CComb</code> (70 corner positions × 2 parity bits = 140), saving one table.</>}
              />
            </p>
          </section>

          {/* ─────────────── 5. 对称类 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">05</span>
              <h2 className="algo-section-title"><L zh="对称类:把 16 个等价状态合成一格" en="Symmetry classes: collapsing 16 equivalent states into one" /></h2>
            </div>
            <p>
              <L
                zh={<>3x3 魔方有 48 个空间对称,其中保 UD 轴的子群有 <strong>16 个</strong> (旋转 S_U4 + 反射 S_LR2 + 180° 翻 S_F2 生成)。如果两个魔方状态 a、b 满足 b = S⁻¹ a S (S 是 16 个对称之一),那它们的求解长度完全相同——只是看的视角不同。这就允许把 16 个等价状态合成一个"对称类" (sym class),只存代表元和到代表元的对称索引。</>}
                en={<>The cube has 48 spatial symmetries; the UD-axis-preserving subgroup has <strong>16</strong> elements (generated by S_U4 quarter-turns, the LR mirror S_LR2 and the F-axis 180° S_F2). If b = S⁻¹ a S for some such S, then a and b have the exact same optimal solution length — they are the same state viewed from a different orientation. So we can collapse each 16-orbit into one <em>symmetry class</em>, storing only the representative + a small sym index back.</>}
              />
            </p>
            <table className="algo-table">
              <thead>
                <tr>
                  <th><L zh="坐标" en="Coord" /></th>
                  <th className="num"><L zh="raw" en="raw" /></th>
                  <th className="num"><L zh="sym class" en="sym class" /></th>
                  <th className="num"><L zh="压缩比" en="ratio" /></th>
                </tr>
              </thead>
              <tbody>
                <tr><td>Twist</td><td className="num">2187</td><td className="num">324</td><td className="num">6.75×</td></tr>
                <tr><td>Flip</td><td className="num">2048</td><td className="num">336</td><td className="num">6.10×</td></tr>
                <tr><td>EPerm / CPerm</td><td className="num">40320</td><td className="num">2768</td><td className="num">14.57×</td></tr>
              </tbody>
            </table>
            <p>
              <L
                zh={<>压缩比远没到 1/16,因为有自对称的状态 (selfSym) 会占多个"格子"。代码里实际存储的是 <code>{'(class<<3 | sym)'}</code> 这种打包格式,16 bit 的 char 类型一格就装下,在做动作转移时通过 <code>SymMult / SymMove / Sym8Move</code> 这些预算的查找表把"动作 m 在 sym 坐标系下的等价动作"算出来:</>}
                en={<>The ratio falls short of 16× because some states are self-symmetric and need extra entries (selfSym). The packed format is <code>{'(class<<3 | sym)'}</code>, fitting in a 16-bit char. Move transitions on a sym-coord use precomputed <code>SymMult / SymMove / Sym8Move</code> tables to translate move m into its equivalent in the representative's frame:</>}
              />
            </p>
            <pre className="algo-code">{`// CoordCube.doMovePrun — phase 1 transition on a sym-coord
twist = TwistMove[cc.twist][CubieCube.Sym8Move[m << 3 | cc.tsym]];
tsym  = (twist & 7) ^ cc.tsym;
twist >>= 3;`}</pre>
            <p>
              <L
                zh={<>这套机制完整在 <code>CubieCube.initFlipSym2Raw</code> / <code>initTwistSym2Raw</code> / <code>initPermSym2Raw</code> 三个函数里初始化,生成 <code>FlipS2R / TwistS2R / EPermS2R</code> 等正反映射表。</>}
                en={<>It is set up inside <code>CubieCube.initFlipSym2Raw</code> / <code>initTwistSym2Raw</code> / <code>initPermSym2Raw</code>, producing the bidirectional maps <code>FlipS2R / TwistS2R / EPermS2R</code>.</>}
              />
            </p>
            <div className="algo-callout">
              <div className="algo-callout-tag"><L zh="为什么 UDSlice 不压缩?" en="Why isn't UDSlice compressed?" /></div>
              <p>
                <L
                  zh={<>UDSlice 只有 495,本身就小,而且它跟 UD 轴对齐——对称组里多数操作不能保它"4 个棱在 E 层"这个性质,压缩反而麻烦。所以它就是 raw 坐标,只对 <strong>另外一边</strong> 的坐标做 sym 压缩,形成 <code>UDSliceTwistPrun[495 × 324]</code> 这种 raw×sym 表。</>}
                  en={<>UDSlice has only 495 values to begin with, and it is aligned with the UD axis — most symmetries in the group don't preserve "those four edges are in E", so compressing it is more trouble than it's worth. It stays a raw coordinate; the symmetry compression only applies to the <strong>other</strong> coordinate, giving raw×sym tables like <code>UDSliceTwistPrun[495 × 324]</code>.</>}
                />
              </p>
            </div>
          </section>

          {/* ─────────────── 6. Huge 剪枝表 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">06</span>
              <h2 className="algo-section-title"><L zh="Huge 剪枝表 + 4 比特紧凑存储" en="Huge prune tables + 4-bit packing" /></h2>
            </div>
            <p>
              <L
                zh={<>min2phase 的 phase1 启发式是 <strong>三表取 max</strong>:</>}
                en={<>The phase-1 heuristic is the <strong>max of three tables</strong>:</>}
              />
            </p>
            <pre className="algo-code">{`// CoordCube.setWithPrun  (phase 1 lower-bound)
prun = max(
    getPruning(TwistFlipPrun,    twist<<11 | flipIdx),     // 2187 × 2048 → "huge"
    getPruning(UDSliceTwistPrun, twist*N_SLICE + sliceX),  // 324  × 495
    getPruning(UDSliceFlipPrun,  flip *N_SLICE + sliceX)); // 336  × 495`}</pre>
            <p>
              <L
                zh={<>第一张 <strong>TwistFlipPrun</strong> 是 cs0x7f 的关键增量,叫 "Huge prune table":N_TWIST_SYM × N_FLIP = 324 × 2048 = 663552 个 cell,每 cell 4 bit,共 332 KB。它给出"角朝向 + 棱朝向"联合下界,把 UDSlice 完全抽掉。这一表的剪枝精度从 <code>pruningValue.txt</code> 看得到——深度 9 时已覆盖 99.97% 的状态:</>}
                en={<>The first one — <strong>TwistFlipPrun</strong> — is cs0x7f's key addition, the "Huge prune table". It has N_TWIST_SYM × N_FLIP = 324 × 2048 = 663,552 cells, 4 bits each, totalling 332 KB. It supplies a joint lower bound on corner+edge orientation alone, abstracting UDSlice away entirely. The accuracy is visible in <code>pruningValue.txt</code> — by depth 9 it already covers 99.97% of states:</>}
              />
            </p>
            <pre className="algo-code">{`// pruningValue.txt — TwistFlipPrun depth distribution
 1         3
 2        15
 3       106
 4       951
 5      9826
 6     89711
 7    447496
 8    662070
 9    663552   ← full coverage at depth 9, total 663,552 cells`}</pre>
            <p>
              <L
                zh="对比另两张 (UDSliceTwistPrun / UDSliceFlipPrun) 在深度 14 才接近覆盖,Huge 表的下界平均高出 1~2 步,直接转化为 phase1 搜索树的指数级剪枝。Algorithm.md 给出三表各自的平均下界:UDSliceTwist 6.76、UDSliceFlip 6.85、TwistFlip 7.18——TwistFlip 最紧,但只有当三表一起 max 才在每个节点都拿到最强下界。"
                en="The other two saturate only around depth 14; the huge table gives a bound that is on average 1–2 moves tighter, which cascades into exponential pruning of the phase-1 tree. Algorithm.md gives the per-table averages: UDSliceTwist 6.76, UDSliceFlip 6.85, TwistFlip 7.18 — the huge table is tightest but the real win is taking max over all three at every node."
              />
            </p>
            <p>
              <L
                zh={<>所有剪枝表都用 <strong>4 比特紧凑存储</strong>:一个 32 位 int 装 8 个 nibble,每 nibble 是该 cell 的"距 solved 的距离 mod 16"。读写两个一行的宏:</>}
                en={<>All prune tables are <strong>4-bit packed</strong>: one int holds 8 nibbles, each nibble being that cell's distance to solved mod 16. Read/write are one-liners:</>}
              />
            </p>
            <pre className="algo-code">{`static int  getPruning(int[] t, int i) { return  t[i >> 3] >> (i << 2) & 0xf; }
static void setPruning(int[] t, int i, int v) { t[i >> 3] ^= v << (i << 2); }`}</pre>
            <p>
              <L
                zh={<><code>{'(i << 2)'}</code> 在 Java 里隐式 mod 32,所以同一个表达式既算 word 偏移又算 nibble 位偏移,省一次 <code>{'(i & 7) * 4'}</code>。整张 TwistFlipPrun 332 KB,UDSliceTwistPrun / UDSliceFlipPrun 各 80 KB,MCPermPrun 33 KB,EPermCCombPPrun 195 KB——加起来内存就到论文宣称的 ~1 MB。</>}
                en={<>The <code>{'(i << 2)'}</code> wraps mod 32 in Java, so the same expression yields both the word offset and the nibble bit offset, saving an <code>{'(i & 7) * 4'}</code>. TwistFlipPrun is 332 KB, UDSliceTwistPrun / UDSliceFlipPrun ~80 KB each, MCPermPrun 33 KB, EPermCCombPPrun 195 KB — together right around the advertised ~1 MB.</>}
              />
            </p>
            <p>
              <L
                zh={<>表的构造用 BFS 加 <strong>inverse-fill</strong> 双向技巧:浅层用前向填充,深度过半 (<code>INV_DEPTH</code>) 后切到反向填充——因为浅层未填的格子越来越少,反向遍历"找还没填的、看它一步能不能到已填的"反而更省。具体见 <code>CoordCube.initRawSymPrun</code>。</>}
                en={<>Construction is BFS with an <strong>inverse-fill</strong> switch: forward-fill while the frontier is small, then once depth exceeds <code>INV_DEPTH</code> switch to scanning unfilled cells and asking whether any successor is already filled — cheaper when the unfilled set has shrunk. See <code>CoordCube.initRawSymPrun</code>.</>}
              />
            </p>
          </section>

          {/* ─────────────── 7. Phase 1 IDA* ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">07</span>
              <h2 className="algo-section-title"><L zh="Phase 1:IDA* + 三表取 max 启发式" en="Phase 1: IDA* with triple-max heuristic" /></h2>
            </div>
            <p>
              <L
                zh={<>Phase 1 是 IDA* (iterative-deepening A*),按总深度 <code>length1</code> 从 0 开始递增。在每个深度内做 DFS,节点扩展时把 18 个动作各做一次,通过 <code>doMovePrun</code> 拿到子节点的启发值,如果 <code>{'prun + depth > maxl'}</code> 立刻剪枝:</>}
                en={<>Phase 1 is IDA* iterated by total depth <code>length1</code> from 0 upwards. At each iteration limit, a DFS expands all 18 moves and calls <code>doMovePrun</code> to get the successor's heuristic; the branch is pruned the moment <code>{'prun + depth > maxl'}</code>:</>}
              />
            </p>
            <pre className="algo-code">{`// Search.phase1 (excerpt)
for (int axis = 0; axis < 18; axis += 3) {
    if (axis == lm || axis == lm - 9) continue;       // skip same / opposite axis
    for (int power = 0; power < 3; power++) {
        int m = axis + power;
        if (skipMoves != 0 && (skipMoves & 1 << m) != 0) continue;

        int prun = nodeUD[maxl].doMovePrun(node, m, true);
        if      (prun >  maxl) break;        // whole axis ruled out
        else if (prun == maxl) continue;     // this power ruled out

        if (USE_CONJ_PRUN) {
            prun = nodeUD[maxl].doMovePrunConj(node, m);
            if (prun >  maxl) break;
            if (prun == maxl) continue;
        }

        move[depth1 - maxl] = m;
        int ret = phase1(nodeUD[maxl], ssym & moveCubeSym[m], maxl - 1, axis);
        if (ret == 0) return 0;
        if (ret >= 2) break;
    }
}`}</pre>
            <p>
              <L
                zh={<>注意三件事。(1) 对同一轴的三个 power (U / U2 / U') 一旦发现某个 power 启发值已经卡死 (== maxl),直接 <code>continue</code> 到下一个 power;但如果是 <em>break</em> 则连同轴的其他 power 一起放弃——cs0x7f 用启发值的 "&gt; maxl" 还是 "== maxl" 区别来传递这种粒度。(2) <code>skipMoves</code> 利用 selfSym:如果当前状态对某个对称是固定的,可以按某种"字典序"丢掉对称等价的第一步,避免重复展开。(3) <code>USE_CONJ_PRUN</code> 是再做一次"魔方共轭一次后查同一张表"——相当于把启发式从一张表里挖出两套独立的下界,免费提升几步精度。</>}
                en={<>Three things to notice. (1) Among the three powers (U / U2 / U') on the same axis, <code>continue</code> rules out just that power while <code>break</code> kills the whole axis. cs0x7f signals the grain via "&gt; maxl" vs "== maxl". (2) <code>skipMoves</code> uses selfSym: if the current state has a non-trivial stabilizer, we can drop first-moves that are symmetry-equivalent to ones already tried, avoiding duplicate expansions. (3) <code>USE_CONJ_PRUN</code> queries the same prune table at one conjugate of the state — effectively doubling the heuristic for free, picking up another move or two of pruning.</>}
              />
            </p>
            <p>
              <L
                zh={<>当 <code>node.prun == 0 && maxl &lt; 5</code> 且 <code>allowShorter</code> 满足时,phase1 选择"提前结束"——这是和 phase2 交错的关键钩子,下一节细讲。</>}
                en={<>When <code>node.prun == 0 && maxl &lt; 5</code> and <code>allowShorter</code> permits, phase1 chooses to exit early — the hook into phase 2 that the next section unpacks.</>}
              />
            </p>
          </section>

          {/* ─────────────── 8. Phase 2 G1 内搜索 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">08</span>
              <h2 className="algo-section-title"><L zh="Phase 2:G1 子群内的 10 动作搜索" en="Phase 2: 10-move search inside G1" /></h2>
            </div>
            <p>
              <L
                zh={<>进入 phase2 后动作集只剩 10 个:U, U2, U', D, D2, D', R2, F2, L2, B2 (其它会破坏 G1 性质)。搜索状态由 3 个坐标完整刻画:<code>EPerm</code> (UD 棱排列)、<code>CPerm</code> (角排列)、<code>MPerm</code> (E 层 4 棱内部排列)。phase2 启发式同样是 max:</>}
                en={<>Inside phase 2 the move set shrinks to 10: U, U2, U', D, D2, D', R2, F2, L2, B2 — anything else would leave G1. Three coordinates fully describe the state: <code>EPerm</code> (UD edges), <code>CPerm</code> (corners), <code>MPerm</code> (E-slice internal). The heuristic is again a max:</>}
              />
            </p>
            <pre className="algo-code">{`// Search.initPhase2 — phase-2 lower bound
int prun = max(
    getPruning(MCPermPrun,       cperm * N_MPERM + MPermConj[mid][csym]),
    getPruning(EPermCCombPPrun,  edge  * N_COMB  + CCombPConj[Perm2CombP[corn]][...]),
    getPruning(EPermCCombPPrun,  edgei * N_COMB  + CCombPConj[Perm2CombP[corni]][...])  // inverse
);`}</pre>
            <p>
              <L
                zh={<>第三项是"反向状态"的启发——把当前状态求逆后再查表,cs0x7f 把 <code>getPermSymInv</code> 写成 O(1) 查表,因此免费再来一次下界。三个值取 max,phase2 在 <code>maxDep2</code> (≤12) 限制内 IDA*。<code>USE_COMBP_PRUN</code> 把 parity (奇偶) 直接编进 CComb 的 70~139 区间,作为剪枝的一部分。</>}
                en={<>The third term is the same heuristic evaluated on the inverse of the current state. cs0x7f makes <code>getPermSymInv</code> an O(1) lookup, so it's free. Phase-2 IDA* runs within <code>maxDep2</code> (≤12). <code>USE_COMBP_PRUN</code> folds parity into the 70–139 range of CComb so it contributes to the pruning bound automatically.</>}
              />
            </p>
            <pre className="algo-code">{`// Search.phase2 — branching with parity-aware move skip
int moveMask = Util.ckmv2bit[lm];
for (int m = 0; m < 10; m++) {
    if ((moveMask >> m & 1) != 0) { m += 0x42 >> m & 3; continue; }
    int midx  = MPermMove[mid][m];
    int cornx = CPermMove[corn][SymMoveUD[csym][m]];
    int csymx = SymMult[cornx & 0xf][csym];
    cornx >>= 4;
    int edgex = EPermMove[edge][SymMoveUD[esym][m]];
    int esymx = SymMult[edgex & 0xf][esym];
    edgex >>= 4;
    // … prun checks … then recurse phase2(edgex, esymx, cornx, csymx, midx, maxl-1, …);
}`}</pre>
            <p>
              <L
                zh={<><code>{'m += 0x42 >> m & 3'}</code> 是 cs0x7f 常用的"按位 LUT"小技巧:0x42 = 0100 0010<sub>2</sub>,对应 m=1 跳 2 步、m=6 跳 2 步——直接把同轴另一个 power 一起跳过,免循环。</>}
                en={<><code>{'m += 0x42 >> m & 3'}</code> is one of cs0x7f's bit-LUT tricks: 0x42 = 0100 0010<sub>2</sub> encodes "at m=1 skip 2, at m=6 skip 2", letting the loop hop past sibling powers on the same axis without an inner branch.</>}
              />
            </p>
          </section>

          {/* ─────────────── 9. P1↔P2 交错策略 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">09</span>
              <h2 className="algo-section-title"><L zh="Phase1 ↔ Phase2 交错:为什么不一次性接上" en="Phase-1 ↔ Phase-2 interleaving" /></h2>
            </div>
            <p>
              <L
                zh={<>原版 Kociemba 找到第一个 phase1 解就直接接 phase2,得到一个合法解 (比如 23 步)。问题是:phase1 用 7 步进 G1 + phase2 用 16 步,总 23 步;但同样的状态可能用 9 步 phase1 + 12 步 phase2 = 21 步更短——因为多走 2 步把 G1 的"位置"挑得更好。原版算法不会回头看。</>}
                en={<>Vanilla Kociemba commits to the first phase-1 solution and chains phase-2, returning a legal but not necessarily shortest answer (say 23 moves). The issue: a 7-move phase 1 + 16-move phase 2 may lose to a 9-move phase 1 + 12-move phase 2 = 21, because the longer phase 1 lands at a friendlier point in G1. Vanilla won't look back.</>}
              />
            </p>
            <p>
              <L
                zh={<>min2phase 把整套搜索按"总长度" <code>length1</code> 外层迭代。<code>search()</code> 的主循环:</>}
                en={<>min2phase iterates the outer loop by <strong>total length</strong> <code>length1</code>. The top-level <code>search()</code> loop:</>}
              />
            </p>
            <pre className="algo-code">{`// Search.search() — outer loop on total length
for (length1 = 0; length1 < solLen; length1++) {
    maxDep2 = Math.min(MAX_DEPTH2, solLen - length1 - 1);
    for (urfIdx = 0; urfIdx < 6; urfIdx++) {
        if ((conjMask & 1 << urfIdx) != 0) continue;   // axis already covered by selfSym
        if (phase1PreMoves(maxPreMoves, -30,
                           urfCubieCube[urfIdx],
                           (int)(selfSym & 0xffff)) == 0) {
            return solution == null ? "Error 8" : solution.toString();
        }
    }
}`}</pre>
            <p>
              <L
                zh={<>外层在试长度 <code>length1</code> 时,phase1 找到的每个"进 G1 的解"都会被立刻喂给 phase2 (调 <code>initPhase2</code>);只要凑出的 phase1+phase2 总长 ≤ <code>solLen</code> 就接受。一旦命中,<code>maxDep2</code> 立刻收紧 (<code>solLen - length1 - 1</code>),phase2 边界变严,但 phase1 继续探下一个等长的解 (因为可能换条 phase1 路径让 phase2 更短)。<code>probeMin</code> 控制至少跑多少次 phase2 才允许早退——这就是 README 里 "find shorter solutions" 那一段的来源。</>}
                en={<>For each value of <code>length1</code>, every phase-1 solution found is immediately handed to phase 2 (<code>initPhase2</code>); a phase1+phase2 chain of total ≤ <code>solLen</code> is accepted. The instant one is accepted, <code>maxDep2</code> is tightened to <code>solLen - length1 - 1</code> and the search keeps probing more phase-1 routes at this same length — a different phase-1 path may unlock a shorter phase 2. <code>probeMin</code> sets how many phase-2 probes must elapse before early exit. That's the "find shorter solutions" knob in the README.</>}
              />
            </p>
            <p>
              <L
                zh={<>另外两层增量:<strong>3 个轴 × 正反向</strong>。<code>urfCubieCube[0..5]</code> 存的是同一个魔方在 6 个 URF 共轭+反向下的视图;phase1 在每个视图独立跑,等价于 Algorithm.md 说的"换 3 个 G1 子群目标 + 同时解反向状态"。<strong>Pre-moves</strong> 是 (Phase1 * Phase2 * PreMoves = Scramble⁻¹) 这种重写,让 phase1 起点不必是原始 scramble——同样多给一倍候选。<code>conjMask</code> 用 selfSym 的位图把 6 个 urfIdx 里已被对称等价覆盖的剔掉,不重复搜。</>}
                en={<>Two more multipliers: <strong>3 axes × forward/inverse</strong>. <code>urfCubieCube[0..5]</code> stores the same cube viewed through six URF-conjugates and inverses; phase 1 runs once on each — matching Algorithm.md's "try three G1 targets + the inverse state". <strong>Pre-moves</strong> rewrite Phase1 · Phase2 · PreMoves = Scramble⁻¹, letting phase 1 not start at the literal scramble — another factor of candidates. <code>conjMask</code> uses the selfSym bitmap to skip urfIdx values already covered by a symmetry equivalence.</>}
              />
            </p>
            <div className="algo-callout">
              <div className="algo-callout-tag"><L zh="终止条件" en="Termination" /></div>
              <p>
                <L
                  zh={<>(a) 找到 <code>length ≤ maxDepth</code> 的解 <strong>且</strong> probe ≥ probeMin → 返回;(b) probe ≥ probeMax 且无解 → 返回 "Error 8";(c) length1 ≥ solLen 且无解 → "Error 7" (给定 maxDepth 下无解)。</>}
                  en={<>(a) Solution at length ≤ maxDepth <strong>and</strong> probe ≥ probeMin → return; (b) probe ≥ probeMax with no solution → "Error 8"; (c) length1 exhausts solLen with no solution → "Error 7" (no solution within the given maxDepth).</>}
                />
              </p>
            </div>
          </section>

          {/* ─────────────── 10. Benchmark ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">10</span>
              <h2 className="algo-section-title"><L zh="Benchmark:作者公布的实数" en="Benchmark: the author's numbers" /></h2>
            </div>
            <p>
              <L
                zh={<><code>Benchmark.md</code> 给出两组表 (作者环境随仓库)。第一组是"目标长度对求解时间":</>}
                en={<><code>Benchmark.md</code> ships two tables (author's environment). The first is target-length vs solve time:</>}
              />
            </p>
            <table className="algo-table">
              <thead>
                <tr>
                  <th><L zh="初始化" en="Init" /></th>
                  <th className="num"><L zh="Unlimited" en="Unlimited" /></th>
                  <th className="num">21 moves</th>
                  <th className="num">20 moves</th>
                  <th className="num"><L zh="启动时间" en="Init time" /></th>
                </tr>
              </thead>
              <tbody>
                <tr><td><L zh="Full" en="Full" /></td><td className="num">0.685 ms</td><td className="num">0.805 ms</td><td className="num">4.62 ms</td><td className="num">195 ms</td></tr>
                <tr><td><L zh="Partial" en="Partial" /></td><td className="num">4.12 ms</td><td className="num">4.52 ms</td><td className="num">19.0 ms</td><td className="num">60 ms</td></tr>
              </tbody>
            </table>
            <p>
              <L
                zh={<>Full init 预计算所有剪枝表 (约 195 ms),之后每次求解 <strong>0.8 ms</strong>;partial init 只算到 BFS 的某个浅深度,初始化只要 60 ms 但每次求解慢 5~6 倍。第二组表是"probeMin 对平均步数的影响":</>}
                en={<>Full init precomputes every prune table (~195 ms), after which each solve costs <strong>0.8 ms</strong>; partial init only fills BFS up to a shallow depth — init drops to 60 ms but solves are 5–6× slower. The second table shows the probe-budget trade-off:</>}
              />
            </p>
            <table className="algo-table">
              <thead>
                <tr>
                  <th className="num">probeMin</th>
                  <th className="num"><L zh="平均步数" en="Avg length" /></th>
                  <th className="num"><L zh="耗时" en="Time" /></th>
                </tr>
              </thead>
              <tbody>
                <tr><td className="num">5</td><td className="num">20.63</td><td className="num">0.827 ms</td></tr>
                <tr><td className="num">10</td><td className="num">20.48</td><td className="num">1.07 ms</td></tr>
                <tr><td className="num">20</td><td className="num">20.27</td><td className="num">1.55 ms</td></tr>
                <tr><td className="num">50</td><td className="num">19.95</td><td className="num">2.83 ms</td></tr>
                <tr><td className="num">100</td><td className="num">19.68</td><td className="num">4.87 ms</td></tr>
                <tr><td className="num">200</td><td className="num">19.48</td><td className="num">8.58 ms</td></tr>
                <tr><td className="num">500</td><td className="num">19.29</td><td className="num">19.4 ms</td></tr>
                <tr><td className="num">1000</td><td className="num">19.11</td><td className="num">36.3 ms</td></tr>
                <tr><td className="num">10000</td><td className="num">18.63</td><td className="num">—</td></tr>
              </tbody>
            </table>
            <p>
              <L
                zh={<>典型 csTimer 配置:probeMin = 0 (允许立刻返回第一解,目标只是合法长度 ≤ 21);此时单次打乱生成约 1 ms。如果用 min2phase 做 fewest-move 辅助分析,probeMin 拉到 1000+ 可以把平均压到 19.1 步,代价是每解几十毫秒。内存方面 README 给到 <strong>~1 MB</strong> 带 TwistFlipPrun,关闭后降到 ~0.7 MB——这正是为什么它能直接编进浏览器 JS 跑。</>}
                en={<>Typical csTimer setup: probeMin = 0 (accept the first legal-length-≤21 solution); one scramble costs ~1 ms. For fewest-move analysis, raise probeMin to 1000+ and the average compresses to 19.1 moves at a tens-of-ms cost per solve. Memory per the README: <strong>~1 MB</strong> with the TwistFlip table, <strong>~0.7 MB</strong> without. That budget is precisely why this fits inside a browser JS bundle.</>}
              />
            </p>
          </section>

          {/* ─────────────── 11. 工程细节 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">11</span>
              <h2 className="algo-section-title"><L zh="工程细节" en="Engineering details" /></h2>
            </div>
            <ul>
              <li>
                <L
                  zh={<><strong>Search 是有状态对象,但 solution() 加 synchronized。</strong>多线程并发要每条线程各持一个 Search 实例;同一实例不能并发调用 solution() / next()。</>}
                  en={<><strong>Search is stateful but solution() is synchronized.</strong> Use one Search instance per thread; do not call solution() / next() on the same instance concurrently.</>}
                />
              </li>
              <li>
                <L
                  zh={<><strong>Search.init() 是全局静态,只跑一次。</strong>所有 CoordCube 静态表是 process 级共享,init 后所有实例共用。再次调用 init() 会被 <code>initLevel</code> 短路。</>}
                  en={<><strong>Search.init() is global and one-shot.</strong> All CoordCube static tables are process-wide. Subsequent init() calls are short-circuited by <code>initLevel</code>.</>}
                />
              </li>
              <li>
                <L
                  zh={<><strong>无 GC 友好的数组复用。</strong><code>nodeUD/nodeRL/nodeFB</code> 各 21 个 CoordCube 在 Search 构造时一次性 new 完,搜索过程中所有 mutation 在这些固定槽位上做;<code>urfCubieCube[0..5]</code>、<code>preMoveCubes[1..MAX_PRE_MOVES]</code> 同理。整个搜索循环零分配。</>}
                  en={<><strong>Allocation-free hot loop.</strong> <code>nodeUD/nodeRL/nodeFB</code> are 21 preallocated CoordCube slots; <code>urfCubieCube[0..5]</code> and <code>preMoveCubes[1..MAX_PRE_MOVES]</code> likewise. The entire inner search reuses these slots — zero per-node allocation.</>}
                />
              </li>
              <li>
                <L
                  zh={<><strong>continueSearch / next()。</strong>找到第一个解后保留搜索状态 (<code>isRec = true</code>),用户继续调 <code>next(probeMax, probeMin, verbose)</code> 可以在不重启 IDA* 的情况下继续找更短解,直到 probe 用尽。</>}
                  en={<><strong>continueSearch / next().</strong> After the first solution the search state is kept (<code>isRec = true</code>); <code>next(probeMax, probeMin, verbose)</code> resumes IDA* in place to keep finding shorter solutions until the probe budget runs out.</>}
                />
              </li>
              <li>
                <L
                  zh={<><strong>Solution.appendSolMove 自动合并。</strong>同轴连续动作 (R + R → R2, R2 + R' → R) 在追加时自动塞回 moves 数组里,跨 phase1/phase2 拼接也自动消同轴对——所以输出的 length 是合并后的实际步数。</>}
                  en={<><strong>Auto move-merging.</strong> Same-axis consecutive moves (R + R → R2, R2 + R' → R) are merged on append, including across the phase-1 / phase-2 join. The reported length is post-merge.</>}
                />
              </li>
              <li>
                <L
                  zh={<><strong>USE_SEPARATOR / INVERSE_SOLUTION / APPEND_LENGTH / OPTIMAL_SOLUTION 四个 verbose flag。</strong>OPTIMAL_SOLUTION 切到 <code>searchopt()</code>——它对三个轴的 phase1 同时迭代,真正给出最优解但慢一个数量级。csTimer 默认不开。</>}
                  en={<><strong>Four verbose flags.</strong> USE_SEPARATOR / INVERSE_SOLUTION / APPEND_LENGTH / OPTIMAL_SOLUTION. OPTIMAL_SOLUTION swaps to <code>searchopt()</code> which iterates all three axes' phase 1 simultaneously, producing a provably optimal solve but an order of magnitude slower. csTimer leaves it off.</>}
                />
              </li>
            </ul>
          </section>

          {/* ─────────────── 12. 实际部署 ─────────────── */}
          <section className="algo-section">
            <div className="algo-section-head">
              <span className="algo-section-num">12</span>
              <h2 className="algo-section-title"><L zh="部署:从 Java 到浏览器 JS" en="Deployment: from Java to browser JS" /></h2>
            </div>
            <p>
              <L
                zh={<>min2phase 的源码就是 Java。要让它在 csTimer 里跑,关键不是手工翻写 JS,而是利用 Java 那套类型严格、无指针、无外部依赖的特征做整体翻译。csTimer 历史上用过两条路径:早期通过 <strong>GWT</strong> (Google Web Toolkit) 把 cs.min2phase 编译成等价 JS;后来 cs0x7f 直接维护手翻 JS 版 (<code>cstimer/src/lib/scramble_333.js</code>),拓扑跟 Java 几乎一比一对应,只是把 <code>char[][]</code> 换成 <code>Uint16Array</code>、<code>int[]</code> 换成 <code>Int32Array</code>。</>}
                en={<>min2phase ships as Java. Putting it inside csTimer is less about hand-porting and more about exploiting Java's strictness and zero external deps. Historically csTimer used <strong>GWT</strong> (Google Web Toolkit) to compile cs.min2phase to equivalent JS; later cs0x7f maintained a hand-translated JS port at <code>cstimer/src/lib/scramble_333.js</code>, almost line-for-line aligned with the Java source, swapping <code>char[][]</code> for <code>Uint16Array</code> and <code>int[]</code> for <code>Int32Array</code>.</>}
              />
            </p>
            <p>
              <L
                zh={<><strong>TNoodle</strong> (WCA 官方打乱生成器) 走另一条路:直接用 JVM 跑 cs.min2phase 的 jar,生成的打乱 hash 灌进 WCA 比赛系统。csTimer 跟 TNoodle 用同一份算法但执行环境不同——后者每场 WCA 比赛打乱都靠它出。</>}
                en={<><strong>TNoodle</strong> (the WCA's official scramble generator) takes a different route: it runs cs.min2phase as a jar on the JVM, hashes the scrambles, and feeds them into the WCA competition system. csTimer and TNoodle share the same algorithm but on different runtimes — TNoodle generates every official WCA scramble.</>}
              />
            </p>
            <p>
              <L
                zh={<>本站 <Link to="/cstimer">/cstimer</Link> 嵌的 iframe 里跑的就是这套 JS 版 min2phase;<Link to="/scramble/gen">/scramble/gen</Link> 的 3x3 默认打乱也是它生成 (随机状态 + min2phase 求解,丢弃求解只保留 scramble)。<Link to="/scramble/analyzer">/scramble/analyzer</Link> 用的 cubeopt-wasm 是更激进的 SAB+多线程方案,跟 min2phase 是平行路线。</>}
                en={<>The iframe at <Link to="/cstimer">/cstimer</Link> on this site runs that JS port of min2phase; the default 3x3 scramble at <Link to="/scramble/gen">/scramble/gen</Link> is also it (random state + min2phase solve, scramble keeps the inverse). <Link to="/scramble/analyzer">/scramble/analyzer</Link> uses cubeopt-wasm — a more aggressive SAB + multi-thread approach — running in parallel.</>}
              />
            </p>
            <div className="algo-callout">
              <div className="algo-callout-tag"><L zh="结语" en="Closing" /></div>
              <p>
                <L
                  zh={<>min2phase 是 Kociemba 二阶段框架下"工程做满"的范例:算法不动一行,通过对称压缩 + Huge prune + 多视图 + IDA* 全长迭代,把同样的二阶段从"几十 MB 内存+秒级"降到"1 MB 内存+毫秒级"。它没有提出新算法,但让旧算法第一次能跑在浏览器里——而这一点,决定了过去十年所有 WCA 选手的打乱怎么来。</>}
                  en={<>min2phase is the textbook case of "engineering the last drop out of an existing algorithm". Kociemba's two-phase framework is not touched; symmetry compression + the huge prune + multi-axis views + full-length IDA* iteration drop the same algorithm from tens of MB and seconds to 1 MB and milliseconds. It doesn't propose a new algorithm — it just makes the old one cheap enough to live in a browser tab. Which is why every WCA scrambler of the last decade looks the way it does.</>}
                />
              </p>
            </div>
          </section>

          <footer className="algo-page-foot">
            <Link to="/">CubeRoot</Link> · <Link to="/code/algorithms">/code/algorithms</Link>
          </footer>
        </div>
      </div>
    </LangCtx.Provider>
  );
}
