/**
 * EOCross 需要 10 步的全部 140 个状态,每个给一条 10 步打乱。
 *
 * 这不是「挑出来的难题」,是**穷尽**:`lib/eocross-dist.ts` 在全部 24,330,240 个 EOCross 态上
 * BFS,d=10 那一档恰好 140 个,而这 140 条打乱落到的正是这 140 个态 —— 一一对应,不多不少。
 * `tests/eocross_dist.test.ts` 每次跑都重验这件事(逐条算距离 + 双向覆盖),所以这份表不是抄来的
 * 清单,是可复算的结论。
 *
 * 打乱来源:`3x3.xlsx` 的 `10f eocross 140` 页(底色黄 = D 面,U/D 轴 EO 口径)。
 */

/** 底色:黄(D 面)。换底色这批打乱就不成立。 */
export const EOCROSS_10F_FACE = 'Yellow' as const;

/**
 * 底面定死后 EO 还剩两条轴(差一个 y 旋转),这批固定的是其中一条。按另一条轴读,
 * 140 条里 139 条掉到 6–9 步 —— 只有这一条两条轴都要 10 步。`tests/eocross_dist.test.ts` 重验。
 */
export const EOCROSS_10F_BOTH_AXES = "B2 F R' B' U' L' F' R L2 D'";

/** 每条 10 步,合计 140 条。 */
export const EOCROSS_10F: readonly string[] = [
  "B' R U F L' D2 F' L2 D' U'",
  "F D F U L' B F' R L2 U2",
  "F D F U L' B F' R L2 U'",
  "R2 B F' R U' B' D' B' L' U2",
  "R2 B F' R U' B' D' B' L' U'",
  "B D B U R' B' F R2 L U2",
  "B D B U R' B' F R2 L U'",
  "L2 B' F L U' F' D' F' R' U2",
  "L2 B' F L U' F' D' F' R' U'",
  "B F2 D2 R U' F L B D' U'",
  "R F D F U L' B F' L2 U'",
  "B2 F D2 L U' B R F D' U'",
  "F R' U' B' L D2 B L2 D' U'",
  "B2 F R L D2 B U' F L' D'",
  "B L' U' R' D2 B' F' R2 L' D'",
  "R F' D' B R U F2 L2 B U'",
  "L2 F R' L U' B' F' D2 L' D'",
  "R2 B' R L' D2 U B' F' L' D'",
  "B F' D2 R' U' B' D' B' L' U'",
  "L B' D' F L U B2 R2 F U'",
  "B' F D2 L' U' F' D' F' R' U'",
  "L' B' F' U' R D2 F R2 L' D'",
  "B R D2 F U' R' B' D2 L' D'",
  "L' F' L2 B U' R D2 F R2 D'",
  "B2 F R' B' U' L' F' R L2 D'",
  "R' B' D' B' U' L' D2 B F' U'",
  "B2 F' L B U' R F R2 L' D'",
  "R F R2 B' U' L' D2 F' L2 D'",
  "B' F2 R F U' L B R' L2 D'",
  "L B L2 F' U' R' D2 B' R2 D'",
  "R' B' R2 F U' L D2 B L2 D'",
  "R2 B D2 R F L' U' B' L' D'",
  "B' L' D2 F' U' B' L' D2 F' D'",
  "B' D2 L' F' U' B' D2 L' F' D'",
  "B' U' L F2 R B F R' D U'",
  "B2 R' D B' F2 R2 F D R' U'",
  "R2 L' F L' D' R B' F D' U'",
  "F R2 L' D' F R' B' F2 D' U'",
  "B' L' F' U' R' F2 D2 B' D U'",
  "B R' L2 D' B L' B2 F' D' U'",
  "R' L2 B R' D' L B F' D' U'",
  "F' U' R B2 L B F L' D U'",
  "F' R' B' U' L' B2 D2 F' D U'",
  "L B2 R2 U' B D2 F D L' U'",
  "B L D' L2 F' R B L' D U'",
  "B U R' F2 L' B' F' L D' U'",
  "R2 B D U F R' L' B' L2 U'",
  "F' U' R B2 L B F L' D' U'",
  "B F2 D2 R U' F L B D U'",
  "B' L U F D B' L' U B' U'",
  "F' D2 R' U' F' D2 R' B' D' U'",
  "B D' L D2 F R' B L2 D2 U'",
  "F U R2 B' L' D2 F' L2 D' U'",
  "F R L B' L D' U2 F D2 U'",
  "B U L2 F' R' D2 B' R2 D' U'",
  "F U L' B2 R' B' F' R D' U'",
  "F D' R2 F' R' B' U' F L' U'",
  "B' U' L F2 R B F R' D' U'",
  "B2 F D2 L U' B R F D U'",
  "B' D2 L' U' B' D2 L' F' D' U'",
  "F' R U B D F' R' U F' U'",
  "F D' R D2 B L' F R2 D2 U'",
  "F R D' R2 B' L F R' D U'",
  "F D' L' F' D' B' R' F D' U'",
  "B R L F' R D' U2 B D2 U'",
  "B D' R' B' D' F' L' B D' U'",
  "R' F U' L' D' B' R F' D' U2",
  "R' F U' L' D' B' R F' D' U'",
  "B' L' B' U F' R' B F2 D U'",
  "F' R' B' U' L' B2 D2 F D' U'",
  "F L B U' R B2 D2 F' D' U'",
  "F L' U2 F U B R F' D U'",
  "F' R D' B U' F' R' B2 D2 U'",
  "F' R' B' U' L' B2 D2 F D U'",
  "D2 F L' U B R' D F' D2 U'",
  "B' L' D F2 R U' B F D2 U'",
  "B' F' D F2 R L' U2 B' D' U'",
  "F' L B R' D' U' B2 F' R2 U'",
  "B U' F' R L D B F2 L2 U'",
  "F D L' U B D R' F' D2 U'",
  "F U' B' R L B2 D F R2 U'",
  "F' R' D B2 L U' B F D2 U'",
  "B D R' U F D L' B' D2 U'",
  "D2 B R' U F L' D B' D2 U'",
  "B' F' D B2 R' L U2 F' D' U'",
  "B' R F L' D' U' B' F2 L2 U'",
  "B R' D2 B' D' F L' B' L2 U'",
  "F' U' R B2 L B F L D' U'",
  "B U' R' B' F D' B' L' D2 U'",
  "R' B2 D2 B' U R' L B' D' U'",
  "F2 D2 F' R2 U L' F' R' D' U'",
  "B2 D2 B' L2 U R' B' L' D' U'",
  "B R' U2 B U F L B' D U'",
  "L' F2 D2 F' U R L' F' D' U'",
  "D2 F' R U' B R L2 D F' U'",
  "F' R U' B R L2 D F' D2 U'",
  "L' B U' R' D' F' L B' D' U'",
  "L' B U' R' D' F' L B' D' U2",
  "B F2 R U' L F' D2 B' D' U'",
  "F' L B R2 D' U' R F' D' U'",
  "F R B U' L' D2 F' R' D' U'",
  "F R B U' L' D' F' R' D' U'",
  "B' L D' F U' B' L' F2 D2 U'",
  "F' D L' F' D' L B' R L' U'",
  "F' R2 U B2 U2 R' B' R' L' U'",
  "B' R F L2 D' U' L B' D' U'",
  "B U' B F R' D F U2 L' U'",
  "L2 B' F D' R B' F D' L' U'",
  "B2 F L U' R B' D2 F' D' U'",
  "B U R' F2 L B' F' L' D' U'",
  "B L F U' R' D' B' L' D' U'",
  "B L2 F2 R2 U' L' U' F' D' U'",
  "L2 B' D' L F D2 U' B' L' U'",
  "L2 B D2 L' U' R' B' F L D'",
  "B R U' L B' F2 R2 D L' U'",
  "R B' F U' L2 B' F U2 L' U'",
  "B D2 F2 U' R' B2 L' F L2 U'",
  "F L B' L2 F2 R D' F' D' U'",
  "B' L2 U2 F2 R B D F' L' U'",
  "R B U' F' R' L B' D2 L2 U'",
  "L F U R B' L' D F' R U'",
  "L2 B' D' L F D2 U' B' L' U2",
  "F2 D B' U L U2 F D' B' L'",
  "R B U L F' R' D B' L U'",
  "L2 B D2 L' U' R' B' F L U'",
  "F' U' R2 B2 L B' R' D' F' U'",
  "B2 R' B L2 F D' R2 U2 L' U'",
  "L' B D R2 U2 B2 U L' F' U'",
  "B' U B' L' F U2 R2 D' L' U'",
  "L' B' F U' R2 D' B' F L' U'",
  "L2 B' D' L F D2 U' B' L' U",
  "L2 F' D2 L U R B' F L' D'",
  "L' B U' R' D U2 B F R2 U'",
  "F D U B R' F L' U' L' U'",
  "F D2 R2 U' L' F D' U2 L' U'",
  "F' L' B' R2 D' U' F R' L U'",
  "L2 F D L' D' B' D' U F L'",
  "F L' D U' B R' U' F L2 U'",
  "L2 F' D2 L U R B' F L' U'",
  "F' U B' D B2 F R' F L' U'",
];

export const EOCROSS_10F_TOTAL = EOCROSS_10F.length;
