// Maintain only the generated local config. A hand-edited config.yml remains authoritative.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { wcaDir, puzzleDir, xcrossDir } from './pipeline_paths.mjs';

const configPath = resolve(dirname(fileURLToPath(import.meta.url)), 'config.yml');
const marker = '# generated by prepare_config.mjs; edit config.yml to take ownership';
if (existsSync(configPath) && !readFileSync(configPath, 'utf8').startsWith(marker)) {
  console.log(`Using custom ${configPath}`);
  process.exit(0);
}
const config = `${marker}\nsets:\n  - key: wca\n    label: WCA\n    label_zh: WCA\n    csv_dir: ${JSON.stringify(join(wcaDir, 'stats'))}\n    scrambles_txt: ${JSON.stringify(join(wcaDir, 'wca_scrambles_no_wide_move.txt'))}\n  - key: xcross_2_col_10f\n    label: dual-color 10f xcross\n    label_zh: 双色底 10f xcross\n    csv_dir: ${JSON.stringify(join(xcrossDir, 'stat'))}\n    scrambles_txt: ${JSON.stringify(join(xcrossDir, 'scrambles.txt'))}\npuzzle_data_dir: ${JSON.stringify(puzzleDir)}\n`;
writeFileSync(configPath, config);
console.log(`Prepared ${configPath}`);
