/**
 * 472 ZBLL algorithms (first alg of each case), extracted from
 * @cuberoot/shared/data/zbll.json. Used by the ZBLL training scramble
 * generator (inverse applied as setup).
 */

export const ZBLL_ALGS: readonly string[] = [
  "R U R' U R U' R' U R U' R' U R' U' R2 U' R' U R' U R",
  "y' R' U2 R U R' U' R U R' U R",
  "R' U' R U' R' U R U' R' U2 R",
  "y R U2 R' U' R U' R' U' R' U' R U' R' U2 R",
  "y' R U2 R' U' R U R' U' R U' R'",
  "R U R' U R U' R' U R U2 R'",
  "y' R' U2 R U R' U R U R U R' U R U2 R'",
  "R U R' U R U2 R' U' R' U2 R U R' U R",
  "F U' R2 U R U2 R' U R2 U2 R' U' R F'",
  "y' R U R' U y' R' U R U' R2 F R F' R",
  "y r U2 R2 F R F' R U2 r' L' U2 L U L' U L",
  "x' U' R U' R' U R' F2 R U' R U R' U x",
  "R' U2 R U R' U R U R' U' R U R' F' R U R' U' R' F R2",
  "y F R U R' U' R U R' U' R U R' U' F'",
  "R' U' F' U F R U f R U R' U' R U R' U' f'",
  "R' F2 r2 U' r' F r' F2 R2 U R' U R U2 R'",
  "y2 R' U' R U' R' U F' R U R' U' R' F R2 U' R' U R",
  "y R' U2 R U R2 D' R U' R' D R2 U R' U R",
  "R U R' U R U r' F R' F' r",
  "y' R U R2 F R F' r U' r' U r U r'",
  "y R U R' U R U2 R' F R U' R' U' R U2 R' U' F'",
  "R' U' R U' R' U' L U' R U L'",
  "y2 R2 D' R U' R' D R2 U' R2 D' R U2 R' D R2",
  "y2 R2 D R' U R D' R2 U R2 D R' U2 R D' R2",
  "y' R U2 R' U' R2 D R' U R D' R2 U' R U' R'",
  "R' U' R D' R U' R' U2 R U2 R U R U' R2 D",
  "y R' F R' F' R2 U' r' U r U' r' U' r",
  "y R' D' R U R' D R2 U R' U2 R U2 R' U R U2 R'",
  "y' R U2 R' U' R U R' U2 R' F R2 U' R' U' R U R' F'",
  "y' R' U2 R U2 R2 F' R U R U' R' F U R",
  "y R' D R2 U' R2 D' R U' R' D R2 U2 R2 D' R",
  "y' R D' R U2 R' U2 R U' R' U' R U R' D R'",
  "y' F R' F' r U R U' r2 F2 r U L' U L",
  "y' R U2 R' U' R U R' U' F' R U R' U' R' F R2 U' R'",
  "y2 R' U' R U' R' U R U R' F R U R' U' R' F' R2",
  "y F' r U R' U' r' F R2 U2 R' U' R U' R'",
  "y2 R' U2 R2 U R2 U R U2 R' F R U R U' R' F'",
  "R F R2 U' R2 U' R2 U2 R2 U' F' R'",
  "y2 F R U' R' U R U2 R' U' R U R' U' F'",
  "y2 f R2 S' U' R2 U' R2 U R2 F'",
  "F R U R' U' R U' R' U2 R U2 R' U' F'",
  "y' R' U' R U R' F' R U R' U' R' F R2",
  "y R U' R' U R U' R' U' R U R' U2 R' D' R U R' D R",
  "L U L' U' L F L' U' L U L F' L2",
  "y' F R U' R' U' R U R' U R' D' R U' R' D R2 U R' U' F'",
  "y R' U R U' R' U' R U' R' U2 R' D' R U' R' D R2",
  "y2 F' r U R' U R' D R U' R' D' R U' r' F R",
  "R' D' R U' R' D R U2 R U' R' U R U R' U' R U R'",
  "y M' U' r U2 R' F R U2 r2 F R",
  "y r U2 r2 F R F' r2 R' U2 r'",
  "r U R2 D' R U2 R' D R U r' F R F'",
  "r U2 R r2 F R' F' r2 U2 r'",
  "y2 F' R U2 R' U2 R' F U2 R U R U' R2 U2 R",
  "y L' U R' U' L R U2 R' U R U R' U R",
  "y2 F' R U2 R' U2 R' F R U R U' R'",
  "y S' R' U' R f R' F' U R U R U' R'",
  "y' R' U' R U R' F2 R U2 R' U2 R' F2 R2",
  "y2 R U2 R' U2 D R' U R' U' R' U R2 D'",
  "y R U R' U R U' R' U R U' R' U R2 D R' U2 R D' R2",
  "R' U' R' D' R U2 R' D R U R U' R' U' R",
  "y' R' F R U R U' R' F' U R U R' U R U' R'",
  "y' F R U' R' U' R U2 R' U' F'",
  "y2 F' r U R' U' r' F R",
  "y R U R' U R' D' R U2 R' D R2 U' R' U R U' R'",
  "y2 R U R' U R U R' U2 R' D' r U2 r' D R",
  "y R' U R' D' R U R' U2 R U R' U D R U' R",
  "R' D' R U2 R' D R U R U2 R' U R U R'",
  "y2 R U2 R' U' R2 D R' U' R D' R2",
  "y R U2 R D R' U2 R D' R2",
  "y2 R' F' R U2 R U2 R' F U' R U R' U' R U' R'",
  "y2 R U R' U R U2 R D R' U2 R D' R' U2 R'",
  "y R U' R2 D' R U' R' D R U2 R U' R' U' R U R'",
  "y R U2 R D r' U2 r D' R2",
  "y R U2 R' U2 R U R2 D' R U2 R' D R2 U2 R'",
  "y' F U' R U R' U R' U2 R U R' U R2 U' R' U F'",
  "y2 F R U R' U' R' F' U' R U R U' R' U' R' U R",
  "D' R U R' U2 R U R' U D R' U2 R U' R' U' R",
  "y' R' U2 R U R2 D' R U R' D R2",
  "R' U R2 D R' U R D' R' U2 R' U R U R' U' R",
  "y' R' U' R2 D r' U2 r D' R2 U R U R' U2 R",
  "R' U2 R' D' R U2 R' D R2",
  "R' U2 R' D' r U2 r' D R2",
  "y' R U' R2 F2 R U2 R U2 R' F2 U2 R U' R'",
  "y R D R' U2 R D' R' U' R' U2 R U' R' U' R",
  "R' U R U' R' U F' R U2 R' U2 R' F R2",
  "R' U2 R U2 R' U' R2 D R' U2 R D' R2 U2 R",
  "y F' R U R' U' R' F R2 U' R' U' R U' R' U R U R'",
  "y' F R U' R' U R U R2 D' R U R' D R2 U' R' F'",
  "y R U2 R' U' R U' R' U2 R U R' U R U2 R'",
  "R' U2 R U R' U R U' R U2 R' U' R U' R'",
  "R2 U R' U' R' U R U R' U R U' R U' R2",
  "y R U2 R' U' R U' R' U R' U2 R U R' U R",
  "R U' R' L' U2 L U L' U L R U2 R'",
  "y' R2 U R' U R' U' R U' R' U' R U R U' R2",
  "y R U R' U R U2 R' U R' U' R U' R' U2 R",
  "y R2 U' R U R U' R' U' R U' R' U R' U R2",
  "y2 R2 U' R U' R U R' U R U R' U' R' U R2",
  "y' R U R' U R U' R' U R U' R' U R U2 R'",
  "R' U' R U' R' U2 R U' R U R' U R U2 R'",
  "y R U R' U R U2 R' U2 R U2 R' U' R U' R'",
  "R' U2 R2 U R' U' R' U2 F R U R U' R' F'",
  "y R U' R' U R U' R' U' R U R2 D' R U' R' D R",
  "y R U R D R' U2 R D' R' U' R' U R U R'",
  "y R2 U R U R D' R U' R' D U' R' U2 R'",
  "R2 D' R U2 R' D R2 U R2 F' R U R U' R' F R",
  "L R U' R' U L' R U R' U R U' R'",
  "x' R U' R' D R U R' D' x",
  "y F R U R' U' R' F' R U2 R U2 R'",
  "y' R' U2 R U2 R U' R D' U R U' R' D R'",
  "y2 R U R' F' U' r' F2 r U F",
  "R' U' R U' R' U R U' R' U R U' R2 D' R U2 R' D R2",
  "y R U' R' U' R' D' r U2 r' D R U' R U R'",
  "F R U R' U' R' F' R U2 R' U' R2 U' R2 U2 R",
  "y' r' F' r U' r' F2 r2 U R' U' r' F R F'",
  "y' R U R' U R U' R' U' R' F' R U2 R U2 R' F",
  "y' R F U R2 U2 R2 U R2 U R2 F' R'",
  "R2 F R U R U' R' F' R U' R' U' R U R' U R",
  "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
  "y2 R U R D R' U' R D' R U' R U' R' U2 R",
  "y2 R' U' R' D' R U R' D R3 U R' U R U2 R'",
  "y' R U R' U R U2 R2 F' r U R U' r' F",
  "y F U R U' R' U R U2 R' U' R U R' F'",
  "y' F U' R U' R' U R U R' U2 R U2 R' U F'",
  "F R' F' R U2 R U2 R' U' r U R' U R U2 r'",
  "y R2 D' R U2 R' D R2 U R2 D' R U R' D R2",
  "r U' r' U' r U r' F R' F' R2 U' R'",
  "R' U' R U' R2 D' R U R' D R2 U' R' U2 R",
  "y2 L' U R U' L U' R' U' R U' R'",
  "R U R' U R2 D R' U' R D' R2 U R U2 R'",
  "y R U2 R' U' R U2 R' U2 R U' R2 D' R U' R' D R",
  "y2 R U2 R' U' R U r' F2 r U2 R' U' r' F r",
  "y' R2 D R' U2 R D' R2 U' R2 D R' U' R D' R2",
  "R' U' R U R2 F' R U R U' R' F U' R U R' U R",
  "r' U r U r' U' r U R2 F R F' R",
  "y' F U R U2 R' U R U R' F' R U2 R' U' R U' R'",
  "y' R U R' U F' R U2 R' U2 R' F R",
  "y R U2 R' U' F' R U2 R' U' R U' R' F R U' R'",
  "y2 R F U' R2 U2 R U R' U R2 U F' R'",
  "y' R' U' R U R' U' R2 D R' U R D' R' U R' U2 R",
  "R' F' U' F U' R U S' R' U R S",
  "R2 D R' U2 R D' R2 U' R U R D R' U2 R D' R2",
  "F U R' U' R2 U' R2 U2 R U2 R U R' F'",
  "R2 D R' U' R D' R' U' R' U R U' R' U' R U' R'",
  "y2 R U2 R' U R' D' R U R' D R2 U' R' U R U' R'",
  "y R' U' R' D' R U R' D R U2 R' D' R U2 R' D R2",
  "y R U R' U' R U R2 D' R U' R' D R U' R U2 R'",
  "R2 D' R U R' D R U R U' R' U R U R' U R",
  "y R U2 R' U2 R' U' F U R2 U' R' U R U' R' F'",
  "R' U' R' D' R U' R' D R2 U R' U' R U R' U R",
  "y R U2 R' U' R U' R2 U r f' U f r'",
  "y R U R' U R U' R' U R2 D R' U' R D' R' U' R'",
  "y R' F R F' r U R' U R U2 r' U' R U' R'",
  "y2 R' U2 R U R' U' R U R2 F R U R U' R' F' R",
  "y F U R U' R' U R U' R2 F' R U R U' R'",
  "y' R U R' U R U' R2 F R F' R U' R' F' U F",
  "R U' R' U' R U' R' U R U R' U R' F' R U R U' R' F",
  "y F U R U2 R' U2 R U R2 F' R U2 R U2 R'",
  "y' R' U' R U' R' U R U' R' U R' D' R U R' D R2",
  "y R U R' U' R U R2 D' R U R' D R U R U' R' U R U2 R'",
  "R' F2 R U2 R U2 R' F2 U' R U' R'",
  "R U R2 U' R2 U' R2 U2 R2 U' R' U R U2 R'",
  "y R' U2 R U2 R' U R U2 R' U R U2 R' U' R",
  "y R U R' U R U2 R2 U2 R U R' U R",
  "R' U2 R2 U R2 U R2 U2 R'",
  "R' U' R U R U2 R' U' R U' R2 U2 R",
  "y' R U2 R' U2 R U' R' U2 R U' R' U2 R U R'",
  "R U2 R2 U' R2 U' R2 U2 R",
  "y2 R U' R' U2 R U R' U2 R U R' U2 R U2 R'",
  "y R U2 R' U' R U' R2 U' R U' R' U2 R",
  "R U R' U' R' U2 R U R' U R2 U2 R'",
  "y2 R' U R U2 R' U' R U2 R' U' R U2 R' U2 R",
  "y R U R' U R U2 R' U R U R' U R U2 R'",
  "R U R' U' R' F R2 U R' U' R U R' U' F'",
  "R U R' U R U2 R' U' R U' L' U R' U' L",
  "R U R D R' U R D' R2 U' R U R' U' R U' R'",
  "y F' R U R' U' R' F R U' R U' R' U' R U R' U R U R'",
  "y' F U R U' R' S R' D' R U R' D R2 U' R' f'",
  "R' F R U R' U' R' F' R2 U' R' U R U' R' U2 R",
  "y2 R2 D' R U' R' D R U' R U R' U' R U R' U R",
  "y R U R' U R U' R' U R U' R D R' U' R D' R2",
  "y' R U R' U F2 R U2 R' U2 R' F2 R",
  "y R U2 R' U' R U R' U' R' D' R U' R' D R2 U' R' U R U' R'",
  "y' R' U' R U' R' U R U' R2 D' R U R' D R U R",
  "y2 R U2 R' U2 R' F R2 U' R' U2 R U2 R' U' F'",
  "y2 R' U2 R U F R' U R U' F'",
  "R' U R U2 R' U R2 D R' U R D' R'",
  "R U R2 F' R U2 R U2 R' F R U' R'",
  "R U R' U R U' R2 F' R U R U' R' F R U' R'",
  "y2 S' U2 L' U2 L U2 L F' L' f",
  "y2 R U R' U R2 D r' U2 r D' R2",
  "F' R U R' U R U2 R' F U R U' R' U2 R U' R'",
  "y R U R' U' R U R2 D' R U R' D R U R U2 R'",
  "y' R' U' R U R2 U' R' U' R U D' R U R' D R'",
  "y2 R U R' U R2 D R' U2 R D' R2",
  "y R' F R U R' U' R' F' D' R U R' D R2",
  "R U2 R D R' U2 R D' R' U R' U R U2 R'",
  "y' R U R' U R U' R D R' U R r' U2 r D' R2",
  "y F U R U' R' U R U' l U' R2 D' R U R'",
  "y' R' U2 R' D' R U R' D R U' R U R' U R",
  "y' R U R' U R U' R D R' U' R D' R2",
  "y x D R2 D2 R U2 R' D2 R U2 R D'",
  "F R U' R' U R U2 R2 F R F' R' F R F' U' F'",
  "y2 R U R' U R U' R D R' U R D' R' U2 R'",
  "y R' U' R U' R2 F' R U R U' R' F U2 R",
  "y2 R2 D' R U' R' D R U' R U R' U R",
  "y' F R' U R U F' R' U F U F' R",
  "y2 R U2 R' U' R U R' U' R U R D R' U2 R D' R2",
  "R U' R' U' R U R D R' U2 R D' R2 U R U2 R'",
  "y' R U R' U' R' U2 R U R U' R' U R' U R",
  "y' R' U2 R U R' U R",
  "R U R' U R U' R' U R' U' R2 U' R' U R' U R",
  "R' U2 R2 U2 R2 U' R2 U' R2 U R",
  "R U R' U' R U R' U R U R U2 R' U' R U' R' U R'",
  "R U R' U R U2 R'",
  "R U R2 F' R U2 R U' R' U' R' F R2 U' R'",
  "y2 R' U' R U' R U R' U R U2 R' U' R' U R",
  "R U R2 U' R2 U' R2 U2 R2 U2 R'",
  "y' R' U2 R2 U R2 U R U' R U' R'",
  "y' R U R' U' R' U2 R U R' U R U' R U' R'",
  "R' F' U' F U R F U R U' R' F'",
  "y2 R U R' F' R U R' U R U' R' U' R' F R2 U' R'",
  "y R' U' R' U R2 D' U2 R U R' U' D R'",
  "y' R' U2 F' R U R' U' R' F R U2 R",
  "y R' U2 R U R' U' R' D' R U2 R' D R2",
  "R U' r' F R' F' r",
  "y' R' U' D R' U R D' U2 R2 U R' U' R'",
  "L U2 L F L' U' L' U L F' U2 L'",
  "R2 D r' U2 r D' R' U' R' U R U2 R'",
  "R2 D R' U2 R D' R' U' R' U R U2 R'",
  "R U R' U R U' R' U' D R2 U' R U' R' U R' U R2 D'",
  "R U R' U R U' R' U' R' F R2 U' R' U' R U R' F'",
  "y' R' U2 R U R' U' R U2 R' F R U R' U' R' F' R2",
  "r' R F R' F' r U2 R U2 R'",
  "y R' U2 R U R2 D' R U' R' D R U2 R",
  "R2 F R U R U' R' F' R U' R' U R",
  "y R' D' R U R' D R2 U R' U2 R U R'",
  "f R' F' R U2 R U2 R' U2 S'",
  "F U R U' R' S R' F' R U R U' R' S'",
  "y F R' U' R2 U' R2 U2 F R F' R U' R' F'",
  "F R U R' U' R' F' R U2 R U' R' U R U2 R'",
  "y2 R2 D' r U2 r' D R2 U R' U R",
  "R' U2 R U R' U R' D' R U2 R' D R U2 R",
  "y F R U R' U' R' F' R U R2 D R' U' R D' R2",
  "y2 R2 D' R U2 R' D R2 U R' U R",
  "F R U' R2 U2 R U R' U R2 U R' F'",
  "R' F R f' U R U R' U2 f R' F' R",
  "y' R U' R2 U2 D' R U R' U D R2 U R'",
  "y2 R U R' U L' U R U' L U2 R'",
  "F U' R' U R U F' R U R2 U R2 U2 R'",
  "R' U2 R U R' U' R F U' R' U' R U F'",
  "y' R' U' F U R U' R' F' R2 U R' U' R' F R F'",
  "y F U R' F R F' R U' R' U R U' R' F'",
  "L' U2 R U' R' U2 L U R U' R' U R U2 R'",
  "y F' R U R' D R U R' U' D' R U' R' F",
  "R U R2 F2 R U2 R U2 R' F2 U R U2 R'",
  "y R2 U R2 F' R U2 R' U' R U' R' F R2 U' R2",
  "R U2 R' U' R U' R2 U2 R U R' U R",
  "y' R' U' R U' R' U R U' R U R2 U R2 U2 R'",
  "y' R U R2 U' R2 U' R2 U2 R U' R U' R'",
  "y' R U R' U R U2 R' U' R U2 R' U' R U' R'",
  "y' R U R' U R U2 R' U2 R' U' R U' R' U2 R",
  "y2 R U' R' U2 R U R' U2 R U R' U R U' R'",
  "y' R U R' U R U' R' U R' U' R2 U' R2 U2 R",
  "R U2 R' U' R U' R' U R U R' U R U2 R'",
  "y2 R' U2 R U R' U R U' R' U' R U' R' U2 R",
  "R' U R U2 R' U' R U' R U R' U' R' U' R U R U' R'",
  "y' R' U' R2 U R2 U R2 U2 R' U R' U R",
  "y2 R' U2 R U R' U R2 U2 R' U' R U' R'",
  "y R' D' R U' R' D R U' R U' R' U R U' R' U' R U R'",
  "R' U' R U2 R D R' U' R D' R2 U R U' R' U R",
  "R U' R' U R U R' U' R U R' U R' D' R U R' D R",
  "y R U R' U' R U R2 D' R U' R' D R U2 R U' R'",
  "y2 R U R' F' R U R' U' R' F R U' R' F R U R U' R' F'",
  "y2 R U' R2 D' r U2 r' D R2 U R'",
  "y2 R2 D' R U' R' D R U R U R' U2 R' D' R U2 R' D R2",
  "y R U' R2 D' r U2 r' D R2 U' R' U' R U' R'",
  "R' U R2 D r' U2 r D' R2 U' R",
  "y R' U' R U R' U' R2 D R' U R D' R' U2 R' U R",
  "y2 R2 F R U R' U' R' F' R' U' R2 U2 R U2 R",
  "y2 R U R' U2 R' D' R U R' D R2 U' R' U R U' R'",
  "y' R U R' U2 R U' R' U2 R U' R2 F' R U R U' R' F",
  "r U R' U' r' F R F' R' U2 R U R' U R",
  "y R' U' R U' F U' R' U R U F' R' U R",
  "R' U2 R' D' R U2 R' D R' U R' U R U2 R'",
  "y' l' U2 R' D2 R U2 R' D2 R2 x'",
  "y R U R' U R' D' R U' R' D R U R U2 R'",
  "R' D' R U R' D R2 U R' U2 R U' R' U' R U' R'",
  "y R' U' R' D' R U R' D R U' R U' R' U2 R",
  "y' R' F2 R U' R2 F2 R2 U' R' U2 R' F2 R2",
  "y' l U2 R D2 R' U2 R D2 R2 x",
  "y2 R U2 R' U' R U' R2 F' r U R U' r' F",
  "y2 F R U R' U' R U' R' U' R U R' F'",
  "y2 F R U R' U' R' F' U2 R U R U' R2 U2 R",
  "y' R' D' R U R' D R2 U' R' U R U R' U' R U R'",
  "y' R U2 R' U2 R' F R U R U' R' F'",
  "y R U R' U R U R' U2 L R U' R' U L'",
  "y2 R' U' R U D' R U' R U R U' R2 D",
  "y' R U R' U' R U' R' L U' R U R' L'",
  "R' U' R U' R2 F' R U R U' R' F U R U' R' U2 R",
  "F U' B' R2 U' R2 U R2 F' B",
  "y2 R U R D R' U2 R D' R' U' R' U R U' R' U' R U' R'",
  "y2 R L' U R' U' L U R U R' U' R U' R'",
  "y' r U R' U' r' F R F'",
  "y' F' U' r' F2 r U F R U' R'",
  "R' U2 R F U' R' U R U F' R' U R",
  "R2 F2 R U2 R U2 R' F2 R U' R' U R",
  "y R U R' U' R U R2 D' R U2 R' D R U' R U' R'",
  "y F U R U2 R' U R U R' F'",
  "y2 R' U' R' D' R U R' D R2",
  "y2 F R2 D R' U' R D' R2 U' R U2 R' U' F'",
  "y' R' U R U R' U' R' D' R U2 R' D R U R",
  "y R' U2 R2 U R' U' R' U2 F' R U2 R U2 R' F",
  "y R U R' U' R' F' R U2 R U2 R' F",
  "y F R U R' U' R U R' U' F' R U R' U' R' F R F'",
  "y R' U' R U' R' U' R U2 L' R' U R U' L",
  "y' R' U' R U R' U R L' U R' U' R L",
  "y' R' U' R' D' R U R' D R U2 R U R' U R",
  "y R U R2 F R F' R U' R' F' U F",
  "R U' R' U R U R' U' R U R' U' R' D' R U' R' D R",
  "y2 R U' R' U2 L R U' R' U L'",
  "R' U R U2 L' R' U R U' L",
  "y2 R' U' R2 U R' F' R U R' U' R' F R2 U' R' U' R' U R",
  "R' U2 R U R' U R F U R U2 R' U R U R' F'",
  "F U' R' U2 R U F' R' U' R U R' U R",
  "y2 r U' r U2 R' F R U2 r2 F",
  "y L' U2 R U2 R' U2 L U R U R' U' R U' R'",
  "F R U' R' U' R U2 R' U' F' R' U' R U' R' U2 R",
  "R U R' U R U' R' F' U' L' U2 L U F",
  "R2 B2 R' B2 R' U R U' L U' L' U R'",
  "r2 F2 r U2 r U' L' U R' U R U' L",
  "y F U R U2 R' U R U R2 F' r U R U' r'",
  "y' F2 R U' R' U' R U R' F' R U R' U' R' F R F2",
  "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
  "y' R2 F' R U R' U' R' F R2 U' R' U2 R2 U R' U R",
  "y' R' U' R F R2 D' R U R' D R2 U' F'",
  "y' r U R' U' r' F R2 U' R' U' R U2 R' U' F'",
  "y R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R' U2 R",
  "y' R2 D R' U2 R D' R' U2 R' U' R U2 R' U' R U' R'",
  "y' F U R2 D' R U' R' D R2 F' R' U R",
  "y' R U2 R' U2 R' F R U R U2 R' U' R U2 R' U' F'",
  "y2 R U' R2 F R U R U' R2 F' R U' F' U F",
  "R' U2 R U R' U R' D' R U' R' D R U R",
  "R' U' R U2 R' F' R U R' U' R' F R2 U2 R' U R",
  "R U R' U R U' R' U2 R' D' R U2 R' D R2 U' R'",
  "x' R2 D2 R' U2 R D2 R' U2 R' x",
  "y' R U' R' U' R U' R' U R' D' R U R' D R2 U R'",
  "y2 R U R' U R U R' U2 R U' R2 D' R U' R' D R",
  "R U R' U R' D' R U2 R' D R2 U' R' U2 R U2 R'",
  "y' R' U2 R U R' U R' D R' U2 R D' R' U2 R'",
  "y2 x R2 D2 R U2 R' D2 R U2 R x'",
  "R F U' R' U' R U2 R' U' R F' R'",
  "F R U' R' U R U R' U R U' R' F'",
  "M' U R' U' F' U F R2 U R' U R U2 r'",
  "y2 R2 D R' U' R D' R' U' R' U R U R'",
  "y' F R U R' U' R U R' U' F' U' R' F' U' F U R",
  "y2 R' U R U R' U' R' D' R U' R' D R2",
  "y2 R' U' F' U F U' R S' R' U R S",
  "y' r U2 R2 F R F' U2 r' R U R U' R'",
  "F U R U2 R' U R U R' U R U2 R' U R U R' F'",
  "R U R' L' U2 R U' R' U' R U' R' L",
  "y' R' U2 R F U' R' U R U R' U R U' F'",
  "R U' R' U' R U R D R' U R D' R2",
  "y' r U R' U' M U R U' R' F R U R' U' F'",
  "R2 D' R U R' D R U R U' R' U' R",
  "y' R' U2 R' D' R U2 R' D R U2 R U R' U R",
  "y R2 D' R U' R' D R2 U' R' U2 R",
  "R2 D' R U2 R' U' D R' U' R2 U R U R2",
  "y2 R' U R U R' U2 R U R D R' U2 R D' R'",
  "R2 D' r U2 r' D R U2 R",
  "y2 F R U R' U' R2 D R' U' R D' R2 U' R U R' F'",
  "R' F' r U2 R' D R U' R' D' R2 U' r' F",
  "y' R' U R U' R' U' R U2 R D R' U' R D' R2 U' R",
  "R D r' U2 r D' R' U2 R' U R U R' U R",
  "F U R U' R D R' U' R D' R2 U R U R' F'",
  "R2 D' R U2 R' D R U2 R",
  "y' R2 F' R U2 R U2 R' F U' R U R' U' R",
  "y2 R' D' r U2 r' D R U2 R U' R' U' R U' R'",
  "y2 R2 D r' U2 r D' R' U2 R'",
  "y R U R' U R U' R' U R U' R' U' L' U R U' R' L",
  "y' R U R' U R U' R' U F' R U2 R' U2 R' F R",
  "y2 R2 D R' U2 R D' R' U2 R'",
  "y R U R2 D' R U R' D R2 U2 R'",
  "y' R U' R' U R U R' U2 R' D' R U R' D R2 U R'",
  "y' R U2 R D R' U2 R D' R' U2 R' U' R U' R'",
  "y' R2 D' R U' R' D R2 U R' U R U2 R' U R U2 R' U' R",
  "y' R U2 R2 D' R U2 R' D R2 U' R' U2 R U2 R'",
  "R U' R' U' R U2 R' U' R' D' R U2 R' D R",
  "R' U' R U R U R' U' R' U F R U R U' R' F'",
  "R' U' R U' R' U2 R2 U R' U R U2 R'",
  "y R' U2 R U R' U R U R' U' R U' R' U2 R",
  "R' U' R U' R U2 R2 U' R2 U' R2 U R",
  "y' R U R' U' R U' R' U2 R U' R' U2 R U R'",
  "y R U2 R' U' R U' R' U2 R' U2 R U R' U R",
  "y' R' U' R U R' U R U2 R' U R U2 R' U' R",
  "y R U2 R' U' R U' R' U' R U R' U R U2 R'",
  "y R' U2 R2 U R2 U R U' R U R' U' R U' R'",
  "y R U2 R2 U' R2 U' R' U R' U' R U R' U R",
  "R U R' U' R U' R U2 R2 U' R U R' U' R2 U' R2",
  "y2 R U R' U R' U2 R2 U R2 U R2 U' R'",
  "y2 R U R' U R U2 R2 U' R U' R' U2 R",
  "y R2 D R' U R D' R2 U' r' F R F' M'",
  "y2 R U2 R' U2 r' F R F' r R'",
  "R' U2 R' D' R U2 R' D R U' R U' R' U2 R",
  "y2 R' U' R U' R2 D' R U2 R' D R2",
  "y2 S R U R' U' R' F R S' R U R' U' F'",
  "y2 R U2 R' U' R U R' U2 R' F R U R U' R' F'",
  "R U' R' U2 R U' R2 D' R U' R' D R",
  "y R U2 R' U' F' R U R' U' R' F R2 U' R'",
  "y' R' U2 R' D' R U R' D R2 U' R' U2 R",
  "y2 R' U' R U' R2 D' r U2 r' D R2",
  "R' U' R U R' F R U R' U' R' F' R2",
  "y R U R' U' R U' R' F' R U R' U R U' R' U' R' F R",
  "y' R' D' R U2 R' D R2 U' R' U2 R U R' U R U R'",
  "y2 R' U' R U' R' U R' D' R U' R' D R U2 R",
  "y2 R' U2 F' R U R' U' R' F R2 U R' U R",
  "y2 R2 D R' U R D' R' U R' U' R U' R'",
  "y R U R2 F' U' F U R F R' F' R2 U2 R'",
  "y2 R' F U' F' U' R F U' R' U' R F'",
  "y' R2 U R2 U R U2 R' U2 R' U' D R' U R D'",
  "R' U' R U' R D' R U2 R' D R U2 R U2 R",
  "y2 R' F U2 F' R F R' U2 R F'",
  "y R' U' R U' R' U R' D' R U R' D R2",
  "y R' U' R U' R' U R' D' R U' R' r U2 r' D R2",
  "y R U2 R D R' U' R D' R' U R' U' R U' R'",
  "y' F R U R' U' R U R' F R' F' R U' F'",
  "y' R U2 R2 U' R2 F' R U R' U' R' F U' R'",
  "y' R2 U R2 F' R U R' U R U2 R' F R2 U' R2",
  "R U R' F' R U2 R' U' R U' R' F R U' R'",
  "y' R U' R2 D' U' R U' R' U2 D R2 U R'",
  "y2 F R' F' R U R U' R2 F R U R' U' F' U R",
  "y' F U' R' U R U F' R' U R U' R' U2 R",
  "y2 R' U F' R U R' U' R' F R U2 R U2 R' U' R",
  "F' U2 R' D R U' R' D' R f R' F R f'",
  "y R U' R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
  "y R' F' U' F U R F R U R' U' R U R' U' F'",
  "y2 R' F R f' U2 R U' R' U' f R' F' R",
  "y' R D R' U' R D' R2 U' R U2 R' U' R",
  "R U2 R' U' R U' R D R' U2 R D' R' U2 R'",
  "y2 f' L F L' U2 L' U2 L U2 S",
  "y2 R2 D R' U2 R D' R2 U' R U' R'",
  "R U R' F' R U R' U' R' F R2 U R' U' R U' R'",
  "R2 D' R U' R' D F R U R U' R' F' R",
  "y R U R' U R U' R2 F R F' r U' r' U r U r'",
  "y2 L' R U' L U R' U2 L' U2 L",
  "y2 R2 D R' U2 R D' R U' R2 U' R' U R' U R",
  "y F R U R2 U2 R2 U R2 U R F'",
  "y2 R2 D r' U2 r D' R2 U' R U' R'",
  "y' R' U' R U' R' F' R U R' U' R' F R U R U' R' U2 R",
  "y' R2 D' R U2 R' D R U R' F R U R U' R' F' R",
  "R' U' R2 U R2 U R2 U2 R2 U2 R",
  "R' U' R U' R' U2 R",
  "y R' U' R U R U2 R' U' R U' R' U R' U R",
  "y R U R' U' R' U' R U R U' R' U' R' U R",
  "y R U2 R' U' R U' R'",
  "R U2 R2 U2 R2 U R2 U R2 U' R'",
  "y' R' U' R U' R U R2 U R U' R U R' U' R U' R'",
  "y R2 U R2 U R' U2 R' U R U R' U' R2",
  "y R' U' R U R U2 R' U' R' U R U' R U' R'",
  "y2 R U R' U R' U' R U' R' U2 R U R U' R'",
  "y2 R U R' U R' U' R2 U' R2 U2 R",
  "y' R' U2 R U R2 D' R U' R' D R2 U R' U' R U R' U R",
  "y R D' U R U' R' U2 D R2 U' R U R",
  "R2 D' R U2 R' D R U R U' R' U2 R",
  "y2 R' U2 R' F' R U R U' R' F U2 R",
  "y2 D R' U' R D' R U' R' U R2 U R' U' R2",
  "y2 F U R U' R' U R U' R2 F' R U2 R U2 R'",
  "y2 F R U' R' U R U R2 F' R U R U R' U' R U' R'",
  "y2 R' U2 R' D' R U R' D R U' R U R' U' R U R' U R",
  "y' R U R U' R2 D U2 R' U' R U D' R",
  "y2 R' U R U R' U' R' D' R U R' D R U R U' R' U2 R",
  "y' R U2 R' U' R U R D R' U2 R D' R2",
  "y2 r' F R F' r U R'",
] as const;
