'use client';

import { useState, useMemo, useCallback } from 'react';
import { GTSec, L, TeX, TeXBlock, useLang } from '../primitives';
import type { Lang } from '../primitives';
import i18n from '@/i18n/i18n-client';

// ── Mathematical constants ────────────────────────────────────────────────────

// The 5 conjugacy classes of the cube rotation group acting on FACES (6 faces)
// Each class: { size, cycles, cycleType, nameZh, nameEn }
interface RotClass {
  size: number;
  cycles: number;
  cycleType: string;
  nameZh: string;
  nameEn: string;
    nameZhHant?: string;
}

const FACE_CLASSES: RotClass[] = [
  { size: 1, cycles: 6, cycleType: '1⁶',     nameZh: '恒等',         nameEn: 'Identity',
      nameZhHant: "恆等"
},
  { size: 6, cycles: 3, cycleType: '1² 4¹',  nameZh: '面轴 90°/270°', nameEn: 'Face 90°/270°',
      nameZhHant: "面軸 90°/270°"
},
  { size: 3, cycles: 4, cycleType: '1² 2²',  nameZh: '面轴 180°',    nameEn: 'Face 180°',
      nameZhHant: "面軸 180°"
},
  { size: 8, cycles: 2, cycleType: '3²',      nameZh: '顶点轴 120°/240°', nameEn: 'Vertex 120°/240°',
      nameZhHant: "頂點軸 120°/240°"
},
  { size: 6, cycles: 3, cycleType: '2³',      nameZh: '棱轴 180°',   nameEn: 'Edge 180°',
      nameZhHant: "稜軸 180°"
},
];

// Acting on EDGES (12 edges)
const EDGE_CLASSES: RotClass[] = [
  { size: 1, cycles: 12, cycleType: '1¹²',    nameZh: '恒等',         nameEn: 'Identity',
      nameZhHant: "恆等"
},
  { size: 6, cycles: 3,  cycleType: '4³',      nameZh: '面轴 90°/270°', nameEn: 'Face 90°/270°',
      nameZhHant: "面軸 90°/270°"
},
  { size: 3, cycles: 6,  cycleType: '2⁶',      nameZh: '面轴 180°',    nameEn: 'Face 180°',
      nameZhHant: "面軸 180°"
},
  { size: 8, cycles: 4,  cycleType: '3⁴',      nameZh: '顶点轴 120°/240°', nameEn: 'Vertex 120°/240°',
      nameZhHant: "頂點軸 120°/240°"
},
  { size: 6, cycles: 7,  cycleType: '1² 2⁵',  nameZh: '棱轴 180°',   nameEn: 'Edge 180°',
      nameZhHant: "稜軸 180°"
},
];

// Acting on VERTICES (8 vertices)
const VERTEX_CLASSES: RotClass[] = [
  { size: 1, cycles: 8, cycleType: '1⁸',      nameZh: '恒等',         nameEn: 'Identity',
      nameZhHant: "恆等"
},
  { size: 6, cycles: 2, cycleType: '4²',       nameZh: '面轴 90°/270°', nameEn: 'Face 90°/270°',
      nameZhHant: "面軸 90°/270°"
},
  { size: 3, cycles: 4, cycleType: '2⁴',       nameZh: '面轴 180°',    nameEn: 'Face 180°',
      nameZhHant: "面軸 180°"
},
  { size: 8, cycles: 4, cycleType: '1² 3²',   nameZh: '顶点轴 120°/240°', nameEn: 'Vertex 120°/240°',
      nameZhHant: "頂點軸 120°/240°"
},
  { size: 6, cycles: 4, cycleType: '2⁴',       nameZh: '棱轴 180°',   nameEn: 'Edge 180°',
      nameZhHant: "稜軸 180°"
},
];

type ObjectMode = 'faces' | 'edges' | 'vertices';

const CLASSES_BY_MODE: Record<ObjectMode, RotClass[]> = {
  faces: FACE_CLASSES,
  edges: EDGE_CLASSES,
  vertices: VERTEX_CLASSES,
};

// Closed-form formulas (verified against the per-class Burnside sums)
// N(k) = (k^6 + 3k^4 + 12k^3 + 8k^2)/24
function faceFormula(k: number): number {
  return (Math.pow(k, 6) + 3 * Math.pow(k, 4) + 12 * Math.pow(k, 3) + 8 * Math.pow(k, 2)) / 24;
}
// E(k) = (k^12 + 6k^7 + 3k^6 + 8k^4 + 6k^3)/24
function edgeFormula(k: number): number {
  return (Math.pow(k, 12) + 6 * Math.pow(k, 7) + 3 * Math.pow(k, 6) + 8 * Math.pow(k, 4) + 6 * Math.pow(k, 3)) / 24;
}
// V(k) = (k^8 + 17k^4 + 6k^2)/24
function vertexFormula(k: number): number {
  return (Math.pow(k, 8) + 17 * Math.pow(k, 4) + 6 * Math.pow(k, 2)) / 24;
}

// The 24 face permutations (indices 0..5 = +x,-x,+y,-y,+z,-z = R,L,U,D,F,B)
// Generated by standard 90° face turns: Rx, Ry, Rz and their inverses
// Encoded as length-6 arrays: perm[i] = which old face goes to position i
function buildFacePerms(): number[][] {
  // Face index: 0=R(+x), 1=L(-x), 2=U(+y), 3=D(-y), 4=F(+z), 5=B(-z)
  // Rx (90° CW around +x axis): y->z, z->-y  =>  U->F, F->D, D->B, B->U; R,L fixed
  const rx = [0, 1, 5, 4, 2, 3];
  // Ry (90° CW around +y axis): z->x, x->-z  =>  F->R, R->B, B->L, L->F; U,D fixed
  const ry = [4, 5, 2, 3, 1, 0];
  // Rz (90° CW around +z axis): x->y, y->-x  =>  R->U, U->L, L->D, D->R; F,B fixed
  const rz = [3, 2, 0, 1, 4, 5];

  function compose(a: number[], b: number[]): number[] {
    return a.map((_, i) => b[a[i]]);
  }
  function pow3(m: number[]): number[] { return compose(compose(m, m), m); }

  const id = [0, 1, 2, 3, 4, 5];
  const gens = [rx, ry, rz, pow3(rx), pow3(ry), pow3(rz)];

  const perms: number[][] = [id];
  const seen = new Set<string>();
  seen.add(id.join(','));

  let frontier = [id];
  while (frontier.length > 0) {
    const next: number[][] = [];
    for (const p of frontier) {
      for (const g of gens) {
        const np = compose(p, g);
        const key = np.join(',');
        if (!seen.has(key)) {
          seen.add(key);
          perms.push(np);
          next.push(np);
        }
      }
    }
    frontier = next;
  }
  return perms.slice(0, 24);
}

const FACE_PERMS: number[][] = buildFacePerms();

function applyPerm(perm: number[], colors: number[]): number[] {
  return perm.map(i => colors[i]);
}

function orbitOf(colors: number[]): string[] {
  const seen = new Set<string>();
  for (const p of FACE_PERMS) {
    seen.add(applyPerm(p, colors).join(','));
  }
  return Array.from(seen);
}

// Categorical color palette
const PALETTE = ['#8B2E3C', '#2A4D69', '#3F7050', '#B8860B', '#6B4E9C', '#C2410C', '#5C7CA0', '#9C4E6B'];

// Face colors for the cube colouring playground (max 8 colours)
const FACE_COLOR_SWATCHES = [
  '#E74C3C', '#3498DB', '#2ECC71', '#F1C40F', '#FF6B35', '#FFFFFF',
  '#9B59B6', '#1ABC9C',
];
const SWATCH_LABELS_ZH = ['红', '蓝', '绿', '黄', '橙', '白', '紫', '青'];
const SWATCH_LABELS_EN = ['Red', 'Blue', 'Green', 'Yellow', 'Orange', 'White', 'Purple', 'Cyan'];

// Cube net layout: cross shape. Face order: 0=R, 1=L, 2=U, 3=D, 4=F, 5=B
// Net positions (col, row) in a standard cross:
//      [U]
// [L] [F] [R] [B]
//      [D]
const NET_POSITIONS: { face: number; col: number; row: number; labelZh: string; labelEn: string
    labelZhHant?: string;
 }[] = [
  { face: 2, col: 1, row: 0, labelZh: '上', labelEn: 'U' },
  { face: 1, col: 0, row: 1, labelZh: '左', labelEn: 'L' },
  { face: 4, col: 1, row: 1, labelZh: '前', labelEn: 'F' },
  { face: 0, col: 2, row: 1, labelZh: '右', labelEn: 'R' },
  { face: 5, col: 3, row: 1, labelZh: '后', labelEn: 'B',
      labelZhHant: "後"
},
  { face: 3, col: 1, row: 2, labelZh: '下', labelEn: 'D' },
];

// ── Main component ─────────────────────────────────────────────────────────────

export default function PolyaCubeColorings() {
  const lang = useLang();

  return (
    <GTSec id="polya-cube-colorings" className="gt-sec">
      <div className="gt-sec-num">§48</div>
      <h2 className="gt-sec-title">
        <L zh="Burnside–Pólya 数立方体染色" en="Counting cube colourings (Burnside-Polya)" />
      </h2>

      <p className="gt-lede">
        <L
          zh={<>
            用 <TeX src={String.raw`k`} /> 种颜色给正方体 6 个面染色，旋转等价的方案算同一种，究竟有多少种不等价的染色？
            对 <TeX src={String.raw`k=2`} /> 答案是 10，对 <TeX src={String.raw`k=6`} /> 是 2226——而若要求 6 种颜色各用一次（双射），则只有 30 种（<TeX src={String.raw`6!/24`} />）。
            这一计数的核心工具是 <strong>Burnside 引理</strong>（历史上实为 Cauchy 和 Frobenius 的定理）与 <strong>Pólya 枚举定理</strong>：对每个旋转 <TeX src={String.raw`g`} />，统计它在 6 个面上的置换圈数 <TeX src={String.raw`c(g)`} />，则不等价染色数恰等于 <TeX src={String.raw`\frac{1}{24}\sum_{g\in G}k^{c(g)}`} />。
          </>}
          en={<>
            How many distinct ways can you colour the 6 faces of a cube with <TeX src={String.raw`k`} /> colours, counting rotations as equivalent? For <TeX src={String.raw`k=2`} /> the answer is 10; for <TeX src={String.raw`k=6`} /> it is 2226 — but if every colour must appear exactly once (a bijection), only 30 arrangements are distinct (<TeX src={String.raw`6!/24`} />). The counting engine is <strong>Burnside's lemma</strong> (due in substance to Cauchy and Frobenius) and the <strong>Pólya Enumeration Theorem</strong>: for each rotation <TeX src={String.raw`g`} />, let <TeX src={String.raw`c(g)`} /> be the number of disjoint cycles of <TeX src={String.raw`g`} /> acting on the 6 faces; then the number of inequivalent colourings is exactly <TeX src={String.raw`\frac{1}{24}\sum_{g\in G}k^{c(g)}`} />.
          </>}
        />
      </p>

      {/* ── Definition: Group action on colourings ── */}
      <div className="gt-def">
        <div className="gt-def-title">
          <L zh="定义: 群在着色集上的作用、轨道与不动点集" en="Definitions: group action on colourings, orbits, and fixed-point sets" />
        </div>
        <div className="gt-def-body">
          <L
            zh={<>
              设 <TeX src={String.raw`G`} /> 为有限群，<TeX src={String.raw`X`} /> 为有限集（此处 <TeX src={String.raw`X=\{1,\ldots,6\}`} /> 为正方体的 6 个面）。<TeX src={String.raw`G`} /> 在 <TeX src={String.raw`X`} /> 上的<strong>群作用</strong>是满足 <TeX src={String.raw`e\cdot x=x`} /> 和 <TeX src={String.raw`g\cdot(h\cdot x)=(gh)\cdot x`} /> 的映射 <TeX src={String.raw`G\times X\to X`} />。正方体的旋转群 <TeX src={String.raw`G\cong S_4`} />（阶 24）以物理旋转正方体的方式作用于 6 个面。
              <br /><br />
              设 <TeX src={String.raw`\mathcal{C}=\{1,\ldots,k\}^X`} /> 为所有 <TeX src={String.raw`k`} />-着色的集合（共 <TeX src={String.raw`k^6`} /> 个）。<TeX src={String.raw`G`} /> 自然地作用在 <TeX src={String.raw`\mathcal{C}`} /> 上：<TeX src={String.raw`(g\cdot c)(x)=c(g^{-1}\cdot x)`} />（先转后看）。
              两个着色<strong>旋转等价</strong>当且仅当属于同一<strong>轨道</strong>。
              对 <TeX src={String.raw`g\in G`} />，其<strong>不动点集</strong>为 <TeX src={String.raw`\mathrm{Fix}(g)=\{c\in\mathcal{C}:g\cdot c=c\}`} />，
              即在 <TeX src={String.raw`g`} /> 的每个面-置换圈上颜色相同的着色；故 <TeX src={String.raw`|\mathrm{Fix}(g)|=k^{c(g)}`} />，
              其中 <TeX src={String.raw`c(g)`} /> 是 <TeX src={String.raw`g`} /> 在 6 个面上的置换圈数（含长度为 1 的固定点圈）。
            </>}
            en={<>
              Let <TeX src={String.raw`G`} /> be a finite group and <TeX src={String.raw`X`} /> a finite set (here <TeX src={String.raw`X=\{1,\ldots,6\}`} />, the 6 faces of the cube). A <strong>group action</strong> of <TeX src={String.raw`G`} /> on <TeX src={String.raw`X`} /> is a map <TeX src={String.raw`G\times X\to X`} /> satisfying <TeX src={String.raw`e\cdot x=x`} /> and <TeX src={String.raw`g\cdot(h\cdot x)=(gh)\cdot x`} />. The rotation group <TeX src={String.raw`G\cong S_4`} /> (order 24) acts by physically rotating the cube.
              <br /><br />
              Let <TeX src={String.raw`\mathcal{C}=\{1,\ldots,k\}^X`} /> be the set of all <TeX src={String.raw`k`} />-colourings (<TeX src={String.raw`k^6`} /> in total). <TeX src={String.raw`G`} /> acts on <TeX src={String.raw`\mathcal{C}`} /> by <TeX src={String.raw`(g\cdot c)(x)=c(g^{-1}\cdot x)`} />. Two colourings are <strong>rotationally equivalent</strong> iff they lie in the same <strong>orbit</strong>. For <TeX src={String.raw`g\in G`} />, the <strong>fixed-point set</strong> is <TeX src={String.raw`\mathrm{Fix}(g)=\{c\in\mathcal{C}:g\cdot c=c\}`} />, those colourings constant on each cycle of <TeX src={String.raw`g`} /> acting on faces; hence <TeX src={String.raw`|\mathrm{Fix}(g)|=k^{c(g)}`} /> where <TeX src={String.raw`c(g)`} /> counts the disjoint cycles of <TeX src={String.raw`g`} /> on the 6 faces (fixed points count as 1-cycles).
            </>}
          />
        </div>
      </div>

      {/* ── Burnside's lemma theorem box ── */}
      <div className="gt-thm">
        <div className="gt-thm-title">
          <L zh="定理 (Cauchy–Frobenius / Burnside 引理)" en="Theorem (Cauchy–Frobenius / Burnside's Lemma)" />
        </div>
        <div className="gt-thm-body">
          <L
            zh={<>
              设有限群 <TeX src={String.raw`G`} /> 作用于有限集 <TeX src={String.raw`\mathcal{C}`} />，则轨道数为：
            </>}
            en={<>
              Let a finite group <TeX src={String.raw`G`} /> act on a finite set <TeX src={String.raw`\mathcal{C}`} />. The number of orbits is:
            </>}
          />
          <TeXBlock src={String.raw`|\mathcal{C}/G| = \frac{1}{|G|}\sum_{g\in G}|\mathrm{Fix}(g)|.`} />
          <L
            zh={<>
              <em>历史注：</em>此结论由 Cauchy（1845）和 Frobenius（1887）各自独立给出；Burnside 1897 年在教材中转述，本人也承认并非己作。
              严格来说应称 <em>Cauchy–Frobenius 引理</em>，但"Burnside 引理"之名已约定俗成。
              <br />
              <em>应用：</em>令 <TeX src={String.raw`\mathcal{C}`} /> 为正方体 6 个面的全部 <TeX src={String.raw`k`} />-着色，<TeX src={String.raw`|\mathrm{Fix}(g)|=k^{c(g)}`} />，得不等价着色数：
            </>}
            en={<>
              <em>Historical note:</em> this result is due to Cauchy (1845) and Frobenius (1887) independently; Burnside (1897) merely cited it and acknowledged he was not the originator. Strictly it should be called the <em>Cauchy–Frobenius lemma</em>, but "Burnside's lemma" is now conventional.
              <br />
              <em>Application:</em> taking <TeX src={String.raw`\mathcal{C}`} /> to be all <TeX src={String.raw`k`} />-colourings of the 6 faces, with <TeX src={String.raw`|\mathrm{Fix}(g)|=k^{c(g)}`} />, gives:
            </>}
          />
          <TeXBlock src={String.raw`N(k) = \frac{1}{24}\!\sum_{g\in G}k^{c(g)} = \frac{k^6+3k^4+12k^3+8k^2}{24}.`} />
        </div>
      </div>

      {/* ── Cycle index box ── */}
      <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
        <L zh="正方体的置换圈指标" en="The cycle index of the cube rotation group" />
      </h3>

      <p>
        <L
          zh={<>
            正方体旋转群 <TeX src={String.raw`G\cong S_4`} /> 有 5 个共轭类，共 <TeX src={String.raw`1+6+3+8+6=24`} /> 个元素。
            同一共轭类中的旋转在 6 个面上诱导相同的圈型，故 <TeX src={String.raw`c(g)`} /> 在每个共轭类上为常数。
            以 <TeX src={String.raw`x_i`} /> 记长度为 <TeX src={String.raw`i`} /> 的圈，<strong>圈指标</strong>（cycle index）为：
          </>}
          en={<>
            The rotation group <TeX src={String.raw`G\cong S_4`} /> has 5 conjugacy classes, totalling <TeX src={String.raw`1+6+3+8+6=24`} /> elements.
            Conjugate rotations induce the same cycle type on the 6 faces, so <TeX src={String.raw`c(g)`} /> is constant on each conjugacy class.
            Writing <TeX src={String.raw`x_i`} /> for cycles of length <TeX src={String.raw`i`} />, the <strong>cycle index</strong> is:
          </>}
        />
        <TeXBlock src={String.raw`Z(G;\,x_1,\ldots,x_6) = \frac{1}{24}\!\left(x_1^6 + 6\,x_1^2 x_4 + 3\,x_1^2 x_2^2 + 8\,x_3^2 + 6\,x_2^3\right).`} />
        <L
          zh={<>
            Pólya 枚举定理（计数形式）：令所有 <TeX src={String.raw`x_i=k`} />，即得不等价 <TeX src={String.raw`k`} />-着色数
            <TeX src={String.raw`N(k)=Z(G;k,\ldots,k)`} />，与上述 Burnside 求和完全一致。
            <br />
            <strong>注意：</strong>这里使用的是阶 24 的<em>纯旋转</em>群，不含反射（含反射为阶 48 的 <TeX src={String.raw`O_h`} />）。使用 <TeX src={String.raw`|G|=48`} /> 会得到不同（更小）的计数，因为镜像染色将被视为等价。
          </>}
          en={<>
            The Pólya Enumeration Theorem (counting form) says: substituting all <TeX src={String.raw`x_i=k`} /> gives <TeX src={String.raw`N(k)=Z(G;k,\ldots,k)`} />, exactly matching the Burnside sum.
            <br />
            <strong>Note:</strong> we use the <em>proper rotation</em> group of order 24, excluding reflections (the full group <TeX src={String.raw`O_h`} /> has order 48). Using <TeX src={String.raw`|G|=48`} /> gives a different, smaller count because mirror-image colourings become equivalent.
          </>}
        />
      </p>

      {/* ── Panel 1: Burnside class breakdown bar ── */}
      <BurnsideBreakdownPanel lang={lang} />

      {/* ── Cube connection callout ── */}
      <div className="gt-pullquote" style={{ marginTop: 40 }}>
        <L
          zh={<>
            <strong>与魔方的联系。</strong>
            这里的 24 个旋转恰好是魔方求解者所说的"整体旋转"（x、y、z 系的轮换）——把魔方视为刚体在空间中的 24 种定向。
            它们通过在 4 条体对角线上的作用同构于 <TeX src={String.raw`S_4`} />。
            特别地，"<TeX src={String.raw`k=6`} /> 色各用一次，共 30 种"精确对应标准配色（白对黄、绿对蓝、红对橙）的 30 种放置方式——其中两种互为镜像（左右手手性），对应现实中魔方有左右手两种版本。
            <strong>但切勿混淆：</strong>魔方的状态空间（约 <TeX src={String.raw`4.3\times10^{19}`} />）是关于角块和棱块的置换+朝向的计数，与面染色毫无关联。
          </>}
          en={<>
            <strong>Connection to the Rubik's cube.</strong>
            The 24 rotations used here are exactly what speedcubers call "whole-cube rotations" (the x, y, z reorientations) — the 24 ways to hold the cube as a rigid solid. They act faithfully on the 4 body diagonals and are isomorphic to <TeX src={String.raw`S_4`} />. In particular, the "<TeX src={String.raw`k=6`} /> distinct colours, 30 arrangements" count corresponds to the 30 ways to assign the 6 standard colours (white/yellow opposite, green/blue opposite, red/orange opposite) to the faces — 2 of which are mirror images of each other, matching the real-world fact that cubes come in two chiral colour schemes. <strong>Do not conflate this</strong> with the Rubik's cube state space (~<TeX src={String.raw`4.3\times10^{19}`} />), which counts cubie permutations and orientations — a completely different computation.
          </>}
        />
        <div className="gt-pullquote-cite">OEIS A047780; Armstrong, <em>Groups and Symmetry</em></div>
      </div>

      {/* ── Panel 2: Cube net colouring playground ── */}
      <CubeNetPanel lang={lang} />

      {/* ── Distinct vs repeated comparison ── */}
      <DistinctVsRepeatedPanel lang={lang} />

      {/* ── Cycle index inspector ── */}
      <CycleIndexPanel lang={lang} />

      {/* ── Known values table ── */}
      <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
        <L zh="各 k 值的染色数" en="Colouring counts for small k" />
      </h3>

      <div style={{ overflowX: 'auto' }}>
        <table className="gt-compare" style={{ minWidth: 340 }}>
          <thead>
            <tr>
              <th>k</th>
              <th><L zh="面 (6 面)" en="Faces (6)" /></th>
              <th><L zh="棱 (12 棱)" en="Edges (12)" /></th>
              <th><L zh="顶点 (8 点)" en="Vertices (8)" /></th>
            </tr>
          </thead>
          <tbody>
            {[1, 2, 3, 4, 5, 6, 7, 8].map(k => (
              <tr key={k}>
                <td style={{ fontFamily: 'var(--mono)', textAlign: 'center' }}>{k}</td>
                <td style={{ textAlign: 'center', fontVariantNumeric: 'tabular-nums' }}>
                  {faceFormula(k).toLocaleString()}
                </td>
                <td style={{ textAlign: 'center', fontVariantNumeric: 'tabular-nums' }}>
                  {edgeFormula(k).toLocaleString()}
                </td>
                <td style={{ textAlign: 'center', fontVariantNumeric: 'tabular-nums' }}>
                  {vertexFormula(k).toLocaleString()}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p style={{ fontSize: 14, color: 'var(--ink-dim)', marginTop: 10 }}>
        <L
          zh={<>OEIS: 面 → <a href="https://oeis.org/A047780" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent-2)' }}>A047780</a>；棱 → A060530；顶点 → A000543。</>}
          en={<>OEIS: faces → <a href="https://oeis.org/A047780" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent-2)' }}>A047780</a>; edges → A060530; vertices → A000543.</>}
        />
      </p>

      {/* ── Common pitfalls ── */}
      <div className="gt-aside" style={{ marginTop: 36 }}>
        <L
          zh={<>
            <strong>常见误区。</strong>
            (1) <strong>固定点 vs 圈数：</strong><TeX src={String.raw`|\mathrm{Fix}(g)|=k^{c(g)}`} /> 中，<TeX src={String.raw`c(g)`} /> 是 <TeX src={String.raw`g`} /> 在 6 个面上的<em>置换圈数</em>（含不动面的 1-圈），而非不动面的数量。面轴 180° 的圈型为 <TeX src={String.raw`1^22^2`} />，故 <TeX src={String.raw`c=4`} />，而非 2。
            (2) <strong>30 vs 2226：</strong>"6 色各用一次"的 30 是射影（双射）数，<TeX src={String.raw`N(6)=2226`} /> 是允许重色的计数，两者针对不同问题，不可混用。
            (3) <strong>阶 24 vs 48：</strong>若把镜像视为等价（用 <TeX src={String.raw`O_h`} />，阶 48），计数一般更小（如 <TeX src={String.raw`k=3`} /> 从 57 降为 56，<TeX src={String.raw`k=6`} /> 从 2226 降为 1771；但 <TeX src={String.raw`k=2`} /> 恰好两者都是 10）。
            (4) <strong>面染色 vs 魔方状态：</strong>两者算法完全不同，不要混淆。
          </>}
          en={<>
            <strong>Common pitfalls.</strong>
            (1) <strong>Fixed faces vs cycle count:</strong> in <TeX src={String.raw`|\mathrm{Fix}(g)|=k^{c(g)}`} />, <TeX src={String.raw`c(g)`} /> is the number of <em>disjoint cycles</em> of <TeX src={String.raw`g`} /> on the 6 faces (fixed points count as 1-cycles), not the number of fixed faces. Face 180° has cycle type <TeX src={String.raw`1^22^2`} />, so <TeX src={String.raw`c=4`} />, not 2.
            (2) <strong>30 vs 2226:</strong> the 30 "all-6-distinct" colourings are bijective assignments; <TeX src={String.raw`N(6)=2226`} /> counts unrestricted <TeX src={String.raw`k=6`} /> colourings. Different questions.
            (3) <strong>Order 24 vs 48:</strong> using <TeX src={String.raw`O_h`} /> (order 48, including reflections) generally gives smaller counts (e.g., <TeX src={String.raw`k=3`} /> drops from 57 to 56 and <TeX src={String.raw`k=6`} /> from 2226 to 1771; but for <TeX src={String.raw`k=2`} /> both equal 10).
            (4) <strong>Face colourings vs Rubik's cube states:</strong> entirely different computations — do not conflate them.
          </>}
        />
      </div>

      {/* ── References ── */}
      <div style={{ marginTop: 40 }}>
        <div className="gt-def-title" style={{ marginBottom: 10 }}>
          <L zh="参考文献" en="References" />
        </div>
        <ol style={{ fontSize: 14, lineHeight: 1.8, color: 'var(--ink-dim)' }}>
          <li>OEIS A047780, "Number of inequivalent ways to color faces of a cube using at most n colors." (Gives the exact cycle index and closed form.)</li>
          <li>M. A. Armstrong, <em>Groups and Symmetry</em>, Springer UTM (1988), Ch. 18 (Burnside's Counting Theorem) and the cube/octahedron worked examples.</li>
          <li>N. G. de Bruijn, "Pólya's theory of counting," in <em>Applied Combinatorial Mathematics</em>, Wiley (1964), pp. 144–184.</li>
          <li>P. M. Neumann, "A lemma that is not Burnside's," <em>Math. Scientist</em> 4 (1979), pp. 133–141. (Historical correction on attribution.)</li>
        </ol>
      </div>
    </GTSec>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// Panel 1: Burnside class breakdown — bar chart + mode selector
// ══════════════════════════════════════════════════════════════════════════════

function BurnsideBreakdownPanel({ lang }: { lang: Lang }) {
  const [k, setK] = useState(2);
  const [mode, setMode] = useState<ObjectMode>('faces');
  const [hoveredClass, setHoveredClass] = useState<number | null>(null);

  const classes = CLASSES_BY_MODE[mode];

  const { terms, total, answer } = useMemo(() => {
    const terms = classes.map(c => c.size * Math.pow(k, c.cycles));
    const total = terms.reduce((a, b) => a + b, 0);
    const answer = total / 24;
    return { terms, total, answer };
  }, [k, classes]);

  const isInt = Number.isInteger(answer);
  const maxTerm = Math.max(...terms, 1);

  const BAR_MAX = 260;
  const BAR_H = 28;
  const ROW_GAP = 8;
  const SVG_H = classes.length * (BAR_H + ROW_GAP) + 60;
  const LEFT = 140;

  const modeLabels: { id: ObjectMode; zh: string; en: string
      zhHant?: string;
 }[] = [
    { id: 'faces',    zh: '面 (6)',   en: 'Faces (6)'    },
    { id: 'edges',    zh: '棱 (12)',  en: 'Edges (12)',
        zhHant: "稜 (12)"
    },
    { id: 'vertices', zh: '顶点 (8)', en: 'Vertices (8)',
        zhHant: "頂點 (8)"
    },
  ];

  return (
    <div className="gt-panel" style={{ marginTop: 36 }}>
      <div className="gt-panel-title">
        <L zh="Burnside 逐类分解" en="Burnside class-by-class breakdown" />
      </div>
      <div className="gt-panel-sub">
        <L
          zh="每个共轭类对 Burnside 总和的贡献 = 类的大小 × k^{圈数}。拖动 k 或切换染色对象实时更新。"
          en="Each conjugacy class contributes (class size) × k^(cycles) to the Burnside sum. Drag k or switch the coloured object to update live."
        />
      </div>

      <div className="gt-panel-input-row" style={{ flexWrap: 'wrap', gap: 8, alignItems: 'center' }}>
        <label style={{ fontFamily: 'var(--mono)', fontSize: 13 }}>
          <L zh="颜色数 k" en="Colours k" />
        </label>
        <input
          type="range" min={1} max={8} value={k}
          onChange={e => setK(+e.target.value)}
          style={{ flex: '1 1 120px' }}
          className="gt-input"
        />
        <span style={{ fontFamily: 'var(--mono)', fontWeight: 700, color: 'var(--accent)', minWidth: 20 }}>{k}</span>
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          {modeLabels.map(m => (
            <button
              key={m.id}
              className={`gt-chip${mode === m.id ? ' gt-chip-active' : ''}`}
              onClick={() => setMode(m.id)}
            >
              {(i18n.language === 'zh-Hant' ? (m.zhHant ?? m.zh) : (i18n.language.startsWith('zh') ? m.zh : m.en))}
            </button>
          ))}
        </div>
      </div>

      <div style={{ overflowX: 'auto', marginTop: 16 }}>
        <svg viewBox={`0 0 ${LEFT + BAR_MAX + 80} ${SVG_H}`} width="100%" style={{ display: 'block' }}>
          {classes.map((cls, ri) => {
            const y = ri * (BAR_H + ROW_GAP);
            const term = terms[ri];
            const barW = term <= 0 ? 0 : Math.max(2, (term / maxTerm) * BAR_MAX);
            const col = PALETTE[ri % PALETTE.length];
            const isHov = hoveredClass === ri;

            return (
              <g
                key={ri}
                style={{ cursor: 'default' }}
                onMouseEnter={() => setHoveredClass(ri)}
                onMouseLeave={() => setHoveredClass(null)}
              >
                {/* Row label */}
                <text
                  x={LEFT - 6} y={y + BAR_H / 2 + 4}
                  textAnchor="end"
                  style={{ fontFamily: 'var(--mono)', fontSize: 10 }}
                  fill={isHov ? col : 'var(--ink-dim)'}
                >
                  {lang === 'zh' ? cls.nameZh : cls.nameEn}
                </text>
                {/* Cycle type badge */}
                <text
                  x={LEFT - 6} y={y + BAR_H / 2 + 4 - 11}
                  textAnchor="end"
                  style={{ fontFamily: 'var(--mono)', fontSize: 8 }}
                  fill="var(--ink-faint)"
                >
                  {cls.cycleType}
                </text>
                {/* Bar background */}
                <rect
                  x={LEFT} y={y} width={BAR_MAX} height={BAR_H} rx={3}
                  fill="var(--bg-elev)" stroke="var(--rule)" strokeWidth={0.5}
                />
                {/* Bar fill */}
                <rect
                  x={LEFT} y={y} width={barW} height={BAR_H} rx={3}
                  fill={col} fillOpacity={isHov ? 0.85 : 0.55}
                />
                {/* Value label */}
                <text
                  x={LEFT + barW + 5} y={y + BAR_H / 2 + 4}
                  style={{ fontFamily: 'var(--mono)', fontSize: 11, fontWeight: isHov ? 700 : 400 }}
                  fill={isHov ? col : 'var(--ink)'}
                >
                  {cls.size}×{k}^{cls.cycles}={term}
                </text>
              </g>
            );
          })}

          {/* Divider + total */}
          {(() => {
            const y = classes.length * (BAR_H + ROW_GAP) + 4;
            return (
              <g>
                <line x1={LEFT} y1={y} x2={LEFT + BAR_MAX} y2={y} stroke="var(--rule)" strokeWidth={1} />
                <text x={LEFT - 6} y={y + 22} textAnchor="end"
                  style={{ fontFamily: 'var(--mono)', fontSize: 11, fontWeight: 700 }}
                  fill="var(--ink)">
                  <L zh="总和 / 24 =" en="Sum / 24 =" />
                </text>
                <text x={LEFT + 8} y={y + 22}
                  style={{ fontFamily: 'var(--mono)', fontSize: 14, fontWeight: 700 }}
                  fill={isInt ? 'var(--green)' : 'var(--warn)'}>
                  {total} / 24 = {answer} {isInt ? '✓' : '(非整数!)'}
                </text>
              </g>
            );
          })()}
        </svg>
      </div>

      {hoveredClass !== null && (
        <div className="gt-aside" style={{ marginTop: 8, fontSize: 13 }}>
          <L
            zh={<>
              <strong>{classes[hoveredClass].nameZh}</strong>（共 {classes[hoveredClass].size} 个旋转，圈型 {classes[hoveredClass].cycleType}，{classes[hoveredClass].cycles} 圈）：
              每个旋转令 {k}<sup>{classes[hoveredClass].cycles}</sup> = {Math.pow(k, classes[hoveredClass].cycles)} 个着色不动；
              该类贡献 {classes[hoveredClass].size} × {Math.pow(k, classes[hoveredClass].cycles)} = <strong>{terms[hoveredClass]}</strong>。
            </>}
            en={<>
              <strong>{classes[hoveredClass].nameEn}</strong> ({classes[hoveredClass].size} rotations, cycle type {classes[hoveredClass].cycleType}, {classes[hoveredClass].cycles} cycles):
              each such rotation fixes {k}<sup>{classes[hoveredClass].cycles}</sup> = {Math.pow(k, classes[hoveredClass].cycles)} colourings;
              this class contributes {classes[hoveredClass].size} × {Math.pow(k, classes[hoveredClass].cycles)} = <strong>{terms[hoveredClass]}</strong>.
            </>}
          />
        </div>
      )}

      <div className="gt-panel-result" style={{ marginTop: 12 }}>
        <div className="gt-result-row">
          <span className="gt-result-label">
            {mode === 'faces' ? <L zh="面染色数 N(k)" en="Face colourings N(k)" /> :
             mode === 'edges' ? <L zh="棱染色数 E(k)" en="Edge colourings E(k)" /> :
                                <L zh="顶点染色数 V(k)" en="Vertex colourings V(k)" />}
          </span>
          <span className="gt-result-val-strong" style={{ color: isInt ? 'var(--green)' : 'var(--warn)', fontSize: 20 }}>
            {isInt ? answer.toLocaleString() : '?'}
          </span>
        </div>
        {mode === 'faces' && k === 2 && (
          <div className="gt-result-row">
            <span className="gt-result-label"><L zh="经典验证 k=2" en="Classic check k=2" /></span>
            <span className="gt-result-val" style={{ color: answer === 10 ? 'var(--green)' : 'var(--warn)' }}>
              {answer === 10 ? '= 10 ✓' : `≠ 10`}
            </span>
          </div>
        )}
        {mode === 'faces' && k === 3 && (
          <div className="gt-result-row">
            <span className="gt-result-label"><L zh="经典验证 k=3" en="Classic check k=3" /></span>
            <span className="gt-result-val" style={{ color: answer === 57 ? 'var(--green)' : 'var(--warn)' }}>
              {answer === 57 ? '= 57 ✓' : `≠ 57`}
            </span>
          </div>
        )}
      </div>
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// Panel 2: Cube net colouring playground — click faces, show orbit
// ══════════════════════════════════════════════════════════════════════════════

function CubeNetPanel({ lang }: { lang: Lang }) {
  const [k, setK] = useState(2);
  // colors[i] = colour index (0..k-1) for face i (0=R,1=L,2=U,3=D,4=F,5=B)
  const [colors, setColors] = useState<number[]>([0, 1, 0, 1, 0, 1]);
  const [showOrbit, setShowOrbit] = useState(false);

  const CELL = 52;

  const orbit = useMemo(() => orbitOf(colors), [colors]);
  const orbitSize = orbit.length;
  const stabSize = 24 / orbitSize;

  const handleFaceClick = useCallback((face: number) => {
    setColors(prev => {
      const next = [...prev];
      next[face] = (next[face] + 1) % k;
      return next;
    });
  }, [k]);

  const handleKChange = useCallback((newK: number) => {
    setK(newK);
    setColors(prev => prev.map(c => c % newK));
  }, []);

  function drawNet(
    colArr: number[],
    scale: number = 1,
    clickable: boolean = true,
  ) {
    const s = CELL * scale;
    const W = 4 * s, H = 3 * s;
    return (
      <svg viewBox={`0 0 ${W} ${H}`} width={W} height={H} style={{ display: 'block' }}>
        {NET_POSITIONS.map(({ face, col, row, labelZh, labelEn }) => {
          const x = col * s, y = row * s;
          const cIdx = colArr[face] ?? 0;
          const fill = FACE_COLOR_SWATCHES[cIdx % FACE_COLOR_SWATCHES.length];
          // determine if fill is light or dark for text contrast
          const isDark = ['#3498DB', '#2ECC71', '#9B59B6', '#1ABC9C'].includes(fill);
          const textFill = isDark ? '#fff' : '#222';
          return (
            <g key={face} style={{ cursor: clickable ? 'pointer' : 'default' }}
              onClick={clickable ? () => handleFaceClick(face) : undefined}>
              <rect x={x} y={y} width={s} height={s} fill={fill}
                stroke="var(--rule)" strokeWidth={1.5} rx={2} />
              {scale >= 0.9 && (
                <text x={x + s / 2} y={y + s / 2 + 4}
                  textAnchor="middle"
                  style={{ fontFamily: 'var(--mono)', fontSize: scale >= 1 ? 11 : 8, userSelect: 'none' }}
                  fill={textFill}>
                  {lang === 'zh' ? labelZh : labelEn}
                </text>
              )}
            </g>
          );
        })}
      </svg>
    );
  }

  // Parse orbit strings back to color arrays for mini gallery
  const orbitColArrays: number[][] = useMemo(
    () => orbit.map(s => s.split(',').map(Number)),
    [orbit],
  );

  return (
    <div className="gt-panel" style={{ marginTop: 36 }}>
      <div className="gt-panel-title">
        <L zh="轨道实验台：展开图染色" en="Orbit playground: cube net colouring" />
      </div>
      <div className="gt-panel-sub">
        <L
          zh={`点击展开图上的面循环切换颜色，右侧显示整个旋转等价类（轨道）的所有成员。颜色数 k 越大，轨道一般越大。`}
          en={`Click a face on the net to cycle its colour. The gallery on the right shows all members of the orbit (rotation-equivalence class). Larger k generally means bigger orbits.`}
        />
      </div>

      <div className="gt-panel-input-row" style={{ flexWrap: 'wrap', gap: 8, alignItems: 'center' }}>
        <label style={{ fontFamily: 'var(--mono)', fontSize: 13 }}>k =</label>
        {[1, 2, 3, 4, 5, 6].map(kv => (
          <button
            key={kv}
            className={`gt-chip${k === kv ? ' gt-chip-active' : ''}`}
            onClick={() => handleKChange(kv)}
          >
            {kv}
          </button>
        ))}
      </div>

      {/* Colour swatch legend */}
      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 8 }}>
        {Array.from({ length: k }, (_, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
            <div style={{
              width: 16, height: 16, borderRadius: 3,
              background: FACE_COLOR_SWATCHES[i],
              border: '1px solid var(--rule)',
            }} />
            <span style={{ fontFamily: 'var(--mono)', fontSize: 11, color: 'var(--ink-dim)' }}>
              {lang === 'zh' ? SWATCH_LABELS_ZH[i] : SWATCH_LABELS_EN[i]}
            </span>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 24, alignItems: 'flex-start', marginTop: 16 }}>
        {/* Main net */}
        <div>
          <div style={{ fontSize: 12, color: 'var(--ink-dim)', marginBottom: 6, fontFamily: 'var(--mono)' }}>
            <L zh="点击面切换颜色" en="Click face to change colour" />
          </div>
          {drawNet(colors, 1, true)}
        </div>

        {/* Results */}
        <div style={{ flex: '1 1 180px' }}>
          <div className="gt-panel-result">
            <div className="gt-result-row">
              <span className="gt-result-label"><L zh="轨道大小" en="Orbit size" /></span>
              <span className="gt-result-val-strong" style={{ color: 'var(--accent)', fontSize: 18 }}>{orbitSize}</span>
            </div>
            <div className="gt-result-row">
              <span className="gt-result-label"><L zh="稳定子大小 |G|/|Orb|" en="Stabiliser |G|/|Orb|" /></span>
              <span className="gt-result-val-strong" style={{ color: 'var(--accent-2)' }}>{stabSize}</span>
            </div>
            <div className="gt-result-row">
              <span className="gt-result-label"><L zh="乘积检验" en="Product check" /></span>
              <span className="gt-result-val" style={{ color: 'var(--green)' }}>
                {orbitSize} × {stabSize} = 24 ✓
              </span>
            </div>
          </div>
          <div style={{ marginTop: 10, fontSize: 13, color: 'var(--ink-dim)', lineHeight: 1.6 }}>
            {orbitSize === 1 && (
              <L
                zh="所有面颜色相同，任意旋转均不动此着色，稳定子 = 整个群 G。"
                en="All faces the same colour — every rotation fixes this colouring, so the stabiliser is all of G."
              />
            )}
            {orbitSize === 24 && (
              <L
                zh="轨道大小等于 |G|，说明只有恒等旋转固定此着色——稳定子平凡。"
                en="Orbit size equals |G|, so only the identity rotation fixes this colouring — trivial stabiliser."
              />
            )}
          </div>
          <button
            className="gt-btn-ghost"
            style={{ marginTop: 10, fontSize: 12 }}
            onClick={() => setShowOrbit(v => !v)}
          >
            <L
              zh={showOrbit ? '隐藏轨道图集' : `显示轨道图集 (${orbitSize} 个)`}
              en={showOrbit ? 'Hide orbit gallery' : `Show orbit gallery (${orbitSize})`}
            />
          </button>
        </div>
      </div>

      {/* Orbit gallery */}
      {showOrbit && (
        <div style={{ marginTop: 16 }}>
          <div style={{ fontSize: 12, color: 'var(--ink-dim)', marginBottom: 8, fontFamily: 'var(--mono)' }}>
            <L
              zh={`轨道中的全部 ${orbitSize} 个旋转等价着色（展开图）`}
              en={`All ${orbitSize} rotationally-equivalent colourings in this orbit`}
            />
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
            {orbitColArrays.map((ca, idx) => (
              <div key={idx} style={{ opacity: ca.join(',') === colors.join(',') ? 1 : 0.65 }}>
                {drawNet(ca, 0.45, false)}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// Panel 3: Distinct-vs-repeated comparison
// ══════════════════════════════════════════════════════════════════════════════

function DistinctVsRepeatedPanel({ lang: _lang }: { lang: Lang }) {
  const [k, setK] = useState(6);

  const unrestricted = useMemo(() => faceFormula(k), [k]);
  const canDoDistinct = k >= 6;
  // injections: k! / (k-6)! = k*(k-1)*...*(k-5); every injection has trivial stab -> orbit size 24
  const injectCount = useMemo(() => {
    if (!canDoDistinct) return null;
    let prod = 1;
    for (let i = 0; i < 6; i++) prod *= (k - i);
    return prod / 24;
  }, [k, canDoDistinct]);

  // Orbit-stabilizer: 6!/24 = 30 for k=6
  const ARROW_X = 90;

  return (
    <div className="gt-panel" style={{ marginTop: 36 }}>
      <div className="gt-panel-title">
        <L zh="30 还是 2226？——允许重色与不允许重色" en='"30 or 2226?" — repeated vs. distinct colours' />
      </div>
      <div className="gt-panel-sub">
        <L
          zh={`最常见的混淆：N(6)=2226 允许重色，而"6 色各用一次"的答案是 30。两个问题，两个答案。`}
          en={`The most common confusion: N(6)=2226 allows repeated colours, while "one of each colour per face" gives 30. Two different questions, two different answers.`}
        />
      </div>

      <div className="gt-panel-input-row" style={{ flexWrap: 'wrap', gap: 8, alignItems: 'center' }}>
        <label style={{ fontFamily: 'var(--mono)', fontSize: 13 }}>k =</label>
        <input
          type="range" min={1} max={8} value={k}
          onChange={e => setK(+e.target.value)}
          style={{ flex: '1 1 100px' }}
          className="gt-input"
        />
        <span style={{ fontFamily: 'var(--mono)', fontWeight: 700, color: 'var(--accent)', minWidth: 20 }}>{k}</span>
      </div>

      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16, marginTop: 20, alignItems: 'stretch' }}>
        {/* Card A: unrestricted */}
        <div style={{
          flex: '1 1 200px',
          padding: '16px',
          background: 'var(--bg-elev)',
          border: '1px solid var(--rule)',
          borderRadius: 8,
        }}>
          <div style={{ fontFamily: 'var(--serif)', fontSize: 15, fontWeight: 600, color: 'var(--ink)', marginBottom: 6 }}>
            <L zh={`最多 ${k} 色（允许重色）`} en={`At most ${k} colours (repeats allowed)`} />
          </div>
          <div style={{ fontFamily: 'var(--mono)', fontSize: 11, color: 'var(--ink-dim)', marginBottom: 10 }}>
            N(k) = (k⁶ + 3k⁴ + 12k³ + 8k²) / 24
          </div>
          <div style={{ fontSize: 28, fontWeight: 700, fontFamily: 'var(--mono)', color: 'var(--accent)' }}>
            {unrestricted.toLocaleString()}
          </div>
          <div style={{ fontSize: 12, color: 'var(--ink-dim)', marginTop: 6 }}>
            <L
              zh={<>= ({Math.pow(k,6)} + 3·{Math.pow(k,4)} + 12·{Math.pow(k,3)} + 8·{Math.pow(k,2)}) / 24</>}
              en={<>= ({Math.pow(k,6)} + 3·{Math.pow(k,4)} + 12·{Math.pow(k,3)} + 8·{Math.pow(k,2)}) / 24</>}
            />
          </div>
        </div>

        {/* Card B: distinct / injective */}
        <div style={{
          flex: '1 1 200px',
          padding: '16px',
          background: canDoDistinct ? 'var(--bg-elev)' : 'var(--bg-deep)',
          border: `1px solid ${canDoDistinct ? 'var(--green)' : 'var(--rule)'}`,
          borderRadius: 8,
          opacity: canDoDistinct ? 1 : 0.5,
        }}>
          <div style={{ fontFamily: 'var(--serif)', fontSize: 15, fontWeight: 600, color: 'var(--ink)', marginBottom: 6 }}>
            <L zh="各色恰好用一次（双射，需 k≥6）" en="One of each colour (bijection, needs k≥6)" />
          </div>
          <div style={{ fontFamily: 'var(--mono)', fontSize: 11, color: 'var(--ink-dim)', marginBottom: 10 }}>
            k!/(k-6)! / 24
          </div>
          {canDoDistinct ? (
            <>
              <div style={{ fontSize: 28, fontWeight: 700, fontFamily: 'var(--mono)', color: 'var(--green)' }}>
                {injectCount?.toLocaleString()}
              </div>
              {k === 6 && (
                <>
                  {/* Arrow diagram: 720 -> /24 -> 30 */}
                  <svg viewBox="0 0 200 38" width="100%" style={{ display: 'block', marginTop: 10 }}>
                    <text x={0} y={24} style={{ fontFamily: 'var(--mono)', fontSize: 13, fontWeight: 700 }} fill="var(--ink)">6! = 720</text>
                    <text x={70} y={14} style={{ fontFamily: 'var(--mono)', fontSize: 9 }} fill="var(--ink-dim)">÷ 24</text>
                    <text x={68} y={28} style={{ fontFamily: 'var(--mono)', fontSize: 9 }} fill="var(--ink-dim)">(|G|, trivial stab)</text>
                    <line x1={ARROW_X} y1={20} x2={140} y2={20} stroke="var(--rule)" strokeWidth={1.5} markerEnd="url(#arr)" />
                    <defs><marker id="arr" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z" fill="var(--rule)" /></marker></defs>
                    <text x={144} y={24} style={{ fontFamily: 'var(--mono)', fontSize: 14, fontWeight: 700 }} fill="var(--green)">30</text>
                  </svg>
                  <div style={{ fontSize: 11, color: 'var(--ink-dim)', marginTop: 4 }}>
                    <L
                      zh="轨道–稳定子：双射着色的稳定子平凡（只有恒等固定），故每轨道大小 = 24，轨道数 = 720/24 = 30。"
                      en="Orbit-stabiliser: an injective colouring has trivial stabiliser (only identity fixes it), so orbit size = 24, giving 720/24 = 30 orbits."
                    />
                  </div>
                </>
              )}
            </>
          ) : (
            <div style={{ fontSize: 14, color: 'var(--ink-faint)', fontStyle: 'italic' }}>
              <L zh={`k=${k} < 6，无法将 6 种不同颜色各放一面`} en={`k=${k} < 6, cannot place 6 distinct colours one per face`} />
            </div>
          )}
        </div>
      </div>

      {k === 6 && (
        <div className="gt-aside" style={{ marginTop: 12, fontSize: 13 }}>
          <L
            zh={<>注意 30 ≠ 2226。前者要求每色恰好用一次（如标准魔方的 6 种颜色各一面），后者允许任意重复。这两个数针对根本不同的问题。</>}
            en={<>Note 30 ≠ 2226. The former requires each colour exactly once (like the 6 colours of a standard cube, one per face); the latter allows any repetition. These answer fundamentally different questions.</>}
          />
        </div>
      )}
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// Panel 4: Cycle index inspector — symbolic display with animated substitution
// ══════════════════════════════════════════════════════════════════════════════

function CycleIndexPanel({ lang }: { lang: Lang }) {
  const [k, setK] = useState(2);
  const [highlighted, setHighlighted] = useState<number | null>(null);

  // The 5 terms of the face cycle index (coefficient, monoial display, c value)
  const TERMS: { coeff: number; mono: string; c: number; classIdx: number }[] = [
    { coeff: 1,  mono: 'x₁⁶',        c: 6, classIdx: 0 },
    { coeff: 6,  mono: 'x₁² x₄',     c: 3, classIdx: 1 },
    { coeff: 3,  mono: 'x₁² x₂²',    c: 4, classIdx: 2 },
    { coeff: 8,  mono: 'x₃²',         c: 2, classIdx: 3 },
    { coeff: 6,  mono: 'x₂³',         c: 3, classIdx: 4 },
  ];

  const termValues = TERMS.map(t => t.coeff * Math.pow(k, t.c));
  const total = termValues.reduce((a, b) => a + b, 0);
  const answer = total / 24;

  return (
    <div className="gt-panel" style={{ marginTop: 36 }}>
      <div className="gt-panel-title">
        <L zh="圈指标检视器" en="Cycle index inspector" />
      </div>
      <div className="gt-panel-sub">
        <L
          zh="悬停或点击每项，高亮其对应的共轭类；拖动 k 观察代入 x_i → k 后的数值变化。"
          en="Hover or click each term to highlight its conjugacy class; drag k to watch the substitution x_i → k animate."
        />
      </div>

      <div className="gt-panel-input-row" style={{ gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
        <label style={{ fontFamily: 'var(--mono)', fontSize: 13 }}>k =</label>
        <input
          type="range" min={1} max={8} value={k}
          onChange={e => setK(+e.target.value)}
          style={{ flex: '1 1 100px' }}
          className="gt-input"
        />
        <span style={{ fontFamily: 'var(--mono)', fontWeight: 700, color: 'var(--accent)', minWidth: 20 }}>{k}</span>
      </div>

      {/* Polynomial display */}
      <div style={{ marginTop: 20, fontFamily: 'var(--mono)', fontSize: 14, lineHeight: 2.2, overflowX: 'auto' }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'baseline', gap: '0 4px' }}>
          <span style={{ color: 'var(--ink-dim)' }}>Z = (1/24)(</span>
          {TERMS.map((t, i) => {
            const isHL = highlighted === i;
            const col = PALETTE[t.classIdx % PALETTE.length];
            return (
              <span key={i}
                style={{
                  cursor: 'pointer',
                  color: isHL ? col : 'var(--ink)',
                  background: isHL ? `color-mix(in srgb, ${col} 12%, transparent)` : 'transparent',
                  borderRadius: 4,
                  padding: '0 4px',
                  fontWeight: isHL ? 700 : 400,
                  transition: 'all .15s',
                  display: 'inline-flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                }}
                onMouseEnter={() => setHighlighted(i)}
                onMouseLeave={() => setHighlighted(null)}
                onClick={() => setHighlighted(prev => prev === i ? null : i)}
              >
                <span>{t.coeff > 1 ? `${t.coeff} ` : ''}{t.mono}</span>
                {/* Substituted value fades in */}
                <span style={{
                  fontSize: 10,
                  color: isHL ? col : 'var(--ink-faint)',
                  minHeight: '1em',
                  transition: 'opacity .2s',
                  opacity: 1,
                }}>
                  = {t.coeff}·{k}^{t.c} = {termValues[i]}
                </span>
              </span>
            );
          }).reduce<React.ReactNode[]>((acc, el, i) => {
            if (i > 0) acc.push(<span key={`+${i}`} style={{ color: 'var(--ink-dim)' }}> + </span>);
            acc.push(el);
            return acc;
          }, [])}
          <span style={{ color: 'var(--ink-dim)' }}>)</span>
        </div>

        {/* Substituted line */}
        <div style={{ marginTop: 8, color: 'var(--ink-dim)', fontSize: 13 }}>
          <L zh="代入 x_i = k：" en="Substituting x_i = k:" />
          <span style={{ color: 'var(--ink)', fontWeight: 600, marginLeft: 6 }}>
            ({termValues.join(' + ')}) / 24 = {total} / 24 ={' '}
            <span style={{ color: 'var(--green)', fontWeight: 700, fontSize: 16 }}>{answer}</span>
          </span>
        </div>
      </div>

      {highlighted !== null && (
        <div className="gt-aside" style={{ marginTop: 12, fontSize: 13 }}>
          <L
            zh={<>
              <strong style={{ color: PALETTE[TERMS[highlighted].classIdx % PALETTE.length] }}>
                {FACE_CLASSES[TERMS[highlighted].classIdx].nameZh}
              </strong>（{FACE_CLASSES[TERMS[highlighted].classIdx].size} 个旋转，圈型 {FACE_CLASSES[TERMS[highlighted].classIdx].cycleType}）：
              圈指标中的单项式 <strong>{TERMS[highlighted].mono}</strong> 记录了这类旋转的圈结构；
              代入 x_i = k 后，该项变为 {TERMS[highlighted].coeff}·k^{TERMS[highlighted].c} = {termValues[highlighted]}。
            </>}
            en={<>
              <strong style={{ color: PALETTE[TERMS[highlighted].classIdx % PALETTE.length] }}>
                {FACE_CLASSES[TERMS[highlighted].classIdx].nameEn}
              </strong> ({FACE_CLASSES[TERMS[highlighted].classIdx].size} rotations, cycle type {FACE_CLASSES[TERMS[highlighted].classIdx].cycleType}):
              the monomial <strong>{TERMS[highlighted].mono}</strong> in the cycle index records this class's cycle structure;
              substituting x_i = k gives {TERMS[highlighted].coeff}·k^{TERMS[highlighted].c} = {termValues[highlighted]}.
            </>}
          />
        </div>
      )}

      {/* Class-to-term cross-reference table */}
      <div style={{ overflowX: 'auto', marginTop: 20 }}>
        <table className="gt-compare">
          <thead>
            <tr>
              <th><L zh="共轭类" en="Conjugacy class" /></th>
              <th><L zh="大小" en="Size" /></th>
              <th><L zh="圈型 (面)" en="Cycle type (faces)" /></th>
              <th><L zh="圈数 c" en="Cycles c" /></th>
              <th><L zh={`k^c (k=${k})`} en={`k^c (k=${k})`} /></th>
              <th><L zh="贡献" en="Contribution" /></th>
            </tr>
          </thead>
          <tbody>
            {FACE_CLASSES.map((cls, i) => (
              <tr
                key={i}
                style={{
                  cursor: 'pointer',
                  background: highlighted === i
                    ? `color-mix(in srgb, ${PALETTE[i % PALETTE.length]} 10%, transparent)`
                    : undefined,
                }}
                onMouseEnter={() => setHighlighted(i)}
                onMouseLeave={() => setHighlighted(null)}
              >
                <td style={{ color: PALETTE[i % PALETTE.length], fontWeight: 600 }}>
                  {lang === 'zh' ? cls.nameZh : cls.nameEn}
                </td>
                <td style={{ textAlign: 'center', fontFamily: 'var(--mono)' }}>{cls.size}</td>
                <td style={{ textAlign: 'center', fontFamily: 'var(--mono)' }}>{cls.cycleType}</td>
                <td style={{ textAlign: 'center', fontFamily: 'var(--mono)' }}>{cls.cycles}</td>
                <td style={{ textAlign: 'center', fontFamily: 'var(--mono)' }}>
                  {Math.pow(k, cls.cycles)}
                </td>
                <td style={{ textAlign: 'center', fontFamily: 'var(--mono)', fontWeight: 700 }}>
                  {termValues[i]}
                </td>
              </tr>
            ))}
            <tr style={{ borderTop: '2px solid var(--rule)', fontWeight: 700 }}>
              <td colSpan={5} style={{ textAlign: 'right', paddingRight: 12, fontFamily: 'var(--mono)' }}>
                <L zh="总和 / 24 =" en="Sum / 24 =" />
              </td>
              <td style={{ textAlign: 'center', fontFamily: 'var(--mono)', color: 'var(--green)', fontSize: 15 }}>
                {total} / 24 = {answer}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
