/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_block222solverwasm_free: (a: number, b: number) => void;
export const __wbg_crosssolverwasm_free: (a: number, b: number) => void;
export const __wbg_f2leosolverwasm_free: (a: number, b: number) => void;
export const __wbg_variantsolverwasm_free: (a: number, b: number) => void;
export const block222solverwasm_new: (a: number, b: number, c: number, d: number) => number;
export const block222solverwasm_solve: (a: number, b: number, c: number) => [number, number];
export const block222solverwasm_solve_face: (a: number, b: number, c: number, d: number) => number;
export const block222solverwasm_solve_moves: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const crosssolverwasm_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => number;
export const crosssolverwasm_solve: (a: number, b: number, c: number, d: number) => [number, number];
export const crosssolverwasm_solve_cumulative: (a: number, b: number, c: number, d: number) => [number, number];
export const crosssolverwasm_solve_face: (a: number, b: number, c: number, d: number, e: number) => number;
export const crosssolverwasm_solve_moves: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const f2leosolverwasm_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => number;
export const f2leosolverwasm_solve_f2leo: (a: number, b: number, c: number) => [number, number];
export const f2leosolverwasm_solve_f2leo_stage: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const f2leosolverwasm_solve_moves: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const f2leosolverwasm_solve_pseudo_f2leo: (a: number, b: number, c: number) => [number, number];
export const variantsolverwasm_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number) => number;
export const variantsolverwasm_solve: (a: number, b: number, c: number, d: number) => [number, number];
export const variantsolverwasm_solve_moves: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const variantsolverwasm_solve_stage: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
