'use client';

import { GTSec, L, TeX, TeXBlock, useLang } from '../primitives';
import { tr } from '@/i18n/tr';
import { TwistyMini } from '../TwistyMini';

function GeneratorRow() {
  const faces: { f: string; zh: string; en: string
 }[] = [
    { f: 'U', zh: '上层顺时针', en: 'Up'
    },
    { f: 'D', zh: '下层顺时针', en: 'Down'
    },
    { f: 'R', zh: '右层顺时针', en: 'Right'
    },
    { f: 'L', zh: '左层顺时针', en: 'Left'
    },
    { f: 'F', zh: '前层顺时针', en: 'Front'
    },
    { f: 'B', zh: '后层顺时针', en: 'Back'
    },
  ];
  const lang = useLang();
  return (
    <div className="gt-cube-row">
      {faces.map(({ f, zh, en }) => (
        <div className="gt-cube-cell" key={f}>
          <div className="gt-cube-label">{f}</div>
          <TwistyMini alg={f} />
          <div className="gt-cube-sub">{lang === 'zh' ? zh : en}</div>
        </div>
      ))}
    </div>
  );
}

// ── §4 CubeStateInspector ───────────────────────────────────────────────────

export default function CubeGroup() {
  return (
      <GTSec id="cube-group" className="gt-sec">
        <div className="gt-sec-num">§2</div>
        <h2 className="gt-sec-title">
          <L zh="魔方群 G" en="The cube group G" />
        </h2>
        <p>
          <L
            zh={<>把还原状态记作 <TeX src={`e`} />。 把每一次「转一个面 90° 或 180°」记作一个置换,作用在 26 个小块的位置和朝向上。所有可由这些转面组合得到的置换 (state) 构成集合 <strong>G</strong>。</>}
            en={<>Write the solved state as <TeX src={`e`} />. Each "turn a face 90° or 180°" is a permutation acting on the positions and orientations of the 26 cubies. The set <strong>G</strong> consists of all permutations producible by composing such turns.</>}
          />
        </p>
        <div className="gt-def">
          <div className="gt-def-title">{tr({ zh: '定义 2.1 — 魔方群', en: 'Definition 2.1 — the cube group'
        })}</div>
          <div className="gt-def-body">
            <TeXBlock src={`G = \\langle U,\\, D,\\, L,\\, R,\\, F,\\, B \\rangle`} />
            <L
              zh={<>由六个面转 <span className="gt-mono">U, D, L, R, F, B</span> <strong>生成</strong> 的群。每个生成元是 90° 顺时针转面;它的逆是 90° 逆时针 (即 <span className="gt-mono">U′</span>),它的平方是 180° (即 <span className="gt-mono">U2</span>),所以 <strong>18 元操作集</strong> {'{U, U′, U2, ..., B2}'} 是常用的工作生成集。</>}
              en={<>The group <strong>generated by</strong> the six face turns <span className="gt-mono">U, D, L, R, F, B</span>. Each generator is a 90° clockwise face turn; its inverse is the CCW turn (<span className="gt-mono">U′</span>), its square is the half-turn (<span className="gt-mono">U2</span>), giving the standard working set of <strong>18 moves</strong>.</>}
            />
          </div>
        </div>

        <p style={{ marginTop: 32, marginBottom: 12 }}>
          <L
            zh="6 个生成元 — 点开任一个面,看 cubing.js 把这个操作转给你看:"
            en="The six generators — click any face below; cubing.js will animate it."
          />
        </p>
        <GeneratorRow />

        <div className="gt-aside">
          <L
            zh={<>注:魔方爱好者熟悉的「中间层切」<span className="gt-mono">M, E, S</span> 和「整体旋转」<span className="gt-mono">x, y, z</span> 不是 G 的额外生成元。它们都能用 6 个面转表示出来,例如 <span className="gt-mono">M = R' L x'</span>。它们存在只是为了书写方便。</>}
            en={<>Aside: the slice moves <span className="gt-mono">M, E, S</span> and full rotations <span className="gt-mono">x, y, z</span> are not extra generators of G. They are derived: <span className="gt-mono">M = R' L x'</span>, etc. They exist only as a notational convenience.</>}
          />
        </div>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
          <L zh="2.1  生成集 — 18 个还是 6 个?" en="2.1  Generating set — 18 or 6?" />
        </h3>
        <p>
          <L
            zh={<>正式的生成集是 6 个 (六个面转),但实际操作时记号上人们用 18 个:每面 ×3 角度 (90°, 180°, 270° = 270° 也写作 -90° 即 <span className="gt-mono">U′</span>)。这 18 个就是 WCA 比赛使用的 <strong>半圈度量</strong> (Half-Turn Metric, HTM)。<br /><br />还有更细致的 <strong>四分一圈度量</strong> (Quarter-Turn Metric, QTM):只允许 90° 转,180° 算两步。在 QTM 下,生成集是 12 个 (六面 ×{2}),魔方群直径变成 <strong>26</strong>。</>}
            en={<>The minimal generating set has 6 elements (the six face turns), but in notation we usually write 18: each face × 3 angles (90°, 180°, 270° = the inverse <span className="gt-mono">U′</span>). These 18 constitute the <strong>Half-Turn Metric (HTM)</strong> used in WCA competition.<br /><br />The stricter <strong>Quarter-Turn Metric (QTM)</strong> only allows 90° turns (180° counts as two). In QTM, the generating set has 12 elements, and the group's diameter rises to <strong>26</strong>.</>}
          />
        </p>
        <div className="gt-def">
          <div className="gt-def-title">{tr({ zh: '定义 2.2 — 度量', en: 'Definition 2.2 — metric on a group'
        })}</div>
          <div className="gt-def-body">
            <L
              zh={<>给定生成集 <TeX src={`S`} />,对任意 <TeX src={`g \\in G`} />,定义 <TeX src={`|g|_S`} /> 为「<em>用 S 的元素表示 g 所需的最少 token 数</em>」。HTM 用 18-生成集,QTM 用 12-生成集。「最短解」是 <TeX src={`|g|_S`} /> 的别名。</>}
              en={<>Given a generating set <TeX src={`S`} />, for any <TeX src={`g \\in G`} />, define <TeX src={`|g|_S`} /> as the <em>minimum number of S-tokens whose product equals g</em>. HTM uses the 18-generator set; QTM the 12-generator set. The "optimal solution length" is simply <TeX src={`|g|_S`} />.</>}
            />
          </div>
        </div>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
          <L zh="2.2  群的呈现 (Presentation)" en="2.2  Group presentation" />
        </h3>
        <p>
          <L
            zh={<>群也可以用「生成元 + 关系」抽象描述。例如 <TeX src={`\\mathbb{Z}/4 = \\langle a \\mid a^4 = e \\rangle`} />,意为「一个元素 a,自乘 4 次为单位元」。对魔方群:</>}
            en={<>A group can also be presented abstractly as "generators with relations." For instance <TeX src={`\\mathbb{Z}/4 = \\langle a \\mid a^4 = e \\rangle`} /> means "one element a, which when raised to the 4th power gives e." For the cube:</>}
          />
        </p>
        <TeXBlock src={`G = \\Bigl\\langle \\;U, D, L, R, F, B \\;\\Bigm|\\; \\begin{aligned} & U^4 = D^4 = L^4 = R^4 = F^4 = B^4 = e, \\\\ & UD = DU,\\;\\; LR = RL,\\;\\; FB = BF, \\\\ & \\text{(plus dozens of opaque longer relators)} \\end{aligned} \\Bigr\\rangle`} />
        <p>
          <L
            zh={<>除了「每面转 4 次回到原点」和「平行面互换」这两条显然的关系,其它的生成元间关系太繁杂,实际上没人完整写下来过。<strong>魔方群的有限呈现</strong> (finite presentation) 是数学上一个有趣却罕被研究的对象。</>}
            en={<>Beyond the trivial "each face cycles in 4" and the "parallel faces commute" relations, the rest of the relators are too tangled to enumerate cleanly. A <em>complete finite presentation</em> for G is mathematically curious but rarely written down explicitly.</>}
          />
        </p>
        <div className="gt-aside">
          <L
            zh={<>有趣的是,「字问题」(word problem,即给定两个字判断是否相等) 在魔方群上是 <em>可解的</em> —— 因为 G 是有限群,字问题等价于「先把两个字归约为正则形式,再比较」。但 <strong>最短字问题</strong> (即「求 g 的最短表示」) 是 NP-困难的。这就是为什么直接构造最优 solver 是个真正的挑战。</>}
            en={<>Curiously, the <em>word problem</em> (decide if two words represent the same element) is solvable for G — because G is finite, normalising via the cube state suffices. But the <strong>shortest-word problem</strong> (find the optimal representation of g) is NP-hard in the general setting. That's why optimal solvers are genuinely difficult.</>}
          />
        </div>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
          <L zh="2.3  子群" en="2.3  Subgroups" />
        </h3>
        <p>
          <L
            zh={<>给定 G 的生成元的任意子集,生成出的「子群」可能远小于 G。常见的有:</>}
            en={<>Any subset of generators generates a subgroup — usually much smaller than G. Common ones:</>}
          />
        </p>
        <ul style={{ paddingLeft: 26, lineHeight: 1.9 }}>
          <li>
            <TeX src={`\\langle U \\rangle`} /> &nbsp; — <L zh={<>只允许 U 转动:同构于 <TeX src={`\\mathbb{Z}/4`} /> (4 个元素)</>} en={<>only U-turns allowed: isomorphic to <TeX src={`\\mathbb{Z}/4`} /> (4 elements)</>} />
          </li>
          <li>
            <TeX src={`\\langle U, D \\rangle`} /> &nbsp; — <L zh={<>只允许上下面:同构于 <TeX src={`\\mathbb{Z}/4 \\times \\mathbb{Z}/4`} /> = 16 元素</>} en={<>up & down faces: isomorphic to <TeX src={`\\mathbb{Z}/4 \\times \\mathbb{Z}/4`} /> = 16 elements</>} />
          </li>
          <li>
            <TeX src={`\\langle R, U \\rangle`} /> &nbsp; — <L zh={<>R 和 U 生成的子群, 73,483,200 个元素。 Cayley 图的常见研究对象。</>} en={<>The subgroup generated by R and U: order ≈ 73 million. A classic Cayley-graph subject.</>} />
          </li>
          <li>
            <TeX src={`\\langle U^2, D^2, L^2, R^2, F^2, B^2 \\rangle = G_3`} /> &nbsp; — <L zh={`只允许半圈,663,552 个元素 ("多米诺群")`} en={`half-turns only, 663,552 elements (the "domino group")`} />
          </li>
        </ul>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
          <L zh="2.4  18 个面转 — 完整列表" en="2.4  The 18 face turns — complete list" />
        </h3>
        <table className="gt-compare">
          <thead>
            <tr><th>{tr({ zh: '面', en: 'Face' })}</th><th>90°</th><th>180°</th><th>270° = 90° CCW</th><th>{tr({ zh: 'HTM 计数', en: 'HTM count'
            })}</th></tr>
          </thead>
          <tbody>
            <tr><td><strong>U</strong></td><td className="num"><span className="gt-mono">U</span></td><td className="num"><span className="gt-mono">U2</span></td><td className="num"><span className="gt-mono">U'</span></td><td className="num">3</td></tr>
            <tr><td><strong>D</strong></td><td className="num"><span className="gt-mono">D</span></td><td className="num"><span className="gt-mono">D2</span></td><td className="num"><span className="gt-mono">D'</span></td><td className="num">3</td></tr>
            <tr><td><strong>L</strong></td><td className="num"><span className="gt-mono">L</span></td><td className="num"><span className="gt-mono">L2</span></td><td className="num"><span className="gt-mono">L'</span></td><td className="num">3</td></tr>
            <tr><td><strong>R</strong></td><td className="num"><span className="gt-mono">R</span></td><td className="num"><span className="gt-mono">R2</span></td><td className="num"><span className="gt-mono">R'</span></td><td className="num">3</td></tr>
            <tr><td><strong>F</strong></td><td className="num"><span className="gt-mono">F</span></td><td className="num"><span className="gt-mono">F2</span></td><td className="num"><span className="gt-mono">F'</span></td><td className="num">3</td></tr>
            <tr><td><strong>B</strong></td><td className="num"><span className="gt-mono">B</span></td><td className="num"><span className="gt-mono">B2</span></td><td className="num"><span className="gt-mono">B'</span></td><td className="num">3</td></tr>
            <tr><td>{tr({ zh: '合计', en: 'Total'
            })}</td><td colSpan={3}></td><td className="num"><strong>18</strong></td></tr>
          </tbody>
        </table>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
          <L zh="2.5  循环结构 — 每个面转拆成的循环" en="2.5  Cycle structure of each face turn" />
        </h3>
        <p>
          <L
            zh={<>每个面转都是一个 8 角块 × 12 棱块 的置换。把 R 写出来 (用 §3 的 cubie 编号):</>}
            en={<>Each face turn is a permutation of the 8 corners and 12 edges. Writing R out explicitly (using the cubie indexing of §3):</>}
          />
        </p>
        <TeXBlock src={`R = (0\\;3\\;7\\;4)_{c} \\cdot (0\\;11\\;4\\;8)_{e}`} />
        <p>
          <L
            zh={<>即 「URF → UBR → DRB → DFR → URF」 这条 4-循环, 加上对应的棱块 4-循环 「UR → BR → DR → FR → UR」。 类似地 U 是 <TeX src={`(0\\;1\\;2\\;3)_c (0\\;1\\;2\\;3)_e`} />,F 还要叠上 4 棱块的翻面 (EO+1)。所有 6 个生成元都呈现「4-cycle 角 × 4-cycle 棱 + 可能的 orientation 偏移」的同一模板:</>}
            en={<>That is the 4-cycle URF → UBR → DRB → DFR → URF on corners, plus the matching 4-cycle UR → BR → DR → FR → UR on edges. Likewise U is <TeX src={`(0\\;1\\;2\\;3)_c (0\\;1\\;2\\;3)_e`} />, and F also flips 4 edges (EO+1). All six generators follow the same pattern: 4-cycle on corners × 4-cycle on edges + optional orientation kick.</>}
          />
        </p>
        <table className="gt-compare">
          <thead>
            <tr><th>{tr({ zh: '生成元', en: 'Gen' })}</th><th>{tr({ zh: '角块循环', en: 'Corner cycle'
            })}</th><th>{tr({ zh: '棱块循环', en: 'Edge cycle'
            })}</th><th>{tr({ zh: '阶', en: 'Order'
            })}</th><th>{tr({ zh: '改 CO?', en: 'Δ CO' })}</th><th>{tr({ zh: '改 EO?', en: 'Δ EO' })}</th></tr>
          </thead>
          <tbody>
            <tr><td><strong>U</strong></td><td><TeX src={`(0\\;1\\;2\\;3)`} /></td><td><TeX src={`(0\\;1\\;2\\;3)`} /></td><td className="num">4</td><td>0</td><td>0</td></tr>
            <tr><td><strong>R</strong></td><td><TeX src={`(0\\;3\\;7\\;4)`} /></td><td><TeX src={`(0\\;11\\;4\\;8)`} /></td><td className="num">4</td><td>{tr({ zh: '是', en: 'yes' })}</td><td>0</td></tr>
            <tr><td><strong>F</strong></td><td><TeX src={`(0\\;4\\;5\\;1)`} /></td><td><TeX src={`(1\\;8\\;5\\;9)`} /></td><td className="num">4</td><td>{tr({ zh: '是', en: 'yes' })}</td><td>{tr({ zh: '4 棱 +1', en: '4 edges +1'
            })}</td></tr>
          </tbody>
        </table>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 40, marginBottom: 14, color: 'var(--ink)' }}>
          <L zh="2.6  关系与反例" en="2.6  Relations and a non-relation" />
        </h3>
        <p>
          <L
            zh={<>显然的关系:每个面转 4 次为单位元, <TeX src={`U^4 = e`} />, 等等。 取逆: <TeX src={`U \\cdot U' = e`} />。 但 <strong>U 与 R 不交换</strong>:</>}
            en={<>Obvious relations: each face has order 4, <TeX src={`U^4 = e`} />, and trivially <TeX src={`U \\cdot U' = e`} />. But <strong>U does not commute with R</strong>:</>}
          />
        </p>
        <TeXBlock src={`UR \\;\\neq\\; RU \\qquad \\text{(verify: apply both to the solved state; resulting corners and edges differ)}`} />
        <p>
          <L
            zh={<>这一条 「非关系」 是整个魔方理论的源头 — 若 UR = RU,魔方就退化为阿贝尔。 Coxeter 风格的呈现(若魔方群恰是 Coxeter 群)会要求 <TeX src={`(s_i s_j)^{m_{ij}} = e`} />。 魔方群 <strong>不是</strong> Coxeter 群: 6 个面转之间没有形如 <TeX src={`(UR)^k = e`} /> 的小整数关系 (<TeX src={`|UR| = 105`} />,见 §8)。 这正说明 G 「比通常对称群更野」。</>}
            en={<>That non-relation is the entire source of cube theory — if UR = RU the cube would collapse to Abelian. A Coxeter-style presentation would demand <TeX src={`(s_i s_j)^{m_{ij}} = e`} /> for some small <TeX src={`m_{ij}`} />. G is <strong>not</strong> a Coxeter group: there is no small integer k with <TeX src={`(UR)^k = e`} /> (<TeX src={`|UR| = 105`} />, see §8). G is genuinely "wilder" than the standard symmetry groups.</>}
          />
        </p>
      </GTSec>
  );
}
