'use client';

import { useState } from 'react';
import { GTSec, L, TeX, TeXBlock, useLang } from '../primitives';
import { tr } from '@/i18n/tr';

// generators), then display |G|/|H| as the count of cosets, with a tiled
function formatBig(n: number): string {
  if (n < 1e6) return n.toLocaleString('en-US');
  if (n < 1e12) return (n / 1e6).toFixed(2) + ' × 10⁶';
  if (n < 1e15) return (n / 1e9).toFixed(2) + ' × 10⁹';
  return n.toExponential(3).replace('e+', ' × 10');
}

const QUOTIENT_OPTIONS = [
  {
    id: 'co-kernel',
    nameZh: 'co-总和 = 0 的核 K_co',
    nameEn: 'ker(Σco): twist-zero',
    indexZh: 'G / K_co ≅ ℤ/3',
    indexEn: 'G / K_co ≅ ℤ/3',
    indexLatex: '|G/K_{\\mathrm{co}}| = 3',
    descZh: '所有让 Σco ≡ 0 的状态构成正规子群,商群是 ℤ/3。',
    descEn: 'States with Σco ≡ 0 form a normal subgroup; the quotient is ℤ/3.',
    n: 3
},
  {
    id: 'eo-kernel',
    nameZh: 'eo-总和 = 0 的核 K_eo',
    nameEn: 'ker(Σeo): flip-zero',
    indexZh: 'G / K_eo ≅ ℤ/2',
    indexEn: 'G / K_eo ≅ ℤ/2',
    indexLatex: '|G/K_{\\mathrm{eo}}| = 2',
    descZh: '所有让 Σeo ≡ 0 的状态构成正规子群,商群是 ℤ/2。',
    descEn: 'States with Σeo ≡ 0 form a normal subgroup; the quotient is ℤ/2.',
    n: 2
},
  {
    id: 'parity-kernel',
    nameZh: '偶置换核 K_par',
    nameEn: 'ker(sgn): even-parity',
    indexZh: 'G / K_par ≅ ℤ/2',
    indexEn: 'G / K_par ≅ ℤ/2',
    indexLatex: '|G/K_{\\mathrm{par}}| = 2',
    descZh: '所有 sgn(cp) = sgn(ep) = +1 的状态。',
    descEn: 'States with sgn(cp) = sgn(ep) = +1.',
    n: 2
},
  {
    id: 'abel',
    nameZh: '换位子群 [G,G]',
    nameEn: 'commutator [G,G]',
    indexZh: 'G^ab = G / [G,G] ≅ ℤ/2',
    indexEn: 'G^ab = G / [G,G] ≅ ℤ/2',
    indexLatex: 'G^{\\mathrm{ab}} \\cong \\mathbb{Z}/2',
    descZh: '所有换位子生成的子群。最大的阿贝尔商。',
    descEn: 'The subgroup generated by all commutators. Yields the largest Abelian quotient.',
    n: 2
},
] as const;

function QuotientGroupBuilder() {
  const lang = useLang();
  const [picked, setPicked] = useState<typeof QUOTIENT_OPTIONS[number]['id']>('co-kernel');
  const opt = QUOTIENT_OPTIONS.find(o => o.id === picked)!;
  return (
    <div className="gt-quotient">
      <div className="gt-quotient-tabs">
        {QUOTIENT_OPTIONS.map(o => (
          <button
            key={o.id}
            className={`gt-quotient-tab ${picked === o.id ? 'active' : ''}`}
            onClick={() => setPicked(o.id)}
          >{lang === 'zh' ? o.nameZh : o.nameEn}</button>
        ))}
      </div>
      <div className="gt-quotient-body">
        <div className="gt-quotient-eqn">
          <TeXBlock src={opt.indexLatex} />
        </div>
        <div className="gt-quotient-desc">{lang === 'zh' ? opt.descZh : opt.descEn}</div>
        <div className="gt-quotient-tiles">
          {Array.from({ length: opt.n }, (_, i) => (
            <div key={i} className="gt-quotient-tile">
              <div className="gt-quotient-tile-coset">[g{i}]</div>
              <div className="gt-quotient-tile-cnt">
                {tr({ zh: '约 ', en: '~'
                })}
                {formatBig(4.3252003274489856e19 / opt.n)}
                {' '}{tr({ zh: '元素', en: 'elts' })}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default function QuotientGroups() {
  return (
      <GTSec id="quotient" className="gt-sec">
        <div className="gt-sec-num">§20</div>
        <h2 className="gt-sec-title">
          <L zh="正规子群与商群" en="Normal subgroups & quotient groups" />
        </h2>
        <p className="gt-lede">
          <L
            zh={<>拉格朗日告诉我们 G 怎么被一个子群 <em>切片</em>;但一般 <strong>陪集本身不是群</strong>。 只有当子群是 <em>正规子群</em> 时,陪集的集合才能继承群的结构,我们得到 <strong>商群</strong> <TeX src={`G/N`} />。 这是整个抽象代数最深的几个想法之一。</>}
            en={<>Lagrange tells us how a subgroup slices G; but <strong>cosets generally don't form a group</strong>. Only when the subgroup is <em>normal</em> does the set of cosets inherit a group structure — giving the <strong>quotient group</strong> <TeX src={`G/N`} />. This is among the deepest ideas in abstract algebra.</>}
          />
        </p>
        <div className="gt-def">
          <div className="gt-def-title">{tr({ zh: '定义 20.1 — 正规子群', en: 'Definition 20.1 — normal subgroup'
        })}</div>
          <div className="gt-def-body">
            <L
              zh={<>子群 <span className="gt-math">N ⊂ G</span> 叫 <strong>正规子群</strong> (记作 <TeX src={`N \\triangleleft G`} />),如果它在共轭下保持不变:<TeXBlock src={`\\forall g \\in G, \\;\\; gNg^{-1} = N`} />等价地:左陪集 = 右陪集,<TeX src={`gN = Ng`} />。</>}
              en={<>A subgroup <span className="gt-math">N ⊂ G</span> is <strong>normal</strong> (written <TeX src={`N \\triangleleft G`} />) if it is invariant under conjugation:<TeXBlock src={`\\forall g \\in G, \\;\\; gNg^{-1} = N.`} />Equivalently, left cosets and right cosets coincide: <TeX src={`gN = Ng`} />.</>}
            />
          </div>
        </div>
        <div className="gt-def">
          <div className="gt-def-title">{tr({ zh: '定理 20.2 — 商群', en: 'Theorem 20.2 — quotient group' })}</div>
          <div className="gt-def-body">
            <L
              zh={<>若 <TeX src={`N \\triangleleft G`} />,陪集集合 <TeX src={`G/N = \\{gN : g \\in G\\}`} /> 在乘法<TeXBlock src={`(g_1 N)(g_2 N) := (g_1 g_2) N`} />下构成群。 阶 <TeX src={`|G/N| = [G:N]`} />。</>}
              en={<>If <TeX src={`N \\triangleleft G`} />, the coset set <TeX src={`G/N = \\{gN : g \\in G\\}`} /> forms a group under<TeXBlock src={`(g_1 N)(g_2 N) := (g_1 g_2) N.`} />Its order is <TeX src={`|G/N| = [G:N]`} />.</>}
            />
          </div>
        </div>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 36, marginBottom: 12, color: 'var(--ink)' }}>
          <L zh="20.1  正规子群从哪儿来?同态的核" en="20.1  Where do normal subgroups come from? Kernels of homomorphisms" />
        </h3>
        <p>
          <L
            zh={<>每个群同态 <TeX src={`\\varphi : G \\to H`} /> 的核<TeXBlock src={`\\ker \\varphi := \\{g \\in G : \\varphi(g) = e_H\\}`} />都是 G 的正规子群。 反过来 <strong>(第一同构定理)</strong>,每个正规子群都是某个同态的核;并且<TeXBlock src={`G/\\ker\\varphi \\;\\cong\\; \\operatorname{im}\\varphi.`} /></>}
            en={<>Every group homomorphism <TeX src={`\\varphi : G \\to H`} /> has a kernel<TeXBlock src={`\\ker \\varphi := \\{g \\in G : \\varphi(g) = e_H\\}`} />which is automatically normal in G. Conversely <strong>(First Isomorphism Theorem)</strong>, every normal subgroup is the kernel of some homomorphism; moreover<TeXBlock src={`G/\\ker\\varphi \\;\\cong\\; \\operatorname{im}\\varphi.`} /></>}
          />
        </p>
        <p>
          <L
            zh={<>这就把 §17 的同态、§5 的守恒律、§20 的正规子群全部串起来:<strong>三大守恒律就是三个同态 G → 小阿贝尔群</strong>。它们的核是 G 的三个特殊正规子群:</>}
            en={<>This ties §17's homomorphisms, §5's invariants, and §20's normal subgroups together: <strong>the three conservation laws are three homomorphisms G → small Abelian groups</strong>. Their kernels are three special normal subgroups of G:</>}
          />
        </p>
        <ul style={{ paddingLeft: 26, lineHeight: 1.9 }}>
          <li><TeX src={`\\Sigma_{co} : G \\to \\mathbb{Z}/3`} />, <L zh="核是 「角扭转和为 0」 的状态集" en="kernel = states with corner twist sum 0" /></li>
          <li><TeX src={`\\Sigma_{eo} : G \\to \\mathbb{Z}/2`} />, <L zh="核是 「棱翻面和为 0」 的状态集" en="kernel = states with edge flip sum 0" /></li>
          <li><TeX src={`\\operatorname{sgn} : G \\to \\mathbb{Z}/2`} />, <L zh="核是 「偶置换」 的状态集 (双偶)" en="kernel = states with even-permutation parity" /></li>
        </ul>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 36, marginBottom: 12, color: 'var(--ink)' }}>
          <L zh="20.2  互动:选一个正规子群,看商群" en="20.2  Interactive: pick N, see G/N" />
        </h3>
        <QuotientGroupBuilder />
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 36, marginBottom: 12, color: 'var(--ink)' }}>
          <L zh="20.3  换位子群 [G,G] 与阿贝尔化" en="20.3  Commutator subgroup [G,G] and abelianization" />
        </h3>
        <p>
          <L
            zh={<><strong>换位子群</strong> <TeX src={`[G,G]`} /> 是所有换位子 <TeX src={`[a,b] = aba^{-1}b^{-1}`} /> 生成的子群。 它一定是 G 的正规子群。 商 <TeX src={`G^{\\mathrm{ab}} := G/[G,G]`} /> 叫 G 的 <strong>阿贝尔化</strong> —— 它是「最大阿贝尔商」。</>}
            en={<>The <strong>commutator subgroup</strong> <TeX src={`[G,G]`} /> is generated by all commutators <TeX src={`[a,b] = aba^{-1}b^{-1}`} />. It is always normal in G. The quotient <TeX src={`G^{\\mathrm{ab}} := G/[G,G]`} /> is called the <strong>abelianization</strong> — the "largest Abelian quotient" of G.</>}
          />
        </p>
        <p>
          <L
            zh={<>对魔方:已知 <TeX src={`G^{\\mathrm{ab}} \\cong \\mathbb{Z}/2`} />。 也就是说 G 唯一的「阿贝尔化身影」就是 sgn 同态。 它说明了 G 是极度非阿贝尔的群:换位子群 [G,G] 占了 G 的一半,只有 sgn 一条信息能「逃出」到 ℤ/2。</>}
            en={<>For the cube, it is known that <TeX src={`G^{\\mathrm{ab}} \\cong \\mathbb{Z}/2`} />. The only Abelian shadow of G is the sgn homomorphism — half of G dies in [G,G]; only one bit (sign) survives. G is extremely non-Abelian.</>}
          />
        </p>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 36, marginBottom: 12, color: 'var(--ink)' }}>
          <L zh="20.4  合成列与单群" en="20.4  Composition series & simple groups" />
        </h3>
        <p>
          <L
            zh={<>把 G 反复「商掉一个正规子群」直到不能再商,得到 <strong>合成列</strong><TeXBlock src={`G = G_0 \\triangleright G_1 \\triangleright G_2 \\triangleright \\cdots \\triangleright G_n = \\{e\\}`} />其中每个商 <TeX src={`G_i/G_{i+1}`} /> 都是 <strong>单群</strong> (即没有非平凡正规子群)。 Jordan–Hölder 定理保证这个商序列在重排下唯一。</>}
            en={<>Iteratively factoring G by normal subgroups gives a <strong>composition series</strong><TeXBlock src={`G = G_0 \\triangleright G_1 \\triangleright G_2 \\triangleright \\cdots \\triangleright G_n = \\{e\\}`} />where each quotient <TeX src={`G_i/G_{i+1}`} /> is <strong>simple</strong> (no proper non-trivial normal subgroup). Jordan–Hölder guarantees that, up to reordering, this sequence is unique.</>}
          />
        </p>
        <p>
          <L
            zh={<>对魔方群 G,合成列的「单群因子」是<TeXBlock src={`A_8 \\;\\times\\; A_{12} \\;\\times\\; (\\mathbb{Z}/2)^4 \\;\\times\\; (\\mathbb{Z}/3)^7`} />本质上是 §6 的结构定理换了语言重述。 A₈ 和 A₁₂ 是无穷家族 <em>非阿贝尔有限单群</em> 的成员。</>}
            en={<>For the cube group, the simple factors are<TeXBlock src={`A_8 \\;\\times\\; A_{12} \\;\\times\\; (\\mathbb{Z}/2)^4 \\;\\times\\; (\\mathbb{Z}/3)^7`} />— essentially a restatement of the structure theorem from §6. A₈ and A₁₂ are members of an infinite family of <em>non-Abelian finite simple groups</em>.</>}
          />
        </p>
        <h3 style={{ fontFamily: 'var(--serif)', fontSize: 22, fontWeight: 600, marginTop: 36, marginBottom: 12, color: 'var(--ink)' }}>
          <L zh="20.5  第二与第三同构定理" en="20.5  Second & third isomorphism theorems" />
        </h3>
        <div className="gt-thm">
          <div className="gt-thm-title">{tr({ zh: '定理 20.4 — 第二同构 (钻石定理)', en: 'Theorem 20.4 — Second isomorphism (diamond)'
        })}</div>
          <div className="gt-thm-body">
            <L
              zh={<>设 <TeX src={`H \\le G`} />, <TeX src={`N \\triangleleft G`} />。 则 <TeX src={`HN`} /> 是 G 的子群,<TeX src={`H \\cap N \\triangleleft H`} />,且<TeXBlock src={`(HN)/N \\;\\cong\\; H/(H \\cap N).`} />常画成钻石格 (lattice):四个顶点 <TeX src={`HN,\\,H,\\,N,\\,H\\cap N`} />,两条对角对应的商相同。</>}
              en={<>Let <TeX src={`H \\le G`} />, <TeX src={`N \\triangleleft G`} />. Then <TeX src={`HN`} /> is a subgroup of G, <TeX src={`H \\cap N \\triangleleft H`} />, and<TeXBlock src={`(HN)/N \\;\\cong\\; H/(H \\cap N).`} />Drawn as a diamond lattice (vertices <TeX src={`HN,\\,H,\\,N,\\,H\\cap N`} />), the two diagonals give isomorphic quotients.</>}
            />
          </div>
        </div>
        <div className="gt-thm">
          <div className="gt-thm-title">{tr({ zh: '定理 20.5 — 第三同构 (商的商)', en: 'Theorem 20.5 — Third isomorphism (quotient of a quotient)'
        })}</div>
          <div className="gt-thm-body">
            <L
              zh={<>设 <TeX src={`K \\triangleleft N \\triangleleft G`} /> (K 也是 G 正规)。 则<TeXBlock src={`(G/K) \\;\\big/\\; (N/K) \\;\\cong\\; G/N.`} />「先商 K 再商 (N/K),等于直接商 N。」</>}
              en={<>Let <TeX src={`K \\triangleleft N \\triangleleft G`} /> (K also normal in G). Then<TeXBlock src={`(G/K) \\;\\big/\\; (N/K) \\;\\cong\\; G/N.`} />"Quotient by K, then by N/K, equals quotient by N."</>}
            />
          </div>
        </div>
        <p>
          <L
            zh={<>魔方上一个干净的应用:取 <TeX src={`H = \\langle U, D\\rangle`} /> (只允许 U、 D 转的所有状态), <TeX src={`N = [G,G]`} /> (偶 parity 状态)。 那么 <TeX src={`HN`} /> 是 「所有 ⟨U,D⟩ 加偶 parity」 状态;由第二同构定理</>}
            en={<>A clean cube application: take <TeX src={`H = \\langle U, D\\rangle`} /> (states reachable using only U and D), and <TeX src={`N = [G,G]`} /> (states of even parity). Then <TeX src={`HN`} /> consists of all "⟨U,D⟩-states with arbitrary parity adjust," and by the second isomorphism theorem</>}
          />
        </p>
        <TeXBlock src={`(HN)/[G,G] \\;\\cong\\; \\langle U,D\\rangle / \\bigl(\\langle U,D\\rangle \\cap [G,G]\\bigr).`} />
        <p>
          <L
            zh={<>右边的指数 [⟨U,D⟩ : ⟨U,D⟩ ∩ [G,G]] = 2,因为 U 和 D 各自是奇置换。 所以 HN 在 [G,G] 上恰好分两个陪集 —— 这给一个 「以 ⟨U,D⟩ 为基的奇偶检测」 直接证明。</>}
            en={<>The right-hand index [⟨U,D⟩ : ⟨U,D⟩ ∩ [G,G]] = 2, because each of U and D is itself an odd permutation. So HN partitions over [G,G] into exactly two cosets — a direct proof of the "⟨U,D⟩-based parity detector" used in many BLD methods.</>}
          />
        </p>
        <div className="gt-thm">
          <div className="gt-thm-title">{tr({ zh: '定理 20.6 — Lattice (对应) 定理', en: 'Theorem 20.6 — Correspondence (lattice) theorem'
        })}</div>
          <div className="gt-thm-body">
            <L
              zh={<>设 <TeX src={`N \\triangleleft G`} />,记 <TeX src={`\\pi : G \\twoheadrightarrow G/N`} /> 为自然投影。 则 <TeX src={`\\pi`} /> 在<strong>包含 N 的子群</strong>和 <TeX src={`G/N`} /> 的<strong>所有子群</strong>之间建立 <em>保序双射</em>:<TeXBlock src={`\\{\\,H \\;:\\; N \\le H \\le G\\,\\} \\;\\overset{\\sim}{\\longleftrightarrow}\\; \\{\\,\\bar{H} \\le G/N\\,\\}.`} />正规子群对应正规子群,指数保持。</>}
              en={<>Let <TeX src={`N \\triangleleft G`} />, <TeX src={`\\pi : G \\twoheadrightarrow G/N`} /> the natural projection. Then <TeX src={`\\pi`} /> gives an <em>order-preserving bijection</em> between <strong>subgroups of G containing N</strong> and <strong>all subgroups of G/N</strong>:<TeXBlock src={`\\{\\,H \\;:\\; N \\le H \\le G\\,\\} \\;\\overset{\\sim}{\\longleftrightarrow}\\; \\{\\,\\bar{H} \\le G/N\\,\\}.`} />Normal subgroups correspond to normal subgroups; indices are preserved.</>}
            />
          </div>
        </div>
        <p>
          <L
            zh={<>魔方上的应用:取 <TeX src={`N = [G,G]`} />, <TeX src={`G/N \\cong \\mathbb{Z}/2`} />。 ℤ/2 只有两个子群 ({'{e}'} 和它自己),所以包含 [G,G] 的 G 子群恰好两个:[G,G] 本身,和 G。 这就明确告诉我们 「介于 [G,G] 和 G 之间没有任何中间子群」 — G 在 sgn 这一比特上是 「不可细分」 的。</>}
            en={<>Application on the cube: with <TeX src={`N = [G,G]`} />, <TeX src={`G/N \\cong \\mathbb{Z}/2`} />. ℤ/2 has only two subgroups ({'{e}'} and itself), so there are exactly two subgroups of G containing [G,G]: namely [G,G] and G. This precisely says "no intermediate subgroup sits strictly between [G,G] and G" — the sgn bit is indivisible.</>}
          />
        </p>
        <div className="gt-aside" style={{ marginTop: 16 }}>
          <L
            zh={<>四个同构定理 (第一、 第二、 第三、 lattice) 把 「同态 ↔ 正规子群 ↔ 商群 ↔ 子群格」 全部钉在一张图上。 这是抽象代数最浓缩的诗:每一条都说 「商」 这个看似抽象的操作其实只是 「换语言看同一个对象」。</>}
            en={<>The four isomorphism theorems (first, second, third, lattice) lock "homomorphisms ↔ normal subgroups ↔ quotients ↔ subgroup lattice" together into a single diagram. The densest verse in abstract algebra: every line says that "taking a quotient" is just "re-naming the same object."</>}
          />
        </div>
      </GTSec>
  );
}
