/*
 * restricted-cube-solver — a MOVE-SET-PARAMETERIZED optimal solver for a RESTRICTED 3×3×3 (a subgroup of the
 * Rubik group generated by a chosen set of face turns). It is the reusable engine behind the siamese bonded
 * cubes (sia222 today; sia123 / sia113 will reuse it with different move masks). Given a piece-tracking move
 * model (the corners + edges a restricted generator set ever touches) and a set of pattern databases, it does
 * IDA* with an admissible PDB heuristic and returns a provably shortest solution in the chosen move metric.
 *
 * WHY THIS EXISTS — the siamese cubes are two 3×3×3s glued at a shared block, moving as one bonded body. The
 * bonded group is a DIRECT PRODUCT G = G_A × G_B (proven by measurement: A-tokens and B-tokens act on disjoint
 * cubie sets and all commute), and the shared block locks 3 faces of each cube, so each half is a restricted
 * ⟨gens⟩ 3×3×3. Because the halves are independent and commute, solving the bonded puzzle = split the scramble
 * into A-moves / B-moves, solve each half independently with this engine, concatenate → GLOBALLY OPTIMAL
 * (optimal_A + optimal_B). See lib/sia222-solver.ts for the sia222 specialization and the A/B split.
 *
 * PRIOR ART — restricted-⟨U,R,F⟩ optimal solving is the standard Korf / Kociemba IDA*-with-pattern-databases
 * approach (R.E. Korf, "Finding Optimal Solutions to Rubik's Cube Using Pattern Databases", AAAI 1997): a
 * corner PDB + two complementary 6-edge PDBs, h = max over the databases. We wrote the engine from scratch in
 * TS; the algorithm (IDA* + admissible additive/max PDB heuristic) is the textbook one. The puzzle geometry
 * and scramble model are borrowed from cstimer (cs0x7f/cstimer) — see credits + lib/sia222-solver.ts header.
 *
 * STATE / MOVE MODEL — a state is a flat Int32Array of NP "piece codes", code = pieceId*24 + rawOri (rawOri is
 * an index into the 24-element rotation group). The first NC slots are corners, the next NE are edges. A move
 * is `next[destSlot] = pieceId*24 + destOri` looked up from a precomputed flat action table act[slot*24+ori] =
 * destSlot*24+destOri. These tables are derived bit-exactly from the puzzle geometry OFFLINE and embedded as
 * data in the specialization (the engine itself is geometry-free). cornerTw[slot][rawOri]∈{0,1,2} and
 * edgeFl[slot][rawOri]∈{0,1} project rawOri to a twist / flip label, used ONLY to compute the injective PDB
 * ranks — moves are always applied on the raw code so they stay bit-exact.
 *
 * PDBs / TIER B — the corner orbit (here 3,674,160 for ⟨U,R,F⟩) and partial-edge orbits are BFS-able offline
 * but too slow to build in a browser tab (~40s). So the heavy PDBs are built OFFLINE (a build script) and
 * shipped as gzip; the browser fetches + inflates them into resident Uint8Array distance tables (per
 * solver/NONWCA_PUZZLE_LOOP.md §0.5 / §0.0 #10, the bic TIER-B pattern). The PDB byte arrays are DENSE
 * (indexed directly by rank), so lookup is O(1) and the heuristic is exact-distance-in-the-projection (always
 * admissible). h(state) = max over all loaded PDBs.
 */

// ── piece-tracking move model (geometry-free; the specialization supplies the tables) ──────────────
export interface RestrictedMoveModel {
  /** Number of tracked pieces (corners first, then edges). */
  NP: number;
  /** Number of tracked corners (slots 0..NC-1). */
  NC: number;
  /** Number of tracked edges (slots NC..NC+NE-1). */
  NE: number;
  /** Move token names in engine order (e.g. ["R","R2","R'","U",…]). */
  tokens: ReadonlyArray<string>;
  /** Per-token "axis"/face letter — consecutive same-axis moves are pruned in IDA*. */
  axes: ReadonlyArray<string>;
  /** Flat action tables: acts[t][slot*24+ori] = destSlot*24 + destOri. One per token. */
  acts: ReadonlyArray<Int32Array>;
  /**
   * Piece-keyed twist labels: cornerTwP[pieceId][slot][rawOri] ∈ {0,1,2}. The label is the index of rawOri
   * among the (exactly 3) orientations the corner CUBIE `pieceId` can have at `slot`, from a single-piece BFS.
   * Keying on the piece (not just the slot) is what makes the twist coordinate a consistent (admissible)
   * homomorphism — a per-slot-only label is NOT consistent across pieces. Indexed [piece][slot] = number[24].
   */
  cornerTwP: ReadonlyArray<ReadonlyArray<ReadonlyArray<number>>>;
  /** Piece-keyed flip labels: edgeFlP[edgePieceId][slot][rawOri] ∈ {0,1} (edgePieceId in NC..NP-1). */
  edgeFlP: ReadonlyArray<ReadonlyArray<ReadonlyArray<number>>>;
}

/**
 * Build a model from the embedded constants the specialization holds. cornerTwP / edgeFlP arrive piece-keyed
 * as sparse objects { [pieceId]: { [slot]: number[24] } } (only the slots a piece can reach) — we densify them
 * into number[NP][NP][24] arrays (unreachable cells stay -1) for O(1) indexing.
 */
export function buildMoveModel(raw: {
  NP: number; NC: number; NE: number;
  tokens: ReadonlyArray<string>; axes: ReadonlyArray<string>;
  acts: ReadonlyArray<ReadonlyArray<number>>;
  cornerTwP: Record<string, Record<string, ReadonlyArray<number>>>;
  edgeFlP: Record<string, Record<string, ReadonlyArray<number>>>;
}): RestrictedMoveModel {
  const NP = raw.NP;
  const densify = (src: Record<string, Record<string, ReadonlyArray<number>>>): number[][][] => {
    const out: number[][][] = [];
    for (let p = 0; p < NP; p++) {
      const slots: number[][] = [];
      for (let s = 0; s < NP; s++) slots.push(new Array<number>(24).fill(-1));
      const byPiece = src[String(p)];
      if (byPiece) for (const sk of Object.keys(byPiece)) slots[Number(sk)] = [...byPiece[sk]];
      out.push(slots);
    }
    return out;
  };
  return {
    NP: raw.NP, NC: raw.NC, NE: raw.NE,
    tokens: raw.tokens, axes: raw.axes,
    acts: raw.acts.map((a) => Int32Array.from(a)),
    cornerTwP: densify(raw.cornerTwP), edgeFlP: densify(raw.edgeFlP),
  };
}

/** The solved-state vector: piece i sits at slot i with orientation 0. */
export function solvedVec(m: RestrictedMoveModel): Int32Array {
  const v = new Int32Array(m.NP);
  for (let j = 0; j < m.NP; j++) v[j] = j * 24;
  return v;
}

/** Apply a token (by engine index) to a state vector, returning a fresh vector. */
export function applyTokenVec(m: RestrictedMoveModel, t: number, v: Int32Array): Int32Array {
  const act = m.acts[t];
  const out = new Int32Array(m.NP);
  for (let j = 0; j < m.NP; j++) {
    const code = v[j];
    const o = code % 24;
    const piece = (code / 24) | 0;
    const mm = act[j * 24 + o];
    out[(mm / 24) | 0] = piece * 24 + (mm % 24);
  }
  return out;
}

/** True iff the vector is solved. */
export function isSolvedVec(m: RestrictedMoveModel, v: Int32Array): boolean {
  for (let j = 0; j < m.NP; j++) if (v[j] !== j * 24) return false;
  return true;
}

// ── PDB rank functions (injective coordinate → dense byte index) ────────────────────────────────
const FACT = (() => { const f = [1]; for (let i = 1; i <= 12; i++) f[i] = f[i - 1] * i; return f; })();

/** Corner PDB rank: perm rank of the 7-corner permutation × 3^NC twist. Dense size = NC! · 3^NC. */
export function cornerRank(m: RestrictedMoveModel, v: Int32Array): number {
  const NC = m.NC;
  // permutation rank (which piece sits at each corner slot)
  let r = 0;
  const seen = new Array<boolean>(NC).fill(false);
  const cp = new Array<number>(NC);
  for (let j = 0; j < NC; j++) cp[j] = (v[j] / 24) | 0;
  for (let i = 0; i < NC; i++) {
    let s = 0;
    for (let k = 0; k < cp[i]; k++) if (!seen[k]) s++;
    r = r * (NC - i) + s;
    seen[cp[i]] = true;
  }
  let tw = 0;
  for (let j = 0; j < NC; j++) tw = tw * 3 + m.cornerTwP[cp[j]][j][v[j] % 24];
  return r * pow3(NC) + tw;
}
function pow3(n: number): number { let p = 1; for (let i = 0; i < n; i++) p *= 3; return p; }
export function cornerRankSpace(m: RestrictedMoveModel): number { return FACT[m.NC] * pow3(m.NC); }

/**
 * A 6-edge PDB: track WHERE 6 chosen edge pieces sit among the NE edge slots (a partial permutation) + their
 * flips. Dense size = NE·(NE-1)·…·(NE-5) · 2^6. The chosen pieces are given as engine piece ids (NC..NC+NE-1).
 */
export interface EdgePdbDef {
  /** 6 edge piece ids (NC..NC+NE-1) this PDB tracks. */
  pieces: ReadonlyArray<number>;
  /** Dense byte-array size (positions·flips). */
  size: number;
}
export function makeEdgePdbDef(m: RestrictedMoveModel, pieces: ReadonlyArray<number>): EdgePdbDef {
  const k = pieces.length;
  let pos = 1;
  for (let i = 0; i < k; i++) pos *= (m.NE - i);
  return { pieces, size: pos * (1 << k) };
}
/** Rank a state into an edge PDB's dense index. */
export function edgeRank(m: RestrictedMoveModel, def: EdgePdbDef, v: Int32Array): number {
  const k = def.pieces.length;
  const NC = m.NC, NE = m.NE;
  const order = [...def.pieces].sort((a, b) => a - b);
  const pos = new Map<number, number>(); order.forEach((p, i) => pos.set(p, i));
  const sl = new Array<number>(k), fl = new Array<number>(k);
  for (let j = 0; j < NE; j++) {
    const code = v[NC + j];
    const piece = (code / 24) | 0;
    if (pos.has(piece)) { const i = pos.get(piece)!; sl[i] = j; fl[i] = m.edgeFlP[piece][NC + j][code % 24]; }
  }
  let r = 0;
  const used = new Array<boolean>(NE).fill(false);
  for (let i = 0; i < k; i++) {
    let sm = 0;
    for (let s = 0; s < sl[i]; s++) if (!used[s]) sm++;
    r = r * (NE - i) + sm;
    used[sl[i]] = true;
  }
  let f = 0;
  for (let i = 0; i < k; i++) f = f * 2 + fl[i];
  return r * (1 << k) + f;
}

// ── pattern databases (resident dense byte arrays) ──────────────────────────────────────────────
export interface RestrictedPdbs {
  corner: Uint8Array;       // dense, indexed by cornerRank
  edges: { def: EdgePdbDef; dist: Uint8Array }[]; // each dense, indexed by edgeRank(def, …)
}

/** OFFLINE: BFS-from-solved over the corner projection → exact distances. Used by the build script + tests. */
export function buildCornerPdb(m: RestrictedMoveModel): Uint8Array {
  const size = cornerRankSpace(m);
  const dist = new Uint8Array(size).fill(255);
  const start = solvedVec(m);
  dist[cornerRank(m, start)] = 0;
  let frontier: Int32Array[] = [start];
  let d = 0;
  while (frontier.length) {
    const next: Int32Array[] = [];
    for (const v of frontier) {
      for (let t = 0; t < m.tokens.length; t++) {
        const o = applyTokenVec(m, t, v);
        const r = cornerRank(m, o);
        if (dist[r] === 255) { dist[r] = d + 1; next.push(o); }
      }
    }
    frontier = next; d++;
  }
  return dist;
}

/** OFFLINE: BFS-from-solved over a 6-edge projection → exact distances. */
export function buildEdgePdb(m: RestrictedMoveModel, def: EdgePdbDef): Uint8Array {
  const dist = new Uint8Array(def.size).fill(255);
  const start = solvedVec(m);
  dist[edgeRank(m, def, start)] = 0;
  let frontier: Int32Array[] = [start];
  let d = 0;
  while (frontier.length) {
    const next: Int32Array[] = [];
    for (const v of frontier) {
      for (let t = 0; t < m.tokens.length; t++) {
        const o = applyTokenVec(m, t, v);
        const r = edgeRank(m, def, o);
        if (dist[r] === 255) { dist[r] = d + 1; next.push(o); }
      }
    }
    frontier = next; d++;
  }
  return dist;
}

/** OFFLINE: build all PDBs for a model given the edge-piece groupings. */
export function buildPdbs(m: RestrictedMoveModel, edgeGroups: ReadonlyArray<ReadonlyArray<number>>): RestrictedPdbs {
  const corner = buildCornerPdb(m);
  const edges = edgeGroups.map((g) => { const def = makeEdgePdbDef(m, g); return { def, dist: buildEdgePdb(m, def) }; });
  return { corner, edges };
}

/** Admissible heuristic = max over the corner PDB and every edge PDB. */
export function heuristic(m: RestrictedMoveModel, pdbs: RestrictedPdbs, v: Int32Array): number {
  let h = pdbs.corner[cornerRank(m, v)];
  for (const e of pdbs.edges) {
    const d = e.dist[edgeRank(m, e.def, v)];
    if (d > h) h = d;
  }
  return h;
}

// ── IDA* (provably optimal in the face-turn metric) ─────────────────────────────────────────────
export interface SolveResult {
  /** Solution as engine token indices. */
  path: number[];
  /** Optimal length (== path.length). */
  length: number;
  /** Search nodes expanded (diagnostic). */
  nodes: number;
}

/**
 * IDA* with the PDB heuristic. Returns the provably shortest solution, or null if `nodeCap` is exceeded before
 * a solution is found (only possible for pathologically deep states well beyond real scrambles — the caller
 * decides what to do). `maxDepth` bounds the iterative deepening.
 */
export function idaSolve(
  m: RestrictedMoveModel, pdbs: RestrictedPdbs, start: Int32Array,
  opts: { maxDepth?: number; nodeCap?: number } = {},
): SolveResult | null {
  const maxDepth = opts.maxDepth ?? 40;
  const nodeCap = opts.nodeCap ?? Number.POSITIVE_INFINITY;
  const NT = m.tokens.length;
  const axes = m.axes;
  let nodes = 0;
  let capped = false;

  const path: number[] = [];
  function dfs(v: Int32Array, g: number, bound: number, lastAxis: string): boolean {
    const h = heuristic(m, pdbs, v);
    if (g + h > bound) return false;
    if (h === 0 && isSolvedVec(m, v)) return true;
    nodes++;
    if (nodes > nodeCap) { capped = true; return false; }
    for (let t = 0; t < NT; t++) {
      const ax = axes[t];
      if (ax === lastAxis) continue; // same-face consecutive moves are redundant
      const nv = applyTokenVec(m, t, v);
      path.push(t);
      if (dfs(nv, g + 1, bound, ax)) return true;
      path.pop();
      if (capped) return false;
    }
    return false;
  }

  for (let bound = heuristic(m, pdbs, start); bound <= maxDepth; bound++) {
    nodes = 0; capped = false; path.length = 0;
    if (dfs(start, 0, bound, '')) return { path: [...path], length: path.length, nodes };
    if (capped) return null;
  }
  return null;
}

/** Convenience: solve a state to a list of token NAMES. */
export function solveToNames(m: RestrictedMoveModel, pdbs: RestrictedPdbs, start: Int32Array,
  opts?: { maxDepth?: number; nodeCap?: number }): { names: string[]; length: number; nodes: number } | null {
  const r = idaSolve(m, pdbs, start, opts);
  if (!r) return null;
  return { names: r.path.map((t) => m.tokens[t]), length: r.length, nodes: r.nodes };
}
