\set ON_ERROR_STOP on
BEGIN;
CREATE SCHEMA auth_apple_token_fixture;
SET LOCAL search_path = auth_apple_token_fixture, public;
CREATE TABLE app_users (id BIGINT PRIMARY KEY);
CREATE TABLE auth_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  provider VARCHAR(16) NOT NULL,
  provider_uid VARCHAR(320) NOT NULL,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_auth_identity UNIQUE(provider, provider_uid)
);
INSERT INTO app_users VALUES (1), (2);
INSERT INTO auth_identities(user_id, provider, provider_uid) VALUES (1, 'email', 'test@example.test');
\ir ../../migrations/0231_auth_apple_token.sql
INSERT INTO auth_identities(user_id, provider, provider_uid, apple_refresh_token_encrypted, apple_token_key_version)
VALUES (1, 'apple', 'test-apple-sub', decode(repeat('ab', 40), 'hex'), 1);
DO $$
BEGIN
  -- Existing non-Apple rows survive, and tokens never leave their owning identity.
  IF (SELECT COUNT(*) FROM auth_identities WHERE provider = 'email' AND apple_refresh_token_encrypted IS NULL) <> 1 THEN
    RAISE EXCEPTION 'legacy identity changed';
  END IF;
  BEGIN
    UPDATE auth_identities SET apple_token_key_version = NULL WHERE provider = 'apple';
    RAISE EXCEPTION 'accepted encrypted token without version';
  EXCEPTION WHEN check_violation THEN NULL;
  END;
  BEGIN
    UPDATE auth_identities SET apple_refresh_token_encrypted = NULL WHERE provider = 'apple';
    RAISE EXCEPTION 'accepted version without encrypted token';
  EXCEPTION WHEN check_violation THEN NULL;
  END;
  BEGIN
    UPDATE auth_identities SET apple_token_key_version = 2 WHERE provider = 'apple';
    RAISE EXCEPTION 'accepted unsupported key version';
  EXCEPTION WHEN check_violation THEN NULL;
  END;
  BEGIN
    UPDATE auth_identities SET apple_refresh_token_encrypted = decode('ab', 'hex') WHERE provider = 'apple';
    RAISE EXCEPTION 'accepted truncated envelope';
  EXCEPTION WHEN check_violation THEN NULL;
  END;
  BEGIN
    UPDATE auth_identities SET provider = 'google' WHERE provider = 'apple';
    RAISE EXCEPTION 'accepted Apple token on another provider';
  EXCEPTION WHEN check_violation THEN NULL;
  END;
  BEGIN
    INSERT INTO app_users VALUES (3);
    INSERT INTO auth_identities(user_id, provider, provider_uid, apple_refresh_token_encrypted, apple_token_key_version)
    VALUES (3, 'apple', 'failed-token-sub', decode('ab', 'hex'), 1);
    RAISE EXCEPTION 'accepted invalid credential';
  EXCEPTION WHEN check_violation THEN NULL;
  END;
  IF EXISTS (SELECT 1 FROM app_users WHERE id = 3) OR EXISTS (SELECT 1 FROM auth_identities WHERE provider_uid = 'failed-token-sub') THEN
    RAISE EXCEPTION 'credential failure left a partial account or identity';
  END IF;
END;
$$;
-- Existing merge moves the identity row, retaining the encrypted revocation credential.
UPDATE auth_identities SET user_id = 2 WHERE provider = 'apple';
DELETE FROM app_users WHERE id = 2;
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM auth_identities WHERE provider = 'apple') THEN
    RAISE EXCEPTION 'account deletion retained Apple token';
  END IF;
END; $$;
ROLLBACK;
