// One-shot generator: walks svg/{event,unofficial,penalty}/*.svg and emits the
// literal-string Record<string,string> maps. Replaces Vite's
// import.meta.glob('./svg/{...}/*.svg', { query: '?raw', eager: true }).
// Re-run via: pnpm --filter @cuberoot/event-icon generate
//
// THREE maps, on purpose:
//  · svg-map-event.ts — WCA projects, independently importable by native apps.
//  · svg-map-unofficial.ts — non-WCA projects, loaded by generic <CubingIcon>.
//  · svg-map-penalty.ts (penalty, ~168KB) — the regulation penalty illustrations
//    are 20-27KB each (full drawings, not glyphs) and nothing renders them through
//    CubingIcon; only the /icon gallery enumerates them. Keeping them in the main
//    map put 168KB of never-drawn markup into /timer and every other page.
//    Add a penalty consumer? Import svg-map-penalty.ts there explicitly.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

/** Emit `svg/<kind>/*.svg` for each kind in `kinds` as one exported record. */
function emit(file, exportName, kinds, note) {
  const out = [
    '// Auto-generated by gen-svg-map.mjs — do not edit by hand.',
    '// Re-run the generator if SVGs are added/changed.',
    `// ${note}`,
    '',
    `export const ${exportName}: Record<string, string> = {`,
  ];
  for (const kind of kinds) {
    const dir = path.join(here, 'svg', kind);
    if (!fs.existsSync(dir)) continue;
    for (const f of fs.readdirSync(dir).sort()) {
      if (!f.endsWith('.svg')) continue;
      const name = f.replace(/\.svg$/, '');
      const raw = fs.readFileSync(path.join(dir, f), 'utf8').trim();
      // Use a template literal; escape backslash, backtick, and ${ — nothing else.
      const escaped = raw
        .replace(/\\/g, '\\\\')
        .replace(/`/g, '\\`')
        .replace(/\$\{/g, '\\${');
      out.push(`  ${JSON.stringify(`${kind}-${name}`)}: \`${escaped}\`,`);
    }
  }
  out.push('};', '');
  fs.writeFileSync(path.join(here, 'src', file), out.join('\n'));
  console.log(`wrote ${file}`);
}

emit('svg-map-event.ts', 'EVENT_SVG_BY_KEY', ['event'],
  'WCA event set — read by the narrow <EventIcon> entry.');
emit('svg-map-unofficial.ts', 'UNOFFICIAL_SVG_BY_KEY', ['unofficial'],
  'Unofficial event set — read by the generic <CubingIcon> entry.');
emit('svg-map-penalty.ts', 'PENALTY_SVG_BY_KEY', ['penalty'],
  'Regulation penalty illustrations — import only where they are actually drawn (/icon).');
