/**
 * /wca 索引页:每条 stat 的 lucide 图标映射(按 stats/index.json 的 id)。
 * 未在表中的 id 由调用处回退到所属分类的图标(见 page.tsx)。
 */
import {
  Trophy, Gauge, Layers, Crown, CircleSlash, Sparkles, Sigma, Repeat,
  Brain, Star, BarChart3, TrendingUp, CalendarCheck, GitCompare, ListOrdered,
  Frown, Hash, Hourglass, Flag, Medal, Users, TrendingDown, CalendarDays,
  Route, House, CalendarRange, CalendarClock, Plane, CheckCheck, EyeOff,
  Globe2, MapPin, Type, Grid2x2, LayoutGrid, Boxes, Map as MapIcon, Globe,
  Percent, UserMinus, Award, Gavel, Zap, Eye, UserRound,
  type LucideIcon,
} from 'lucide-react';

export const STAT_ICONS: Record<string, LucideIcon> = {
  // 世界纪录分析
  wr_current: Trophy,
  wr_metric: Gauge,
  wr_aoxr: Layers,
  wr_dominance: Crown,
  wr_non_pr: CircleSlash,
  wr_newcomer: Sparkles,
  average_of: Sigma,
  consecutive_sub_5_average: Repeat,
  // 成绩与纪录
  best_potential_fmc_mean: Brain,
  best_round: Star,
  most_frequent_results: BarChart3,
  moving_average: TrendingUp,
  date_match_pr: CalendarCheck,
  smallest_diff_between_single_and_average: GitCompare,
  yearly_rankings: ListOrdered,
  // 领奖台与荣誉
  best_result_off_podium: Frown,
  complete_competition_winners: Crown,
  most_4th_places: Hash,
  most_competitions_before_winning: Hourglass,
  most_finals: Flag,
  most_podiums_at_single_competition: Medal,
  most_podiums_together: Users,
  worst_result_on_podium: TrendingDown,
  // 选手经历
  competitions_per_year_by_person: CalendarDays,
  longest_competitions_path: Route,
  longest_streak_of_competitions_in_own_country: House,
  longest_streak_of_personal_records: TrendingUp,
  longest_streak_of_podiums: Medal,
  longest_time_to_sub_10: Hourglass,
  most_attended_competitions_in_single_month: CalendarRange,
  most_attended_competitions_in_single_week: CalendarClock,
  most_competitions_abroad: Plane,
  most_completed_solves: CheckCheck,
  most_distinct_dates_competed_on: CalendarCheck,
  most_solves_before_bld_success: EyeOff,
  most_visited_continents: Globe2,
  most_visited_countries: MapPin,
  name_parts_count: Type,
  shortest_time_to_reach_milestone_in_comps_count: Flag,
  shortest_time_to_get_all_singles: Grid2x2,
  shortest_time_to_get_all_singles_and_averages: LayoutGrid,
  // 赛事统计
  average_event_count_by_competition: Boxes,
  competition_days_count_by_region: MapIcon,
  competitions_count_by_week: CalendarClock,
  competitions_per_year_by_country: Globe,
  dnf_rate_by_event: Percent,
  fewest_competitors_contest: UserMinus,
  most_records_at_single_competition: Award,
  // 纪录与国家
  best_medal_collection_from_abroad_by_country: Medal,
  best_medal_collection_from_abroad_by_person: Award,
  current_world_records_by_country: Flag,
  delegated_competition_per_year: Gavel,
  first_r_is_wr: Zap,
  longest_standing_records: Hourglass,
  longest_streak_of_world_records: Repeat,
  most_delegated_competitions: Gavel,
  potentially_seen_world_records: Eye,
  records_in_most_events: Boxes,
  winned_week_count: CalendarCheck,
  world_championship_podiums_by_country: Medal,
  world_championship_podiums_by_person: Trophy,
  world_championship_records: Trophy,
  world_records_by_country: Globe2,
  world_records_by_person: UserRound,
};
