// Two collections of 24. Names describe what the animal actually does.
const rows = [
  ['idle','歇一会儿','Taking a break','放松下来，看看四周。','Settles down and watches the world.',4.2],
  ['hello','打招呼','Hello','轻轻晃一晃，向你打个招呼。','Gives a little greeting, then settles down.',3.6],
  ['walk','四处逛逛','Exploring','往前挪一点，停下来看看四周。','Moves forward a little and stops to look around.',4.2],
  ['look-around','东张西望','Looking around','先看左边，再看右边。','Looks left, then right.',4.1],
  ['nod','点点头','Yes','认真地点两下头。','Two deliberate little nods.',3.1],
  ['shake-head','摇摇头','No','左右摇头，再看向你。','Shakes its head, then looks back at you.',3.3],
  ['curious','歪头看看','Curious','歪着头凑近一点，好像发现了什么。','Tilts its head and leans closer.',3.8],
  ['surprised','吓一跳','A surprise','突然一愣，往后缩一下，又小心地探头。','Startles, pulls back, then takes another look.',3.4],
  ['happy','好开心','So happy','身子轻轻弹两下，开心地晃一晃。','Two happy bounces and a little wiggle.',3.6],
  ['shy','不好意思','Feeling shy','低下头，悄悄抬眼看你。','Looks down, then sneaks a glance at you.',4.0],
  ['proud','有点得意','Feeling proud','抬起头，得意地晃一晃。','Lifts its head with a small, pleased sway.',3.8],
  ['sad','有点难过','Feeling low','垂下头，慢慢缩成一团。','Lowers its head and curls in a little.',4.5],
  ['angry','生气了','Grumpy','绷住身子，气呼呼地抖两下。','Tenses up and gives two grumpy shakes.',3.4],
  ['thanks','谢谢你','Thank you','低头鞠个躬，再抬头看你。','Bows, then looks up at you.',3.8],
  ['cheer','加油','You can do it','精神一振，一下一下给你打气。','Perks up and cheers you on.',3.7],
  ['heart','喜欢你','For you','往前凑一点，送你一颗小爱心。','Leans closer and sends a little heart.',4.1],
  ['stretch','伸个懒腰','A good stretch','慢慢伸展开，再舒舒服服地收回来。','Stretches out and settles comfortably.',4.5],
  ['yawn','打哈欠','Yawning','头往后仰，打完哈欠眯一下眼。','Tips its head back for a yawn, then blinks.',4.4],
  ['doze','打瞌睡','Nodding off','脑袋一点一点，差点睡着又抬起来。','Nods off, catches itself, then droops again.',4.8],
  ['sleep','睡着了','Fast asleep','安静睡着，身子随着呼吸轻轻起伏。','Sleeps peacefully with a gentle breathing rhythm.',5.2],
  ['wake','睡醒了','Waking up','睁开眼，伸展开，慢慢恢复精神。','Opens its eyes, stretches, and slowly wakes up.',4.3],
  ['groom','整理一下','Tidying up','低头整理自己，抖一抖再放松下来。','Tidies itself, gives a shake, and settles.',4.2],
  ['scratch','挠挠痒','An itchy spot','侧过身挠两下，终于舒服了。','Turns to scratch an itch, then relaxes.',3.8],
  ['sneeze','打喷嚏','Achoo','先憋住，突然一个喷嚏，自己也愣住了。','Holds it in, sneezes, then looks a little surprised.',3.6],
  ['read','看书','Reading','低头读书，翻过一页，接着往下看。','Reads, turns a page, and keeps going.',5.0],
  ['letter','收到信了','A letter','凑近信封，打开后认真看一看。','Leans toward an envelope and looks inside.',4.4],
  ['draw','画画','Drawing','在纸上画几笔，退后看看自己的作品。','Makes a few marks, then pulls back to admire them.',4.6],
  ['music','听音乐','Listening to music','跟着拍子点头，越听越投入。','Nods to the beat and gets into the music.',4.0],
  ['drum','打节拍','Keeping the beat','左右交替敲出一段小节奏。','Taps out a short rhythm, left then right.',3.8],
  ['ball','玩球','Playing ball','碰一下小球，看它滚远，再把它拦住。','Nudges a ball, watches it roll, and stops it.',4.5],
  ['bubbles','看泡泡','Watching bubbles','跟着泡泡往上看，破掉时眨一下眼。','Follows a bubble upward and blinks when it pops.',4.4],
  ['butterfly','追蝴蝶','Following a butterfly','跟着蝴蝶转头，扑了个空。','Follows a butterfly and just misses it.',4.3],
  ['leaf','接落叶','A falling leaf','抬头等叶子落下来，再轻轻碰一碰。','Watches a leaf fall and gives it a gentle nudge.',4.4],
  ['flower','闻花香','Smelling a flower','凑近闻一闻，满足地闭上眼。','Leans in to smell a flower and closes its eyes.',4.2],
  ['water','玩水','Making a splash','试着碰一下水，溅起来后赶紧缩回去。','Tests the water and pulls back from the splash.',4.0],
  ['rain','躲雨','Under an umbrella','往伞下面挪一挪，听雨落下来。','Moves under an umbrella and listens to the rain.',4.7],
  ['wind','起风了','A gust of wind','被风吹得歪一下，稳住后抖掉一片叶子。','Leans into the wind, then shakes off a leaf.',4.1],
  ['star','看星星','Stargazing','抬头看着星星，轻轻伸过去。','Looks up at a star and reaches toward it.',4.4],
  ['lantern','看灯笼','A little lantern','看灯笼左右摇，脑袋也跟着摆。','Watches a lantern sway from side to side.',4.5],
  ['gift','拆礼物','Opening a present','小心碰开盒盖，惊喜地往里看。','Lifts the lid and peeks inside with delight.',4.6],
  ['snack','吃点心','Snack time','凑近吃一小口，满足地晃一下。','Takes a small bite and gives a contented wiggle.',4.3],
  ['tea','喝口水','A little drink','低头喝一口，再抬起头慢慢咽下。','Leans down for a sip, then lifts its head.',4.5],
  ['balance','稳住了','Keeping balance','晃到左边又晃到右边，总算稳住了。','Wobbles left and right, then finds its balance.',4.2],
  ['peek','探个头','Peeking out','从叶子后面探头，停一下，又缩回去。','Peeks out from behind a leaf, pauses, and hides again.',4.4],
  ['chase','追过去','Chasing a ribbon','盯住飘动的丝带，追过去又扑了个空。','Chases a fluttering ribbon and just misses it.',4.1],
  ['hide','藏起来','Hide and seek','缩到叶子后面，忍不住又偷偷看一眼。','Hides behind a leaf, then sneaks another look.',4.5],
  ['goodnight','晚安','Good night','晃一晃道个晚安，靠着小枕头慢慢闭上眼。','Gives a little sway, then rests against a pillow.',5.0],
  ['celebrate','庆祝一下','Time to celebrate','身子轻轻一弹，跟着彩纸转一转。','Bounces and turns as confetti falls.',4.2],
];
export const ORIGINAL_SCENES = rows.map(([id,zh,en,description,descriptionEn,duration],index)=>({id,zh,en,description,descriptionEn,duration,poster:.56,collection:index<24?'daily':'play'}));
if (ORIGINAL_SCENES.length !== 48 || new Set(rows.map(x=>x[0])).size!==48) throw Error('Expected 48 different stories');
