/**
 * Mock data for /memo/colpi/.
 *
 * Real coLPI is crowdsourced (~44k words across 40+ languages); this page is a UI clone for
 * demo/portfolio purposes. The pair → words map below is hand-curated English samples
 * (most realistic letter pairs people use in BLD memo).
 */

export const ALPHABET = [
  'A','B','C','D','E','F','G','H','I','J','K','L','M',
  'N','O','P','Q','R','S','T','U','V','W','X','Y','Z',
  'ʧ',
];

export type Category = 'unspecified' | 'object' | 'person';

/** Map from 2-letter pair to up to 3 sample words. Missing entries render as empty (grey). */
export const PAIRS: Record<string, string[]> = {
  // A_
  AA: ['AA BATTERY', 'AARON', 'AARDVARK'],
  AB: ['ABS', 'ABACUS', 'ABBA'],
  AC: ['AIR CONDITIONER', 'ACE', 'ACORN'],
  AD: ['AD', 'ANDROID', 'ADHD'],
  AE: ['AEROPLANE', 'EINSTEIN', 'APPLE'],
  AF: ['AFRO', 'AFRICA', 'AFK'],
  AG: ['ANGEL', 'SILVER', 'ALLIGATOR'],
  AH: ['ASH', 'AIR HOCKEY', 'AIRHORN'],
  AI: ['AI', 'ARTIFICIAL INTELLIGENCE', 'AIR'],
  AJ: ['APPLE JUICE', 'AJAX', 'AJ'],
  AK: ['AK-47', 'ALASKA'],
  AL: ['ALIEN', 'ALL', 'WEIRD AL'],
  AM: ['AMMO', 'ARMOR', 'ARM'],
  AN: ['ANT', 'ANVIL', 'ANAKIN'],
  AO: ['AORTA', 'ANNOYING ORANGE'],
  AP: ['APPLE', 'APP', 'APE'],
  AQ: ['AQUARIUM', 'AQUA', 'AQUAMAN'],
  AR: ['ARROW', 'AIR', 'AUGMENTED REALITY'],
  AS: ['ASTRONAUT', 'ASIA'],
  AT: ['ATOM', 'AT (@)', 'ATM'],
  AU: ['GOLD', 'AUSTRALIA', 'AMONG US'],
  AV: ['AVOCADO', 'AVATAR'],
  AW: ['AWWW', 'ALAN WALKER', 'ARROW'],
  AX: ['AXE', 'AJAX AMSTERDAM'],
  AY: ['AYY LMAO', 'JAY'],
  AZ: ['ARIZONA', 'A-Z DICTIONARY', 'AZTEC'],
  // B_
  BA: ['BANANA', 'BASKETBALL'],
  BB: ['BABY', 'BIG BEN', 'BOMB'],
  BC: ['BACON', 'BARCODE'],
  BD: ['BED', 'BAD', 'BIRD'],
  BE: ['BEE', 'BELT', 'BEETLE'],
  BF: ['BLINDFOLD', 'BEEF', 'BOYFRIEND'],
  BG: ['BAG', 'BUG', 'BIG'],
  BH: ['BEEHIVE', 'BATH'],
  BI: ['BIBLE', 'BIKINI'],
  BJ: ['BANJO'],
  BK: ['BIKE', 'BACKPACK'],
  BL: ['BALL', 'BLUE', 'BULL'],
  BM: ['BOMB', 'BMW', 'BMX'],
  BN: ['BONE', 'BUN', 'BIN'],
  BO: ['BOOK', 'BOOT', 'BOAT'],
  BP: ['BACKPACK', 'BANK PIN'],
  BR: ['BRICK', 'BREAD', 'BRO'],
  BS: ['BUS', 'BSOD', 'BASS'],
  BT: ['BAT', 'BUTTER', 'BLUETOOTH'],
  BU: ['BUNNY', 'BULB'],
  BY: ['BABY', 'BOY'],
  // C_
  CA: ['CAT', 'CAR', 'CAKE'],
  CB: ['CUBE', 'CRYBABY'],
  CC: ['CC', 'COSTCO'],
  CD: ['CD', 'CANDY'],
  CE: ['CELLO', 'CEMENT'],
  CF: ['COFFEE', 'CFOP'],
  CG: ['CAGE', 'CARGO'],
  CH: ['CHAIR', 'CHEESE'],
  CI: ['CIGAR', 'CINEMA'],
  CK: ['CAKE', 'CLOCK'],
  CL: ['CLOCK', 'CLOUD', 'CLAW'],
  CM: ['CAMEL', 'CAMERA'],
  CN: ['CNN', 'CANNON', 'CHINA'],
  CO: ['COIN', 'COKE', 'COW'],
  CP: ['CAP', 'CUP', 'CPU'],
  CR: ['CROWN', 'CRAB'],
  CS: ['COSTCO', 'CSGO'],
  CT: ['CAT', 'COTTON', 'COURT'],
  CU: ['CUP', 'COPPER', 'CUTE'],
  CV: ['CV', 'CONVOY'],
  CW: ['COW'],
  CX: ['CXC'],
  CY: ['CYCLE', 'CYANIDE', 'CYBORG'],
  CZ: ['CZAR', 'CZECH'],
  // D_
  DA: ['DAD', 'DAGGER'],
  DB: ['DB COOPER', 'DUMBBELL'],
  DC: ['DC COMICS', 'DEACON'],
  DD: ['DODO'],
  DE: ['DESK', 'DEER', 'DENT'],
  DF: ['DUFFEL'],
  DG: ['DOG', 'DUNGEON'],
  DI: ['DICE', 'DINOSAUR'],
  DJ: ['DJ', 'DJANGO'],
  DK: ['DUCK', 'DARK'],
  DL: ['DOLL', 'DALI'],
  DM: ['DOOM', 'DAMP'],
  DN: ['DONUT', 'DEAN'],
  DO: ['DOOR', 'DOUGHNUT'],
  DP: ['DOPE', 'DIPPER'],
  DR: ['DRUM', 'DRAGON'],
  DS: ['NINTENDO DS', 'DESK'],
  DT: ['DART', 'DIRT'],
  DU: ['DUMBBELL', 'DUDE'],
  DV: ['DVD', 'DIVE'],
  DW: ['DAWN', 'DWARF'],
  DY: ['DYE', 'DYNAMITE'],
  // E_
  EA: ['EAR', 'EASEL'],
  EB: ['EBAY', 'EBONY'],
  EC: ['ECLIPSE', 'ECHO'],
  ED: ['ED SHEERAN', 'EDISON'],
  EF: ['EFFEL TOWER', 'EFL'],
  EG: ['EGG', 'EGYPT'],
  EH: ['EHRMAN'],
  EI: ['EIFFEL TOWER', 'EINSTEIN'],
  EL: ['ELEPHANT', 'ELF'],
  EM: ['EMU', 'EMERALD', 'EMOJI'],
  EN: ['ENGINE', 'ENVELOPE'],
  EP: ['EPIC', 'EPI PEN'],
  EQ: ['EQUALIZER', 'EQUATION'],
  ER: ['ERASER', 'ERROR'],
  ES: ['ESPRESSO', 'ESCAPE'],
  ET: ['E.T.', 'ETHERNET'],
  EU: ['EUROPE', 'EURO'],
  EV: ['EVE', 'ELEVATOR'],
  EW: ['EWE', 'EWOK'],
  EX: ['EXIT', 'EX', 'EXCALIBUR'],
  EY: ['EYE', 'EYEBALL'],
  // F_
  FA: ['FAN', 'FACE'],
  FB: ['FACEBOOK', 'FBI'],
  FC: ['FACE', 'FCC'],
  FD: ['FROG DOG'],
  FE: ['IRON', 'FENCE', 'FEMUR'],
  FF: ['FIREFOX', 'FFXIV'],
  FG: ['FROG', 'FUGU'],
  FH: ['FISH HOOK'],
  FI: ['FIRE', 'FINGER'],
  FK: ['FORK'],
  FL: ['FLOWER', 'FLAG'],
  FM: ['FM RADIO', 'FAMILY'],
  FN: ['FAN', 'FN MEKA'],
  FO: ['FOOD', 'FOX', 'FORK'],
  FP: ['FROG PRINCE'],
  FR: ['FROG', 'FROST'],
  FS: ['FISH', 'FENCE'],
  FT: ['FOOT', 'FORT'],
  FU: ['FUR', 'FUSE'],
  FW: ['FIREWORK', 'FORWARD'],
  FX: ['FOX', 'SPECIAL FX'],
  FY: ['FYI'],
  // G_
  GA: ['GARLIC', 'GAS'],
  GB: ['GIGABYTE', 'GAMEBOY'],
  GC: ['GAS CAN'],
  GD: ['GOOD', 'GUARD'],
  GF: ['GIRLFRIEND', 'GOLF'],
  GG: ['GIGGLE', 'GG'],
  GH: ['GHOST', 'GHANA'],
  GI: ['GI JOE', 'GIN'],
  GK: ['GOALKEEPER'],
  GL: ['GLUE', 'GLOVE', 'GIRL'],
  GM: ['GUM', 'GAMEMASTER'],
  GN: ['GENIE', 'GUN'],
  GO: ['GOAT', 'GOLD'],
  GP: ['GPS', 'GAP'],
  GR: ['GRAPE', 'GREEN'],
  GS: ['GHOST', 'GAS'],
  GT: ['GOAT', 'GUITAR'],
  GU: ['GUM', 'GUN'],
  GW: ['GATEWAY'],
  GY: ['GYM', 'GUY'],
  // H_
  HA: ['HAT', 'HAMMER', 'HAND'],
  HB: ['HUBBLE', 'HUSBAND'],
  HC: ['HORSE COW'],
  HD: ['HEAD', 'HARD DRIVE'],
  HE: ['HELMET', 'HELIUM', 'HEN'],
  HF: ['HALF', 'HALF-LIFE'],
  HG: ['MERCURY', 'HUG'],
  HH: ['HAHA'],
  HI: ['HIPPO', 'HILL'],
  HK: ['HOOK', 'HONG KONG'],
  HL: ['HALL', 'HEEL'],
  HM: ['HAM', 'HOME'],
  HN: ['HEN', 'HORN'],
  HO: ['HOOK', 'HORSE'],
  HP: ['HARRY POTTER', 'HARP'],
  HR: ['HAIR', 'HEART'],
  HS: ['HORSE', 'HOSE'],
  HT: ['HAT', 'HEART'],
  HU: ['HULK', 'HUT'],
  HW: ['HOMEWORK', 'HIGHWAY'],
  HY: ['HAY', 'HYENA'],
  // I_
  IC: ['ICE CREAM', 'ICE'],
  ID: ['ID', 'IDIOT'],
  IG: ['INSTAGRAM', 'IGLOO'],
  IK: ['IKEA'],
  IL: ['ILLUMINATI', 'ILLINOIS'],
  IM: ['IRON MAN'],
  IN: ['INTERNET', 'INDIAN'],
  IO: ['IO MOTH', 'IODINE'],
  IP: ['IPHONE', 'IPAD'],
  IR: ['IRON', 'IRELAND'],
  IS: ['ISIS', 'ISLAND'],
  IT: ['ITALY', 'IT'],
  IV: ['IVY', 'IV BAG'],
  IY: ['IY'],
  // J_
  JA: ['JAR', 'JACK'],
  JB: ['JUSTIN BIEBER', 'JAMES BOND'],
  JC: ['JESUS CHRIST'],
  JD: ['JD'],
  JE: ['JET', 'JELLY'],
  JF: ['JFK'],
  JK: ['JOKE', 'JACK'],
  JL: ['JELLO'],
  JM: ['JAM', 'JIM'],
  JN: ['JUNE', 'JOHN'],
  JO: ['JOKER', 'JOB'],
  JP: ['JAPAN', 'JEEP'],
  JR: ['JR (JUNIOR)'],
  JS: ['JAVASCRIPT', 'JESUS'],
  JT: ['JET', 'JUSTIN TIMBERLAKE'],
  JU: ['JUICE', 'JURY'],
  JY: ['JOY', 'JAY'],
  // K_
  KA: ['KARATE', 'KANGAROO'],
  KB: ['KEYBOARD', 'KOBE BRYANT'],
  KC: ['KFC', 'KEY CARD'],
  KD: ['KENDO'],
  KE: ['KEY', 'KEN'],
  KF: ['KFC', 'KNIFE'],
  KG: ['KG (KILOGRAM)', 'KING'],
  KI: ['KIWI', 'KITE'],
  KK: ['KKK'],
  KL: ['KILL', 'KOOLAID'],
  KM: ['KIM JONG UN', 'KILOMETER'],
  KN: ['KNIFE', 'KING'],
  KO: ['KOALA', 'K.O.'],
  KP: ['KEEPER', 'KETCHUP'],
  KR: ['KOREA', 'KRAKEN'],
  KS: ['KISS', 'KIDS'],
  KT: ['KITE', 'KETTLE'],
  KW: ['KIWI'],
  KY: ['KEY', 'KAYAK'],
  // L_
  LA: ['LAMP', 'LASER'],
  LB: ['LIBRARY', 'POUND (LB)'],
  LC: ['LACE', 'LCD'],
  LD: ['LADDER', 'LAD'],
  LE: ['LEMON', 'LEG'],
  LF: ['LEAF', 'LIFE'],
  LG: ['LEG', 'LOG'],
  LH: ['LAUGH', 'LEFT HAND'],
  LI: ['LION', 'LINK'],
  LK: ['LOCK', 'LICK'],
  LL: ['LL COOL J', 'LULU'],
  LM: ['LEMON', 'LIMA BEAN'],
  LN: ['LION', 'LINE'],
  LO: ['LOG', 'LOTION'],
  LP: ['LP (RECORD)', 'LAPTOP'],
  LR: ['LARP', 'LIAR'],
  LS: ['LASSO', 'LIPSTICK'],
  LT: ['LATTE', 'LIGHT'],
  LU: ['LUNCH', 'LUNG'],
  LV: ['LOVE', 'LAVA'],
  LW: ['LAW', 'LION WEDDING'],
  LY: ['LILY', 'LYNX'],
  // M_
  MA: ['MAP', 'MAGNET'],
  MB: ['MARBLE', 'MAILBOX'],
  MC: ['MICROPHONE', 'MCDONALDS'],
  MD: ['MUD', 'MOLD'],
  ME: ['ME', 'MEAT'],
  MF: ['MUFFIN', 'MOFOS'],
  MG: ['MAGNUM', 'MAGAZINE'],
  MH: ['MAMMOTH'],
  MI: ['MILK', 'MITTEN'],
  MK: ['MILK', 'MASK'],
  ML: ['MOLE', 'MAIL'],
  MM: ['M&M', 'MUMMY'],
  MN: ['MOON', 'MAN'],
  MO: ['MOUSE', 'MONK'],
  MP: ['MOP', 'MAP'],
  MR: ['MR. T', 'MARIO'],
  MS: ['MOUSE', 'MOSS'],
  MT: ['MOUNTAIN', 'MUTT'],
  MU: ['MUSHROOM', 'MUG'],
  MV: ['MOVIE'],
  MW: ['MICROWAVE', 'MOTOWN'],
  MX: ['MEXICO', 'MIX'],
  MY: ['MAYO', 'MUMMY'],
  // N_
  NA: ['SODIUM', 'NACHO'],
  NB: ['NEWBIE', 'NBA'],
  NC: ['NIKE', 'NCAA'],
  ND: ['NEEDLE', 'ND FILTER'],
  NE: ['NEEDLE', 'NEON'],
  NF: ['NETFLIX', 'NFL'],
  NG: ['NUGGET', 'NIGER'],
  NI: ['NICKEL', 'NINJA'],
  NK: ['NIKE', 'NUKE'],
  NL: ['NAIL', 'NETHERLANDS'],
  NM: ['NEMO', 'NUMBER'],
  NN: ['NUN', 'NOON'],
  NO: ['NOSE', 'NORTH'],
  NP: ['NEPTUNE', 'NAPKIN'],
  NR: ['NAIR', 'NOSE RING'],
  NS: ['NOSE', 'NESS'],
  NT: ['NUT', 'NET'],
  NU: ['NUN', 'NUDE'],
  NV: ['NAVY', 'NIRVANA'],
  NW: ['NEW WORLD'],
  NY: ['NEW YORK'],
  // O_ ... and so on (cut to keep file size reasonable)
  OB: ['OBAMA', 'OBI-WAN'],
  OC: ['OCEAN', 'OCTOPUS'],
  OD: ['ODD', 'OREO DONUT'],
  OG: ['OGRE', 'OG'],
  OK: ['OK', 'OKLAHOMA'],
  OL: ['OIL', 'OWL'],
  OM: ['OMG', 'OMELET'],
  ON: ['ONION', 'ON'],
  OP: ['OPERATION', 'OP'],
  OR: ['ORANGE', 'ORC'],
  OS: ['OSTRICH', 'OSAMA'],
  OT: ['OTTER', 'OAT'],
  OU: ['OUTER SPACE', 'OUNCE'],
  OV: ['OVEN', 'OVAL'],
  OW: ['OWL', 'COW'],
  OX: ['OX', 'OXYGEN'],
  OY: ['OYSTER', 'BOY'],
  OZ: ['WIZARD OF OZ', 'OUNCE'],
  // P_
  PA: ['PASTA', 'PAINT'],
  PB: ['PB&J', 'PUBLISHER'],
  PC: ['PC', 'PEACOCK'],
  PD: ['PANDA', 'POD'],
  PE: ['PEN', 'PEACH'],
  PF: ['PUFF', 'PUFFER FISH'],
  PG: ['PIG', 'PG-13'],
  PH: ['PHONE', 'PHARAOH'],
  PI: ['PIE', 'PI', 'PIANO'],
  PJ: ['PAJAMAS'],
  PK: ['POKEMON', 'PACK'],
  PL: ['PLANE', 'PLATE'],
  PM: ['PALM', 'PRIME MINISTER'],
  PN: ['PEN', 'PINE'],
  PO: ['POO', 'POT'],
  PP: ['POPCORN', 'PEPPER'],
  PR: ['PEAR', 'PAPER'],
  PS: ['PASTA', 'PEPSI'],
  PT: ['POT', 'PIRATE'],
  PU: ['PUG', 'PUMA'],
  PW: ['POWER', 'PLAYBOY'],
  PY: ['PYRAMID', 'PYTHON'],
  // Q_
  QA: ['QATAR'],
  QB: ['QUARTERBACK'],
  QE: ['QUEEN ELIZABETH'],
  QI: ['QI MAGAZINE', 'CHI'],
  QK: ['QUACK', 'QUICK'],
  QN: ['QUEEN'],
  QR: ['QR CODE', 'QUARTZ'],
  QT: ['QT (QUART)', 'CUTIE'],
  QU: ['QUILL', 'QUEEN'],
  // R_
  RA: ['RAT', 'RAM'],
  RB: ['RUBIK', 'RIBBON'],
  RC: ['RC CAR', 'RICE'],
  RD: ['RED', 'ROAD'],
  RE: ['RED', 'REINDEER'],
  RF: ['ROOF', 'REF (REFEREE)'],
  RG: ['RAGE', 'RING'],
  RH: ['RHINO', 'RHUBARB'],
  RI: ['RING', 'RIB'],
  RJ: ['RJ45'],
  RK: ['ROCK', 'RICK'],
  RL: ['RAIL', 'RUSSIAN'],
  RM: ['RAM', 'ROMEO'],
  RN: ['RAIN', 'RUNE'],
  RO: ['ROSE', 'ROBIN'],
  RP: ['ROPE', 'RPG'],
  RR: ['RR (ROLLS ROYCE)'],
  RS: ['ROSE', 'RUSSIA'],
  RT: ['RAT', 'ROOT'],
  RU: ['RUNE', 'RUST'],
  RV: ['RV (RECREATIONAL VEHICLE)'],
  RW: ['RAINBOW', 'ROW'],
  RY: ['RYE', 'RYAN'],
  // S_
  SA: ['SALT', 'SAW'],
  SB: ['SUBWAY', 'SBARRO'],
  SC: ['SCISSORS', 'SCARF'],
  SD: ['SD CARD', 'SAND'],
  SE: ['SEAL', 'SEED'],
  SF: ['SAN FRANCISCO', 'SOFA'],
  SG: ['SLINGSHOT'],
  SH: ['SHARK', 'SHIP'],
  SI: ['SILICON', 'SIN'],
  SJ: ['STEVE JOBS'],
  SK: ['SKATEBOARD', 'SOCK'],
  SL: ['SLEIGH', 'SLED'],
  SM: ['SUMO', 'SAM'],
  SN: ['SUN', 'SNAIL'],
  SO: ['SOAP', 'SOCK'],
  SP: ['SPIDER', 'SOAP'],
  SR: ['SIR', 'STAR'],
  SS: ['SUSHI', 'SS (NAZI)'],
  ST: ['STOP', 'STAR'],
  SU: ['SUSHI', 'SUN'],
  SV: ['SUV'],
  SW: ['SWORD', 'SWIM'],
  SY: ['SOY', 'SYRINGE'],
  // T_
  TA: ['TAPE', 'TACO'],
  TB: ['TUBA', 'TUBE'],
  TC: ['TACO', 'TAXI CAB'],
  TD: ['TOAD', 'TUDOR'],
  TE: ['TENT', 'TEA'],
  TF: ['TOFU', 'TURF'],
  TG: ['TOGA', 'TIGER'],
  TH: ['THOR', 'THUMB'],
  TI: ['TIGER', 'TITAN'],
  TJ: ['TJ MAXX'],
  TK: ['TANK', 'TIK TOK'],
  TL: ['TAIL', 'TOOL'],
  TM: ['TOM', 'TIMER'],
  TN: ['TUNA', 'TIN'],
  TO: ['TOAD', 'TOMATO'],
  TP: ['TOILET PAPER', 'TAPE'],
  TR: ['TREE', 'TRAIN'],
  TS: ['TOAST', 'TAXI'],
  TT: ['TATTOO', 'TIT'],
  TU: ['TUNA', 'TUBE'],
  TV: ['TV', 'TOVAH'],
  TW: ['TOWEL', 'TWIN'],
  TX: ['TEXAS', 'TXT'],
  TY: ['TIE', 'TYPHOON'],
  // U_
  UB: ['UBER', 'UB40'],
  UC: ['UC BERKELEY'],
  UF: ['UFO'],
  UK: ['UK', 'UKULELE'],
  UM: ['UMBRELLA', 'UMA THURMAN'],
  UN: ['UN (UNITED NATIONS)', 'UNICORN'],
  UP: ['UP (MOVIE)', 'UPS'],
  UR: ['URN', 'URANUS'],
  US: ['USA', 'USB'],
  UT: ['UTAH', 'UTERUS'],
  UV: ['UV LIGHT'],
  // V_
  VA: ['VAMPIRE', 'VAN'],
  VB: ['VOLLEYBALL', 'VB'],
  VC: ['VACCINE', 'VICKS'],
  VD: ['VENDING MACHINE'],
  VE: ['VEIL', 'VET'],
  VF: ['VFX'],
  VG: ['VEGAN', 'VG'],
  VH: ['VHS TAPE'],
  VI: ['VIKING', 'VINE'],
  VK: ['VK (VKONTAKTE)'],
  VL: ['VIAL', 'VAULT'],
  VM: ['VAMPIRE', 'VIM'],
  VN: ['VEIN', 'VAN'],
  VO: ['VOLCANO', 'VOID'],
  VP: ['VICE PRESIDENT', 'VIP'],
  VR: ['VR HEADSET', 'VIRUS'],
  VS: ['VS (VERSUS)', 'VENUS'],
  VT: ['VAULT', 'VITAMIN'],
  VW: ['VW BEETLE'],
  // W_
  WA: ['WASABI', 'WAX'],
  WB: ['WEBCAM', 'WORLD BANK'],
  WC: ['WC TOILET', 'WORLD CUP'],
  WD: ['WD-40', 'WIZARD'],
  WE: ['WEB', 'WEED'],
  WF: ['WAFFLE', 'WIFE'],
  WG: ['WIG', 'WAGON'],
  WH: ['WHALE', 'WHEEL'],
  WI: ['WIFI', 'WINDOW'],
  WK: ['WOK', 'WALKMAN'],
  WL: ['WOLF', 'WALL'],
  WM: ['WORM', 'WALMART'],
  WN: ['WINE', 'WAGON'],
  WO: ['WOK', 'WORLD'],
  WP: ['WHIP', 'WAFFLE PRESS'],
  WR: ['WRENCH', 'WIRE'],
  WS: ['WINDOWS', 'WSJ'],
  WT: ['WATERMELON', 'WHITE'],
  WV: ['WAVE'],
  WW: ['WORLD WAR', 'WALL-E'],
  WX: ['WAX'],
  WY: ['WAYNE', 'WYOMING'],
  // X_
  XB: ['XBOX'],
  XL: ['XL SHIRT'],
  XM: ['XMAS'],
  XR: ['X-RAY'],
  XX: ['XX (CHROMOSOME)'],
  XY: ['XYLOPHONE', 'XY (CHROMOSOME)'],
  // Y_
  YA: ['YACHT', 'YAK'],
  YB: ['YIN-YANG BALL'],
  YE: ['YETI', 'YELLOW'],
  YK: ['YOKE', 'YORK'],
  YL: ['YELLOW'],
  YM: ['YAM', 'YMCA'],
  YN: ['YEN', 'YOUNG'],
  YO: ['YO-YO', 'YODA'],
  YP: ['YUPPIE'],
  YR: ['YEAR', 'YARN'],
  YS: ['YOSHI', 'YES'],
  YT: ['YOGURT', 'YACHT'],
  YU: ['YUKON'],
  // Z_
  ZA: ['ZACK', 'ZAMBIA'],
  ZB: ['ZBLL'],
  ZE: ['ZEUS', 'ZEBRA'],
  ZI: ['ZIP', 'ZINC'],
  ZL: ['ZELDA'],
  ZM: ['ZOOM', 'ZAMBONI'],
  ZN: ['ZINC'],
  ZO: ['ZOO', 'ZORRO'],
  ZP: ['ZIPPER', 'ZIPLOC'],
  ZR: ['ZERO'],
  ZU: ['ZULU'],
  ZZ: ['ZZZ', 'PIZZA'],
};

export interface RecentSubmission {
  id: number;
  pair: string;
  word: string;
  category: Category;
}

export const RECENT_SUBMISSIONS: RecentSubmission[] = [
  { id: 50762, pair: 'DQ', word: 'DOCK', category: 'object' },
  { id: 50761, pair: 'GH', word: 'GHOST', category: 'unspecified' },
  { id: 50760, pair: 'HJ', word: 'HORSE JOCKEY', category: 'person' },
  { id: 50759, pair: 'XR', word: 'X-RAY MACHINE', category: 'object' },
  { id: 50758, pair: 'WI', word: 'WINSTON CHURCHILL', category: 'person' },
  { id: 50757, pair: 'OK', word: 'OKEY DOKEY', category: 'unspecified' },
  { id: 50756, pair: 'JN', word: 'JOHN CENA', category: 'person' },
  { id: 50755, pair: 'BQ', word: 'BARBECUE', category: 'object' },
  { id: 50754, pair: 'YT', word: 'YO-YO TRICK', category: 'unspecified' },
  { id: 50753, pair: 'ZF', word: 'ZIP FILE', category: 'object' },
];

// Merge recent-submission words into PAIRS so click-through from the recent list opens
// a coherent detail panel (otherwise users see "no words yet" for a pair the recent list
// just listed). Idempotent.
for (const s of RECENT_SUBMISSIONS) {
  const existing = PAIRS[s.pair] ?? [];
  if (!existing.includes(s.word)) PAIRS[s.pair] = [...existing, s.word];
}

export interface Contributor {
  rank: number;
  name: string;
  country: string;
  activity: number;
  value: number;
  valuability: number;
}

export const TOP_CONTRIBUTORS: Contributor[] = [
  { rank: 1, name: 'Roman Strakhov',  country: 'ru', activity: 412, value: 287, valuability: 698 },
  { rank: 2, name: 'Stanley Chapel',  country: 'us', activity: 305, value: 198, valuability: 503 },
  { rank: 3, name: 'Jeff Park',       country: 'us', activity: 244, value: 161, valuability: 405 },
  { rank: 4, name: 'Graham Siggins',  country: 'us', activity: 198, value: 144, valuability: 342 },
  { rank: 5, name: 'Tymon Kolasinski',country: 'pl', activity: 175, value: 122, valuability: 297 },
  { rank: 6, name: 'Max Park',        country: 'us', activity: 142, value: 110, valuability: 252 },
  { rank: 7, name: 'Yusheng Du',      country: 'cn', activity: 121, value: 95,  valuability: 216 },
  { rank: 8, name: 'Feliks Zemdegs',  country: 'au', activity: 99,  value: 84,  valuability: 183 },
  { rank: 9, name: 'Anna Hoffmann',   country: 'de', activity: 78,  value: 66,  valuability: 144 },
  { rank: 10,name: 'Yiheng Wang',     country: 'cn', activity: 65,  value: 51,  valuability: 116 },
];

export const STATS = {
  users: 2133,
  englishWords: 11797,
  totalWords: 44582,
};
