import { l, microLesson } from './builders';
import type { MicroCourse } from './types';

export const TRIAL_MICRO_COURSE: MicroCourse = {
  id: 'trial',
  label: l('试听课', 'Trial course'),
  title: l('五次小成功，完成第一次挑战', 'Five small wins and a first real challenge'),
  summary: l('先用四节导入认识速拧、讲师、CubeRoot 与课程路线，再用五节挑战完成白色小花，最后引导学员选择层先法或 CFOP 正式课程。', 'Four introductions explain speedcubing, the instructor, CubeRoot, and the learning path; five challenge lessons then build a white daisy and guide learners into the full beginner-method or CFOP course.'),
  audience: l('第一次接触三阶魔方的学员和正在选课的家长', 'Learners meeting the 3×3 for the first time and parents choosing a course'),
  stages: [
    {
      id: 'trial-start',
      title: l('第一次上手', 'First contact'),
      summary: l('每节只完成一个看得见的小目标，试听结束时明确说明两套正式课程的区别和购买入口。', 'Each lesson ends with one visible result, and the trial closes by explaining the difference between the two full courses and where to purchase them.'),
      modules: [
        {
          id: 'trial-success',
          title: l('先体验“我做得到”', 'Start with “I can do this”'),
          summary: l('从认识魔方到做出白色小花，让学员先体验学习效果，再根据当前基础选择层先法或 CFOP 正式课程。', 'Move from meeting the cube to making a white daisy, demonstrate the learning experience, then guide learners to the full beginner-method or CFOP course that matches their current level.'),
          lessons: [
            microLesson({
              id: 'trial-intro-speedcubing',
              title: l('什么是魔方速拧', 'What is speedcubing?'),
              minutes: 3,
              outcome: l('能说出速拧的目标、学习价值，以及练习带来的可见进步', 'Explain speedcubing’s goal, learning value, and the visible progress created by practice'),
              script: [
                l('大家好，我是颜瑞民，欢迎来到魔方课。接下来，我会陪你从第一次看懂魔方，慢慢走到独立复原，再到更快、更顺地完成它。', 'Hello, I am Ruimin Yan. Welcome to the course. I will take you from understanding the cube for the first time to solving independently, then solving faster and more smoothly.'),
                l('我们先聊一个最基本的问题：什么是速拧？简单说，就是先把魔方正确复原，再想办法少停顿、少走弯路，让整次复原越来越快。', 'Let us begin with the most basic question: what is speedcubing? Put simply, solve the cube correctly first, then reduce pauses and wasted moves so the whole solve becomes faster.'),
                l('【画面对比：慢速复原、有停顿的复原、连贯复原】', '[Compare a slow solve, a solve with pauses, and a smooth solve.]'),
                l('刚开始时，你可能要找很久，才看见自己需要的那一块。练一段时间以后，同样的位置一眼就能发现。进步看得见，也能用计时一点点记录下来，这就是速拧特别有意思的地方。', 'At first, it may take a long time to spot the piece you need. After some practice, the same piece can jump out immediately. Progress is visible and can be recorded one solve at a time, which is part of what makes speedcubing so satisfying.'),
                l('练魔方时，你要看颜色、想位置、做判断，还要让双手配合起来。做错了也没关系，停下来找原因，再试一次。它不是提高智商的捷径，却能实实在在地练空间想象、专注和解决问题。', 'Cubing asks you to read colours, picture positions, make decisions, and coordinate both hands. When something goes wrong, stop, find the reason, and try again. It is not a shortcut to higher IQ, but it gives spatial thinking, focus, and problem-solving real practice.'),
                l('现在，魔方早已不只是一个人在家里玩的益智玩具。各地的比赛、社团和学习资源越来越丰富，你可以计时、参赛、认识同好，也可以把学会的方法分享给别人。', 'Today, cubing is far more than a puzzle practised alone at home. Competitions, clubs, and learning resources continue to grow, so you can time solves, compete, meet other cubers, and share what you learn.'),
                l('如果把第一次独立复原、每周的计时变化、比赛成绩和复盘心得留下来，它们就会成为一份真实的成长记录。你能从中看到，自己是怎样发现问题、调整方法，再一步步完成目标的。', 'If you keep your first independent solve, weekly timing changes, competition results, and practice reflections, they become an authentic record of growth. It shows how you learned to spot problems, adjust your approach, and reach a goal step by step.'),
                l('这份经历也可以成为申请国际学校时的具体素材：你为什么开始，哪里卡住，后来怎么解决，又把什么分享给了别人。当然，魔方不是录取捷径，真正有价值的，是你认真做过、想过，而且能把收获讲清楚。', 'This experience can also provide concrete material for an international-school application: why you started, where you got stuck, how you solved the problem, and what you shared with others. Cubing is never an admissions shortcut; what matters is that you did the work, reflected on it, and can explain what you learned.'),
                l('更重要的是，每完成一个原本觉得很难的小目标，你都会多一点学习信心。现在不用追求快，也不用怕做错，我们先让你真正感受到“原来我也能做到”。下一节，我先介绍一下自己，再告诉你这套课为什么这样安排。', 'Most importantly, every small goal that once seemed difficult adds a little more confidence in your ability to learn. There is no need to chase speed yet or fear mistakes. We will first let you genuinely feel, “I can do this too.” Next, I will introduce myself and explain why the course is arranged this way.'),
              ],
            }),
            microLesson({
              id: 'trial-intro-ruimin',
              title: l('关于颜瑞民', 'About Ruimin Yan'),
              minutes: 2,
              outcome: l('了解讲师的魔方学习、比赛与课程设计经验', 'Understand the instructor’s experience in cubing, competition, and course design'),
              script: [
                l('正式开始前，我想用一分钟介绍一下自己。我叫颜瑞民，是魔方根 CubeRoot 的创始人，也是接下来陪你上课的人。', 'Before we begin, I want to take one minute to introduce myself. I am Ruimin Yan, founder of CubeRoot and your instructor for the lessons ahead.'),
                l('我学的是物理和数学，所以我喜欢魔方，不只是因为它能拧得很快。我更着迷的是：这么乱的东西，背后居然有清楚的结构和规律。', 'My background is in physics and mathematics, so speed is not the only reason I enjoy the cube. What fascinates me more is that something so scrambled can still have such clear structure and patterns.'),
                l('【展示早期练习、比赛现场和教学画面，不念屏幕文字】', '[Show early practice, competition, and teaching footage without reading on-screen text.]'),
                l('我从 2017 年开始参加 WCA 比赛，也接触过不同项目、不同解法和不同阶段的练习者。练得越久，我越确定一件事：真正稳定的进步，靠的不是突然开窍，而是方法正确，再一点点练熟。', 'I have competed in WCA events since 2017 and met learners across different events, methods, and stages. The longer I practise, the more certain I become: reliable progress does not come from a sudden flash of talent, but from a sound method made familiar step by step.'),
                l('这些年，我一直在做魔方课程、公式库和练习工具。上课时，我最关心的不是你一天背了多少，而是你有没有看懂、能不能做对，出错以后知不知道去哪里检查。', 'Over the years, I have worked on cubing courses, algorithm libraries, and practice tools. What matters to me is not how much you memorize in one day, but whether you understand, can do it correctly, and know where to look when something goes wrong.'),
                l('所以，我不会拿一条很长的视频把所有知识一下子塞给你。每节课只讲一个新判断，或者一个新动作。看完就停下来练，成功几次，再往下走。', 'That is why I will not pack everything into one long video. Each lesson introduces one decision or one action. Watch it, pause to practise, succeed a few times, and then continue.'),
                l('如果某一步总出错，也不用怀疑自己。直接回到对应编号，只解决眼前这一个问题。能找到问题，本身就是在进步。', 'If one step keeps going wrong, there is no reason to doubt yourself. Return to that lesson number and solve only the problem in front of you. Finding the problem is already progress.'),
                l('我希望这套课结束时，你不只是“会拧”，还知道自己为什么这样做。下一节，我们看看 CubeRoot 能怎样陪你把学习、练习和检查连在一起。', 'By the end, I want you not only to solve, but to know why you are doing each step. Next, we will see how CubeRoot connects learning, practice, and checking.'),
              ],
            }),
            microLesson({
              id: 'trial-intro-cuberoot',
              title: l('关于 CubeRoot', 'About CubeRoot'),
              minutes: 2,
              outcome: l('了解 CubeRoot 如何把课程、公式与练习工具连成学习路线', 'Understand how CubeRoot connects lessons, algorithms, and practice tools into one learning path'),
              script: [
                l('为什么我要做 CubeRoot？因为网上从来不缺魔方教程，真正让人头疼的是：我到底该先看哪一个，练到什么程度，下一步又是什么。', 'Why did I build CubeRoot? The internet has no shortage of cube tutorials. The real problem is knowing what to watch first, how far to practise, and what comes next.'),
                l('有些视频单独看都讲得不错，可是顺序一乱，就容易漏掉基础，或者还没学会观察，就急着背很多公式。等动作变成习惯，再改反而更费时间。', 'Many individual videos explain their topic well, but the wrong order can leave gaps or introduce lots of algorithms before observation is ready. Once an action becomes a habit, fixing it takes more work.'),
                l('【展示课程页、公式库、练习器和计时器的站内画面】', '[Show the course page, algorithm library, trainers, and timer on CubeRoot.]'),
                l('CubeRoot 把课程顺序、标准拿法、公式图、练习器和计时器放在一起。视频先把一件事讲明白，工具再帮你多练几次，看看自己是不是真的掌握了。', 'CubeRoot brings the course sequence, standard grips, algorithm diagrams, trainers, and timer together. A video explains one thing clearly, then the tools help you practise and check whether it has really settled in.'),
                l('如果你还不会复原，就从结构和基本动作开始，一直学到独立完成六面。如果你已经会复原，就从减少停顿开始，再学 CFOP 和后面的进阶内容。', 'If you cannot solve yet, begin with structure and basic moves and continue to an independent full solve. If you already can, start by reducing pauses, then move into CFOP and later advanced topics.'),
                l('课程里也会提前提醒一些常见问题，比如拿法总在变、只记手上的动作却不看魔方，或者一着急就跳过检查。好习惯早点养成，后面会轻松很多。', 'The course also points out common problems early: changing grips constantly, memorizing hand movements without watching the cube, or skipping checks in a rush. Good habits make everything later much easier.'),
                l('如果你在某一节反复卡住，就记下它的编号。这样你能很快回来复习，我也能听懂你的具体问题，继续把讲解和镜头做得更清楚。', 'If you keep getting stuck in one lesson, note its number. That lets you return quickly, and it gives me a clear problem I can use to improve the explanation and camera work.'),
                l('下一节，我们把整套课程像地图一样摊开。看完以后，你就会知道自己应该从哪里出发。', 'Next, we will lay out the whole course like a map. By the end, you will know exactly where to begin.'),
              ],
            }),
            microLesson({
              id: 'trial-intro-structure',
              title: l('课程结构与学习方法', 'Course structure and study method'),
              minutes: 3,
              outcome: l('能根据当前基础选择试听课、层先法或 CFOP 的学习路线', 'Choose the trial, beginner-method, or CFOP path that matches the current skill level'),
              script: [
                l('现在，我们把整套课的地图看一遍。主要有三段：试听课、层先法正式课和 CFOP 正式课。学完 CFOP，还可以继续学三阶和二阶的进阶内容。', 'Now let us look at the map of the full programme. It has three main parts: the trial, the full beginner-method course, and the full CFOP course. Further 3×3 and 2×2 topics follow CFOP.'),
                l('【屏幕展示四段路线：试听课→层先法→CFOP→后续课程】', '[Show the four-part route: trial, beginner method, CFOP, and further courses.]'),
                l('如果你还不能独立复原，就先完成试听里的白色小花，再进入层先法。层先法会从魔方结构和动作记号讲起，一直带你完成六面。', 'If you cannot solve independently yet, finish the white-daisy challenge in the trial and continue into the beginner method. It begins with cube structure and move notation and takes you all the way to six solved faces.'),
                l('如果你已经会复原，想解决停顿多、速度上不去的问题，就直接进入 CFOP。我们会依次学习十字、F2L、OLL 和 PLL，再慢慢加入观察、预判和更多案例。', 'If you can already solve but pause too often or struggle to improve speed, enter CFOP directly. We will learn Cross, F2L, OLL, and PLL in order, then gradually add recognition, lookahead, and more cases.'),
                l('每节课都很短，只增加一个新判断，或者一个新动作。但短不等于赶进度。真正的学习，发生在你按下暂停、拿起魔方、自己试的那几分钟里。', 'Every lesson is short and adds only one decision or one action. Short does not mean rushed. The real learning happens in the minutes when you pause, pick up the cube, and try it yourself.'),
                l('看完一节，先按过关要求做几次。还不稳定就再看一遍，不用跟别人比进度。今天比昨天多看懂一点，就是有效的进步。', 'After each lesson, complete the checkpoint a few times. If it is not stable, watch again; there is no need to compare your pace with anyone else. Understanding a little more than yesterday is real progress.'),
                l('如果有一项你已经很熟，可以按编号找到更适合自己的位置；如果中间有一步不确定，就从那里接着学，不用硬着头皮往后跳。', 'If one topic is already familiar, use the lesson numbers to find a better starting point. If one step is uncertain, continue from there instead of forcing yourself to skip ahead.'),
                l('现在判断一下自己的起点：不会独立复原，就走试听和层先法；已经会复原、想继续提速，就走 CFOP。路线选对以后，我们不用着急，一节一节稳稳地往前走。', 'Choose your starting point now: use the trial and beginner method if you cannot solve independently, or CFOP if you can solve and want more speed. Once the route is right, there is no rush; we will move forward one steady lesson at a time.'),
              ],
            }),
            microLesson({
              id: 'trial-01',
              title: l('魔方不是靠运气', 'The cube is not luck'),
              minutes: 2,
              outcome: l('能说出复原靠的是可重复路线，而不是碰运气', 'Explain that solving follows a repeatable route rather than luck'),
              script: [
                l('你好，欢迎来到魔方课。先看同一个魔方：它可以乱成这样，也可以一步一步回到六面整齐。', 'Hello and welcome. The same cube can look completely scrambled, then return to six neat faces one step at a time.'),
                l('【展示打乱状态，再快速切到复原状态】', '[Show the scrambled cube, then cut to the solved cube.]'),
                l('会复原的人不是每次都猜对，而是知道一条可以重复走通的路线。接下来每一节，我们只走路线中的一小步。', 'Solvers do not guess correctly every time. They know a route that works again and again. Each lesson will cover one small step on that route.'),
                l('做错不代表失败，只说明我们找到了一个需要再看一次的位置。慢一点、看清楚，你一样可以做到。', 'A mistake is not failure. It simply shows us the place to inspect again. Slow down, look carefully, and you can do it too.'),
                l('请把魔方拿起来，随便转两下，再停住。无论它看起来多乱，中心、棱和角仍然遵守固定规则。', 'Pick up the cube, make two random turns, and stop. No matter how mixed it looks, its centers, edges, and corners still follow fixed rules.'),
                l('【让学员暂停，自己打乱两步再复原两步】', '[Invite the learner to pause, make two turns, then undo both turns.]'),
                l('你刚刚已经验证了一件事：动作可以记录，也可以倒着走回来。后面的复原，就是把很多个可理解的小动作排好顺序。', 'You have already proved something important: moves can be recorded and reversed. A full solve is simply many understandable actions placed in the right order.'),
                l('今天先记住一句话：魔方不是靠运气。下一节，我们认识负责带路的中心块。', 'Remember one sentence today: the cube is not luck. Next, we will meet the center pieces that guide every face.'),
              ],
            }),
            microLesson({
              id: 'trial-02',
              title: l('找到不会换位置的中心块', 'Find the centers that never trade places'),
              minutes: 3,
              outcome: l('能找到六个中心块，并用中心颜色判断每一面的归属', 'Find all six centers and use them to identify each face'),
            }),
            microLesson({
              id: 'trial-03',
              title: l('找到一块白色棱块', 'Find one white edge'),
              minutes: 3,
              outcome: l('能区分中心、棱和角，并准确指出一块白色棱块', 'Tell centers, edges, and corners apart and point to a white edge'),
            }),
            microLesson({
              id: 'trial-04',
              title: l('把第一片花瓣送到黄色中心旁', 'Move the first petal beside the yellow center'),
              minutes: 4,
              outcome: l('能独立把任意一块白色棱块送到黄色中心旁', 'Move any white edge beside the yellow center independently'),
              kind: 'case',
            }),
            microLesson({
              id: 'trial-05',
              title: l('四片花瓣与正式课程选择', 'Four petals and choosing a full course'),
              minutes: 4,
              outcome: l('能做出白色小花，并根据自己的基础选择层先法或 CFOP 正式课程', 'Make a white daisy and choose the full beginner-method or CFOP course that matches the learner’s level'),
              kind: 'milestone',
              script: [
                l('把刚才的方法重复四次，四块白色棱块就会围在黄色中心旁边，像一朵白色小花。', 'Repeat the same idea four times. The four white edges will surround the yellow center like a white daisy.'),
                l('【俯拍完成第四片花瓣，停留三秒】', '[Complete the fourth petal overhead and hold for three seconds.]'),
                l('先检查四片花瓣都是棱块，不是白色角块。再转动顶层，确认每片花瓣都能跟着黄色中心一起移动。', 'Check that all four petals are edges, not white corners. Turn the top layer and confirm that every petal travels around the yellow center.'),
                l('你已经不是只会乱转魔方了。你刚刚完成了复原路线中的第一个真实目标。请记住这一刻：复杂的东西，也能被你一步一步看懂。', 'You are no longer just turning randomly. You have completed the first real goal on the solving route. Remember this moment: you can understand something complex one step at a time.'),
                l('【把后五节挑战的成果依次显示在屏幕上，再出现层先法和 CFOP 两条课程路线】', '[Show the result from each of the five challenge lessons, then reveal the beginner-method and CFOP course paths.]'),
                l('试听课到这里结束，接下来有两套正式课程可以选择。它们不是难度不同的同一套内容，而是分别解决“学会复原”和“系统提速”两个目标。', 'The trial ends here, and there are two full courses to choose from. They are not simply easier and harder versions of the same material: one teaches a complete solve, while the other develops systematic speed.'),
                l('如果你现在还不能独立复原三阶魔方，就选择层先法正式课。课程会从魔方结构和动作语言开始，把完整复原拆成 26 课，最后带你独立完成六面复原。', 'If you cannot yet solve a 3×3 independently, choose the full beginner-method course. It starts with cube structure and move language, divides the complete solve into 26 lessons, and guides you to an independent solve.'),
                l('如果你已经能够独立复原，并且想减少停顿、提高速度，就选择 CFOP 正式课。课程会系统学习十字、F2L、OLL 和 PLL，再逐步进入观察、预判和进阶案例。', 'If you can already solve independently and want fewer pauses and faster times, choose the full CFOP course. It systematically covers Cross, F2L, OLL, and PLL before moving into recognition, lookahead, and advanced cases.'),
                l('如果你是零基础，又希望以后继续提速，推荐先完成层先法正式课，再进入 CFOP 正式课。这样每一步都有基础，不需要跳着背公式。', 'If you are starting from zero and want to become faster later, complete the full beginner-method course first, then continue into the full CFOP course. This gives every new skill a foundation instead of forcing you to memorize algorithms out of sequence.'),
                l('两套正式课仍然采用今天的学习方式：一课只增加一个判断或动作，看完立即练习，并用明确的过关标准检查是否真正掌握。', 'Both full courses use the same learning format you experienced today: one new decision or action per lesson, immediate practice, and a clear checkpoint to confirm mastery.'),
                l('如果今天有一步不稳定，不用重看全部内容。回到对应编号，只练那一个小目标，成功三次再继续。', 'If one step feels uncertain, do not replay everything. Return to that numbered lesson, practise only its small goal, and continue after three successes.'),
                l('课后挑战：打乱白色棱块，再独立做出两次白色小花。完成以后，先为自己刚才的耐心和判断鼓一次掌。然后点击视频下方适合你的正式课程：不会独立复原就选择层先法课，已经会复原并想提速就选择 CFOP 课。今天的小花只是起点，下一次，我们把它继续变成完整六面和更流畅的速度。正式课程见。', 'After-class challenge: scramble the white edges and make the daisy twice independently. When you finish, first give yourself credit for the patience and decisions that got you there. Then choose the full course below: the beginner method if you cannot yet solve independently, or CFOP if you can solve and want more speed. Today’s daisy is only the start; next, we will turn it into a complete solve and smoother speed. See you in the full course.'),
              ],
            }),
          ],
        },
      ],
    },
  ],
};
