import { ArrowUpRight, Check, Cpu, HeartHandshake } from 'lucide-react';
import AppLink from '@/components/AppLink';
import { tr } from '@/i18n/tr';
import { ANNUAL_RECURRING_CNY, EQUIPMENT_GROUPS, EXPENSES, ONE_TIME_TOTAL, RMB_PER_USD, annualExpenseCny, equipmentGroupTotal } from '@/lib/infrastructure-costs';
import { FUNDING_ALLOCATIONS, FUNDING_SCENARIOS } from './funding-plan';
import '@/components/sticky-table.css';

const yuan = (value: number) => `¥${Math.round(value).toLocaleString('en-US')}`;

export default function CostsFunding() {
  return <>
    <section className="overview-section overview-wrap" aria-labelledby="overview-cost-title">
      <p className="overview-kicker">{tr({ zh: '06 / 已有投入与持续成本', en: '06 / Resources & recurring costs' })}</p>
      <h2 id="overview-cost-title">{tr({ zh: '工具已经在运行，\n投入也有据可查。', en: 'Tools already running.\nResources you can inspect.' })}</h2>
      <div className="overview-cost-totals"><div><span>{tr({ zh: '已登记设备金额合计', en: 'Recorded equipment values' })}</span><strong>{yuan(ONE_TIME_TOTAL)}<small>{tr({ zh: '起', en: 'minimum' })}</small></strong></div><div><span>{tr({ zh: '已登记年度固定服务费', en: 'Recorded annual fixed services' })}</span><strong>{yuan(ANNUAL_RECURRING_CNY)}<small>{tr({ zh: '约 / 年', en: 'approx. / year' })}</small></strong></div></div>
      <div className="overview-cost-grid"><div><h3>{tr({ zh: '开发、运行与内容服务', en: 'Development, hosting & content services' })}</h3><dl className="overview-cost-list">{EXPENSES.map(expense => <div key={expense.name.en}><dt><strong>{tr(expense.name)}</strong><span>{tr(expense.purpose)}</span></dt><dd><strong>{expense.amount.currency === 'USD' ? `US$${expense.amount.value}` : yuan(expense.amount.value)}{tr(expense.amount.period === 'month' ? { zh: ' / 月', en: ' / month' } : { zh: ' / 年', en: ' / year' })}</strong><span>{tr({ zh: `年折合约 ${yuan(annualExpenseCny(expense.amount))}`, en: `Approx. ${yuan(annualExpenseCny(expense.amount))} / year` })}</span></dd></div>)}</dl></div><div><h3>{tr({ zh: '已有工作设备', en: 'Existing work equipment' })}</h3><div className="overview-equipment-pictures"><img src="/images/dev/infrastructure/mac-mini-m5-pro.webp" width={240} height={180} loading="lazy" alt="Mac mini" /><img src="/images/dev/infrastructure/canon-eos-r5-mark-ii-cutout.webp" width={240} height={180} loading="lazy" alt="Canon EOS R5 Mark II" /><img src="/images/dev/infrastructure/dji-mic-3.webp" width={240} height={180} loading="lazy" alt="DJI Mic 3" /></div><dl className="overview-cost-list">{EQUIPMENT_GROUPS.filter(group => equipmentGroupTotal(group) > 0).map(group => <div key={group.category.en}><dt><strong>{tr(group.category)}</strong><span>{group.items.map(item => tr(item.name)).slice(0, 3).join(' · ')}…</span></dt><dd><strong>{yuan(equipmentGroupTotal(group))}</strong></dd></div>)}</dl><p className="overview-small">{tr({ zh: '电脑用于开发、计算与多端测试；影像和收音设备为内容制作提供基础。新预算优先投入交付与验证，复用已有设备。', en: 'Computers support development, computation and platform testing; cameras and audio equipment support production. The new budget prioritises delivery and validation using existing equipment.' })}</p></div></div>
      <p className="overview-small">{tr({ zh: `金额沿用网站设备与支出清单。设备含曾用设备、估价与基础机型首发起价，并非全部属于本项目的实付款或待采购额；未标价设备不计入。美元按清单记录的 2026-08-27 汇率 1 美元 = ${RMB_PER_USD.toFixed(4)} 元换算，并非实时汇率；固定服务费不含开发劳动报酬、用量计费与税费。`, en: `Figures come from the site’s inventory. Equipment includes former devices, estimates and base-model launch prices; these are not all project payments or planned purchases. Unpriced items are excluded. USD uses the inventory’s 2026-08-27 rate of 1 USD = ${RMB_PER_USD.toFixed(4)} CNY, not a live rate. Fixed services exclude development labour, usage charges and taxes.` })}</p>
      <AppLink href="/dev/infrastructure" prefetch={false} className="overview-text-link">{tr({ zh: '查看设备与支出完整清单', en: 'Inspect the full equipment & expense inventory' })}<ArrowUpRight size={16} aria-hidden /></AppLink>
    </section>

    <section className="overview-section overview-wrap" id="overview-funding" aria-labelledby="overview-funding-title">
      <p className="overview-kicker">{tr({ zh: '07 / 本轮资金需求', en: '07 / Funding request' })}</p>
      <h2 id="overview-funding-title">{tr({ zh: '20 万—50 万元，\n支持下一年的产品与商业验证。', en: '¥200,000–¥500,000.\nA year of delivery and validation.' })}</h2>
      <p className="overview-intro">{tr({ zh: '希望争取人民币 20 万到 50 万元的融资、项目资助或品牌赞助。已有产品和设备是起点；下一阶段资金重点保障持续开发、内容建设、真实试用和付费验证，让技术积累有机会形成可持续业务。', en: 'Seeking CNY 200,000–500,000 through financing, project support or brand sponsorship. Existing products and equipment provide the starting point. Funding would support sustained development, content, real-world pilots and paid-service validation to turn technical work into a sustainable business.' })}</p>
      <div className="overview-funding-cards">{FUNDING_SCENARIOS.map(scenario => <article key={scenario.amount} data-site-surface="panel"><span>{tr(scenario.title)}</span><strong>{yuan(scenario.amount)}</strong><p>{tr(scenario.body)}</p></article>)}</div>
      <h3>{tr({ zh: '12 个月建议预算', en: 'Proposed 12-month budget' })}</h3>
      <div className="sticky-scroll sticky-scroll-mobile overview-budget-scroll"><table className="sticky-thead overview-budget"><thead><tr><th scope="col">{tr({ zh: '用途', en: 'Use of funds' })}</th>{FUNDING_SCENARIOS.map(scenario => <th scope="col" key={scenario.amount}>{yuan(scenario.amount)}</th>)}</tr></thead><tbody>{FUNDING_ALLOCATIONS.map(row => <tr key={row.name.en}><th scope="row">{tr(row.name)}<span>{tr(row.purpose)}</span></th>{row.amounts.map((amount, index) => <td key={index}>{yuan(amount)}</td>)}</tr>)}</tbody><tfoot><tr><th scope="row">{tr({ zh: '合计', en: 'Total' })}</th>{FUNDING_SCENARIOS.map(scenario => <td key={scenario.amount}>{yuan(scenario.amount)}</td>)}</tr></tfoot></table></div>
      <p className="overview-small">{tr({ zh: '以上为建议分配，不是已发生支出或供应商报价。服务预算已包含上方年度固定费用，不重复叠加；既有设备金额不计入本轮资金需求。实际净资金缺口还需扣除可用于项目的自有资金和已落实回款，金额、周期与交付在合作前共同确认。', en: 'Allocations are proposals, not incurred expenses or supplier quotes. Services include the recurring baseline above; existing equipment is not added to this funding request. The net funding gap must deduct available project funds and committed receipts. Amounts, periods and deliverables are agreed before partnering.' })}</p>
      <div className="overview-funding-reason"><Cpu size={25} aria-hidden /><div><h3>{tr({ zh: '为什么需要的不只是服务器费？', en: 'Why more than hosting costs?' })}</h3><p>{tr({ zh: '服务器让网站保持在线，持续的开发时间、教学内容与用户验证，才能让工具成为用户长期选择的产品。预算中最大的部分是产品开发与维护：覆盖创始人的劳动报酬和必要协作，使投入与阶段交付对应。', en: 'Hosting keeps a site online. Sustained development, teaching content and user validation make it a product people choose repeatedly. The largest allocation covers development and maintenance, including founder compensation and targeted collaborators, tied to staged delivery.' })}</p></div></div>
    </section>

    <section className="overview-section overview-wrap" aria-labelledby="overview-partner-value-title">
      <p className="overview-kicker">{tr({ zh: '08 / 合作方的价值与验收', en: '08 / Partner value & review' })}</p><h2 id="overview-partner-value-title">{tr({ zh: '把合作价值，写进具体交付。', en: 'Make partner value part of the deliverables.' })}</h2>
      <div className="overview-business-grid"><article><h3>{tr({ zh: '融资合作', en: 'Financing' })}</h3><p>{tr({ zh: '共同验证个人订阅、机构服务与品牌合作的收入路径。提供产品进展、用户留存、付费试验和成本报告；融资结构、估值与权益另行商议。', en: 'Validate revenue paths across individual subscriptions, educator services and brand partnerships. Review delivery, retention, paid experiments and costs; financing structure, valuation and rights are negotiated separately.' })}</p></article><article><h3>{tr({ zh: '品牌赞助', en: 'Brand sponsorship' })}</h3><p>{tr({ zh: '可讨论指定页面的合作品牌展示、联合教学内容、直播或活动合作，以及约定周期内的合作报告。位置、次数、排期与统计口径提前约定，按实际交付验收。', en: 'Discuss agreed-page brand placement, co-created educational content, livestreams or activities, and reporting. Agree locations, quantities, schedules and measurement before delivery.' })}</p></article><article><h3>{tr({ zh: '项目资助与共创', en: 'Project support & co-creation' })}</h3><p>{tr({ zh: '支持一组明确工具或教学试点，看到可体验的功能、试用反馈与成果报告。机构提供真实使用场景，项目按约定周期回应需求。', en: 'Support defined tools or teaching pilots with usable features, feedback and outcome reports. Educational partners contribute real settings; the project responds within an agreed schedule.' })}</p></article></div>
      <div className="overview-review" data-site-surface="panel"><HeartHandshake size={26} aria-hidden /><div><h3>{tr({ zh: '建议分阶段拨付，每一阶段都有材料可看。', en: 'Proposed staged funding, with evidence at each review.' })}</h3><ul>{[
        { zh: '第 1–3 个月：确定预算与试点范围，交付核心体验改进，建立使用与成本基线。', en: 'Months 1–3: agree the budget and pilots, deliver core improvements and establish usage and cost baselines.' },
        { zh: '第 4–6 个月：建议招募 30 位试用者、3 家教学伙伴，形成训练与教学反馈报告，并开展付费或赞助试点。', en: 'Months 4–6: target 30 pilot users and 3 teaching partners; document training feedback and run paid-service or sponsorship pilots.' },
        { zh: '第 7–12 个月：报告重复使用、付费转化、续订与合作交付；依据真实结果决定续投、调整或收缩。', en: 'Months 7–12: report repeat use, paid conversion, renewals and partner delivery; decide whether to extend, adapt or narrow the work.' },
      ].map(item => <li key={item.en}><Check size={16} aria-hidden /><span>{tr(item)}</span></li>)}</ul><p className="overview-small">{tr({ zh: '人数、机构数与阶段节奏为建议目标，不代表现有用户或已签约伙伴。月度沟通、季度复核；各阶段金额、交付条件和后续资金承诺以双方约定为准。', en: 'Pilot counts and timing are proposed targets, not existing users or signed partners. Use monthly updates and quarterly reviews, with stage amounts, conditions and future funding commitments agreed by both parties.' })}</p></div></div>
    </section>
  </>;
}
