'use client';

import { ArrowUpRight, BookOpen, ChartNoAxesColumnIncreasing, Globe2, HeartHandshake, Printer, ScanSearch, School, Timer } from 'lucide-react';
import AppLink from '@/components/AppLink';
import HeaderToggles from '@/components/HeaderToggles';
import { VisualCube } from '@/components/VisualCube';
import { tr } from '@/i18n/tr';
import CostsFunding from './CostsFunding';
import './overview.css';

const PRODUCTS = [
  { Icon: Timer, href: '/timer', title: { zh: '练习与计时', en: 'Practice & timing' }, body: { zh: '打乱、计时与训练记录，让日常练习有迹可循。', en: 'Scrambles, timing and solve records give everyday practice a history.' }, tag: { zh: '高频使用入口', en: 'An everyday entry point' } },
  { Icon: BookOpen, href: '/alg', title: { zh: '公式与训练', en: 'Algorithms & training' }, body: { zh: '把公式、状态图示与动画放在一起，帮助用户理解并练习。', en: 'Algorithms, state diagrams and animation help cubers understand and practise.' }, tag: { zh: '从学习到掌握', en: 'From learning to mastery' } },
  { Icon: ScanSearch, href: '/recon', title: { zh: '复盘与分析', en: 'Reconstruction & analysis' }, body: { zh: '复盘还原过程，结合逐帧视频工具，研究步骤与效率。', en: 'Reconstruct solves and use frame-by-frame video tools to study steps and efficiency.' }, tag: { zh: '服务进阶选手', en: 'For improving competitors' } },
  { Icon: ChartNoAxesColumnIncreasing, href: '/wca', title: { zh: '比赛与数据', en: 'Competitions & data' }, body: { zh: '通过比赛、成绩、统计与可视化，理解个人进步和全球赛事。', en: 'Explore competitions, results, statistics and visualisations to understand progress and the wider sport.' }, tag: { zh: '连接全球魔方圈', en: 'Connected to global cubing' } },
] as const;

const ROADMAP = [
  { period: { zh: '近期 · 未来 3 个月', en: 'Near term · next 3 months' }, title: { zh: '让核心体验可靠，让需求可验证。', en: 'Make the core reliable. Validate demand.' }, body: { zh: '集中打磨计时、公式与复盘的连续使用体验；邀请老师、选手和机构参与小规模试用，形成明确的问题清单。', en: 'Refine the connected timing, algorithm and reconstruction experience; invite teachers, competitors and organisations into small pilots with a clear issue list.' }, proof: { zh: '观察：重复使用、任务完成、试用反馈与维护成本。', en: 'Measure: repeat use, task completion, pilot feedback and maintenance costs.' } },
  { period: { zh: '中期 · 3–12 个月', en: 'Medium term · 3–12 months' }, title: { zh: '验证付费价值与合作交付。', en: 'Validate paid value and partner delivery.' }, body: { zh: '以个人进阶服务、机构教学工具和品牌合作做分阶段试点；持续推进多端体验，用真实使用结果决定投入顺序。', en: 'Run staged pilots for advanced individual services, teaching tools and brand partnerships; improve cross-platform access and let real use determine priorities.' }, proof: { zh: '观察：付费转化、续订、机构留存与赞助交付结果。', en: 'Measure: paid conversion, renewals, organisation retention and sponsor deliverables.' } },
  { period: { zh: '长期 · 1–3 年', en: 'Long term · 1–3 years' }, title: { zh: '成为贯穿学习、训练与交流的魔方平台。', en: 'Connect learning, practice and community.' }, body: { zh: '让个人训练数据、教学反馈与赛事信息相互连接，逐步扩大中英双语内容和合作网络，向全球性的魔方平台发展。', en: 'Connect training records, teaching feedback and competition information; expand bilingual content and partnerships towards a global cubing platform.' }, proof: { zh: '方向：长期使用、可持续收入与可复制的服务能力。', en: 'Focus: lasting use, sustainable revenue and repeatable service delivery.' } },
] as const;

export default function OverviewPage() {
  return <main className="overview-page">
    <header className="overview-nav overview-wrap">
      <AppLink href="/" prefetch={false} className="overview-brand">CubeRoot<span>{tr({ zh: '魔方根', en: 'Built for cubers' })}</span></AppLink>
      <div className="overview-actions"><button type="button" onClick={() => window.print()}><Printer size={16} aria-hidden />{tr({ zh: '打印 / PDF', en: 'Print / PDF' })}</button><HeaderToggles /></div>
    </header>

    <section className="overview-hero overview-wrap" aria-labelledby="overview-title">
      <div className="overview-hero-copy">
        <p className="overview-kicker">{tr({ zh: '项目介绍 · 面向投资与赞助交流', en: 'Project brief · funding & sponsorship conversations' })}</p>
        <h1 id="overview-title">{tr({ zh: '把对魔方的热爱，\n做成长期有用的工具。', en: 'A love of cubing.\nTools built to last.' })}</h1>
        <p className="overview-lead">{tr({ zh: 'CubeRoot 是由颜瑞民创立并维护的魔方工具与学习平台。以训练、公式、复盘和比赛数据为起点，逐步连接爱好者、老师、机构与品牌。', en: 'Founded and maintained by Ruimin Yan, CubeRoot is a cubing tools and learning platform. Starting with practice, algorithms, solve analysis and competition data, it aims to connect cubers, teachers, organisations and brands.' })}</p>
        <a href="#overview-product" className="overview-primary">{tr({ zh: '看看已经做出的产品', en: 'Explore the product' })}<ArrowUpRight size={17} aria-hidden /></a>
        <a href="#overview-funding" className="overview-funding-request">{tr({ zh: '本轮资金需求：人民币 20 万—50 万元', en: 'Funding sought: CNY 200,000–500,000' })}<ArrowUpRight size={16} aria-hidden /></a>
        <p className="overview-reading">{tr({ zh: '约 8 分钟阅读 · 2026 年 10 月', en: 'About an 8-minute read · October 2026' })}</p>
      </div>
      <figure className="overview-cover"><img src="/images/overview/cubing-cover-v1.webp" width={1536} height={1024} alt={tr({ zh: '魔方与抽象学习、数据元素组成的概念插画', en: 'Concept illustration of a cube with abstract learning and data elements' })} fetchPriority="high" /><figcaption>{tr({ zh: 'AI 生成概念插画', en: 'AI-generated concept illustration' })}</figcaption></figure>
    </section>

    <div className="overview-summary overview-wrap">
      {[{ label: { zh: '服务对象', en: 'For' }, text: { zh: '爱好者 · 选手 · 老师与机构', en: 'Cubers · competitors · educators' } }, { label: { zh: '已有基础', en: 'Built so far' }, text: { zh: '可体验的 Web 工具与学习内容', en: 'Web tools and learning content' } }, { label: { zh: '发展方向', en: 'Next' }, text: { zh: '进阶服务 · 教学工具 · 品牌合作', en: 'Advanced services · teaching · partnerships' } }].map(item => <div key={item.label.en}><span>{tr(item.label)}</span><strong>{tr(item.text)}</strong></div>)}
    </div>

    <section className="overview-section overview-wrap overview-founder" aria-labelledby="overview-founder-title">
      <div><p className="overview-kicker">{tr({ zh: '01 / 创始人', en: '01 / Founder' })}</p><h2 id="overview-founder-title">{tr({ zh: '懂数学，\n也在魔方圈里。', en: 'Mathematical roots.\nA cuber’s perspective.' })}</h2><AppLink href="/about/ruimin" prefetch={false} className="overview-text-link">{tr({ zh: '颜瑞民 · 完整个人介绍与获奖档案', en: 'Ruimin Yan · full profile and award archive' })}<ArrowUpRight size={16} aria-hidden /></AppLink></div>
      <div className="overview-story"><p>{tr({ zh: '我在南开大学学习数学与金融数学、物理学，之后取得乔治华盛顿大学数学硕士学位。数学和科学计算的训练，让我习惯把复杂问题拆开、建模，再做成可以验证的工具。', en: 'I studied Mathematics and Financial Mathematics, and Physics at Nankai University, then earned a master’s degree in Mathematics at the George Washington University. Mathematics and scientific computing taught me to break complex problems down, model them and build tools whose results can be checked.' })}</p><p>{tr({ zh: '自 2017 年起参加 WCA 比赛，也持续做速拧课程设计、公式库建设与魔方内容创作，著有《超脑思维：魔方游戏技巧从入门到精通》。这些经历，是 CubeRoot 产品方向的基础：把专业知识变成更容易学习、更方便使用的东西。', en: 'I have competed in WCA events since 2017 and work on speedcubing courses, algorithm libraries and cubing content. I wrote Superbrain Thinking: Rubik’s Cube Skills from Beginner to Mastery. These experiences underpin CubeRoot: turning specialist knowledge into resources that are easier to learn from and use.' })}</p><div className="overview-founder-note"><School size={24} aria-hidden /><p>{tr({ zh: '数学与物理背景 × 参赛经历 × 教学与内容 × 产品开发', en: 'Mathematics & physics × competing × teaching & content × product development' })}</p></div></div>
    </section>

    <section className="overview-section overview-wrap" aria-labelledby="overview-market-title">
      <p className="overview-kicker">{tr({ zh: '02 / 魔方圈与机会', en: '02 / Cubing & the opportunity' })}</p><h2 id="overview-market-title">{tr({ zh: '赛事连接世界，\n日常进步需要工具。', en: 'Competitions connect the world.\nProgress happens every day.' })}</h2>
      <div className="overview-market-grid"><div className="overview-market-fact" data-site-surface="panel"><Globe2 size={27} aria-hidden /><strong>1,864</strong><p>{tr({ zh: '2025 年 WCA 世界锦标赛参赛人数', en: 'Competitors at the 2025 WCA World Championship' })}</p><a href="https://www.worldcubeassociation.org/competitions/WC2025" target="_blank" rel="noopener noreferrer">{tr({ zh: '来源：WCA 官方赛事页 ↗', en: 'Source: official WCA event page ↗' })}</a></div><div className="overview-story"><p>{tr({ zh: '魔方拥有跨地区的比赛体系与公开成绩数据。WCA 为外部分析提供成绩导出，给训练研究、赛事服务与数据产品带来基础。', en: 'Cubing has an international competition system and public results. WCA results exports provide a foundation for training research, event services and data products.' })} <a href="https://www.worldcubeassociation.org/export/results" target="_blank" rel="noopener noreferrer">WCA ↗</a></p><p>{tr({ zh: 'CubeRoot 的判断是：比赛之外，爱好者仍需要持续学习、训练和复盘，老师需要理解学员的进步，品牌需要与真实使用场景建立联系。这些需求能否形成稳定付费，需要用产品和试点验证。', en: 'CubeRoot’s thesis is that beyond competitions, cubers need ongoing learning, practice and analysis; teachers need to understand student progress; brands need meaningful connections with real usage. Product use and pilots must establish whether these needs support recurring revenue.' })}</p><p className="overview-small">{tr({ zh: '赛事人数用于说明一个具体赛事的规模，不代表市场总量或本站用户数。', en: 'The event count describes one competition, not the total market or CubeRoot’s user base.' })}</p></div></div>
    </section>

    <section id="overview-product" className="overview-section overview-wrap" aria-labelledby="overview-product-title">
      <p className="overview-kicker">{tr({ zh: '03 / 产品基础', en: '03 / Product foundation' })}</p><div className="overview-section-head"><h2 id="overview-product-title">{tr({ zh: '有产品，才有下一步。', en: 'A working foundation for what comes next.' })}</h2><AppLink href="/achievements" prefetch={false} className="overview-text-link">{tr({ zh: '查看原创工作', en: 'Explore original work' })}<ArrowUpRight size={16} aria-hidden /></AppLink></div>
      <div className="overview-product-grid">{PRODUCTS.map(({ Icon, href, title, body, tag }) => <AppLink href={href} prefetch={false} className="overview-product" data-site-surface="panel" key={href}><Icon size={27} strokeWidth={1.5} aria-hidden /><span className="overview-small">{tr(tag)}</span><h3>{tr(title)}</h3><p>{tr(body)}</p><span className="overview-text-link">{tr({ zh: '打开体验', en: 'Try it' })}<ArrowUpRight size={16} aria-hidden /></span></AppLink>)}</div>
      <div className="overview-engine"><VisualCube view="iso" algorithm="R U R' U'" size={170} local alt={tr({ zh: '可计算、可展示的魔方状态', en: 'A cube state that can be computed and visualised' })} /><div><h3>{tr({ zh: '专业能力，进入日常使用。', en: 'Specialist work, everyday use.' })}</h3><p>{tr({ zh: '求解器、打乱难度分析、状态可视化与数据统计，为进阶体验提供技术基础。网站同时使用公开数据与开源项目，保留来源与致谢。', en: 'Solvers, scramble difficulty analysis, state visualisation and statistics provide the technical foundation for advanced experiences. Public data and open-source projects are used with attribution.' })}</p><AppLink href="/about" prefetch={false} className="overview-text-link">{tr({ zh: '数据与开源致谢', en: 'Data & open-source credits' })}<ArrowUpRight size={15} aria-hidden /></AppLink></div></div>
    </section>

    <section className="overview-section overview-wrap" aria-labelledby="overview-plan-title"><p className="overview-kicker">{tr({ zh: '04 / 阶段规划', en: '04 / Roadmap' })}</p><h2 id="overview-plan-title">{tr({ zh: '从可靠工具，走向长期平台。', en: 'From reliable tools to a lasting platform.' })}</h2><p className="overview-intro">{tr({ zh: '以下是本提案建议的推进节奏，随资金、试用反馈与团队能力调整；多端客户端和教学系统正在推进，不等于已经全面发布或完成商业验证。', en: 'This brief proposes a sequence that can adapt to funding, feedback and team capacity. Cross-platform clients and teaching systems are in development; that does not imply full release or commercial validation.' })}</p><ol className="overview-roadmap">{ROADMAP.map((item, index) => <li key={item.period.en}><span className="overview-step">0{index + 1}</span><div><p className="overview-kicker">{tr(item.period)}</p><h3>{tr(item.title)}</h3><p>{tr(item.body)}</p><p className="overview-measure">{tr(item.proof)}</p></div></li>)}</ol></section>

    <section className="overview-section overview-wrap" aria-labelledby="overview-business-title"><p className="overview-kicker">{tr({ zh: '05 / 可持续发展', en: '05 / Sustainability' })}</p><h2 id="overview-business-title">{tr({ zh: '让使用价值，支撑持续投入。', en: 'Let useful work sustain further work.' })}</h2><div className="overview-business-grid">{[
      { title: { zh: '个人进阶服务', en: 'Advanced individual services' }, body: { zh: '保留基础工具的使用价值，探索训练分析、个性化学习与长期记录等进阶服务的订阅需求。', en: 'Preserve the value of core tools while testing subscription demand for deeper analysis, personalised learning and long-term records.' } },
      { title: { zh: '机构教学工具', en: 'Tools for educators' }, body: { zh: '围绕训练任务、学员进步与教学反馈，从小规模真实试用验证机构订阅和服务价值。', en: 'Use real pilots around training assignments, student progress and teaching feedback to validate organisational subscriptions.' } },
      { title: { zh: '品牌与内容合作', en: 'Brand & content partnerships' }, body: { zh: '围绕工具使用、课程内容或活动约定赞助权益，按周期报告实际交付和触达结果。', en: 'Agree sponsorship deliverables around tools, educational content or activities, and report actual delivery and reach by period.' } },
    ].map(item => <article key={item.title.en}><h3>{tr(item.title)}</h3><p>{tr(item.body)}</p></article>)}</div><p className="overview-small">{tr({ zh: '上述是商业验证方向。网站使用量、收入、续订率与具体预算，应在合作沟通中提供可核对的统计与材料。', en: 'These are commercial hypotheses. Usage, revenue, renewal rates and budgets should be supported with reviewable records during partner discussions.' })}</p></section>

    <CostsFunding />
    <section className="overview-section overview-wrap overview-partner" aria-labelledby="overview-partner-title"><div><p className="overview-kicker">{tr({ zh: '09 / 开始合作', en: '09 / Next steps' })}</p><h2 id="overview-partner-title">{tr({ zh: '把下一年的计划，\n变成可共同推进的项目。', en: 'Turn the next year’s plan\ninto a shared undertaking.' })}</h2><p className="overview-intro">{tr({ zh: '希望争取 20 万到 50 万元，支持下一阶段产品与商业验证。欢迎先体验产品，再围绕融资、赞助或项目资助讨论一份具体的合作安排。', en: 'Seeking CNY 200,000–500,000 for the next stage of product and business validation. Try the tools, then discuss a concrete financing, sponsorship or project-support arrangement.' })}</p><AppLink href="/contact" prefetch={false} className="overview-primary">{tr({ zh: '联系颜瑞民，讨论合作', en: 'Contact Ruimin Yan to discuss partnering' })}<ArrowUpRight size={17} aria-hidden /></AppLink><p className="overview-print-url">cuberoot.me/zh/overview</p></div><div className="overview-use-of-funds" data-site-surface="panel"><HeartHandshake size={28} aria-hidden /><h3>{tr({ zh: '下一次沟通，明确四件事', en: 'Four decisions for our next conversation' })}</h3><ul><li>{tr({ zh: '合作方式与资金规模', en: 'Partnership type and funding amount' })}</li><li>{tr({ zh: '12 个月预算与阶段交付', en: '12-month budget and staged delivery' })}</li><li>{tr({ zh: '双方权益与成果统计口径', en: 'Partner rights and outcome measurement' })}</li><li>{tr({ zh: '拨付、复核与后续安排', en: 'Funding stages, reviews and next steps' })}</li></ul><p>{tr({ zh: '从一组明确目标开始，用真实使用和交付结果建立长期合作。', en: 'Start with clear objectives and build a lasting partnership through real use and delivery.' })}</p></div></section>
    <footer className="overview-footer overview-wrap"><strong>CubeRoot</strong><p>{tr({ zh: '颜瑞民 · 项目介绍 · 2026.10', en: 'Ruimin Yan · Project brief · 2026.10' })}</p><AppLink href="/about/ruimin" prefetch={false}>{tr({ zh: '个人履历', en: 'Founder profile' })}</AppLink><AppLink href="/contact" prefetch={false}>{tr({ zh: '联系方式', en: 'Contact' })}</AppLink></footer>
  </main>;
}
