/** Generated offline by solver/src/bin/second_layer_distribution.rs. */
export const FIRST_LAYER_SOLVED_SECOND_LAYER_EXAMPLES: Readonly<Record<string, readonly string[]>> = {
  '0': [
    "",
  ],
  '5': [
    "F2 U2 F2 U2 F2",
    "F2 U2 F U2 F2",
    "F2 U2 F' U2 F2",
    "L2 D2 R2 D2 L2",
    "F2 D U' R2 D'",
    "R2 D' U F2 D",
    "L2 D2 R' D2 L2",
    "L2 D2 R D2 L2",
    "F2 D2 B2 D2 F2",
    "B2 D2 U2 F2 D2",
    "R2 D U' B2 D'",
    "B2 D U' L2 D'",
  ],
  '6': [
    "F L F L' U' F'",
    "F2 U2 F' U2 F2 U'",
    "F U L F' L' F'",
    "F2 U2 F U2 F2 U'",
    "R F R F' U' R'",
    "L2 D2 R' D2 L2 U'",
    "R U F R' F' R'",
    "L2 D2 R D2 L2 U'",
    "B2 D2 F' U2 F2 D2",
    "B2 D2 F U2 F2 D2",
    "B R B R' U' B'",
    "L U B L' B' L'",
  ],
  '7': [
    "L' U L F' L F L'",
    "F U2 R U2 R' U2 F'",
    "L U2 B L2 B' U2 L'",
    "F U F' U' L' U' L",
    "F U2 R U R' U2 F'",
    "L U2 B L B' U2 L'",
    "L U2 B L' B' U2 L'",
    "F U' F' U2 L' U2 L",
    "L' D2 F' U F D2 L",
    "F R L' U2 R' L F",
    "F L F L' U' F' U2",
    "R' D' F D F R F'",
  ],
  '8': [
    "B2 D2 R' D2 B2 U2 L' U",
    "B2 D2 R' D2 B2 U2 L' U2",
    "F R L' U2 R' L F U",
    "B2 D2 R' D2 B2 U2 L' U'",
    "L' D2 F' U F D2 L U2",
    "F R L' U2 R' L F U2",
    "L' D2 F' U F D2 L U'",
    "F R L' U2 R' L F U'",
    "B2 D2 R F2 D2 B2 L U'",
    "R D2 F U2 F' D2 R' U",
    "L2 F2 U2 L' U2 F2 L2 U'",
    "R F' U' F R' D' F D",
  ],
  '9': [
    "L2 U2 B L2 B' U2 L' U L'",
    "R' U R' U2 B' R2 B U2 R2",
    "R2 U2 F R2 F' U2 R' U R'",
    "L' U L' U2 F' L2 F U2 L2",
    "B U R D L2 B' L' D' R'",
    "L B L U' B' L2 B2 L B2",
    "F2 U' L' U' F' U2 F L F",
    "L2 U F U L U2 L' F' L'",
    "F' R' F' U R F2 R2 F' R2",
    "R' U' B' D' F2 R F D B",
    "L U B U L2 U' L' B' L'",
    "L' U' F' U F L2 F2 L' F2",
  ],
  '10': [
    "L2 U F U L U2 L' F' L' U'",
    "F' R' F' U R F2 R2 F' R2 U'",
    "F U' F D2 R D B D F2 L",
    "R' U' B' D' F2 R F D B U'",
    "L D2 F D R D L2 B U L",
    "F2 D' L D U' F' D' U2 L2 D",
    "L2 D F' D' U L D U2 F2 D'",
    "L2 F' L2 F2 L U L' U' F' U'",
    "R2 F R2 F2 R' U' F R F U'",
    "F' D2 L' D' B' D' F2 R' U' F'",
    "F' L' F' U2 F U L U F2 U'",
    "F L2 D R D B D2 L U' L",
  ],
  '11': [
    "F2 D2 R' B' U' B' D2 U F2 U' L'",
    "B L' D' R' D' R F' D2 L2 B' L'",
    "B' R' U2 R L2 D' R' D' F' D2 L2",
    "L D' U B D' U R D' U F D'",
    "B' U' R2 D2 U L' U' L' F' D2 R2",
    "F L F2 D2 R B' D B D F L'",
    "F D' U L D' U B D' U R D'",
    "B2 D2 R' D' F' D' B2 F U2 F' L'",
    "R D' U F D' U L D' U B D'",
    "B D' U R D' U F D' U L D'",
    "L2 D F' D' U L D U2 F2 D' U'",
    "F' D2 L' D' B' D' F2 R' U' F' U'",
  ],
  '12': [
    "L D' B D U F L D' B D2 R D'",
    "L2 D' U L U B' D' R2 B' D' R D'",
    "R' B' D L' D2 F' D U' B' D L' D'",
    "L D' B D' U R' D B D' U R2 D2",
    "R2 D U' B' D' R D U' B' D L' D2",
    "B D' R' B2 D' R' U F D' U F2 D'",
    "F2 L' F' D R F D U B D L2 D",
    "F2 R F D' L' F' D' U' B' D' R2 D'",
    "B D B' L D L F D F2 D2 L' D'",
    "R' D2 F2 D F R D R B' D B D'",
    "R2 U' B F' R B2 D U' B' R L' D'",
    "F2 D U R D B' U B2 L U2 L' D2",
  ],
  '13': [
    "R F' D B F D F2 U L2 F D L' D2",
    "L2 D' U L U B' D' R2 B' D' R D' U'",
    "R' B' D L' D2 F' D U' B' D L' D' U'",
    "B' L' D F' D2 R' D U' L' D F' D' U'",
    "R' D B' D U' F' D2 R' D B' L' D' U'",
    "F2 L D2 B' D U' L' U2 B D2 U2 R2 D'",
    "B2 R D2 F' D U' R' U2 F D2 U2 L2 D'",
    "L2 U2 B' F L' D' U B' D2 F2 R L' D'",
    "R2 D' U R U F' D' L2 F' D' L D' U'",
    "L' F' D R' D2 B' D U' F' D R' D' U'",
    "R2 F D2 L' D U' F' U2 L D2 U2 B2 D'",
    "L2 B D2 R' D U' B' U2 R D2 U2 F2 D'",
    "R L' B2 D2 F' D' U L' B F' U2 L2 D'",
    "F' R D2 B' R' U B' R2 B R B2 L' D2",
    "B R2 F' R' F2 R U' F R D2 F' L D2",
    "L B U F2 U2 L2 F' U B' U F2 U2 L'",
    "L' D F' D U' B' D2 L' D F' R' D' U'",
    "F' R' D B' D2 L' D U' R' D B' D' U'",
  ],
};
