import { Masking } from '@cuberoot/visualcube';

export interface MaskOption {
  value: string;
  label: string;
}

export const CORE_MASKS: MaskOption[] = [
  { value: '', label: '—' },
  { value: Masking.FL, label: 'FL' },
  { value: Masking.F2L, label: 'F2L' },
  { value: Masking.LL, label: 'LL' },
  { value: Masking.CLL, label: 'CLL' },
  { value: Masking.ELL, label: 'ELL' },
  { value: Masking.OLL, label: 'OLL' },
  { value: Masking.OCLL, label: 'OCLL' },
  { value: Masking.OELL, label: 'OELL' },
  { value: Masking.COLL, label: 'COLL' },
  { value: Masking.OCELL, label: 'OCELL' },
  { value: Masking.WV, label: 'WV' },
  { value: Masking.VH, label: 'VH' },
  { value: Masking.ELS, label: 'ELS' },
  { value: Masking.CLS, label: 'CLS' },
  { value: Masking.CMLL, label: 'CMLL' },
  { value: Masking.CROSS, label: 'CROSS' },
  { value: Masking.F2L1, label: 'F2L #1' },
  { value: Masking.F2L2, label: 'F2L #2' },
  { value: Masking.F2L3, label: 'F2L #3' },
  { value: Masking.F2LSM, label: 'F2L SM' },
  { value: Masking.F2B, label: 'F2B' },
  { value: Masking.LINE, label: 'LINE' },
];

export const EXTENDED_MASKS: MaskOption[] = [
  { value: Masking.TWO_BY_TWO_BY_TWO, label: '2x2x2' },
  { value: Masking.TWO_BY_TWO_BY_THREE, label: '2x2x3' },
  { value: Masking.ONE_ONE_TWO, label: '1x1x2' },
  { value: Masking.ONE_TWO_TWO, label: '1x2x2' },
  { value: Masking.CROSS_PARTIAL, label: 'Cross (partial)' },
  { value: Masking.CROSS_FR, label: 'Cross FR' },
  { value: Masking.CROSS_BR, label: 'Cross BR' },
  { value: Masking.CROSS_FB, label: 'Cross FB' },
  { value: Masking.CROSS_LR, label: 'Cross LR' },
  { value: Masking.XCROSS_FR, label: 'XCross FR' },
  { value: Masking.XCROSS_BR, label: 'XCross BR' },
  { value: Masking.XCROSS_FL, label: 'XCross FL' },
  { value: Masking.XCROSS_BL, label: 'XCross BL' },
  { value: Masking.XXCROSS, label: 'XXCross' },
  { value: Masking.DEC, label: 'DEC' },
  { value: Masking.TEC_FR, label: 'TEC FR' },
  { value: Masking.TEC_FL, label: 'TEC FL' },
  { value: Masking.TEC_BL, label: 'TEC BL' },
  { value: Masking.TEC_BR, label: 'TEC BR' },
  { value: Masking.PAIR, label: 'Pair' },
  { value: Masking.EO_ORBIT, label: 'EO orbit' },
  { value: Masking.EO_OUTER_ORBIT, label: 'EO outer orbit' },
  { value: Masking.EOLRB_R, label: 'EOLRb R' },
  { value: Masking.EOLRB_L, label: 'EOLRb L' },
  { value: Masking.EOLRB_F, label: 'EOLRb F' },
  { value: Masking.EOLRB_B, label: 'EOLRb B' },
  { value: Masking.FB, label: 'Roux FB' },
  { value: Masking.SB, label: 'Roux SB' },
  { value: Masking.FB1, label: 'Roux FB1' },
  { value: Masking.FB2, label: 'Roux FB2' },
  { value: Masking.SB1, label: 'Roux SB1' },
  { value: Masking.SB2, label: 'Roux SB2' },
  { value: Masking.ROUX_CO, label: 'Roux CO' },
  { value: Masking.ROUX_DR, label: 'Roux DR' },
  { value: Masking.ROUX_DR_ONLY, label: 'Roux DR-only' },
  { value: Masking.TWO_TWO_TWO_FL, label: '2x2x2 FL' },
  { value: Masking.TWO_TWO_TWO_BL, label: '2x2x2 BL' },
  { value: Masking.TWO_TWO_TWO_BR, label: '2x2x2 BR' },
  { value: Masking.SQ_RDF, label: 'SQ RDF' },
  { value: Masking.SQ_FDR, label: 'SQ FDR' },
  { value: Masking.SQ_DFR, label: 'SQ DFR' },
  { value: Masking.DR, label: 'DR' },
  { value: Masking.DR_R, label: 'DR R' },
  { value: Masking.DR_R_U2_RP, label: "DR R U2 R'" },
  { value: Masking.DR_R_U_RP, label: "DR R U R'" },
  { value: Masking.DR_R_UP_RP, label: "DR R U' R'" },
  { value: Masking.DR_U, label: 'DR U' },
  { value: Masking.MEHTA_SQ, label: 'Mehta Sq' },
  { value: Masking.MEHTA_BELT2, label: 'Mehta Belt2' },
  { value: Masking.MEHTA_EOLE2, label: 'Mehta EOLE2' },
  { value: Masking.MEHTA_TDR, label: 'Mehta TDR' },
  { value: Masking.EOLS, label: 'EOLS' },
  { value: Masking.L5EF, label: 'L5EF' },
  { value: Masking.OLLCP, label: 'OLLCP' },
  { value: Masking.CLL_FULL, label: 'CLL (full)' },
];

export const SIZE2_MASKS: MaskOption[] = [
  { value: Masking.FF, label: 'FF (First Face)' },
];

export const SIZE4_MASKS: MaskOption[] = [
  { value: Masking.F1C, label: 'F1C' },
  { value: Masking.F2C, label: 'F2C' },
  { value: Masking.L2C, label: 'L2C' },
  { value: Masking.CENTER, label: 'Center' },
  { value: Masking.F1E, label: 'F1E' },
  { value: Masking.LCE, label: 'LCE' },
  { value: Masking.NO_CORNER, label: 'No Corner' },
  { value: Masking.HOYA, label: 'Hoya' },
  { value: Masking.YAU, label: 'Yau' },
  { value: Masking.MEYER, label: 'Meyer' },
  { value: Masking.HALF_CENTER, label: 'Half Center' },
];

export const SIZE5_MASKS: MaskOption[] = [
  { value: Masking.ONE_BY_THREE, label: '1x3' },
  { value: Masking.TWO_BY_THREE, label: '2x3' },
  { value: Masking.THREE_BY_THREE, label: '3x3' },
  { value: Masking.TWO_BY_TWO, label: '2x2' },
  { value: Masking.T, label: 'T' },
  { value: Masking.L2C, label: 'L2C' },
  { value: Masking.L2E, label: 'L2E' },
  { value: Masking.L1E, label: 'L1E' },
  { value: Masking.CENTER, label: 'Center' },
  { value: Masking.MIDGE, label: 'Midge' },
  { value: Masking.T_CENTER, label: 'T Center' },
  { value: Masking.X_CENTER, label: 'X Center' },
  { value: Masking.WING, label: 'Wing' },
];

export const SIZE6_MASKS: MaskOption[] = [
  { value: Masking.ONE_BY_FOUR, label: '1x4' },
  { value: Masking.TWO_BY_FOUR, label: '2x4' },
  { value: Masking.THREE_BY_FOUR, label: '3x4' },
  { value: Masking.FOUR_BY_FOUR, label: '4x4' },
  { value: Masking.TWO_BY_TWO, label: '2x2' },
  { value: Masking.THREE_BY_THREE, label: '3x3' },
  { value: Masking.T, label: 'T' },
  { value: Masking.THREE_ONE_BY_FOUR, label: '3+1x4' },
  { value: Masking.L2C, label: 'L2C' },
  { value: Masking.L2E, label: 'L2E' },
  { value: Masking.L1E, label: 'L1E' },
  { value: Masking.OBLIQUE, label: 'Oblique' },
  { value: Masking.CENTER, label: 'Center' },
];

export const SIZE7_MASKS: MaskOption[] = [
  { value: Masking.ONE_BY_FIVE, label: '1x5' },
  { value: Masking.TWO_BY_FIVE, label: '2x5' },
  { value: Masking.THREE_BY_FIVE, label: '3x5' },
  { value: Masking.FOUR_BY_FIVE, label: '4x5' },
  { value: Masking.FIVE_BY_FIVE, label: '5x5' },
  { value: Masking.TWO_BY_TWO, label: '2x2' },
  { value: Masking.THREE_BY_THREE, label: '3x3' },
  { value: Masking.FOUR_BY_FOUR, label: '4x4' },
  { value: Masking.L2C, label: 'L2C' },
  { value: Masking.L2E, label: 'L2E' },
  { value: Masking.L1E, label: 'L1E' },
  { value: Masking.CENTER, label: 'Center' },
];

export const SIZE9_MASKS: MaskOption[] = [
  { value: Masking.UB, label: 'UB' },
];

export const MASK_ROTATIONS = ['', 'x', "x'", 'x2', 'y', "y'", 'y2', 'z', "z'", 'z2'];

// ── Stage cheat-sheet (/visualcube/stages) ──────────────────────────────────

export interface StageEntry {
  label: string;
  mask: string;
}

export interface StageSection {
  title: { en: string; zh: string };
  cubeSize: number;
  items: StageEntry[];
}

export const STAGE_SECTIONS: StageSection[] = [
  {
    title: { en: 'Origin (3x3)', zh: '原版 (3x3)' },
    cubeSize: 3,
    items: [
      { label: 'fl', mask: 'fl' },
      { label: 'f2l', mask: 'f2l' },
      { label: 'll', mask: 'll' },
      { label: 'cll', mask: 'cll' },
      { label: 'ell', mask: 'ell' },
      { label: 'oll', mask: 'oll' },
      { label: 'ocll', mask: 'ocll' },
      { label: 'oell', mask: 'oell' },
      { label: 'coll', mask: 'coll' },
      { label: 'ocell', mask: 'ocell' },
      { label: 'wv', mask: 'wv' },
      { label: 'vh', mask: 'vh' },
      { label: 'els', mask: 'els' },
      { label: 'cls', mask: 'cls' },
      { label: 'cmll', mask: 'cmll' },
      { label: 'cross', mask: 'cross' },
      { label: 'f2l_3', mask: 'f2l_3' },
      { label: 'f2l_2', mask: 'f2l_2' },
      { label: 'f2l_1', mask: 'f2l_1' },
      { label: 'f2l_sm', mask: 'f2l_sm' },
      { label: 'f2b', mask: 'f2b' },
      { label: 'line', mask: 'line' },
      { label: '2x2x2', mask: '2x2x2' },
      { label: '2x2x3', mask: '2x2x3' },
    ],
  },
  {
    title: { en: '3x3 (Custom)', zh: '3x3 (扩展)' },
    cubeSize: 3,
    items: [
      { label: 'FL', mask: 'fl' },
      { label: 'F2L', mask: 'f2l' },
      { label: '1LLL', mask: 'll' },
      { label: 'OLL', mask: 'oll' },
      { label: 'OLLCP', mask: 'ollcp' },
      { label: 'OLS', mask: 'cls' },
      { label: 'ELS', mask: 'els' },
      { label: 'L5EF', mask: 'l5ef' },
      { label: 'CLL', mask: 'cll_full' },
      { label: 'CMLL', mask: 'cmll' },
      { label: 'Roux_CO', mask: 'roux_co' },
      { label: 'Roux_DR', mask: 'roux_dr' },
      { label: 'Roux_DRonly', mask: 'roux_dronly' },
      { label: 'Cross_Center', mask: 'cross' },
      { label: 'Cross', mask: 'cross_partial' },
      { label: 'Cross_FR', mask: 'cross_fr' },
      { label: 'Cross_BR', mask: 'cross_br' },
      { label: 'Cross_FB', mask: 'cross_fb' },
      { label: 'Cross_LR', mask: 'cross_lr' },
      { label: 'Xcross_FR', mask: 'xcross_fr' },
      { label: 'Xcross_BR', mask: 'xcross_br' },
      { label: 'Xcross_FL', mask: 'xcross_fl' },
      { label: 'Xcross_BL', mask: 'xcross_bl' },
      { label: 'XXcross', mask: 'xxcross' },
      { label: 'DEC', mask: 'dec' },
      { label: 'TEC_FR', mask: 'tec_fr' },
      { label: 'TEC_FL', mask: 'tec_fl' },
      { label: 'TEC_BL', mask: 'tec_bl' },
      { label: 'TEC_BR', mask: 'tec_br' },
      { label: 'EO_Orbit', mask: 'eo_orbit' },
      { label: 'EO_Outer_Orbit', mask: 'eo_outer_orbit' },
      { label: 'EOLRb_R', mask: 'eolrb_r' },
      { label: 'EOLRb_L', mask: 'eolrb_l' },
      { label: 'EOLRb_F', mask: 'eolrb_f' },
      { label: 'EOLRb_B', mask: 'eolrb_b' },
      { label: 'EOLS', mask: 'eols' },
      { label: '112', mask: '112' },
      { label: '122', mask: '122' },
      { label: '222', mask: '2x2x2' },
      { label: '222_FL', mask: '222_fl' },
      { label: '222_BL', mask: '222_bl' },
      { label: '222_BR', mask: '222_br' },
      { label: '223', mask: '2x2x3' },
      { label: 'F2B', mask: 'f2b' },
      { label: 'FB1', mask: 'fb1' },
      { label: 'FB2', mask: 'fb2' },
      { label: 'SB1', mask: 'sb1' },
      { label: 'SB2', mask: 'sb2' },
      { label: 'FB', mask: 'fb' },
      { label: 'SB', mask: 'sb' },
      { label: 'SQ_RDF', mask: 'sq_rdf' },
      { label: 'SQ_FDR', mask: 'sq_fdr' },
      { label: 'SQ_DFR', mask: 'sq_dfr' },
      { label: 'Line', mask: 'line' },
      { label: 'DR', mask: 'dr' },
      { label: 'DR_R', mask: 'dr_r' },
      { label: 'DR_R_U2_Rp', mask: 'dr_r_u2_rp' },
      { label: 'DR_R_U_Rp', mask: 'dr_r_u_rp' },
      { label: 'DR_R_Up_Rp', mask: 'dr_r_up_rp' },
      { label: 'DR_U', mask: 'dr_u' },
      { label: 'Pair', mask: 'pair' },
      { label: 'Mehta_Sq', mask: 'mehta_sq' },
      { label: 'Mehta_Belt2', mask: 'mehta_belt2' },
      { label: 'Mehta_EOLE2', mask: 'mehta_eole2' },
      { label: 'Mehta_TDR', mask: 'mehta_tdr' },
    ],
  },
  {
    title: { en: '2x2', zh: '2x2' },
    cubeSize: 2,
    items: [
      { label: 'FF', mask: 'ff' },
      { label: 'FL', mask: 'fl' },
      { label: 'OLL', mask: 'oll' },
      { label: '1LLL', mask: 'll' },
    ],
  },
  {
    title: { en: '4x4', zh: '4x4' },
    cubeSize: 4,
    items: [
      { label: 'F1C', mask: 'f1c' },
      { label: 'F2C', mask: 'f2c' },
      { label: 'F1E', mask: 'f1e' },
      { label: 'LCE', mask: 'lce' },
      { label: 'L2C', mask: 'l2c' },
      { label: 'No_Corner', mask: 'no_corner' },
      { label: 'Center', mask: 'center' },
      { label: 'Yau', mask: 'yau' },
      { label: 'Hoya', mask: 'hoya' },
      { label: 'Meyer', mask: 'meyer' },
      { label: 'Half_Center', mask: 'half_center' },
      { label: 'OLL', mask: 'oll' },
    ],
  },
  {
    title: { en: '5x5', zh: '5x5' },
    cubeSize: 5,
    items: [
      { label: '1x3', mask: '1x3' },
      { label: '2x3', mask: '2x3' },
      { label: '3x3', mask: '3x3' },
      { label: '2x2', mask: '2x2' },
      { label: 'T', mask: 't' },
      { label: 'L2C', mask: 'l2c' },
      { label: 'L2E', mask: 'l2e' },
      { label: 'L1E', mask: 'l1e' },
      { label: 'Center', mask: 'center' },
      { label: 'Midge', mask: 'midge' },
      { label: 'T_Center', mask: 't_center' },
      { label: 'X_Center', mask: 'x_center' },
      { label: 'Wing', mask: 'wing' },
      { label: 'OLL', mask: 'oll' },
    ],
  },
  {
    title: { en: '6x6', zh: '6x6' },
    cubeSize: 6,
    items: [
      { label: '1x4', mask: '1x4' },
      { label: '2x4', mask: '2x4' },
      { label: '3x4', mask: '3x4' },
      { label: '4x4', mask: '4x4' },
      { label: '2x2', mask: '2x2' },
      { label: '3x3', mask: '3x3' },
      { label: 'T', mask: 't' },
      { label: '3_1x4', mask: '3_1x4' },
      { label: 'L2C', mask: 'l2c' },
      { label: 'L2E', mask: 'l2e' },
      { label: 'L1E', mask: 'l1e' },
      { label: 'Center', mask: 'center' },
      { label: 'Oblique', mask: 'oblique' },
      { label: 'OLL', mask: 'oll' },
    ],
  },
  {
    title: { en: '7x7', zh: '7x7' },
    cubeSize: 7,
    items: [
      { label: '1x5', mask: '1x5' },
      { label: '2x5', mask: '2x5' },
      { label: '3x5', mask: '3x5' },
      { label: '4x5', mask: '4x5' },
      { label: '5x5', mask: '5x5' },
      { label: '2x2', mask: '2x2' },
      { label: '3x3', mask: '3x3' },
      { label: '4x4', mask: '4x4' },
      { label: 'L2C', mask: 'l2c' },
      { label: 'L2E', mask: 'l2e' },
      { label: 'L1E', mask: 'l1e' },
      { label: 'Center', mask: 'center' },
      { label: 'OLL', mask: 'oll' },
    ],
  },
  {
    title: { en: '9x9', zh: '9x9' },
    cubeSize: 9,
    items: [
      { label: 'UB', mask: 'ub' },
    ],
  },
];
