/**
 * Static algorithm database — every set scraped from speedcubedb.com.
 *
 * Use {@link loadAlg} to lazy-import a (puzzle, set) pair. Each JSON is
 * code-split by Vite, so only opened sets ship to the browser.
 *
 * Data is generated by `scramble-stats-build/bin/scrape_speedcubedb.ts`.
 */

export interface AlgEntry {
  alg: string;
  altId?: string;
  /** YouTube finger-tricks tutorial id (no full URL — caller composes) */
  ytId?: string;
}

export type AlgSticker =
  | { kind: 'f2l'; fl: string }
  | { kind: 'face'; us: string; ub: string; uf: string; ul: string; ur: string }
  | { kind: 'raw'; tag: string; attrs: Record<string, string> };

export interface AlgCase {
  name: string;
  subgroup: string;
  setup: string;
  standard?: string;
  sticker: AlgSticker;
  /** F2L: 4 entries (FR / FL / BL / BR). Most others: single entry. */
  algs: AlgEntry[][];
  /** F2L only — names of each orientation tab (e.g. "Front Right") */
  oriNames?: string[];
}

export interface AlgFile {
  scrapedAt: string;
  source: string;
  /** "2x2" | "3x3" | "4x4" | "5x5" */
  puzzle: string;
  /** slug — e.g. "f2l", "zbll", "ortega-oll", "oll-parity" */
  set: string;
  cases: AlgCase[];
}

export type AlgPuzzle = '2x2' | '3x3' | '4x4' | '5x5' | 'sq1' | 'megaminx' | 'pyraminx' | 'skewb';

/** 3x3 set slug — matches `slug` in {@link ALG_CATALOG['3x3']}. */
export type Alg3x3Set =
  | 'f2l' | 'adv-f2l' | 'oll' | 'pll'
  | 'coll' | 'wv' | 'cmll' | 'sbls' | 'eo4a' | 'anti-pll' | 'sv' | 'ell' | 'fruf'
  | 'cls' | 'vls' | 'ollcp' | 'zbll' | '1lll' | 'zbls';

/** Catalogue of available sets per puzzle (display name + slug). Drives the index pages. */
export interface AlgSetMeta {
  /** URL slug (matches data filename: alg_<puzzle>_<slug>.json) */
  slug: string;
  /** Speedcubedb subset key (just for reference; not used at runtime) */
  scd: string;
  en: string;
  zh: string;
  /** True for sets that speedcubedb organises under sub-pages (ZBLL → ZBLL U/L/T/...).
   *  UI shows a subgroup-picker landing page first, then cases for the picked subgroup. */
  umbrella?: boolean;
}

export const ALG_CATALOG: Record<AlgPuzzle, AlgSetMeta[]> = {
  '2x2': [
    { slug: 'ortega-oll', scd: 'OrtegaOLL', en: 'Ortega OLL', zh: 'Ortega OLL' },
    { slug: 'ortega-pbl', scd: 'OrtegaPBL', en: 'Ortega PBL', zh: 'Ortega PBL' },
    { slug: 'cll',        scd: 'CLL',       en: 'CLL',        zh: 'CLL' },
    { slug: 'eg1',        scd: 'EG1',       en: 'EG 1',       zh: 'EG 1' },
    { slug: 'eg2',        scd: 'EG2',       en: 'EG 2',       zh: 'EG 2' },
  ],
  '3x3': [
    { slug: 'f2l',       scd: 'F2L',         en: 'F2L',                  zh: 'F2L (基础)' },
    { slug: 'adv-f2l',   scd: 'AdvancedF2L', en: 'Advanced F2L',         zh: 'F2L (进阶)' },
    { slug: 'oll',       scd: 'OLL',         en: 'OLL',                  zh: 'OLL' },
    { slug: 'pll',       scd: 'PLL',         en: 'PLL',                  zh: 'PLL' },
    { slug: 'coll',      scd: 'COLL',        en: 'COLL',                 zh: 'COLL' },
    { slug: 'wv',        scd: 'WV',          en: 'Winter Variation',     zh: 'Winter Variation' },
    { slug: 'cmll',      scd: 'CMLL',        en: 'CMLL',                 zh: 'CMLL' },
    { slug: 'sbls',      scd: 'SBLS',        en: 'Second Block Last Slot', zh: 'Second Block Last Slot' },
    { slug: 'eo4a',      scd: 'EO4A',        en: 'Edge Orientation (4a)', zh: 'Edge Orientation (4a)' },
    { slug: 'anti-pll',  scd: 'AntiPLL',     en: 'Anti PLL',             zh: 'Anti PLL' },
    { slug: 'sv',        scd: 'SV',          en: 'Summer Variation',     zh: 'Summer Variation' },
    { slug: 'ell',       scd: 'ELL',         en: 'Edges of the Last Layer (ELL)', zh: 'Edges of the Last Layer (ELL)' },
    { slug: 'fruf',      scd: 'FRUF',        en: "F <R,U> F'",           zh: "F <R,U> F'" },
    { slug: 'cls',       scd: 'CLS',         en: 'Corners Last Slot',    zh: 'Corners Last Slot' },
    { slug: 'zbls',      scd: 'ZBLS',        en: 'ZBLS',                 zh: 'ZBLS' },
    { slug: 'vls',       scd: 'VLS',         en: 'VLS',                  zh: 'VLS',   umbrella: true },
    { slug: 'ollcp',     scd: 'OLLCP',       en: 'OLLCP',                zh: 'OLLCP', umbrella: true },
    { slug: 'zbll',      scd: 'ZBLL',        en: 'ZBLL',                 zh: 'ZBLL',  umbrella: true },
    { slug: '1lll',      scd: '1LLL',        en: '1LLL',                 zh: '1LLL',  umbrella: true },
  ],
  '4x4': [
    { slug: 'oll-parity', scd: 'OLLParity', en: 'OLL Parity', zh: 'OLL Parity' },
    { slug: 'pll-parity', scd: 'PLLParity', en: 'PLL Parity', zh: 'PLL Parity' },
  ],
  '5x5': [
    { slug: 'l2e', scd: 'L2E', en: 'Last Two Edges',   zh: 'Last Two Edges (L2E)' },
    { slug: 'l2c', scd: 'L2C', en: 'Last Two Centers', zh: 'Last Two Centers (L2C)' },
  ],
  'sq1': [
    { slug: 'cs',     scd: 'SQ1CS',     en: 'Cube Shape',          zh: '形状' },
    { slug: 'co',     scd: 'SQ1CO',     en: 'Corner Orientation',  zh: '角块定向 (CO)' },
    { slug: 'eo',     scd: 'SQ1EO',     en: 'Edge Orientation',    zh: '棱块定向 (EO)' },
    { slug: 'cp',     scd: 'SQ1CP',     en: 'Corner Permutation',  zh: '角块排列 (CP)' },
    { slug: 'ep',     scd: 'SQ1EP',     en: 'Edge Permutation',    zh: '棱块排列 (EP)' },
    { slug: 'parity', scd: 'SQ1Parity', en: 'Parity',              zh: 'Parity' },
  ],
  'megaminx': [
    { slug: 'eo', scd: 'MegaminxEO', en: 'Edge Orientation',    zh: '棱块定向 (EO)' },
    { slug: 'co', scd: 'MegaminxCO', en: 'Corner Orientation',  zh: '角块定向 (CO)' },
    { slug: 'ep', scd: 'MegaminxEP', en: 'Edge Permutation',    zh: '棱块排列 (EP)' },
    { slug: 'cp', scd: 'MegaminxCP', en: 'Corner Permutation',  zh: '角块排列 (CP)' },
  ],
  'pyraminx': [
    { slug: 'l3e', scd: 'L3E', en: 'Last 3 Edges', zh: 'Last 3 Edges (L3E)' },
    { slug: 'l4e', scd: 'L4E', en: 'Last 4 Edges', zh: 'Last 4 Edges (L4E)' },
  ],
  'skewb': [
    { slug: 'sarahs-advanced', scd: 'SarahsAdvanced', en: "Sarah's Advanced", zh: "Sarah's Advanced" },
  ],
};

export const ALG_PUZZLES: AlgPuzzle[] = ['2x2', '3x3', '4x4', '5x5', 'sq1', 'megaminx', 'pyraminx', 'skewb'];

export function getAlgSetMeta(puzzle: AlgPuzzle, slug: string): AlgSetMeta | undefined {
  return ALG_CATALOG[puzzle]?.find(s => s.slug === slug);
}

/** Lazy load — Vite code-splits each JSON. Throws on unknown (puzzle, set). */
export async function loadAlg(puzzle: AlgPuzzle, set: string): Promise<AlgFile> {
  const key = `${puzzle}/${set}`;
  switch (key) {
    // 2x2
    case '2x2/ortega-oll': return (await import('../data/alg_2x2_ortega-oll.json')).default as unknown as AlgFile;
    case '2x2/ortega-pbl': return (await import('../data/alg_2x2_ortega-pbl.json')).default as unknown as AlgFile;
    case '2x2/cll':        return (await import('../data/alg_2x2_cll.json')).default as unknown as AlgFile;
    case '2x2/eg1':        return (await import('../data/alg_2x2_eg1.json')).default as unknown as AlgFile;
    case '2x2/eg2':        return (await import('../data/alg_2x2_eg2.json')).default as unknown as AlgFile;
    // 3x3
    case '3x3/f2l':        return (await import('../data/alg_3x3_f2l.json')).default as unknown as AlgFile;
    case '3x3/adv-f2l':    return (await import('../data/alg_3x3_adv-f2l.json')).default as unknown as AlgFile;
    case '3x3/oll':        return (await import('../data/alg_3x3_oll.json')).default as unknown as AlgFile;
    case '3x3/pll':        return (await import('../data/alg_3x3_pll.json')).default as unknown as AlgFile;
    case '3x3/coll':       return (await import('../data/alg_3x3_coll.json')).default as unknown as AlgFile;
    case '3x3/wv':         return (await import('../data/alg_3x3_wv.json')).default as unknown as AlgFile;
    case '3x3/cmll':       return (await import('../data/alg_3x3_cmll.json')).default as unknown as AlgFile;
    case '3x3/sbls':       return (await import('../data/alg_3x3_sbls.json')).default as unknown as AlgFile;
    case '3x3/eo4a':       return (await import('../data/alg_3x3_eo4a.json')).default as unknown as AlgFile;
    case '3x3/anti-pll':   return (await import('../data/alg_3x3_anti-pll.json')).default as unknown as AlgFile;
    case '3x3/sv':         return (await import('../data/alg_3x3_sv.json')).default as unknown as AlgFile;
    case '3x3/ell':        return (await import('../data/alg_3x3_ell.json')).default as unknown as AlgFile;
    case '3x3/fruf':       return (await import('../data/alg_3x3_fruf.json')).default as unknown as AlgFile;
    case '3x3/cls':        return (await import('../data/alg_3x3_cls.json')).default as unknown as AlgFile;
    case '3x3/zbls':       return (await import('../data/alg_3x3_zbls.json')).default as unknown as AlgFile;
    case '3x3/vls':        return (await import('../data/alg_3x3_vls.json')).default as unknown as AlgFile;
    case '3x3/ollcp':      return (await import('../data/alg_3x3_ollcp.json')).default as unknown as AlgFile;
    case '3x3/zbll':       return (await import('../data/alg_3x3_zbll.json')).default as unknown as AlgFile;
    case '3x3/1lll':       return (await import('../data/alg_3x3_1lll.json')).default as unknown as AlgFile;
    // 4x4
    case '4x4/oll-parity': return (await import('../data/alg_4x4_oll-parity.json')).default as unknown as AlgFile;
    case '4x4/pll-parity': return (await import('../data/alg_4x4_pll-parity.json')).default as unknown as AlgFile;
    // 5x5
    case '5x5/l2e':        return (await import('../data/alg_5x5_l2e.json')).default as unknown as AlgFile;
    case '5x5/l2c':        return (await import('../data/alg_5x5_l2c.json')).default as unknown as AlgFile;
    // sq1
    case 'sq1/cs':         return (await import('../data/alg_sq1_cs.json')).default as unknown as AlgFile;
    case 'sq1/co':         return (await import('../data/alg_sq1_co.json')).default as unknown as AlgFile;
    case 'sq1/eo':         return (await import('../data/alg_sq1_eo.json')).default as unknown as AlgFile;
    case 'sq1/cp':         return (await import('../data/alg_sq1_cp.json')).default as unknown as AlgFile;
    case 'sq1/ep':         return (await import('../data/alg_sq1_ep.json')).default as unknown as AlgFile;
    case 'sq1/parity':     return (await import('../data/alg_sq1_parity.json')).default as unknown as AlgFile;
    // megaminx
    case 'megaminx/eo':    return (await import('../data/alg_megaminx_eo.json')).default as unknown as AlgFile;
    case 'megaminx/co':    return (await import('../data/alg_megaminx_co.json')).default as unknown as AlgFile;
    case 'megaminx/ep':    return (await import('../data/alg_megaminx_ep.json')).default as unknown as AlgFile;
    case 'megaminx/cp':    return (await import('../data/alg_megaminx_cp.json')).default as unknown as AlgFile;
    // pyraminx
    case 'pyraminx/l3e':   return (await import('../data/alg_pyraminx_l3e.json')).default as unknown as AlgFile;
    case 'pyraminx/l4e':   return (await import('../data/alg_pyraminx_l4e.json')).default as unknown as AlgFile;
    // skewb
    case 'skewb/sarahs-advanced': return (await import('../data/alg_skewb_sarahs-advanced.json')).default as unknown as AlgFile;
    default:
      throw new Error(`unknown alg set: ${key}`);
  }
}
