/**
 * Static algorithm database — every set scraped from speedcubedb.com.
 *
 * Use {@link loadAlg} to lazy-import a (puzzle, set) pair. Each JSON is
 * code-split by Vite, so only opened sets ship to the browser.
 *
 * Data is generated by `scramble-stats-build/bin/scrape_speedcubedb.ts`.
 */

/** 公式标签。转写自站长 1LLL 表里的 `[oh]` / `[ft]` / `[fmc]` / `[big]` / `[key]`。 */
export type AlgTag = 'oh' | 'ft' | 'fmc' | 'big' | 'key';

export interface AlgEntry {
  /** Plain-text alg, used for clipboard copy (no HTML, but `[OH]` prefix and
   *  finger-trick UTF-8 chars like `·` `↑` `↓` `←` `→` are kept inline). */
  alg: string;
  /** Optional HTML markup for display, with whitelist tags `<u> <s> <em>
   *  <strong> <sub> <sup>` preserving docx finger-trick notation
   *  (underline / strike / italic-wave / bold / sub / sup). When absent,
   *  display falls back to plain `alg`. */
  algHtml?: string;
  altId?: string;
  /** YouTube finger-tricks tutorial id (no full URL — caller composes) */
  ytId?: string;
  /** 单手 / 脚拧 / 最少步 / 高阶 / 虚拟键盘。UI 据此做筛选。 */
  tags?: AlgTag[];
  /** 公式出处。站长自编的排在 speedcubedb 抓来的前面。 */
  source?: 'cuberoot' | 'speedcubedb';
  /** 这条公式**照写**的步数(`R4` = 1 STM / 4 SQTM —— 它是个真实的物理动作,见 alg_notation)。 */
  stm?: number;
  sqtm?: number;
}

/**
 * case 的富元数据。只有从站长自编的那张 1LLL 表导入的 case 才有,其余 `undefined`。
 * 字段多且只对一个 set 有意义,所以整块塞 `alg_cases.meta` JSONB,不给表加列。
 * 前端走弹窗展示,不占主视图。
 */
export interface AlgCaseMeta {
  /** 表里的 case 编号(1–3916;缺 0005 = LL 连跳) */
  no: number;
  /** OLLCP 名:`AB3` = OLL `A` + 角换 `B` + 识别特征 `3`(十六进制 1–9,A,B,C) */
  ollcp: string;
  /** `PLL` / `ZBLL-U` / `1LLL` / `ELL-A` … */
  subset: string;
  /** 字母制 OLL 名 */
  oll: string;
  /** 角换类型 */
  cp: string;
  /** 打乱 = 逆 case 的公式(已剥掉起手 AUF) */
  scramble?: string;
  /** 生成元集合,如 `FLlMU`(大小写不敏感排序,同字母按首次出现) */
  gen?: string;
  /** 叠加公式类型:`OO` = OLL+OLL、`OP` = OLL+PLL、`CC` = conjugate commutator … */
  type?: string;
  /** 镜像 / 逆 / 镜像逆 case 的**表编号**(不是 DB id —— 表编号才是站长认的那套) */
  mirror?: number;
  inv?: number;
  im?: number;
  /** 四套最优解:每个度量下的最优步数 + 对应打乱 */
  optimal?: Partial<Record<'stm' | 'sqtm' | 'htm' | 'qtm', { len: number; scramble?: string }>>;
  /** COEP(角朝向 + 棱排列)—— 只有 ZBLL / PLL 有 */
  coep?: { alg?: string; scramble?: string };
  /** 对称性 */
  sym?: {
    /** 循环对称阶,如 `C2` / `C4` */
    cn?: string;
    selfMirror?: boolean;
    selfInv?: boolean;
    any?: boolean;
    full?: boolean;
    anti?: boolean;
  };
  /** speedcubedb 的 ZBLL 编号(只有 472 行有) */
  sdbNo?: string;
  /** 旧编号,备查 */
  docNo?: string;
  oldNo?: string;
}

export type AlgSticker =
  | { kind: 'f2l'; fl: string }
  | { kind: 'face'; us: string; ub: string; uf: string; ul: string; ur: string }
  | { kind: 'raw'; tag: string; attrs: Record<string, string> };

export interface AlgCase {
  /** PG `alg_cases.id` — populated by API responses; absent in legacy code paths. */
  id?: number;
  name: string;
  /** Per-set business 编号 (F2L 1..41 = CFOP 文献规范);其它 set 为 undefined。跟 排序的 position 解耦。 */
  number?: number;
  subgroup: string;
  setup: string;
  standard?: string;
  sticker: AlgSticker;
  /** F2L: 4 entries (FR / FL / BL / BR). Most others: single entry. */
  algs: AlgEntry[][];
  /** F2L only — names of each orientation tab (e.g. "Front Right") */
  oriNames?: string[];
  /** ZBLS only — links cases into the trainer's grid layout. */
  trainerKey?: string;
  /** 1lll / zbll / pll / ell only — see {@link AlgCaseMeta}. */
  meta?: AlgCaseMeta;
}

export interface AlgFile {
  scrapedAt: string;
  source: string;
  /** "2x2" | "3x3" | "4x4" | "5x5" */
  puzzle: string;
  /** slug — e.g. "f2l", "zbll", "ortega-oll", "oll-parity" */
  set: string;
  cases: AlgCase[];
}

export type AlgPuzzle = '2x2' | '3x3' | '4x4' | '5x5' | 'sq1' | 'megaminx' | 'pyraminx' | 'skewb';

/** 3x3 set slug — matches `slug` in {@link ALG_CATALOG['3x3']}. */
export type Alg3x3Set =
  | 'f2l' | 'adv-f2l' | 'oll' | 'pll'
  | 'coll' | 'wv' | 'cmll' | 'sbls' | 'eo4a' | 'anti-pll' | 'sv' | 'ell' | 'fruf'
  | 'cls' | 'vls' | 'ollcp' | 'zbll' | '1lll' | 'zbls';

/** Catalogue of available sets per puzzle (display name + slug). Drives the index pages. */
export interface AlgSetMeta {
  /** URL slug (matches data filename: alg_<puzzle>_<slug>.json) */
  slug: string;
  /** Speedcubedb subset key (just for reference; not used at runtime) */
  scd: string;
  en: string;
  zh: string;
  /** True for sets that speedcubedb organises under sub-pages (ZBLL → ZBLL U/L/T/...).
   *  UI shows a subgroup-picker landing page first, then cases for the picked subgroup. */
  umbrella?: boolean;
}

export const ALG_CATALOG: Record<AlgPuzzle, AlgSetMeta[]> = {
  '2x2': [
    { slug: 'ortega-oll', scd: 'OrtegaOLL', en: 'Ortega OLL', zh: 'Ortega OLL' },
    { slug: 'ortega-pbl', scd: 'OrtegaPBL', en: 'Ortega PBL', zh: 'Ortega PBL' },
    { slug: 'cll',        scd: 'CLL',       en: 'CLL',        zh: 'CLL' },
    { slug: 'eg1',        scd: 'EG1',       en: 'EG 1',       zh: 'EG 1' },
    { slug: 'eg2',        scd: 'EG2',       en: 'EG 2',       zh: 'EG 2' },
  ],
  '3x3': [
    { slug: 'f2l',       scd: 'F2L',         en: 'F2L',                  zh: 'F2L (基础)' },
    { slug: 'adv-f2l',   scd: 'AdvancedF2L', en: 'Advanced F2L',         zh: 'F2L (进阶)' },
    { slug: 'oll',       scd: 'OLL',         en: 'OLL',                  zh: 'OLL' },
    { slug: 'pll',       scd: 'PLL',         en: 'PLL',                  zh: 'PLL' },
    { slug: 'coll',      scd: 'COLL',        en: 'COLL',                 zh: 'COLL' },
    { slug: 'wv',        scd: 'WV',          en: 'Winter Variation',     zh: 'Winter Variation' },
    { slug: 'cmll',      scd: 'CMLL',        en: 'CMLL',                 zh: 'CMLL' },
    { slug: 'sbls',      scd: 'SBLS',        en: 'Second Block Last Slot', zh: 'Second Block Last Slot' },
    { slug: 'eo4a',      scd: 'EO4A',        en: 'Edge Orientation (4a)', zh: 'Edge Orientation (4a)' },
    { slug: 'anti-pll',  scd: 'AntiPLL',     en: 'Anti PLL',             zh: 'Anti PLL' },
    { slug: 'sv',        scd: 'SV',          en: 'Summer Variation',     zh: 'Summer Variation' },
    { slug: 'ell',       scd: 'ELL',         en: 'Edges of the Last Layer (ELL)', zh: 'Edges of the Last Layer (ELL)' },
    { slug: 'fruf',      scd: 'FRUF',        en: "F <R,U> F'",           zh: "F <R,U> F'" },
    { slug: 'cls',       scd: 'CLS',         en: 'Corners Last Slot',    zh: 'Corners Last Slot' },
    { slug: 'zbls',      scd: 'ZBLS',        en: 'ZBLS',                 zh: 'ZBLS',  umbrella: true },
    { slug: 'vls',       scd: 'VLS',         en: 'VLS',                  zh: 'VLS',   umbrella: true },
    { slug: 'ollcp',     scd: 'OLLCP',       en: 'OLLCP',                zh: 'OLLCP', umbrella: true },
    { slug: 'zbll',      scd: 'ZBLL',        en: 'ZBLL',                 zh: 'ZBLL',  umbrella: true },
    { slug: '1lll',      scd: '1LLL',        en: '1LLL',                 zh: '1LLL',  umbrella: true },
  ],
  '4x4': [
    { slug: 'oll-parity', scd: 'OLLParity', en: 'OLL Parity', zh: 'OLL Parity' },
    { slug: 'pll-parity', scd: 'PLLParity', en: 'PLL Parity', zh: 'PLL Parity' },
  ],
  '5x5': [
    { slug: 'l2e', scd: 'L2E', en: 'Last Two Edges',   zh: 'Last Two Edges (L2E)' },
    { slug: 'l2c', scd: 'L2C', en: 'Last Two Centers', zh: 'Last Two Centers (L2C)' },
  ],
  'sq1': [
    { slug: 'cs',     scd: 'SQ1CS',     en: 'Cube Shape',          zh: '形状' },
    { slug: 'co',     scd: 'SQ1CO',     en: 'Corner Orientation',  zh: '角块定向 (CO)' },
    { slug: 'eo',     scd: 'SQ1EO',     en: 'Edge Orientation',    zh: '棱块定向 (EO)' },
    { slug: 'cp',     scd: 'SQ1CP',     en: 'Corner Permutation',  zh: '角块排列 (CP)' },
    { slug: 'ep',     scd: 'SQ1EP',     en: 'Edge Permutation',    zh: '棱块排列 (EP)' },
    { slug: 'parity', scd: 'SQ1Parity', en: 'Parity',              zh: 'Parity' },
  ],
  'megaminx': [
    { slug: 'eo', scd: 'MegaminxEO', en: 'Edge Orientation',    zh: '棱块定向 (EO)' },
    { slug: 'co', scd: 'MegaminxCO', en: 'Corner Orientation',  zh: '角块定向 (CO)' },
    { slug: 'ep', scd: 'MegaminxEP', en: 'Edge Permutation',    zh: '棱块排列 (EP)' },
    { slug: 'cp', scd: 'MegaminxCP', en: 'Corner Permutation',  zh: '角块排列 (CP)' },
  ],
  'pyraminx': [
    { slug: 'l3e', scd: 'L3E', en: 'Last 3 Edges', zh: 'Last 3 Edges (L3E)' },
    { slug: 'l4e', scd: 'L4E', en: 'Last 4 Edges', zh: 'Last 4 Edges (L4E)' },
  ],
  'skewb': [
    { slug: 'sarahs-advanced', scd: 'SarahsAdvanced', en: "Sarah's Advanced", zh: "Sarah's Advanced" },
  ],
};

export const ALG_PUZZLES: AlgPuzzle[] = ['2x2', '3x3', '4x4', '5x5', 'sq1', 'megaminx', 'pyraminx', 'skewb'];

export function getAlgSetMeta(puzzle: AlgPuzzle, slug: string): AlgSetMeta | undefined {
  return ALG_CATALOG[puzzle]?.find(s => s.slug === slug);
}

/**
 * Load an alg set from the server.
 *
 * Source of truth lives in the `alg_sets` / `alg_cases` PG tables; the 41 JSON
 * files that used to be code-split via Vite are gone. Browser caches per
 * `Cache-Control` header (1 hour by default).
 */
// `declare const process` keeps the literal `process.env.NODE_ENV` token sequence intact
// so Webpack/Turbopack can replace it with a string literal at build time. Wrapped in a
// function so the throw is contained (Vite browser bundles have no `process`).
declare const process: { env: { NODE_ENV?: string } };
function nodeProcessEnv(): string | undefined {
  return process.env.NODE_ENV;
}

export async function loadAlg(puzzle: AlgPuzzle, set: string, opts?: { fresh?: boolean }): Promise<AlgFile> {
  // NOTE: 用 import.meta.env.DEV 而不是 hostname 检查 — 走 LAN IP / 隧道域名(dev.cuberoot.me)
  // 等其它 dev host 时,hostname 检查会错判成 prod 直接打 api.cuberoot.me 跨域,
  // 而 api 的 CORS allowlist 没那些 host → 浏览器拦截。vite 在 client build 时
  // 替换 import.meta.env.DEV;server 端 loadAlg 不被调,?.DEV undefined 走 prod 分支也无害。
  // Next.js (client) 用 process.env.NODE_ENV — 同样在 client build 时被替换。
  const viteDev = Boolean((import.meta as { env?: { DEV?: boolean } }).env?.DEV);
  // Webpack/Turbopack replace `process.env.NODE_ENV` as a string literal at build time,
  // but only when accessed by that literal token sequence. Vite browsers don't replace
  // it, and `process` isn't defined globally — wrap in try so it doesn't ReferenceError.
  // process.env.NODE_ENV is replaced by Webpack/Turbopack as a string literal at build
  // time; in Vite browser bundles process doesn't exist, so guard with try/catch.
  // `declare const process` keeps the literal token sequence so the bundler replaces it.
  let nodeEnv: string | undefined;
  try { nodeEnv = nodeProcessEnv(); } catch { /* not in Node/bundler context */ }
  const isDev = viteDev || nodeEnv === 'development';
  const base = isDev
    ? '/v1/alg/sets'  // dev: vite proxy
    : 'https://api.cuberoot.me/v1/alg/sets';  // prod: 跨域到 API 子域
  // NOTE: fresh=true 给 admin 用,绕开 1 小时 Cache-Control。
  // 通过 query 时间戳 cache-bust + cache:'no-cache' header,跨浏览器最稳。
  const url = `${base}/${encodeURIComponent(puzzle)}/${encodeURIComponent(set)}`
    + (opts?.fresh ? `?_=${Date.now()}` : '');
  const res = await fetch(url, opts?.fresh ? { cache: 'no-cache' } : undefined);
  if (!res.ok) {
    throw new Error(`Failed to load alg ${puzzle}/${set}: HTTP ${res.status}`);
  }
  return (await res.json()) as AlgFile;
}
