/**
 * Static algorithm database — every set scraped from speedcubedb.com.
 *
 * Use {@link loadAlgdb} to lazy-import a (puzzle, set) pair. Each JSON is
 * code-split by Vite, so only opened sets ship to the browser.
 *
 * Data is generated by `scramble-stats-build/bin/scrape_speedcubedb.ts`.
 */

export interface AlgdbEntry {
  alg: string;
  altId?: string;
  /** YouTube finger-tricks tutorial id (no full URL — caller composes) */
  ytId?: string;
}

export type AlgdbSticker =
  | { kind: 'f2l'; fl: string }
  | { kind: 'face'; us: string; ub: string; uf: string; ul: string; ur: string }
  | { kind: 'raw'; tag: string; attrs: Record<string, string> };

export interface AlgdbCase {
  name: string;
  subgroup: string;
  setup: string;
  standard?: string;
  sticker: AlgdbSticker;
  /** F2L: 4 entries (FR / FL / BL / BR). Most others: single entry. */
  algs: AlgdbEntry[][];
  /** F2L only — names of each orientation tab (e.g. "Front Right") */
  oriNames?: string[];
}

export interface AlgdbFile {
  scrapedAt: string;
  source: string;
  /** "2x2" | "3x3" | "4x4" | "5x5" */
  puzzle: string;
  /** slug — e.g. "f2l", "zbll", "ortega-oll", "oll-parity" */
  set: string;
  cases: AlgdbCase[];
}

export type AlgdbPuzzle = '2x2' | '3x3' | '4x4' | '5x5';

/** 3x3 set slug — matches `slug` in {@link ALGDB_CATALOG['3x3']}. */
export type Algdb3x3Set =
  | 'f2l' | 'adv-f2l' | 'oll' | 'pll'
  | 'coll' | 'wv' | 'cmll' | 'sbls' | 'eo4a' | 'anti-pll' | 'sv' | 'ell' | 'fruf'
  | 'cls' | 'vls' | 'ollcp' | 'zbll' | '1lll';

/** Catalogue of available sets per puzzle (display name + slug). Drives the index pages. */
export interface AlgdbSetMeta {
  /** URL slug (matches data filename: algdb_<puzzle>_<slug>.json) */
  slug: string;
  /** Speedcubedb subset key (just for reference; not used at runtime) */
  scd: string;
  en: string;
  zh: string;
  /** True for sets that speedcubedb organises under sub-pages (ZBLL → ZBLL U/L/T/...).
   *  UI shows a subgroup-picker landing page first, then cases for the picked subgroup. */
  umbrella?: boolean;
}

export const ALGDB_CATALOG: Record<AlgdbPuzzle, AlgdbSetMeta[]> = {
  '2x2': [
    { slug: 'ortega-oll', scd: 'OrtegaOLL', en: 'Ortega OLL', zh: 'Ortega OLL' },
    { slug: 'ortega-pbl', scd: 'OrtegaPBL', en: 'Ortega PBL', zh: 'Ortega PBL' },
    { slug: 'cll',        scd: 'CLL',       en: 'CLL',        zh: 'CLL' },
    { slug: 'eg1',        scd: 'EG1',       en: 'EG 1',       zh: 'EG 1' },
    { slug: 'eg2',        scd: 'EG2',       en: 'EG 2',       zh: 'EG 2' },
  ],
  '3x3': [
    { slug: 'f2l',       scd: 'F2L',         en: 'F2L',                  zh: 'F2L (基础)' },
    { slug: 'adv-f2l',   scd: 'AdvancedF2L', en: 'Advanced F2L',         zh: 'F2L (进阶)' },
    { slug: 'oll',       scd: 'OLL',         en: 'OLL',                  zh: 'OLL' },
    { slug: 'pll',       scd: 'PLL',         en: 'PLL',                  zh: 'PLL' },
    { slug: 'coll',      scd: 'COLL',        en: 'COLL',                 zh: 'COLL' },
    { slug: 'wv',        scd: 'WV',          en: 'Winter Variation',     zh: 'Winter Variation' },
    { slug: 'cmll',      scd: 'CMLL',        en: 'CMLL',                 zh: 'CMLL' },
    { slug: 'sbls',      scd: 'SBLS',        en: 'Second Block Last Slot', zh: 'Second Block Last Slot' },
    { slug: 'eo4a',      scd: 'EO4A',        en: 'Edge Orientation (4a)', zh: 'Edge Orientation (4a)' },
    { slug: 'anti-pll',  scd: 'AntiPLL',     en: 'Anti PLL',             zh: 'Anti PLL' },
    { slug: 'sv',        scd: 'SV',          en: 'Summer Variation',     zh: 'Summer Variation' },
    { slug: 'ell',       scd: 'ELL',         en: 'Edges of the Last Layer (ELL)', zh: 'Edges of the Last Layer (ELL)' },
    { slug: 'fruf',      scd: 'FRUF',        en: "F <R,U> F'",           zh: "F <R,U> F'" },
    { slug: 'cls',       scd: 'CLS',         en: 'Corners Last Slot',    zh: 'Corners Last Slot' },
    { slug: 'vls',       scd: 'VLS',         en: 'VLS',                  zh: 'VLS',   umbrella: true },
    { slug: 'ollcp',     scd: 'OLLCP',       en: 'OLLCP',                zh: 'OLLCP', umbrella: true },
    { slug: 'zbll',      scd: 'ZBLL',        en: 'ZBLL',                 zh: 'ZBLL',  umbrella: true },
    { slug: '1lll',      scd: '1LLL',        en: '1LLL',                 zh: '1LLL',  umbrella: true },
  ],
  '4x4': [
    { slug: 'oll-parity', scd: 'OLLParity', en: 'OLL Parity', zh: 'OLL Parity' },
    { slug: 'pll-parity', scd: 'PLLParity', en: 'PLL Parity', zh: 'PLL Parity' },
  ],
  '5x5': [
    { slug: 'l2e', scd: 'L2E', en: 'Last Two Edges',   zh: 'Last Two Edges (L2E)' },
    { slug: 'l2c', scd: 'L2C', en: 'Last Two Centers', zh: 'Last Two Centers (L2C)' },
  ],
};

export const ALGDB_PUZZLES: AlgdbPuzzle[] = ['2x2', '3x3', '4x4', '5x5'];

export function getAlgdbSetMeta(puzzle: AlgdbPuzzle, slug: string): AlgdbSetMeta | undefined {
  return ALGDB_CATALOG[puzzle]?.find(s => s.slug === slug);
}

/** Lazy load — Vite code-splits each JSON. Throws on unknown (puzzle, set). */
export async function loadAlgdb(puzzle: AlgdbPuzzle, set: string): Promise<AlgdbFile> {
  const key = `${puzzle}/${set}`;
  switch (key) {
    // 2x2
    case '2x2/ortega-oll': return (await import('../data/algdb_2x2_ortega-oll.json')).default as unknown as AlgdbFile;
    case '2x2/ortega-pbl': return (await import('../data/algdb_2x2_ortega-pbl.json')).default as unknown as AlgdbFile;
    case '2x2/cll':        return (await import('../data/algdb_2x2_cll.json')).default as unknown as AlgdbFile;
    case '2x2/eg1':        return (await import('../data/algdb_2x2_eg1.json')).default as unknown as AlgdbFile;
    case '2x2/eg2':        return (await import('../data/algdb_2x2_eg2.json')).default as unknown as AlgdbFile;
    // 3x3
    case '3x3/f2l':        return (await import('../data/algdb_3x3_f2l.json')).default as unknown as AlgdbFile;
    case '3x3/adv-f2l':    return (await import('../data/algdb_3x3_adv-f2l.json')).default as unknown as AlgdbFile;
    case '3x3/oll':        return (await import('../data/algdb_3x3_oll.json')).default as unknown as AlgdbFile;
    case '3x3/pll':        return (await import('../data/algdb_3x3_pll.json')).default as unknown as AlgdbFile;
    case '3x3/coll':       return (await import('../data/algdb_3x3_coll.json')).default as unknown as AlgdbFile;
    case '3x3/wv':         return (await import('../data/algdb_3x3_wv.json')).default as unknown as AlgdbFile;
    case '3x3/cmll':       return (await import('../data/algdb_3x3_cmll.json')).default as unknown as AlgdbFile;
    case '3x3/sbls':       return (await import('../data/algdb_3x3_sbls.json')).default as unknown as AlgdbFile;
    case '3x3/eo4a':       return (await import('../data/algdb_3x3_eo4a.json')).default as unknown as AlgdbFile;
    case '3x3/anti-pll':   return (await import('../data/algdb_3x3_anti-pll.json')).default as unknown as AlgdbFile;
    case '3x3/sv':         return (await import('../data/algdb_3x3_sv.json')).default as unknown as AlgdbFile;
    case '3x3/ell':        return (await import('../data/algdb_3x3_ell.json')).default as unknown as AlgdbFile;
    case '3x3/fruf':       return (await import('../data/algdb_3x3_fruf.json')).default as unknown as AlgdbFile;
    case '3x3/cls':        return (await import('../data/algdb_3x3_cls.json')).default as unknown as AlgdbFile;
    case '3x3/vls':        return (await import('../data/algdb_3x3_vls.json')).default as unknown as AlgdbFile;
    case '3x3/ollcp':      return (await import('../data/algdb_3x3_ollcp.json')).default as unknown as AlgdbFile;
    case '3x3/zbll':       return (await import('../data/algdb_3x3_zbll.json')).default as unknown as AlgdbFile;
    case '3x3/1lll':       return (await import('../data/algdb_3x3_1lll.json')).default as unknown as AlgdbFile;
    // 4x4
    case '4x4/oll-parity': return (await import('../data/algdb_4x4_oll-parity.json')).default as unknown as AlgdbFile;
    case '4x4/pll-parity': return (await import('../data/algdb_4x4_pll-parity.json')).default as unknown as AlgdbFile;
    // 5x5
    case '5x5/l2e':        return (await import('../data/algdb_5x5_l2e.json')).default as unknown as AlgdbFile;
    case '5x5/l2c':        return (await import('../data/algdb_5x5_l2c.json')).default as unknown as AlgdbFile;
    default:
      throw new Error(`unknown algdb set: ${key}`);
  }
}
