/**
 * Static algorithm database — F2L / AdvancedF2L / OLL / PLL, scraped from
 * speedcubedb.com. Use {@link loadAlgdb} to lazy-import a category.
 *
 * Data is generated by `scramble-stats-build/bin/scrape_speedcubedb.ts`.
 */

export interface AlgdbEntry {
  alg: string;
  altId?: string;
  /** YouTube finger-tricks tutorial id (no full URL — caller composes) */
  ytId?: string;
}

export type AlgdbSticker =
  | { kind: 'f2l'; fl: string }
  | { kind: 'face'; us: string; ub: string; uf: string; ul: string; ur: string };

export interface AlgdbCase {
  name: string;
  subgroup: string;
  setup: string;
  standard?: string;
  sticker: AlgdbSticker;
  /** F2L: 4 entries (FR / FL / BL / BR). OLL/PLL: single entry. */
  algs: AlgdbEntry[][];
  /** F2L only — names of each orientation tab (e.g. "Front Right") */
  oriNames?: string[];
}

export interface AlgdbFile {
  scrapedAt: string;
  source: string;
  category: string;
  cases: AlgdbCase[];
}

export type AlgdbCategory = 'f2l' | 'adv_f2l' | 'oll' | 'pll';

/** Lazy load — keeps each ~200-500KB JSON out of the main bundle. */
export async function loadAlgdb(cat: AlgdbCategory): Promise<AlgdbFile> {
  switch (cat) {
    case 'f2l':     return (await import('../data/algdb_f2l.json')).default as unknown as AlgdbFile;
    case 'adv_f2l': return (await import('../data/algdb_adv_f2l.json')).default as unknown as AlgdbFile;
    case 'oll':     return (await import('../data/algdb_oll.json')).default as unknown as AlgdbFile;
    case 'pll':     return (await import('../data/algdb_pll.json')).default as unknown as AlgdbFile;
  }
}
