'use client';

// /regulation/scrambling — Article 4 (Scrambling).
// Illustrated guide to how official WCA scrambles are made and applied:
// random-state vs random-move generation, the per-event minimum-move table,
// and the scrambling procedure (secrecy, the 2-hour window, verification,
// re-scrambling on error). Shared shell + primitives do the chrome.

import { useTranslation } from 'react-i18next';
import { Dices, Eye, ShieldCheck, Timer, PenLine, ScanLine } from 'lucide-react';
import Link from '@/components/AppLink';
import { useT } from '../../../../hooks/useT';
import { EventIcon } from '@/components/EventIcon';
import CubingPreview from '@/components/CubingPreview';
import RegArticleLayout from '../_components/RegArticleLayout';
import FullClauses from '../_components/FullClauses';
import clauses from '../_data/reg-clauses/4.json';
import { RegSection, Callout, RegQuote, RegList } from '../_components/primitives';
import './scrambling.css';

// A real TNoodle-style 3×3×3 scramble used as the concrete example. Fixed so the
// page stays static (SSG) and the net preview is deterministic.
const SAMPLE_333 = "R2 U2 F2 D' L2 D R2 U2 F2 D2 R' B U' L F2 U2 R' D' F' R2";

// Random-state events: minimum number of moves the scramble must be away from
// solved. Source: WCA Regulations 4b3 / 4b3b / 4b3c / 4b3d / 4b3f.
const STATE_EVENTS: { id: string; zh: string; en: string; min: number }[] = [
  { id: '333',   zh: '三阶',     en: '3×3×3',     min: 2 },
  { id: '222',   zh: '二阶',     en: '2×2×2',     min: 4 },
  { id: 'pyram', zh: '金字塔',   en: 'Pyraminx',  min: 6 },
  { id: 'skewb', zh: '斜转',     en: 'Skewb',     min: 7 },
  { id: 'sq1',   zh: 'Square-1', en: 'Square-1',  min: 11 },
  { id: '444',   zh: '四阶',     en: '4×4×4',     min: 2 },
  { id: 'clock', zh: '魔表',     en: 'Clock',     min: 2 },
];

// Random-move events: state computation is too expensive, so the program applies
// a long random move sequence instead. The move counts are what the official
// program (TNoodle) actually generates; the regulation only requires the result
// be ≥ 2 moves from solved (4b3e).
const MOVE_EVENTS: { id: string; zh: string; en: string; moves: number }[] = [
  { id: '555', zh: '五阶', en: '5×5×5',    moves: 60 },
  { id: '666', zh: '六阶', en: '6×6×6',    moves: 80 },
  { id: '777', zh: '七阶', en: '7×7×7',    moves: 100 },
  { id: 'minx', zh: '五魔', en: 'Megaminx', moves: 77 },
];

export default function ScramblingChapter() {
  useTranslation();
  const t = useT();

  return (
    <RegArticleLayout slug="scrambling">
      {/* ── 1. Random state, not random twiddling ───────────────── */}
      <RegSection
        eyebrow={t('它怎么生成', 'How it is generated', "它怎麼生成")}
        title={t('随机状态,不是随手转', 'A random state, not random twiddling', "隨機狀態,不是隨手轉")}
        lede={t(
          '官方打乱不是裁判随手拧几下。打乱程序先在所有可能的魔方状态里等概率挑一个,再算出一条把已复原魔方变成那个状态的转动序列。',
          'An official scramble is not a judge idly twisting the cube. The scramble program first picks one state, with equal probability, from every possible state of the puzzle — then computes a move sequence that turns a solved cube into exactly that state.', "官方打亂不是裁判隨手擰幾下。打亂程式先在所有可能的魔方狀態裡等機率挑一個,再算出一條把已復原魔方變成那個狀態的轉動序列。"
        )}
      >
        <div className="scr-flow">
          <div className="scr-flow-step">
            <div className="scr-flow-cap">{t('1 · 抽一个随机状态', '1 · Pick a random state', "1 · 抽一個隨機狀態")}</div>
            <p className="scr-flow-text">
              {t(
                '从全部状态中等概率随机选一个目标状态 —— 每个状态被选中的机会完全相同,没有偏向。',
                'One target state is drawn uniformly at random — every state has exactly the same chance, with no bias toward any pattern.', "從全部狀態中等機率隨機選一個目標狀態 —— 每個狀態被選中的機會完全相同,沒有偏向。"
              )}
            </p>
          </div>
          <div className="scr-flow-arrow" aria-hidden>→</div>
          <div className="scr-flow-step">
            <div className="scr-flow-cap">{t('2 · 反算出打乱序列', '2 · Solve back to a sequence', "2 · 反算出打亂序列")}</div>
            <p className="scr-flow-text">
              {t(
                '程序计算一条转动序列,把已复原的魔方变成那个目标状态。这条序列就是发到成绩单上的官方打乱。',
                'The program computes the move sequence that takes a solved cube to that target state. That sequence is the official scramble printed on the scorecard.', "程式計算一條轉動序列,把已復原的魔方變成那個目標狀態。這條序列就是發到成績單上的官方打亂。"
              )}
            </p>
          </div>
        </div>

        <RegQuote num="4b">
          {t(
            '比赛打乱公式必须由当前版本的 WCA 官方打乱程序生成;生成后不得提前查阅,也不得以任何方式筛选或挑选。',
            'Competition scrambles must be generated by a current official version of the WCA scramble program. Once generated they may not be inspected in advance, nor filtered or hand-picked in any way.', "比賽打亂公式必須由當前版本的 WCA 官方打亂程式生成;生成後不得提前查閱,也不得以任何方式篩選或挑選。"
          )}
        </RegQuote>

        <Callout tone="success" label={t('为什么这样做:公平', 'Why it works this way: fairness', "為什麼這樣做:公平")}>
          {t(
            '随机状态保证每次打乱的难度分布一致,谁也拿不到“好签”。配合规则 1h+:同一组选手用同一条打乱,不同组用不同打乱;每个项目的最后一轮(以及三阶最少步)全场只有一组,所有人用完全相同的打乱。',
            'Random states keep every scramble drawn from the same difficulty distribution — nobody gets a lucky one. Together with Regulation 1h+: competitors in the same group share one scramble, different groups get different scrambles, and the final round of every event (plus Fewest Moves) is a single group where everyone solves the exact same scramble.', "隨機狀態保證每次打亂的難度分佈一致,誰也拿不到“好籤”。配合規則 1h+:同一組選手用同一條打亂,不同組用不同打亂;每個項目的最後一輪(以及三階最少步)全場只有一組,所有人用完全相同的打亂。"
          )}
        </Callout>
      </RegSection>

      {/* ── 2. The per-event minimum-move table ─────────────────── */}
      <RegSection
        eyebrow={t('够乱才算数', 'It has to be lost enough', "夠亂才算數")}
        title={t('每个项目要离复原多远', 'How far from solved each event must be', "每個項目要離復原多遠")}
        lede={t(
          '一条几乎复原的“打乱”是无效的。规则给每个随机状态项目定了最少步数下界:抽到的状态至少要离复原这么多步,程序才会采用。',
          'A near-solved “scramble” is no scramble at all. The Regulations set a minimum distance for each random-state event: the drawn state must be at least this many moves from solved before the program will use it.', "一條几乎復原的“打亂”是無效的。規則給每個隨機狀態項目定了最少步數下界:抽到的狀態至少要離復原這麼多步,程式才會採用。"
        )}
      >
        <div className="scr-table-wrap">
          <table className="reg-table">
            <thead>
              <tr>
                <th>{t('项目', 'Event', "項目")}</th>
                <th>{t('最少步数', 'Minimum moves', "最少步數")}</th>
                <th>{t('规则', 'Regulation', "規則")}</th>
              </tr>
            </thead>
            <tbody>
              {STATE_EVENTS.map((e) => (
                <tr key={e.id}>
                  <td>
                    <span className="reg-evt">
                      <EventIcon event={e.id} />
                      {t(e.zh, e.en)}
                    </span>
                  </td>
                  <td>
                    <span className="reg-num">≥ {e.min}</span>
                    <span className="reg-evt-text"> {t('步', 'moves')}</span>
                  </td>
                  <td className="scr-reg-cell">
                    {e.id === '222' ? '4b3b'
                      : e.id === 'skewb' ? '4b3c'
                      : e.id === 'sq1' ? '4b3d'
                      : e.id === 'pyram' ? '4b3f'
                      : '4b3'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="reg-foot-note">
          {t(
            '没有专属下界的随机状态项目(三阶、四阶、魔表等)走默认值:至少 2 步。盲拧项目额外要求随机朝向 —— 整个魔方的指向也等概率随机(规则 4b3a)。',
            'Random-state events without their own minimum (3×3×3, 4×4×4, Clock, …) use the default of at least 2 moves. Blindfolded events add a random orientation requirement — the whole cube’s facing is randomized too, with equal probability (Regulation 4b3a).', "沒有專屬下界的隨機狀態項目(三階、四階、魔錶等)走預設值:至少 2 步。盲擰項目額外要求隨機朝向 —— 整個魔方的指向也等機率隨機(規則 4b3a)。"
          )}
        </p>

        <h3 className="scr-sub">{t('随机转动的大魔方', 'The big puzzles use random moves', "隨機轉動的大魔方")}</h3>
        <p className="scr-sub-lede">
          {t(
            '五阶以上和五魔方,精确计算随机状态在算力上太昂贵。程序改为施加一长串随机转动来代替,只要保证结果至少离复原 2 步(规则 4b3e)。下面是官方程序实际生成的步数:',
            'For 5×5×5 and up, and Megaminx, computing an exact random state is too expensive. The program applies a long run of random moves instead, only requiring the result be at least 2 moves from solved (Regulation 4b3e). These are the move counts the official program actually generates:', "五階以上和五魔方,精確計算隨機狀態在算力上太昂貴。程式改為施加一長串隨機轉動來代替,只要保證結果至少離復原 2 步(規則 4b3e)。下面是官方程式實際生成的步數:"
          )}
        </p>
        <div className="reg-evt-chips">
          {MOVE_EVENTS.map((e) => (
            <span key={e.id} className="reg-evt-chip">
              <EventIcon event={e.id} />
              {t(e.zh, e.en)}
              <span className="reg-num">{e.moves}</span>
              <span className="reg-evt-text">{t('步', 'moves')}</span>
            </span>
          ))}
        </div>
        <p className="reg-foot-note">
          {t(
            '想看每种项目真实打乱的步数分布,可以去',
            'To see the real move-length distribution of scrambles for each event, visit ', "想看每種項目真實打亂的步數分佈,可以去"
          )}
          <Link href="/scramble/stats">{t('打乱难度统计', 'the scramble stats', "打亂難度統計")}</Link>
          {t(';想现场生成一条打乱,去', '; to generate one live, go to ', ";想現場生成一條打亂,去")}
          <Link href="/scramble/gen">{t('打乱生成器', 'the scramble generator', "打亂生成器")}</Link>
          {t('。', '.')}
        </p>
      </RegSection>

      {/* ── 3. A concrete sample scramble ───────────────────────── */}
      <RegSection
        eyebrow={t('长这样', 'What one looks like', "長這樣")}
        title={t('一条真实的三阶打乱', 'A real 3×3×3 scramble', "一條真實的三階打亂")}
        lede={t(
          '把上面那条随机状态序列摊成平面展开图就是这个样子。成绩单上的打乱员会照着同一条序列,把每个人的魔方拧到完全一致的状态。',
          'Unfold one of those random-state sequences into a flat net and this is what you get. Following the very same sequence, the scrambler twists every competitor’s cube into an identical state.', "把上面那條隨機狀態序列攤成平面展開圖就是這個樣子。成績單上的打亂員會照著同一條序列,把每個人的魔方擰到完全一致的狀態。"
        )}
      >
        <figure className="scr-sample">
          <CubingPreview event="333" scramble={SAMPLE_333} height={200} className="scr-sample-img" />
          <figcaption className="scr-sample-cap">
            <code className="scr-sample-alg">{SAMPLE_333}</code>
          </figcaption>
        </figure>
      </RegSection>

      {/* ── 4. The scrambling procedure ─────────────────────────── */}
      <RegSection
        eyebrow={t('上场之前', 'Before it reaches the mat', "上場之前")}
        title={t('打乱的流程与纪律', 'The scrambling procedure', "打亂的流程與紀律")}
        lede={t(
          '从生成到上场,打乱要经过一套保密、核对和时限的规程,确保每个人拿到的是同一个、没被偷看过、且正确的打乱。',
          'From generation to the mat, a scramble passes through rules on secrecy, verification and timing — so that everyone gets the same scramble, unseen in advance, and correctly applied.', "從生成到上場,打亂要經過一套保密、核對和時限的規程,確保每個人拿到的是同一個、沒被偷看過、且正確的打亂。"
        )}
      >
        <RegList
          items={[
            <span key="who">
              <Eye size={16} className="scr-li-icon" />
              <strong>{t('谁能看:严格保密。', 'Who may see it: strictly secret.', "誰能看:嚴格保密。")}</strong>{' '}
              {t(
                '某组比赛开始前,该组打乱只有 WCA 代表可看;开赛后到该组结束前,只有代表和打乱员可看(三阶最少步是例外,选手在轮次中拿到打乱)。',
                'Before a group starts, only the WCA Delegate may see its scrambles; once it begins and until it ends, only the Delegate and scramblers may. Fewest Moves is the exception — competitors receive the scramble during the round.', "某組比賽開始前,該組打亂只有 WCA 代表可看;開賽後到該組結束前,只有代表和打亂員可看(三階最少步是例外,選手在輪次中拿到打亂)。"
              )}{' '}
              <span className="scr-tag">4b2</span>
            </span>,
            <span key="photo">
              <ScanLine size={16} className="scr-li-icon" />
              <strong>{t('禁止记录。', 'No recording.', "禁止記錄。")}</strong>{' '}
              {t(
                '选手、工作人员、观众都不得拍照或以任何方式记录打乱序列,除非 WCA 代表许可;打乱区还应与选手在视觉上隔离。',
                'Competitors, officials and spectators must not photograph or otherwise record a scramble sequence without the Delegate’s permission; the scrambling area should also be visually isolated from competitors.', "選手、工作人員、觀眾都不得拍照或以任何方式記錄打亂序列,除非 WCA 代表許可;打亂區還應與選手在視覺上隔離。"
              )}{' '}
              <span className="scr-tag">4b2b</span>
            </span>,
            <span key="apply">
              <Dices size={16} className="scr-li-icon" />
              <strong>{t('谁来打乱。', 'Who scrambles.', "誰來打亂。")}</strong>{' '}
              {t(
                '由打乱员照打乱公式把已复原的魔方拧乱。每个选手都可能被叫去当打乱员,无正当理由不得推辞。',
                'Scramblers apply the published sequence to a solved puzzle. Every competitor may be called to scramble and can be excused only for a legitimate reason.', "由打亂員照打亂公式把已復原的魔方擰亂。每個選手都可能被叫去當打亂員,無正當理由不得推辭。"
              )}{' '}
              <span className="scr-tag">4a · 1f2</span>
            </span>,
            <span key="verify">
              <ShieldCheck size={16} className="scr-li-icon" />
              <strong>{t('核对与签名。', 'Verify and sign.', "核對與簽名。")}</strong>{' '}
              {t(
                '打乱后打乱员必须核对魔方是否乱对了,错了就改正;可再交给第二名打乱员复核,两人都在成绩单上签名。冠军赛决赛建议一律二次核对。',
                'After scrambling, the scrambler must verify the state is correct and fix it if not. A second scrambler may re-verify, with both signing the scorecard. Championship finals should always be double-checked.', "打亂後打亂員必須核對魔方是否亂對了,錯了就改正;可再交給第二名打亂員複核,兩人都在成績單上簽名。冠軍賽決賽建議一律二次核對。"
              )}{' '}
              <span className="scr-tag">4g · 4g3</span>
            </span>,
          ]}
        />

        <Callout tone="info" label={t('两小时用完', 'A two-hour shelf life', "兩小時用完")} icon={<Timer size={17} />}>
          {t(
            '一条打乱公式自第一次被使用起,应在 2 小时内用完(规则 4b4)。只要在这个窗口内开始的还原,都按正常程序进行 —— 窗口不会打断已经开始的尝试。这样可以减少打乱被记住或泄露后还在用的风险。',
            'A scramble sequence should be used up within 2 hours of its first use (Regulation 4b4). Any attempt started inside that window proceeds normally — the window never interrupts a solve in progress. This limits how long a scramble can stay in play after someone might have memorized or leaked it.', "一條打亂公式自第一次被使用起,應在 2 小時內用完(規則 4b4)。只要在這個視窗內開始的還原,都按正常程式進行 —— 視窗不會打斷已經開始的嘗試。這樣可以減少打亂被記住或洩露後還在用的風險。"
          )}
        </Callout>

        <Callout tone="warn" label={t('打乱出错怎么办', 'When the scramble is wrong', "打亂出錯怎麼辦")} icon={<PenLine size={17} />}>
          {t(
            '若魔方没被正确打乱,一般必须当场改正后再交给选手。大魔方和五魔方可由 WCA 代表酌情豁免改正(五阶盲拧除外,必须改正);三阶多盲还要求打乱员在乱完全部魔方后确认没有重复打乱。若错误在还原之后才发现,是否给额外机会按规则 11 处理。',
            'If a puzzle was not scrambled correctly it must, in general, be corrected before reaching the competitor. For the big cubes and Megaminx the Delegate may waive the correction (except 5×5×5 Blindfolded, which must be corrected); for 3×3×3 Multi-Blind the scrambler must also confirm no two puzzles share a scramble. If the error is found only after a solve, whether an extra attempt is granted is handled under Article 11.', "若魔方沒被正確打亂,一般必須當場改正後再交給選手。大魔方和五魔方可由 WCA 代表酌情豁免改正(五階盲擰除外,必須改正);三階多盲還要求打亂員在亂完全部魔方後確認沒有重複打亂。若錯誤在還原之後才發現,是否給額外機會按規則 11 處理。"
          )}
        </Callout>
      </RegSection>
      <FullClauses data={clauses} />
    </RegArticleLayout>
  );
}
