import { createHash } from 'node:crypto';

export interface Machine {
  owner: string; device: string; os: 'mac' | 'windows'; transport: 'frp' | 'ssh';
  status: 'pending' | 'active' | 'revoked'; localPort: number; remotePort: number;
  certificate: string; aliases: string[];
}
export interface Registry {
  version: number; domain: string; server: string; adminSsh: string;
  reservedPorts: number[]; machines: Machine[];
}
export const slug = (s: string, maxLength = 40) => {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s) || s.length > maxLength) throw Error(`Invalid lowercase name: ${s}`);
  return s;
};
export const idOf = (m: Pick<Machine, 'owner' | 'device'>) => `${slug(m.owner)}-${slug(m.device)}`;
export const hostOf = (r: Registry, m: Machine) => `dev-${idOf(m)}.${r.domain}`;
export const userOf = (m: Machine) => `crdev-${createHash('sha256').update(idOf(m)).digest('hex').slice(0, 12)}`;
export function validate(r: Registry) {
  if (r.version !== 1 || r.domain !== 'cuberoot.me' || r.server !== '47.97.30.181' || r.adminSsh !== 'cuberoot') throw Error('Unexpected registry/server');
  const ports = new Set(r.reservedPorts), names = new Set<string>();
  for (const m of r.machines) {
    if (`dev-${idOf(m)}`.length > 63 || !['mac', 'windows'].includes(m.os)
      || !['frp', 'ssh'].includes(m.transport) || !['pending', 'active', 'revoked'].includes(m.status)) throw Error('Invalid machine');
    if (m.localPort !== 3000 || !Number.isInteger(m.remotePort) || m.remotePort < 7100 || m.remotePort > 7199 || ports.has(m.remotePort)) throw Error(`Port collision/invalid port: ${m.remotePort}`);
    ports.add(m.remotePort); slug(m.certificate, 63);
    for (const host of [hostOf(r, m), ...m.aliases]) {
      if (!/^dev(?:-[a-z0-9]+)*\.cuberoot\.me$/.test(host) || names.has(host)) throw Error(`Duplicate/invalid domain: ${host}`);
      names.add(host);
    }
  }
  return r;
}
export function allocate(r: Registry, live: number[] = []) {
  const used = new Set([...r.reservedPorts, ...r.machines.map(m => m.remotePort), ...live]);
  for (let p = 7105; p < 7199; p++) if (!used.has(p)) return p;
  throw Error('No free development port');
}
export const sh = (s: string) => `'${s.replaceAll("'", "'\\''")}'`;
export function publicKey(s: string) {
  const parts = s.trim().split(/\s+/);
  if (parts[0] !== 'ssh-ed25519' || !/^[A-Za-z0-9+/]+=*$/.test(parts[1] ?? '') || Buffer.from(parts[1], 'base64').length !== 51) throw Error('Expected an Ed25519 public key');
  return `${parts[0]} ${parts[1]}`;
}
export function nginx(r: Registry) {
  const enabled = r.machines.filter(m => m.status !== 'revoked');
  const names = (m: Machine) => [hostOf(r, m), ...m.aliases.filter(h => h !== 'dev.cuberoot.me')];
  return `# Generated by core/scripts/dev-preview/cli.ts from ops/dev-preview/machines.json.\n# dev.cuberoot.me remains in its existing vhost.\n` + (enabled.length ? `server {
    listen 80;
    server_name ${enabled.flatMap(names).join(' ')};
    location ^~ /.well-known/acme-challenge/ {
        root /www/wwwroot/cuberoot-spa;
        default_type "text/plain";
        try_files $uri =404;
    }
    location / { return 301 https://$host$request_uri; }
}
` : '') + enabled.filter(m => m.status === 'active').map(m => `
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${names(m).join(' ')};
    ssl_certificate /etc/letsencrypt/live/${m.certificate}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${m.certificate}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    access_log /www/wwwlogs/${hostOf(r, m)}.log;
    error_log /www/wwwlogs/${hostOf(r, m)}.error.log;
    add_header X-Robots-Tag "noindex, nofollow" always;
    location / {
        proxy_pass http://127.0.0.1:${m.remotePort};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_cache off;
        proxy_buffering off;
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
    }
}
`).join('');
}
export function origins(r: Registry) {
  return '// Generated by core/scripts/dev-preview/cli.ts. Do not edit.\n'
    + `export const DEV_PREVIEW_HOSTS: readonly string[] = ${JSON.stringify(r.machines.filter(m => m.status === 'active').flatMap(m => [hostOf(r, m), ...m.aliases]), null, 2)};\n`;
}
export function sshBlock(m: Machine) {
  return `# BEGIN cuberoot-dev ${idOf(m)}
Match User ${userOf(m)}
    AuthenticationMethods publickey
    PasswordAuthentication no
    PubkeyAuthentication yes
    AuthorizedKeysFile /var/lib/cuberoot-dev/${idOf(m)}/authorized_keys
    AllowTcpForwarding remote
    AllowStreamLocalForwarding no
    PermitListen 127.0.0.1:${m.remotePort}
    PermitOpen none
    GatewayPorts no
    PermitTTY no
    AllowAgentForwarding no
    X11Forwarding no
    PermitTunnel no
    MaxSessions 0
    ForceCommand /bin/false
Match all
# END cuberoot-dev ${idOf(m)}
`;
}
export function authorizeScript(m: Machine, key: string) {
  const id = idOf(m), user = userOf(m), dir = `/var/lib/cuberoot-dev/${id}`;
  const auth = `restrict,port-forwarding,permitlisten="127.0.0.1:${m.remotePort}",command="/bin/false" ${publicKey(key)} cuberoot-dev-${id}\n`;
  const block = Buffer.from(sshBlock(m)).toString('base64');
  return `set -eu
exec 9>/var/lock/cuberoot-dev.lock
flock -x 9
install -d -m 0755 /var/lib/cuberoot-dev
install -d -m 0700 /var/lib/cuberoot-dev/ports
reservation=/var/lib/cuberoot-dev/ports/${m.remotePort}
if [ -f "$reservation" ]; then test "$(cat "$reservation")" = ${sh(id)}; else
  if ss -H -lnt | awk '{print $4}' | grep -Eq ':${m.remotePort}$'; then echo 'Port already occupied' >&2; exit 1; fi
fi
if ! id ${sh(user)} >/dev/null 2>&1; then
  useradd --system --no-create-home --home-dir ${sh(dir)} --shell /bin/false ${sh(user)}
  usermod --password '*' ${sh(user)}
fi
test "$(getent passwd ${sh(user)} | cut -d: -f6)" = ${sh(dir)}
install -d -o root -g root -m 0755 ${sh(dir)}
if [ -s ${sh(dir + '/authorized_keys')} ] && ! cmp -s ${sh(dir + '/authorized_keys')} <(printf %s ${sh(auth)}); then
  echo 'Existing different key; revoke explicitly before replacing it' >&2; exit 1
fi
backup=$(mktemp /etc/ssh/sshd_config.cuberoot-backup.XXXXXXXX)
cp -p /etc/ssh/sshd_config "$backup"
if ! grep -q ${sh('# BEGIN cuberoot-dev ' + id)} /etc/ssh/sshd_config; then
  printf '\\nMatch all\\n' >> /etc/ssh/sshd_config
  printf %s ${sh(block)} | base64 -d >> /etc/ssh/sshd_config
fi
if ! /usr/sbin/sshd -t; then cp -p "$backup" /etc/ssh/sshd_config; exit 1; fi
effective=$(/usr/sbin/sshd -T -C user=${user},host=localhost,addr=127.0.0.1)
for expected in 'allowtcpforwarding remote' 'allowstreamlocalforwarding no' 'gatewayports no' 'maxsessions 0' 'passwordauthentication no' 'permitlisten 127.0.0.1:${m.remotePort}'; do
  if ! printf '%s\\n' "$effective" | grep -Fxq "$expected"; then cp -p "$backup" /etc/ssh/sshd_config; echo "Unexpected SSH policy: $expected" >&2; exit 1; fi
done
printf %s ${sh(auth)} > ${sh(dir + '/authorized_keys')}
chmod 0644 ${sh(dir + '/authorized_keys')}
printf %s ${sh(id)} > "$reservation"
if ! systemctl reload sshd; then cp -p "$backup" /etc/ssh/sshd_config; : > ${sh(dir + '/authorized_keys')}; exit 1; fi
echo 'Authorized ${id}: remote forwarding only on 127.0.0.1:${m.remotePort}'
`;
}
