import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, s, n, f, p, c } from '../_lib/stack_tool_types';

// ─── Capacitor 8 ─────────────────────────────────────────────────────────────

export const CAPACITOR: StackTool = {
  slug: 'capacitor',
  name: 'Capacitor',
  version: '8.3.4',
  since: '2019-05',
  group: 'frontend',
  accent: '#119EFF',
  bright: '#5BBAFF',
  glyph: '‖',
  floats: ['WebView', 'bridge', 'native plugin', 'WKWebView', 'live reload', 'server.url', 'Cordova compat', 'ios/', 'android/', 'capacitor.config', 'WebViewAssetLoader', 'PWA'],
  zh: {
    tagline: '把 Web 应用套成 iOS / Android 原生壳',
    role: '本站移动端就是它 —— 同一份 Next.js 站点塞进系统 WebView, 双 runner CI 出 APK + IPA。',
    heroSub: <>Ionic 团队做的<strong>原生运行时</strong>, 定位是 Cordova 的现代继任者。它给你一个轻薄的原生壳 (真正的 Xcode / Android Studio 项目, <code>ios/</code> 与 <code>android/</code> 目录直接进 git), 壳里嵌一个系统 WebView (iOS <code>WKWebView</code> / Android System WebView), 你的 Web 代码就在里面跑; 需要相机、文件、推送这类原生能力时, 通过一座 JS↔原生的 bridge 调插件。一句话: <strong>你的网页, 装进了 App Store 能上架的盒子</strong>。</>,
    whatDesc: <>Capacitor 让你<strong>把已经在浏览器里跑得好好的 Web 应用直接打包成原生 App</strong>。它不重写 UI —— 渲染的就是你那份 HTML/CSS/JS, 跑在系统 WebView 里。原生侧只做两件事: 提供壳 (生命周期、启动屏、状态栏) 与一座 bridge, 让 JS 调用相机 / 文件系统 / 推送 / 蓝牙等原生 API。它最大的设计取舍是<strong>把原生项目当源代码而非构建产物</strong> —— <code>ios/</code> <code>android/</code> 进版本库, 你可以手改原生工程、加任意第三方 SDK, 而不被框架锁死。</>,
    historyDesc: <>从 2019 年 5 月 1.0 发布、喊出 "Cordova 的现代继任者", 到 2025 年 12 月 8.0 GA、2026 年的 8.3.4 当前线, 七年。中间几乎每年一个大版本, 节奏稳: 2.0 (2020) 跟进新 WebView, 3.0 (2021) 插件 API 重做, 4.0~6.0 持续抬 iOS/Android 最低版本与 Swift/Kotlin 现代化, 7.0 (2025) 锁定新一代原生工具链, 8.0 (2025-12) 是当前主线起点。</>,
    conceptsTitle: '壳 + WebView + bridge',
    conceptsDesc: <>Capacitor 的核心只有三块: 一个原生壳 (可手改的 Xcode/AS 项目)、一个系统 WebView (装你的 Web 代码)、一座 bridge (JS 调原生)。围绕它的是插件体系、<code>server.url</code> 远程加载模式、live reload 开发流, 以及对 Cordova 插件的兼容。</>,
    whyDesc: <>当你已经有一个跑得很好的 Web 应用, 又想上 App Store / Google Play, Capacitor 是成本最低的那条路 —— 不重写 UI、不学第二套技术栈、原生项目还能手改逃生。代价是: 性能与手感天花板是 WebView 的天花板, 极度吃原生能力 / 启动时间 / 内存的场景, 它给不了 React Native 那种真原生控件。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>Ionic 自家整个生态、BurgerKing / Southwest Airlines 一类品牌 App、Sworkit / SiriusXM 等都用 Capacitor 把 Web 套成原生。它继承了 Cordova 庞大的插件存量, 又给现代 Web 框架 (React / Vue / Angular / Next) 提供干净的上手路径。</>,
    cuberootDesc: <>本站的 iOS / Android App 就是 Capacitor 套壳 —— 同一份 Next.js 站点, 壳用 <code>server.url</code> 指向线上, 改前端不必重 build 壳。下面讲这套构建管线 (双 runner CI)、为什么这么选, 以及它跟 React Native / macOS 端的关系。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>8.x 是当前主线 (8.3.4 / 2026-05), 9.0 在 alpha。趋势是更现代的原生最低版本、WebView 能力随系统演进而水涨船高、以及 PWA / 原生壳 / live reload 三态打通的开发体验。对一个 web-first 工具站, "WebView 即天花板" 同时是它的优势与边界。</>,
  },
  en: {
    tagline: 'Wrap a web app into an iOS / Android native shell',
    role: "The site's mobile build is this — the same Next.js site dropped into a system WebView, dual-runner CI producing APK + IPA.",
    heroSub: <>A <strong>native runtime</strong> from the Ionic team, positioned as the modern successor to Cordova. It hands you a thin native shell (real Xcode / Android Studio projects, with <code>ios/</code> and <code>android/</code> committed straight to git) that embeds a system WebView (iOS <code>WKWebView</code> / Android System WebView) where your web code runs; when you need native capability like camera, files, or push, you reach it through a JS↔native bridge to a plugin. In one line: <strong>your webpage, in a box you can ship to the App Store</strong>.</>,
    whatDesc: <>Capacitor lets you <strong>package a web app that already runs well in the browser straight into a native app</strong>. It doesn't rewrite the UI — what renders is your same HTML/CSS/JS, running inside the system WebView. The native side does two things only: provide the shell (lifecycle, splash screen, status bar) and a bridge so JS can call camera / filesystem / push / Bluetooth native APIs. Its biggest design choice is <strong>treating native projects as source, not build artifacts</strong> — <code>ios/</code> and <code>android/</code> live in version control, so you can hand-edit the native project and add any third-party SDK without being boxed in by the framework.</>,
    historyDesc: <>From the 1.0 release in May 2019 — billed as "the modern successor to Cordova" — to 8.0 GA in December 2025 and the 8.3.4 current line in 2026, seven years. A major version almost every year, on a steady cadence: 2.0 (2020) tracked newer WebViews, 3.0 (2021) reworked the plugin API, 4.0–6.0 kept raising minimum iOS/Android versions and modernizing Swift/Kotlin, 7.0 (2025) locked onto the latest native toolchain, and 8.0 (2025-12) is the current mainline's starting point.</>,
    conceptsTitle: 'Shell + WebView + bridge',
    conceptsDesc: <>Capacitor's core is just three pieces: a native shell (a hand-editable Xcode/AS project), a system WebView (holding your web code), and a bridge (JS calling native). Around them: the plugin system, the <code>server.url</code> remote-load mode, the live-reload dev flow, and compatibility with Cordova plugins.</>,
    whyDesc: <>When you already have a web app that runs well and want it on the App Store / Google Play, Capacitor is the cheapest path — no UI rewrite, no second tech stack to learn, and the native project stays hand-editable as an escape hatch. The cost: your performance and feel ceiling is the WebView's ceiling; for things that lean hard on native capability / startup time / memory, it can't give you React Native's real native widgets.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Ionic's entire ecosystem, brand apps like Burger King and Southwest Airlines, and apps such as Sworkit and SiriusXM all use Capacitor to wrap web into native. It inherits Cordova's huge plugin back-catalog while giving modern web frameworks (React / Vue / Angular / Next) a clean on-ramp.</>,
    cuberootDesc: <>The site's iOS / Android app is a Capacitor shell — the same Next.js site, with the shell pointing <code>server.url</code> at production, so front-end changes don't require rebuilding the shell. Below: the build pipeline (dual-runner CI), why it was chosen, and how it relates to React Native and the macOS endpoint.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>8.x is the current mainline (8.3.4 / 2026-05), with 9.0 in alpha. The trend is more modern native minimums, WebView capabilities rising as the OS evolves, and a smoother dev experience spanning PWA / native shell / live reload. For a web-first toolkit, "the WebView is the ceiling" is both its advantage and its boundary.</>,
  },
  heroStats: [
    { num: '8', unit: '.3.4', zh: <>当前稳定版 <em>2026-05</em></>, en: <>current stable <em>2026-05</em></>
    },
    { num: '2', unit: '端', zh: <>一套 Web 代码出 iOS + Android <em>外加 PWA</em></>, en: <>platforms from one web codebase <em>plus PWA</em></>
    },
    { num: '7', unit: 'y', zh: <>从 2019 至今 <em>Cordova 的现代继任者</em></>, en: <>since 2019 <em>Cordova's modern successor</em></>
    },
    { num: '0', unit: 'rewrite', zh: <>UI 重写量 <em>跑你那份 Web 代码</em></>, en: <>UI rewrite required <em>runs your web code as-is</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>Capacitor 是 Ionic 团队 2019 年 5 月发布的原生运行时。它要解决的问题很具体: Ionic 多年依赖 Cordova 把 Web 应用套成 App, 但 Cordova 那套 (插件机制、原生工程被当成一次性构建产物、对现代工具链支持差) 越来越拖后腿。Capacitor 是从零重做的继任者 —— 保留 "Web 代码跑在 WebView 里" 的核心思路, 同时<strong>把原生工程提升成可长期维护的源代码</strong>。</p>
        <p>它的架构一句话能说完: 一个原生壳 + 一个系统 WebView + 一座 bridge。壳是真正的 Xcode / Android Studio 项目, <code>ios/</code> 与 <code>android/</code> 直接进版本库, 你可以像对待任何原生工程那样手改它、加 SDK、改权限。WebView 用平台自带的 (iOS <code>WKWebView</code> / Android System WebView), 你的 HTML/CSS/JS 在里面渲染, 跟它在浏览器里完全一样。需要原生能力时, JS 通过 bridge 调一个插件, 插件用 Swift / Kotlin 实现, 把结果回传给 JS。相机、文件、推送、蓝牙、地理位置都是这么接的。</p>
        <p>跟 React Native 的根本区别在这: <strong>Capacitor 跑的是真实的 Web 代码 (DOM + CSS), RN 跑的是 JS 驱动的真原生控件</strong>。前者意味着零 UI 重写、Web 生态全可用、但天花板是 WebView; 后者意味着真原生手感、但要把 UI 重写成原生组件。Capacitor 还有个独特玩法 —— <code>server.url</code>: 壳可以不打包本地资源, 而是直接加载一个远程站点, 这让 "前端独立部署、壳只当加载器" 成为可能。七年下来它几乎每年一个大版本, 2025 年 12 月的 8.0 是当前主线起点, 2026 年 5 月的 8.3.4 是当前线, 9.0 已在 alpha。</p>
      </>
    ),
    en: (
      <>
        <p>Capacitor is a native runtime the Ionic team released in May 2019. The problem it solved was concrete: for years Ionic relied on Cordova to wrap web apps into native ones, but Cordova's approach (its plugin mechanism, treating the native project as a throwaway build artifact, weak modern-toolchain support) increasingly held things back. Capacitor is a from-scratch successor — it keeps the core idea of "web code running in a WebView" while <strong>promoting the native project into long-lived source code</strong>.</p>
        <p>Its architecture fits in one sentence: a native shell + a system WebView + a bridge. The shell is a real Xcode / Android Studio project; <code>ios/</code> and <code>android/</code> go straight into version control, and you can hand-edit it, add SDKs, change permissions, just like any native project. The WebView is the platform's own (iOS <code>WKWebView</code> / Android System WebView), where your HTML/CSS/JS renders exactly as it does in a browser. When you need native capability, JS calls a plugin through the bridge; the plugin is implemented in Swift / Kotlin and hands the result back to JS. Camera, files, push, Bluetooth, geolocation all wire up this way.</p>
        <p>The fundamental difference from React Native: <strong>Capacitor runs real web code (DOM + CSS), while RN runs JS-driven real native widgets</strong>. The former means zero UI rewrite and the full web ecosystem available, but the ceiling is the WebView; the latter means genuine native feel but requires rewriting the UI into native components. Capacitor also has a distinctive trick — <code>server.url</code>: the shell can skip bundling local assets and load a remote site directly, making "the front-end deploys independently, the shell is just a loader" possible. Over seven years it has shipped a major version almost yearly; December 2025's 8.0 is the current mainline's start, May 2026's 8.3.4 is the current line, and 9.0 is already in alpha.</p>
      </>
    ),
  },
  history: [
    { year: '2019·05', zh: { title: <>1.0 发布</>, desc: <>Ionic 团队推出 Capacitor 1.0, 喊出 "Cordova 的现代继任者"。核心定位: 原生工程当源代码、系统 WebView + bridge、兼容大量 Cordova 插件。</> }, en: { title: <>1.0 released</>, desc: <>The Ionic team ships Capacitor 1.0, billed as "the modern successor to Cordova." Core positioning: native projects as source, system WebView + bridge, compatibility with a large body of Cordova plugins.</> } },
    { year: '2020·04', zh: { title: <>2.0 — 跟进新 WebView</>, desc: <>2.0 抬高最低平台版本, 用上更新的 iOS/Android WebView 能力, 插件体系趋于稳定。框架成熟度第一次让团队敢在生产 App 上押它。</> }, en: { title: <>2.0 — newer WebViews</>, desc: <>2.0 raises minimum platform versions and adopts newer iOS/Android WebView capabilities; the plugin system stabilizes. The first maturity step that let teams bet production apps on it.</> } },
    { year: '2021·05', zh: { title: <>3.0 — 插件 API 重做</>, desc: <>3.0 重做插件 API, 引入更清晰的官方插件包拆分 (Camera / Filesystem / Push 各自独立)。"按需装插件" 取代早期的全家桶。</> }, en: { title: <>3.0 — plugin API rework</>, desc: <>3.0 reworks the plugin API and splits official plugins into separate packages (Camera / Filesystem / Push each standalone). "Install plugins as needed" replaces the early all-in-one bundle.</> } },
    { year: '2022·07', zh: { title: <>4.0 — 工具链现代化</>, desc: <>4.0 继续抬高 iOS/Android 最低版本, 全面 Swift / Kotlin 化原生侧, 改善 Apple Silicon 与新版 Gradle 的构建体验。</> }, en: { title: <>4.0 — toolchain modernization</>, desc: <>4.0 keeps raising minimum iOS/Android versions, moves the native side fully to Swift / Kotlin, and improves builds on Apple Silicon and newer Gradle.</> } },
    { year: '2023·05', zh: { title: <>5.0 — 持续抬底线</>, desc: <>5.0 跟进当年的平台 SDK 要求, 收紧最低系统版本, 让插件作者集中维护现代目标。生态进一步收敛到 "现代 Web 框架 + Capacitor"。</> }, en: { title: <>5.0 — raising the floor</>, desc: <>5.0 tracks that year's platform SDK requirements and tightens minimum OS versions so plugin authors can focus on modern targets. The ecosystem converges further on "modern web frameworks + Capacitor."</> } },
    { year: '2024·04', zh: { title: <>6.0 — 框架无关上手</>, desc: <>6.0 强化与 React / Vue / Angular / 各 web 框架的干净集成路径, "把任意 Web 应用套成原生" 的体验更顺。</> }, en: { title: <>6.0 — framework-agnostic on-ramp</>, desc: <>6.0 strengthens clean integration paths with React / Vue / Angular and other web frameworks, smoothing the "wrap any web app into native" experience.</> } },
    { year: '2025·01', zh: { title: <>7.0 — 新一代原生工具链</>, desc: <>7.0 锁定新一代 iOS/Android 工具链与构建系统, 进一步现代化原生壳。为后续主线打底。</> }, en: { title: <>7.0 — next-gen native toolchain</>, desc: <>7.0 locks onto a next-gen iOS/Android toolchain and build system, further modernizing the native shell and laying groundwork for the upcoming mainline.</> } },
    { year: '2025·12', zh: { title: <>8.0 GA</>, desc: <>2025-12-08 8.0 正式发布, 成为当前主线起点。延续 "Web 代码 + 系统 WebView + 可手改原生工程" 的核心, 平台最低版本与依赖再上一档。</> }, en: { title: <>8.0 GA</>, desc: <>8.0 ships on 2025-12-08 as the current mainline's start. It continues the core of "web code + system WebView + hand-editable native project," with platform minimums and dependencies stepped up.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>8.3.4 / 当前稳定</>, desc: <>2026-05-12 当前线 8.3.4。8.x 全面铺开, 9.0 进入 alpha。本站移动壳就跑在 8.x 上, 用 <code>server.url</code> 指向线上 Next 站点。</> }, en: { title: <>8.3.4 / current stable</>, desc: <>The current line is 8.3.4 (2026-05-12). 8.x is fully rolled out and 9.0 is in alpha. The site's mobile shell runs on 8.x, with <code>server.url</code> pointed at the live Next site.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>WebView 容器</>, desc: <>App 内容跑在系统自带 WebView 里 —— iOS <code>WKWebView</code>, Android System WebView。你的 HTML/CSS/JS 原样渲染, 跟浏览器里一致, 不重写 UI。</> }, en: { title: <>The WebView container</>, desc: <>App content runs in the OS's built-in WebView — <code>WKWebView</code> on iOS, System WebView on Android. Your HTML/CSS/JS renders as-is, identical to the browser, no UI rewrite.</> }, code: <code>{c('// 原生壳启动 -> 载入 WebView -> 你的 web app')}{'\n'}{c('// iOS: WKWebView   Android: System WebView')}</code> },
    { tag: 'B', zh: { title: <>JS ↔ 原生 bridge</>, desc: <>WebView 里的 JS 通过 bridge 调原生方法, 原生用 Swift / Kotlin 实现, 异步把结果回传。所有原生能力 (相机 / 推送 / 文件) 都走这条通道。</> }, en: { title: <>The JS ↔ native bridge</>, desc: <>JS in the WebView calls native methods over the bridge; native is implemented in Swift / Kotlin and returns results asynchronously. Every native capability (camera / push / files) goes through this channel.</> }, code: <code>{k('const')} photo = {k('await')} {v('Camera')}.{f('getPhoto')}({'{ '}{p('quality')}: {n('90')} {'}'});{'\n'}{c('// JS -> bridge -> Swift/Kotlin -> JS')}</code> },
    { tag: 'C', zh: { title: <>原生插件</>, desc: <>每个原生能力封装成一个插件: 一份 TS 接口 + iOS/Android 原生实现。官方包 (Camera / Geolocation / Push…) 按需装, 也能自己写。</> }, en: { title: <>Native plugins</>, desc: <>Each native capability is wrapped as a plugin: one TS interface plus iOS/Android native implementations. Official packages (Camera / Geolocation / Push…) install on demand, and you can write your own.</> }, code: <code>{k('import')} {'{ '}{v('Geolocation')} {'}'} {k('from')} {s("'@capacitor/geolocation'")};{'\n'}{k('const')} pos = {k('await')} {v('Geolocation')}.{f('getCurrentPosition')}();</code> },
    { tag: 'D', zh: { title: <>原生项目即源代码</>, desc: <>Capacitor 把 <code>ios/</code> <code>android/</code> 当源代码而非构建产物, 直接进 git。你可手改 Xcode/Gradle 工程、加任意 SDK, 不被框架锁死 —— 这是它跟 Cordova 最大的分野。</> }, en: { title: <>Native project as source</>, desc: <>Capacitor treats <code>ios/</code> and <code>android/</code> as source, not build artifacts, committed straight to git. You can hand-edit the Xcode/Gradle project and add any SDK, never boxed in — the biggest break from Cordova.</> }, code: <code>{p('$')} {f('npx')} cap add ios{'\n'}{p('$')} {f('npx')} cap add android{'\n'}{c('# ios/ 与 android/ 进版本库, 可手改')}</code> },
    { tag: 'E', zh: { title: <>server.url 远程加载</>, desc: <>config 里设 <code>server.url</code>, 壳就不打包本地资源, 直接加载一个远程站点。前端独立部署、壳只当加载器 —— 改前端不必重 build App。</> }, en: { title: <>server.url remote load</>, desc: <>Set <code>server.url</code> in config and the shell skips bundled assets, loading a remote site directly. The front-end deploys independently and the shell is just a loader — front-end changes need no app rebuild.</> }, code: <code>{c('// capacitor.config')}{'\n'}{p('server')}: {'{ '}{p('url')}: {s("'https://...'")} {'}'}{'\n'}{c('// 壳加载线上站点, 不打包本地 dist')}</code> },
    { tag: 'F', zh: { title: <>live reload 开发流</>, desc: <>开发时把 <code>server.url</code> 指向本机 dev server, 改 Web 代码即在真机 / 模拟器里热刷新。反馈环跟纯 Web 开发一样快, 不必每次重装 App。</> }, en: { title: <>Live reload dev flow</>, desc: <>In development, point <code>server.url</code> at your local dev server; edit web code and it hot-reloads on device / simulator. A web-fast feedback loop, no reinstalling the app each time.</> }, code: <code>{p('$')} {f('npx')} cap run ios {p('-l')} {p('--external')}{'\n'}{c('# WebView -> 本机 dev server, 改代码即刷')}</code> },
    { tag: 'G', zh: { title: <>Cordova 插件兼容</>, desc: <>Capacitor 能直接吃大量现成 Cordova 插件, 让从 Cordova/Ionic 迁移的项目不必把原生集成全部重写。庞大的历史插件存量直接可用。</> }, en: { title: <>Cordova plugin compatibility</>, desc: <>Capacitor can consume many existing Cordova plugins directly, so projects migrating from Cordova/Ionic don't have to rewrite every native integration. The large legacy plugin back-catalog stays usable.</> }, code: <code>{p('$')} {f('npm')} install cordova-plugin-x{'\n'}{p('$')} {f('npx')} cap sync{'\n'}{c('# 多数 Cordova 插件被直接识别')}</code> },
    { tag: 'H', zh: { title: <>PWA / 原生 三态同源</>, desc: <>同一份 Web 代码可出 PWA、iOS App、Android App 三种形态。插件在原生壳里调真原生, 在 PWA 里降级走 Web API, 一套代码三处跑。</> }, en: { title: <>PWA / native, one source</>, desc: <>The same web code ships as a PWA, an iOS app, and an Android app. Plugins call true native inside the shell and fall back to Web APIs in the PWA — one codebase, three targets.</> }, code: <code>{c('// 壳内: 真原生插件实现')}{'\n'}{c('// 浏览器/PWA: 降级到 Web API')}</code> },
  ],
  whyCards: [
    { icon: '‖', zh: { title: <>零 UI 重写</>, desc: <>你已有的 HTML/CSS/JS 原样跑在 WebView 里, 不必把每个页面用原生组件重做。对一个已经在 Web 上跑得好好的工具站, 这是最省的上架路径。</> }, en: { title: <>Zero UI rewrite</>, desc: <>Your existing HTML/CSS/JS runs in the WebView as-is — no redoing every page in native components. For a toolkit already running well on the web, it's the cheapest path to the stores.</> }, code: <>{c('// 同一份 Next.js 站点 = iOS + Android')}</> },
    { icon: '◧', zh: { title: <>原生工程可手改</>, desc: <><code>ios/</code> <code>android/</code> 是真 Xcode/Gradle 工程, 进 git。要加个偏门 SDK、改权限、塞原生代码, 直接改 —— 不被框架锁死, 这是 Cordova 当年给不了的。</> }, en: { title: <>Hand-editable native project</>, desc: <><code>ios/</code> and <code>android/</code> are real Xcode/Gradle projects in git. Need an obscure SDK, a permission change, or some native code — just edit it. Not boxed in, something Cordova couldn't offer.</> }, code: <>{c('// 直接打开 ios/App.xcworkspace 改')}</> },
    { icon: '⇄', zh: { title: <>server.url 解耦壳与前端</>, desc: <>壳用 <code>server.url</code> 指向线上, 它就只是个加载器。前端改了照常 deploy, 壳不必重 build / 重新过商店审核。Web 的发布节奏带进原生壳。</> }, en: { title: <>server.url decouples shell from front-end</>, desc: <>Point the shell's <code>server.url</code> at production and it's just a loader. Front-end changes deploy as usual; the shell needs no rebuild or fresh store review. Web's release cadence, inside a native shell.</> }, code: <>{p('server')}.{p('url')} = {s("'https://...'")}</> },
    { icon: '⟳', zh: { title: <>live reload 快反馈</>, desc: <>开发时 WebView 直连本机 dev server, 改代码即在真机刷新。调试体验跟纯 Web 一样, 不必每改一行就重装 App。</> }, en: { title: <>Fast live-reload feedback</>, desc: <>In dev the WebView connects straight to your local dev server; edit code and it refreshes on a real device. The debug loop feels like pure web, no reinstalling per change.</> }, code: <>{f('npx')} cap run android {p('-l')} {p('--external')}</> },
    { icon: '⊞', zh: { title: <>插件生态 + Cordova 存量</>, desc: <>官方插件覆盖相机 / 文件 / 推送 / 蓝牙 / 地理位置等高频需求, 还能直接复用海量 Cordova 历史插件。原生能力不必从零接。</> }, en: { title: <>Plugin ecosystem + Cordova back-catalog</>, desc: <>Official plugins cover camera / files / push / Bluetooth / geolocation and more; you can also reuse the vast Cordova plugin back-catalog. Native capability isn't wired from scratch.</> }, code: <>{f('npm')} i @capacitor/camera @capacitor/push-notifications</> },
    { icon: '◑', zh: { title: <>一套代码三处跑</>, desc: <>同一份 Web 代码出 PWA + iOS + Android。插件在壳里走真原生、在浏览器里降级走 Web API, 不必为每个目标维护独立代码。</> }, en: { title: <>One codebase, three targets</>, desc: <>The same web code yields PWA + iOS + Android. Plugins use true native in the shell and fall back to Web APIs in the browser — no separate codebase per target.</> }, code: <>{c('// PWA / iOS / Android 同源')}</> },
    { icon: '◇', zh: { title: <>边界: WebView 即天花板</>, desc: <>性能与手感的上限是系统 WebView 的上限。极度吃原生控件 / 启动时间 / 内存的场景 (如后台常驻蓝牙), 它给不了 RN 那种真原生。务实的取舍, 不是万能。</> }, en: { title: <>Boundary: the WebView is the ceiling</>, desc: <>Performance and feel cap out at the system WebView's ceiling. For things leaning hard on native widgets / startup / memory (e.g. background-resident Bluetooth), it can't give RN's true native. A pragmatic trade-off, not a silver bullet.</> }, code: <>{c('// WebView 跑不动 -> 才考虑下沉原生 / RN')}</> },
  ],
  adopters: [
    { name: 'Ionic', href: 'https://ionicframework.com', highlight: true, zhNote: 'Capacitor 的出品方, 整个 Ionic 生态默认用它套壳', enNote: "Capacitor's maker — the whole Ionic ecosystem wraps with it by default" },
    { name: 'Cordova (legacy)', href: 'https://cordova.apache.org', zhNote: 'Capacitor 的前身与兼容对象, 大量插件被直接复用', enNote: "Capacitor's predecessor and compat target — many plugins reused directly" },
    { name: 'Burger King', href: 'https://www.bk.com', zhNote: '品牌 App 用 Capacitor 套 Web', enNote: 'Brand app wraps web with Capacitor' },
    { name: 'Southwest Airlines', href: 'https://www.southwest.com', zhNote: '航司 App 用 Capacitor 上架双端', enNote: 'Airline app ships both platforms via Capacitor' },
    { name: 'Sworkit', href: 'https://sworkit.com', zhNote: '健身 App, Ionic + Capacitor 案例', enNote: 'Fitness app, an Ionic + Capacitor case' },
    { name: 'SiriusXM', href: 'https://www.siriusxm.com', zhNote: '音频流媒体, Web 技术栈套原生', enNote: 'Audio streaming, web stack wrapped native' },
    { name: 'Vue / Angular / React', zhNote: '主流 Web 框架都有 Capacitor 干净集成路径', enNote: 'All major web frameworks have clean Capacitor integration' },
    { name: 'Next.js', href: 'https://nextjs.org', zhNote: '可直接套壳 (本站即此路线)', enNote: 'Wraps directly into a shell (this site takes this route)' },
    { name: 'Ionic Appflow', href: 'https://ionic.io/appflow', zhNote: '官方 CI/CD + 实时更新, 跟 Capacitor 配套', enNote: 'Official CI/CD + live updates paired with Capacitor' },
    { name: 'Capgo', href: 'https://capgo.app', zhNote: '社区 OTA 热更新方案, 服务 Capacitor 应用', enNote: 'Community OTA live-update solution for Capacitor apps' },
    { name: 'PWA Elements', href: 'https://github.com/ionic-team/pwa-elements', zhNote: '官方 web 组件, 让插件在浏览器里也有 UI', enNote: 'Official web components giving plugins UI in the browser' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站移动端 — Capacitor 套 Next.js, server.url 指向线上, 见 §06', enNote: "This site's mobile build — Capacitor wrapping Next.js, server.url to production, see §06" },
  ],
  outlook: [
    { tag: <>HOT · 2025-12</>, hot: true, big: true, zh: { title: <>8.x 当前主线</>, body: <><p>8.0 在 2025-12-08 GA, 8.3.4 (2026-05) 是当前线。8.x 继续抬高 iOS/Android 最低平台版本与依赖, 让插件作者集中维护现代目标, 也让原生壳享受新版工具链的构建与签名改进。</p><p>对一个 web-first 工具站, 这意味着: 壳越来越薄、越来越稳, 真正的迭代仍发生在 Web 侧。9.0 已进 alpha, 主线会继续 "跟系统能力水涨船高" 的节奏。</p></> }, en: { title: <>8.x is the current mainline</>, body: <><p>8.0 went GA on 2025-12-08, and 8.3.4 (2026-05) is the current line. 8.x keeps raising minimum iOS/Android platform versions and dependencies, letting plugin authors focus on modern targets and the native shell benefit from newer toolchain build and signing improvements.</p><p>For a web-first toolkit this means the shell gets thinner and steadier while real iteration stays on the web side. 9.0 is already in alpha; the mainline will keep its "rise with OS capability" cadence.</p></> } },
    { tag: 'WEBVIEW', big: true, zh: { title: <>WebView 随系统进化</>, body: <><p>Capacitor 不自带渲染引擎, 用的是系统 WebView, 所以它的能力天花板随 iOS / Android 自身演进而抬高 —— 新的 CSS、新的 Web API、更好的 WebGL/WebGPU 自动可用, 不需要 Capacitor 自己升引擎。</p><p>这是 webview 方案的结构性优势: 你押注的是平台 WebView 的长期投入。本站的 WebCodecs 解码、cubing.js 3D、WASM solver 都靠这条线吃到现代 Web 能力。</p></> }, en: { title: <>The WebView evolves with the OS</>, body: <><p>Capacitor ships no rendering engine of its own — it uses the system WebView, so its capability ceiling rises as iOS / Android themselves evolve. New CSS, new Web APIs, better WebGL/WebGPU become available automatically, with no engine upgrade on Capacitor's part.</p><p>That's a structural advantage of the webview approach: you're betting on the platform WebView's long-term investment. The site's WebCodecs decode, cubing.js 3D, and WASM solver all ride this line into modern web capability.</p></> } },
    { tag: 'OTA', zh: { title: <>实时更新与 server.url</>, body: <><p>结合 <code>server.url</code> 远程加载或 Appflow / Capgo 这类 OTA 方案, Web 资源可绕过应用商店审核直接更新。"壳一次审, 内容随便改" 让原生壳拿到接近 Web 的发布速度。</p></> }, en: { title: <>Live updates and server.url</>, body: <><p>Combined with <code>server.url</code> remote loading or OTA solutions like Appflow / Capgo, web assets can update without an app-store review. "Review the shell once, change content freely" gives the native shell near-web release speed.</p></> } },
    { tag: 'VS-RN', zh: { title: <>跟 React Native 的分工</>, body: <><p>两条路根本不同: Capacitor 跑真实 Web 代码 (DOM + CSS) 在 WebView 里, RN 用 JS 驱动真原生控件。内容 / 工具类 App 选 Capacitor 省下整套 UI 重写; 吃真原生手感、深度系统集成的选 RN。本站属于前者。</p></> }, en: { title: <>Division of labor with React Native</>, body: <><p>The two roads differ fundamentally: Capacitor runs real web code (DOM + CSS) in a WebView, while RN drives true native widgets from JS. Content / tool apps pick Capacitor to save the entire UI rewrite; apps needing real native feel or deep system integration pick RN. This site is the former.</p></> } },
    { tag: 'BOUNDARY', zh: { title: <>边界: 何时翻盘</>, body: <><p>如果哪天要做一个真正吃原生能力的功能 —— 后台常驻蓝牙智能魔方计时、原生级触觉反馈、对启动时间 / 内存极度敏感的场景 —— WebView 的天花板就压不住了, 那时才该考虑下沉原生模块或 RN。目前本站没有功能跨过这条线。</p></> }, en: { title: <>Boundary: when it flips</>, body: <><p>The day a feature genuinely needs native capability — a background-resident Bluetooth smartcube timer, native-grade haptics, something extremely sensitive to startup time / memory — the WebView ceiling stops holding, and only then should you consider dropping to native modules or RN. For now nothing on this site has crossed that line.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本站的 iOS / Android App 就是 Capacitor 套壳 —— 同一份 Next.js 站点 (<code>core/packages/client</code>, Next.js 16 App Router + React 19), 不维护第二套原生 UI。壳的角色刻意做薄: 它只是一个加载器, 用 <code>server.url</code> 指向线上 Next 站点。结果是<strong>前端改了 Next 不必重 build 壳</strong> —— 内容迭代照常走 Web 的发布节奏, 壳本身很少动。</p>
        <p>构建走 GitHub Actions 的 <code>mobile_build.yml</code>, <code>workflow_dispatch</code> 手动触发, <strong>双 runner 并行</strong>: 一个 Linux runner 出 Android APK, 一个 macOS runner 出 iOS IPA (iOS 的 IPA 只能在 macOS 上构建, 这也是为什么 macOS 端是这条移动线绕不开的一环 —— 见 <code>mac-mini</code> 页)。产物落到 CI artifact, 用户说 "更新 app" 即触发这条流水线把 APK + IPA 拉下来。</p>
        <p>本地测试用 MuMu 安卓模拟器 + ADB 自驱: 从 CI artifact 拉下 APK, <code>adb install</code> 进模拟器, 再用 ADB 驱动点击 / 截图验证页面。整条链路不需要真机也能跑通 Android 侧的冒烟测试; iOS 侧因为构建依赖 macOS, 走 CI 出 IPA。</p>
        <p>为什么是 Capacitor 不是 React Native: 本站是内容与工具密集型 —— frame-count 的 WebCodecs 解码管线、cubing.js 的 3D 魔方、cubeopt-wasm 的 WASM solver、一堆 worker, 这些本来就在浏览器里跑得很好。换 RN 意味着把每个页面 UI 用原生组件重写、把整条 WASM/worker 管线重新接到原生侧, 对一个 web-first 工具站这笔重写换不回等价收益。所以 <code>react-native</code> 页是 "认真评估过、当下有意识没走的另一条路"; Capacitor 是务实的那一边。这三页 (Capacitor / react-native / mac-mini) 串起来就是本站完整的移动线。</p>
      </>
    ),
    en: (
      <>
        <p>The site's iOS / Android app is a Capacitor shell — the same Next.js site (<code>core/packages/client</code>, Next.js 16 App Router + React 19), with no second native UI to maintain. The shell is deliberately thin: it's just a loader, pointing <code>server.url</code> at the live Next site. The result is that <strong>front-end changes to Next need no shell rebuild</strong> — content iterates on web's release cadence and the shell itself rarely moves.</p>
        <p>Builds run through GitHub Actions' <code>mobile_build.yml</code>, triggered manually via <code>workflow_dispatch</code>, with <strong>two runners in parallel</strong>: a Linux runner producing the Android APK and a macOS runner producing the iOS IPA (an iOS IPA can only be built on macOS — which is why the macOS endpoint is an unavoidable link in this mobile line; see the <code>mac-mini</code> page). Artifacts land in CI; when the user says "update the app," this pipeline fires and pulls down the APK + IPA.</p>
        <p>Local testing uses the MuMu Android emulator + ADB, self-driven: pull the APK from the CI artifact, <code>adb install</code> it into the emulator, then drive taps / screenshots over ADB to verify pages. The whole chain runs the Android-side smoke test without a physical device; the iOS side, dependent on macOS to build, ships its IPA through CI.</p>
        <p>Why Capacitor over React Native: the site is content- and tool-heavy — frame-count's WebCodecs decode pipeline, cubing.js 3D cubes, cubeopt-wasm's WASM solver, a pile of workers — all already running well in the browser. Switching to RN would mean rewriting every page's UI in native components and re-wiring the entire WASM/worker pipeline to native; for a web-first toolkit that rewrite doesn't buy back equivalent value. So the <code>react-native</code> page is "the road seriously evaluated and consciously not taken for now"; Capacitor is the pragmatic side. These three pages (Capacitor / react-native / mac-mini) together form the site's complete mobile line.</p>
      </>
    ),
  },
  links: [
    { label: 'capacitorjs.com', href: 'https://capacitorjs.com' },
    { label: 'GitHub · ionic-team/capacitor', href: 'https://github.com/ionic-team/capacitor' },
    { label: 'Docs · Getting Started', href: 'https://capacitorjs.com/docs/getting-started' },
    { label: 'Official Plugins', href: 'https://capacitorjs.com/docs/apis' },
    { label: 'Capacitor vs Cordova', href: 'https://capacitorjs.com/docs/cordova' },
  ],
};

export default CAPACITOR;
