import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, s, f, p, c, t } from '../_lib/stack_tool_types';

// ─── cubing.js ──────────────────────────────────────────────────────────────

export const CUBING_JS: StackTool = {
  slug: 'cubing-js',
  name: 'cubing.js',
  version: '0.63.3',
  since: '2018-09',
  group: 'frontend',
  accent: '#F7B500',
  bright: '#FFD45A',
  glyph: '▣',
  floats: ['TwistyPlayer', 'randomScrambleForEvent', 'Alg', 'KPuzzle', 'KPattern', 'Move', 'cubing/twisty', 'cubing/scramble', 'cubing/kpuzzle', 'cubing/alg', 'puzzle-geometry', 'kociemba'],
  zh: {
    tagline: 'WCA 级打乱 + 3D 动画 + 公式解析',
    role: '17 个 WCA 项目的随机态打乱、所有公式播放器的 3D 动画、KPuzzle 状态推导全部走它。',
    heroSub: <>Lucas Garron 从 2018 年开始,把"speedcubing 圈过去二十年靠 C++ 拼出来的算法 (Kociemba / Threephase / sq1 reducer / pyraminx solver / ...)"一一搬进浏览器, 包成一个 npm 包。今天 WCA 官方、WCA Live、所有现代魔方网站打乱都从这一棵 TS 树长出来。</>,
    whatDesc: <>cubing.js 是一个<strong>纯前端</strong> speedcubing 工具集 —— 10 个子模块 (alg / kpuzzle / scramble / twisty / search / puzzles / notation / puzzle-geometry / bluetooth / stream)。没有服务器, 所有 solver / 打乱生成 / 状态推导都在 Worker 里跑。配 three.js 出 3D 动画, 配自家 SVG 出 2D 展开图。</>,
    historyDesc: <>2018 年 9 月 GitHub 首个 commit, 起点是把 alg.cubing.net (Lucas 自己 2009 年起维护的 alg playground) 模块化。之后五年完成 Kociemba GPU 友好移植、KPuzzle 通用引擎、TwistyPlayer Web Component, 直到 2024 年 WCA 官网整站换用 cubing.js 打乱。</>,
    conceptsTitle: '十个模块的核心抽象',
    conceptsDesc: <>三个核心抽象一旦理解,所有 API 都顺:<strong>Alg</strong> 是公式字符串的 AST,<strong>KPuzzle</strong> 是带状态的魔方定义,<strong>KPattern</strong> 是某一刻的 sticker 排列。TwistyPlayer 只是把这三件事接到 Canvas 上。</>,
    whyDesc: <>2026 年要在 web 上做魔方相关任何东西, 选项基本只有 cubing.js —— 没有第二个库覆盖到 17 个 WCA 项目, 没有第二个团队在维护 WCA 标准的 random-state 打乱生成器。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>WCA 官方网站、WCA Live (现场记分)、speedcubedb (公式库)、reco.nz (recon)、cubing.net 自家工具站、几乎所有第三方 alg trainer。最近一年 csTimer 也把部分 sq1 / megaminx 打乱逻辑参考了过来。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>cubing.js 现在还在快版本节奏 (0.63.3, 月更), 距 1.0 主要差稳定 API 承诺。下一阶段重点是 Bluetooth 智能魔方协议统一、WebGPU 渲染管线、WCA 即将要求的更严格 random-state 规则。</>,
  },
  en: {
    tagline: 'WCA-grade scrambles + 3D twisty + alg parsing',
    role: 'Random-state scrambles for all 17 WCA events, 3D animation for every player, and KPuzzle state derivation all live here.',
    heroSub: <>Lucas Garron has been moving "twenty years of speedcubing community C++ algorithms (Kociemba / Threephase / sq1 reducer / pyraminx solver / ...)" into the browser, one module at a time, since 2018. Today the WCA, WCA Live, and every modern cubing site grow their scrambles from this one TS tree.</>,
    whatDesc: <>cubing.js is a <strong>pure-frontend</strong> speedcubing toolkit — 10 sub-modules (alg / kpuzzle / scramble / twisty / search / puzzles / notation / puzzle-geometry / bluetooth / stream). No server: every solver, scramble generator, and state transition runs in a Web Worker. It pairs with three.js for 3D animation and its own SVG renderer for 2D unfolded layouts.</>,
    historyDesc: <>First commit September 2018, born as a modular rewrite of alg.cubing.net (which Lucas had run since 2009). Over the next five years it gained a browser port of Kociemba, the generic KPuzzle engine, and the TwistyPlayer Web Component — culminating in the WCA's main site switching to cubing.js scrambles in 2024.</>,
    conceptsTitle: 'Ten modules, three core abstractions',
    conceptsDesc: <>Three abstractions and the rest follows: <strong>Alg</strong> is the AST of an algorithm string, <strong>KPuzzle</strong> is a stateful puzzle definition, and <strong>KPattern</strong> is one sticker configuration. TwistyPlayer is just those three wired to a canvas.</>,
    whyDesc: <>If you're building anything cube-related on the web in 2026, cubing.js is effectively the only choice — nothing else covers all 17 WCA events, and nothing else has a team maintaining the WCA spec's random-state scramblers.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>The WCA's own site, WCA Live (in-venue scoring), speedcubedb (alg library), reco.nz (reconstructions), cubing.net's own tool suite, and almost every third-party alg trainer. Even csTimer borrowed parts of the sq1 / megaminx logic in the last year.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>cubing.js is still on a rapid-release cadence (0.63.3, monthly bumps); the main gap before 1.0 is stable-API commitments. Up next: a unified smart-cube Bluetooth protocol, a WebGPU render pipeline, and the stricter random-state rules the WCA is about to mandate.</>,
  },
  heroStats: [
    { num: '17', zh: <>覆盖 WCA 项目 <em>含 4x4 reduction / sq1</em></>, en: <>WCA events covered <em>incl. 4x4 reduction / sq1</em></>
    },
    { num: '10', zh: <>子模块 <em>alg / kpuzzle / twisty / scramble / ...</em></>, en: <>sub-modules <em>alg / kpuzzle / twisty / scramble / ...</em></>
    },
    { num: '0', unit: '.63', zh: <>当前版本 <em>2026-05 · npm cubing@0.63.3</em></>, en: <>current release <em>2026-05 · npm cubing@0.63.3</em></>
    },
    { num: '8', unit: 'y', zh: <>2018 年首个 commit 至今</>, en: <>since the first commit in 2018</>
    },
  ],
  intro: {
    zh: (
      <>
        <p>cubing.js 是 Lucas Garron (前 Stanford CS、WCA 代表、3x3 早年世界纪录保持者之一) 主导的开源项目。它的起点不是 2018, 而是更早的 2009 —— Lucas 当时为了让 speedcuber 在浏览器里粘公式、回放、改朝向, 自己写了 alg.cubing.net。那是一坨直接挂在 HTML 上的 JS。十年下来, 这一份代码膨胀到无法维护, 2018 年 9 月他用 TypeScript 开了新仓库, 决定把里面的算法、UI、protocol 全部模块化, 命名 cubing.js。</p>
        <p>魔方圈过去几十年里, 真正吃算法的部分 (Kociemba 求解器、Threephase 4x4 reduction、square-1 二阶段、megaminx pruning) 几乎全是 C++ / Java 写的, 跑在 cstimer / qqTimer / TNoodle 这类原生程序里。cubing.js 做的事是把这堆代码移植到现代 JS,加上 Web Worker / TS 类型 / 模块化打包,让 web 应用直接 npm install 就能 random-state 出来一条 WCA 合规的打乱。这是过去十年 speedcubing 工程化里最大的一次"技术下沉"。</p>
        <p>到 2024 年, WCA 把官网首页的打乱组件正式换成 cubing.js, 等于由社区 maintain 的 npm 包接管了官方仪式性的"这一场比赛用什么打乱"这件事。同年 WCA Live (现场实时记分) 也全面拥抱。cubing.js 从此不再是一个第三方工具, 而是事实上的官方基础设施。</p>
      </>
    ),
    en: (
      <>
        <p>cubing.js is the open-source project led by Lucas Garron (former Stanford CS, WCA delegate, and one of the early 3x3 world-record holders). Its real origin isn't 2018 — it's 2009, when Lucas wrote alg.cubing.net so that speedcubers could paste algorithms into a browser, replay them, and reorient. That codebase was a single blob of script-tag JS. After ten years it had grown unmaintainable, so in September 2018 he opened a new TypeScript repository — algorithms, UI, protocols all modularized — and named it cubing.js.</p>
        <p>For decades, the genuinely hard parts of cubing software (Kociemba's solver, Threephase 4x4 reduction, the square-1 two-phase, megaminx pruning) lived almost entirely in C++ / Java inside native programs like cstimer, qqTimer, and TNoodle. cubing.js does the work of porting that code to modern JS, layering on Web Workers / TS types / proper module packaging — so a web app can <code>npm install cubing</code> and emit a WCA-legal random-state scramble in one call. It's the largest single piece of "tech maturation" speedcubing has seen in a decade.</p>
        <p>By 2024 the WCA had moved its main site's scramble component onto cubing.js — meaning a community-maintained npm package now generates the ceremonial "what scramble does this competition use?" that every WCA event runs on. The same year, WCA Live (live in-venue scoring) followed. cubing.js is no longer a third-party tool; it is, de facto, official infrastructure.</p>
      </>
    ),
  },
  history: [
    { year: '2009', zh: { title: <>alg.cubing.net 起点</>, desc: <>Lucas Garron 写一个浏览器里黏公式 / 回放的 toy 站, 后来成 speedcubing 圈最大公式分享工具。代码是单文件 JS, 没有模块。</> }, en: { title: <>alg.cubing.net begins</>, desc: <>Lucas Garron writes a toy site to paste and replay algorithms in the browser; it grows into the largest alg-sharing tool in the community. Single-file JS, no modules.</> } },
    { year: '2018·09', zh: { title: <>cubing.js 立项</>, desc: <>9 月 18 日 GitHub 首个 commit。决定把 alg.cubing.net 的内核拆成 TS 模块, 第一版仅包含 alg parser 和最简的 puzzle 抽象。</> }, en: { title: <>cubing.js bootstrap</>, desc: <>First GitHub commit on Sept 18. Decision to break the alg.cubing.net core into TS modules; v1 ships only an alg parser and a minimal puzzle abstraction.</> } },
    { year: '2019', zh: { title: <>KPuzzle 通用引擎</>, desc: <>不再为每种魔方写一份代码:用 JSON 描述 face / orbit / move, 引擎自动算转动后的 sticker 排列。从此加新魔方只需要写定义文件。</> }, en: { title: <>KPuzzle generic engine</>, desc: <>Stop hand-coding each puzzle: describe faces / orbits / moves as JSON, let the engine derive the post-move sticker layout. Adding a new puzzle becomes a definition-only change.</> } },
    { year: '2020·09', zh: { title: <>TwistyPlayer Web Component</>, desc: <>&lt;twisty-player alg="R U R&apos; U R U2&apos; R&apos;"&gt;&lt;/twisty-player&gt; 单标签出 3D 动画。three.js 渲染、自动算 sticker、内置播放控件。"在网页里嵌一个魔方"从此一行 HTML。</> }, en: { title: <>TwistyPlayer Web Component</>, desc: <>&lt;twisty-player alg="R U R&apos; U R U2&apos; R&apos;"&gt;&lt;/twisty-player&gt; renders a full 3D player from one tag. three.js for rendering, auto sticker derivation, built-in controls. "Embed a cube on a page" becomes one line of HTML.</> } },
    { year: '2021', zh: { title: <>Kociemba in Web Worker</>, desc: <>把 cs0x7f 的 min2phase Kociemba C 移植到 JS + 放进 Worker, 随机态 3x3 打乱第一次在浏览器里 100ms 出结果。</> }, en: { title: <>Kociemba in a Web Worker</>, desc: <>Port cs0x7f's min2phase Kociemba C into JS and put it in a Worker. Random-state 3x3 scrambles cross the 100ms mark in-browser for the first time.</> } },
    { year: '2022', zh: { title: <>覆盖全 17 个 WCA 项目</>, desc: <>4x4 Threephase reduction、sq1 二阶段、megaminx / pyraminx / skewb 求解全部到位。tnoodle 之外第一个全项目 WCA-spec random-state 实现。</> }, en: { title: <>All 17 WCA events covered</>, desc: <>4x4 Threephase reduction, sq1 two-phase, megaminx / pyraminx / skewb solvers all land. The first full-event WCA-spec random-state implementation outside TNoodle.</> } },
    { year: '2023', zh: { title: <>puzzle-geometry 通用化</>, desc: <>从 KPuzzle 进一步抽到几何层:任意凸面体 + 切平面 → 自动算 face / sticker / 移动语义。NxN、面心切、轴心切都从一个生成器吐出来。</> }, en: { title: <>puzzle-geometry generalization</>, desc: <>Abstract one level below KPuzzle: any convex polyhedron + slicing planes → auto-derive faces / stickers / move semantics. NxN, face-turning, axis-turning all emerge from one generator.</> } },
    { year: '2024·02', zh: { title: <>Twizzle alpha</>, desc: <>alpha.twizzle.net 上线 —— alg.cubing.net 的精神继任者, 完全基于 cubing.js。多魔方支持、URL 状态保留、键盘 / 鼠标 / 智能魔方多输入源统一。</> }, en: { title: <>Twizzle alpha</>, desc: <>alpha.twizzle.net launches — the spiritual successor to alg.cubing.net, built entirely on cubing.js. Multi-puzzle, URL-encoded state, unified keyboard / mouse / smart-cube input.</> } },
    { year: '2024·07', zh: { title: <>WCA 官网切换</>, desc: <>worldcubeassociation.org 把"比赛用什么打乱"的官方渲染组件换成 cubing.js。从此 WCA 仪式性的打乱展示由 npm 包接管。</> }, en: { title: <>WCA's main site switches over</>, desc: <>worldcubeassociation.org swaps its "what scramble is used at this competition" component to cubing.js. The WCA's ceremonial scramble display is now backed by an npm package.</> } },
    { year: '2024·11', zh: { title: <>WCA Live 全面拥抱</>, desc: <>现场实时记分系统 live.worldcubeassociation.org 把比赛页里的回放、scramble 预览全部走 cubing.js。一场 WCA 比赛全流程都接到这一棵 TS 树上。</> }, en: { title: <>WCA Live full adoption</>, desc: <>Live-scoring system live.worldcubeassociation.org routes its replays and scramble previews through cubing.js. A full WCA competition now runs end-to-end on this one TS tree.</> } },
    { year: '2025', zh: { title: <>Bluetooth 智能魔方协议</>, desc: <>GAN / Moyu / QiYi 等智能魔方的协议在 cubing/bluetooth 子模块统一抽象。一份代码听任意品牌的实时旋转, 再回放成 KPuzzle 状态流。</> }, en: { title: <>Bluetooth smart-cube protocols</>, desc: <>GAN / Moyu / QiYi smart-cube protocols are unified inside the cubing/bluetooth submodule. One bit of code listens to any brand's live turns and replays them into a KPuzzle state stream.</> } },
    { year: '2025·12', highlight: true, zh: { title: <>three.js 0.170 + 类型同步</>, desc: <>底层 three.js 跟到 r170, Twisty 内 AmbientLight intensity 适配 r155+ 的物理光照单位 (×π)。@types/three 一同 bump。</> }, en: { title: <>three.js 0.170 + types bump</>, desc: <>Underlying three.js follows to r170; Twisty's AmbientLight intensity adapts to the r155+ physical-light unit (×π). @types/three is bumped alongside.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>0.63.3 / 当前</>, desc: <>最新发布 cubing@0.63.3。CDN 镜像 cdn.cubing.net 维持 v0 兼容线, npm 主线月度更新, 距 1.0 主要差稳定 API 承诺。</> }, en: { title: <>0.63.3 / current</>, desc: <>Latest release is cubing@0.63.3. The cdn.cubing.net mirror keeps a v0-compatible line; the npm trunk bumps monthly. The gap to 1.0 is mostly stable-API commitments.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>Alg —— 公式的 AST</>, desc: <>把 "R U R&apos; U&apos; F&apos; ..." 一串字符串解析成有结构的对象: Move / Commutator / Conjugate / Pause / Grouping。可以 invert、expand、序列化回字符串。</> }, en: { title: <>Alg — the AST of an algorithm</>, desc: <>Parses a string like "R U R&apos; U&apos; F&apos; ..." into a structured tree of Move / Commutator / Conjugate / Pause / Grouping. It can be inverted, expanded, and serialized back to a string.</> }, code: <code>{k('import')} {'{'} {v('Alg')} {'}'} {k('from')} {s("'cubing/alg'")};{'\n\n'}{k('const')} {v('a')} = {k('new')} {f('Alg')}({s("'[R, U]'")});{'\n'}{v('a')}.{f('expand')}().{f('toString')}();{'\n'}{c("// 'R U R\\' U\\''")}</code> },
    { tag: 'B', zh: { title: <>KPuzzle —— 通用魔方定义</>, desc: <>用 JSON 描述某种魔方:有几个 face、orbit (corner/edge/center 等)、每个 move 让 sticker 怎么排列。引擎读完就能模拟。</> }, en: { title: <>KPuzzle — generic puzzle definition</>, desc: <>A JSON definition: how many faces, what orbits (corner / edge / center / ...), and how each move permutes stickers. Feed it in and the engine simulates the puzzle.</> }, code: <code>{k('import')} {'{'} {v('cube3x3x3')} {'}'} {k('from')} {s("'cubing/puzzles'")};{'\n\n'}{k('const')} {v('kpuzzle')} = {k('await')} {v('cube3x3x3')}.{f('kpuzzle')}();{'\n'}{k('const')} {v('solved')} = {v('kpuzzle')}.{p('defaultPattern')}();</code> },
    { tag: 'C', zh: { title: <>KPattern —— 一刻的状态</>, desc: <>某一时刻所有 sticker 的具体排列, 也就是 "现在魔方长这样"。可以 applyAlg() 走一步公式得新 pattern。</> }, en: { title: <>KPattern — a single state snapshot</>, desc: <>The concrete sticker arrangement at one moment — "the cube looks like this right now." Call applyAlg() with a move sequence to derive the next pattern.</> }, code: <code>{k('const')} {v('p2')} = {v('solved')}.{f('applyAlg')}({s("'R U R\\''")});{'\n'}{c('// p2 differs from solved; applyAlg with inverse returns solved')}</code> },
    { tag: 'D', zh: { title: <>randomScrambleForEvent</>, desc: <>一个函数, 输入 WCA 项目 id ('333' / '444' / 'sq1' / 'pyram' / ...), 异步吐一条 WCA 合规打乱。背后是 Web Worker + 各项目专属 solver。</> }, en: { title: <>randomScrambleForEvent</>, desc: <>One function: pass a WCA event id ('333' / '444' / 'sq1' / 'pyram' / ...) and asynchronously get back a WCA-legal scramble. Backed by a Web Worker plus per-event solvers.</> }, code: <code>{k('import')} {'{'} {v('randomScrambleForEvent')} {'}'} {k('from')} {s("'cubing/scramble'")};{'\n\n'}{k('const')} {v('scramble')} = {k('await')} {f('randomScrambleForEvent')}({s("'333'")});{'\n'}{v('scramble')}.{f('toString')}(); {c('// 19-21 moves, random-state')}</code> },
    { tag: 'E', zh: { title: <>TwistyPlayer Web Component</>, desc: <>&lt;twisty-player&gt; 一行 HTML 出 3D 动画。可设 alg / experimental-setup-alg / background / control-panel / hint-facelets / visualization。</> }, en: { title: <>TwistyPlayer Web Component</>, desc: <>One-line HTML 3D player: &lt;twisty-player&gt;. Configure via alg / experimental-setup-alg / background / control-panel / hint-facelets / visualization.</> }, code: <code>&lt;{f('twisty-player')}{'\n  '}{p('alg')}={s('"R U R\' U\' F\' U F"')}{'\n  '}{p('puzzle')}={s('"3x3x3"')}{'\n  '}{p('control-panel')}={s('"none"')}{'\n'}/&gt;</code> },
    { tag: 'F', zh: { title: <>Move —— 单步旋转</>, desc: <>Alg 解析后最底层的原子。带 family ('R')、amount (1 / 2 / -1)、outerLayer、innerLayer。表示 wide / slice / rotation 都一个类。</> }, en: { title: <>Move — the atomic turn</>, desc: <>The bottom-level atom after parsing. Carries family ('R'), amount (1 / 2 / -1), outerLayer, innerLayer. One class handles wide turns, slices, and rotations alike.</> }, code: <code>{k('import')} {'{'} {v('Move')} {'}'} {k('from')} {s("'cubing/alg'")};{'\n\n'}{k('const')} {v('m')} = {k('new')} {f('Move')}({s("'3Rw2'")});{'\n'}{v('m')}.{p('family')};        {c("// 'R'")}{'\n'}{v('m')}.{p('amount')};        {c('// 2')}{'\n'}{v('m')}.{p('innerLayer')};    {c('// 3')}</code> },
    { tag: 'G', zh: { title: <>puzzle-geometry</>, desc: <>更底一层抽象:输入"几面体 + 一组切平面", 自动出 KPuzzle 定义。NxN、Crazy 3x3、Bermuda、PuzzleMaster 各种自制变体都从这一个生成器出。</> }, en: { title: <>puzzle-geometry</>, desc: <>One layer below: feed in a polyhedron and a set of slicing planes, and a KPuzzle definition is generated. NxN, Crazy 3x3, Bermuda, PuzzleMaster — every fan-made variant comes out of this one generator.</> }, code: <code>{k('import')} {'{'} {v('getPuzzleGeometryByName')} {'}'} {k('from')} {s("'cubing/puzzle-geometry'")};{'\n\n'}{k('const')} {v('pg')} = {f('getPuzzleGeometryByName')}({s("'4x4x4'")});{'\n'}{k('const')} {v('def')} = {v('pg')}.{f('writekpuzzle')}();</code> },
    { tag: 'H', zh: { title: <>cubing/bluetooth</>, desc: <>智能魔方 (GAN / Moyu / QiYi) 协议层。一份 connect() 出来的 SmartPuzzle 暴露 algMoveStream, 用户每转一面就吐一个 Move 事件。</> }, en: { title: <>cubing/bluetooth</>, desc: <>The smart-cube (GAN / Moyu / QiYi) protocol layer. One connect() returns a SmartPuzzle whose algMoveStream emits a Move event per physical turn.</> }, code: <code>{k('import')} {'{'} {v('connectSmartPuzzle')} {'}'} {k('from')} {s("'cubing/bluetooth'")};{'\n\n'}{k('const')} {v('cube')} = {k('await')} {f('connectSmartPuzzle')}();{'\n'}{v('cube')}.{p('algMoveStream')}.{f('addListener')}({v('onMove')});</code> },
    { tag: 'I', zh: { title: <>setSearchDebug</>, desc: <>调 solver / scramble 行为的旋钮:打乱预取等级、Worker 数、log 级别。<code>scramblePrefetchLevel: &apos;immediate&apos;</code> 让下一条 scramble 在当前 resolve 那一刻立即开跑。</> }, en: { title: <>setSearchDebug</>, desc: <>The knob for solver / scramble behavior: prefetch level, worker count, log verbosity. <code>scramblePrefetchLevel: &apos;immediate&apos;</code> kicks off the next scramble the instant the current one resolves.</> }, code: <code>{k('import')} {'{'} {v('setSearchDebug')} {'}'} {k('from')} {s("'cubing/search'")};{'\n\n'}{f('setSearchDebug')}({'{'} {p('scramblePrefetchLevel')}: {s("'immediate'")} {'}'});</code> },
  ],
  whyCards: [
    { icon: '⌬', zh: { title: <>17 个 WCA 项目唯一全覆盖</>, desc: <>3x3 Kociemba、4x4 Threephase、sq1 二阶段、megaminx pruning、pyraminx / skewb 求解、clock 随机态 —— 一个 npm install 全部到位。</> }, en: { title: <>Only library covering all 17 WCA events</>, desc: <>3x3 Kociemba, 4x4 Threephase, sq1 two-phase, megaminx pruning, pyraminx / skewb solvers, clock random-state — one npm install lands them all.</> }, code: <>{f('randomScrambleForEvent')}({s("'sq1'")})</> },
    { icon: '⚙', zh: { title: <>WCA 官方背书</>, desc: <>worldcubeassociation.org + WCA Live 都在用。"现场比赛用的打乱来自这个库"这种地位, 第三方再难替代。</> }, en: { title: <>WCA-blessed</>, desc: <>worldcubeassociation.org and WCA Live both depend on it. "The scrambles used in actual competitions come from this library" — a position no replacement can easily claim.</> }, code: <>{c('// WCA main site + WCA Live')}{'\n'}{c('// both rely on cubing.js')}</> },
    { icon: '▣', zh: { title: <>TwistyPlayer 一行嵌 3D</>, desc: <>Web Component 标签, framework-agnostic。React / Vue / vanilla HTML 全都能直接放进 DOM, three.js 内部细节用户不用碰。</> }, en: { title: <>3D player in one HTML line</>, desc: <>Web Component, framework-agnostic. React / Vue / vanilla HTML can drop it into the DOM directly; three.js details stay internal.</> }, code: <>&lt;{f('twisty-player')} {p('alg')}={s('"R U R\'"')} /&gt;</> },
    { icon: '⌁', zh: { title: <>Web Worker 默认并行</>, desc: <>所有重 solver (Kociemba / Threephase) 默认在 Worker 里跑, 主线程零卡顿。配 setSearchDebug 还能调多 worker。</> }, en: { title: <>Workers by default</>, desc: <>Every heavy solver (Kociemba / Threephase) ships in a Worker; the main thread never blocks. setSearchDebug lets you dial worker counts further.</> }, code: <>{c('// Solver runs in a Worker.')}{'\n'}{c('// Main thread stays fluid.')}</> },
    { icon: '⎇', zh: { title: <>KPuzzle 通用化加新魔方零代码</>, desc: <>想加 5x5 / Crazy 3x3 / 自制变体? 只需要写一个 JSON 定义, 不用写新 solver / 新渲染器。puzzle-geometry 甚至能从几何参数自动出 JSON。</> }, en: { title: <>KPuzzle adds new puzzles without code</>, desc: <>Want 5x5 / Crazy 3x3 / a custom variant? Write one JSON definition; no new solver or renderer needed. puzzle-geometry can even auto-derive the JSON from geometry parameters.</> }, code: <>{c('// JSON puzzle def → renderable cube')}{'\n'}{c('// no solver code required')}</> },
    { icon: '⌘', zh: { title: <>Alg AST 可逆可展开</>, desc: <>"R U R&apos; U&apos;" 的逆是 "U R U&apos; R&apos;"; "[R, U]" 展开是 "R U R&apos; U&apos;"。这些操作 Alg 类一行调用, 不用自己写 parser。</> }, en: { title: <>Invertible / expandable alg AST</>, desc: <>The inverse of "R U R&apos; U&apos;" is "U R U&apos; R&apos;"; "[R, U]" expands to "R U R&apos; U&apos;". One method call on the Alg class — no hand-rolled parser required.</> }, code: <>{v('alg')}.{f('invert')}().{f('toString')}()</> },
    { icon: '⌖', zh: { title: <>TS 类型一等</>, desc: <>从 Alg / Move / KPuzzle / KPattern 到 TwistyPlayer 的每个 prop 都有完整类型。VS Code 自动补全准、refactor 安全。</> }, en: { title: <>First-class TS types</>, desc: <>Full types for everything from Alg / Move / KPuzzle / KPattern to every TwistyPlayer prop. VS Code completions are accurate; refactors are safe.</> }, code: <>{k('import')} {k('type')} {'{'} {t('KPattern')} {'}'} {k('from')} {s("'cubing/kpuzzle'")};</> },
    { icon: '⇆', zh: { title: <>智能魔方协议统一</>, desc: <>GAN / Moyu / QiYi 三家智能魔方的 BLE 协议在 cubing/bluetooth 抽到一个接口。一份代码听任意品牌。</> }, en: { title: <>Smart-cube protocols unified</>, desc: <>GAN / Moyu / QiYi smart cubes all expose the same BLE-driven interface inside cubing/bluetooth. One bit of code, any brand.</> }, code: <>{k('await')} {f('connectSmartPuzzle')}();</> },
    { icon: '⌗', zh: { title: <>MIT-friendly 双许可</>, desc: <>MPL-2.0 OR GPL-3.0+ 双轨, 商业产品也能直接 import 用。社区出版 + 厂商集成都没法律阻力。</> }, en: { title: <>License-friendly dual MPL / GPL</>, desc: <>MPL-2.0 OR GPL-3.0+ dual-licensed; commercial products can import it directly. No legal friction for community publishing or vendor integration.</> }, code: <>{c('// MPL-2.0 OR GPL-3.0+')}</> },
  ],
  adopters: [
    { name: 'World Cube Association', href: 'https://www.worldcubeassociation.org', highlight: true, zhNote: 'WCA 官网打乱组件 2024 年起走 cubing.js', enNote: 'WCA main site uses cubing.js for its scramble component since 2024' },
    { name: 'WCA Live', href: 'https://live.worldcubeassociation.org', highlight: true, zhNote: '现场实时记分, 比赛页回放 / scramble 预览', enNote: 'Live in-venue scoring — replays and scramble preview' },
    { name: 'Twizzle', href: 'https://alpha.twizzle.net', highlight: true, zhNote: 'cubing.js 团队自家 alg playground, alg.cubing.net 继任者', enNote: 'In-house alg playground from the cubing.js team — successor to alg.cubing.net' },
    { name: 'speedcubedb', href: 'https://speedcubedb.com', zhNote: '3x3 公式库网站, 公式播放器全部 TwistyPlayer', enNote: '3x3 alg library — every alg player is a TwistyPlayer' },
    { name: 'reco.nz', href: 'https://reco.nz', zhNote: 'recon 平台, 公式解析 + 动画都走它', enNote: 'Reconstruction platform — alg parsing and animation both go through it' },
    { name: 'AlphaCubing', href: 'https://alphacubing.com', zhNote: '训练 + 计时一体, web 上的 cstimer 平替', enNote: 'Training + timing all-in-one — a web-native cstimer alternative' },
    { name: 'Cubing Stations', zhNote: '展位现场 / 表演用的大屏播放器', enNote: 'Floor / demo big-screen players for in-person events' },
    { name: 'csTimer', href: 'https://cstimer.net', zhNote: 'sq1 / minx 部分逻辑参考 cubing.js', enNote: 'sq1 / minx logic partly references cubing.js' },
    { name: 'TNoodle', zhNote: '官方比赛打乱发生器, 共享同源 solver 数据', enNote: 'Official competition scramble generator — shares solver lineage' },
    { name: 'cubing.net', href: 'https://cubing.net', zhNote: '团队自家工具站, 自然全栈 cubing.js', enNote: 'The team’s own tool hub — natively all-in on cubing.js' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 20+ 文件直接 import, 24 个工具页里 8 个核心依赖', enNote: 'This site — 20+ files import it directly; 8 of 24 tool pages depend on it as a core' },
  ],
  outlook: [
    { tag: <>1.0</>, hot: true, big: true, zh: { title: <>稳定 API 承诺</>, body: <><p>cubing.js 现在还在 0.x 月更, 任何 minor 都可能 break 用户 import。社区 (尤其 WCA / WCA Live 这种 production 用户) 在催 1.0, 把 alg / kpuzzle / scramble / twisty 四个公共面定下来。</p><p>1.0 不会只是 tag 一个版本号 —— 它意味着官方承诺"在 2.0 之前不破坏 import 路径", 这对依赖它做记分系统 / 训练平台的下游是决定性的。</p></> }, en: { title: <>Stable-API commitment</>, body: <><p>cubing.js still moves on monthly 0.x bumps, and any minor can break user imports. Downstream (especially production users like WCA / WCA Live) is asking for a 1.0 that locks in the four public surfaces: alg / kpuzzle / scramble / twisty.</p><p>1.0 isn't just a tag — it would be an explicit promise that import paths stay stable until 2.0, which is decisive for the scoring systems and training platforms built on top.</p></> } },
    { tag: 'BLE', zh: { title: <>智能魔方协议大一统</>, body: <><p>GAN / Moyu / QiYi 三家智能魔方目前协议各异, cubing/bluetooth 子模块在 2025 把抽象统一了 70%。剩下的 30% (校准 / 电池 / OTA) 是下一阶段重点。完成后, 任意品牌的智能魔方插上就能 driver-free 流转 KPuzzle 状态。</p></> }, en: { title: <>One protocol for all smart cubes</>, body: <><p>GAN / Moyu / QiYi smart cubes still ship divergent BLE protocols. The cubing/bluetooth submodule unified ~70% of the surface in 2025; the remaining 30% (calibration / battery / OTA) is the next focus. When done, any brand plugs in and streams KPuzzle states driver-free.</p></> } },
    { tag: <>WebGPU</>, zh: { title: <>下一代渲染管线</>, body: <><p>TwistyPlayer 当前走 three.js WebGL2 后端, 万级 sticker 同屏 (例如 megaminx + hint facelet 全开) 有掉帧。WebGPU 后端在试验仓库里已能跑, 落主仓需要 three.js r170+ 的稳定 WebGPURenderer 配合, 预计 2026 下半年。</p></> }, en: { title: <>The next render pipeline</>, body: <><p>TwistyPlayer currently runs on three.js's WebGL2 backend; tens of thousands of stickers on screen (e.g. megaminx with full hint facelets) drop frames. A WebGPU backend already runs in an experimental fork; landing it in the trunk requires three.js r170+'s stable WebGPURenderer — expected in H2 2026.</p></> } },
    { tag: 'WCA', zh: { title: <>更严的 random-state 规则</>, body: <><p>WCA Regulations Committee 在 2025 讨论"是否要求所有项目都达到严格 random-state, 不允许 random-move 兜底"。一旦落地, 5x5 / 6x6 / 7x7 / megaminx 现在还兜 random-move 的项目就必须有真正的 solver。cubing.js 是少数几个有计算资源去做这件事的实现。</p></> }, en: { title: <>Stricter random-state rules</>, body: <><p>The WCA Regulations Committee is debating in 2025 whether every event must reach strict random-state — no more random-move fallback. If adopted, 5x5 / 6x6 / 7x7 / megaminx will need real solvers. cubing.js is one of very few implementations with the compute headroom to deliver them.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>cuberoot.me 把 cubing.js 当成<strong>魔方计算的标准库</strong>来用 —— <code>packages/client</code> 里 20+ 文件直接 <code>import 'cubing/...'</code>, 拓扑大致:打乱生成、公式解析、3D 动画、状态推导四块同时吃。</p>
        <p><strong>打乱:</strong> <code>utils/cubingScramble.ts</code> 包了 <code>randomScrambleForEvent</code>, 在 module init 调 <code>setSearchDebug({'{'} scramblePrefetchLevel: 'immediate' {'}'})</code>, 让连续生成时下一条 scramble 在当前 resolve 那一刻立即开跑。4x4 因为 cubing.js 内部跑前先 random-state 一个 3x3 (额外 50-200ms), 改路由到 cs0x7f 的 Threephase, 自己包了 <code>utils/cstimer_pool.ts</code> 的 8-worker pool, 4x4 / sq1 / megaminx 等 cstimer 路由项目共享。<code>/scramble/gen</code> 落地时 <code>cstimerPrewarm</code> 把所有 worker 的 pruning-table 并发预热一遍, 用户配置事件期间冷启动成本就摊掉了。</p>
        <p><strong>公式:</strong> <code>utils/alg_ops.ts</code> / <code>utils/alg_validation.ts</code> 用 <code>Alg</code> + <code>Move</code> 做语法校验、逆、展开、normalize。<code>/algdb</code> 公式库的每条记录入库前都过一遍 cubing.js 的 parser 当 lint。Square-1 是个例外 —— <code>AlgPlayer.tsx</code> 里有一段 sq1 alg → canonical <code>(t,b)/(t,b)/...</code> 的归一化, 因为 cubing.js TwistyPlayer 只认那种写法。</p>
        <p><strong>动画:</strong> <code>components/TwistySection.tsx</code> 和 <code>components/AlgPlayer/AlgPlayer.tsx</code> 都用 <code>import('cubing/twisty')</code> 动态拉, 避开 ~150KB 的二进制进首屏 chunk。AlgPlayer 还从 TwistyPlayer 实例上取底层 controller 做光标-动画同步:文本框光标移到第 5 步, 动画跳到第 5 步。<code>/recon</code> / <code>/alg</code> 41 套公式训练页全靠这一套。</p>
        <p><strong>状态推导:</strong> CFOP 各阶段 (cross / F2L / OLL / PLL / ZBLL) 的 lookup 都需要 <code>KPattern</code> 做 sticker 排列识别 —— 见 <code>utils/f2l_lookup.ts</code> / <code>oll_lookup.ts</code> / <code>pll_lookup.ts</code> / <code>zbll_lookup.ts</code>。<code>utils/recon_autofill_core.ts</code> 用同样的 KPattern 做 recon 提交时自动补缺失字段。<code>/demo/sq1</code> 用 sq1 的 KPuzzle 定义算每一步切片后的 sticker。</p>
        <p>版本固定 <code>"cubing": "^0.63.3"</code>, alg-build / client / server 三个 workspace 一致。cubing.js 还在 0.x 节奏意味着我们偶尔会跟着小版本调一两个 import 名, 但每次 break 都在 release notes 里清楚标注, 不算重负担。</p>
      </>
    ),
    en: (
      <>
        <p>cuberoot.me uses cubing.js as the <strong>standard library for cube math</strong>. 20+ files in <code>packages/client</code> import directly from <code>cubing/...</code>; the surface roughly splits into four areas: scramble generation, alg parsing, 3D animation, and state derivation.</p>
        <p><strong>Scrambles:</strong> <code>utils/cubingScramble.ts</code> wraps <code>randomScrambleForEvent</code> and calls <code>setSearchDebug({'{'} scramblePrefetchLevel: 'immediate' {'}'})</code> at module init so the next scramble starts the instant the current one resolves. 4x4 is special-cased: cubing.js prepends an extra random-state 3x3 solve (50–200ms), so we route 4x4 to cs0x7f's Threephase via <code>utils/cstimer_pool.ts</code>'s 8-worker pool — 4x4 / sq1 / megaminx and other cstimer-routed events share it. On <code>/scramble/gen</code> mount, <code>cstimerPrewarm</code> warms every worker's pruning table in parallel, amortizing the cold start while the user picks events.</p>
        <p><strong>Algs:</strong> <code>utils/alg_ops.ts</code> / <code>utils/alg_validation.ts</code> use <code>Alg</code> + <code>Move</code> for syntax checks, inverse, expansion, and normalization. Every record entering the <code>/algdb</code> library is parsed by cubing.js as a lint pass. Square-1 is the one exception — <code>AlgPlayer.tsx</code> contains a normalizer that turns sq1 algs into canonical <code>(t,b)/(t,b)/...</code> form, because cubing.js's TwistyPlayer only accepts that shape.</p>
        <p><strong>Animation:</strong> Both <code>components/TwistySection.tsx</code> and <code>components/AlgPlayer/AlgPlayer.tsx</code> use <code>import('cubing/twisty')</code> dynamically to keep the ~150KB chunk off the landing path. AlgPlayer grabs the underlying controller from the TwistyPlayer instance to wire caret-driven animation sync — move the textarea cursor to step 5 and the player jumps to step 5. <code>/recon</code> and the 41-set <code>/alg</code> trainer pages all ride this.</p>
        <p><strong>State derivation:</strong> CFOP stage detection (cross / F2L / OLL / PLL / ZBLL) uses <code>KPattern</code> to identify sticker layouts — see <code>utils/f2l_lookup.ts</code> / <code>oll_lookup.ts</code> / <code>pll_lookup.ts</code> / <code>zbll_lookup.ts</code>. <code>utils/recon_autofill_core.ts</code> uses the same KPattern shape to auto-fill missing fields on recon submission. <code>/demo/sq1</code> drives every slice's sticker layout from the sq1 KPuzzle definition.</p>
        <p>Version is pinned at <code>"cubing": "^0.63.3"</code> across the alg-build / client / server workspaces. Being on 0.x means occasional minor-version import renames, but each break is well-documented in the release notes — a manageable cost.</p>
      </>
    ),
  },
  links: [
    { label: 'js.cubing.net', href: 'https://js.cubing.net/cubing' },
    { label: 'GitHub · cubing/cubing.js', href: 'https://github.com/cubing/cubing.js' },
    { label: 'npm · cubing', href: 'https://www.npmjs.com/package/cubing' },
    { label: 'Twizzle (alpha)', href: 'https://alpha.twizzle.net' },
  ],
};

export default CUBING_JS;
