import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, f, p, c, s } from '../_lib/stack_tool_types';

// ─── curl ───────────────────────────────────────────────────────────────────

export const CURL: StackTool = {
  slug: 'curl',
  name: 'curl',
  version: '8.20.0',
  since: '1996-11',
  group: 'dev',
  accent: '#073551',
  bright: '#3F6E96',
  glyph: '⇄',
  floats: ['HTTP', 'HTTPS', 'FTP', 'SFTP', 'IMAP', 'SMTP', 'MQTT', 'libcurl', 'QUIC', 'HTTP/3', 'TLS', '--write-out', 'multi-handle', 'etag'],
  zh: {
    tagline: '一个人维护 30 年, 跑在 200 亿台设备里的 HTTP 客户端',
    role: '本仓库调试 API 的默认方式。开 nginx vhost, ping endpoint, 看 cert 过期, 跑 GitHub Actions 健康检查, 全是它。',
    heroSub: <>Daniel Stenberg 1996 年 11 月接手 Rafael Sagula 的 <strong>HttpGet 0.1</strong>, 一路改名 urlget → curl, 二十九年还是同一个 maintainer。如今 curl 跑在 <strong>200 亿台</strong> 设备里:每一部手机、几乎每一辆车、绝大多数电视、所有 Linux 发行版、Windows 10 起的系统命令、macOS 默认、还有 NASA 火星车。"一个人写一个工具能走多远"在 curl 这里被推到了上限。</>,
    whatDesc: <>curl 是命令行 HTTP / 网络客户端, <strong>libcurl</strong> 是它背后的 C 库 —— 几乎所有现代语言的 HTTP 客户端最底层都能追到 libcurl。它的特点是 <strong>协议广 + 单二进制 + 嵌入容易</strong>:HTTP / HTTPS / FTP / SFTP / SCP / SMTP / POP3 / IMAP / LDAP / MQTT / RTSP / WebSocket / DICT / TELNET / FILE / GOPHER 几十个协议同一个二进制都能讲, 静态链接后 2~3MB, 嵌入任何固件都不嫌大。</>,
    historyDesc: <>从 1996-11-11 Rafael Sagula 的 HttpGet 0.1, 到 2026-04-29 的 8.20.0, 二十九年。中间最大几个节点:1998-03 改名 curl 4 (加上传)、2000-08 libcurl 7.1 拆出 (第一个非 beta)、2017-10 Daniel 获 Polhem Prize、2019-01 Daniel 入职 wolfSSL 全职做 curl、2019-09 HTTP/3 实验性、2021-02 Rust hyper backend 进入、2025-2026 200 亿安装规模。</>,
    conceptsTitle: '协议矩阵 + libcurl + multi handle',
    conceptsDesc: <>表面是命令行, 底下是一个抽象到 TLS backend / DNS resolver / 协议 driver 都可替换的库。<code>-H</code> / <code>-d</code> / <code>-o</code> / <code>-w</code> 几个核心 flag 撑起 99% 日常用法, 剩下 250+ 选项给少数派。</>,
    whyDesc: <>2026 年还选 curl, 不是因为它"新", 而是因为它<strong>无处不在 + 接口稳 + 一个人三十年没换班</strong>。任何写脚本 / 写文档 / 写 SDK / 写 firmware 的人, 默认能假设目标系统已经装好 curl —— 这一条几乎没有其它工具能做到。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>问"谁在用 curl"已经没意义。它在 200 亿台设备里, 110 个操作系统, 28 种 CPU 架构上跑。NASA 把它送上火星, Tesla / 各路汽车信息娱乐系统里都有, 几乎所有 Linux 发行版默认装, macOS / Windows 10+ 自带。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>HTTP/3 在 8.x 系列全面默认可用; Rust hyper backend 从实验性慢慢成熟; wcurl 这种"对人友好"的 wrapper 在 2024 起被 Debian 等发行版默认包入。Daniel 仍在 wolfSSL 全职维护 curl, 三十周年纪念在 2026-11 — "一个人的开源工具能走多远" 还在继续刷新上限。</>,
  },
  en: {
    tagline: 'Thirty years, one maintainer, twenty billion installations',
    role: 'The default way to poke this repo. Opening an nginx vhost, pinging an endpoint, checking a cert, running a GitHub Actions health probe — all curl.',
    heroSub: <>Daniel Stenberg picked up Rafael Sagula's <strong>HttpGet 0.1</strong> in November 1996, renamed it through urlget into curl, and is still the same maintainer twenty-nine years later. curl now runs in <strong>twenty billion</strong> instances: every smartphone, nearly every car, most TVs, every mainstream Linux distro, the built-in <code>curl.exe</code> shipped with Windows 10 and later, the one in macOS, and NASA's Mars rovers. "How far can one person take one tool" hits its ceiling here.</>,
    whatDesc: <>curl is a command-line network client; <strong>libcurl</strong> is the C library behind it — the deepest HTTP client layer in nearly every modern language eventually traces to libcurl. Its identity is <strong>protocol breadth, one binary, easy embedding</strong>: HTTP / HTTPS / FTP / SFTP / SCP / SMTP / POP3 / IMAP / LDAP / MQTT / RTSP / WebSocket / DICT / TELNET / FILE / GOPHER and more all in one binary, 2–3 MB statically linked, small enough to ship in any firmware.</>,
    historyDesc: <>From Rafael Sagula's HttpGet 0.1 on 1996-11-11 to 8.20.0 on 2026-04-29, twenty-nine years. Big nodes along the way: rename to curl 4 with uploads (1998-03), libcurl 7.1 split out as first non-beta (2000-08), Daniel awarded the Polhem Prize (2017-10), Daniel joins wolfSSL to work on curl full-time (2019-01), experimental HTTP/3 (2019-09), Rust hyper backend lands (2021-02), 20 billion installs surveyed (2025–2026).</>,
    conceptsTitle: 'Protocol matrix + libcurl + multi-handle',
    conceptsDesc: <>The surface is a CLI; the interior is a library where TLS backend, DNS resolver, and protocol drivers are all swappable. A handful of flags (<code>-H</code> / <code>-d</code> / <code>-o</code> / <code>-w</code>) cover 99% of daily use; 250+ other options serve the long tail.</>,
    whyDesc: <>Picking curl in 2026 isn't about novelty. It's about <strong>ubiquity, interface stability, and one maintainer for thirty years</strong>. Anyone writing a script, a doc, an SDK, or firmware can assume the target machine already has curl — almost no other tool can claim that.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>"Who uses curl" is the wrong question. It runs on 20 billion devices, 110 operating systems, 28 CPU architectures. NASA shipped it to Mars; Tesla and other carmakers run it in infotainment; every mainstream Linux distro ships it by default; macOS and Windows 10+ bundle it.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>HTTP/3 is broadly default-on in the 8.x line; the Rust hyper backend is maturing past experimental; wcurl, a "friendly" wrapper, started landing as a default package in Debian and others through 2024. Daniel continues full-time at wolfSSL on curl; the 30th anniversary lands in 2026-11 — "how far one person's open-source tool can go" keeps extending its ceiling.</>,
  },
  heroStats: [
    { num: '20', unit: 'B', zh: <>200 亿 安装规模 <em>2026 估计 · daniel.haxx.se</em></>, en: <>20 B installations <em>2026 est. · daniel.haxx.se</em></>
    },
    { num: '29', unit: 'y', zh: <>一个 maintainer 二十九年 <em>1996-11 至今</em></>, en: <>one maintainer for 29 years <em>since 1996-11</em></>
    },
    { num: '28', unit: '+', zh: <>支持的网络协议 <em>HTTP/HTTPS/FTP/MQTT/...</em></>, en: <>network protocols supported <em>HTTP/HTTPS/FTP/MQTT/...</em></>
    },
    { num: '110', unit: 'OS', zh: <>跑过的操作系统 <em>28 种 CPU 架构</em></>, en: <>operating systems it runs on <em>28 CPU architectures</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>curl 的起源不是 Daniel Stenberg, 是巴西开发者 Rafael Sagula。1996 年 11 月 11 日 Rafael 发了一个叫 <strong>HttpGet 0.1</strong> 的小工具, 用来通过 IRC 频道下载汇率信息。Daniel 当时在瑞典写一个 IRC bot, 顺手 patch 了一些 bug, 12 月 17 日发了 0.2 (含他的修改)。然后 Daniel 接管了项目, 1997 年 8 月加了 FTP 改名 urlget, 1998 年 3 月加了上传改名 <strong>curl 4</strong>。"Client for URLs" 就这么定下来了。</p>
        <p>2000 年春天, Daniel 做了一次大重构, 把所有"做网络"的代码从命令行壳子里拆出来变成一个独立的 C 库 —— <strong>libcurl</strong>。2000-08-07 libcurl 7.1 发布, 是第一个非 beta 版本。这一步决定了 curl 接下来二十六年的命运:命令行只是 libcurl 的一个 demo, libcurl 才是被几乎所有语言的 HTTP 客户端 (PHP cURL extension / Python pycurl / Node node-libcurl / Ruby Typhoeus / Rust curl-rust / ...) 当作底层调的那一个。</p>
        <p>2007 年加 IPv6, 2018 年默认 HTTP/2, 2019 年实验性 HTTP/3 + QUIC (用 ngtcp2 / quiche 两个 backend, curl 自己不写 QUIC 实现, 但提供统一接口), 2021 年加入 Rust hyper backend (Mozilla 的 HTTP 库) 作为可选 HTTP/1.1 + HTTP/2 实现, 走"内存安全 HTTP 引擎"路线。Daniel 2019 年起在 wolfSSL 全职做 curl, 是世界上极少数"被付钱专门维护一个开源项目"的人之一。2017 年他拿到了 Polhem Prize (瑞典工程界最高奖之一), 2020 年起 curl 安装规模官方说法从"百亿"刷到 2026 的"200 亿"。</p>
      </>
    ),
    en: (
      <>
        <p>curl didn't start with Daniel Stenberg — it started with Brazilian developer Rafael Sagula. On 1996-11-11 Rafael released a small tool called <strong>HttpGet 0.1</strong> for fetching exchange rates over an IRC channel. Daniel was writing an IRC bot in Sweden, patched a few bugs, and on 1996-12-17 shipped 0.2 with his fixes. Daniel then took over: FTP support in 1997-08 renamed it to urlget; upload support in 1998-03 renamed it again to <strong>curl 4</strong>. "Client for URLs" stuck.</p>
        <p>In spring 2000 Daniel did a major restructure, pulling all the networking code out of the CLI shell into a standalone C library — <strong>libcurl</strong>. libcurl 7.1 shipped on 2000-08-07, the first non-beta release. That decision fixed curl's path for the next twenty-six years: the CLI is just one demo of libcurl, and libcurl became the bottom layer of HTTP clients in nearly every language — PHP's cURL extension, Python pycurl, Node node-libcurl, Ruby Typhoeus, Rust curl-rust, and many more all sit on top.</p>
        <p>IPv6 in 2007, HTTP/2 default-on in 2018, experimental HTTP/3 + QUIC in 2019 (with ngtcp2 and quiche as pluggable backends — curl itself doesn't implement QUIC, but exposes one unified interface). Rust hyper backend joined in 2021 as an optional memory-safe HTTP/1.1 + HTTP/2 engine from Mozilla. Daniel has been full-time on curl at wolfSSL since 2019 — one of very few people on Earth paid specifically to maintain a single open-source project. He received the Polhem Prize in 2017 (one of Sweden's top engineering awards); from 2020 on the official install count climbed from "tens of billions" to the current 2026 figure of <strong>twenty billion</strong>.</p>
      </>
    ),
  },
  history: [
    { year: '1996·11', zh: { title: <>Rafael 发 HttpGet 0.1</>, desc: <>1996-11-11 巴西的 Rafael Sagula 发出 HttpGet 0.1, 用来通过 IRC 看汇率。Daniel Stenberg 当时在写 IRC bot, 顺手 patch, 12-17 发了 0.2。curl 真正的开始日。</> }, en: { title: <>Rafael ships HttpGet 0.1</>, desc: <>On 1996-11-11 Brazilian Rafael Sagula releases HttpGet 0.1 to read exchange rates through an IRC channel. Daniel Stenberg, then writing an IRC bot, sends patches and ships 0.2 on 1996-12-17. The real birth date.</> } },
    { year: '1997·08', zh: { title: <>加 FTP, 改名 urlget</>, desc: <>FTP 协议加入后名字不再准, 改成 urlget 2.0。Daniel 此时已是事实上的 maintainer。</> }, en: { title: <>FTP added, renamed urlget</>, desc: <>With FTP support the old name no longer fit; the project becomes urlget 2.0. Daniel is now the de facto maintainer.</> } },
    { year: '1998·03', zh: { title: <>改名 curl 4, 加上传</>, desc: <>1998-03-20 加上传能力, 名字最终定为 curl ("Client for URLs"), 版本号直接跳 4 来对齐之前的累积发布数。</> }, en: { title: <>Renamed to curl 4, uploads added</>, desc: <>On 1998-03-20 upload support arrives; the name settles on curl ("Client for URLs") and the version jumps to 4 to align with the accumulated release count.</> } },
    { year: '2000·08', zh: { title: <>libcurl 7.1 拆出</>, desc: <>2000-08-07 libcurl 7.1 发布 (第一个非 beta), 把网络代码从 CLI 拆成独立 C 库。决定了 curl 接下来 26 年是几乎所有语言 HTTP 客户端的底层。</> }, en: { title: <>libcurl 7.1 splits out</>, desc: <>On 2000-08-07 libcurl 7.1 ships as the first non-beta — the networking code becomes a standalone C library. This shapes the next 26 years: libcurl ends up as the bottom layer of HTTP clients in nearly every language.</> } },
    { year: '2007·07', zh: { title: <>IPv6 全面</>, desc: <>7.16+ 把 IPv6 从可选编译进入默认开启状态。HTTP / FTP / SCP / TFTP 等全协议都走 v6, 早于绝大多数 HTTP 工具。</> }, en: { title: <>IPv6 across the board</>, desc: <>7.16+ flips IPv6 from optional to default-on across HTTP / FTP / SCP / TFTP — earlier than nearly every other HTTP tool of the era.</> } },
    { year: '2017·10', zh: { title: <>Daniel 获 Polhem Prize</>, desc: <>瑞典工程师皇家协会 (IVA) 颁的 Polhem Prize, 由瑞典国王 Carl XVI Gustaf 亲手交给 Daniel, 表彰他 21 年单人维护 curl。</> }, en: { title: <>Daniel receives the Polhem Prize</>, desc: <>The Royal Swedish Academy of Engineering Sciences (IVA) presents the Polhem Prize to Daniel, handed by King Carl XVI Gustaf, recognising 21 years of single-handed curl stewardship.</> } },
    { year: '2018·09', zh: { title: <>HTTP/2 默认</>, desc: <>7.61+ 把 HTTP/2 (nghttp2 backend) 设为 HTTPS 默认协议。"libcurl 是不是支持 HTTP/2" 这种问题从此不需要问。</> }, en: { title: <>HTTP/2 by default</>, desc: <>7.61+ makes HTTP/2 (via nghttp2) the default over HTTPS. "Does libcurl support HTTP/2" is no longer a question worth asking.</> } },
    { year: '2019·01', zh: { title: <>Daniel 入 wolfSSL 全职做 curl</>, desc: <>Daniel 接受 wolfSSL 全职 offer 专门维护 curl + libcurl + 相关周边。世界上极少数被付钱专门做一个开源项目的人。</> }, en: { title: <>Daniel joins wolfSSL full-time</>, desc: <>Daniel accepts a wolfSSL full-time role dedicated to curl + libcurl + adjacent libraries. One of very few people paid specifically to maintain a single OSS project.</> } },
    { year: '2019·09', zh: { title: <>HTTP/3 + QUIC 实验性</>, desc: <>7.66 加 HTTP/3 实验性支持。curl 自己不写 QUIC, 而是抽象 ngtcp2 / quiche 两个 backend, 让协议团队各自竞争。</> }, en: { title: <>Experimental HTTP/3 + QUIC</>, desc: <>7.66 ships experimental HTTP/3. curl doesn't implement QUIC itself — it abstracts over ngtcp2 and quiche as backends, letting protocol teams compete.</> } },
    { year: '2021·02', zh: { title: <>hyper Rust backend</>, desc: <>7.75 加 Mozilla hyper Rust HTTP 库作为可选 HTTP/1.1 + HTTP/2 backend。"libcurl 内存安全路径"的第一个里程碑。</> }, en: { title: <>hyper Rust backend lands</>, desc: <>7.75 introduces Mozilla's hyper Rust HTTP library as an optional HTTP/1.1 + HTTP/2 backend — the first milestone toward a memory-safe libcurl path.</> } },
    { year: '2023·10', zh: { title: <>CVE-2023-38545 高危事件</>, desc: <>SOCKS5 heap overflow, Daniel 把它叫"我职业生涯最糟的 curl 安全 bug"。从公开预告到补丁全过程透明, 行业 disclosure 范本。</> }, en: { title: <>CVE-2023-38545 high-severity event</>, desc: <>A SOCKS5 heap overflow Daniel called "the worst curl security bug of my career." Pre-announcement, embargo, and patch were all run in the open — a model disclosure for the industry.</> } },
    { year: '2025·05', zh: { title: <>200 亿安装规模</>, desc: <>Daniel 在 2025-2026 多次公开演讲把 curl 安装规模从 "100 亿+" 上修到 <strong>200 亿</strong>, 跑在 110 种操作系统 + 28 种 CPU 架构上。</> }, en: { title: <>20 billion installs</>, desc: <>Through 2025–2026 talks Daniel revises the install figure from "10B+" to <strong>20 billion</strong>, running on 110 operating systems and 28 CPU architectures.</> } },
    { year: '2026·04', highlight: true, zh: { title: <>8.20.0 / 当前稳定</>, desc: <>2026-04-29 8.20.0 GA。HTTP/3 在主流平台全部 stable, hyper backend 接近 production-ready, wcurl friendly wrapper 进入 Debian / Ubuntu / Fedora 默认包。11 月 curl 满 30 周年。</> }, en: { title: <>8.20.0 / current stable</>, desc: <>8.20.0 GA on 2026-04-29. HTTP/3 stable on mainstream platforms; hyper backend nearly production-ready; the wcurl friendly wrapper now ships by default in Debian / Ubuntu / Fedora. November marks curl's 30th anniversary.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>协议矩阵 = 一个二进制</>, desc: <>HTTP / HTTPS / FTP / FTPS / SFTP / SCP / SMTP / SMTPS / POP3 / POP3S / IMAP / IMAPS / LDAP / LDAPS / MQTT / RTSP / RTMP / WebSocket / DICT / TELNET / FILE / GOPHER / TFTP, 一个二进制全收。</> }, en: { title: <>One binary, every protocol</>, desc: <>HTTP / HTTPS / FTP / FTPS / SFTP / SCP / SMTP / SMTPS / POP3 / POP3S / IMAP / IMAPS / LDAP / LDAPS / MQTT / RTSP / RTMP / WebSocket / DICT / TELNET / FILE / GOPHER / TFTP — all in one binary.</> }, code: <code>{p('$')} {f('curl')} {p('-V')}{'\n'}{v('curl 8.20.0')} (x86_64-pc-linux-gnu){'\n'}{v('Protocols:')} dict file ftp ftps gopher gophers{'\n'}  http https imap imaps ldap ldaps mqtt{'\n'}  pop3 pop3s rtmp rtsp scp sftp smb smbs{'\n'}  smtp smtps telnet tftp ws wss</code> },
    { tag: 'B', zh: { title: <>libcurl — 库才是主角</>, desc: <>命令行 curl 只是 libcurl 的一个 demo。PHP cURL / Python pycurl / Node node-libcurl / Ruby Typhoeus / Rust curl-rust / Go go-curl / Swift CocoaLumberjack 全部走 libcurl, 几乎所有语言的 HTTP 客户端底层都能追到它。</> }, en: { title: <>libcurl is the real product</>, desc: <>The curl CLI is just one demo of libcurl. PHP's cURL extension, Python pycurl, Node node-libcurl, Ruby Typhoeus, Rust curl-rust, Go go-curl — nearly every language's HTTP client traces down to libcurl.</> }, code: <code>{c('// C')}{'\n'}CURL {s('*')}h = {f('curl_easy_init')}();{'\n'}{f('curl_easy_setopt')}(h, CURLOPT_URL, {s('"https://api.cuberoot.me/v1/wca/persons"')});{'\n'}{f('curl_easy_perform')}(h);</code> },
    { tag: 'C', zh: { title: <>TLS backend 抽象</>, desc: <>curl 自己不带加密实现, 而是抽象出 TLS backend 接口, 编译时选 OpenSSL / wolfSSL / GnuTLS / mbedTLS / Schannel (Windows 原生) / Secure Transport (Apple, 已弃) / BearSSL / rustls 之一。</> }, en: { title: <>TLS backend abstraction</>, desc: <>curl doesn't bundle a crypto implementation — it abstracts a TLS backend, picked at build time: OpenSSL / wolfSSL / GnuTLS / mbedTLS / Schannel (Windows native) / Secure Transport (Apple, deprecated) / BearSSL / rustls.</> }, code: <code>{p('$')} {f('curl')} {p('-V')} {p('|')} {f('grep')} SSL{'\n'}{v('OpenSSL/3.2.0')} (ssl) (...){'\n'}{c('# wolfSSL build:')}{'\n'}{v('wolfSSL/5.7.0')} (ssl) (HTTPS-proxy)</code> },
    { tag: 'D', zh: { title: <>核心 flag 七件套</>, desc: <><code>-H</code> header / <code>-d</code> body / <code>-X</code> method / <code>-o</code> 输出文件 / <code>-O</code> 用远程名 / <code>-L</code> 跟 redirect / <code>-v</code> verbose。99% 日常用法靠这七个。</> }, en: { title: <>The seven daily flags</>, desc: <><code>-H</code> header / <code>-d</code> body / <code>-X</code> method / <code>-o</code> output file / <code>-O</code> use remote name / <code>-L</code> follow redirects / <code>-v</code> verbose. 99% of daily curl is these seven.</> }, code: <code>{p('$')} {f('curl')} {p('-X')} POST {p('-H')} {s('"Content-Type: application/json"')} \{'\n'}    {p('-d')} {s('\'{"name":"WC2026"}\'')} \{'\n'}    {p('-o')} resp.json {p('-w')} {s('"%{http_code}\\n"')} \{'\n'}    https://api.cuberoot.me/v1/recon</code> },
    { tag: 'E', zh: { title: <>-w 模板 — 拿数据不靠 jq</>, desc: <><code>--write-out</code> 模板能直接吐 <code>%{'{'}http_code{'}'}</code> / <code>%{'{'}time_total{'}'}</code> / <code>%{'{'}size_download{'}'}</code> / <code>%{'{'}remote_ip{'}'}</code> 几十个指标。配 shell 脚本做监控比上 Prometheus 便宜得多。</> }, en: { title: <>-w templates — metrics without jq</>, desc: <><code>--write-out</code> templates emit <code>%{'{'}http_code{'}'}</code> / <code>%{'{'}time_total{'}'}</code> / <code>%{'{'}size_download{'}'}</code> / <code>%{'{'}remote_ip{'}'}</code> and dozens more directly. Pair with shell for monitoring far cheaper than a Prometheus stack.</> }, code: <code>{p('$')} {f('curl')} {p('-s')} {p('-o')} {v('/dev/null')} \{'\n'}    {p('-w')} {s('"%{http_code} %{time_total}s\\n"')} \{'\n'}    https://api.cuberoot.me/health{'\n'}{v('200 0.084s')}</code> },
    { tag: 'F', zh: { title: <>HTTP/3 + QUIC</>, desc: <>2019 实验性, 2024 起在主流平台 stable。curl 自己不写 QUIC, 抽象 ngtcp2 / quiche 两个 backend。<code>--http3</code> flag 一开即用。</> }, en: { title: <>HTTP/3 + QUIC</>, desc: <>Experimental in 2019, stable on mainstream platforms from 2024. curl doesn't implement QUIC itself — it abstracts ngtcp2 / quiche as backends. The <code>--http3</code> flag opts in.</> }, code: <code>{p('$')} {f('curl')} {p('--http3')} {p('-v')} https://cloudflare-quic.com/{'\n'}{v('* using HTTP/3')}{'\n'}{v('* h3 [...] 0RTT-handshake done')}</code> },
    { tag: 'G', zh: { title: <>multi-handle 并发模型</>, desc: <><code>curl_multi_*</code> 一组 API 用一个 select loop 跑数千并发请求, 一线程足够 — 浏览器引擎 / 服务器端 HTTP client / 爬虫框架默认走这条路。</> }, en: { title: <>multi-handle concurrency</>, desc: <>The <code>curl_multi_*</code> API drives thousands of concurrent requests through one select loop, on a single thread — what browser engines, server-side HTTP clients, and crawler frameworks reach for.</> }, code: <code>CURLM {s('*')}mh = {f('curl_multi_init')}();{'\n'}{f('curl_multi_add_handle')}(mh, easy1);{'\n'}{f('curl_multi_add_handle')}(mh, easy2);{'\n'}{f('curl_multi_perform')}(mh, {s('&running')});</code> },
    { tag: 'H', zh: { title: <>etag + If-None-Match 缓存</>, desc: <><code>--etag-save</code> / <code>--etag-compare</code> 让脚本自己实现 HTTP 缓存层, 第二次请求服务端没变就 304, 省带宽省时间。CI 拉公共资产标配。</> }, en: { title: <>etag + If-None-Match caching</>, desc: <><code>--etag-save</code> / <code>--etag-compare</code> let scripts implement an HTTP cache layer themselves — second request returns 304 if unchanged, saving bandwidth. Standard kit when CI pulls shared assets.</> }, code: <code>{p('$')} {f('curl')} {p('--etag-save')} stats.etag \{'\n'}    {p('--etag-compare')} stats.etag \{'\n'}    {p('-o')} stats.json \{'\n'}    https://api.cuberoot.me/v1/wca/stats.json</code> },
    { tag: 'I', zh: { title: <>--resolve 绕 DNS</>, desc: <><code>--resolve host:port:ip</code> 单次请求覆盖 DNS, 调试 nginx vhost / 验证新 IP 切流 / 排查 CDN 缓存非常顺手。<code>/etc/hosts</code> 改完忘了改回去那种坑直接避开。</> }, en: { title: <>--resolve overrides DNS</>, desc: <><code>--resolve host:port:ip</code> overrides DNS for one request — ideal for debugging an nginx vhost, validating a new IP cutover, or chasing CDN cache. Avoids the "I forgot to revert /etc/hosts" trap.</> }, code: <code>{p('$')} {f('curl')} {p('--resolve')} api.cuberoot.me:443:127.0.0.1 \{'\n'}    https://api.cuberoot.me/v1/health{'\n'}{c('# hits local Hono on :3001 reverse-proxied')}</code> },
  ],
  whyCards: [
    { icon: '⇄', zh: { title: <>无处不在 = 默认假设</>, desc: <>写脚本 / 写文档 / 写 SDK / 写 firmware 时, 默认能假设目标系统有 curl —— 200 亿设备 / 110 OS / 28 CPU 架构。这是别的 HTTP 工具都没有的优势。</> }, en: { title: <>Ubiquity is the killer feature</>, desc: <>Writing a script, a doc, an SDK, or firmware — you can assume the target machine already has curl. 20 B devices / 110 OSes / 28 CPU architectures. No other HTTP tool comes close.</> }, code: <>{c('# README example, anywhere on Earth')}{'\n'}{f('curl')} {p('-fsSL')} https://get.example.com {p('|')} bash</> },
    { icon: '⫶', zh: { title: <>一个 maintainer 三十年</>, desc: <>Daniel Stenberg 1996 接手, 2019 在 wolfSSL 拿全职 offer 后到今天还是同一个人。这种"长跨度可信供给"是别的项目极少能给的承诺。</> }, en: { title: <>One maintainer for thirty years</>, desc: <>Daniel Stenberg picked up curl in 1996, went full-time at wolfSSL in 2019, and is still the same person today. Few open-source projects can credibly promise this kind of long-horizon delivery.</> }, code: <>{c('// every release notes file:')}{'\n'}Contributors: 1100+, Releases: 260+, Years: 29</> },
    { icon: '⤳', zh: { title: <>libcurl 是几乎所有语言 HTTP 的下游</>, desc: <>PHP cURL / Python pycurl / Node node-libcurl / Ruby Typhoeus / Rust curl-rust / Go cgo wrapper / R RCurl / Lua lcurl / R curl 包 / Tcl TclCurl, 写完 libcurl 就同时支援所有这些。</> }, en: { title: <>libcurl: downstream of nearly every language</>, desc: <>PHP cURL, Python pycurl, Node node-libcurl, Ruby Typhoeus, Rust curl-rust, Go cgo wrappers, R curl, Lua lcurl, Tcl TclCurl — fix something in libcurl and you fix it everywhere at once.</> }, code: <>{c('# Python:')}{'\n'}{k('import')} pycurl  {c('# libcurl under the hood')}{'\n'}{c('# Ruby:')}{'\n'}{k('require')} {s("'typhoeus'")}  {c('# libcurl under the hood')}</> },
    { icon: '⌬', zh: { title: <>协议覆盖广到离谱</>, desc: <>HTTP 系列 / FTP 系列 / SMTP 收发邮件 / IMAP 读邮件 / LDAP 查目录 / MQTT 接 IoT / RTSP 收视频 / WebSocket / DICT / TELNET / FILE / GOPHER。28+ 协议, 同一组 flag 思路, 学一次走天下。</> }, en: { title: <>Absurd protocol breadth</>, desc: <>HTTP family, FTP family, SMTP for sending mail, IMAP for reading, LDAP for directories, MQTT for IoT, RTSP for video, WebSocket, DICT, TELNET, FILE, GOPHER — 28+ protocols sharing one flag philosophy. Learn once, use everywhere.</> }, code: <>{f('curl')} mqtts://broker/topic{'\n'}{f('curl')} ldap://ds.example.com/dc=ex,dc=com{'\n'}{f('curl')} imaps://mail/INBOX</> },
    { icon: '⛯', zh: { title: <>安全响应透明</>, desc: <>curl 把每个 CVE 走全公开流程:预告 → embargo → 补丁 → 详细 disclosure (描述 / 利用难度 / 受影响版本 / 缓解方案), 在 curl.se/docs/security.html 全可查。"开源安全模范"。</> }, en: { title: <>Security response in the open</>, desc: <>Every curl CVE runs through full disclosure: pre-announce, embargo, patch, then detailed write-up (description, exploit difficulty, affected versions, mitigation) on curl.se/docs/security.html. A textbook open-source security process.</> }, code: <>{c('// see https://curl.se/docs/security.html')}{'\n'}{c('// 150+ CVEs, all documented')}</> },
    { icon: '⌗', zh: { title: <>30+ 年 ABI 稳定承诺</>, desc: <>libcurl 公开承诺 ABI 永远向后兼容, 2000 年写的 C 代码今天 link 新 libcurl 还跑得动。"开源 C 库长期可信"的样本。</> }, en: { title: <>30+ years of ABI stability</>, desc: <>libcurl publicly commits to permanent ABI backward compatibility — C code written in 2000 still links against today's libcurl and runs. A reference exhibit for "long-term trustworthy open-source C library."</> }, code: <>{c('// curl_easy_setopt() signature: unchanged since 2000')}</> },
    { icon: '⊙', zh: { title: <>嵌入式友好</>, desc: <>静态链接 2~3MB, 没动态分配热点, 没线程依赖, 给嵌入式设备 / 路由器 / 电视 / 汽车信息娱乐系统 / 智能手表都用得起。这就是 200 亿设备的物理基础。</> }, en: { title: <>Embedded-friendly</>, desc: <>2–3 MB statically linked, no hot allocator paths, no thread requirements — embedded devices, routers, TVs, automotive infotainment, smartwatches can all afford it. The physical foundation of those 20 billion installs.</> }, code: <>{c('// minimal build')}{'\n'}{f('./configure')} {p('--disable-shared')} {p('--without-ssl')}{'\n'}{c('// result: ~800KB binary')}</> },
    { icon: '↯', zh: { title: <>调试器 + 文档 + 健康探针 一身</>, desc: <>"看看这个 API 返啥" / "vhost 是不是 reload 了" / "cert 还几天过期" / "DNS 切了没" / "新 LB 健康吗" 几乎所有运维场景都能在一行 curl 内完成。<code>-v</code> 一开等于内置 wireshark。</> }, en: { title: <>Debugger, doc, and health probe in one</>, desc: <>"What does this API return" / "did the vhost reload" / "how many days until cert expiry" / "did DNS cut over" / "is the new LB healthy" — almost every ops question collapses to one line of curl. Flip on <code>-v</code> and you have a built-in mini-Wireshark.</> }, code: <>{f('curl')} {p('-vI')} https://api.cuberoot.me{'\n'}{c('// HTTP version, TLS, headers, redirect chain — all printed')}</> },
  ],
  adopters: [
    { name: 'NASA Mars rovers', href: 'https://www.nasa.gov', highlight: true, zhNote: 'curl 进了 Curiosity / Perseverance 火星车软件栈, Daniel 多次公开提及', enNote: 'curl ships in Curiosity / Perseverance rover software stacks; cited publicly by Daniel' },
    { name: 'Windows 10/11', href: 'https://learn.microsoft.com', highlight: true, zhNote: '2017 起 Windows 默认带 curl.exe, 替换老的 curl alias 给 Invoke-WebRequest', enNote: 'Windows has shipped curl.exe by default since 2017, replacing the old curl alias for Invoke-WebRequest' },
    { name: 'macOS', href: 'https://www.apple.com/macos', zhNote: 'Apple 默认装 curl + libcurl, 从 OS X 10.1 (2001) 至今', enNote: 'Apple has shipped curl + libcurl by default since OS X 10.1 (2001)' },
    { name: 'Linux 全发行版', zhNote: 'Debian / Ubuntu / Fedora / Arch / Alpine / OpenWrt 全部默认或一键 apt install', enNote: 'Debian / Ubuntu / Fedora / Arch / Alpine / OpenWrt all default or one apt install away' },
    { name: 'Tesla / 汽车信息娱乐', zhNote: 'Tesla / 大众 / 福特 / 保时捷 等汽车信息娱乐系统嵌入 libcurl 做 OTA + telemetry', enNote: 'Tesla / VW / Ford / Porsche infotainment systems embed libcurl for OTA + telemetry' },
    { name: 'PHP', href: 'https://www.php.net/manual/en/book.curl.php', zhNote: '内置 cURL 扩展, PHP 生态默认 HTTP 客户端', enNote: 'Built-in cURL extension, the default HTTP client in PHP land' },
    { name: 'git', href: 'https://git-scm.com', zhNote: 'git HTTPS transport 默认走 libcurl', enNote: 'git\'s HTTPS transport runs on libcurl' },
    { name: 'YouTube TV / Netflix / Spotify 客户端', zhNote: '智能电视 / 机顶盒 / 流媒体 client 大量内嵌 libcurl', enNote: 'Smart TVs, set-top boxes, and streaming clients widely embed libcurl' },
    { name: 'Game consoles', zhNote: 'PlayStation / Xbox / Switch SDK 内置 libcurl', enNote: 'PlayStation / Xbox / Switch SDKs embed libcurl' },
    { name: 'Docker / Kubernetes / Helm', zhNote: '容器生态 pull image / fetch chart 默认走 libcurl 或 fork', enNote: 'Container ecosystem image pulls and chart fetches use libcurl or its forks' },
    { name: 'GitHub Actions', href: 'https://docs.github.com/actions', zhNote: '官方 ubuntu-latest / windows-latest / macos-latest runner 默认装 curl', enNote: 'Official ubuntu-latest / windows-latest / macos-latest runners ship curl by default' },
    { name: 'Anthropic Claude API examples', href: 'https://docs.anthropic.com', zhNote: '官方文档默认 curl 示例, AI agent 也用 curl 调外部 API', enNote: 'Official docs use curl as the default request example; AI agents reach for curl too' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本仓库 — API 调试 / nginx 验证 / GitHub Actions 健康探针 全用 curl', enNote: 'This repo — API debugging, nginx verification, GitHub Actions health probes all run on curl' },
  ],
  outlook: [
    { tag: <>HOT · 2026-04</>, hot: true, big: true, zh: { title: <>8.20.0 + 30 周年</>, body: <><p>2026-04-29 发出的 8.20.0 是 curl 30 周年(2026-11)前最重要的一个 release。HTTP/3 在主流平台全部 stable, hyper backend 接近 production-ready, wcurl 这种 "对人友好" 的 wrapper 在 Debian / Ubuntu / Fedora 默认包入。</p><p>2026-11-11 是 curl 满 30 周年, 计划公开"30 年技术回顾 + 路线图"长文。Daniel 在 wolfSSL 全职年限来到第 8 年, 没有交接计划 —— 这是 OSS 圈罕见的"个人长期供给"承诺。</p></> }, en: { title: <>8.20.0 + 30 years</>, body: <><p>8.20.0, shipped on 2026-04-29, is the most consequential release before curl's 30th anniversary (2026-11). HTTP/3 is stable across mainstream platforms; the hyper backend is approaching production-ready; the friendly wcurl wrapper now ships by default in Debian / Ubuntu / Fedora.</p><p>2026-11-11 marks 30 years of curl; Daniel has signalled a "30 years tech retrospective + roadmap" long-form post. He's now in year 8 of full-time work at wolfSSL with no handover plan — a rare long-term individual commitment in OSS.</p></> } },
    { tag: <>HOT</>, hot: true, zh: { title: <>Rust hyper backend 出实验</>, body: <><p>从 7.75 (2021-02) 起 hyper 作为 Rust HTTP/1.1 + HTTP/2 backend 进 curl, 五年磨合后在 8.x 末期接近 production-ready。意义不在于"libcurl 改 Rust", 而在于"curl 用户终于有一条内存安全的协议解析路径", 嵌入式产品长期 CVE 风险下降一个量级。</p></> }, en: { title: <>Rust hyper backend leaves experimental</>, body: <><p>hyper joined curl as a Rust HTTP/1.1 + HTTP/2 backend in 7.75 (2021-02); five years of bedding-in put it near production-ready by late 8.x. The point isn't "rewriting libcurl in Rust" — it's that curl users finally get a memory-safe protocol-parsing path, lowering long-term embedded CVE exposure by an order of magnitude.</p></> } },
    { tag: <>HTTP/3</>, zh: { title: <>HTTP/3 全面默认化</>, body: <><p>HTTP/3 在 curl 2024 起在主流平台全部 stable, 2026 起预计在常规 build 中默认 enabled (不再需要 <code>--http3</code> 显式 opt-in)。curl 通过 ngtcp2 / quiche 两个 backend 抽象 QUIC, 让上游 QUIC 库自由竞争, 这种"协议抽象 + 多 backend"模式被 ngrok / quic-interop 测试套件广泛参考。</p></> }, en: { title: <>HTTP/3 becomes default-on</>, body: <><p>HTTP/3 reached stable across mainstream platforms in 2024 and is expected to be default-enabled in regular builds from 2026 (no more explicit <code>--http3</code> opt-in). curl abstracts QUIC across ngtcp2 and quiche, letting upstream QUIC libraries compete — a "protocol abstraction + multi-backend" model now widely cited by ngrok and the quic-interop test suite.</p></> } },
    { tag: 'WCURL', zh: { title: <>wcurl — 给人用的 curl</>, body: <><p>2023 Sam Hartman 发起的 wcurl, 是 curl 的"友好 wrapper" —— 默认 follow redirect, 默认进度条, 默认自动选输出文件名, 不开 <code>-fsSL</code> 这种长 flag 链。2024 起 Debian / Ubuntu / Fedora 默认包入, "<code>curl URL</code> 直接下下来"终于不需要记 flag 了。</p></> }, en: { title: <>wcurl — curl for humans</>, body: <><p>wcurl, started by Sam Hartman in 2023, is curl's "friendly wrapper" — follows redirects, shows a progress bar, picks a sensible output filename, no <code>-fsSL</code> flag chain required. Default in Debian / Ubuntu / Fedora as of 2024, so "<code>curl URL</code> and it just downloads" no longer needs flag memorisation.</p></> } },
    { tag: 'AI', zh: { title: <>AI agent 时代仍是 first-class HTTP tool</>, body: <><p>Claude Code / Cursor / Devin 等 AI agent 调外部 API 时默认生成 curl 命令 —— 不是因为它"现代", 是因为它"无处不在 + 文档密集 + 可解释性极高"。这种"AI agent 友好"的属性也是 curl 三十周年继续被选的理由。</p></> }, en: { title: <>Still first-class in the AI agent era</>, body: <><p>AI agents like Claude Code, Cursor, and Devin generate curl commands by default when calling external APIs — not because curl is modern, but because it's ubiquitous, densely documented, and highly explainable. This "AI-agent-friendly" property is another reason curl keeps being chosen entering its fourth decade.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本仓库 <code>RuiminYan/cuberoot.me</code> 调 API 的默认动作就是 curl。Hono server (<code>core/packages/server</code>) 加了一条新路由 (比如 <code>/v1/wca/persons/search</code>), 第一个验证手段不是写测试, 是 <code>curl 'https://api.cuberoot.me/v1/wca/persons/search?q=...'</code> 看响应 JSON 结构。本地 dev 同理 —— Vite proxy 把 <code>/api</code> 转到本地 Hono 时, 用 <code>curl http://127.0.0.1:5173/api/...</code> 一行验证 proxy 通没通。</p>
        <p>nginx vhost (<code>ops/nginx/www.cuberoot.me.conf</code>) 改完, <code>deploy_nginx</code> workflow 在服务器上 <code>nginx -t</code> + reload + 失败 .bak 回滚 — 整个流程的最后一步是 <code>curl -v https://www.cuberoot.me/health</code> 拿状态码确认 reload 真的生效。COOP/COEP header 对 <code>/scramble/(solver|analyzer)</code> 加了 nginx map 控制, 验证手段也是 <code>curl -I</code> 看 <code>Cross-Origin-Opener-Policy</code> 这一行存不存在 — UI 验证慢 5 倍, curl 5 秒搞定。</p>
        <p>GitHub Actions 部署完会跑一个 <code>curl --max-time 10 -fsS https://api.cuberoot.me/health</code> 探活, 任何非 200 都 fail the run, 直接通知。SSL cert 是不是真续上, <code>curl --cert-status -vI</code> 一行看 OCSP 响应 + Expire 时间。同款套路也用在 nginx proxy_cache (<code>/v1/wca/*</code> 24h cache) 排查上 — 加 <code>-H "Cache-Purge: ..."</code> 触发 purge, 加 <code>-D -</code> 看 <code>X-Cache-Status</code> 头确认命中。</p>
        <p>libcurl 间接的下游也都用到 — pnpm 拉包靠它, GitHub Actions runner 默认 curl, AI agent (Claude Code) 给的"测试这个 endpoint"命令都是 curl, 文档里的 API 示例也用 curl。"全栈的 HTTP 默认动词" 这条标语在本仓库被无数次验证。</p>
      </>
    ),
    en: (
      <>
        <p>For this repo <code>RuiminYan/cuberoot.me</code>, hitting an API begins with curl. Add a new Hono route in <code>core/packages/server</code> (say <code>/v1/wca/persons/search</code>) and the first check isn't a test — it's <code>curl 'https://api.cuberoot.me/v1/wca/persons/search?q=...'</code> to inspect the response JSON. Same locally: with Vite proxying <code>/api</code> to local Hono, <code>curl http://127.0.0.1:5173/api/...</code> verifies the proxy in one line.</p>
        <p>Edit the nginx vhost in <code>ops/nginx/www.cuberoot.me.conf</code> and the <code>deploy_nginx</code> workflow runs <code>nginx -t</code> + reload + .bak rollback on failure — the very last step is <code>curl -v https://www.cuberoot.me/health</code> to confirm the reload actually took effect. The COOP/COEP headers for <code>/scramble/(solver|analyzer)</code> are gated by an nginx map; verifying is <code>curl -I</code> and grepping for <code>Cross-Origin-Opener-Policy</code> — five seconds instead of a five-minute UI round trip.</p>
        <p>Post-deploy, GitHub Actions runs <code>curl --max-time 10 -fsS https://api.cuberoot.me/health</code> — any non-200 fails the run and notifies. Did the SSL cert actually renew? <code>curl --cert-status -vI</code> shows the OCSP response and the expiry line. Same playbook for debugging the nginx proxy_cache (24h cache on <code>/v1/wca/*</code>): add <code>-H "Cache-Purge: ..."</code> to trigger purge, <code>-D -</code> to dump headers and confirm the <code>X-Cache-Status</code>.</p>
        <p>The indirect users matter too — pnpm fetches via libcurl, GitHub Actions runners default to curl, AI agents (Claude Code) emit curl when asked to "test this endpoint," and API examples in the docs are curl. "The default HTTP verb of the full stack" is a tagline this repo confirms over and over.</p>
      </>
    ),
  },
  links: [
    { label: 'curl.se', href: 'https://curl.se' },
    { label: 'GitHub · curl/curl', href: 'https://github.com/curl/curl' },
    { label: 'curl 8.20.0 release', href: 'https://curl.se/changes.html' },
    { label: 'Daniel Stenberg blog (daniel.haxx.se)', href: 'https://daniel.haxx.se/blog/' },
    { label: 'curl security CVE log', href: 'https://curl.se/docs/security.html' },
    { label: 'Pro libcurl tutorial', href: 'https://curl.se/libcurl/c/libcurl-tutorial.html' },
  ],
};

export default CURL;
