import type { StackTool } from '../_lib/stack_tool_types';
import { v, s, n, f, p, c } from '../_lib/stack_tool_types';

// ─── GitHub Actions ─────────────────────────────────────────────────────────

export const GITHUB_ACTIONS: StackTool = {
  slug: 'github-actions',
  name: 'GitHub Actions',
  version: 'ubuntu-24.04',
  since: '2018-10',
  group: 'dev',
  accent: '#2088FF',
  bright: '#6FB8FF',
  glyph: '▶',
  floats: ['workflow', 'job', 'step', 'runner', 'matrix', 'uses:', 'with:', 'env:', 'secrets', 'OIDC', 'reusable', 'composite'],
  zh: {
    tagline: 'YAML 驱动的 CI/CD + 通用编排',
    role: '本仓库 9 条 workflow 的执行引擎。每个 PR 跑测试,每次 push main 触发 build 和 deploy。',
    heroSub: <>2018 年 10 月 GitHub Universe 上首次亮相, 2019 年 11 月 13 日 GA。把 "CI/CD" 从一个独立产品 (Travis / CircleCI / Jenkins) 拉回 git 仓库内 —— workflow 是 <code>.github/workflows/*.yml</code> 一个普通文件, 跟代码一起 review、一起 commit、一起回滚。八年下来已成 OSS 项目的默认 CI。</>,
    whatDesc: <>GitHub Actions 是一个 <strong>事件驱动的工作流编排平台</strong>, 跑在 GitHub 自家托管的 runner 上 (也支持 self-hosted)。它把仓库事件 (push / PR / issue / schedule / release) 映射成 YAML 描述的 workflow, workflow 拆成 job, job 拆成 step。它不只做 CI/CD —— 抓数据、跑 cron、发通知、自动 label / triage 全在它的射程内。</>,
    historyDesc: <>从 2018-10 在 Universe 上以 HCL 语法 beta 亮相, 到 2019-11 切到 YAML 并 GA, 再到 2021 的 OIDC + reusable workflows、2024 的 arm64 公测、2026 年初 arm64 私库 GA 和定价下调,八年间它从一个 "GitHub 内部把 LGTM 自动化" 的边路实验, 变成 OSS 默认 CI。Marketplace 上 25k+ public action 是这条护城河最深的地方。</>,
    conceptsTitle: 'Workflow + Job + Step + Runner',
    conceptsDesc: <>底层模型只四层:<strong>workflow</strong> (一个 yml 文件, 由事件触发) → <strong>job</strong> (跑在一个 runner 上, 多个 job 默认并行) → <strong>step</strong> (一条 shell 或一个 action) → <strong>action</strong> (可复用的封装单元)。其余 (matrix / environments / reusable / composite) 都是这四层的组合。</>,
    whyDesc: <>2026 年还选 Actions, 不是因为它"最快"或"最便宜",而是因为它<strong>跟 repo 同根</strong>:secret / permission / branch protection / OIDC 全部走 GitHub 一套权限模型, 没有第二份配置要同步, 没有第二份账号要管。剩余几条 (Marketplace / 免费额度 / AI 工具默认目标) 是网络效应。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>问"谁用 Actions"基本等于问"谁在 GitHub 上活跃"。Node.js / React / Rust / Linux distros 的发行流水线、大量 SaaS 的 build / deploy、Anthropic Claude Code 的 release 自动化、本站 9 条 workflow 全在 Actions 上跑。Travis CI 和 CircleCI 在 OSS 圈 2020 后被它吃掉绝大部分份额。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>arm64 runner 2026-01 在私库 GA 并大幅降价, 给 ARM 原生 build (容器、Rust crate、Apple Silicon 对齐) 拉低成本;Copilot agentic workflow 把 CI runner 直接接进 LLM 上下文, "PR 自动修红"被纳入路线;Reusable workflow + composite action + Marketplace 让大企业内部 platform 团队的 boilerplate 复用率显著上升。</>,
  },
  en: {
    tagline: 'YAML-driven CI/CD + general-purpose orchestration',
    role: 'The execution engine behind this repo\'s 9 workflows. Every PR runs tests, every push to main builds and deploys.',
    heroSub: <>Unveiled at GitHub Universe in October 2018 and GA on November 13, 2019. It pulled "CI/CD" out of dedicated products (Travis / CircleCI / Jenkins) and back into the git repo — a workflow is just a file at <code>.github/workflows/*.yml</code>, reviewed, committed, and rolled back alongside the code. Eight years later it is the default CI for OSS.</>,
    whatDesc: <>GitHub Actions is an <strong>event-driven workflow orchestration platform</strong> running on GitHub-hosted runners (and self-hosted ones). Repo events (push / PR / issue / schedule / release) map to YAML workflows; workflows decompose into jobs; jobs into steps. It does more than CI/CD — scraping data, running cron, sending notifications, auto-labeling, and triage all sit in its envelope.</>,
    historyDesc: <>From the October 2018 Universe beta (then HCL syntax) to the November 2019 YAML rewrite and GA, then OIDC + reusable workflows in 2021, arm64 public preview in 2024, and arm64 private GA + a pricing cut in early 2026. Across eight years it went from an internal "automate LGTM" experiment to the OSS default CI. The 25k+ public actions on the Marketplace are its deepest moat.</>,
    conceptsTitle: 'Workflow + Job + Step + Runner',
    conceptsDesc: <>The model is four layers: <strong>workflow</strong> (one yml file, triggered by an event) → <strong>job</strong> (runs on one runner; multiple jobs parallelize by default) → <strong>step</strong> (a shell command or an action) → <strong>action</strong> (a reusable unit). Everything else (matrix, environments, reusable, composite) is a composition.</>,
    whyDesc: <>Picking Actions in 2026 isn\'t because it\'s "the fastest" or "the cheapest" — it\'s because it shares a root with the repo: secrets, permissions, branch protection, OIDC all use GitHub\'s one auth model. No second configuration to sync, no second account to admin. The rest (Marketplace / free tier / AI tool defaults) is network effect.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Asking "who uses Actions" is roughly asking "who is active on GitHub." Node.js / React / Rust / Linux distro release pipelines, countless SaaS build / deploy chains, Anthropic Claude Code release automation, and this site\'s 9 workflows all run on it. Travis CI and CircleCI lost most of their OSS share after 2020.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>arm64 runners reached private-repo GA in January 2026 with a steep price cut, lowering the cost of native ARM builds (containers, Rust crates, Apple-Silicon alignment); Copilot agentic workflows wire CI runners into LLM context for "auto-fix-the-red-PR" loops; reusable workflows + composite actions + Marketplace let enterprise platform teams reuse boilerplate at meaningful scale.</>,
  },
  heroStats: [
    { num: '9', zh: <>本仓库 workflow 数 <em>test / deploy / stats / 健康检查</em></>, en: <>workflows in this repo <em>test / deploy / stats / healthcheck</em></>
    },
    { num: '7', unit: 'y', zh: <>2018-10 Universe 首发以来 <em>OSS 默认 CI</em></>, en: <>since Universe 2018 <em>now the OSS default CI</em></>
    },
    { num: '25', unit: 'k+', zh: <>Marketplace 公开 action 数 <em>生态护城河</em></>, en: <>public actions on Marketplace <em>the ecosystem moat</em></>
    },
    { num: '2000', unit: 'min', zh: <>免费私库月配额 <em>公开仓库无限</em></>, en: <>free monthly minutes for private repos <em>unlimited on public</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>GitHub Actions 是 GitHub 在 Microsoft 收购 (2018-06) 后, 同年 10 月 Universe 大会上推出的工作流自动化平台。技术底盘复用 Azure Pipelines 的 runner 基础设施 —— Microsoft 三亿美元/年级别的 CI 投入, 一夜之间变成 GitHub 用户的免费工具。第一版用 HCL 语法 (跟 Terraform 同套), beta 跑了一年, 听完用户反馈在 2019-11-13 GA 时全切到 YAML, 这次"敢换语法"让后续表达力更强的特性 (matrix / reusable / composite) 能干净落地。</p>
        <p>它跟 Travis CI / CircleCI / Jenkins 的根本差异是<strong>跟 repo 同根</strong>:secret / permission / branch protection / OIDC 全走 GitHub 一套权限模型, workflow 文件跟代码一起 review、一起 commit、一起回滚。"build 配置藏在 SaaS 仪表板里, 没人记得改过" 这种历史 CI 顽疾被结构性解决。OIDC (2021) 让 workflow 用短期 token 直连云资源, secret 数量大幅下降。</p>
        <p>八年下来生态护城河深得吓人:Marketplace 上 25000+ 公开 action, 想干啥几乎都能 <code>uses:</code> 引用一个现成的;免费额度对公开仓库不限分钟, 私库每月 2000 分钟。2024 ARM Linux runner 公测、Apple Silicon macOS runner 上线、2026-01-29 ARM 私库 GA + 全面降价 (-39%) 给原生 ARM 编译拉低成本一档。Copilot 系列 agentic workflow 在 2026 把 LLM 直接接进 CI 上下文 —— "PR 红了自动修" 从演示变成实际工作流。</p>
      </>
    ),
    en: (
      <>
        <p>GitHub Actions was unveiled at the October 2018 Universe conference, the year Microsoft acquired GitHub. The technical foundation reused Azure Pipelines runner infrastructure — Microsoft\'s 300M-USD/year-class CI investment became free to GitHub users overnight. The first version used HCL syntax (same as Terraform), ran a one-year beta, and after listening to users was rewritten in YAML for GA on November 13, 2019. That willingness to switch syntaxes let later, more expressive features (matrix, reusable, composite) land cleanly.</p>
        <p>The fundamental difference from Travis CI / CircleCI / Jenkins is that it <strong>shares a root with the repo</strong>: secrets, permissions, branch protection, and OIDC all use GitHub\'s one auth model. Workflow files are reviewed, committed, and rolled back with the code. The classic CI ailment — "build config is hidden in a SaaS dashboard nobody remembers editing" — is structurally fixed. OIDC (2021) lets workflows hit cloud resources with short-lived tokens, dramatically reducing the number of stored secrets.</p>
        <p>The ecosystem moat is now intimidating: 25000+ public actions on the Marketplace, almost any task is one <code>uses:</code> away; the free tier is unlimited minutes for public repos and 2000 minutes/month for private. ARM Linux runners (2024 public preview), Apple Silicon macOS runners, and the January 2026 ARM private-repo GA paired with a sweeping 39% price cut materially lower the cost of native ARM builds. Copilot agentic workflows in 2026 wire LLMs directly into CI context — "PR turned red, auto-fix it" moves from demo to actual workflow.</p>
      </>
    ),
  },
  history: [
    { year: '2018·06', zh: { title: <>Microsoft 收购 GitHub</>, desc: <>75 亿美元收购完成。Azure Pipelines 团队成为 Actions 的技术底盘 — runner 基础设施直接复用, 没从零造轮子。</> }, en: { title: <>Microsoft acquires GitHub</>, desc: <>$7.5B acquisition closes. The Azure Pipelines team becomes the technical foundation for Actions — runner infra is reused directly, no greenfield build.</> } },
    { year: '2018·10', zh: { title: <>Universe 上 beta 亮相</>, desc: <>10 月 16 日 GitHub Universe 公开 Actions beta, 首版用 HCL 语法 (跟 Terraform 同套)。"workflow as code" 第一次进 git 仓库, 业界震动。</> }, en: { title: <>Beta debut at Universe</>, desc: <>On October 16 at GitHub Universe, Actions debuts in beta with HCL syntax (same as Terraform). "Workflow as code" lands inside the repo for the first time — the industry takes notice.</> } },
    { year: '2019·08', zh: { title: <>YAML 切换 + public beta</>, desc: <>听完一年用户反馈, HCL 被弃, 重写为 YAML。matrix / strategy / job dependency 等表达力强的语义这次结构性进 schema。</> }, en: { title: <>YAML rewrite + public beta</>, desc: <>After one year of feedback, HCL is dropped and the schema is rewritten in YAML. matrix / strategy / job dependencies enter the schema structurally.</> } },
    { year: '2019·11', zh: { title: <>GA — Universe 2019</>, desc: <>11 月 13 日 GA。同时上线 GitHub Packages, "build + 制品仓库 + 发布" 链路在一个平台闭环。Travis / CircleCI 的 OSS 份额从这天起开始下滑。</> }, en: { title: <>GA — Universe 2019</>, desc: <>GA on November 13. GitHub Packages launches the same day — build + artifact registry + release closes inside one platform. Travis / CircleCI OSS share starts declining from this day.</> } },
    { year: '2020·07', zh: { title: <>self-hosted runner GA</>, desc: <>self-hosted runner 标签和 group 机制完成。企业能把 Actions 跑在自己机房, 同一份 YAML, 不同执行环境。</> }, en: { title: <>Self-hosted runners GA</>, desc: <>Self-hosted runner labels and groups stabilize. Enterprises can run Actions on their own hardware — same YAML, different execution environment.</> } },
    { year: '2021·10', zh: { title: <>Reusable workflows + OIDC</>, desc: <>workflow 之间能 <code>uses:</code> 互相 import, 解决 boilerplate 复制粘贴。同期 OIDC 让 workflow 用短期 token 直连云厂商, 长期 access key 大幅减少。</> }, en: { title: <>Reusable workflows + OIDC</>, desc: <>Workflows can <code>uses:</code> each other, ending boilerplate copy-paste. OIDC ships in parallel — workflows hit cloud providers with short-lived tokens, slashing long-lived access keys.</> } },
    { year: '2022·08', zh: { title: <>Composite action + 大型 runner</>, desc: <>Composite action 让一组 step 打包成单个可复用单元。Larger runners (8-core / 16-core / GPU) 进市场, 重型 build (Chromium / 大单仓 monorepo) 在 GitHub-hosted runner 上变可行。</> }, en: { title: <>Composite actions + larger runners</>, desc: <>Composite actions bundle multiple steps into one reusable unit. Larger runners (8-core / 16-core / GPU) ship — heavy builds (Chromium, big monorepos) become viable on GitHub-hosted runners.</> } },
    { year: '2023·01', zh: { title: <>macOS Apple Silicon runner</>, desc: <>M1 / M2 mac runner 上线 (付费层), iOS app build 不再走 Intel 模拟, 速度提升 ~3x。Xcode + arm64 native 链路完整。</> }, en: { title: <>macOS Apple Silicon runners</>, desc: <>M1 / M2 mac runners ship on paid tiers. iOS app builds drop Intel emulation, ~3x speedup. Xcode + arm64 native path is now complete.</> } },
    { year: '2024·06', zh: { title: <>ubuntu-24.04 + arm64 公测</>, desc: <>Ubuntu 24.04 LTS 镜像默认 (Node 22 / GCC 14 / Python 3.12)。Linux arm64 runner 进入公测, 公开仓库免费, 给容器 multi-arch build 拉低成本。</> }, en: { title: <>ubuntu-24.04 + arm64 public preview</>, desc: <>Ubuntu 24.04 LTS images become default (Node 22 / GCC 14 / Python 3.12). Linux arm64 runners enter public preview, free on public repos — lowering the cost of multi-arch container builds.</> } },
    { year: '2025·01', zh: { title: <>arm64 公开仓库免费</>, desc: <>1 月 16 日 Linux arm64 runner 在公开仓库免费使用 (public preview)。OSS 项目第一次能廉价跑 ARM-native CI, Rust / Go / 容器生态先吃到红利。</> }, en: { title: <>arm64 free on public repos</>, desc: <>January 16: Linux arm64 runners are free on public repos (public preview). OSS projects can finally run ARM-native CI cheaply; Rust / Go / container ecosystems benefit first.</> } },
    { year: '2025·11', zh: { title: <>agentic workflow + Copilot</>, desc: <>Copilot Workspace 把 LLM 接进 workflow 上下文。<code>workflow_run</code> 失败时 agent 自动拉日志、定位、提 fix PR 的链路 demo 落地, 早期采用者验证可用。</> }, en: { title: <>Agentic workflows + Copilot</>, desc: <>Copilot Workspace wires LLMs into workflow context. The "<code>workflow_run</code> failed → agent pulls logs, locates the issue, opens a fix PR" loop demos publicly and is validated by early adopters.</> } },
    { year: '2026·01', highlight: true, zh: { title: <>arm64 私库 GA + 全面降价</>, desc: <>1 月 29 日 arm64 standard runner 在私库 GA。同期定价整体下调最高 39%, 不同 SKU 不同幅度。"用 ARM 跑 CI" 从公开 OSS 福利变成普适默认。</> }, en: { title: <>arm64 private GA + sweeping price cut</>, desc: <>January 29: arm64 standard runners reach GA on private repos. Pricing drops by up to 39% across SKUs the same month. "Run CI on ARM" goes from public-OSS-only perk to a default option for everyone.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>ubuntu-24.04 / 当前镜像</>, desc: <>本仓库 9 条 workflow 全部用 <code>ubuntu-latest</code> (= ubuntu-24.04)。Node 22 / pnpm 11 / rsync 默认就装好, install 步骤极短。GitHub-hosted runner 持续保持周更。</> }, en: { title: <>ubuntu-24.04 / current image</>, desc: <>All 9 workflows in this repo use <code>ubuntu-latest</code> (= ubuntu-24.04). Node 22 / pnpm 11 / rsync ship in the default image — install steps stay short. GitHub-hosted runner images keep updating weekly.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>workflow 文件</>, desc: <><code>.github/workflows/*.yml</code> 一个文件 = 一条 workflow。事件触发, 跟代码同 review, 同 commit, 同 rollback。</> }, en: { title: <>Workflow file</>, desc: <>One file at <code>.github/workflows/*.yml</code> = one workflow. Event-triggered, reviewed with code, committed with code, rolled back with code.</> }, code: <code>{c('# .github/workflows/test.yml')}{'\n'}{p('name')}: {v('Test')}{'\n'}{p('on')}:{'\n'}  {p('pull_request')}: {n('null')}{'\n'}  {p('push')}: {'{ '}{p('branches')}: [{v('main')}] {'}'}</code> },
    { tag: 'B', zh: { title: <>事件 (events)</>, desc: <><code>push</code> / <code>pull_request</code> / <code>schedule</code> (cron) / <code>workflow_dispatch</code> (手动) / <code>release</code> / <code>issue_comment</code> 等。<code>paths:</code> 过滤让 monorepo 只跑相关 job。</> }, en: { title: <>Events</>, desc: <><code>push</code> / <code>pull_request</code> / <code>schedule</code> (cron) / <code>workflow_dispatch</code> (manual) / <code>release</code> / <code>issue_comment</code>, etc. <code>paths:</code> filters keep monorepos lean — only relevant jobs run.</> }, code: <code>{p('on')}:{'\n'}  {p('push')}:{'\n'}    {p('branches')}: [{v('main')}]{'\n'}    {p('paths')}: [{s("'core/**'")}]{'\n'}  {p('schedule')}:{'\n'}    - {p('cron')}: {s("'0 20 * * 0'")}  {c('# Sundays 20:00 UTC')}</code> },
    { tag: 'C', zh: { title: <>job + runner</>, desc: <>一个 job 跑在一个 runner 上。多个 job 默认并行, <code>needs:</code> 声明依赖。Runner 类型:<code>ubuntu-latest</code> / <code>windows-latest</code> / <code>macos-latest</code> / self-hosted。</> }, en: { title: <>Job + runner</>, desc: <>One job runs on one runner. Multiple jobs run in parallel by default; <code>needs:</code> declares dependencies. Runner types: <code>ubuntu-latest</code> / <code>windows-latest</code> / <code>macos-latest</code> / self-hosted.</> }, code: <code>{p('jobs')}:{'\n'}  {p('test')}:{'\n'}    {p('runs-on')}: {v('ubuntu-latest')}{'\n'}    {p('timeout-minutes')}: {n('10')}{'\n'}  {p('deploy')}:{'\n'}    {p('needs')}: {v('test')}{'\n'}    {p('runs-on')}: {v('ubuntu-latest')}</code> },
    { tag: 'D', zh: { title: <>step + uses + run</>, desc: <>每个 step 要么 <code>uses:</code> 引用一个 action, 要么 <code>run:</code> 跑一条 shell。<code>actions/checkout</code> / <code>actions/setup-node</code> 是几乎每个 workflow 的开头两步。</> }, en: { title: <>Step + uses + run</>, desc: <>Each step either <code>uses:</code> an action or <code>run:</code>s a shell command. <code>actions/checkout</code> and <code>actions/setup-node</code> are the first two steps of almost every workflow.</> }, code: <code>{p('steps')}:{'\n'}  - {p('uses')}: {v('actions/checkout@v4')}{'\n'}  - {p('uses')}: {v('actions/setup-node@v4')}{'\n'}    {p('with')}: {'{ '}{p('node-version')}: {s("'22'")} {'}'}{'\n'}  - {p('run')}: pnpm install {p('--frozen-lockfile')}</code> },
    { tag: 'E', zh: { title: <>matrix build</>, desc: <>用 <code>strategy.matrix</code> 让一份 job 描述展开成 N 个并行 job (跨 Node 版本 / OS / 架构)。库类项目最常用, 一次 PR 在 9-12 个组合上跑测试。</> }, en: { title: <>Matrix builds</>, desc: <>Use <code>strategy.matrix</code> to expand one job spec into N parallel jobs (across Node versions / OS / architectures). Libraries lean on this — one PR runs tests on 9-12 combinations.</> }, code: <code>{p('strategy')}:{'\n'}  {p('matrix')}:{'\n'}    {p('node')}: [{n('20')}, {n('22')}]{'\n'}    {p('os')}: [{v('ubuntu-latest')}, {v('macos-latest')}]{'\n'}{c('# 4 jobs in parallel')}</code> },
    { tag: 'F', zh: { title: <>secret + OIDC</>, desc: <>静态 secret 走 <code>secrets.NAME</code>, 长期 access key 模式。OIDC (2021) 让 workflow 用短期 JWT 换云资源 token, 没东西可泄。</> }, en: { title: <>Secrets + OIDC</>, desc: <>Static secrets via <code>secrets.NAME</code> — the long-lived access-key pattern. OIDC (2021) trades a short-lived JWT for cloud-resource tokens — nothing to leak long-term.</> }, code: <code>- {p('uses')}: {v('aws-actions/configure-aws-credentials@v4')}{'\n'}  {p('with')}:{'\n'}    {p('role-to-assume')}: {v('arn:aws:iam::...')}{'\n'}    {c('# no static keys — OIDC trust')}</code> },
    { tag: 'G', zh: { title: <>reusable workflow</>, desc: <>一个 workflow 用 <code>workflow_call</code> 让其它 workflow <code>uses:</code> 进来。组织内部把 "build node app + 推制品" 提一份, 各 repo 引用, 改一处。</> }, en: { title: <>Reusable workflows</>, desc: <>A workflow declares <code>workflow_call</code> so others can <code>uses:</code> it. Org-internal "build node app + push artifact" lives in one place; consumer repos reference it; one change updates all.</> }, code: <code>{c('# in caller')}{'\n'}{p('jobs')}:{'\n'}  {p('build')}:{'\n'}    {p('uses')}: {v('myorg/workflows/.github/workflows/node-build.yml@v1')}{'\n'}    {p('with')}: {'{ '}{p('node-version')}: {s("'22'")} {'}'}</code> },
    { tag: 'H', zh: { title: <>composite action</>, desc: <>把几条 step 打包成一个 <code>action.yml</code>, 放进 repo 或 Marketplace。比 reusable workflow 更轻量, 适合"做完一件小事"的封装。</> }, en: { title: <>Composite actions</>, desc: <>Bundle several steps into one <code>action.yml</code>, kept in-repo or published to the Marketplace. Lighter than a reusable workflow — suited to "do one small thing" wrappers.</> }, code: <code>{c('# action.yml')}{'\n'}{p('runs')}:{'\n'}  {p('using')}: {s("'composite'")}{'\n'}  {p('steps')}:{'\n'}    - {p('shell')}: {v('bash')}{'\n'}      {p('run')}: pnpm install {p('--frozen-lockfile')}</code> },
    { tag: 'I', zh: { title: <>artifact + cache</>, desc: <><code>actions/upload-artifact</code> 把 build 产物存 90 天, 跨 job 拿。<code>actions/cache</code> 缓存 pnpm-store / cargo registry / build cache, install 步从 60s 缩到 5s。</> }, en: { title: <>Artifacts + cache</>, desc: <><code>actions/upload-artifact</code> stores build outputs for 90 days, retrievable across jobs. <code>actions/cache</code> caches pnpm-store / cargo registry / build caches — install drops from 60s to 5s.</> }, code: <code>- {p('uses')}: {v('actions/setup-node@v4')}{'\n'}  {p('with')}:{'\n'}    {p('cache')}: {s("'pnpm'")}{'\n'}    {p('cache-dependency-path')}: {v('core/pnpm-lock.yaml')}</code> },
  ],
  whyCards: [
    { icon: '⌬', zh: { title: <>跟 repo 同根</>, desc: <>secret / permission / branch protection / OIDC / Marketplace 全部走 GitHub 一套权限模型, 没有第二份配置, 没有第二份账号。"build config 藏在 SaaS 仪表板里" 这个历史顽疾被结构性解决。</> }, en: { title: <>Shares a root with the repo</>, desc: <>Secrets, permissions, branch protection, OIDC, and Marketplace all use GitHub\'s one auth model — no second config, no second account. The classic "build config hidden in a SaaS dashboard" ailment is structurally fixed.</> }, code: <>{c('// secrets.GH_TOKEN is auto-injected,')}{'\n'}{c('// scoped to current repo, short-lived')}</> },
    { icon: '⚙', zh: { title: <>YAML = code review 友好</>, desc: <>workflow 改动跟普通 commit 一样进 PR, 一样跑 CI, 一样被 reviewer 看。"昨天 CI 配置悄悄改了" 用 <code>git blame .github/workflows/</code> 一眼定位。</> }, en: { title: <>YAML is code-review friendly</>, desc: <>Workflow changes go through PRs like any other commit, run CI like any other commit, are reviewed like any other commit. "Yesterday someone silently changed CI" is one <code>git blame .github/workflows/</code> away.</> }, code: <>{f('git')} log {p('--oneline')} .github/workflows/{'\n'}{c('// readable history per workflow')}</> },
    { icon: '⌗', zh: { title: <>Marketplace 25k+ action</>, desc: <>"checkout / setup-node / setup-python / cache / upload-artifact / configure-aws-credentials" 等高频动作有官方版, 边角需求也几乎都能 <code>uses:</code> 一个现成的。生态护城河无人能比。</> }, en: { title: <>25k+ actions on Marketplace</>, desc: <>"checkout / setup-node / setup-python / cache / upload-artifact / configure-aws-credentials" have official versions; long-tail needs almost always have a ready-made <code>uses:</code>. The ecosystem moat is unmatched.</> }, code: <>- {p('uses')}: {v('docker/build-push-action@v5')}{'\n'}- {p('uses')}: {v('peaceiris/actions-gh-pages@v3')}</> },
    { icon: '⛯', zh: { title: <>免费额度对 OSS 友好</>, desc: <>公开仓库分钟数无限, 私库每月 2000 分钟。Linux arm64 在公开仓库 2025-01 起免费。本站九条 workflow 跑下来每月用量个位数美元等值, 实际全在免费额度内。</> }, en: { title: <>OSS-friendly free tier</>, desc: <>Unlimited minutes for public repos, 2000 minutes/month for private. Linux arm64 has been free on public repos since January 2025. This site\'s 9 workflows consume single-digit dollars\' equivalent per month — comfortably inside the free tier.</> }, code: <>{c('// public repo:')}{'\n'}{c('// unlimited minutes, free arm64')}</> },
    { icon: '⌖', zh: { title: <>path filter = monorepo 必备</>, desc: <><code>on.push.paths</code> 让 monorepo 只跑相关 workflow。本仓库 <code>core/**</code> 触发 deploy_core, <code>ops/nginx/**</code> 触发 deploy_nginx, <code>stats/**</code> 触发 stats 重建 — 一次 push 只跑相关那条。</> }, en: { title: <>path filters = monorepo essential</>, desc: <><code>on.push.paths</code> keeps monorepos lean. <code>core/**</code> triggers deploy_core; <code>ops/nginx/**</code> triggers deploy_nginx; <code>stats/**</code> triggers a stats rebuild. One push runs only the workflow that matters.</> }, code: <>{p('on')}: {'{ '}{p('push')}: {'{ '}{p('paths')}: [{s("'core/**'")}] {'} }'}</> },
    { icon: '⌁', zh: { title: <>OIDC = secret 数量陡降</>, desc: <>过去要在 secret 里塞云厂商长期 access key, 泄一个全完。OIDC 让 workflow 拿短期 JWT 换 token, 角色信任配在云端, secret 列表从 10+ 砍到 1-2 个。</> }, en: { title: <>OIDC slashes secret counts</>, desc: <>The old way stuffed long-lived cloud access keys into secrets — one leak and it\'s game over. OIDC trades short-lived JWTs for tokens, with role trust configured cloud-side. The secret list drops from 10+ to 1-2.</> }, code: <>{p('permissions')}:{'\n'}  {p('id-token')}: {v('write')}{'\n'}  {p('contents')}: {v('read')}</> },
    { icon: '⏚', zh: { title: <>reusable + composite 让大公司活</>, desc: <>组织内部把 "build node app + 推制品" 提一份, 几十个 repo <code>uses:</code> 进来, 改一处全部生效。"没 reusable 之前每个 repo 一份 yml 复制粘贴" 那个痛点被根除。</> }, en: { title: <>Reusable + composite let big orgs scale</>, desc: <>Hoist "build node app + push artifact" into one workflow; dozens of repos <code>uses:</code> it; change once, propagate everywhere. The "every repo copy-pastes the same yml" pain is gone.</> }, code: <>{p('uses')}: {v('myorg/.github/.github/workflows/build.yml@v2')}</> },
    { icon: '⎇', zh: { title: <>self-hosted = 跑特殊硬件</>, desc: <>GPU build / 大内存 / 网内专网 / Windows on ARM 这些 GitHub-hosted runner 不一定有的场景, 自托 runner 一个 token 接进来, 同一份 YAML 不变。</> }, en: { title: <>Self-hosted = special hardware</>, desc: <>GPU builds, big-memory runs, internal-network access, Windows-on-ARM — anything the hosted fleet doesn\'t cover — a self-hosted runner joins with one token and runs the same YAML unchanged.</> }, code: <>{p('runs-on')}: [{v('self-hosted')}, {v('gpu')}, {v('linux')}]</> },
    { icon: '⌬', zh: { title: <>AI agent 默认目标</>, desc: <>Claude Code / Cursor / Devin / Copilot Workspace 自动发 PR 的实际工作单位都是 GitHub repo, CI 反馈走 Actions。"agent 提 PR → Actions 跑测试 → 红了 agent 自己修" 闭环已经能跑通。</> }, en: { title: <>The default target of AI agents</>, desc: <>Claude Code / Cursor / Devin / Copilot Workspace all auto-open PRs to GitHub repos, and CI feedback flows through Actions. The "agent opens PR → Actions runs tests → agent fixes red CI" loop is functional today.</> }, code: <>{c('// Claude Code default target:')}{'\n'}{c('// gh pr create + gh run watch')}</> },
  ],
  adopters: [
    { name: 'GitHub itself', href: 'https://github.com', highlight: true, zhNote: 'github/github 内部 dogfood, 几千条 workflow', enNote: 'github/github dogfoods Actions across thousands of workflows' },
    { name: 'Node.js', href: 'https://github.com/nodejs/node', highlight: true, zhNote: '官方仓库 CI + release 全 Actions, 跨 11 个平台 matrix', enNote: 'Official repo runs CI + release on Actions, matrix across 11 platforms' },
    { name: 'React', href: 'https://github.com/facebook/react', highlight: true, zhNote: 'PR 自动跑测试 + bundle size 报告', enNote: 'PRs auto-run tests + bundle-size reports' },
    { name: 'Rust language', href: 'https://github.com/rust-lang/rust', zhNote: 'rustc / cargo CI 全 Actions, 含 self-hosted ARM', enNote: 'rustc / cargo CI fully on Actions, including self-hosted ARM' },
    { name: 'Linux distros', zhNote: 'Debian / Fedora / NixOS package CI 大量在 Actions', enNote: 'Debian / Fedora / NixOS package CI runs heavily on Actions' },
    { name: 'Anthropic Claude Code', href: 'https://github.com/anthropics/claude-code', highlight: true, zhNote: 'release + npm 发布全 Actions 自动化', enNote: 'Release + npm publish fully automated on Actions' },
    { name: 'Vercel / Next.js', href: 'https://github.com/vercel/next.js', zhNote: 'Next.js 仓库测试 + canary 发布全 Actions', enNote: 'Next.js repo tests + canary releases on Actions' },
    { name: 'Astro / SvelteKit / Remix', zhNote: '主流框架仓库默认 Actions', enNote: 'Mainstream frameworks default to Actions' },
    { name: 'Hashicorp Terraform', href: 'https://github.com/hashicorp/terraform', zhNote: 'OSS 部分 CI 在 Actions', enNote: 'OSS portion of CI runs on Actions' },
    { name: 'Docker', href: 'https://github.com/docker', zhNote: 'docker/build-push-action 是官方 Marketplace 高频 action', enNote: 'docker/build-push-action is one of the most-used Marketplace actions' },
    { name: 'pnpm / Turbo / Vite', zhNote: '本仓库依赖链上的工具仓库默认 Actions', enNote: 'The toolchain repos this site depends on all default to Actions' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本仓库 — 9 条 workflow 跑测试 + deploy + 周更 stats', enNote: 'This repo — 9 workflows for tests + deploys + weekly stats updates' },
  ],
  outlook: [
    { tag: <>HOT · 2026-01</>, hot: true, big: true, zh: { title: <>arm64 私库 GA + 全面降价</>, body: <><p>1 月 29 日 arm64 standard runner 在私库 GA, 同期定价全面调整, GitHub-hosted runner 价格下调最高 39%。"用 ARM 跑 CI" 从公开 OSS 福利变成普适默认 — 容器 multi-arch build、Rust crate、Apple Silicon 一致性测试全部受益。</p><p>更深一层:GitHub-hosted runner 不再是 "免费但慢、付费才好" 的二元选择, 价格梯度变密, 跟自建 / 第三方托管 (Depot / RunsOn / Buildjet) 的差距收窄。第三方托管的护城河从 "更便宜" 退到 "更快启动 + 缓存 + GPU"。</p></> }, en: { title: <>arm64 private GA + sweeping price cut</>, body: <><p>On January 29, arm64 standard runners reached GA on private repos, alongside a sweeping pricing rework — GitHub-hosted runners dropped by up to 39%. "Run CI on ARM" went from a public-OSS perk to a default for everyone — container multi-arch builds, Rust crates, Apple-Silicon parity tests all benefit.</p><p>The deeper point: hosted runners stop being a binary "free but slow / paid and good" choice. The pricing gradient is denser, narrowing the gap to self-hosted and third-party hosts (Depot / RunsOn / Buildjet). Third-party moats shift from "cheaper" to "faster cold-start + caching + GPU."</p></> } },
    { tag: <>AI</>, hot: true, zh: { title: <>agentic workflow + Copilot</>, body: <><p>Copilot Workspace 把 LLM 接进 workflow_run 上下文 —— 失败的 job 日志、改动的文件 diff、相关 issue 全部进 prompt, agent 提一个 fix PR。早期采用者验证可用, 2026 中开始进入更多企业内部 platform。</p><p>对小项目同样意义重大:本站这种 9 条 workflow 的仓库, CI 红的故事从 "我读日志找根因" 变成 "agent 读日志, 我审 PR"。"build broken time" 这个指标第一次有结构性下降的工具。</p></> }, en: { title: <>Agentic workflows + Copilot</>, body: <><p>Copilot Workspace wires LLMs into <code>workflow_run</code> context — the failed job\'s logs, the diff under test, and related issues all enter the prompt, and the agent opens a fix PR. Validated by early adopters; expected to land in more enterprise platforms through mid-2026.</p><p>This matters at small scale too: for a 9-workflow repo like this site, "CI is red" shifts from "I read the logs and chase the root cause" to "agent reads logs, I review the PR." For the first time there is a structural tool to drive "time-to-build-green" down.</p></> } },
    { tag: 'REUSE', zh: { title: <>reusable + composite 在大组织扩散</>, body: <><p>2021 的 reusable workflow + 2022 的 composite action 经过四年迭代, 大企业内部 platform 团队开始系统化用它们建 "golden path" CI 模板。"每个 repo 一份 yml 复制粘贴" 这条历史路径在 1000+ repo 规模下被根除。</p><p>OSS 圈同期扩散较慢, 因为小项目复用一份 yml 收益不大;但工具链类项目 (主流 framework / 主流 lib) 开始公开发布 reusable workflow, 让下游消费者一键接入测试 / 发布。</p></> }, en: { title: <>Reusable + composite scale across orgs</>, body: <><p>Four years after reusable workflows (2021) and composite actions (2022) shipped, enterprise platform teams are systematically building "golden path" CI templates with them. At 1000+ repos, "every repo copy-pastes the same yml" is finally eliminated as a problem class.</p><p>OSS adoption is slower — for small projects the gain is marginal — but toolchain projects (mainstream frameworks, mainstream libs) now publish reusable workflows so downstream consumers wire up tests / releases in one line.</p></> } },
    { tag: 'OIDC', zh: { title: <>secret 长期减少, OIDC 成主流</>, body: <><p>云厂商角色信任配置全部完善, 几乎不再需要把云 access key 塞 secret。本仓库 secret 列表只剩 <code>DEPLOY_SSH_KEY</code> / <code>DEPLOY_HOST</code> 等基础设施凭据, 其它都被 GITHUB_TOKEN + OIDC 替代。</p><p>这是 supply chain 安全的根 — "build 过程被注入恶意" 的攻击面跟 secret 数量正相关, secret 越少表面越小。</p></> }, en: { title: <>Secrets shrink, OIDC becomes default</>, body: <><p>Cloud providers\' role-trust setup is now complete; cloud access keys rarely need to live in secrets. This repo\'s secret list is down to infrastructure essentials like <code>DEPLOY_SSH_KEY</code> / <code>DEPLOY_HOST</code> — the rest is GITHUB_TOKEN + OIDC.</p><p>This is the supply-chain-security root — the "malicious injection during build" attack surface tracks the secret count, and fewer secrets mean a smaller surface.</p></> } },
    { tag: 'DATA', zh: { title: <>9 workflow / 月 6 美元等值</>, body: <><p>本仓库 2026-05 月度数据:9 条 workflow, 包括每周一次 stats build (重型), 每个 PR / push 跑 typecheck + vitest, 每次 deploy_core 触发 build + scp + pm2 reload。月用量个位数美元等值, 全在免费额度内。</p><p>这是 OSS 项目的现实:Actions 的"免费档"对独立维护者基本等于"无限"。Travis / CircleCI 在 OSS 圈被淘汰也是这一条贡献最大。</p></> }, en: { title: <>9 workflows / under $10/month equiv.</>, body: <><p>This repo\'s May 2026 numbers: 9 workflows including one heavyweight weekly stats build, typecheck + vitest on every PR / push, and deploy_core (build + scp + pm2 reload) on each main push. Monthly consumption is single-digit-dollars equivalent — fully inside the free tier.</p><p>The OSS reality: Actions\' free tier is effectively unlimited for solo maintainers. This is the single biggest factor in why Travis / CircleCI lost the OSS segment.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本仓库 <code>.github/workflows/</code> 下有 9 条 workflow, 全部 path-filter 触发, 各管一段。<code>test.yml</code> 在 PR + push main 时跑前端 typecheck (<code>typecheck:ci</code>, 对齐 CI 全量) + vitest 单元测试 + algorithm 回归 fixture, 失败拒合;它顺手还跑 server typecheck, 因为 server 走 esbuild bundle, esbuild 只剥类型不查, 不真跑 tsc CI 会漏。</p>
        <p><code>deploy_core.yml</code> 是主力:push main 含 <code>core/**</code> 时构建 SPA (<code>pnpm --filter @cuberoot/client build</code>) + 构建 server bundle (esbuild 单文件) + git commit hashed assets 到仓库根 (供 GH Pages 镜像 + nginx serve) + scp 到生产 VM + pm2 reload + apply migrations + 清 nginx api_cache。<code>deploy_mirror.yml</code> 把 <code>deploy_core</code> 的产物 rsync 到 GH Pages 镜像 repo, 给 cuberoot.me CNAME 路径兜底。</p>
        <p>已知坑:<code>deploy_core.yml</code> 的 <code>paths: ['core/**']</code> 在一次 push 文件数超过 300 时偶尔静默不触发 (GitHub 的 path filter 大 push 已知行为), 兜底方案是手动 <code>gh workflow run deploy_core.yml</code> 一次。<code>deploy_nginx.yml</code> 改 <code>ops/nginx/**</code> 时自动 scp + <code>nginx -t</code> 验证 + reload, 失败回滚 <code>.bak</code> — 给手抖留兜底。</p>
        <p><code>stats.yml</code> 是周更, 每周日 20:00 UTC cron 自动跑 + push 触发时同步跑 (改 <code>core/packages/stats-build/src/**</code> 时)。它下载 WCA 公开 dump、跑 80+ 条统计的 builder、产出 <code>stats/**/*.json</code> + 几条 <code>.copy.tsv</code> 给 server PG。<code>scp historical_ranks.copy.tsv</code> 和 <code>load.sql</code> 这条三处协调的链路漏一处就服务端表静默空 — 改 stats.yml / builder / load.sql 必须三处一起核 (memory <code>feedback_ci_pipeline_dry_run</code>)。</p>
      </>
    ),
    en: (
      <>
        <p>The repo has 9 workflows under <code>.github/workflows/</code>, all path-filter triggered, each owning a slice. <code>test.yml</code> runs frontend typecheck (<code>typecheck:ci</code>, force-rebuild aligned with CI) + vitest unit tests + algorithm regression fixtures on every PR and push to main — failures block merge. It also runs the server typecheck because the server ships through an esbuild bundle, and esbuild strips types without checking — skipping a real tsc run silently lets type errors through.</p>
        <p><code>deploy_core.yml</code> is the workhorse: any push to main touching <code>core/**</code> builds the SPA (<code>pnpm --filter @cuberoot/client build</code>), builds the server bundle (single-file esbuild), commits hashed assets to the repo root (for GH Pages mirror + nginx serving), scps to the production VM, runs <code>pm2 reload</code>, applies migrations, and purges the nginx api_cache. <code>deploy_mirror.yml</code> rsyncs the <code>deploy_core</code> output to the GH Pages mirror repo for the cuberoot.me CNAME fallback path.</p>
        <p>Known pitfall: <code>deploy_core.yml</code>\'s <code>paths: ['core/**']</code> sometimes silently fails to trigger when a push touches more than 300 files (known GitHub path-filter behavior on large pushes). Fallback is a manual <code>gh workflow run deploy_core.yml</code>. <code>deploy_nginx.yml</code> scps changes under <code>ops/nginx/**</code>, runs <code>nginx -t</code> for validation, then reloads, rolling back to a <code>.bak</code> on failure — a safety net for typos.</p>
        <p><code>stats.yml</code> runs weekly: cron at Sundays 20:00 UTC, plus on push when <code>core/packages/stats-build/src/**</code> changes. It downloads the WCA public dump, runs 80+ stat builders, and emits <code>stats/**/*.json</code> plus a handful of <code>.copy.tsv</code> files for the server\'s PG. The three-way chain — <code>scp historical_ranks.copy.tsv</code> in stats.yml, builder output, and the <code>load.sql</code> on the VM — must stay in sync; skip one of the three and the server table silently empties out (memory <code>feedback_ci_pipeline_dry_run</code>).</p>
      </>
    ),
  },
  links: [
    { label: 'github.com/features/actions', href: 'https://github.com/features/actions' },
    { label: 'GitHub Actions docs', href: 'https://docs.github.com/en/actions' },
    { label: 'GitHub-hosted runners reference', href: 'https://docs.github.com/en/actions/reference/runners/github-hosted-runners' },
    { label: 'Actions Marketplace', href: 'https://github.com/marketplace?type=actions' },
    { label: 'Universe 2018 announcement', href: 'https://github.blog/2018-10-16-future-of-software/' },
  ],
};

export default GITHUB_ACTIONS;
