import type { StackTool } from '../_lib/stack_tool_types';
import { v, s, f, p, c } from '../_lib/stack_tool_types';

// ─── Mac mini ─────────────────────────────────────────────────────────────────

export const MAC_MINI: StackTool = {
  slug: 'mac-mini',
  name: 'Mac mini',
  version: 'M4 / M4 Pro',
  since: '2005-01',
  group: 'dev',
  accent: '#86868B',
  bright: '#B0B3B5',
  glyph: '⌘',
  floats: ['Apple Silicon', 'unified memory', 'Thunderbolt', 'Neural Engine', 'unibody', 'SoC', 'macOS', 'headless'],
  zh: {
    tagline: '一块 SoC + 统一内存的小型台式机',
    role: '本站规划中的 macOS 端点。iOS / Capacitor 构建和 WebKit 真引擎测试只能在 macOS 上跑, 这台是预留的拼图, 还没到位。',
    heroSub: <>2005 年 1 月 Steve Jobs 在 Macworld 拿出一台 <strong>16.5 厘米见方</strong>、起价 499 美元的小盒子, 第一次把 Mac 卖给"只买主机、自带显示器键鼠"的人。二十一年后它换了三代架构 (PowerPC → Intel → Apple Silicon), 体积缩到 <strong>13 厘米见方</strong>, 一块 M4 SoC 把 CPU / GPU / Neural Engine / 内存焊进同一颗芯片, 成了"最便宜的一台正经 Mac"。</>,
    whatDesc: <>Mac mini 是 Apple 的 <strong>无显示器小型台式机</strong> —— 不含屏幕 / 键盘 / 鼠标, 只给一个主机。它的真正意义在 2020 年之后:M1 起改用 <strong>Apple Silicon SoC</strong>, 把 CPU、GPU、Neural Engine 和内存 (unified memory) 全集成进一颗芯片, 内存不再是插槽里的条子, 而是和处理器共享同一片地址空间。结果是同样体积下功耗极低、待机几乎不发热, 一台 mini 可以 7×24 当无头服务器或 CI 节点常年开着。</>,
    historyDesc: <>从 2005 年 1 月初代 PowerPC G4 (499 美元) 到 2024 年 11 月 M4 重新设计 (13 厘米见方), 二十一年, 跨了三代指令集架构。几个关键跳跃:2006 年 2 月转 Intel、2010 年 6 月换 unibody 铝壳 + HDMI、2018 年 11 月 space gray 重新定位 pro、2020 年 11 月 M1 首发 Apple Silicon、2023 年 1 月 M2 / M2 Pro、2024 年 11 月 M4 / M4 Pro 把机身砍到只有 13 厘米见方并把电源做进机内。</>,
    conceptsTitle: 'SoC + 统一内存',
    conceptsDesc: <>Mac mini 现在最值得讲的不是外形, 是它背后的 Apple Silicon 设计:一颗 <strong>SoC</strong> 集成全部计算单元 + <strong>unified memory</strong> 让 CPU / GPU / Neural Engine 共享同一片内存, 不用在显存和系统内存之间来回拷贝。下面这几张卡片就是理解"为什么一台小盒子能这么省电又这么快"的核心。</>,
    whyDesc: <>把 Mac mini 放进开发者的桌面 / 机柜, 不是因为它跑分多高, 而是因为它在体积 / 功耗 / 单核延迟 / 生态四个维度上找到一个别的机器给不出的平衡点 —— 尤其是当你需要一台 <strong>真的能跑 macOS / Xcode / Safari WebKit</strong> 的机器时, 它是最便宜的合法选择。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>从个人开发者的桌面主机, 到 CI 农场里一柜子无头 mini 跑 iOS 构建, 再到家用小服务器 (homelab) / 媒体盒子。Apple Silicon 之后, "买一台 mini 当永久在线的小机器"成了一个被广泛接受的方案 —— 它够便宜、够安静、够省电。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>当前在售仍是 2024 年 11 月那台 M4 / M4 Pro。2026 上半年业界普遍预期 M5 / M5 Pro 版会接棒 (机身大概率沿用 13 厘米设计), 但截至 2026 年 6 月官网在售机型仍是 M4。更大的趋势是 Neural Engine 算力被持续堆高, 让本地跑中小模型推理变成 mini 的新卖点。</>,
  },
  en: {
    tagline: 'A tiny desktop built on one SoC + unified memory',
    role: 'The planned macOS endpoint for this site. iOS / Capacitor builds and real WebKit testing can only run on macOS — this is the reserved missing piece, not yet acquired.',
    heroSub: <>In January 2005 Steve Jobs pulled a <strong>6.5-inch-square</strong> box out at Macworld, starting at $499 — the first Mac sold to people who'd bring their own display, keyboard, and mouse. Twenty-one years later it has changed architecture three times (PowerPC → Intel → Apple Silicon), shrunk to a <strong>5-inch square</strong>, and welds CPU / GPU / Neural Engine / memory into a single M4 SoC, becoming "the cheapest real Mac you can buy."</>,
    whatDesc: <>Mac mini is Apple's <strong>headless small-form-factor desktop</strong> — no screen, keyboard, or mouse, just the box. Its real significance starts after 2020: from M1 on it uses an <strong>Apple Silicon SoC</strong>, integrating CPU, GPU, Neural Engine, and memory (unified memory) into one chip, so RAM is no longer a slotted stick but a shared address space with the processor. The result is extremely low power at the same size, near-zero idle heat — one mini can run 24/7 as a headless server or CI node for years.</>,
    historyDesc: <>From the original PowerPC G4 in January 2005 ($499) to the M4 redesign in November 2024 (5-inch square), twenty-one years across three instruction-set architectures. Key jumps: the Intel transition (Feb 2006), the unibody aluminum case + HDMI (Jun 2010), the space-gray pro repositioning (Nov 2018), the M1 Apple Silicon debut (Nov 2020), M2 / M2 Pro (Jan 2023), and M4 / M4 Pro shrinking the body to a 5-inch square with the power supply moved inside (Nov 2024).</>,
    conceptsTitle: 'SoC + unified memory',
    conceptsDesc: <>What's worth explaining about Mac mini now isn't the shape — it's the Apple Silicon design behind it: one <strong>SoC</strong> integrating every compute unit, plus <strong>unified memory</strong> letting CPU / GPU / Neural Engine share the same RAM with no copying between VRAM and system memory. These cards are the core of "why a tiny box can be both this power-efficient and this fast."</>,
    whyDesc: <>You put a Mac mini on a desk or in a rack not because it benchmarks highest, but because it hits a balance across size / power / single-core latency / ecosystem that nothing else offers — especially when you need a machine that <strong>truly runs macOS / Xcode / Safari WebKit</strong>, where it's the cheapest legal option.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>From an individual developer's desktop box, to a rack of headless minis running iOS builds in a CI farm, to home servers (homelab) and media boxes. After Apple Silicon, "buy a mini as an always-on little machine" became a widely accepted plan — cheap enough, quiet enough, power-efficient enough.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>The current model on sale is still the M4 / M4 Pro from November 2024. Through the first half of 2026 the industry broadly expects an M5 / M5 Pro version to take over (most likely keeping the 5-inch body), but as of June 2026 the model Apple ships is still M4. The bigger trend is Neural Engine compute climbing, making local small-to-mid model inference a new selling point for the mini.</>,
  },
  heroStats: [
    { num: '5', unit: 'in', zh: <>机身边长 (2024 重设计) <em>13 厘米见方</em></>, en: <>body edge (2024 redesign) <em>5-inch square</em></>
    },
    { num: '21', unit: 'y', zh: <>从 2005 至今 <em>跨 PowerPC / Intel / Apple Silicon</em></>, en: <>since 2005 <em>across PowerPC / Intel / Apple Silicon</em></>
    },
    { num: '48', unit: 'GB', zh: <>M4 Pro 统一内存上限 <em>CPU / GPU / NPU 共享</em></>, en: <>M4 Pro unified memory ceiling <em>shared by CPU / GPU / NPU</em></>
    },
    { num: '499', unit: '$', zh: <>初代起价 (2005-01) <em>第一台"自带显示器"的 Mac</em></>, en: <>original starting price (2005-01) <em>first bring-your-own-display Mac</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>Mac mini 是 Apple 2005 年 1 月在 Macworld 推出的小型台式机。定位很清楚:给已经有显示器 / 键盘 / 鼠标的人 (尤其是想从 Windows 转过来的人) 一台便宜的 Mac 主机, 起价 499 美元, 机身只有 16.5 厘米见方。它从来不是 Apple 的旗舰, 但一直是"门槛最低的一台正经 Mac"。</p>
        <p>它的二十一年史就是 Apple 处理器路线的缩影:2005 年初代是 PowerPC G4, 2006 年 2 月跟着全线转 Intel, 2010 年 6 月换上 unibody 铝壳并加了 HDMI, 2018 年 11 月以 space gray 外观重新往专业用户靠。真正的分水岭是 2020 年 11 月 —— Mac mini 是首批搭载 M1 的三台 Apple Silicon Mac 之一, 从此 CPU / GPU / Neural Engine / 内存被集成进一颗 SoC, 性能 / 功耗比一夜之间换代。</p>
        <p>2024 年 11 月的 M4 / M4 Pro 是最近一次大改:机身从 19.7 厘米见方砍到 13 厘米见方, 电源做进机内, 前面板第一次带了 USB-C 口, M4 Pro 上了 Thunderbolt 5。截至 2026 年 6 月, 官网在售仍是这台 M4 / M4 Pro。对开发者来说它的关键身份没变:一台够小、够安静、能 7×24 开着的 macOS 机器 —— 而 macOS 是 iOS 构建 / 签名 / WebKit 测试唯一的合法落脚点。</p>
      </>
    ),
    en: (
      <>
        <p>Mac mini is the small desktop Apple introduced at Macworld in January 2005. The positioning was clear: give people who already own a display, keyboard, and mouse (especially Windows switchers) a cheap Mac box — $499 to start, just 6.5 inches square. It has never been Apple's flagship, but it has always been "the lowest-barrier real Mac."</p>
        <p>Its twenty-one-year history is a miniature of Apple's processor roadmap: the 2005 original ran a PowerPC G4; in February 2006 it followed the line-wide Intel transition; in June 2010 it switched to a unibody aluminum case and gained HDMI; in November 2018 a space-gray redesign nudged it toward pro users. The real watershed was November 2020 — Mac mini was one of the first three Apple Silicon Macs with M1, after which CPU / GPU / Neural Engine / memory all integrate into one SoC, and performance-per-watt changed generation overnight.</p>
        <p>The M4 / M4 Pro of November 2024 is the latest big redesign: the body shrinks from 7.7 inches square to 5 inches square, the power supply moves inside, the front panel carries USB-C for the first time, and M4 Pro adds Thunderbolt 5. As of June 2026 the model on sale is still this M4 / M4 Pro. For developers its core identity is unchanged: a machine small, quiet, and efficient enough to run macOS 24/7 — and macOS is the only legal home for iOS builds / signing / WebKit testing.</p>
      </>
    ),
  },
  history: [
    { year: '2005·01', zh: { title: <>初代 PowerPC G4</>, desc: <>1 月 22 日发布, 起价 499 美元, 16.5 厘米见方, PowerPC G4 处理器。Apple 第一次卖"自带显示器键鼠"的小主机, 主打 Windows 用户低成本试 Mac。</> }, en: { title: <>Original PowerPC G4</>, desc: <>Released January 22, $499 to start, 6.5 inches square, PowerPC G4. Apple's first bring-your-own-display box, aimed at letting Windows users try Mac cheaply.</> } },
    { year: '2006·02', zh: { title: <>转 Intel</>, desc: <>2 月 28 日换 Intel Core Solo / Core Duo, 跟随全线 Intel 迁移。同体积下性能跳了一档, 也为后来跑 Boot Camp / 虚拟 Windows 打开门。</> }, en: { title: <>Intel transition</>, desc: <>February 28 brought Intel Core Solo / Core Duo, following the line-wide Intel migration. A performance jump at the same size, and the door to Boot Camp / virtualized Windows.</> } },
    { year: '2010·06', zh: { title: <>unibody 铝壳 + HDMI</>, desc: <>6 月 15 日换上整块铝切削的 unibody 机身, 更薄, 首次带 HDMI 输出。"接电视当媒体盒子"从此成了 mini 的一个常见用法。</> }, en: { title: <>Unibody aluminum + HDMI</>, desc: <>June 15 introduced a thinner unibody case machined from a single aluminum block, with HDMI out for the first time. "Plug into a TV as a media box" became a common mini use from here.</> } },
    { year: '2014·10', zh: { title: <>2014 款 (Haswell)</>, desc: <>10 月 16 日更新到 Haswell 双核, 加 802.11ac Wi-Fi、4K HDMI 输出。但内存焊死、性能保守, 被很多老用户视为一次倒退。</> }, en: { title: <>2014 model (Haswell)</>, desc: <>October 16 updated to dual-core Haswell, adding 802.11ac Wi-Fi and 4K HDMI out. But soldered RAM and conservative performance made many long-time users call it a regression.</> } },
    { year: '2018·11', zh: { title: <>space gray + pro 定位</>, desc: <>11 月 7 日推出 space gray 配色, 四个 Thunderbolt 3 口 + 桌面级四 / 六核 Intel, 第一次把 mini 往"小钢炮 / 开发机 / 服务器"方向重新定位。也是最后一代 Intel mini。</> }, en: { title: <>Space gray + pro positioning</>, desc: <>November 7 brought a space-gray finish, four Thunderbolt 3 ports, and desktop-class 4 / 6-core Intel, repositioning the mini toward "compact powerhouse / dev box / server" for the first time. Also the last Intel mini.</> } },
    { year: '2020·11', zh: { title: <>M1 — Apple Silicon 首发</>, desc: <>11 月 17 日, Mac mini 是首批三台 Apple Silicon Mac 之一。一颗 M1 SoC 集成 CPU / GPU / Neural Engine + 统一内存, 性能功耗比相对 Intel mini 跨代提升, 待机几乎不发热。</> }, en: { title: <>M1 — Apple Silicon debut</>, desc: <>November 17, Mac mini was one of the first three Apple Silicon Macs. One M1 SoC integrates CPU / GPU / Neural Engine plus unified memory; performance-per-watt jumped a generation over the Intel mini, with near-zero idle heat.</> } },
    { year: '2023·01', zh: { title: <>M2 / M2 Pro</>, desc: <>1 月 24 日上 M2 和 M2 Pro。M2 Pro 把"高端 mini"补上, 提供更多 CPU / GPU 核与更高内存带宽, 缩小了和 Mac Studio 的差距。</> }, en: { title: <>M2 / M2 Pro</>, desc: <>January 24 brought M2 and M2 Pro. M2 Pro filled in the "high-end mini," offering more CPU / GPU cores and higher memory bandwidth, narrowing the gap to Mac Studio.</> } },
    { year: '2024·11', highlight: true, zh: { title: <>M4 / M4 Pro 重新设计</>, desc: <>11 月 8 日发布。机身砍到 13 厘米见方 (从 19.7), 电源内置, 前面板首次带两个 USB-C。M4 给三个 Thunderbolt 4, M4 Pro 给三个 Thunderbolt 5, 统一内存最高 24GB / 48GB。截至 2026-06 仍是在售机型。</> }, en: { title: <>M4 / M4 Pro redesign</>, desc: <>Released November 8. Body shrinks to 5 inches square (from 7.7), power supply built in, front panel carries two USB-C for the first time. M4 has three Thunderbolt 4, M4 Pro three Thunderbolt 5, unified memory up to 24GB / 48GB. Still the model on sale as of 2026-06.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>SoC — 一颗芯片装下整台机器</>, desc: <>Apple Silicon 把 CPU、GPU、Neural Engine、内存控制器、IO 控制器全做进一颗 System on Chip。没有南北桥、没有独立显卡、没有内存条 —— 缩短了所有互联路径, 这是 mini 又小又省电的物理前提。</> }, en: { title: <>SoC — one chip is the whole machine</>, desc: <>Apple Silicon puts CPU, GPU, Neural Engine, memory controller, and IO controllers into one System on Chip. No chipset, no discrete GPU, no RAM sticks — every interconnect path shrinks, the physical reason a mini is both small and efficient.</> }, code: <code>{p('$')} {f('sysctl')} {p('-n')} machdep.cpu.brand_string{'\n'}{v('Apple M4')}{'\n\n'}{p('$')} {f('sysctl')} {p('-n')} hw.ncpu{'\n'}{v('10')}  {c('// 4 perf + 6 efficiency cores')}</code> },
    { tag: 'B', zh: { title: <>统一内存 (unified memory)</>, desc: <>CPU / GPU / Neural Engine 共享同一片物理内存, 同一片地址空间。传统 PC 上 GPU 要把数据从系统内存拷进显存才能算, Apple Silicon 上这一步消失了 —— 大模型推理、视频编辑这种"内存搬运密集"场景受益最大。</> }, en: { title: <>Unified memory</>, desc: <>CPU / GPU / Neural Engine share the same physical RAM and address space. On a traditional PC the GPU must copy data from system RAM into VRAM before computing; on Apple Silicon that step disappears — model inference and video editing, the memory-shuffle-heavy workloads, benefit most.</> }, code: <code>{p('$')} {f('system_profiler')} SPHardwareDataType {p('|')} {f('grep')} Memory{'\n'}{v('Memory: 24 GB')}  {c('// shared CPU / GPU / NPU')}</code> },
    { tag: 'C', zh: { title: <>Neural Engine (NPU)</>, desc: <>SoC 里专门跑神经网络的单元, M4 是 16 核 Neural Engine。系统级特性 (语音 / 图像 / 端侧推理) 和第三方 Core ML 模型都跑在它上面, 比拿 GPU / CPU 算同样的任务省电得多。</> }, en: { title: <>Neural Engine (NPU)</>, desc: <>A dedicated neural-network unit inside the SoC; M4 has a 16-core Neural Engine. System features (speech / image / on-device inference) and third-party Core ML models run on it, far more power-efficient than the same work on GPU / CPU.</> }, code: <code>{c('// Core ML automatically picks the Neural Engine')}{'\n'}{f('let')} config = MLModelConfiguration(){'\n'}config.{p('computeUnits')} = .all  {c('// CPU + GPU + ANE')}</code> },
    { tag: 'D', zh: { title: <>macOS — 唯一能跑它的系统</>, desc: <>Mac mini 出厂跑 macOS, 这不是限制而是它存在的理由:Xcode、iOS 模拟器、codesign、Safari WebKit 引擎都只在 macOS 上有。任何团队要做 iOS / Safari, 链条上必须有至少一台 Mac, mini 是其中最便宜的。</> }, en: { title: <>macOS — the only OS that runs it</>, desc: <>Mac mini ships with macOS — not a limitation but its reason to exist: Xcode, the iOS simulator, codesign, and the Safari WebKit engine live only on macOS. Any team shipping iOS / Safari needs at least one Mac in the chain, and the mini is the cheapest one.</> }, code: <code>{p('$')} {f('xcodebuild')} {p('-version')}{'\n'}{v('Xcode 17.0')}{'\n\n'}{p('$')} {f('xcrun')} simctl list devices booted</code> },
    { tag: 'E', zh: { title: <>低功耗 → 7×24 长开</>, desc: <>Apple Silicon mini 满载约几十瓦, 待机几瓦, 安静无风扇噪音感。一台插着电常年开着当无头服务器 / CI 节点, 电费和噪音都可以忽略 —— 这是它做 always-on 小机器的物理基础。</> }, en: { title: <>Low power → always-on</>, desc: <>An Apple Silicon mini draws tens of watts loaded, a few watts idle, with no noticeable fan noise. Leave one plugged in year-round as a headless server / CI node and both power cost and noise are negligible — the physical basis for an always-on machine.</> }, code: <code>{p('$')} {f('powermetrics')} {p('--samplers')} cpu_power{'\n'}{v('Combined Power: 6840 mW')}  {c('// idle, headless')}</code> },
    { tag: 'F', zh: { title: <>Thunderbolt — 外接扩展</>, desc: <>M4 给三个 Thunderbolt 4, M4 Pro 给三个 Thunderbolt 5 (带宽更高)。外接高速 SSD、多台显示器、eGPU 替代方案、网络存储都走它。无显示器的 mini 靠 Thunderbolt 把"扩展性"补回来。</> }, en: { title: <>Thunderbolt — external expansion</>, desc: <>M4 has three Thunderbolt 4, M4 Pro three Thunderbolt 5 (higher bandwidth). External fast SSDs, multiple displays, eGPU alternatives, and network storage all ride it. A display-less mini gets its expandability back through Thunderbolt.</> }, code: <code>{p('$')} {f('system_profiler')} SPThunderboltDataType{'\n'}{v('Thunderbolt 4  -  40 Gb/s')}</code> },
    { tag: 'G', zh: { title: <>headless — 无头运行</>, desc: <>mini 设计上就允许不接显示器跑:开 Remote Login (ssh) + Screen Sharing (VNC), 放进机柜或抽屉常年远程访问。CI 农场就是一柜子无头 mini, 每台跑一条 iOS 构建流水线。</> }, en: { title: <>Headless operation</>, desc: <>The mini is built to run with no display: enable Remote Login (ssh) + Screen Sharing (VNC), tuck it in a rack or drawer, access remotely year-round. A CI farm is literally a rack of headless minis, each running one iOS build pipeline.</> }, code: <code>{p('$')} {f('sudo')} systemsetup {p('-setremotelogin')} on{'\n'}{p('$')} {f('ssh')} ci@mac-mini.local {s('"xcodebuild ..."')}</code> },
    { tag: 'H', zh: { title: <>unibody — 整块铝切削</>, desc: <>2010 年起机身用整块铝合金 CNC 切削而成 (unibody), 既是散热体也是结构件。被动散热靠这块铝把热导出, 配合低功耗 SoC 让 mini 在很小体积里维持稳定温度。</> }, en: { title: <>Unibody — machined aluminum</>, desc: <>Since 2010 the body is CNC-machined from a single aluminum block (unibody), serving as both heatsink and structure. Passive cooling conducts heat through this aluminum, which together with the low-power SoC keeps the mini stable in a tiny volume.</> }, code: <code>{c('// the chassis IS the heatsink')}{'\n'}{c('// no copper tower, no loud fan curve')}</code> },
  ],
  whyCards: [
    { icon: '⌘', zh: { title: <>跑 macOS = iOS 构建唯一合法路</>, desc: <>Xcode / codesign / iOS 模拟器只在 macOS 上有。要发 App Store, 链条里必须有一台 Mac, 没有例外。mini 是这条强制要求里最便宜的满足项。</> }, en: { title: <>macOS = the only legal iOS build path</>, desc: <>Xcode / codesign / the iOS simulator exist only on macOS. To ship to the App Store you must have a Mac in the chain, no exceptions. The mini is the cheapest way to satisfy that hard requirement.</> }, code: <>{f('xcodebuild')} {p('-scheme')} App archive{'\n'}{f('xcrun')} {p('--sdk')} iphoneos ...</> },
    { icon: '◫', zh: { title: <>统一内存 = 没有拷贝开销</>, desc: <>CPU 和 GPU 看同一片内存, 不用在系统内存和显存之间搬数据。对"加载大模型 / 处理大视频帧"这种内存密集任务, 等效带宽和延迟都比独显 PC 占优。</> }, en: { title: <>Unified memory = zero copy overhead</>, desc: <>CPU and GPU see the same RAM, no shuffling data between system memory and VRAM. For memory-bound work (loading big models / large video frames), effective bandwidth and latency beat a discrete-GPU PC.</> }, code: <>{c('// GPU reads the same buffer the CPU wrote')}{'\n'}{c('// no upload to VRAM')}</> },
    { icon: '◴', zh: { title: <>省电安静 = 可以常年开</>, desc: <>无风扇噪音感、待机几瓦, 一台插着当无头服务器 / CI 节点全年不关, 电费忽略不计。这一条是它和台式工作站的根本差异。</> }, en: { title: <>Quiet + efficient = run it forever</>, desc: <>No noticeable fan noise, a few watts idle — leave one plugged in as a headless server / CI node all year, power cost negligible. This is the fundamental difference from a desktop workstation.</> }, code: <>{c('// idle ~6W, loaded tens of W')}{'\n'}{c('// safe to keep on 24/7')}</> },
    { icon: '◰', zh: { title: <>体积小 = 桌面 / 机柜都塞得下</>, desc: <>13 厘米见方比一个路由器还小。放桌面不占地方, 进机柜一层能塞好几台。CI 农场就是这么堆出来的 —— 同样占地比塔式机密度高得多。</> }, en: { title: <>Tiny = fits a desk or a rack</>, desc: <>A 5-inch square is smaller than a router. On a desk it takes no space; in a rack a shelf holds several. CI farms are stacked exactly this way — far higher density per area than tower machines.</> }, code: <>{c('// 5 x 5 x 2 in')}{'\n'}{c('// rack shelf holds a column of them')}</> },
    { icon: '◵', zh: { title: <>Neural Engine = 端侧推理省电</>, desc: <>16 核 Neural Engine 跑 Core ML 模型比 GPU / CPU 省电得多。语音转写、图像处理、中小模型本地推理落在 NPU 上, 不必上云、不必占满 GPU。</> }, en: { title: <>Neural Engine = efficient on-device inference</>, desc: <>The 16-core Neural Engine runs Core ML models far more efficiently than GPU / CPU. Speech transcription, image processing, and small-to-mid model inference land on the NPU — no cloud round-trip, no saturated GPU.</> }, code: <>config.{p('computeUnits')} = .all{'\n'}{c('// dispatched to the Neural Engine')}</> },
    { icon: '◶', zh: { title: <>WebKit 真引擎 = Safari 测得准</>, desc: <>Safari 用 WebKit, Windows 上的 Chrome / Edge 都是 Chromium, 测不出 WebKit 自己的渲染 / JS 差异。要保证页面在 iOS Safari 上对, 必须在真 macOS / WebKit 上验。</> }, en: { title: <>Real WebKit = accurate Safari testing</>, desc: <>Safari uses WebKit; Chrome / Edge on Windows are Chromium and can't surface WebKit's own rendering / JS differences. To guarantee a page is correct in iOS Safari you must verify on real macOS / WebKit.</> }, code: <>{f('open')} {p('-a')} Safari http://localhost:3000{'\n'}{c('// WebKit, not Chromium')}</> },
    { icon: '◷', zh: { title: <>headless 远程 = 抽屉里也能干活</>, desc: <>开 ssh + 屏幕共享, mini 不接显示器塞进抽屉 / 机柜常年远程访问。"一台不在视线里但一直在线的小 Mac" 是它最被低估的用法。</> }, en: { title: <>Headless remote = works from a drawer</>, desc: <>Enable ssh + Screen Sharing and the mini runs display-less in a drawer / rack, accessed remotely year-round. "A little Mac out of sight but always online" is its most underrated use.</> }, code: <>{f('ssh')} mac-mini.local{'\n'}{f('screen sharing')} {p('->')} vnc://mac-mini.local</> },
    { icon: '◳', zh: { title: <>生态完整 = 不是半截方案</>, desc: <>它是一台正经 Mac, 不是开发板也不是阉割机:全套 macOS、App Store、Xcode、Homebrew、Docker (虚拟化) 都能跑。买它得到的是完整 Apple 生态, 只是没带屏幕。</> }, en: { title: <>Full ecosystem = not a half solution</>, desc: <>It's a real Mac, not a dev board or a cut-down unit: full macOS, App Store, Xcode, Homebrew, Docker (virtualized) all run. You get the complete Apple ecosystem — just without a screen.</> }, code: <>{f('brew')} install node{'\n'}{f('softwareupdate')} {p('--install')} {p('--all')}</> },
  ],
  adopters: [
    { name: 'iOS / app developers', zhNote: '桌面主力机, 跑 Xcode / 模拟器 / 真机调试', enNote: 'Primary desktop, running Xcode / simulator / device debugging' },
    { name: 'GitHub Actions macOS runners', href: 'https://docs.github.com/actions/using-github-hosted-runners/about-github-hosted-runners', zhNote: 'macOS runner 即 Apple Silicon mini, 跑 iOS 构建', enNote: 'macOS runners are Apple Silicon minis running iOS builds' },
    { name: 'MacStadium', href: 'https://www.macstadium.com', zhNote: '成柜出租无头 Mac mini, 给 CI / 构建用', enNote: 'Rents racks of headless Mac minis for CI / builds' },
    { name: 'Scaleway Apple Silicon', href: 'https://www.scaleway.com/en/apple-silicon-m1-as-a-service/', zhNote: '按小时出租 Apple Silicon mini 实例', enNote: 'Hourly Apple Silicon mini instances' },
    { name: 'Flutter / React Native teams', href: 'https://flutter.dev', zhNote: '跨平台框架的 iOS 产物必须 Mac 出', enNote: 'Cross-platform frameworks still need a Mac for iOS artifacts' },
    { name: 'Homelab / self-hosters', href: 'https://www.reddit.com/r/homelab/', zhNote: '低功耗当家用小服务器 / 媒体盒子', enNote: 'Low-power home servers / media boxes' },
    { name: 'Plex / Jellyfin media servers', href: 'https://www.plex.tv', zhNote: '安静省电, 适合 7×24 媒体串流', enNote: 'Quiet and efficient for 24/7 media streaming' },
    { name: 'Ollama (local LLM)', href: 'https://ollama.com', zhNote: '靠统一内存在 mini 上本地跑中小模型', enNote: 'Runs small-to-mid models locally on the mini via unified memory' },
    { name: 'Final Cut / video editors', href: 'https://www.apple.com/final-cut-pro/', zhNote: 'M4 Pro 统一内存 + 媒体引擎做剪辑', enNote: 'M4 Pro unified memory + media engine for editing' },
    { name: 'Xcode Cloud', href: 'https://developer.apple.com/xcode-cloud/', zhNote: 'Apple 自家 CI, 底层即 Apple Silicon Mac', enNote: "Apple's own CI, Apple Silicon Macs underneath" },
    { name: 'Cubing.js / WCA tooling', href: 'https://js.cubing.net', zhNote: '魔方生态前端工具需 Safari / WebKit 验证', enNote: 'Cubing frontend tooling needs Safari / WebKit verification' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 — Capacitor iOS 构建 + WebKit 测试的 macOS 端点', enNote: 'This site — macOS endpoint for Capacitor iOS builds + WebKit testing' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>M5 / M5 Pro 接棒在即</>, body: <><p>2026 上半年业界普遍预期 Mac mini 会更新到 M5 / M5 Pro, 沿用 2024 年那台 13 厘米见方的机身, 主要升级在 Neural Engine 算力、SSD 速度和基础存储容量上 (传 Apple 已在 2026 年中停掉 256GB 入门款, 把 512GB 设为新起点)。</p><p>但要诚实:截至 2026 年 6 月, 官网在售机型仍是 2024 年 11 月那台 M4 / M4 Pro。M5 mini 的确切发布窗口 (春季专场 / 年中开发者大会) 仍未官方确认, 这里写的是预期不是事实。</p></> }, en: { title: <>M5 / M5 Pro nearly here</>, body: <><p>Through the first half of 2026 the industry broadly expects a Mac mini refresh to M5 / M5 Pro, keeping the 2024 5-inch body, with the main upgrades in Neural Engine compute, SSD speed, and base storage (Apple reportedly dropped the 256GB entry tier mid-2026, making 512GB the new floor).</p><p>To be honest: as of June 2026 the model on sale is still the M4 / M4 Pro from November 2024. The exact M5 mini launch window (a spring event / the mid-year developer conference) is not officially confirmed — what's written here is expectation, not fact.</p></> } },
    { tag: <>AI</>, hot: true, zh: { title: <>本地推理成新卖点</>, body: <><p>统一内存让 mini 能把整个中小模型放进内存一次推理, Neural Engine 每代算力翻倍, "买一台 mini 在桌面本地跑模型"从极客玩法变成主流卖点。对隐私敏感 / 不想上云的场景, 一台 48GB 统一内存的 M4 Pro mini 是性价比很高的端侧推理盒子。</p></> }, en: { title: <>Local inference becomes a selling point</>, body: <><p>Unified memory lets a mini fit a whole small-to-mid model in RAM for inference, and Neural Engine compute roughly doubles each generation, turning "buy a mini and run models locally on your desk" from a geek trick into a mainstream selling point. For privacy-sensitive / cloud-averse cases, a 48GB unified-memory M4 Pro mini is a cost-effective on-device inference box.</p></> } },
    { tag: 'CI', zh: { title: <>无头 mini 成 iOS CI 标准件</>, body: <><p>因为 iOS 构建强制要 macOS, 一柜子无头 Apple Silicon mini 成了 iOS CI 农场的标准形态。省电 + 小体积让"机柜里塞一列 mini, 每台跑一条流水线"在密度和电费上都划算, 主流 CI 厂商和 Apple 自家 Xcode Cloud 底层都是这套。</p></> }, en: { title: <>Headless minis become standard iOS CI</>, body: <><p>Because iOS builds mandate macOS, a rack of headless Apple Silicon minis is the standard shape of an iOS CI farm. Efficiency plus small size make "a column of minis per shelf, one pipeline each" economical on both density and power; mainstream CI vendors and Apple's own Xcode Cloud run this underneath.</p></> } },
    { tag: 'PORTS', zh: { title: <>Thunderbolt 5 普及外接扩展</>, body: <><p>M4 Pro 上的 Thunderbolt 5 把外接带宽再翻一档, 让无显示器的 mini 靠外接 SSD / 多显示器 / 高速网络存储把扩展性补满。随着 TB5 外设变多, "一台 mini + 一堆 TB5 外接"逐渐能替代一部分塔式工作站的角色。</p></> }, en: { title: <>Thunderbolt 5 broadens expansion</>, body: <><p>Thunderbolt 5 on M4 Pro doubles external bandwidth again, letting a display-less mini regain full expandability through external SSDs / multiple displays / fast network storage. As TB5 peripherals proliferate, "a mini plus a stack of TB5 gear" increasingly replaces part of a tower workstation's role.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本站主开发机是一台 Windows 11 Pro, 几乎所有代码都在 Claude Code CLI 里写; 前端主工作区 <code>core/packages/client</code> 是 Next.js 16 App Router + React 19, 后端 Hono 跑在 <code>api.cuberoot.me</code> (Node 22 + pm2 + PG 13)。这套日常开发完全不需要 Mac。Mac mini 的位置很窄、也很硬:它是工具链里那个不可替代的 macOS 端点。</p>
        <p>本站有移动端 —— 用 Capacitor 把同一份 Web 套成 iOS / Android, 走 <code>mobile_build.yml</code> workflow 触发构建。Android 侧 (APK) 在 Linux / Windows 上就能出, 但 <strong>iOS 侧的 IPA 构建和签名只能在 macOS 上做</strong>:Xcode、codesign、iOS 模拟器都不存在于非 macOS 系统。这是硬性约束, 绕不过去, 也是为什么这套跨平台流水线必须有一个 macOS 落脚点。</p>
        <p>第二个真实用途是 WebKit 端验证。iOS Safari 用 WebKit 引擎, 而本站平时在 Windows 上用 Chrome / Edge 测 (都是 Chromium), 测不出 WebKit 自己的渲染和 JS 行为差异。要确认页面在 iPhone Safari 上不错位 / 不白屏, 必须在真 macOS + 真 Safari 上跑一遍 —— Mac mini 就是这台"真引擎机器"。</p>
        <p>诚实说明:这是 Mac mini 在本站工具链里的<strong>真实定位描述</strong>, 不是说本站当下已经常态化在跑一座无头 mini CI 农场。当前移动端构建主要走托管 macOS runner; 自己摆一台 mini 长期当本地 iOS 构建 + WebKit 真机测试节点, 是这套架构里自然、合理的下一步, 这里照实标注为"工具链定位"而非已落地的基建细节, 不编造无法核实的内容。</p>
      </>
    ),
    en: (
      <>
        <p>This site's primary dev machine is a Windows 11 Pro box, with nearly all code written inside the Claude Code CLI; the frontend main workspace <code>core/packages/client</code> is Next.js 16 App Router + React 19, and the Hono backend runs at <code>api.cuberoot.me</code> (Node 22 + pm2 + PG 13). None of this daily development needs a Mac. Mac mini's place is narrow but firm: it's the irreplaceable macOS endpoint of the toolchain.</p>
        <p>The site has a mobile target — Capacitor wraps the same web app into iOS / Android, triggered by the <code>mobile_build.yml</code> workflow. The Android side (APK) builds fine on Linux / Windows, but <strong>iOS IPA building and signing can only happen on macOS</strong>: Xcode, codesign, and the iOS simulator simply don't exist off macOS. That's a hard constraint with no way around it, and why this cross-platform pipeline must have a macOS foothold.</p>
        <p>The second real use is WebKit-side verification. iOS Safari uses the WebKit engine, while this site normally tests on Windows with Chrome / Edge (both Chromium), which can't surface WebKit's own rendering and JS behavior differences. To confirm a page doesn't misalign / white-screen in iPhone Safari, you must run it on real macOS + real Safari — and a Mac mini is exactly that "real-engine machine."</p>
        <p>Honest note: this is a <strong>description of Mac mini's role</strong> in this toolchain, not a claim that the site currently runs a headless mini CI farm as routine. Current mobile builds mostly use hosted macOS runners; standing up a mini long-term as a local iOS build + WebKit device-test node is the natural, sensible next step for this architecture. It's marked here as a toolchain role, not as deployed infrastructure, with nothing fabricated that can't be verified.</p>
      </>
    ),
  },
  links: [
    { label: 'apple.com Mac mini', href: 'https://www.apple.com/mac-mini/' },
    { label: 'Mac mini tech specs', href: 'https://support.apple.com/en-us/111912' },
    { label: 'Apple Silicon overview', href: 'https://www.apple.com/mac/m4/' },
    { label: 'Capacitor iOS docs', href: 'https://capacitorjs.com/docs/ios' },
    { label: 'Mac Mini — Wikipedia', href: 'https://en.wikipedia.org/wiki/Mac_Mini' },
  ],
};

export default MAC_MINI;
