import type { StackTool } from '../_lib/stack_tool_types';
import { v, s, f, p, c } from '../_lib/stack_tool_types';

// ─── npm (registry + package.json spec + CLI) ───────────────────────────────

export const NPM: StackTool = {
  slug: 'npm',
  name: 'npm',
  version: '11.14',
  since: '2010-01',
  group: 'dev',
  accent: '#CB3837',
  bright: '#E55B5A',
  glyph: '❒',
  floats: ['npm install', 'npx', 'package.json', 'semver', '^1.0.0', 'npm audit', 'workspaces', 'npm publish', 'package-lock.json', 'dist-tags', 'peerDependencies', 'tarball'],
  zh: {
    tagline: '全球最大的代码仓库 + JavaScript 的事实标准包格式',
    role: '我们用 pnpm CLI, 但每个依赖最终都从 registry.npmjs.org 拉。package.json 是源头, semver / lockfile 协议把整个生态串起来。',
    heroSub: <>Isaac Schlueter 2009 年起意, 2010 年发布 npm 1.0, 给 Node 早期的"没有 module 分发"问题画了一个出口。十六年过去, registry 上有 <strong>400 万</strong>+ 包、周下载几千亿次, <code>package.json</code> 成了 JS 之外都在抄的<strong>事实标准 manifest 格式</strong>。我们日常用 pnpm 装包, 但拉的还是 <code>registry.npmjs.org</code>。</>,
    whatDesc: <>npm 是三件事的合称:<strong>注册表</strong> (registry.npmjs.org)、<strong>包格式规范</strong> (package.json + tarball + semver)、<strong>CLI 工具</strong> (npm 命令)。yarn / pnpm / bun 都是同一注册表的不同<strong>客户端</strong>, 它们能共存正因为格式是 npm 定的、registry 是 npm 托管的。</>,
    historyDesc: <>从 2009 年 Schlueter 在 Node 早期写下第一行, 到 2014 年 npm Inc. 成立, 2016 年 left-pad 事件改写 unpublish 政策, 2020 年被 GitHub (Microsoft) 收购, 再到 2024 年 provenance attestations 落地。十六年里 npm 几乎没换过身份:JS 世界的官方包源。</>,
    conceptsTitle: 'package.json + semver + tarball 三件套',
    conceptsDesc: <>npm 的可观察"产品"其实是<strong>一份规范</strong>:每个包是个 .tar.gz, 里面有个 <code>package.json</code> 描述自己, 版本号按 semver 排, 依赖图按 semver 范围解析。客户端 (npm / pnpm / yarn / bun) 只是这套协议的不同实现。</>,
    whyDesc: <>2026 年继续把 npm 作为基础设施, 不是因为 CLI 多好用 (pnpm 客户端体验明显更好), 而是因为<strong>注册表的网络效应</strong>、<strong>package.json 已成跨语言抄袭对象</strong>、<strong>免费层不缩水 + provenance 给了 supply-chain 一条路</strong>这三件事换不动了。</>,
    adoptersTitle: '谁在用 (registry + 格式)',
    adoptersDesc: <>"用 npm" 这件事范围很大 —— 任何跑 <code>install</code> 的 JS / TS 项目都在用 npm 注册表。下面列的是<strong>把 npm 当核心基础设施</strong>的几个组织, 包括我们自己。</>,
    cuberootDesc: <>本仓库根有 <code>package.json</code>, <code>core/</code> 还有一个 workspace 根 <code>package.json</code> + 11 个 workspace 各自的 <code>package.json</code>。我们日常 <code>pnpm install</code>, 但 pnpm 把 tarball 从 <code>registry.npmjs.org</code> 拉下来, 走的还是 npm 协议。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>2026 年 npm 的位置已经稳到不需要"防守":provenance + sigstore 给 supply-chain 加可证明性, JSR (Deno 的新 registry) 在试但体量差 1000x, AI 工具一代默认输出 npm install 命令。registry 不动, 客户端继续卷。</>,
  },
  en: {
    tagline: "The world's largest software registry — and the de-facto JS package format",
    role: "We type `pnpm install`, but every dependency still comes from registry.npmjs.org. package.json is the source; semver / lockfile is the glue.",
    heroSub: <>Isaac Schlueter sketched npm in 2009 and shipped 1.0 in 2010, giving early Node a way to ship modules. Sixteen years on, the registry holds <strong>4M+</strong> packages, serves hundreds of billions of weekly downloads, and <code>package.json</code> has become the <strong>de-facto manifest format</strong> copied even outside JS. We install with pnpm, but the bytes still come from <code>registry.npmjs.org</code>.</>,
    whatDesc: <>npm is three things in one name: <strong>the registry</strong> (registry.npmjs.org), <strong>the package format spec</strong> (package.json + tarball + semver), and <strong>the CLI</strong> (the <code>npm</code> command). yarn / pnpm / bun are different <strong>clients</strong> against the same registry — they coexist precisely because the format and the hub belong to npm.</>,
    historyDesc: <>From Schlueter's first commit during Node's earliest days, to npm Inc. (2014), the left-pad incident that rewrote unpublish policy (2016), the GitHub (Microsoft) acquisition (2020), to provenance attestations landing in 2024. Across sixteen years npm has barely changed identity: it's the official source for JS packages.</>,
    conceptsTitle: 'package.json + semver + tarball',
    conceptsDesc: <>The actual "product" npm sells is <strong>a spec</strong>: each package is a .tar.gz containing a <code>package.json</code> that describes itself; versions are ordered by semver; dependency graphs resolve against semver ranges. Every client (npm / pnpm / yarn / bun) is a different implementation of this protocol.</>,
    whyDesc: <>Keeping npm as core infrastructure in 2026 isn't about the CLI ergonomics (pnpm clearly wins there). It's that three things are not movable: <strong>registry network effects</strong>, <strong>package.json copied even by non-JS ecosystems</strong>, and <strong>a free tier that hasn't shrunk + provenance giving supply-chain a real path forward</strong>.</>,
    adoptersTitle: 'Who uses it (registry + format)',
    adoptersDesc: <>"Using npm" is everyone — any JS / TS project that runs <code>install</code> is using the npm registry. Listed below are organizations that treat <strong>npm itself as core infrastructure</strong>, including this site.</>,
    cuberootDesc: <>The repo root has a <code>package.json</code>, and <code>core/</code> is a workspace root with 11 per-package <code>package.json</code> files. Day to day we type <code>pnpm install</code>, but pnpm pulls tarballs from <code>registry.npmjs.org</code> over the npm protocol.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>By 2026 npm doesn't really need to defend its position: provenance + sigstore add provable supply-chain, JSR (Deno's new registry) is trying but is ~1000x smaller, and the AI-tool generation emits <code>npm install</code> by default. The registry stays still; the clients keep iterating.</>,
  },
  heroStats: [
    { num: '4M', unit: '+', zh: <>注册包总数 <em>npmjs.com 2026-05</em></>, en: <>packages on the registry <em>npmjs.com 2026-05</em></>
    },
    { num: '300B', unit: '+', zh: <>周下载量量级 <em>2026 估算</em></>, en: <>weekly downloads order <em>2026 estimate</em></>
    },
    { num: '11', unit: '.14', zh: <>当前 CLI 版本 <em>2026-05-08 · v11.14.1</em></>, en: <>current CLI version <em>2026-05-08 · v11.14.1</em></>
    },
    { num: '16', unit: 'y', zh: <>从 2010 至今 <em>JS 包源不变</em></>, en: <>since 2010 <em>still the JS package source</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>npm 来自 Isaac Schlueter 2009 年的一个 personal project。当时 Node 刚发布几个月, Ryan Dahl 把"包管理"这件事明确推给社区, 所以 Schlueter (他自己是 Node core 团队成员) 写了 npm。雏形 2009 下半年提交, 2010 年 1 月公开发布 1.0。最开始的设计就立住了:每个包一个 <code>package.json</code> manifest, 一个 .tar.gz tarball, 版本走 semver, 解析按 semver range。这套格式十六年没动。</p>
        <p>2014 年 npm 公司化 (npm Inc.), Schlueter 当 CEO, registry 从 CouchDB 慢慢迁到生产基础设施。2016 年 3 月发生<strong>左 pad 事件</strong>:作者 Azer Koçulu 因跟另一个包名 (kik) 撞名仲裁不爽, unpublish 了自己 25 个包, 其中包括 11 行代码的 <code>left-pad</code>。这个小包是 React / Babel / Webpack 的间接依赖, unpublish 后整个 JS 生态构建瘫痪几小时。npm 当晚改了 unpublish 政策:发布 24 小时后不能撤, 改成"deprecate"。这是 supply-chain 思维进 JS 圈的起点。</p>
        <p>2020 年 3 月 GitHub (即 Microsoft) 收购 npm Inc.。当时社区紧张 —— 担心免费层缩水, 担心私有包定价被卡。结果反而是:免费层没动, 私有包合并进 GitHub Packages 作为额外选项, registry 稳定性提升, supply-chain 安全的投入 (audit / provenance / sigstore 集成) 反而加速。2024 年 provenance attestations 在 GitHub Actions 里成默认 —— "这个 package 真的从这个 repo 在这次 build 出来" 第一次可证明。pnpm / yarn / bun 在过去十年陆续出现, 但都跑同一个 registry, 同一个 package.json, 同一份 semver。Schlueter 那套设计当年看是临时方案, 十六年后变成 JS 生态最不可替换的一块。</p>
      </>
    ),
    en: (
      <>
        <p>npm started as a 2009 personal project by Isaac Schlueter. Node had been public only a few months, and Ryan Dahl had explicitly punted package management to the community — so Schlueter (then on the Node core team) wrote npm. The prototype landed in late 2009; 1.0 went public in January 2010. The design crystallized fast: each package has a <code>package.json</code> manifest, ships as a .tar.gz tarball, follows semver, and resolves against semver ranges. That format hasn't changed in sixteen years.</p>
        <p>npm Inc. formed in 2014, with Schlueter as CEO; the registry slowly migrated from CouchDB onto serious production infrastructure. March 2016 brought the <strong>left-pad incident</strong>: author Azer Koçulu, unhappy with a name-dispute arbitration over the package "kik," unpublished all 25 of his packages — including the 11-line <code>left-pad</code>. That tiny module was an indirect dependency of React / Babel / Webpack; for several hours, JS-ecosystem builds across the planet broke. npm changed unpublish policy that same night: after 24 hours, you can no longer pull a package — only deprecate it. That was the entry point of supply-chain thinking into the JS world.</p>
        <p>In March 2020, GitHub (i.e. Microsoft) acquired npm Inc. The community was nervous — would the free tier shrink, would private-package pricing tighten? The opposite happened: free tier untouched, private packages got merged into GitHub Packages as an additional option, registry reliability improved, and supply-chain investment (audit, provenance, sigstore integration) actually accelerated. By 2024, provenance attestations were available by default in GitHub Actions — "this package was really built from this repo in this run" is now cryptographically provable. pnpm / yarn / bun all appeared along the way, but every one of them runs against the same registry, the same package.json, the same semver. What looked like a temporary scaffold in 2010 turned out to be the least-replaceable layer of the JS ecosystem.</p>
      </>
    ),
  },
  history: [
    { year: '2009·09', zh: { title: <>Schlueter 起意</>, desc: <>Node 刚发布几个月, 没有官方包源。Isaac Schlueter (Node core 成员) 开始写 npm, 设计:每包一个 package.json + 一个 tarball + semver。</> }, en: { title: <>Schlueter sketches npm</>, desc: <>Node has been public only a few months and has no official package source. Isaac Schlueter (then on Node core) starts npm; the design is: one package.json + one tarball + semver per package.</> } },
    { year: '2010·01', zh: { title: <>npm 1.0 公开</>, desc: <>1 月正式发布。当时 Node 是 v0.1.x, npm 跟着 Node 早期一起涨。package.json 这个名字从此固定。</> }, en: { title: <>npm 1.0 ships</>, desc: <>January release. Node is still at v0.1.x; npm grows alongside it. The name "package.json" is locked in from here on.</> } },
    { year: '2014·02', zh: { title: <>npm Inc. 成立</>, desc: <>Schlueter 当 CEO, registry 从 CouchDB 原型逐步迁到 production infra。从此 npm 不再是一个人的副业。</> }, en: { title: <>npm Inc. founded</>, desc: <>Schlueter takes CEO; the registry migrates off its CouchDB prototype to production infrastructure. npm stops being a side project.</> } },
    { year: '2014·11', zh: { title: <>~100k 包</>, desc: <>Node + npm 生态进入加速期。Express / Browserify / Grunt / Gulp 时代, registry 第一次开始扛真量。</> }, en: { title: <>~100k packages</>, desc: <>Node + npm enter their acceleration phase. The Express / Browserify / Grunt / Gulp era. The registry handles serious traffic for the first time.</> } },
    { year: '2016·03', highlight: true, zh: { title: <>left-pad 事件</>, desc: <>Azer Koçulu 因 kik 名字仲裁 unpublish 自己 25 个包, 11 行的 <code>left-pad</code> 是 React / Babel / Webpack 的间接依赖, 全球构建挂几小时。npm 改 unpublish 政策:发布 24 小时后只能 deprecate, 不能撤。</> }, en: { title: <>The left-pad incident</>, desc: <>Azer Koçulu unpublishes 25 packages after a "kik" naming arbitration. The 11-line <code>left-pad</code> is an indirect dep of React / Babel / Webpack — global builds break for hours. npm changes the unpublish policy: after 24 hours you can only deprecate, not remove.</> } },
    { year: '2017·05', zh: { title: <>npm 5 + package-lock.json</>, desc: <>yarn 已上线一年半, 用 yarn.lock 把可复现性做扎实了。npm 5 跟上, 加 package-lock.json。从此 "lockfile 是标配" 成为共识。</> }, en: { title: <>npm 5 + package-lock.json</>, desc: <>Yarn has been out for 18 months with yarn.lock owning reproducibility. npm 5 catches up by adding package-lock.json. "A lockfile is mandatory" becomes consensus.</> } },
    { year: '2018·05', zh: { title: <>npm 6 + npm audit</>, desc: <><code>npm audit</code> 把已知漏洞扫描内建。post-event-stream 时代的标配 —— 装包前先看 CVE。</> }, en: { title: <>npm 6 + npm audit</>, desc: <><code>npm audit</code> ships built-in CVE scanning. A post-event-stream-era default: scan known vulns before you install.</> } },
    { year: '2020·03', highlight: true, zh: { title: <>GitHub (Microsoft) 收购</>, desc: <>3 月公告, npm Inc. 并入 GitHub。社区紧张过, 但免费层没动, 私有包合并进 GitHub Packages 作为可选, registry 稳定性反而提升。</> }, en: { title: <>GitHub (Microsoft) acquires npm</>, desc: <>March announcement; npm Inc. folds into GitHub. The community is wary, but the free tier stays untouched, private packages merge into GitHub Packages as an optional layer, and registry reliability improves.</> } },
    { year: '2021·02', zh: { title: <>npm 7 GA + workspaces</>, desc: <>真正的 workspace 支持落地, 之前要靠 lerna 拼。同时 peer dependencies 默认自动安装, 跟 pnpm / yarn 对齐。</> }, en: { title: <>npm 7 GA + workspaces</>, desc: <>Real workspace support arrives — previously the job of lerna. Peer dependencies now install automatically by default, matching pnpm / yarn.</> } },
    { year: '2022·11', zh: { title: <>npm 9 — 严 peer deps</>, desc: <>peer dep 不满足直接报错而不是 warn。短期阵痛, 长期对 supply-chain 健康。</> }, en: { title: <>npm 9 — strict peer deps</>, desc: <>Unsatisfied peer deps now fail instead of warning. Short-term pain, long-term supply-chain hygiene.</> } },
    { year: '2024·04', zh: { title: <>provenance attestations</>, desc: <><code>npm publish --provenance</code> 把"这个包从哪个 GitHub repo 在哪次 build 出来"用 sigstore 签上, 在 npmjs.com 包页可验证。supply-chain 第一次有可证明的链路。</> }, en: { title: <>Provenance attestations</>, desc: <><code>npm publish --provenance</code> signs "which GitHub repo, which CI run" via sigstore — verifiable on the package page on npmjs.com. The first cryptographically provable supply-chain link.</> } },
    { year: '2025·09', zh: { title: <>npm 11</>, desc: <>跟随 Node 24 LTS 发布, Node 20+ 强制, 大量内部依赖升级。catalog 类协议讨论开始进 npm 主线 (向 pnpm 取经)。</> }, en: { title: <>npm 11</>, desc: <>Released alongside Node 24 LTS. Requires Node 20+; many internal deps bumped. Catalog-style protocol proposals (cribbing from pnpm) enter the npm mainline.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>11.14.1 / 当前 CLI</>, desc: <>2026-05-08 发布。注册表 ~400 万包, 周下载几千亿次。本仓库 <code>core/package.json</code> 的 <code>packageManager</code> 锁的是 pnpm, 但所有包仍从 registry.npmjs.org 拉。</> }, en: { title: <>11.14.1 / current CLI</>, desc: <>Released 2026-05-08. Registry at ~4M packages, hundreds of billions of weekly downloads. This repo's <code>core/package.json</code> pins pnpm via <code>packageManager</code>, but every dependency still comes from registry.npmjs.org.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>package.json</>, desc: <>每个包的身份证。name + version 必填, 加 dependencies / scripts / exports / engines 等几十个可选字段。十六年没大改。</> }, en: { title: <>package.json</>, desc: <>Every package's identity card. name + version required; dependencies / scripts / exports / engines and dozens of optional fields. Sixteen years, almost no breaking changes.</> }, code: <code>{'{'}{'\n'}  {p('"name"')}: {s('"@cuberoot/client"')},{'\n'}  {p('"version"')}: {s('"0.1.0"')},{'\n'}  {p('"type"')}: {s('"module"')},{'\n'}  {p('"dependencies"')}: {'{'}{'\n'}    {p('"react"')}: {s('"^19.2.0"')}{'\n'}  {'}'}{'\n'}{'}'}</code> },
    { tag: 'B', zh: { title: <>semver range</>, desc: <><code>^1.2.3</code> = 兼容更新到 &lt;2.0.0 (锁主版本), <code>~1.2.3</code> = 兼容到 &lt;1.3.0 (锁次版本), <code>1.2.3</code> = 完全锁定。lockfile 把这套 range 解析后的具体版本记下。</> }, en: { title: <>semver range</>, desc: <><code>^1.2.3</code> = compatible up to &lt;2.0.0 (major locked), <code>~1.2.3</code> = up to &lt;1.3.0 (minor locked), <code>1.2.3</code> = exact pin. The lockfile records the resolved version after parsing.</> }, code: <code>{p('"react"')}: {s('"^19.2.0"')}    {c('// 19.x.x')}{'\n'}{p('"react"')}: {s('"~19.2.0"')}    {c('// 19.2.x')}{'\n'}{p('"react"')}: {s('"19.2.0"')}     {c('// exactly 19.2.0')}</code> },
    { tag: 'C', zh: { title: <>dependencies 三类</>, desc: <><strong>dependencies</strong> 运行时必须、<strong>devDependencies</strong> 只 build / test 用、<strong>peerDependencies</strong> 由宿主提供 (插件常用)。npm 7+ 默认自动装 peer。</> }, en: { title: <>Three kinds of deps</>, desc: <><strong>dependencies</strong> = runtime-required, <strong>devDependencies</strong> = build / test only, <strong>peerDependencies</strong> = provided by the host (typical for plugins). npm 7+ auto-installs peers.</> }, code: <code>{p('"dependencies"')}: {'{ '}{p('"hono"')}: {s('"^4"')} {'}'},{'\n'}{p('"devDependencies"')}: {'{ '}{p('"vite"')}: {s('"^8"')} {'}'},{'\n'}{p('"peerDependencies"')}: {'{ '}{p('"react"')}: {s('"^19"')} {'}'}</code> },
    { tag: 'D', zh: { title: <>lockfile</>, desc: <><code>package-lock.json</code> (npm) / <code>pnpm-lock.yaml</code> / <code>yarn.lock</code> 都做同一件事:把 semver range 解析出来的具体版本 + 完整依赖树固定, 让<strong>每次 install 拿一样的字节</strong>。</> }, en: { title: <>The lockfile</>, desc: <><code>package-lock.json</code> (npm) / <code>pnpm-lock.yaml</code> / <code>yarn.lock</code> all do the same thing: pin the resolved versions + full dependency tree so <strong>every install produces the same bytes</strong>.</> }, code: <code>{p('"node_modules/react"')}: {'{'}{'\n'}  {p('"version"')}: {s('"19.2.0"')},{'\n'}  {p('"resolved"')}: {s('"https://reg.../react-19.2.0.tgz"')},{'\n'}  {p('"integrity"')}: {s('"sha512-..."')}{'\n'}{'}'}</code> },
    { tag: 'E', zh: { title: <>npx / npm exec</>, desc: <>从 registry 临时拉一个 CLI 跑一次, 不装进当前项目。create-vite / tsx / vercel 这种"一次性脚本"全靠它。pnpm 的对应叫 <code>pnpm dlx</code>。</> }, en: { title: <>npx / npm exec</>, desc: <>Pull a CLI from the registry, run it once, no install footprint. <code>create-vite</code> / <code>tsx</code> / <code>vercel</code> all flow through it. pnpm's equivalent is <code>pnpm dlx</code>.</> }, code: <code>$ {f('npx')} create-vite my-app{'\n'}$ {f('npx')} tsx ./scripts/seed.ts{'\n'}$ {f('npm')} exec -- prettier .</code> },
    { tag: 'F', zh: { title: <>dist-tags</>, desc: <>给同一个 package 起多个移动标签:<code>latest</code> (默认安装目标) / <code>next</code> / <code>beta</code> / <code>canary</code>。<code>npm install react@next</code> 装的是 next 标签当前指向的那版。</> }, en: { title: <>dist-tags</>, desc: <>Move tags pointing at versions of the same package: <code>latest</code> (default install target) / <code>next</code> / <code>beta</code> / <code>canary</code>. <code>npm install react@next</code> resolves through whatever <code>next</code> currently points at.</> }, code: <code>$ {f('npm')} dist-tag ls react{'\n'}{c('// latest: 19.2.0')}{'\n'}{c('// next:   20.0.0-rc.1')}</code> },
    { tag: 'G', zh: { title: <>workspaces</>, desc: <>npm 7 起 monorepo 一等公民:根 <code>package.json</code> 的 <code>workspaces</code> 字段 + 子目录的 <code>package.json</code>。本仓库用 pnpm 的 workspace, 协议形状一样。</> }, en: { title: <>workspaces</>, desc: <>Since npm 7, monorepos are first-class: a root <code>package.json</code> with a <code>workspaces</code> field + sub-package <code>package.json</code> files. This repo uses pnpm's workspaces — same protocol shape.</> }, code: <code>{'{'}{'\n'}  {p('"name"')}: {s('"root"')},{'\n'}  {p('"private"')}: {v('true')},{'\n'}  {p('"workspaces"')}: [{s('"packages/*"')}]{'\n'}{'}'}</code> },
    { tag: 'H', zh: { title: <>engines + os + cpu</>, desc: <>声明这个包要求的 Node 版本、操作系统、CPU 架构。<code>npm install</code> 默认 warn 不阻塞, 但 CI 里加 <code>--engine-strict</code> 就硬卡。</> }, en: { title: <>engines + os + cpu</>, desc: <>Declare required Node version, OS, and CPU architecture. <code>npm install</code> warns by default; pass <code>--engine-strict</code> in CI to make it a hard error.</> }, code: <code>{p('"engines"')}: {'{ '}{p('"node"')}: {s('">=22"')} {'}'},{'\n'}{p('"os"')}: [{s('"linux"')}, {s('"darwin"')}],{'\n'}{p('"cpu"')}: [{s('"x64"')}, {s('"arm64"')}]</code> },
  ],
  whyCards: [
    { icon: '⬢', zh: { title: <>注册表 + 格式 ≠ 客户端</>, desc: <>用 pnpm 装包不代表"不用 npm"。tarball 还是从 <code>registry.npmjs.org</code> 来, 协议还是 npm 定的, package.json 还是 npm 的格式。客户端是可换的, 这套底座不是。</> }, en: { title: <>Registry + spec ≠ CLI</>, desc: <>Using pnpm doesn't mean "not using npm." The tarballs still come from <code>registry.npmjs.org</code>, the protocol is still npm's, package.json is still npm's format. The client is swappable; the substrate isn't.</> }, code: <>{c('// pnpm install hono')}{'\n'}{c('// → GET registry.npmjs.org/hono')}</> },
    { icon: '⌬', zh: { title: <>400 万包谁也搬不动</>, desc: <>2026 年 registry 上 4M+ 包, 周下载几千亿次。"我们换一个 registry" 听起来简单, 但这意味着<strong>每一个</strong>依赖、依赖的依赖都得重新发布。物理上不可能。</> }, en: { title: <>4M+ packages no one can move</>, desc: <>2026: ~4M packages on the registry, hundreds of billions of weekly downloads. "Let's switch registries" sounds simple until you realize <strong>every</strong> dep, and every transitive dep, would need re-publishing. Physically impossible.</> }, code: <>{c('// 4M packages × dep graphs')}{'\n'}{c('// = unmoveable substrate')}</> },
    { icon: '⎇', zh: { title: <>package.json 成跨语言标准</>, desc: <>deno.json 抄了一半, cargo.toml 的 [dependencies] 字段灵感来自这里, bun.lock 跟 npm 协议 1:1 兼容。Schlueter 当年定的字段长成了行业默认。</> }, en: { title: <>package.json went cross-language</>, desc: <>deno.json copies half of it; cargo.toml's [dependencies] section was inspired by it; bun.lock is 1:1 compatible with the npm protocol. The fields Schlueter chose in 2010 are now industry default.</> }, code: <>{c('// deno.json')}{'\n'}{'{ '}{p('"imports"')}: {'{ '}{p('"react"')}: {s('"npm:react@^19"')} {'}'} {'}'}</> },
    { icon: '⌖', zh: { title: <>semver 已是行业事实标准</>, desc: <>Major.Minor.Patch 这套 npm 1.0 就锁的版本号语义, 后来被 cargo / pip / composer / gem 全抄。它的明确语义把"什么时候算 breaking" 这种本来要写在 readme 的话, 变成了一个数字。</> }, en: { title: <>semver is the de-facto standard</>, desc: <>Major.Minor.Patch was locked into npm 1.0 and is now copied by cargo / pip / composer / gem. The explicit semantics turn "is this a breaking change?" from prose in a README into a number.</> }, code: <>{c('// breaking → major bump')}{'\n'}{c('// feature → minor bump')}{'\n'}{c('// fix     → patch bump')}</> },
    { icon: '⌗', zh: { title: <>publish 一键, 全球 CDN</>, desc: <><code>npm publish</code> 把 tarball 推上去, 几分钟内全球 CDN 边缘节点都有。<code>npm install</code> 命中最近的边缘缓存。这一套对单个开发者是免费的。</> }, en: { title: <>One-command publish, global CDN</>, desc: <><code>npm publish</code> pushes a tarball; within minutes every CDN edge has it. <code>npm install</code> hits the nearest edge cache. The whole pipeline is free for individual developers.</> }, code: <>$ {f('npm')} publish{'\n'}{c('// → global CDN in minutes')}</> },
    { icon: '⏚', zh: { title: <>免费层不缩水, provenance 加固</>, desc: <>GitHub (Microsoft) 2020 收购后社区担心的"免费层缩水"没发生。反而是 supply-chain 投入加速 —— audit / provenance / sigstore 集成全是收购后做的。</> }, en: { title: <>Free tier intact, provenance hardened</>, desc: <>The "free tier shrinkage" the community feared after GitHub (Microsoft) acquired in 2020 never happened. The opposite: supply-chain investment accelerated — audit, provenance, sigstore integration were all post-acquisition.</> }, code: <>$ {f('npm')} publish --provenance{'\n'}{c('// signed by GitHub Actions')}</> },
    { icon: '⌁', zh: { title: <>AI 工具一代默认输出 npm</>, desc: <>Claude Code / Cursor / v0 / Bolt 在生成项目时几乎全部第一个命令是 <code>npm install</code> 或 <code>pnpm install</code>。LLM 训练集里 package.json 是最常见的 manifest 之一, "AI 写代码默认从 npm 装包" 巩固了它的位置。</> }, en: { title: <>The AI generation defaults to npm</>, desc: <>Claude Code / Cursor / v0 / Bolt almost always emit <code>npm install</code> or <code>pnpm install</code> as the first command of a new project. LLM training sets are saturated with package.json — "AI-generated code installs from npm" cements its position.</> }, code: <>{c('// "Set up a Node API"')}{'\n'}{c('// LLM step 1: npm install')}</> },
    { icon: '⚐', zh: { title: <>JSR 等挑战者体量差 1000x</>, desc: <>Deno 团队 2024 起力推 JSR (新 registry, 原生 ESM + 强类型)。设计更现代但体量目前在几万包级别, 跟 npm 的 4M 差三个数量级。短期撬不动。</> }, en: { title: <>JSR and the like are ~1000x smaller</>, desc: <>The Deno team has been pushing JSR (a new registry, native ESM + strong types) since 2024. The design is more modern, but it's at ~tens of thousands of packages — three orders of magnitude behind npm's 4M. Not movable in the short term.</> }, code: <>{c('// JSR    ~tens of k pkgs')}{'\n'}{c('// npm    4M+ pkgs')}</> },
  ],
  adopters: [
    { name: 'Node.js', href: 'https://nodejs.org', highlight: true, zhNote: '官方 runtime, 自带 npm CLI 出厂', enNote: 'Official runtime — ships the npm CLI in the box' },
    { name: 'GitHub (Microsoft)', href: 'https://github.com/npm', highlight: true, zhNote: '2020 收购 npm Inc., registry 现归 GitHub 运营', enNote: 'Acquired npm Inc. in 2020; the registry is now operated by GitHub' },
    { name: 'TypeScript / VS Code', href: 'https://www.typescriptlang.org', highlight: true, zhNote: 'tsc 自己从 npm 装 + VS Code 扩展走 npm registry', enNote: 'tsc installs from npm; VS Code extension build chain rides the npm registry' },
    { name: 'Vercel · Next.js', href: 'https://nextjs.org', zhNote: '部署流水线核心是 npm install', enNote: 'Deploy pipeline core is npm install' },
    { name: 'Cloudflare Workers', href: 'https://workers.cloudflare.com', zhNote: 'Wrangler build / deploy 都拉 npm 包', enNote: 'Wrangler build / deploy both pull from npm' },
    { name: 'Netlify', href: 'https://netlify.com', zhNote: '所有 build agent 跑 npm / pnpm install', enNote: 'Every build agent runs npm / pnpm install' },
    { name: 'JetBrains · IntelliJ', href: 'https://jetbrains.com', zhNote: 'WebStorm / IDEA 把 npm 当一等 task runner', enNote: 'WebStorm / IDEA treat npm as a first-class task runner' },
    { name: 'GitHub Actions', href: 'https://github.com/features/actions', zhNote: 'setup-node / cache 都围绕 npm 协议', enNote: 'setup-node / cache are organized around the npm protocol' },
    { name: 'jsDelivr · unpkg', href: 'https://www.jsdelivr.com', zhNote: 'npm 包的全球 CDN 镜像, 给 ESM CDN 兜底', enNote: 'Global CDN mirrors of npm packages — the backbone of ESM CDNs' },
    { name: 'Snyk · Socket', href: 'https://snyk.io', zhNote: 'supply-chain 安全公司, 全部围绕 npm 生态', enNote: 'Supply-chain security companies built entirely around the npm ecosystem' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 ~50 个 npm 包, 通过 pnpm 装 + lock', enNote: 'This site — ~50 npm packages, installed and locked via pnpm' },
  ],
  outlook: [
    { tag: <>HOT · 2024</>, hot: true, big: true, zh: { title: <>provenance attestations 改写 supply-chain</>, body: <><p><code>npm publish --provenance</code> 用 sigstore 把"这个 package 从哪个 GitHub repo 在哪次 CI run 出来"签上, 在 npmjs.com 的包页可点开验证。<strong>第一次有可证明的供应链</strong>, 而不是"作者说自己是好的"。</p><p>2026 年 React / Vite / Next 等头部包默认 provenance, 整条依赖图慢慢覆盖。下一步是 npm 在 install 层加可选的"只装 provenance 过的包"开关, 给企业用户一个明确的安全边界。</p></> }, en: { title: <>Provenance attestations rewrite supply-chain</>, body: <><p><code>npm publish --provenance</code> uses sigstore to sign "which GitHub repo, which CI run" — verifiable from the package page on npmjs.com. <strong>The first cryptographically provable supply chain</strong>, replacing "the author claims to be honest."</p><p>By 2026, React / Vite / Next and other headline packages default to provenance, and the rest of the graph follows. Next step: an opt-in "install only provenance-attested packages" flag at install time — a clear security boundary for enterprises.</p></> } },
    { tag: 'JSR', zh: { title: <>JSR (Deno) 想挑战, 但体量差三个数量级</>, body: <><p>Deno 2024 推 JSR:原生 ESM-only、TS 类型一等公民、按 GitHub 账号 namespace。设计明显更现代, 但 2026-05 还在几万包级别, npm 是 4M+。短期不动 npm 的根基, 但长期可能蚕食"新发布的 ESM-only 工具"那块。</p></> }, en: { title: <>JSR (Deno) tries, but ~1000x smaller</>, body: <><p>Deno's JSR (2024): native ESM-only, types as first-class, GitHub-account namespacing. The design is clearly more modern. As of 2026-05 it's at ~tens of thousands of packages versus npm's 4M+ — three orders of magnitude behind. Won't move npm's substrate in the short term, but may slowly take the "newly-published ESM-only tooling" slice.</p></> } },
    { tag: 'CLIENTS', zh: { title: <>客户端竞争激化, registry 不动</>, body: <><p>pnpm 在 monorepo 拿下默认, Bun install 在新项目里增速最快, yarn 4 (PnP) 在大企业还有阵地, npm CLI 自身也每个 major 在加 workspaces / catalog 类协议。<strong>客户端层卷</strong>, 但 registry 不变。这种"协议稳、实现可换"的状态是协议设计最理想的形态。</p></> }, en: { title: <>Client competition heats up; registry stays still</>, body: <><p>pnpm has the monorepo default, Bun install is the fastest-growing on new projects, Yarn 4 (PnP) still holds enterprise ground, and the npm CLI itself bumps in workspaces / catalog protocols every major. <strong>The client layer churns</strong>, but the registry doesn't. "Protocol stable, implementations swappable" is the ideal end-state of a protocol design.</p></> } },
    { tag: <>AI</>, zh: { title: <>AI 工具一代把 npm 巩固成默认</>, body: <><p>Claude Code / Cursor / v0 / Bolt 生成项目时几乎一边倒输出 <code>npm install</code> 或 <code>pnpm install</code>。LLM 训练集里 package.json 出现频率极高, "AI 默认从 npm 装" 反过来给 npm 又加一层护城河。Deno / Bun / JSR 在 LLM 输出里出现频率明显更低。</p></> }, en: { title: <>AI generation cements npm as default</>, body: <><p>Claude Code / Cursor / v0 / Bolt overwhelmingly emit <code>npm install</code> or <code>pnpm install</code> when scaffolding. package.json is one of the densest manifest patterns in LLM training data, so "AI defaults to installing from npm" adds another moat. Deno / Bun / JSR show up noticeably less often in LLM output.</p></> } },
    { tag: <>WORKSPACES</>, zh: { title: <>workspaces 标准化, lerna 退场</>, body: <><p>npm 7 加 workspaces 之后, lerna 的核心价值 (跨包 link + 并行 script) 就被吃掉了。2026 年 lerna 还活但只是边缘工具, monorepo 工作流默认走 npm / pnpm / yarn 原生 workspace + turbo / nx 做编排。整套生态干净了。</p></> }, en: { title: <>Workspaces standardized; lerna retires</>, body: <><p>Once npm 7 shipped workspaces, lerna's core value (cross-package link + parallel scripts) was absorbed. In 2026 lerna still exists but as a peripheral tool — monorepo workflows default to npm / pnpm / yarn native workspaces + turbo / nx for orchestration. The ecosystem is cleaner.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本仓库的根有一个 <code>package.json</code> (主要是给静态 HTML fork 留的占位), 真正的开发都在 <code>core/</code> 里。<code>core/package.json</code> 是 pnpm workspace 根, <code>packageManager</code> 字段锁 pnpm 版本, 同时声明 11 个 workspace 各有自己的 <code>package.json</code>。整个 monorepo 一份 <code>pnpm-lock.yaml</code> 锁所有版本。</p>
        <p>关键依赖一律走 npm registry:<code>react</code> / <code>react-dom</code> / <code>vite</code> / <code>hono</code> / <code>postgres</code> / <code>cubing</code> / <code>three</code> / <code>zustand</code> / <code>mp4box</code> / <code>@ffmpeg/ffmpeg</code> / <code>tsx</code> / <code>turbo</code> / <code>vitest</code> / <code>lucide-react</code> 等大约 50 个直接依赖, 加上间接依赖整棵图大概 1500 个包。每个都从 <code>registry.npmjs.org</code> 拉, pnpm 把它们硬链接进 <code>~/.local/share/pnpm/store</code> 全局去重。</p>
        <p>选 pnpm 不选 npm CLI 的理由很具体:硬链接省盘 (本机十几个 React 项目共享一份 react@19 的字节)、严格 node_modules 布局让 phantom dep 在 install 时就挂、<code>--filter</code> 选包跑 script 比 npm workspaces 体验好。但<strong>底层协议、tarball 来源、semver 解释、lockfile 概念都还是 npm 的</strong>。</p>
        <p>本仓库几乎不向 registry 发包 —— 11 个 workspace 全部标 <code>"private": true</code>, 仅供 monorepo 内部用 <code>workspace:*</code> 链接。例外情况下要发 (比如把 <code>@cuberoot/visualcube</code> 抽出去给第三方用), 命令是 <code>pnpm publish</code>, 走的还是 npm publish 协议, 推到 <code>registry.npmjs.org</code> 的 @cuberoot 组织 namespace 下。所有 npm 协议的事情都没绕开。</p>
      </>
    ),
    en: (
      <>
        <p>The repo root has a <code>package.json</code> (mostly a placeholder for the static-HTML forks); real development lives under <code>core/</code>. <code>core/package.json</code> is the pnpm workspace root — its <code>packageManager</code> field pins the pnpm version and it declares 11 workspaces, each with its own <code>package.json</code>. One <code>pnpm-lock.yaml</code> locks every version across the whole monorepo.</p>
        <p>All key dependencies flow through the npm registry: <code>react</code> / <code>react-dom</code> / <code>vite</code> / <code>hono</code> / <code>postgres</code> / <code>cubing</code> / <code>three</code> / <code>zustand</code> / <code>mp4box</code> / <code>@ffmpeg/ffmpeg</code> / <code>tsx</code> / <code>turbo</code> / <code>vitest</code> / <code>lucide-react</code> — about 50 direct deps, ~1500 total in the resolved graph. Every one of them comes from <code>registry.npmjs.org</code>; pnpm hard-links them out of <code>~/.local/share/pnpm/store</code> to dedupe globally.</p>
        <p>Why pnpm-the-client, not the npm CLI: hard-linking saves disk (a dozen React projects share one copy of react@19 on this box), the strict node_modules layout catches phantom deps at install time, and <code>--filter</code> is more ergonomic than npm workspaces. But <strong>the underlying protocol, the tarball source, the semver semantics, and the lockfile concept are all still npm's</strong>.</p>
        <p>This repo barely publishes — all 11 workspaces are marked <code>"private": true</code> and only link to each other via <code>workspace:*</code>. If we ever extract one for outside use (say, breaking out <code>@cuberoot/visualcube</code>), the command is <code>pnpm publish</code>, riding the npm publish protocol, going to the @cuberoot org namespace on <code>registry.npmjs.org</code>. Nothing about the npm protocol gets bypassed.</p>
      </>
    ),
  },
  links: [
    { label: 'npmjs.com', href: 'https://www.npmjs.com' },
    { label: 'GitHub · npm/cli', href: 'https://github.com/npm/cli' },
    { label: 'npm docs', href: 'https://docs.npmjs.com' },
    { label: 'semver spec', href: 'https://semver.org' },
    { label: 'left-pad incident write-up', href: 'https://www.theregister.com/2016/03/23/npm_left_pad_chaos/' },
  ],
};

export default NPM;
