import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, s, n, f, p, c, t } from '../_lib/stack_tool_types';

// ─── nuqs 2.8.9 ─────────────────────────────────────────────────────────────

export const NUQS: StackTool = {
  slug: 'nuqs',
  name: 'nuqs',
  version: '2.8.9',
  since: '2020-05',
  group: 'frontend',
  accent: '#F59E0B',
  bright: '#FBBF24',
  glyph: '?=',
  floats: ['useQueryState', 'useQueryStates', 'parseAsInteger', 'parseAsBoolean', 'parseAsStringEnum', 'parseAsArrayOf', 'withDefault', 'withOptions', 'createSearchParamsCache', 'createSerializer', 'NuqsAdapter', 'shallow', "history: 'push'", 'throttleMs', 'clearOnDefault'],
  zh: {
    tagline: '像 useState, 但状态存在 URL query 里',
    role: '全站页内状态(tab / 筛选 / 排序 / 搜索 / 浮层)进 URL 的唯一方式。33 个页面在用, CI 强制禁裸 history.pushState。',
    heroSub: <>页内的 tab、筛选、搜索词应该进 URL —— 这样刷新不丢、链接能分享、浏览器前进后退能用。但自己写 <code>history.pushState</code> + 监听 <code>popstate</code> + 手动 parse query string 既啰嗦又容易错。François Best 从 2020 年的 <code>next-usequerystate</code> 一路做到今天的 <strong>nuqs</strong>:<strong>一个像 <code>useState</code> 的 hook, 返回值类型由 parser 决定, 状态自动双向同步到 URL query</strong>, 前进后退、刷新、分享全部免费。</>,
    whatDesc: <>nuqs 是一个 <strong>约 6 kB gzip 的 React 状态库</strong>, 把组件状态存进 URL 的 search params。核心是 <code>useQueryState</code> / <code>useQueryStates</code> 两个 hook + 一套类型安全 parser (<code>parseAsInteger</code> / <code>parseAsBoolean</code> / <code>parseAsStringEnum</code> / <code>parseAsArrayOf</code> …)。底层通过 adapter 适配不同路由器, 所以它框架无关 —— Next.js / React Router / Remix / TanStack Router 用同一份 API。</>,
    historyDesc: <>2020 年作为 <code>next-usequerystate</code> 起步, 只服务 Next.js Pages Router。Next 13 App Router 出来后跟着适配, 2023 年底改名 nuqs, 2024 年 10 月的 2.0 重写成框架无关的 adapter 架构 —— 从"Next 的一个工具"变成"React 生态的 URL 状态标准件"。</>,
    conceptsTitle: 'hook + parser + adapter',
    conceptsDesc: <>可观察 API 很小:<code>useQueryState</code> 管单个 param、<code>useQueryStates</code> 管一组、parser 决定每个 param 的类型与序列化、<code>withOptions</code> 控后退栈与节流、<code>NuqsAdapter</code> 在 root 挂一次接路由器。服务端再有 <code>createSearchParamsCache</code> 给 RSC 用。</>,
    whyDesc: <>2026 年要把状态放进 URL, 选 nuqs 而不是手写 history, 是因为这四件事一起成立:<strong>API 像 useState</strong>、<strong>parser 给类型安全</strong>、<strong>前进后退自动同步</strong>、<strong>框架无关一份代码</strong>。手写 <code>pushState</code> + <code>popstate</code> 一样都拿不全。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>nuqs 官方一等 adapter 覆盖 Next.js (app + pages) / React SPA / Remix / React Router v6+v7 / TanStack Router (实验), GitHub 上 10k+ star。它是 Next.js 社区里"search params 状态"事实上的首选。本站 33 个页面全部走它。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>2.x 持续补 adapter (React Router v7 / TanStack Router) 和 RSC 侧的 <code>createSearchParamsCache</code>。方向很清楚:让"URL 即状态"在所有 React 路由器上写法一致, 同时跟上 server component 的类型安全边界。</>,
  },
  en: {
    tagline: 'Like useState, but stored in the URL query string',
    role: 'The single way page-level state (tabs / filters / sort / search / overlays) goes into the URL site-wide — 33 pages use it, CI forbids raw history.pushState.',
    heroSub: <>A page's tabs, filters, and search terms belong in the URL — so a refresh keeps them, a link shares them, and back/forward just works. But hand-rolling <code>history.pushState</code> + a <code>popstate</code> listener + manual query-string parsing is verbose and error-prone. François Best took <code>next-usequerystate</code> (2020) all the way to today's <strong>nuqs</strong>: <strong>a <code>useState</code>-like hook whose return type is decided by a parser, with state synced both ways to the URL query</strong> — back/forward, refresh, and sharing all for free.</>,
    whatDesc: <>nuqs is a <strong>~6 kB gzipped React state library</strong> that stores component state in the URL's search params. The core is two hooks — <code>useQueryState</code> / <code>useQueryStates</code> — plus a set of type-safe parsers (<code>parseAsInteger</code> / <code>parseAsBoolean</code> / <code>parseAsStringEnum</code> / <code>parseAsArrayOf</code> …). An adapter layer plugs into different routers, so it's framework-agnostic: Next.js / React Router / Remix / TanStack Router all share one API.</>,
    historyDesc: <>It started in 2020 as <code>next-usequerystate</code>, Next.js Pages Router only. It tracked Next 13's App Router, was renamed nuqs in late 2023, and the October 2024 2.0 rewrite went framework-agnostic with an adapter architecture — graduating from "a Next.js helper" into "the URL-state standard part for the React ecosystem."</>,
    conceptsTitle: 'hook + parser + adapter',
    conceptsDesc: <>The observable API is small: <code>useQueryState</code> for one param, <code>useQueryStates</code> for a group, a parser deciding each param's type and serialization, <code>withOptions</code> for the history stack and throttling, and <code>NuqsAdapter</code> mounted once at the root to wire up the router. On the server there's <code>createSearchParamsCache</code> for RSC.</>,
    whyDesc: <>Picking nuqs over hand-rolled history in 2026 is about four things being true at once: <strong>a useState-like API</strong>, <strong>type safety from parsers</strong>, <strong>back/forward synced automatically</strong>, <strong>one codebase across frameworks</strong>. Hand-writing <code>pushState</code> + <code>popstate</code> never gets all four.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>First-class official adapters cover Next.js (app + pages) / React SPA / Remix / React Router v6+v7 / TanStack Router (experimental), with 10k+ GitHub stars. It is the de-facto pick for "search-params state" in the Next.js community. All 33 of this site's such pages run on it.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>2.x keeps adding adapters (React Router v7 / TanStack Router) and the RSC-side <code>createSearchParamsCache</code>. The direction is clear: make "URL as state" read the same across every React router while keeping up with the server-component type-safety boundary.</>,
  },
  heroStats: [
    { num: '2', unit: '.8.9', zh: <>当前稳定 <em>2026-02 发布</em></>, en: <>current stable <em>shipped 2026-02</em></>
    },
    { num: '~6', unit: ' kB', zh: <>gzip 包大小 <em>nuqs.dev</em></>, en: <>gzipped bundle <em>nuqs.dev</em></> },
    { num: '10.5', unit: 'k', zh: <>GitHub stars <em>47ng/nuqs</em></>, en: <>GitHub stars <em>47ng/nuqs</em></> },
    { num: '33', zh: <>本站用它的页面 <em>useQueryState</em></>, en: <>pages on this site <em>useQueryState</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>nuqs 的起点是 2020 年 5 月, François Best (开源组织 47ng) 发布的 <code>next-usequerystate</code>。当时它只解决一个具体痛点:在 Next.js 里把一个组件状态存进 URL 的 query string, 用起来像 <code>useState</code>。名字直白 —— "Next 的 useQueryState"。</p>
        <p>之后几年它跟着 React / Next 的演进走:Next 13 把 App Router + React Server Components 推成主线, nuqs 跟着适配 <code>useSearchParams</code> / <code>router</code> 那套新 API;parser 体系 (<code>parseAsInteger</code> / <code>parseAsStringEnum</code> / <code>parseAsArrayOf</code> …) 逐步成型, 把"URL 里全是字符串"这件事用类型安全的方式封掉。2023 年底, 项目改名 <strong>nuqs</strong> (取 use<strong>Q</strong>uery<strong>S</strong>tate 的发音), 为脱离 Next 专属做铺垫。</p>
        <p>真正的分水岭是 2024 年 10 月的 <strong>2.0</strong>:整个库被重写成 <strong>adapter 架构</strong> —— 核心逻辑跟具体路由器解耦, Next.js (app + pages)、React SPA、Remix、React Router、TanStack Router 各写一个薄薄的 adapter 接进来。同一份 <code>useQueryState</code> API 从此跨框架通用, nuqs 从"Next 的一个工具"变成"React 生态里 URL 状态的标准件"。到 2026 年 2 月的 2.8.9, 它在 GitHub 上 10k+ star, 是 Next.js 社区处理 search params 的默认答案。</p>
      </>
    ),
    en: (
      <>
        <p>nuqs starts in May 2020, when François Best (the 47ng open-source org) released <code>next-usequerystate</code>. Back then it solved one specific pain: storing a component's state in the URL's query string inside Next.js, with a <code>useState</code>-like feel. The name was literal — "Next's useQueryState."</p>
        <p>Over the next few years it tracked React / Next's evolution: Next 13 pushed the App Router + React Server Components into the mainline, and nuqs adapted to that new <code>useSearchParams</code> / <code>router</code> surface. A parser system (<code>parseAsInteger</code> / <code>parseAsStringEnum</code> / <code>parseAsArrayOf</code> …) took shape, wrapping the "everything in a URL is a string" problem in a type-safe way. In late 2023 the project was renamed <strong>nuqs</strong> (the sound of use<strong>Q</strong>uery<strong>S</strong>tate), setting up the move beyond Next-only.</p>
        <p>The real watershed is the October 2024 <strong>2.0</strong>: the whole library was rewritten around an <strong>adapter architecture</strong> — the core decoupled from any specific router, with thin adapters for Next.js (app + pages), React SPA, Remix, React Router, and TanStack Router plugging in. The same <code>useQueryState</code> API now works across frameworks, graduating nuqs from "a Next.js helper" into "the URL-state standard part of the React ecosystem." By 2.8.9 in February 2026 it has 10k+ GitHub stars and is the default answer for search params in the Next.js community.</p>
      </>
    ),
  },
  history: [
    { year: '2020·05', zh: { title: <>next-usequerystate 首发</>, desc: <>François Best 在 47ng 下发布第一版, 只服务 Next.js Pages Router。一个 hook 把组件状态搬进 URL query, 用起来像 <code>useState</code>。</> }, en: { title: <>next-usequerystate ships</>, desc: <>François Best releases v1 under 47ng — Next.js Pages Router only. One hook moves component state into the URL query, with a <code>useState</code> feel.</> } },
    { year: '2022·10', zh: { title: <>跟进 App Router</>, desc: <>Next 13 推出 App Router + React Server Components, nuqs 跟着适配新的 <code>useSearchParams</code> / <code>router</code> API, 兼容 app 与 pages 两套。</> }, en: { title: <>Tracks the App Router</>, desc: <>Next 13 lands the App Router + React Server Components; nuqs adapts to the new <code>useSearchParams</code> / <code>router</code> API and supports both app and pages.</> } },
    { year: '2023·11', zh: { title: <>改名 nuqs</>, desc: <>npm 上以新名 <code>nuqs</code> 起步, 跟旧名 <code>next-usequerystate</code> 并行发 1.x。改名是为脱离 Next 专属做铺垫。</> }, en: { title: <>Renamed to nuqs</>, desc: <>Publishing begins under the new name <code>nuqs</code> on npm, releasing 1.x in parallel with the old <code>next-usequerystate</code>. The rename sets up the move beyond Next-only.</> } },
    { year: '2024·02', zh: { title: <>parser 体系成型</>, desc: <>1.17 一线:<code>parseAsInteger</code> / <code>parseAsBoolean</code> / <code>parseAsStringEnum</code> / <code>parseAsArrayOf</code> / <code>parseAsJson</code> 等内置 parser 把"URL 全是字符串"封成类型安全。</> }, en: { title: <>Parser system matures</>, desc: <>Around 1.17: built-in parsers (<code>parseAsInteger</code> / <code>parseAsBoolean</code> / <code>parseAsStringEnum</code> / <code>parseAsArrayOf</code> / <code>parseAsJson</code>) wrap the "URL is all strings" problem in type safety.</> } },
    { year: '2024·10', highlight: true, zh: { title: <>2.0 — 框架无关 adapter</>, desc: <>10 月 22 日 2.0.0。整库重写成 adapter 架构, 核心跟路由器解耦, Next / React SPA / Remix / React Router 各接一个 adapter。<code>next-usequerystate</code> 旧名停在 1.20。</> }, en: { title: <>2.0 — framework-agnostic adapters</>, desc: <>2.0.0 on Oct 22. The library is rewritten around adapters; the core decouples from the router, with Next / React SPA / Remix / React Router each plugging in. The old <code>next-usequerystate</code> name stops at 1.20.</> } },
    { year: '2024·11', zh: { title: <>adapter 矩阵铺开</>, desc: <>React Router v6 / v7、Remix、再到 TanStack Router 的 adapter 陆续落地, 加上 <code>NuqsTestingAdapter</code> 给单测用。一套 API 跨整个 React 路由生态。</> }, en: { title: <>Adapter matrix fills out</>, desc: <>Adapters for React Router v6 / v7, Remix, and then TanStack Router land in turn, plus <code>NuqsTestingAdapter</code> for unit tests. One API across the whole React routing ecosystem.</> } },
    { year: '2025', zh: { title: <>RSC 侧 server cache</>, desc: <><code>createSearchParamsCache</code> / <code>createSerializer</code> 给 React Server Components 一条类型安全读 searchParams 的通道, 服务端与客户端共用同一份 parser 定义。</> }, en: { title: <>Server cache for RSC</>, desc: <><code>createSearchParamsCache</code> / <code>createSerializer</code> give React Server Components a type-safe path to read searchParams, sharing one parser definition between server and client.</> } },
    { year: '2026·02', highlight: true, zh: { title: <>2.8.9 / 当前稳定</>, desc: <>2026-02-27 发布 2.8.9。GitHub 10.5k star。本仓库 client 锁的就是 <code>^2.8.9</code>, 33 个页面在用。</> }, en: { title: <>2.8.9 / current stable</>, desc: <>2.8.9 shipped 2026-02-27. 10.5k GitHub stars. This repo's client pins exactly <code>^2.8.9</code>, with 33 pages using it.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>useQueryState 单个 param</>, desc: <>API 几乎跟 <code>useState</code> 一样, 区别是状态读写都映射到一个 URL query 参数。刷新 / 分享 / 前进后退自动保持。</> }, en: { title: <>useQueryState for one param</>, desc: <>Almost the same API as <code>useState</code>, except reads and writes map to one URL query param. Refresh / share / back-forward stay in sync automatically.</> }, code: <code>{k('const')} [{v('tab')}, {f('setTab')}] = {f('useQueryState')}({s("'tab'")});{'\n'}{c('// ?tab=schedule  ←→  React state')}</code> },
    { tag: 'B', zh: { title: <>parser 给类型安全</>, desc: <>URL 里一切都是字符串, parser 把它解析成 number / boolean / enum / array, 返回值类型由 parser 决定, 不用手写 parseInt。</> }, en: { title: <>Parsers give type safety</>, desc: <>Everything in a URL is a string; a parser turns it into number / boolean / enum / array, and the return type follows the parser — no hand-rolled parseInt.</> }, code: <code>{k('const')} [{v('page')}] = {f('useQueryState')}({s("'page'")},{'\n'}  {f('parseAsInteger')}.{f('withDefault')}({n('1')}));{'\n'}{c('// page: number, ?page 在 =1 时省略')}</code> },
    { tag: 'C', zh: { title: <>useQueryStates 一组</>, desc: <>一次声明多个相关 param, 同时更新只产生一次 URL 导航 (批量), 适合经纬度 / 日期区间 / 多字段筛选。</> }, en: { title: <>useQueryStates for a group</>, desc: <>Declare several related params at once; updating them together produces a single URL navigation (batched). Great for lat/lng, date ranges, multi-field filters.</> }, code: <code>{k('const')} [{v('coords')}, {f('set')}] = {f('useQueryStates')}({'{'}{'\n'}  {p('lat')}: {f('parseAsFloat')}, {p('lng')}: {f('parseAsFloat')},{'\n'}{'}'});{'\n'}{f('set')}({'{ '}{p('lat')}: {n('48.8')}, {p('lng')}: {n('2.3')} {'}'});</code> },
    { tag: 'D', zh: { title: <>withDefault + clearOnDefault</>, desc: <>给个默认值, 当前值等于默认时 nuqs 自动把这个 param 从 URL 里删掉 (v2 默认开), URL 永远保持最短。</> }, en: { title: <>withDefault + clearOnDefault</>, desc: <>Give a default; when the current value equals it, nuqs drops the param from the URL (on by default in v2), keeping the URL minimal.</> }, code: <code>{f('parseAsStringEnum')}([{s("'list'")}, {s("'grid'")}]){'\n'}  .{f('withDefault')}({s("'list'")});{'\n'}{c('// view=list 时 URL 里不出现 ?view')}</code> },
    { tag: 'E', zh: { title: <>withOptions 控后退栈</>, desc: <>大视图 / 大 tab 切换用 <code>history: 'push'</code> (后退能返回上个视图);筛选 / 排序用默认 <code>replace</code> (不堆历史)。</> }, en: { title: <>withOptions for the history stack</>, desc: <>Big view / tab switches use <code>history: 'push'</code> (back returns to the previous view); filters / sorting stay on the default <code>replace</code> (no history pile-up).</> }, code: <code>{f('useQueryState')}({s("'view'")},{'\n'}  {f('parseAsStringEnum')}(VIEWS){'\n'}    .{f('withOptions')}({'{ '}{p('history')}: {s("'push'")} {'}'}));</code> },
    { tag: 'F', zh: { title: <>shallow + throttle</>, desc: <>默认 shallow 只改 URL 不打服务器 (client-first);需要服务端响应时 <code>shallow: false</code>。连续写用 <code>throttleMs</code> 节流, 默认 50ms。</> }, en: { title: <>shallow + throttle</>, desc: <>Shallow by default — updates the URL without hitting the server (client-first); set <code>shallow: false</code> when the server must react. Rapid writes are throttled via <code>throttleMs</code>, default 50ms.</> }, code: <code>{f('setQuery')}({v('val')}, {'{'}{'\n'}  {p('shallow')}: {v('false')}, {p('throttleMs')}: {n('100')},{'\n'}{'}'});</code> },
    { tag: 'G', zh: { title: <>createSearchParamsCache (RSC)</>, desc: <>服务端组件里用同一份 parser 定义类型安全地读 searchParams, 客户端 hook 与服务端 cache 共享一份 schema, 不重复写。</> }, en: { title: <>createSearchParamsCache (RSC)</>, desc: <>Read searchParams type-safely in server components with the same parser definitions; the client hook and the server cache share one schema instead of duplicating it.</> }, code: <code>{k('const')} {v('cache')} = {f('createSearchParamsCache')}({'{'}{'\n'}  {p('q')}: {f('parseAsString')}, {p('page')}: {f('parseAsInteger')},{'\n'}{'}'});{'\n'}{v('cache')}.{f('parse')}({v('searchParams')}); {v('cache')}.{f('get')}({s("'q'")});</code> },
    { tag: 'H', zh: { title: <>NuqsAdapter 接路由器</>, desc: <>在 root 挂一次, 选对应框架的 adapter, 整棵树的 <code>useQueryState</code> 就接到了真实路由器。换框架只换这一个 import。</> }, en: { title: <>NuqsAdapter wires the router</>, desc: <>Mounted once at the root with the right framework adapter, every <code>useQueryState</code> in the tree connects to the real router. Switching frameworks changes just this one import.</> }, code: <code>{k('import')} {'{ '}{v('NuqsAdapter')} {'}'} {k('from')} {s("'nuqs/adapters/next/app'")};{'\n\n'}&lt;{t('NuqsAdapter')}&gt;{'{'}{v('children')}{'}'}&lt;/{t('NuqsAdapter')}&gt;</code> },
  ],
  whyCards: [
    { icon: '⌖', zh: { title: <>URL = 单一真相源</>, desc: <>状态进 URL 后, 刷新不丢、链接能分享、浏览器前进后退天然可用。状态不再藏在某个组件的内存里, 而是页面地址本身。</> }, en: { title: <>URL = single source of truth</>, desc: <>Once state lives in the URL, refresh keeps it, links share it, and browser back/forward just work. State stops hiding in a component's memory — it's the page address itself.</> }, code: <>{c('// /wca/comp?view=globe&event=333')}{'\n'}{c('// 整个视图状态都在地址里')}</> },
    { icon: '≈', zh: { title: <>API 像 useState</>, desc: <>没有 reducer、没有 action、没有 store。<code>const [x, setX] = useQueryState(...)</code> 跟 <code>useState</code> 长得一样, 学习成本几乎为零。</> }, en: { title: <>useState-like API</>, desc: <>No reducer, no actions, no store. <code>const [x, setX] = useQueryState(...)</code> looks just like <code>useState</code> — near-zero learning cost.</> }, code: <>{k('const')} [{v('q')}, {f('setQ')}] = {f('useQueryState')}({s("'q'")});{'\n'}{c('// 跟 useState 一模一样')}</> },
    { icon: '⛭', zh: { title: <>parser 给端到端类型</>, desc: <>URL 是字符串汤, parser 把它变成 number / boolean / enum / array, TS 一路推导到组件。不用每个页面手写 parse + validate。</> }, en: { title: <>End-to-end types from parsers</>, desc: <>The URL is string soup; parsers turn it into number / boolean / enum / array, with TS inference flowing into the component. No per-page parse + validate boilerplate.</> }, code: <>{f('useQueryState')}({s("'n'")}, {f('parseAsInteger')});{'\n'}{c('// n: number | null, 不是 string')}</> },
    { icon: '⇄', zh: { title: <>前进后退自动同步</>, desc: <>每次写 URL 走 push 或 replace, 浏览器历史就对了。后退回到上个 tab / 上个筛选, 不用自己监听 <code>popstate</code> 再 setState。</> }, en: { title: <>Back/forward synced for free</>, desc: <>Each URL write goes through push or replace, so browser history is correct. Back returns to the previous tab / filter — no hand-wired <code>popstate</code> + setState.</> }, code: <>{c('// history: push → 后退能返回')}{'\n'}{c('// history: replace → 后退跳过')}</> },
    { icon: '⊞', zh: { title: <>框架无关一份代码</>, desc: <>adapter 把核心跟路由器解耦, Next / React Router / Remix / TanStack Router 用同一个 <code>useQueryState</code>。从 Vite SPA 迁到 Next 16, 业务代码一行不改。</> }, en: { title: <>One codebase across frameworks</>, desc: <>Adapters decouple the core from the router, so Next / React Router / Remix / TanStack Router share one <code>useQueryState</code>. Migrating a Vite SPA to Next 16 touches zero business lines.</> }, code: <>{k('from')} {s("'nuqs/adapters/react-router/v7'")}{'\n'}{k('from')} {s("'nuqs/adapters/next/app'")}</> },
    { icon: '⚖', zh: { title: <>批量更新一次导航</>, desc: <><code>useQueryStates</code> 把多个 param 的改动合并成一次 URL 写入, 不会一个字段一跳。日期区间、经纬度这类一组参数特别省。</> }, en: { title: <>Batched updates, one navigation</>, desc: <><code>useQueryStates</code> merges changes to several params into a single URL write — no one-hop-per-field. A big win for grouped params like date ranges and lat/lng.</> }, code: <>{f('set')}({'{ '}{p('from')}: {v('a')}, {p('to')}: {v('b')} {'}'});{'\n'}{c('// 一次导航, 不是两次')}</> },
    { icon: '◷', zh: { title: <>~6 kB, client-first</>, desc: <>约 6 kB gzip, 默认 shallow 只改地址栏不打服务器, 交互即时。需要服务端响应再显式 <code>shallow: false</code>。</> }, en: { title: <>~6 kB, client-first</>, desc: <>~6 kB gzipped, shallow by default — only touches the address bar, not the server, so interactions feel instant. Opt into server reaction with <code>shallow: false</code>.</> }, code: <>{c('// bundlephobia: nuqs ~6 kB gzip')}</> },
    { icon: '⛨', zh: { title: <>取代手写 history</>, desc: <>裸 <code>history.pushState</code> + <code>popstate</code> + 手动 parse query 容易漏 case (后退、深链、默认值清理)。nuqs 把这些全收进 hook, 本站 CI 直接禁裸写。</> }, en: { title: <>Replaces hand-rolled history</>, desc: <>Raw <code>history.pushState</code> + <code>popstate</code> + manual query parsing misses cases (back, deep links, default cleanup). nuqs folds all of it into the hook — this site's CI bans the raw form.</> }, code: <>{c('// ❌ history.pushState + popstate')}{'\n'}{c('// ✓ useQueryState')}</> },
  ],
  adopters: [
    { name: 'Next.js (App + Pages Router)', href: 'https://nextjs.org', highlight: true, zhNote: '官方一等 adapter, nuqs 在 Next 社区是 search params 的默认答案', enNote: 'First-class official adapter; the de-facto search-params pick in the Next community' },
    { name: 'React Router v6 / v7', href: 'https://reactrouter.com', highlight: true, zhNote: 'v6 与 v7 各有官方 adapter, SPA / framework 模式都能用', enNote: 'Official adapters for both v6 and v7 — works in SPA and framework modes' },
    { name: 'Remix', href: 'https://remix.run', zhNote: '@remix-run/react v2+ 官方 adapter', enNote: 'Official adapter for @remix-run/react v2+' },
    { name: 'TanStack Router', href: 'https://tanstack.com/router', zhNote: '实验性 adapter, @tanstack/react-router v1+', enNote: 'Experimental adapter for @tanstack/react-router v1+' },
    { name: 'Plain React SPA (Vite / CRA)', href: 'https://vite.dev', zhNote: '不依赖任何框架路由器也能用, 纯 React 即可', enNote: 'Works with no framework router at all — plain React is enough' },
    { name: '47ng / nuqs.dev', href: 'https://nuqs.dev', highlight: true, zhNote: '作者 François Best 的组织, 文档站本身就跑 nuqs', enNote: "François Best's org; the docs site itself runs on nuqs" },
    { name: 'GitHub · 47ng/nuqs', href: 'https://github.com/47ng/nuqs', zhNote: '10.5k star, Next.js 生态里最高的 URL 状态库', enNote: '10.5k stars — the top URL-state library in the Next.js ecosystem' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 33 个页面统一走 nuqs, CI 禁裸 history', enNote: 'This site — 33 pages standardized on nuqs, CI bans raw history' },
  ],
  outlook: [
    { tag: <>HOT · 2024-10</>, hot: true, big: true, zh: { title: <>2.0 — adapter 架构</>, body: <><p>2.0 把整库重写成框架无关:核心只管"状态 ↔ search params"的逻辑, 具体怎么改 URL、怎么监听导航交给各框架的 adapter。Next.js (app + pages)、React SPA、Remix、React Router 各接一个薄层。</p><p>对用户代码的意义是:<code>useQueryState</code> 这套 API 不再绑死 Next。一个组件库 / 一份业务页面可以在 Vite SPA 和 Next 之间搬, URL 状态那部分原样跑。</p></> }, en: { title: <>2.0 — the adapter architecture</>, body: <><p>2.0 rewrote the whole library to be framework-agnostic: the core only owns the "state ↔ search params" logic, while how the URL is mutated and how navigation is observed is delegated to each framework's adapter. Next.js (app + pages), React SPA, Remix, and React Router each plug in a thin layer.</p><p>For user code this means the <code>useQueryState</code> API is no longer tied to Next. A component library or a business page can move between a Vite SPA and Next with the URL-state part running unchanged.</p></> } },
    { tag: 'RSC', zh: { title: <>server cache 类型安全</>, body: <><p><code>createSearchParamsCache</code> 让 React Server Components 用跟客户端 hook 同一份 parser 定义去读 searchParams。一份 schema 两端共用, 服务端预渲染拿到的值跟客户端 hydration 后完全一致, 不会出现"服务端 string、客户端 number"的错位。</p></> }, en: { title: <>Type-safe server cache</>, body: <><p><code>createSearchParamsCache</code> lets React Server Components read searchParams with the same parser definitions as the client hook. One schema shared by both sides: the value from server prerender matches the client after hydration exactly — no "server string, client number" mismatch.</p></> } },
    { tag: 'ROUTERS', zh: { title: <>覆盖全 React 路由生态</>, body: <><p>React Router v7、TanStack Router 的 adapter 陆续补齐 (后者仍标实验)。方向是任何一个主流 React 路由器上, "把状态放 URL"都是同一个写法。剩下的硬骨头是 TanStack Start 这类把路由 schema 也类型化的框架, 跟 nuqs 的 parser 怎么对齐。</p></> }, en: { title: <>Covering the whole React router ecosystem</>, body: <><p>Adapters for React Router v7 and TanStack Router keep filling in (the latter still experimental). The goal: on any mainstream React router, "put state in the URL" reads the same way. The remaining hard part is frameworks like TanStack Start that type their route schema too — aligning that with nuqs's parsers.</p></> } },
    { tag: <>TESTING</>, zh: { title: <>NuqsTestingAdapter</>, body: <><p>专门的测试 adapter 让 <code>useQueryState</code> 的组件在 vitest / jest 里不用起真路由器就能跑, 直接喂初始 searchParams、断言写回的 URL。URL 状态从"难测"变成单测里一等公民。</p></> }, en: { title: <>NuqsTestingAdapter</>, body: <><p>A dedicated testing adapter runs <code>useQueryState</code> components in vitest / jest without a real router — feed initial searchParams, assert the written-back URL. URL state goes from "hard to test" to a first-class citizen in unit tests.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本站把"页内状态进 URL"这件事整体收口到 nuqs, 版本锁 <code>^2.8.9</code>。<code>NuqsAdapter</code> 在 root <code>app/layout.tsx</code> 挂一次 (Next App Router adapter), 全站 33 个页面通过 <code>useQueryState</code> / <code>useQueryStates</code> 把 tab、筛选、排序、搜索词、全屏浮层开关都映射到 URL query。</p>
        <p>用法在 CLAUDE.md 里写成硬约束:页内状态<strong>一律</strong>走 nuqs, <strong>禁</strong>裸 <code>history.pushState</code> / <code>replaceState</code> + 手写 <code>popstate</code> (maplibre / canvas / video 这类重组件例外, 加注释豁免)。粒度规则也固定:大视图 / 大 tab / 大 mode / 打开全屏浮层用 <code>.withOptions({'{ '}history: 'push' {'}'})</code> (后退能返回), 筛选 / 排序 / 搜索词 / 子开关用默认 <code>replace</code> (不堆历史)。默认值一律 <code>.withDefault(x)</code>, 靠 v2 默认开的 <code>clearOnDefault</code> 自动从 URL 省略;枚举用 <code>parseAsStringEnum</code>。</p>
        <p>范本是 <code>app/[lang]/wca/comp/page.tsx</code> 的 <code>viewMode</code> (日历 / 列表 / 地球三视图切换走 push)。其它密集用户:<code>scramble/gen</code> 的变体与底色、<code>nemesizer</code> 三种模式、<code>calc</code> / <code>sim</code> 的参数、<code>persons</code> 选手页的 tab 都在 URL 里。</p>
        <p>这条约束有 CI 兜底:<code>tests/url-state-no-raw-history.test.ts</code> (vitest, CI 跑 vitest 不跑 eslint) 扫整个 client, 谁再裸写 <code>history.pushState</code> / <code>replaceState</code> / <code>popstate</code> 就红。确属特殊场景 (zustand data-blob / 自定义编码 / 全局 infra) 才豁免, 加进该测试的 ALLOWLIST + 文件内注释写理由。"写入即拦 + CI 兜底"两层一起铺, 不靠 review 记得。</p>
      </>
    ),
    en: (
      <>
        <p>This site funnels "page state into the URL" entirely through nuqs, pinned at <code>^2.8.9</code>. <code>NuqsAdapter</code> is mounted once at the root <code>app/layout.tsx</code> (the Next App Router adapter), and all 33 such pages map tabs, filters, sorting, search terms, and full-screen overlay toggles to the URL query via <code>useQueryState</code> / <code>useQueryStates</code>.</p>
        <p>The usage is a hard rule in CLAUDE.md: page state <strong>always</strong> goes through nuqs, and raw <code>history.pushState</code> / <code>replaceState</code> + hand-written <code>popstate</code> is <strong>banned</strong> (heavy components like maplibre / canvas / video are the exception, exempted with a comment). The granularity rules are fixed too: big view / tab / mode switches and opening full-screen overlays use <code>.withOptions({'{ '}history: 'push' {'}'})</code> (back returns), while filters / sorting / search / sub-toggles stay on the default <code>replace</code> (no history pile-up). Defaults always go through <code>.withDefault(x)</code>, omitted from the URL automatically via v2's default-on <code>clearOnDefault</code>; enums use <code>parseAsStringEnum</code>.</p>
        <p>The canonical template is <code>viewMode</code> in <code>app/[lang]/wca/comp/page.tsx</code> (calendar / list / globe three-view switch on push). Other heavy users: <code>scramble/gen</code>'s variant and base color, the three <code>nemesizer</code> modes, the <code>calc</code> / <code>sim</code> params, and the <code>persons</code> page tabs all live in the URL.</p>
        <p>The rule has a CI backstop: <code>tests/url-state-no-raw-history.test.ts</code> (vitest — CI runs vitest, not eslint) scans all of client and goes red if anyone hand-writes <code>history.pushState</code> / <code>replaceState</code> / <code>popstate</code>. Genuinely special cases (zustand data-blob / custom encoding / global infra) are exempted only by adding to that test's ALLOWLIST plus an in-file comment with the reason. "Block-on-write + CI backstop," two layers together, not relying on reviewers to remember.</p>
      </>
    ),
  },
  links: [
    { label: 'nuqs.dev', href: 'https://nuqs.dev' },
    { label: 'GitHub · 47ng/nuqs', href: 'https://github.com/47ng/nuqs' },
    { label: 'npm · nuqs', href: 'https://www.npmjs.com/package/nuqs' },
    { label: 'v2 migration guide', href: 'https://nuqs.dev/docs/migrations/v2' },
  ],
};

export default NUQS;
