import type { StackTool } from '../_lib/stack_tool_types';
import { v, s, n, f, p, c } from '../_lib/stack_tool_types';

// ─── Zed (Zed Industries' GPU-accelerated editor) ───────────────────────────

export const ZED: StackTool = {
  slug: 'zed',
  name: 'Zed',
  version: '1.4',
  since: '2023-03',
  group: 'dev',
  accent: '#0EA5E9',
  bright: '#3DBEF5',
  glyph: 'Z',
  floats: ['GPUI', 'CRDT', 'tree-sitter', 'LSP', 'multibuffer', 'ACP', 'Zeta2', 'DeltaDB', 'DAP', 'multiplayer'],
  zh: {
    tagline: 'Rust 写的 GPU 加速代码编辑器',
    role: 'cuberoot.me 的图形编辑器:代码阅读 / 跳转 / 手改 / diff review。Claude Code 写绝大部分代码, Zed 当眼睛和方向盘, 它自带的 AI agent 面板 + ACP 还能直接跟 agent 协作。',
    heroSub: <>Atom 和 Tree-sitter 的原班人马 (Nathan Sobo 牵头) 在 Atom 2022 年停摆后<strong>推倒重来</strong>的产物。他们没去优化那个 Chromium fork, 而是用 Rust 从零写了一套 GPU 渲染的 UI 框架 <strong>GPUI</strong>, "像做游戏一样做编辑器"。结果是亚毫秒的输入延迟和秒级冷启动, 同时内建 LSP / tree-sitter / 实时协作 / AI agent。</>,
    whatDesc: <>Zed 是一个 <strong>原生 (非 Electron) 的高性能代码编辑器</strong>。VS Code / Atom 这条路把编辑器架在浏览器引擎上 (Atom 自己催生了 Electron), 渲染和输入延迟天生有上限。Zed 反过来, 整个 UI 用自研的 <strong>GPUI</strong> 框架直接打到 GPU, 用 Rust 吃满多核。它不是"又一个 VS Code 皮肤", 是把编辑器当作高性能桌面应用重写一遍。</>,
    historyDesc: <>从 2023-03 macOS 公开预览, 到 2024-01 开源、2024-07 Linux、2025-10 Windows, 再到 2026-04-29 发布 1.0 (此前一千多个版本号全是 0 开头), 三年。中间最大的转向是<strong>从协作编辑器变成 AI-native 编辑器</strong>:多 agent 并行、Agent Client Protocol (ACP)、Zeta2 编辑预测、面向人与 agent 共享一致代码视图的 DeltaDB。</>,
    conceptsTitle: 'GPUI + CRDT + tree-sitter + ACP',
    conceptsDesc: <>底层四块基石:<strong>GPUI</strong> (Rust 写的 GPU 立即模式 UI 框架, Apache 2.0 单独开源)、<strong>CRDT</strong> (无冲突复制数据类型, 撑实时协作)、<strong>tree-sitter</strong> (增量解析, 团队自己的另一个项目)、<strong>ACP</strong> (Agent Client Protocol, 让任意 agent 接进编辑面板)。其余 LSP / DAP / 多缓冲都是在这之上的能力。</>,
    whyDesc: <>2026 年还做一个新编辑器, 不是因为"VS Code 不够用", 而是因为 <strong>Electron 的延迟上限是结构性的</strong>。当你要的是"打字零延迟 + 大文件秒开 + agent 实时改一屏代码"时, 浏览器引擎这层抽象就是天花板。Zed 用 Rust + GPU 把这层拆掉, 顺手把 AI 协作做成一等公民。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>从最早的 Rust / 系统编程社区 (对延迟最敏感的人群), 扩散到喜欢 Vim 模态编辑 + 现代 LSP 的开发者, 再到 2025 年起被"agent 并行编辑"吸引来的 AI-first 用户。1.0 后跨平台齐全 (macOS / Linux / Windows), 采用面明显变宽。</>,
    cuberootDesc: <>本仓库代码<strong>几乎全部</strong>在 Claude Code CLI 里写 (Read / Edit / Bash / Grep + 子 agent + skill + memory)。Zed 在这套流程里是图形编辑器:读 agent 改完的 diff、在大 monorepo 里跳转符号、偶尔手动微调一两行、用它的 Git 面板 review staged hunk。它自带 AI agent 面板和 ACP, 也能直接接 Claude 一起改 —— 跟 Claude Code 是互补不是替代。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>1.0 之后 Zed 把"周更"节奏保留, 重心压在 AI-native:DeltaDB (人和 agent 共享一份一致代码视图)、ACP 生态扩张、Zeta2 开放权重编辑预测模型。GPUI 作为独立 Apache 框架也在吸引"想用 Rust 写高性能桌面应用"的人。</>,
  },
  en: {
    tagline: 'A GPU-accelerated code editor written in Rust',
    role: "cuberoot.me's GUI editor: reading code, navigation, hand-edits, diff review. Claude Code writes nearly all the code; Zed is the eyes and the steering wheel — and its built-in AI agent panel + ACP can collaborate with agents directly.",
    heroSub: <>The product of a <strong>full restart</strong> by the original Atom and Tree-sitter team (led by Nathan Sobo) after Atom was shut down in 2022. Instead of optimizing that Chromium fork, they wrote a GPU-rendered UI framework, <strong>GPUI</strong>, from scratch in Rust — "building an editor like a video game." The result is sub-millisecond input latency and second-scale cold starts, with LSP / tree-sitter / real-time collaboration / AI agents built in.</>,
    whatDesc: <>Zed is a <strong>native (non-Electron) high-performance code editor</strong>. VS Code / Atom build the editor on a browser engine (Atom itself spawned Electron), with structural ceilings on render and input latency. Zed inverts this: the entire UI runs on the self-built <strong>GPUI</strong> framework straight to the GPU, with Rust saturating multiple cores. It isn't "another VS Code skin" — it's the editor rewritten as a high-performance desktop app.</>,
    historyDesc: <>From the March 2023 macOS public preview, through open-sourcing (2024-01), Linux (2024-07), Windows (2025-10), to the 1.0 release on 2026-04-29 (the prior thousand-plus versions all began with zero), three years. The biggest pivot: <strong>from a collaboration editor to an AI-native editor</strong> — parallel agents, the Agent Client Protocol (ACP), Zeta2 edit prediction, and DeltaDB for a shared consistent codebase view between humans and agents.</>,
    conceptsTitle: 'GPUI + CRDT + tree-sitter + ACP',
    conceptsDesc: <>Four foundations underneath: <strong>GPUI</strong> (a Rust GPU immediate-mode UI framework, open-sourced separately under Apache 2.0), <strong>CRDT</strong> (conflict-free replicated data types powering real-time collaboration), <strong>tree-sitter</strong> (incremental parsing — the team's other project), and <strong>ACP</strong> (the Agent Client Protocol, plugging any agent into the editor panel). LSP / DAP / multibuffer are capabilities layered on top.</>,
    whyDesc: <>Building a new editor in 2026 isn't because "VS Code isn't enough" — it's because <strong>Electron's latency ceiling is structural</strong>. When you want zero typing latency, large files opening instantly, and an agent editing a screenful of code live, the browser-engine abstraction is the wall. Zed tears that layer out with Rust + GPU and makes AI collaboration a first-class citizen along the way.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>From the earliest Rust / systems-programming community (the people most sensitive to latency), out to developers who want Vim-style modal editing plus a modern LSP, and from 2025 to the AI-first crowd drawn in by parallel agent editing. After 1.0 the cross-platform story is complete (macOS / Linux / Windows) and adoption visibly widens.</>,
    cuberootDesc: <>This repo's code is written <strong>almost entirely</strong> inside the Claude Code CLI (Read / Edit / Bash / Grep + subagents + skills + memory). In that flow Zed is the GUI editor: reading the diffs an agent just produced, jumping symbols across a large monorepo, occasionally hand-tweaking a line or two, and reviewing staged hunks in its Git panel. Its built-in AI agent panel and ACP can also wire Claude in directly — complementary to Claude Code, not a replacement.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>After 1.0, Zed keeps the weekly cadence and bets on AI-native: DeltaDB (humans and agents sharing one consistent codebase view), an expanding ACP ecosystem, and the Zeta2 open-weight edit-prediction model. GPUI, as a standalone Apache framework, is also drawing people who want to write high-performance Rust desktop apps.</>,
  },
  heroStats: [
    { num: '1', unit: '.4', zh: <>当前稳定版 <em>2026-05-28 · v1.4.4</em></>, en: <>current stable <em>2026-05-28 · v1.4.4</em></>
    },
    { num: '1', unit: '.0', zh: <>2026-04-29 发布 <em>此前 1000+ 版本全是 0 开头</em></>, en: <>shipped 2026-04-29 <em>1000+ prior versions all began with zero</em></>
    },
    { num: '0', unit: 'ms', zh: <>追求亚毫秒输入延迟 <em>GPUI 直打 GPU</em></>, en: <>sub-millisecond input latency target <em>GPUI straight to GPU</em></>
    },
    { num: '3', zh: <>个平台齐全 <em>macOS / Linux / Windows</em></>, en: <>platforms supported <em>macOS / Linux / Windows</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>Zed 是 Atom 和 Tree-sitter 的原班人马做的第二个编辑器。Atom 在 2022 年被 GitHub 正式停摆 (它催生的 Electron 框架反倒成了 VS Code 的地基), 三位核心贡献者 (Nathan Sobo 牵头) 决定不修旧的, 从零开一个新项目。判断很简单:Atom 慢的根因是它架在 Chromium 上, 这层抽象的延迟上限是结构性的, 修不动。</p>
        <p>设计目标一句话:把编辑器当作一个高性能桌面应用 (而不是网页应用) 重写。他们用 Rust 从零写了一套 GPU 立即模式 UI 框架 <strong>GPUI</strong> —— 用团队自己的话说"像做游戏一样做编辑器", 所有绘制走 GPU, 多核全吃满。同时保留他们最擅长的两块:增量语法解析 (tree-sitter 本来就是这个团队的另一个项目) 和实时协作 (基于 CRDT 的多人同编)。2023-03-15 macOS 公开预览, 主打速度与协作, 当时还完全没提 AI。</p>
        <p>三年里路线明显转了一个弯。2024-01-24 开源 (编辑器 GPL、服务端 AGPL、GPUI 单独 Apache 2.0), 2024-07 上 Linux, 2025 拿到 Sequoia 的 3200 万美元融资并补齐 Windows (2025-10), 2026-04-29 发布 1.0 —— 此前一千多个版本号全是 0 开头, 1.0 是他们第一次说"够稳了"。与此同时编辑器从"多人协作"重心整体移到 <strong>AI-native</strong>:多 agent 并行编辑、Agent Client Protocol (ACP) 让任意 agent 接进面板、Zeta2 开放权重编辑预测、面向人与 agent 共享一致代码视图的 DeltaDB。</p>
      </>
    ),
    en: (
      <>
        <p>Zed is the second editor from the original Atom and Tree-sitter team. After GitHub shut Atom down in 2022 (the Electron framework it spawned ironically became VS Code's foundation), three core contributors (led by Nathan Sobo) decided not to fix the old thing but to start a new project from scratch. The reasoning was simple: Atom's slowness rooted in being built on Chromium, and that abstraction's latency ceiling is structural — unfixable.</p>
        <p>The design goal in one sentence: rewrite the editor as a high-performance desktop app, not a web app. They wrote a GPU immediate-mode UI framework, <strong>GPUI</strong>, from scratch in Rust — in the team's words, "building an editor like a video game," with all drawing on the GPU and multiple cores saturated. They kept the two things they do best: incremental syntax parsing (tree-sitter is this team's other project) and real-time collaboration (CRDT-based multiplayer editing). The macOS public preview landed on 2023-03-15, leading with speed and collaboration — with no mention of AI at all.</p>
        <p>Three years bent the roadmap. Open-sourced on 2024-01-24 (GPL for the editor, AGPL for the server, GPUI separately under Apache 2.0), Linux in 2024-07, $32M from Sequoia and Windows (2025-10) in 2025, and 1.0 on 2026-04-29 — the prior thousand-plus versions all began with zero; 1.0 was the first time they called it stable. Meanwhile the editor's center of gravity shifted from multiplayer collaboration to <strong>AI-native</strong>: parallel agent editing, the Agent Client Protocol (ACP) plugging any agent into the panel, Zeta2 open-weight edit prediction, and DeltaDB for a shared consistent codebase view across humans and agents.</p>
      </>
    ),
  },
  history: [
    { year: '2022', zh: { title: <>Atom 停摆, 团队重启</>, desc: <>GitHub 正式归档 Atom。Nathan Sobo 等三位核心贡献者判断 Chromium 那层延迟上限修不动, 决定不优化旧项目, 用 Rust 从零写新编辑器。</> }, en: { title: <>Atom shut down, team restarts</>, desc: <>GitHub archives Atom. Nathan Sobo and two other core contributors judge the Chromium latency ceiling unfixable and decide to write a new editor from scratch in Rust rather than optimize the old one.</> } },
    { year: '2023·03', zh: { title: <>macOS 公开预览</>, desc: <>3 月 15 日 Zed 在 macOS 上公开 (beta), 主打速度与实时协作, 完全没提 AI。GPUI + tree-sitter + CRDT 三块基石首次同台。</> }, en: { title: <>macOS public preview</>, desc: <>On March 15 Zed opens publicly on macOS (beta), leading with speed and real-time collaboration — no mention of AI. GPUI + tree-sitter + CRDT debut together.</> } },
    { year: '2024·01', highlight: false, zh: { title: <>开源</>, desc: <>1 月 24 日 Zed 开源:编辑器 GPL、服务端 AGPL、GPUI 单独 Apache 2.0 (好让人拿它写任意许可的桌面应用)。同期内建 OpenAI / Copilot 支持。</> }, en: { title: <>Open-sourced</>, desc: <>On January 24 Zed goes open source: GPL for the editor, AGPL for the server, GPUI separately under Apache 2.0 (so it can build desktop apps under any license). Built-in OpenAI / Copilot support arrives alongside.</> } },
    { year: '2024·07', zh: { title: <>Linux 支持</>, desc: <>Zed 登陆 Linux。跨平台从"只 macOS"扩到两个平台, Rust / 系统编程社区采用面明显上涨。</> }, en: { title: <>Linux support</>, desc: <>Zed lands on Linux. Cross-platform grows from macOS-only to two platforms; adoption visibly climbs in the Rust / systems-programming community.</> } },
    { year: '2024', zh: { title: <>AI assistant 内建</>, desc: <>Zed AI / assistant 面板成熟, 把 LLM 编码协助做进编辑器主流程, 而非插件。这是从"协作编辑器"转向"AI-native"的起点。</> }, en: { title: <>Built-in AI assistant</>, desc: <>The Zed AI / assistant panel matures, building LLM coding help into the editor's main flow rather than as a plugin. The starting point of the shift from collaboration editor to AI-native.</> } },
    { year: '2025', zh: { title: <>Sequoia 3200 万美元融资</>, desc: <>Zed Industries 拿到 Sequoia Capital 领投的 3200 万美元。资金推动 Windows 补齐 + AI-native 路线全面加速。</> }, en: { title: <>$32M from Sequoia</>, desc: <>Zed Industries raises $32M led by Sequoia Capital. The funding drives Windows parity and a full acceleration of the AI-native roadmap.</> } },
    { year: '2025', zh: { title: <>ACP + 多 agent 并行</>, desc: <>Agent Client Protocol (ACP) 上线, 让 Claude / Codex / OpenCode 等任意 agent 接进编辑面板;多个 agent 可以并行在不同项目里改代码。</> }, en: { title: <>ACP + parallel agents</>, desc: <>The Agent Client Protocol (ACP) ships, plugging any agent (Claude / Codex / OpenCode) into the editor panel; multiple agents can edit across different projects in parallel.</> } },
    { year: '2025·10', zh: { title: <>Windows 支持 (GA)</>, desc: <>Zed 正式上 Windows。三大桌面平台 (macOS / Linux / Windows) 齐全, 为 1.0 铺平最后一块路。</> }, en: { title: <>Windows support (GA)</>, desc: <>Zed reaches Windows. All three desktop platforms (macOS / Linux / Windows) covered, paving the last stretch toward 1.0.</> } },
    { year: '2026·04', highlight: true, zh: { title: <>1.0 发布</>, desc: <>4 月 29 日 Zed 1.0。此前一千多个版本号全是 0 开头, 1.0 是首个稳定里程碑。书签 / view-commit / GIF 预览 / 更好的 fuzzy 匹配等, 周更节奏保留, 改用 semver。</> }, en: { title: <>1.0 released</>, desc: <>On April 29 Zed 1.0. The prior thousand-plus versions all began with zero; 1.0 is the first stable milestone. Bookmarks / view-commit / GIF preview / better fuzzy matching, weekly cadence retained, now on semver.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>当前 — v1.4.4</>, desc: <>5 月 28 日 v1.4.4 稳定。近版本加 agent skills (从 GitHub URL 导入) + 全局 AGENTS.md 配置, Copilot 集成修复。DeltaDB (人/agent 共享一致代码视图) 在路线上。</> }, en: { title: <>Now — v1.4.4</>, desc: <>v1.4.4 stable on May 28. Recent releases add agent skills (importable from GitHub URLs) + global AGENTS.md config, plus Copilot integration fixes. DeltaDB (shared consistent codebase view for humans/agents) is on the roadmap.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>GPUI — GPU 立即模式 UI</>, desc: <>整个界面用 Rust 自研的 GPUI 框架直接打到 GPU, 不经浏览器引擎。它单独以 Apache 2.0 开源, 你能拿它写任意许可的高性能桌面应用。</> }, en: { title: <>GPUI — GPU immediate-mode UI</>, desc: <>The whole interface renders through the self-built Rust GPUI framework, straight to the GPU, with no browser engine. It is open-sourced separately under Apache 2.0, usable to build high-performance desktop apps under any license.</> }, code: <code>{c('// GPUI: build UI like a game frame')}{'\n'}{f('div')}(){'\n'}  .{f('flex')}(){'\n'}  .{f('bg')}({v('rgb')}({n('0x0EA5E9')})){'\n'}  .{f('child')}({s('"hello from the GPU"')})</code> },
    { tag: 'B', zh: { title: <>CRDT — 实时协作</>, desc: <>无冲突复制数据类型让多人 (以及 agent) 同时编辑同一个 buffer, 不需要锁、不需要中心冲突解决。这是 Zed 协作和未来 DeltaDB 的数学基础。</> }, en: { title: <>CRDT — real-time collaboration</>, desc: <>Conflict-free replicated data types let multiple people (and agents) edit the same buffer simultaneously, with no locks and no central conflict resolution. The mathematical basis for Zed's collaboration and the future DeltaDB.</> }, code: <code>{c('// each edit is a commutative op')}{'\n'}buffer.{f('insert')}(pos, {s('"x"')}); {c('// peer A')}{'\n'}buffer.{f('insert')}(pos, {s('"y"')}); {c('// peer B')}{'\n'}{c('// converge without conflict')}</code> },
    { tag: 'C', zh: { title: <>tree-sitter — 增量解析</>, desc: <>tree-sitter 本就是这个团队的另一个项目:把源码解析成具体语法树, 改一个字符只重解析受影响的子树。语法高亮 / 结构选择 / 跳转全靠它。</> }, en: { title: <>tree-sitter — incremental parsing</>, desc: <>tree-sitter is this team's other project: it parses source into a concrete syntax tree and, on a one-character edit, re-parses only the affected subtree. Syntax highlighting / structural selection / navigation all ride on it.</> }, code: <code>{c('// edit one char ->')}{'\n'}{c('// only the touched subtree re-parses')}{'\n'}tree.{f('edit')}({'{ '}{p('start')}, {p('old_end')}, {p('new_end')}{' }'});{'\n'}parser.{f('parse')}(src, tree);</code> },
    { tag: 'D', zh: { title: <>ACP — Agent Client Protocol</>, desc: <>一个开放协议, 让任意 coding agent (Claude / Codex / OpenCode...) 接进 Zed 的编辑面板。agent 直接看到 / 改到真实 buffer, 不是贴文本框。</> }, en: { title: <>ACP — Agent Client Protocol</>, desc: <>An open protocol that plugs any coding agent (Claude / Codex / OpenCode...) into Zed's editor panel. The agent sees and edits the real buffer directly, not a chat textbox.</> }, code: <code>{c('// connect an agent over ACP')}{'\n'}{'{'} {p('agent')}: {s('"claude"')}, {p('protocol')}: {s('"acp"')} {'}'}{'\n'}{c('// agent edits the live multibuffer')}</code> },
    { tag: 'E', zh: { title: <>LSP — 语言能力</>, desc: <>Language Server Protocol 接各语言的 server, 拿到补全 / 诊断 / 跳定义 / 重命名。配 GPUI 的渲染速度, 大项目里跳转和补全几乎无延迟。</> }, en: { title: <>LSP — language intelligence</>, desc: <>The Language Server Protocol connects each language's server for completion / diagnostics / go-to-definition / rename. Paired with GPUI's render speed, navigation and completion feel near-instant in large projects.</> }, code: <code>{p('$')} {c('# Zed auto-installs language servers')}{'\n'}{c('# rust-analyzer, tsserver, pyright, ...')}{'\n'}{c('# go-to-def, rename, diagnostics inline')}</code> },
    { tag: 'F', zh: { title: <>multibuffer — 跨文件编辑面</>, desc: <>把多个文件的相关片段拼成一个可编辑的虚拟缓冲。search-replace 结果、agent 的多处修改、一组 diff 都可以在一屏里直接改, 而不是来回切 tab。</> }, en: { title: <>multibuffer — cross-file editing surface</>, desc: <>Stitches relevant fragments from many files into one editable virtual buffer. Search-replace results, an agent's scattered edits, or a group of diffs can all be edited on one screen instead of tab-hopping.</> }, code: <code>{c('// one multibuffer, three files')}{'\n'}{v('SoloView.tsx')}  L40-58{'\n'}{v('StageSolver.tsx')} L112-130{'\n'}{v('theme.ts')}       L8-20</code> },
    { tag: 'G', zh: { title: <>Zeta2 — 编辑预测</>, desc: <>开放权重的编辑预测模型, 不止补当前 token, 而是预测下一处<strong>编辑</strong> (常是别处的关联改动), 按 Tab 跳过去接受。比传统行内补全更贴"重构"场景。</> }, en: { title: <>Zeta2 — edit prediction</>, desc: <>An open-weight edit-prediction model that goes beyond completing the current token to predicting the next <strong>edit</strong> (often a related change elsewhere), accepted by tabbing to it. Fits refactor flows better than inline completion.</> }, code: <code>{c('// predict the NEXT edit, not next token')}{'\n'}rename {f('foo')} {'->'} {f('bar')} here{'\n'}{c('// Zeta2 predicts the call site change')}{'\n'}{c('// press Tab to jump + accept')}</code> },
    { tag: 'H', zh: { title: <>DAP — 内建调试</>, desc: <>Debug Adapter Protocol 让 Zed 直接调试 (断点 / 单步 / 变量), 不靠外部 IDE。跟 LSP 一样是协议接入, 各语言 adapter 复用社区现成的。</> }, en: { title: <>DAP — built-in debugging</>, desc: <>The Debug Adapter Protocol lets Zed debug directly (breakpoints / stepping / variables) without an external IDE. Like LSP, it's protocol-based, reusing the community's existing per-language adapters.</> }, code: <code>{c('// set a breakpoint, F5 to run')}{'\n'}{p('breakpoint')} at SoloView.tsx:42{'\n'}{c('// step, inspect, continue — no plugin')}</code> },
  ],
  whyCards: [
    { icon: 'Z', zh: { title: <>原生 = 没有 Electron 上限</>, desc: <>UI 直接走 GPU, 不经浏览器引擎。打字延迟 / 滚动 / 大文件打开都没有那层抽象的天花板。这是 Zed 整个存在理由的核心。</> }, en: { title: <>Native — no Electron ceiling</>, desc: <>The UI renders straight to the GPU with no browser engine. Typing latency, scrolling, and opening large files have no abstraction-layer ceiling. The core reason Zed exists.</> }, code: <>{c('// GPU draw, not DOM reflow')}{'\n'}frame {n('0')} {'->'} frame {n('1')}: {v('<1ms')}</> },
    { icon: '⚡', zh: { title: <>秒级冷启动</>, desc: <>Rust 二进制冷启动以秒计, 不是十几秒等 JS bundle。"打开就能用"这件事对每天开几十次编辑器的人是实打实的省。</> }, en: { title: <>Second-scale cold start</>, desc: <>A Rust binary cold-starts in seconds, not the dozen-second wait for a JS bundle. "Open and go" is a real saving for anyone launching the editor dozens of times a day.</> }, code: <>{p('$')} {f('time')} zed .{'\n'}{v('real    0m1.2s')}</> },
    { icon: '⌬', zh: { title: <>AI agent 一等公民</>, desc: <>ACP 让 agent 直接改真实 buffer, 不是贴聊天框文本。多 agent 可以并行在不同项目里干活, 编辑器原生承载, 不靠插件凑。</> }, en: { title: <>AI agents are first-class</>, desc: <>ACP lets agents edit the real buffer directly, not paste into a chat box. Multiple agents work across projects in parallel, carried natively by the editor rather than bolted on via plugins.</> }, code: <>{c('// agent edits live multibuffer over ACP')}{'\n'}claude {'->'} buffer.{f('edit')}(...)</> },
    { icon: '⌖', zh: { title: <>tree-sitter 跳得准</>, desc: <>同一批人写 tree-sitter 又写 Zed, 语法树解析是它的母语。结构化选择 / 符号跳转 / 高亮在大文件里依然准且快。</> }, en: { title: <>tree-sitter navigation is precise</>, desc: <>The same people wrote tree-sitter and Zed — syntax-tree parsing is its mother tongue. Structural selection / symbol navigation / highlighting stay precise and fast even in large files.</> }, code: <>{f('select')}(enclosing-function){'\n'}{f('goto')}(symbol)</> },
    { icon: '⛁', zh: { title: <>GPUI 可单独用</>, desc: <>UI 框架单独以 Apache 2.0 开源, 跟编辑器解耦。想用 Rust 写一个高性能桌面应用, 可以直接拿 GPUI, 用任意许可分发自己的产品。</> }, en: { title: <>GPUI is usable on its own</>, desc: <>The UI framework is open-sourced separately under Apache 2.0, decoupled from the editor. To build a high-performance Rust desktop app, take GPUI and ship your product under any license.</> }, code: <>{f('use')} gpui::*;{'\n'}{c('// your own app, Apache-2.0 framework')}</> },
    { icon: '⚙', zh: { title: <>实时协作内建</>, desc: <>CRDT 撑起多人同编一个 buffer + 共享屏幕 + 远程开发, 不靠第三方扩展。pair programming 和未来的人/agent 共享视图共用一套底层。</> }, en: { title: <>Collaboration built in</>, desc: <>CRDTs power multiplayer editing of one buffer + screen sharing + remote development, with no third-party extension. Pair programming and the future human/agent shared view ride the same substrate.</> }, code: <>{c('// share a project, edit together')}{'\n'}{f('zed')} collab {p('--invite')} teammate</> },
    { icon: '⌗', zh: { title: <>Vim 模态原生</>, desc: <>Vim-style 模态编辑是内建模式 (不是仿真插件), 跟 LSP / multibuffer / agent 面板都能配。从 Vim 来的人几乎零迁移成本。</> }, en: { title: <>Native Vim mode</>, desc: <>Vim-style modal editing is a built-in mode (not an emulation plugin), composable with LSP / multibuffer / agent panel. Near-zero migration cost for people coming from Vim.</> }, code: <>{c('// settings.json')}{'\n'}{p('vim_mode')}: {v('true')}</> },
    { icon: '⌁', zh: { title: <>跨平台齐全 (1.0 后)</>, desc: <>macOS / Linux / Windows 全到位。1.0 之前 Linux/Windows 是逐步补的, 现在三平台一致, 一份配置走天下, 跨机协作没断点。</> }, en: { title: <>Full cross-platform (post-1.0)</>, desc: <>macOS / Linux / Windows all covered. Linux/Windows were phased in before 1.0; now the three platforms are consistent — one config everywhere, no break in cross-machine collaboration.</> }, code: <>{c('// same settings.json on all three')}{'\n'}macOS · Linux · Windows</> },
  ],
  adopters: [
    { name: 'Zed Industries', href: 'https://zed.dev', highlight: true, zhNote: '自家团队全员日用, dogfood 跑得最深', enNote: 'The team itself uses it daily; deepest dogfood' },
    { name: 'Rust community', href: 'https://www.rust-lang.org', highlight: true, zhNote: '对延迟最敏感的人群, 最早一批采用者', enNote: 'The most latency-sensitive crowd; earliest adopters' },
    { name: 'tree-sitter', href: 'https://tree-sitter.github.io', zhNote: '同团队项目, 是 Zed 解析层的基石', enNote: "The team's own project; the foundation of Zed's parsing" },
    { name: 'GPUI', href: 'https://www.gpui.rs', zhNote: 'Zed 抽出的 Apache 2.0 UI 框架, 独立被复用', enNote: "Zed's Apache-2.0 UI framework, reused as a standalone" },
    { name: 'Anthropic Claude', href: 'https://www.anthropic.com', highlight: true, zhNote: 'Claude agent 可经 ACP 接进 Zed 编辑面板', enNote: 'Claude agent plugs into the Zed panel via ACP' },
    { name: 'Vim / Neovim 迁移者', zhNote: '原生模态编辑 + 现代 LSP, 迁移成本低', enNote: 'Native modal editing + modern LSP; low migration cost' },
    { name: 'Systems / 嵌入式开发者', zhNote: '看重低延迟与 Rust 工具链体验', enNote: 'Value low latency and the Rust toolchain experience' },
    { name: 'AI-first 开发者', zhNote: '被多 agent 并行编辑吸引, 2025 起涌入', enNote: 'Drawn by parallel agent editing; inflow from 2025' },
    { name: 'OSS maintainers', zhNote: '开源 + 周更节奏, 贡献门槛低', enNote: 'Open source + weekly cadence; low contribution barrier' },
    { name: 'Sequoia Capital', href: 'https://www.sequoiacap.com', zhNote: '2025 领投 3200 万美元, 押注原生 AI 编辑器', enNote: 'Led the 2025 $32M round, betting on a native AI editor' },
    { name: 'Indie / solo devs', zhNote: '单人项目里轻量但全功能的主力编辑器', enNote: 'Lightweight yet full-featured editor for solo projects' },
    { name: 'cuberoot.me', href: 'https://cuberoot.me', highlight: true, zhNote: '本站的 GUI 编辑器, 配 Claude Code 做读改与 review', enNote: "This site's GUI editor, paired with Claude Code for read/edit/review" },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>DeltaDB — 人与 agent 共享一致视图</>, body: <><p>1.0 之后路线图上最大的一块是 DeltaDB:让多个人和多个 agent 在同一份代码上看到一致、实时的视图。这是把 Zed 早期的 CRDT 协作能力, 推到"人 + agent 混合编辑"这个 2026 才真正成立的场景。</p><p>意义在于 <strong>agent 不再是贴 diff 的外挂</strong> —— 它和你看到同一个 buffer、同一个光标上下文、同一份未提交改动, 冲突在数据层就被解掉, 而不是事后 merge。这是"原生 AI 编辑器"区别于"装了 AI 插件的编辑器"的根。</p></> }, en: { title: <>DeltaDB — shared consistent view for humans and agents</>, body: <><p>The biggest item on the post-1.0 roadmap is DeltaDB: a consistent, real-time view of one codebase shared by multiple humans and multiple agents. It pushes Zed's early CRDT collaboration into the "humans + agents mixed editing" scenario that only really arrived in 2026.</p><p>The point: <strong>the agent stops being a diff-pasting add-on</strong> — it sees the same buffer, the same cursor context, the same uncommitted changes you do; conflicts dissolve at the data layer instead of being merged after the fact. This is what separates a native AI editor from "an editor with an AI plugin."</p></> } },
    { tag: 'ACP', zh: { title: <>ACP 生态扩张</>, body: <><p>Agent Client Protocol 是开放协议, 不绑某一家 agent。Claude / Codex / OpenCode 已接, 越多 agent 支持 ACP, "在 Zed 里换一个 agent"就越像"换一个 LSP server"那样无痛。这跟 Claude Code 的 MCP 是同一种"用开放协议对抗锁定"的姿态。</p></> }, en: { title: <>ACP ecosystem expands</>, body: <><p>The Agent Client Protocol is an open spec, not bound to one agent. Claude / Codex / OpenCode already connect; the more agents speak ACP, the more "swap an agent in Zed" feels like "swap an LSP server" — painless. The same "open protocol against lock-in" stance as Claude Code's MCP.</p></> } },
    { tag: 'OSS', zh: { title: <>GPUI 作为独立框架</>, body: <><p>GPUI 单独 Apache 2.0 开源, 把"用 Rust 写 GPU 加速桌面 UI"这件事从 Zed 里解耦出来。已有项目拿它做编辑器之外的高性能桌面应用。一个编辑器顺手孵出一个可复用 UI 框架, 是 Atom 当年催生 Electron 的镜像 —— 只是这次方向是原生而非网页。</p></> }, en: { title: <>GPUI as a standalone framework</>, body: <><p>GPUI is open-sourced separately under Apache 2.0, decoupling "GPU-accelerated desktop UI in Rust" from Zed itself. Projects already use it for high-performance desktop apps beyond editors. An editor incidentally hatching a reusable UI framework mirrors Atom spawning Electron — except this time the direction is native, not web.</p></> } },
    { tag: 'AI', zh: { title: <>Zeta2 编辑预测开放权重</>, body: <><p>Zeta2 是 Zed 自家的开放权重编辑预测模型, 预测下一处编辑 (而非下一个 token), 按 Tab 跳过去接受。开放权重意味着可审计、可本地化, 跟"全闭源云端补全"是相反方向。它把 AI 辅助从"补全行"升级到"驱动重构"。</p></> }, en: { title: <>Zeta2 edit prediction, open-weight</>, body: <><p>Zeta2 is Zed's own open-weight edit-prediction model, predicting the next edit (not the next token), accepted by tabbing to it. Open weights mean auditable and localizable — the opposite of fully closed cloud completion. It upgrades AI assistance from "complete a line" to "drive a refactor."</p></> } },
    { tag: <>RISK</>, zh: { title: <>vs VS Code 的生态壁垒</>, body: <><p>VS Code 的扩展市场 (数万个) 和默认地位是真实护城河, Zed 的扩展生态还在追。Zed 的差异化在原生延迟 + AI-native, 但"我那个冷门语言 / 工具的插件 Zed 有没有"仍是劝退点。1.0 跨平台齐全后这条会缓和, 但生态厚度不是一年能追平的。</p></> }, en: { title: <>vs VS Code's ecosystem moat</>, body: <><p>VS Code's extension marketplace (tens of thousands) and default status are a real moat; Zed's extension ecosystem is still catching up. Zed differentiates on native latency + AI-native, but "does Zed have a plugin for my niche language / tool" remains a turn-off. Post-1.0 cross-platform parity eases it, but ecosystem depth isn't closed in a year.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>诚实地说:cuberoot.me 这个仓库的代码<strong>几乎全部</strong>在 Claude Code CLI 里写出来 —— Read / Edit / Bash / Grep 加子 agent、skill、跨会话 memory, 这套自然语言 + 工具调用的流程承担了绝大部分增删改。Zed 在这里不是"主力码字工具", 它的定位是<strong>图形编辑器</strong>:看代码、跳符号、review diff、偶尔手动微调。</p>
        <p>具体怎么用:agent 改完一批文件后, 在 Zed 里打开看 diff 比纯终端直观 —— 它的 Git 面板能逐 hunk review staged 改动, multibuffer 能把一次改动散落在 <code>core/packages/client</code> 多个文件的片段拼到一屏。在这个 Next.js 16 App Router + React 19 的主工作区里跳转组件 / 找 hook 定义, tree-sitter + LSP 比 grep 更准。偶尔需要手动改一两行 (调个 CSS 色值、挪个 import) 时, 直接在 Zed 里改比起一句话指挥 agent 更快。</p>
        <p>Zed 自带 AI agent 面板和 ACP, 理论上可以把 Claude 接进编辑面板直接改 buffer。这跟 Claude Code 是<strong>互补</strong>关系:Claude Code 强在终端原生 / 可脚本化 / 子 agent 并行 / 跨会话 memory, 适合"一句话跑完一个完整任务";Zed 强在图形化的代码导航和 diff 审阅, 适合"人快速看清 agent 做了什么、在哪手动接管一下"。本项目的现实是前者占绝大头, Zed 是趁手的眼睛和方向盘。</p>
        <p>环境上对得很顺:主开发机是 Windows 11 Pro + pwsh 7 (Zed 2025-10 后 Windows GA, 三平台一致, 跟开发机没有断层), monorepo 用 pnpm + Turbo, 后端 Hono 跑在 <code>api.cuberoot.me</code> (Node 22 + pm2 + PG 13)。不夸大:Zed 在本项目里不是必需品, 但作为配合 Claude Code 的图形编辑器, 它原生的速度和对 AI agent 的一等公民支持, 跟这个仓库"几乎全 AI 写"的工作方式是同一个方向的。</p>
      </>
    ),
    en: (
      <>
        <p>Honestly: the code in the cuberoot.me repo is written <strong>almost entirely</strong> inside the Claude Code CLI — Read / Edit / Bash / Grep plus subagents, skills, and cross-session memory; that natural-language + tool-call flow carries the vast majority of add/edit/delete. Zed here is not the "primary typing tool"; its role is the <strong>GUI editor</strong>: reading code, jumping symbols, reviewing diffs, occasional hand-tweaks.</p>
        <p>Concretely: after an agent edits a batch of files, opening the diff in Zed is more legible than the raw terminal — its Git panel reviews staged changes hunk by hunk, and a multibuffer stitches one change's fragments scattered across multiple files in <code>core/packages/client</code> onto one screen. In this Next.js 16 App Router + React 19 main workspace, jumping components / finding hook definitions via tree-sitter + LSP beats grep on precision. When a manual one- or two-line edit is needed (a CSS color value, moving an import), editing directly in Zed is faster than dictating it to an agent.</p>
        <p>Zed ships its own AI agent panel and ACP, so in principle Claude can be wired into the editor panel to edit the buffer directly. This is <strong>complementary</strong> to Claude Code: Claude Code is strong on terminal-native / scriptable / parallel subagents / cross-session memory, suited to "run a full task from one sentence"; Zed is strong on graphical code navigation and diff review, suited to "a human quickly seeing what the agent did and manually taking over where needed." The reality of this project is that the former does the overwhelming majority; Zed is a handy set of eyes and a steering wheel.</p>
        <p>The environment fits cleanly: the main dev machine is Windows 11 Pro + pwsh 7 (Zed went Windows-GA in 2025-10, consistent across the three platforms with no gap from the dev box), the monorepo uses pnpm + Turbo, and the Hono backend runs at <code>api.cuberoot.me</code> (Node 22 + pm2 + PG 13). Without overstating it: Zed isn't a necessity in this project, but as the GUI editor alongside Claude Code, its native speed and first-class AI-agent support point the same direction as this repo's "almost entirely AI-written" way of working.</p>
      </>
    ),
  },
  links: [
    { label: 'zed.dev', href: 'https://zed.dev' },
    { label: 'GitHub · zed-industries/zed', href: 'https://github.com/zed-industries/zed' },
    { label: 'Zed is 1.0 (blog)', href: 'https://zed.dev/blog/zed-1-0' },
    { label: 'Zed is now open source (blog)', href: 'https://zed.dev/blog/zed-is-now-open-source' },
    { label: 'GPUI', href: 'https://www.gpui.rs' },
    { label: 'Agent Client Protocol', href: 'https://agentclientprotocol.com' },
  ],
};

export default ZED;
