import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, s, n, f, p, c, t } from '../_lib/stack_tool_types';

// ─── Zustand 5 ──────────────────────────────────────────────────────────────

export const ZUSTAND: StackTool = {
  slug: 'zustand',
  name: 'Zustand',
  version: '5.0.x',
  since: '2019-09',
  group: 'frontend',
  accent: '#B57655',
  bright: '#E4A977',
  glyph: 'ʕ',
  floats: ['create', 'useStore', 'set', 'get', 'subscribe', 'persist', 'devtools', 'immer', 'selector', 'shallow', 'useShallow', 'slices'],
  zh: {
    tagline: '简到极致的 React 状态管理',
    role: '客户端跨页持久状态:auth / settings / sessions / trainer / battle / calc / mosaic / viz / recon 共 11 个 store。',
    heroSub: <>Redux 上的样板代码厌倦了, Context 一旦树深就 re-render 全屋, MobX 不熟魔法不敢用 —— Daishi Kato 2019 年在 Poimandres 集体写了 Zustand:<strong><code>create()</code> 返回一个 hook, 没有 Provider, 没有 reducer, 没有 action type 字符串</strong>。六年后, 它在 npm 上每周下载千万, 在新建 React 项目里超过 Redux Toolkit, 成为事实上的首选。</>,
    whatDesc: <>Zustand 是一个 <strong>体积约 1.16 KB 的 React 状态管理库</strong>, 内核是一个发布订阅 store + React 18+ 的 <code>useSyncExternalStore</code> 适配。API 一只手数得过来:<code>create</code> / <code>set</code> / <code>get</code> / <code>subscribe</code>, 加几个可选 middleware (persist / devtools / immer)。"够用 + 没噪声" 是它最锋利的部分。</>,
    historyDesc: <>2019 年 Daishi Kato 在 Poimandres (react-three-fiber 那个集体) 顺手做的库, 起点是给 r3f 的内部状态找一个比 Redux 更轻的方案。Jotai / Valtio / Zustand 三兄弟同期出生, Zustand 走的是"vanilla store + selector hook" 这条最朴素的路, 反而后来跑得最远。</>,
    conceptsTitle: 'create + selector + middleware',
    conceptsDesc: <>可观察 API 极小:<code>create()</code> 返回一个 hook、组件里调 hook 传 selector 拿想要的切片、需要时套 middleware (<code>persist</code> / <code>devtools</code> / <code>immer</code> / <code>subscribeWithSelector</code>)。再往下是 <code>useShallow</code> 让多字段选择不无谓 re-render。</>,
    whyDesc: <>2026 年新项目继续选 Zustand 而不是 Redux Toolkit / Jotai / Context, 不是性能差异 (基本拉平), 而是<strong>没有 Provider</strong>、<strong>没有 reducer 仪式</strong>、<strong>能在 React 外用</strong>、<strong>AI 写得最对</strong>这四件事其它方案不全。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>Pmndrs 全家桶 (react-three-fiber / drei / leva) 起家就是它, Vercel / Cursor / Bluesky web / Excalidraw / Linear 内部都有 Zustand store。AI 一代工具生成 React 状态时几乎默认这套。本站 11 个 store 也全跑在它上面。</>,
    cuberootDesc: <>整个客户端的全局 / 跨页状态都在 Zustand store 里:<code>auth_store</code> (WCA OAuth 用户)、<code>settingsStore</code> (主题 / 语言 / trainer 配置, persist 到 localStorage)、<code>sessionStore</code> (当前 solve session)、<code>statsStore</code> (WCA 查询参数)、<code>trainerStore</code> / <code>recon_store</code>, 加上四个 page-local store (battle / calc / mosaic / viz)。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>5.0 (2024-11) 砍 React 17, 强制 18+, 内部清理一轮包大小再降。同期 React Compiler + <code>useShallow</code> 让 selector 写起来更准, RSC 时代 client-side store 边界更清晰。Zustand 没有"下一个大版本要重做" 的剧本, 这本身就是稳定的承诺。</>,
  },
  en: {
    tagline: 'Bear-minimum React state management',
    role: 'Client-side cross-page state — 11 stores: auth / settings / sessions / trainer / battle / calc / mosaic / viz / recon.',
    heroSub: <>Tired of Redux boilerplate, scared of Context re-rendering the whole tree, and not fluent enough in MobX to dare use the magic — in 2019 Daishi Kato wrote Zustand inside Poimandres: <strong><code>create()</code> returns a hook. No Provider, no reducers, no action-type strings.</strong> Six years later it sees tens of millions of weekly npm downloads and has overtaken Redux Toolkit as the de-facto pick for new React projects.</>,
    whatDesc: <>Zustand is a <strong>~1.16 KB React state library</strong>. The kernel is a pub-sub store + a React 18 <code>useSyncExternalStore</code> adapter. The whole API fits on one hand: <code>create</code> / <code>set</code> / <code>get</code> / <code>subscribe</code>, plus a few optional middlewares (persist / devtools / immer). "Just enough, zero noise" is its sharpest edge.</>,
    historyDesc: <>Built by Daishi Kato in 2019 inside Poimandres (the react-three-fiber collective). The seed was a Redux-lighter solution for r3f's internal state. Jotai / Valtio / Zustand are siblings born around the same time; Zustand took the most boring path — vanilla store + selector hook — and ended up traveling the furthest.</>,
    conceptsTitle: 'create + selector + middleware',
    conceptsDesc: <>The observable API is tiny: <code>create()</code> returns a hook, components call the hook with a selector to pick a slice, and middlewares (<code>persist</code> / <code>devtools</code> / <code>immer</code> / <code>subscribeWithSelector</code>) wrap as needed. <code>useShallow</code> sits on top, keeping multi-field reads from re-rendering for free.</>,
    whyDesc: <>Picking Zustand in 2026 over Redux Toolkit / Jotai / Context isn't about perf (basically equal). It's the combination: <strong>no Provider</strong>, <strong>no reducer ceremony</strong>, <strong>usable outside React</strong>, <strong>LLMs get it right</strong> — none of the alternatives ticks all four boxes.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Pmndrs (react-three-fiber / drei / leva) was the original home. Vercel / Cursor / Bluesky web / Excalidraw / Linear all have Zustand stores in production. The AI-tool generation defaults to it when emitting React state. This site's 11 stores ride it too.</>,
    cuberootDesc: <>All global / cross-page state on the client lives in Zustand stores: <code>auth_store</code> (WCA OAuth user), <code>settingsStore</code> (theme / language / trainer config, persisted to localStorage), <code>sessionStore</code> (current solve session), <code>statsStore</code> (WCA query params), <code>trainerStore</code> / <code>recon_store</code>, plus four page-local stores (battle / calc / mosaic / viz).</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>5.0 (2024-11) drops React 17, requires 18+, and trims the bundle further. React Compiler + <code>useShallow</code> tighten selectors; the RSC era sharpens the client-side store boundary. There's no "next big rewrite" looming — that absence is itself the stability promise.</>,
  },
  heroStats: [
    { num: '5', unit: '.0', zh: <>当前稳定 <em>2024-11 起,2026-05 仍 5.0.x</em></>, en: <>current stable <em>5.0.x since 2024-11</em></>
    },
    { num: '~1', unit: '.16 KB', zh: <>min+gzip 包大小 <em>bundlephobia</em></>, en: <>min+gzip bundle size <em>bundlephobia</em></> },
    { num: '~50', unit: 'k+', zh: <>GitHub stars <em>pmndrs/zustand</em></>, en: <>GitHub stars <em>pmndrs/zustand</em></> },
    { num: '11', zh: <>本站 store 数量 <em>6 全局 + 5 页面级</em></>, en: <>stores on this site <em>6 global + 5 page-local</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>Zustand 是 Daishi Kato 2019 年 9 月在 Poimandres 集体下开源的小库。Poimandres 是 react-three-fiber 那帮人, Kato 同时还在维护 Jotai 和 Valtio。三个状态库同时长出来, 各自占一种心智模型:Jotai 走 atom 派、Valtio 走 proxy 派、Zustand 走 vanilla store 派。前两个聪明, 第三个朴素 —— 然后朴素那个跑赢了。</p>
        <p>Zustand 的设计起点几乎是反 Redux 的:不要 Provider、不要 reducer、不要 action type 字符串、不要 dispatch。<code>create()</code> 返回一个 hook, 组件传 selector 拿切片就完事。state 可以直接 mutate 风格 (<code>set(state =&gt; ({'{...}'}))</code>), 也可以原样替换。整套 API 一只手数得过来, README 上能看完。</p>
        <p>从 2019 niche 到 2024 主流, 中间没有任何戏剧性事件。每个版本只做"包再小一点 / 类型再准一点 / middleware 再多一点"。2024-11 的 5.0 砍掉 React 17 支持, 内部清理一轮, 至今最新仍是 5.0.x。Redux Toolkit 还在更新, 但<strong>新建项目里 Zustand 已经反超</strong>。React 社区罕见地在状态管理这条线上达成共识:够用就是最好的。</p>
      </>
    ),
    en: (
      <>
        <p>Zustand was open-sourced by Daishi Kato under the Poimandres collective in September 2019. Poimandres is the react-three-fiber group; Kato also maintains Jotai and Valtio. Three state libraries grew at the same time, each occupying a mental model — Jotai's atoms, Valtio's proxies, Zustand's vanilla store. The first two are clever; the third is boring. The boring one won.</p>
        <p>Zustand's starting point is almost anti-Redux: no Provider, no reducers, no action-type strings, no dispatch. <code>create()</code> returns a hook; components pass a selector to read a slice and that's it. State can be set in a mutate-ish style (<code>set(state =&gt; ({'{...}'}))</code>) or replaced wholesale. The whole API fits in one hand and reads end-to-end on the README.</p>
        <p>The 2019-to-2024 arc had no drama. Each release just made the bundle smaller, the types sharper, or shipped another middleware. 5.0 (2024-11) dropped React 17 support and cleaned the internals; 5.0.x is still current. Redux Toolkit ships on, but <strong>new projects pick Zustand more often now</strong>. The React community quietly converged on state management, and the consensus is: enough is the best.</p>
      </>
    ),
  },
  history: [
    { year: '2019·09', zh: { title: <>首次开源</>, desc: <>Daishi Kato 在 Poimandres 下首次推送 zustand 仓库, README 一页搞定。最初是给 react-three-fiber 内部状态用的副产物。</> }, en: { title: <>First open-source push</>, desc: <>Daishi Kato pushes the first commit under Poimandres. README fits on one page. Born as a side-effect of building react-three-fiber's internal state.</> } },
    { year: '2020', zh: { title: <>middleware 雏形</>, desc: <>persist / devtools / subscribeWithSelector 这套 middleware 陆续落地。"小核心 + 可选附加" 的形态确立, 之后再没变过。</> }, en: { title: <>Middleware shape settles</>, desc: <>persist / devtools / subscribeWithSelector all land. The "tiny core + opt-in addons" shape is set, and never changes after.</> } },
    { year: '2021·04', zh: { title: <>3.0</>, desc: <>API 收敛, 类型重写。同期 Jotai / Valtio 各自发版, 三兄弟一起进入 Pmndrs 全家桶。</> }, en: { title: <>3.0</>, desc: <>API converges; types are rewritten. Jotai / Valtio cut releases alongside; the three siblings settle into the Pmndrs stack.</> } },
    { year: '2022·06', zh: { title: <>4.0 + immer 集成</>, desc: <>4.0 重做 TS 类型 (curried create 解决泛型推导), immer middleware 正式进官方。"persist / devtools / immer 三件套" 成为大型应用标配。</> }, en: { title: <>4.0 + first-class immer</>, desc: <>4.0 reworks TS types (curried <code>create()</code> fixes generic inference); the immer middleware becomes official. The persist / devtools / immer trio becomes standard for larger apps.</> } },
    { year: '2023·05', zh: { title: <>useSyncExternalStore 切换</>, desc: <>内部切到 React 18 的 <code>useSyncExternalStore</code> 钩子, concurrent rendering 下 tearing 问题彻底关掉。</> }, en: { title: <>useSyncExternalStore migration</>, desc: <>Internals move to React 18's <code>useSyncExternalStore</code>. Tearing under concurrent rendering is closed for good.</> } },
    { year: '2023·11', zh: { title: <>周下载破千万</>, desc: <>npm 周下载量首次超过 1000 万。同期 Redux Toolkit 增速放缓, 新项目占比开始反转。</> }, en: { title: <>10M+ weekly downloads</>, desc: <>Weekly npm downloads cross 10M for the first time. Redux Toolkit's growth slows; the new-project share starts flipping.</> } },
    { year: '2024·05', zh: { title: <>useShallow 进官方</>, desc: <>多字段 selector 常被 "返回新对象引用" 拖累, <code>useShallow</code> 把浅比较做成一等公民, 写法回到符合直觉。</> }, en: { title: <>useShallow lands in core</>, desc: <>Multi-field selectors used to suffer from new-reference re-renders; <code>useShallow</code> makes shallow comparison first-class and selectors read naturally again.</> } },
    { year: '2024·11', highlight: true, zh: { title: <>5.0 GA</>, desc: <>砍 React 17, 强制 React 18+。内部清理一轮, 包体再降。<code>createStore</code> 跟 <code>create</code> 拆开导出, vanilla 用法更明确。</> }, en: { title: <>5.0 GA</>, desc: <>Drops React 17, requires 18+. Internals cleaned, bundle shrinks further. <code>createStore</code> and <code>create</code> split into separate exports — vanilla usage is more explicit.</> } },
    { year: '2025·06', zh: { title: <>State of React: 反超 RTK</>, desc: <>State of React 调查里 Zustand 在 "新项目首选" 这一栏首次超过 Redux Toolkit。"小而锐" 路线赢下一轮共识。</> }, en: { title: <>State of React: surpasses RTK</>, desc: <>In the State of React survey Zustand passes Redux Toolkit on "first choice for new projects." The "small and sharp" approach wins a round of consensus.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>5.0.x / 当前稳定</>, desc: <>2026-05 仍是 5.0 系列。本仓库 client package.json 锁的是 <code>^5.0.0</code>。没有 6.0 路线图, 没有大变要求迁移。</> }, en: { title: <>5.0.x / current stable</>, desc: <>Still on the 5.0 line as of 2026-05. The client's package.json pins <code>^5.0.0</code>. No 6.0 roadmap, no looming breaking migration.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>create() 返回 hook</>, desc: <>调用 <code>create</code> 拿到一个 React hook, 整个 store 没有 Provider, 直接 import 直接用。</> }, en: { title: <>create() returns a hook</>, desc: <>Call <code>create</code> and get a React hook. No Provider — import it and use it.</> }, code: <code>{k('import')} {'{ '}{v('create')} {'}'} {k('from')} {s("'zustand'")};{'\n\n'}{k('export const')} {v('useCounter')} = {f('create')}&lt;{t('State')}&gt;()(({v('set')}) =&gt; ({'{'}{'\n'}  {p('count')}: {n('0')},{'\n'}  {p('inc')}: () =&gt; {f('set')}(({v('s')}) =&gt; ({'{ '}{p('count')}: {v('s')}.{p('count')} + {n('1')} {'}'})),{'\n'}{'}'}));</code> },
    { tag: 'B', zh: { title: <>selector + useStore</>, desc: <>组件里调 hook 传 selector, 只在<strong>selector 结果变化</strong>时 re-render。粒度由 selector 决定。</> }, en: { title: <>Selector + useStore</>, desc: <>Call the hook with a selector inside a component; re-renders only when <strong>the selector result changes</strong>. Granularity is in your hands.</> }, code: <code>{k('const')} {v('count')} = {f('useCounter')}(({v('s')}) =&gt; {v('s')}.{p('count')});{'\n'}{k('const')} {v('inc')} = {f('useCounter')}(({v('s')}) =&gt; {v('s')}.{p('inc')});{'\n'}{c('// count 变才 re-render, inc 永不变')}</code> },
    { tag: 'C', zh: { title: <>set 合并 vs 替换</>, desc: <>默认 <code>set</code> 浅合并到 root state, 第二参数 <code>true</code> 时整体替换。函数形式拿到旧 state, 类似 React useState。</> }, en: { title: <>set merge vs replace</>, desc: <>By default <code>set</code> shallow-merges into root state; pass <code>true</code> as the second arg to replace wholesale. Functional form gets the previous state, like React's useState.</> }, code: <code>{f('set')}({'{ '}{p('count')}: {n('5')} {'}'});           {c('// shallow merge')}{'\n'}{f('set')}({'{ '}{p('count')}: {n('0')} {'}'}, {v('true')});     {c('// replace entire state')}{'\n'}{f('set')}(({v('s')}) =&gt; ({'{ '}{p('count')}: {v('s')}.{p('count')} + {n('1')} {'}'}));</code> },
    { tag: 'D', zh: { title: <>subscribe 在 React 外</>, desc: <>store 本质是 vanilla pub-sub, 任何 JS 代码 (worker / Node / RAF loop) 都能 <code>subscribe</code> 听变化, 不依赖 React。</> }, en: { title: <>subscribe outside React</>, desc: <>The store is plain pub-sub. Any JS — workers, Node, an RAF loop — can <code>subscribe</code> and react. No React dependency.</> }, code: <code>{k('const')} {v('unsub')} = {f('useCounter')}.{f('subscribe')}(({v('s')}) =&gt; {'{'}{'\n'}  {f('console')}.{f('log')}({s("'count is now'")}, {v('s')}.{p('count')});{'\n'}{'}'});{'\n\n'}{c('// cleanup later')}{'\n'}{f('unsub')}();</code> },
    { tag: 'E', zh: { title: <>persist middleware</>, desc: <>套一层 <code>persist</code> 自动 localStorage / sessionStorage 同步, 给个 <code>name</code> key 就完事。本站 <code>settingsStore</code> 就是这么持久化 theme / 语言的。</> }, en: { title: <>persist middleware</>, desc: <>Wrap with <code>persist</code> for automatic localStorage / sessionStorage sync — just give it a <code>name</code> key. This site's <code>settingsStore</code> persists theme + language exactly this way.</> }, code: <code>{k('import')} {'{ '}{v('persist')} {'}'} {k('from')} {s("'zustand/middleware'")};{'\n\n'}{f('create')}&lt;{t('Settings')}&gt;()({'\n'}  {f('persist')}({'\n'}    ({v('set')}) =&gt; ({'{ '}{p('theme')}: {s("'dark'")}, {p('setTheme')}: ({v('t')}) =&gt; {f('set')}({'{ '}{p('theme')}: {v('t')} {'}'}) {'}'}),{'\n'}    {'{ '}{p('name')}: {s("'trainer-settings'")} {'}'},{'\n'}  ),{'\n'});</code> },
    { tag: 'F', zh: { title: <>devtools middleware</>, desc: <>套 <code>devtools</code> 接 Redux DevTools 浏览器扩展, 看 action 时间轴 + state diff。开发期免费, 生产 tree-shake 掉。</> }, en: { title: <>devtools middleware</>, desc: <>Wrap with <code>devtools</code> to connect Redux DevTools — action timeline + state diffs in the browser. Free in dev, tree-shaken in prod.</> }, code: <code>{k('import')} {'{ '}{v('devtools')} {'}'} {k('from')} {s("'zustand/middleware'")};{'\n\n'}{f('create')}&lt;{t('State')}&gt;()(({'\n'}  {f('devtools')}(({v('set')}) =&gt; ({'{ '}{p('count')}: {n('0')} {'}'}), {'{ '}{p('name')}: {s("'counter'")} {'}'}){'\n'}));</code> },
    { tag: 'G', zh: { title: <>immer middleware</>, desc: <>嵌套 state 改起来麻烦时套 <code>immer</code>, 写法变成"直接 mutate", immer 帮你返回新引用。大型 state 树常用。</> }, en: { title: <>immer middleware</>, desc: <>For deeply nested state, wrap with <code>immer</code> and write "mutate"-style code; immer hands back a new reference. Common in larger state trees.</> }, code: <code>{k('import')} {'{ '}{v('immer')} {'}'} {k('from')} {s("'zustand/middleware/immer'")};{'\n\n'}{f('create')}&lt;{t('State')}&gt;()(({f('immer')}(({v('set')}) =&gt; ({'{'}{'\n'}  {p('todos')}: [],{'\n'}  {p('add')}: ({v('t')}) =&gt; {f('set')}(({v('s')}) =&gt; {'{ '}{v('s')}.{p('todos')}.{f('push')}({v('t')}); {'}'}),{'\n'}{'}'}))));</code> },
    { tag: 'H', zh: { title: <>useShallow 多字段</>, desc: <>需要从 store 读多个字段同时 minimal re-render 时, 套 <code>useShallow</code> 让 React 跑浅比较而非 ===。</> }, en: { title: <>useShallow for multi-field reads</>, desc: <>Reading several fields and want re-renders kept minimal? Wrap the selector in <code>useShallow</code> to compare shallowly instead of with ===.</> }, code: <code>{k('import')} {'{ '}{v('useShallow')} {'}'} {k('from')} {s("'zustand/react/shallow'")};{'\n\n'}{k('const')} {'{ '}{v('a')}, {v('b')} {'}'} = {f('useStore')}({f('useShallow')}(({v('s')}) =&gt; ({'{ '}{p('a')}: {v('s')}.{p('a')}, {p('b')}: {v('s')}.{p('b')} {'}'})));</code> },
  ],
  whyCards: [
    { icon: '⌬', zh: { title: <>没有 Provider</>, desc: <>不用在 root 套一层 <code>&lt;Provider store={'{...}'}&gt;</code>。store 是 module-scope 的 hook, 哪里 import 哪里能用。SSR 下需要时再用 vanilla store + context, 但默认不需要。</> }, en: { title: <>No Provider</>, desc: <>No wrapping <code>&lt;Provider store={'{...}'}&gt;</code> at the root. The store is a module-scoped hook — import where you need it. For SSR you can pair vanilla store + context, but the default needs neither.</> }, code: <>{c('// No <Provider>, just:')}{'\n'}{k('const')} {v('user')} = {f('useAuthStore')}(({v('s')}) =&gt; {v('s')}.{p('user')});</> },
    { icon: '⚙', zh: { title: <>~1.16 KB min+gzip</>, desc: <>核心 ~1.16 KB, 加 persist / devtools 总共也就 ~3 KB。比 Redux Toolkit (~13 KB) 小一个数量级, 对首屏 bundle 几乎透明。</> }, en: { title: <>~1.16 KB min+gzip</>, desc: <>Core is ~1.16 KB; even with persist + devtools the total is ~3 KB. An order of magnitude smaller than Redux Toolkit (~13 KB) — invisible to first-load budget.</> }, code: <>{c('// bundlephobia')}{'\n'}{c('// zustand: 1.16 KB')}{'\n'}{c('// @reduxjs/toolkit: 13 KB')}</> },
    { icon: '⌖', zh: { title: <>TS 推导一条龙</>, desc: <>curried <code>create()</code> 让泛型推导干净, state shape 一次写完整个 store 类型自动跑出来。本站 strict mode 零 any。</> }, en: { title: <>End-to-end TS inference</>, desc: <>The curried <code>create()</code> form keeps generic inference clean — write the state shape once and the whole store's types fall out. Strict mode, zero "any" on this site.</> }, code: <>{f('create')}&lt;{t('State')}&gt;()(({v('set')}) =&gt; ({'{...}'}));{'\n'}{c('// types flow through everywhere')}</> },
    { icon: '⎇', zh: { title: <>在 React 外也能用</>, desc: <>store 本质 vanilla, <code>useCounter.getState()</code> / <code>.subscribe()</code> 直接在 worker、Node 脚本、RAF loop 里调。本站 trainer worker 跨 worker 读 settings 就靠这个。</> }, en: { title: <>Works outside React too</>, desc: <>The store is vanilla. <code>useCounter.getState()</code> / <code>.subscribe()</code> work in workers, Node scripts, RAF loops. This site's trainer worker reads settings across the worker boundary via exactly this.</> }, code: <>{k('const')} {v('snap')} = {f('useCounter')}.{f('getState')}();{'\n'}{f('useCounter')}.{f('subscribe')}({v('onChange')});</> },
    { icon: '⏚', zh: { title: <>selector 控粒度</>, desc: <>组件挑 selector 就挑了订阅粒度。只读 <code>count</code> 的组件不会因 <code>theme</code> 变就 re-render。Context 做不到这件事。</> }, en: { title: <>Selectors control granularity</>, desc: <>Picking a selector picks the subscription granularity. A component reading only <code>count</code> won't re-render when <code>theme</code> changes. Context can't do this.</> }, code: <>{f('useStore')}(({v('s')}) =&gt; {v('s')}.{p('count')});  {c('// re-renders on count only')}</> },
    { icon: '⌗', zh: { title: <>middleware 生态齐</>, desc: <>persist / devtools / immer / subscribeWithSelector / combine / redux 兼容层全部官方。社区 middleware (auth / undo / sync) 套 <code>create</code> 就能用。</> }, en: { title: <>Middleware ecosystem</>, desc: <>persist / devtools / immer / subscribeWithSelector / combine / redux-compat — all official. Community middlewares (auth, undo, sync) stack onto <code>create</code> directly.</> }, code: <>{f('create')}(({f('devtools')}(({f('persist')}(({f('immer')}({v('store')})), {'{...}'}))));</> },
    { icon: '⌁', zh: { title: <>心智模型 = vanilla pubsub</>, desc: <>没什么"魔法"。store 就是个 listener 集合, set 触发通知。任何前端工程师 30 秒能看明白源码主干。</> }, en: { title: <>Mental model = vanilla pub-sub</>, desc: <>No magic. The store is a listener set; <code>set</code> notifies. Any frontend engineer can read the core source in 30 seconds.</> }, code: <>{c('// store = { state, listeners }')}{'\n'}{c('// set() → forEach(listeners)')}</> },
    { icon: '⛯', zh: { title: <>AI codegen 写得最对</>, desc: <>LLM 训练数据里 Zustand 例子量大、形态一致 (没有 Redux 那种 reducer / action type / dispatch 三层模板), 生成的代码 IDE 上红波浪线最少。</> }, en: { title: <>LLMs emit it correctly</>, desc: <>Training data has abundant, uniform Zustand examples (no Redux-style reducer / action-type / dispatch trio). LLM-generated state code shows the fewest IDE red squiggles.</> }, code: <>{c('// "Add a counter store"')}{'\n'}{c('// LLMs: 95%+ emit Zustand')}</> },
    { icon: '⚐', zh: { title: <>无大版本剧本</>, desc: <>5.0 之后没有 6.0 路线图。"已经做完了" 的状态库, 在仍在改的世界里反而成了稀缺资源。</> }, en: { title: <>No major-version drama</>, desc: <>No 6.0 roadmap after 5.0. A "done" state library is a rare asset in a world that keeps churning.</> }, code: <>{c('// pin ^5.0.0, forget about it')}</> },
  ],
  adopters: [
    { name: 'Pmndrs (react-three-fiber / drei / leva)', href: 'https://github.com/pmndrs', highlight: true, zhNote: '亲爹集体, r3f 内部状态用了一直没换', enNote: 'Origin collective — r3f internals use it and never switched away' },
    { name: 'Vercel', href: 'https://vercel.com', highlight: true, zhNote: 'Next.js 内部 + dashboard 多处 Zustand store', enNote: 'Next.js internals and dashboard run Zustand stores' },
    { name: 'Cursor', href: 'https://cursor.com', highlight: true, zhNote: 'AI IDE, Electron + React + Zustand', enNote: 'AI IDE — Electron + React + Zustand' },
    { name: 'Excalidraw', href: 'https://excalidraw.com', zhNote: '画板状态走 Zustand', enNote: 'Whiteboard state runs on Zustand' },
    { name: 'Bluesky (web)', href: 'https://bsky.app', zhNote: 'Web 客户端部分 store 用 Zustand', enNote: 'Web client uses Zustand for several stores' },
    { name: 'Linear', href: 'https://linear.app', zhNote: '部分 client state 走 Zustand', enNote: 'Several client stores run on Zustand' },
    { name: 'Lobe Chat', href: 'https://lobehub.com', zhNote: 'LLM 客户端, 全量 Zustand + persist', enNote: 'LLM client — Zustand throughout, with persist' },
    { name: 'Vinxi / TanStack Start', href: 'https://tanstack.com', zhNote: '示例和模板里 Zustand 是默认', enNote: 'Examples and starters default to Zustand' },
    { name: 'Mui Toolpad', href: 'https://mui.com/toolpad', zhNote: '低代码平台的 page-local state', enNote: 'Page-local state in the low-code platform' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 11 个 store, 全部 Zustand 5', enNote: 'This site — 11 stores, all on Zustand 5' },
  ],
  outlook: [
    { tag: <>HOT · 2024-11</>, hot: true, big: true, zh: { title: <>5.0 — React 18+ 时代</>, body: <><p>5.0 砍 React 17 支持, 强制 18+, 内部全面切到 <code>useSyncExternalStore</code>。concurrent rendering 下的 tearing 风险关掉, types 重排, <code>createStore</code> (vanilla) 跟 <code>create</code> (React) 拆开。</p><p>外部接口几乎没动 —— 用户代码从 4.x 升 5.x 的迁移工作基本是改 React 依赖号。这是 Zustand 维护团队的一贯风格:版本号往上跳, 用户感知尽可能小。</p></> }, en: { title: <>5.0 — the React 18+ era</>, body: <><p>5.0 drops React 17, mandates 18+, and moves the internals fully onto <code>useSyncExternalStore</code>. Concurrent-rendering tearing is closed off, types are reshuffled, and <code>createStore</code> (vanilla) is split from <code>create</code> (React).</p><p>The external API barely moves — migrating user code from 4.x to 5.x is mostly bumping the React peer dep. That's the maintainer style: bump the version, keep user-facing churn near zero.</p></> } },
    { tag: 'RSC', zh: { title: <>RSC 时代的 client store</>, body: <><p>RSC 把"什么数据在服务器、什么在 client"画了条新线。Zustand 自然落到 client side, 配合 <code>'use client'</code> 边界用。Pmndrs 在文档里加了 SSR / RSC 整合模式, 用 context 配 vanilla store 安全 hydration。</p></> }, en: { title: <>Client store in the RSC era</>, body: <><p>RSC redraws the "what lives on the server vs client" line. Zustand naturally sits on the client side, behind <code>'use client'</code> boundaries. Pmndrs documents an SSR / RSC pattern using context + a vanilla store for safe hydration.</p></> } },
    { tag: 'COMPILER', zh: { title: <>React Compiler + useShallow</>, body: <><p>React Compiler 自动 memoize 大部分 props, 但 store selector 仍由用户决定粒度。<code>useShallow</code> 让多字段读法接近"零样板", 跟 Compiler 协同后, 一份 state-heavy 组件几乎再没有手写 memo 的必要。</p></> }, en: { title: <>React Compiler + useShallow</>, body: <><p>The React Compiler auto-memoizes most props, but selector granularity is still the user's call. <code>useShallow</code> makes multi-field reads near-zero-boilerplate; together with the Compiler, state-heavy components hardly need hand-rolled memos anymore.</p></> } },
    { tag: 'TS', zh: { title: <>TS 5.x 推导更稳</>, body: <><p>curried <code>create()</code> 在 TS 5.x 下推导路径更短, 之前需要写 <code>StateCreator&lt;...&gt;</code> 才能稳的 middleware 组合, 现在多数能直接推。slice 模式 (把大 store 拆若干小 creator 再 combine) 也少了几行 type annotation。</p></> }, en: { title: <>Sharper TS 5.x inference</>, body: <><p>The curried <code>create()</code> form has a shorter inference path on TS 5.x. Middleware combinations that previously needed an explicit <code>StateCreator&lt;...&gt;</code> now mostly infer cleanly. The slice pattern (split a large store into small creators and combine) also sheds a few annotation lines.</p></> } },
    { tag: <>VS RTK</>, zh: { title: <>跟 Redux Toolkit 长期共存</>, body: <><p>Redux Toolkit 没有被替代, 它在大型企业项目 + 需要严格 audit 的场景仍是更合适的选择 (action 时间轴 + replay 调试)。Zustand 占的是"新建项目 + 中小型 + AI 写代码" 这一段。两边长期共存, 不是零和。</p></> }, en: { title: <>Long-term coexistence with Redux Toolkit</>, body: <><p>RTK isn't being replaced — for large enterprise projects and audit-heavy contexts (action timelines, replay debugging) it remains the better fit. Zustand owns "new projects + small-to-medium + AI-emitted code." The two coexist long-term; this isn't a zero-sum game.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本站客户端的全局状态都跑在 Zustand 5 上, 一共 11 个 store, 分两层:</p>
        <p><strong>6 个全局 store</strong> 在 <code>src/stores/</code>:<code>auth_store</code> (WCA OAuth 用户信息, 监听 <code>window 'storage'</code> 事件做跨 tab 同步)、<code>settingsStore</code> (主题 / 语言 / trainer 配置, 套 <code>persist</code> 中间件落 localStorage key <code>trainer-settings</code>)、<code>sessionStore</code> (当前 solve session)、<code>statsStore</code> (WCA 查询参数, 跨 wca 子页共享)、<code>trainerStore</code> (训练 session, 自带 timer state machine)、<code>recon_store</code> (recon 缓存)。</p>
        <p><strong>5 个 page-local store</strong> 跟着各自页面落地:<code>pages/battle/engine/battle_store</code>、<code>pages/calc/stores/calc_store</code>、<code>pages/mosaic/state/store</code>、<code>pages/viz/stores/viz_store</code> 以及 viz canvas 内部还有一组小 store。这类 store 跨 page 不共享, 用 page-local 是因为单页内部 state 树深度足够大、组件间需要 selector 控粒度。</p>
        <p>没有 Provider —— React 树顶层就是 <code>&lt;BrowserRouter&gt;</code> 包 <code>&lt;Routes&gt;</code>, 没有任何 store provider 在中间。每个组件直接 <code>import {'{ useAuthStore }'} from '../stores/auth_store'</code> 然后调 selector, 就完事。<code>useShallow</code> 在多字段读取的地方 (PlayerControls / SimPage 等) 兜底, 避免无意义 re-render。整个客户端的 strict mode 类型推导没有任何一行被 Zustand 卡住。</p>
      </>
    ),
    en: (
      <>
        <p>The client's global state runs on Zustand 5 — 11 stores in two layers:</p>
        <p><strong>Six global stores</strong> live in <code>src/stores/</code>: <code>auth_store</code> (WCA OAuth user, with a <code>window 'storage'</code> listener for cross-tab sync), <code>settingsStore</code> (theme / language / trainer config, wrapped in <code>persist</code> writing to localStorage key <code>trainer-settings</code>), <code>sessionStore</code> (current solve session), <code>statsStore</code> (WCA query params shared across the /wca sub-pages), <code>trainerStore</code> (training session, with its own timer state machine), and <code>recon_store</code> (recon cache).</p>
        <p><strong>Five page-local stores</strong> ship with their pages: <code>pages/battle/engine/battle_store</code>, <code>pages/calc/stores/calc_store</code>, <code>pages/mosaic/state/store</code>, <code>pages/viz/stores/viz_store</code>, plus a small one inside the viz canvas. These never cross page boundaries — they live page-local because the state tree inside a single page is deep enough that selector-controlled granularity is worth it.</p>
        <p>No Provider in the tree — the root is just <code>&lt;BrowserRouter&gt;</code> wrapping <code>&lt;Routes&gt;</code>, no store provider in between. Components <code>import {'{ useAuthStore }'} from '../stores/auth_store'</code> and call a selector — that's it. <code>useShallow</code> is used where multi-field reads happen (PlayerControls / SimPage, etc.) to avoid pointless re-renders. The whole strict-mode TS inference never trips on Zustand.</p>
      </>
    ),
  },
  links: [
    { label: 'zustand.docs.pmnd.rs', href: 'https://zustand.docs.pmnd.rs' },
    { label: 'GitHub · pmndrs/zustand', href: 'https://github.com/pmndrs/zustand' },
    { label: 'npm · zustand', href: 'https://www.npmjs.com/package/zustand' },
    { label: 'v5 release notes', href: 'https://github.com/pmndrs/zustand/releases/tag/v5.0.0' },
  ],
};

export default ZUSTAND;
