import { describe, it, expect } from 'vitest';
import { PgEngineBinding } from '@/app/[lang]/sim/engine/pgBinding';
import { ftoPgBridge } from '@/app/[lang]/sim/engine/fto/ftoPgBridge';
import { randomFtoScramble, invertFtoMoves } from '@/app/[lang]/sim/engine/fto/ftoState';
import { FtoModel } from './_fto_model';

// |G| of the group generated by the 8 face turns, with PG's pieces all distinct (same
// convention as the megaminx bridge). Computed by Schreier-Sims, locked here as a review
// signal. NOTE this is the ABSTRACT group order; the often-quoted ~3.14×10²² FTO "positions"
// (Jaap / Wikipedia) is the VISIBLE-state count — smaller because the 24 centres are two
// orbits of three indistinguishable same-colour triplets (÷ by their permutations).
const FTO_ORDER = 158260810061489362698240000000n;

describe('FTO PG bridge — facts + faithful live mirror (no BSGS)', () => {
  const binding = new PgEngineBinding(ftoPgBridge);

  it('serves Schreier-Sims facts over the 8 face turns but opts out of constructive BSGS', () => {
    expect(binding.solvable).toBe(false);
    expect(binding.order).toBe(FTO_ORDER);
    expect(binding.solveMoves()).toEqual([]);
    expect(binding.scrambleMoves()).toEqual([]);
  });

  it('facts: 6×ℤ4 corners, 12×ℤ2 edges, 24 single-colour centres (two orbits), 8 moves', () => {
    const f = binding.facts();
    expect(f.order).toBe(FTO_ORDER);
    expect(f.reorientations).toBe(1n);
    const byName = Object.fromEntries(f.orbits.map((o) => [o.name, o]));
    expect(byName.C4RNER).toMatchObject({ pieces: 6, oriMod: 4 });
    expect(byName.EDGES).toMatchObject({ pieces: 12, oriMod: 2 });
    expect(byName.CENTERS).toMatchObject({ pieces: 12, oriMod: 1 });
    expect(byName.CENTERS2).toMatchObject({ pieces: 12, oriMod: 1 });
    expect(f.moveNames).toHaveLength(8);
  });

  it('live mirror is faithful: engine-solved ⇔ PG-identity across random sequences', () => {
    // The engine reference is the pure-geometric model (the same turn rule FtoCube uses).
    for (let t = 0; t < 40; t++) {
      const scr = randomFtoScramble(16 + (t % 14));
      binding.rebuild(scr);
      const m = new FtoModel(); m.applyAll(scr);
      expect(binding.solved).toBe(m.solved);
      if (scr.length) expect(binding.solved).toBe(false); // a scramble from solved is never solved
    }
  });

  it('moves then their reverse-inverse return to identity; a single move does not', () => {
    for (let t = 0; t < 20; t++) {
      const scr = randomFtoScramble(16);
      binding.rebuild([...scr, ...invertFtoMoves(scr)]);
      expect(binding.solved).toBe(true);
      binding.rebuild([scr[0]]);
      expect(binding.solved).toBe(false);
    }
  });
});
