/**
 * Offline generator for `engine/pgFacts.generated.ts` — the precomputed group facts for
 * every PG-bound /sim puzzle. Skipped in CI (it re-runs Schreier-Sims, incl. a ~8s 7x7);
 * run it by hand whenever a bridge's generators / pgName change, or a new puzzle is added:
 *
 *   GEN_PG_FACTS=1 pnpm --filter @cuberoot/client exec vitest run tests/gen_pg_facts.gen.test.ts
 *
 * It builds every bridge from `allBridges()`, computes facts via the live path, and writes
 * the baked table. See engine/pgFacts.ts for why these are precomputed.
 */
import { describe, it, expect } from 'vitest';
import { writeFileSync } from 'node:fs';
import { PgEngineBinding } from '@/app/[lang]/sim/engine/pgBinding';
import { PermEngineBinding } from '@/app/[lang]/sim/engine/permBinding';
import { ExploreFactsBinding } from '@/app/[lang]/sim/engine/exploreBinding';
import { allBridges, permBridges, exploreBridges } from '@/app/[lang]/sim/engine/pgBindings';
import { serializePgFacts, type SerializedPgFacts } from '@/app/[lang]/sim/engine/pgFacts';

const RUN = !!process.env.GEN_PG_FACTS;
const OUT = 'D:/cube/cuberoot.me/core/packages/client/app/[lang]/sim/engine/pgFacts.generated.ts';

describe('generate pgFacts.generated.ts', () => {
  (RUN ? it : it.skip)('bakes facts for every bridge', () => {
    const table: Record<string, SerializedPgFacts> = {};
    for (const bridge of allBridges()) {
      const binding = new PgEngineBinding(bridge);
      const facts = binding.computeFactsLive();
      table[String(bridge.pgName)] = serializePgFacts(facts);
      // eslint-disable-next-line no-console
      console.log(`  ${bridge.pgName}: |G| = ${facts.order}`);
    }
    // Perm-backbone puzzles (ivy, rex) — baked under bridge.key, not a PG name.
    for (const bridge of permBridges()) {
      const facts = new PermEngineBinding(bridge).computeFactsLive();
      table[bridge.key] = serializePgFacts(facts);
      // eslint-disable-next-line no-console
      console.log(`  ${bridge.key}: |G| = ${facts.order}`);
    }
    // cubing.js "explore" doctrinaire puzzles — facts-only, baked under the explore id.
    // |G| over the OUTER generators (allMoves:false — the faithful, non-inflated move set).
    for (const { key, def } of exploreBridges()) {
      const facts = new ExploreFactsBinding(key, def).computeFactsLive();
      table[key] = serializePgFacts(facts);
      // eslint-disable-next-line no-console
      console.log(`  ${key}: |G| = ${facts.order}`);
    }
    const body = Object.entries(table)
      .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
      .join('\n');
    const src = `// AUTO-GENERATED by tests/gen_pg_facts.gen.test.ts — do not edit by hand.
// Precomputed group facts for every PG-bound /sim puzzle (keyed by bridge.pgName).
// Regenerate: GEN_PG_FACTS=1 pnpm --filter @cuberoot/client exec vitest run tests/gen_pg_facts.gen.test.ts
import type { SerializedPgFacts } from './pgFacts';

export const PRECOMPUTED_PG_FACTS: Record<string, SerializedPgFacts> = {
${body}
};
`;
    writeFileSync(OUT, src);
    expect(Object.keys(table).length).toBeGreaterThan(0);
  });
});
