/** CubingApp SQ1 Cube Shape + CSP JSON -> 0107 data migration. */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { invertSq1Alg } from '@cuberoot/shared/sq1-notation';
import {
  invariant, normalizeSubgroup, readCubingAppSq1Set, sourceAlgs, upstreamCase,
} from './cubingapp_sq1_import.mts';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const upstreamRoot = resolve(process.cwd(), process.argv[2] ?? resolve(HERE, '../../../../cubingapp'));
const output = resolve(process.cwd(), process.argv[3] ?? resolve(HERE, '../server/migrations/0107_sq1_cubingapp_csp.sql'));
const cubeShape = readCubingAppSq1Set(upstreamRoot, 'SQ1-Cube-Shape');
const csp = readCubingAppSq1Set(upstreamRoot, 'SQ1-CSP');

const cubeShapeEntries = Object.entries(cubeShape.cases);
const cspEntries = Object.entries(csp.cases);
invariant(cubeShapeEntries.length === 169, `expected 169 Cube Shape cases, got ${cubeShapeEntries.length}`);
invariant(cubeShapeEntries.reduce((n, [, c]) => n + Object.keys(c.algs).length, 0) === 173, 'Cube Shape formula count drifted');
invariant(cspEntries.length === 179, `expected 179 CSP cases, got ${cspEntries.length}`);
invariant(cspEntries.reduce((n, [, c]) => n + Object.keys(c.algs).length, 0) === 203, 'CSP formula count drifted');

const csPatchMap = [
  { upstream: 'Pair / 5-1 Right', target: 'Pair / Right 5-1', mode: 'replace' },
  { upstream: 'Crown / 4-2 Left', target: 'Parallel Edges / Left 4-2', mode: 'prepend' },
  { upstream: '3-2-1 Left / Crown', target: '3-2-1 / Parallel Edges', mode: 'prepend' },
  { upstream: 'Crown / 3-2-1 Left', target: 'Parallel Edges / 3-2-1', mode: 'prepend' },
  { upstream: '3-2-1 Right / Crown', target: '3-1-2 / Parallel Edges', mode: 'prepend' },
  { upstream: 'Crown / 3-2-1 Right', target: 'Parallel Edges / 3-1-2', mode: 'prepend' },
] as const;

const csPayload = {
  patches: csPatchMap.map(({ upstream, target, mode }) => ({
    name: target,
    mode,
    algs: sourceAlgs(upstreamCase(cubeShape, upstream)),
  })),
  missing: (() => {
    const source = upstreamCase(cubeShape, '4-2 Left / Arrow');
    const algs = sourceAlgs(source);
    return {
      // The existing dataset already has a position-84 hole at exactly this source case.
      // Fill that stable key; do not renumber the 85 cases after it.
      position: 84,
      name: 'Left 4-2 / Perpendicular Edges',
      subgroup: normalizeSubgroup(source.subset),
      setup: invertSq1Alg(algs[0][0].alg),
      sticker: { kind: 'raw', tag: 'sqcube', attrs: {} },
      algs,
    };
  })(),
};

const cspPayload = cspEntries.map(([name, source], position) => {
  const algs = sourceAlgs(source);
  return {
    position,
    name,
    subgroup: normalizeSubgroup(source.subset),
    setup: invertSq1Alg(algs[0][0].alg),
    sticker: { kind: 'raw', tag: 'sqcube', attrs: {} },
    algs,
  };
});

const pretty = (value: unknown) => JSON.stringify(value, null, 2);
const lines = [
  '-- Complete the existing SQ1 Cube Shape set and import CubingApp CSP.',
  '-- Generated by packages/alg-build/gen_cubingapp_sq1_sql.mts.',
  '-- Upstream: CubingApp commit 613a49885dc618023368e5f0c2a25024b8c7e9a5 (MIT).',
  '',
  `INSERT INTO alg_sets (puzzle, set_slug, source, scraped_at) VALUES ('sq1', 'cs', 'https://speedcubedb.com/a/sq1/SQ1CS; https://cubingapp.com/algorithms/SQ1-Cube-Shape; https://github.com/spencerchubb/cubingapp/commit/613a49885dc618023368e5f0c2a25024b8c7e9a5', NOW())`,
  'ON CONFLICT (puzzle, set_slug) DO UPDATE SET source = EXCLUDED.source, scraped_at = EXCLUDED.scraped_at;',
  '',
  `INSERT INTO alg_sets (puzzle, set_slug, source, scraped_at) VALUES ('sq1', 'csp', 'https://cubingapp.com/algorithms/SQ1-CSP; https://github.com/spencerchubb/cubingapp/commit/613a49885dc618023368e5f0c2a25024b8c7e9a5', NOW())`,
  'ON CONFLICT (puzzle, set_slug) DO UPDATE SET source = EXCLUDED.source, scraped_at = EXCLUDED.scraped_at;',
  '',
  '-- JSON blocks are deliberately readable: tests audit their exact source coverage.',
  `WITH payload AS (SELECT $cubingapp_cs_patch$${pretty(csPayload)}$cubingapp_cs_patch$::jsonb AS body),`,
  "patches AS (SELECT value AS patch FROM payload, jsonb_array_elements(body->'patches'))",
  'UPDATE alg_cases AS c',
  'SET algs = CASE',
  "  WHEN patches.patch->>'mode' = 'replace' THEN patches.patch->'algs'",
  '  ELSE jsonb_build_array(',
  "    COALESCE(patches.patch->'algs'->0, '[]'::jsonb) ||",
  '    COALESCE((',
  '      SELECT jsonb_agg(existing.entry ORDER BY existing.ord)',
  "      FROM jsonb_array_elements(COALESCE(c.algs->0, '[]'::jsonb)) WITH ORDINALITY AS existing(entry, ord)",
  '      WHERE NOT EXISTS (',
  "        SELECT 1 FROM jsonb_array_elements(COALESCE(patches.patch->'algs'->0, '[]'::jsonb)) AS added(entry)",
  "        WHERE added.entry->>'alg' = existing.entry->>'alg'",
  '      )',
  "    ), '[]'::jsonb)",
  '  )',
  'END',
  'FROM patches',
  "WHERE c.puzzle = 'sq1' AND c.set_slug = 'cs' AND c.name = patches.patch->>'name';",
  '',
  '-- Insert the one missing non-solved shape into the existing position-84 hole.',
  '-- No existing id, position or saved progress key is renumbered.',
  `WITH payload AS (SELECT $cubingapp_cs_patch$${pretty(csPayload)}$cubingapp_cs_patch$::jsonb AS body),`,
  "missing AS (SELECT body->'missing' AS item FROM payload)",
  'INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)',
  "SELECT 'sq1', 'cs', (item->>'position')::integer, item->>'name', item->>'subgroup', item->>'setup', item->'sticker', item->'algs'",
  'FROM missing',
  "WHERE NOT EXISTS (SELECT 1 FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'cs' AND name = item->>'name');",
  '',
  "DELETE FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'csp';",
  '',
  `WITH payload AS (SELECT $cubingapp_csp_cases$${pretty(cspPayload)}$cubingapp_csp_cases$::jsonb AS body)`,
  'INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)',
  "SELECT 'sq1', 'csp', (item->>'position')::integer, item->>'name', item->>'subgroup', item->>'setup', item->'sticker', item->'algs'",
  'FROM payload, jsonb_array_elements(body) AS cases(item);',
  '',
  'DO $sq1_cubingapp_counts$',
  'DECLARE got BIGINT;',
  'BEGIN',
  "  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'cs';",
  "  IF got <> 170 THEN RAISE EXCEPTION 'sq1/cs: expected 170 cases (169 shapes + solved), got %', got; END IF;",
  "  SELECT SUM(jsonb_array_length(algs->0)) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'cs';",
  "  IF got <> 178 THEN RAISE EXCEPTION 'sq1/cs: expected 178 algorithms, got %', got; END IF;",
  "  SELECT COUNT(DISTINCT position) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'cs' AND position BETWEEN 0 AND 169;",
  "  IF got <> 170 THEN RAISE EXCEPTION 'sq1/cs: expected contiguous positions 0..169, got %', got; END IF;",
  "  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'csp';",
  "  IF got <> 179 THEN RAISE EXCEPTION 'sq1/csp: expected 179 cases, got %', got; END IF;",
  "  SELECT SUM(jsonb_array_length(algs->0)) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'csp';",
  "  IF got <> 203 THEN RAISE EXCEPTION 'sq1/csp: expected 203 algorithms, got %', got; END IF;",
  'END',
  '$sq1_cubingapp_counts$;',
  '',
];

writeFileSync(output, lines.join('\n'), 'utf8');
console.log(`wrote ${output}: CS +1 case/+6 formulas; CSP ${cspPayload.length} cases/203 formulas`);
