/**
 * Generate SQL to:
 *   1. Apostrophe-rule split C-X subgroups (excl F, T, S) on existing alg_cases data:
 *      name ends with `'` → subgroup += '-'; else → subgroup += '+'.
 *   2. DELETE + re-INSERT Solved Pair / A / B rows from scraped docx data
 *      (with proper subgroup A+/A-/B+/B-, full algs incl AUF prefix, multi-alg,
 *      finger-trick algHtml when present).
 *
 * Writes to C:/tmp/zbls_apply.sql, ready for `scp + psql -f`.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SCRAPED = JSON.parse(readFileSync('D:/cube/ruiminyan.github.io/core/packages/alg-build/zbls_scraped.json', 'utf-8'));
const APOSTROPHE_LETTERS = ['C','D','E','G','H','I','J','K','L','M','P','Q','R','U','V','W','X'];
const NEW_LETTERS_FROM_DOCX = ['Solved Pair','A','B'];

// Filter scraped cases for the letters we want to bulk-insert
const newRows = SCRAPED.filter(c => {
  if (c.subgroup === 'Solved Pair') return true;
  return c.subgroup.startsWith('A') || c.subgroup.startsWith('B');
});

// PG string literal escape: '"foo's bar"' → '"foo''s bar"'
function pgQuote(s) {
  if (s == null) return 'NULL';
  return `'${String(s).replace(/'/g, "''")}'`;
}
function pgJsonb(v) {
  if (v == null) return 'NULL';
  return `${pgQuote(JSON.stringify(v))}::jsonb`;
}

let sql = `-- Generated by gen_zbls_sql.mjs at ${new Date().toISOString()}
-- 1) Apostrophe-rule split for C-X (excl F, T, S)
-- 2) DELETE + INSERT Solved Pair / A / B from docx scrape

BEGIN;

-- Sanity: count before
SELECT 'before' AS stage, subgroup, COUNT(*) AS n
FROM alg_cases WHERE puzzle='3x3' AND set_slug='zbls'
GROUP BY subgroup ORDER BY subgroup;

-- 1a) Cases ending with ' → minus side
UPDATE alg_cases SET subgroup = subgroup || '-'
WHERE puzzle='3x3' AND set_slug='zbls'
  AND subgroup IN (${APOSTROPHE_LETTERS.map(pgQuote).join(',')})
  AND name LIKE '%' || chr(39);

-- 1b) Remaining (no trailing ') → plus side
UPDATE alg_cases SET subgroup = subgroup || '+'
WHERE puzzle='3x3' AND set_slug='zbls'
  AND subgroup IN (${APOSTROPHE_LETTERS.map(pgQuote).join(',')});

-- 2) Wipe Solved Pair / A / B rows
DELETE FROM alg_cases
WHERE puzzle='3x3' AND set_slug='zbls'
  AND subgroup IN (${NEW_LETTERS_FROM_DOCX.map(pgQuote).join(',')});

-- 2b) Insert fresh rows from docx scrape (position auto-allocated from current MAX+1)
`;

// Allocate positions sequentially starting from a high base so new rows sort after existing untouched ones
const POSITION_BASE = 10000;
newRows.forEach((c, i) => {
  const sticker = { fl: '', kind: 'f2l' };
  const algs = [c.algs];  // 2D array (1 orientation × N algs)
  const pos = POSITION_BASE + i;
  sql += `INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs) VALUES (`
    + `'3x3', 'zbls', ${pos}, ${pgQuote(c.name)}, ${pgQuote(c.subgroup)}, ${pgQuote(c.setup)}, `
    + `${pgJsonb(sticker)}, ${pgJsonb(algs)});\n`;
});

sql += `
-- Sanity: count after
SELECT 'after' AS stage, subgroup, COUNT(*) AS n
FROM alg_cases WHERE puzzle='3x3' AND set_slug='zbls'
GROUP BY subgroup ORDER BY subgroup;

COMMIT;
`;

writeFileSync('C:/tmp/zbls_apply.sql', sql, 'utf-8');
console.log(`Wrote C:/tmp/zbls_apply.sql (${sql.length} bytes, ${newRows.length} INSERTs for A/B/SP)`);
