/** Build the 33-case PSF2L set from the site owner's PSF2L.docx reference sheet. */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Alg } from 'cubing/alg';
import { puzzles } from 'cubing/puzzles';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const output = resolve(
  process.cwd(),
  process.argv[2] ?? resolve(HERE, '../server/migrations/0116_psf2l.sql'),
);

/** Row-major order from the DOCX sheet; the three diagrams in its header are explanations, not cases. */
const DOCX_ALGS = [
  "D U R U' R' D'",
  "D d' L' U L D'",
  "D R U R' D'",
  "D F' U' F D'",
  "D U2 R U' R' U' R U R' D'",
  "D U' R U' R' d R' U' R D'",
  "D U' R U' R' U R U R' D'",
  "D y U L' U L U' L' U' L D'",
  "D R U' R' U R U' R' U2 R U' R' D'",
  "D U' R U2' R' d R' U' R D'",
  "D U' R U R' U2 R U' R' D'",
  "D U' r U' R' U R U r' D'",
  "D U' R U2' R' U2 R U' R' D'",
  "D d R' U2 R U2' R' U R D'",
  "D U R U2' R' U R U' R' D'",
  "D d' L' U2 L U' L' U L D'",
  "D R U' R' U2 R U R' D'",
  "D U2 R U R' F' U' F D'",
  "D R' D' R U' R' D R U R U' R' D'",
  "D R U' R' U2 F' U' F D'",
  "D R U2' R' U' R U R' D'",
  "D y L' U2 L U L' U' L D'",
  "D U R U' R' U' R U' R' U R U' R' D'",
  "D U' R U R2' F R F' R U' R' D'",
  "D R U' R' U R U' R' D'",
  "D y L' U L U' L' U L D'",
  "D R U R' U' R U R' D'",
  "D U2 R U' R' F' U' F D'",
  "D U' R' F R F' R U' R' D'",
  "D U2 R U' R' U' F' U' F D'",
  "D U F' U' F U' R U R' D'",
  "D r U' r' U2 r U r' R U R' D'",
  "D R U' R' r U' r' U2 r U r' D'",
] as const;

function invariant(ok: unknown, message: string): asserts ok {
  if (!ok) throw new Error(message);
}

const normalizedAlgs = DOCX_ALGS.map(alg => alg.replace(/2'/g, '2'));
invariant(normalizedAlgs.length === 33, `expected 33 PSF2L cases, got ${normalizedAlgs.length}`);

const kpuzzle = await puzzles['3x3x3'].kpuzzle();
const solved = JSON.stringify(kpuzzle.defaultPattern().patternData);
const payload = normalizedAlgs.map((alg, position) => {
  const tokens = alg.split(/\s+/);
  invariant(tokens[0] === 'D' && tokens[tokens.length - 1] === "D'", `case ${position + 1}: outer D pair missing`);
  const setup = new Alg(alg).invert().toString();
  const result = kpuzzle.defaultPattern().applyAlg(`${setup} ${alg}`);
  invariant(JSON.stringify(result.patternData) === solved, `case ${position + 1}: setup + alg is not solved`);
  return {
    position,
    name: `PSF2L ${String(position + 1).padStart(2, '0')}`,
    subgroup: '',
    setup,
    sticker: { kind: 'f2l', fl: '' },
    algs: [[{ alg, source: 'cuberoot' }]],
  };
});

const pretty = JSON.stringify(payload, null, 2);
const lines = [
  '-- Import the 33-case Pseudoslotting (PSF2L) reference sheet.',
  '-- Generated by packages/alg-build/gen_psf2l_sql.mts from PSF2L.docx.',
  '-- The three header diagrams explain + / - / 0 entry patterns and are not cases.',
  '',
  'INSERT INTO alg_sets (puzzle, set_slug, source, scraped_at) VALUES',
  "  ('3x3', 'psf2l', 'PSF2L.docx (site-owner reference); https://solved.no/guides/pseudoslotting; https://www.youtube.com/watch?v=49Izh9ZnBog', NOW())",
  'ON CONFLICT (puzzle, set_slug) DO UPDATE SET source = EXCLUDED.source, scraped_at = EXCLUDED.scraped_at;',
  '',
  `WITH payload AS (SELECT $psf2l$${pretty}$psf2l$::jsonb AS body),`,
  'items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))',
  'UPDATE alg_cases AS c',
  "SET position = (items.item->>'position')::integer, subgroup = items.item->>'subgroup',",
  "    setup = items.item->>'setup', sticker = items.item->'sticker', algs = items.item->'algs'",
  'FROM items',
  "WHERE c.puzzle = '3x3' AND c.set_slug = 'psf2l' AND c.name = items.item->>'name';",
  '',
  `WITH payload AS (SELECT $psf2l$${pretty}$psf2l$::jsonb AS body),`,
  'items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))',
  'INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)',
  "SELECT '3x3', 'psf2l', (item->>'position')::integer, item->>'name', item->>'subgroup',",
  "       item->>'setup', item->'sticker', item->'algs'",
  'FROM items',
  "WHERE NOT EXISTS (SELECT 1 FROM alg_cases WHERE puzzle = '3x3' AND set_slug = 'psf2l' AND name = item->>'name');",
  '',
  'DO $psf2l_counts$',
  'DECLARE got BIGINT;',
  'BEGIN',
  "  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = 'psf2l';",
  "  IF got <> 33 THEN RAISE EXCEPTION '3x3/psf2l: expected 33 cases, got %', got; END IF;",
  "  SELECT COALESCE(SUM((SELECT SUM(jsonb_array_length(orientation.value)) FROM jsonb_array_elements(algs) AS orientation(value))), 0) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = 'psf2l';",
  "  IF got <> 33 THEN RAISE EXCEPTION '3x3/psf2l: expected 33 algorithms, got %', got; END IF;",
  'END',
  '$psf2l_counts$;',
  '',
];

writeFileSync(output, lines.join('\n'), 'utf8');
console.log(`wrote ${output}: 33 PSF2L cases / 33 algorithms`);
