/**
 * Generate SQL to:
 *   1. Apostrophe-rule split C-X subgroups (excl F, T, S) on existing alg_cases data:
 *      name ends with `'` → subgroup += '-'; else → subgroup += '+'.
 *   2. DELETE + re-INSERT Solved Pair / A / B rows from scraped docx data,
 *      with full algs incl AUF prefix, multi-alg, finger-trick algHtml,
 *      and **alignment baked in** (FR display + UFR pair corner).
 *
 * Writes to C:/tmp/zbls_apply.sql.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { alignCase } from './zbls_align_lib.mjs';

const SCRAPED = JSON.parse(readFileSync('D:/cube/ruiminyan.github.io/core/packages/alg-build/zbls_scraped.json', 'utf-8'));
const APOSTROPHE_LETTERS = ['C','D','E','G','H','I','J','K','L','M','P','Q','R','U','V','W','X'];
const NEW_LETTERS_FROM_DOCX = ['Solved Pair','A','B'];

const newRows = SCRAPED.filter(c => {
  if (c.subgroup === 'Solved Pair') return true;
  return c.subgroup.startsWith('A') || c.subgroup.startsWith('B');
});

function pgQuote(s) {
  if (s == null) return 'NULL';
  return `'${String(s).replace(/'/g, "''")}'`;
}
function pgJsonb(v) {
  if (v == null) return 'NULL';
  return `${pgQuote(JSON.stringify(v))}::jsonb`;
}

let sql = `-- Generated by gen_zbls_sql.mjs at ${new Date().toISOString()}
-- 1) Apostrophe-rule split for C-X (excl F, T, S)
-- 2) DELETE + INSERT Solved Pair / A / B from docx scrape (alignment baked in)

BEGIN;

SELECT 'before' AS stage, subgroup, COUNT(*) AS n
FROM alg_cases WHERE puzzle='3x3' AND set_slug='zbls'
GROUP BY subgroup ORDER BY subgroup;

-- 1a) Cases ending with ' → minus side
UPDATE alg_cases SET subgroup = subgroup || '-'
WHERE puzzle='3x3' AND set_slug='zbls'
  AND subgroup IN (${APOSTROPHE_LETTERS.map(pgQuote).join(',')})
  AND name LIKE '%' || chr(39);

-- 1b) Remaining (no trailing ') → plus side
UPDATE alg_cases SET subgroup = subgroup || '+'
WHERE puzzle='3x3' AND set_slug='zbls'
  AND subgroup IN (${APOSTROPHE_LETTERS.map(pgQuote).join(',')});

-- 2) Wipe Solved Pair / A / B rows
DELETE FROM alg_cases
WHERE puzzle='3x3' AND set_slug='zbls'
  AND subgroup IN (${NEW_LETTERS_FROM_DOCX.map(pgQuote).join(',')});

`;

const POSITION_BASE = 10000;
let alignedCount = 0, unalignedCount = 0;
newRows.forEach((c, i) => {
  const sticker = { fl: '', kind: 'f2l' };
  let setup = c.setup;
  let algs = c.algs;
  // Try alignment (no-op for Solved Pair)
  const aligned = alignCase({ subgroup: c.subgroup, setup, algs, name: c.name });
  if (aligned) {
    setup = aligned.newSetup;
    algs = aligned.newAlgs;
    alignedCount++;
  } else {
    unalignedCount++;
  }
  // Wrap to 2D if not already
  const algs2D = Array.isArray(algs[0]) ? algs : [algs];
  const pos = POSITION_BASE + i;
  sql += `INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs) VALUES (`
    + `'3x3', 'zbls', ${pos}, ${pgQuote(c.name)}, ${pgQuote(c.subgroup)}, ${pgQuote(setup)}, `
    + `${pgJsonb(sticker)}, ${pgJsonb(algs2D)});\n`;
});

console.log(`Aligned ${alignedCount} rows; ${unalignedCount} skipped (Solved Pair / unparseable).`);

sql += `
SELECT 'after' AS stage, subgroup, COUNT(*) AS n
FROM alg_cases WHERE puzzle='3x3' AND set_slug='zbls'
GROUP BY subgroup ORDER BY subgroup;

COMMIT;
`;

writeFileSync('C:/tmp/zbls_apply.sql', sql, 'utf-8');
console.log(`Wrote C:/tmp/zbls_apply.sql (${sql.length} bytes, ${newRows.length} INSERTs for A/B/SP)`);
