-- 0008_traffic_analytics.sql
-- 站内自有流量分析(替代第三方 GA / CF Analytics 等,符合 "自成一体" 规则).
--
-- 两张表:
--   pageviews     -- 原始 pv,90 天滚动清理(由 systemd analytics-aggregate.timer 删旧)
--   traffic_daily -- 日聚合,永久保留(报表查询走这张,/v1/analytics/summary 用)
--
-- 隐私:不存 IP / 不存完整 UA.
--   visitor_id = sha256(remote_ip || ua || YYYY-MM-DD || ANALYTICS_SALT) 截前 16 字节
--   每天换 day-key → 跨日同一访客 = 不同 hash(只能做 daily-unique UV,不能跨日跟踪).
--   ANALYTICS_SALT 在 .env,丢失即历史 visitor_id 不可逆.

CREATE TABLE pageviews (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  visitor_id  BYTEA       NOT NULL,           -- 16 字节 daily-rotating hash
  path        TEXT        NOT NULL,           -- SPA route, e.g. "/wca/persons/2018WANG..."
  ref_domain  TEXT,                           -- 已 normalize 到 eTLD+1, e.g. "google.com"
  country     CHAR(2),                        -- GeoIP iso2, 'XX' 表查不到
  ua_class    VARCHAR(10),                    -- desktop|mobile|tablet|bot
  dwell_ms    INTEGER                         -- 离开/换页时回填
);
CREATE INDEX idx_pageviews_ts      ON pageviews (ts DESC);
CREATE INDEX idx_pageviews_path_ts ON pageviews (path, ts DESC);

CREATE TABLE traffic_daily (
  day          DATE        NOT NULL,
  path         TEXT        NOT NULL,
  country      CHAR(2)     NOT NULL DEFAULT 'XX',
  ref_domain   TEXT        NOT NULL DEFAULT '',
  pv           INTEGER     NOT NULL,
  uv           INTEGER     NOT NULL,
  avg_dwell_ms INTEGER,
  PRIMARY KEY (day, path, country, ref_domain)
);
CREATE INDEX idx_traffic_daily_day ON traffic_daily (day DESC);
