-- 0026_article.sql — /article 社区长文发布系统
-- 任何登录 WCA 用户可发 (untrusted)。正文 = markdown + 自定义指令 (source of record),
-- 渲染时经 rehype-sanitize 净化;DB 只存纯 TEXT,不约束 markup。
-- 软删 (deleted_at) 替代 DELETE;published_at NULL = 草稿。
-- 配图存 article_image BYTEA,经 /v1/article/img/:id 公开服务 (immutable + nginx cache)。

CREATE TABLE article (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(200) NOT NULL,                     -- URL 路径,小写字母数字连字符
  title         TEXT         NOT NULL,
  subtitle      TEXT,
  body          TEXT         NOT NULL,                     -- markdown + 指令
  lang          VARCHAR(8)   NOT NULL DEFAULT 'zh',
  owner_wca_id  VARCHAR(20)  NOT NULL,                     -- 创建者 WCA ID
  owner_name    TEXT         NOT NULL DEFAULT '',          -- 创建时快照 (WCA 名可变)
  published_at  TIMESTAMPTZ,                               -- NULL = 草稿
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_article_slug   ON article (slug)              WHERE deleted_at IS NULL;
CREATE INDEX        idx_article_pub   ON article (published_at DESC) WHERE deleted_at IS NULL AND published_at IS NOT NULL;
CREATE INDEX        idx_article_owner ON article (owner_wca_id)      WHERE deleted_at IS NULL;
CREATE TRIGGER article_updated_at BEFORE UPDATE ON article
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TABLE article_image (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id    BIGINT REFERENCES article(id) ON DELETE CASCADE,  -- 可空:编辑期先传图后绑文章
  data          BYTEA       NOT NULL,
  mime          VARCHAR(64) NOT NULL,                      -- image/png | image/jpeg | image/webp
  width         INTEGER,
  height        INTEGER,
  size_bytes    INTEGER     NOT NULL,
  owner_wca_id  VARCHAR(20) NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_article_image_article ON article_image (article_id);
