-- 公开「打卡」：登录用户给做过的 WCA 真实比赛打乱做标记（/timer WCA 打乱来源）。
-- 打乱用六元自然键 (competition_id, event_id, round_type_id, group_id, is_extra,
-- scramble_num) 标识（wca_scrambles 的 id 会随重灌漂移，自然键稳定；comp 模式新比赛
-- 走 wca_scrambles_cache，镜像表里可能还没有，所以不设 FK、不校验存在性）。
-- name/country 为写入时冗余快照（wca_users 无 country，country 由客户端报，纯装饰）。
CREATE TABLE IF NOT EXISTS scramble_marks (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wca_id         VARCHAR(20) NOT NULL,
  name           VARCHAR(200) NOT NULL DEFAULT '',
  country        VARCHAR(2)  NOT NULL DEFAULT '',
  competition_id VARCHAR(32) NOT NULL,
  event_id       VARCHAR(6)  NOT NULL,
  round_type_id  VARCHAR(1)  NOT NULL,
  group_id       VARCHAR(3)  NOT NULL,
  is_extra       SMALLINT    NOT NULL DEFAULT 0,
  scramble_num   INT         NOT NULL,
  time_cs        INT,
  created_at     BIGINT      NOT NULL,
  CONSTRAINT uq_scramble_marks UNIQUE (wca_id, competition_id, event_id, round_type_id, group_id, is_extra, scramble_num)
);
-- 单条打乱的标记列表（timer 打乱条下的「N 人做过」）。
CREATE INDEX IF NOT EXISTS idx_scr_marks_scramble ON scramble_marks(competition_id, event_id, round_type_id, group_id, is_extra, scramble_num);
-- 最近标记 feed（/timer/marks，全站 + 按人过滤）。
CREATE INDEX IF NOT EXISTS idx_scr_marks_created ON scramble_marks(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_scr_marks_user ON scramble_marks(wca_id, created_at DESC);
