-- 0043_sponsors.sql — /support 致谢/赞助墙。admin 手录每笔打赏(WCA OAuth Bearer / X-Admin-Key)。
-- 公开 GET 按金额降序;头像在录入时从 WCA 拉 thumb_url 存下,公开页零 WCA 调用。
CREATE TABLE sponsors (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(200)  NOT NULL,
  wca_id      VARCHAR(20),
  avatar_url  TEXT,
  amount      NUMERIC(10,2) NOT NULL DEFAULT 0,
  currency    VARCHAR(8)    NOT NULL DEFAULT 'CNY',
  message     TEXT,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_sponsors_amount ON sponsors(amount DESC, created_at);
CREATE TRIGGER sponsors_updated_at BEFORE UPDATE ON sponsors
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
