-- 0095_sim_masks.sql — /sim 阶段遮罩下拉的管理员自维护(sim_masks)
-- 清单本体仍在代码里(engine stickering.ts 的方法学阶段 + visualcube 位串,单一源不动),
-- 这张表只叠一层「管理员改过什么」:
--   kind='builtin' → 覆盖代码里某条的标签 / 顺序 / 是否显示(mask_key = 下拉里的阶段名)
--   kind='custom'  → 管理员在 /sim 点选贴纸存出来的新遮罩(sids = mask-core 清单)
-- 删掉一行 = 恢复该条的代码默认;所以 builtin 行是纯覆盖层,不需要种子数据。
--
-- sids/pick/rest 与 /sim 的 ?stickeringMask= ?stickeringPick= ?stickeringRest= 同一份编码
-- (`U:0,2;F:3-5`,面序 U R F D L B),存的就是可分享的 URL 参数。
-- cube_size:custom 遮罩只对该阶数有意义(点选清单绑死了阶数);builtin 行照样按阶记一份。
-- position = -1 是「还没排过」:只为改名 / 隐藏建的行不能顺带把条目挪到组首,所以排序
-- 只由 /sim-masks/reorder 写(它给该阶全量条目写 0..n-1),别的写路径一律不碰这列。
-- server/routes/sim_masks.ts。

CREATE TABLE sim_masks (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mask_key    VARCHAR(80)  NOT NULL UNIQUE,
  kind        VARCHAR(10)  NOT NULL DEFAULT 'builtin',
  cube_size   INTEGER      NOT NULL DEFAULT 3,
  position    INTEGER      NOT NULL DEFAULT -1,
  hidden      BOOLEAN      NOT NULL DEFAULT FALSE,
  label_en    VARCHAR(60)  NOT NULL DEFAULT '',
  label_zh    VARCHAR(60)  NOT NULL DEFAULT '',
  sids        TEXT         NOT NULL DEFAULT '',
  pick        VARCHAR(10)  NOT NULL DEFAULT 'regular',
  rest        VARCHAR(10)  NOT NULL DEFAULT 'ignored',
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_sim_masks_size_position ON sim_masks(cube_size, position);
CREATE TRIGGER sim_masks_updated_at BEFORE UPDATE ON sim_masks
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
