-- /calendar —— 登录用户的个人日历(Google 日历那一套:多日历 + 重复事件 + 提醒 + 嘉宾 + 对外分享)。
--
-- 时刻一律存绝对毫秒(BIGINT epoch ms)+ 事件自己的 IANA 时区,不用 TIMESTAMPTZ:
-- 重复事件必须按**墙上钟点**推进(每周三 9:00 换季后还是 9:00),这要求把「时区」当事件
-- 的一等字段留着,而不是在写入时折算掉。展开逻辑在 @cuberoot/shared/recur,前后端同一份。
--
-- 归属键 owner_key = requireAuth(c).wcaId(绑了 WCA 就是真 wca_id,没绑是 `u<uid>`),
-- 与 notifications.user_key / comp_follows.wca_id 同语义,长度对齐 VARCHAR(20)。

CREATE TABLE IF NOT EXISTS calendars (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_key   VARCHAR(20) NOT NULL,
  name        VARCHAR(80) NOT NULL DEFAULT '',
  color       VARCHAR(16) NOT NULL DEFAULT 'peacock',
  tz          VARCHAR(64) NOT NULL DEFAULT 'UTC',
  is_default  BOOLEAN     NOT NULL DEFAULT FALSE,  -- 主日历,不可删
  sort_order  INTEGER     NOT NULL DEFAULT 0,
  created_at  BIGINT      NOT NULL,
  updated_at  BIGINT      NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_calendars_owner ON calendars(owner_key, sort_order, id);
-- 一人只能有一个主日历(首次进 /calendar 时自动建)。
CREATE UNIQUE INDEX IF NOT EXISTS idx_calendars_one_default ON calendars(owner_key) WHERE is_default;

CREATE TABLE IF NOT EXISTS calendar_events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calendar_id   BIGINT       NOT NULL REFERENCES calendars(id) ON DELETE CASCADE,
  owner_key     VARCHAR(20)  NOT NULL,
  title         VARCHAR(300) NOT NULL DEFAULT '',
  description   TEXT         NOT NULL DEFAULT '',
  location      VARCHAR(300) NOT NULL DEFAULT '',
  all_day       BOOLEAN      NOT NULL DEFAULT FALSE,
  start_ms      BIGINT       NOT NULL,             -- 全天 = 事件时区当日 0 点
  end_ms        BIGINT       NOT NULL,             -- 半开区间,不含
  tz            VARCHAR(64)  NOT NULL,
  rrule         VARCHAR(200) NOT NULL DEFAULT '',  -- RFC 5545 正文,空 = 不重复
  exdates       TEXT         NOT NULL DEFAULT '',  -- 逗号分隔的 occurrence 起点 ms(删单次 / 被单次覆盖)
  -- 「只改这一次」会生成一条覆盖行:series_id 指主事件,occurrence_ms 说明替换的是哪一次。
  series_id     BIGINT       REFERENCES calendar_events(id) ON DELETE CASCADE,
  occurrence_ms BIGINT,
  color         VARCHAR(16)  NOT NULL DEFAULT '',  -- 空 = 跟随所在日历
  reminders     VARCHAR(120) NOT NULL DEFAULT '',  -- 逗号分隔的「提前分钟数」
  created_at    BIGINT       NOT NULL,
  updated_at    BIGINT       NOT NULL
);
-- 主查询:某人某时间窗的事件。
CREATE INDEX IF NOT EXISTS idx_calendar_events_owner_time ON calendar_events(owner_key, start_ms);
CREATE INDEX IF NOT EXISTS idx_calendar_events_cal_time ON calendar_events(calendar_id, start_ms);
CREATE INDEX IF NOT EXISTS idx_calendar_events_series ON calendar_events(series_id) WHERE series_id IS NOT NULL;
-- 重复事件的 start_ms 只是首次,窗口过滤对它无效 —— 一律整取,所以单独一条部分索引。
CREATE INDEX IF NOT EXISTS idx_calendar_events_recurring ON calendar_events(owner_key) WHERE rrule <> '';

-- 对外展示设置:一人一行,一个不可猜的 token。detail='busy' 时服务端只发时间段,
-- 标题/正文/地点根本不出库外(脱敏在服务端做,不靠前端不渲染)。
CREATE TABLE IF NOT EXISTS calendar_shares (
  owner_key    VARCHAR(20) PRIMARY KEY,
  token        VARCHAR(32) NOT NULL UNIQUE,
  enabled      BOOLEAN     NOT NULL DEFAULT FALSE,
  detail       VARCHAR(8)  NOT NULL DEFAULT 'busy' CHECK (detail IN ('full', 'busy')),
  title        VARCHAR(80) NOT NULL DEFAULT '',
  calendar_ids TEXT        NOT NULL DEFAULT '',    -- 逗号分隔;空 = 全部日历
  tz           VARCHAR(64) NOT NULL DEFAULT 'UTC',
  created_at   BIGINT      NOT NULL,
  updated_at   BIGINT      NOT NULL
);

-- 站内嘉宾(邀请别人参加)。被邀请者在自己的 /calendar 里能看到这条事件,并可接受 / 拒绝。
CREATE TABLE IF NOT EXISTS calendar_guests (
  event_id   BIGINT      NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
  guest_key  VARCHAR(20) NOT NULL,
  status     VARCHAR(10) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at BIGINT      NOT NULL,
  PRIMARY KEY (event_id, guest_key)
);
CREATE INDEX IF NOT EXISTS idx_calendar_guests_key ON calendar_guests(guest_key);

-- 提醒去重:扫描器每分钟跑一次,发过的 (事件, 第几次, 提前几分钟, 收件人) 不再发。
-- 进程重启 / 扫描窗口重叠都不会重复轰炸。
CREATE TABLE IF NOT EXISTS calendar_reminder_log (
  event_id      BIGINT      NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
  occurrence_ms BIGINT      NOT NULL,
  minutes       INTEGER     NOT NULL,
  user_key      VARCHAR(20) NOT NULL,
  sent_at       BIGINT      NOT NULL,
  PRIMARY KEY (event_id, occurrence_ms, minutes, user_key)
);
-- 老记录清理(扫描器顺手删 30 天前的)。
CREATE INDEX IF NOT EXISTS idx_calendar_reminder_log_sent ON calendar_reminder_log(sent_at);
