-- 导入批次 —— 让一次 .ics / .zip 导入可以整批撤销。
--
-- 一次导入会跨多个请求(每个日历一批、每批最多 500 条),所以批次得先建出来、把 id 带在
-- 后续每个请求上,而不是靠时间戳事后猜哪些是一起进来的。
--
-- 撤销 = 删掉挂着这个 id 的事件,再删掉这次导入**新建**且此刻仍然空着的日历。
-- 行本身留着(undone_at 记一笔),这样界面能说清「这次导入已撤销」而不是凭空消失。

CREATE TABLE IF NOT EXISTS calendar_imports (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_key   VARCHAR(20)  NOT NULL,
  source      VARCHAR(120) NOT NULL DEFAULT '',   -- 文件名,给用户认是哪一次
  event_count INTEGER      NOT NULL DEFAULT 0,    -- 实际落库条数,导完回填
  created_at  BIGINT       NOT NULL,
  undone_at   BIGINT                              -- NULL = 还在
);
CREATE INDEX IF NOT EXISTS idx_calendar_imports_owner ON calendar_imports(owner_key, id DESC);

-- ON DELETE SET NULL:批次行万一被清理,事件本身不该跟着没。
ALTER TABLE calendar_events
  ADD COLUMN IF NOT EXISTS import_id BIGINT REFERENCES calendar_imports(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_calendar_events_import
  ON calendar_events(import_id) WHERE import_id IS NOT NULL;

-- 日历也记一笔:这次导入新建的,撤销时若已空则一并删掉,不留一列空壳。
ALTER TABLE calendars
  ADD COLUMN IF NOT EXISTS import_id BIGINT REFERENCES calendar_imports(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_calendars_import
  ON calendars(import_id) WHERE import_id IS NOT NULL;
