-- Import the 33-case Pseudoslotting (PSF2L) reference sheet.
-- Generated by packages/alg-build/gen_psf2l_sql.mts from PSF2L.docx.
-- The three header diagrams explain + / - / 0 entry patterns and are not cases.

INSERT INTO alg_sets (puzzle, set_slug, source, scraped_at) VALUES
  ('3x3', 'psf2l', 'PSF2L.docx (site-owner reference); https://solved.no/guides/pseudoslotting; https://www.youtube.com/watch?v=49Izh9ZnBog', NOW())
ON CONFLICT (puzzle, set_slug) DO UPDATE SET source = EXCLUDED.source, scraped_at = EXCLUDED.scraped_at;

WITH payload AS (SELECT $psf2l$[
  {
    "position": 0,
    "name": "PSF2L 01",
    "subgroup": "",
    "setup": "D R U R' U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 1,
    "name": "PSF2L 02",
    "subgroup": "",
    "setup": "D L' U' L d D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D d' L' U L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 2,
    "name": "PSF2L 03",
    "subgroup": "",
    "setup": "D R U' R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 3,
    "name": "PSF2L 04",
    "subgroup": "",
    "setup": "D F' U F D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 4,
    "name": "PSF2L 05",
    "subgroup": "",
    "setup": "D R U' R' U R U R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U' R' U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 5,
    "name": "PSF2L 06",
    "subgroup": "",
    "setup": "D R' U R d' R U R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U' R' d R' U' R D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 6,
    "name": "PSF2L 07",
    "subgroup": "",
    "setup": "D R U' R' U' R U R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U' R' U R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 7,
    "name": "PSF2L 08",
    "subgroup": "",
    "setup": "D L' U L U L' U' L U' y' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D y U L' U L U' L' U' L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 8,
    "name": "PSF2L 09",
    "subgroup": "",
    "setup": "D R U R' U2' R U R' U' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U R U' R' U2 R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 9,
    "name": "PSF2L 10",
    "subgroup": "",
    "setup": "D R' U R d' R U2' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U2 R' d R' U' R D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 10,
    "name": "PSF2L 11",
    "subgroup": "",
    "setup": "D R U R' U2' R U' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U R' U2 R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 11,
    "name": "PSF2L 12",
    "subgroup": "",
    "setup": "D r U' R' U' R U r' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' r U' R' U R U r' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 12,
    "name": "PSF2L 13",
    "subgroup": "",
    "setup": "D R U R' U2' R U2' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U2 R' U2 R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 13,
    "name": "PSF2L 14",
    "subgroup": "",
    "setup": "D R' U' R U2' R' U2' R d' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D d R' U2 R U2 R' U R D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 14,
    "name": "PSF2L 15",
    "subgroup": "",
    "setup": "D R U R' U' R U2' R' U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U R U2 R' U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 15,
    "name": "PSF2L 16",
    "subgroup": "",
    "setup": "D L' U' L U L' U2' L d D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D d' L' U2 L U' L' U L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 16,
    "name": "PSF2L 17",
    "subgroup": "",
    "setup": "D R U' R' U2' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U2 R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 17,
    "name": "PSF2L 18",
    "subgroup": "",
    "setup": "D F' U F R U' R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U R' F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 18,
    "name": "PSF2L 19",
    "subgroup": "",
    "setup": "D R U R' U' R' D' R U R' D R D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R' D' R U' R' D R U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 19,
    "name": "PSF2L 20",
    "subgroup": "",
    "setup": "D F' U F U2' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U2 F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 20,
    "name": "PSF2L 21",
    "subgroup": "",
    "setup": "D R U' R' U R U2' R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U2 R' U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 21,
    "name": "PSF2L 22",
    "subgroup": "",
    "setup": "D L' U L U' L' U2' L y' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D y L' U2 L U L' U' L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 22,
    "name": "PSF2L 23",
    "subgroup": "",
    "setup": "D R U R' U' R U R' U R U R' U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U R U' R' U' R U' R' U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 23,
    "name": "PSF2L 24",
    "subgroup": "",
    "setup": "D R U R' F R' F' R2' U' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U R2 F R F' R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 24,
    "name": "PSF2L 25",
    "subgroup": "",
    "setup": "D R U R' U' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 25,
    "name": "PSF2L 26",
    "subgroup": "",
    "setup": "D L' U' L U L' U' L y' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D y L' U L U' L' U L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 26,
    "name": "PSF2L 27",
    "subgroup": "",
    "setup": "D R U' R' U R U' R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U R' U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 27,
    "name": "PSF2L 28",
    "subgroup": "",
    "setup": "D F' U F R U R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U' R' F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 28,
    "name": "PSF2L 29",
    "subgroup": "",
    "setup": "D R U R' F R' F' R U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R' F R F' R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 29,
    "name": "PSF2L 30",
    "subgroup": "",
    "setup": "D F' U F U R U R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U' R' U' F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 30,
    "name": "PSF2L 31",
    "subgroup": "",
    "setup": "D R U' R' U F' U F U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U F' U' F U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 31,
    "name": "PSF2L 32",
    "subgroup": "",
    "setup": "D R U' R' r U' r' U2' r U r' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D r U' r' U2 r U r' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 32,
    "name": "PSF2L 33",
    "subgroup": "",
    "setup": "D r U' r' U2' r U r' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' r U' r' U2 r U r' D'",
          "source": "cuberoot"
        }
      ]
    ]
  }
]$psf2l$::jsonb AS body),
items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))
UPDATE alg_cases AS c
SET position = (items.item->>'position')::integer, subgroup = items.item->>'subgroup',
    setup = items.item->>'setup', sticker = items.item->'sticker', algs = items.item->'algs'
FROM items
WHERE c.puzzle = '3x3' AND c.set_slug = 'psf2l' AND c.name = items.item->>'name';

WITH payload AS (SELECT $psf2l$[
  {
    "position": 0,
    "name": "PSF2L 01",
    "subgroup": "",
    "setup": "D R U R' U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 1,
    "name": "PSF2L 02",
    "subgroup": "",
    "setup": "D L' U' L d D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D d' L' U L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 2,
    "name": "PSF2L 03",
    "subgroup": "",
    "setup": "D R U' R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 3,
    "name": "PSF2L 04",
    "subgroup": "",
    "setup": "D F' U F D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 4,
    "name": "PSF2L 05",
    "subgroup": "",
    "setup": "D R U' R' U R U R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U' R' U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 5,
    "name": "PSF2L 06",
    "subgroup": "",
    "setup": "D R' U R d' R U R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U' R' d R' U' R D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 6,
    "name": "PSF2L 07",
    "subgroup": "",
    "setup": "D R U' R' U' R U R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U' R' U R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 7,
    "name": "PSF2L 08",
    "subgroup": "",
    "setup": "D L' U L U L' U' L U' y' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D y U L' U L U' L' U' L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 8,
    "name": "PSF2L 09",
    "subgroup": "",
    "setup": "D R U R' U2' R U R' U' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U R U' R' U2 R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 9,
    "name": "PSF2L 10",
    "subgroup": "",
    "setup": "D R' U R d' R U2' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U2 R' d R' U' R D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 10,
    "name": "PSF2L 11",
    "subgroup": "",
    "setup": "D R U R' U2' R U' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U R' U2 R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 11,
    "name": "PSF2L 12",
    "subgroup": "",
    "setup": "D r U' R' U' R U r' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' r U' R' U R U r' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 12,
    "name": "PSF2L 13",
    "subgroup": "",
    "setup": "D R U R' U2' R U2' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U2 R' U2 R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 13,
    "name": "PSF2L 14",
    "subgroup": "",
    "setup": "D R' U' R U2' R' U2' R d' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D d R' U2 R U2 R' U R D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 14,
    "name": "PSF2L 15",
    "subgroup": "",
    "setup": "D R U R' U' R U2' R' U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U R U2 R' U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 15,
    "name": "PSF2L 16",
    "subgroup": "",
    "setup": "D L' U' L U L' U2' L d D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D d' L' U2 L U' L' U L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 16,
    "name": "PSF2L 17",
    "subgroup": "",
    "setup": "D R U' R' U2' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U2 R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 17,
    "name": "PSF2L 18",
    "subgroup": "",
    "setup": "D F' U F R U' R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U R' F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 18,
    "name": "PSF2L 19",
    "subgroup": "",
    "setup": "D R U R' U' R' D' R U R' D R D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R' D' R U' R' D R U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 19,
    "name": "PSF2L 20",
    "subgroup": "",
    "setup": "D F' U F U2' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U2 F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 20,
    "name": "PSF2L 21",
    "subgroup": "",
    "setup": "D R U' R' U R U2' R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U2 R' U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 21,
    "name": "PSF2L 22",
    "subgroup": "",
    "setup": "D L' U L U' L' U2' L y' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D y L' U2 L U L' U' L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 22,
    "name": "PSF2L 23",
    "subgroup": "",
    "setup": "D R U R' U' R U R' U R U R' U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U R U' R' U' R U' R' U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 23,
    "name": "PSF2L 24",
    "subgroup": "",
    "setup": "D R U R' F R' F' R2' U' R' U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R U R2 F R F' R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 24,
    "name": "PSF2L 25",
    "subgroup": "",
    "setup": "D R U R' U' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' U R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 25,
    "name": "PSF2L 26",
    "subgroup": "",
    "setup": "D L' U' L U L' U' L y' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D y L' U L U' L' U L D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 26,
    "name": "PSF2L 27",
    "subgroup": "",
    "setup": "D R U' R' U R U' R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U R' U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 27,
    "name": "PSF2L 28",
    "subgroup": "",
    "setup": "D F' U F R U R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U' R' F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 28,
    "name": "PSF2L 29",
    "subgroup": "",
    "setup": "D R U R' F R' F' R U D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U' R' F R F' R U' R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 29,
    "name": "PSF2L 30",
    "subgroup": "",
    "setup": "D F' U F U R U R' U2' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U2 R U' R' U' F' U' F D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 30,
    "name": "PSF2L 31",
    "subgroup": "",
    "setup": "D R U' R' U F' U F U' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D U F' U' F U' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 31,
    "name": "PSF2L 32",
    "subgroup": "",
    "setup": "D R U' R' r U' r' U2' r U r' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D r U' r' U2 r U r' R U R' D'",
          "source": "cuberoot"
        }
      ]
    ]
  },
  {
    "position": 32,
    "name": "PSF2L 33",
    "subgroup": "",
    "setup": "D r U' r' U2' r U r' R U R' D'",
    "sticker": {
      "kind": "f2l",
      "fl": ""
    },
    "algs": [
      [
        {
          "alg": "D R U' R' r U' r' U2 r U r' D'",
          "source": "cuberoot"
        }
      ]
    ]
  }
]$psf2l$::jsonb AS body),
items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))
INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)
SELECT '3x3', 'psf2l', (item->>'position')::integer, item->>'name', item->>'subgroup',
       item->>'setup', item->'sticker', item->'algs'
FROM items
WHERE NOT EXISTS (SELECT 1 FROM alg_cases WHERE puzzle = '3x3' AND set_slug = 'psf2l' AND name = item->>'name');

DO $psf2l_counts$
DECLARE got BIGINT;
BEGIN
  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = 'psf2l';
  IF got <> 33 THEN RAISE EXCEPTION '3x3/psf2l: expected 33 cases, got %', got; END IF;
  SELECT COALESCE(SUM((SELECT SUM(jsonb_array_length(orientation.value)) FROM jsonb_array_elements(algs) AS orientation(value))), 0) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = 'psf2l';
  IF got <> 33 THEN RAISE EXCEPTION '3x3/psf2l: expected 33 algorithms, got %', got; END IF;
END
$psf2l_counts$;
