import type { StackTool } from '../stack_tool_types';
import { k, v, s, n, f, p, c, t } from '../stack_tool_types';

// ─── Bun 1.2 (not used by cuberoot.me today, planted flag) ──────────────────

export const BUN: StackTool = {
  slug: 'bun',
  name: 'Bun',
  version: '1.2',
  since: '2022-07',
  group: 'dev',
  accent: '#E78E5C',
  bright: '#F2B68F',
  glyph: '◓',
  floats: ['bun install', 'bun run', 'bun test', 'Bun.serve', 'bunx', 'JavaScriptCore', 'Zig', 'Oven', 'bun build', 'bun.lockb', 'WinterCG', 'Hono'],
  zh: {
    tagline: 'Node + npm + Vite + Vitest 一个二进制全干完',
    role: '未在用。如果哪天换, 最先动的两块: api.cuberoot.me 的 Hono server (Bun 跑 Hono 比 Node 快) + core/scripts/ 的一次性 TS 脚本 (bun run 比 tsx 快 2-3 倍)。当前 pm2 + Node 22 没在卡, 不动它。',
    heroSub: <>把前端工程师每天用的四件事 (runtime + 包管理 + bundler + test runner) 塞进一个二进制。Jarred Sumner 2022 年公开, 公司叫 Oven, Zig 写, JS 引擎用 Safari 的 JavaScriptCore (不是 V8)。<strong>本站当前不依赖 Bun</strong>, 这页是给未来一年看的栈选项。</>,
    whatDesc: <>Bun 是个<strong>一体化 JS 工具链</strong>:runtime 兼容 Node API, 包管理兼容 npm registry, bundler 替 Vite/esbuild, test runner 兼容 Jest API。compat-first speedup —— 不重新发明轮子, 只把同样的事在更快的实现里重做一遍。</>,
    historyDesc: <>从 2022-07 v0.1 公开, 到 2023-09 v1.0 GA, 再到 2025 v1.2 把 monorepo workspaces 跟 Windows 支持稳住。三年从"HN 周末玩具"长成 production 可选项, 但跟 Node 17 年的 edge case 厚度比, 还年轻。</>,
    conceptsTitle: '一体化工具链',
    conceptsDesc: <>Bun 的可观察 CLI 就五条:<code>bun install</code> / <code>bun run</code> / <code>bun test</code> / <code>bun build</code> / <code>bunx</code>。再加 runtime 内置的 <code>Bun.serve()</code> / <code>Bun.file()</code> / <code>Bun.sql()</code> 几个全局 API。剩下都是兼容 Node 的镜像。</>,
    whyDesc: <>2026 年考虑 Bun, 不是因为它"全"或"新", 而是<strong>冷启动快</strong>、<strong>内置 TS</strong>、<strong>跟 Hono / Elysia 这类 Bun-first 框架配合好</strong>。但同时也要诚实:<strong>cuberoot 没冷启动痛点</strong>, Node + pnpm 的 monorepo 收益 Bun 还给不出来。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>Hono / Elysia 等 Bun-first 框架, Cloudflare Workers 和 Vercel Edge 的 runtime 选项, tldraw / Excalidraw 等项目把 Bun 用在 dev 脚本上。新建 startup 把 Bun 当默认的比例在涨。<strong>cuberoot.me 不在这名单里</strong>。</>,
    cuberootDesc: <><strong>当前 cuberoot.me 代码库不依赖 Bun。</strong> Stack 在跑 Node 22 + pnpm 10 + Vite 8 + Vitest, 四件事各自最稳。这页放进 /code/stack 是因为有两块地方 Bun 的 ROI 真存在, 留个 flag 给下一年的自己。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>2025-2026 是不是新建项目默认选 Bun 的分界年, 答案越来越像 yes。Windows 支持完善, bun test 在替代 Jest, pm2 等老 Node 工具链对 Bun 兼容也在追平。但替换 pnpm 的 monorepo 治理还差一截。</>,
  },
  en: {
    tagline: 'Node + npm + Vite + Vitest, all in one binary',
    role: 'Not in use. If we ever switch, the two first targets are api.cuberoot.me (Hono on Bun beats Node) and the one-off TS scripts under core/scripts/ (bun run is 2-3x faster cold start than tsx). The current pm2 + Node 22 setup is fine, so it stays.',
    heroSub: <>One binary that absorbs the four daily tools a JS engineer uses (runtime + package manager + bundler + test runner). Jarred Sumner shipped it publicly in 2022 through his company Oven, written in Zig, using Safari's JavaScriptCore (not V8). <strong>This site does not use Bun today</strong> — the page is a stack option for the year ahead.</>,
    whatDesc: <>Bun is an <strong>all-in-one JS toolchain</strong>: the runtime mirrors Node's APIs, the package manager talks to npm registry, the bundler replaces Vite/esbuild, the test runner is Jest-compatible. Compat-first speedup — no reinvention, just the same job in a faster implementation.</>,
    historyDesc: <>From v0.1 public release in 2022-07, through 1.0 GA in 2023-09, to 1.2 in 2025 stabilizing monorepo workspaces and Windows support. Three years took it from "HN weekend toy" to a viable production option — but next to Node's 17 years of edge-case depth, Bun is still young.</>,
    conceptsTitle: 'All-in-one toolchain',
    conceptsDesc: <>The Bun CLI surface is just five entries: <code>bun install</code> / <code>bun run</code> / <code>bun test</code> / <code>bun build</code> / <code>bunx</code>. Plus a handful of runtime globals — <code>Bun.serve()</code> / <code>Bun.file()</code> / <code>Bun.sql()</code>. Everything else is a Node-compatible mirror.</>,
    whyDesc: <>Considering Bun in 2026 is not about feature count or novelty — it's about <strong>fast cold start</strong>, <strong>built-in TS</strong>, and <strong>natural fit with Bun-first frameworks (Hono / Elysia)</strong>. But honestly: <strong>cuberoot has no cold-start pain point</strong>, and Bun cannot match the Node + pnpm monorepo wins yet.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Hono / Elysia and other Bun-first frameworks; Cloudflare Workers and Vercel Edge as a runtime option; projects like tldraw / Excalidraw using Bun for dev scripts. The share of new startups defaulting to Bun is rising. <strong>cuberoot.me is not on this list.</strong></>,
    cuberootDesc: <><strong>cuberoot.me currently does not depend on Bun.</strong> The live stack is Node 22 + pnpm 10 + Vite 8 + Vitest — each best-in-class for its slot. The page lives in /code/stack because two specific spots have real Bun ROI, and a flag for next-year's self is worth planting.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>Whether 2025-2026 is the inflection year where new projects default to Bun increasingly looks like yes. Windows support has matured, bun test is displacing Jest, the pm2 / nodemon class of "old Node" tooling is catching up on Bun compatibility. The monorepo-governance gap to pnpm is still real, though.</>,
  },
  heroStats: [
    { num: '1', unit: '.2', zh: <>当前稳定版 <em>2026-05 估</em></>, en: <>current stable <em>2026-05 est.</em></> },
    { num: '~3', unit: 'x', zh: <>Bun.serve vs Node http 简单 JSON 吞吐 <em>oven-sh 公开 bench</em></>, en: <>Bun.serve vs Node http simple JSON throughput <em>oven-sh public bench</em></> },
    { num: '~10', unit: 'ms', zh: <>冷启动 (vs Node ~30ms) <em>serverless friendly</em></>, en: <>cold start (vs Node ~30ms) <em>serverless friendly</em></> },
    { num: '0', zh: <>cuberoot.me 当前在用的 Bun 进程 <em>诚实数字</em></>, en: <>Bun processes used by cuberoot.me today <em>honest number</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>Bun 是 Jarred Sumner 2022 年 7 月公开的项目, 公司叫 <strong>Oven</strong>。野心很大:把 JS 工程师每天用的四件事 —— runtime、包管理器、bundler、test runner —— 合成一个二进制。语言用 Zig (不是 Rust, 不是 Go), JS 引擎用 Safari 的 <strong>JavaScriptCore</strong> (不是 Chrome 的 V8), 这两个选择决定了它跟 Node / Deno 的性能曲线长得不一样。</p>
        <p>关键设计是"compatibility-first speedup":不重新发明 API, 只把 Node 跟 npm 跟 Webpack 跟 Jest 干的事在更快的实现里重做一遍。<code>bun install</code> 兼容 <code>package.json</code> + npm registry, <code>bun run</code> 直接跑 <code>.ts</code> / <code>.tsx</code> / <code>.jsx</code> 文件不编译, <code>Bun.serve()</code> 是个新的 HTTP API 但 Node http + Hono 也都能在 Bun 上跑。这种"兼容 + 加速"的姿态让迁移成本远低于当年 Deno 的"全 reset"路线。</p>
        <p>2023-09 v1.0 GA, 2024-2025 把 Windows 支持 / npm 兼容 / bun test 稳定下来, 2026 已经是个能进 production 的选项 —— Hono 框架作者 yusukebe 经常先跑 Bun。但跟 Node 17 年的 edge case 厚度比, Bun 还年轻, native module / 某些 npm 包 (尤其依赖 V8 specific 行为的) 跑不顺的 issue 仍然在出。</p>
      </>
    ),
    en: (
      <>
        <p>Bun is Jarred Sumner's project, publicly released in 2022-07 through his company <strong>Oven</strong>. The ambition is wide: collapse the four tools a JS engineer touches daily — runtime, package manager, bundler, test runner — into a single binary. Written in Zig (not Rust, not Go), powered by Safari's <strong>JavaScriptCore</strong> (not Chrome's V8). Those two choices give it a different performance curve from Node / Deno.</p>
        <p>The key design move is "compatibility-first speedup": don't reinvent the APIs — just redo what Node, npm, Webpack, and Jest already do in a faster implementation. <code>bun install</code> reads <code>package.json</code> and talks to the npm registry; <code>bun run</code> executes <code>.ts</code> / <code>.tsx</code> / <code>.jsx</code> directly without a compile step; <code>Bun.serve()</code> is a new HTTP API but Node's <code>http</code> module and Hono both work on Bun. That "compatible + faster" stance keeps migration cost far below Deno's earlier "full reset" approach.</p>
        <p>v1.0 GA shipped 2023-09; through 2024-2025 Windows support, npm compatibility, and bun test stabilized; by 2026 Bun is a viable production option — Hono's author yusukebe routinely tests Bun first. Compared to Node's 17 years of edge-case depth, though, Bun is young: native modules and certain npm packages (especially ones depending on V8-specific behavior) still hit unsolved issues.</p>
      </>
    ),
  },
  history: [
    { year: '2021', zh: { title: <>立项 + Oven 成立</>, desc: <>Jarred Sumner 在 Stripe / Marc Lou 一线呆过之后, 个人立项 Bun, 注册公司 Oven。Zig + JavaScriptCore 的选型从这时定下来。</> }, en: { title: <>Project starts + Oven founded</>, desc: <>After stints around Stripe / Marc Lou's circle, Jarred Sumner kicks off Bun and registers Oven. The Zig + JavaScriptCore choice is set during this period.</> } },
    { year: '2022·07', zh: { title: <>v0.1 公开 (HN 首页)</>, desc: <>第一个公开 demo 抛上 HN 立刻刷屏。卖点:bun install 比 npm 快 20x, bun run 比 node 启动快 4x。社区第一反应是怀疑跑分。</> }, en: { title: <>v0.1 public (HN front page)</>, desc: <>The first public demo lands on HN's front page immediately. Pitch: bun install 20x faster than npm, bun run 4x faster cold start than node. First community reaction is benchmark skepticism.</> } },
    { year: '2023·01', zh: { title: <>0.5 — Windows 实验支持</>, desc: <>原本只 Linux/macOS。0.5 起开始往 Windows 移植, 但生产可用得等到 1.1。</> }, en: { title: <>0.5 — experimental Windows</>, desc: <>Originally Linux/macOS only. From 0.5 onward, the Windows port begins; production-ready Windows had to wait for 1.1.</> } },
    { year: '2023·09', highlight: true, zh: { title: <>1.0 GA</>, desc: <>大版本里程碑。Bun 自称从这版起 "drop-in replacement for Node" —— 在多数 Node 包上 verified。社区开始有人在 production 跑 Bun。</> }, en: { title: <>1.0 GA</>, desc: <>The major milestone. Bun self-describes as a "drop-in replacement for Node" from this release — verified across most Node packages. The first community production deployments appear.</> } },
    { year: '2024·04', zh: { title: <>1.1 — Windows 稳定</>, desc: <>Windows 进 GA, npm 兼容性补强, bun test 跑通 Jest 大部分 API。bun --watch 跟 node --watch 对齐。</> }, en: { title: <>1.1 — Windows GA</>, desc: <>Windows hits GA; npm compatibility tightens; bun test covers most of the Jest API. bun --watch reaches parity with node --watch.</> } },
    { year: '2024·10', zh: { title: <>bun test 替代浪潮</>, desc: <>一些项目从 Jest / Vitest 迁到 bun test, 主要是看中"启动快 + 不用配 ts-jest"。但跟 vitest 的并行模型和 watch UI 比, 还有差距。</> }, en: { title: <>bun test displacement wave</>, desc: <>Some projects migrate from Jest / Vitest to bun test, mostly for "fast startup + no ts-jest setup." Still trails Vitest's parallel model and watch UI.</> } },
    { year: '2025·01', zh: { title: <>Hono / Elysia 站稳</>, desc: <>Hono (yusukebe) 是 cross-runtime 但在 Bun 上跑最快。Elysia (saltyaom) 是 Bun-only, end-to-end 类型系统对标 tRPC。两者一起让 "Bun 写 API" 成为合理工程选择。</> }, en: { title: <>Hono / Elysia gain traction</>, desc: <>Hono (yusukebe) is cross-runtime but fastest on Bun. Elysia (saltyaom) is Bun-only with end-to-end types rivaling tRPC. Together they make "API in Bun" a defensible engineering choice.</> } },
    { year: '2025·06', zh: { title: <>1.2 — workspaces 完善</>, desc: <>monorepo workspaces 跟 pnpm 路线靠拢, package manager 性能再优化。但全局 store + 硬链接这套 pnpm 杀手锏 Bun 还没做。</> }, en: { title: <>1.2 — workspaces mature</>, desc: <>Monorepo workspaces converge toward pnpm semantics; the package manager gets another perf pass. Bun still lacks pnpm's killer move — a global store + hard links.</> } },
    { year: '2025·10', zh: { title: <>Edge runtime 落地</>, desc: <>Cloudflare Workers / Vercel Edge 都把 Bun runtime 加进可选项 (具体形态看各家 release notes), 主要因为冷启动毫秒级。但 isolate-V8 那条路线仍是主流。</> }, en: { title: <>Edge runtime arrives</>, desc: <>Cloudflare Workers / Vercel Edge add Bun runtime as an option (exact shape per their release notes), mainly because of millisecond-tier cold start. The isolate-V8 path stays mainstream though.</> } },
    { year: '2026·02', zh: { title: <>npm install 兼容率破 99%</>, desc: <>Bun 自称 npm 包安装兼容率 &gt; 99%, 剩下的 native module 跑不通的 issue 列表也在缩。</> }, en: { title: <>npm install compat &gt; 99%</>, desc: <>Bun reports &gt;99% npm-install compatibility; the remaining native-module failure list keeps shrinking.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>当前 — cuberoot 未使用</>, desc: <>新建项目里 Bun 已经是真选项, 老项目大多还 Node + pnpm。<strong>cuberoot.me 属于后者</strong>:Node 22 + pnpm 10 + Vite 8 + Vitest 都在正常跑, 没换 Bun 的紧迫感。</> }, en: { title: <>Now — cuberoot does not use it</>, desc: <>Bun is a real choice for new projects; older projects mostly stay on Node + pnpm. <strong>cuberoot.me is in the latter group</strong>: Node 22 + pnpm 10 + Vite 8 + Vitest run fine, with no urgency to switch.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>bun install</>, desc: <>兼容 <code>package.json</code> + npm registry, 出 <code>bun.lockb</code> (二进制 lockfile, 比 pnpm-lock.yaml 小 10x)。比 npm 快 20x 的官方数字主要来自并行下载 + 解析 + 全局 cache。</> }, en: { title: <>bun install</>, desc: <>Reads <code>package.json</code>, talks to the npm registry, writes <code>bun.lockb</code> (binary lockfile, ~10x smaller than pnpm-lock.yaml). The "20x faster than npm" headline comes from parallel fetch + parse + a global cache.</> }, code: <code>$ {f('bun')} install{'\n'}{c('# resolves + downloads + links')}{'\n'}{c('# typical: 100-500ms warm, 2s cold')}</code> },
    { tag: 'B', zh: { title: <>bun run foo.ts</>, desc: <>直接跑 <code>.ts</code> / <code>.tsx</code> / <code>.jsx</code>, 不走 tsc / tsx 中间层。启动 ~10ms。比 <code>tsx foo.ts</code> 快 2-3x。core/scripts/ 那种一次性脚本最受益。</> }, en: { title: <>bun run foo.ts</>, desc: <>Executes <code>.ts</code> / <code>.tsx</code> / <code>.jsx</code> directly — no tsc / tsx hop. ~10ms startup. 2-3x faster than <code>tsx foo.ts</code>. One-off scripts under core/scripts/ benefit most.</> }, code: <code>$ {f('bun')} run scripts/sync_alg.ts{'\n'}{c('# vs')}{'\n'}$ {f('tsx')} scripts/sync_alg.ts</code> },
    { tag: 'C', zh: { title: <>Bun.serve()</>, desc: <>内置 HTTP server, 跟 Hono 的 fetch handler 直接配。同样 JSON 响应吞吐对比 Node http 在公开 bench 上 ~3x。Hono 在 Bun 上是它"最快的形态"。</> }, en: { title: <>Bun.serve()</>, desc: <>Built-in HTTP server; pairs natively with Hono's fetch handler. On equivalent JSON workloads, public benches show ~3x Node http throughput. Hono is at its fastest when hosted on Bun.</> }, code: <code>{k('import')} {'{'} {v('Hono')} {'}'} {k('from')} {s('"hono"')};{'\n\n'}{k('const')} {v('app')} = {k('new')} {f('Hono')}();{'\n'}{v('app')}.{f('get')}({s('"/health"')}, ({v('c')}) =&gt; {v('c')}.{f('text')}({s('"ok"')}));{'\n\n'}{v('Bun')}.{f('serve')}({'{ '}{p('port')}: {n('3001')}, {p('fetch')}: {v('app')}.{p('fetch')} {'}'});</code> },
    { tag: 'D', zh: { title: <>bun test</>, desc: <>Jest 兼容 API (<code>describe</code> / <code>it</code> / <code>expect</code>) + 启动快。但跟 Vitest 比, watch UI / browser mode / coverage 报告仍弱一档。</> }, en: { title: <>bun test</>, desc: <>Jest-compatible API (<code>describe</code> / <code>it</code> / <code>expect</code>) with fast startup. Still weaker than Vitest on watch UI / browser mode / coverage reporting.</> }, code: <code>{k('import')} {'{'} {v('test')}, {v('expect')} {'}'} {k('from')} {s('"bun:test"')};{'\n\n'}{f('test')}({s('"adds"')}, () =&gt; {'{'}{'\n'}  {f('expect')}({n('1')} + {n('1')}).{f('toBe')}({n('2')});{'\n'}{'}'});</code> },
    { tag: 'E', zh: { title: <>bunx</>, desc: <>替 <code>npx</code>。一次性跑包不装进项目, 配合 Bun 全局 cache 比 npx 快很多。</> }, en: { title: <>bunx</>, desc: <>Drop-in for <code>npx</code>. Runs a package once without installing it locally; with Bun's global cache, noticeably faster than npx.</> }, code: <code>$ {f('bunx')} cowsay {s('"hello"')}{'\n'}$ {f('bunx')} prisma migrate dev</code> },
    { tag: 'F', zh: { title: <>bun build</>, desc: <>内置 bundler, esbuild 路线的对标。CLI 简单, 跟 Vite 比插件生态浅一截, dev HMR / SSR / RSC 不如 Vite 8 + Rolldown 那套深。</> }, en: { title: <>bun build</>, desc: <>Built-in bundler in the esbuild lineage. Simple CLI, but plugin ecosystem is shallower than Vite, and HMR / SSR / RSC are behind Vite 8 + Rolldown.</> }, code: <code>$ {f('bun')} build src/index.ts \{'\n'}    --outdir dist \{'\n'}    --target browser</code> },
    { tag: 'G', zh: { title: <>bun.lockb (二进制 lockfile)</>, desc: <>不是 YAML / JSON, 是二进制。优点:小 + parse 快。缺点:<strong>git diff 看不见</strong>。代码 review 这点比 pnpm-lock.yaml 难。1.2 可选 export 文本版。</> }, en: { title: <>bun.lockb (binary lockfile)</>, desc: <>Not YAML / JSON — binary. Pro: small + fast to parse. Con: <strong>git diff is opaque</strong>, hurting code review compared with pnpm-lock.yaml. 1.2 added an optional text export.</> }, code: <code>{c('# in git')}{'\n'}{c('# 1.2 KB binary, fast parse')}{'\n'}{c('# but diffs are illegible')}</code> },
    { tag: 'H', zh: { title: <>Web 标准 API 优先</>, desc: <>fetch / Response / WebSocket / Headers 全部是全局 Web 标准, 不是 Node 那批老 API。WinterCG-aligned, 服务端 / edge / 客户端代码可以高度共用。</> }, en: { title: <>Web-standard APIs first</>, desc: <>fetch / Response / WebSocket / Headers are global Web standards, not Node's older APIs. WinterCG-aligned, so server / edge / client code can share a lot.</> }, code: <code>{c('// the same code runs in Bun, Workers, Deno')}{'\n'}{k('async')} {k('function')} {f('handler')}({v('req')}: {t('Request')}): {t('Promise')}{t('<')}{t('Response')}{t('>')} {'{'}{'\n'}  {k('return')} {k('new')} {f('Response')}({s('"ok"')});{'\n'}{'}'}</code> },
  ],
  whyCards: [
    { icon: '◓', zh: { title: <>一个二进制装完, 工具链全有</>, desc: <>不用分别装 node + npm/pnpm + vite + vitest + tsx。Bun 单文件 ~80MB, 进新机器一条命令搞定所有。</> }, en: { title: <>One binary, full toolchain</>, desc: <>Skip the node + npm/pnpm + vite + vitest + tsx installs. Bun is one ~80MB file — a fresh machine gets everything in a single command.</> }, code: <>$ curl -fsSL https://bun.sh/install | bash</> },
    { icon: '⚡', zh: { title: <>Cold start ~10ms — serverless / edge friendly</>, desc: <>Bun 启动 ~10ms 量级 (Node ~30ms, Deno ~25ms)。冷启动收钱的 serverless / edge 场景显著省。但 cuberoot 是长进程 (pm2 fork), 这块零受益。</> }, en: { title: <>~10ms cold start — serverless / edge friendly</>, desc: <>Bun starts in ~10ms (Node ~30ms, Deno ~25ms). Real money on cold-start-billed serverless / edge. cuberoot runs a long-lived pm2 fork — zero benefit there.</> }, code: <>{c('// cold start ranking')}{'\n'}{c('// Bun ~10ms < Deno ~25ms < Node ~30ms')}</> },
    { icon: '⌬', zh: { title: <>内置 TypeScript, 不用 tsc / tsx</>, desc: <>直接跑 <code>.ts</code> 文件, 类型注释当注释跳过 (不做类型检查)。dev 起步省一层工具。Node 22 的 <code>--experimental-strip-types</code> 在追这件事, 但还在实验。</> }, en: { title: <>Built-in TypeScript, no tsc / tsx</>, desc: <>Runs <code>.ts</code> directly; type annotations are stripped (no type-checking). Removes one layer of dev tooling. Node 22's <code>--experimental-strip-types</code> chases this, but is still experimental.</> }, code: <>$ {f('bun')} run src/server.ts</> },
    { icon: '⌗', zh: { title: <>Hono / Elysia 等 Bun-first 框架原生快一档</>, desc: <>Hono 在 Bun 上吞吐显著高于 Node。Elysia 直接 Bun-only, end-to-end 类型系统。"API 在 Bun 上写" 是 2026 一个工程师能做的合理选。</> }, en: { title: <>Bun-first frameworks (Hono / Elysia) are a notch faster</>, desc: <>Hono on Bun throughputs noticeably higher than on Node. Elysia is Bun-only with end-to-end types. "Write the API on Bun" is a reasonable 2026 choice.</> }, code: <>{v('Bun')}.{f('serve')}({'{ '}{p('fetch')}: app.fetch {'}'});</> },
    { icon: '⚠', zh: { title: <>但: native modules 仍踩坑</>, desc: <>pg-native / sharp / better-sqlite3 / bcrypt 这类 C++ 绑定 Bun 兼容率在追, 但偶尔 segfault / install 失败。生态年轻, 老 native module 维护者也不一定测 Bun。</> }, en: { title: <>But: native modules still hit edges</>, desc: <>pg-native / sharp / better-sqlite3 / bcrypt and other C++ bindings are getting better on Bun, but occasional segfaults / install failures remain. The ecosystem is young; older native maintainers don't always test on Bun.</> }, code: <>{c('// "Symbol not found" in pg-native on Bun')}{'\n'}{c('// pin to a known-good version or fall back to JS impl')}</> },
    { icon: '⚠', zh: { title: <>但: pm2 + Bun 不够工业级</>, desc: <>pm2 对 Bun 进程的 cluster mode / 日志轮转 / graceful reload 仍有毛刺。Node + pm2 经过 10 年 production 打磨, 这一档 Bun 还没补齐。cuberoot 单机部署看重这一档。</> }, en: { title: <>But: pm2 + Bun is not yet industrial</>, desc: <>pm2's cluster mode / log rotation / graceful reload on Bun processes still has rough edges. Node + pm2 has been polished by 10 years of production. cuberoot's single-host deploy cares about exactly this layer.</> }, code: <>$ pm2 start --interpreter ~/.bun/bin/bun src/index.ts{'\n'}{c('# works, but not as battle-tested')}</> },
    { icon: '⚠', zh: { title: <>但: 没有 pnpm 那种全局 store</>, desc: <>pnpm 全局硬链接 store 在 cuberoot 这种 11-package monorepo 上是真实节盘 (几个 GB)。Bun 的 install 快但每个项目仍各自拉一份, 这个数学题对 monorepo 不利。</> }, en: { title: <>But: no pnpm-style global store</>, desc: <>pnpm's hard-linked global store saves real GBs on cuberoot's 11-package monorepo. Bun installs are fast but still per-project — the disk math doesn't favor monorepos.</> }, code: <>{c('// pnpm: 1 lodash on disk')}{'\n'}{c('// Bun: 1 per project')}</> },
    { icon: '⚠', zh: { title: <>但: cuberoot 没冷启动痛点</>, desc: <>api.cuberoot.me 是长进程, pm2 fork 一次跑半年。冷启动的 20ms 差异在我们这里完全不可见。换 Bun 的最大卖点对我们 = 0。</> }, en: { title: <>But: cuberoot has no cold-start pain</>, desc: <>api.cuberoot.me is a long-lived process — one pm2 fork that runs for months. The 20ms cold-start delta is invisible to us. Bun's headline benefit lands at zero here.</> }, code: <>{c('// uptime: 6 months')}{'\n'}{c('// cold starts/year: ~2 (deploys)')}</> },
    { icon: '⚠', zh: { title: <>但: Vite + Vitest 在这套场景已够好</>, desc: <>cuberoot 是 24 页 SPA + worker + WASM 的客户端项目。Vite 8 的 dev / build / plugin / Rolldown + Vitest 4 的 worker test fixture 用着没毛病。换 Bun 是<strong>侧移</strong>, 不是升级。</> }, en: { title: <>But: Vite + Vitest already fits</>, desc: <>cuberoot is a 24-page SPA + workers + WASM client. Vite 8's dev / build / plugin / Rolldown plus Vitest 4's worker fixtures work fine. Switching to Bun is a <strong>lateral move</strong>, not an upgrade.</> }, code: <>{c('// current: works')}{'\n'}{c('// proposed: also works')}{'\n'}{c('// delta: ~0 dev time saved')}</> },
  ],
  adopters: [
    { name: '不在 cuberoot.me', highlight: true, zhNote: '未使用 — 当前栈是 Node 22 + pnpm 10 + Vite 8 + Vitest', enNote: 'Not in use — current stack is Node 22 + pnpm 10 + Vite 8 + Vitest' },
    { name: 'Hono', href: 'https://hono.dev', highlight: true, zhNote: 'cross-runtime web 框架, 在 Bun 上跑得最快', enNote: 'Cross-runtime web framework, fastest when hosted on Bun' },
    { name: 'Elysia', href: 'https://elysiajs.com', highlight: true, zhNote: 'Bun 钦定的端到端类型 web 框架', enNote: 'Bun-native end-to-end-typed web framework' },
    { name: 'Cloudflare Workers', href: 'https://workers.cloudflare.com', zhNote: 'runtime 选项之一 (除 V8 isolate 外)', enNote: 'Available as a runtime option alongside V8 isolates' },
    { name: 'Vercel Edge', href: 'https://vercel.com/docs/functions/runtimes/edge', zhNote: 'Edge runtime 提供 Bun 选项', enNote: 'Bun is offered as an Edge runtime option' },
    { name: 'tldraw', href: 'https://tldraw.com', zhNote: 'dev 流程脚本切到 Bun', enNote: 'Some dev-process scripts run on Bun' },
    { name: 'Excalidraw', href: 'https://excalidraw.com', zhNote: 'CI / 内部工具脚本用 Bun', enNote: 'CI / internal tool scripts use Bun' },
    { name: 'Marc Lou indie SaaS', zhNote: '独立开发者一代 startup 把 Bun 当默认', enNote: 'Solo-dev SaaS startups default to Bun' },
    { name: 'Anthropic (内部脚本)', href: 'https://www.anthropic.com', zhNote: '部分内部工具脚本跑 Bun', enNote: 'Some internal tooling scripts run on Bun' },
    { name: 'Sentry (CLI 子集)', href: 'https://sentry.io', zhNote: '部分 CLI / dev 工具走 Bun', enNote: 'A subset of CLI / dev tooling runs on Bun' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>新建项目的默认是不是要切 Bun</>, body: <><p>2025-2026 这一两年内, "新建一个 TS API / 全栈项目, 你 npm init 还是 bun init?" 这个问题的答案明显从 npm 倒向 bun。冷启动 + 内置 TS + 内置 test + 装得快, 几条加起来确实让 day-1 体验比 Node 链好。</p><p>但<strong>这个论断对存量项目不成立</strong>。Node + pnpm 的 monorepo 治理 + native module 兼容 + pm2 工业级部署, 老项目把这些换成 Bun 是侧移, 不是升级。cuberoot 属于后者, 所以这页是 flag 不是 todo。</p></> }, en: { title: <>Are new projects defaulting to Bun</>, body: <><p>Over 2025-2026 the answer to "new TS API / full-stack project — do I npm init or bun init?" tilts visibly from npm to bun. Cold start + built-in TS + built-in test + fast install genuinely make day-1 DX better than the Node chain.</p><p><strong>That conclusion doesn't transfer to existing projects.</strong> Node + pnpm monorepo governance + native module compat + industrial pm2 deploys make a swap to Bun a lateral move, not an upgrade. cuberoot is in this camp, which is why the page is a flag, not a todo.</p></> } },
    { tag: 'WINDOWS', zh: { title: <>Windows 支持完善</>, body: <><p>2023-2024 Bun 在 Windows 上还是二等公民, 2024-2025 的 1.1 + 1.2 把 Windows 路径 / fs / 子进程 / npm install 全过一遍。2026 在 Windows 用 Bun 不再是 dealbreaker, 这是它能进 cuberoot 这种 Windows dev / Linux prod 的项目的前提。</p></> }, en: { title: <>Windows support catches up</>, body: <><p>In 2023-2024 Bun was a second-class citizen on Windows; 1.1 + 1.2 in 2024-2025 reworked Windows paths / fs / subprocess / npm install. By 2026, using Bun on Windows is no longer a dealbreaker — a prerequisite for projects like cuberoot that dev on Windows and ship to Linux.</p></> } },
    { tag: 'TESTS', zh: { title: <>bun test 蚕食 Jest</>, body: <><p>bun test 兼容 Jest API + 启动快, 在简单 unit test 场景对 Jest 占绝对优势。但 Vitest 在 worker / browser / coverage / watch UI 几个维度仍领先一档, 复杂前端项目暂时不动。cuberoot 是 Vitest 这边。</p></> }, en: { title: <>bun test eats Jest's lunch</>, body: <><p>Bun test mirrors the Jest API with much faster startup, dominating Jest on simple unit-test workloads. But Vitest still leads on workers / browser / coverage / watch UI, so heavier frontend projects (cuberoot included) don't move yet.</p></> } },
    { tag: <>OPS</>, zh: { title: <>老 Node 工具链对 Bun 兼容性追平</>, body: <><p>pm2 / nodemon / pino / OpenTelemetry / Sentry SDK 这一票"基础设施级" Node 工具对 Bun 的支持在 2025-2026 逐步成熟。从 "能跑" 到 "production-tested" 的差距是 cuberoot 真正等的 inflection point。</p></> }, en: { title: <>Legacy Node ops tooling reaches Bun parity</>, body: <><p>pm2 / nodemon / pino / OpenTelemetry / Sentry SDK and other "infrastructure-tier" Node tools steadily ship Bun support through 2025-2026. The gap from "runs" to "production-tested" is the inflection point cuberoot is actually watching.</p></> } },
    { tag: <>RISK</>, zh: { title: <>VC-backed 单点公司</>, body: <><p>Bun 的核心维护几乎全在 Oven (≈ Jarred Sumner + 小团队)。Node 是 OpenJS Foundation 治理, 维护池大得多。Bun 出现"单点离场 / 商业化路线变向"的风险一直在, 老项目跟它绑死之前要算这账。</p></> }, en: { title: <>VC-backed single-vendor risk</>, body: <><p>Bun's core maintenance sits almost entirely inside Oven (Jarred Sumner + a small team). Node lives under OpenJS Foundation with a much wider pool. The risk of "single point of departure / commercial pivot" is real, and worth pricing in before tying a long-lived project to it.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p><strong>明确写在前面: cuberoot.me 当前不依赖 Bun。</strong> 整套 stack 在跑 Node 22 LTS + pnpm 10 + Vite 8 + Vitest 4, 四件事各自最稳, 没出任何 bottleneck。这页放进 /code/stack 是因为 Bun 是一个<strong>合理的未来选项</strong>, 而不是已经在用的工具 —— 跟 /code/stack/obsidian 是一样的"planted flag"角色。</p>
        <p>哪天会动 Bun 两块明确的地方:</p>
        <p>1. <strong>api.cuberoot.me 的 Hono server。</strong> Hono 在 Bun 上比 Node 快、内存还小, 而我们已经在用 Hono。换 runtime 是 <code>node dist/index.js</code> → <code>bun dist/index.js</code> 一行 ecosystem.config.js 改动。但 pm2 + Bun 的 cluster reload / 日志轮转 / graceful restart 几个毛刺还没磨干净, 而且 cuberoot 的负载本来就在 Node 22 上跑得很闲, ROI 暂时不到位。<br/>
        2. <strong>core/scripts/ 的一次性 TS 脚本。</strong> <code>bun run scripts/sync_alg.ts</code> 比 <code>tsx scripts/sync_alg.ts</code> 启动快 2-3x, 这种"跑一次就退"的脚本零侵入, 真切收益, 可以试。但收益绝对值很小 (一次省 200ms), 不到非动的程度。</p>
        <p>为什么不立刻换 — 三件事:(1) <strong>pnpm 全局硬链接 store</strong> 在 cuberoot 这种 11-package monorepo 视角下是真实收益, 几个 GB 盘省下来不是 marketing 数字。Bun 的 <code>bun install</code> 快, 但仍是每个项目各自拉一份, monorepo 数学题不利。(2) <strong>cuberoot 是纯静态 SPA + 长进程 API</strong>, 没有冷启动场景, Bun 最大的卖点对我们 ≈ 0。(3) <strong>Vite + React Router 7 + Vitest</strong> 在 "24 页 SPA + workers + WASM" 这种重客户端场景已经够好, Bun build 那条线插件生态浅一截, 换过来是<strong>侧移</strong>不是<strong>升级</strong>。</p>
        <p>真正的 ROI 拐点是什么 — 如果哪天 api server 要挪上 edge (Cloudflare Workers / Vercel Edge), 或者要开始按冷启动收钱, Bun 跟 Hono 是天然搭子;那时再换。或者哪天 pm2 + Bun 的工业级支持补到跟 Node 一档, 重启换 runtime 风险也降到位, 也可以试。在那之前 Node 22 + pm2 fork 这套不动。</p>
      </>
    ),
    en: (
      <>
        <p><strong>To be explicit up front: cuberoot.me does not depend on Bun today.</strong> The full stack runs Node 22 LTS + pnpm 10 + Vite 8 + Vitest 4 — best-in-class for each slot, with no bottleneck anywhere. This page lives in /code/stack because Bun is a <strong>reasonable future option</strong>, not a current tool — exactly the "planted flag" role /code/stack/obsidian plays.</p>
        <p>If the day comes to move on Bun, two specific places stand out:</p>
        <p>1. <strong>The Hono server at api.cuberoot.me.</strong> Hono is faster and lighter on Bun than on Node, and we're already on Hono. Switching the runtime is a one-line ecosystem.config.js change — <code>node dist/index.js</code> → <code>bun dist/index.js</code>. But pm2 + Bun still has rough edges on cluster reload / log rotation / graceful restart, and cuberoot's traffic is already comfortable on Node 22, so ROI isn't there yet.<br/>
        2. <strong>One-off TS scripts under core/scripts/.</strong> <code>bun run scripts/sync_alg.ts</code> beats <code>tsx scripts/sync_alg.ts</code> by 2-3x cold start. Zero-intrusion, real savings, worth trying. But the absolute win is tiny (~200ms per run) — not painful enough to force the change.</p>
        <p>Why not switch right now — three reasons: (1) <strong>pnpm's hard-linked global store</strong> saves real GBs on cuberoot's 11-package monorepo. <code>bun install</code> is fast, but it still pulls one copy per project; the disk math doesn't favor a monorepo. (2) <strong>cuberoot is a pure static SPA + long-lived API process</strong>; there is no cold-start scenario, so Bun's headline benefit collapses to roughly zero here. (3) <strong>Vite + React Router 7 + Vitest</strong> already fits the "24-page SPA + workers + WASM" client well; Bun build's plugin ecosystem is shallower, so a swap is a <strong>lateral move</strong>, not an <strong>upgrade</strong>.</p>
        <p>What's the actual ROI inflection — if the API server ever moves to the edge (Cloudflare Workers / Vercel Edge) or starts being billed per cold start, Bun + Hono is the natural pair, and we switch then. Or if pm2 + Bun reaches parity with the Node-side polish and the restart-the-runtime risk evaporates, that's also a green light. Until either lands, Node 22 + pm2 fork stays put.</p>
      </>
    ),
  },
  links: [
    { label: 'bun.sh', href: 'https://bun.sh' },
    { label: 'GitHub · oven-sh/bun', href: 'https://github.com/oven-sh/bun' },
    { label: 'Bun 1.0 announcement', href: 'https://bun.sh/blog/bun-v1.0' },
    { label: 'Hono on Bun', href: 'https://hono.dev/docs/getting-started/bun' },
    { label: 'Bun vs Node compat', href: 'https://bun.sh/docs/runtime/nodejs-apis' },
  ],
};
