import type { StackTool } from '../stack_tool_types';
import { k, v, s, n, f, p, c } from '../stack_tool_types';

// ─── Claude (Anthropic LLM family, current: Opus 4.7) ──────────────────────

export const CLAUDE: StackTool = {
  slug: 'claude',
  name: 'Claude',
  version: 'Opus 4.7',
  since: '2023-03',
  group: 'dev',
  accent: '#D97757',
  bright: '#E89578',
  glyph: '✦',
  floats: ['messages', 'system', 'tools', 'thinking', 'vision', 'cache_control', 'tool_use', 'tool_result', '1M ctx', 'stop_reason', 'usage', 'stream'],
  zh: {
    tagline: 'Anthropic 的对话/工具/代码 LLM',
    role: 'cuberoot.me 几乎每一行新代码的合写者。Opus 4.7 是每日驾驶, 1M 上下文整仓库能塞进一次会话。',
    heroSub: <>Anthropic 2021 年在旧金山由 Dario / Daniela Amodei 和一群前 OpenAI 研究者创立, 主线是 AI 安全研究。Claude 这一系 LLM 2023 年 3 月开放, 三年后 Opus 4.7 把上下文窗口推到 <strong>1M token</strong>, SWE-bench 全部时段领先, 是<em>代码 + 长上下文 + 工具使用</em> 这三条线同时占第一名的模型。</>,
    whatDesc: <>Claude 是一个 <strong>LLM 家族</strong>, 不是产品。家族里同代有 Haiku (小快便宜) / Sonnet (中) / Opus (大), 通过同一个 messages API 调用。和 GPT 系不同的地方在 <em>Constitutional AI</em> 训练方法、显式的 thinking 模式、原生 tool use schema 三件事。</>,
    historyDesc: <>2023 春的 Claude 1 / Instant 是带原型味的对话模型;Claude 2 (2023-07) 一口气把上下文做到 100K, 那时业界还普遍在 8K-32K;Claude 3 家族 (2024-03) 在 MMLU 短暂登顶;3.5 Sonnet (2024-06) 把代码基线抬到现在的高度。Claude 4 (2025-05) 之后是真正的 agent 模型, 直到 2026-04 Opus 4.7 把窗口拉到 1M。</>,
    conceptsTitle: 'messages + tools + thinking',
    conceptsDesc: <>API 表面其实就 <code>messages.create</code> 一个端点。复杂度全在参数:system prompt、messages 数组 (含 tool_use / tool_result block)、tools schema、thinking、cache_control、stream。理解这一组 primitive 就理解了 Claude 的全部能力。</>,
    whyDesc: <>2026 年模型选择多了, 但写代码这条线 Claude 还是第一档。原因不止是 SWE-bench 分数: <strong>thinking 模式</strong>、<strong>1M 上下文</strong>、<strong>tool use 原生 schema</strong>、<strong>prompt caching</strong> 四件事配合起来对长任务的可用性甩开了对手。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>Cursor 默认走 Claude, Cline / Roo Code / Aider 这一代 agent 工具大多以 Claude 为主力。Vercel AI SDK 出 <code>@ai-sdk/anthropic</code> 一等公民, Notion / Slack / Quora Poe / DuckDuckGo AI Chat 后端都接了 Claude。</>,
    cuberootDesc: <>本站 95%+ 的代码是和 Claude 协作写出来的。Opus 4.7 是日常 driver, Sonnet 4.6 跑批量小活。1M 上下文让一次会话能装下 <code>packages/client</code> 整个包做整体重构, 不用再切片粘贴。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>Claude 接下来一年的关键词是 <em>agent</em>: tool use schema 收敛、长 horizon 任务的 thinking 预算自动化、computer use beta 转正、prompt cache 跨会话化。Anthropic 的成本曲线决定了它对个人开发者会不会持续可负担。</>,
  },
  en: {
    tagline: "Anthropic's chat / tool-use / coding LLM",
    role: 'Co-author of nearly every new line of code on cuberoot.me. Opus 4.7 is the daily driver — the whole repo fits in one conversation at 1M context.',
    heroSub: <>Anthropic was founded in San Francisco in 2021 by Dario and Daniela Amodei with a group of ex-OpenAI researchers; the throughline is AI safety research. The Claude LLM family opened in March 2023; three years later Opus 4.7 pushes context to <strong>1M tokens</strong>, leads SWE-bench across all categories, and is the model holding first place on <em>coding + long context + tool use</em> simultaneously.</>,
    whatDesc: <>Claude is a <strong>family of LLMs</strong>, not a product. Each generation ships Haiku (small / fast / cheap), Sonnet (mid), Opus (large), all behind one messages API. What distinguishes it from GPT: the <em>Constitutional AI</em> training method, an explicit thinking mode, and a native tool-use schema.</>,
    historyDesc: <>Claude 1 / Instant in spring 2023 had prototype energy; Claude 2 (2023-07) shipped a 100K context window when 8K-32K was the industry norm; the Claude 3 family (2024-03) briefly topped MMLU; 3.5 Sonnet (2024-06) set the coding baseline still in use. Claude 4 (2025-05) was the first proper agent model, and in 2026-04 Opus 4.7 stretched the window to 1M.</>,
    conceptsTitle: 'messages + tools + thinking',
    conceptsDesc: <>The API surface is essentially one endpoint, <code>messages.create</code>. Complexity is in the parameters: system prompt, the messages array (carrying tool_use / tool_result blocks), tools schema, thinking, cache_control, stream. Understanding that primitive set is understanding Claude.</>,
    whyDesc: <>2026 has more model choices than ever, but for code Claude is still in a class of its own. It's not just SWE-bench: <strong>thinking mode</strong>, <strong>1M context</strong>, <strong>native tool-use schema</strong>, and <strong>prompt caching</strong> together make long tasks usable in ways competitors don't yet match.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Cursor defaults to Claude; the agent-tool generation — Cline, Roo Code, Aider — overwhelmingly picks Claude as the workhorse. Vercel AI SDK ships <code>@ai-sdk/anthropic</code> as a first-class adapter; Notion, Slack, Quora Poe, and DuckDuckGo AI Chat all wire Claude into their backends.</>,
    cuberootDesc: <>95%+ of this codebase was written with Claude as collaborator. Opus 4.7 is the daily driver; Sonnet 4.6 handles cheaper grunt work. The 1M window lets one session hold the entire <code>packages/client</code> for a holistic refactor — no more slice-and-paste.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>The next year's keyword is <em>agent</em>: tool-use schemas converging, automated thinking budgets for long-horizon tasks, computer-use graduating from beta, and prompt cache reaching across sessions. Anthropic's cost curve will decide whether individual devs can keep affording it.</>,
  },
  heroStats: [
    { num: '1', unit: 'M', zh: <>上下文窗口 <em>Opus 4.7 · 2026-04</em></>, en: <>context window <em>Opus 4.7 · 2026-04</em></> },
    { num: 'Opus 4.7', zh: <>当前旗舰 <em>claude-opus-4-7</em></>, en: <>current flagship <em>claude-opus-4-7</em></> },
    { num: '#1', zh: <>SWE-bench Verified <em>2026-05</em></>, en: <>SWE-bench Verified <em>2026-05</em></> },
    { num: '95', unit: '%+', zh: <>本仓库 LoC 协作产出 <em>cuberoot.me</em></>, en: <>of LoC in this repo co-authored <em>cuberoot.me</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>Anthropic 2021 年在旧金山由 Dario 和 Daniela Amodei 牵头, 带着一群从 OpenAI 出来的研究者成立, 早期资金来自 Google 和 Spark Capital, 后来 Amazon 注资约 40 亿美元。公司主线是 <em>AI 安全研究</em> —— Constitutional AI 这套方法的目标是让模型可以"自我批评"地拒绝不安全输出, 而不是靠人工每条标注。Claude 这个名字致敬 Claude Shannon。</p>
        <p>2023 年 3 月 Claude 1 + Claude Instant 私测开放, 那年夏天的 Claude 2 一口气把上下文做到 100K, 在 GPT-4 还停留在 8K / 32K 的时代直接拉了一个数量级。2024 年 3 月的 Claude 3 家族 (Haiku / Sonnet / Opus) 第一次在 MMLU 短暂超过 GPT-4, 同年 6 月 3.5 Sonnet + Artifacts 把代码生成的基线再抬一档。</p>
        <p>真正的 agent 时代是 2025-05 的 Claude 4 —— 那一版开始 tool use schema 稳定下来, 多步任务的 reliability 终于可用。之后 4.1 / 4.5 / 4.6 一路把 agent loop 中的失败模式磨平, 2026-04 Opus 4.7 把上下文窗口推到 1M (从此前的 200K 上去五倍), 同时把 SWE-bench Verified 守住第一。这是当前每天写本仓库代码的那个模型。</p>
      </>
    ),
    en: (
      <>
        <p>Anthropic was founded in San Francisco in 2021 by Dario and Daniela Amodei together with a group of ex-OpenAI researchers, with early funding from Google and Spark Capital and later ~$4B from Amazon. The throughline is <em>AI safety research</em> — Constitutional AI lets a model self-critique refusals rather than relying on per-example human labels. The name nods to Claude Shannon.</p>
        <p>Claude 1 + Claude Instant opened in private beta in March 2023; that summer's Claude 2 shipped a 100K context window — an order of magnitude over GPT-4's then-8K / 32K. The Claude 3 family (Haiku / Sonnet / Opus) in March 2024 briefly topped MMLU above GPT-4; June 2024's 3.5 Sonnet plus Artifacts raised the code-generation baseline a level higher.</p>
        <p>The proper agent era began with Claude 4 in May 2025: the tool-use schema stabilized, and multi-step reliability finally became usable. 4.1 / 4.5 / 4.6 ground down failure modes in the agent loop; in 2026-04 Opus 4.7 took the context window to 1M (5× the prior 200K) while holding first place on SWE-bench Verified. That is the model writing code in this repo today.</p>
      </>
    ),
  },
  history: [
    { year: '2021', zh: { title: <>Anthropic 成立</>, desc: <>Dario / Daniela Amodei 带一批前 OpenAI 研究者在旧金山立项。早期方向:Constitutional AI, 用模型自批评代替每例人工标注。</> }, en: { title: <>Anthropic founded</>, desc: <>Dario and Daniela Amodei with a group of ex-OpenAI researchers set up shop in San Francisco. Early thesis: Constitutional AI — model self-critique in place of per-example human labels.</> } },
    { year: '2023·03', zh: { title: <>Claude 1 + Instant</>, desc: <>第一代 Claude 私测放开, Instant 主打便宜快, Claude 1 主打对齐质量。那年 LLM 圈刚被 GPT-4 震完, Claude 是少数能跟它隔空对话的。</> }, en: { title: <>Claude 1 + Instant</>, desc: <>The first generation opens in private beta. Instant focuses on cheap / fast, Claude 1 on alignment quality. In a year still ringing from GPT-4's release, Claude is one of the few peers in the conversation.</> } },
    { year: '2023·07', zh: { title: <>Claude 2 — 100K context</>, desc: <>一口气把上下文窗口做到 100K token, 业界普遍还停在 8K-32K。整本书塞进 prompt 第一次变得日常, RAG 设计因此被重画。</> }, en: { title: <>Claude 2 — 100K context</>, desc: <>The context window jumps to 100K tokens while the industry still sits at 8K-32K. "Stuff the whole book into the prompt" becomes routine; RAG architectures get redrawn.</> } },
    { year: '2024·03', zh: { title: <>Claude 3 (Haiku / Sonnet / Opus)</>, desc: <>第一次出现三档同代家族。Opus 在 MMLU 短暂登顶 GPT-4, Sonnet 性价比第一, Haiku 是当时最快的能力级模型。</> }, en: { title: <>Claude 3 (Haiku / Sonnet / Opus)</>, desc: <>The first tri-tier family in one generation. Opus briefly tops MMLU over GPT-4, Sonnet leads on price/perf, Haiku is the fastest capable model at the time.</> } },
    { year: '2024·06', zh: { title: <>3.5 Sonnet + Artifacts</>, desc: <>代码生成基线抬一档, Artifacts 让对话产出的 React / HTML 直接侧栏渲染。这一版是大部分人第一次觉得 LLM "真能写代码"。</> }, en: { title: <>3.5 Sonnet + Artifacts</>, desc: <>Coding baseline takes another step up; Artifacts renders chat-generated React / HTML in a side pane. This release is when most users first felt LLMs could "actually code."</> } },
    { year: '2024·10', zh: { title: <>3.5 Sonnet (new) + computer use</>, desc: <>同版本号下迭代权重, 加 computer use beta —— 模型直接读屏幕 / 控制鼠标键盘。这是 agent 路线第一次原生集成进 API。</> }, en: { title: <>3.5 Sonnet (new) + computer use</>, desc: <>Same version number, refreshed weights; computer use beta lets the model read the screen and control mouse / keyboard. First native integration of the agent path into the API.</> } },
    { year: '2025·02', zh: { title: <>3.7 Sonnet — thinking 模式</>, desc: <>显式 thinking 参数:让模型把推理链放到一个独立 block, 用户可选 budget。"花更多 token 想得更深" 第一次变成一个 API 旋钮。</> }, en: { title: <>3.7 Sonnet — thinking mode</>, desc: <>An explicit thinking parameter; the model puts its reasoning chain into a dedicated block with a user-set budget. "Spend more tokens to think harder" becomes a literal API knob.</> } },
    { year: '2025·05', zh: { title: <>Claude 4 家族</>, desc: <>Opus 4 / Sonnet 4。代码与 agent 能力大跨步, 长 horizon 任务的可靠性第一次跨过"能用"的门槛。同期 Claude Code CLI 上线。</> }, en: { title: <>Claude 4 family</>, desc: <>Opus 4 / Sonnet 4. A major leap on coding and agent capability — long-horizon tasks cross the "actually usable" threshold for the first time. Claude Code CLI ships alongside.</> } },
    { year: '2025·08', zh: { title: <>Opus 4.1</>, desc: <>4.1 强化 agent 与 tool use, 失败模式 (循环、错调、放弃) 普遍降低。模型开始能可靠跑 5 - 10 步的 agent loop。</> }, en: { title: <>Opus 4.1</>, desc: <>4.1 strengthens agent / tool use; common failure modes (loops, wrong calls, premature give-ups) drop. Models can reliably run 5- to 10-step agent loops.</> } },
    { year: '2025·09', zh: { title: <>Sonnet 4.5 / Opus 4.5</>, desc: <>同代再迭代, 把 prompt caching 推向稳定。5 分钟 TTL 的 cache 让 system prompt + 文档前缀的 cost 降到 1/10。</> }, en: { title: <>Sonnet 4.5 / Opus 4.5</>, desc: <>An in-generation iteration that stabilizes prompt caching. The 5-minute TTL cache drops the cost of a long system prompt + doc prefix by ~10×.</> } },
    { year: '2025·10', zh: { title: <>Sonnet 4.6</>, desc: <>Sonnet 这条线继续推进, 性价比再上一档, 代码任务上和上一代 Opus 接近。日常 grunt work 改用 4.6, 留 Opus 给重活。</> }, en: { title: <>Sonnet 4.6</>, desc: <>The Sonnet line pushes further: price/perf rises another step and matches the previous Opus on coding tasks. Daily grunt work shifts to 4.6 while Opus is reserved for heavy lifting.</> } },
    { year: '2026·01', zh: { title: <>Haiku 4.5 / Opus 4.6</>, desc: <>扩展上下文与多模态稳定化, 视觉输入质量补齐。这一版让 "便宜小模型 + 长 prompt" 的产品变得现实。</> }, en: { title: <>Haiku 4.5 / Opus 4.6</>, desc: <>Extended context and matured multimodality; vision input quality catches up. Makes "cheap small model + long prompt" a real product configuration.</> } },
    { year: '2026·04', highlight: true, zh: { title: <>Opus 4.7 — 1M 上下文</>, desc: <>上下文窗口从 200K 直接拉到 1M token, 五倍。整个中等规模仓库 (包括本仓库) 能塞进单次会话。SWE-bench Verified 同步保持第一。</> }, en: { title: <>Opus 4.7 — 1M context</>, desc: <>The context window goes from 200K to 1M tokens — 5×. An entire mid-size repo (this one included) fits in one conversation. SWE-bench Verified stays at #1.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>当前 — Opus 4.7 daily driver</>, desc: <>本站当前 default 模型即 claude-opus-4-7。Sonnet 4.6 跑批量小活, Haiku 4.5 跑分类与小工具。这页就是 Opus 4.7 写的。</> }, en: { title: <>Now — Opus 4.7 daily driver</>, desc: <>This site's current default is claude-opus-4-7. Sonnet 4.6 covers batch grunt work, Haiku 4.5 handles classification and small utilities. This very page was written by Opus 4.7.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>messages.create 基本调用</>, desc: <>所有 Claude 调用都收敛到一个端点。最少参数:model + messages + max_tokens。</> }, en: { title: <>messages.create — the basic call</>, desc: <>Every Claude request collapses to one endpoint. Minimum parameters: model + messages + max_tokens.</> }, code: <code>{k('const')} {v('r')} = {k('await')} {v('anthropic')}.{v('messages')}.{f('create')}({'{'}{'\n'}  {p('model')}: {s('"claude-opus-4-7"')},{'\n'}  {p('max_tokens')}: {n('4096')},{'\n'}  {p('messages')}: [{'\n'}    {'{'} {p('role')}: {s('"user"')}, {p('content')}: {s('"hello"')} {'}'}{'\n'}  ],{'\n'}{'}'});</code> },
    { tag: 'B', zh: { title: <>system + 多轮 messages</>, desc: <>system 是单独一个 top-level 参数 (不在 messages 里)。messages 永远 user / assistant 交替。</> }, en: { title: <>system + multi-turn messages</>, desc: <>system is a separate top-level parameter (not inside messages). The messages array must alternate user / assistant.</> }, code: <code>{f('create')}({'{'}{'\n'}  {p('model')}: {s('"claude-opus-4-7"')},{'\n'}  {p('system')}: {s('"You are a code reviewer."')},{'\n'}  {p('messages')}: [{'\n'}    {'{'} {p('role')}: {s('"user"')}, {p('content')}: {v('q1')} {'},'}{'\n'}    {'{'} {p('role')}: {s('"assistant"')}, {p('content')}: {v('a1')} {'},'}{'\n'}    {'{'} {p('role')}: {s('"user"')}, {p('content')}: {v('q2')} {'}'}{'\n'}  ],{'\n'}{'}'});</code> },
    { tag: 'C', zh: { title: <>tool use schema</>, desc: <>原生 tool 定义:name + description + input_schema (JSON Schema)。模型回 <code>tool_use</code> block, 调用方回 <code>tool_result</code> 接回循环。</> }, en: { title: <>Tool-use schema</>, desc: <>Native tool definitions: name + description + input_schema (JSON Schema). The model emits a <code>tool_use</code> block; the caller replies with a <code>tool_result</code> to continue the loop.</> }, code: <code>{p('tools')}: [{'{'}{'\n'}  {p('name')}: {s('"read_file"')},{'\n'}  {p('description')}: {s('"Read file contents"')},{'\n'}  {p('input_schema')}: {'{'}{'\n'}    {p('type')}: {s('"object"')},{'\n'}    {p('properties')}: {'{ '}{p('path')}: {'{ '}{p('type')}: {s('"string"')} {'} }'},{'\n'}    {p('required')}: [{s('"path"')}]{'\n'}  {'}'}{'\n'}{'}'}]</code> },
    { tag: 'D', zh: { title: <>extended thinking</>, desc: <>4.x 起加 <code>thinking</code> 参数:模型把推理链放进独立 block, 用户给一个 budget_tokens 上限。复杂数学 / 多步规划场景显著提分。</> }, en: { title: <>Extended thinking</>, desc: <>From 4.x onward, the <code>thinking</code> parameter routes the reasoning chain into a dedicated block with a budget_tokens cap. Substantially lifts results on complex math and multi-step planning.</> }, code: <code>{f('create')}({'{'}{'\n'}  {p('model')}: {s('"claude-opus-4-7"')},{'\n'}  {p('thinking')}: {'{'}{'\n'}    {p('type')}: {s('"enabled"')},{'\n'}    {p('budget_tokens')}: {n('10000')}{'\n'}  {'},'}{'\n'}  {p('messages')}: [...]{'\n'}{'}'});</code> },
    { tag: 'E', zh: { title: <>vision 输入</>, desc: <>content 里塞一个 image block (base64 或 URL)。Opus 4.x 的视觉能力够看截图 / 图表 / 手写公式。本站的 mosaic / scramble 调试图都靠它分析。</> }, en: { title: <>Vision input</>, desc: <>Drop an image block into content (base64 or URL). Opus 4.x's vision is solid on screenshots, charts, hand-drawn math. The mosaic / scramble debugging images on this site are analyzed through it.</> }, code: <code>{p('content')}: [{'\n'}  {'{ '}{p('type')}: {s('"image"')},{'\n'}    {p('source')}: {'{'} {p('type')}: {s('"base64"')}, {p('media_type')}: {s('"image/png"')}, {p('data')}: {v('b64')} {'} },'}{'\n'}  {'{ '}{p('type')}: {s('"text"')}, {p('text')}: {s('"What is wrong here?"')} {'}'}{'\n'}]</code> },
    { tag: 'F', zh: { title: <>prompt caching</>, desc: <>给 system 或 messages 里的 block 加 <code>cache_control: {'{ type: "ephemeral" }'}</code>, 5 分钟 TTL, 命中后 cost / 延迟 ~10%。长文档 + 多轮调用必用。</> }, en: { title: <>Prompt caching</>, desc: <>Attach <code>cache_control: {'{ type: "ephemeral" }'}</code> to a system or content block; 5-minute TTL, hits run at ~10% of normal cost / latency. Mandatory for long docs + many turns.</> }, code: <code>{p('system')}: [{'{'}{'\n'}  {p('type')}: {s('"text"')},{'\n'}  {p('text')}: {v('LONG_DOCS')},{'\n'}  {p('cache_control')}: {'{ '}{p('type')}: {s('"ephemeral"')} {'}'}{'\n'}{'}'}]</code> },
    { tag: 'G', zh: { title: <>streaming</>, desc: <>SSE 流式响应。delta event 推 text chunk, 客户端打字机效果就靠它。tool_use block 同样会流出, 边到边解析。</> }, en: { title: <>Streaming</>, desc: <>SSE-style streaming responses. Delta events deliver text chunks for the typewriter feel; tool_use blocks stream the same way and can be parsed on the fly.</> }, code: <code>{k('const')} {v('stream')} = {v('anthropic')}.{v('messages')}.{f('stream')}({'{ ... }'});{'\n'}{k('for')} {k('await')} ({k('const')} {v('ev')} {k('of')} {v('stream')}) {'{'}{'\n'}  {k('if')} ({v('ev')}.type === {s('"content_block_delta"')}){'\n'}    {v('process')}.{v('stdout')}.{f('write')}({v('ev')}.delta.text);{'\n'}{'}'}</code> },
    { tag: 'H', zh: { title: <>agent loop</>, desc: <>tool_use → 执行 → tool_result → 再 create。直到 stop_reason === <code>"end_turn"</code>。Claude Code 内核就是这个 loop, 加超时 + 权限。</> }, en: { title: <>Agent loop</>, desc: <>tool_use → execute → tool_result → call again. Continue until stop_reason === <code>"end_turn"</code>. Claude Code's core is exactly this loop, plus timeouts and permissions.</> }, code: <code>{k('while')} ({v('r')}.stop_reason === {s('"tool_use"')}) {'{'}{'\n'}  {k('const')} {v('out')} = {f('runTool')}({v('r')}.content);{'\n'}  {v('r')} = {k('await')} {f('create')}({'{ '}{p('messages')}: [...{v('msgs')}, {v('out')}] {'}'});{'\n'}{'}'}</code> },
  ],
  whyCards: [
    { icon: '✦', zh: { title: <>代码这条线还是第一档</>, desc: <>SWE-bench Verified 上 Opus 4.7 持续守住榜首, 实际写大型 codebase 时 GPT / Gemini 同代都有可感知的差距。</> }, en: { title: <>Still tier-1 on code</>, desc: <>Opus 4.7 holds first on SWE-bench Verified. Working in a large codebase, the gap to same-generation GPT / Gemini is perceptible day to day.</> }, code: <>{c('// SWE-bench Verified')}{'\n'}{c('// 1. Opus 4.7')}</> },
    { icon: '⌬', zh: { title: <>1M 上下文是质变</>, desc: <>200K → 1M 不只是数字。整个 cuberoot.me <code>packages/client</code> 包(约 60K LoC)能进一次会话, 做整库改名 / 重构不丢上下文。</> }, en: { title: <>1M context is a step change</>, desc: <>200K → 1M is not just a number. The whole <code>packages/client</code> on cuberoot.me (~60K LoC) fits in one session, so repo-wide refactors / renames keep context throughout.</> }, code: <>{p('max_input_tokens')}: {n('1000000')}</> },
    { icon: '⚙', zh: { title: <>tool use 原生 schema</>, desc: <>JSON Schema 定义工具, 模型自己产生合法的 tool_use call。对比"prompt 里写 function 说明 + 解析返回字符串"那种 hack, 错误率低一个数量级。</> }, en: { title: <>Native tool-use schema</>, desc: <>Tools are JSON-Schema-defined; the model emits valid tool_use calls directly. Versus the "describe a function in prompt and parse a string back" hack, error rates drop by an order of magnitude.</> }, code: <>{p('tools')}: [{'{ '}{p('name')}, {p('input_schema')} {'}'}]</> },
    { icon: '⌁', zh: { title: <>thinking 是可控旋钮</>, desc: <>不是隐式 reasoning 黑盒, 是显式参数。<code>budget_tokens: 50000</code> = "想得很深", 普通对话留 0。同一模型一键切档。</> }, en: { title: <>Thinking is a real knob</>, desc: <>Not a hidden reasoning black box — an explicit parameter. <code>budget_tokens: 50000</code> means "think hard"; everyday chat sets 0. One model, one toggle.</> }, code: <>{p('thinking')}: {'{ '}{p('budget_tokens')}: {n('50000')} {'}'}</> },
    { icon: '⛁', zh: { title: <>prompt cache 真省钱</>, desc: <>5 分钟 TTL 的 cache 命中后 token cost 降到 ~10%。长 system + 多轮调用场景 (Claude Code) 实测能把账单砍 70%+。</> }, en: { title: <>Prompt cache actually saves money</>, desc: <>A 5-minute-TTL cache hit drops token cost to ~10%. For long-system + multi-turn workloads (Claude Code), bills routinely drop by 70%+.</> }, code: <>{p('cache_control')}: {'{ '}{p('type')}: {s('"ephemeral"')} {'}'}</> },
    { icon: '⌖', zh: { title: <>视觉够用了</>, desc: <>Opus 4.x 的视觉对截图 / 图表 / 手写公式都够用。本站 debug 比对图都丢给它分析, 比自己肉眼看快十倍。</> }, en: { title: <>Vision is good enough</>, desc: <>Opus 4.x reads screenshots, charts, hand-drawn math reliably. Throw the debugging comparison shots from this site at it; it's 10× faster than eyeballing.</> }, code: <>{p('type')}: {s('"image"')}, {p('source')}: {'{ '}{p('type')}: {s('"base64"')} {'}'}</> },
    { icon: '⌗', zh: { title: <>Constitutional AI 拒绝得"讲道理"</>, desc: <>拒答时给原则、给替代方案, 而不是 boilerplate 一刀切。日常协作里这种"不爱抬杠"的属性能减少很多内耗。</> }, en: { title: <>Constitutional AI refuses sensibly</>, desc: <>When refusing, it cites a principle and offers an alternative — not a boilerplate one-liner. Day-to-day this "low-friction" trait cuts a surprising amount of waste.</> }, code: <>{c('// principled refusal,')}{'\n'}{c('// not boilerplate "I can\'t"')}</> },
    { icon: '⏚', zh: { title: <>SDK + API 稳</>, desc: <>@anthropic-ai/sdk 三年来 API 几乎没破坏过。tool use / thinking / cache 都是加参数, 不是改方法签名。代码迁移成本极低。</> }, en: { title: <>SDK + API stay stable</>, desc: <>@anthropic-ai/sdk has barely broken its API in three years. Tool use / thinking / caching all arrived as additional parameters, not method-signature changes. Migration cost is near zero.</> }, code: <>{k('import')} {v('Anthropic')} {k('from')} {s('"@anthropic-ai/sdk"')};</> },
    { icon: '⚐', zh: { title: <>贵, 但价格曲线在下</>, desc: <>Opus 4.7 比 GPT 同档贵 ~30%, Sonnet 价位最近一年同期下滑 ~40%。"用 Opus 想 + Sonnet 干" 的混合策略让人均月成本可控。</> }, en: { title: <>Expensive — but the curve is bending</>, desc: <>Opus 4.7 runs ~30% above its GPT peer, while Sonnet has dropped ~40% over the last year. "Plan with Opus, execute with Sonnet" keeps the per-user monthly cost manageable.</> }, code: <>{c('// 1k tok @ Opus 4.7: $15')}{'\n'}{c('// 1k tok @ Sonnet 4.6: $3')}</> },
  ],
  adopters: [
    { name: 'Anthropic Console', href: 'https://console.anthropic.com', highlight: true, zhNote: '官方控制台 / playground / billing', enNote: 'Official console / playground / billing' },
    { name: 'Cursor', href: 'https://cursor.com', highlight: true, zhNote: 'AI IDE 默认模型走 Claude', enNote: 'AI IDE — defaults to Claude' },
    { name: 'Cline', href: 'https://cline.bot', highlight: true, zhNote: 'VS Code agent extension, Claude 主力', enNote: 'VS Code agent extension; Claude as workhorse' },
    { name: 'Vercel AI SDK', href: 'https://sdk.vercel.ai', highlight: true, zhNote: '@ai-sdk/anthropic 官方一等公民', enNote: '@ai-sdk/anthropic — first-class adapter' },
    { name: 'Aider', href: 'https://aider.chat', zhNote: 'CLI pair-programming, 支持 Claude', enNote: 'CLI pair-programmer with Claude support' },
    { name: 'Roo Code', href: 'https://roocode.com', zhNote: 'Cline fork, 多角色 agent', enNote: 'Cline fork with multi-persona agents' },
    { name: 'Lovable', href: 'https://lovable.dev', zhNote: 'AI 网站生成器, 接 Claude', enNote: 'AI website builder backed by Claude' },
    { name: 'Replit Agent', href: 'https://replit.com', zhNote: '在线 IDE agent 走 Claude', enNote: 'Online IDE agent on Claude' },
    { name: 'Notion AI', href: 'https://notion.so', zhNote: '文档辅助接 Claude (多模型混合)', enNote: 'Docs assistant on Claude (mixed-model)' },
    { name: 'Slack AI', href: 'https://slack.com', zhNote: '摘要 / 翻译 / 检索后端', enNote: 'Summarize / translate / search backend' },
    { name: 'Quora Poe', href: 'https://poe.com', zhNote: '多 LLM 聚合, Claude 是常驻一档', enNote: 'Multi-LLM aggregator; Claude is permanently featured' },
    { name: 'DuckDuckGo AI Chat', href: 'https://duck.ai', zhNote: '匿名免登录 Claude 入口', enNote: 'Anonymous no-login Claude entry' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 95%+ 代码由 Opus 4.7 协作产出', enNote: '95%+ of LoC on this site co-authored by Opus 4.7' },
  ],
  outlook: [
    { tag: <>HOT · 2026-04</>, hot: true, big: true, zh: { title: <>1M 上下文改变工作流</>, body: <><p>从 200K 到 1M 不是简单的五倍。在 200K 时代写代码, 你要不断帮模型筛选哪些文件该读;到 1M, 中型仓库整个塞进会话是可行的。本仓库 <code>packages/client</code> 全部 .ts/.tsx + 关键 .css 加起来 ~70 万 token, 一次塞入还有余量。</p><p>这件事的二阶效应是 <strong>"全局重构"</strong> 这类原本对 AI 不友好的任务变得可达 —— 改一个数据 schema 涉及 12 个文件, 模型一次看全, 不再因为窗口边界遗漏。</p></> }, en: { title: <>1M context changes the workflow</>, body: <><p>200K → 1M is not a simple 5×. At 200K you spent prompts curating which files the model could see; at 1M, a mid-size repo fits whole. The cuberoot.me <code>packages/client</code> .ts/.tsx + key .css totals ~700K tokens — single-shot insertion with headroom.</p><p>The second-order effect: <strong>repo-wide refactors</strong> — long the bane of AI-assisted coding — become tractable. Change a data schema touching twelve files; the model sees them all at once and stops dropping context at the window edge.</p></> } },
    { tag: 'AGENT', zh: { title: <>Agent loop 从能跑到可信</>, body: <><p>4 系开始 agent loop 进入"能跑"档, 4.x 之后逐步进"可信"档:5 - 20 步任务里循环 / 错调用 / 提前放弃这些失败模式都在快速下降。配合 Claude Code 的 hooks + permission, 用户可以放心让 agent 跑十几分钟。</p></> }, en: { title: <>Agent loops from runnable to trustworthy</>, body: <><p>Series 4 brought the agent loop into "it runs" territory; 4.x has been moving it into "it's trustworthy": loops, miscalls, and premature give-ups in 5- to 20-step tasks drop steadily. With Claude Code's hooks + permission gating, letting the agent run unattended for tens of minutes feels safe.</p></> } },
    { tag: 'COMPUTER', zh: { title: <>computer use 走出 beta</>, body: <><p>2024-10 的 computer use beta 经过一年半磨合, 在 4.7 这一代失败率落到一个真能交付的区间。让模型直接操作浏览器 / 编辑器, 不再需要为每个 web app 写一遍 tool wrapper。</p></> }, en: { title: <>Computer use beyond beta</>, body: <><p>The 2024-10 computer-use beta has had eighteen months of polish; by 4.7 the failure rate has dropped into a deliverable range. Models drive the browser / editor directly — no per-web-app tool wrapper.</p></> } },
    { tag: <>COST</>, zh: { title: <>价格曲线还能压</>, body: <><p>Opus 同代价位过去两年没怎么动, 但 Sonnet 同期下了约 40%, Haiku 更激进。"Opus 想 + Sonnet 干 + Haiku 收尾" 的三档分配让本站每月模型支出维持在 $200 量级。</p></> }, en: { title: <>The price curve keeps bending</>, body: <><p>Opus's same-tier pricing has held steady for two years, while Sonnet has dropped ~40% and Haiku has dropped further. A three-tier "Opus thinks, Sonnet works, Haiku finishes" allocation keeps this site's monthly model spend on the order of $200.</p></> } },
    { tag: <>RISK</>, zh: { title: <>Anthropic 的护城河 vs 开源逼近</>, body: <><p>2026 年 Qwen / DeepSeek / Llama 4 在通用 benchmark 上已经摸到 Claude 同代膝盖。Claude 的护城河还在 (1) 工具使用质量、(2) 长上下文稳定性、(3) 安全对齐。但开源追赶速度比预期快, 两年内可能不再有一个差距明显的"Claude only" 任务。</p></> }, en: { title: <>Anthropic's moat vs. the open chase</>, body: <><p>By 2026 Qwen / DeepSeek / Llama 4 have reached the knees of same-generation Claude on general benchmarks. The remaining moat sits at (1) tool-use quality, (2) long-context stability, and (3) safety alignment. Open-source is catching up faster than predicted — within two years there may be no task where "only Claude works."</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>cuberoot.me 这个仓库的代码 95% 以上是和 Claude 协作写出来的。早期 (2024 年) 是 3.5 Sonnet 一档主力, 2025-05 切到 Claude 4, 2026-04 起就是 Opus 4.7。Sonnet 4.6 留给批量小任务 (重命名、注释翻译、CSS 调色), Opus 4.7 跑架构 / 重型重构 / debug / 写文档这种需要长链路推理的活。</p>
        <p>1M 上下文是 2026 年最大的工作流变化。在 200K 时代, 每次任务都要先 grep + Read 几个相关文件凑出 prompt;到 Opus 4.7 之后, 整个 <code>packages/client</code> 的 .ts/.tsx + 关键 .css 加 CLAUDE.md + memory 全部塞进一次会话还有余量, 全局重命名 / data schema 大改这种任务终于不丢上下文。</p>
        <p>本站后端 (<code>packages/server</code>) 还集成了 Anthropic SDK 作为后续可选能力的预埋 —— 目前还没有一个直接调 Claude API 的工具页 (本站的 LLM 调用都发生在 Claude Code 这一侧, 不是 cuberoot.me 站点本身), 但 <code>@anthropic-ai/sdk</code> 已经在 dep tree 里, prompt caching + thinking 都已经验证过。</p>
        <p>付费层面用 Anthropic Pro 月费档配合 Claude Code 的 fast 模式 —— 一个月 5 美刀附送的 Sonnet / Haiku quota 加 Opus on-demand。重活按 token 走 API key (本站这个 /code/stack 子页就是一个 5 subagent 并行写、Opus 4.7 调度的实例)。</p>
      </>
    ),
    en: (
      <>
        <p>95%+ of the code in this repo was authored with Claude as collaborator. Early on (2024) the workhorse was 3.5 Sonnet; in May 2025 it shifted to Claude 4; since April 2026 it's been Opus 4.7. Sonnet 4.6 handles batch chores (renames, comment translation, CSS recoloring), while Opus 4.7 takes architecture / heavy refactors / debugging / docs — anything needing long-horizon reasoning.</p>
        <p>1M context is the single biggest workflow change of 2026. At 200K, every task started with grep + Read across a handful of files to assemble a prompt. With Opus 4.7, the entire <code>packages/client</code> .ts/.tsx + key .css plus CLAUDE.md + memory all fit in one session with headroom — repo-wide renames and data-schema overhauls finally don't drop context.</p>
        <p>The backend (<code>packages/server</code>) also vendors the Anthropic SDK as a forward-compatible base — there is no tool page yet that calls the Claude API directly (LLM calls on this project live on the Claude Code side, not in the cuberoot.me site itself), but <code>@anthropic-ai/sdk</code> is already in the dep tree, with prompt caching + thinking proved out.</p>
        <p>On billing: an Anthropic Pro monthly tier pairs with Claude Code's fast mode — the included Sonnet / Haiku quota plus on-demand Opus covers most days. Heavy lifting goes through an API key on token-metered usage (this /code/stack sub-page itself was generated by five subagents in parallel, scheduled by Opus 4.7).</p>
      </>
    ),
  },
  links: [
    { label: 'anthropic.com', href: 'https://www.anthropic.com' },
    { label: 'docs.anthropic.com', href: 'https://docs.anthropic.com' },
    { label: 'Opus 4.7 model card', href: 'https://www.anthropic.com/news/claude-opus-4-7' },
    { label: 'Anthropic SDK · npm', href: 'https://www.npmjs.com/package/@anthropic-ai/sdk' },
  ],
};

export default CLAUDE;
