import type { StackTool } from '../stack_tool_types';
import { k, v, s, f, p, c } from '../stack_tool_types';

// ─── Monorepo (pattern, not a single tool) ──────────────────────────────────

export const MONOREPO: StackTool = {
  slug: 'monorepo',
  name: 'Monorepo',
  version: 'pnpm 10 + Turbo 2',
  since: '~2003',
  group: 'dev',
  accent: '#0D9488',
  bright: '#14B8A6',
  glyph: '⌑',
  floats: ['workspaces', 'pnpm-workspace.yaml', 'tsconfig.references', 'Turbo', 'hoisted node_modules', '--filter', 'shared types', 'lockfile', 'monolith ≠ monorepo', 'Bazel', 'Nx', 'Lerna RIP'],
  zh: {
    tagline: '一个仓库,多个包,一份 lockfile',
    role: '5 个 workspace (client / server / shared / stats-build / stats-ui), 一份 pnpm-lock, Turbo cache, 一个 CI workflow。',
    heroSub: <>Monorepo 不是软件, 是一种<strong>组织选择</strong>:一个仓库装多个互相依赖的包, 共用 lockfile / CI / 工具链。Google 把它做到 2B+ LOC 同根树, JS 圈 2015 年才有 Lerna 第一次喊出"monorepo"。十年后, pnpm workspaces + Turbo 几乎是新项目的默认骨架。cuberoot.me 5 个 workspace 跑了 18 个月没拆。</>,
    whatDesc: <>Monorepo 不是 monolith。monolith 是<strong>一个进程</strong>什么都做, monorepo 是<strong>一个仓库</strong>装多个独立可发布的包。重点在<em>仓库</em>那一层共享 (lockfile / CI / 类型 / 工具链), 不在运行时强耦合。这条边界搞清楚, 后面所有 trade-off 才讲得通。</>,
    historyDesc: <>从 Bell Labs / IBM 时代起内部代码本来就堆在一棵树里;只是没人这么叫。真正把"monorepo"做成方法论的是 Google (Piper)、Facebook (用 Mercurial 改造扛 1.3M 文件)。JS 生态是迟到者:2015 年 Lerna 第一次喊出口号, 2017 年 Yarn workspaces 把它原生化, 2019 年 pnpm workspaces 用硬链接重塑, 2021 年 Turbo / Nx 把 CI cache 做到亚秒级。</>,
    conceptsTitle: 'Workspace + 任务图 + 共享类型',
    conceptsDesc: <>JS monorepo 的可观察 surface 其实小:一份 <code>pnpm-workspace.yaml</code> 声明包, 一份 <code>turbo.json</code> 编排任务, 一份 <code>pnpm-lock.yaml</code> 锁版本, 各包 <code>tsconfig.json</code> 用 references 串编译图。剩下的复杂度都在内部。</>,
    whyDesc: <>2026 年还选 monorepo (而不是一堆独立 git repo + submodule), 不是因为"代码放一起感觉好", 而是<strong>跨包重构原子化</strong>、<strong>类型即合同</strong>、<strong>CI 只跑改动到的包</strong>这三件实事。也有真实代价:lockfile churn 大、新人 onboarding 多一步、并发提交容易撞 lockfile。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>Google 全公司一个 monorepo (Piper, 2B+ LOC), Meta 把 Mercurial 改造扛 1.3M 文件, Microsoft 用 1ES + Office 内部 monorepo。开源侧:React / Vue / Babel / Next.js 自己的仓库全部是 monorepo, Anthropic / Vercel / Stripe SDK 也都是。</>,
    cuberootDesc: <>本仓库 <code>core/</code> 是经典 5-package pnpm + Turbo monorepo:client / server / shared / stats-build / stats-ui (另外还有 6 个支撑包)。一份 lockfile, 一份 tsconfig.references, 一个 GitHub Actions workflow, 跑了 18 个月没拆。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>tsc references + Turbo cache 把增量重建压到秒级。Nx Cloud / Turbo Remote Cache 让 CI 跨机器共享 build 产物。"polyrepo + git submodule" 在新项目里几乎绝迹。下一站是 SBOM / supply-chain attestation 在 monorepo 天然容易做 — 一棵树一份 manifest。</>,
  },
  en: {
    tagline: 'One repo, many packages, one lockfile',
    role: 'Five workspaces (client / server / shared / stats-build / stats-ui), one pnpm-lock, Turbo cache, one CI workflow.',
    heroSub: <>Monorepo is not software — it's an <strong>organizational choice</strong>: one repository holds many interdependent packages sharing lockfile / CI / tooling. Google ran 2B+ LoC under a single root; the JS world only got the word in 2015 with Lerna. A decade later, pnpm workspaces + Turbo is the default skeleton for new projects. cuberoot.me has run a 5-workspace tree for 18 months without splitting.</>,
    whatDesc: <>Monorepo ≠ monolith. A monolith is <strong>one process</strong> doing everything; a monorepo is <strong>one repository</strong> housing many independently-publishable packages. Sharing happens at the <em>repository</em> layer (lockfile / CI / types / tooling) — not at runtime. Get this boundary right and every trade-off downstream makes sense.</>,
    historyDesc: <>Big internal trees have existed since Bell Labs / IBM; nobody called them "monorepo." Google (Piper) and Facebook (Mercurial scaled to 1.3M files) made it a real methodology. JS arrived late: Lerna coined the term in 2015, Yarn workspaces (2017) made it native, pnpm workspaces (2019) rebuilt it on hard links, Turbo / Nx (2021) drove CI cache to sub-second.</>,
    conceptsTitle: 'Workspace + task graph + shared types',
    conceptsDesc: <>The observable surface of a JS monorepo is small: one <code>pnpm-workspace.yaml</code> declares packages, one <code>turbo.json</code> orchestrates tasks, one <code>pnpm-lock.yaml</code> locks versions, each package's <code>tsconfig.json</code> threads the compile graph via references. Everything else is internal complexity.</>,
    whyDesc: <>Picking a monorepo in 2026 over a swarm of git repos + submodules isn't aesthetics — it's three concrete wins: <strong>atomic cross-package refactors</strong>, <strong>types as contracts</strong>, <strong>CI only runs what changed</strong>. Real costs too: lockfile churn, an extra onboarding step, lockfile-collision-prone parallel commits.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Google runs one company-wide monorepo (Piper, 2B+ LoC). Meta scaled Mercurial to 1.3M files. Microsoft has 1ES + the Office monorepo. Open source: React / Vue / Babel / Next.js are all monorepos themselves; Anthropic / Vercel / Stripe SDKs the same.</>,
    cuberootDesc: <>This repo's <code>core/</code> is a textbook 5-package pnpm + Turbo monorepo: client / server / shared / stats-build / stats-ui (plus six supporting packages). One lockfile, one tsconfig.references chain, one GitHub Actions workflow — 18 months without splitting.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>tsc references + Turbo cache push incremental rebuilds into the sub-second range. Nx Cloud / Turbo Remote Cache let CI share artifacts across machines. "polyrepo + git submodule" is effectively gone from new projects. Next stop: SBOM / supply-chain attestation is naturally easier in a monorepo — one tree, one manifest.</>,
  },
  heroStats: [
    { num: '5', zh: <>核心 workspace 数 <em>client / server / shared / stats-build / stats-ui</em></>, en: <>core workspaces <em>client / server / shared / stats-build / stats-ui</em></> },
    { num: '~140', unit: 'k', zh: <>跨包源码总量 (LOC) <em>client 占 ~85%</em></>, en: <>cross-package source LoC <em>client is ~85%</em></> },
    { num: '1', zh: <>共享 types 包, 零运行时 <em>@cuberoot/shared</em></>, en: <>shared types package, zero runtime <em>@cuberoot/shared</em></> },
    { num: '2B', unit: '+', zh: <>Google Piper 同根树代码量 <em>对照参考</em></>, en: <>LoC in Google's Piper monorepo <em>reference point</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>"把所有代码堆在一棵树里"是计算机刚有源码控制时的默认形态。Bell Labs / IBM 那个年代根本没"monorepo"这个词, 因为没人意识到还有别的选项。真正把它做成方法论的是 Google:2000 年代初期, Perforce 撑不住, 他们写了 Piper + Blaze (后来开源叫 Bazel), 把全公司代码塞进同一棵树, 2016 年公开数字时已经 2B+ LOC, 16k 工程师同时操作。Facebook 走的是另一条路 — 改造 Mercurial 让它扛 1.3M 文件, 2014 年的故事。</p>
        <p>JS 生态是迟到者。2015 年之前, "一个 npm 包一个 GitHub repo" 是默认审美;Babel 团队 (Sebastian McKenzie) 发现自己维护几十个互相依赖的小 repo 不堪重负, 2015 年 6 月发了 Lerna 1.0, 第一次让 JS 圈听到"monorepo"这个词。2017 年 10 月 Yarn 1.0 把 workspaces 原生化, Lerna 开始式微。2019 年 4 月 pnpm workspaces 用硬链接 + 严格布局重塑, 把"幽灵依赖"这个折磨整个生态多年的问题堵死。</p>
        <p>2021 年 12 月 Vercel 收购了 Jared Palmer 一个人写的 Turborepo, 把"任务图 + 内容寻址缓存"做到亚秒级。Nx 同期被 Nrwl 推到企业市场。到 2024 年, pnpm 9 + Turbo 2 + tsc references 基本是 JS monorepo 默认栈, 2025 年大量 SDK (Anthropic / Vercel / Stripe / Stainless 生成的) 公开 monorepo 化。2026 年 cuberoot.me 这种"几个互相依赖的包 + 共享类型"的中型项目用这套方案 18 个月没动过结构。</p>
      </>
    ),
    en: (
      <>
        <p>"Everything in one tree" was the default in the earliest source-control days — Bell Labs / IBM never had the word "monorepo" because nobody saw an alternative. Google made it a methodology: in the early 2000s, Perforce buckled, so they built Piper + Blaze (later open-sourced as Bazel) and stuffed the whole company into one tree. By the 2016 public number, it was 2B+ LoC with 16k engineers active simultaneously. Facebook took a different path — modifying Mercurial to scale to 1.3M files, around 2014.</p>
        <p>JavaScript was a latecomer. Pre-2015, "one npm package = one GitHub repo" was the default aesthetic. The Babel team (Sebastian McKenzie) found maintaining dozens of interlinked small repos unbearable and shipped Lerna 1.0 in June 2015 — the first time the JS world heard the word "monorepo." Yarn 1.0 (October 2017) made workspaces native and Lerna started fading. pnpm workspaces (April 2019) rebuilt it on hard links + strict layout, blocking the phantom-dependency disease that plagued the ecosystem for years.</p>
        <p>December 2021, Vercel acquired Jared Palmer's solo-built Turborepo and pushed "task graph + content-addressed cache" into sub-second territory. Nx, from Nrwl, climbed the enterprise side in parallel. By 2024, pnpm 9 + Turbo 2 + tsc references was the default JS monorepo stack; by 2025, a wave of SDKs (Anthropic, Vercel, Stripe, anything from Stainless) was public-monorepo by default. As of 2026, cuberoot.me — a midsize "few interdependent packages + shared types" project — has run this stack for 18 months without restructuring.</p>
      </>
    ),
  },
  history: [
    { year: '~1991', zh: { title: <>大公司内部默认</>, desc: <>Bell Labs / IBM / DEC 内部把所有代码堆在一棵树里是默认形态, 没人叫"monorepo" — 因为还没出现 polyrepo 那一脚。</> }, en: { title: <>Big-co default</>, desc: <>At Bell Labs / IBM / DEC, lumping all code into one tree was the default — nobody called it "monorepo" because polyrepo hadn't been invented as a contrast.</> } },
    { year: '~2003', zh: { title: <>Google Piper 时代成型</>, desc: <>Perforce 撑不住, Google 写自家 Piper + Blaze (后开源 Bazel)。全公司一棵树, 后来公开数字 2B+ LOC, 16k 工程师同时操作。</> }, en: { title: <>Google's Piper era</>, desc: <>Perforce buckled; Google built Piper + Blaze (later open-sourced as Bazel). One company, one tree — later reported as 2B+ LoC with 16k engineers active in parallel.</> } },
    { year: '2014·08', zh: { title: <>Meta 把 Hg 扛上 1.3M 文件</>, desc: <>Facebook 工程团队改造 Mercurial 让 working copy + status 都能在 1.3M 文件的仓库下保持秒级响应。"为什么不用 git" 写成一篇出名博客。</> }, en: { title: <>Meta scales Hg to 1.3M files</>, desc: <>Facebook engineering modifies Mercurial so working copy + status stay sub-second on a 1.3M-file repo. "Why we don't use Git" becomes a famous blog post.</> } },
    { year: '2015·06', zh: { title: <>Lerna 1.0 (Babel)</>, desc: <>Sebastian McKenzie 给 Babel 团队写 Lerna, JS 圈第一次官方喊出"monorepo"这个词。同年底 React 自己也切了 monorepo (facebook/react/packages/*)。</> }, en: { title: <>Lerna 1.0 (Babel)</>, desc: <>Sebastian McKenzie writes Lerna for the Babel team — the first time the JS world officially uses the word "monorepo." React itself migrates to a monorepo (facebook/react/packages/*) the same year.</> } },
    { year: '2016·10', zh: { title: <>Yarn 1.0 workspaces 实验</>, desc: <>Yarn classic 在 1.0 实验 workspaces 概念。原生支持比 Lerna 工具链外挂干净一档, 后面演化成默认。</> }, en: { title: <>Yarn 1.0 workspaces experiment</>, desc: <>Yarn classic experiments with workspaces in 1.0. Native support is a notch cleaner than Lerna's external tooling, and it slowly becomes the default.</> } },
    { year: '2017·10', zh: { title: <>Yarn 1.0 workspaces 正式</>, desc: <>workspaces 转 stable。Lerna 从"包管理 + 任务编排" 退守到 "任务编排", 一两年后基本式微。</> }, en: { title: <>Yarn 1.0 workspaces stable</>, desc: <>Workspaces graduate to stable. Lerna retreats from "package manager + task runner" to just task running, and fades over the next year or two.</> } },
    { year: '2019·04', zh: { title: <>pnpm workspaces</>, desc: <>Zoltan Kochan 把 workspaces 用<strong>硬链接 + 严格 node_modules</strong>重塑。同时把 yarn 装包重复占盘问题 + 幽灵依赖问题一次性堵死。</> }, en: { title: <>pnpm workspaces</>, desc: <>Zoltan Kochan rebuilds workspaces on <strong>hard links + strict node_modules</strong>. Yarn's "every project copies the same lodash again" and the phantom-dependency disease are both shut down in one move.</> } },
    { year: '2020·11', zh: { title: <>Turborepo 立项</>, desc: <>Jared Palmer 一个人在 GitHub 开 turborepo.org。目标 "monorepo 里没改的包别再跑"。一年后被 Vercel 收购。</> }, en: { title: <>Turborepo started</>, desc: <>Jared Palmer solo-launches turborepo.org. Goal: "stop rebuilding monorepo packages that haven't changed." Vercel acquires it a year later.</> } },
    { year: '2021·12', zh: { title: <>Turbo 1.0 + Vercel 收购</>, desc: <>Turborepo 1.0 落地 + Vercel 收购同时发生。remote cache 上云, "本地构过的 hash, CI 秒命中"成可能。</> }, en: { title: <>Turbo 1.0 + Vercel acquisition</>, desc: <>Turborepo 1.0 ships and Vercel acquires it the same month. Remote cache lands on the cloud — "developer's local hash, CI hits in seconds" becomes possible.</> } },
    { year: '2022·11', zh: { title: <>Lerna 接力被 Nx 接管</>, desc: <>Lerna 项目活跃度归零后, Nrwl (Nx 团队) 接手维护。"JS monorepo 第一代工具"正式合并进"第二代"工具栈。</> }, en: { title: <>Nx adopts Lerna</>, desc: <>Lerna had gone dormant; Nrwl (the Nx team) takes over maintenance. The first-generation JS monorepo tool merges into the second-generation stack.</> } },
    { year: '2024·06', zh: { title: <>Turbo 2.0 (Rust)</>, desc: <>Go 代码全删, Rust 重写完。cache 协议变严, 平均产物从 180MB 降到 45MB。pnpm 9 + Turbo 2 + tsc references 几乎是新项目默认栈。</> }, en: { title: <>Turbo 2.0 (Rust)</>, desc: <>The Go codebase is gone, full Rust rewrite. Cache protocol tightens; average artifact drops from 180MB to 45MB. pnpm 9 + Turbo 2 + tsc references becomes the default new-project stack.</> } },
    { year: '2025·??', zh: { title: <>SDK 公开 monorepo 化</>, desc: <>Anthropic / Vercel / Stripe / Stainless 生成的官方 SDK 几乎清一色 monorepo。"一个 SDK 一个 git repo" 的写法被淘汰到只剩遗留项目。</> }, en: { title: <>SDKs go public monorepo</>, desc: <>Official SDKs from Anthropic / Vercel / Stripe / Stainless-generated all ship as monorepos. "One SDK, one git repo" is left only to legacy projects.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>cuberoot.me · 18 个月</>, desc: <>本仓库 <code>core/</code> 跑 5-package pnpm + Turbo 结构 18 个月没拆。日常加新包是 <em>append-only</em>, 没出现过反向 (拆掉某个包) 的需求。</> }, en: { title: <>cuberoot.me · 18 months</>, desc: <>This repo's <code>core/</code> has run the 5-package pnpm + Turbo structure for 18 months. Adding a new package has only ever been append-only — no reversal (splitting one out) has been needed.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>workspaces 声明</>, desc: <>一份 <code>pnpm-workspace.yaml</code> 把哪些子目录是 workspace 包列出来。pnpm install 把它们之间的 <code>workspace:*</code> 依赖 symlink 起来。</> }, en: { title: <>Workspace declaration</>, desc: <>One <code>pnpm-workspace.yaml</code> lists which subdirectories are workspace packages. pnpm install symlinks their <code>workspace:*</code> deps to each other.</> }, code: <code>{c('# core/pnpm-workspace.yaml')}{'\n'}{p('packages')}:{'\n'}  - {s("'packages/*'")}</code> },
    { tag: 'B', zh: { title: <>--filter 跨包跑命令</>, desc: <>不进子目录, 在 root 直接 <code>pnpm --filter @cuberoot/client dev</code>。支持 glob、依赖图遍历 (<code>...^pkg</code> 含依赖)。</> }, en: { title: <>--filter cross-package commands</>, desc: <>Never cd in — run <code>pnpm --filter @cuberoot/client dev</code> from root. Supports globs and dep-graph traversal (<code>...^pkg</code> includes deps).</> }, code: <code>pnpm --filter @cuberoot/client {f('dev')}{'\n'}pnpm -r {f('typecheck')}{'\n'}pnpm --filter {s('"...^@cuberoot/client"')} {f('build')}</code> },
    { tag: 'C', zh: { title: <>tsconfig.references</>, desc: <>给 tsc 一份 DAG, 让 <code>tsc -b</code> 知道编译顺序并增量缓存。改 shared 类型, client/server 只 typecheck 改动到的子图。</> }, en: { title: <>tsconfig.references</>, desc: <>Feed tsc a DAG so <code>tsc -b</code> knows compile order and caches incrementally. Edit a shared type and only the affected subgraph re-typechecks.</> }, code: <code>{c('// client/tsconfig.json')}{'\n'}{'{'}{'\n'}  {p('"references"')}: [{'\n'}    {'{ '}{p('"path"')}: {s('"../shared"')} {'}'}{'\n'}  ]{'\n'}{'}'}</code> },
    { tag: 'D', zh: { title: <>共享 types 包</>, desc: <>cuberoot.me 的 <code>@cuberoot/shared</code> 只有 <code>.d.ts</code> + 极薄 runtime, 给 client + server 共用类型。Hono RPC 类型也走这里流到前端。</> }, en: { title: <>Shared types package</>, desc: <>cuberoot.me's <code>@cuberoot/shared</code> is <code>.d.ts</code> + a thin runtime, shared by client + server. Hono RPC types flow through it into the frontend.</> }, code: <code>{c('// @cuberoot/shared/src/alg.ts')}{'\n'}{k('export')} {k('interface')} {v('AlgCase')} {'{'}{'\n'}  {p('id')}: {v('string')};{'\n'}  {p('name')}: {v('string')};{'\n'}  {p('alg')}: {v('string')};{'\n'}{'}'}</code> },
    { tag: 'E', zh: { title: <>单一 lockfile</>, desc: <>整棵树一份 <code>pnpm-lock.yaml</code>。升 react 一次, 所有包同步;不会出现 "client 用 19.2 / stats-ui 用 19.1" 这种漂移。</> }, en: { title: <>One lockfile</>, desc: <>One <code>pnpm-lock.yaml</code> for the whole tree. Bump react once, every package follows — no drift like "client on 19.2, stats-ui on 19.1."</> }, code: <code>{c('# pnpm-lock.yaml')}{'\n'}{p('importers')}:{'\n'}  {p('packages/client')}: ...{'\n'}  {p('packages/server')}: ...{'\n'}  {p('packages/shared')}: ...</code> },
    { tag: 'F', zh: { title: <>Turbo 任务编排</>, desc: <>一份 <code>turbo.json</code> 描述 build / typecheck / test 之间的依赖图。每个任务输入 hash, 命中 cache 秒回。</> }, en: { title: <>Turbo task orchestration</>, desc: <>One <code>turbo.json</code> describes the build / typecheck / test dep graph. Each task hashes its inputs; cache hits replay in milliseconds.</> }, code: <code>{'{'}{'\n'}  {p('"tasks"')}: {'{'}{'\n'}    {p('"build"')}: {'{ '}{p('"dependsOn"')}: [{s('"^build"')}] {'}'},{'\n'}    {p('"typecheck"')}: {'{ '}{p('"dependsOn"')}: [{s('"^build"')}] {'}'}{'\n'}  {'}'}{'\n'}{'}'}</code> },
    { tag: 'G', zh: { title: <>循环依赖检测</>, desc: <><code>pnpm why</code> + <code>pnpm list --recursive</code> 看包之间的依赖路径;monorepo 里 A 依赖 B 又依赖 A 是死亡 trap, 一般在 install 阶段 pnpm 就报错。</> }, en: { title: <>Cycle detection</>, desc: <><code>pnpm why</code> + <code>pnpm list --recursive</code> trace cross-package paths. A→B→A cycles in a monorepo are death traps; pnpm typically errors them out at install.</> }, code: <code>pnpm why @cuberoot/shared{'\n'}{c('// shows which packages pull it')}</code> },
    { tag: 'H', zh: { title: <>polyrepo vs monorepo</>, desc: <>polyrepo = N 个 git repo + N 份 lockfile + N 个 CI;monorepo = 1 + 1 + 1。多于 ~50 个包时 monorepo 要上 Nx / Turbo cloud cache, 否则 CI 也吃不消。</> }, en: { title: <>polyrepo vs monorepo</>, desc: <>polyrepo: N git repos, N lockfiles, N CI workflows. Monorepo: 1 + 1 + 1. Past ~50 packages, a monorepo needs Nx / Turbo cloud cache or CI buckles.</> }, code: <code>{c('// cuberoot.me trade-off')}{'\n'}{c('// 11 packages → sweet spot')}{'\n'}{c('// no remote cache needed')}</code> },
  ],
  whyCards: [
    { icon: '⚙', zh: { title: <>跨包重构是 atomic commit</>, desc: <>改 <code>@cuberoot/shared</code> 的类型, <strong>同一个 PR</strong> 里把 client + server 的调用点全收紧。polyrepo 下这种改动要协调三个 PR 三次 review。</> }, en: { title: <>Cross-package refactors are atomic</>, desc: <>Change a type in <code>@cuberoot/shared</code> and fix the call sites in client + server in <strong>one PR</strong>. The same change in a polyrepo means three PRs and three reviews.</> }, code: <>{c('// One commit:')}{'\n'}{c('//   shared/src/alg.ts')}{'\n'}{c('//   client/src/AlgPage.tsx')}{'\n'}{c('//   server/src/routes/alg.ts')}</> },
    { icon: '⌬', zh: { title: <>lockfile = 单一版本真相</>, desc: <>一份 <code>pnpm-lock.yaml</code> 锁所有包的所有依赖。升 react 一次, 整棵树跟着走;不会出现"客户端 19.2 / 内部库 19.1"这种慢性漂移。</> }, en: { title: <>Lockfile = single version of truth</>, desc: <>One <code>pnpm-lock.yaml</code> locks every dep across every package. Bump react once and the whole tree follows — no slow drift like "client on 19.2, stats-ui on 19.1."</> }, code: <>{c('// pnpm-lock.yaml')}{'\n'}{c('// react: 19.2.0 (everywhere)')}</> },
    { icon: '⎇', zh: { title: <>共享类型零运行时</>, desc: <><code>@cuberoot/shared</code> 几乎只有 <code>.d.ts</code>, 编译产物对 bundle size 影响为零, 但前后端 API contract 完全锁死。Hono RPC + tRPC 这套范式的基础。</> }, en: { title: <>Shared types, zero runtime</>, desc: <><code>@cuberoot/shared</code> is mostly <code>.d.ts</code>; the compiled output adds nothing to bundle size while fully locking the front/back API contract. The foundation of the Hono RPC + tRPC paradigm.</> }, code: <>{k('import')} {k('type')} {'{'} {v('AlgCase')} {'}'} {k('from')} {s("'@cuberoot/shared'")};</> },
    { icon: '⌁', zh: { title: <>CI 只跑改动到的包</>, desc: <>Turbo 看 git diff + 依赖图, 算出"这次只 client 改了, server / stats-build 直接 cache 命中"。本仓库 CI 平均 build 在 90 秒以内。</> }, en: { title: <>CI runs only what changed</>, desc: <>Turbo reads the git diff + dep graph and concludes "only client changed; server / stats-build hit the cache." This repo's average CI build is under 90 seconds.</> }, code: <>{f('turbo')} build {f('--filter')}=...[origin/main]{'\n'}{c('// only affected packages')}</> },
    { icon: '⌖', zh: { title: <>缺点:lockfile churn</>, desc: <>多 AI / 多人并行时, 两边各跑 <code>pnpm add</code>, 提交时 <code>pnpm-lock.yaml</code> 100% 撞。本项目的 CLAUDE.md 显式写了"提交前必扫 lockfile 变化"。</> }, en: { title: <>Drawback: lockfile churn</>, desc: <>With multi-AI / multi-human parallel work, two sides running <code>pnpm add</code> guarantees a <code>pnpm-lock.yaml</code> collision. This project's CLAUDE.md explicitly mandates "scan lockfile changes before commit."</> }, code: <>git status{'\n'}{c('// always check pnpm-lock.yaml')}</> },
    { icon: '⌗', zh: { title: <>缺点:onboarding 加一步</>, desc: <>新人得先理解 workspace protocol, 得知道 "pnpm add 必须在 core/ 内跑" (在仓库根跑会生成错的 lockfile, CI 立刻挂)。这条本项目 CLAUDE.md 也写死了。</> }, en: { title: <>Drawback: onboarding cost</>, desc: <>Newcomers must grok the workspace protocol and learn "run pnpm add only inside core/" (running it at the repo root produces a wrong lockfile and CI fails). This rule is pinned in CLAUDE.md.</> }, code: <>{c('// MUST be inside core/')}{'\n'}cd core && pnpm add foo</> },
    { icon: '⏚', zh: { title: <>适用边界</>, desc: <>5~20 个互相耦合的包是甜区, 配 pnpm + Turbo + tsc references 几乎零运维成本。&gt; 50 个包要上 Nx / Turbo Remote Cache 才扛得动 CI。彻底独立的包还是分开 repo 更干净。</> }, en: { title: <>Where it fits</>, desc: <>The sweet spot is 5~20 interdependent packages — pnpm + Turbo + tsc references has near-zero overhead. Past 50 packages you need Nx / Turbo Remote Cache to keep CI sane. Truly unrelated packages belong in separate repos.</> }, code: <>{c('// cuberoot.me: 11 packages')}{'\n'}{c('// → no remote cache needed')}</> },
    { icon: '⛯', zh: { title: <>SBOM / supply-chain 容易做</>, desc: <>一份 lockfile + 一棵 commit 历史, 自动生成 SBOM (Software Bill of Materials) 比 polyrepo 散在 N 个仓库容易一个数量级。监管侧 (SLSA / sigstore) 都偏好这种形态。</> }, en: { title: <>SBOM / supply-chain made easy</>, desc: <>One lockfile + one commit history makes generating an SBOM (Software Bill of Materials) an order of magnitude easier than gluing N polyrepos together. Compliance side (SLSA / sigstore) prefers this shape.</> }, code: <>{c('// one lockfile')}{'\n'}{c('// → one SBOM')}</> },
  ],
  adopters: [
    { name: 'Google (Piper)', highlight: true, zhNote: '亲爹, 全公司一棵树 2B+ LOC, 16k 工程师同时操作', enNote: 'The grandparent — one company tree at 2B+ LoC, 16k engineers in parallel' },
    { name: 'Meta (Mercurial)', href: 'https://engineering.fb.com', highlight: true, zhNote: '把 Mercurial 改造扛 1.3M 文件, "Why not git" 出名博客', enNote: 'Scaled Mercurial to 1.3M files; "Why not Git" famous post' },
    { name: 'Microsoft 1ES + Office', href: 'https://microsoft.com', zhNote: 'Office monorepo, 1ES Engineering 整套支撑', enNote: 'Office monorepo backed by 1ES Engineering tooling' },
    { name: 'React (facebook/react)', href: 'https://github.com/facebook/react', highlight: true, zhNote: 'React 自己就是 monorepo, packages/* 100+', enNote: 'React itself is a monorepo — packages/* counts in the 100s' },
    { name: 'Vue 3', href: 'https://github.com/vuejs/core', zhNote: 'Vue 3 + Vite + Vitest 全家桶 monorepo', enNote: 'Vue 3 + Vite + Vitest are all monorepos' },
    { name: 'Babel (Lerna 起源)', href: 'https://github.com/babel/babel', highlight: true, zhNote: 'Lerna 诞生地, JS monorepo 第一次落地', enNote: 'Lerna was born here — the first time JS got "monorepo" as a term' },
    { name: 'Next.js / Turborepo', href: 'https://github.com/vercel/next.js', zhNote: 'Vercel 自己的 monorepo, 同时也是 Turborepo 的灯塔用户', enNote: "Vercel's own monorepo and Turborepo's lighthouse user" },
    { name: 'Anthropic SDK', href: 'https://github.com/anthropics/anthropic-sdk-typescript', zhNote: 'Anthropic 官方 TS SDK 是 monorepo', enNote: "Anthropic's official TS SDK is a monorepo" },
    { name: 'Stripe SDK', href: 'https://github.com/stripe/stripe-node', zhNote: 'Stripe Node SDK / Connect / Terminal 都同仓', enNote: 'Stripe Node SDK / Connect / Terminal share one tree' },
    { name: 'Cloudflare Workers SDK', href: 'https://github.com/cloudflare/workers-sdk', zhNote: 'Wrangler + Miniflare + workers-types 同仓', enNote: 'Wrangler + Miniflare + workers-types share one tree' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本仓库 core/ 5 个核心包 + 6 个支撑包, 18 个月没拆', enNote: 'This repo — 5 core + 6 supporting packages, 18 months without splitting' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>tsc references + Turbo cache 让重建 &lt; 5s</>, body: <><p>2025 之前"改一行 shared 类型, 等 30 秒全 monorepo 重 typecheck"是常态。tsc references 走 DAG 增量, Turbo cache 把上次结果按 hash 重放, 现在 cuberoot.me 这种 11 包项目改一行典型在 1~3 秒内完成。</p><p>这不只是体感快, 是改变了开发节奏 — refactor shared 类型不再"等一波再说", 而是改完即看。从 "compile 时长决定迭代节奏" 退化到 "compile 时长不再是变量"。</p></> }, en: { title: <>Rebuilds under 5s via tsc refs + Turbo cache</>, body: <><p>Before 2025, "edit one shared type, wait 30s for the whole monorepo to re-typecheck" was normal. tsc references walk the DAG incrementally; Turbo cache replays prior results by hash. On an 11-package project like cuberoot.me, a one-line edit lands in 1~3 seconds.</p><p>This isn't just a feel-good number — it changes the development cadence. Refactoring a shared type stops being a "batch it and wait" affair; it becomes "edit and see." Compile time goes from "the variable that paces iteration" to "no longer a variable at all."</p></> } },
    { tag: 'REMOTE-CACHE', zh: { title: <>Nx Cloud / Turbo Remote Cache</>, body: <><p>本地构过的 hash 上传到云端 backend, CI 跑同一 commit 时秒级命中。一个工程师本地 build 完, 同事拉同 commit 直接拿现成产物, 不再各跑各。</p><p>对大型团队 CI 时间从分钟级降到秒级。对小项目 (像 cuberoot.me) 暂时不需要 — 但接口是 1 行 token, 想加就加。</p></> }, en: { title: <>Nx Cloud / Turbo Remote Cache</>, body: <><p>Upload locally-built hashes to a cloud backend; CI hits the cache in seconds on the same commit. One engineer builds locally, a teammate pulling the same commit gets the artifact for free.</p><p>For large teams, CI drops from minutes to seconds. Small projects like cuberoot.me don't need it yet — but the integration is a one-line token, opt-in anytime.</p></> } },
    { tag: 'POLYREPO RIP', zh: { title: <>polyrepo + git submodule 几乎绝迹</>, body: <><p>2020 之前"几个 repo + git submodule"还能见到, 2026 在新项目里几乎绝迹。submodule 的"切换分支后忘了 update"陷阱配上"跨 repo 类型对不上"双重折磨, 在 monorepo 工具成熟后彻底没有理由存在。</p></> }, en: { title: <>polyrepo + git submodule effectively gone</>, body: <><p>Pre-2020 you'd still see "a few repos stitched with git submodule." In 2026 it's effectively absent from new projects. The "forgot to submodule update after branch switch" trap plus the "types don't match across repos" pain has no reason left to exist once monorepo tooling matures.</p></> } },
    { tag: 'SBOM', zh: { title: <>SBOM + supply-chain attestation</>, body: <><p>监管侧 (SLSA / sigstore / CRA in EU) 都在推 SBOM, 而 monorepo 一份 lockfile + 一棵 commit 历史让生成 SBOM 比 polyrepo 容易一个数量级。pnpm v11 把 store 换 SQLite 后, supply-chain attestation 也方便挂。</p><p>预测:2027 起公开 SDK 在 monorepo 内附带 SLSA provenance 会成默认。</p></> }, en: { title: <>SBOM + supply-chain attestation</>, body: <><p>Regulators (SLSA / sigstore / EU CRA) push SBOM, and a monorepo's single lockfile + single commit history makes SBOM generation an order of magnitude easier than gluing N polyrepos. pnpm v11's SQLite store further opens the door for hanging attestation off the build.</p><p>Prediction: from 2027, public SDKs shipping inside monorepos with SLSA provenance attached becomes the default.</p></> } },
    { tag: <>AI</>, zh: { title: <>AI agent 自己跑测试再 merge</>, body: <><p>Google / Meta 内部已经在试: AI agent 收到 PR 后<strong>自己跑测试 + 看 cache hit 率 + 给 review 建议</strong>, 人审在最后一步。monorepo 一份 lockfile + 单一 CI 让这种"全图可见"的 agent 比 polyrepo 容易写一个数量级。</p><p>对个人项目 (cuberoot.me 多 AI 并行) 已经在跑 — 几个 Claude agent 同时改不同包, 提交前各自 typecheck + lockfile 扫一遍, 撞了再人工合。</p></> }, en: { title: <>AI agents test + merge autonomously</>, body: <><p>Google / Meta are already piloting: an AI agent receives a PR, <strong>runs the tests, checks cache hit rate, suggests review comments</strong> — humans only step in at the very end. A monorepo's single lockfile + single CI makes such a "whole graph visible" agent an order of magnitude easier to write than across N polyrepos.</p><p>It's already running at the individual-project scale (multi-AI work on cuberoot.me) — several Claude agents edit different packages in parallel, each running typecheck + lockfile scan before commit; collisions get manually merged.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>cuberoot.me 是经典的 pnpm + Turbo monorepo, 跑了 18 个月没换过结构。仓库根是一堆 fork 来的静态 HTML (Solver / Alg Trainers / csTimer 三家), 真正的开发都在 <code>core/</code>。<code>core/</code> 即 pnpm workspace 根, <code>pnpm-workspace.yaml</code> 把 <code>packages/*</code> 全部纳入, 共 11 个 workspace。</p>
        <p>5 个核心包:<code>@cuberoot/client</code> (~120k LOC, React 19 SPA, 24+ 工具页) + <code>@cuberoot/server</code> (~8k, Hono + PG API) + <code>@cuberoot/shared</code> (~1k, 纯 TS 类型, 给前后端共用 alg / recon / training 的 contract) + <code>@cuberoot/stats-build</code> (~5k, WCA 统计 CLI, 周更跑在 GitHub Actions) + <code>@cuberoot/stats-ui</code> (~3k, 统计页通用壳)。另外 6 个支撑包:<code>alg-build</code> / <code>scramble-stats-build</code> / <code>stack-kernel</code> / <code>vendor-sr-puzzlegen</code> / <code>visualcube</code> / <code>wb-build</code>, 多数是独立 CLI 或 vendor wrap, 不耦合主链路。</p>
        <p>依赖图: <code>client</code> + <code>server</code> 都依赖 <code>shared</code> (<code>workspace:*</code> 协议, pnpm install 直接 symlink); <code>client</code> 还依赖 <code>stats-ui</code> + <code>visualcube</code>; <code>stats-build</code> / <code>scramble-stats-build</code> / <code>alg-build</code> 是独立 CLI 跑在 CI, 跟主链路只通过最终生成的 JSON 文件耦合。一份 <code>pnpm-lock.yaml</code> 锁所有依赖; 每个包 <code>tsconfig.json</code> 用 references 串成 DAG, <code>tsc -b</code> 增量编译只跑改动到的子图; <code>turbo.json</code> 定义 <code>build</code> / <code>dev</code> / <code>typecheck</code> / <code>lint</code> 四个 pipeline。</p>
        <p>维护细节:改 <code>shared</code> 类型时 client + server 必须在<strong>同一个 PR</strong> 收紧 (atomic refactor), 这是 monorepo 最大红利;<code>pnpm add</code> 必须在 <code>core/</code> 里跑, 仓库根没 workspace 文件, 跑了会生成错的 lockfile, CI 立刻挂 — 这条写死在项目 CLAUDE.md;多 AI 并发提交时 <code>pnpm-lock.yaml</code> 几乎必撞, 提交前必须 <code>git status</code> 扫一遍。CI 没接 Turbo Remote Cache — 单作者项目, 本地 + GitHub Actions 跑得够快, 没动力搭后端。</p>
      </>
    ),
    en: (
      <>
        <p>cuberoot.me is a textbook pnpm + Turbo monorepo that has held its shape for 18 months. The repo root is a collection of forked static HTML (Solver / Alg Trainers / csTimer); all real development lives under <code>core/</code>. <code>core/</code> is the pnpm workspace root — <code>pnpm-workspace.yaml</code> registers <code>packages/*</code>, eleven workspaces in total.</p>
        <p>Five core packages: <code>@cuberoot/client</code> (~120k LoC, React 19 SPA, 24+ tool pages) + <code>@cuberoot/server</code> (~8k, Hono + PG API) + <code>@cuberoot/shared</code> (~1k, pure TS types — front/back contracts for alg / recon / training) + <code>@cuberoot/stats-build</code> (~5k, WCA stats CLI, weekly run on GitHub Actions) + <code>@cuberoot/stats-ui</code> (~3k, the shared stats-page chrome). Six supporting packages: <code>alg-build</code> / <code>scramble-stats-build</code> / <code>stack-kernel</code> / <code>vendor-sr-puzzlegen</code> / <code>visualcube</code> / <code>wb-build</code> — mostly standalone CLIs or vendor wrappers, decoupled from the main chain.</p>
        <p>Dependency graph: <code>client</code> + <code>server</code> both depend on <code>shared</code> (via <code>workspace:*</code>, pnpm install symlinks it); <code>client</code> also depends on <code>stats-ui</code> + <code>visualcube</code>; <code>stats-build</code> / <code>scramble-stats-build</code> / <code>alg-build</code> are independent CLIs running in CI, coupling to the main chain only through the JSON files they produce. One <code>pnpm-lock.yaml</code> locks everything; each package's <code>tsconfig.json</code> threads the references DAG so <code>tsc -b</code> incremental builds run only the affected subgraph; <code>turbo.json</code> defines four pipelines: <code>build</code> / <code>dev</code> / <code>typecheck</code> / <code>lint</code>.</p>
        <p>Maintenance: editing a <code>shared</code> type means client + server land in <strong>one PR</strong> — atomic refactor, the single biggest monorepo dividend. <code>pnpm add</code> must run inside <code>core/</code>; the repo root has no workspace file, so running there yields a wrong lockfile and CI fails immediately — pinned in CLAUDE.md. Under multi-AI parallel commits, <code>pnpm-lock.yaml</code> collides nearly every time, so <code>git status</code> must be scanned before each commit. No Turbo Remote Cache yet — single-author project, local + GitHub Actions runs fast enough, no motivation to host a backend.</p>
      </>
    ),
  },
  links: [
    { label: 'monorepo.tools', href: 'https://monorepo.tools' },
    { label: 'pnpm Workspaces', href: 'https://pnpm.io/workspaces' },
    { label: 'Turborepo docs', href: 'https://turborepo.dev/docs' },
    { label: 'tsc Project References', href: 'https://www.typescriptlang.org/docs/handbook/project-references.html' },
    { label: 'Why Google Stores Billions of Lines of Code in a Single Repository (ACM 2016)', href: 'https://research.google/pubs/why-google-stores-billions-of-lines-of-code-in-a-single-repository/' },
  ],
};
