import type { StackTool } from '../stack_tool_types';
import { k, s, n, f, p, c } from '../stack_tool_types';

// ─── Obsidian + Obsidian CLI (planned tooling, not yet integrated) ──────────

export const OBSIDIAN: StackTool = {
  slug: 'obsidian',
  name: 'Obsidian',
  version: '1.7',
  since: '2020-03',
  group: 'dev',
  accent: '#7C3AED',
  bright: '#A78BFA',
  glyph: '◇',
  floats: ['markdown', '[[wiki-link]]', 'vault', 'Dataview', 'Templater', 'community plugins', 'Obsidian Sync', 'Publish', 'Canvas', 'MCP server', 'obsidian-cli', 'obsidian://'],
  zh: {
    tagline: '本地优先的 Markdown 思考工具',
    role: '计划中 — 个人知识管理 + AI-era 上下文仓库。当前 cuberoot.me 代码库不依赖, 但下一年准备把笔记 / 设计决策 / 调研记录都搬进来, 跟 Claude Code 形成闭环。',
    heroSub: <>2020 年由 Dynalist 团队的 Erica Xu 和 Shida Li 推出, 反方向走 Roam Research 的全云订阅路线:<strong>本地优先</strong>, 文件就是普通 markdown, 你拥有你的数据。六年长成 2000+ plugin 的生态, 在 AI 时代又因为"vault 就是给 LLM 的最佳长期记忆"被重新发现。</>,
    whatDesc: <>Obsidian 是一个 <strong>本地 markdown 笔记应用</strong>, 数据存在你的硬盘上的一个普通文件夹 (vault) 里。每个笔记就是一个 .md 文件, 双链 / tag / metadata 全部在文件本体里, app 关停了 vault 还是普通文件夹, 任何编辑器都能读。</>,
    historyDesc: <>2020 年公开 beta, 那时 Roam Research 刚把"双链笔记"概念引爆, Obsidian 走相反方向:本地、买断、文件归你。2021-2024 plugin 生态指数级长, Dataview / Templater / Excalidraw 几乎成事实标准。2025 起 MCP 让 vault 直接接进 Claude / Cursor, 角色从"个人笔记本"变成"AI agent 的长期记忆"。</>,
    conceptsTitle: 'Markdown + 双链 + 程序化入口',
    conceptsDesc: <>Obsidian 的核心 primitive 极少:.md 文件 + <code>[[wiki-link]]</code> + YAML frontmatter + plugin。剩下的复杂度都长在 plugin 上 (Dataview / Templater / Tasks)。AI 时代多了第三类入口:URI 协议 + obsidian-cli + MCP server。</>,
    whyDesc: <>2026 年选 Obsidian 而不是 Notion / Logseq 的理由不是功能多, 是 <strong>所有权清晰</strong>、<strong>本地优先</strong>、<strong>markdown 是 LLM 母语</strong>、<strong>plugin 自由</strong>四件事配合起来在 AI 时代变成杀手锏。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>从 Andy Matuschak / Maggie Appleton 这种"数字花园"原教旨主义者, 到法学院 / 历史学家的公开 vault, 到 Linking Your Thinking 5 万学员的个人知识管理课程。1M+ 注册用户, 大部分是独立研究者 / 写作者 / 开发者。</>,
    cuberootDesc: <><strong>当前 cuberoot.me 代码库不依赖 Obsidian。</strong> 这页放在 /code/stack 是因为它即将进入个人工作流 —— 下一年准备把散落在 D:\cube 下的 SKILL / 设计决策 / 调研笔记整理进 vault, 跟 Claude Code + MCP 形成"笔记 ↔ commit ↔ 设计文档"的闭环。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>MCP server 把 Obsidian vault 接进 Claude / Cursor 是 2026 下半年最明显的趋势。obsidian-cli 工具链同步成熟, "agent 直接 query / append note" 从想法变成日常脚本。Properties + Dataview 4.0 让 vault 变成半结构化数据库。</>,
  },
  en: {
    tagline: 'Local-first markdown thinking tool',
    role: 'Planned tooling — personal knowledge base + AI-era context store. The cuberoot.me codebase does not depend on it yet, but the next year of work plans to move notes / design decisions / research into a vault and close the loop with Claude Code.',
    heroSub: <>Built in 2020 by Erica Xu and Shida Li of the Dynalist team, deliberately opposing Roam Research's cloud-subscription model: <strong>local-first</strong>, files stay plain markdown, the data is yours. Six years grew into 2000+ plugins, and the AI era rediscovered it because "a vault is the ideal long-term memory for an LLM."</>,
    whatDesc: <>Obsidian is a <strong>local markdown notes app</strong>; data sits in a plain folder (the vault) on your disk. Each note is a .md file; bidirectional links / tags / metadata all live in the file body. If Obsidian shut down tomorrow, the vault is still just a folder any editor can read.</>,
    historyDesc: <>Public beta in 2020 — Roam Research had just ignited the "bidirectional links" wave, and Obsidian went the other way: local, one-time license, your files. From 2021-2024 the plugin ecosystem grew exponentially; Dataview / Templater / Excalidraw became de-facto standards. From 2025 onward MCP wires vaults straight into Claude / Cursor, and the role shifts from "personal notebook" to "AI agent's long-term memory."</>,
    conceptsTitle: 'Markdown + bidirectional links + programmatic entry',
    conceptsDesc: <>Obsidian's core primitives are few: .md files + <code>[[wiki-link]]</code> + YAML frontmatter + plugins. All complexity lives in plugins (Dataview / Templater / Tasks). The AI era adds a third class of entry: the URI scheme, obsidian-cli, and the MCP server.</>,
    whyDesc: <>Choosing Obsidian over Notion / Logseq in 2026 is not about feature count — it's about <strong>ownership clarity</strong>, <strong>local-first storage</strong>, <strong>markdown being an LLM's native language</strong>, and <strong>plugin freedom</strong>. These four together become the killer combination in the AI era.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>From digital-garden originalists like Andy Matuschak and Maggie Appleton, to public law-school and historian vaults, to the 50k students of the Linking Your Thinking course. 1M+ registered users — most of them independent researchers, writers, and developers.</>,
    cuberootDesc: <><strong>cuberoot.me currently does not depend on Obsidian.</strong> This page sits in /code/stack because it is about to enter the personal workflow — the next year's plan is to consolidate the SKILL / design decisions / research notes scattered under D:\cube into a vault, and close the loop with Claude Code + MCP into "notes ↔ commits ↔ design docs."</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>MCP servers wiring Obsidian vaults into Claude / Cursor is the dominant trend of late 2026. The obsidian-cli toolchain matures in parallel; "agent queries / appends notes" goes from idea to a routine script. Properties + Dataview 4.0 turn the vault into a semi-structured database.</>,
  },
  heroStats: [
    { num: '1', unit: 'M+', zh: <>注册用户 <em>2026 公开估计</em></>, en: <>registered users <em>2026 public estimate</em></> },
    { num: '2000', unit: '+', zh: <>community plugins <em>obsidian.md/plugins</em></>, en: <>community plugins <em>obsidian.md/plugins</em></> },
    { num: '100', unit: '%', zh: <>markdown — 文件属于你 <em>无云锁</em></>, en: <>markdown — files are yours <em>no cloud lock-in</em></> },
    { num: '1.7', zh: <>当前稳定版 <em>2026-04</em></>, en: <>current stable <em>2026-04</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>Obsidian 2020 年由 Erica Xu 和 Shida Li 推出, 这俩是夫妻档, 之前做过同样思路的 outliner 应用 Dynalist。立项的背景是 Roam Research 刚把"双链笔记"概念引爆 —— 但 Roam 是全云、月费 15 美元、数据存对方服务器上。Obsidian 反方向走:<em>本地优先</em>, vault 就是你硬盘上一个普通文件夹, 每个笔记是一个 .md 文件, 个人用永久免费, 同步 / 出版才收费。</p>
        <p>2020-2024 是 plugin 生态爆发期。Dataview (笔记当数据库查询) / Templater (用 JS 写模板) / Excalidraw (手绘图)/ Calendar / Tasks 几乎成为人手必装。到 2024 年 Obsidian 1.0 GA + 移动端正式版上线时, "本地优先 + 强插件" 这条路线已经被验证可以从个人笔记一路扛到大学研究者公开 vault。</p>
        <p>2025-2026 是 AI 时代的二次发现。MCP (Model Context Protocol, Anthropic 在 2024 末推出) 出现以后, 本地 vault 突然成了给 LLM 的最佳长期记忆载体 —— markdown 是模型最熟悉的格式, 文件可以程序化读写, agent 可以直接 query 你过去半年的笔记。社区出的 obsidian-mcp-server 让 Claude / Cursor 几乎零成本接进 vault。这就是为什么本站 owner 准备认真把 Obsidian 上手, 并写下这一页。</p>
      </>
    ),
    en: (
      <>
        <p>Obsidian shipped in 2020 by Erica Xu and Shida Li, a married couple who previously built the outliner Dynalist. The context: Roam Research had just ignited the "bidirectional links" wave — but Roam was all-cloud, $15/mo, with your data on their servers. Obsidian deliberately went the other way: <em>local-first</em>, the vault is a plain folder on your disk, each note is a .md file, personal use is free forever, only sync and publish are paid.</p>
        <p>2020-2024 was the plugin ecosystem explosion. Dataview (querying notes as a database), Templater (JS-driven templates), Excalidraw (hand-drawn diagrams), Calendar, Tasks — all became near-universal installs. By the time Obsidian 1.0 GA shipped with the proper mobile app in 2024, the "local-first + strong plugins" line had been validated all the way from personal notebooks to publicly published university research vaults.</p>
        <p>2025-2026 is the second discovery — in the AI era. After MCP (Model Context Protocol, released by Anthropic in late 2024), local vaults suddenly became the ideal long-term-memory substrate for LLMs: markdown is the model's most familiar format, files can be read and written programmatically, and an agent can query half a year of your notes directly. The community-built obsidian-mcp-server wires Claude / Cursor into a vault with near-zero ceremony. That is why this site's owner is about to commit to Obsidian, and why this page exists.</p>
      </>
    ),
  },
  history: [
    { year: '2020·03', zh: { title: <>私测开始</>, desc: <>Dynalist 团队 (Erica Xu + Shida Li) 抛出第一个公开 beta。卖点:本地 markdown + 双链 + 图谱视图 + plugin。免费个人用。</> }, en: { title: <>Private beta opens</>, desc: <>The Dynalist team (Erica Xu + Shida Li) ships the first public beta. Pitch: local markdown + bidirectional links + graph view + plugins. Free for personal use.</> } },
    { year: '2020·10', zh: { title: <>v0.9 公开 + Roam 难民迁入</>, desc: <>Roam 涨价 + 服务不稳, 大量用户找替代。Obsidian 的"本地、文件归你"在那一批用户里像甘霖。社区 plugin 商店雏形出现。</> }, en: { title: <>v0.9 public + Roam refugees arrive</>, desc: <>Roam raised prices and had service hiccups; users fled looking for alternatives. Obsidian's "local, files-are-yours" was a relief to that cohort. The community plugin store takes early shape.</> } },
    { year: '2021·06', zh: { title: <>v1 阶段 + plugin 商店</>, desc: <>Community plugins 商店正式上线, 第一批生态 plugin (Dataview / Templater / Calendar) 进入快速迭代。Catalyst 赞助计划开放。</> }, en: { title: <>v1 era + plugin store</>, desc: <>The community plugin store launches officially; the first ecosystem-tier plugins (Dataview / Templater / Calendar) enter rapid iteration. The Catalyst sponsorship tier opens.</> } },
    { year: '2021·11', zh: { title: <>Obsidian Sync 上线</>, desc: <>官方收费同步服务, E2EE, $8/月。给那些不想自己折腾 git / iCloud / Syncthing 的人一条干净的官方路径。</> }, en: { title: <>Obsidian Sync ships</>, desc: <>Official paid sync, end-to-end encrypted, $8/mo. A clean official path for users who don't want to wire git / iCloud / Syncthing themselves.</> } },
    { year: '2022·02', zh: { title: <>Canvas 白板视图</>, desc: <>JSON 描述的无限画布, 节点可以是 note / 图 / web / 卡片, 节点间画线。第一次把"笔记网络可视化"做成第一公民。</> }, en: { title: <>Canvas — infinite whiteboard</>, desc: <>A JSON-described infinite canvas; nodes can be notes / images / webpages / cards, with edges between them. First time "visualize the note network" becomes a first-class feature.</> } },
    { year: '2023·07', zh: { title: <>1.0 GA + 移动端正式版</>, desc: <>桌面 1.0 + iOS / Android 同步正式版。"在手机上写, 在桌面继续, vault 都是同一个文件夹" 这条工作流终于稳。</> }, en: { title: <>1.0 GA + mobile officially out</>, desc: <>Desktop 1.0 plus iOS / Android sync go GA. "Write on phone, continue on desktop, same vault folder" becomes a fully reliable workflow.</> } },
    { year: '2024·05', zh: { title: <>Publish + Properties</>, desc: <>Publish 服务给个人 garden 提供官方托管。Properties 把 frontmatter 升格为一等公民 UI, 笔记开始能像 Notion 一样有结构化字段。</> }, en: { title: <>Publish + Properties</>, desc: <>The Publish service offers official hosting for personal gardens. Properties promote frontmatter into a first-class UI; notes start carrying Notion-like structured fields.</> } },
    { year: '2024·11', zh: { title: <>MCP 协议出现</>, desc: <>Anthropic 发布 Model Context Protocol。社区立刻开始写 obsidian-mcp-server, 把 vault 接进 Claude / Cursor 的 tool 列表。Obsidian 的角色发生质变。</> }, en: { title: <>MCP arrives</>, desc: <>Anthropic releases the Model Context Protocol. The community immediately starts building obsidian-mcp-server to expose vaults to Claude / Cursor as tools. Obsidian's role shifts qualitatively.</> } },
    { year: '2025·06', zh: { title: <>obsidian-cli 工具链成熟</>, desc: <>第三方包 (Yakitrak/obsidian-cli, smithery 等) 让 <code>obsidian get-note "daily/2025-06-20"</code> 这种脚本可用。agent / shell 第一次能直接读 vault。</> }, en: { title: <>obsidian-cli toolchain matures</>, desc: <>Third-party packages (Yakitrak/obsidian-cli, smithery, etc.) make <code>obsidian get-note "daily/2025-06-20"</code> a real command. For the first time agents and shells can read the vault directly.</> } },
    { year: '2025·11', zh: { title: <>MCP server 走入主流</>, desc: <>obsidian-mcp-server 稳定后, Claude Code / Cursor / Cline 几乎所有 agent IDE 都默认能接 vault。"用 Claude 写代码时让它直接 grep 我的笔记" 成为日常。</> }, en: { title: <>MCP server goes mainstream</>, desc: <>Once obsidian-mcp-server stabilizes, virtually every agent IDE (Claude Code / Cursor / Cline) can wire into a vault by default. "Let Claude grep my notes while coding" becomes routine.</> } },
    { year: '2026·02', zh: { title: <>1.7 — Bases + Dataview 4</>, desc: <>1.7 加 Bases (内置数据库视图, 跟 Notion table 对标) + Properties UI 重做。Dataview 进 4.0, query 性能大幅提升。</> }, en: { title: <>1.7 — Bases + Dataview 4</>, desc: <>1.7 ships Bases (built-in DB views, the official answer to Notion tables) and a Properties UI overhaul. Dataview hits 4.0 with sharply improved query performance.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>当前 — 计划上手</>, desc: <>本站 owner 当前 (2026-05) 还没正式把工作流迁过来, 但 plugin 列表 + vault 结构已经设计完。下一年的重点是把 D:\cube 下的散乱 markdown 整理进 vault。</> }, en: { title: <>Now — about to adopt</>, desc: <>As of 2026-05 the site owner has not yet migrated the workflow, but the plugin list and vault layout are designed. The next year's focus is consolidating the scattered markdown under D:\cube into a single vault.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>笔记就是 .md 文件</>, desc: <>vault 是一个普通文件夹, 每个笔记一个 .md。app 关停也不影响读写, 任何编辑器 / git / grep 直接能用。</> }, en: { title: <>A note is a .md file</>, desc: <>The vault is a plain folder, one .md per note. If the app shuts down the files still read with any editor / git / grep.</> }, code: <code>{c('# vault/projects/cuberoot.md')}{'\n'}{c('---')}{'\n'}{p('tags')}: [project, frontend]{'\n'}{p('status')}: active{'\n'}{c('---')}{'\n\n'}# cuberoot.me{'\n\n'}See [[stack/react]] and [[stack/hono]].</code> },
    { tag: 'B', zh: { title: <>[[wiki-link]] 双链</>, desc: <>方括号写文件名直接成链接, 反向链接面板自动维护。重命名一个文件, 所有引用同步改。</> }, en: { title: <>[[wiki-link]] backlinks</>, desc: <>Brackets around a filename become a link; the backlinks panel maintains the inverse automatically. Rename a file and every reference updates.</> }, code: <code>I learned [[CRDT]] from [[Martin Kleppmann]].{'\n'}This relates to [[distributed-systems#consistency|consistency models]].{'\n\n'}{c('// rename "CRDT.md" → "CRDTs.md"')}{'\n'}{c('// all [[CRDT]] references auto-update')}</code> },
    { tag: 'C', zh: { title: <>YAML frontmatter / Properties</>, desc: <>每个笔记顶部可放 YAML 块, 字段在 1.4 之后升级为 Properties 一等公民 UI, 跨笔记可查询。</> }, en: { title: <>YAML frontmatter / Properties</>, desc: <>Every note can carry a YAML block at the top; from 1.4 onward those fields are first-class Properties with a real UI and cross-note query support.</> }, code: <code>{c('---')}{'\n'}{p('title')}: {s('"Obsidian intro"')}{'\n'}{p('date')}: 2026-05-18{'\n'}{p('tags')}: [pkm, markdown, tooling]{'\n'}{p('rating')}: 5{'\n'}{p('related')}: [{s('"[[Roam Research]]"')}, {s('"[[Logseq]]"')}]{'\n'}{c('---')}</code> },
    { tag: 'D', zh: { title: <>Dataview query</>, desc: <>把整个 vault 当数据库查询, 在 markdown 里直接写 SQL-ish DSL。可以列出所有 status=active 的项目, 按 date 排序。</> }, en: { title: <>Dataview query</>, desc: <>Query the whole vault like a database; an SQL-ish DSL embeds inside markdown. List all active projects sorted by date, etc.</> }, code: <code>{s('```dataview')}{'\n'}{k('TABLE')} status, file.mtime {k('as')} {s('"updated"')}{'\n'}{k('FROM')} {s('"projects"')}{'\n'}{k('WHERE')} status = {s('"active"')}{'\n'}{k('SORT')} file.mtime {k('DESC')}{'\n'}{s('```')}</code> },
    { tag: 'E', zh: { title: <>Templater 用 JS 写模板</>, desc: <>插入笔记时跑一段 JS, 拿当前时间 / 文件名 / vault metadata 自动填充。"每天的 daily note" 这种工作流核心靠它。</> }, en: { title: <>Templater — JS templates</>, desc: <>Run a snippet of JS at note-insertion time; pull current date / filename / vault metadata for auto-fills. Daily-note workflows are built on it.</> }, code: <code>{c('# <% tp.date.now("YYYY-MM-DD") %>')}{'\n\n'}{c('## 今日')}{'\n'}{'- [ ] <% '}{f('tp.web.daily_quote')}{'() %>'}{'\n\n'}{c('## 昨日回顾')}{'\n'}{'![[<% '}{f('tp.date.now')}({s('"YYYY-MM-DD"')}, -{n('1')}){' %>]]'}</code> },
    { tag: 'F', zh: { title: <>Canvas 白板</>, desc: <>JSON 描述的无限画布。节点可以是 note embed / 图 / web / 文本卡片, 节点间画线表关系。本质是一个可视化的 graph 数据结构。</> }, en: { title: <>Canvas whiteboard</>, desc: <>A JSON-described infinite canvas. Nodes can be note embeds / images / webpages / text cards; edges show relations. Underneath it's a visualizable graph data structure.</> }, code: <code>{c('// my-board.canvas (just JSON)')}{'\n'}{'{'}{'\n'}  {p('nodes')}: [{'\n'}    {'{ '}{p('id')}: {s('"a"')}, {p('type')}: {s('"file"')}, {p('file')}: {s('"notes/idea.md"')} {'},'}{'\n'}    {'{ '}{p('id')}: {s('"b"')}, {p('type')}: {s('"text"')}, {p('text')}: {s('"todo"')} {'}'}{'\n'}  ],{'\n'}  {p('edges')}: [{'{ '}{p('fromNode')}: {s('"a"')}, {p('toNode')}: {s('"b"')} {'}'}]{'\n'}{'}'}</code> },
    { tag: 'G', zh: { title: <>obsidian:// URI 协议</>, desc: <>系统级 URL scheme。任何 app / 脚本 / 浏览器都能 <code>start obsidian://open?vault=X&file=Y</code> 直接打开笔记。AI agent 的"跳进 Obsidian 看上下文"就靠它。</> }, en: { title: <>obsidian:// URI scheme</>, desc: <>An OS-level URL scheme. Any app / script / browser can <code>start obsidian://open?vault=X&file=Y</code> to jump into a note. AI agents use this to "drop into Obsidian for context."</> }, code: <code>{c('# Windows PowerShell')}{'\n'}{f('Start-Process')} {s('"obsidian://open?vault=cube&file=daily/2026-05-18"')}{'\n\n'}{c('# create a new note')}{'\n'}{f('Start-Process')} {s('"obsidian://new?vault=cube&name=idea&content=hello"')}</code> },
    { tag: 'H', zh: { title: <>MCP server: Claude 读 vault</>, desc: <>obsidian-mcp-server 通过 stdio 暴露一组 tool (search / read / append / link), Claude / Cursor 把它当工具调用。LLM 直接 grep / read / 写你的笔记。</> }, en: { title: <>MCP server: Claude reads the vault</>, desc: <>obsidian-mcp-server exposes a tool set (search / read / append / link) over stdio; Claude / Cursor call them like any other tool. The LLM grep / reads / appends your notes directly.</> }, code: <code>{c('# claude_desktop_config.json')}{'\n'}{'{'}{'\n'}  {p('mcpServers')}: {'{'}{'\n'}    {p('obsidian')}: {'{'}{'\n'}      {p('command')}: {s('"npx"')},{'\n'}      {p('args')}: [{s('"obsidian-mcp-server"')}, {s('"--vault"')}, {s('"D:/cube/vault"')}]{'\n'}    {'}'}{'\n'}  {'}'}{'\n'}{'}'}</code> },
  ],
  whyCards: [
    { icon: '◇', zh: { title: <>本地优先, 数据归你</>, desc: <>vault 是硬盘上的普通文件夹。Obsidian 哪天关停, 你的笔记还是一堆 .md, 任何编辑器都能读。Notion 做不到这一点。</> }, en: { title: <>Local-first — files are yours</>, desc: <>The vault is a plain folder on your disk. If Obsidian shut down tomorrow, your notes remain a folder of .md, readable by any editor. Notion can't promise that.</> }, code: <>{c('// vault/ is just a folder')}{'\n'}{c('// ls vault/projects/*.md')}</> },
    { icon: '⌬', zh: { title: <>双链 + Graph 让结构涌现</>, desc: <><code>[[wiki-link]]</code> 写多了, Graph 视图自然显现知识网络。从未刻意维护分类, 但相关笔记会自己聚成簇。Andy Matuschak evergreen notes 那套理念在这里实现得最干净。</> }, en: { title: <>Bidirectional links let structure emerge</>, desc: <>Write enough <code>[[wiki-links]]</code> and the Graph view exposes the network on its own. You never explicitly maintain taxonomy; related notes cluster themselves. Andy Matuschak's evergreen-notes pattern lives most cleanly here.</> }, code: <>[[CRDT]] cites [[Kleppmann]]{'\n'}[[event sourcing]] cites [[CRDT]]</> },
    { icon: '⛁', zh: { title: <>2000+ plugin, 几乎没空白</>, desc: <>Dataview / Templater / Excalidraw / Calendar / Tasks / Kanban / Mind-map / Vim-mode / Git。需求基本都已经被人写过, 直接装。</> }, en: { title: <>2000+ plugins, almost no gaps</>, desc: <>Dataview / Templater / Excalidraw / Calendar / Tasks / Kanban / Mind-map / Vim-mode / Git. Almost every need has been built; install and go.</> }, code: <>{c('// Community plugins:')}{'\n'}{c('// 2000+ as of 2026-05')}</> },
    { icon: '⚙', zh: { title: <>跟 git 天然兼容</>, desc: <>vault 就是文件夹, .md 是文本, <code>git init</code> + <code>git commit</code> 就行。obsidian-git plugin 还能定时自动 commit + push。</> }, en: { title: <>Plays naturally with git</>, desc: <>The vault is a folder; .md is text. <code>git init</code> + <code>git commit</code> just works. The obsidian-git plugin can even auto-commit + push on a timer.</> }, code: <code>{f('git')} init{'\n'}{f('git')} add .{'\n'}{f('git')} commit -m {s('"daily/2026-05-18"')}</code> },
    { icon: '⏚', zh: { title: <>同步路线多, 自由</>, desc: <>官方 Obsidian Sync ($8/月, E2EE) 是省事路径。git + GitHub / iCloud Drive / Syncthing / Dropbox 全都能用, vault 跟它们没有耦合。</> }, en: { title: <>Many sync paths — your choice</>, desc: <>Official Obsidian Sync ($8/mo, E2EE) is the no-setup path. git + GitHub / iCloud Drive / Syncthing / Dropbox all work — the vault has no coupling to any one.</> }, code: <>{c('// pick one:')}{'\n'}{c('// Obsidian Sync | git | iCloud')}</> },
    { icon: '✦', zh: { title: <>markdown 是 LLM 的母语</>, desc: <>LLM 训练数据里 markdown 占比极大。让 Claude 读 / 写 markdown 比读 / 写 Notion API 或 Roam JSON 准确率显著高。vault 等于天然友好的 LLM 上下文。</> }, en: { title: <>Markdown is the LLM's native tongue</>, desc: <>LLM training data is markdown-heavy. Asking Claude to read / write markdown is notably more accurate than the Notion API or Roam JSON. A vault is naturally LLM-friendly context.</> }, code: <>{c('// LLM accuracy on markdown >')}{'\n'}{c('// any proprietary doc format')}</> },
    { icon: '⌗', zh: { title: <>MCP 把 vault 接进 agent</>, desc: <>obsidian-mcp-server 让 Claude / Cursor 通过 stdio 调用 search / read / append / link 这组工具。"agent 跑代码任务时顺手翻笔记" 在 2026 已经是日常。</> }, en: { title: <>MCP wires the vault into agents</>, desc: <>obsidian-mcp-server exposes search / read / append / link to Claude / Cursor over stdio. "Agent flips through notes mid-task" is routine in 2026.</> }, code: <>{p('tools')}: [{s('"search"')}, {s('"read"')}, {s('"append"')}, {s('"link"')}]</> },
    { icon: '⌖', zh: { title: <>obsidian-cli + URI 走脚本闭环</>, desc: <><code>obsidian get-note daily/2026-05-18</code> / <code>obsidian append "todo: ..."</code> 让 shell / cron / agent 直接操作 vault。比 GUI 还快。</> }, en: { title: <>obsidian-cli + URI for scripts</>, desc: <><code>obsidian get-note daily/2026-05-18</code> / <code>obsidian append "todo: ..."</code> let shells / cron / agents drive the vault directly. Faster than the GUI.</> }, code: <code>{f('obsidian')} append daily/today {s('"- [ ] ship stack page"')}</code> },
    { icon: '⚐', zh: { title: <>不订阅也能用</>, desc: <>个人用永久免费, 没有功能墙。Notion / Roam / Logseq Cloud 都有云锁, Obsidian 没有 —— 你想买 Sync 就买, 不想买拿 git 也行。</> }, en: { title: <>Works without a subscription</>, desc: <>Free forever for personal use, no feature paywall. Notion / Roam / Logseq Cloud all have lock-in; Obsidian doesn't — buy Sync if you want, or stick with git.</> }, code: <>{c('// Personal: $0 forever')}{'\n'}{c('// Sync (optional): $8/mo')}</> },
  ],
  adopters: [
    { name: 'Andy Matuschak', href: 'https://andymatuschak.org', highlight: true, zhNote: 'evergreen notes 概念发明者, 公开 vault', enNote: 'inventor of evergreen notes — public vault' },
    { name: 'Maggie Appleton', href: 'https://maggieappleton.com', highlight: true, zhNote: '数字花园 (digital garden) 代言人, Obsidian-based', enNote: 'voice of the digital-garden movement; Obsidian-based' },
    { name: 'Linking Your Thinking', href: 'https://www.linkingyourthinking.com', highlight: true, zhNote: 'Nick Milo 个人知识管理课程, ~50k 学员', enNote: "Nick Milo's PKM course, ~50k students" },
    { name: 'Bryan Jenks', href: 'https://github.com/tallguyjenks', zhNote: 'YouTube PKM 教学, Obsidian + Dataview 重度用户', enNote: 'PKM YouTuber; heavy Obsidian + Dataview user' },
    { name: 'Curtis McHale', href: 'https://curtismchale.ca', zhNote: '独立顾问, Obsidian-only 工作流', enNote: 'independent consultant on an Obsidian-only workflow' },
    { name: 'Eleanor Konik', href: 'https://www.eleanorkonik.com', zhNote: '历史 / 神话研究者, 公开 vault 与笔记方法学', enNote: 'historian / mythology researcher; public vault and methodology' },
    { name: 'Anthropic engineers (公开)', href: 'https://www.anthropic.com', zhNote: '多位 Anthropic 员工提到日常用 Obsidian + Claude', enNote: 'several Anthropic staff cite daily Obsidian + Claude use' },
    { name: 'Sloan Foundation 资助研究者', zhNote: '独立研究项目把 vault 当公开成果发布', enNote: 'independent research projects publish vaults as deliverables' },
    { name: 'obsidian-mcp-server (社区)', href: 'https://github.com/cyanheads/obsidian-mcp-server', zhNote: '把 vault 暴露给 Claude / Cursor 的事实标准', enNote: 'the de-facto MCP bridge exposing vaults to Claude / Cursor' },
    { name: 'cuberoot.me (计划中)', zhNote: '当前不依赖, 但下一年准备把 D:\\cube 笔记搬进 vault', enNote: 'not yet — but next year plans to consolidate D:\\cube notes into a vault' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>MCP 把 vault 接进 agent 闭环</>, body: <><p>2025 末 obsidian-mcp-server 稳定下来后, "Claude / Cursor / Claude Code 在跑代码任务时同时能 grep / read / append 我的笔记" 从想法变成日常。这件事的二阶效应是: <strong>笔记不再只是给人看的, 也是给 agent 看的长期记忆</strong>。</p><p>对个人开发者意味着: 把设计决策 / 调研结果 / failed experiments 写进笔记的 ROI 暴涨 —— 同一份内容既是个人 PKM 也是 AI 上下文, 一份维护两份用。本站下一年的工作流重构核心就是这一点。</p></> }, en: { title: <>MCP closes the vault-into-agent loop</>, body: <><p>After obsidian-mcp-server stabilized in late 2025, "Claude / Cursor / Claude Code can grep / read / append my notes mid-task" went from an idea to a routine. The second-order effect: <strong>notes are no longer just for humans — they are long-term memory for agents too</strong>.</p><p>For individual developers the ROI on writing down design decisions / research / failed experiments soars: one body of content serves both personal PKM and AI context — maintained once, used twice. That's the heart of this site's next-year workflow rebuild.</p></> } },
    { tag: 'CLI', zh: { title: <>obsidian-cli 工具链成熟</>, body: <><p>2024 年 obsidian-cli 还是几个零散实验, 2025-2026 出现了能用的产品级版本 (Yakitrak/obsidian-cli, mcp-obsidian 内置 cli)。<code>obsidian search</code> / <code>obsidian append</code> / <code>obsidian list</code> 一行命令让 shell 脚本 / cron / agent 都能操作 vault。</p><p>跟 git hook 配合很自然 —— commit message 自动追加进 daily note, cron 每天扫一遍 todo, agent 跑完任务自动归档结果。这是 Obsidian 走出 GUI 的关键一步。</p></> }, en: { title: <>obsidian-cli toolchain matures</>, body: <><p>In 2024 obsidian-cli was a handful of scattered experiments; by 2025-2026 product-grade implementations exist (Yakitrak/obsidian-cli, the bundled cli in mcp-obsidian). <code>obsidian search</code> / <code>obsidian append</code> / <code>obsidian list</code> let shell scripts, cron, and agents all operate on the vault from one line.</p><p>It composes naturally with git hooks — commit messages auto-append into a daily note, cron sweeps a todo list nightly, an agent archives its results when done. This is Obsidian's key step beyond the GUI.</p></> } },
    { tag: 'BASES', zh: { title: <>Bases + Dataview 4 半结构化</>, body: <><p>1.7 的 Bases 是 Obsidian 对 Notion table 的官方回应。配合 Properties + Dataview 4 的查询性能提升, vault 终于能扛"几千个 note 维护一张项目表" 这种场景, 不再只是纯文本笔记。</p></> }, en: { title: <>Bases + Dataview 4 — semi-structured vault</>, body: <><p>The Bases feature in 1.7 is Obsidian's official answer to Notion tables. Combined with Properties + Dataview 4's improved query performance, the vault can finally carry "thousands of notes maintained as a project table" — no longer pure free-text notes.</p></> } },
    { tag: <>RISK</>, zh: { title: <>VC 化压力 + 闭源核心</>, body: <><p>Obsidian 核心是闭源的 (plugin / theme 开源, 主程序不开源)。这一直是个隐性风险:如果团队某天换掌门或被收购, "数据归你" 也许还成立, 但软件可能停更。社区的 obsidian-cli / mcp-server / 替代客户端 (Logseq, Anytype) 在长期看是给 vault 的 backup plan。</p></> }, en: { title: <>VC pressure + closed-source core</>, body: <><p>The Obsidian core is closed source (plugins and themes are open; the binary isn't). It is a latent risk: if the team changes leadership or is acquired, "data is yours" may hold, but the software could stall. Community obsidian-cli / mcp-server / alternative clients (Logseq, Anytype) are the long-term backup plan for vaults.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p><strong>明确写在前面: cuberoot.me 当前代码库不依赖 Obsidian。</strong> 整个 monorepo (<code>packages/client</code> / <code>packages/server</code> / <code>packages/shared</code> / <code>packages/stats-build</code>) 跑起来不需要 vault 存在, 也没有任何运行时 / 构建时调用 vault。把这页放在 /code/stack 是因为它即将进入 owner 的个人工作流, 跟代码库形成 "笔记 ↔ commit ↔ 设计文档" 闭环 —— 写在 /code/stack 比藏在 /timeline 里诚实。</p>
        <p>下一年 (2026-05 至 2027-05) 的迁移计划大致四步:</p>
        <p>1. <strong>整理 D:\cube 下散乱的 markdown 进一个 vault。</strong> 现在 SKILL 文件 / 设计决策 / 调研笔记 / failed experiment 散在 <code>D:\cube\</code>, <code>D:\cube\cuberoot.me\</code>, <code>D:\cube\solver\</code>, <code>.claude\skills\</code> 各处。第一步是把它们按"项目 / 概念 / 日记 / 决策" 四类整合进同一个 vault。<br/>
        2. <strong>把 Claude Code 的 CLAUDE.md / skill / memory 文件视作 vault 的子集。</strong> 这些本质上都是 markdown, 跟 Obsidian 天然兼容。让 Claude Code 直接读 vault 里的设计 doc 跟读 CLAUDE.md 是同一件事。<br/>
        3. <strong>装 obsidian-mcp-server 让 Claude 直接 query / append note。</strong> agent 跑完一个任务把"做了什么 + 为什么这么做"自动追加进 daily note, 长期下来 vault 就是 AI-augmented 工作日志。<br/>
        4. <strong>把 /code/architecture 第 11 节的 timeline 数据半自动从 vault 同步出来。</strong> daily note 里写过的 "今天上线 /foo" 通过脚本提取进 <code>timeline_commits.json</code>, 不用人工维护两份。</p>
        <p>为什么是 Obsidian 而不是 Notion / Logseq: Notion 是云锁 + 私有格式, AI agent 操作要走 API + rate limit, markdown 来回转损耗大。Logseq 路线最近 (block-first / outline-first) 偏激进, 跟 markdown-first 的 LLM 训练分布不太匹配。Obsidian 是<strong>本地优先 + 纯 markdown + plugin 自由 + 不订阅也能用</strong>这四件事同时满足的唯一一个。</p>
        <p>这页就当作给"未来一年的工作流"立一个 flag。一年后回看, 如果 vault 真上手了, 就把 cuberoot 这段改成现在时;如果没上手, 就改成"复盘:为什么没上手"。两种结果都比闷头不写诚实。</p>
      </>
    ),
    en: (
      <>
        <p><strong>To be explicit up front: cuberoot.me's codebase does not depend on Obsidian today.</strong> The whole monorepo (<code>packages/client</code> / <code>packages/server</code> / <code>packages/shared</code> / <code>packages/stats-build</code>) runs without a vault — no runtime, no build-time call into one. This page sits in /code/stack because Obsidian is about to enter the owner's personal workflow, closing a "notes ↔ commits ↔ design docs" loop with the codebase. Putting it in /code/stack is more honest than burying it in /timeline.</p>
        <p>The migration plan for the next year (2026-05 → 2027-05) is roughly four steps:</p>
        <p>1. <strong>Consolidate the scattered markdown under D:\cube into one vault.</strong> SKILL files / design decisions / research notes / failed experiments are currently spread across <code>D:\cube\</code>, <code>D:\cube\cuberoot.me\</code>, <code>D:\cube\solver\</code>, <code>.claude\skills\</code>, and more. Step one is to organize them into a single vault by "project / concept / journal / decision."<br/>
        2. <strong>Treat Claude Code's CLAUDE.md / skill / memory files as a vault subset.</strong> They are all markdown — natively compatible with Obsidian. Letting Claude Code read a design doc in the vault is the same operation as reading CLAUDE.md.<br/>
        3. <strong>Install obsidian-mcp-server so Claude can query / append notes directly.</strong> When an agent finishes a task, it appends "what I did + why" into a daily note. Over time the vault becomes an AI-augmented work journal.<br/>
        4. <strong>Semi-automate the /code/architecture section-11 timeline from vault data.</strong> The "shipped /foo today" lines already in daily notes get extracted by a script into <code>timeline_commits.json</code> — no more dual maintenance.</p>
        <p>Why Obsidian, not Notion / Logseq: Notion is cloud-locked and stores in a proprietary format; AI agents have to go through API + rate limits, with high markdown round-trip loss. Logseq's recent block-first / outline-first direction is more radical and matches the markdown-first LLM training distribution less well. Obsidian is the only one ticking all four of <strong>local-first + pure markdown + plugin freedom + no-subscription-required</strong> at once.</p>
        <p>Treat this page as a flag planted for "next year's workflow." A year from now, if the vault has actually taken hold, this section gets rewritten in the present tense. If it hasn't, it gets rewritten as a postmortem on why not. Either outcome is more honest than not writing it down.</p>
      </>
    ),
  },
  links: [
    { label: 'obsidian.md', href: 'https://obsidian.md' },
    { label: 'Community plugins', href: 'https://obsidian.md/plugins' },
    { label: 'Dataview docs', href: 'https://blacksmithgu.github.io/obsidian-dataview/' },
    { label: 'MCP spec', href: 'https://modelcontextprotocol.io' },
    { label: 'obsidian-mcp-server', href: 'https://github.com/cyanheads/obsidian-mcp-server' },
    { label: 'Yakitrak/obsidian-cli', href: 'https://github.com/Yakitrak/obsidian-cli' },
  ],
};

export default OBSIDIAN;
