import type { StackTool } from '../stack_tool_types';
import { k, v, s, n, f, p, c } from '../stack_tool_types';

// ─── Three.js r184 ──────────────────────────────────────────────────────────

export const THREE: StackTool = {
  slug: 'three',
  name: 'Three.js',
  version: 'r184',
  since: '2010-04',
  group: 'frontend',
  accent: '#049EF4',
  bright: '#5BC3F9',
  glyph: '△',
  floats: ['Scene', 'Mesh', 'Geometry', 'Material', 'WebGLRenderer', 'WebGPURenderer', 'PerspectiveCamera', 'GLTFLoader', 'BufferGeometry', 'ShaderMaterial', 'TSL', 'r184'],
  zh: {
    tagline: '浏览器里写 3D 的事实标准',
    role: '本站所有 3D 魔方渲染的底层。TwistyPlayer / sq1 demo 都跑在 three.js 上。',
    heroSub: <>Ricardo Cabello (Mr.doob) 2010 年 4 月把一份 ActionScript 3D 引擎 port 成 JS 推到 GitHub, 十六年后 WebGL2 / WebGPU / GLTF / TSL 节点材质全部围绕这一棵树长起来。声明 Scene、塞进 Mesh、给个 Camera 和 Renderer, 一帧画出来。</>,
    whatDesc: <>three.js 是一个 <strong>3D 渲染库</strong>, 不是引擎。它只负责"把场景图变成屏幕上的像素"这一段 —— 物理 / 动画状态机 / ECS / 资源管线全部交给生态。这种克制让它在游戏外的应用 (产品展示、数据可视化、工业 CAD、艺术装置) 取得近乎垄断的地位。</>,
    historyDesc: <>从 2010 年第一版 SVG / Canvas / WebGL 三 renderer 并存, 到 2023 年 r150 把内部模块结构大重写, 再到 2025 年 r180+ 把 WebGPU + TSL (节点着色器) 推上一线 path, three.js 一直处在 web 3D 演进的最前沿。每个 revision 都是月度发布, 16 年保持节奏没断。</>,
    conceptsTitle: '场景图 + 渲染器核心',
    conceptsDesc: <>three.js 的核心抽象其实就 5 个:Scene、Object3D (含 Mesh / Group / Light / Camera)、Geometry、Material、Renderer。其它一切 (loader / control / postprocess) 都搭在这五个原子之上。</>,
    whyDesc: <>2026 年还选 three.js, 不是因为它"快"或"小", 而是因为它的<strong>覆盖面</strong>、<strong>文档密度</strong>、<strong>三方生态</strong> 在 web 3D 这条线上没有竞品能赶上。Babylon / PlayCanvas 单看某些维度更强, 但通用程度差一档。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>从 Google Earth (Maps Lite) 到 NASA Eyes、Bruno Simon 的 portfolio、Active Theory 整个公司、Apple Vision Pro 早期 demo, 都跑在 three.js 上。WebGL 这条线几乎等同于 three.js 这条线。</>,
    cuberootDesc: <>本站所有 3D 魔方渲染都站在 three.js 肩膀上。一条路径是<strong>间接的</strong> —— cubing.js 的 <code>TwistyPlayer</code> 内部用 three.js 画三维 cube, 这个组件出现在 <code>/trainer</code>、<code>/recon</code>、<code>/algdb</code> 等页。另一条是<strong>直接的</strong> —— <code>/demo/sq1</code> 这页绕开 TwistyPlayer 直接用 three, 手写 PerspectiveCamera + 自定义 BufferGeometry + per-piece matrix 累乘做 Square-1 的 slice / 旋转动画。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>WebGPU 终于在 Chrome / Safari 26 / Firefox 都默认开启;TSL (Three Shading Language) 让节点材质成为一等公民, 一份材质同时编译到 WebGL2 GLSL 和 WebGPU WGSL;r183 引入的 RenderPipeline 把后处理重新做成节点图;r184 进一步收紧内存分配。</>,
  },
  en: {
    tagline: 'The de facto standard for 3D in the browser',
    role: 'The renderer behind every 3D cube on this site — TwistyPlayer and the sq1 demo both ride three.js.',
    heroSub: <>Ricardo Cabello (Mr.doob) ported an ActionScript engine to JavaScript and pushed it to GitHub in April 2010. Sixteen years later, WebGL2 / WebGPU / GLTF / TSL node materials all grew around the same tree. Declare a Scene, drop in a Mesh, hand it a Camera and a Renderer, and you have a frame.</>,
    whatDesc: <>three.js is a <strong>3D rendering library</strong>, not an engine. It owns the "scene graph to pixels" segment only — physics, animation state machines, ECS, asset pipelines all live in the ecosystem. That restraint is exactly why it has come to near-monopoly status outside games (product showcases, data viz, industrial CAD, art installations).</>,
    historyDesc: <>From the 2010 first release with SVG / Canvas / WebGL renderers side-by-side, through the r150 internal rewrite in 2023, to r180+ in 2025 pushing WebGPU + TSL (node shaders) onto the primary path, three.js has stayed at the leading edge of web 3D. Monthly revisions, sixteen years, never missed a beat.</>,
    conceptsTitle: 'Scene graph + renderer core',
    conceptsDesc: <>The core abstractions are basically five: Scene, Object3D (Mesh / Group / Light / Camera), Geometry, Material, Renderer. Loaders, controls, postprocess — everything else stacks on top of those five atoms.</>,
    whyDesc: <>Picking three.js in 2026 isn't because it's "fast" or "small" — it's because three things still beat alternatives in web 3D: <strong>breadth of coverage</strong>, <strong>documentation density</strong>, and <strong>third-party ecosystem</strong>. Babylon / PlayCanvas may win specific axes, but general-purpose reach trails by one tier.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>From Google Earth (Maps Lite) to NASA Eyes, Bruno Simon's portfolio, the entire Active Theory studio, early Apple Vision Pro demos — they all ride three.js. The WebGL line is roughly the three.js line.</>,
    cuberootDesc: <>Every 3D cube on this site stands on three.js. One path is <strong>indirect</strong>: cubing.js's <code>TwistyPlayer</code> uses three.js internally, and that component shows up in <code>/trainer</code>, <code>/recon</code>, <code>/algdb</code>, etc. The other path is <strong>direct</strong>: <code>/demo/sq1</code> bypasses TwistyPlayer and uses three.js straight — a hand-built PerspectiveCamera, custom BufferGeometry, and per-piece matrix composition driving the Square-1 slice / rotation animation.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>WebGPU is finally on-by-default in Chrome / Safari 26 / Firefox. TSL (Three Shading Language) makes node materials first-class — one material compiles to both WebGL2 GLSL and WebGPU WGSL. The r183 RenderPipeline redoes postprocessing as a node graph; r184 further tightens per-frame allocations.</>,
  },
  heroStats: [
    { num: '#1', zh: <>web 3D 库使用率 <em>State of JS 2025</em></>, en: <>web 3D library by usage <em>State of JS 2025</em></> },
    { num: '110', unit: 'k★', zh: <>GitHub star <em>2026-05 · 全球前 25</em></>, en: <>GitHub stars <em>2026-05 · global top 25</em></> },
    { num: '16', unit: 'y', zh: <>从 2010 至今 <em>月度发布从未断</em></>, en: <>since 2010 <em>monthly cadence unbroken</em></> },
    { num: 'r', unit: '184', zh: <>当前稳定 revision <em>2026-03 · 0.184.0</em></>, en: <>current stable revision <em>2026-03 · 0.184.0</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>three.js 起源是 Ricardo Cabello (网名 Mr.doob) 在 Flash 时代写的一个 ActionScript 3D 引擎。2010 年 4 月浏览器开始有 WebGL, Cabello 把同一套 API 用 JS 重写一遍推上 GitHub, 名字取自 "JavaScript 3D"。第一版同时跑 SVG / Canvas / WebGL 三个 renderer, 哪个能跑用哪个 —— 这种"硬件加速可选"的设计在当年还有意义。</p>
        <p>之后 16 年 three.js 月度发布从未停。r 编号一路从 r1 走到 r184。期间 WebGL 1 → 2、GLTF 取代 OBJ / Collada、Physically-Based Rendering 进 core、postprocessing 重写两次、loader / controls / examples 全部稳态扩张。Mr.doob 仍是主维护者, WestLangley、Mugen87、gkjohnson 等长期 contributor 撑起了核心 PR 流。</p>
        <p>2023 年 r150 是一次大转折 —— 内部模块拆分、ES modules-only、CommonJS 入口移除。2025 年 r180+ 把 WebGPU + TSL 推到一线: 节点式材质一份代码同时编译到 WebGL2 (GLSL) 和 WebGPU (WGSL)。整个 web 3D 行业仍在围绕这棵树长, 没有第二个候选具备同等覆盖面。</p>
      </>
    ),
    en: (
      <>
        <p>three.js started as Ricardo Cabello's (a.k.a. Mr.doob) ActionScript engine from the Flash era. In April 2010, when WebGL first reached browsers, Cabello rewrote the same API in JavaScript and pushed it to GitHub — the name is literally "JavaScript 3D." The very first release shipped three renderers side by side: SVG, Canvas, and WebGL — pick whichever the device could run. "Hardware acceleration optional" still made sense back then.</p>
        <p>Sixteen years on, the monthly cadence has never broken. The r-numbers walked from r1 to r184. Along the way: WebGL 1 → 2, GLTF replacing OBJ / Collada, Physically-Based Rendering into core, postprocessing rewritten twice, loaders / controls / examples expanding into a steady state. Mr.doob is still the lead maintainer; long-tail contributors like WestLangley, Mugen87, and gkjohnson keep the PR firehose flowing.</p>
        <p>r150 in 2023 was a pivot: internal module split, ES-modules-only, CommonJS entry dropped. From r180 in late 2025, WebGPU + TSL became the headline path — node-based materials whose single source compiles to both WebGL2 (GLSL) and WebGPU (WGSL). The whole web-3D industry still orbits this tree; no second candidate matches its coverage.</p>
      </>
    ),
  },
  history: [
    { year: '2010·04', zh: { title: <>第一次推 GitHub</>, desc: <>Ricardo Cabello 把自己 Flash 时代的 ActionScript 3D 引擎用 JS 重写, 推上 GitHub。第一版同时含 SVG / Canvas / WebGL 三个 renderer。</> }, en: { title: <>First push to GitHub</>, desc: <>Cabello rewrites his ActionScript engine from the Flash era in JS and pushes to GitHub. First release ships SVG / Canvas / WebGL renderers side by side.</> } },
    { year: '2011', zh: { title: <>WebGL 主导, examples 起飞</>, desc: <>WebGL 在 Chrome / Firefox 默认开启。three.js examples 仓库爆炸式增长, 一时间所有 WebGL 教程都在用它。</> }, en: { title: <>WebGL leads, examples explode</>, desc: <>WebGL ships on by default in Chrome / Firefox. The examples repo balloons; for a moment every WebGL tutorial uses three.js.</> } },
    { year: '2014', zh: { title: <>Google Earth Lite 选用</>, desc: <>Google Maps 的轻量级 Earth 视图用 three.js 渲染。同期 NASA / Apple 的多个公开 demo 跟进, three.js 进入"严肃 production"阶段。</> }, en: { title: <>Adopted by Google Earth Lite</>, desc: <>Google Maps' lightweight Earth view runs on three.js. NASA and Apple ship public demos in the same period; three.js enters "serious production."</> } },
    { year: '2017·08', zh: { title: <>r87 / GLTF 进 core</>, desc: <>GLTF 2.0 loader 进入 examples, 后逐渐变成 three.js 推荐资产格式, OBJ / Collada 退到二线。</> }, en: { title: <>r87 / GLTF in core</>, desc: <>GLTF 2.0 loader lands in examples and later becomes the recommended asset format. OBJ / Collada step into the back row.</> } },
    { year: '2019·04', zh: { title: <>r103 / PBR 默认</>, desc: <>MeshStandardMaterial / MeshPhysicalMaterial 成为推荐材质, 让 three.js 的输出和 Blender / Substance 主流 PBR 工作流对齐。</> }, en: { title: <>r103 / PBR by default</>, desc: <>MeshStandardMaterial / MeshPhysicalMaterial become the recommended materials, aligning three.js output with Blender / Substance PBR workflows.</> } },
    { year: '2020·07', zh: { title: <>react-three-fiber 起势</>, desc: <>Poimandres 团队的 react-three-fiber 把 three.js 包成 React 组件树。从此 "声明式 3D" 成为 React 生态的官方答案。</> }, en: { title: <>react-three-fiber takes off</>, desc: <>Poimandres ships react-three-fiber, wrapping three.js as a React component tree. "Declarative 3D" becomes the official React-ecosystem answer.</> } },
    { year: '2021·05', zh: { title: <>r128 / WebXR + WebGL2</>, desc: <>WebXR 入 core, three.js 成为 web VR / AR 的事实运行时。WebGL2 context 也开始切默认。</> }, en: { title: <>r128 / WebXR + WebGL2</>, desc: <>WebXR lands in core; three.js becomes the de facto runtime for web VR / AR. WebGL2 context starts becoming the default.</> } },
    { year: '2022·11', zh: { title: <>r147 / WebGPU 实验入 examples</>, desc: <>第一版 WebGPURenderer 进 examples 目录, 当时还不稳, 但 API 雏形已经定型 —— 后面三年围绕这条线长。</> }, en: { title: <>r147 / experimental WebGPU in examples</>, desc: <>First WebGPURenderer lands in examples — unstable, but the API shape stabilizes. The next three years all branch off this line.</> } },
    { year: '2023·02', zh: { title: <>r150 / 内部大重写</>, desc: <>模块结构拆分、ES modules-only、CommonJS 入口移除。是 three.js 历史上少有的"破坏性"大版本, 升级清单超过 100 条。</> }, en: { title: <>r150 / internal rewrite</>, desc: <>Module split, ES-modules-only, CommonJS entry dropped. One of the rare breaking majors in three.js history — upgrade checklist over 100 items.</> } },
    { year: '2024·06', zh: { title: <>r166 / TSL 正式登场</>, desc: <>Three Shading Language (TSL) 节点材质从实验转正, 一份材质同时编译 GLSL + WGSL。Mugen87 主导。</> }, en: { title: <>r166 / TSL goes mainstream</>, desc: <>Three Shading Language (TSL) graduates from experimental — a single node material compiles to both GLSL and WGSL. Driven by Mugen87.</> } },
    { year: '2025·09', zh: { title: <>r180 / WebGPU 主路径</>, desc: <>WebGPURenderer 不再是"实验性"。文档把"WebGL renderer vs WebGPU renderer"并列推荐, GLTF loader 加 userData 全面支持。</> }, en: { title: <>r180 / WebGPU as primary path</>, desc: <>WebGPURenderer is no longer flagged "experimental." Docs recommend WebGL and WebGPU renderers side by side; GLTF loader gains full userData support.</> } },
    { year: '2025·12', zh: { title: <>r183 / RenderPipeline</>, desc: <>后处理重写成节点图 RenderPipeline, 取代原来 "EffectComposer + Pass 数组" 的写法。Postprocessing 这条历史包袱卸下。</> }, en: { title: <>r183 / RenderPipeline</>, desc: <>Postprocessing is rewritten as a node graph called RenderPipeline, replacing the old "EffectComposer + Pass array" pattern. A long-standing legacy is finally retired.</> } },
    { year: '2026·03', highlight: true, zh: { title: <>r184 / HTMLTexture + 内存收紧</>, desc: <>r184 加入 HTMLTexture (把 DOM 节点当贴图)、消除每帧对象分配、@rollup/plugin-terser 升 1.0。当前稳定版 0.184.0, npm 周下载 ~140 万。</> }, en: { title: <>r184 / HTMLTexture + memory tighten</>, desc: <>r184 adds HTMLTexture (DOM nodes as textures), eliminates per-frame allocations, bumps @rollup/plugin-terser to 1.0. Current stable 0.184.0; ~1.4M weekly npm downloads.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>当前 / 本站使用中</>, desc: <>cuberoot.me 锁在 cubing.js 内置的 three 版本, /demo/sq1 直接 import 'three' 用同一份。WebGPU 路径暂未启用 —— TwistyPlayer 自己还在 WebGL2 path。</> }, en: { title: <>Today / live on this site</>, desc: <>cuberoot.me uses the three version pinned by cubing.js; /demo/sq1 imports 'three' directly and shares it. WebGPU path is not yet enabled — TwistyPlayer is still on WebGL2.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>Scene + Object3D</>, desc: <>场景图。所有可渲染 / 可变换的东西都继承自 Object3D, 通过 add() 形成父子树。</> }, en: { title: <>Scene + Object3D</>, desc: <>The scene graph. Everything renderable or transformable extends Object3D and forms a parent / child tree via add().</> }, code: <code>{k('const')} {v('scene')} = {k('new')} {f('THREE.Scene')}();{'\n'}{v('scene')}.{f('add')}({v('mesh')});{'\n'}{v('scene')}.{f('add')}({v('light')});</code> },
    { tag: 'B', zh: { title: <>Geometry + Material → Mesh</>, desc: <>几何体描述顶点 / 索引, 材质描述着色。两者绑成一个 Mesh 才能渲染。</> }, en: { title: <>Geometry + Material → Mesh</>, desc: <>Geometry holds vertices / indices, Material holds shading. Pair them into a Mesh to render.</> }, code: <code>{k('const')} {v('geo')} = {k('new')} {f('THREE.BoxGeometry')}({n('1')}, {n('1')}, {n('1')});{'\n'}{k('const')} {v('mat')} = {k('new')} {f('THREE.MeshStandardMaterial')}({'{ '}{p('color')}: {s("'#049EF4'")} {'}'});{'\n'}{k('const')} {v('mesh')} = {k('new')} {f('THREE.Mesh')}({v('geo')}, {v('mat')});</code> },
    { tag: 'C', zh: { title: <>Camera</>, desc: <>透视 (PerspectiveCamera) 或正交 (OrthographicCamera) 投影。设置位置、朝向, 渲染器从它的视角取一帧。</> }, en: { title: <>Camera</>, desc: <>Perspective or orthographic projection. Place it, aim it, and the renderer draws a frame from its viewpoint.</> }, code: <code>{k('const')} {v('cam')} = {k('new')} {f('THREE.PerspectiveCamera')}({n('50')}, {v('aspect')}, {n('0.1')}, {n('1000')});{'\n'}{v('cam')}.{p('position')}.{f('set')}({n('5')}, {n('5')}, {n('5')});{'\n'}{v('cam')}.{f('lookAt')}({n('0')}, {n('0')}, {n('0')});</code> },
    { tag: 'D', zh: { title: <>WebGLRenderer / WebGPURenderer</>, desc: <>两种渲染后端。WebGL2 是稳态默认, WebGPU 在 r180 后成为推荐次选, 同 scene / mesh / 材质都能复用。</> }, en: { title: <>WebGLRenderer / WebGPURenderer</>, desc: <>Two backends. WebGL2 is the steady default; WebGPU is the recommended alternative from r180 onward. The same scene / mesh / material works on either.</> }, code: <code>{k('const')} {v('renderer')} = {k('new')} {f('THREE.WebGLRenderer')}({'{ '}{p('antialias')}: {k('true')} {'}'});{'\n'}{v('renderer')}.{f('setSize')}({v('w')}, {v('h')});{'\n'}{v('renderer')}.{f('render')}({v('scene')}, {v('cam')});</code> },
    { tag: 'E', zh: { title: <>BufferGeometry</>, desc: <>底层几何容器。用 typed array 直接喂 position / normal / uv / index, 自定义形状走这一层。</> }, en: { title: <>BufferGeometry</>, desc: <>Low-level geometry container. Feed typed arrays for position / normal / uv / index directly — custom shapes go through this layer.</> }, code: <code>{k('const')} {v('g')} = {k('new')} {f('THREE.BufferGeometry')}();{'\n'}{v('g')}.{f('setAttribute')}({'\n'}  {s("'position'")},{'\n'}  {k('new')} {f('THREE.BufferAttribute')}({v('verts')}, {n('3')}){'\n'});</code> },
    { tag: 'F', zh: { title: <>GLTFLoader</>, desc: <>读 .gltf / .glb 文件。返回 scene + animations + cameras。是 three.js 推荐的资产入口。</> }, en: { title: <>GLTFLoader</>, desc: <>Loads .gltf / .glb files, returning scene + animations + cameras. The recommended asset entry for three.js.</> }, code: <code>{k('const')} {v('loader')} = {k('new')} {f('GLTFLoader')}();{'\n'}{v('loader')}.{f('load')}({s("'/cube.glb'")}, ({v('gltf')}) =&gt; {'{'}{'\n'}  {v('scene')}.{f('add')}({v('gltf')}.{p('scene')});{'\n'}{'}'});</code> },
    { tag: 'G', zh: { title: <>ShaderMaterial / TSL</>, desc: <>自定义着色器。手写 GLSL 走 ShaderMaterial; r166 起推荐用 TSL 节点, 同一份代码同时跑 WebGL + WebGPU。</> }, en: { title: <>ShaderMaterial / TSL</>, desc: <>Custom shaders. Hand-write GLSL via ShaderMaterial; from r166, TSL node materials are preferred — one source runs on both WebGL and WebGPU.</> }, code: <code>{k('const')} {v('mat')} = {k('new')} {f('THREE.ShaderMaterial')}({'{'}{'\n'}  {p('vertexShader')}: {v('vs')},{'\n'}  {p('fragmentShader')}: {v('fs')},{'\n'}{'}'});</code> },
    { tag: 'H', zh: { title: <>InstancedMesh</>, desc: <>同一 geometry + material 画一万次, GPU 上一次 draw call。本站魔方贴纸 / 多块体都靠它。</> }, en: { title: <>InstancedMesh</>, desc: <>Draw the same geometry + material ten thousand times in a single GPU draw call. The site's cube stickers / multi-cubie meshes rely on it.</> }, code: <code>{k('const')} {v('inst')} = {k('new')} {f('THREE.InstancedMesh')}({v('geo')}, {v('mat')}, {n('27')});{'\n'}{v('inst')}.{f('setMatrixAt')}({n('0')}, {v('m')});{'\n'}{v('inst')}.{p('instanceMatrix')}.{p('needsUpdate')} = {k('true')};</code> },
    { tag: 'I', zh: { title: <>Animation loop</>, desc: <>requestAnimationFrame + setAnimationLoop。每帧改变换 / 触发 tween / 调 renderer.render()。</> }, en: { title: <>Animation loop</>, desc: <>requestAnimationFrame + setAnimationLoop. Each frame mutate transforms / run tweens / call renderer.render().</> }, code: <code>{v('renderer')}.{f('setAnimationLoop')}(() =&gt; {'{'}{'\n'}  {v('mesh')}.{p('rotation')}.{p('y')} += {n('0.01')};{'\n'}  {v('renderer')}.{f('render')}({v('scene')}, {v('cam')});{'\n'}{'}'});</code> },
  ],
  whyCards: [
    { icon: '⚙', zh: { title: <>覆盖面无人能及</>, desc: <>从一个旋转立方体的 hello world 到 GLTF + PBR + WebGPU 工业级管线, 同一棵 API 树都能撑。Babylon 在游戏轴线更强, 但通用度差一档。</> }, en: { title: <>Unmatched breadth</>, desc: <>From a hello-world spinning cube to GLTF + PBR + WebGPU industrial pipelines, the same API tree carries it all. Babylon wins on the game axis, but general-purpose reach lags one tier.</> }, code: <>{c('// One library, hello-world to AAA')}{'\n'}{k('import')} * {k('as')} THREE {k('from')} {s("'three'")};</> },
    { icon: '⌬', zh: { title: <>文档 + examples 密度</>, desc: <>官方 examples 600+ 个, 每个都可点击源码看实现。<strong>threejs.org/examples</strong> 是 web 3D 入门的事实教科书。</> }, en: { title: <>Docs + examples density</>, desc: <>The official examples page has 600+ entries, each linking straight to source. <strong>threejs.org/examples</strong> is the de facto textbook for getting into web 3D.</> }, code: <>{c('// 600+ examples, click-to-source')}{'\n'}{c('// threejs.org/examples')}</> },
    { icon: '⎇', zh: { title: <>react-three-fiber 整合</>, desc: <>Poimandres 团队的 r3f 把 three.js 包成 React 组件。&lt;mesh&gt;&lt;boxGeometry /&gt;&lt;meshStandardMaterial /&gt;&lt;/mesh&gt; 直接声明, 状态管理 / hooks 全部复用 React 生态。</> }, en: { title: <>react-three-fiber integration</>, desc: <>Poimandres' r3f wraps three.js as React components. Declare &lt;mesh&gt;&lt;boxGeometry /&gt;&lt;meshStandardMaterial /&gt;&lt;/mesh&gt; directly; state / hooks reuse the React ecosystem.</> }, code: <>&lt;{f('mesh')}&gt;&lt;{f('boxGeometry')} /&gt;&lt;{f('meshStandardMaterial')} /&gt;&lt;/{f('mesh')}&gt;</> },
    { icon: '⌁', zh: { title: <>WebGPU + TSL 落地</>, desc: <>r180 起 WebGPURenderer 与 WebGL2 并列推荐。TSL 节点材质让一份 shader 同时跑两套后端 —— 没有第二个引擎做到。</> }, en: { title: <>WebGPU + TSL landed</>, desc: <>From r180 the WebGPURenderer is co-recommended with WebGL2. TSL node materials run the same shader on both backends — no other engine has shipped this.</> }, code: <>{k('const')} {v('mat')} = {f('MeshStandardNodeMaterial')}();{'\n'}{c('// runs on WebGL2 + WebGPU')}</> },
    { icon: '⌖', zh: { title: <>npm 周下载 140 万</>, desc: <>2026-05 数据:three 包周下载 ~140 万次。web 3D 这条线里, babylon (~10 万) 跟它差一个量级以上。</> }, en: { title: <>1.4M weekly downloads</>, desc: <>As of 2026-05: ~1.4M weekly downloads for the three package. In web 3D, Babylon (~100K) trails by more than an order of magnitude.</> }, code: <>{c('// npm: three weekly ~1.4M')}{'\n'}{c('// npm: babylon weekly ~100K')}</> },
    { icon: '⌗', zh: { title: <>cubing.js 的底座</>, desc: <>整个 cubing.js 的 3D 渲染 (TwistyPlayer 组件) 都构建在 three.js 上。本站 <code>/trainer</code> / <code>/recon</code> / <code>/algdb</code> 间接共享这条管线。</> }, en: { title: <>The base layer of cubing.js</>, desc: <>All of cubing.js's 3D rendering (the TwistyPlayer component) is built on three.js. This site's <code>/trainer</code> / <code>/recon</code> / <code>/algdb</code> ride that pipeline indirectly.</> }, code: <>{k('import')} {'{'} {v('TwistyPlayer')} {'}'} {k('from')} {s("'cubing/twisty'")};{'\n'}{c('// three.js inside')}</> },
    { icon: '⏚', zh: { title: <>16 年月度发布从未断</>, desc: <>r1 (2010-04) 到 r184 (2026-03), 每月一个 revision, 节奏稳到极致。版本号即时间戳, 升级路径线性可读。</> }, en: { title: <>16 years of uninterrupted monthly cadence</>, desc: <>r1 (2010-04) to r184 (2026-03), one revision a month, rhythm steady to the point of being predictable. The version number doubles as a timestamp; the upgrade path reads linearly.</> }, code: <>{c('// r1 → r184')}{'\n'}{c('// 16 years, monthly')}</> },
    { icon: '⛯', zh: { title: <>资产格式跟工业流水线对齐</>, desc: <>GLTF 2.0 + Draco 压缩 + KTX2 贴图。Blender / Substance / Maya 一键导出的资产直接进 three.js, 不需要中间转换。</> }, en: { title: <>Asset formats aligned with industrial pipelines</>, desc: <>GLTF 2.0 + Draco compression + KTX2 textures. Assets exported one-click from Blender / Substance / Maya drop straight into three.js with no middle conversion.</> }, code: <>{c('// Blender → .glb → three.js')}{'\n'}{f('GLTFLoader')}.{f('load')}({s("'/x.glb'")});</> },
    { icon: '⚐', zh: { title: <>实战护栏 (three-mesh-bvh 等)</>, desc: <>gkjohnson 维护的 three-mesh-bvh 让 raycast / 碰撞检测从"几千面卡顿"提到"几十万面流畅"。这种社区工具填补了 three.js 自身不做的工程缝隙。</> }, en: { title: <>Battle-tested side packages (three-mesh-bvh etc.)</>, desc: <>gkjohnson's three-mesh-bvh lifts raycast / collision from "thousands of faces is slow" to "hundreds of thousands is smooth." Community tooling like this fills the engineering gaps three.js intentionally leaves out.</> }, code: <>{k('import')} {'{'} {v('MeshBVH')} {'}'} {k('from')} {s("'three-mesh-bvh'")};</> },
  ],
  adopters: [
    { name: 'Google Earth / Maps Lite', highlight: true, zhNote: 'web 上轻量地球视图核心渲染', enNote: 'Lightweight Earth view in Maps — three.js renders' },
    { name: 'NASA Eyes', href: 'https://eyes.nasa.gov', zhNote: '太阳系探测器实时位置可视化', enNote: 'Live solar-system probe visualization' },
    { name: 'Bruno Simon · bruno-simon.com', href: 'https://bruno-simon.com', highlight: true, zhNote: 'three.js 教学与个人 portfolio 标杆', enNote: 'Benchmark personal portfolio + three.js teacher' },
    { name: 'Active Theory', href: 'https://activetheory.net', zhNote: '整家公司围绕 three.js + WebGL 接活', enNote: 'A whole studio built around three.js + WebGL' },
    { name: 'Igloo Inc.', href: 'https://igloo.inc', zhNote: '获 Awwwards Site of the Year, 全 r3f', enNote: 'Awwwards Site of the Year, entirely r3f' },
    { name: 'Apple Vision Pro (Hologram 早期 demo)', zhNote: 'visionOS web 端 3D 演示', enNote: 'visionOS-side web 3D demos' },
    { name: 'react-three-fiber', href: 'https://r3f.docs.pmnd.rs', highlight: true, zhNote: 'Poimandres, three.js 的 React 包装', enNote: 'Poimandres, the React wrapping of three.js' },
    { name: 'Sketchfab', href: 'https://sketchfab.com', zhNote: '在线 3D 模型仓库 web viewer', enNote: 'Online 3D model repository web viewer' },
    { name: 'Spline', href: 'https://spline.design', zhNote: '可视化 3D 编辑器 web 运行时', enNote: 'Visual 3D editor web runtime' },
    { name: 'TheFWA / 大量获奖作品', href: 'https://thefwa.com', zhNote: 'FWA Site of the Year 多次得主用 three.js', enNote: 'Repeat FWA Site-of-the-Year winners' },
    { name: 'cubing.js · TwistyPlayer', href: 'https://github.com/cubing/cubing.js', highlight: true, zhNote: '魔方 3D 渲染组件, 间接服务 TwistyPlayer 全部使用者', enNote: 'Cube 3D rendering component — TwistyPlayer downstream uses it' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 /demo/sq1 直用 three; trainer / recon / algdb 经 cubing.js 间接用', enNote: 'This site — /demo/sq1 uses three directly; trainer / recon / algdb use it via cubing.js' },
  ],
  outlook: [
    { tag: <>HOT · 2025-09</>, hot: true, big: true, zh: { title: <>WebGPU 成主路径</>, body: <><p>r180 把 WebGPURenderer 从"实验性"摘掉, 文档把 WebGL renderer 和 WebGPU renderer 并列推荐。Chrome / Safari 26 / Firefox 都默认开启 WebGPU 后, three.js 是<strong>第一个</strong>提供"同一份 API, 两套后端"无缝切换的库。</p><p>更深一层意义:Compute shader 第一次在 three.js 主流接口里出现。粒子模拟 / 物理 / BVH 构建这些以前必须靠 CPU 或者 fragment shader hack 的活儿, 现在可以直接走 WebGPU compute。three.js 从"渲染库"开始往"通用 GPU 编程入口"延伸。</p></> }, en: { title: <>WebGPU as the primary path</>, body: <><p>r180 graduated the WebGPURenderer out of "experimental"; docs now co-recommend WebGL and WebGPU renderers. With WebGPU on by default in Chrome / Safari 26 / Firefox, three.js is the <strong>first</strong> library to ship "one API, two backends" as a seamless switch.</p><p>The deeper point: compute shaders finally land in three.js's mainstream surface. Particle simulation, physics, BVH construction — work that used to demand CPU or fragment-shader hacks — can now go through WebGPU compute directly. three.js starts to extend from "rendering library" toward "general-purpose GPU entry point."</p></> } },
    { tag: 'TSL', zh: { title: <>Three Shading Language</>, body: <><p>TSL 节点材质让 shader 不再是"写一份 GLSL, 再写一份 WGSL"。同一份 JS 表达 (color = mix(a, b, t)) 编译到两套后端。Mugen87 主导, 2024 年从实验转正, 2026 年逐渐渗透到 examples / 第三方教程。</p></> }, en: { title: <>Three Shading Language</>, body: <><p>TSL node materials kill the "write GLSL, then rewrite WGSL" tax. One JS expression (color = mix(a, b, t)) compiles to both backends. Driven by Mugen87, graduated from experimental in 2024, by 2026 it has permeated examples and third-party tutorials.</p></> } },
    { tag: 'PIPELINE', zh: { title: <>RenderPipeline 取代 EffectComposer</>, body: <><p>r183 引入的 RenderPipeline 把后处理整成节点图, 取代用了多年的 "EffectComposer + Pass 数组" 写法。Bloom / SSAO / DOF 等效果以节点形式串起来, 跟 TSL 节点同一套思维。</p></> }, en: { title: <>RenderPipeline replaces EffectComposer</>, body: <><p>The RenderPipeline introduced in r183 turns postprocessing into a node graph, replacing the long-standing "EffectComposer + Pass array" pattern. Bloom / SSAO / DOF chain together as nodes, sharing the same mental model as TSL.</p></> } },
    { tag: 'XR', zh: { title: <>WebXR + visionOS</>, body: <><p>WebXR API 稳定后, three.js 已是 web VR / AR 事实运行时。Apple Vision Pro 上的 visionOS Safari 支持 WebXR, 一份 three.js scene 直接进沉浸式视图。Hologram / 立体展示这类应用爆发式增长。</p></> }, en: { title: <>WebXR + visionOS</>, body: <><p>With WebXR APIs stabilized, three.js is the de facto runtime for web VR / AR. Apple Vision Pro's visionOS Safari supports WebXR, so a single three.js scene drops into immersive view. Hologram / volumetric showcase apps are exploding.</p></> } },
    { tag: <>STABILITY</>, zh: { title: <>16 年月度节奏, 还在跑</>, body: <><p>2026-03 r184 是最新稳定。月度发布从 2010 年起没断过, contributor 1800+, 维护节奏比绝大多数同年代的 JS 库都长。短期内没看到这条线被替代的迹象。</p></> }, en: { title: <>16 years of monthly cadence, still running</>, body: <><p>r184 (2026-03) is the latest stable. Monthly releases since 2010 have never lapsed; 1800+ contributors; a maintenance rhythm longer than most JS libraries born in the same era. No sign of this line being displaced in the near term.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本站所有 3D 魔方相关的像素最终都从 three.js 这棵树出来。路径分两条。</p>
        <p>第一条<strong>间接路径</strong>:cubing.js 的 <code>TwistyPlayer</code> 组件内部用 three.js 渲染三维 cube —— PerspectiveCamera、自带的 OrbitControls 风格交互、MeshStandardMaterial 贴纸、按 move 触发的 group rotation。这个组件出现在 <code>/trainer</code> (公式计时训练)、<code>/recon</code> (复盘)、<code>/algdb</code> (公式库浏览)、<code>/analyze</code> (CFOP 分析) 等多个工具页, 用户看到的 cube 都来自这条管线。</p>
        <p>第二条<strong>直接路径</strong>:<code>/demo/sq1</code> 这页绕开 TwistyPlayer, 直接 <code>import * as THREE from 'three'</code>。原因是 Square-1 的 slice 切割 / 块状转动需要 per-piece 自定义几何 + 矩阵累乘, 远超 TwistyPlayer 的标准 puzzle 模型能表达的范围。实现见 <code>packages/client/src/pages/sim/cuber/</code>:手写 BufferGeometry 拼出每个角 / 棱块, 用一个 pivot Group 做 slice 时的旋转累积, 最后用 PerspectiveCamera + WebGLRenderer 出帧。</p>
        <p>版本上锁在 cubing.js 内置的 three 版本。<code>/demo/sq1</code> 通过 <code>import 'three'</code> 复用同一份, 不会出现两份 three 并存 bundle 爆炸的问题。WebGPU 路径暂未启用 —— TwistyPlayer 自身还在 WebGL2 path, 现阶段稳定优先于性能。</p>
      </>
    ),
    en: (
      <>
        <p>Every 3D-cube pixel on this site eventually flows out of the three.js tree. Two paths.</p>
        <p>The <strong>indirect path</strong>: cubing.js's <code>TwistyPlayer</code> component uses three.js internally to render the 3D cube — a PerspectiveCamera, OrbitControls-style interaction, MeshStandardMaterial stickers, group rotations triggered per move. This component appears in <code>/trainer</code> (alg timing drills), <code>/recon</code> (replay), <code>/algdb</code> (alg library browse), <code>/analyze</code> (CFOP analysis), and other tool pages. Every cube the user sees comes through this pipeline.</p>
        <p>The <strong>direct path</strong>: <code>/demo/sq1</code> bypasses TwistyPlayer and reaches for <code>import * as THREE from 'three'</code> straight. The reason is that Square-1's slice / per-piece rotation needs custom per-piece geometry and matrix composition that falls outside TwistyPlayer's standard puzzle model. The implementation is in <code>packages/client/src/pages/sim/cuber/</code>: hand-built BufferGeometry assembles each corner / edge piece, a pivot Group accumulates rotation during a slice, and a PerspectiveCamera + WebGLRenderer renders the frame.</p>
        <p>The three version is pinned to whatever cubing.js bundles. <code>/demo/sq1</code> shares the same copy via <code>import 'three'</code> — no double-bundle bloat. The WebGPU path is not enabled yet; TwistyPlayer itself is still on WebGL2, and at this stage stability outweighs the perf upside.</p>
      </>
    ),
  },
  links: [
    { label: 'threejs.org', href: 'https://threejs.org' },
    { label: 'GitHub · mrdoob/three.js', href: 'https://github.com/mrdoob/three.js' },
    { label: 'Examples', href: 'https://threejs.org/examples/' },
    { label: 'r184 release notes', href: 'https://github.com/mrdoob/three.js/releases/tag/r184' },
    { label: 'react-three-fiber', href: 'https://r3f.docs.pmnd.rs' },
  ],
};
