import type { StackTool } from '../stack_tool_types';
import { k, v, s, n, f, p, c } from '../stack_tool_types';

// ─── WebCodecs + video pipeline (WebCodecs + mp4box.js + @ffmpeg/ffmpeg + mp4-muxer)

export const WEBCODECS: StackTool = {
  slug: 'webcodecs',
  name: 'WebCodecs Stack',
  version: 'CR 2023-02',
  since: '2020-11',
  group: 'frontend',
  accent: '#FB7185',
  bright: '#FDA4AF',
  glyph: '⏵',
  floats: ['VideoDecoder', 'VideoEncoder', 'VideoFrame', 'EncodedVideoChunk', 'OffscreenCanvas', 'mp4box.js', 'mp4-muxer', 'ffmpeg.wasm', 'Hardware decode', 'VFR', 'H.264', 'HEVC'],
  zh: {
    tagline: '浏览器里硬件解码 + 重编码 + 零丢帧导出',
    role: '`/frame-count` 工具的核心管线。视频文件 → mp4box.js 解析 → WebCodecs 硬件解码出 VideoFrame → OffscreenCanvas crop → VideoEncoder 硬件重编码 → mp4-muxer 写回 .mp4。VFR / 奇怪 codec 走 ffmpeg.wasm 兜底。',
    heroSub: <>把视频"打开、看每一帧、改一改、再写回去"这件事原本只能交给 ffmpeg。WebCodecs API 让浏览器第一次能直接吃到 GPU 硬件解码出来的 VideoFrame, 配上 mp4box.js / mp4-muxer 两端的容器解析、ffmpeg.wasm 兜底, 整套管线常态运行在普通笔电的硬件解码器里, 速度比 WASM 软解快一个量级。</>,
    whatDesc: <>这是<strong>四件套</strong>:<strong>WebCodecs</strong> (W3C 标准, 浏览器原生 API) 负责编解码, <strong>mp4box.js</strong> 把 .mp4 拆成 EncodedVideoChunk 喂给 decoder, <strong>mp4-muxer</strong> 把 encoder 吐出来的 chunk 写回 .mp4, <strong>@ffmpeg/ffmpeg</strong> (ffmpeg.wasm) 兜底处理 VFR / 奇怪 codec / 音频混合。任意一件单拿出来都不够用, 凑齐才是一条完整的浏览器视频管线。</>,
    historyDesc: <>2014 年 MediaSource Extensions 让浏览器第一次能"喂"视频; 2020 年 WebCodecs origin trial 让浏览器第一次能"看到"视频的每一帧; 2023 年 Candidate Recommendation 把 API 锁住; 2024 年 Safari 跟上; 2026 年生态里的 mp4box / mp4-muxer / ffmpeg.wasm 各自补到 production-ready。</>,
    conceptsTitle: '管线四件套关键 API',
    conceptsDesc: <>从 file 到 file 一共需要五个 API: <code>mp4box.createFile()</code> 拆容器, <code>VideoDecoder</code> 出帧, <code>OffscreenCanvas</code> 处理像素, <code>VideoEncoder</code> 重新编码, <code>mp4-muxer.Muxer</code> 写回容器。<code>FFmpeg</code> 兜底单独走一条路。</>,
    whyDesc: <>为什么不直接用 ffmpeg.wasm 一把梭? 因为硬件解码比 WASM 软解快 10 倍, 内存峰值低一个数量级, 还省 30MB 的 wasm 下载。WebCodecs 主路径吃 95%, ffmpeg.wasm 兜底 5%, ROI 拐点就在这里。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>YouTube / Discord / Zoom / Google Meet 等大用户在 web 端的录制 / 上传管线全都跑这套。本站 <code>/frame-count</code> 也是同款思路。</>,
    cuberootDesc: <>cuberoot.me 把 WebCodecs 当成 <code>/frame-count</code> 数帧工具的<strong>核心管线</strong>, mp4box + mp4-muxer + ffmpeg.wasm 三个 npm 包是必备配角。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>HEVC / AV1 在 Safari / Firefox 一两年内会补齐, WebGPU + WebCodecs 配合后可以做实时 shader 滤镜; ffmpeg.wasm 7.x 把 SIMD + multithread 打开, 兜底路径也快了。</>,
  },
  en: {
    tagline: 'Hardware-accelerated decode + re-encode + zero-drop export in the browser',
    role: 'The core pipeline behind /frame-count. Video file → mp4box.js demux → WebCodecs hardware decode into VideoFrame → OffscreenCanvas crop → VideoEncoder hardware re-encode → mp4-muxer writes back to .mp4. VFR / exotic codecs fall back to ffmpeg.wasm.',
    heroSub: <>"Open a video, read every frame, modify, write back" used to be ffmpeg-only work. The WebCodecs API lets the browser feed VideoFrames straight out of the GPU hardware decoder for the first time; paired with mp4box.js / mp4-muxer for container parsing and ffmpeg.wasm as a fallback, the whole pipeline runs on a normal laptop's hardware silicon — an order of magnitude faster than WASM software decoding.</>,
    whatDesc: <>This is a <strong>four-piece</strong> stack: <strong>WebCodecs</strong> (W3C standard, browser-native API) handles encode / decode; <strong>mp4box.js</strong> demuxes .mp4 into EncodedVideoChunks for the decoder; <strong>mp4-muxer</strong> writes encoder output back into .mp4; <strong>@ffmpeg/ffmpeg</strong> (ffmpeg.wasm) covers VFR / odd codecs / audio mixing. None of them alone is enough — together they form a complete in-browser video pipeline.</>,
    historyDesc: <>2014's MediaSource Extensions let browsers "feed" video for the first time; 2020's WebCodecs origin trial let them "see" each frame; the 2023 Candidate Recommendation froze the API; Safari caught up in 2024; by 2026 mp4box / mp4-muxer / ffmpeg.wasm are all production-ready alongside.</>,
    conceptsTitle: 'Five APIs across four packages',
    conceptsDesc: <>File-to-file needs five APIs: <code>mp4box.createFile()</code> for demux, <code>VideoDecoder</code> for frames, <code>OffscreenCanvas</code> for pixel work, <code>VideoEncoder</code> for re-encode, <code>mp4-muxer.Muxer</code> for remux. <code>FFmpeg</code> sits on its own fallback path.</>,
    whyDesc: <>Why not just use ffmpeg.wasm? Because hardware decode is ~10x faster than WASM software, memory peaks are an order lower, and you save ~30MB of wasm download. WebCodecs handles 95% via the main path; ffmpeg.wasm covers the 5% — that's where the ROI knee is.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>YouTube / Discord / Zoom / Google Meet all wire this stack into their web recording / upload pipelines. cuberoot.me's <code>/frame-count</code> takes the same approach.</>,
    cuberootDesc: <>cuberoot.me treats WebCodecs as the <strong>core pipeline</strong> of <code>/frame-count</code>; mp4box + mp4-muxer + ffmpeg.wasm are mandatory supporting cast.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>HEVC / AV1 on Safari / Firefox will be filled in within a year or two; WebGPU + WebCodecs together unlock real-time shader filters; ffmpeg.wasm 7.x flipped on SIMD + multithread, so the fallback path is faster too.</>,
  },
  heroStats: [
    { num: '94', unit: '+', zh: <>Chrome 起原生支持 <em>2021-09</em></>, en: <>Chrome stable since <em>2021-09</em></> },
    { num: '~10', unit: 'x', zh: <>硬件解码 vs WASM 软解</>, en: <>hardware decode vs WASM software</> },
    { num: '0', zh: <>丢帧 <em>零拷贝 GPU 管线</em></>, en: <>drops <em>zero-copy GPU pipeline</em></> },
    { num: '4', zh: <>件套 <em>WebCodecs · mp4box · mp4-muxer · ffmpeg.wasm</em></>, en: <>packages <em>WebCodecs · mp4box · mp4-muxer · ffmpeg.wasm</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>WebCodecs API 是 Chrome 团队 2020 年开始推的浏览器底层 API, 第一次把 <strong>硬件 codec</strong> (你笔电里那块负责解 H.264 / HEVC / AV1 的专用芯片) 暴露给 JS。在它之前, 浏览器里想"看到"视频的每一帧, 只能要么 <code>&lt;video&gt;.currentTime = x</code> 等 seek 完截图 (慢、不可靠、出 P/B 帧抖动), 要么把整段视频塞进 ffmpeg.wasm 软解 (10 倍速度损失 + 30MB wasm 下载)。WebCodecs 把这一步搬到了硬件, decode 一帧 1080p H.264 从 ~50ms 降到 ~5ms。</p>
        <p>但 WebCodecs 本身只管 <strong>编 / 解码</strong>, 它不认 .mp4 容器格式 —— 容器是 ISO/IEC 14496-12 那一套 box 树。这件事 <strong>mp4box.js</strong> (Cyril Concolato 从 2014 年起在 Telecom ParisTech / MovieLabs 维护) 干了:解析 moov / trak / mdat, 把每个 frame 切成 EncodedVideoChunk 喂给 VideoDecoder。反方向 <strong>mp4-muxer</strong> (Vanilagy 2023 起开发) 把 VideoEncoder 吐出来的 chunk 重新拼成合法 .mp4。这两个 npm 包加起来 ~150KB, 比 ffmpeg.wasm 的 30MB 小两个量级。</p>
        <p>还剩 5% 的边角情况 —— VFR 视频 (timestamp 不规则的 iPhone 录像)、HEVC 4:2:2 RExt 这类专业 codec、音轨混合、容器不规范的旧文件 —— WebCodecs 撑不住。这时候 <strong>@ffmpeg/ffmpeg</strong> (ffmpeg.wasm) 兜底:把视频先 transcode 到 baseline H.264, 再交回 WebCodecs 主路径。<code>/frame-count</code> 这种工具的 ROI 拐点就在这里:WebCodecs 走 95% 主路径 (硬件 + 快), ffmpeg.wasm 走 5% 兜底 (软件 + 慢但万能)。</p>
      </>
    ),
    en: (
      <>
        <p>The WebCodecs API was Chrome team's 2020 push to expose <strong>hardware codecs</strong> (the dedicated H.264 / HEVC / AV1 silicon in your laptop) to JS. Before it, "see every frame" inside a browser meant either <code>&lt;video&gt;.currentTime = x</code> + screenshot (slow, unreliable, P/B-frame jitter) or feed the whole file to ffmpeg.wasm software decode (10x slower, plus a 30MB wasm download). WebCodecs moves that step to hardware — decoding one 1080p H.264 frame drops from ~50ms to ~5ms.</p>
        <p>But WebCodecs only handles <strong>encode / decode</strong>; it doesn't speak .mp4 container format — that's an ISO/IEC 14496-12 box tree. <strong>mp4box.js</strong> (maintained by Cyril Concolato since 2014 at Telecom ParisTech / MovieLabs) handles that: parse moov / trak / mdat, hand each frame to VideoDecoder as an EncodedVideoChunk. The reverse direction is <strong>mp4-muxer</strong> (by Vanilagy, since 2023), which re-assembles VideoEncoder output into a valid .mp4. Combined, the two npm packages are ~150KB — two orders smaller than ffmpeg.wasm's 30MB.</p>
        <p>The remaining 5% is the long tail — VFR clips from iPhones, HEVC 4:2:2 RExt and other professional codecs, audio track mixing, malformed-container legacy files — WebCodecs can't cover them. That's where <strong>@ffmpeg/ffmpeg</strong> (ffmpeg.wasm) sits: transcode the file to baseline H.264, hand it back to the WebCodecs main path. The ROI knee for a tool like <code>/frame-count</code> is exactly here — WebCodecs for 95% (hardware + fast), ffmpeg.wasm for 5% (software + slow but universal).</p>
      </>
    ),
  },
  history: [
    { year: '2014·01', zh: { title: <>MediaSource Extensions</>, desc: <>MSE 落地 Chrome / Firefox, 浏览器第一次能在播放期间动态 append 视频 chunk。YouTube DASH 和 Netflix HTML5 播放器在此之后才可能。但 MSE 只能"喂", 看不到帧内部。</> }, en: { title: <>MediaSource Extensions</>, desc: <>MSE lands in Chrome / Firefox — browsers can append video chunks during playback. YouTube DASH and Netflix's HTML5 player become possible. But MSE only "feeds" — it can't see inside frames.</> } },
    { year: '2014·??', zh: { title: <>mp4box.js 立项</>, desc: <>Cyril Concolato 在 Telecom ParisTech 开始 mp4box.js, JS 端 ISO BMFF 解析器。最初目标是 DASH / HLS 工具链, 后来配 WebCodecs 大放异彩。</> }, en: { title: <>mp4box.js bootstrapped</>, desc: <>Cyril Concolato kicks off mp4box.js at Telecom ParisTech — a JS-side ISO BMFF parser. Original target was DASH / HLS tooling; it found its second life paired with WebCodecs.</> } },
    { year: '2018·11', zh: { title: <>WebCodecs Explainer</>, desc: <>Chrome 团队 (Chris Cunningham / Dan Sanders) 在 WICG 提 WebCodecs 提案。核心论点:WASM 软解性能上限不够, 浏览器需要直接暴露硬件 codec。</> }, en: { title: <>WebCodecs Explainer</>, desc: <>The Chrome team (Chris Cunningham / Dan Sanders) files the WebCodecs proposal at WICG. Thesis: WASM software decoding has a perf ceiling, browsers must expose hardware codecs directly.</> } },
    { year: '2020·11', zh: { title: <>Chrome 86 origin trial</>, desc: <>WebCodecs origin trial 开门, VideoDecoder / VideoEncoder / VideoFrame 第一次能在真实站点上跑。Zoom / Google Meet 是早期 trialist。</> }, en: { title: <>Chrome 86 origin trial</>, desc: <>WebCodecs origin trial opens — VideoDecoder / VideoEncoder / VideoFrame run on real sites for the first time. Zoom / Google Meet are early trialists.</> } },
    { year: '2021·09', zh: { title: <>Chrome 94 stable</>, desc: <>WebCodecs 转 stable, Chrome / Edge / Opera 默认开启。配套 mp4box.js 在同期发 v0.5+, 第一次出现"mp4box + WebCodecs" 的官方 demo。</> }, en: { title: <>Chrome 94 stable</>, desc: <>WebCodecs goes stable; Chrome / Edge / Opera ship it on by default. mp4box.js bumps to v0.5+, and the first "mp4box + WebCodecs" official demos appear.</> } },
    { year: '2022·09', zh: { title: <>ffmpeg.wasm 0.11 + SIMD</>, desc: <>ffmpeg.wasm 把 SIMD 编译进 wasm, 性能 ~2x。这条软件兜底路径从"勉强能跑"变成"小文件可接受"。WebCodecs 主路径 + ffmpeg.wasm 兜底的分工开始合理化。</> }, en: { title: <>ffmpeg.wasm 0.11 + SIMD</>, desc: <>ffmpeg.wasm compiles SIMD into the wasm — roughly 2x perf. The software fallback path goes from "barely works" to "acceptable for small files." The "WebCodecs main + ffmpeg.wasm fallback" split starts to make sense.</> } },
    { year: '2023·02', zh: { title: <>WebCodecs CR</>, desc: <>W3C Candidate Recommendation 发布。从此 API 形状基本锁死, 上层框架敢于在 production 依赖。同年 Vanilagy 开 mp4-muxer 仓库。</> }, en: { title: <>WebCodecs CR</>, desc: <>W3C Candidate Recommendation publishes. API shape is effectively locked; downstream frameworks dare to depend on it in production. Vanilagy opens the mp4-muxer repository the same year.</> } },
    { year: '2023·11', zh: { title: <>mp4-muxer 1.0</>, desc: <>Vanilagy 的 mp4-muxer 发 1.0, 配 WebCodecs VideoEncoder 把 EncodedVideoChunk 写回 .mp4 容器。"在浏览器里完整 encode 一段视频" 第一次成为一行 import。</> }, en: { title: <>mp4-muxer 1.0</>, desc: <>Vanilagy ships mp4-muxer 1.0 — pair it with VideoEncoder and EncodedVideoChunks become a valid .mp4. "Encode a full video in the browser" reduces to a single npm import.</> } },
    { year: '2024·03', zh: { title: <>Safari 17.4 全面 WebCodecs</>, desc: <>Safari 跟上 H.264 / H.265 / VP9 全套 VideoDecoder + VideoEncoder。iOS / macOS 上的硬件管线接入。VFR iPhone 视频还有零星 bug, 但 main path 已可用。</> }, en: { title: <>Safari 17.4 full WebCodecs</>, desc: <>Safari supports H.264 / H.265 / VP9 across VideoDecoder + VideoEncoder. iOS / macOS hardware pipelines join. iPhone VFR clips still have edge-case bugs, but the main path works.</> } },
    { year: '2024·12', zh: { title: <>Firefox 133 H.264</>, desc: <>Firefox 默认开 WebCodecs H.264, 三大浏览器第一次能在 web 上跑同一条 hardware decode 路径。AV1 / HEVC 在 nightly。</> }, en: { title: <>Firefox 133 H.264</>, desc: <>Firefox enables WebCodecs H.264 by default — for the first time the three major browsers share the same hardware decode path on the web. AV1 / HEVC still ride nightly.</> } },
    { year: '2025·11', zh: { title: <>ffmpeg.wasm 0.13 + multithread</>, desc: <>ffmpeg.wasm 把 SharedArrayBuffer + multithread 全打开, 性能再 ~2x。兜底 5% 路径也终于不慢。配套的 COOP / COEP header 要求让站点架构略显复杂。</> }, en: { title: <>ffmpeg.wasm 0.13 + multithread</>, desc: <>ffmpeg.wasm enables SharedArrayBuffer + multithread by default — another ~2x. The 5% fallback path is finally not slow. The required COOP / COEP headers add a touch of architecture complexity, though.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>当前状态 / production-ready</>, desc: <>WebCodecs 已是浏览器视频处理的事实标准。mp4box@2.3 / mp4-muxer@5.2 / @ffmpeg/ffmpeg@0.12 四件套配齐。cuberoot.me 的 /frame-count 在 2026-04 上线时直接吃这套。</> }, en: { title: <>Current state / production-ready</>, desc: <>WebCodecs is now the de-facto standard for browser video processing. mp4box@2.3 / mp4-muxer@5.2 / @ffmpeg/ffmpeg@0.12 round out the stack. cuberoot.me's /frame-count shipped on it in April 2026.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>VideoDecoder 基本用法</>, desc: <>configure() 喂 codec 字符串 + extradata; decode() 喂 EncodedVideoChunk; output 回调拿 VideoFrame。所有重活儿在 GPU 上跑。</> }, en: { title: <>VideoDecoder basics</>, desc: <>configure() takes a codec string + extradata; decode() takes an EncodedVideoChunk; the output callback yields a VideoFrame. All the heavy lifting runs on the GPU.</> }, code: <code>{k('const')} {v('decoder')} = {k('new')} {f('VideoDecoder')}({'{'}{'\n'}  {p('output')}: ({v('frame')}) =&gt; {f('paint')}({v('frame')}),{'\n'}  {p('error')}: ({v('e')}) =&gt; {f('console')}.{f('warn')}({v('e')}),{'\n'}{'}'});{'\n'}{v('decoder')}.{f('configure')}({'{'} {p('codec')}: {s("'avc1.42E01E'")}, {p('description')} {'}'});{'\n'}{v('decoder')}.{f('decode')}({k('new')} {f('EncodedVideoChunk')}({'{'} {p('type')}: {s("'key'")}, {p('data')}, {p('timestamp')} {'}'}));</code> },
    { tag: 'B', zh: { title: <>mp4box.js onSamples</>, desc: <>createFile().appendBuffer(chunk) 流式喂入, onReady 回调拿 codec 配置, onSamples 回调拿一批 EncodedVideoChunk 原料。</> }, en: { title: <>mp4box.js onSamples</>, desc: <>Stream-feed createFile().appendBuffer(chunk); onReady delivers codec config; onSamples delivers a batch of raw EncodedVideoChunk payload.</> }, code: <code>{k('const')} {v('mp4')} = {f('createFile')}();{'\n'}{v('mp4')}.{p('onReady')} = ({v('info')}) =&gt; {f('configureDecoder')}({v('info')});{'\n'}{v('mp4')}.{p('onSamples')} = ({v('_id')}, {v('_u')}, {v('samples')}) =&gt; {'{'}{'\n'}  {k('for')} ({k('const')} {v('s')} {k('of')} {v('samples')}) {v('decoder')}.{f('decode')}({f('toChunk')}({v('s')}));{'\n'}{'}'};{'\n'}{v('mp4')}.{f('appendBuffer')}({v('buf')}); {v('mp4')}.{f('flush')}();</code> },
    { tag: 'C', zh: { title: <>VideoFrame → OffscreenCanvas crop</>, desc: <>VideoFrame 是 GPU 资源, drawImage 到 OffscreenCanvas 上可以 crop / scale / 滤镜, 再 transferToImageBitmap 拿出来。零 JS 拷贝。</> }, en: { title: <>VideoFrame → OffscreenCanvas crop</>, desc: <>A VideoFrame is a GPU resource; drawImage onto an OffscreenCanvas to crop / scale / filter, then transferToImageBitmap. Zero JS-side copy.</> }, code: <code>{k('const')} {v('canvas')} = {k('new')} {f('OffscreenCanvas')}({n('1280')}, {n('720')});{'\n'}{k('const')} {v('ctx')} = {v('canvas')}.{f('getContext')}({s("'2d'")});{'\n'}{v('ctx')}.{f('drawImage')}({v('frame')}, {v('sx')}, {v('sy')}, {v('sw')}, {v('sh')}, {n('0')}, {n('0')}, {n('1280')}, {n('720')});{'\n'}{k('const')} {v('bmp')} = {v('canvas')}.{f('transferToImageBitmap')}();{'\n'}{v('frame')}.{f('close')}(); {c('// 释放 GPU 资源, 不放就泄露')}</code> },
    { tag: 'D', zh: { title: <>VideoEncoder + output handler</>, desc: <>跟 decoder 对称:configure() 给目标 codec, encode(VideoFrame, {'{'} keyFrame {'}'}) 喂帧, output 回调拿 EncodedVideoChunk 交给 muxer。</> }, en: { title: <>VideoEncoder + output handler</>, desc: <>Mirror of decoder: configure() the target codec, encode(VideoFrame, {'{'} keyFrame {'}'}) per frame, output callback yields EncodedVideoChunks for the muxer.</> }, code: <code>{k('const')} {v('encoder')} = {k('new')} {f('VideoEncoder')}({'{'}{'\n'}  {p('output')}: ({v('chunk')}, {v('meta')}) =&gt; {v('muxer')}.{f('addVideoChunk')}({v('chunk')}, {v('meta')}),{'\n'}  {p('error')}: ({v('e')}) =&gt; {f('console')}.{f('warn')}({v('e')}),{'\n'}{'}'});{'\n'}{v('encoder')}.{f('configure')}({'{'} {p('codec')}: {s("'avc1.4d0028'")}, {p('width')}: {n('1920')}, {p('height')}: {n('1080')}, {p('bitrate')}: {n('8_000_000')} {'}'});{'\n'}{v('encoder')}.{f('encode')}({v('frame')}, {'{'} {p('keyFrame')}: {v('i')} % {n('60')} === {n('0')} {'}'});</code> },
    { tag: 'E', zh: { title: <>mp4-muxer 写回 .mp4</>, desc: <>new Muxer({'{'} target, video:{'{'}codec,width,height{'}'} {'}'}), 每个 chunk addVideoChunk, 最后 finalize() 出 Uint8Array, Blob 下载。</> }, en: { title: <>mp4-muxer writes back to .mp4</>, desc: <>new Muxer({'{'} target, video: {'{'} codec, width, height {'}'} {'}'}); addVideoChunk per chunk; finalize() returns a Uint8Array. Wrap in a Blob and download.</> }, code: <code>{k('import')} {'{'} {v('Muxer')}, {v('ArrayBufferTarget')} {'}'} {k('from')} {s("'mp4-muxer'")};{'\n\n'}{k('const')} {v('muxer')} = {k('new')} {f('Muxer')}({'{'}{'\n'}  {p('target')}: {k('new')} {f('ArrayBufferTarget')}(),{'\n'}  {p('video')}: {'{'} {p('codec')}: {s("'avc'")}, {p('width')}: {n('1920')}, {p('height')}: {n('1080')} {'}'},{'\n'}  {p('fastStart')}: {s("'in-memory'")},{'\n'}{'}'});{'\n'}{v('muxer')}.{f('finalize')}(); {v('muxer')}.{p('target')}.{p('buffer')};</code> },
    { tag: 'F', zh: { title: <>ffmpeg.wasm 兜底</>, desc: <>VFR 视频或非主流 codec 走这条:toBlobURL 加载 core + worker, writeFile 灌输入, exec 转码, readFile 拿输出。慢但万能。</> }, en: { title: <>ffmpeg.wasm fallback</>, desc: <>For VFR clips or off-spec codecs: toBlobURL loads core + worker, writeFile feeds input, exec transcodes, readFile pulls the output. Slow but universal.</> }, code: <code>{k('const')} {v('ff')} = {k('new')} {f('FFmpeg')}();{'\n'}{k('await')} {v('ff')}.{f('load')}({'{'} {p('coreURL')}, {p('wasmURL')}, {p('workerURL')} {'}'});{'\n'}{k('await')} {v('ff')}.{f('writeFile')}({s("'in.mp4'")}, {k('await')} {f('fetchFile')}({v('file')}));{'\n'}{k('await')} {v('ff')}.{f('exec')}([{s("'-i'")}, {s("'in.mp4'")}, {s("'-c:v'")}, {s("'libx264'")}, {s("'-vf'")}, {s("'fps=60'")}, {s("'out.mp4'")}]);{'\n'}{k('const')} {v('buf')} = {k('await')} {v('ff')}.{f('readFile')}({s("'out.mp4'")});</code> },
    { tag: 'G', zh: { title: <>背压 + decodeQueueSize</>, desc: <>硬件 decoder 队列溢出会抛 EncodingError, iOS 上更敏感。await decodeQueueSize 降下来再喂下一帧。</> }, en: { title: <>Backpressure + decodeQueueSize</>, desc: <>Hardware decoder queue overflow throws EncodingError — iOS is especially touchy. Await decodeQueueSize to drain before feeding the next chunk.</> }, code: <code>{k('while')} ({v('decoder')}.{p('decodeQueueSize')} &gt; {n('16')}) {'{'}{'\n'}  {k('await')} {k('new')} {f('Promise')}({v('r')} =&gt; {f('setTimeout')}({v('r')}, {n('4')}));{'\n'}{'}'}{'\n'}{v('decoder')}.{f('decode')}({v('chunk')});</code> },
    { tag: 'H', zh: { title: <>VFR 检测</>, desc: <>iPhone 录像常变帧率 (15-67fps 大幅波动), 扫一遍 sample.duration 拿 min/max, 比值 &lt;0.8 判 VFR, 走 ffmpeg.wasm 兜底前先做 timestamp 反推。</> }, en: { title: <>VFR detection</>, desc: <>iPhone clips often vary frame rate (15-67fps swing). Scan sample.duration for min / max; if min/max &lt; 0.8 flag as VFR. Route through ffmpeg.wasm fallback or use timestamp-based positioning.</> }, code: <code>{k('let')} {v('minDur')} = {n('Infinity')}, {v('maxDur')} = {n('0')};{'\n'}{k('for')} ({k('const')} {v('s')} {k('of')} {v('samples')}) {'{'}{'\n'}  {k('if')} ({v('s')}.{p('duration')} &lt; {v('minDur')}) {v('minDur')} = {v('s')}.{p('duration')};{'\n'}  {k('if')} ({v('s')}.{p('duration')} &gt; {v('maxDur')}) {v('maxDur')} = {v('s')}.{p('duration')};{'\n'}{'}'}{'\n'}{k('const')} {v('isVFR')} = {v('minDur')} / {v('maxDur')} &lt; {n('0.8')};</code> },
  ],
  whyCards: [
    { icon: '⚙', zh: { title: <>硬件解码, 10x 速度</>, desc: <>VideoDecoder 直接走笔电的 H.264 / HEVC / AV1 专用解码芯片, CPU 占用接近 0, 解码一帧 1080p 在 5ms 量级。WASM 软解同条件大约 50ms。</> }, en: { title: <>Hardware decode, 10x faster</>, desc: <>VideoDecoder uses the laptop's dedicated H.264 / HEVC / AV1 silicon directly — near-zero CPU, ~5ms for a 1080p frame. WASM software decode on the same machine is ~50ms.</> }, code: <>{c('// Hardware decode 1080p H.264:')}{'\n'}{c('// VideoDecoder  ~5ms')}{'\n'}{c('// ffmpeg.wasm ~50ms')}</> },
    { icon: '⌬', zh: { title: <>零丢帧 / 零 JS 拷贝</>, desc: <>VideoFrame 是个 GPU resource handle, 不是 ArrayBuffer。drawImage 到 OffscreenCanvas 走 GPU 内传, 不经过 JS heap, 整条管线零拷贝。close() 才释放显存。</> }, en: { title: <>Zero dropped frames, zero JS copy</>, desc: <>A VideoFrame is a GPU resource handle, not an ArrayBuffer. drawImage to OffscreenCanvas stays GPU-side, never touches the JS heap. close() releases the VRAM.</> }, code: <>{c('// VideoFrame stays GPU-side')}{'\n'}{v('frame')}.{f('close')}();</> },
    { icon: '⌁', zh: { title: <>OffscreenCanvas + Worker 脱主线程</>, desc: <>整条管线可以放进 Web Worker (VideoDecoder / Encoder / OffscreenCanvas 都能 transfer), 主线程一帧都不卡, UI 拖动 / 输入零延迟。</> }, en: { title: <>OffscreenCanvas + Worker = main thread free</>, desc: <>The whole pipeline fits in a Worker (VideoDecoder / Encoder / OffscreenCanvas all transfer cleanly). Main thread never blocks, UI scrubbing and input stay instant.</> }, code: <>{c('// Run decode in a Worker')}{'\n'}{c('// main thread stays at 60fps')}</> },
    { icon: '⌗', zh: { title: <>浏览器原生, 不下 wasm</>, desc: <>WebCodecs 是 W3C 标准 API, 不需要额外下载。30MB 的 ffmpeg.wasm 只在 5% 边角情况下才真去取, 首屏跑得轻。</> }, en: { title: <>Native API, no wasm download</>, desc: <>WebCodecs is a W3C standard API — no extra payload. The 30MB ffmpeg.wasm only loads for the 5% edge cases; the main path stays lightweight on first paint.</> }, code: <>{c('// WebCodecs: 0 KB to ship')}{'\n'}{c('// ffmpeg.wasm: ~30 MB (lazy)')}</> },
    { icon: '⎇', zh: { title: <>四件套覆盖完整管线</>, desc: <>"解 → 处理 → 编 → 写" 四步:mp4box.js (解) + WebCodecs (Decode / Encode) + OffscreenCanvas (处理) + mp4-muxer (写)。任意单件做不到全程, 凑齐就是一条完整的 file-to-file 管线。</> }, en: { title: <>Four packages cover the full pipeline</>, desc: <>"Demux → process → encode → mux": mp4box.js (demux) + WebCodecs (decode / encode) + OffscreenCanvas (process) + mp4-muxer (mux). No single package does it all; together they form a complete file-to-file pipeline.</> }, code: <>{c('// .mp4  →  mp4box  →  decoder')}{'\n'}{c('//  →  canvas  →  encoder  →  muxer')}</> },
    { icon: '⌖', zh: { title: <>VFR 视频可识别</>, desc: <>mp4box 给的每个 sample 都带 timestamp, 不用相信 fps 一个标量。iPhone VFR 录像 (15-67fps 波动) 用 timestamp 反推 sample, WCA 公式起表帧再不差 ±1 帧。</> }, en: { title: <>VFR clips handled</>, desc: <>mp4box gives each sample a timestamp — never trust a single fps scalar. iPhone VFR clips (15-67fps swings) get sample-by-sample timestamps; the WCA start-frame formula is no longer ±1 frame off.</> }, code: <>{v('s')}.{p('timestamp')}; {c('// μs, ground truth')}</> },
    { icon: '⏚', zh: { title: <>兜底有 ffmpeg.wasm</>, desc: <>HEVC 4:2:2 RExt、HEVC Main 12、损坏容器、奇异音轨编码 —— WebCodecs 撑不住的, ffmpeg.wasm 全能转。先 transcode 到 baseline H.264, 再交回主路径。慢, 但绝不挂。</> }, en: { title: <>ffmpeg.wasm as the safety net</>, desc: <>HEVC 4:2:2 RExt, HEVC Main 12, broken containers, exotic audio codecs — anything WebCodecs can't handle, ffmpeg.wasm can transcode. Convert to baseline H.264 first, hand back to the main path. Slow but never fails.</> }, code: <>{k('await')} {v('ff')}.{f('exec')}([{s("'-i'")}, {v('input')}, {s("'-c:v'")}, {s("'libx264'")}, {v('output')}]);</> },
    { icon: '▶', zh: { title: <>精确数帧 / 裁剪 / 拼接</>, desc: <>给 WCA 裁判 / 视频分析师 / 数帧场景做的, 不是给非线性编辑用的。GOP 内任意 seek 不是它强项, 但"按帧前进 / 倒退 / 标记 / 导出" 是它母语。</> }, en: { title: <>Perfect for frame-accurate editing</>, desc: <>Built for WCA judging / video analysis / frame counting — not non-linear editing. Arbitrary in-GOP seek isn't its strength, but per-frame step / mark / export is its native dialect.</> }, code: <>{c('// step ±1 frame')}{'\n'}{c('// no Premiere needed')}</> },
  ],
  adopters: [
    { name: 'YouTube web (upload + editor)', href: 'https://youtube.com', highlight: true, zhNote: 'Studio 编辑器的 trim / mute / blur 全走 WebCodecs', enNote: 'Studio editor trim / mute / blur all run on WebCodecs' },
    { name: 'Google Meet', href: 'https://meet.google.com', zhNote: '会议录制 + 屏幕分享走 VideoEncoder', enNote: 'Meeting recording + screen share via VideoEncoder' },
    { name: 'Discord', href: 'https://discord.com', zhNote: '桌面端视频通话 H.264 / VP9 走 WebCodecs', enNote: 'Desktop video calls H.264 / VP9 via WebCodecs' },
    { name: 'Zoom (web client)', href: 'https://zoom.us', zhNote: 'origin trial 时期最早一批 trialist', enNote: 'Among the earliest trialists during origin trial' },
    { name: 'tldraw / Excalidraw', href: 'https://tldraw.com', zhNote: '画板录屏 → mp4 导出', enNote: 'Whiteboard screen recording → mp4 export' },
    { name: 'rrweb', href: 'https://github.com/rrweb-io/rrweb', zhNote: '用户行为录制回放, 视频导出用 WebCodecs', enNote: 'User-session record / replay, video export via WebCodecs' },
    { name: 'bilibili web 创作', zhNote: '直播录屏 / 投稿前转码走 ffmpeg.wasm + WebCodecs', enNote: 'Live recording / pre-upload transcode uses ffmpeg.wasm + WebCodecs' },
    { name: 'ffmpegwasm.netlify.app', href: 'https://ffmpegwasm.netlify.app', zhNote: '@ffmpeg/ffmpeg 官方 demo 站', enNote: 'Official @ffmpeg/ffmpeg demo site' },
    { name: 'Borg-7 / ReconViewer', href: 'https://github.com/Borg-7/ReconViewer', zhNote: '魔方裁判数帧工具, /frame-count 的设计参考', enNote: 'Cubing judge frame-counting tool — the design reference for /frame-count' },
    { name: 'cuberoot.me /frame-count', highlight: true, zhNote: '本站工具, mp4box + WebCodecs + mp4-muxer + ffmpeg.wasm 全配齐', enNote: 'This site — uses mp4box + WebCodecs + mp4-muxer + ffmpeg.wasm together' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>跨浏览器 HEVC / AV1 一致</>, body: <><p>2026 年 Safari + Firefox 仍在补 HEVC / AV1 的 VideoEncoder。一旦补齐, "在浏览器里 H.265 重编码" 就不再是 Chrome 专属。iPhone 录像 (HEVC) 默认能直接走硬件, 不需要 ffmpeg.wasm 转码。</p><p>更深一层:智能手机原生 HEVC 录像越来越普遍, 浏览器侧能处理 HEVC 直接 saves 90% 的兜底压力。Apple 是 H.265 patent pool 成员, 推动它在 Safari 上原生, 是真利益对齐。</p></> }, en: { title: <>Cross-browser HEVC / AV1 parity</>, body: <><p>Safari + Firefox are still filling in HEVC / AV1 VideoEncoder support through 2026. Once done, "H.265 re-encode in the browser" stops being Chrome-only. iPhone HEVC clips can stay on hardware end-to-end, no ffmpeg.wasm transcode required.</p><p>Deeper: smartphone-native HEVC recording is mainstream now. Native browser HEVC processing eliminates ~90% of the fallback burden. Apple is a member of the H.265 patent pool — pushing it into Safari is genuine interest alignment.</p></> } },
    { tag: 'GPU', zh: { title: <>WebGPU + WebCodecs 实时滤镜</>, body: <><p>VideoFrame 已经在 GPU 上, WebGPU 也在 GPU 上, 两者中间不用回 CPU。一条 compute shader 就能给视频做实时 LUT / 降噪 / 上色, 每帧 1ms 量级。2026 年这套已在 Chromium 实验性可用, 主仓预计 2026 下半年。</p></> }, en: { title: <>WebGPU + WebCodecs for real-time filters</>, body: <><p>A VideoFrame already lives on the GPU; WebGPU runs on the GPU — no round-trip to CPU needed. One compute shader handles real-time LUT / denoise / grading at roughly 1ms per frame. Experimental in Chromium today, trunk landing expected in H2 2026.</p></> } },
    { tag: 'OPFS', zh: { title: <>OPFS + WebCodecs = web NLE</>, body: <><p>Origin Private File System (OPFS) 让浏览器有了"真本地文件系统"。配 WebCodecs 之后, 几个 GB 的素材可以不在 RAM 里整段持有, 而是 stream 读写 OPFS。"浏览器里跑非线性剪辑" 第一次成为可能, CapCut Web / Clipchamp 已在做。</p></> }, en: { title: <>OPFS + WebCodecs = web-native NLE</>, body: <><p>Origin Private File System gives browsers a real local filesystem. Combined with WebCodecs, multi-GB clips can stream-read / write OPFS instead of being held entirely in RAM. "Run a non-linear editor in the browser" is finally feasible — CapCut Web and Clipchamp are already shipping on it.</p></> } },
    { tag: <>WASM</>, zh: { title: <>ffmpeg.wasm 7.x 兜底也快了</>, body: <><p>ffmpeg.wasm 0.13+ 把 SIMD + SharedArrayBuffer multithread 全打开, 兜底路径的转码速度跟一年前比是 ~4x。但代价是站点必须发 COOP / COEP 头, 进 cross-origin isolated context, 这影响一些 OAuth / iframe 嵌入场景, 需要 nginx 配置精确路由。</p></> }, en: { title: <>ffmpeg.wasm 7.x: the fallback is fast too</>, body: <><p>ffmpeg.wasm 0.13+ enables SIMD + SharedArrayBuffer multithread by default — the fallback transcode path is ~4x faster than a year ago. The cost: the site must serve COOP / COEP headers and enter a cross-origin isolated context. That affects some OAuth / iframe-embed flows and requires precise nginx routing.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p><code>/frame-count</code> (路径 <code>packages/client/src/pages/frame-count/</code>) 是 cuberoot.me 最依赖这套栈的工具, 给魔方裁判 / 选手用于精确数帧、检测违规 sliding、计算 WCA 公式起表帧。整页核心逻辑放在 <code>FrameCountPage.tsx</code> + <code>useFrameBuffer.ts</code> + <code>VideoInfoPanels.tsx</code>, 2716 行 + 1000 行 + 314 行, 是站内最重的单页之一。</p>
        <p><strong>主路径 (95%):</strong> 用户拖一段 .mp4 进来 → <code>useFrameBuffer</code> 用 <code>createFile()</code> 起 mp4box.js, 流式 <code>appendBuffer</code> 全部字节 → <code>onReady</code> 拿 codec 配置 → <code>onSamples</code> 收集所有 EncodedVideoChunk → 配两个 <code>VideoDecoder</code> 分别做缩略图 (I 帧批) 和精确帧 (按 prefetch 范围按需 decode), 解出的 <code>VideoFrame</code> 走 <code>OffscreenCanvas.transferToImageBitmap()</code> 进 LRU 缓存。每次用户按 A 或 D 步进, 直接从缓存吐 <code>ImageBitmap</code> 渲染, 不走 <code>&lt;video&gt;.currentTime</code> seek。</p>
        <p><strong>导出路径:</strong> 用户选定一段帧区间 → 重新走 <code>VideoEncoder</code> 配 <code>avc1.4d0028</code> (H.264 Main) → output 回调把 <code>EncodedVideoChunk</code> 直接喂给 <code>mp4-muxer</code> 的 <code>Muxer({'{'} target: new ArrayBufferTarget(), fastStart: 'in-memory' {'}'})</code> → <code>finalize()</code> 拿 <code>Uint8Array</code> 包成 Blob 让用户下载。中间如果需要 crop, 走 <code>OffscreenCanvas.drawImage(frame, sx, sy, sw, sh, ...)</code> 一次性硬件 crop。整个 encode 过程跑在硬件 encoder 上, 1080p 60fps 大约实时速度。</p>
        <p><strong>兜底路径 (5%):</strong> 如果 mp4box 解析 samples=0 / config 缺失 (<code>parseFailed</code>), 或 VideoDecoder 第一帧就抛 EncodingError (<code>decoderDead</code>), 切到 <code>FFmpeg</code> 实例 (lazy load <code>/ffmpeg/ffmpeg-core.js</code> + <code>ffmpeg-core.wasm</code> + <code>ffmpeg-core.worker.js</code> 三件套, ~30MB), <code>exec(['-i', 'in.mp4', '-c:v', 'libx264', '-vf', 'fps=60', 'out.mp4'])</code> 转码到 baseline H.264 再交回主路径。导出"只剪不重编"的 trim-only 模式也走 ffmpeg.wasm 的 stream copy, 更省时间。</p>
        <p><strong>iOS Safari 专门绕路:</strong> iOS Safari 单页 GPU 内存极紧 (~1GB), 缩略图分辨率封顶 540p, LRU 缓存从 360 帧降到 60 帧, 并发 decode 强制串行 (桌面端 2 路并行)。VFR iPhone 录像 (15-67fps 大幅波动) 在 <code>useFrameBuffer.findStartFrameByTimestamp</code> 里用 sample timestamp 反推起表帧, 而不是相信单一 fps 标量 —— WCA 起表帧 ±1 帧的争议从此消失。OffscreenCanvas warmup (<code>fillRect</code> + <code>transferToImageBitmap().close()</code>) 也是 iOS Safari 第一帧全黑 race 的兜底。</p>
        <p>这套管线在 <code>core/timeline_commits.json</code> 的 <strong>2026-04-06 ~ 04-16 那 10 天</strong> 集中迭代:从最初的 819 行单页 (只走 <code>&lt;video&gt;</code> + <code>requestVideoFrameCallback</code>), 一路扩到现在的 2716 行 + 完整 useFrameBuffer hook, 接入 mp4box / mp4-muxer / ffmpeg.wasm 四件套全栈。</p>
      </>
    ),
    en: (
      <>
        <p><code>/frame-count</code> (at <code>packages/client/src/pages/frame-count/</code>) is the tool that leans hardest on this stack — built for cubing judges and competitors to count frames precisely, detect sliding violations, and resolve the WCA formula's start frame. Core logic lives in <code>FrameCountPage.tsx</code> + <code>useFrameBuffer.ts</code> + <code>VideoInfoPanels.tsx</code> (2716 + 1000 + 314 lines), one of the heaviest single pages on the site.</p>
        <p><strong>Main path (95%):</strong> User drops in a .mp4 → <code>useFrameBuffer</code> starts mp4box.js via <code>createFile()</code>, streams every byte through <code>appendBuffer</code> → <code>onReady</code> yields codec config → <code>onSamples</code> collects every EncodedVideoChunk → two <code>VideoDecoder</code> instances drive (1) thumbnails (I-frame pass) and (2) exact frames (on-demand decode within prefetch range). Decoded <code>VideoFrame</code>s go through <code>OffscreenCanvas.transferToImageBitmap()</code> into an LRU cache. When the user presses A or D, the next <code>ImageBitmap</code> comes straight from the cache — no <code>&lt;video&gt;.currentTime</code> seek.</p>
        <p><strong>Export path:</strong> User picks a frame range → fresh <code>VideoEncoder</code> with <code>avc1.4d0028</code> (H.264 Main) → output callback hands every <code>EncodedVideoChunk</code> to <code>mp4-muxer</code>'s <code>Muxer({'{'} target: new ArrayBufferTarget(), fastStart: 'in-memory' {'}'})</code> → <code>finalize()</code> returns a <code>Uint8Array</code>, wrapped in a Blob for download. If crop is needed, a single <code>OffscreenCanvas.drawImage(frame, sx, sy, sw, sh, ...)</code> handles it on the GPU. The whole encode runs on hardware silicon — roughly real-time at 1080p 60fps.</p>
        <p><strong>Fallback path (5%):</strong> If mp4box parses samples=0 / config missing (<code>parseFailed</code>), or VideoDecoder throws EncodingError on the first frame (<code>decoderDead</code>), we swap to an <code>FFmpeg</code> instance (lazy load <code>/ffmpeg/ffmpeg-core.js</code> + <code>ffmpeg-core.wasm</code> + <code>ffmpeg-core.worker.js</code>, ~30MB), then <code>exec(['-i', 'in.mp4', '-c:v', 'libx264', '-vf', 'fps=60', 'out.mp4'])</code> transcodes to baseline H.264 and hands back to the main path. The "trim-only" export mode also goes through ffmpeg.wasm using a stream copy — faster than re-encoding.</p>
        <p><strong>iOS Safari workarounds:</strong> Single-page GPU memory is tight on iOS Safari (~1GB), so thumbnails cap at 540p, the LRU cache drops from 360 to 60 frames, and concurrent decodes are forced serial (desktop runs 2-way). VFR iPhone clips (15-67fps swings) get start-frame derivation via <code>useFrameBuffer.findStartFrameByTimestamp</code>, which trusts sample timestamps over a single fps scalar — ending the ±1-frame WCA start-frame dispute. The OffscreenCanvas warmup pass (<code>fillRect</code> + <code>transferToImageBitmap().close()</code>) is also the safety net for the iOS Safari "first frame is black" race.</p>
        <p>This pipeline was built up across <strong>2026-04-06 to 04-16</strong> in <code>core/timeline_commits.json</code> — 10 days from the initial 819-line single-page (which only used <code>&lt;video&gt;</code> + <code>requestVideoFrameCallback</code>) to the current 2716 lines plus the full useFrameBuffer hook, wiring in all four pieces of the stack.</p>
      </>
    ),
  },
  links: [
    { label: 'WebCodecs · MDN', href: 'https://developer.mozilla.org/docs/Web/API/WebCodecs_API' },
    { label: 'GitHub · gpac/mp4box.js', href: 'https://github.com/gpac/mp4box.js' },
    { label: 'GitHub · Vanilagy/mp4-muxer', href: 'https://github.com/Vanilagy/mp4-muxer' },
    { label: 'GitHub · ffmpegwasm/ffmpeg.wasm', href: 'https://github.com/ffmpegwasm/ffmpeg.wasm' },
    { label: 'Chrome · WebCodecs intro', href: 'https://developer.chrome.com/docs/web-platform/best-practices/webcodecs' },
  ],
};
