import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { beforeAll, afterAll, describe, it, expect } from 'vitest';
const url = process.env.APPLE_IAP_TEST_DATABASE_URL;
describe.skipIf(!url)('Apple subscription migration on isolated PostgreSQL', () => {
  const schema = `apple_iap_${randomUUID().replaceAll('-', '')}`;
  let admin: ReturnType<typeof postgres>, db: ReturnType<typeof postgres>;
  const token = randomUUID();
  beforeAll(async () => {
    const parsed = new URL(url!);
    if (parsed.hostname !== '127.0.0.1' || parsed.pathname !== '/apple_iap_test') throw new Error('Dedicated loopback apple_iap_test required');
    admin = postgres(url!, { max: 1, onnotice: () => {} });
    await admin.unsafe(`CREATE SCHEMA ${schema}`);
    db = postgres(url!, { max: 1, connection: { search_path: schema, timezone: 'UTC' }, onnotice: () => {} });
    await db.unsafe('CREATE TABLE app_users(id BIGINT PRIMARY KEY,wca_id TEXT,display_name TEXT,avatar_url TEXT)');
    const snapshot = readFileSync(new URL('../src/db/schema.pg.sql', import.meta.url), 'utf8');
    // Production added vip_number after the original columns. A SELECT * UNION
    // passed against the snapshot's different order but failed on that schema.
    const membershipTable = snapshot.match(/CREATE TABLE memberships \([\s\S]*?\n\);/)![0];
    await db.unsafe(membershipTable.replace(/^\s*vip_number[^\n]*\n/m, ''));
    await db.unsafe('ALTER TABLE memberships ADD COLUMN vip_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE');
    await db.unsafe(readFileSync(new URL('../migrations/0254_apple_membership.sql', import.meta.url), 'utf8'));
    await db.unsafe("INSERT INTO app_users VALUES(7,NULL,'Fixture',NULL)");
    await db.unsafe('INSERT INTO apple_membership_accounts(token,user_id) VALUES($1,7)', [token]);
    await db.unsafe(`INSERT INTO apple_membership_subscriptions VALUES('Production','1000',$1,'1001','me.cuberoot.app.membership.monthly',1,'2030-01-01',true,true,'signed-fixture','signed-fixture',NOW())`, [token]);
  });
  afterAll(async () => { await db?.end(); if (admin) { await admin.unsafe(`DROP SCHEMA ${schema} CASCADE`); await admin.end(); } });
  it('grants Apple-only membership to an account without a WCA identity', async () => {
    expect((await db.unsafe("SELECT source FROM effective_memberships WHERE wca_id='u7'"))[0].source).toBe('apple');
  });
  it('does not add Apple and website durations; refunds preserve the website grant', async () => {
    await db.unsafe("INSERT INTO memberships(wca_id,plan_slug,expires_at) VALUES('u7','yearly','2029-01-01')");
    expect((await db.unsafe("SELECT expires_at FROM effective_memberships WHERE wca_id='u7'"))[0].expires_at.toISOString()).toBe('2030-01-01T00:00:00.000Z');
    await db.unsafe("UPDATE apple_membership_subscriptions SET status=5");
    expect((await db.unsafe("SELECT expires_at FROM effective_memberships WHERE wca_id='u7'"))[0].expires_at.toISOString()).toBe('2029-01-01T00:00:00.000Z');
  });
  it('keeps lifetime website membership ahead of an Apple grant', async () => {
    await db.unsafe('UPDATE apple_membership_subscriptions SET status=1');
    await db.unsafe("UPDATE memberships SET expires_at=NULL WHERE wca_id='u7'");
    expect((await db.unsafe("SELECT expires_at FROM effective_memberships WHERE wca_id='u7'"))[0].expires_at).toBeNull();
  });
  it('preserves original tokens and moves Apple grants atomically during a confirmed merge', async () => {
    await db.unsafe("INSERT INTO app_users VALUES(8,NULL,'Retained',NULL)");
    await expect(db.begin(async tx => {
      await tx.unsafe('UPDATE apple_membership_accounts SET user_id=8 WHERE user_id=7');
      expect((await tx.unsafe("SELECT source FROM effective_memberships WHERE wca_id='u8'"))[0].source).toBe('apple');
      expect((await tx.unsafe('SELECT token FROM apple_membership_accounts'))[0].token).toBe(token);
      throw new Error('rollback fixture');
    })).rejects.toThrow('rollback fixture');
    expect(Number((await db.unsafe('SELECT user_id FROM apple_membership_accounts'))[0].user_id)).toBe(7);
  });
  it('account deletion tombstones the token and retains transaction evidence', async () => {
    await db.unsafe('DELETE FROM app_users WHERE id=7');
    expect((await db.unsafe('SELECT user_id FROM apple_membership_accounts'))[0].user_id).toBeNull();
    expect((await db.unsafe('SELECT * FROM apple_membership_subscriptions')).length).toBe(1);
    expect((await db.unsafe("SELECT * FROM effective_memberships WHERE source='apple'")).length).toBe(0);
  });
});
