import { afterEach, expect, it, vi } from 'vitest';
import { Hono } from 'hono';
import { CompetitionCaptchaStore, renderCompetitionCaptcha, issueCompetitionCaptcha, submitCompetitionCaptcha } from '../src/utils/competition_captcha';
import { verifyCompetitionProof, COMPETITION_ACCESS_COOKIE } from '@cuberoot/shared/competition-access';
const secret = 'test-only-secret-with-more-than-32-characters';
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllEnvs(); });
it('consumes a correct answer once; rejects wrong browser, expired code and three failures', () => {
  const store = new CompetitionCaptchaStore();
  const a = store.issue('a', 1000)!;
  expect(store.consume(a.id, a.answer, 'b', 1001)).toBe(false);
  expect(store.consume(a.id, a.answer.toLowerCase(), 'a', 1002)).toBe(true);
  expect(store.consume(a.id, a.answer, 'a', 1003)).toBe(false);
  const b = store.issue('a', 1000)!;
  for (let i = 0; i < 3; i++) expect(store.consume(b.id, 'WRONG', 'a', 1001)).toBe(false);
  expect(store.consume(b.id, b.answer, 'a', 1002)).toBe(false);
  const c = store.issue('a', 1000)!;
  expect(store.consume(c.id, c.answer, 'a', 121000)).toBe(false);
  for (let i = 0; i < 6; i++) expect(store.allow('ip', 6, 1000)).toBe(true);
  expect(store.allow('ip', 6, 1001)).toBe(false);
  expect(store.allow('ip', 6, 61000)).toBe(true);
});
it('renders glyph outlines without exposing answer text', () => {
  const image = renderCompetitionCaptcha('ABC234');
  expect(image).toContain('<path');
  expect(image).not.toContain('<text');
  expect(image).not.toContain('ABC234');
});
it('HTTP endpoints never expose an answer, reject bad origin, and mint only after one-use validation', async () => {
  vi.stubEnv('COMPETITION_ACCESS_SECRET', secret);
  const app = new Hono();
  app.get('/challenge', issueCompetitionCaptcha); app.post('/verify', submitCompetitionCaptcha);
  const consumed = vi.spyOn(CompetitionCaptchaStore.prototype, 'consume');
  const issued = vi.spyOn(CompetitionCaptchaStore.prototype, 'issue');
  const headers = { 'user-agent': 'test-browser', origin: 'https://cuberoot.me', 'content-type': 'application/json' };
  const response = await app.request('/challenge', { headers });
  expect(response.status).toBe(200);
  const body = await response.json();
  expect(Object.keys(body).sort()).toEqual(['expiresIn', 'id', 'image']);
  const answer = issued.mock.results[0].value.answer;
  const submit = (value: string, origin = headers.origin) => app.request('/verify', { method: 'POST', headers: { ...headers, origin }, body: JSON.stringify({ id: body.id, answer: value }) });
  expect((await submit(answer, 'https://evil.example')).status).toBe(403);
  expect(consumed).not.toHaveBeenCalled();
  expect((await submit('WRONG')).status).toBe(400);
  const good = await submit(answer);
  expect(good.status).toBe(200);
  const cookie = good.headers.get('set-cookie')!;
  expect(cookie).toContain('HttpOnly; Secure; SameSite=Lax');
  const proof = cookie.split(';')[0].slice(COMPETITION_ACCESS_COOKIE.length + 1);
  expect(await verifyCompetitionProof(secret, proof, 'browser', 'test-browser')).toBe(true);
  expect((await submit(answer)).status).toBe(400);
});
