import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { sql } from '../src/db/connection.js';
import { issueCode, verifyCode, markCodeDelivery, loginWithIdentity, findUserByIdentity, withVerifiedCode } from '../src/utils/account.js';
import { bindEmailWithCode, issueEmailCode, loginWithEmailCode } from '../src/utils/email_code_auth.js';

const enabled = process.env.EMAIL_CODE_PG_TEST === '1'
  && process.env.DB_NAME === 'email_code_test' && process.env.DB_HOST === '127.0.0.1';
const send = vi.fn<typeof fetch>();
async function pending(target: string, purpose: 'login' | 'link' = 'login') {
  const issued = await issueCode('email', target, purpose, undefined, { deliveryStatus: 'pending' });
  if ('error' in issued) throw new Error('unexpected cooldown');
  return issued;
}
async function sent(target: string, purpose: 'login' | 'link' = 'login') {
  const issued = await pending(target, purpose);
  expect(await markCodeDelivery(issued.id, 'sent')).toBe(true);
  return issued;
}
async function row(id: string) { return (await sql`SELECT * FROM auth_codes WHERE id = ${id}`)[0]; }

describe.skipIf(!enabled)('email code lifecycle on dedicated PostgreSQL', () => {
  beforeAll(async () => {
    await sql.unsafe(`CREATE TABLE app_users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      display_name TEXT NOT NULL DEFAULT '', avatar_url TEXT, avatar_source TEXT NOT NULL DEFAULT 'auto',
      avatar_preset TEXT, wca_id TEXT UNIQUE, is_admin BOOLEAN NOT NULL DEFAULT FALSE,
      country_iso2 TEXT, region_code TEXT, city_name TEXT, merged_into_user_id BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE auth_identities (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES app_users(id), provider VARCHAR(16) NOT NULL, provider_uid TEXT NOT NULL,
      verified_at TIMESTAMPTZ, apple_refresh_token_encrypted BYTEA, apple_token_key_version SMALLINT,
      UNIQUE(provider, provider_uid)
    );
    CREATE UNIQUE INDEX uq_email ON auth_identities(user_id) WHERE provider = 'email';
    CREATE UNIQUE INDEX uq_phone ON auth_identities(user_id) WHERE provider = 'phone';
    CREATE TABLE auth_web_session_tickets(ticket_hash CHAR(64) PRIMARY KEY);
    CREATE TABLE auth_codes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, channel VARCHAR(8) NOT NULL,
      target VARCHAR(320) NOT NULL, purpose VARCHAR(16) NOT NULL DEFAULT 'login', code_hash TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL, attempts INT NOT NULL DEFAULT 0, consumed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`);
    const oldHash = createHash('sha256').update(`${process.env.AUTH_CODE_PEPPER}:email:legacy@example.invalid:012345`).digest('hex');
    await sql`INSERT INTO auth_codes(channel,target,purpose,code_hash,expires_at) VALUES('email','legacy@example.invalid','login',${oldHash},NOW()+INTERVAL '10 minutes')`;
    await sql.unsafe(await readFile(new URL('../migrations/0243_auth_code_delivery.sql', import.meta.url), 'utf8'));
    await sql.unsafe(await readFile(new URL('../migrations/0232_auth_identity_pending.sql', import.meta.url), 'utf8'));
    await sql.unsafe(await readFile(new URL('../migrations/0234_auth_identity_choice_providers.sql', import.meta.url), 'utf8'));
  });
  beforeEach(() => { send.mockReset(); send.mockResolvedValue(new Response(JSON.stringify({ id: 'synthetic-message' }))); vi.stubGlobal('fetch', send); });
  afterEach(() => vi.unstubAllGlobals());
  afterAll(async () => { await sql.end(); });

  it('additive migration preserves the exact legacy hash and in-flight code', async () => {
    const [old] = await sql`SELECT * FROM auth_codes WHERE target = 'legacy@example.invalid'`;
    expect(old.delivery_status).toBe('sent'); expect(String(old.code_hash)).toHaveLength(64);
    expect(await verifyCode('email', 'legacy@example.invalid', 'login', '012345')).toBe(true);
    expect(await verifyCode('email', 'legacy@example.invalid', 'login', '012345')).toBe(false);
  });

  it('pending/failed code is unusable and only the exact reservation can be activated', async () => {
    const issued = await pending('pending@example.invalid');
    expect(await verifyCode('email', 'pending@example.invalid', 'login', issued.code)).toBe(false);
    expect(await markCodeDelivery(issued.id, 'failed')).toBe(true);
    expect(await markCodeDelivery(issued.id, 'sent')).toBe(false);
    expect(await verifyCode('email', 'pending@example.invalid', 'login', issued.code)).toBe(false);
  });

  it('concurrent absent-target issuance allows one code and applies cooldown across purposes', async () => {
    const results = await Promise.all(Array.from({ length: 10 }, (_, i) => issueCode('email', 'raced@example.invalid', i % 2 ? 'login' : 'link', undefined, { deliveryStatus: 'pending' })));
    expect(results.filter(result => 'code' in result)).toHaveLength(1);
    expect(results.filter(result => 'error' in result)).toHaveLength(9);
    expect(await sql`SELECT id FROM auth_codes WHERE target = 'raced@example.invalid'`).toHaveLength(1);
  });

  it('superseded and expired deliveries cannot revive codes or activate their replacements', async () => {
    const first = await pending('late@example.invalid');
    await sql`UPDATE auth_codes SET created_at = NOW()-INTERVAL '61 seconds' WHERE id = ${first.id}`;
    const second = await pending('late@example.invalid');
    expect(await markCodeDelivery(first.id, 'sent')).toBe(false);
    expect((await row(second.id)).delivery_status).toBe('pending');
    expect(await markCodeDelivery(second.id, 'sent')).toBe(true);
    expect((await row(first.id)).consumed_at).not.toBeNull();
    expect(await verifyCode('email', 'late@example.invalid', 'login', second.code)).toBe(true);
    const expired = await pending('expired@example.invalid');
    await sql`UPDATE auth_codes SET expires_at=NOW()-INTERVAL '1 second' WHERE id=${expired.id}`;
    expect(await markCodeDelivery(expired.id, 'sent')).toBe(false);
  });

  it('expiry is rechecked after waiting for a held code row lock', async () => {
    const issued = await sent('lock-expiry@example.invalid');
    await sql`UPDATE auth_codes SET expires_at=clock_timestamp()+INTERVAL '400 milliseconds' WHERE id=${issued.id}`;
    let release!: () => void; let locked!: () => void;
    const ready = new Promise<void>(resolve => { locked = resolve; });
    const barrier = new Promise<void>(resolve => { release = resolve; });
    const holder = sql.begin(async transaction => {
      await transaction`SELECT id FROM auth_codes WHERE id=${issued.id} FOR UPDATE`;
      locked(); await barrier;
    });
    await ready;
    const verification = verifyCode('email', 'lock-expiry@example.invalid', 'login', issued.code);
    await new Promise(resolve => setTimeout(resolve, 600)); release(); await holder;
    expect(await verification).toBe(false); expect((await row(issued.id)).consumed_at).toBeNull();
  });

  it('real email orchestration exposes pending during I/O and marks only successful delivery sent', async () => {
    send.mockImplementation(async (_url, request) => {
      const message = JSON.parse(String(request?.body));
      const code = String(message.subject).match(/[0-9]{6}/)![0];
      const target = message.to[0];
      expect(await verifyCode('email', target, 'login', code)).toBe(false);
      return new Response('{"id":"synthetic-message"}');
    });
    expect(await issueEmailCode('delivered@example.invalid', 'login', 'en')).toEqual({ ok: true });
    const [stored] = await sql`SELECT delivery_status FROM auth_codes WHERE target='delivered@example.invalid'`;
    expect(stored.delivery_status).toBe('sent');
    expect(send).toHaveBeenCalledTimes(1);
  });

  it('provider and network failures mark failed, keep cooldown and never resend automatically', async () => {
    for (const [target, fail] of [['reject@example.invalid', false], ['network@example.invalid', true]] as const) {
      send.mockImplementationOnce(async () => { if (fail) throw new Error('synthetic sensitive upstream body'); return new Response('sensitive recipient body', { status: 503 }); });
      await expect(issueEmailCode(target, 'login', 'zh')).rejects.toMatchObject({ code: 'send_failed', message: 'send_failed' });
      const [stored] = await sql`SELECT delivery_status FROM auth_codes WHERE target=${target}`;
      expect(stored.delivery_status).toBe('failed');
      expect(await issueEmailCode(target, 'login', 'zh')).toEqual({ error: 'cooldown' });
    }
    expect(send).toHaveBeenCalledTimes(2);
  });

  it('ambiguous shared-transport 2xx response does not activate a code or automatically send again', async () => {
    send.mockResolvedValueOnce(new Response(null, { status: 204 }));
    await expect(issueEmailCode('ambiguous@example.invalid', 'login', 'en')).rejects.toMatchObject({ code: 'send_failed' });
    const [stored] = await sql`SELECT delivery_status FROM auth_codes WHERE target='ambiguous@example.invalid'`;
    expect(stored.delivery_status).toBe('failed'); expect(send).toHaveBeenCalledTimes(1);
  });

  it('delivery-state storage failure keeps the accepted email code unusable and hides database errors', async () => {
    await sql.unsafe(`CREATE FUNCTION reject_code_activation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF NEW.target='activation-fault@example.invalid' THEN RAISE EXCEPTION 'synthetic private storage failure'; END IF;
      RETURN NEW; END $$;
      CREATE TRIGGER fail_code_activation BEFORE UPDATE ON auth_codes FOR EACH ROW EXECUTE FUNCTION reject_code_activation();`);
    try {
      await expect(issueEmailCode('activation-fault@example.invalid', 'login', 'en')).rejects.toMatchObject({ code: 'send_failed', message: 'send_failed' });
      const [stored] = await sql`SELECT delivery_status FROM auth_codes WHERE target='activation-fault@example.invalid'`;
      expect(stored.delivery_status).toBe('pending'); expect(send).toHaveBeenCalledTimes(1);
    } finally { await sql`DROP TRIGGER fail_code_activation ON auth_codes`; }
  });

  it('failed guesses commit and five concurrent guesses burn the code without a successful action', async () => {
    const issued = await sent('guesses@example.invalid'); const wrong = issued.code === '000000' ? '000001' : '000000';
    const action = vi.fn();
    const results = await Promise.all(Array.from({ length: 10 }, () => withVerifiedCode('email', 'guesses@example.invalid', 'login', wrong, action)));
    expect(results.every(result => !result.verified)).toBe(true); expect(action).not.toHaveBeenCalled();
    const stored = await row(issued.id); expect(stored.attempts).toBe(5); expect(stored.consumed_at).not.toBeNull();
    expect(await verifyCode('email', 'guesses@example.invalid', 'login', issued.code)).toBe(false);
  });

  it('account-choice write failure rolls back proof; exact retry creates one ticket', async () => {
    const issued = await sent('choice@example.invalid');
    await sql.unsafe(`CREATE FUNCTION reject_choice() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic choice failure'; END $$;
      CREATE TRIGGER fail_choice BEFORE INSERT ON auth_identity_pending FOR EACH ROW EXECUTE FUNCTION reject_choice();`);
    await expect(loginWithEmailCode('choice@example.invalid', issued.code, false)).rejects.toThrow('account service unavailable');
    expect((await row(issued.id)).consumed_at).toBeNull();
    await sql`DROP TRIGGER fail_choice ON auth_identity_pending`;
    const results = await Promise.all([loginWithEmailCode('choice@example.invalid', issued.code, false), loginWithEmailCode('choice@example.invalid', issued.code, false)]);
    expect(results.filter(result => result.verified)).toHaveLength(1);
    expect(await sql`SELECT ticket_hash FROM auth_identity_pending WHERE provider_uid='choice@example.invalid'`).toHaveLength(1);
  });

  it('existing-only missing account rolls back consumption, allowing the normal choice flow', async () => {
    const issued = await sent('missing@example.invalid');
    await expect(loginWithEmailCode('missing@example.invalid', issued.code, true)).rejects.toThrow('account not found');
    expect((await row(issued.id)).consumed_at).toBeNull();
    expect((await loginWithEmailCode('missing@example.invalid', issued.code, false)).verified).toBe(true);
  });

  it('existing email login consumes once and retains existing profile behavior', async () => {
    const account = await loginWithIdentity('email', 'existing@example.invalid', { name: '' });
    const issued = await sent('existing@example.invalid');
    const result = await loginWithEmailCode('existing@example.invalid', issued.code, true);
    expect(result.verified).toBe(true);
    if (!result.verified || 'pending' in result.value) throw new Error('missing existing user');
    expect(result.value.user.id).toBe(account.user.id); expect(result.value.user.display_name).toBe('existing');
    expect((await loginWithEmailCode('existing@example.invalid', issued.code, true)).verified).toBe(false);
  });

  it('binding conflict rolls back consumption and leaves both accounts unchanged', async () => {
    const owner = await loginWithIdentity('email', 'owned@example.invalid', { name: 'owner' });
    const other = await loginWithIdentity('google', 'binding-other', { name: 'other' });
    const issued = await sent('owned@example.invalid', 'link');
    await expect(bindEmailWithCode(other.user.id, 'owned@example.invalid', issued.code)).rejects.toMatchObject({ code: 'conflict' });
    expect((await row(issued.id)).consumed_at).toBeNull();
    expect((await findUserByIdentity('email', 'owned@example.invalid'))?.id).toBe(owner.user.id);
    expect((await bindEmailWithCode(owner.user.id, 'owned@example.invalid', issued.code)).verified).toBe(true);
  });

  it('binding storage fault rolls back identity and consumption, then exact retry succeeds', async () => {
    const owner = await loginWithIdentity('google', 'bind-fault-owner', { name: 'owner' });
    const issued = await sent('bind-fault@example.invalid', 'link');
    await sql.unsafe(`CREATE FUNCTION reject_email_identity() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.provider='email' THEN RAISE EXCEPTION 'synthetic identity failure'; END IF; RETURN NEW; END $$;
      CREATE TRIGGER fail_identity BEFORE INSERT OR UPDATE ON auth_identities FOR EACH ROW EXECUTE FUNCTION reject_email_identity();`);
    await expect(bindEmailWithCode(owner.user.id, 'bind-fault@example.invalid', issued.code)).rejects.toThrow();
    expect((await row(issued.id)).consumed_at).toBeNull(); expect(await findUserByIdentity('email', 'bind-fault@example.invalid')).toBeNull();
    await sql`DROP TRIGGER fail_identity ON auth_identities`;
    expect((await bindEmailWithCode(owner.user.id, 'bind-fault@example.invalid', issued.code)).verified).toBe(true);
  });

  it('email replacement failure preserves the old identity and proof, successful retry commits both', async () => {
    const owner = await loginWithIdentity('email', 'replace-old@example.invalid', { name: 'owner' });
    const issued = await sent('replace-new@example.invalid', 'link');
    await sql.unsafe(`CREATE TRIGGER fail_identity BEFORE INSERT OR UPDATE ON auth_identities FOR EACH ROW EXECUTE FUNCTION reject_email_identity();`);
    await expect(bindEmailWithCode(owner.user.id, 'replace-new@example.invalid', issued.code, true)).rejects.toMatchObject({ code: 'conflict' });
    expect((await row(issued.id)).consumed_at).toBeNull(); expect((await findUserByIdentity('email', 'replace-old@example.invalid'))?.id).toBe(owner.user.id);
    await sql`DROP TRIGGER fail_identity ON auth_identities`;
    expect((await bindEmailWithCode(owner.user.id, 'replace-new@example.invalid', issued.code, true)).verified).toBe(true);
    expect(await findUserByIdentity('email', 'replace-old@example.invalid')).toBeNull(); expect((await findUserByIdentity('email', 'replace-new@example.invalid'))?.id).toBe(owner.user.id);
  });

  it('phone/internal channels preserve existing sent and consume:false behavior', async () => {
    for (const [channel, target, purpose] of [['phone', '+8613900000001', 'login'], ['merge', '123', 'account_merge'], ['id_link', '456', 'identity_link']] as const) {
      const issued = await issueCode(channel, target, purpose); if ('error' in issued) throw new Error('unexpected cooldown');
      expect((await row(issued.id)).delivery_status).toBe('sent');
      expect(await verifyCode(channel, target, purpose, issued.code, { consume: false })).toBe(true);
      expect((await row(issued.id)).consumed_at).toBeNull();
      expect(await verifyCode(channel, target, purpose, issued.code)).toBe(true);
      expect(await verifyCode(channel, target, purpose, issued.code)).toBe(false);
    }
  });
});
