import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { afterAll, beforeAll, expect, it, vi, describe } from 'vitest';
import { HTTPException } from 'hono/http-exception';
const mocks = vi.hoisted(() => ({ sql: null as unknown as ReturnType<typeof postgres>, actor: 1, admin: false }));
vi.mock('../src/db/connection.js', () => ({ get sql() { return mocks.sql; } }));
vi.mock('../src/utils/app_user_auth.js', () => ({ requireAppUserId: async () => { if (!mocks.actor) throw new HTTPException(401); return mocks.actor; } }));
vi.mock('../src/utils/recon_helpers.js', () => ({ checkRateLimit: () => {}, requireAdmin: async () => { if (!mocks.admin) throw new HTTPException(403); } }));
import { enterpriseVerificationRoutes as app } from '../src/routes/enterprise_verification.js';
const enabled = process.env.ENTERPRISE_PG_TEST === '1';
const schema = 'test_enterprise_' + randomUUID().replaceAll('-', '');
const org = '11111111-1111-4111-8111-111111111111';
const otherOrg = '22222222-2222-4222-8222-222222222222';
const image = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a9sAAAAASUVORK5CYII=';
const draft = { legalName: '测试企业', creditCode: '91350211M000100Y46', representative: '测试法人', contactName: '测试经办人', contactPhone: '13800000000', payerAccount: '123456789012', payerBank: '测试付款银行', licenseDataUrl: image, declaration: true };
const settings = { enabled: true, accountName: '测试收款企业', accountNumber: '987654321012', bankName: '测试招商银行', refundNotice: '测试退款说明' };
const call = (path: string, method = 'GET', data?: unknown, key = randomUUID()) => app.request('/enterprise-verification' + path, { method, headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key }, ...(data ? { body: JSON.stringify(data) } : {}) });
let application: Record<string, any>;
const savedKey = process.env.ENTERPRISE_VERIFICATION_KEY;
describe.skipIf(!enabled)('enterprise verification against isolated PostgreSQL schema', () => {
  beforeAll(async () => {
    mocks.sql = postgres({ host: '/tmp/cuberoot-institution-pg', port: 54329, database: 'postgres', max: 2, onnotice: () => {}, connection: { search_path: schema } });
    await mocks.sql.unsafe(`CREATE SCHEMA ${schema}`);
    await mocks.sql.unsafe(`CREATE TABLE app_users(id BIGINT PRIMARY KEY); INSERT INTO app_users VALUES (1),(2),(3);
      CREATE TABLE organizations(id UUID PRIMARY KEY, slug TEXT, status TEXT);
      CREATE TABLE organization_members(organization_id UUID, user_id BIGINT, role TEXT, status TEXT);
      INSERT INTO organizations VALUES ('${org}','test-enterprise','active'),('${otherOrg}','other-enterprise','active');
      INSERT INTO organization_members VALUES ('${org}',1,'owner','active'),('${otherOrg}',3,'owner','active');`);
    await mocks.sql.unsafe(await readFile(new URL('../migrations/0271_enterprise_verification.sql', import.meta.url), 'utf8'));
    process.env.ENTERPRISE_VERIFICATION_KEY = Buffer.alloc(32, 71).toString('base64');
  });
  afterAll(async () => {
    await mocks.sql.unsafe(`DROP SCHEMA ${schema} CASCADE`); await mocks.sql.end();
    if (savedKey === undefined) delete process.env.ENTERPRISE_VERIFICATION_KEY; else process.env.ENTERPRISE_VERIFICATION_KEY = savedKey;
  });
  it('denies anonymous, cross-tenant and non-admin access; fails closed without configuration', async () => {
    mocks.actor = 0; expect((await call('/organizations/test-enterprise')).status).toBe(401);
    mocks.actor = 3; expect((await call('/organizations/test-enterprise')).status).toBe(403);
    mocks.actor = 1; expect((await call('/admin/settings')).status).toBe(403);
    expect((await call('/organizations/test-enterprise', 'POST', draft)).status).toBe(503);
    expect((await (await call('/organizations/test-enterprise')).json()).available).toBe(false);
  });
  it('requires encryption and serializes idempotent requests; keeps recipient snapshots immutable', async () => {
    mocks.admin = true; mocks.actor = 2; delete process.env.ENTERPRISE_VERIFICATION_KEY;
    expect((await call('/admin/settings', 'PUT', settings)).status).toBe(503);
    process.env.ENTERPRISE_VERIFICATION_KEY = Buffer.alloc(32, 71).toString('base64');
    expect((await call('/admin/settings', 'PUT', settings)).status).toBe(200);
    mocks.admin = false; mocks.actor = 1;
    const key = randomUUID();
    const responses = await Promise.all([call('/organizations/test-enterprise', 'POST', draft, key), call('/organizations/test-enterprise', 'POST', draft, key)]);
    expect(responses.map(r => r.status)).toEqual([201,201]);
    const values = await Promise.all(responses.map(r => r.json())); application = values[0].application;
    expect(values[1].application.id).toBe(application.id);
    expect((await call('/organizations/test-enterprise', 'POST', { ...draft, contactName: '其他人' }, key)).status).toBe(409);
    const stored = await mocks.sql`SELECT * FROM enterprise_verification_applications WHERE id = ${application.id}`;
    expect(stored[0].encrypted_details.toString()).not.toContain(draft.payerAccount);
    expect(JSON.stringify(values[0])).not.toContain('licenseDataUrl');
    mocks.admin = true; mocks.actor = 2;
    expect((await call('/admin/settings', 'PUT', { ...settings, accountNumber: '999999999999' })).status).toBe(200);
    mocks.admin = false; mocks.actor = 1;
    const state = await (await call('/organizations/test-enterprise')).json();
    expect(state.application.recipient.accountNumber).toBe(settings.accountNumber);
  });
  it('never verifies from a declaration alone; rejects self review and incorrect bank evidence', async () => {
    expect((await call(`/organizations/test-enterprise/${application.id}/submit`, 'POST', {})).status).toBe(200);
    expect((await call(`/organizations/test-enterprise/${application.id}/submit`, 'POST', {})).status).toBe(200);
    expect((await (await call('/organizations/test-enterprise')).json()).application.status).toBe('pending_review');
    mocks.admin = true;
    const review = { decision: 'verify', note: '核对测试', registryChecked: true, licenseChecked: true, authorizationChecked: true };
    expect((await call(`/admin/applications/${application.id}/review`, 'POST', review)).status).toBe(403);
    mocks.actor = 2;
    expect((await call(`/admin/applications/${application.id}/review`, 'POST', review)).status).toBe(400);
    const receipt = { transactionId: 'BANK-1', payerName: draft.legalName, payerAccount: draft.payerAccount, amountMinor: application.amountMinor, reference: application.transferReference, receivedAt: new Date().toISOString() };
    expect((await call(`/admin/applications/${application.id}/review`, 'POST', { ...review, receipt: { ...receipt, payerName: '冒名企业' } })).status).toBe(400);
    expect((await call(`/admin/applications/${application.id}/review`, 'POST', { ...review, registryChecked: false, receipt })).status).toBe(400);
    expect((await call(`/admin/applications/${application.id}/review`, 'POST', { ...review, receipt })).status).toBe(200);
    expect((await call(`/admin/applications/${application.id}/review`, 'POST', { ...review, receipt })).status).toBe(409);
  });
  it('prevents duplicate certification and tracks actual refunds and revocation', async () => {
    mocks.actor = 3; mocks.admin = false;
    expect((await call('/organizations/other-enterprise', 'POST', draft)).status).toBe(409);
    mocks.actor = 2; mocks.admin = true;
    const path = `/admin/applications/${application.id}/refund`;
    expect((await call(path, 'POST', { reference: 'REFUND-1' })).status).toBe(400);
    expect((await call(path, 'POST', { reference: 'REFUND-1', returnedToOriginalAccount: true })).status).toBe(200);
    expect((await call(path, 'POST', { reference: 'REFUND-1', returnedToOriginalAccount: true })).status).toBe(200);
    expect((await call(path, 'POST', { reference: 'REFUND-2', returnedToOriginalAccount: true })).status).toBe(409);
    const detail = await (await call(`/admin/applications/${application.id}`)).json();
    expect(detail.application.refundedAt).toBeTruthy(); expect(detail.details.refundReference).toBe('REFUND-1'); expect(detail.details.licenseDataUrl).toBe(image);
    const events = await mocks.sql`SELECT action FROM enterprise_verification_events WHERE application_id = ${application.id} ORDER BY id`;
    expect(events.map(e => e.action)).toEqual(['application.created','transfer.declared','application.verified','refund.recorded','materials.viewed']);
    expect((await call(`/admin/applications/${application.id}/revoke`, 'POST', { note: '企业资料变化' })).status).toBe(200);
    mocks.actor = 1; mocks.admin = false;
    expect((await (await call('/organizations/test-enterprise')).json()).application.status).toBe('revoked');
    expect((await call(`/admin/applications/${application.id}`)).status).toBe(403);
  });
  it('rejects reused bank transactions and expired submissions, without changing old materials', async () => {
    const response = await call('/organizations/test-enterprise', 'POST', draft); expect(response.status).toBe(201);
    const next = (await response.json()).application;
    // Uniqueness is enforced by PostgreSQL even if two reviews race.
    const previous = (await mocks.sql`SELECT bank_transaction_hash FROM enterprise_verification_applications WHERE id = ${application.id}`)[0];
    await expect(mocks.sql`UPDATE enterprise_verification_applications SET bank_transaction_hash = ${previous.bank_transaction_hash} WHERE id = ${next.id}`).rejects.toMatchObject({ code: '23505' });
    await mocks.sql`UPDATE enterprise_verification_applications SET created_at = NOW() - INTERVAL '9 days' WHERE id = ${application.id}`;
    await mocks.sql`UPDATE enterprise_verification_applications SET created_at = NOW() - INTERVAL '8 days', expires_at = NOW() - INTERVAL '1 day' WHERE id = ${next.id}`;
    expect((await call(`/organizations/test-enterprise/${next.id}/submit`, 'POST', {})).status).toBe(409);
    expect((await (await call('/organizations/test-enterprise')).json()).application.status).toBe('expired');
    expect((await call('/organizations/test-enterprise', 'POST', draft)).status).toBe(201);
    mocks.actor = 2; mocks.admin = true;
    const receipt = { transactionId: 'WRONG-LATE-1', payerName: '其他付款人', payerAccount: '5555555555', amountMinor: 200, reference: '错误附言', receivedAt: new Date().toISOString() };
    expect((await call(`/admin/applications/${next.id}/receipt`, 'POST', receipt)).status).toBe(200);
    expect((await call(`/admin/applications/${next.id}/refund`, 'POST', { reference: 'RETURN-WRONG-1', returnedToOriginalAccount: true })).status).toBe(200);
    expect((await (await call(`/admin/applications/${next.id}`)).json()).application.status).toBe('expired');
  });
});
