import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import postgres from 'postgres';
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
const mocks = vi.hoisted(() => ({ request: vi.fn(), run: vi.fn(), transaction: vi.fn(), verifyIdToken: vi.fn() }));
vi.mock('../src/db/connection.js', () => ({ query: mocks.run, withTransaction: mocks.transaction }));
vi.mock('google-auth-library', () => ({
  GoogleAuth: class { getAccessToken = async () => 'fixture'; getClient = async () => ({ request: mocks.request }); },
  OAuth2Client: class { verifyIdToken = mocks.verifyIdToken; },
}));
import { googleAccountId, reconcileGoogleSubscription, verifyGooglePushAuthorization } from '../src/payment/google-membership.js';
import type { GoogleSubscription } from '../src/payment/google-membership-policy.js';
const url = process.env.GOOGLE_IAP_TEST_DATABASE_URL;
describe.skipIf(!url)('Google subscriptions on isolated PostgreSQL', () => {
  const schema = `google_iap_${randomUUID().replaceAll('-', '')}`;
  let admin: ReturnType<typeof postgres>, db: ReturnType<typeof postgres>;
  const account = randomUUID();
  let purchase: GoogleSubscription;
  const runner = (sql: ReturnType<typeof postgres> | postgres.TransactionSql) => async (query: string, params: never[] = []) => {
    let index = 0;
    return sql.unsafe(query.replace(/\?/g, () => `$${++index}`), params);
  };
  beforeAll(async () => {
    const parsed = new URL(url!);
    if (parsed.hostname !== '127.0.0.1' || parsed.pathname !== '/google_iap_test') throw new Error('Dedicated loopback google_iap_test required');
    admin = postgres(url!, { max: 1, onnotice: () => {} });
    await admin.unsafe(`CREATE SCHEMA ${schema}`);
    db = postgres(url!, { max: 3, connection: { search_path: schema, timezone: 'UTC' }, onnotice: () => {} });
    await db.unsafe('CREATE TABLE app_users(id BIGINT PRIMARY KEY,wca_id TEXT,display_name TEXT,avatar_url TEXT)');
    const snapshot = readFileSync(new URL('../src/db/schema.pg.sql', import.meta.url), 'utf8');
    const table = snapshot.match(/CREATE TABLE memberships \([\s\S]*?\n\);/)![0];
    await db.unsafe(table.replace(/^\s*vip_number[^\n]*\n/m, ''));
    await db.unsafe('ALTER TABLE memberships ADD COLUMN vip_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE');
    await db.unsafe(readFileSync(new URL('../migrations/0254_apple_membership.sql', import.meta.url), 'utf8'));
    await db.unsafe(readFileSync(new URL('../migrations/0256_google_membership.sql', import.meta.url), 'utf8'));
    mocks.run.mockImplementation(runner(db));
    mocks.transaction.mockImplementation(callback => db.begin(tx => callback(runner(tx))));
    process.env.GOOGLE_IAP_ENABLED = '1'; process.env.GOOGLE_IAP_KEY_PATH = '/fixture-only';
  });
  afterAll(async () => {
    await db?.end(); if (admin) { await admin.unsafe(`DROP SCHEMA ${schema} CASCADE`); await admin.end(); }
    delete process.env.GOOGLE_IAP_ENABLED; delete process.env.GOOGLE_IAP_KEY_PATH; delete process.env.GOOGLE_IAP_TEST_USER_IDS;
  });
  beforeEach(async () => {
    await db.unsafe('TRUNCATE google_membership_subscriptions, google_membership_accounts, apple_membership_subscriptions, apple_membership_accounts, memberships, app_users CASCADE');
    await db.unsafe("INSERT INTO app_users VALUES(7,NULL,'Fixture',NULL),(8,NULL,'Other',NULL)");
    await db.unsafe('INSERT INTO google_membership_accounts(token,user_id) VALUES($1,7)', [account]);
    purchase = { subscriptionState: 'SUBSCRIPTION_STATE_ACTIVE', acknowledgementState: 'ACKNOWLEDGEMENT_STATE_PENDING',
      externalAccountIdentifiers: { obfuscatedExternalAccountId: account },
      lineItems: [{ productId: 'me.cuberoot.app.membership.monthly', expiryTime: '2030-01-01T00:00:00Z', autoRenewingPlan: { autoRenewEnabled: true } }] };
    mocks.request.mockReset().mockImplementation(async args => {
      if (args.method === 'POST') {
        expect((await db.unsafe('SELECT 1 FROM google_membership_subscriptions')).length).toBe(1);
        return { data: {} };
      }
      return { data: structuredClone(purchase) };
    });
    delete process.env.GOOGLE_IAP_TEST_USER_IDS;
  });
  it('reuses server-generated ownership and grants before acknowledgement', async () => {
    expect(await googleAccountId(7)).toBe(account);
    await reconcileGoogleSubscription('purchase-token-1', 7);
    expect((await db.unsafe("SELECT source FROM effective_memberships WHERE wca_id='u7'"))[0].source).toBe('google');
    expect(mocks.request.mock.calls[1][0].method).toBe('POST');
  });
  it('rejects account stealing, unknown ownership and unauthorized test purchases', async () => {
    await expect(reconcileGoogleSubscription('purchase-token-1', 8)).rejects.toThrow();
    purchase.externalAccountIdentifiers = { obfuscatedExternalAccountId: randomUUID() };
    await expect(reconcileGoogleSubscription('purchase-token-1', 7)).rejects.toThrow();
    purchase.externalAccountIdentifiers = { obfuscatedExternalAccountId: account }; purchase.testPurchase = {};
    await expect(reconcileGoogleSubscription('purchase-token-1', 7)).rejects.toThrow();
    expect(await db.unsafe('SELECT * FROM google_membership_subscriptions')).toHaveLength(0);
    process.env.GOOGLE_IAP_TEST_USER_IDS = '7';
    await reconcileGoogleSubscription('purchase-token-1', 7);
  });
  it('refunds revoke only Google grants and cannot resurrect via a repeated hint', async () => {
    await db.unsafe("INSERT INTO memberships(wca_id,plan_slug,expires_at) VALUES('u7','yearly','2029-01-01')");
    await reconcileGoogleSubscription('purchase-token-1', 7);
    purchase.subscriptionState = 'SUBSCRIPTION_STATE_EXPIRED'; purchase.acknowledgementState = 'ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED';
    await reconcileGoogleSubscription('purchase-token-1');
    await reconcileGoogleSubscription('purchase-token-1', 7);
    expect((await db.unsafe("SELECT source FROM effective_memberships WHERE wca_id='u7'"))[0].source).not.toBe('google');
    await db.unsafe("UPDATE memberships SET expires_at=NULL WHERE wca_id='u7'");
    purchase.subscriptionState = 'SUBSCRIPTION_STATE_ACTIVE';
    await reconcileGoogleSubscription('purchase-token-1');
    expect((await db.unsafe("SELECT expires_at FROM effective_memberships WHERE wca_id='u7'"))[0].expires_at).toBeNull();
  });
  it('persists a pending-to-active replacement even when the old token arrives last', async () => {
    purchase.subscriptionState = 'SUBSCRIPTION_STATE_PENDING'; purchase.linkedPurchaseToken = 'old-token-1';
    await reconcileGoogleSubscription('new-token-1', 7);
    purchase.subscriptionState = 'SUBSCRIPTION_STATE_ACTIVE';
    await reconcileGoogleSubscription('new-token-1', 7);
    purchase.linkedPurchaseToken = undefined; purchase.acknowledgementState = 'ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED';
    await reconcileGoogleSubscription('old-token-1', 7);
    expect((await db.unsafe("SELECT grants_membership FROM google_membership_subscriptions WHERE purchase_token='old-token-1'"))[0].grants_membership).toBe(false);
  });
  it('preserves merged identifiers and tombstones deleted ownership', async () => {
    await reconcileGoogleSubscription('purchase-token-1', 7);
    await db.unsafe('UPDATE google_membership_accounts SET user_id=8 WHERE user_id=7');
    await expect(reconcileGoogleSubscription('purchase-token-1', 7)).rejects.toThrow();
    await reconcileGoogleSubscription('purchase-token-1', 8);
    await db.unsafe('DELETE FROM app_users WHERE id=8');
    await expect(reconcileGoogleSubscription('purchase-token-1', 7)).rejects.toThrow();
    expect((await db.unsafe('SELECT user_id FROM google_membership_accounts'))[0].user_id).toBeNull();
    expect(await db.unsafe("SELECT * FROM effective_memberships WHERE source='google'")).toHaveLength(0);
  });
});
it('authenticates Pub/Sub audience and exact verified service identity', async () => {
  process.env.GOOGLE_IAP_RTDN_AUDIENCE = 'https://api.example.test/rtdn';
  process.env.GOOGLE_IAP_RTDN_SERVICE_ACCOUNT = 'push@example.iam.gserviceaccount.com';
  await expect(verifyGooglePushAuthorization(undefined)).rejects.toThrow();
  mocks.verifyIdToken.mockResolvedValue({ getPayload: () => ({ email: 'other', email_verified: true }) });
  await expect(verifyGooglePushAuthorization('Bearer fixture')).rejects.toThrow();
  mocks.verifyIdToken.mockResolvedValue({ getPayload: () => ({ email: process.env.GOOGLE_IAP_RTDN_SERVICE_ACCOUNT, email_verified: true }) });
  await verifyGooglePushAuthorization('Bearer fixture');
  expect(mocks.verifyIdToken).toHaveBeenLastCalledWith({ idToken: 'fixture', audience: process.env.GOOGLE_IAP_RTDN_AUDIENCE });
});
