import { readFile } from 'node:fs/promises';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { sql } from '../src/db/connection.js';
import { beginIdentityLogin, cleanupIdentityChoices, completeIdentityChoice, type ChoiceProvider } from '../src/utils/identity_choice.js';
import { loginWithIdentity } from '../src/utils/account.js';
import { approveWechatBrowserSession, issueWechatBrowserSession } from '../src/utils/web_session_ticket.js';

// Explicit dedicated database only. CI/local must create this empty test database, never point at production.
const enabled = process.env.IDENTITY_CHOICE_PG_TEST === '1'
  && /^identity_choice_test(?:_\d+)?$/.test(process.env.DB_NAME ?? '') && process.env.DB_HOST === '127.0.0.1';
const credential = { encryptedToken: Buffer.alloc(48, 7), keyVersion: 1 };
async function pending(provider: ChoiceProvider, sub: string) {
  const result = await beginIdentityLogin({ provider, providerUid: sub, profile: { name: '' },
    appleCredential: provider === 'apple' ? credential : undefined });
  if (!('pending' in result)) throw new Error('expected account choice');
  return result;
}
async function count(table: 'app_users' | 'auth_identities' | 'auth_identity_pending') {
  const rows = await sql.unsafe(`SELECT COUNT(*)::int AS count FROM ${table}`);
  return Number(rows[0].count);
}
describe.skipIf(!enabled)('identity choice on real isolated PostgreSQL', () => {
  beforeAll(async () => {
    // Empty dedicated DB prerequisite deliberately fails if reused or pointed at a nonempty schema.
    await sql.unsafe(`CREATE TABLE app_users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      display_name TEXT NOT NULL DEFAULT '', avatar_url TEXT, avatar_source TEXT NOT NULL DEFAULT 'auto',
      avatar_preset TEXT, wca_id TEXT UNIQUE, is_admin BOOLEAN NOT NULL DEFAULT FALSE,
      country_iso2 TEXT, region_code TEXT, city_name TEXT, merged_into_user_id BIGINT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE auth_identities (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
      provider VARCHAR(16) NOT NULL, provider_uid TEXT NOT NULL, verified_at TIMESTAMPTZ,
      UNIQUE(provider, provider_uid)
    );
    CREATE TABLE auth_web_session_tickets (
      ticket_hash CHAR(64) PRIMARY KEY, user_id BIGINT REFERENCES app_users(id),
      purpose VARCHAR(16), code_challenge CHAR(43), expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`);
    await sql.unsafe(await readFile(new URL('../migrations/0231_auth_apple_token.sql', import.meta.url), 'utf8'));
    await sql.unsafe(await readFile(new URL('../migrations/0232_auth_identity_pending.sql', import.meta.url), 'utf8'));
  });
  afterAll(async () => { await sql.end(); });

  it('rejects NULL, unsupported and cross-provider Apple credential metadata at the database boundary', async () => {
    for (const keyVersion of [null, 2]) {
      await expect(sql`INSERT INTO auth_identity_pending(ticket_hash, provider, provider_uid,
        apple_refresh_token_encrypted, apple_token_key_version, expires_at)
        VALUES (${ 'f'.repeat(64) }, 'apple', 'invalid-key', ${credential.encryptedToken}, ${keyVersion}, NOW() + INTERVAL '15 minutes')`)
        .rejects.toMatchObject({ code: '23514' });
    }
    await expect(sql`INSERT INTO auth_identity_pending(ticket_hash, provider, provider_uid,
      apple_refresh_token_encrypted, apple_token_key_version, expires_at)
      VALUES (${ 'e'.repeat(64) }, 'google', 'wrong-provider', ${credential.encryptedToken}, 1, NOW() + INTERVAL '15 minutes')`)
      .rejects.toMatchObject({ code: '23514' });
  });

  it.each(['apple', 'google', 'wechat', 'qq', 'alipay', 'wca'] as const)('%s unknown identity never creates an account/session or exposes identity claims', async (provider) => {
    const before = await count('app_users');
    const result = await pending(provider, 'unknown-' + provider);
    expect(Object.keys(result).sort()).toEqual(['code', 'error', 'pending']);
    expect(result.pending).toEqual({ provider, ticket: expect.stringMatching(/^[A-Za-z0-9_-]{43}$/), expiresInSeconds: 900 });
    expect(await count('app_users')).toBe(before);
    const [row] = await sql`SELECT ticket_hash, profile FROM auth_identity_pending WHERE provider_uid = ${'unknown-' + provider}`;
    expect(row.ticket_hash).not.toBe(result.pending.ticket);
    expect(row.profile).toEqual({ name: '' });
  });

  it('explicit create atomically migrates Apple credential, consumes once, and subsequent login skips the choice', async () => {
    const choice = await pending('apple', 'apple-created');
    const created = await completeIdentityChoice(choice.pending.ticket, 'create');
    expect(created.isNew).toBe(true);
    const [row] = await sql`SELECT user_id, apple_refresh_token_encrypted FROM auth_identities WHERE provider_uid = 'apple-created'`;
    expect(Number(row.user_id)).toBe(created.user.id);
    expect(row.apple_refresh_token_encrypted).toEqual(credential.encryptedToken);
    await expect(completeIdentityChoice(choice.pending.ticket, 'create')).rejects.toThrow('already used');
    const known = await beginIdentityLogin({ provider: 'apple', providerUid: 'apple-created', profile: { name: '' }, appleCredential: credential });
    expect(known).toMatchObject({ user: { id: created.user.id }, isNew: false });
    expect('pending' in known).toBe(false);
  });

  it('two requests for the same ticket produce exactly one successful create', async () => {
    const choice = await pending('google', 'single-use');
    const before = await count('app_users');
    const results = await Promise.allSettled([completeIdentityChoice(choice.pending.ticket, 'create'), completeIdentityChoice(choice.pending.ticket, 'create')]);
    expect(results.map(r => r.status).sort()).toEqual(['fulfilled', 'rejected']);
    expect(await count('app_users')).toBe(before + 1);
  });

  it('two independently verified tickets for one subject converge without an orphan account', async () => {
    const first = await pending('apple', 'same-subject');
    const second = await pending('apple', 'same-subject');
    const before = await count('app_users');
    const results = await Promise.all([completeIdentityChoice(first.pending.ticket, 'create'), completeIdentityChoice(second.pending.ticket, 'create')]);
    expect(results[0].user.id).toBe(results[1].user.id);
    expect(results.map(r => r.isNew).sort()).toEqual([false, true]);
    expect(await count('app_users')).toBe(before + 1);
  });

  it('mixed create/link for one ticket has one winner without inverse-lock deadlock', async () => {
    const target = await loginWithIdentity('email', 'mixed-target@test.invalid', { name: '' });
    const choice = await pending('apple', 'mixed-actions');
    const before = await count('app_users');
    const [create, link] = await Promise.allSettled([
      completeIdentityChoice(choice.pending.ticket, 'create'),
      completeIdentityChoice(choice.pending.ticket, 'link', target.user.id),
    ]);
    expect([create.status, link.status].sort()).toEqual(['fulfilled', 'rejected']);
    expect(await count('app_users')).toBe(before + (create.status === 'fulfilled' ? 1 : 0));
    const rows = await sql`SELECT user_id FROM auth_identities WHERE provider_uid = 'mixed-actions'`;
    expect(rows).toHaveLength(1);
  });

  it('email and phone existing-only verification cannot create unknown identities', async () => {
    const before = await count('app_users');
    for (const provider of ['email', 'phone'] as const) {
      await expect(loginWithIdentity(provider, 'unknown-' + provider, { name: '' }, undefined,
        { createIfMissing: false })).rejects.toThrow('account not found');
    }
    expect(await count('app_users')).toBe(before);
  });

  it('delete-before-link rejects the vanished account and keeps the ticket retryable', async () => {
    const target = await loginWithIdentity('email', 'deleted-target@test.invalid', { name: '' });
    const choice = await pending('google', 'deleted-target');
    await sql`DELETE FROM app_users WHERE id = ${target.user.id}`;
    await expect(completeIdentityChoice(choice.pending.ticket, 'link', target.user.id)).rejects.toThrow('account changed');
    expect((await completeIdentityChoice(choice.pending.ticket, 'create')).isNew).toBe(true);
  });

  it('link targets only the confirmed account and conflicts roll back without consuming the ticket', async () => {
    const target = await loginWithIdentity('email', 'target@test.invalid', { name: '' });
    const other = await loginWithIdentity('email', 'other@test.invalid', { name: '' });
    const first = await pending('apple', 'link-subject');
    const competing = await pending('apple', 'link-subject');
    expect(await completeIdentityChoice(first.pending.ticket, 'link', target.user.id)).toMatchObject({ user: { id: target.user.id }, isNew: false });
    await expect(completeIdentityChoice(competing.pending.ticket, 'link', other.user.id)).rejects.toThrow('another account');
    expect(await completeIdentityChoice(competing.pending.ticket, 'link', target.user.id)).toMatchObject({ user: { id: target.user.id }, isNew: false });
  });

  it('storage failure rolls back account/identity and retains pending credential for retry', async () => {
    const choice = await pending('apple', 'fail-storage');
    const before = await count('app_users');
    await sql.unsafe(`CREATE FUNCTION test_identity_failure() RETURNS trigger LANGUAGE plpgsql AS $$
      BEGIN IF NEW.provider_uid = 'fail-storage' THEN RAISE EXCEPTION 'fixture storage failure'; END IF; RETURN NEW; END $$;
      CREATE TRIGGER test_identity_failure BEFORE INSERT ON auth_identities FOR EACH ROW EXECUTE FUNCTION test_identity_failure();`);
    await expect(completeIdentityChoice(choice.pending.ticket, 'create')).rejects.toThrow('account creation failed');
    expect(await count('app_users')).toBe(before);
    const [row] = await sql`SELECT apple_refresh_token_encrypted FROM auth_identity_pending WHERE provider_uid = 'fail-storage'`;
    expect(row.apple_refresh_token_encrypted).toEqual(credential.encryptedToken);
    await sql.unsafe('ALTER TABLE auth_identities DISABLE TRIGGER test_identity_failure');
    expect((await completeIdentityChoice(choice.pending.ticket, 'create')).isNew).toBe(true);
  });

  it('merge-before-link rejects the old target without consuming or silently retargeting', async () => {
    const target = await loginWithIdentity('email', 'merge-target@test.invalid', { name: '' });
    const canonical = await loginWithIdentity('email', 'canonical@test.invalid', { name: '' });
    const choice = await pending('google', 'merged-target');
    await sql`UPDATE app_users SET merged_into_user_id = ${canonical.user.id} WHERE id = ${target.user.id}`;
    await expect(completeIdentityChoice(choice.pending.ticket, 'link', target.user.id)).rejects.toThrow('account changed');
    expect((await completeIdentityChoice(choice.pending.ticket, 'link', canonical.user.id)).user.id).toBe(canonical.user.id);
  });

  it('expiry blocks use and erases abandoned credentials without revoking an existing identity grant', async () => {
    const choice = await pending('apple', 'abandoned');
    await sql`UPDATE auth_identity_pending SET expires_at = NOW() - INTERVAL '1 second' WHERE provider_uid = 'abandoned'`;
    await expect(completeIdentityChoice(choice.pending.ticket, 'create')).rejects.toThrow('expired');
    await cleanupIdentityChoices();
    const rows = await sql`SELECT 1 FROM auth_identity_pending WHERE provider_uid = 'abandoned'`;
    expect(rows).toHaveLength(0);
    const [active] = await sql`SELECT apple_refresh_token_encrypted FROM auth_identities WHERE provider_uid = 'apple-created'`;
    expect(active.apple_refresh_token_encrypted).toEqual(credential.encryptedToken);
  });

  it('existing-only WeChat browser approval rejects a newly created account but accepts a pre-existing account', async () => {
    const old = await loginWithIdentity('email', 'wechat-old@test.invalid', { name: '' });
    const choice = await issueWechatBrowserSession(true);
    const fresh = await loginWithIdentity('email', 'wechat-fresh@test.invalid', { name: '' });
    expect(await approveWechatBrowserSession(choice.approval, fresh.user.id)).toBe(false);
    expect(await approveWechatBrowserSession(choice.approval, old.user.id)).toBe(true);
  });
});
