// Auto-generated. Reflects landing-card fields only; full detail in stack_tools/<slug>.tsx (lazy).
// Regen: node /tmp/extract_stack_meta.mjs (or just hand-edit when adding a tool).

export interface StackToolMeta {
  slug: string;
  name: string;
  version: string;
  since: string;
  group: 'frontend' | 'backend' | 'edge' | 'dev';
  accent: string;
  bright: string;
  glyph: string;
  zh: { tagline: string; role: string };
  en: { tagline: string; role: string };
}

export const STACK_TOOLS_META: StackToolMeta[] = [
  { slug: 'react', name: "React", version: '19.2', since: '2013-05', group: 'frontend', accent: '#61DAFB', bright: '#9FE9FE', glyph: "⚛",
    zh: { tagline: "声明式 UI + 组件 + 虚拟 DOM", role: "渲染整个 SPA。24 个工具页全部跑在它的组件树上。" },
    en: { tagline: "Declarative UI, components, virtual DOM", role: "Renders the whole SPA — 24 tool pages all live inside one React tree." } },
  { slug: 'react-router', name: "React Router", version: '7.x', since: '2014-05', group: 'frontend', accent: '#F44250', bright: '#FF7080', glyph: "⇄",
    zh: { tagline: "把 URL 跟组件树绑在一起", role: "24+ 工具页全部靠它路由, 每个页 lazy() 切独立 chunk, <Suspense> 兜底加载态, react-router-dom 7 跟 React 19 配合 concurrent renderer。" },
    en: { tagline: "Binds URLs to your component tree", role: "Routes all 24+ tool pages. Each page is lazy()-split into its own chunk with <Suspense> covering the load; react-router-dom 7 pairs with React 19 concurrent renderer." } },
  { slug: 'next-js', name: "Next.js", version: '16.2.6', since: '2016-10', group: 'frontend', accent: '#0070F3', bright: '#3B9EFF', glyph: "▲",
    zh: { tagline: "React 之上的全栈框架", role: "本站现在整个跑在它上面。Phase 4 (2026-05) 把 SPA 切成 Next 16 App Router, ~128 个页面 SSG。" },
    en: { tagline: "The full-stack framework on top of React", role: "The whole site now runs on it. Phase 4 (2026-05) cut the SPA over to Next 16 App Router, ~128 pages prerendered." } },
  { slug: 'vite', name: "Vite", version: '8.0', since: '2020-04', group: 'frontend', accent: '#646CFF', bright: '#8A8FFF', glyph: "⚡",
    zh: { tagline: "原生 ESM dev server + Rolldown 生产打包", role: "本站前端的开发服务器 + 生产打包器。dev 起 1s 内, build 出 80 个 hashed chunks。" },
    en: { tagline: "Native ESM dev server + Rolldown production build", role: "Dev server + production bundler for the SPA. Cold start under 1s; build emits ~80 hashed chunks." } },
  { slug: 'three', name: "Three.js", version: 'r184', since: '2010-04', group: 'frontend', accent: '#049EF4', bright: '#5BC3F9', glyph: "△",
    zh: { tagline: "浏览器里写 3D 的事实标准", role: "本站所有 3D 魔方渲染的底层。TwistyPlayer / sq1 demo 都跑在 three.js 上。" },
    en: { tagline: "The de facto standard for 3D in the browser", role: "The renderer behind every 3D cube on this site — TwistyPlayer and the sq1 demo both ride three.js." } },
  { slug: 'cubing-js', name: "cubing.js", version: '0.63.3', since: '2018-09', group: 'frontend', accent: '#F7B500', bright: '#FFD45A', glyph: "▣",
    zh: { tagline: "WCA 级打乱 + 3D 动画 + 公式解析", role: "17 个 WCA 项目的随机态打乱、所有公式播放器的 3D 动画、KPuzzle 状态推导全部走它。" },
    en: { tagline: "WCA-grade scrambles + 3D twisty + alg parsing", role: "Random-state scrambles for all 17 WCA events, 3D animation for every player, and KPuzzle state derivation all live here." } },
  { slug: 'webcodecs', name: "WebCodecs Stack", version: 'CR 2023-02', since: '2020-11', group: 'frontend', accent: '#FB7185', bright: '#FDA4AF', glyph: "⏵",
    zh: { tagline: "浏览器里硬件解码 + 重编码 + 零丢帧导出", role: "`/frame-count` 工具的核心管线。视频文件 → mp4box.js 解析 → WebCodecs 硬件解码出 VideoFrame → OffscreenCanvas crop → VideoEncoder 硬件重编码 → mp4-muxer 写回 .mp4。VFR / 奇怪 codec 走 ffmpeg.wasm 兜底。" },
    en: { tagline: "Hardware-accelerated decode + re-encode + zero-drop export in the browser", role: "The core pipeline behind /frame-count. Video file → mp4box.js demux → WebCodecs hardware decode into VideoFrame → OffscreenCanvas crop → VideoEncoder hardware re-encode → mp4-muxer writes back to .mp4. VFR / exotic codecs fall back to ffmpeg.wasm." } },
  { slug: 'tailwind', name: "Tailwind CSS", version: '4.3', since: '2017-11', group: 'frontend', accent: '#38BDF8', bright: '#7DD3FC', glyph: "≈",
    zh: { tagline: "Utility-first 的 CSS 框架", role: "装在 cuberoot.me 上,主要作 preflight 基础层 + 偶尔 utility 兜底。" },
    en: { tagline: "Utility-first CSS framework", role: "Installed on cuberoot.me, but mostly used as the preflight base layer with utility classes as an escape hatch." } },
  { slug: 'i18next', name: "i18next", version: '24.x + 15.x', since: '2011-08', group: 'frontend', accent: '#26C6DA', bright: '#7FE4EE', glyph: "⊕",
    zh: { tagline: "JavaScript 世界的国际化事实标准", role: "整站中英双语主框架。两种 pattern 并存:大段文案走 t(\\" },
    en: { tagline: "The de-facto i18n stack of JavaScript", role: "The whole site\\" } },
  { slug: 'zustand', name: "Zustand", version: '5.0.x', since: '2019-09', group: 'frontend', accent: '#B57655', bright: '#E4A977', glyph: "ʕ",
    zh: { tagline: "简到极致的 React 状态管理", role: "客户端跨页持久状态:auth / settings / sessions / trainer / battle / calc / mosaic / viz / recon 共 11 个 store。" },
    en: { tagline: "Bear-minimum React state management", role: "Client-side cross-page state — 11 stores: auth / settings / sessions / trainer / battle / calc / mosaic / viz / recon." } },
  { slug: 'react-native', name: "React Native", version: '0.85.3', since: '2015-03', group: 'frontend', accent: '#149ECA', bright: '#5BC8EE', glyph: "◫",
    zh: { tagline: "用 React 写真原生 App", role: "本站没用它 —— 移动端走 Capacitor 套壳。这页讲它是什么、为什么这套 web-first 工具链选了另一条路。" },
    en: { tagline: "Real native apps, written in React", role: "The site doesn't use it — mobile goes through a Capacitor shell. This page covers what it is and why this web-first toolchain took a different road." } },
  { slug: 'hono', name: "Hono", version: '4.12', since: '2022-01', group: 'backend', accent: '#FF5C00', bright: '#FF9858', glyph: "炎",
    zh: { tagline: "TS-first 多运行时 web 框架", role: "本站后端 API 的整个壳。Hono 4 + Node 22 + pm2, 22 个端点跑在 127.0.0.1:3001。" },
    en: { tagline: "TS-first multi-runtime web framework", role: "The whole backend API shell on this site. Hono 4 + Node 22 + pm2, 22 endpoints on 127.0.0.1:3001." } },
  { slug: 'node', name: "Node.js", version: '22 LTS', since: '2009-05', group: 'backend', accent: '#5FA04E', bright: '#8BC97B', glyph: "⬢",
    zh: { tagline: "JavaScript 服务端运行时", role: "后端 API、构建工具、测试 runner、脚本全部跑在它上面。" },
    en: { tagline: "JavaScript runtime for the server", role: "Where the backend API, build tools, test runner, and scripts all run." } },
  { slug: 'pm2', name: "PM2", version: '7.0', since: '2013-06', group: 'backend', accent: '#2B96EC', bright: '#6FB9F2', glyph: "P2",
    zh: { tagline: "Node 进程守护 + 集群 + 日志", role: "把 Hono API 拉起来、崩了拉回去、reboot 后自动恢复, 全靠它一个 CLI。" },
    en: { tagline: "Node process manager, cluster, and logs", role: "Starts the Hono API, restarts it on crash, and brings it back after reboot — one CLI." } },
  { slug: 'postgresql', name: "PostgreSQL", version: '13', since: '1986', group: 'backend', accent: '#336791', bright: '#4F8BC2', glyph: "Pg",
    zh: { tagline: "对象关系型 + 文档 + 数组 一锅端", role: "主库。recon 缓存 / 41 套 alg 公式 / 训练数据 / WCA 衍生统计全部落 PG 13。" },
    en: { tagline: "Object-relational + document + array, one engine", role: "Primary store. Recon caches, the 41-set alg library, training data, and WCA stats derivatives all live in PG 13." } },
  { slug: 'pg-dump', name: "pg_dump", version: 'nightly', since: '1996', group: 'backend', accent: '#4F7FAF', bright: '#6F9FCF', glyph: "↧",
    zh: { tagline: "PostgreSQL 官方逻辑备份工具", role: "夜间备份。03:00 UTC systemd timer 跑 -Fc 自定义格式, 滚动 30 天保留。" },
    en: { tagline: "PostgreSQL\\", role: "Nightly backups. A 03:00 UTC systemd timer runs pg_dump -Fc into custom format on a 30-day rolling window." } },
  { slug: 'mysql', name: "MySQL", version: '9.7.0 LTS', since: '1995-05', group: 'backend', accent: '#4479A1', bright: '#7BA5C9', glyph: "≣",
    zh: { tagline: "世界上最普及的开源关系型数据库", role: "本地解析 WCA 公开 dump。stats-build 管道读它产 JSON, 不进 prod。" },
    en: { tagline: "The world’s most ubiquitous open-source relational database", role: "Local parser for the WCA public dump. stats-build reads it, ships JSON — never touches prod." } },
  { slug: 'docker', name: "Docker", version: '29.4', since: '2013-03', group: 'backend', accent: '#2496ED', bright: '#5EB6F4', glyph: "⊞",
    zh: { tagline: "应用打包成镜像, 一行命令到处跑", role: "本地起 PG13 容器,在推生产前把 schema / migrations / load.sql 全部跑一遍。" },
    en: { tagline: "Package apps as images and run them anywhere", role: "Run a local PG13 container to dry-run schema / migrations / load.sql before pushing to prod." } },
  { slug: 'systemd', name: "systemd", version: '260', since: '2010-03', group: 'backend', accent: '#30D475', bright: '#5EE89C', glyph: "⌬",
    zh: { tagline: "PID 1 + 服务管理 + 日志 + 定时器", role: "云服务器上跑 cuberoot.me 整套后端: nginx、pm2、pg-dump 备份、acme.sh 续证全是 systemd unit。" },
    en: { tagline: "PID 1 + service manager + journal + timers", role: "Runs the whole cuberoot.me VM — nginx, pm2, the pg-dump backup, and acme.sh renewals are all systemd units." } },
  { slug: 'nginx', name: "nginx", version: 'mainline 1.31', since: '2004-10', group: 'edge', accent: '#009639', bright: '#4FB572', glyph: "n",
    zh: { tagline: "事件驱动 web 服务器 + 反向代理", role: "所有流量的第一跳。SPA / API / WASM COI / blog 静态归档全靠这一个进程分发。" },
    en: { tagline: "Event-driven web server + reverse proxy", role: "First hop for every request. SPA / API / WASM COI / blog archive all dispatched by one process." } },
  { slug: 'cloudflare-dns', name: "Cloudflare DNS", version: 'authoritative', since: '2009-09', group: 'edge', accent: '#F38020', bright: '#F8A85B', glyph: "CF",
    zh: { tagline: "权威 DNS + 全球 anycast 网络", role: "托管整个 cuberoot.me zone, 仅做权威 DNS, 不走 proxy。每条记录灰云。" },
    en: { tagline: "Authoritative DNS + global anycast network", role: "Hosts the entire cuberoot.me zone. Authoritative only, grey-cloud on every record." } },
  { slug: 'lets-encrypt', name: "Let’s Encrypt", version: 'ACME v2', since: '2015-12', group: 'edge', accent: '#3777BE', bright: '#5FA0D9', glyph: "LE",
    zh: { tagline: "免费 + 全自动 + 全世界默认信任的 CA", role: "签 cuberoot.me / api.cuberoot.me / blog.cuberoot.me 三本证书,acme.sh + DNS-01 + systemd timer 全自动续。" },
    en: { tagline: "Free, automated, universally trusted CA", role: "Signs the three certs (cuberoot.me / api.cuberoot.me / blog.cuberoot.me) used across this site; acme.sh + DNS-01 + a systemd timer renews them with zero hand-holding." } },
  { slug: 'git', name: "Git", version: '2.54', since: '2005-04', group: 'dev', accent: '#F05032', bright: '#F58366', glyph: "⎇",
    zh: { tagline: "分布式版本控制 + 内容寻址存储", role: "本仓库的唯一真相源。每个 commit、每条 branch、每个 deploy 触发都从它出发。" },
    en: { tagline: "Distributed version control + content-addressable storage", role: "The single source of truth for this repo. Every commit, every branch, every deploy trigger starts here." } },
  { slug: 'pnpm', name: "pnpm", version: '11.1.2', since: '2017-01', group: 'dev', accent: '#F69220', bright: '#FBB048', glyph: "⬢",
    zh: { tagline: "硬链接 + 内容寻址的 npm 替代品", role: "cuberoot.me monorepo 的包管理器, 把 10 个 workspace 串成一棵共享树。" },
    en: { tagline: "A drop-in npm replacement, with a content-addressable store and hard links", role: "Package manager for the cuberoot.me monorepo — stitches 10 workspaces into a shared tree." } },
  { slug: 'turbo', name: "Turborepo", version: '2.5', since: '2020-11', group: 'dev', accent: '#FF1E56', bright: '#FF638F', glyph: "⟫",
    zh: { tagline: "增量任务编排 + 内容寻址缓存", role: "把 monorepo 里 build / typecheck / test / lint 串成依赖图, 没改的包直接从缓存吐结果。" },
    en: { tagline: "Incremental task orchestration + content-addressed cache", role: "Threads build / typecheck / test / lint across the monorepo into a dependency graph, replaying cached outputs for unchanged packages." } },
  { slug: 'monorepo', name: "Monorepo", version: 'pnpm 10 + Turbo 2', since: '~2003', group: 'dev', accent: '#0D9488', bright: '#14B8A6', glyph: "⌑",
    zh: { tagline: "一个仓库,多个包,一份 lockfile", role: "4 个核心 workspace (client / server / shared / stats-build), 一份 pnpm-lock, Turbo cache, 一个 CI workflow。" },
    en: { tagline: "One repo, many packages, one lockfile", role: "Four core workspaces (client / server / shared / stats-build), one pnpm-lock, Turbo cache, one CI workflow." } },
  { slug: 'npm', name: "npm", version: '11.14', since: '2010-01', group: 'dev', accent: '#CB3837', bright: '#E55B5A', glyph: "❒",
    zh: { tagline: "全球最大的代码仓库 + JavaScript 的事实标准包格式", role: "我们用 pnpm CLI, 但每个依赖最终都从 registry.npmjs.org 拉。package.json 是源头, semver / lockfile 协议把整个生态串起来。" },
    en: { tagline: "The world's largest software registry — and the de-facto JS package format", role: "We type `pnpm install`, but every dependency still comes from registry.npmjs.org. package.json is the source; semver / lockfile is the glue." } },
  { slug: 'bun', name: "Bun", version: '1.2', since: '2022-07', group: 'dev', accent: '#E78E5C', bright: '#F2B68F', glyph: "◓",
    zh: { tagline: "Node + npm + Vite + Vitest 一个二进制全干完", role: "未在用。如果哪天换, 最先动的两块: api.cuberoot.me 的 Hono server (Bun 跑 Hono 比 Node 快) + core/scripts/ 的一次性 TS 脚本 (bun run 比 tsx 快 2-3 倍)。当前 pm2 + Node 22 没在卡, 不动它。" },
    en: { tagline: "Node + npm + Vite + Vitest, all in one binary", role: "Not in use. If we ever switch, the two first targets are api.cuberoot.me (Hono on Bun beats Node) and the one-off TS scripts under core/scripts/ (bun run is 2-3x faster cold start than tsx). The current pm2 + Node 22 setup is fine, so it stays." } },
  { slug: 'uv', name: "uv", version: '0.11.14', since: '2024-02', group: 'dev', accent: '#DE5FE9', bright: '#EA8AF3', glyph: "✦",
    zh: { tagline: "pip + virtualenv + pipx + pyenv 一个 Rust 二进制全替了", role: "管理 Python 工具链 + 依赖 + venv。本站脚本以后会迁过去, 现在还是 plain python3。" },
    en: { tagline: "pip + virtualenv + pipx + pyenv, replaced by one Rust binary", role: "Python toolchain + deps + venvs in one binary. The site’s scripts are still on plain python3 — uv is the migration plan." } },
  { slug: 'github-actions', name: "GitHub Actions", version: 'ubuntu-24.04', since: '2018-10', group: 'dev', accent: '#2088FF', bright: '#6FB8FF', glyph: "▶",
    zh: { tagline: "YAML 驱动的 CI/CD + 通用编排", role: "本仓库 9 条 workflow 的执行引擎。每个 PR 跑测试,每次 push main 触发 build 和 deploy。" },
    en: { tagline: "YAML-driven CI/CD + general-purpose orchestration", role: "The execution engine behind this repo\\" } },
  { slug: 'playwright', name: "Playwright", version: '1.60', since: '2020-01', group: 'dev', accent: '#2EAD33', bright: '#52CB58', glyph: "▶",
    zh: { tagline: "跨浏览器端到端测试 + 浏览器自动化", role: "本站 UI 回归测试 + AI agent 验证页面行为的主力工具。" },
    en: { tagline: "Cross-browser E2E testing + browser automation", role: "UI regression suites + the browser backend AI agents drive to verify pages on this site." } },
  { slug: 'vitest', name: "Vitest", version: '4.1', since: '2021-12', group: 'dev', accent: '#6E9F18', bright: '#8DC73A', glyph: "✓",
    zh: { tagline: "Vite 原生的下一代测试框架", role: "跑 unit / worker / 回归测试。utils 纯函数、worker 算法、analyzer baseline 全部交给它。" },
    en: { tagline: "Next-gen test runner powered by Vite", role: "Runs unit / worker / regression tests — utils pure functions, worker algorithms, analyzer baselines all live here." } },
  { slug: 'eslint', name: "ESLint", version: '10.4.0', since: '2013-06', group: 'dev', accent: '#4B32C3', bright: '#8B6FE8', glyph: "⬣",
    zh: { tagline: "可插拔的 JavaScript 静态检查器", role: "本站 client-next 的代码检查。一条 flat config 规则: 强制 playwright 脚本走 headless.mjs 包装, 不直接 import 浏览器引擎。" },
    en: { tagline: "The pluggable JavaScript linter", role: "Code-checks the site's client-next. One flat-config rule: force playwright scripts through the headless.mjs wrapper instead of importing a browser engine directly." } },
  { slug: 'tailscale', name: "Tailscale", version: '1.96.5', since: '2019-04', group: 'dev', accent: '#5F5FFF', bright: '#8A8AFF', glyph: "◇",
    zh: { tagline: "基于 WireGuard 的 mesh VPN", role: "把开发机、手机、笔记本拉进同一张私有网络, dev server 不用开公网也能跨设备访问。" },
    en: { tagline: "WireGuard-based mesh VPN", role: "Pulls dev machine, phone, laptop onto one private network — dev servers reachable across devices without ever opening a public port." } },
  { slug: 'openssh', name: "OpenSSH", version: '10.3p1', since: '1999-12', group: 'dev', accent: '#5A6E7F', bright: '#7A8E9F', glyph: "⌬",
    zh: { tagline: "一个协议跑遍全互联网的加密远程登录套件", role: "所有服务器登录 / 部署 / Git push 的底层通道。cuberoot.me 每次 CI 部署都走它。" },
    en: { tagline: "The encrypted remote-login suite that runs the public internet", role: "The transport beneath every server login, deploy, and git push. Every CI deploy on cuberoot.me rides it." } },
  { slug: 'rsync', name: "rsync", version: '3.4.2', since: '1996-06', group: 'dev', accent: '#8B5CF6', bright: '#A88AFA', glyph: "⇆",
    zh: { tagline: "只发改动的那几个字节", role: "把构建产物 / 备份 / 镜像在两台机器之间同步, 只传差异。" },
    en: { tagline: "Ship only the bytes that changed", role: "Syncs build artifacts / backups / mirrors between two machines — only the delta crosses the wire." } },
  { slug: 'obsidian', name: "Obsidian", version: '1.7', since: '2020-03', group: 'dev', accent: '#7C3AED', bright: '#A78BFA', glyph: "◇",
    zh: { tagline: "本地优先的 Markdown 思考工具", role: "计划中 — 个人知识管理 + AI-era 上下文仓库。当前 cuberoot.me 代码库不依赖, 但下一年准备把笔记 / 设计决策 / 调研记录都搬进来, 跟 Claude Code 形成闭环。" },
    en: { tagline: "Local-first markdown thinking tool", role: "Planned tooling — personal knowledge base + AI-era context store. The cuberoot.me codebase does not depend on it yet, but the next year of work plans to move notes / design decisions / research into a vault and close the loop with Claude Code." } },
  { slug: 'github', name: "GitHub", version: '3.20', since: '2008-04', group: 'dev', accent: '#0969DA', bright: '#4A9BF0', glyph: "◔",
    zh: { tagline: "git 之上的社交化 forge + 第一方 CI / AI 协作平台", role: "本仓库 RuiminYan/cuberoot.me 的托管处, 也是 deploy / mirror / stats / 健康检查 workflow 的执行环境。" },
    en: { tagline: "A social forge on top of git, with first-party CI and AI collaboration", role: "Hosts this repo, RuiminYan/cuberoot.me, and executes the deploy / mirror / stats / healthcheck workflows." } },
  { slug: 'curl', name: "curl", version: '8.20.0', since: '1996-11', group: 'dev', accent: '#073551', bright: '#3F6E96', glyph: "⇄",
    zh: { tagline: "一个人维护 30 年, 跑在 200 亿台设备里的 HTTP 客户端", role: "本仓库调试 API 的默认方式。开 nginx vhost, ping endpoint, 看 cert 过期, 跑 GitHub Actions 健康检查, 全是它。" },
    en: { tagline: "Thirty years, one maintainer, twenty billion installations", role: "The default way to poke this repo. Opening an nginx vhost, pinging an endpoint, checking a cert, running a GitHub Actions health probe — all curl." } },
  { slug: 'windows', name: "Windows", version: '11 25H2', since: '1985-11', group: 'dev', accent: '#0078D4', bright: '#4CA0E0', glyph: "▦",
    zh: { tagline: "桌面操作系统 + NT 内核 + Win32 生态", role: "本仓库的主开发机就是它。每一行代码在 Windows 11 Pro 上写, pwsh 做 shell, 127.0.0.1:3000 跑 dev。" },
    en: { tagline: "Desktop operating system + NT kernel + Win32 ecosystem", role: "This repo's main dev machine. Every line is written on Windows 11 Pro — pwsh as the shell, dev on 127.0.0.1:3000." } },
  { slug: 'wsl2', name: "WSL2", version: '2.7.3', since: '2016-08', group: 'dev', accent: '#16A085', bright: '#22C3A0', glyph: "⧈",
    zh: { tagline: "Windows 里跑一个真 Linux 内核", role: "不在主开发流程里 (本仓库走 Windows 原生 pwsh), 但 Docker Desktop 的引擎默认跑在 WSL2 的轻量 VM 里 —— 本地那个 PG13 容器其实就坐在 WSL2 的 Linux 内核上。" },
    en: { tagline: "A real Linux kernel running inside Windows", role: "Not in the main dev flow (this repo is Windows-native pwsh), but Docker Desktop's engine runs inside the WSL2 lightweight VM by default — the local PG13 container actually sits on the WSL2 Linux kernel." } },
  { slug: 'mac-mini', name: "Mac mini", version: 'M4 / M4 Pro', since: '2005-01', group: 'dev', accent: '#86868B', bright: '#B0B3B5', glyph: "⌘",
    zh: { tagline: "一块 SoC + 统一内存的小型台式机", role: "本站规划中的 macOS 端点。iOS / Capacitor 构建和 WebKit 真引擎测试只能在 macOS 上跑, 这台是预留的拼图, 还没到位。" },
    en: { tagline: "A tiny desktop built on one SoC + unified memory", role: "The planned macOS endpoint for this site. iOS / Capacitor builds and real WebKit testing can only run on macOS — the reserved missing piece, not yet acquired." } },
  { slug: 'zed', name: "Zed", version: '1.4', since: '2023-03', group: 'dev', accent: '#0EA5E9', bright: '#3DBEF5', glyph: "Z",
    zh: { tagline: "Rust 写的 GPU 加速代码编辑器", role: "cuberoot.me 的图形编辑器:代码阅读 / 跳转 / 手改 / diff review。Claude Code 写绝大部分代码, Zed 当眼睛和方向盘, 它自带的 AI agent 面板 + ACP 还能直接跟 agent 协作。" },
    en: { tagline: "A GPU-accelerated code editor written in Rust", role: "cuberoot.me's GUI editor: reading code, navigation, hand-edits, diff review. Claude Code writes nearly all the code; Zed is the eyes and the steering wheel — and its built-in AI agent panel + ACP can collaborate with agents directly." } },
  { slug: 'maplibre-gl', name: "MapLibre GL", version: '5.24', since: '2020-12', group: 'frontend', accent: '#285DAA', bright: '#4F86C6', glyph: "◍",
    zh: { tagline: "浏览器里渲染矢量地图的开源 WebGL 引擎", role: "本站 /wca/comp?view=globe 比赛地球的渲染层。把 WCA 比赛按经纬度铺在一颗矢量地球上。" },
    en: { tagline: "Open-source WebGL engine for vector maps in the browser", role: "The render layer behind the /wca/comp?view=globe competition globe — WCA comps plotted by lat/lng on a vector earth." } },
  { slug: 'turbopack', name: "Turbopack", version: 'Next 16', since: '2022-10', group: 'frontend', accent: '#0096FF', bright: '#38B2FF', glyph: "≫",
    zh: { tagline: "Rust 写的增量打包器, Next.js 默认内核", role: "本站 dev 的打包器与 HMR 引擎。Next 16 起 next dev / next build 默认走它, 取代 webpack。" },
    en: { tagline: "Rust incremental bundler, the default Next.js core", role: "The dev bundler and HMR engine for this site. Since Next 16 it is the default for next dev / next build, replacing webpack." } },
  { slug: 'capacitor', name: "Capacitor", version: '8.3.4', since: '2019-05', group: 'frontend', accent: '#119EFF', bright: '#5BBAFF', glyph: "‖",
    zh: { tagline: "把 Web 应用套成 iOS / Android 原生壳", role: "本站移动端就是它 —— 同一份 Next.js 站点塞进系统 WebView, 双 runner CI 出 APK + IPA。" },
    en: { tagline: "Wrap a web app into an iOS / Android native shell", role: "The site's mobile build is this — the same Next.js site dropped into a system WebView, dual-runner CI producing APK + IPA." } },
  { slug: 'nuqs', name: "nuqs", version: '2.8.9', since: '2020-05', group: 'frontend', accent: '#F59E0B', bright: '#FBBF24', glyph: "?=",
    zh: { tagline: "像 useState, 但状态存在 URL query 里", role: "全站页内状态(tab / 筛选 / 排序 / 搜索 / 浮层)进 URL 的唯一方式。33 个页面在用, CI 强制禁裸 history.pushState。" },
    en: { tagline: "Like useState, but stored in the URL query string", role: "The single way page-level state (tabs / filters / sort / search / overlays) goes into the URL site-wide — 33 pages use it, CI forbids raw history.pushState." } },
];
