'use client';

import { sessionFetch } from '@/lib/session-fetch';
import { useEffect, useState } from 'react';
import { PlatformReferenceField } from './PlatformReferenceField';
import BoolToggle from '@/components/BoolToggle';
import { useT } from '@/hooks/useT';
import { apiUrl } from '@/lib/api-base';
import { authHeaders, handleApi } from '@/lib/admin-api';
import { platformLocalDateTime, platformMajorToMinor, platformMinorToMajor } from '@/lib/platform-commerce-fields';
import { commerceRecord, commerceText } from './PlatformCommerceContent';
import './platform-commerce.css';

type Entry=Record<string,unknown>;
type Column={key:string;zh:string;en:string;kind?:'number'|'money'|'lines'|'textarea'|'datetime-local'|'url'|'boolean';required?:boolean;signed?:boolean};
const variantFields:Column[]=[{key:'sku',zh:'规格编号',en:'SKU',required:true},{key:'titleZh',zh:'中文名称',en:'Chinese name',required:true},{key:'titleEn',zh:'英文名称',en:'English name'},{key:'amountMinor',zh:'价格（元）',en:'Price (major units)',kind:'money',required:true},{key:'memberAmountMinor',zh:'会员价（元，可空）',en:'Member price (optional)',kind:'money'},{key:'currency',zh:'币种',en:'Currency',required:true},{key:'inventoryOnHand',zh:'库存总数',en:'Inventory on hand',kind:'number',required:true},{key:'weightGrams',zh:'重量（克）',en:'Weight (grams)',kind:'number'}];
const ticketFields:Column[]=[{key:'code',zh:'票种编号',en:'Ticket code',required:true},{key:'titleZh',zh:'中文名称',en:'Chinese name',required:true},{key:'titleEn',zh:'英文名称',en:'English name'},{key:'amountMinor',zh:'票价（元）',en:'Price (major units)',kind:'money',required:true},{key:'currency',zh:'币种',en:'Currency',required:true},{key:'capacity',zh:'名额',en:'Capacity',kind:'number',required:true},{key:'salesStartAt',zh:'开售时间（本地时间）',en:'Sales open (local time)',kind:'datetime-local'},{key:'salesEndAt',zh:'截止时间（本地时间）',en:'Sales close (local time)',kind:'datetime-local'}];
const venueFields:Column[]=[{key:'name',zh:'场地名称',en:'Venue name'},{key:'city',zh:'城市',en:'City'},{key:'address',zh:'地址',en:'Address'},{key:'url',zh:'场地网址',en:'Venue URL',kind:'url'}];
const productPresentation:Column[]=[{key:'brand',zh:'品牌',en:'Brand'},{key:'imageUrl',zh:'商品图片网址',en:'Product image URL',kind:'url'},{key:'originalAmountMinor',zh:'原价（元，可空）',en:'Original price (optional)',kind:'money'},{key:'featuresZh',zh:'中文特性（每行一项）',en:'Chinese features (one per line)',kind:'lines'},{key:'featuresEn',zh:'英文特性（每行一项）',en:'English features (one per line)',kind:'lines'}];
const coursePresentation:Column[]=[{key:'level',zh:'适合水平',en:'Level'},{key:'format',zh:'课程形式',en:'Format'},{key:'tags',zh:'标签（每行一项）',en:'Tags (one per line)',kind:'lines'},{key:'highlights',zh:'课程亮点（每行一项）',en:'Highlights (one per line)',kind:'lines'},{key:'coverUrl',zh:'封面网址',en:'Cover URL',kind:'url'},{key:'previewUrl',zh:'试听网址',en:'Preview URL',kind:'url'},{key:'nextLiveAt',zh:'下次直播',en:'Next live session',kind:'datetime-local'}];

function Scalar({column,value,onChange}:{column:Column;value:unknown;onChange:(value:unknown)=>void}) {
  const t=useT();const label=t(column.zh,column.en);
  const external=column.kind==='money'?platformMinorToMajor(value):column.kind==='lines'&&Array.isArray(value)?value.join('\n'):column.kind==='datetime-local'?platformLocalDateTime(value):String(value??'');
  const [draft,setDraft]=useState(external);
  useEffect(()=>{setDraft(previous=>column.kind==='money' && Number(previous)===Number(external) && (previous!==''||external==='')?previous:external);},[external,column.kind]);
  if(column.kind==='boolean')return <BoolToggle value={value===true} label={label} onChange={onChange}/>;
  const edit=(next:string)=>{setDraft(next);if(column.kind==='money'){try{const negative=column.signed&&next.startsWith('-');const parsed=platformMajorToMinor(negative?next.slice(1):next);onChange(parsed==null?null:negative?-parsed:parsed);}catch{return;}}else if(column.kind==='lines')onChange(next.split('\n'));else if(column.kind==='number')onChange(next===''?null:Number(next));else if(column.kind==='datetime-local')onChange(next?new Date(next).toISOString():null);else onChange(next);};
  return <label><span>{label}</span>{column.kind==='lines'||column.kind==='textarea'?<textarea className="platform-field-control" rows={4} value={draft} required={column.required} onChange={event=>edit(event.target.value)}/>:<input className="platform-field-control" type={column.kind==='money'||column.kind==='number'?'number':column.kind??'text'} min={!column.signed&&(column.kind==='money'||column.kind==='number')?0:undefined} step={column.kind==='money'?'0.01':column.kind==='number'?'1':undefined} value={draft} required={column.required} onChange={event=>edit(event.target.value)}/>}</label>;
}
function Fields({columns,row,onChange}:{columns:Column[];row:Entry;onChange:(row:Entry)=>void}) {return <div className="platform-structured-fields">{columns.map(column=><Scalar key={column.key} column={column} value={row[column.key]} onChange={value=>onChange({...row,[column.key]:value})}/>)}</div>;}

function PathItem({row,onChange,courses}:{row:Entry;onChange:(row:Entry)=>void;courses:Entry[]}) {
  const t=useT();const [lessons,setLessons]=useState<Entry[]>([]);const [error,setError]=useState('');
  useEffect(()=>{if(!row.courseId){setLessons([]);return;}const controller=new AbortController();void sessionFetch(apiUrl(`/v1/platform/admin/courses/${encodeURIComponent(String(row.courseId))}`),{headers:authHeaders(false),signal:controller.signal}).then(response=>handleApi<{course:Entry}>(response)).then(result=>{setLessons(Array.isArray(result.course.lessons)?result.course.lessons.map(commerceRecord):[]);setError('');}).catch(reason=>{if(!controller.signal.aborted)setError(String(reason));});return()=>controller.abort();},[row.courseId]);
  return <div className="platform-structured-fields"><label><span>{t('课程','Course')}</span><select className="platform-field-control" required value={String(row.courseId??'')} onChange={event=>onChange({...row,courseId:event.target.value,lessonId:null})}><option value="">{t('选择课程','Choose a course')}</option>{courses.map(course=><option key={String(course.id)} value={String(course.id)}>{commerceText(course,'title',t)}</option>)}</select></label><label><span>{t('课时','Lesson')}</span><select className="platform-field-control" value={String(row.lessonId??'')} onChange={event=>onChange({...row,lessonId:event.target.value||null})}><option value="">{t('整门课程','Whole course')}</option>{lessons.map(lesson=><option key={String(lesson.id)} value={String(lesson.id)}>{commerceText(lesson,'title',t)}</option>)}</select></label>{error?<p role="alert">{error}</p>:null}</div>;
}

function Question({row,onChange}:{row:Entry;onChange:(row:Entry)=>void}) {
  const t=useT();const choices=Array.isArray(row.choices)?row.choices.map(String):[];const type=String(row.type??'single_choice');const selected=Array.isArray(row.answerKey)?row.answerKey:[];
  return <div className="platform-structured-row"><label>{t('题型','Question type')}<select className="platform-field-control" value={type} onChange={event=>{const next=event.target.value;onChange({...row,type:next,choices:next.includes('choice')?['','']:[],answerKey:next==='boolean'?true:next==='text'?'':next==='multiple_choice'?[0]:0});}}><option value="single_choice">{t('单选','Single choice')}</option><option value="multiple_choice">{t('多选','Multiple choice')}</option><option value="boolean">{t('判断','True / false')}</option><option value="text">{t('填空','Text answer')}</option></select></label><Fields row={row} onChange={onChange} columns={[{key:'promptZh',zh:'中文题目',en:'Chinese question',kind:'textarea',required:true},{key:'promptEn',zh:'英文题目',en:'English question',kind:'textarea'},{key:'points',zh:'分值',en:'Points',kind:'number',required:true}]}/>
    {type.includes('choice')?<><h4>{t('选项与正确答案','Choices and correct answers')}</h4>{choices.map((choice,index)=><div className="platform-structured-fields" key={index}><input className="platform-field-control" required aria-label={t(`选项 ${index+1}`,`Choice ${index+1}`)} value={choice} onChange={event=>onChange({...row,choices:choices.map((value,i)=>i===index?event.target.value:value)})}/>{type==='single_choice'?<label><input type="radio" name={`correct-${String(row.editorKey??row.promptZh)}`} checked={row.answerKey===index} onChange={()=>onChange({...row,answerKey:index})}/>{t('正确答案','Correct answer')}</label>:<BoolToggle label={t('正确答案','Correct answer')} value={selected.includes(index)} onChange={checked=>onChange({...row,answerKey:checked?[...selected,index]:selected.filter(value=>value!==index)})}/>}</div>)}<button type="button" className="platform-button" onClick={()=>onChange({...row,choices:[...choices,'']})}>{t('添加选项','Add choice')}</button>{choices.length>2?<button type="button" className="platform-button" onClick={()=>onChange({...row,choices:choices.slice(0,-1),answerKey:type==='multiple_choice'?selected.filter(value=>Number(value)<choices.length-1):Math.min(Number(row.answerKey),choices.length-2)})}>{t('移除最后一个选项','Remove last choice')}</button>:null}</>:type==='boolean'?<BoolToggle label={t('正确答案为“对”','Correct answer is true')} value={row.answerKey===true} onChange={value=>onChange({...row,answerKey:value})}/>:<Scalar column={{key:'answerKey',zh:'正确答案',en:'Correct answer',required:true}} value={row.answerKey} onChange={value=>onChange({...row,answerKey:value})}/>}
  </div>;
}

export function PlatformStructuredField({fieldKey,label,value,onChange,routeId}:{fieldKey:string;label:string;value:string;onChange:(value:string)=>void;routeId:string}) {
  const t=useT();let parsed:unknown;try{parsed=JSON.parse(value||(['venue','presentation','eligibility'].includes(fieldKey)?'{}':'[]'));}catch{parsed={};}
  const rows=Array.isArray(parsed)?parsed.map(commerceRecord):[];const object=commerceRecord(parsed);
  const [courses,setCourses]=useState<Entry[]>([]);const [loadError,setLoadError]=useState('');
  useEffect(()=>{if(fieldKey!=='items')return;const controller=new AbortController();void(async()=>{try{const loaded:Entry[]=[];for(let page=1;page<=100;page++){const response=await sessionFetch(apiUrl(`/v1/platform/admin/courses?page=${page}&pageSize=100`),{headers:authHeaders(false),signal:controller.signal});const result=await handleApi<{courses:Entry[];total?:number}>(response);loaded.push(...result.courses);if(result.courses.length<100||(result.total!=null&&loaded.length>=result.total))break;}setCourses(loaded);setLoadError('');}catch(reason){if(!controller.signal.aborted)setLoadError(String(reason));}})();return()=>controller.abort();},[fieldKey]);
  const save=(next:unknown)=>onChange(JSON.stringify(next));
  const update=(index:number,next:Entry)=>save(rows.map((row,i)=>i===index?next:row));
  const objectColumns=fieldKey==='venue'?venueFields:fieldKey==='presentation'?(routeId.includes('product')?productPresentation:coursePresentation):null;
  if(objectColumns)return <fieldset className="platform-structured-editor"><legend>{label}</legend><Fields columns={objectColumns} row={object} onChange={save}/>{fieldKey==='presentation'&&!routeId.includes('product')?<PlatformStructuredField fieldKey="outline" label={t('课程大纲','Course outline')} value={JSON.stringify(object.outline??[])} routeId={routeId} onChange={next=>save({...object,outline:JSON.parse(next)})}/>:null}</fieldset>;
  if(fieldKey==='eligibility')return <fieldset className="platform-structured-editor"><legend>{label}</legend><BoolToggle label={t('仅限会员使用','Members only')} value={object.memberOnly===true} onChange={value=>save({...object,memberOnly:value})}/>{['courseIds','productIds','productVariantIds','eventIds','eventTicketTypeIds','membershipPlanIds'].map(key=><PlatformReferenceField key={key} source={key} label={t(({courseIds:'适用课程',productIds:'适用商品',productVariantIds:'适用规格',eventIds:'适用活动',eventTicketTypeIds:'适用票种',membershipPlanIds:'适用会员套餐'} as Record<string,string>)[key],({courseIds:'Courses',productIds:'Products',productVariantIds:'Variants',eventIds:'Events',eventTicketTypeIds:'Ticket types',membershipPlanIds:'Membership plans'} as Record<string,string>)[key])} selected={Array.isArray(object[key])?(object[key] as unknown[]).map(String):[]} onChange={values=>save({...object,[key]:values})}/>)}</fieldset>;
  const add=()=>{const row=fieldKey==='variants'?{sku:'',titleZh:'',titleEn:'',amountMinor:0,currency:'CNY',inventoryOnHand:0,status:'active'}:fieldKey==='tickets'?{code:'',titleZh:'',titleEn:'',amountMinor:0,currency:'CNY',capacity:1,status:'active'}:fieldKey==='records'?{providerTransactionId:'',amountMinor:0,currency:'CNY'}:fieldKey==='questions'?{type:'single_choice',promptZh:'',promptEn:'',choices:['',''],answerKey:0,points:1}:{};save([...rows,row]);};
  return <fieldset className="platform-structured-editor"><legend>{label}</legend>{loadError?<p role="alert">{loadError}</p>:null}{rows.map((row,index)=><section className="platform-structured-row" key={index}><strong>{index+1}</strong>{fieldKey==='items'?<PathItem row={row} onChange={next=>update(index,next)} courses={courses}/>:fieldKey==='questions'?<Question row={{...row,editorKey:`question-${index}`}} onChange={next=>update(index,next)}/>:<Fields row={row} onChange={next=>update(index,next)} columns={fieldKey==='variants'?variantFields:fieldKey==='tickets'?ticketFields:fieldKey==='records'?[{key:'providerTransactionId',zh:'渠道流水号',en:'Provider transaction reference',required:true},{key:'amountMinor',zh:'收付金额（元；退款填负数）',en:'Amount (major units; negative for refunds)',kind:'money',signed:true,required:true},{key:'currency',zh:'币种',en:'Currency',required:true}]:[{key:'label',zh:'章节',en:'Section',required:true},{key:'topic',zh:'内容',en:'Topic',kind:'textarea'}]}/>}{['variants','tickets'].includes(fieldKey)?<label>{t('状态','Status')}<select className="platform-field-control" value={String(row.status??'active')} onChange={event=>update(index,{...row,status:event.target.value})}><option value="active">{t('销售中','Available')}</option><option value="sold_out">{t('售罄','Sold out')}</option><option value="archived">{t('已归档','Archived')}</option></select></label>:null}<div className="platform-write-actions"><button type="button" className="platform-button" disabled={index===0} onClick={()=>{const next=[...rows];[next[index-1],next[index]]=[next[index],next[index-1]];save(next);}}>{t('上移','Move up')}</button><button type="button" className="platform-button" disabled={index===rows.length-1} onClick={()=>{const next=[...rows];[next[index],next[index+1]]=[next[index+1],next[index]];save(next);}}>{t('下移','Move down')}</button><button type="button" className="platform-button" onClick={()=>save(rows.filter((_,i)=>i!==index))}>{t('移除此项','Remove item')}</button></div></section>)}<button type="button" className="platform-button" onClick={add}>{t('添加一项','Add item')}</button></fieldset>;
}
