/**
 * cubing.js "explore" puzzle ids (pgCatalog) that get a FAITHFUL group-theory kernel,
 * shown as a facts-only panel (|G| + orbit structure — no live state, since these render
 * purely via TwistyPlayer with no in-house engine cube to mirror).
 *
 * Only DOCTRINAIRE puzzles belong here: puzzles whose reachable-state group equals the
 * group generated by their outer-layer turns. For a doctrinaire puzzle the displayed
 * |G| = |⟨outer turns⟩| (Schreier-Sims over the canonical outer generators, allMoves:false)
 * IS the exact reachable-state count — rigorous by construction, no external validation
 * needed. Same frame-distinct convention as the engine puzzles (baked 2×2×2 = 88,179,840).
 *
 * JUMBLING puzzles are EXCLUDED — their reachable set is strictly LARGER than the outer-turn
 * group (partial/off-axis moves reach states no block turn does), so a displayed outer-turn
 * |G| would UNDERSTATE the puzzle. Also excluded: shape-shifters whose outer-turn group is
 * an unfaithful subgroup (pyramorphix / mastermorphix family) and puzzles too large to
 * precompute (degree > ~320: gigaminx, teraminx, …). Jumbling determination for the
 * borderline dodeca/icosa cuts was decided by a high-rigor 3-vote adversarial workflow
 * against Jaap Scherphuis's corner-overhang criterion — anything not unanimously
 * non-jumbling was excluded (pentultimate, masterpentultimate, starminxcombo, starminx2,
 * astrominx, chopasaurus, bigchop, eitansstar, …).
 *
 * Lightweight (ids only, no heavy imports) so it can be imported by the panel / SimPage
 * without pulling in the vendored puzzle-geometry.
 */
export const EXPLORE_BOUND_IDS: readonly string[] = [
  // Tetrahedral (pyraminx / tetraminx family — 3-fold axes never jumble at any depth)
  'tetraminx', // |G| ≈ 1.12×10⁷
  'jingpyraminx', // ≈ 4.48×10⁷
  'mastertetraminx', // ≈ 2.68×10¹⁵
  'masterpyraminx', // ≈ 2.61×10¹⁸
  'professortetraminx', // ≈ 1.85×10³³
  'professorpyraminx', // ≈ 1.50×10³⁵
  'royaltetraminx', // ≈ 2.11×10⁵⁷
  'royalpyraminx', // ≈ 1.71×10⁵⁹
  'emperortetraminx', // ≈ 3.48×10⁸³
  'emperorpyraminx', // ≈ 2.82×10⁸⁵
  // Cube vertex-turn (skewb family) + octahedral 3-fold (dual of skewb) — doctrinaire
  'skewbdiamond', // ≈ 1.66×10⁶
  'christophersjewel', // ≈ 2.01×10¹⁵
  'trajbersoctahedron', // ≈ 4.05×10¹⁹
  'cube2dino', // 24! ≈ 6.20×10²³ (2×2 face + Dino vertex, "Super X")
  'masterskewb', // ≈ 5.19×10³²
  'professorskewb', // ≈ 4.09×10⁷⁴
  'masterfto', // octahedral face-turn, ≈ 3.13×10⁵⁶
  // Dodeca/icosa 5-fold, shallow-or-through-centre (non-jumbling — 3-vote verified)
  'starminx', // dodeca vertex-turn (Dino-dodecahedron), ≈ 2.48×10⁵⁰
  'pyraminxcrystal', // dodeca face-turn (through adjacent centres), ≈ 1.01×10⁶⁸
  'icosamate', // icosa vertex-turn through centre, ≈ 7.11×10³⁴
  'redicosahedron', // icosa vertex-turn (Redi depth), ≈ 1.74×10⁴⁹
  'redicosahedroncenters', // icosa vertex-turn (Redi + centres), ≈ 1.74×10⁴⁹
  'icosaminx', // icosa vertex-turn (Megaminx-shape depth), ≈ 2.11×10⁶⁷
];

export const EXPLORE_BOUND = new Set<string>(EXPLORE_BOUND_IDS);

export const isExploreBound = (id: string): boolean => EXPLORE_BOUND.has(id);
