/**
 * ExploreFactsBinding — a facts-only GroupKernel for cubing.js "explore" puzzles
 * (pgCatalog), which render purely through TwistyPlayer and have NO in-house engine cube.
 * Without an engine to mirror, there is no live state / solve / scramble; the panel shows
 * only the static group facts. Those facts are the RIGOROUS group generated by the
 * puzzle's canonical OUTER-layer turns (built with allMoves:false — the faithful move set;
 * PG's default allMoves:true adds deep slices that inflate |G|, e.g. compy 1.88×10¹³ vs the
 * true 1.57×10¹²). Only doctrinaire puzzles are bound (see exploreBound.ts).
 *
 * Facts come from the SAME precomputed table as the engine puzzles (keyed by the explore
 * id), so the runtime never runs Schreier-Sims; the live path (computeFactsLive) is used
 * only by the offline generator.
 */
import { PgBackbone, type PgGroupFacts } from './pgBackbone';
import type { GroupKernel } from './pgBinding';
import { precomputedFacts } from './pgFacts';

export class ExploreFactsBinding implements GroupKernel {
  readonly solvable = false;
  readonly solved = true;
  readonly hasLiveState = false;
  private cachedFacts?: PgGroupFacts;

  /** @param key  the explore id (pgCatalog id), also the precomputed-facts table key
   *  @param def  the PG description string (pgCatalog `def`, e.g. 'd f 0') */
  constructor(private readonly key: string, private readonly def: string) {}

  facts(): PgGroupFacts {
    if (!this.cachedFacts) {
      const pre = precomputedFacts(this.key);
      if (pre) {
        this.cachedFacts = pre;
      } else {
        if ((import.meta as { env?: { DEV?: boolean } }).env?.DEV) {
          console.warn(`[pgFacts] no precomputed facts for explore "${this.key}" — computing live (freezes UI). Regenerate tests/gen_pg_facts.gen.test.ts`);
        }
        this.cachedFacts = this.computeFactsLive();
      }
    }
    return this.cachedFacts;
  }

  /** Live-computed facts — offline generator only. Rigorous |G| over the puzzle's outer
   *  generators (allMoves:false), via the same `factsOver` path the PG bridges use for
   *  their turning-only groups (reorientations = 1, reassembly over the moved orbits). */
  computeFactsLive(): PgGroupFacts {
    const bb = new PgBackbone({ desc: this.def, allMoves: false });
    return bb.factsOver(bb.od.moveops, bb.od.movenames);
  }

  rebuildFromString(): void { /* no live state */ }
  currentOrder(): number { return 1; }
  solveString(): string { return ''; }
  scrambleString(): string { return ''; }
}
