'use client';

import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useParams } from 'next/navigation';
import {
  TEACHING_WEEKLY_REPORT_VISIBILITIES,
  hasTeachingPermission,
  type TeachingOrganizationRole,
  type TeachingWeeklyReport,
  type TeachingWeeklyReportVisibility,
} from '@cuberoot/shared/teaching';
import AppLink from '@/components/AppLink';
import WeeklyReportSections, { teachingVisibilityLabel } from '@/components/teaching/WeeklyReportSections';
import { useT } from '@/hooks/useT';
import { getTeachingWeeklyReport, publishTeachingWeeklyReport } from '@/lib/teaching-saas-api';
import OrgWorkspace from '../../../_components/OrgWorkspace';
import {
  entityStatusLabel,
  MutationMessage,
  teachingErrorMessage,
  teachingRoleLabel,
  useOperationKey,
} from '../../../_components/OrgUi';

export default function WeeklyReportPage() {
  const params = useParams<{ orgSlug: string; reportId: string }>();
  return (
    <OrgWorkspace orgSlug={params.orgSlug}>
      {(organization) => (
        <ReportContent orgSlug={params.orgSlug} reportId={params.reportId} role={organization.role} />
      )}
    </OrgWorkspace>
  );
}

function ReportContent({ orgSlug, reportId, role }: {
  orgSlug: string;
  reportId: string;
  role: TeachingOrganizationRole;
}) {
  const t = useT();
  const operationKey = useOperationKey();
  const [report, setReport] = useState<TeachingWeeklyReport | null>(null);
  const [loadError, setLoadError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [message, setMessage] = useState('');
  const [mutationError, setMutationError] = useState('');
  const canManage = hasTeachingPermission(role, 'report:manage');

  const loadReport = useCallback(async () => {
    try {
      setReport(await getTeachingWeeklyReport(orgSlug, reportId));
      setLoadError('');
    } catch (reason) {
      setLoadError(teachingErrorMessage(reason, t));
    }
  }, [orgSlug, reportId, t]);

  useEffect(() => { void loadReport(); }, [loadReport]);

  async function publish(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const teacherSummary = String(data.get('teacherSummary') ?? '').trim();
    const nextWeekPlan = String(data.get('nextWeekPlan') ?? '').trim();
    const rawVisibility = String(data.get('visibility') ?? '');
    if (teacherSummary.length < 1 || teacherSummary.length > 5_000
      || nextWeekPlan.length < 1 || nextWeekPlan.length > 5_000) {
      setMutationError(t('本周总结和下周计划都需填写，且各不超过 5000 字。', 'Complete both fields with no more than 5,000 characters each.'));
      return;
    }
    if (!(TEACHING_WEEKLY_REPORT_VISIBILITIES as readonly string[]).includes(rawVisibility)) {
      setMutationError(t('请选择有效的发布范围。', 'Select a valid publication audience.'));
      return;
    }
    const visibility = rawVisibility as TeachingWeeklyReportVisibility;
    setSubmitting(true);
    setMessage('');
    setMutationError('');
    try {
      const published = await publishTeachingWeeklyReport(
        orgSlug,
        reportId,
        { teacherSummary, nextWeekPlan, visibility },
        operationKey.get(),
      );
      setReport(published);
      operationKey.reset();
      setMessage(t('每周报告已发布。', 'Weekly report published.'));
    } catch (reason) {
      setMutationError(teachingErrorMessage(reason, t));
    } finally {
      setSubmitting(false);
    }
  }

  if (loadError) return <MutationMessage message={loadError} error />;
  if (!report) return <p aria-busy="true">{t('正在加载每周报告…', 'Loading weekly report…')}</p>;

  return (
    <>
      <AppLink href={`/org/${orgSlug}/reports`} prefetch={false}>{t('每周报告列表', 'Weekly report list')}</AppLink>
      <div className="org-heading-row">
        <h2>{report.studentDisplayNameSnapshot}</h2>
        <span className="org-status">{entityStatusLabel(report.status, t)}</span>
      </div>
      <p className="org-lead">{report.weekStart} – {report.weekEnd} / {report.timezoneSnapshot}</p>
      <p className="org-help">{t('发布范围决定学员本人或监护人是否能在主站学习中心读取这份报告。', 'The publication audience controls whether the learner or guardians can read this report in the main-site learning center.')}</p>
      <dl className="org-summary">
        <div><dt>{t('版本', 'Revision')}</dt><dd>{report.revision}</dd></div>
        <div><dt>{t('发布范围', 'Publication audience')}</dt><dd>{teachingVisibilityLabel(report.visibility, t)}</dd></div>
        <div><dt>{t('生成人', 'Generated by')}</dt><dd>{report.generatedByDisplayNameSnapshot} / {teachingRoleLabel(report.generatedByRoleSnapshot, t)}</dd></div>
        <div><dt>{t('生成时间', 'Generated at')}</dt><dd>{new Date(report.generatedAt).toLocaleString()}</dd></div>
        {report.publishedByDisplayNameSnapshot && <div><dt>{t('发布人', 'Published by')}</dt><dd>{report.publishedByDisplayNameSnapshot}</dd></div>}
        {report.publishedAt && <div><dt>{t('发布时间', 'Published at')}</dt><dd>{new Date(report.publishedAt).toLocaleString()}</dd></div>}
      </dl>

      <WeeklyReportSections
        aggregate={report.aggregate}
        teacherSummary={report.teacherSummary}
        nextWeekPlan={report.nextWeekPlan}
        assignmentHref={(assignmentId) => `/org/${orgSlug}/training/assignments/${assignmentId}`}
      />

      {canManage && report.status === 'draft' && (
        <section className="org-section">
          <h2>{t('发布报告', 'Publish report')}</h2>
          <form className="org-form" onSubmit={publish} onChange={() => { operationKey.reset(); setMessage(''); }}>
            <fieldset disabled={submitting}>
              <label className="org-field-wide">{t('本周总结', 'Weekly summary')}
                <textarea className="org-form-control org-form-textarea" name="teacherSummary" required minLength={1} maxLength={5_000} defaultValue={report.teacherSummary} />
              </label>
              <label className="org-field-wide">{t('下周计划', 'Next week plan')}
                <textarea className="org-form-control org-form-textarea" name="nextWeekPlan" required minLength={1} maxLength={5_000} defaultValue={report.nextWeekPlan} />
              </label>
              <label>{t('发布范围', 'Publication audience')}
                <select className="org-form-control" name="visibility" defaultValue={report.visibility}>
                  {TEACHING_WEEKLY_REPORT_VISIBILITIES.map((visibility) => (
                    <option value={visibility} key={visibility}>{teachingVisibilityLabel(visibility, t)}</option>
                  ))}
                </select>
                <small className="org-help">{t('选择“学员与监护人”才会向已绑定监护人开放。', 'Choose “Student and guardians” to make the report available to linked guardians.')}</small>
              </label>
              <div className="org-form-actions">
                <button className="org-form-button" type="submit">{submitting ? t('发布中…', 'Publishing…') : t('发布报告', 'Publish report')}</button>
              </div>
            </fieldset>
          </form>
        </section>
      )}
      <MutationMessage message={mutationError || message} error={!!mutationError} />
    </>
  );
}
