/** Web runtime adapter for the framework-free Web/Mobile timer history contract. */
export {
  TIMER_HISTORY_FILTER_CONTRACTS,
  TIMER_HISTORY_PENALTIES,
  TIMER_HISTORY_QUICK_ACTION_COPY,
  TIMER_HISTORY_QUICK_ACTION_IDS,
  TIMER_SOLVE_DETAIL_ACTION_CONTRACTS,
  TIMER_SOLVE_DETAIL_ACTION_IDS,
  createTimerHistoryFilters,
  computeTimerHistoryTags,
  deleteTimerHistorySolve,
  filterTimerHistorySolves,
  parseTimerHistorySeconds,
  pruneTimerHistoryCompareSelection,
  restoreTimerHistorySolve,
  resolveTimerHistoryComparePair,
  timerHistoryCopyText,
  timerHistoryMoveTargets,
  timerHistoryQuickActionPenalty,
  timerHistoryQuickActionStates,
  timerSolveDetailActionStates,
  toggleTimerHistoryTag,
  toggleTimerHistoryPenalty,
  toggleTimerHistoryCompareSelection,
  updateTimerHistorySolve,
  type TimerHistoryFilters,
  type TimerHistoryTagId,
  type TimerHistoryQuickActionId,
  type TimerSolveDetailActionId,
} from '@cuberoot/shared/timer';
