// One-shot converter: TNoodle i18n YAMLs → bundled TS module.
// Source: D:\cube\tnoodle\server\src\main\resources\i18n\*.yml
// Output: src/pages/gen/tnoodle_i18n.ts
//
// Run when upstream tnoodle ships new translations:
//   node scripts/build_tnoodle_i18n.mjs
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
// js-yaml not in client deps; use the workspace install via direct path.
import yaml from '../../../node_modules/.pnpm/js-yaml@4.1.1/node_modules/js-yaml/dist/js-yaml.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = 'D:/cube/tnoodle/server/src/main/resources/i18n';
const OUT_FILE = join(__dirname, '..', 'src', 'pages', 'gen', 'tnoodle_i18n.ts');

const out = {};
for (const file of readdirSync(SRC_DIR).sort()) {
  if (!file.endsWith('.yml')) continue;
  const localeKey = file.replace(/\.yml$/, '');
  const text = readFileSync(join(SRC_DIR, file), 'utf8');
  const parsed = yaml.load(text);
  // Top-level key matches the locale; flatten one layer.
  const root = parsed[Object.keys(parsed)[0]];
  out[localeKey] = root;
}

const localeCodes = Object.keys(out).sort();
const banner = `// Generated by scripts/build_tnoodle_i18n.mjs from D:\\cube\\tnoodle\\server\\src\\main\\resources\\i18n
// DO NOT EDIT BY HAND. Re-run the script when tnoodle upstream updates translations.

export type TnoodleLocale = ${localeCodes.map(l => JSON.stringify(l)).join(' | ')};

export const TNOODLE_LOCALES: readonly TnoodleLocale[] = ${JSON.stringify(localeCodes)} as const;

export interface TnoodleTranslations {
  fmc: {
    scrambleXofY: string;
    scramble: string;
    round: string;
    attempt: string;
    competitor: string;
    warning: string;
    event: string;
    graded: string;
    result: string;
    competition: string;
    registrantId: string;
    rule1: string;
    rule2: string;
    rule3: string;
    rule4: string;
    rule5: string;
    rule6: string;
    faceMoves: string;
    rotations: string;
    clockwise: string;
    counterClockwise: string;
    double: string;
    scrambleOnSeparateSheet: string;
  };
}

export const TNOODLE_I18N: Record<TnoodleLocale, TnoodleTranslations> = ${JSON.stringify(out, null, 2)};
`;

writeFileSync(OUT_FILE, banner);
console.log(`Wrote ${OUT_FILE} with ${localeCodes.length} locales: ${localeCodes.join(', ')}`);
