/** Generate the cross-runtime avatar allowlist from the existing pet gallery. */
import { resolve } from 'node:path';
import { resolveWorkspacePath } from '../../../scripts/resolve-workspace-path.mjs';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createContext, Script } from 'node:vm';
import { DOMParser, Element } from 'linkedom';
import { svgPathProperties } from 'svg-path-properties';
import svgpath from 'svgpath';
import { PET_GALLERY } from '../lib/deskpet-gallery';
import { CLAWD_AVATAR_PRESETS } from '@cuberoot/shared/account-avatar';
// Scripted Cloudling SVGs are blank/incomplete in <img>. Freeze their own scene
// renderer at 1.5 s into an inert SVG so all existing avatar consumers can use it.
function freezeScriptedAvatar(src: string): string {
  const raw = readFileSync(new URL('../public' + src.split('?')[0], import.meta.url), 'utf8');
  const document = new DOMParser().parseFromString(raw, 'image/svg+xml');
  Object.defineProperty(document, 'body', { value: document.documentElement });
  Object.assign(Element.prototype, {
    getTotalLength(this: Element) { return new svgPathProperties(svgpath(this.getAttribute('d') ?? '').unarc().toString()).getTotalLength(); },
    getPointAtLength(this: Element, length: number) { return new svgPathProperties(svgpath(this.getAttribute('d') ?? '').unarc().toString()).getPointAtLength(length); },
  });
  const scripts = [...document.querySelectorAll('script')].map(node => {
    const code = node.textContent!.replace(/^\s*<!\[CDATA\[/, '').replace(/\]\]>\s*$/, '');
    node.remove(); return code;
  });
  let now = 0;
  let frames: Array<(time: number) => void> = [];
  const scope = { document, performance: { now: () => now },
    requestAnimationFrame: (cb: (time: number) => void) => { frames.push(cb); return frames.length; },
    cancelAnimationFrame: () => {}, setTimeout: () => 0, clearTimeout: () => {},
    addEventListener: () => {}, matchMedia: () => ({ matches: false, addEventListener: () => {} }),
    Math: Object.assign(Object.create(Math), { random: () => 0.5 }),
    location: { search: '' }, URLSearchParams, console,
  };
  const context = createContext({ ...scope, window: scope });
  for (const code of scripts) new Script(code).runInContext(context, { timeout: 1000 });
  for (now = 0; now <= 1500; now += 50) {
    const pending = frames; frames = [];
    for (const cb of pending) cb(now);
  }
  const svg = document.querySelector('svg')!.outerHTML;
  const hash = createHash('sha256').update(svg).digest('hex').slice(0, 12);
  const file = src.split('/').pop()!.split('?')[0];
  const dir = new URL('../public/deskpet/avatars/', import.meta.url);
  mkdirSync(dir, { recursive: true });
  writeFileSync(new URL(file, dir), svg);
  return '/deskpet/avatars/' + file + '?v=' + hash;
}
const legacy = new Set(CLAWD_AVATAR_PRESETS.map(p => `/deskpet/${p.file}`));
const seen = new Set<string>();
const presets = PET_GALLERY.flatMap(group => group.anims.flatMap(anim => {
  const src = anim.src ?? `${group.base}${anim.file}${group.v ? `?v=${group.v}` : ''}`;
  const path = src.split('?')[0];
  if (legacy.has(path) || seen.has(path)) return [];
  seen.add(path);
  return [{ id: `pet-${createHash('sha256').update(path).digest('hex').slice(0, 24)}`,
    petId: ['cubing', 'moves'].includes(group.id) ? 'clawd' : group.id,
    src: group.scripted ? freezeScriptedAvatar(src) : src, sourceSrc: src, zh: anim.zh, en: anim.en }];
}));
writeFileSync(resolve(import.meta.dirname, '../../..', resolveWorkspacePath('@cuberoot/shared'), 'src/account_avatar_gallery.generated.ts'),
  '// Generated by client/scripts/build-account-avatars.ts from PET_GALLERY; do not edit.\n'
  + 'const presets: readonly { id: string; petId: string; src: string; sourceSrc: string; zh: string; en: string }[] = '
  + JSON.stringify(presets, null, 2) + ';\nexport default presets;\n');
console.log(`Generated ${presets.length} additional avatar choices.`);
