/**
 * Convert words_multilang.ndjson → colpi_seed_multilang.sql.
 *
 * Output is idempotent: per-batch INSERT … ON CONFLICT (pair, word, language)
 * DO NOTHING. Run once to seed prod; re-run safely for incremental fixes.
 *
 * Usage: node scripts/colpi_ndjson_to_sql.mjs [--in=path] [--out=path]
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const BATCH = 500;

function parseArgs() {
  const out = { inFile: null, outFile: null };
  for (const a of process.argv.slice(2)) {
    if (a.startsWith('--in=')) out.inFile = a.slice(5);
    else if (a.startsWith('--out=')) out.outFile = a.slice(6);
  }
  return out;
}

function escape(s) {
  return s.replace(/'/g, "''");
}

function rowToValues(r) {
  return `('${escape(r.pair)}', '${escape(r.word)}', '${escape(r.category)}', '${escape(r.language)}', ${r.offensive ? 'TRUE' : 'FALSE'})`;
}

function main() {
  const args = parseArgs();
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  const inFile  = args.inFile  || path.join(__dirname, 'words_multilang.ndjson');
  const outFile = args.outFile || path.join(__dirname, 'colpi_seed_multilang.sql');

  if (!fs.existsSync(inFile)) {
    console.error(`Input not found: ${inFile}`);
    process.exit(1);
  }

  const lines = fs.readFileSync(inFile, 'utf-8').split('\n').filter(Boolean);
  console.log(`Input: ${lines.length} rows from ${inFile}`);

  // De-dup at file level (same pair+word+lang would still collide on insert,
  // but trimming early shrinks the SQL).
  const seen = new Set();
  const rows = [];
  let dups = 0;
  for (const line of lines) {
    let r;
    try { r = JSON.parse(line); } catch { continue; }
    const key = `${r.pair}|${r.word}|${r.language}`;
    if (seen.has(key)) { dups++; continue; }
    seen.add(key);
    rows.push(r);
  }
  console.log(`After dedup: ${rows.length} rows (${dups} dups)`);

  const langCounts = {};
  for (const r of rows) langCounts[r.language] = (langCounts[r.language] || 0) + 1;
  console.log('Per-lang:', JSON.stringify(langCounts));

  const out = [];
  out.push('-- Auto-generated by colpi_ndjson_to_sql.mjs.');
  out.push('-- Idempotent: ON CONFLICT (pair, word, language) DO NOTHING.');
  out.push("SET client_encoding = 'UTF8';");
  out.push('BEGIN;');
  for (let i = 0; i < rows.length; i += BATCH) {
    const chunk = rows.slice(i, i + BATCH);
    out.push(
      `INSERT INTO colpi_words (pair, word, category, language, offensive) VALUES\n  ` +
      chunk.map(rowToValues).join(',\n  ') +
      `\nON CONFLICT (pair, word, language) DO NOTHING;`,
    );
  }
  out.push('COMMIT;');

  fs.writeFileSync(outFile, out.join('\n') + '\n');
  const sizeKb = (fs.statSync(outFile).size / 1024).toFixed(1);
  console.log(`Wrote ${rows.length} rows in ${Math.ceil(rows.length / BATCH)} batches (${sizeKb} KB) → ${outFile}`);
}

main();
