# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy>=1.26", "scipy>=1.11"]
# ///
"""
MANO pkl -> web hand asset (JSON + base64 buffers) for /sim hands.

Usage (uv, per global convention):
  uv run core/packages/client/scripts/convert-mano.py [--src D:/cube/mano] [--no-subdiv]

Input:  MANO_RIGHT.pkl (searched under --src, its models/ subdir, or inside
        mano_v1_2.zip found there). This is the licensed MPI file the user
        downloads from https://mano.is.tue.mpg.de after registration — NEVER
        commit it or the converted output (repo is public; MANO license
        forbids redistribution). Output dir is gitignored.
        The LEFT asset is generated by mirroring RIGHT across x=0. The shipped
        MANO_LEFT template is itself a bit-exact mirror of RIGHT (verified
        2026-07-11: max vert/joint/weight diff 0.0) — mirroring in-converter
        just drops the second pkl and keeps L/R symmetry true by construction.
        (An earlier "left template is asymmetric" diagnosis was wrong: the
        measured fGap difference came from a wrist-anchor offset bug in
        homeLeft, since fixed — see handPoses.ts homeLeft mano branch.)
Output: core/packages/client/public/sim/hands/mano/{right,left}.mano.json

Also (when models_smplx_v1_1.zip / SMPLX_NEUTRAL.npz is present under --src):
        core/packages/client/public/sim/hands/smplx/forearm.smplx.json
        — a real-forearm piece cut from the SMPL-X body (elbow-to-past-wrist
        slab in the forearm frame), replacing the procedural tapered tube in
        handModel.buildForearm. Rigid (no skinning; the rig poses the forearm
        as one group), right side only — the left arm is y-mirrored at runtime
        (ulna head sits on the pinky side; a real forearm is not symmetric).
        load_smplx() keeps ALL model tensors (weights/posedirs/kintree) so a
        future full-body mode reuses the same loader + operators (mask cut ->
        cap -> subdivide -> unwrap); the forearm is just the first consumer.
        Same license rule as MANO: never commit the npz or converted output.

What it does (bind pose = MANO zero pose, betas = 0):
  1. Unpickle with a chumpy stub (original pkls reference chumpy classes;
     we only need the wrapped ndarrays — no chumpy install, no numpy pin).
  2. joints = J_regressor @ v_template  (16: wrist + 5 fingers x 3).
  3. Identify finger chains geometrically (thumb = chain base closest to
     wrist; index..pinky ordered by lateral position, index on thumb side)
     — robust to MANO's odd index/middle/pinky/ring/thumb joint order.
  4. Synthesize the WebXR joints MANO lacks: four-finger metacarpals
     (wrist + 22% toward MCP, zero skin weight — FK anchors for the rig's
     palm-arch meta channel) and five tips (extremal skin vertex along the
     distal bone axis). Result: the exact 25-name WebXR set, so the
     existing adaptGltfHand() consumes this asset unchanged.
  5. Cap the open wrist ring (fan to centroid, skinned to wrist) so the
     mesh is closed; then one Loop subdivision step (778 -> ~3.1k verts,
     silhouette-smooth; skin weights averaged + renormalized to top-4).
  6. Injective UV atlas via box projection (MANO has no authored UV layout):
     faces bucketed by dominant normal axis (6 directions), split into
     edge-connected components, each component projected onto its axis plane
     and shelf-packed with gutters; seam vertices are duplicated per
     component. This is what lets bakeHandTextures (UV-space rasterization,
     3D-domain feature evaluation) run on MANO — an overlapping projection
     would blend palm/dorsal features into the same texels.
  7. Smooth area-weighted vertex normals exported explicitly (computed
     BEFORE seam duplication — computeVertexNormals on the duplicated mesh
     would produce hard shading seams along every UV island border).
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import pickle
import sys
import zipfile
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]  # core/packages/client/scripts -> repo/core
OUT_DIR = REPO / "packages" / "client" / "public" / "sim" / "hands" / "mano"
SMPLX_OUT_DIR = REPO / "packages" / "client" / "public" / "sim" / "hands" / "smplx"

WEBXR_FINGERS = ["thumb", "index", "middle", "ring", "pinky"]


# ---------------------------------------------------------------- unpickle
class _ChumpyStub:
    """Absorbs any chumpy.* class: keeps the pickled state dict; the wrapped
    ndarray lives under 'x' (Ch) — np.asarray() below digs it out."""

    def __init__(self, *a, **k):
        self.__dict__["_state"] = {}

    def __setstate__(self, state):
        self.__dict__["_state"] = state


class _Unpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module.startswith("chumpy"):
            return _ChumpyStub
        return super().find_class(module, name)


def _to_np(x) -> np.ndarray:
    if isinstance(x, _ChumpyStub):
        st = x.__dict__.get("_state", {})
        if isinstance(st, dict):
            for key in ("x", "a", "_data"):
                if key in st:
                    return _to_np(st[key])
        raise ValueError(f"chumpy stub without array payload: keys={list(st) if isinstance(st, dict) else type(st)}")
    if hasattr(x, "toarray"):  # scipy sparse
        return np.asarray(x.toarray())
    return np.asarray(x)


def load_pkl(raw: bytes) -> dict:
    d = _Unpickler(io.BytesIO(raw), encoding="latin1").load()
    out = {}
    for k in ("v_template", "f", "weights", "J_regressor", "kintree_table", "posedirs"):
        if k not in d:
            raise KeyError(f"MANO pkl missing '{k}' (got keys {sorted(d.keys())})")
        out[k] = _to_np(d[k])
    return out


def find_source(src: Path) -> bytes:
    """Return MANO_RIGHT.pkl bytes from a loose pkl or a zip (left is mirrored)."""
    fname = "MANO_RIGHT.PKL"
    for cand in (src, src / "models", src / "mano_v1_2" / "models"):
        for p in cand.glob("*.pkl") if cand.is_dir() else []:
            if p.name.upper() == fname:
                return p.read_bytes()
    if src.is_dir():
        for zp in sorted(src.glob("*.zip")):
            with zipfile.ZipFile(zp) as z:
                for info in z.infolist():
                    if Path(info.filename).name.upper() == fname:
                        return z.read(info)
    sys.exit(f"[convert-mano] missing MANO_RIGHT.pkl under {src} (loose pkl, models/, or mano_v1_2.zip)")


# ---------------------------------------------------------------- geometry
def loop_subdivide(v: np.ndarray, f: np.ndarray, w: np.ndarray, uv: np.ndarray):
    """One Loop step on a CLOSED triangle mesh. Weights/uv: edge verts = avg
    of endpoints; old verts keep their weights (positions get Loop smoothing)."""
    nv = len(v)
    edges: dict[tuple[int, int], int] = {}
    opp: dict[tuple[int, int], list[int]] = {}
    for tri in f:
        for i in range(3):
            a, b, c = tri[i], tri[(i + 1) % 3], tri[(i + 2) % 3]
            key = (min(a, b), max(a, b))
            opp.setdefault(key, []).append(c)
    for key in opp:
        edges[key] = nv + len(edges)
    # neighbor sets for old-vertex smoothing
    nbr: list[set[int]] = [set() for _ in range(nv)]
    for (a, b) in opp:
        nbr[a].add(b)
        nbr[b].add(a)
    v_old = np.empty_like(v)
    for i in range(nv):
        n = len(nbr[i])
        if n < 3:
            v_old[i] = v[i]
            continue
        beta = (5.0 / 8.0 - (3.0 / 8.0 + 0.25 * np.cos(2 * np.pi / n)) ** 2) / n
        v_old[i] = (1 - n * beta) * v[i] + beta * sum(v[j] for j in nbr[i])
    v_edge = np.empty((len(edges), 3))
    w_edge = np.empty((len(edges), w.shape[1]))
    uv_edge = np.empty((len(edges), 2))
    for (a, b), idx in edges.items():
        os_ = opp[(a, b)]
        if len(os_) == 2:
            v_edge[idx - nv] = 3 / 8 * (v[a] + v[b]) + 1 / 8 * (v[os_[0]] + v[os_[1]])
        else:  # boundary edge (shouldn't happen after capping) — midpoint
            v_edge[idx - nv] = 0.5 * (v[a] + v[b])
        w_edge[idx - nv] = 0.5 * (w[a] + w[b])
        uv_edge[idx - nv] = 0.5 * (uv[a] + uv[b])
    f2 = []
    for tri in f:
        a, b, c = tri
        ab = edges[(min(a, b), max(a, b))]
        bc = edges[(min(b, c), max(b, c))]
        ca = edges[(min(c, a), max(c, a))]
        f2 += [[a, ab, ca], [b, bc, ab], [c, ca, bc], [ab, bc, ca]]
    return (
        np.vstack([v_old, v_edge]),
        np.asarray(f2, dtype=np.int64),
        np.vstack([w, w_edge]),
        np.vstack([uv, uv_edge]),
    )


def cap_boundary(v: np.ndarray, f: np.ndarray, w: np.ndarray, uv: np.ndarray, wrist_col: int):
    """Fan-cap every boundary loop (MANO wrist ring) with a centroid vertex
    skinned 100% to the wrist. Winding: boundary edge (a,b) seen as a->b in
    its face -> cap triangle (b,a,center) faces outward."""
    cnt: dict[tuple[int, int], int] = {}
    directed: dict[tuple[int, int], tuple[int, int]] = {}
    for tri in f:
        for i in range(3):
            a, b = tri[i], tri[(i + 1) % 3]
            key = (min(a, b), max(a, b))
            cnt[key] = cnt.get(key, 0) + 1
            directed[key] = (a, b)
    border = [directed[k] for k, c in cnt.items() if c == 1]
    if not border:
        return v, f, w, uv
    # chain loops
    nxt = {a: b for a, b in border}
    loops: list[list[int]] = []
    seen: set[int] = set()
    for a in list(nxt):
        if a in seen:
            continue
        loop = [a]
        seen.add(a)
        cur = nxt.get(a)
        while cur is not None and cur != a and cur not in seen:
            loop.append(cur)
            seen.add(cur)
            cur = nxt.get(cur)
        if len(loop) >= 3:
            loops.append(loop)
    tris = list(f)
    for loop in loops:
        center = len(v)
        cpos = v[loop].mean(axis=0, keepdims=True)
        v = np.vstack([v, cpos])
        wc = np.zeros((1, w.shape[1]))
        wc[0, wrist_col] = 1.0
        w = np.vstack([w, wc])
        uv = np.vstack([uv, uv[loop].mean(axis=0, keepdims=True)])
        for i in range(len(loop)):
            a, b = loop[i], loop[(i + 1) % len(loop)]
            tris.append([b, a, center])
    return v, np.asarray(tris, dtype=np.int64), w, uv


def b64(arr: np.ndarray, dtype) -> str:
    return base64.b64encode(np.ascontiguousarray(arr, dtype=dtype).tobytes()).decode("ascii")


def box_unwrap(v: np.ndarray, f: np.ndarray):
    """Injective UV atlas: dominant-axis bucket (6) -> edge-connected components
    -> per-component planar projection -> shelf pack. Returns (uv, vmap, f2)
    where vmap[i] = source vertex of output vertex i (seam verts duplicated)
    and f2 indexes the duplicated vertex list."""
    e1 = v[f[:, 1]] - v[f[:, 0]]
    e2 = v[f[:, 2]] - v[f[:, 0]]
    fn = np.cross(e1, e2)
    fnn = fn / np.maximum(np.linalg.norm(fn, axis=1, keepdims=True), 1e-12)
    ax = np.argmax(np.abs(fnn), axis=1)
    island = ax * 2 + (fnn[np.arange(len(f)), ax] < 0)

    # ---- majority smoothing: raw per-face argmax zigzags on curved surfaces
    # (hundreds of sliver components -> pad/shelf waste ate 80% of the atlas).
    # Reassign each face to its edge-neighbors' majority island, gated on the
    # target axis still having slope >= 0.3 (stretch <= 3.3x, fine for noise
    # features evaluated in 3D). 3 rounds converge.
    nbr_faces: list[list[int]] = [[] for _ in range(len(f))]
    edge_owner: dict[tuple[int, int], int] = {}
    for fi, tri in enumerate(f):
        for i in range(3):
            a, b = tri[i], tri[(i + 1) % 3]
            key = (min(a, b), max(a, b))
            if key in edge_owner:
                fj = edge_owner[key]
                nbr_faces[fi].append(fj)
                nbr_faces[fj].append(fi)
            else:
                edge_owner[key] = fi
    def can_join(fi: int, isl: int) -> bool:
        c = float(fnn[fi, isl // 2])
        if abs(c) < 0.3:
            return False  # 目标轴上过陡,拉伸 >3.3x
        sign_needed = -1.0 if isl % 2 else 1.0
        # 号向一致,或近切向(側壁锯齿面,折叠风险低)—— 反向大分量并入会折叠重叠
        return c * sign_needed > 0 or abs(c) < 0.35

    for _ in range(3):
        nxt = island.copy()
        for fi in range(len(f)):
            votes: dict[int, int] = {int(island[fi]): 1}
            for fj in nbr_faces[fi]:
                votes[int(island[fj])] = votes.get(int(island[fj]), 0) + 1
            best = max(votes, key=lambda k: votes[k])
            if best != island[fi] and can_join(fi, best):
                nxt[fi] = best
        island = nxt

    # union-find faces sharing an edge within the same island
    parent = list(range(len(f)))

    def find(a: int) -> int:
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    edge_face: dict[tuple[int, int], int] = {}
    for fi, tri in enumerate(f):
        for i in range(3):
            a, b = tri[i], tri[(i + 1) % 3]
            key = (min(a, b), max(a, b))
            if key in edge_face:
                fj = edge_face[key]
                if island[fi] == island[fj]:
                    ra, rb = find(fi), find(fj)
                    if ra != rb:
                        parent[ra] = rb
            else:
                edge_face[key] = fi
    comp_of = np.array([find(i) for i in range(len(f))])
    # merge components of the same root only if same island (roots already respect it)
    comps = {}
    for fi, root in enumerate(comp_of):
        comps.setdefault(root, []).append(fi)

    uv_axes_of = {0: (1, 2), 1: (0, 2), 2: (0, 1)}
    span = float((v.max(axis=0) - v.min(axis=0)).max())
    pad = 0.008 * span
    boxes = []  # (root, faces, uv2d per corner, w, h)
    for root, faces in comps.items():
        a = ax[faces[0]]
        ua, va = uv_axes_of[a]
        pts = v[f[faces]][:, :, [ua, va]]  # (nf,3,2)
        lo = pts.reshape(-1, 2).min(axis=0)
        pts = pts - lo + pad
        hi = pts.reshape(-1, 2).max(axis=0) + pad
        boxes.append([root, faces, pts, hi[0], hi[1]])
    # shelf pack, tallest first
    boxes.sort(key=lambda b: -b[4])
    strip_w = 1.15 * float(np.sqrt(sum(b[3] * b[4] for b in boxes)))
    x = y = row_h = 0.0
    offsets = {}
    for b in boxes:
        if x + b[3] > strip_w and x > 0:
            y += row_h
            x = row_h = 0.0
        offsets[b[0]] = (x, y)
        x += b[3]
        row_h = max(row_h, b[4])
    total_h = y + row_h
    used_w = max(offsets[b[0]][0] + b[3] for b in boxes)
    # 非均匀拉伸填满 [0,1]²(特征在 3D 域求值,纹素长宽比失真无害;
    # 均匀缩放曾留 ~40% 空带,纹素密度白折半)
    sx = 1.0 / used_w
    sy = 1.0 / total_h

    # duplicate vertices per (vertex, component)
    vmap: list[int] = []
    uv_out: list[tuple[float, float]] = []
    f2 = np.empty_like(f)
    inst: dict[tuple[int, int], int] = {}
    for b in boxes:
        root, faces, pts = b[0], b[1], b[2]
        ox, oy = offsets[root]
        for k, fi in enumerate(faces):
            for c in range(3):
                vid = int(f[fi][c])
                key = (vid, root)
                if key not in inst:
                    inst[key] = len(vmap)
                    vmap.append(vid)
                    uv_out.append(((pts[k, c, 0] + ox) * sx, (pts[k, c, 1] + oy) * sy))
                f2[fi][c] = inst[key]
    return np.asarray(uv_out), np.asarray(vmap, dtype=np.int64), f2


def convert(hand: str, raw: bytes, subdiv: bool, mirror: bool = False) -> dict:
    d = load_pkl(raw)
    v = np.asarray(d["v_template"], dtype=np.float64)          # (778,3)
    pd = np.asarray(d["posedirs"], dtype=np.float64)           # (778,3,135) 姿态修正场
    assert pd.shape == (778, 3, 135), pd.shape
    if mirror:  # left = exact mirror of RIGHT across x=0 (strict L/R symmetry)
        v = v.copy()
        v[:, 0] *= -1.0
        # posedirs 镜像:左位姿 R' = M·R·M ⇒ 系数 (R'−I)_ab = s_a·s_b·(R−I)_ab
        # (s = [−1,1,1]),故 P_L[j,a,b] = s_a·s_b · M · P_R[j,a,b]。不用官方
        # MANO_LEFT 的 posedirs:几何走镜像右手,修正场必须严格自洽。
        s = np.array([-1.0, 1.0, 1.0])
        k = np.arange(135)
        a, b = (k % 9) // 3, k % 3
        sgn = s[a] * s[b]                       # (135,)
        pd = pd * sgn[None, None, :]
        pd = pd.copy()
        pd[:, 0, :] *= -1.0                     # M·P
    f = np.asarray(d["f"], dtype=np.int64)                     # (1538,3)
    w = np.asarray(d["weights"], dtype=np.float64)             # (778,16)
    J = np.asarray(d["J_regressor"], dtype=np.float64) @ v     # (16,3)
    kin = np.asarray(d["kintree_table"], dtype=np.int64)       # (2,16) parent row 0
    parent = kin[0].copy()
    parent[0] = -1
    assert v.shape == (778, 3) and w.shape == (778, 16) and J.shape == (16, 3), (v.shape, w.shape, J.shape)

    # ---- finger chains from kintree (each: [base, mid, dist] joint ids) ----
    roots = [j for j in range(1, 16) if parent[j] == 0]
    assert len(roots) == 5, roots
    chains = []
    for r in roots:
        chain = [r]
        while True:
            kids = [j for j in range(16) if parent[j] == chain[-1]]
            if not kids:
                break
            assert len(kids) == 1, kids
            chain.append(kids[0])
        assert len(chain) == 3, chain
        chains.append(chain)

    # ---- assign chains to fingers geometrically ----
    wrist = J[0]
    thumb_chain = min(chains, key=lambda c: np.linalg.norm(J[c[0]] - wrist))
    rest = [c for c in chains if c is not thumb_chain]
    mcps = np.array([J[c[0]] for c in rest])
    fwd = mcps.mean(axis=0) - wrist
    fwd /= np.linalg.norm(fwd)
    # lateral axis = dominant spread of the four MCPs perpendicular to fwd
    centered = mcps - mcps.mean(axis=0)
    centered -= np.outer(centered @ fwd, fwd)
    _, _, vt = np.linalg.svd(centered)
    lat = vt[0]
    order = sorted(range(4), key=lambda i: float(mcps[i] @ lat))
    # index end = the end whose MCP is closer to the thumb base
    tb = J[thumb_chain[0]]
    if np.linalg.norm(mcps[order[-1]] - tb) < np.linalg.norm(mcps[order[0]] - tb):
        order = order[::-1]
    finger_chains = {
        "thumb": thumb_chain,
        "index": rest[order[0]],
        "middle": rest[order[1]],
        "ring": rest[order[2]],
        "pinky": rest[order[3]],
    }
    std = {"index": [1, 2, 3], "middle": [4, 5, 6], "pinky": [7, 8, 9], "ring": [10, 11, 12], "thumb": [13, 14, 15]}
    if any(finger_chains[k] != std[k] for k in std):
        print(f"[convert-mano] note: {hand} joint order differs from standard MANO layout: {finger_chains}")

    # ---- close wrist, subdivide ----
    # posedirs 以列拼进 w 一起过管线:封腕心行自动置 0(cap 只给 wrist 列 1),
    # 细分边点自动取端点均值 —— 与几何同一插值算子,免重写重采样。
    w = np.hstack([w, pd.reshape(778, -1)])     # (778, 16+405)
    uv_axes = np.argsort(v.max(axis=0) - v.min(axis=0))[::-1][:2]
    span = float((v.max(axis=0) - v.min(axis=0))[uv_axes[0]])
    uv = v[:, uv_axes] / span * 4.0
    v, f, w, uv = cap_boundary(v, f, w, uv, wrist_col=0)
    # 封盖后网格闭合 → 符号体积可判外向绕向;负体积 = 面片朝内(左右手资产
    # 绕向不可信),整体翻转,否则 three 正面剔除下渲成 inside-out。
    vol = float(np.einsum("ij,ij->", v[f[:, 0]], np.cross(v[f[:, 1]], v[f[:, 2]]))) / 6.0
    if vol < 0:
        print(f"[convert-mano] {hand}: negative signed volume ({vol:.2e}) — flipping winding")
        f = f[:, ::-1].copy()
    if subdiv:
        v, f, w, uv = loop_subdivide(v, f, w, uv)
    pd = w[:, 16:].reshape(len(v), 3, 135)      # 重采样后的 posedirs
    w = w[:, :16]

    # ---- synthesized joints: metacarpals + tips ----
    bones: list[dict] = [{"name": "wrist", "pos": J[0].tolist()}]
    bone_col: list[int | None] = [0]  # which weights column feeds this bone (None = synthetic)
    for name in WEBXR_FINGERS:
        c = finger_chains[name]
        if name == "thumb":
            chain_names = ["thumb-metacarpal", "thumb-phalanx-proximal", "thumb-phalanx-distal"]
        else:
            meta_pos = J[0] + 0.22 * (J[c[0]] - J[0])
            bones.append({"name": f"{name}-finger-metacarpal", "pos": meta_pos.tolist()})
            bone_col.append(None)
            chain_names = [f"{name}-finger-phalanx-proximal", f"{name}-finger-phalanx-intermediate", f"{name}-finger-phalanx-distal"]
        for jid, jn in zip(c, chain_names):
            bones.append({"name": jn, "pos": J[jid].tolist()})
            bone_col.append(jid)
        # tip = farthest distal-weighted skin vertex along the distal bone axis
        dist_j = c[2]
        axis = J[dist_j] - J[c[1]]
        axis /= np.linalg.norm(axis)
        cand = np.where(w[:, dist_j] > 0.5)[0]
        if len(cand) == 0:
            cand = np.argsort(w[:, dist_j])[-30:]
        proj = (v[cand] - J[dist_j]) @ axis
        tip_pos = v[cand[int(np.argmax(proj))]]
        bones.append({"name": f"{name}{'' if name == 'thumb' else '-finger'}-tip", "pos": tip_pos.tolist()})
        bone_col.append(None)
    assert len(bones) == 25, len(bones)
    names = [b["name"] for b in bones]
    assert len(set(names)) == 25

    # ---- weights: MANO 16 columns -> top-4 over the 25-bone list ----
    col_to_bone = {}
    for bi, col in enumerate(bone_col):
        if col is not None:
            col_to_bone[col] = bi
    assert len(col_to_bone) == 16
    n = len(v)
    sk_i = np.zeros((n, 4), dtype=np.uint8)
    sk_w = np.zeros((n, 4), dtype=np.float64)
    top = np.argsort(w, axis=1)[:, ::-1][:, :4]
    for i in range(n):
        ws = w[i, top[i]]
        s = ws.sum()
        if s <= 0:
            sk_i[i, 0] = col_to_bone[0]
            sk_w[i, 0] = 1.0
            continue
        for k in range(4):
            sk_i[i, k] = col_to_bone[int(top[i, k])]
            sk_w[i, k] = ws[k] / s

    # ---- smooth normals (area-weighted, BEFORE seam duplication) ----
    fn = np.cross(v[f[:, 1]] - v[f[:, 0]], v[f[:, 2]] - v[f[:, 0]])
    nrm = np.zeros_like(v)
    for k in range(3):
        np.add.at(nrm, f[:, k], fn)
    nrm /= np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True), 1e-12)

    # ---- injective UV atlas + seam vertex duplication ----
    uv2, vmap, f2 = box_unwrap(v, f)
    v2 = v[vmap]
    nrm2 = nrm[vmap]
    sk_i2 = sk_i[vmap]
    sk_w2 = sk_w[vmap]
    pd2 = pd[vmap]                              # (n2,3,135)
    n2 = len(v2)

    # posedirs int8 量化(逐系数尺度):修正位移 ~毫米级,int8 精度 <1% 足够;
    # 全量 float32 会把资产撑到 ~9MB。
    pd_scale = np.maximum(np.abs(pd2).max(axis=(0, 1)), 1e-9) / 127.0   # (135,)
    pd_q = np.clip(np.round(pd2 / pd_scale[None, None, :]), -127, 127)

    print(f"[convert-mano] {hand}: verts {n}->{n2} (uv seams) faces {len(f)} bones 25"
          f" | wrist {np.round(J[0], 4).tolist()} middle-tip reach {np.linalg.norm(v[np.argmax(np.linalg.norm(v - J[0], axis=1))] - J[0]):.4f} m")
    return {
        "format": "cuberoot-mano-hand@3",
        "hand": hand,
        "counts": {"verts": n2, "faces": int(len(f2))},
        "bones": bones,
        "position": b64(v2, np.float32),
        "normal": b64(nrm2, np.float32),
        "index": b64(f2, np.uint32),
        "uv": b64(uv2, np.float32),
        "skinIndex": b64(sk_i2, np.uint8),
        "skinWeight": b64(sk_w2, np.float32),
        # MANO 姿态修正 blendshape(LBS 之外的另一半模型 —— 鱼际隆起/关节
        # 鼓包全靠它;丢了它拇指对掌时鱼际瘪成空壳,2026-07-11 用户抓的)。
        # 布局 (n,3,135) C 序;系数 k=(j−1)·9+a·3+b 对应关节 j 局部旋转
        # (R−I)_ab,关节序 = MANO 标准 kintree(index/middle/pinky/ring/thumb)。
        "posedirs": b64(pd_q, np.int8),
        "posedirsScale": b64(pd_scale, np.float32),
    }


# ---------------------------------------------------------------- SMPL-X
# Standard SMPL-X joint layout (fixed in the released model; smplx codebase).
SMPLX_J = {"right_elbow": 19, "right_wrist": 21, "right_index1": 40, "right_pinky1": 46}

# Rig-unit calibration (handModel.buildForearm procedural tube, U space):
# wrist-end y half-width 34.5U (matched to the hand stump), tip reach -186U
# (embedded in the cuff, which covers [-188U,-124U]), overlap +25U past the
# wrist into the hand interior (hides the junction inside the hand mesh).
FOREARM_HALFY_U = 34.5
FOREARM_LEN_U = 186.0
FOREARM_OVL_U = 25.0


def load_smplx(src: Path) -> dict | None:
    """SMPLX_NEUTRAL.npz (loose, models/smplx/, or inside models_smplx_v1_1.zip).
    Returns every model tensor — the forearm piece only needs geometry, but a
    future full-body mode reuses this loader as-is. None if not present."""
    def pick(z) -> dict:
        keys = ("v_template", "f", "weights", "J_regressor", "kintree_table", "posedirs")
        return {k: np.asarray(z[k]) for k in keys}

    for cand in (src, src / "models" / "smplx", src / "models"):
        if cand.is_dir():
            for p in cand.glob("*.npz"):
                if p.name.upper() == "SMPLX_NEUTRAL.NPZ":
                    return pick(np.load(p))
    if src.is_dir():
        for zp in sorted(src.glob("*.zip")):
            with zipfile.ZipFile(zp) as z:
                for info in z.infolist():
                    if Path(info.filename).name.upper() == "SMPLX_NEUTRAL.NPZ":
                        return pick(np.load(io.BytesIO(z.read(info))))
    return None


def convert_smplx_forearm(d: dict, subdiv: bool) -> dict:
    v = np.asarray(d["v_template"], dtype=np.float64)       # (10475,3) m, T-pose
    f = np.asarray(d["f"], dtype=np.int64)                  # (20908,3)
    J = np.asarray(d["J_regressor"], dtype=np.float64) @ v  # (55,3)
    jw, je = J[SMPLX_J["right_wrist"]], J[SMPLX_J["right_elbow"]]

    # Forearm-group frame (rig contract, handsRig forearm IK): origin = wrist,
    # +x = elbow->wrist, +z = palm normal, +y = z×x. Derived from joints, not
    # hardcoded axes — robust to the template's exact T-pose arm direction.
    xg = jw - je
    xg /= np.linalg.norm(xg)
    idx1 = J[SMPLX_J["right_index1"]] - jw
    pnk1 = J[SMPLX_J["right_pinky1"]] - jw
    zg = np.cross(idx1, pnk1)  # right hand: index×pinky points out of the palm
    zg -= (zg @ xg) * xg
    zg /= np.linalg.norm(zg)
    yg = np.cross(zg, xg)
    p = (v - jw) @ np.stack([xg, yg, zg], axis=1)           # (10475,3) local

    # Wrist ring half-width sets the meters->U scale; cut lengths follow so the
    # scaled piece lands on the procedural tube's calibrated envelope.
    ring = p[np.abs(p[:, 0]) < 0.006]
    assert len(ring) > 8, len(ring)
    half_y = float(ring[:, 1].max() - ring[:, 1].min()) / 2.0
    cut_len = FOREARM_LEN_U / FOREARM_HALFY_U * half_y
    ovl = FOREARM_OVL_U / FOREARM_HALFY_U * half_y

    keep = (p[:, 0] > -cut_len) & (p[:, 0] < ovl)
    fsel = f[keep[f].all(axis=1)]
    assert len(fsel) > 100, len(fsel)
    # largest vertex-connected component (guards against stray slab islands)
    parent: dict[int, int] = {}

    def find(a: int) -> int:
        parent.setdefault(a, a)
        while parent[a] != a:
            parent[a] = parent.setdefault(parent[a], parent[a])
            a = parent[a]
        return a

    for tri in fsel:
        ra = find(int(tri[0]))
        for b in (int(tri[1]), int(tri[2])):
            rb = find(b)
            if ra != rb:
                parent[rb] = ra
                ra = find(ra)
    comps: dict[int, list[int]] = {}
    for fi, tri in enumerate(fsel):
        comps.setdefault(find(int(tri[0])), []).append(fi)
    fsel = fsel[max(comps.values(), key=len)]

    used = np.unique(fsel)
    remap = np.full(len(p), -1, dtype=np.int64)
    remap[used] = np.arange(len(used))
    v2 = p[used]
    f2 = remap[fsel]

    # cap both open rings (elbow end / palm end; both hidden but capping stops
    # see-through at glancing angles), fix winding, subdivide — all via the
    # MANO operators (dummy weights/uv columns, unused downstream).
    w2 = np.ones((len(v2), 1))
    uv0 = np.zeros((len(v2), 2))
    v2, f2, w2, uv0 = cap_boundary(v2, f2, w2, uv0, wrist_col=0)
    vol = float(np.einsum("ij,ij->", v2[f2[:, 0]], np.cross(v2[f2[:, 1]], v2[f2[:, 2]]))) / 6.0
    if vol < 0:
        print(f"[convert-mano] smplx forearm: negative signed volume ({vol:.2e}) — flipping winding")
        f2 = f2[:, ::-1].copy()
    if subdiv:
        # two steps: the SMPL-X body mesh is coarse in the forearm (~190 raw
        # verts here vs 778 for a whole MANO hand) — one step still silhouettes.
        for _ in range(2):
            v2, f2, w2, uv0 = loop_subdivide(v2, f2, w2, uv0)

    fn = np.cross(v2[f2[:, 1]] - v2[f2[:, 0]], v2[f2[:, 2]] - v2[f2[:, 0]])
    nrm = np.zeros_like(v2)
    for k in range(3):
        np.add.at(nrm, f2[:, k], fn)
    nrm /= np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True), 1e-12)

    uv2, vmap, f3 = box_unwrap(v2, f2)
    v3 = v2[vmap]
    nrm3 = nrm[vmap]

    print(f"[convert-mano] smplx forearm: verts {len(v2)}->{len(v3)} (uv seams) faces {len(f3)}"
          f" | wrist halfY {half_y * 1000:.1f} mm, x [{v3[:, 0].min():+.3f},{v3[:, 0].max():+.3f}] m")
    return {
        "format": "cuberoot-smplx-forearm@1",
        "hand": "right",
        "counts": {"verts": len(v3), "faces": int(len(f3))},
        "position": b64(v3, np.float32),
        "normal": b64(nrm3, np.float32),
        "index": b64(f3, np.uint32),
        "uv": b64(uv2, np.float32),
        "wristHalfY": half_y,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="D:/cube/mano")
    ap.add_argument("--no-subdiv", action="store_true")
    args = ap.parse_args()
    raw = find_source(Path(args.src))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for hand in ("right", "left"):
        data = convert(hand, raw, subdiv=not args.no_subdiv, mirror=hand == "left")
        out = OUT_DIR / f"{hand}.mano.json"
        out.write_text(json.dumps(data), encoding="utf-8")
        print(f"[convert-mano] wrote {out} ({out.stat().st_size / 1024:.0f} KB)")
    sx = load_smplx(Path(args.src))
    if sx is None:
        print("[convert-mano] no SMPLX_NEUTRAL.npz under --src — skipping real-forearm piece (procedural tube remains)")
        return
    SMPLX_OUT_DIR.mkdir(parents=True, exist_ok=True)
    data = convert_smplx_forearm(sx, subdiv=not args.no_subdiv)
    out = SMPLX_OUT_DIR / "forearm.smplx.json"
    out.write_text(json.dumps(data), encoding="utf-8")
    print(f"[convert-mano] wrote {out} ({out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
