# /// script
# requires-python = ">=3.10"
# dependencies = ["numpy>=1.26", "scipy>=1.11"]
# ///
"""
MANO pkl -> web hand asset (JSON + base64 buffers) for /sim hands.

Usage (uv, per global convention):
  uv run core/packages/client/scripts/convert-mano.py [--src D:/cube/mano] [--no-subdiv]

Input:  MANO_RIGHT.pkl (searched under --src, its models/ subdir, or inside
        mano_v1_2.zip found there). This is the licensed MPI file the user
        downloads from https://mano.is.tue.mpg.de after registration — NEVER
        commit it or the converted output (repo is public; MANO license
        forbids redistribution). Output dir is gitignored.
        The LEFT asset is generated by mirroring RIGHT across x=0. The shipped
        MANO_LEFT template is itself a bit-exact mirror of RIGHT (verified
        2026-07-11: max vert/joint/weight diff 0.0) — mirroring in-converter
        just drops the second pkl and keeps L/R symmetry true by construction.
        (An earlier "left template is asymmetric" diagnosis was wrong: the
        measured fGap difference came from a wrist-anchor offset bug in
        homeLeft, since fixed — see handPoses.ts homeLeft mano branch.)
Output: core/packages/client/public/sim/hands/mano/{right,left}.mano.json

Since @4 SMPLX_NEUTRAL.npz is REQUIRED: the real forearm (cut from the SMPL-X
        body, scale-matched by each template's own middle-finger length) is
        FUSED into the hand mesh at convert time (wrist rings zip-bridged into
        one closed mesh, forearm verts skinned to a new 26th "forearm" bone
        pivoting at the wrist). One mesh = one skinning = one texture bake =
        seamless wrist, matching the upstream single-body look (两件套时代的
        腕缝台阶 / 贴图断层 / stumpFit 单位混用 bug 一并根除,2026-07-11)。
        Also emits smplx/fullbody.smplx.json (debug viewer, raw T-pose body).
        Same license rule as MANO: never commit the npz or converted output.

What it does (bind pose = MANO zero pose, betas = 0):
  1. Unpickle with a chumpy stub (original pkls reference chumpy classes;
     we only need the wrapped ndarrays — no chumpy install, no numpy pin).
  2. joints = J_regressor @ v_template  (16: wrist + 5 fingers x 3).
  3. Identify finger chains geometrically (thumb = chain base closest to
     wrist; index..pinky ordered by lateral position, index on thumb side)
     — robust to MANO's odd index/middle/pinky/ring/thumb joint order.
  4. Synthesize the WebXR joints MANO lacks: four-finger metacarpals
     (wrist + 22% toward MCP, zero skin weight — FK anchors for the rig's
     palm-arch meta channel) and five tips (extremal skin vertex along the
     distal bone axis). Result: the exact 25-name WebXR set, so the
     existing adaptGltfHand() consumes this asset unchanged.
  5. Cap the open wrist ring (fan to centroid, skinned to wrist) so the
     mesh is closed; then one Loop subdivision step (778 -> ~3.1k verts,
     silhouette-smooth; skin weights averaged + renormalized to top-4).
  6. Injective UV atlas via box projection (MANO has no authored UV layout):
     faces bucketed by dominant normal axis (6 directions), split into
     edge-connected components, each component projected onto its axis plane
     and shelf-packed with gutters; seam vertices are duplicated per
     component. This is what lets bakeHandTextures (UV-space rasterization,
     3D-domain feature evaluation) run on MANO — an overlapping projection
     would blend palm/dorsal features into the same texels.
  7. Smooth area-weighted vertex normals exported explicitly (computed
     BEFORE seam duplication — computeVertexNormals on the duplicated mesh
     would produce hard shading seams along every UV island border).
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import pickle
import sys
import zipfile
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]  # core/packages/client/scripts -> repo/core
OUT_DIR = REPO / "packages" / "client" / "public" / "sim" / "hands" / "mano"
SMPLX_OUT_DIR = REPO / "packages" / "client" / "public" / "sim" / "hands" / "smplx"

WEBXR_FINGERS = ["thumb", "index", "middle", "ring", "pinky"]


# ---------------------------------------------------------------- unpickle
class _ChumpyStub:
    """Absorbs any chumpy.* class: keeps the pickled state dict; the wrapped
    ndarray lives under 'x' (Ch) — np.asarray() below digs it out."""

    def __init__(self, *a, **k):
        self.__dict__["_state"] = {}

    def __setstate__(self, state):
        self.__dict__["_state"] = state


class _Unpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module.startswith("chumpy"):
            return _ChumpyStub
        return super().find_class(module, name)


def _to_np(x) -> np.ndarray:
    if isinstance(x, _ChumpyStub):
        st = x.__dict__.get("_state", {})
        if isinstance(st, dict):
            for key in ("x", "a", "_data"):
                if key in st:
                    return _to_np(st[key])
        raise ValueError(f"chumpy stub without array payload: keys={list(st) if isinstance(st, dict) else type(st)}")
    if hasattr(x, "toarray"):  # scipy sparse
        return np.asarray(x.toarray())
    return np.asarray(x)


def load_pkl(raw: bytes) -> dict:
    d = _Unpickler(io.BytesIO(raw), encoding="latin1").load()
    out = {}
    for k in ("v_template", "f", "weights", "J_regressor", "kintree_table", "posedirs"):
        if k not in d:
            raise KeyError(f"MANO pkl missing '{k}' (got keys {sorted(d.keys())})")
        out[k] = _to_np(d[k])
    return out


def find_source(src: Path) -> bytes:
    """Return MANO_RIGHT.pkl bytes from a loose pkl or a zip (left is mirrored)."""
    fname = "MANO_RIGHT.PKL"
    for cand in (src, src / "models", src / "mano_v1_2" / "models"):
        for p in cand.glob("*.pkl") if cand.is_dir() else []:
            if p.name.upper() == fname:
                return p.read_bytes()
    if src.is_dir():
        for zp in sorted(src.glob("*.zip")):
            with zipfile.ZipFile(zp) as z:
                for info in z.infolist():
                    if Path(info.filename).name.upper() == fname:
                        return z.read(info)
    sys.exit(f"[convert-mano] missing MANO_RIGHT.pkl under {src} (loose pkl, models/, or mano_v1_2.zip)")


# ---------------------------------------------------------------- geometry
def loop_subdivide(v: np.ndarray, f: np.ndarray, w: np.ndarray, uv: np.ndarray, pin_boundary: bool = False):
    """One Loop step on a CLOSED triangle mesh. Weights/uv: edge verts = avg
    of endpoints; old verts keep their weights (positions get Loop smoothing).
    pin_boundary: 边界顶点不平滑(开口件预细分用 —— 环缩会把待桥接的切口
    拉离对缝平面)。"""
    nv = len(v)
    edges: dict[tuple[int, int], int] = {}
    opp: dict[tuple[int, int], list[int]] = {}
    for tri in f:
        for i in range(3):
            a, b, c = tri[i], tri[(i + 1) % 3], tri[(i + 2) % 3]
            key = (min(a, b), max(a, b))
            opp.setdefault(key, []).append(c)
    for key in opp:
        edges[key] = nv + len(edges)
    pinned: set[int] = set()
    if pin_boundary:
        for (a, b), os_ in opp.items():
            if len(os_) == 1:
                pinned.add(a)
                pinned.add(b)
    # neighbor sets for old-vertex smoothing
    nbr: list[set[int]] = [set() for _ in range(nv)]
    for (a, b) in opp:
        nbr[a].add(b)
        nbr[b].add(a)
    v_old = np.empty_like(v)
    for i in range(nv):
        n = len(nbr[i])
        if n < 3 or i in pinned:
            v_old[i] = v[i]
            continue
        beta = (5.0 / 8.0 - (3.0 / 8.0 + 0.25 * np.cos(2 * np.pi / n)) ** 2) / n
        v_old[i] = (1 - n * beta) * v[i] + beta * sum(v[j] for j in nbr[i])
    v_edge = np.empty((len(edges), 3))
    w_edge = np.empty((len(edges), w.shape[1]))
    uv_edge = np.empty((len(edges), 2))
    for (a, b), idx in edges.items():
        os_ = opp[(a, b)]
        if len(os_) == 2:
            v_edge[idx - nv] = 3 / 8 * (v[a] + v[b]) + 1 / 8 * (v[os_[0]] + v[os_[1]])
        else:  # boundary edge (shouldn't happen after capping) — midpoint
            v_edge[idx - nv] = 0.5 * (v[a] + v[b])
        w_edge[idx - nv] = 0.5 * (w[a] + w[b])
        uv_edge[idx - nv] = 0.5 * (uv[a] + uv[b])
    f2 = []
    for tri in f:
        a, b, c = tri
        ab = edges[(min(a, b), max(a, b))]
        bc = edges[(min(b, c), max(b, c))]
        ca = edges[(min(c, a), max(c, a))]
        f2 += [[a, ab, ca], [b, bc, ab], [c, ca, bc], [ab, bc, ca]]
    return (
        np.vstack([v_old, v_edge]),
        np.asarray(f2, dtype=np.int64),
        np.vstack([w, w_edge]),
        np.vstack([uv, uv_edge]),
    )


def cap_boundary(v: np.ndarray, f: np.ndarray, w: np.ndarray, uv: np.ndarray, wrist_col: int):
    """Fan-cap every boundary loop (MANO wrist ring) with a centroid vertex
    skinned 100% to the wrist. Winding: boundary edge (a,b) seen as a->b in
    its face -> cap triangle (b,a,center) faces outward."""
    cnt: dict[tuple[int, int], int] = {}
    directed: dict[tuple[int, int], tuple[int, int]] = {}
    for tri in f:
        for i in range(3):
            a, b = tri[i], tri[(i + 1) % 3]
            key = (min(a, b), max(a, b))
            cnt[key] = cnt.get(key, 0) + 1
            directed[key] = (a, b)
    border = [directed[k] for k, c in cnt.items() if c == 1]
    if not border:
        return v, f, w, uv
    # chain loops
    nxt = {a: b for a, b in border}
    loops: list[list[int]] = []
    seen: set[int] = set()
    for a in list(nxt):
        if a in seen:
            continue
        loop = [a]
        seen.add(a)
        cur = nxt.get(a)
        while cur is not None and cur != a and cur not in seen:
            loop.append(cur)
            seen.add(cur)
            cur = nxt.get(cur)
        if len(loop) >= 3:
            loops.append(loop)
    tris = list(f)
    for loop in loops:
        center = len(v)
        cpos = v[loop].mean(axis=0, keepdims=True)
        v = np.vstack([v, cpos])
        wc = np.zeros((1, w.shape[1]))
        wc[0, wrist_col] = 1.0
        w = np.vstack([w, wc])
        uv = np.vstack([uv, uv[loop].mean(axis=0, keepdims=True)])
        for i in range(len(loop)):
            a, b = loop[i], loop[(i + 1) % len(loop)]
            tris.append([b, a, center])
    return v, np.asarray(tris, dtype=np.int64), w, uv


def find_border_loops(f: np.ndarray) -> tuple[list[list[int]], dict[int, int]]:
    """开口环:返回 (环列表[链式有向序], nxt 有向边表)。loop[i]→loop[i+1] 是
    面内朝向的边界边(cap_boundary 同款判定)。"""
    cnt: dict[tuple[int, int], int] = {}
    directed: dict[tuple[int, int], tuple[int, int]] = {}
    for tri in f:
        for i in range(3):
            a, b = int(tri[i]), int(tri[(i + 1) % 3])
            key = (min(a, b), max(a, b))
            cnt[key] = cnt.get(key, 0) + 1
            directed[key] = (a, b)
    border = [directed[k] for k, c in cnt.items() if c == 1]
    nxt = {a: b for a, b in border}
    loops: list[list[int]] = []
    seen: set[int] = set()
    for a in list(nxt):
        if a in seen:
            continue
        loop = [a]
        seen.add(a)
        cur = nxt.get(a)
        while cur is not None and cur != a and cur not in seen:
            loop.append(cur)
            seen.add(cur)
            cur = nxt.get(cur)
        if len(loop) >= 3:
            loops.append(loop)
    return loops, nxt


def zip_rings(idsM: list[int], angM: np.ndarray, nxtM: dict[int, int],
              idsA: list[int], angA: np.ndarray, nxtA: dict[int, int]) -> list[list[int]]:
    """两开口环 zip 桥接(手腕环 ↔ 前臂切口环):按角参数归并推进,逐边出三角。
    朝向规则同 cap_boundary:边界有向边 (a,b) → 桥三角 (b,a,third) 外向 ——
    两侧网格都外向时桥面自动全局一致。ids 须已按角升序,ang 与之对应。"""
    tris: list[list[int]] = []
    nM, nA = len(idsM), len(idsA)

    def orient(u: int, wv: int, third: int, nxt: dict[int, int]) -> list[int]:
        if nxt.get(u) == wv:
            return [wv, u, third]
        assert nxt.get(wv) == u, (u, wv)  # 角序相邻但非链相邻 → 环非星形,须换角心
        return [u, wv, third]

    i = j = 0
    while i < nM or j < nA:
        mNext = angM[(i + 1) % nM] + 2 * np.pi * ((i + 1) // nM) if nM else np.inf
        aNext = angA[(j + 1) % nA] + 2 * np.pi * ((j + 1) // nA) if nA else np.inf
        if j >= nA or (i < nM and mNext <= aNext):
            tris.append(orient(idsM[i % nM], idsM[(i + 1) % nM], idsA[j % nA], nxtM))
            i += 1
        else:
            tris.append(orient(idsA[j % nA], idsA[(j + 1) % nA], idsM[i % nM], nxtA))
            j += 1
    return tris


def validate_closed_manifold(v: np.ndarray, f: np.ndarray, label: str) -> None:
    """融合网格质量闸:闭合(无边界边)+ 二流形(每无向边恰 2 面、方向相反)。"""
    cnt: dict[tuple[int, int], list[tuple[int, int]]] = {}
    for tri in f:
        for i in range(3):
            a, b = int(tri[i]), int(tri[(i + 1) % 3])
            cnt.setdefault((min(a, b), max(a, b)), []).append((a, b))
    bad_open = sum(1 for es in cnt.values() if len(es) == 1)
    bad_multi = sum(1 for es in cnt.values() if len(es) > 2)
    bad_dir = sum(1 for es in cnt.values() if len(es) == 2 and es[0] == es[1])
    assert bad_open == 0 and bad_multi == 0 and bad_dir == 0, (
        f"{label}: open={bad_open} multi={bad_multi} samedir={bad_dir}")


def fuse_smplx_forearm(m: dict, sx: dict) -> dict:
    """SMPL-X 右前臂缝进 MANO 右手模板 → 单一开口网格(唯一开口 = 肘端,后续
    cap_boundary 封盖)。「手臂手一体」的根治:两件套时代腕缝永远可见(几何台
    阶 / 法线断 / 两次分开烘的贴图),且运行时对齐层出过单位混用 bug(stumpFit
    拿米制几何比 rig 单位 WRIST_LOCAL,fit 恒 undefined → 前臂恒走 34.5U 旧回
    退,比 MANO 真腕细 18%,2026-07-11 用户三抓「手臂比手细」的真根因)。

    尺度:两模板各按自身中指链长归一(k = midLen_mano/midLen_smplx),前臂在
    MANO 米制下与手同一标定 —— 上游各自内部比例都保真。蒙皮:前臂顶点挂新增
    forearm 列(16),近腕 30mm 与 wrist(0)线性混合;posedirs 补零。左手由
    调用方对融合结果整体镜像(尺骨头位于小指侧的真前臂不对称随镜像保留)。"""
    v = np.asarray(m["v_template"], dtype=np.float64)       # (778,3)
    f = np.asarray(m["f"], dtype=np.int64)
    w = np.asarray(m["weights"], dtype=np.float64)          # (778,16)
    pd = np.asarray(m["posedirs"], dtype=np.float64)        # (778,3,135)
    J = np.asarray(m["J_regressor"], dtype=np.float64) @ v  # (16,3)
    kin = np.asarray(m["kintree_table"], dtype=np.int64)
    assert v.shape == (778, 3) and pd.shape == (778, 3, 135), (v.shape, pd.shape)

    # ---- MANO 手系(与 SMPL-X 前臂系同构:+x=腕→掌根延伸向,+z=掌法向)----
    wrist = J[0]
    mcps = J[[1, 4, 10, 7]]                                 # index/middle/ring/pinky 近节
    fwd = mcps.mean(axis=0) - wrist
    fwd /= np.linalg.norm(fwd)
    zm = np.cross(J[1] - wrist, J[7] - wrist)               # 食指×小指 → 掌外法向(右手)
    zm -= (zm @ fwd) * fwd
    zm /= np.linalg.norm(zm)
    ym = np.cross(zm, fwd)
    Rm = np.stack([fwd, ym, zm], axis=1)                    # 列基,模板空间

    # ---- 尺度 k:各自中指链长(MCP→PIP→DIP→指尖极值点)归一比 ----
    def midlen(vv: np.ndarray, JJ: np.ndarray, ww: np.ndarray, c: list[int]) -> float:
        axis = JJ[c[2]] - JJ[c[1]]
        axis /= np.linalg.norm(axis)
        cand = np.where(ww[:, c[2]] > 0.5)[0]
        tip = vv[cand[int(np.argmax((vv[cand] - JJ[c[2]]) @ axis))]]
        return float(np.linalg.norm(JJ[c[1]] - JJ[c[0]]) + np.linalg.norm(JJ[c[2]] - JJ[c[1]]) + np.linalg.norm(tip - JJ[c[2]]))

    vx = np.asarray(sx["v_template"], dtype=np.float64)
    fx = np.asarray(sx["f"], dtype=np.int64)
    wx = np.asarray(sx["weights"], dtype=np.float64)
    Jx = np.asarray(sx["J_regressor"], dtype=np.float64) @ vx
    k = midlen(v, J, w, [4, 5, 6]) / midlen(vx, Jx, wx, [43, 44, 45])

    # ---- SMPL-X 前臂局部系(同旧 convert_smplx_forearm)+ 配尺度 ----
    jw, je = Jx[SMPLX_J["right_wrist"]], Jx[SMPLX_J["right_elbow"]]
    xg = jw - je
    xg /= np.linalg.norm(xg)
    idx1 = Jx[SMPLX_J["right_index1"]] - jw
    pnk1 = Jx[SMPLX_J["right_pinky1"]] - jw
    zg = np.cross(idx1, pnk1)
    zg -= (zg @ xg) * xg
    zg /= np.linalg.norm(zg)
    yg = np.cross(zg, xg)
    p = ((vx - jw) @ np.stack([xg, yg, zg], axis=1)) * k    # 局部米制(已配 MANO)

    # ---- MANO 腕环(模板唯一开口)与其平面 ----
    loopsM, nxtM = find_border_loops(f)
    assert len(loopsM) == 1, [len(x) for x in loopsM]
    ringM = loopsM[0]
    ring_local = (v[ringM] - wrist) @ Rm
    x_ring = float(ring_local[:, 0].mean())

    # ---- 切前臂段(腕环平面外 1.5mm 起,向肘 155mm)+ 最大连通片 ----
    GAP, ARM_LEN = 0.0015, 0.155
    keep = (p[:, 0] < x_ring - GAP) & (p[:, 0] > x_ring - ARM_LEN)
    fsel = fx[keep[fx].all(axis=1)]
    assert len(fsel) > 100, len(fsel)
    parent: dict[int, int] = {}

    def find(a: int) -> int:
        parent.setdefault(a, a)
        while parent[a] != a:
            parent[a] = parent.setdefault(parent[a], parent[a])
            a = parent[a]
        return a

    for tri in fsel:
        ra = find(int(tri[0]))
        for b in (int(tri[1]), int(tri[2])):
            rb = find(b)
            if ra != rb:
                parent[rb] = ra
                ra = find(ra)
    comps: dict[int, list[int]] = {}
    for fi, tri in enumerate(fsel):
        comps.setdefault(find(int(tri[0])), []).append(fi)
    fsel = fsel[max(comps.values(), key=len)]
    used = np.unique(fsel)
    remap = np.full(len(p), -1, dtype=np.int64)
    remap[used] = np.arange(len(used))
    pa = p[used]
    fa = remap[fsel]

    # ---- 前臂预细分一次(SMPL-X 体网格在前臂粗;钉死边界防切口环缩)----
    da = np.ones((len(pa), 1))
    ua = np.zeros((len(pa), 2))
    pa, fa, da, ua = loop_subdivide(pa, fa, da, ua, pin_boundary=True)

    loopsA, nxtA = find_border_loops(fa)
    assert len(loopsA) == 2, len(loopsA)
    loopsA.sort(key=lambda L: float(np.mean(pa[L, 0])))
    ringA = loopsA[1]                                       # 腕侧切口

    # ---- 桥接:两环按角参数(手系 y/z,合心)zip ----
    cM = ring_local[:, 1:].mean(axis=0)
    aLoc = pa[ringA][:, 1:]
    cA = aLoc.mean(axis=0)
    c0 = (cM + cA) / 2
    angM_ring = np.arctan2(ring_local[:, 2] - c0[1], ring_local[:, 1] - c0[0])
    oM = np.argsort(angM_ring)
    idsM = [int(np.asarray(ringM)[t]) for t in oM]
    angM = angM_ring[oM]
    angA_ring = np.arctan2(pa[ringA, 2] - c0[1], pa[ringA, 1] - c0[0])
    oA = np.argsort(angA_ring)
    idsA_local = [int(np.asarray(ringA)[t]) for t in oA]
    angA = angA_ring[oA]
    idsA = [778 + t for t in idsA_local]                     # 前臂顶点全局偏移
    nxtA_g = {778 + a: 778 + b for a, b in nxtA.items()}
    bridge = zip_rings(idsM, angM, nxtM, idsA, angA, nxtA_g)

    # ---- 组装:几何 / 面 / 17 列权重 / posedirs 补零 ----
    va = wrist + pa @ Rm.T                                   # 前臂 → 模板空间
    v2 = np.vstack([v, va])
    f2 = np.vstack([f, fa + 778, np.asarray(bridge, dtype=np.int64)])
    validate_closed_manifold_open_elbow(v2, f2)
    wa = np.zeros((len(pa), 17))
    t = np.clip((pa[:, 0] - (x_ring - 0.03)) / 0.03, 0.0, 1.0)  # 近腕 30mm 混腕权
    wa[:, 0] = t
    wa[:, 16] = 1.0 - t
    w17 = np.hstack([w, np.zeros((778, 1))])
    w2 = np.vstack([w17, wa])
    pd2 = np.vstack([pd, np.zeros((len(pa), 3, 135))])
    print(f"[convert-mano] fuse: hand 778 + arm {len(pa)} verts, bridge {len(bridge)} tris, "
          f"k {k:.4f}, x_ring {x_ring * 1000:.1f} mm")
    return {"v": v2, "f": f2, "w": w2, "pd": pd2, "J": J, "kin": kin,
            "forearm_dir": (-fwd).tolist()}


def validate_closed_manifold_open_elbow(v: np.ndarray, f: np.ndarray) -> None:
    """融合后质量闸:恰一个开口环(肘端),其余全流形。"""
    cnt: dict[tuple[int, int], list[tuple[int, int]]] = {}
    for tri in f:
        for i in range(3):
            a, b = int(tri[i]), int(tri[(i + 1) % 3])
            cnt.setdefault((min(a, b), max(a, b)), []).append((a, b))
    open_edges = [es[0] for es in cnt.values() if len(es) == 1]
    bad_multi = sum(1 for es in cnt.values() if len(es) > 2)
    bad_dir = sum(1 for es in cnt.values() if len(es) == 2 and es[0] == es[1])
    assert bad_multi == 0 and bad_dir == 0, f"fuse: multi={bad_multi} samedir={bad_dir}"
    nxt = {a: b for a, b in open_edges}
    loops = 0
    seen: set[int] = set()
    for a in list(nxt):
        if a in seen:
            continue
        loops += 1
        cur: int | None = a
        while cur is not None and cur not in seen:
            seen.add(cur)
            cur = nxt.get(cur)
    assert loops == 1, f"fuse: expected 1 open loop (elbow), got {loops}"


def b64(arr: np.ndarray, dtype) -> str:
    return base64.b64encode(np.ascontiguousarray(arr, dtype=dtype).tobytes()).decode("ascii")


def box_unwrap(v: np.ndarray, f: np.ndarray):
    """Injective UV atlas: dominant-axis bucket (6) -> edge-connected components
    -> per-component planar projection -> shelf pack. Returns (uv, vmap, f2)
    where vmap[i] = source vertex of output vertex i (seam verts duplicated)
    and f2 indexes the duplicated vertex list."""
    e1 = v[f[:, 1]] - v[f[:, 0]]
    e2 = v[f[:, 2]] - v[f[:, 0]]
    fn = np.cross(e1, e2)
    fnn = fn / np.maximum(np.linalg.norm(fn, axis=1, keepdims=True), 1e-12)
    ax = np.argmax(np.abs(fnn), axis=1)
    island = ax * 2 + (fnn[np.arange(len(f)), ax] < 0)

    # ---- majority smoothing: raw per-face argmax zigzags on curved surfaces
    # (hundreds of sliver components -> pad/shelf waste ate 80% of the atlas).
    # Reassign each face to its edge-neighbors' majority island, gated on the
    # target axis still having slope >= 0.3 (stretch <= 3.3x, fine for noise
    # features evaluated in 3D). 3 rounds converge.
    nbr_faces: list[list[int]] = [[] for _ in range(len(f))]
    edge_owner: dict[tuple[int, int], int] = {}
    for fi, tri in enumerate(f):
        for i in range(3):
            a, b = tri[i], tri[(i + 1) % 3]
            key = (min(a, b), max(a, b))
            if key in edge_owner:
                fj = edge_owner[key]
                nbr_faces[fi].append(fj)
                nbr_faces[fj].append(fi)
            else:
                edge_owner[key] = fi
    def can_join(fi: int, isl: int) -> bool:
        c = float(fnn[fi, isl // 2])
        if abs(c) < 0.3:
            return False  # 目标轴上过陡,拉伸 >3.3x
        sign_needed = -1.0 if isl % 2 else 1.0
        # 号向一致,或近切向(側壁锯齿面,折叠风险低)—— 反向大分量并入会折叠重叠
        return c * sign_needed > 0 or abs(c) < 0.35

    for _ in range(3):
        nxt = island.copy()
        for fi in range(len(f)):
            votes: dict[int, int] = {int(island[fi]): 1}
            for fj in nbr_faces[fi]:
                votes[int(island[fj])] = votes.get(int(island[fj]), 0) + 1
            best = max(votes, key=lambda k: votes[k])
            if best != island[fi] and can_join(fi, best):
                nxt[fi] = best
        island = nxt

    # union-find faces sharing an edge within the same island
    parent = list(range(len(f)))

    def find(a: int) -> int:
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    edge_face: dict[tuple[int, int], int] = {}
    for fi, tri in enumerate(f):
        for i in range(3):
            a, b = tri[i], tri[(i + 1) % 3]
            key = (min(a, b), max(a, b))
            if key in edge_face:
                fj = edge_face[key]
                if island[fi] == island[fj]:
                    ra, rb = find(fi), find(fj)
                    if ra != rb:
                        parent[ra] = rb
            else:
                edge_face[key] = fi
    comp_of = np.array([find(i) for i in range(len(f))])
    # merge components of the same root only if same island (roots already respect it)
    comps = {}
    for fi, root in enumerate(comp_of):
        comps.setdefault(root, []).append(fi)

    uv_axes_of = {0: (1, 2), 1: (0, 2), 2: (0, 1)}
    span = float((v.max(axis=0) - v.min(axis=0)).max())
    pad = 0.008 * span
    boxes = []  # (root, faces, uv2d per corner, w, h)
    for root, faces in comps.items():
        a = ax[faces[0]]
        ua, va = uv_axes_of[a]
        pts = v[f[faces]][:, :, [ua, va]]  # (nf,3,2)
        lo = pts.reshape(-1, 2).min(axis=0)
        pts = pts - lo + pad
        hi = pts.reshape(-1, 2).max(axis=0) + pad
        boxes.append([root, faces, pts, hi[0], hi[1]])
    # shelf pack, tallest first
    boxes.sort(key=lambda b: -b[4])
    strip_w = 1.15 * float(np.sqrt(sum(b[3] * b[4] for b in boxes)))
    x = y = row_h = 0.0
    offsets = {}
    for b in boxes:
        if x + b[3] > strip_w and x > 0:
            y += row_h
            x = row_h = 0.0
        offsets[b[0]] = (x, y)
        x += b[3]
        row_h = max(row_h, b[4])
    total_h = y + row_h
    used_w = max(offsets[b[0]][0] + b[3] for b in boxes)
    # 非均匀拉伸填满 [0,1]²(特征在 3D 域求值,纹素长宽比失真无害;
    # 均匀缩放曾留 ~40% 空带,纹素密度白折半)
    sx = 1.0 / used_w
    sy = 1.0 / total_h

    # duplicate vertices per (vertex, component)
    vmap: list[int] = []
    uv_out: list[tuple[float, float]] = []
    f2 = np.empty_like(f)
    inst: dict[tuple[int, int], int] = {}
    for b in boxes:
        root, faces, pts = b[0], b[1], b[2]
        ox, oy = offsets[root]
        for k, fi in enumerate(faces):
            for c in range(3):
                vid = int(f[fi][c])
                key = (vid, root)
                if key not in inst:
                    inst[key] = len(vmap)
                    vmap.append(vid)
                    uv_out.append(((pts[k, c, 0] + ox) * sx, (pts[k, c, 1] + oy) * sy))
                f2[fi][c] = inst[key]
    return np.asarray(uv_out), np.asarray(vmap, dtype=np.int64), f2


def convert(hand: str, fused: dict, subdiv: bool, mirror: bool = False) -> dict:
    """fused = fuse_smplx_forearm() 的单一网格(手 + 前臂,唯一开口 = 肘端)。"""
    v = np.asarray(fused["v"], dtype=np.float64).copy()        # (n,3)
    f = np.asarray(fused["f"], dtype=np.int64).copy()
    w = np.asarray(fused["w"], dtype=np.float64).copy()        # (n,17) 16 MANO + forearm
    pd = np.asarray(fused["pd"], dtype=np.float64).copy()      # (n,3,135) 前臂行全零
    J = np.asarray(fused["J"], dtype=np.float64).copy()        # (16,3)
    fdir = np.asarray(fused["forearm_dir"], dtype=np.float64).copy()
    nf = len(v)
    assert pd.shape == (nf, 3, 135) and w.shape == (nf, 17) and J.shape == (16, 3), (pd.shape, w.shape, J.shape)
    if mirror:  # left = exact mirror of fused RIGHT across x=0 (strict L/R symmetry)
        v[:, 0] *= -1.0
        J[:, 0] *= -1.0
        fdir[0] *= -1.0
        # posedirs 镜像:左位姿 R' = M·R·M ⇒ 系数 (R'−I)_ab = s_a·s_b·(R−I)_ab
        # (s = [−1,1,1]),故 P_L[j,a,b] = s_a·s_b · M · P_R[j,a,b]。不用官方
        # MANO_LEFT 的 posedirs:几何走镜像右手,修正场必须严格自洽。
        s = np.array([-1.0, 1.0, 1.0])
        k = np.arange(135)
        a, b = (k % 9) // 3, k % 3
        sgn = s[a] * s[b]                       # (135,)
        pd = pd * sgn[None, None, :]
        pd = pd.copy()
        pd[:, 0, :] *= -1.0                     # M·P
    kin = np.asarray(fused["kin"], dtype=np.int64)             # (2,16) parent row 0
    parent = kin[0].copy()
    parent[0] = -1

    # ---- finger chains from kintree (each: [base, mid, dist] joint ids) ----
    roots = [j for j in range(1, 16) if parent[j] == 0]
    assert len(roots) == 5, roots
    chains = []
    for r in roots:
        chain = [r]
        while True:
            kids = [j for j in range(16) if parent[j] == chain[-1]]
            if not kids:
                break
            assert len(kids) == 1, kids
            chain.append(kids[0])
        assert len(chain) == 3, chain
        chains.append(chain)

    # ---- assign chains to fingers geometrically ----
    wrist = J[0]
    thumb_chain = min(chains, key=lambda c: np.linalg.norm(J[c[0]] - wrist))
    rest = [c for c in chains if c is not thumb_chain]
    mcps = np.array([J[c[0]] for c in rest])
    fwd = mcps.mean(axis=0) - wrist
    fwd /= np.linalg.norm(fwd)
    # lateral axis = dominant spread of the four MCPs perpendicular to fwd
    centered = mcps - mcps.mean(axis=0)
    centered -= np.outer(centered @ fwd, fwd)
    _, _, vt = np.linalg.svd(centered)
    lat = vt[0]
    order = sorted(range(4), key=lambda i: float(mcps[i] @ lat))
    # index end = the end whose MCP is closer to the thumb base
    tb = J[thumb_chain[0]]
    if np.linalg.norm(mcps[order[-1]] - tb) < np.linalg.norm(mcps[order[0]] - tb):
        order = order[::-1]
    finger_chains = {
        "thumb": thumb_chain,
        "index": rest[order[0]],
        "middle": rest[order[1]],
        "ring": rest[order[2]],
        "pinky": rest[order[3]],
    }
    std = {"index": [1, 2, 3], "middle": [4, 5, 6], "pinky": [7, 8, 9], "ring": [10, 11, 12], "thumb": [13, 14, 15]}
    if any(finger_chains[k] != std[k] for k in std):
        print(f"[convert-mano] note: {hand} joint order differs from standard MANO layout: {finger_chains}")

    # ---- close elbow, subdivide ----
    # posedirs 以列拼进 w 一起过管线:封盖心行自动置 0(cap 只给 forearm 列 1),
    # 细分边点自动取端点均值 —— 与几何同一插值算子,免重写重采样。腕环已在
    # fuse 阶段与前臂桥接,唯一开口 = 肘端断口(袖口遮盖区)。
    w = np.hstack([w, pd.reshape(nf, -1)])      # (n, 17+405)
    uv_axes = np.argsort(v.max(axis=0) - v.min(axis=0))[::-1][:2]
    span = float((v.max(axis=0) - v.min(axis=0))[uv_axes[0]])
    uv = v[:, uv_axes] / span * 4.0
    v, f, w, uv = cap_boundary(v, f, w, uv, wrist_col=16)
    validate_closed_manifold(v, f, f"{hand} fused+capped")
    # 封盖后网格闭合 → 符号体积可判外向绕向;负体积 = 面片朝内(左右手资产
    # 绕向不可信),整体翻转,否则 three 正面剔除下渲成 inside-out。
    vol = float(np.einsum("ij,ij->", v[f[:, 0]], np.cross(v[f[:, 1]], v[f[:, 2]]))) / 6.0
    if vol < 0:
        print(f"[convert-mano] {hand}: negative signed volume ({vol:.2e}) — flipping winding")
        f = f[:, ::-1].copy()
    if subdiv:
        v, f, w, uv = loop_subdivide(v, f, w, uv)
    pd = w[:, 17:].reshape(len(v), 3, 135)      # 重采样后的 posedirs
    w = w[:, :17]

    # ---- synthesized joints: metacarpals + tips ----
    bones: list[dict] = [{"name": "wrist", "pos": J[0].tolist()}]
    bone_col: list[int | None] = [0]  # which weights column feeds this bone (None = synthetic)
    for name in WEBXR_FINGERS:
        c = finger_chains[name]
        if name == "thumb":
            chain_names = ["thumb-metacarpal", "thumb-phalanx-proximal", "thumb-phalanx-distal"]
        else:
            meta_pos = J[0] + 0.22 * (J[c[0]] - J[0])
            bones.append({"name": f"{name}-finger-metacarpal", "pos": meta_pos.tolist()})
            bone_col.append(None)
            chain_names = [f"{name}-finger-phalanx-proximal", f"{name}-finger-phalanx-intermediate", f"{name}-finger-phalanx-distal"]
        for jid, jn in zip(c, chain_names):
            bones.append({"name": jn, "pos": J[jid].tolist()})
            bone_col.append(jid)
        # tip = farthest distal-weighted skin vertex along the distal bone axis
        dist_j = c[2]
        axis = J[dist_j] - J[c[1]]
        axis /= np.linalg.norm(axis)
        cand = np.where(w[:, dist_j] > 0.5)[0]
        if len(cand) == 0:
            cand = np.argsort(w[:, dist_j])[-30:]
        proj = (v[cand] - J[dist_j]) @ axis
        tip_pos = v[cand[int(np.argmax(proj))]]
        bones.append({"name": f"{name}{'' if name == 'thumb' else '-finger'}-tip", "pos": tip_pos.tolist()})
        bone_col.append(None)
    assert len(bones) == 25, len(bones)
    # 前臂骨:轴心 = 腕关节(rig 以腕为支点朝肘锚摆前臂;蒙皮列 16)。
    bones.append({"name": "forearm", "pos": J[0].tolist()})
    bone_col.append(16)
    names = [b["name"] for b in bones]
    assert len(set(names)) == 26

    # ---- weights: 16 MANO + forearm columns -> top-4 over the 26-bone list ----
    col_to_bone = {}
    for bi, col in enumerate(bone_col):
        if col is not None:
            col_to_bone[col] = bi
    assert len(col_to_bone) == 17
    n = len(v)
    sk_i = np.zeros((n, 4), dtype=np.uint8)
    sk_w = np.zeros((n, 4), dtype=np.float64)
    top = np.argsort(w, axis=1)[:, ::-1][:, :4]
    for i in range(n):
        ws = w[i, top[i]]
        s = ws.sum()
        if s <= 0:
            sk_i[i, 0] = col_to_bone[0]
            sk_w[i, 0] = 1.0
            continue
        for k in range(4):
            sk_i[i, k] = col_to_bone[int(top[i, k])]
            sk_w[i, k] = ws[k] / s

    # ---- smooth normals (area-weighted, BEFORE seam duplication) ----
    fn = np.cross(v[f[:, 1]] - v[f[:, 0]], v[f[:, 2]] - v[f[:, 0]])
    nrm = np.zeros_like(v)
    for k in range(3):
        np.add.at(nrm, f[:, k], fn)
    nrm /= np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True), 1e-12)

    # ---- injective UV atlas + seam vertex duplication ----
    uv2, vmap, f2 = box_unwrap(v, f)
    v2 = v[vmap]
    nrm2 = nrm[vmap]
    sk_i2 = sk_i[vmap]
    sk_w2 = sk_w[vmap]
    pd2 = pd[vmap]                              # (n2,3,135)
    n2 = len(v2)

    # posedirs int8 量化(逐系数尺度):修正位移 ~毫米级,int8 精度 <1% 足够;
    # 全量 float32 会把资产撑到 ~9MB。
    pd_scale = np.maximum(np.abs(pd2).max(axis=(0, 1)), 1e-9) / 127.0   # (135,)
    pd_q = np.clip(np.round(pd2 / pd_scale[None, None, :]), -127, 127)

    print(f"[convert-mano] {hand}: verts {n}->{n2} (uv seams) faces {len(f)} bones 26 (hand+forearm fused)"
          f" | wrist {np.round(J[0], 4).tolist()} middle-tip reach {np.linalg.norm(v[np.argmax(np.linalg.norm(v - J[0], axis=1))] - J[0]):.4f} m")
    return {
        "format": "cuberoot-mano-hand@4",
        "hand": hand,
        "counts": {"verts": n2, "faces": int(len(f2))},
        "bones": bones,
        "position": b64(v2, np.float32),
        "normal": b64(nrm2, np.float32),
        "index": b64(f2, np.uint32),
        "uv": b64(uv2, np.float32),
        "skinIndex": b64(sk_i2, np.uint8),
        "skinWeight": b64(sk_w2, np.float32),
        # MANO 姿态修正 blendshape(LBS 之外的另一半模型 —— 鱼际隆起/关节
        # 鼓包全靠它;丢了它拇指对掌时鱼际瘪成空壳,2026-07-11 用户抓的)。
        # 布局 (n,3,135) C 序;系数 k=(j−1)·9+a·3+b 对应关节 j 局部旋转
        # (R−I)_ab,关节序 = MANO 标准 kintree(index/middle/pinky/ring/thumb)。
        "posedirs": b64(pd_q, np.int8),
        "posedirsScale": b64(pd_scale, np.float32),
        # 前臂绑定伸向(腕→肘,资产空间单位向量;左手已镜像)。运行时据此算
        # forearm 骨的摆动旋转(目标 = 肘锚方向)。
        "forearmDir": fdir.tolist(),
    }


# ---------------------------------------------------------------- SMPL-X
# Standard SMPL-X joint layout (fixed in the released model; smplx codebase).
SMPLX_J = {"right_elbow": 19, "right_wrist": 21, "right_index1": 40, "right_pinky1": 46}


def load_smplx(src: Path) -> dict | None:
    """SMPLX_NEUTRAL.npz (loose, models/smplx/, or inside models_smplx_v1_1.zip).
    Returns every model tensor — the forearm piece only needs geometry, but a
    future full-body mode reuses this loader as-is. None if not present."""
    def pick(z) -> dict:
        keys = ("v_template", "f", "weights", "J_regressor", "kintree_table", "posedirs")
        return {k: np.asarray(z[k]) for k in keys}

    for cand in (src, src / "models" / "smplx", src / "models"):
        if cand.is_dir():
            for p in cand.glob("*.npz"):
                if p.name.upper() == "SMPLX_NEUTRAL.NPZ":
                    return pick(np.load(p))
    if src.is_dir():
        for zp in sorted(src.glob("*.zip")):
            with zipfile.ZipFile(zp) as z:
                for info in z.infolist():
                    if Path(info.filename).name.upper() == "SMPLX_NEUTRAL.NPZ":
                        return pick(np.load(io.BytesIO(z.read(info))))
    return None


def convert_smplx_fullbody(d: dict) -> dict:
    """SMPL-X neutral 全身原样导出(米制,T-pose,y-up 面朝 +z):/sim 调试开关
    「SMPL-X 全身」用 —— 核对手/前臂比例的上游解剖真值。不细分不变形:就是
    v_template 本体 + 平滑法线(比例核对要零失真)。同 MANO 授权:产物禁 commit。"""
    v = np.asarray(d["v_template"], dtype=np.float64)       # (10475,3) m
    f = np.asarray(d["f"], dtype=np.int64)                  # (20908,3)
    vol = float(np.einsum("ij,ij->", v[f[:, 0]], np.cross(v[f[:, 1]], v[f[:, 2]]))) / 6.0
    if vol < 0:
        print(f"[convert-mano] smplx fullbody: negative signed volume ({vol:.2e}) — flipping winding")
        f = f[:, ::-1].copy()
    fn = np.cross(v[f[:, 1]] - v[f[:, 0]], v[f[:, 2]] - v[f[:, 0]])
    nrm = np.zeros_like(v)
    for k in range(3):
        np.add.at(nrm, f[:, k], fn)
    nrm /= np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True), 1e-12)
    height = float(v[:, 1].max() - v[:, 1].min())
    print(f"[convert-mano] smplx fullbody: verts {len(v)} faces {len(f)} | height {height:.3f} m")
    return {
        "format": "cuberoot-smplx-fullbody@1",
        "counts": {"verts": len(v), "faces": int(len(f))},
        "position": b64(v, np.float32),
        "normal": b64(nrm, np.float32),
        "index": b64(f, np.uint32),
        "heightM": height,
    }


# SMPL-X 55 关节标准布局里全身层需要的命名下标(smplx codebase 固定)。
SMPLX_BODY_J = {
    "pelvis": 0, "spine1": 3, "spine2": 6, "spine3": 9, "neck": 12, "head": 15,
    "left_collar": 13, "right_collar": 14,
    "left_shoulder": 16, "right_shoulder": 17,
    "left_elbow": 18, "right_elbow": 19,
    "left_wrist": 20, "right_wrist": 21,
}


def convert_smplx_body_rig(d: dict) -> dict:
    """SMPL-X 全身可动 rig(@1,「完整人还原魔方」用):T-pose 本体 + 55 关节
    骨架 + top-4 稀疏蒙皮权重。双臂在「腕内 150mm」半空间切除 —— 前臂+手由 @4
    手资产接管(其前臂从腕向肘伸 155mm,留 ~5mm 套接重叠遮开口;T-pose 双臂沿
    ±x 水平伸出,该半空间恰只含前臂尖+手,躯干/头/腿不受影响)。posedirs 不导
    出:躯干/腿静态站姿(T-pose 即站立)、运行时只做双臂 2 骨 IK,省 ~14MB。
    同 MANO 授权:产物禁 commit。"""
    v = np.asarray(d["v_template"], dtype=np.float64)       # (10475,3) m
    f = np.asarray(d["f"], dtype=np.int64)
    w = np.asarray(d["weights"], dtype=np.float64)          # (10475,55)
    J = np.asarray(d["J_regressor"], dtype=np.float64) @ v  # (55,3)
    kin = np.asarray(d["kintree_table"], dtype=np.int64)
    parents = kin[0].astype(np.int64).copy()
    parents[0] = -1
    # 绕向与 fullbody@1 同一口径(闭合全身网格上判符号,再沿用到切后开口网格)
    vol = float(np.einsum("ij,ij->", v[f[:, 0]], np.cross(v[f[:, 1]], v[f[:, 2]]))) / 6.0
    if vol < 0:
        f = f[:, ::-1].copy()
    keep = np.ones(len(v), dtype=bool)
    CUT = 0.150
    for side in ("left", "right"):
        wj = J[SMPLX_BODY_J[f"{side}_wrist"]]
        ej = J[SMPLX_BODY_J[f"{side}_elbow"]]
        ax = (wj - ej) / np.linalg.norm(wj - ej)
        keep &= (v - wj) @ ax < -CUT
    fsel = f[keep[f].all(axis=1)]
    used = np.unique(fsel)
    remap = np.full(len(v), -1, dtype=np.int64)
    remap[used] = np.arange(len(used))
    vb, fb, wb = v[used], remap[fsel], w[used]
    fn = np.cross(vb[fb[:, 1]] - vb[fb[:, 0]], vb[fb[:, 2]] - vb[fb[:, 0]])
    nrm = np.zeros_like(vb)
    for k3 in range(3):
        np.add.at(nrm, fb[:, k3], fn)
    nrm /= np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True), 1e-12)
    order = np.argsort(-wb, axis=1)[:, :4]                   # top-4 稀疏化
    wt = np.take_along_axis(wb, order, axis=1)
    wt /= np.maximum(wt.sum(axis=1, keepdims=True), 1e-12)
    height = float(v[:, 1].max() - v[:, 1].min())
    print(f"[convert-mano] smplx body-rig: verts {len(vb)}/{len(v)} faces {len(fb)} joints {len(J)} | height {height:.3f} m")
    return {
        "format": "cuberoot-smplx-bodyrig@1",
        "counts": {"verts": len(vb), "faces": int(len(fb)), "joints": int(len(J))},
        "position": b64(vb, np.float32),
        "normal": b64(nrm, np.float32),
        "index": b64(fb, np.uint32),
        "joints": b64(J, np.float32),
        "parents": parents.tolist(),
        "skinIndex": b64(order, np.uint8),
        "skinWeight": b64(wt, np.float32),
        "named": SMPLX_BODY_J,
        "heightM": height,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="D:/cube/mano")
    ap.add_argument("--no-subdiv", action="store_true")
    args = ap.parse_args()
    raw = find_source(Path(args.src))
    sx = load_smplx(Path(args.src))
    if sx is None:
        sys.exit("[convert-mano] SMPLX_NEUTRAL.npz required since @4 (forearm fused into the hand asset) — put models_smplx_v1_1.zip under --src")
    fused = fuse_smplx_forearm(load_pkl(raw), sx)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for hand in ("right", "left"):
        data = convert(hand, fused, subdiv=not args.no_subdiv, mirror=hand == "left")
        out = OUT_DIR / f"{hand}.mano.json"
        out.write_text(json.dumps(data), encoding="utf-8")
        print(f"[convert-mano] wrote {out} ({out.stat().st_size / 1024:.0f} KB)")
    SMPLX_OUT_DIR.mkdir(parents=True, exist_ok=True)
    # 旧两件套时代的独立前臂件已并入手资产,删陈迹防误用
    (SMPLX_OUT_DIR / "forearm.smplx.json").unlink(missing_ok=True)
    data = convert_smplx_fullbody(sx)
    out = SMPLX_OUT_DIR / "fullbody.smplx.json"
    out.write_text(json.dumps(data), encoding="utf-8")
    print(f"[convert-mano] wrote {out} ({out.stat().st_size / 1024:.0f} KB)")
    data = convert_smplx_body_rig(sx)
    out = SMPLX_OUT_DIR / "bodyrig.smplx.json"
    out.write_text(json.dumps(data), encoding="utf-8")
    print(f"[convert-mano] wrote {out} ({out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
