import type { StackTool } from '../_lib/stack_tool_types';
import { v, s, n, f, p, c } from '../_lib/stack_tool_types';

// ─── GitHub ─────────────────────────────────────────────────────────────────

export const GITHUB: StackTool = {
  slug: 'github',
  name: 'GitHub',
  version: '3.20',
  since: '2008-04',
  group: 'dev',
  accent: '#0969DA',
  bright: '#4A9BF0',
  glyph: '◔',
  floats: ['repo', 'fork', 'PR', 'issue', 'label', 'Actions', 'release', 'tag', 'gist', 'star', 'Codespace', 'Copilot'],
  zh: {
    tagline: 'git 之上的社交化 forge + 第一方 CI / AI 协作平台',
    role: '本仓库 RuiminYan/cuberoot.me 的托管处, 也是 deploy / mirror / stats / 健康检查 workflow 的执行环境。',
    heroSub: <>2008 年 4 月 10 日由 Tom Preston-Werner 等四人推出, 把 git 从"命令行底层工具"变成"带 web 前端 + fork/PR 社交工作流"的协作平台。2018 年 6 月 Microsoft 以 <strong>75 亿美元</strong>收购, 此后 Actions / Codespaces / Copilot 一路堆叠, 到 2026 年用户数 <strong>1.5 亿+</strong>、仓库数 <strong>10 亿+</strong>, 几乎是地球开源的默认起点。</>,
    whatDesc: <>GitHub 是 <strong>git 之上的 SaaS forge</strong>:web 前端看 commit / diff、fork + PR 工作流、Issues + Labels 项目管理、Actions YAML CI/CD、Packages 制品仓库、Codespaces 云 IDE、Copilot AI 协作。技术底盘是 git, 商业逻辑是社交图谱 (1.5 亿账号互相 follow / star / contribute), 护城河是这两者的乘积。</>,
    historyDesc: <>从 2008-04-10 Tom Preston-Werner / Chris Wanstrath / PJ Hyett / Scott Chacon 上线第一版, 到 2026 GitHub Enterprise Server 3.20 + Copilot 全面 agentic, 十八年。中间最大几个跳跃:2008 上线 fork/PR 工作流、2018-06 Microsoft 75 亿美元收购、2019-11 Actions GA、2022-06 Copilot 个人版 GA、2023-08 Codespaces GA、2024-04 Copilot Workspace 技术预览、2025 仓库数过 10 亿。</>,
    conceptsTitle: '七层协作抽象',
    conceptsDesc: <>底下是 git, 上面叠了七层概念把"代码托管"变成"协作平台":Repo + Fork (代码物理分布)、PR (代码审查单元)、Issue + Label (任务追踪)、Actions (CI/CD)、Releases + Packages (制品分发)、Codespaces (云 IDE)、Copilot (AI 协作)。每一层都可以单用, 但叠起来才是 GitHub 的网络效应。</>,
    whyDesc: <>2026 年还选 GitHub, 不是因为它"功能最全"或"最便宜" (GitLab / Gitea / Sourcehut 各有所长), 而是因为<strong>网络效应已经锁死</strong>:OSS 默认归宿、第一方 CI 跟 repo 同根、AI agent 第一类目标都是 GitHub URL、1.5 亿用户社交图谱、25k+ Actions Marketplace。换平台的成本远大于忍它的痛点。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>问"谁在用 GitHub"已经没意义。Linux kernel mirror、Microsoft 全栈、Kubernetes、TensorFlow、React、Vue、Rust、Go、Python, 以及大量政府开源 (US Digital Service / 18F / GOV.UK)。Octoverse 2024 报告:5.18 亿仓库、56 亿次贡献、Python 首次成为最常用语言。Mercurial 唯一坚持的 Facebook 2022 年也迁去 Sapling (git 兼容)。</>,
    cuberootDesc: <>本仓库 <code>RuiminYan/cuberoot.me</code> 完全托管在 GitHub, 单一 git 树包 24 工具页 + Hono 服务端 + stats 管道 + nginx vhost。<code>.github/workflows/</code> 下九条 workflow 用 path filter 触发各自的 deploy。GH Pages 走 <code>CNAME=cuberoot.me</code> 做镜像。Issues + Discussions 几乎不用 (个人项目), 但 Releases + tag 是 stats 数据版本锚点。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>Copilot 工作流深度 agentic 化 (Workspace / Coding Agent / 自动修 red PR), 已从 demo 变成主流采用方案。Actions 仍是 OSS 默认 CI, arm64 私库 GA + 全面降价后竞争对手更难追。Codespaces 普及度卡在"个人开发者愿意付月费吗"这道坎, 团队场景普及更快。跟 GitLab / Gitea / Codeberg / Sourcehut 的格局长期稳定:GitHub 占 OSS 默认, 其余各守一块自托管 / 隐私 / 极简 / 非营利的细分。</>,
  },
  en: {
    tagline: 'A social forge on top of git, with first-party CI and AI collaboration',
    role: 'Hosts this repo, RuiminYan/cuberoot.me, and executes the deploy / mirror / stats / healthcheck workflows.',
    heroSub: <>Launched on April 10, 2008 by Tom Preston-Werner and three co-founders. It turned git from "a lower-level CLI tool" into a collaboration platform with a web frontend plus a fork/PR social workflow. Microsoft acquired it in June 2018 for <strong>$7.5B</strong>; Actions, Codespaces, and Copilot stacked on top. By 2026 it carries <strong>150M+ users</strong> and <strong>1B+ repos</strong> — effectively the default starting point for open source.</>,
    whatDesc: <>GitHub is a <strong>SaaS forge built on top of git</strong>: a web frontend for commits and diffs, fork + PR workflow, Issues + Labels for project tracking, Actions YAML CI/CD, Packages for artifact registry, Codespaces for cloud IDEs, Copilot for AI collaboration. The technical foundation is git; the business logic is a social graph (150M accounts following / starring / contributing). The moat is the product of those two.</>,
    historyDesc: <>From April 10, 2008 — Tom Preston-Werner, Chris Wanstrath, PJ Hyett, and Scott Chacon shipping the first version — to GitHub Enterprise Server 3.20 and a fully agentic Copilot in 2026, eighteen years. Major jumps: the launch of the fork/PR workflow (2008), Microsoft's $7.5B acquisition (June 2018), Actions GA (November 2019), Copilot individual GA (June 2022), Codespaces GA (August 2023), Copilot Workspace technical preview (April 2024), and repos passing 1 billion (2025).</>,
    conceptsTitle: 'Seven layers of collaboration',
    conceptsDesc: <>git sits underneath; on top, seven concepts turn "code hosting" into a collaboration platform: Repo + Fork (physical code distribution), PR (review unit), Issue + Label (task tracking), Actions (CI/CD), Releases + Packages (artifact distribution), Codespaces (cloud IDE), Copilot (AI collaboration). Each layer is usable standalone, but stacked they produce GitHub's network effect.</>,
    whyDesc: <>Picking GitHub in 2026 isn't because it has "the most features" or "the lowest price" (GitLab / Gitea / Sourcehut each win on their axes). It's because <strong>the network effect is locked in</strong>: default OSS home, first-party CI sharing one auth model with the repo, AI agents target GitHub URLs first, a 150M-user social graph, 25k+ Actions on the Marketplace. The switching cost dwarfs the pain.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>"Who uses GitHub" is the wrong question. The Linux kernel mirror, all of Microsoft, Kubernetes, TensorFlow, React, Vue, Rust, Go, Python — plus heavy government open source (US Digital Service, 18F, GOV.UK). Octoverse 2024: 518M repos, 5.6B contributions, Python becomes the most-used language for the first time. Even Facebook, the last Mercurial holdout, migrated to Sapling (git-compatible) in 2022.</>,
    cuberootDesc: <>This repo <code>RuiminYan/cuberoot.me</code> lives entirely on GitHub — one git tree carrying 24 tool pages, the Hono server, the stats pipeline, and the nginx vhost. Nine workflows under <code>.github/workflows/</code> are path-filter triggered. GH Pages serves the mirror via <code>CNAME=cuberoot.me</code>. Issues + Discussions stay mostly unused (solo project), but Releases + tags anchor stats data versions.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>Copilot workflows go deeply agentic (Workspace / Coding Agent / auto-fix-the-red-PR) — past demo, now mainstream adoption. Actions remains the OSS default CI; competitors find it harder to catch up after the arm64 private GA and sweeping price cut. Codespaces adoption is gated by "will individual devs pay monthly?" — team scenarios adopt faster. The competitive landscape with GitLab / Gitea / Codeberg / Sourcehut is stable long-term: GitHub holds the OSS default, the rest each hold a self-hosted / privacy / minimalist / non-profit niche.</>,
  },
  heroStats: [
    { num: '150', unit: 'M+', zh: <>注册用户 <em>2025-05 官方披露</em></>, en: <>registered users <em>per GitHub, May 2025</em></> },
    { num: '1', unit: 'B+', zh: <>仓库数过 10 亿 <em>2025-06 GitHub 公告</em></>, en: <>repositories surpassed <em>per GitHub, June 2025</em></> },
    { num: '7.5', unit: 'B$', zh: <>Microsoft 收购对价 <em>2018-06-04 宣布</em></>, en: <>Microsoft acquisition price <em>announced 2018-06-04</em></> },
    { num: '18', unit: 'y', zh: <>自 2008-04-10 上线 <em>OSS 默认归宿</em></>, en: <>since 2008-04-10 launch <em>now the OSS default home</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>GitHub 2008 年 4 月 10 日由 Tom Preston-Werner、Chris Wanstrath、PJ Hyett、Scott Chacon 四人上线。背景是 git 当时刚火三年, 但用 git 协作仍然非常痛苦 —— SSH 公钥得自己折腾、patch 得邮件来回、谁能 push 到哪条 branch 全靠口头约定。GitHub 把这一切包成 web 前端 + fork 模型:不信任你? fork 一份, 你在你的 fork 上改, 改好开 Pull Request, 我 review 完合不合再说。这个工作流一年内吃下了 hg / Bazaar / Mercurial 的市场。</p>
        <p>2008-2018 是公司独立期, 主要做 git web 前端、Issues、Wiki、Pages、Releases 这些 git-周边的协作工具。2018 年 6 月 4 日 Microsoft 宣布以 75 亿美元收购, 10 月 26 日交易完成, Nat Friedman 任 CEO。这个时间节点之后 GitHub 进入"功能爆发期":2019-11 Actions GA、2020-05 Codespaces 宣布、2021-10 OIDC + Reusable workflows、2022-06 Copilot 个人版 GA、2023-08 Codespaces GA、2024-04 Copilot Workspace 技术预览。Microsoft 没有"改造" GitHub 成 Azure 的附庸, 而是把 Azure 的资源 (CI runner / 数据中心 / AI 算力) 拿来当 GitHub 的弹药。这个判断后续几年被证明是对的。</p>
        <p>到 2026 年 GitHub 已是事实上的开源默认归宿:Octoverse 2024 报告 5.18 亿仓库、56 亿次贡献、Python 首次成为最常用语言、生成式 AI 项目 13.7 万个 (同比 98%)。1.5 亿用户的社交图谱、25k+ Actions Marketplace、Copilot 跟 Workspace 的 AI 集成深度, 三者乘起来是其它 forge 短期追不上的护城河。Thomas Dohmke 2021-11 接任 CEO 至 2025 年末, 2026 起 GitHub 进入下一任领导阶段, 战略主线"AI 全流程嵌入" 持续推进。</p>
      </>
    ),
    en: (
      <>
        <p>GitHub launched on April 10, 2008, founded by Tom Preston-Werner, Chris Wanstrath, PJ Hyett, and Scott Chacon. The context: git was only three years old and still painful to collaborate on — fiddling with SSH keys, mailing patches around, and trusting verbal agreements about who could push to what branch. GitHub wrapped all of that in a web frontend plus a fork-based model: don't trust you? Fork a copy, you change your fork, open a Pull Request, I review and decide whether to merge. Within a year that workflow ate the market share of hg, Bazaar, and Mercurial.</p>
        <p>2008-2018 was the independent-company era — git web frontend, Issues, Wiki, Pages, Releases, mostly git-adjacent collaboration tooling. On June 4, 2018, Microsoft announced the $7.5B acquisition; it closed October 26, with Nat Friedman as CEO. The years after that became a feature explosion: Actions GA (November 2019), Codespaces announced (May 2020), OIDC + reusable workflows (October 2021), Copilot individual GA (June 2022), Codespaces GA (August 2023), Copilot Workspace technical preview (April 2024). Microsoft did not "convert" GitHub into an Azure satellite. Instead it routed Azure's resources (CI runners, data centers, AI compute) into GitHub as ammunition. The years since have proven that the right call.</p>
        <p>By 2026 GitHub is the de facto default home of open source. Octoverse 2024: 518M repos, 5.6B contributions, Python becomes the most-used language for the first time, 137k generative AI projects (up 98% YoY). A 150M-user social graph, a 25k+ Actions Marketplace, and the Copilot + Workspace AI integration depth — multiplied together, that is a moat other forges cannot close short-term. Thomas Dohmke ran the company as CEO from November 2021 through the end of 2025; 2026 begins under new leadership, with the strategic spine "AI woven through the entire workflow" continuing.</p>
      </>
    ),
  },
  history: [
    { year: '2008·04', zh: { title: <>四个人在旧金山上线 GitHub</>, desc: <>4 月 10 日 Tom Preston-Werner / Chris Wanstrath / PJ Hyett / Scott Chacon 在旧金山公开 beta。第一版只有 git 托管 + Issue tracker + fork/PR 工作流, 但"fork 一份, 改完发 PR" 这条社交化工作流改写了 OSS 协作。</> }, en: { title: <>Four founders launch GitHub</>, desc: <>April 10: Tom Preston-Werner, Chris Wanstrath, PJ Hyett, and Scott Chacon open the public beta in San Francisco. The first version was just git hosting + an Issue tracker + the fork/PR workflow — but "fork a copy, change it, open a PR" rewrote how OSS collaborates.</> } },
    { year: '2012·04', zh: { title: <>A 轮 — Andreessen Horowitz 1 亿美元</>, desc: <>a16z 领投 1 亿美元, 估值 7.5 亿美元 (当年最大软件公司 A 轮之一)。GitHub 在没融过 seed 的情况下直接 A 轮, 公司四年盈利。</> }, en: { title: <>Series A — $100M from a16z</>, desc: <>Andreessen Horowitz leads a $100M round at a $750M valuation, one of the biggest software Series A rounds at the time. GitHub skipped seed funding entirely and had been profitable for four years.</> } },
    { year: '2015·07', zh: { title: <>B 轮 + 第一个 GitHub Universe</>, desc: <>2.5 亿美元 B 轮, 估值 20 亿美元。同年 10 月在旧金山办首届 GitHub Universe 用户大会, 此后成为 GitHub 每年的产品发布节奏。</> }, en: { title: <>Series B + the first Universe conference</>, desc: <>$250M Series B at a $2B valuation. In October the inaugural GitHub Universe conference is held in San Francisco — it has been GitHub's annual product cadence ever since.</> } },
    { year: '2018·06', zh: { title: <>Microsoft 75 亿美元收购</>, desc: <>6 月 4 日宣布, 10 月 26 日交易完成。Nat Friedman (前 Xamarin CEO) 接任 GitHub CEO。社区当时担忧"被 Microsoft 收编", 后续几年用产品反向证明判断。</> }, en: { title: <>Microsoft acquires for $7.5B</>, desc: <>Announced June 4, closed October 26. Nat Friedman (former Xamarin CEO) becomes GitHub CEO. The community feared Microsoft would absorb GitHub into Azure; subsequent years proved the opposite.</> } },
    { year: '2019·11', zh: { title: <>Actions GA + Packages 上线</>, desc: <>11 月 13 日 GitHub Universe 上 Actions 正式 GA, 同期 GitHub Packages (制品仓库) 上线。"build + 制品 + 发布" 全链路闭环, Travis CI / CircleCI 的 OSS 份额从这一年开始下滑。</> }, en: { title: <>Actions GA + Packages launch</>, desc: <>On November 13 at GitHub Universe, Actions reaches GA; GitHub Packages (artifact registry) launches alongside. "Build → artifact → release" closes in one platform, and Travis CI / CircleCI's OSS share starts declining from this point.</> } },
    { year: '2020·05', zh: { title: <>Codespaces 宣布</>, desc: <>5 月 6 日 GitHub Satellite 上宣布 Codespaces — 浏览器内的 VS Code, 跑在 GitHub 托管的 Linux 容器。"打开 issue 直接调代码"第一次成立, 当时只对部分账号开放预览。</> }, en: { title: <>Codespaces announced</>, desc: <>On May 6 at GitHub Satellite, Codespaces is announced — VS Code in the browser, running on a GitHub-managed Linux container. "Open an issue, start debugging immediately" becomes real for the first time, initially limited to preview access.</> } },
    { year: '2021·06', zh: { title: <>Copilot 技术预览</>, desc: <>Copilot 第一次公开, 基于 OpenAI Codex 模型。VS Code 扩展, 边写边补全, 公开预览即引爆社区, "AI 写代码" 从研究论文变成日常工具。</> }, en: { title: <>Copilot technical preview</>, desc: <>Copilot debuts publicly, built on OpenAI's Codex model. A VS Code extension that completes code as you type, public preview ignites the community. "AI writes code" moves from research papers into daily tooling.</> } },
    { year: '2021·11', zh: { title: <>Thomas Dohmke 接任 CEO</>, desc: <>11 月 15 日 Nat Friedman 离任, Thomas Dohmke (前 GitHub COO) 接任 CEO。Friedman 离开后专注 AI Grant 等独立投资项目。</> }, en: { title: <>Thomas Dohmke becomes CEO</>, desc: <>On November 15, Nat Friedman steps down and Thomas Dohmke (previously GitHub COO) becomes CEO. Friedman moves on to independent investments like AI Grant.</> } },
    { year: '2022·06', zh: { title: <>Copilot 个人版 GA</>, desc: <>6 月 21 日 Copilot 从技术预览转 GA, 个人版 10 美元/月、学生免费。这是第一个达到大规模付费用户的 LLM 应用, 给整个 AI coding 赛道定了起跑线。</> }, en: { title: <>Copilot individual GA</>, desc: <>On June 21, Copilot graduates from technical preview to GA — $10/month for individuals, free for students. The first LLM application to reach paying users at scale, setting the starting line for the whole AI-coding category.</> } },
    { year: '2023·08', zh: { title: <>Codespaces GA</>, desc: <>8 月 9 日 Codespaces 在所有计划下 GA。两核机器每月 60 小时免费, 重型机器按小时付费。"git clone 完才能开始开发" 时代结束。</> }, en: { title: <>Codespaces GA</>, desc: <>On August 9, Codespaces reaches GA across all plans. Free 60 hours/month on 2-core machines, hourly billing for larger ones. The "you can't start until git clone finishes" era ends.</> } },
    { year: '2024·04', zh: { title: <>Copilot Workspace 技术预览</>, desc: <>4 月 29 日 Copilot Workspace 技术预览公开。从"issue → 规划 → 编辑 → PR" 整条链路由 LLM 驱动, "AI 拿 issue 自己干完一个 PR" 第一次有可演示的实现。</> }, en: { title: <>Copilot Workspace technical preview</>, desc: <>On April 29, Copilot Workspace enters technical preview. The full chain — "issue → plan → edit → PR" — runs under LLM orchestration. "An AI takes an issue and ships a PR" gets its first demonstrable implementation.</> } },
    { year: '2024·10', zh: { title: <>Octoverse 2024 — Python #1</>, desc: <>Octoverse 2024:5.18 亿仓库、56 亿次贡献、Python 首次成为最常用语言 (超过 JavaScript)、生成式 AI 项目 13.7 万个同比 98%。开源主力语言十年来第一次换位。</> }, en: { title: <>Octoverse 2024 — Python takes #1</>, desc: <>Octoverse 2024: 518M repos, 5.6B contributions, Python becomes the most-used language for the first time (overtaking JavaScript), 137k generative AI projects (up 98% YoY). The leading OSS language changes for the first time in a decade.</> } },
    { year: '2025·06', zh: { title: <>仓库数过 10 亿</>, desc: <>6 月 GitHub 官方披露仓库数突破 10 亿, 用户数 1.5 亿+。同年 8 月 Thomas Dohmke 宣布年底离任, GitHub 进入第三任 CEO 时代。</> }, en: { title: <>Repositories pass 1 billion</>, desc: <>In June, GitHub announces it has crossed 1 billion repositories; users sit at 150M+. That August, Thomas Dohmke announces he will step down at year-end — GitHub enters its third CEO era.</> } },
    { year: '2026·03', highlight: true, zh: { title: <>Enterprise Server 3.20 / 当前稳定</>, desc: <>3 月 17 日 GitHub Enterprise Server 3.20 GA。同时 Copilot agentic workflow 在企业版完整可用, "PR 自动修红" 从演示变实际工作流, AI 全流程嵌入是这一阶段的主线。</> }, en: { title: <>Enterprise Server 3.20 / current stable</>, desc: <>March 17: GitHub Enterprise Server 3.20 GA. Copilot agentic workflows reach full availability in Enterprise; "auto-fix the red PR" moves from demo to real workflow. Weaving AI through the entire flow is the strategic spine of this era.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>Repo + Fork</>, desc: <>Repo = git 仓库 + 元数据 (描述 / topic / license / star)。Fork = 服务端 git clone, 共享底层 packfile, 创建是 O(1)。fork 后 PR 回上游是 OSS 协作的基本路径。</> }, en: { title: <>Repo + Fork</>, desc: <>A repo is a git tree plus metadata (description, topics, license, stars). A fork is a server-side git clone sharing the underlying packfile — creating one is O(1). Forking then opening a PR back is the standard OSS collaboration path.</> }, code: <code>{p('$')} {f('gh')} repo fork RuiminYan/cuberoot.me {p('--clone')}{'\n'}{v('✓ Created fork yrmfxc/cuberoot.me')}{'\n'}{v('✓ Cloned fork')}</code> },
    { tag: 'B', zh: { title: <>Pull Request</>, desc: <>PR 不是 git 概念, 是 GitHub 在 git branch 之上发明的 review 单元。一条 source branch → target branch 的提案 + 评论 + check 状态 + reviewer 审批 + merge 策略 (merge commit / squash / rebase)。</> }, en: { title: <>Pull Request</>, desc: <>A PR isn't a git concept — it's GitHub's review unit on top of git branches. A proposal from source branch → target branch with comments, check statuses, reviewer approvals, and a merge strategy (merge commit / squash / rebase).</> }, code: <code>{p('$')} {f('gh')} pr create {p('--title')} {s('"feat: add /code/stack/github"')}{'\n'}{p('$')} {f('gh')} pr merge {p('--squash')}{'\n'}{v('✓ Squashed and merged')}</code> },
    { tag: 'C', zh: { title: <>Issues + Labels</>, desc: <>每个 repo 自带 issue tracker, 用 label / milestone / assignee / project 组织。"close #123" commit 消息自动关 issue。比 Jira 之类轻量得多, 但跟代码同源是无可替代的优势。</> }, en: { title: <>Issues + Labels</>, desc: <>Every repo carries an issue tracker organized via labels, milestones, assignees, and projects. A "close #123" in a commit message auto-closes the issue. Far lighter than Jira and similar tools, but co-located with the code — an irreplaceable advantage.</> }, code: <code>{c('// in commit message')}{'\n'}fix(recon): cache write-through{'\n\n'}Closes {p('#')}{v('142')}</code> },
    { tag: 'D', zh: { title: <>Actions — CI/CD 跟 repo 同根</>, desc: <><code>.github/workflows/*.yml</code> 一个普通文件, 事件驱动, GitHub-hosted runner 跑 (公开仓库免费无限分钟, 私库每月 2000 分钟)。Secret / permission / OIDC 全走 GitHub 一套权限模型。</> }, en: { title: <>Actions — CI/CD shares one root with the repo</>, desc: <><code>.github/workflows/*.yml</code> is just a file in the repo, event-driven, executed on GitHub-hosted runners (unlimited minutes free on public repos, 2000/month on private). Secrets, permissions, and OIDC all use GitHub's one auth model.</> }, code: <code>{c('# .github/workflows/test.yml')}{'\n'}{p('on:')} [push, pull_request]{'\n'}{p('jobs:')}{'\n'}  {p('test:')}{'\n'}    {p('runs-on:')} ubuntu-{n('24.04')}{'\n'}    {p('steps:')}{'\n'}      - {p('uses:')} actions/checkout{p('@v4')}</code> },
    { tag: 'E', zh: { title: <>Releases + Packages + Pages</>, desc: <>Release = 一个 git tag + changelog + 可选二进制资产。Packages = npm/cargo/docker/maven 等多语制品仓库, OIDC 短期 token 直接 push。Pages = 仓库静态托管, 本站 GH Pages 镜像走的就是它 + CNAME。</> }, en: { title: <>Releases + Packages + Pages</>, desc: <>Release = one git tag + changelog + optional binary assets. Packages = multi-language artifact registry (npm / cargo / docker / maven), pushed via OIDC short-lived tokens. Pages = static hosting from a repo — this site's GH Pages mirror is Pages + CNAME.</> }, code: <code>{p('$')} {f('gh')} release create v{n('1.0')} {p('--notes')} {s('"first stable"')}{'\n'}{p('$')} {f('gh')} release upload v{n('1.0')} dist.tar.gz</code> },
    { tag: 'F', zh: { title: <>Codespaces — 云 IDE</>, desc: <>每个 repo 可以一键起一个浏览器 VS Code, 跑在 GitHub 托管的容器, <code>.devcontainer/devcontainer.json</code> 描述环境。2 核机每月 60 小时免费。"git clone 完才能开发"的延迟被消掉。</> }, en: { title: <>Codespaces — cloud IDE</>, desc: <>Any repo can launch a browser-based VS Code on a GitHub-managed container — environment is described by <code>.devcontainer/devcontainer.json</code>. Free 60 hours/month on 2-core boxes. The "wait until git clone finishes before you can develop" delay disappears.</> }, code: <code>{c('// .devcontainer/devcontainer.json')}{'\n'}{'{'}{'\n'}  {p('"image"')}: {s('"mcr.microsoft.com/devcontainers/javascript-node:22"')},{'\n'}  {p('"forwardPorts"')}: [{n('5173')}, {n('3001')}]{'\n'}{'}'}</code> },
    { tag: 'G', zh: { title: <>Copilot — AI 协作层</>, desc: <>IDE 内联补全 (Copilot) + 聊天 (Copilot Chat) + agent (Coding Agent / Workspace)。后两者把"读 issue → 改代码 → 开 PR"全链路接入 LLM 上下文, 2026 进入生产可用。</> }, en: { title: <>Copilot — the AI collaboration layer</>, desc: <>IDE inline completion (Copilot), chat (Copilot Chat), agents (Coding Agent / Workspace). The latter two wire the full chain — "read issue → edit code → open PR" — into LLM context. Production-ready by 2026.</> }, code: <code>{c('// in PR description')}{'\n'}@copilot please fix the failing test{'\n'}in tests/recon.spec.ts</code> },
    { tag: 'H', zh: { title: <>Marketplace + Apps</>, desc: <>25k+ 公开 Actions + 数千 GitHub Apps (CI 集成 / 安全扫描 / bot 等)。用 GitHub App 接 webhook 而不是 personal access token, 是 2026 的最佳实践 — 短期 token、细粒度 permission、可撤销。</> }, en: { title: <>Marketplace + Apps</>, desc: <>25k+ public Actions plus thousands of GitHub Apps (CI integrations, security scans, bots, etc.). Wiring a webhook through a GitHub App rather than a personal access token is the 2026 best practice — short-lived tokens, fine-grained permissions, and revocable.</> }, code: <code>{p('$')} {f('gh')} app create {p('--scopes')} contents:read,pull_requests:write{'\n'}{c('// JWT exchanged for short-lived installation token')}</code> },
  ],
  whyCards: [
    { icon: '◔', zh: { title: <>1.5 亿用户社交图谱</>, desc: <>follow / star / contribute 形成的社交图谱在 2026 是 GitHub 最深的护城河。同一份 OSS 项目放到 GitLab 上 star 数会差一个量级, 不是平台问题, 是社交图谱不可迁移。</> }, en: { title: <>A 150M-user social graph</>, desc: <>The graph of follows, stars, and contributions is GitHub's deepest moat in 2026. The same OSS project posted on GitLab gets an order of magnitude fewer stars — not a platform issue, the social graph just isn't transferable.</> }, code: <>{c('// star count drives discovery, drives contributors')}{'\n'}stars → traffic → contributors → stars</> },
    { icon: '◑', zh: { title: <>OSS 默认归宿</>, desc: <>问"在哪开源" 99% 默认 GitHub。npm / cargo / pip / go module / docker buildx 的 git URL 字段全部假设 github.com。"AI agent 进 git repo" 第一个 fixture 都是 GitHub。</> }, en: { title: <>The default OSS home</>, desc: <>"Where should I open source this?" defaults to GitHub 99% of the time. npm, cargo, pip, go modules, docker buildx — every git-URL field assumes github.com. "AI agents working in a git repo" — every first fixture is on GitHub.</> }, code: <>{f('npm')} install {p('github:user/repo')}{'\n'}{f('cargo')} install {p('--git')} https://github.com/...</> },
    { icon: '◐', zh: { title: <>第一方 CI 同根</>, desc: <>Actions 跟 repo 共用同一套权限模型, 没有第二份配置要同步, 没有第二份账号要管。Travis / CircleCI / Jenkins 永远做不到这条 — 它们是外挂, Actions 是内嵌。</> }, en: { title: <>First-party CI, one root</>, desc: <>Actions shares its auth model with the repo — no second config to sync, no second account to administer. Travis / CircleCI / Jenkins can never reach this — they're bolted on; Actions is built in.</> }, code: <>{p('permissions:')}{'\n'}  {p('contents:')} read{'\n'}  {p('id-token:')} write   {c('# OIDC, no stored secret')}</> },
    { icon: '◒', zh: { title: <>AI 集成深度</>, desc: <>Copilot 早 6 个月起跑, 2026 已是 LLM 编程市占第一。Coding Agent / Workspace 把 GitHub 的 issue / PR / Actions 全打进 agent 上下文 — 单独 LLM API 永远拼不出这种集成深度。</> }, en: { title: <>AI integration depth</>, desc: <>Copilot launched six months ahead of competitors; by 2026 it leads LLM-coding market share. Coding Agent and Workspace pull GitHub's issues, PRs, and Actions into agent context — a standalone LLM API cannot assemble that depth on its own.</> }, code: <>{c('// @copilot in issue/PR comment')}{'\n'}@copilot implement spec in design.md{'\n'}{c('// agent reads issue + repo + actions + opens PR')}</> },
    { icon: '◓', zh: { title: <>25k+ Action Marketplace</>, desc: <>想干啥, <code>uses: org/action@v3</code> 一行通常就有现成的:checkout / setup-node / cache / docker buildx / rsync / scp / SSH / S3 sync。生态已成的护城河, 后来者很难追。</> }, en: { title: <>25k+ Actions on the Marketplace</>, desc: <>Almost any task is one <code>uses: org/action@v3</code> away — checkout / setup-node / cache / docker buildx / rsync / scp / ssh / s3 sync. The formed ecosystem is the moat newcomers struggle to close.</> }, code: <>- {p('uses:')} actions/checkout{p('@v4')}{'\n'}- {p('uses:')} pnpm/action-setup{p('@v4')}{'\n'}- {p('uses:')} actions/cache{p('@v4')}</> },
    { icon: '◕', zh: { title: <>免费层够慷慨</>, desc: <>公开仓库无限分钟 Actions、Pages 静态托管不限流量、Codespaces 月 60 小时、Copilot 学生免费。OSS 项目几乎所有基础设施需求免费起步, "试一试" 的门槛被压到 0。</> }, en: { title: <>Generous free tier</>, desc: <>Unlimited Actions minutes on public repos, unmetered traffic on Pages, 60 free Codespaces hours/month, Copilot free for students. OSS projects start with nearly free infrastructure — the cost of "give it a try" is pushed to zero.</> }, code: <>{c('// public repo on GitHub')}{'\n'}{c('// Actions: unlimited minutes')}{'\n'}{c('// Pages: unlimited bandwidth')}{'\n'}{c('// = host this site for $0')}</> },
    { icon: '◖', zh: { title: <>跟 IDE / CLI / API 全打通</>, desc: <>VS Code / JetBrains / Neovim 都有一等公民集成。<code>gh</code> CLI 把 PR / issue / release / workflow / api 全包进一个二进制。REST + GraphQL 双 API + webhooks 让自动化深度任意。</> }, en: { title: <>Wired into every IDE / CLI / API</>, desc: <>VS Code, JetBrains, and Neovim all carry first-class integrations. The <code>gh</code> CLI packs PR / issue / release / workflow / API into one binary. REST + GraphQL + webhooks let automation depth go arbitrarily deep.</> }, code: <>{f('gh')} pr list {p('--state')} open{'\n'}{f('gh')} workflow run deploy_core.yml{'\n'}{f('gh')} api repos/:owner/:repo/issues</> },
    { icon: '◗', zh: { title: <>企业版自托管路径</>, desc: <>GitHub Enterprise Server (本地部署 + 季度新版本) + GitHub Enterprise Cloud (SaaS + SAML SSO + 审计) 两条路。受合规约束的团队不必两难, 同一个 UI / 同一套 API / 同一份知识。</> }, en: { title: <>Enterprise self-hosted path</>, desc: <>GitHub Enterprise Server (on-prem, quarterly releases) + GitHub Enterprise Cloud (SaaS, SAML SSO, audit logs) — two clean paths. Compliance-constrained teams aren't forced to choose: same UI, same API, same shared knowledge.</> }, code: <>{c('// Enterprise Server 3.20 (2026-03)')}{'\n'}{c('// Enterprise Cloud (SaaS)')}{'\n'}{c('// same UI, same gh CLI, same API')}</> },
  ],
  adopters: [
    { name: 'Linux kernel (mirror)', href: 'https://github.com/torvalds/linux', highlight: true, zhNote: 'Linus 自己的镜像仓库, 主开发仍在 git.kernel.org', enNote: 'Linus\'s mirror repository — main development stays on git.kernel.org' },
    { name: 'Microsoft', href: 'https://github.com/microsoft', highlight: true, zhNote: '收购方, VS Code / TypeScript / .NET / PowerShell 全在 GitHub', enNote: 'The acquirer — VS Code / TypeScript / .NET / PowerShell all live on GitHub' },
    { name: 'Kubernetes', href: 'https://github.com/kubernetes/kubernetes', zhNote: 'CNCF 旗舰, 3000+ contributor, 全部走 GitHub PR / Issues', enNote: 'CNCF flagship — 3000+ contributors, entirely on GitHub PRs / Issues' },
    { name: 'TensorFlow / PyTorch', href: 'https://github.com/pytorch/pytorch', zhNote: 'Google 和 Meta 的两大 ML 框架全在 GitHub', enNote: 'Google\'s and Meta\'s two ML frameworks both on GitHub' },
    { name: 'React / Vue / Svelte', href: 'https://github.com/facebook/react', zhNote: '三大前端框架全部 GitHub, npm 包源链回 github URL', enNote: 'The three major frontend frameworks — npm packages link back to GitHub URLs' },
    { name: 'Rust / Go / Python', href: 'https://github.com/rust-lang/rust', zhNote: '三大现代语言, RFC 流程也走 GitHub Issues', enNote: 'Three modern languages — their RFC processes run on GitHub Issues' },
    { name: 'Anthropic Claude Code', href: 'https://github.com/anthropics/claude-code', zhNote: 'AI 编程 agent, 默认 issue/PR 集成在 GitHub', enNote: 'AI coding agent — issue/PR integrations default to GitHub' },
    { name: 'US Digital Service / 18F', href: 'https://github.com/18F', zhNote: '美国政府数字化团队, 开源策略 GitHub 优先', enNote: 'US government digital teams — open-source-first policy, on GitHub' },
    { name: 'GOV.UK', href: 'https://github.com/alphagov', zhNote: '英国政府数字服务, 整套设计系统在 GitHub', enNote: 'UK Government Digital Service — full design system on GitHub' },
    { name: 'Homebrew', href: 'https://github.com/Homebrew', zhNote: 'macOS 包管理器, 几乎所有 formula 都是 GitHub URL', enNote: 'macOS package manager — virtually every formula is a GitHub URL' },
    { name: 'Flutter', href: 'https://github.com/flutter/flutter', zhNote: 'Google 跨平台 UI 框架, 一开始就是 GitHub-first', enNote: 'Google\'s cross-platform UI framework — GitHub-first from day one' },
    { name: 'Sapling (Meta)', href: 'https://github.com/facebook/sapling', zhNote: 'Meta 2022 年从 Mercurial 迁来的 git 兼容 VCS, 自己也在 GitHub', enNote: 'Meta\'s git-compatible VCS replacing Mercurial in 2022 — itself hosted on GitHub' },
    { name: 'cuberoot.me', href: 'https://github.com/RuiminYan/cuberoot.me', highlight: true, zhNote: '本仓库 — 单一 git 树托管 24 工具 + server + ops + 9 条 workflow', enNote: 'This repo — one git tree hosting 24 tools + server + ops + 9 workflows' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>Copilot 进入 agentic 工作流时代</>, body: <><p>Copilot 系列从"边写边补全"进化到"读 issue → 拉日志 → 改代码 → 开 PR" 全链路 agent。2024-04 Workspace 技术预览、2025-2026 Coding Agent 在 GitHub 平台原生可用、企业版 2026 一季度完整开放。"AI 提一个 PR 给我 review" 从 demo 变成日常工作流。</p><p>这对 GitHub 的护城河影响最大 —— Copilot 的训练语料 / 上下文窗口 / Actions 联动深度全部需要 GitHub 平台数据本身, 单独 LLM API 永远做不出同等集成。竞争对手 (GitLab Duo / Sourcegraph Cody / Cursor Background Agent) 在 2026 各有所长, 但深度集成上 GitHub 优势明显。</p></> }, en: { title: <>Copilot enters the agentic-workflow era</>, body: <><p>Copilot evolves from "complete as you type" to a full agent — "read issue → pull logs → edit code → open PR." Workspace's April 2024 technical preview, Coding Agent's 2025-2026 native availability inside GitHub, and full Enterprise availability in Q1 2026 turn "an AI opens a PR for me to review" from demo into daily workflow.</p><p>This hits GitHub's moat hardest in the best way — Copilot's training corpus, context window, and Actions integration depth all require the GitHub platform's own data. A standalone LLM API cannot match the integration. Competitors (GitLab Duo, Sourcegraph Cody, Cursor Background Agent) each hold their corners in 2026, but on integration depth GitHub's advantage is clear.</p></> } },
    { tag: <>HOT</>, hot: true, zh: { title: <>Actions arm64 私库 GA + 全面降价</>, body: <><p>2026-01-29 arm64 standard runner 在私库 GA, 同期定价整体下调最高 39%。"用 ARM 跑 CI" 从公开 OSS 福利变成普适默认, Rust / Go / 容器多架构 build 成本拉低一档。</p><p>这条对 GitHub 跟 GitLab / 自托管 Jenkins 的差距进一步拉开 — 自托管 ARM runner 集群的运维成本不是小数, 把它打成 SaaS 免运维方案是网络效应 + 经济规模的乘积。</p></> }, en: { title: <>Actions arm64 private GA + sweeping price cut</>, body: <><p>On January 29, 2026, arm64 standard runners reach GA on private repos, with pricing cut by up to 39% across SKUs in the same month. "Run CI on ARM" moves from a public-OSS-only perk to a default option, materially lowering the cost of native ARM builds for Rust / Go / multi-arch containers.</p><p>This widens the gap with GitLab and self-hosted Jenkins — operating an ARM runner cluster yourself isn't free, and folding it into a SaaS-with-no-ops offering multiplies network effect by economies of scale.</p></> } },
    { tag: <>AI</>, zh: { title: <>Octoverse:生成式 AI 项目 98% 同比</>, body: <><p>Octoverse 2024:13.7 万生成式 AI 公开项目, 同比 98% 增长;5.6 亿次贡献中 AI 相关项目占近 6% 增量。Python 首次超过 JavaScript 成为最常用语言, 直接原因是 AI / ML 主力语言的爆发。GitHub 既是这一切的承载者, 又是观察者 — Octoverse 报告本身就是平台地位的衍生品。</p></> }, en: { title: <>Octoverse: generative AI projects +98% YoY</>, body: <><p>Octoverse 2024: 137k public generative-AI projects, up 98% YoY; AI-related projects account for nearly 6% of the 5.6B contribution growth. Python overtakes JavaScript as the most-used language for the first time — driven directly by the AI/ML language surge. GitHub is both the substrate and the observer of all of this — the Octoverse report is itself a byproduct of the platform's position.</p></> } },
    { tag: 'FORGE', zh: { title: <>多 forge 格局长期稳定</>, body: <><p>GitLab 守企业自托管 + DevSecOps 一体化, Gitea / Forgejo 守轻量自托管 + 隐私, Codeberg 守非营利, Sourcehut 守 email-driven 极简, Bitbucket 守 Atlassian 生态。2026 这个格局长期稳定, GitHub 不会一统但守住 OSS 默认。每条赛道都有清晰受众, 互不抢饭碗。</p></> }, en: { title: <>The multi-forge landscape stabilizes</>, body: <><p>GitLab holds enterprise self-hosted + DevSecOps unification; Gitea / Forgejo hold lightweight self-hosted + privacy; Codeberg holds non-profit; Sourcehut holds email-driven minimalism; Bitbucket holds the Atlassian ecosystem. By 2026 this layout is stable long-term — GitHub doesn't unify everything but keeps the OSS default. Every track has a clear audience and doesn't poach from the others.</p></> } },
    { tag: 'CEO', zh: { title: <>第三任 CEO 时代开启</>, body: <><p>Thomas Dohmke 2021-11 接任至 2025 年末离任, 任内 Copilot 从技术预览到 LLM 编程市占第一、Codespaces GA、Actions 全面成熟。2026 起 GitHub 进入第三任 CEO 时代, 战略主线"AI 全流程嵌入" 继续推进 — 这条路线在多次内部公开承诺中已经定调, 短期不会重大转向。</p></> }, en: { title: <>The third-CEO era begins</>, body: <><p>Thomas Dohmke served from November 2021 through the end of 2025 — under his tenure Copilot went from technical preview to market leader in LLM coding, Codespaces reached GA, and Actions fully matured. From 2026 GitHub enters its third-CEO era, and the strategic spine "weave AI through the whole workflow" continues — this direction has been publicly committed multiple times internally and won't make a major pivot short-term.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本仓库 <code>RuiminYan/cuberoot.me</code> 完全托管在 GitHub, 自定义域名 <code>cuberoot.me</code> 走 GH Pages CNAME 做境外镜像, 主源是云服务器 nginx 服 <code>cuberoot.me</code> + <code>www.cuberoot.me</code>。一棵 git 树包 24 个工具页 (<code>core/packages/client</code>)、Hono 服务端 (<code>core/packages/server</code>)、stats build 管道 (<code>core/packages/stats-build</code>)、nginx vhost (<code>ops/nginx/</code>)、deploy workflow (<code>.github/workflows/</code>) — 跟站点相关的所有东西 (除 WP blog 外) 都进 GitHub。</p>
        <p>九条 workflow 跑在 <code>.github/workflows/</code>, 全部 path filter 触发:<code>test.yml</code> PR/push 跑 typecheck + vitest, <code>deploy_core.yml</code> push <code>core/**</code> 触发 build SPA + bundle server + rsync 到生产 VM + 同步 GH Pages 镜像, <code>deploy_nginx.yml</code> push <code>ops/nginx/**</code> 触发 scp + <code>nginx -t</code> + reload + 失败 .bak 回滚, <code>stats.yml</code> 每周日重算 WCA 统计 build + scp + <code>load.sql</code>, 还有 deploy_mirror / healthcheck 等几条。所有部署密钥走 GitHub Actions secret, SSH 私钥也存在 secrets 里 (短期来看是合理 tradeoff)。</p>
        <p>GH Pages 镜像走 CNAME=<code>cuberoot.me</code>, 当国内 nginx 出问题时是免运维兜底。Issues + Discussions 几乎不用 (个人项目), 但 <strong>Releases + git tag</strong> 是 stats 数据版本锚点 —— 每次 stats 重 build 自动打 tag, 走 GitHub release notes 写改动。Actions 给的免费 2000 分钟/月私库额度对本仓库够用, 公开仓库无限分钟根本碰不到上限。</p>
        <p>一条已知坑:<strong>push 文件数 {'>'} 300 时 GitHub Actions path filter 偶尔静默失效</strong>, deploy_core / deploy_mirror 不触发。兜底方案是手动 <code>gh workflow run deploy_core.yml</code>, 也已记进项目 memory。<code>gh</code> CLI 在本机 <code>winget install GitHub.cli</code> 装着, 一切 GitHub 操作直接 <code>gh pr / gh release / gh workflow run</code>, 比开 web UI 快。pre-push hook 跑 typecheck (~12s) 在本机拦红 PR, 跟 Actions <code>test.yml</code> 双保险。</p>
      </>
    ),
    en: (
      <>
        <p>This repo <code>RuiminYan/cuberoot.me</code> lives entirely on GitHub. The custom domain <code>cuberoot.me</code> uses a GH Pages CNAME as an out-of-region mirror; the primary source is an nginx server hosting <code>cuberoot.me</code> + <code>www.cuberoot.me</code>. One git tree carries 24 tool pages (<code>core/packages/client</code>), the Hono server (<code>core/packages/server</code>), the stats build pipeline (<code>core/packages/stats-build</code>), the nginx vhost (<code>ops/nginx/</code>), and deploy workflows (<code>.github/workflows/</code>) — everything site-related except the WP blog lives on GitHub.</p>
        <p>Nine workflows under <code>.github/workflows/</code> are all path-filter triggered: <code>test.yml</code> runs typecheck + vitest on PRs and pushes; <code>deploy_core.yml</code> fires on <code>core/**</code> pushes to build the SPA, bundle the server, rsync to the production VM, and sync the GH Pages mirror; <code>deploy_nginx.yml</code> fires on <code>ops/nginx/**</code> for scp + <code>nginx -t</code> + reload + .bak rollback on failure; <code>stats.yml</code> rebuilds WCA stats every Sunday with build + scp + <code>load.sql</code>; plus deploy_mirror / healthcheck and a few more. All deploy keys live in GitHub Actions secrets, including SSH private keys (a reasonable short-term tradeoff).</p>
        <p>The GH Pages mirror uses CNAME=<code>cuberoot.me</code> as a maintenance-free fallback when the primary nginx has issues. Issues and Discussions stay mostly unused (solo project), but <strong>Releases + git tags</strong> anchor stats data versions — every stats rebuild auto-tags and writes change notes through GitHub release notes. The free 2000 Actions minutes/month private-repo quota is enough; the unlimited public-repo minutes are nowhere near the ceiling.</p>
        <p>One known pitfall: <strong>when a push touches more than 300 files, GitHub Actions path filters occasionally fail silently</strong> and deploy_core / deploy_mirror don't trigger. The fallback is a manual <code>gh workflow run deploy_core.yml</code> — already recorded in project memory. The <code>gh</code> CLI is installed locally via <code>winget install GitHub.cli</code>, and every GitHub operation runs through <code>gh pr / gh release / gh workflow run</code> directly — faster than opening the web UI. A pre-push hook runs typecheck (~12s) to catch reds locally; together with the Actions <code>test.yml</code> that's a double safety net.</p>
      </>
    ),
  },
  links: [
    { label: 'github.com', href: 'https://github.com' },
    { label: 'GitHub Docs', href: 'https://docs.github.com' },
    { label: 'Octoverse 2024', href: 'https://github.blog/news-insights/octoverse/octoverse-2024/' },
    { label: 'GitHub Blog', href: 'https://github.blog' },
    { label: 'gh CLI', href: 'https://cli.github.com' },
    { label: 'Enterprise Server release notes', href: 'https://docs.github.com/en/enterprise-server/admin/release-notes' },
  ],
};

export default GITHUB;
