import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, s, n, f, p, c } from '../_lib/stack_tool_types';

// ─── MapLibre GL JS 5.24 ──────────────────────────────────────────────────────

export const MAPLIBRE_GL: StackTool = {
  slug: 'maplibre-gl',
  name: 'MapLibre GL',
  version: '5.24',
  since: '2020-12',
  group: 'frontend',
  accent: '#285DAA',
  bright: '#4F86C6',
  glyph: '◍',
  floats: ['vector tiles', 'WebGL', 'style spec', 'GeoJSON', 'MVT', 'globe', 'tile server', 'addProtocol', 'Source', 'Layer', 'expression', 'glyphs'],
  zh: {
    tagline: '浏览器里渲染矢量地图的开源 WebGL 引擎',
    role: '本站 /wca/comp?view=globe 比赛地球的渲染层。把 WCA 比赛按经纬度铺在一颗矢量地球上。',
    heroSub: <>2020 年 12 月 Mapbox 把 Mapbox GL JS v2 改成专有许可后, 社区从最后一个 BSD 开源版 (v1.13) <strong>硬 fork</strong> 出来, 放进 Linux Foundation 孵化。一份 JSON style spec 描述地图长相, GPU 把矢量瓦片 (MVT) 实时绘成线 / 面 / 文字, 平移缩放旋转全是 60fps。</>,
    whatDesc: <>MapLibre GL JS 是一个 <strong>WebGL 矢量地图渲染库</strong> —— 它不是底图数据, 也不是瓦片服务器, 而是"拿矢量瓦片 + 一份 style 文档, 在 canvas 上用 GPU 画出可交互地图"这一段。和栅格地图 (一张张拼接的 PNG) 不同, 矢量瓦片把几何 + 属性发到客户端, 配色 / 标签 / 路网粗细全部客户端实时算, 因此能无级缩放 / 即时换主题 / 任意旋转倾斜。</>,
    historyDesc: <>从 2020 年 12 月那次 license 变更触发的紧急 fork, 到 2021 年初 1.x 接续开源线, 2023 年 3.0 大重写、2024 年 4.0 全面 TypeScript、2024 年底 5.0 加入真 3D 球面投影 (globe), MapLibre 用四年从"保命 fork"长成"被亚马逊 / Meta / 微软等组成的联盟资助、由选举产生的技术指导委员会治理"的独立项目。</>,
    conceptsTitle: 'Style spec + Source/Layer 核心',
    conceptsDesc: <>API 看着庞杂, 核心其实只有几块:一份 <strong>style spec</strong> (JSON) 描述整张地图; <strong>Source</strong> 是数据来源 (vector / geojson / raster); <strong>Layer</strong> 把某个 source 的某层画成 circle / line / fill / symbol; <strong>expression</strong> 让样式随数据/缩放动态算。其它 (popup / marker / control / 自定义 protocol) 都搭在这上面。</>,
    whyDesc: <>2026 年做 web 地图选 MapLibre, 第一是<strong>开源无锁定</strong> —— BSD 许可、无强制 token、可完全自托管瓦片; 第二是<strong>数据格式标准</strong> —— style spec / MVT 已成事实标准, 一份样式喂 MapLibre / Mapbox / 各家瓦片服务通用; 第三是<strong>治理可信</strong> —— Linux Foundation 下联盟资助, 不会再被某一家公司一纸 license 改翻。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>从各国政府开放地图门户、Wikimedia、AllTrails 户外路线、到 deck.gl 大数据可视化叠层, 凡是"要可交互矢量地图但不想被某厂 token 绑死"的场景, MapLibre 几乎是默认答案。配套的 Martin / pmtiles 让"自己生成 + 自己托管瓦片"变成一条成熟链路。</>,
    cuberootDesc: <>本站 <code>/wca/comp?view=globe</code> 这页的矢量地球就是 MapLibre GL JS 渲染的。upcoming 模式把近期全球比赛聚合成点; cuber 模式按时间顺序画选手生涯的大圆弧足迹; wr 模式按国家做世界纪录 choropleth。地图库本身 ~550KB, 不该拖慢首屏, 所以走 <code>next/dynamic</code> + <code>ssr:false</code> 按需加载 —— 只有用户真的进这页才下载。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>5.x 把真 3D 球面投影 (globe) 推成一等公民, 不再是平面墨卡托近似。MapLibre Tile (MLT) 这种新一代矢量瓦片格式 2026 年初公开, 压缩 / 解码比 MVT 更快。配套生态 (Rust 写的 Martin 瓦片服务、PMTiles 单文件瓦片) 让自托管门槛持续走低, v6 已在开发。</>,
  },
  en: {
    tagline: 'Open-source WebGL engine for vector maps in the browser',
    role: 'The render layer behind the /wca/comp?view=globe competition globe — WCA comps plotted by lat/lng on a vector earth.',
    heroSub: <>After Mapbox relicensed Mapbox GL JS v2 as proprietary in December 2020, the community <strong>hard-forked</strong> the last BSD-licensed release (v1.13) and incubated it at the Linux Foundation. One JSON style spec describes how the map looks; the GPU rasterizes vector tiles (MVT) into lines / fills / labels in real time; pan, zoom, and rotate all run at 60fps.</>,
    whatDesc: <>MapLibre GL JS is a <strong>WebGL vector-map rendering library</strong> — not the basemap data, not the tile server, just the "take vector tiles plus a style document and draw an interactive map on a canvas with the GPU" segment. Unlike raster maps (stitched PNGs), vector tiles ship geometry plus attributes to the client, so colors / labels / road widths are computed client-side, enabling continuous zoom, instant theme swaps, and arbitrary rotation and tilt.</>,
    historyDesc: <>From the emergency fork triggered by the December 2020 license change, through the open-source 1.x continuation in early 2021, the 3.0 rewrite in 2023, the full-TypeScript 4.0 in 2024, and the true 3D globe projection in 5.0 at the end of 2024, MapLibre grew in four years from a survival fork into an independent project funded by a consortium (Amazon, Meta, Microsoft, and others) and governed by an elected technical steering committee.</>,
    conceptsTitle: 'Style spec + Source/Layer core',
    conceptsDesc: <>The surface looks sprawling, but the core is a few pieces: a <strong>style spec</strong> (JSON) describes the whole map; a <strong>Source</strong> is where data comes from (vector / geojson / raster); a <strong>Layer</strong> draws one layer of one source as circle / line / fill / symbol; <strong>expressions</strong> make styling react to data and zoom. Popups, markers, controls, and custom protocols all stack on top.</>,
    whyDesc: <>Picking MapLibre for web maps in 2026 comes down to three things: <strong>open and lock-in-free</strong> — BSD license, no mandatory token, fully self-hostable tiles; <strong>standard data formats</strong> — style spec / MVT are de facto standards, one style feeds MapLibre / Mapbox / any tile service; and <strong>trustworthy governance</strong> — funded by a Linux Foundation consortium, never again flipped by a single company's license change.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>From national open-map portals to Wikimedia, AllTrails outdoor routes, and deck.gl big-data visualization overlays — anywhere you need interactive vector maps without being bound to one vendor's token, MapLibre is close to the default answer. Companion tools like Martin and PMTiles turn "generate and self-host your own tiles" into a mature path.</>,
    cuberootDesc: <>The vector globe on this site's <code>/wca/comp?view=globe</code> page is rendered by MapLibre GL JS. The upcoming mode clusters near-term competitions worldwide into points; the cuber mode draws a competitor's career as great-circle arcs in chronological order; the wr mode is a per-country world-record choropleth. The map library itself is ~550KB and should not slow down first paint, so it loads on demand via <code>next/dynamic</code> + <code>ssr:false</code> — downloaded only when the user actually navigates here.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>5.x promotes a true 3D globe projection to first-class status, no longer a flat Mercator approximation. The MapLibre Tile (MLT) format, a next-gen vector tile spec announced in early 2026, compresses and decodes faster than MVT. Companion tooling (the Rust-based Martin tile server, single-file PMTiles) keeps lowering the self-hosting bar, and v6 is already in development.</>,
  },
  heroStats: [
    { num: '5', unit: '.24', zh: <>当前稳定版 <em>2026 · npm maplibre-gl 5.24.0</em></>, en: <>current stable <em>2026 · npm maplibre-gl 5.24.0</em></> },
    { num: 'v1', unit: '.13', zh: <>fork 自此版本 <em>Mapbox GL JS 最后 BSD 开源版</em></>, en: <>forked from this version <em>last BSD-licensed Mapbox GL JS</em></> },
    { num: '0', unit: 'token', zh: <>无强制 API key <em>瓦片可完全自托管</em></>, en: <>no mandatory API key <em>tiles fully self-hostable</em></> },
    { num: 'LF', zh: <>Linux Foundation 孵化 <em>选举产生的技术指导委员会治理</em></>, en: <>Linux Foundation incubated <em>elected technical steering committee</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>MapLibre GL JS 的起点是一次 license 危机。2020 年 12 月, Mapbox 发布 Mapbox GL JS v2, 同时把许可从开源 (BSD) 改成专有 —— 旧版免费、可自由 fork 的代码, 在 v2 起变成必须有 Mapbox 账号 / token、按用量计费。对依赖它做矢量地图的整个 web 生态, 这是釜底抽薪。</p>
        <p>社区反应极快。几乎在 Mapbox 宣布的当周, 就有多个 fork 出现, 随后大家合流, 决定共同维护并继续开发<strong>最后一个开源版本</strong> —— Mapbox GL JS v1.13 (BSD 许可)。这个 hard fork 取名 MapLibre, 几周内放进 Linux Foundation 孵化, 用回原 BSD 许可。技术上它和 v1.13 完全兼容:同一套 style spec、同一种矢量瓦片格式 (MVT)、同样的 GeoJSON source / layer 模型, 迁移成本接近零。</p>
        <p>之后四年它走出了自己的路。2023 年 3.0 是一次大重写 (500+ commit、近一年打磨); 2024 年 4.0 全面转 TypeScript; 2024 年底 5.0 加入真 3D 球面投影 (globe) —— 地图不再是平面墨卡托近似, 而是真正的地球曲面 + 大气层渲染。治理上, 2022 年起每年 8 月选举技术指导委员会, 项目由亚马逊 / Meta / 微软 / StadiaMaps / Elastic 等组成的联盟资助。姊妹项目 MapLibre Native (移动 / 桌面 / 嵌入式的 C++ 渲染器) 共享同一套 style spec, 让 web 和原生端长一张脸。</p>
      </>
    ),
    en: (
      <>
        <p>MapLibre GL JS began with a license crisis. In December 2020, Mapbox shipped Mapbox GL JS v2 and at the same time switched the license from open source (BSD) to proprietary — code that had been free and freely forkable now required a Mapbox account / token and was billed by usage from v2 onward. For the entire web ecosystem that depended on it for vector maps, that pulled the rug out.</p>
        <p>The community moved fast. Within the same week Mapbox announced the change, multiple forks appeared; they soon converged and decided to jointly maintain and keep developing the <strong>last open-source version</strong> — Mapbox GL JS v1.13 (BSD-licensed). The hard fork was named MapLibre, incubated at the Linux Foundation within weeks, and restored the original BSD license. Technically it stayed fully compatible with v1.13: the same style spec, the same vector tile format (MVT), the same GeoJSON source / layer model — migration cost near zero.</p>
        <p>Over the next four years it found its own path. The 3.0 release in 2023 was a major rewrite (500+ commits, nearly a year in the making); 4.0 in 2024 went full TypeScript; 5.0 at the end of 2024 added a true 3D globe projection — the map is no longer a flat Mercator approximation but a genuine spherical surface with atmosphere rendering. On governance, a technical steering committee has been elected each August since 2022, and the project is funded by a consortium including Amazon, Meta, Microsoft, StadiaMaps, and Elastic. The sister project MapLibre Native (a C++ renderer for mobile / desktop / embedded) shares the same style spec, keeping web and native looking identical.</p>
      </>
    ),
  },
  history: [
    { year: '2020·12', zh: { title: <>Mapbox GL JS v2 转专有</>, desc: <>Mapbox 发布 v2, 把许可从开源 BSD 改成专有 + 强制 token + 按用量计费。整个依赖它的 web 地图生态被迫找出路。</> }, en: { title: <>Mapbox GL JS v2 goes proprietary</>, desc: <>Mapbox ships v2, switching the license from open-source BSD to proprietary with a mandatory token and usage billing. The whole web-map ecosystem that depended on it must find an exit.</> } },
    { year: '2020·12', zh: { title: <>社区当周 fork</>, desc: <>几乎同周内多个 fork 出现。社区合流, 决定共同维护 Mapbox GL JS 最后一个 BSD 开源版 v1.13, 取名 MapLibre。</> }, en: { title: <>Community forks within the week</>, desc: <>Multiple forks appear almost the same week. The community converges to jointly maintain Mapbox GL JS's last BSD release, v1.13, naming it MapLibre.</> } },
    { year: '2021·01', zh: { title: <>Linux Foundation 孵化</>, desc: <>MapLibre 作为原 BSD 许可的 hard fork 进入 Linux Foundation 孵化。从"某公司一个 fork"变成"中立基金会下的社区项目", 治理可信度落地。</> }, en: { title: <>Incubated at Linux Foundation</>, desc: <>MapLibre enters Linux Foundation incubation as a BSD-licensed hard fork. It shifts from "one company's fork" to "a community project under a neutral foundation," grounding its governance credibility.</> } },
    { year: '2021', zh: { title: <>1.x 接续开源线</>, desc: <>1.x 系列直接接续 v1.13, 保持 API / style spec 完全兼容。Mapbox v1 的用户改一个 import 就能迁过来, 几乎零成本。</> }, en: { title: <>1.x continues the open-source line</>, desc: <>The 1.x series picks up directly from v1.13, keeping the API and style spec fully compatible. Mapbox v1 users migrate by changing one import — near zero cost.</> } },
    { year: '2022·05', zh: { title: <>MapLibre Native 整合</>, desc: <>移动 / 桌面 / 嵌入式的 C++ 渲染器 (前 Mapbox GL Native fork) 并入 MapLibre 伞下, 与 web 端共享同一套 style spec, 一份样式两端通用。</> }, en: { title: <>MapLibre Native consolidated</>, desc: <>The C++ renderer for mobile / desktop / embedded (a former Mapbox GL Native fork) joins the MapLibre umbrella, sharing the same style spec with the web — one style, both ends.</> } },
    { year: '2022·08', zh: { title: <>首届技术指导委员会选举</>, desc: <>项目第一次选举产生技术指导委员会。此后每年 8 月改选, 由社区而非单一公司决定方向。</> }, en: { title: <>First steering committee election</>, desc: <>The project holds its first elected technical steering committee. Re-elected each August since, direction is set by the community rather than a single company.</> } },
    { year: '2023·05', zh: { title: <>3.0 / 大重写</>, desc: <>3.0 是一次累积 500+ commit、近一年打磨的大版本。内部结构现代化, 性能与可维护性整体提升, 为后续 TypeScript / globe 铺路。</> }, en: { title: <>3.0 / major rewrite</>, desc: <>3.0 lands as a big release with 500+ commits and nearly a year of work. Internals are modernized, performance and maintainability improve across the board, paving the way for TypeScript and globe.</> } },
    { year: '2023·09', zh: { title: <>治理委员会 + 章程</>, desc: <>首届治理委员会 (Governing Board) 选举, MapLibre Charter 作为指导文件通过。项目治理结构正式定型。</> }, en: { title: <>Governing board + charter</>, desc: <>The first Governing Board is elected and the MapLibre Charter is adopted as the guiding document. The project's governance structure is formalized.</> } },
    { year: '2024·01', zh: { title: <>4.0 / 全面 TypeScript</>, desc: <>4.0 完成向 TypeScript 的全面迁移, 类型定义随源码内置。第三方集成 (deck.gl / react 封装) 的类型体验大幅改善。</> }, en: { title: <>4.0 / full TypeScript</>, desc: <>4.0 completes the migration to TypeScript, with type definitions built into the source. Third-party integrations (deck.gl, React wrappers) gain a much better typing experience.</> } },
    { year: '2024·12', zh: { title: <>5.0 / 真 3D 球面投影</>, desc: <>5.0 加入 globe 投影 + 大气层渲染、超 90° 俯仰、相机滚转、WebGL2→WebGL1 双栈回退。地图第一次是真正的地球曲面而非平面近似。</> }, en: { title: <>5.0 / true 3D globe</>, desc: <>5.0 adds globe projection with atmosphere rendering, pitch beyond 90°, camera roll, and a WebGL2→WebGL1 dual-stack fallback. The map is finally a real spherical surface, not a flat approximation.</> } },
    { year: '2026·01', zh: { title: <>MapLibre Tile (MLT) 公开</>, desc: <>下一代矢量瓦片格式 MLT 公开, 相比 MVT 有更好的压缩与更快的解码。配套 Martin (Rust 瓦片服务) 已发 1.0, 自托管链路成熟。</> }, en: { title: <>MapLibre Tile (MLT) announced</>, desc: <>The next-gen vector tile format MLT is announced, with better compression and faster decoding than MVT. Companion Martin (the Rust tile server) shipped 1.0; the self-hosting chain is mature.</> } },
    { year: '2026', highlight: true, zh: { title: <>5.24 / 当前稳定, v6 在路上</>, desc: <>npm <code>maplibre-gl</code> 当前稳定 5.24.0, 仍在月度迭代。v6 已在 pre-release 阶段。本站 <code>/wca/comp?view=globe</code> 锁 <code>^5.23</code>, 跑 globe 投影 + 矢量瓦片。</> }, en: { title: <>5.24 / current stable, v6 incoming</>, desc: <>npm <code>maplibre-gl</code> is at a stable 5.24.0 with ongoing monthly iteration; v6 is in pre-release. This site's <code>/wca/comp?view=globe</code> pins <code>^5.23</code>, running globe projection + vector tiles.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>style spec (JSON)</>, desc: <>一份 JSON 文档描述整张地图:版本、sources、layers、glyphs / sprite。换主题就是换一份 style。这套规范已是事实标准, MapLibre / Mapbox / 各瓦片服务通用。</> }, en: { title: <>style spec (JSON)</>, desc: <>A single JSON document describes the whole map: version, sources, layers, glyphs / sprite. Swapping themes means swapping a style. The spec is a de facto standard shared by MapLibre / Mapbox / tile services.</> }, code: <code>{'{'}{'\n'}  {p('"version"')}: {n('8')},{'\n'}  {p('"sources"')}: {'{'} ... {'}'},{'\n'}  {p('"layers"')}: [ ... ]{'\n'}{'}'}</code> },
    { tag: 'B', zh: { title: <>Source — 数据来源</>, desc: <>vector (矢量瓦片) / geojson (内联 / URL) / raster (栅格底图)。一个 source 提供数据, 不直接画 —— 怎么画交给 layer。</> }, en: { title: <>Source — where data comes from</>, desc: <>vector (tile pyramids) / geojson (inline or URL) / raster (raster basemaps). A source supplies data but draws nothing — how it draws is left to layers.</> }, code: <code>{v('map')}.{f('addSource')}({s("'comps'")}, {'{'}{'\n'}  {p('type')}: {s("'geojson'")},{'\n'}  {p('data')}: {v('featureCollection')},{'\n'}{'}'});</code> },
    { tag: 'C', zh: { title: <>Layer — 怎么画</>, desc: <>把某个 source 的某层画成 circle / line / fill / symbol / heatmap。同一个 source 可以被多个 layer 用不同方式渲染。</> }, en: { title: <>Layer — how it draws</>, desc: <>Renders one layer of a source as circle / line / fill / symbol / heatmap. The same source can be drawn by multiple layers in different ways.</> }, code: <code>{v('map')}.{f('addLayer')}({'{'}{'\n'}  {p('id')}: {s("'comp-dots'")}, {p('type')}: {s("'circle'")},{'\n'}  {p('source')}: {s("'comps'")},{'\n'}  {p('paint')}: {'{ '}{p("'circle-radius'")}: {n('6')} {'}'},{'\n'}{'}'});</code> },
    { tag: 'D', zh: { title: <>expression — 数据驱动样式</>, desc: <>样式属性可以是表达式, 随 feature 属性 / 缩放级别动态算。本站世界纪录 choropleth 就用 <code>interpolate + log10</code> 把计数映射成色阶。</> }, en: { title: <>expression — data-driven styling</>, desc: <>Style properties can be expressions evaluated against feature properties and zoom. This site's world-record choropleth uses <code>interpolate + log10</code> to map counts onto a color ramp.</> }, code: <code>[{s("'interpolate'")}, [{s("'linear'")}],{'\n'}  [{s("'log10'")}, [{s("'get'")}, {s("'count'")}]],{'\n'}  {n('0')}, {s("'#FFEDA0'")}, {n('3')}, {s("'#BD0026'")}]</code> },
    { tag: 'E', zh: { title: <>vector tile (MVT)</>, desc: <>矢量瓦片把几何 + 属性按 z/x/y 切片发到客户端, 客户端实时着色 / 标签。和栅格瓦片 (PNG 拼图) 比, 无级缩放 + 即时换样式 + 任意旋转。</> }, en: { title: <>vector tile (MVT)</>, desc: <>Vector tiles ship geometry plus attributes sliced by z/x/y, with coloring and labels computed client-side. Versus raster tiles (PNG mosaics): continuous zoom, instant restyle, arbitrary rotation.</> }, code: <code>{p('type')}: {s("'vector'")},{'\n'}{p('tiles')}: [{s("'https://.../{z}/{x}/{y}.pbf'")}],{'\n'}{p('maxzoom')}: {n('14')}</code> },
    { tag: 'F', zh: { title: <>globe 投影</>, desc: <>5.0 起支持真 3D 球面投影。需要 WebGL2; 老设备自动回退墨卡托。本站默认 globe, 探测无 WebGL2 时降级。</> }, en: { title: <>globe projection</>, desc: <>From 5.0, a true 3D spherical projection. Requires WebGL2; older devices fall back to Mercator automatically. This site defaults to globe and degrades when WebGL2 is absent.</> }, code: <code>{k('new')} {f('maplibregl.Map')}({'{'}{'\n'}  {p('container')}: {v('el')},{'\n'}  {p('projection')}: {s("'globe'")},{'\n'}{'}'});</code> },
    { tag: 'G', zh: { title: <>GeoJSON source</>, desc: <>把内存里算好的 FeatureCollection 直接喂给地图。本站选手足迹的大圆弧 / 聚合点都是运行时算出 GeoJSON 再 setData。</> }, en: { title: <>GeoJSON source</>, desc: <>Feed an in-memory FeatureCollection straight to the map. This site's career-footprint arcs and cluster points are computed at runtime as GeoJSON, then pushed via setData.</> }, code: <code>{k('const')} {v('src')} = {v('map')}.{f('getSource')}({s("'arcs'")});{'\n'}({v('src')} {k('as')} GeoJSONSource).{f('setData')}({v('fc')});</code> },
    { tag: 'H', zh: { title: <>addProtocol — 自定义瓦片管线</>, desc: <>注册一个 URL 协议, 拦截瓦片请求做任意处理再返回。本站用它拦矢量瓦片, 把繁体地名转简体后再交给渲染器。</> }, en: { title: <>addProtocol — custom tile pipeline</>, desc: <>Register a URL scheme to intercept tile requests, do arbitrary processing, and return the result. This site uses it to intercept vector tiles and convert traditional-Chinese place names to simplified before rendering.</> }, code: <code>{f('maplibregl.addProtocol')}({s("'zh-tile'")},{'\n'}  {k('async')} ({v('params')}) =&gt; {'{'}{'\n'}    {c('// rewrite name props, re-encode MVT')}{'\n'}  {'}'});</code> },
    { tag: 'I', zh: { title: <>control / popup / marker</>, desc: <>导航 / 缩放 / 比例尺等 control 挂在地图角上; popup 是点击弹层; marker 是钉在某坐标的 DOM 元素。都是 style 之外的交互层。</> }, en: { title: <>control / popup / marker</>, desc: <>Controls (navigation / zoom / scale) attach to the map corners; a popup is a click overlay; a marker is a DOM element pinned to a coordinate. All are interaction layers outside the style.</> }, code: <code>{k('new')} {f('maplibregl.Popup')}(){'\n'}  .{f('setLngLat')}([{v('lng')}, {v('lat')}]){'\n'}  .{f('setHTML')}({v('html')}){'\n'}  .{f('addTo')}({v('map')});</code> },
  ],
  whyCards: [
    { icon: '⌖', zh: { title: <>开源无锁定</>, desc: <>BSD 许可、无强制 token、瓦片可完全自托管。和 Mapbox GL JS v2 那种"必须账号 + 按量计费"彻底相反 —— 这正是 MapLibre 当初存在的理由。</> }, en: { title: <>Open, no lock-in</>, desc: <>BSD license, no mandatory token, tiles fully self-hostable. The exact opposite of Mapbox GL JS v2's "account required, billed by usage" — which is precisely why MapLibre exists.</> }, code: <>{c('// no API key required')}{'\n'}{k('import')} maplibregl {k('from')} {s("'maplibre-gl'")};</> },
    { icon: '⌬', zh: { title: <>style spec 是事实标准</>, desc: <>一份 style JSON 喂 MapLibre / Mapbox / OpenFreeMap / MapTiler / 各家瓦片服务通用。换底图供应商不用重写样式, 只换一个 URL。</> }, en: { title: <>style spec is a de facto standard</>, desc: <>One style JSON feeds MapLibre / Mapbox / OpenFreeMap / MapTiler / any tile service. Switching basemap providers means changing a URL, not rewriting the style.</> }, code: <>{k('new')} {f('maplibregl.Map')}({'{'} {p('style')}: {v('styleUrl')} {'}'});</> },
    { icon: '◍', zh: { title: <>矢量瓦片 = 无级缩放</>, desc: <>几何 + 属性发到客户端, 客户端实时着色。无级缩放、即时换主题 (dark/light/卫星)、任意旋转倾斜 —— 栅格瓦片做不到这些。</> }, en: { title: <>Vector tiles = continuous zoom</>, desc: <>Geometry plus attributes ship to the client and are colored in real time. Continuous zoom, instant theme swaps (dark/light/satellite), arbitrary rotation and tilt — raster tiles can't do any of this.</> }, code: <>{c('// same tiles, swap dark <-> light instantly')}{'\n'}{v('map')}.{f('setStyle')}({v('darkStyle')});</> },
    { icon: '⊕', zh: { title: <>真 3D globe</>, desc: <>5.0 起的球面投影 + 大气层渲染, 把世界级数据画在真正的地球曲面上, 而不是被墨卡托拉变形的两极。本站 /wca/comp?view=globe 默认就用它。</> }, en: { title: <>True 3D globe</>, desc: <>The 5.0 spherical projection with atmosphere draws world-scale data on a real spherical surface instead of Mercator-distorted poles. This site's /wca/comp?view=globe uses it by default.</> }, code: <>{p('projection')}: {s("'globe'")}{'\n'}{c('// poles no longer stretched')}</> },
    { icon: '⎇', zh: { title: <>addProtocol 可拦可改</>, desc: <>注册自定义 URL 协议, 在瓦片到渲染器之间插一段任意逻辑。本站靠它把矢量瓦片里的繁体地名实时转简体, 不改底图源也不重新发瓦片。</> }, en: { title: <>addProtocol is interceptable</>, desc: <>Register a custom URL scheme to insert arbitrary logic between tile and renderer. This site uses it to convert traditional-Chinese place names in vector tiles to simplified on the fly, without changing the source or re-publishing tiles.</> }, code: <>{f('maplibregl.addProtocol')}({s("'zh-tile'")}, {v('handler')});</> },
    { icon: '⌗', zh: { title: <>deck.gl 大数据叠层</>, desc: <>MapLibre 出底图, deck.gl 在同一个 canvas 上叠百万级数据层 (弧 / 热力 / 散点)。两者共享相机, 是 web 地理大数据可视化的标准组合。</> }, en: { title: <>deck.gl big-data overlays</>, desc: <>MapLibre provides the basemap; deck.gl overlays million-scale data layers (arcs / heatmaps / scatter) on the same canvas. Sharing one camera, the pair is the standard combo for web geo big-data viz.</> }, code: <>{k('import')} {'{'} {v('MapboxOverlay')} {'}'} {k('from')} {s("'@deck.gl/mapbox'")};{'\n'}{c('// works on a MapLibre map')}</> },
    { icon: '⏚', zh: { title: <>自托管链路成熟</>, desc: <>Martin (Rust 瓦片服务, 从 PostGIS 出 MVT) + PMTiles (单文件瓦片归档) 让"自己生成 + 自己托管"门槛持续走低, 无需任何商业瓦片订阅。</> }, en: { title: <>Mature self-hosting chain</>, desc: <>Martin (the Rust tile server emitting MVT from PostGIS) plus PMTiles (single-file tile archives) keep lowering the bar for "generate and host your own," with zero commercial tile subscription.</> }, code: <>{c('// Martin: PostGIS -> MVT, no SaaS')}{'\n'}{c('// PMTiles: one file, range requests')}</> },
    { icon: '⛯', zh: { title: <>治理可信</>, desc: <>Linux Foundation 下、由亚马逊 / Meta / 微软等组成的联盟资助、选举产生的技术指导委员会治理。不会再被某一家公司一纸 license 改翻 —— 这是当初 Mapbox 教训的直接回应。</> }, en: { title: <>Trustworthy governance</>, desc: <>Under the Linux Foundation, funded by a consortium (Amazon, Meta, Microsoft, etc.), governed by an elected technical steering committee. It can't be flipped by one company's license change again — a direct answer to the Mapbox lesson.</> }, code: <>{c('// LF-incubated, consortium-funded')}{'\n'}{c('// elected steering committee')}</> },
  ],
  adopters: [
    { name: 'Wikimedia / Wikipedia maps', href: 'https://maps.wikimedia.org', zhNote: '维基百科地图服务的渲染层', enNote: 'The render layer of Wikipedia\'s map service' },
    { name: 'deck.gl', href: 'https://deck.gl', highlight: true, zhNote: 'Uber 大数据可视化框架, 以 MapLibre 为常用底图', enNote: 'Uber\'s big-data viz framework — MapLibre as a common basemap' },
    { name: 'AllTrails', href: 'https://www.alltrails.com', zhNote: '户外徒步 / 越野路线地图', enNote: 'Outdoor hiking / trail route maps' },
    { name: 'Martin', href: 'https://martin.maplibre.org', zhNote: 'Rust 瓦片服务, 从 PostGIS 出 MVT (MapLibre 伞下)', enNote: 'Rust tile server emitting MVT from PostGIS (MapLibre umbrella)' },
    { name: 'PMTiles', href: 'https://github.com/protomaps/PMTiles', zhNote: '单文件瓦片归档, 与 MapLibre 深度整合', enNote: 'Single-file tile archives, deeply integrated with MapLibre' },
    { name: 'OpenFreeMap', href: 'https://openfreemap.org', zhNote: '免费开放矢量瓦片服务, MapLibre style', enNote: 'Free open vector tile service, MapLibre styles' },
    { name: 'MapTiler', href: 'https://www.maptiler.com', zhNote: '商业瓦片供应商, 主力推 MapLibre SDK', enNote: 'Commercial tile provider, ships a MapLibre-based SDK' },
    { name: 'StadiaMaps', href: 'https://stadiamaps.com', zhNote: 'MapLibre 联盟资助方之一', enNote: 'One of the MapLibre consortium funders' },
    { name: 'MapLibre Native', href: 'https://github.com/maplibre/maplibre-native', highlight: true, zhNote: '姊妹项目, 移动 / 桌面 / 嵌入式 C++ 渲染器, 共享 style spec', enNote: 'Sister project — C++ renderer for mobile / desktop / embedded, shared style spec' },
    { name: 'NASA GIBS / Esri imagery', href: 'https://nasa-gibs.github.io', zhNote: '本站卫星模式叠加的栅格底图源', enNote: 'Raster basemap sources behind this site\'s satellite mode' },
    { name: 'Linux Foundation', href: 'https://www.linuxfoundation.org', zhNote: 'MapLibre 的孵化与治理归属', enNote: 'Home of MapLibre\'s incubation and governance' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 /wca/comp?view=globe 比赛地球的矢量渲染层', enNote: 'This site — the vector render layer of the /wca/comp?view=globe competition globe' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>MapLibre Tile (MLT) 接班 MVT</>, body: <><p>2026 年初公开的 MapLibre Tile 是下一代矢量瓦片格式, 针对 MVT 的痛点 (重复属性、解码慢、压缩不够紧) 重做编码, 解码更快、体积更小。MVT 用了十多年, 现在终于有了由 MapLibre 自己主导的继任者。</p><p>更深一层意义:格式标准从"沿用 Mapbox 时代遗产"转向"社区自己定义未来"。MLT 与 globe 投影、Martin 瓦片服务、PMTiles 归档一起, 构成了一条完全独立于任何商业供应商的开源地图栈 —— 从生成、托管到渲染全链路自主。</p></> }, en: { title: <>MapLibre Tile (MLT) succeeds MVT</>, body: <><p>The MapLibre Tile format, announced in early 2026, is the next-gen vector tile format. It reworks the encoding to fix MVT's pain points (repeated attributes, slow decode, loose compression), decoding faster at a smaller size. MVT has run for over a decade; now there is finally a successor led by MapLibre itself.</p><p>The deeper point: the format standard moves from "inheriting the Mapbox era" to "the community defining its own future." MLT, together with globe projection, the Martin tile server, and PMTiles archives, forms a fully open map stack independent of any commercial vendor — autonomous end to end, from generation through hosting to rendering.</p></> } },
    { tag: <>GLOBE</>, zh: { title: <>真 3D 球面成一等公民</>, body: <><p>5.0 起的 globe 投影 + 大气层渲染让地图不再是被墨卡托拉变形的平面。配合超 90° 俯仰、相机滚转, 世界级数据 (本站的世界纪录 / 选手足迹) 终于能画在真正的地球曲面上, 两极不再失真。WebGL2 是前提, 老设备自动回退墨卡托。</p></> }, en: { title: <>True 3D globe is first-class</>, body: <><p>The 5.0 globe projection with atmosphere ends the Mercator-distorted flat map. With pitch beyond 90° and camera roll, world-scale data (this site's world records / competitor footprints) can finally be drawn on a real spherical surface with undistorted poles. WebGL2 is the prerequisite; older devices fall back to Mercator.</p></> } },
    { tag: <>TS</>, zh: { title: <>全 TypeScript + 类型内置</>, body: <><p>4.0 起源码全面 TypeScript, 类型定义随包内置, 不再依赖外部 @types。对 deck.gl 集成、React 封装、自定义 expression 的类型体验都更稳。第三方生态据此长出更厚的类型安全层。</p></> }, en: { title: <>Full TypeScript with built-in types</>, body: <><p>From 4.0 the source is fully TypeScript with type definitions bundled in — no external @types needed. The typing experience for deck.gl integration, React wrappers, and custom expressions is steadier, and the third-party ecosystem grows a thicker type-safe layer on top.</p></> } },
    { tag: <>SELF-HOST</>, zh: { title: <>自托管瓦片门槛归零</>, body: <><p>Martin (Rust, 从 PostGIS 直出 MVT, 2025 年 11 月发 1.0) + PMTiles (单文件瓦片, 走 HTTP range request, 静态托管即可) 让"自己生成 + 自己托管整张地图"不再需要任何商业订阅。这是 MapLibre 开源承诺的最后一块拼图 —— 数据也不被锁。</p></> }, en: { title: <>Self-hosting tiles drops to zero cost</>, body: <><p>Martin (Rust, MVT straight from PostGIS, shipped 1.0 in November 2025) plus PMTiles (single-file tiles served via HTTP range requests on plain static hosting) make "generate and host your whole map yourself" require no commercial subscription. This is the last piece of MapLibre's open-source promise — the data isn't locked either.</p></> } },
    { tag: <>STABILITY</>, zh: { title: <>四年从保命 fork 到独立项目</>, body: <><p>2020 年那次 license 危机本可能让整条 web 矢量地图线分裂崩塌, 结果社区四年内把 MapLibre 做成了被多家大厂联盟资助、治理结构完整、月度迭代的独立项目。当前稳定 5.24, v6 在路上。"被某厂 license 改翻"这种风险, 在 MapLibre 这条线上已经不存在了。</p></> }, en: { title: <>Four years from survival fork to independent project</>, body: <><p>The 2020 license crisis could have fractured the entire web vector-map line. Instead the community turned MapLibre, within four years, into an independent project funded by a multi-vendor consortium, with full governance and monthly iteration. Current stable is 5.24 with v6 incoming. The risk of "a vendor flipping the license" no longer exists on this line.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本站 <code>/wca/comp?view=globe</code> 这页的矢量地球, 渲染层就是 MapLibre GL JS。它把 WCA 比赛数据按经纬度铺在一颗可旋转的 3D 地球上, 有三种模式:<strong>upcoming</strong> 把近期全球比赛聚合成点 (cluster); <strong>cuber</strong> 按时间顺序画某个选手生涯的大圆弧足迹, 支持播放 / 拖动时间轴; <strong>wr</strong> 按国家做世界纪录的 choropleth, 颜色随累计纪录数走对数色阶。</p>
        <p>渲染管线全在 MapLibre 的 style spec 模型上:运行时把比赛 / 足迹算成 GeoJSON FeatureCollection, 喂给 geojson source, 再用 circle / line / fill / symbol 多个 layer 画出来; 颜色 / 半径用 expression (<code>interpolate</code> + <code>log10</code>) 随数据动态算。默认走 globe 投影 (需 WebGL2, 探测不到时降级墨卡托), 支持 dark / light / 卫星三套主题即时切换。</p>
        <p>有一处用得比较深的是 <code>addProtocol</code>:注册一个自定义瓦片协议, 在矢量瓦片到渲染器之间拦一道, 把瓦片里的繁体中文地名实时转成简体再交回去 —— 这样不用改底图供应商、也不用重新发一套瓦片, 就能让中文界面下的地名一致。</p>
        <p>性能上严格遵守本站习惯:地图库本身约 550KB (加全部依赖更大), 绝不该进首屏 bundle。<code>/wca/comp?view=globe</code> 的页面壳极小, 真正的地图组件走 <code>next/dynamic</code> + <code>ssr:false</code> 按需动态 import —— 只有用户真的导航到这页、且在客户端 mount 之后, 才会下载 maplibre-gl。其它页面完全不付这个体积代价。</p>
      </>
    ),
    en: (
      <>
        <p>The vector globe on this site's <code>/wca/comp?view=globe</code> page is rendered by MapLibre GL JS. It plots WCA competition data by lat/lng on a rotatable 3D earth, with three modes: <strong>upcoming</strong> clusters near-term competitions worldwide into points; <strong>cuber</strong> draws a competitor's career as great-circle arcs in chronological order, with play / scrub on a timeline; <strong>wr</strong> is a per-country world-record choropleth whose color follows a logarithmic ramp on cumulative record counts.</p>
        <p>The whole render pipeline sits on MapLibre's style spec model: competitions / footprints are computed at runtime into GeoJSON FeatureCollections, fed to a geojson source, then drawn by multiple circle / line / fill / symbol layers; color and radius are computed dynamically from data via expressions (<code>interpolate</code> + <code>log10</code>). It defaults to globe projection (needs WebGL2, falling back to Mercator when absent) and supports instant switching among dark / light / satellite themes.</p>
        <p>One deeper usage is <code>addProtocol</code>: a custom tile scheme is registered to intercept between vector tile and renderer, converting traditional-Chinese place names in the tiles to simplified on the fly before handing them back — so place names stay consistent in the Chinese UI without changing the basemap provider or re-publishing a tile set.</p>
        <p>On performance the site's habit is strict: the map library is roughly 550KB (larger with all deps) and must never enter the first-paint bundle. The <code>/wca/comp?view=globe</code> page shell is tiny; the real map component is dynamically imported via <code>next/dynamic</code> + <code>ssr:false</code> — maplibre-gl downloads only when the user actually navigates here and after client mount. No other page pays that weight.</p>
      </>
    ),
  },
  links: [
    { label: 'maplibre.org', href: 'https://maplibre.org' },
    { label: 'GitHub · maplibre/maplibre-gl-js', href: 'https://github.com/maplibre/maplibre-gl-js' },
    { label: 'Docs · MapLibre GL JS', href: 'https://maplibre.org/maplibre-gl-js/docs/' },
    { label: 'Style Spec', href: 'https://maplibre.org/maplibre-style-spec/' },
    { label: 'About / governance', href: 'https://maplibre.org/about/' },
    { label: 'Mapbox migration guide', href: 'https://maplibre.org/maplibre-gl-js/docs/guides/mapbox-migration-guide/' },
  ],
};

export default MAPLIBRE_GL;
