import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, s, f, p, c } from '../_lib/stack_tool_types';

// ─── React Router 7 ─────────────────────────────────────────────────────────

export const REACT_ROUTER: StackTool = {
  slug: 'react-router',
  name: 'React Router',
  version: '7.x',
  since: '2014-05',
  group: 'frontend',
  accent: '#F44250',
  bright: '#FF7080',
  glyph: '⇄',
  floats: ['<BrowserRouter>', '<Route>', '<Outlet>', 'useNavigate', 'useParams', 'useSearchParams', '<Link>', 'lazy', '<Suspense>', 'loader', 'action', 'framework mode'],
  zh: {
    tagline: '把 URL 跟组件树绑在一起',
    role: '24+ 工具页全部靠它路由, 每个页 lazy() 切独立 chunk, <Suspense> 兜底加载态, react-router-dom 7 跟 React 19 配合 concurrent renderer。',
    heroSub: <>SPA 的本质是"假装多页面",而把 URL 跟组件树绑在一起这件事 React 自己不管。Michael Jackson 和 Ryan Florence 2014 年抛出 React Router, 十二年里换了 5 次 API, 最后一次 (v7) 跟 Remix 合并, 同一个包既能做纯客户端路由库, 又能做带 loader / action / SSR 的全栈框架。</>,
    whatDesc: <>React Router 不是路由"框架", 它是<strong>把 URL 当作另一层组件 state</strong> 的库。<code>&lt;Route&gt;</code> 是一个普通组件, <code>useParams()</code> 是一个普通 hook。React 不管 URL, RR 就把这块补上, 别的什么都不动。</>,
    historyDesc: <>从 2014 年的 v0.x 到 2024 年底的 v7, React Router 经历了 5 次大改写:v3 component-based、v4 "route is just a component"、v5 + Hooks、v6 nested + data API、v7 跟 Remix 合并。每次改 API 都引发一轮"还能不能信任这个库"的舆论, 然后下一次升级照常发生。</>,
    conceptsTitle: 'Routes + Hooks 核心',
    conceptsDesc: <>v6 起 API 收敛到几样东西:<code>&lt;Routes&gt;</code> / <code>&lt;Route&gt;</code> 配置树、<code>&lt;Link&gt;</code> + <code>useNavigate</code> 导航、<code>useParams</code> / <code>useSearchParams</code> 读 URL、<code>&lt;Outlet&gt;</code> 嵌套、配合 React.lazy + Suspense 做代码分割。framework mode 再加一层 loader / action。</>,
    whyDesc: <>2026 年还选 RR, 不是因为它最快或最小, 而是因为它<strong>跟 React 节奏 1:1 同步</strong>, 加上跟 React.lazy + Suspense + concurrent renderer 配合得最丝滑。其它路由库要么停更, 要么跟着某个 meta-framework 走绑死路。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>不是 Next.js 的 React SPA 几乎全在用它:Discord、Linear、Notion、Spotify web、Shopify hydrogen 都是。从 2014 到 2026 一直是 React 路由领域的事实标准。</>,
    cuberootDesc: <>cuberoot.me 整站走 react-router-dom 7 的 <strong>library mode</strong>。24+ 工具页全部 <code>React.lazy(() =&gt; import(...))</code> 切独立 chunk, 外面包 <code>&lt;Suspense fallback="..." /&gt;</code>。首屏只下落地页代码, 其它页惰性。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>v7 之后路线分成两条:library mode 给纯 SPA (本站这类), framework mode 给需要 SSR / RSC 的应用。2026 年 framework mode 的 RSC 支持正在跟 React 19 一起逐步成熟。View Transitions API 跟 React Compiler 的配合也是下一年的重点。</>,
  },
  en: {
    tagline: 'Binds URLs to your component tree',
    role: 'Routes all 24+ tool pages. Each page is lazy()-split into its own chunk with <Suspense> covering the load; react-router-dom 7 pairs with React 19 concurrent renderer.',
    heroSub: <>SPAs are "pretend multi-page apps," and React itself doesn't bind URLs to your component tree. Michael Jackson and Ryan Florence shipped React Router in 2014; over twelve years it cycled through five API rewrites, and the final one (v7) merged with Remix — the same package now serves as either a pure client-side routing library or a full-stack framework with loader / action / SSR.</>,
    whatDesc: <>React Router isn't a routing "framework" — it's a library that treats <strong>the URL as one more layer of component state</strong>. <code>&lt;Route&gt;</code> is just a component, <code>useParams()</code> is just a hook. React doesn't own the URL; RR fills that gap and touches nothing else.</>,
    historyDesc: <>From v0.x in 2014 to v7 in late 2024, React Router went through five paradigm rewrites: v3 component-based, v4 "route is just a component," v5 + Hooks, v6 nested + data API, v7 merged with Remix. Each rewrite triggered a wave of "can we still trust this library" — and every subsequent upgrade still happened on schedule.</>,
    conceptsTitle: 'Routes + Hooks core',
    conceptsDesc: <>From v6 onward, the API converges on a few things: a <code>&lt;Routes&gt;</code> / <code>&lt;Route&gt;</code> config tree, <code>&lt;Link&gt;</code> + <code>useNavigate</code> for navigation, <code>useParams</code> / <code>useSearchParams</code> for reading the URL, <code>&lt;Outlet&gt;</code> for nesting, and React.lazy + Suspense for code splitting. Framework mode adds loader / action on top.</>,
    whyDesc: <>Picking RR in 2026 isn't because it's fastest or smallest — it's because it ships <strong>in lockstep with React</strong> and integrates more cleanly with React.lazy + Suspense + the concurrent renderer than any alternative. Competing routers are either unmaintained or welded to a specific meta-framework.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Nearly every non-Next.js React SPA: Discord, Linear, Notion, Spotify web, Shopify Hydrogen. From 2014 to 2026 it has been the de facto standard for routing in React.</>,
    cuberootDesc: <>cuberoot.me ships react-router-dom 7 in <strong>library mode</strong>. All 24+ tool pages are <code>React.lazy(() =&gt; import(...))</code>-split into their own chunks and wrapped in <code>&lt;Suspense fallback="..." /&gt;</code>. The landing page is the only code loaded up front.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>Post-v7 the roadmap forks: library mode for pure SPAs (this site), framework mode for apps that want SSR / RSC. RSC support in framework mode is maturing alongside React 19 through 2026. The View Transitions API and React Compiler integration are the next pieces on the table.</>,
  },
  heroStats: [
    { num: '7', unit: '.x', zh: <>当前主版本 <em>2024-11 GA · 仍在 7.x</em></>, en: <>current major <em>2024-11 GA · still on 7.x</em></>,
        zhHant: <>當前主版本 <em>2024-11 GA · 仍在 7.x</em></>
    },
    { num: '13', unit: 'M', zh: <>npm 周下载 <em>react-router-dom 2026</em></>, en: <>weekly npm downloads <em>react-router-dom 2026</em></>,
        zhHant: <>npm 周下載 <em>react-router-dom 2026</em></>
    },
    { num: '24', unit: '+', zh: <>本站工具页路由数 <em>全部 lazy</em></>, en: <>tool pages routed here <em>all lazy</em></>,
        zhHant: <>本站工具頁路由數 <em>全部 lazy</em></>
    },
    { num: '12', unit: 'y', zh: <>从 2014 至今 <em>React 路由事实标准</em></>, en: <>since 2014 <em>de facto standard in React</em></>,
        zhHant: <>從 2014 至今 <em>React 路由事實標準</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>React Router 2014 年 5 月由 Michael Jackson 和 Ryan Florence 公开发布。当时 React 刚开源一年, 社区一致的痛点是:"我的 SPA 怎么处理 URL?" React 本身只管"组件 → DOM", 路由完全不在它的职责范围。两人参考了 Ember 的路由设计, 用 React 组件树本身来表达路由结构 —— <code>&lt;Route path="/users/:id" component={'{User}'} /&gt;</code> 这种写法在 v0.x 就成型, 从此成为整个生态的范式。</p>
        <p>之后是 5 次大的 API 改写:2016 年 v3 把 component-based 写法做到完善, 2017 年 v4 推倒重来 ("route is just a component"), 2019 年 v5 加 hooks (<code>useHistory</code> / <code>useParams</code>), 2021 年 v6 nested routes + data API, 2024 年 v7 跟 Remix 合并。每次改 API 都引发社区争议, 但每次升级路径都做得足够好, 大项目都跟得上。</p>
        <p>2023 年 Remix 团队公开宣布:Remix 框架跟 React Router 库会合并成同一个包, 同一个团队维护。2024 年 11 月 v7 GA 落地这个承诺 —— 同一个 <code>react-router</code> 包既能当纯客户端路由库 (library mode), 也能当带 loader / action / SSR / RSC 的全栈框架 (framework mode)。这是 React 路由领域十年来最大的整合。</p>
      </>
    ),
    en: (
      <>
        <p>React Router was first released in May 2014 by Michael Jackson and Ryan Florence. React itself was barely a year old; the community pain was unanimous: "How does an SPA handle URLs?" React owns "components → DOM" only — routing was explicitly outside its scope. The two borrowed from Ember's router and used the React component tree itself to express the route structure — <code>&lt;Route path="/users/:id" component={'{User}'} /&gt;</code> emerged in v0.x and became the ecosystem's paradigm.</p>
        <p>Five paradigm rewrites followed: v3 (2016) polished the component-based model; v4 (2017) tore everything down ("route is just a component"); v5 (2019) added hooks (<code>useHistory</code> / <code>useParams</code>); v6 (2021) brought nested routes + the data API; v7 (2024) merged with Remix. Each rewrite drew loud debate, but the upgrade paths were good enough that large projects kept up every time.</p>
        <p>In 2023 the Remix team announced the merger: the Remix framework and the React Router library would consolidate into one package, one team. November 2024's v7 GA delivered on that promise — the same <code>react-router</code> package now ships either as a pure client-side routing library (library mode) or as a full-stack framework with loader / action / SSR / RSC (framework mode). The biggest consolidation in React routing in a decade.</p>
      </>
    ),
  },
  history: [
    { year: '2014·05', zh: { title: <>v0.x 首发</>, desc: <>Michael Jackson + Ryan Florence 在 GitHub 公开 React Router 0.x。借鉴 Ember 路由, 把 <code>&lt;Route&gt;</code> 当组件写。React 自己刚开源一年, 社区第一次有了"react SPA 怎么处理 URL"的标准答案。</> }, en: { title: <>v0.x first release</>, desc: <>Michael Jackson + Ryan Florence open-source React Router 0.x. Drawing on Ember's router, <code>&lt;Route&gt;</code> is written as a component. React itself was barely a year old; the community got its first standard answer to "how does a React SPA handle URLs."</> } },
    { year: '2015·07', zh: { title: <>v1.0 首个稳定</>, desc: <>API 收敛, route 嵌套 + 命名路由稳定下来。Redux 同期普及, "React + Redux + React Router" 成为这一阶段的标配组合。</> }, en: { title: <>v1.0 first stable</>, desc: <>API stabilizes; nested routes + named routes lock in. Redux ramps in parallel; "React + Redux + React Router" becomes the default stack of the era.</> } },
    { year: '2016·10', zh: { title: <>v3 — component-based 成熟</>, desc: <>3.x 把 component-based routing 做到稳定。同期 webpack 2 的 dynamic import 让懒加载 + 路由切割开始流行, 大型 SPA 第一次有了真正能用的代码分割方案。</> }, en: { title: <>v3 — component-based matures</>, desc: <>3.x makes component-based routing stable. webpack 2's dynamic import ships in parallel, enabling lazy loading + route-level splitting; large SPAs finally get usable code splitting.</> } },
    { year: '2017·04', zh: { title: <>v4 — 完全重写</>, desc: <>"Route is just a component" 推倒 v3。<code>&lt;Switch&gt;</code> + 动态匹配 + 嵌套渲染。社区一片争议, 升级成本高, 但范式上回到了 React "组合优于配置"的初心。</> }, en: { title: <>v4 — full rewrite</>, desc: <>"Route is just a component" upends v3. <code>&lt;Switch&gt;</code> + dynamic matching + nested rendering. Loud community pushback and a real upgrade cost — but the paradigm returns to React's "composition over configuration" core.</> } },
    { year: '2018·??', zh: { title: <>code-splitting 成主流</>, desc: <>React.lazy (16.6) + Suspense 配合 RR 4 让 "每个 page 一个 chunk, 首屏只下首页代码" 成为新建项目的默认做法。本站后来用的就是这套, 而且一直用到今天。</> }, en: { title: <>code-splitting goes mainstream</>, desc: <>React.lazy (16.6) + Suspense paired with RR 4 makes "one chunk per page, ship only the landing page upfront" the new-project default. The exact pattern this site still uses today.</> } },
    { year: '2019·03', zh: { title: <>v5 + Hooks</>, desc: <>5.1 加 hooks API: <code>useHistory</code> / <code>useLocation</code> / <code>useParams</code> / <code>useRouteMatch</code>。读 URL 从 prop drilling 变成 import 一个 hook, 业务代码大幅瘦身。</> }, en: { title: <>v5 + Hooks</>, desc: <>5.1 adds the hooks API: <code>useHistory</code> / <code>useLocation</code> / <code>useParams</code> / <code>useRouteMatch</code>. Reading the URL becomes "import a hook" instead of prop drilling; business code shrinks substantially.</> } },
    { year: '2021·11', zh: { title: <>v6 alpha — nested + data API</>, desc: <>nested routes 在 <code>&lt;Routes&gt;</code> 里通过子 <code>&lt;Route&gt;</code> 自然表达, <code>&lt;Outlet&gt;</code> 占位渲染子路由。data API (loader / action) 进入 alpha, 受 Remix 启发。</> }, en: { title: <>v6 alpha — nested + data API</>, desc: <>Nested routes are expressed naturally as child <code>&lt;Route&gt;</code>s inside <code>&lt;Routes&gt;</code>; <code>&lt;Outlet&gt;</code> renders the nested child. The data API (loader / action) enters alpha, inspired by Remix.</> } },
    { year: '2022·05', zh: { title: <>v6 GA — 完整 data API</>, desc: <>6.4 把 data API 落地: <code>createBrowserRouter</code> + 每条路由的 (loader / action / Component) 三元组, 数据加载从组件里搬到路由配置层。框架 mode 的雏形。</> }, en: { title: <>v6 GA — full data API</>, desc: <>6.4 ships the data API in full: <code>createBrowserRouter</code> + a (loader / action / Component) triple per route. Data fetching moves out of components into the route config — the embryo of framework mode.</> } },
    { year: '2023·10', zh: { title: <>Remix + RR 合并公告</>, desc: <>Remix 团队公开宣布:Remix 框架跟 React Router 库会合并成同一个包, 同一个团队维护。"library mode + framework mode" 的双轨方案第一次摊牌。</> }, en: { title: <>Remix + RR merger announced</>, desc: <>The Remix team publicly announces the merger: the Remix framework and the React Router library will consolidate into one package, one team. The "library mode + framework mode" dual track is laid out for the first time.</> } },
    { year: '2024·11', highlight: true, zh: { title: <>v7 GA</>, desc: <>11 月 v7.0.0 GA。同一个 <code>react-router</code> 包既能当客户端路由库 (library mode), 又能当带 loader / action / SSR / RSC 的全栈框架 (framework mode)。Remix 7 名字退役。</> }, en: { title: <>v7 GA</>, desc: <>November: v7.0.0 GA. The same <code>react-router</code> package serves as either a client-side routing library (library mode) or a full-stack framework with loader / action / SSR / RSC (framework mode). The "Remix 7" name retires.</> } },
    { year: '2025·06', zh: { title: <>v7.x 稳定迭代</>, desc: <>一连串 7.x 点 release 把 framework mode 的 RSC 流程稳住, SPA mode 加 View Transitions API 支持。大项目 (Linear / Notion / Shopify) 升级路径平稳。</> }, en: { title: <>v7.x stable cadence</>, desc: <>A stream of 7.x patch releases stabilizes framework-mode RSC and adds View Transitions API support to SPA mode. Upgrade paths for large projects (Linear / Notion / Shopify) stay smooth.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>7.x / 当前稳定</>, desc: <>2026-05 仍在 7.x 序列。npm 周下载 react-router-dom ~1300 万, 非 Next 的 React SPA 几乎都跑它。下一个大跳跃尚未公布。</> }, en: { title: <>7.x / current stable</>, desc: <>Still on the 7.x line as of 2026-05. react-router-dom sits at ~13M weekly npm downloads; nearly every non-Next React SPA runs it. No next major announced yet.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>&lt;BrowserRouter&gt; + &lt;Routes&gt; + &lt;Route&gt;</>, desc: <>顶层包 <code>&lt;BrowserRouter&gt;</code>, 里面写一棵 <code>&lt;Routes&gt;</code> + <code>&lt;Route&gt;</code> 配置树。匹配到的 <code>element</code> 渲染出来。</> }, en: { title: <>&lt;BrowserRouter&gt; + &lt;Routes&gt; + &lt;Route&gt;</>, desc: <>Wrap the app in <code>&lt;BrowserRouter&gt;</code>; describe routes with a <code>&lt;Routes&gt;</code> + <code>&lt;Route&gt;</code> tree inside. The matching <code>element</code> renders.</> }, code: <code>&lt;{f('BrowserRouter')}&gt;{'\n'}  &lt;{f('Routes')}&gt;{'\n'}    &lt;{f('Route')} {p('path')}={s('"/"')} {p('element')}={'{<Landing />}'} /&gt;{'\n'}    &lt;{f('Route')} {p('path')}={s('"/recon/:id"')} {p('element')}={'{<Detail />}'} /&gt;{'\n'}  &lt;/{f('Routes')}&gt;{'\n'}&lt;/{f('BrowserRouter')}&gt;</code> },
    { tag: 'B', zh: { title: <>&lt;Link&gt; + useNavigate</>, desc: <>客户端导航:声明式用 <code>&lt;Link to&gt;</code>, 命令式 (按钮回调 / submit 后跳转) 用 <code>useNavigate()</code>。两者都走 history API, 不触发整页刷新。</> }, en: { title: <>&lt;Link&gt; + useNavigate</>, desc: <>Client-side navigation: declarative via <code>&lt;Link to&gt;</code>, imperative (button handlers, post-submit redirects) via <code>useNavigate()</code>. Both use the history API; no full page reload.</> }, code: <code>&lt;{f('Link')} {p('to')}={s('"/recon"')}&gt;复盘&lt;/{f('Link')}&gt;{'\n\n'}{k('const')} {v('navigate')} = {f('useNavigate')}();{'\n'}{f('navigate')}({s('"/recon/123"')});</code> },
    { tag: 'C', zh: { title: <>useParams / useSearchParams</>, desc: <>读 URL 路径参数 + query string。<code>useParams</code> 拿 <code>:slug</code>, <code>useSearchParams</code> 拿 <code>?lang=zh</code> 之类。</> }, en: { title: <>useParams / useSearchParams</>, desc: <>Read URL path params + query string. <code>useParams</code> grabs <code>:slug</code>; <code>useSearchParams</code> handles things like <code>?lang=zh</code>.</> }, code: <code>{k('const')} {'{ '}{v('id')} {'}'} = {f('useParams')}();{'\n'}{k('const')} [{v('search')}, {v('setSearch')}] = {f('useSearchParams')}();{'\n\n'}{k('const')} {v('lang')} = {v('search')}.{f('get')}({s('"lang"')}) ?? {s('"en"')};</code> },
    { tag: 'D', zh: { title: <>&lt;Outlet&gt; 嵌套</>, desc: <>父 <code>&lt;Route&gt;</code> 渲染 <code>&lt;Outlet&gt;</code>, 匹配到的子路由就在这个位置渲染。layout (导航栏 / 侧栏) 写一次, 内容区按 URL 变。</> }, en: { title: <>&lt;Outlet&gt; nesting</>, desc: <>The parent <code>&lt;Route&gt;</code> renders <code>&lt;Outlet&gt;</code>; the matching child route renders into that slot. Write your layout (navbar / sidebar) once; the content area changes with the URL.</> }, code: <code>{k('function')} {f('Layout')}() {'{'}{'\n'}  {k('return')} (&lt;&gt;{'\n'}    &lt;{f('Header')} /&gt;{'\n'}    &lt;{f('Outlet')} /&gt;{'\n'}  &lt;/&gt;);{'\n'}{'}'}</code> },
    { tag: 'E', zh: { title: <>React.lazy + &lt;Suspense&gt;</>, desc: <>每个 page 一个 <code>lazy(() =&gt; import(...))</code>, 外面包 Suspense fallback。webpack / Rollup / Rolldown 自动把每个 page 切成独立 chunk。本站用的就是这套。</> }, en: { title: <>React.lazy + &lt;Suspense&gt;</>, desc: <>One <code>lazy(() =&gt; import(...))</code> per page, wrapped in a Suspense fallback. webpack / Rollup / Rolldown automatically split each page into its own chunk. This site uses exactly this pattern.</> }, code: <code>{k('const')} {v('ReconPage')} = {f('lazy')}(() =&gt; {f('import')}({s('"./pages/recon/ReconListPage"')}));{'\n\n'}&lt;{f('Route')} {p('path')}={s('"/recon"')} {p('element')}={'{'}{'\n'}  &lt;{f('Suspense')} {p('fallback')}={s('"Loading..."')}&gt;&lt;{f('ReconPage')} /&gt;&lt;/{f('Suspense')}&gt;{'\n'}{'}}'} /&gt;</code> },
    { tag: 'F', zh: { title: <>loader / action (framework mode)</>, desc: <>把"路由切换前先取数据 / 提交前先跑这段函数"绑到路由配置上, 组件内不再写 useEffect + fetch。需要 framework mode, 本站没启用。</> }, en: { title: <>loader / action (framework mode)</>, desc: <>Bind "fetch data before the route renders / run this function before submit" to the route config — no more useEffect + fetch inside components. Requires framework mode; this site doesn't use it.</> }, code: <code>{k('export')} {k('async')} {k('function')} {f('loader')}({'{ '}{v('params')} {'}'}) {'{'}{'\n'}  {k('return')} {k('await')} {f('fetchRecon')}({v('params')}.{p('id')});{'\n'}{'}'}{'\n\n'}{k('export')} {k('default')} {k('function')} {f('Detail')}() {'{'}{'\n'}  {k('const')} {v('recon')} = {f('useLoaderData')}();{'\n'}  {k('return')} &lt;{f('pre')}&gt;{'{'}JSON.{f('stringify')}({v('recon')}){'}'}&lt;/{f('pre')}&gt;;{'\n'}{'}'}</code> },
    { tag: 'G', zh: { title: <>&lt;Navigate&gt; 重定向</>, desc: <>声明式重定向。配合 <code>replace</code> 不进历史栈, 旧路径迁新路径用这个。本站 <code>/scramble-stats</code> → <code>/scramble/stats</code> 走的就是这条。</> }, en: { title: <>&lt;Navigate&gt; redirect</>, desc: <>Declarative redirect. Pair with <code>replace</code> to skip the history stack — perfect for old-path → new-path migrations. This site's <code>/scramble-stats</code> → <code>/scramble/stats</code> uses exactly this.</> }, code: <code>&lt;{f('Route')} {p('path')}={s('"/scramble-stats"')}{'\n'}       {p('element')}={'{<Navigate to="/scramble/stats" replace />}'}{'\n'}/&gt;</code> },
    { tag: 'H', zh: { title: <>library vs framework mode</>, desc: <>同一个 npm 包两种用法。library mode = 老式纯客户端路由库, 你自带 build 工具 (Vite / webpack);framework mode = 带 CLI + loader/action + SSR + RSC 的全栈框架, 接管整个 app。</> }, en: { title: <>library vs framework mode</>, desc: <>One npm package, two usage modes. Library mode = the classic client-side routing library, bring your own build tool (Vite / webpack). Framework mode = a full-stack framework with CLI + loader/action + SSR + RSC, takes over the whole app.</> }, code: <code>{c('// library mode (this site)')}{'\n'}{k('import')} {'{ '}{v('BrowserRouter')}, {v('Routes')} {'}'} {k('from')} {s('"react-router-dom"')};{'\n\n'}{c('// framework mode')}{'\n'}{c('// npx create-react-router@latest')}{'\n'}{c('// → app/routes.tsx + loader/action')}</code> },
  ],
  whyCards: [
    { icon: '⇄', zh: { title: <>跟 React 节奏 1:1 同步</>, desc: <>React 出新东西 (concurrent / Suspense / use()), RR 通常一两个小版本里就接上。其它路由库 (Reach Router、wouter 等) 要么停更, 要么落后一个量级。</> }, en: { title: <>In lockstep with React</>, desc: <>When React ships something new (concurrent, Suspense, use()), RR catches up within a minor version or two. Other routers (Reach Router, wouter, etc.) are either unmaintained or an order of magnitude behind.</> }, code: <>{c('// React 19 concurrent')}{'\n'}&lt;{f('Suspense')}&gt; ... &lt;/{f('Suspense')}&gt;</> },
    { icon: '⌬', zh: { title: <>URL 就是状态</>, desc: <>RR 让 URL 成为可分享、可回退、可刷新的应用状态。"复制链接给同事打开就是同一页"这种 SPA 基本要求, 全靠它兜底。</> }, en: { title: <>URL is state</>, desc: <>RR makes the URL a shareable, back-and-forth-able, refreshable piece of app state. "Copy a link to a coworker and they open the same view" — the SPA baseline — depends on it.</> }, code: <>{c('// /recon/123?ev=333&fmt=ao5')}{'\n'}{c('// fully restorable')}</> },
    { icon: '⌗', zh: { title: <>lazy() + Suspense 让 SPA 起得来</>, desc: <>每个 page 切独立 chunk, 首屏只下落地页代码。本站 24+ 工具页, 首屏 JS &lt; 80KB gzip, 重型工具用到才下。这条路径 RR 配 React.lazy 走得最顺。</> }, en: { title: <>lazy() + Suspense let SPAs boot</>, desc: <>One chunk per page, only the landing page ships up front. This site has 24+ tool pages with &lt;80KB gzip first-paint JS; heavy tools fetch on navigation. RR + React.lazy is the smoothest path here.</> }, code: <>{k('const')} {v('Page')} = {f('lazy')}(() =&gt; {f('import')}({s('"./Page"')}));</> },
    { icon: '⎇', zh: { title: <>hooks API 极简</>, desc: <>读 URL / 跳转 / 拿 query 都是一个 import。组件不再吃一堆 routing prop, 也不需要 HOC 套娃。</> }, en: { title: <>Minimal hooks API</>, desc: <>Reading the URL, navigating, grabbing the query — each is one import. Components no longer take a pile of routing props, and there's no HOC tower.</> }, code: <>{k('const')} {v('navigate')} = {f('useNavigate')}();{'\n'}{k('const')} {'{ '}{v('id')} {'}'} = {f('useParams')}();</> },
    { icon: '⌖', zh: { title: <>data API 让路由 = (loader, action, Component)</>, desc: <>v6.4 之后, 一条路由可以同时声明数据加载、提交处理、UI 组件。组件内 useEffect + fetch 的样板从此可以删干净 (前提是用 framework mode 或 createBrowserRouter)。</> }, en: { title: <>Data API: route = (loader, action, Component)</>, desc: <>Since 6.4, a route can declare data loading, submit handling, and UI in one place. The useEffect + fetch boilerplate inside components can be deleted (when using framework mode or createBrowserRouter).</> }, code: <>{'{ '}{p('path')}: {s('"/u/:id"')}, {p('loader')}: {v('fn')}, {p('Component')}: {v('UI')} {'}'}</> },
    { icon: '⚐', zh: { title: <>跟 Remix 合并 → framework mode</>, desc: <>v7 之后同一个包能做 SSR + RSC, 不用换库。今天 library mode 够用, 明天要 SSR 也不需要替换。这是其它 React 路由库给不了的保险。</> }, en: { title: <>Remix merger → framework mode</>, desc: <>Post-v7, the same package handles SSR + RSC — no library swap needed. Today library mode is enough; tomorrow you can flip to framework mode without changing libraries. No other React router offers this safety net.</> }, code: <>{c('// same package, two modes')}{'\n'}{k('import')} {v('x')} {k('from')} {s('"react-router"')};</> },
    { icon: '⌑', zh: { title: <>跟懒重型库配合好</>, desc: <>cubing.js (~2MB)、three.js、mp4box.js 这些重依赖, RR 配 React.lazy 一行 dynamic import 就切成独立 chunk, 不影响首屏。本站重型工具 (Sim / FrameCount / Analyzer) 都靠这套。</> }, en: { title: <>Plays well with lazy heavy deps</>, desc: <>Heavy deps like cubing.js (~2MB), three.js, mp4box.js split into their own chunks with one dynamic import via RR + React.lazy — zero first-paint impact. The site's heavy tools (Sim / FrameCount / Analyzer) all rely on this.</> }, code: <>{f('import')}({s('"cubing/twisty"')}).{f('then')}(...)</> },
    { icon: '⌬', zh: { title: <>生态最广</>, desc: <>Sentry、PostHog、Datadog 等监控工具的 React SDK 都内置 RR 集成, 不需要手写 location 监听。文档 / SO / GitHub issue 数量也是其它路由库的几个量级。</> }, en: { title: <>Largest ecosystem</>, desc: <>Sentry, PostHog, Datadog and other monitoring SDKs ship RR integrations out of the box — no hand-rolled location listeners. The volume of docs, SO answers, and GitHub issues is orders of magnitude beyond competitors.</> }, code: <>{c('// Sentry / PostHog / etc.')}{'\n'}{c('// auto-instrument RR navigation')}</> },
  ],
  adopters: [
    { name: 'Remix', href: 'https://remix.run', highlight: true, zhNote: '原 Remix 团队, 2023 年宣布合并, v7 起两个项目变一个', enNote: 'The original Remix team — announced the merger in 2023; one project from v7 on' },
    { name: 'Shopify Hydrogen', href: 'https://hydrogen.shopify.dev', highlight: true, zhNote: 'RSC + Remix 商家店面框架, 路由层就是 RR 7', enNote: 'Storefront framework on RSC + Remix; routing layer is RR 7' },
    { name: 'Discord', href: 'https://discord.com', zhNote: 'Web 端百万行 React, 路由全部 RR', enNote: 'Million-line React web app, fully on RR' },
    { name: 'Linear', href: 'https://linear.app', zhNote: 'SPA 路由 + 大量动态 routing 模式', enNote: 'SPA routing with extensive dynamic patterns' },
    { name: 'Notion', href: 'https://notion.so', zhNote: 'Block editor 外壳路由', enNote: 'Outer-shell routing around the block editor' },
    { name: 'Spotify Web', href: 'https://open.spotify.com', zhNote: 'Web 播放器 SPA, RR 路由', enNote: 'Web player SPA, RR-routed' },
    { name: 'GitHub (parts)', href: 'https://github.com', zhNote: '逐步把老 Rails ERB 页面迁到 React + RR', enNote: 'Migrating legacy Rails ERB pages to React + RR' },
    { name: 'X / Twitter Lite', zhNote: '历史上 SPA 版本一直跑 RR', enNote: 'The historical SPA version has always run on RR' },
    { name: 'Coinbase', href: 'https://coinbase.com', zhNote: 'Web 端大量 React + RR', enNote: 'Web frontends rely heavily on React + RR' },
    { name: 'Vercel Dashboard', href: 'https://vercel.com', zhNote: '主控制台 SPA', enNote: 'Main dashboard SPA' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 24+ 路由 + lazy() + Suspense, library mode', enNote: 'This site — 24+ routes + lazy() + Suspense, library mode' },
  ],
  outlook: [
    { tag: <>HOT · 2026</>, hot: true, big: true, zh: { title: <>framework mode + RSC 慢慢成熟</>, body: <><p>v7 framework mode 跟 React 19 的 RSC 一起在 2026 慢慢稳。"组件可以跑在服务器、零 JS 下发"这条路径之前几乎只在 Next.js 看到, 现在 RR framework mode 提供了第二条选项, 而且跟 Remix 老用户的 mental model 一致。</p><p>2026 年下半年应该会看到几家中大型公司的 case study, 把"从 Next 迁到 RR framework mode"或"从 RR 6 library 升 RR 7 framework"的取舍跑通。</p></> }, en: { title: <>framework mode + RSC slowly maturing</>, body: <><p>v7's framework mode is stabilizing alongside React 19's RSC through 2026. "Component runs on the server, ship zero JS" used to be Next.js territory; RR framework mode now offers a second door — one that matches the mental model existing Remix users already have.</p><p>Expect case studies in the second half of 2026 from mid-to-large companies walking through "Next → RR framework mode" or "RR 6 library → RR 7 framework" trade-offs.</p></> } },
    { tag: 'SPA', zh: { title: <>library mode 仍是默认</>, body: <><p>不是所有 React 应用都需要 SSR / RSC。纯静态部署 (本站、控制台、内部工具) 走 library mode 就够 —— 一个 BrowserRouter + Routes 配置树就能搞定一切。RR 7 库部分 API 跟 v6 完全兼容, 升级几乎只需要改 import 路径。</p></> }, en: { title: <>Library mode is still the default</>, body: <><p>Not every React app needs SSR / RSC. Pure static deploys (this site, dashboards, internal tools) are fine in library mode — a single BrowserRouter + Routes tree covers everything. RR 7's library API is essentially v6-compatible; upgrading is mostly an import-path change.</p></> } },
    { tag: 'VT', zh: { title: <>View Transitions API 实验</>, body: <><p>Chrome 在 2024 年把 View Transitions API 推稳。RR 7 加了 <code>unstable_viewTransition</code> prop 给 <code>&lt;Link&gt;</code>, 让"路由切换时浏览器自动跑一段 CSS transition"零样板代码。2026 年这部分应该从 unstable 转稳。</p></> }, en: { title: <>View Transitions API experiment</>, body: <><p>Chrome stabilized the View Transitions API in 2024. RR 7 added an <code>unstable_viewTransition</code> prop on <code>&lt;Link&gt;</code> so route changes get a browser-native CSS transition with zero boilerplate. Expect that API to graduate from unstable through 2026.</p></> } },
    { tag: 'COMPILER', zh: { title: <>跟 React Compiler 配合</>, body: <><p>React Compiler 进 RC 之后, 路由切换里"哪段组件需要 memo / 哪段可以 re-render"的判断都自动化。RR 的 useLocation / useParams 这类高频 hook 不再触发不必要的 re-render, 复杂路由树性能会再上一个台阶。</p></> }, en: { title: <>Pairing with the React Compiler</>, body: <><p>Once the React Compiler hits RC, deciding "which component to memoize / which to re-render" on route transitions is automatic. RR's hot hooks (useLocation / useParams) stop triggering unnecessary re-renders, and complex route trees get another performance bump.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>cuberoot.me 整站走 react-router-dom 7 的 <strong>library mode</strong>。<code>App.tsx</code> 顶层一个 <code>&lt;BrowserRouter basename="/"&gt;</code>, 里面一棵 <code>&lt;Routes&gt;</code> 树, 24+ 工具页全部声明在那里。每个 page component 都是 <code>React.lazy(() =&gt; import('./pages/.../Page'))</code>, 外面包一层 <code>&lt;Suspense fallback={'{<div>Loading...</div>}'} /&gt;</code>。首屏只加载落地页 (<code>LandingPage</code>) 的代码, 其它 24 页是惰性, 用到才下对应 chunk。</p>
        <p>具体几条路由作为例子:<code>/recon</code> / <code>/recon/:id</code> 用 <code>useParams</code> 读 id;<code>/trainer/:puzzle/:set/run</code> 三层嵌套路径直接平铺成顶层路由 (没有用 <code>&lt;Outlet&gt;</code>, 因为 layout 都各自不同);<code>/scramble/solver</code> / <code>/frame-count</code> 这类重型工具靠 lazy chunk 隔离 ~2MB 的 cubing.js / mp4box.js 不影响首屏;旧路径 <code>/scramble-stats</code> → <code>/scramble/stats</code> 用 <code>&lt;Navigate to="..." replace /&gt;</code> 兼容。</p>
        <p>不用 framework mode 的原因很直接:本站是<strong>纯静态 SPA</strong>, build 出来就是一堆 hashed JS + CSS + 资源, 直接扔到 nginx root 跟 GH Pages, 没有 server-rendered HTML 这条路径, loader / action 用不上。Hono API 单独跑在 <code>api.cuberoot.me</code>, 跟前端完全解耦, 用 <code>fetch()</code> 调就行, 不需要路由层接管。</p>
        <p>边角:全站 URL 都要带 <code>?lang=zh|en</code>, 由一个 <code>LangParamGuard</code> 组件在 <code>&lt;BrowserRouter&gt;</code> 里订阅 <code>useLocation</code>, 客户端导航缺 lang 就 <code>window.history.replaceState</code> 补一个;catch-all <code>&lt;Route path="*"&gt;</code> 走 <code>BlogRedirectFallback</code> 处理旧 WP slug + 境外 GH Pages mirror 兜底跳到 <code>blog.cuberoot.me</code>。这两块都是 RR 提供的常规 API 在用, 没动到内部。</p>
      </>
    ),
    en: (
      <>
        <p>cuberoot.me runs react-router-dom 7 in <strong>library mode</strong> end-to-end. <code>App.tsx</code> wraps everything in a top-level <code>&lt;BrowserRouter basename="/"&gt;</code> containing one <code>&lt;Routes&gt;</code> tree where all 24+ tool pages are declared. Every page component is <code>React.lazy(() =&gt; import('./pages/.../Page'))</code> with a <code>&lt;Suspense fallback={'{<div>Loading...</div>}'} /&gt;</code> wrapper. Only the landing page (<code>LandingPage</code>) code ships on first paint; the other 24 are lazy and fetched on demand.</p>
        <p>Some concrete routes as examples: <code>/recon</code> / <code>/recon/:id</code> read the id with <code>useParams</code>; the three-segment <code>/trainer/:puzzle/:set/run</code> is flattened into a top-level route (no <code>&lt;Outlet&gt;</code> because each layout is bespoke); heavy tools like <code>/scramble/solver</code> / <code>/frame-count</code> use lazy chunks to keep ~2MB of cubing.js / mp4box.js off the first paint; legacy <code>/scramble-stats</code> → <code>/scramble/stats</code> uses <code>&lt;Navigate to="..." replace /&gt;</code> for back-compat.</p>
        <p>The reason for not using framework mode is direct: the site is a <strong>pure static SPA</strong>. The build is just hashed JS + CSS + assets dropped onto nginx root and GH Pages — there's no server-rendered HTML path, so loader / action have no role. The Hono API runs separately at <code>api.cuberoot.me</code>, completely decoupled from the frontend; <code>fetch()</code> handles all data, no need to bring routing into it.</p>
        <p>Edge bits: every URL must carry <code>?lang=zh|en</code>, enforced by a <code>LangParamGuard</code> component inside <code>&lt;BrowserRouter&gt;</code> that subscribes to <code>useLocation</code> and patches in the missing lang via <code>window.history.replaceState</code> on client-side navigation. The catch-all <code>&lt;Route path="*"&gt;</code> hits a <code>BlogRedirectFallback</code> that handles legacy WP slugs and falls back to <code>blog.cuberoot.me</code> for the GH Pages mirror. Both use stock RR APIs — no internals touched.</p>
      </>
    ),
  },
  links: [
    { label: 'reactrouter.com', href: 'https://reactrouter.com' },
    { label: 'GitHub · remix-run/react-router', href: 'https://github.com/remix-run/react-router' },
    { label: 'React Router v7 announcement', href: 'https://remix.run/blog/react-router-v7' },
    { label: 'React.lazy + Suspense docs', href: 'https://react.dev/reference/react/lazy' },
    { label: 'Framework mode docs', href: 'https://reactrouter.com/start/framework/installation' },
  ],
};

export default REACT_ROUTER;
