import type { StackTool } from '../_lib/stack_tool_types';
import { k, v, s, f, p, c, t } from '../_lib/stack_tool_types';

// ─── Turbopack ──────────────────────────────────────────────────────────────
// NOTE: Turbopack (bundler) is NOT Turborepo (monorepo task runner). Same parent
// (Vercel), confusingly similar names, completely different products.

export const TURBOPACK: StackTool = {
  slug: 'turbopack',
  name: 'Turbopack',
  version: 'Next 16',
  since: '2022-10',
  group: 'frontend',
  accent: '#0096FF',
  bright: '#38B2FF',
  glyph: '≫',
  floats: ['Rust', 'incremental', 'Turbo engine', 'function-level cache', 'HMR', 'lazy bundling', 'unified graph', 'SWC', 'Fast Refresh', 'invalidation', 'next dev', '--webpack'],
  zh: {
    tagline: 'Rust 写的增量打包器, Next.js 默认内核',
    role: '本站 dev 的打包器与 HMR 引擎。Next 16 起 next dev / next build 默认走它, 取代 webpack。',
    heroSub: <>webpack 作者 Tobias Koppers 2021 年加入 Vercel 后用 Rust 重写的下一代打包器。核心是 Turbo engine 的<strong>函数级增量缓存</strong>:把构建拆成一张细到函数粒度的计算图, 算过的不再重算, 改一行只重跑被它影响的那几个节点。2022 年随 Next 13 以 alpha 亮相, 三年后成为 Next 16 的默认内核。注意:它是<strong>打包器</strong> Turbopack, 不是同公司那个 monorepo 任务编排器 Turborepo。</>,
    whatDesc: <>Turbopack 是一个 <strong>增量打包器</strong> (incremental bundler), 内建在 Next.js 里, 用 Rust 写。它要回答的问题跟 Vite 一样 —— "怎么让大项目的 dev 改一行后秒级更新" —— 但答案不同:Vite 选 dev 不打包、浏览器原生 ESM, Turbopack 选<strong>仍然打包、但缓存到函数级</strong>。这条路在超大应用 (几千上万模块) 上更稳, 不会被几百个并发请求拖垮。一个关键提醒:别跟 <strong>Turborepo</strong> 混, 那是 Vercel 的 monorepo 任务编排器, 跑 build / test / lint 的依赖图, 不打包任何模块。两者只是名字像。</>,
    historyDesc: <>从 2022 年 10 月随 Next 13 的 <code>next dev --turbo</code> alpha (当时 "比 Vite 快 10x" 的宣传立刻被 Vite 作者 Evan You 公开质疑基准方法), 到 2025 年 10 月 Next 16 把它设成 dev + build 的默认内核, 三年。中间逐步走过:dev 从 alpha → beta → 2024 年底 Next 15 dev stable; build 2025 年 Next 15.3 实验性 → 15.5 beta → 16 默认。每一步都比承诺慢, 但方向没变。</>,
    conceptsTitle: '增量计算的几个原子',
    conceptsDesc: <>Turbopack 对用户暴露的表面极小 (零配置, 一个 <code>turbopack</code> config key)。真正的复杂度在内部:Turbo engine 怎么把构建拆成可缓存的函数图、怎么按需 lazy bundle、怎么精确 invalidate。这几个概念是理解它跟 webpack / Vite 取舍的关键。</>,
    whyDesc: <>2026 年用 Next.js 就等于用 Turbopack —— 它是默认, 不用选。选它 (而非退回 webpack) 的理由是<strong>Fast Refresh 快一个量级</strong>、<strong>大项目不卡</strong>、<strong>零配置</strong>。代价是 webpack 插件生态用不了 (loader 能用, plugin 不能), 边角 Sass / CSS Modules 特性还有缺口。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>Turbopack 跟 Next.js 绑死, 所以"谁在用 Next"基本等于"谁在用 Turbopack":OpenAI、Notion、TikTok、Twitch、Nike 的 Next 前端在 Next 16 后都默认走它。它不像 Vite 那样独立于框架被各家采用 —— 它是 Next 的内核, 不单独发行。</>,
    cuberootDesc: <>本站主工作区 <code>core/packages/client-next</code> 是 Next 16 App Router + React 19, dev 的打包与 HMR 就是 Turbopack。<code>next dev</code> 跑在 <code>127.0.0.1:3000</code>, 改一行 Fast Refresh 不刷页面。注意:同仓库的 monorepo 任务编排走的是 <strong>Turborepo</strong> (名字像但不同物)。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>Next 16 把 Turbopack 设成默认是里程碑, 但故事没完:文件系统缓存 (dev 默认开 / build 仍 opt-in) 让构建跨重启复用, 还在 beta;webpack plugin 兼容层、剩余 Sass / Less 缺口、standalone (脱离 Next 独立用) 是后续主线。长期跟同公司 Turborepo 共享 Rust 依赖图后端。</>,
  },
  en: {
    tagline: 'Rust incremental bundler, the default Next.js core',
    role: 'The dev bundler and HMR engine for this site. Since Next 16 it is the default for next dev / next build, replacing webpack.',
    heroSub: <>A next-gen bundler webpack author Tobias Koppers rewrote in Rust after joining Vercel in 2021. The core is the Turbo engine's <strong>function-level incremental cache</strong>: it breaks the build into a computation graph down to function granularity, never recomputes what it already did, and on a one-line edit only re-runs the nodes that edit touches. It debuted as an alpha with Next 13 in 2022 and became Next 16's default core three years later. Note: this is the <strong>bundler</strong> Turbopack, not the same company's monorepo task runner Turborepo.</>,
    whatDesc: <>Turbopack is an <strong>incremental bundler</strong> built into Next.js and written in Rust. It answers the same question as Vite — "how do you make a large app update in milliseconds after a one-line edit" — but with a different answer: Vite skips bundling in dev and serves native ESM, whereas Turbopack <strong>still bundles, but caches down to the function level</strong>. That path holds up better on very large apps (thousands of modules) without drowning in hundreds of concurrent requests. One key caveat: don't confuse it with <strong>Turborepo</strong>, which is Vercel's monorepo task orchestrator that runs the build / test / lint dependency graph and bundles nothing. The names just look alike.</>,
    historyDesc: <>From the <code>next dev --turbo</code> alpha shipped with Next 13 in October 2022 (whose "10x faster than Vite" pitch was immediately challenged on methodology by Vite author Evan You) to Next 16 in October 2025 making it the default core for dev and build, three years. Along the way: dev went alpha → beta → stable in Next 15 (late 2024); build went experimental in Next 15.3 → beta in 15.5 → default in 16. Every step landed slower than promised, but the direction never changed.</>,
    conceptsTitle: 'A few atoms of incremental computation',
    conceptsDesc: <>The surface Turbopack exposes is tiny (zero-config, a single <code>turbopack</code> config key). The real complexity is internal: how the Turbo engine splits a build into a cacheable function graph, how it lazy-bundles on demand, how it invalidates precisely. These concepts are the key to understanding its tradeoff against webpack / Vite.</>,
    whyDesc: <>Using Next.js in 2026 means using Turbopack — it's the default, no choice required. The reason to keep it (rather than fall back to webpack) is <strong>Fast Refresh an order of magnitude faster</strong>, <strong>no stalls on large apps</strong>, and <strong>zero config</strong>. The cost is the webpack plugin ecosystem doesn't apply (loaders work, plugins don't), and some edge Sass / CSS Modules features still have gaps.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Turbopack is welded to Next.js, so "who uses Next" is essentially "who uses Turbopack": the Next frontends of OpenAI, Notion, TikTok, Twitch, and Nike all default to it after Next 16. Unlike Vite, it isn't adopted framework-independently by various projects — it's Next's core, not shipped on its own.</>,
    cuberootDesc: <>This site's primary workspace <code>core/packages/client-next</code> is Next 16 App Router + React 19; the dev bundling and HMR are Turbopack. <code>next dev</code> runs on <code>127.0.0.1:3000</code>, hot-replacing edits without a reload. Note: the monorepo task orchestration in the same repo runs on <strong>Turborepo</strong> (similar name, different tool).</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>Next 16 making Turbopack the default is a milestone, but the story isn't over: filesystem caching (on by default in dev, still opt-in for build) reuses work across restarts and is still beta; a webpack-plugin compatibility layer, remaining Sass / Less gaps, and standalone use (outside Next) are the next storyline. Long-term it shares a Rust dep-graph backend with the same company's Turborepo.</>,
  },
  heroStats: [
    { num: '16', zh: <>Next.js 16 起设为默认打包器 <em>2025-10 GA</em></>, en: <>default bundler since Next.js 16 <em>2025-10 GA</em></>,
        zhHant: <>Next.js 16 起設為預設打包器 <em>2025-10 GA</em></>
    },
    { num: '10', unit: '×', zh: <>Fast Refresh 提速 (vs webpack) <em>Vercel 官方数据</em></>, en: <>faster Fast Refresh vs webpack <em>Vercel official</em></>,
        zhHant: <>Fast Refresh 提速 (vs webpack) <em>Vercel 官方資料</em></>
    },
    { num: '3', unit: 'y', zh: <>从 2022 alpha 到 16 默认 <em>逐步转正</em></>, en: <>from 2022 alpha to v16 default <em>gradual graduation</em></>,
        zhHant: <>從 2022 alpha 到 16 預設 <em>逐步轉正</em></>
    },
    { num: '1', zh: <>种内核覆盖 dev + build <em>统一依赖图</em></>, en: <>one core covers dev + build <em>unified graph</em></>,
        zhHant: <>種核心覆蓋 dev + build <em>統一依賴圖</em></>
    },
  ],
  intro: {
    zh: (
      <>
        <p>Turbopack 的起点是一个人:Tobias Koppers, webpack 的作者。Next.js 在 2021 年 (Next 12) 把 Babel + Terser 换成 Rust 写的 SWC, 编译快了约 5 倍, 这让 Vercel 团队相信 "用 Rust 重写整个打包流水线" 是值得的方向。Koppers 2021 年 4 月加入 Vercel, 主导从零写一个 Rust 打包器, 代号 Turbopack。</p>
        <p>2022 年 10 月 25 日的 Next.js Conf 上, Turbopack 随 Next 13 以 alpha 发布 (<code>next dev --turbo</code>)。Vercel 的宣传口号是 "比 Vite 快 10x、比 webpack 快 700x"。这个数字立刻引来争议:Vite 作者 Evan You 公开质疑基准方法 —— 对比用的是 Turbopack+SWC 对 Vite+Babel、跑的是 2 万模块的合成测试、数字四舍五入偏向自己。真实的常见场景 (root 组件 HMR) 两者差不多, leaf 组件 Turbopack 快但远不到宣传的倍数。这场公开辩论让 "Turbopack 到底快多少" 成了两年里反复被讨论的话题。</p>
        <p>之后是漫长的逐步转正:dev 从 alpha 走到 Next 15 (2024 年底) 的 stable;build 慢得多 —— Next 15.3 (2025) 实验性、15.5 beta、直到 2025 年 10 月 21 日的 Next 16 才把 dev + build 都设成默认, webpack 退居 <code>--webpack</code> opt-out。三年时间, Turbopack 从 "一个有争议的 demo" 变成 "你用 Next 就在用、不需要知道它存在" 的默认内核。这中间最重要的不是某个版本号, 而是 Turbo engine 那套<strong>函数级增量缓存</strong>模型在真实大项目上被验证可靠。</p>
      </>
    ),
    en: (
      <>
        <p>Turbopack starts with one person: Tobias Koppers, the author of webpack. In 2021 (Next 12) Next.js swapped Babel + Terser for the Rust-written SWC and got roughly 5× faster compilation, which convinced Vercel that "rewrite the entire bundling pipeline in Rust" was a direction worth taking. Koppers joined Vercel in April 2021 to lead a from-scratch Rust bundler codenamed Turbopack.</p>
        <p>At Next.js Conf on 2022-10-25, Turbopack shipped with Next 13 as an alpha (<code>next dev --turbo</code>). Vercel's pitch was "10x faster than Vite, 700x faster than webpack." Those numbers drew immediate fire: Vite author Evan You publicly challenged the methodology — the comparison pitted Turbopack+SWC against Vite+Babel, ran a synthetic 20,000-module test, and rounded favorably. In the common real scenario (root-component HMR) the two were about even; leaf components were faster on Turbopack but nowhere near the advertised multiple. That public debate made "how much faster is Turbopack, really" a recurring topic for two years.</p>
        <p>What followed was a long, gradual graduation: dev went from alpha to stable in Next 15 (late 2024); build lagged far more — experimental in Next 15.3 (2025), beta in 15.5, and only with Next 16 on 2025-10-21 did both dev and build become the default, with webpack demoted to a <code>--webpack</code> opt-out. Over three years Turbopack went from "a controversial demo" to "the default core you use whenever you use Next, without needing to know it exists." The most important thing in between was not any version number but the Turbo engine's <strong>function-level incremental cache</strong> model proving reliable on real large projects.</p>
      </>
    ),
  },
  history: [
    { year: '2021·04', zh: { title: <>Koppers 加入 Vercel</>, desc: <>webpack 作者 Tobias Koppers 加入 Vercel。Next 12 同年把 Babel + Terser 换成 Rust 写的 SWC, 编译快约 5 倍, 给 "整条流水线 Rust 化" 铺路。Turbopack 项目秘密启动。</> }, en: { title: <>Koppers joins Vercel</>, desc: <>webpack author Tobias Koppers joins Vercel. Next 12 that year replaces Babel + Terser with the Rust-written SWC for ~5× faster compilation, paving the way for a fully Rust pipeline. The Turbopack project quietly starts.</> } },
    { year: '2022·10', zh: { title: <>alpha 随 Next 13 亮相</>, desc: <>10 月 25 日 Next.js Conf, Turbopack 以 alpha 发布 (<code>next dev --turbo</code>)。Vercel 打出 "比 Vite 快 10x" 的旗号, 用 Turbo engine + Rust 做核心。注意:同期 Next 13 也用了 Turborepo 跑自己的 monorepo, 两个名字从此被外界混淆。</> }, en: { title: <>alpha debuts with Next 13</>, desc: <>October 25, Next.js Conf: Turbopack ships as an alpha (<code>next dev --turbo</code>), powered by the Turbo engine + Rust, under a "10x faster than Vite" banner. Note: Next 13 also used Turborepo for its own monorepo, and the two names get conflated by outsiders from here on.</> } },
    { year: '2022·10', zh: { title: <>基准之争</>, desc: <>10 月底 Vite 作者 Evan You 公开质疑 "10x" 基准:对比 SWC 对 Babel、跑 2 万模块合成测试、数字取整偏己。"Turbopack 到底快多少" 成了两年的争论焦点, 也逼着双方做更诚实的基准。</> }, en: { title: <>The benchmark dispute</>, desc: <>Late October, Vite author Evan You publicly challenges the "10x" benchmark: it compared SWC against Babel, ran a 20,000-module synthetic test, and rounded in its own favor. "How much faster is Turbopack" becomes a two-year debate and pushes both sides toward more honest benchmarks.</> } },
    { year: '2023·05', zh: { title: <>Next 13.4 — App Router + Turbopack 继续 alpha</>, desc: <>App Router 转正, Turbopack 仍只在 dev 跑且仍标 alpha。这一年里它的重写范围扩大 (CSS / 静态资源 / 字体), 但稳定性还不足以摘 alpha 帽。</> }, en: { title: <>Next 13.4 — App Router + Turbopack still alpha</>, desc: <>The App Router goes stable while Turbopack remains dev-only and still labeled alpha. Over this year its rewrite scope widens (CSS / static assets / fonts), but stability isn't yet enough to drop the alpha tag.</> } },
    { year: '2024·05', zh: { title: <>Next 14 — dev beta</>, desc: <>Turbopack 在 <code>next dev</code> 通过 Next.js 自家 8000+ 集成测试, 升到 beta。"开发体验已经能用了" 第一次成立, 但 build 仍走 webpack。</> }, en: { title: <>Next 14 — dev beta</>, desc: <>Turbopack passes Next.js's own 8,000+ integration tests for <code>next dev</code> and graduates to beta. "The dev experience is usable" is true for the first time, but build still runs on webpack.</> } },
    { year: '2024·10', highlight: false, zh: { title: <>Next 15 — dev stable</>, desc: <>Next 15 把 <code>next dev --turbo</code> 标为 stable。日常开发默认推荐用它, webpack 仍是 build 端唯一选项。这是 Turbopack 第一次摘掉所有不稳定标签 (限 dev)。</> }, en: { title: <>Next 15 — dev stable</>, desc: <>Next 15 marks <code>next dev --turbo</code> as stable. Everyday dev is recommended on it; webpack remains the only build-side option. The first time Turbopack sheds every unstable label (for dev).</> } },
    { year: '2025·04', zh: { title: <>Next 15.3 — build 实验性</>, desc: <>15.3 第一次让 <code>next build --turbopack</code> 可用 (实验性)。生产构建终于开始走 Turbopack, 大量边角特性 (source map / minify / tree-shake) 在这一版补齐。</> }, en: { title: <>Next 15.3 — experimental build</>, desc: <>15.3 makes <code>next build --turbopack</code> available for the first time (experimental). Production builds finally start running on Turbopack, with many edge features (source maps / minify / tree-shake) filled in this release.</> } },
    { year: '2025·08', zh: { title: <>Next 15.5 — build beta</>, desc: <>15.5 把 build 端从实验性提到 beta, 大多数 app 已能用 Turbopack 出生产构建。为 16 设默认做最后铺垫。</> }, en: { title: <>Next 15.5 — build beta</>, desc: <>15.5 promotes the build side from experimental to beta; most apps can now produce production builds with Turbopack. The final groundwork before making it the default in 16.</> } },
    { year: '2025·10', highlight: true, zh: { title: <>Next 16 — 设为默认内核</>, desc: <>10 月 21 日 Next 16 GA。<code>next dev</code> 与 <code>next build</code> 默认都走 Turbopack, webpack 退到 <code>--webpack</code> opt-out。dev Fast Refresh 快约 10x, 文件系统缓存 (dev 默认开 / build opt-in) 让构建跨重启复用。Turbopack 三年从 alpha 走到默认。</> }, en: { title: <>Next 16 — becomes the default core</>, desc: <>October 21, Next 16 GA. Both <code>next dev</code> and <code>next build</code> default to Turbopack; webpack falls back to a <code>--webpack</code> opt-out. Dev Fast Refresh is ~10× faster; filesystem caching (on by default in dev, opt-in for build) reuses work across restarts. Three years from alpha to default.</> } },
    { year: '2026·05', highlight: true, zh: { title: <>16.2.6 / 本站锁定版</>, desc: <>本仓库 <code>core/packages/client-next</code> 锁 Next 16.2.6, dev 打包与 HMR 全部 Turbopack。文件系统缓存 build 端仍 opt-in, webpack 兼容层与 standalone 用法继续推进中。</> }, en: { title: <>16.2.6 / pinned in this repo</>, desc: <>This repo's <code>core/packages/client-next</code> pins Next 16.2.6; dev bundling and HMR are all Turbopack. Filesystem caching is still opt-in on the build side; the webpack-compat layer and standalone usage keep advancing.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>函数级增量缓存</>, desc: <>Turbo engine 把整个构建拆成细到函数粒度的计算图, 每个节点的结果按输入 hash 缓存。改一行只让被它影响的那几个节点失效, 其余直接重放。这是 Turbopack 跟 webpack 最根本的区别。</> }, en: { title: <>Function-level incremental cache</>, desc: <>The Turbo engine splits the entire build into a computation graph down to function granularity; each node's result is cached by input hash. A one-line edit invalidates only the nodes it touches; everything else replays. This is the most fundamental difference from webpack.</> }, code: <code>{c('// conceptual: each compute step is a cached fn node')}{'\n'}{f('parse')}({s('"App.tsx"')})   {c('// cached, key = file hash')}{'\n'}{f('transform')}(ast)     {c('// re-run only if parse changed')}{'\n'}{f('bundle')}(graph)       {c('// re-run only affected chunks')}</code> },
    { tag: 'B', zh: { title: <>dev 仍打包 (vs Vite)</>, desc: <>Vite 选 dev 不打包、浏览器原生 ESM;Turbopack 选 dev <strong>仍然打包</strong>, 但优化得很快。理由是超大应用 (上万模块) 下原生 ESM 会发几百个并发请求拖慢浏览器, 打包后反而更稳。</> }, en: { title: <>Bundles in dev (vs Vite)</>, desc: <>Vite skips bundling in dev and serves native ESM; Turbopack <strong>still bundles</strong> in dev, just very fast. The rationale: on very large apps (tens of thousands of modules) native ESM fans out hundreds of concurrent requests and stalls the browser, so a bundled output is actually steadier.</> }, code: <code>{c('// Vite dev:   browser imports source directly')}{'\n'}{c('// Turbopack:  bundles, but caches at fn level')}{'\n'}{c('// both target sub-100ms edit-to-paint')}</code> },
    { tag: 'C', zh: { title: <>lazy bundling</>, desc: <>Turbopack 只打包 dev server 实际请求到的那部分。打开 <code>/timer</code> 才编 timer 相关模块, 没访问的页面根本不进图。冷启动与内存都因此变小。</> }, en: { title: <>Lazy bundling</>, desc: <>Turbopack only bundles what the dev server actually requests. Open <code>/timer</code> and only the timer modules compile; pages you never visit never enter the graph. Cold start and memory both shrink as a result.</> }, code: <code>{c('// dev server requests /timer')}{'\n'}{c('// -> only timer route + its deps are compiled')}{'\n'}{c('// /recon stays uncompiled until visited')}</code> },
    { tag: 'D', zh: { title: <>统一依赖图 (unified graph)</>, desc: <>client / server / edge 多个输出环境共用<strong>同一张</strong>模块图。webpack 时代要为每个环境跑独立 compiler 再拼 bundle, Turbopack 一张图覆盖, 跨环境共享的模块只算一次。</> }, en: { title: <>Unified graph</>, desc: <>Client / server / edge output environments share <strong>one</strong> module graph. Where webpack ran a separate compiler per environment and stitched bundles together, Turbopack covers all of them with a single graph, computing modules shared across environments only once.</> }, code: <code>{c('// one graph spans:')}{'\n'}{c('//   client bundle  (browser)')}{'\n'}{c('//   server bundle  (RSC / route handlers)')}{'\n'}{c('//   shared module computed once')}</code> },
    { tag: 'E', zh: { title: <>HMR / Fast Refresh</>, desc: <>改一个文件, Turbopack 沿函数图精确算出哪些 chunk 受影响, 只把变化的模块推给浏览器, React 状态不丢。Next 里这就是 Fast Refresh, 官方称比 webpack 快约 10x。</> }, en: { title: <>HMR / Fast Refresh</>, desc: <>Edit a file and Turbopack walks the function graph to compute exactly which chunks are affected, pushing only the changed modules to the browser with React state preserved. In Next this is Fast Refresh — officially ~10× faster than webpack.</> }, code: <code>{c('// edit a component')}{'\n'}{c('// ✓ Compiled in 41ms (Turbopack)')}{'\n'}{c('// only the changed module re-sent, state kept')}</code> },
    { tag: 'F', zh: { title: <>Rust + SWC</>, desc: <>整个引擎用 Rust 写, JS / TS / JSX 的解析与转换交给同样 Rust 写的 SWC。类型检查不归 Turbopack 管 (跑 <code>tsc</code> 或靠 IDE)。Rust 的并行与零成本抽象是它能跑满多核的根。</> }, en: { title: <>Rust + SWC</>, desc: <>The whole engine is written in Rust; JS / TS / JSX parsing and transforms go to SWC, also in Rust. Type-checking is not Turbopack's job (run <code>tsc</code> or rely on the IDE). Rust's parallelism and zero-cost abstractions are why it saturates multiple cores.</> }, code: <code>{c('// type-check is separate from bundling')}{'\n'}{p('$')} {f('tsc')} {p('--watch')} {c('// or rely on IDE')}{'\n'}{p('$')} {f('next')} dev      {c('// Turbopack bundles, SWC transforms')}</code> },
    { tag: 'G', zh: { title: <>零配置 + turbopack key</>, desc: <>常见用法零配置直接跑。要扩展时在 <code>next.config</code> 的 <code>turbopack</code> 下加 <code>rules</code> (webpack loader)、<code>resolveAlias</code>、<code>resolveExtensions</code>。注意 webpack <strong>plugin</strong> 不支持, 只支持 loader。</> }, en: { title: <>Zero-config + the turbopack key</>, desc: <>Common cases run with zero config. To extend, add <code>rules</code> (webpack loaders), <code>resolveAlias</code>, or <code>resolveExtensions</code> under the <code>turbopack</code> key in <code>next.config</code>. Note: webpack <strong>plugins</strong> are unsupported — only loaders.</> }, code: <code>{c('// next.config.ts')}{'\n'}{k('const')} {v('config')}: {t('NextConfig')} = {'{'}{'\n'}  {p('turbopack')}: {'{ '}{p('resolveAlias')}: {'{ '}{p('underscore')}: {s('"lodash"')} {'}'} {'}'},{'\n'}{'}'};</code> },
    { tag: 'H', zh: { title: <>≠ Turborepo</>, desc: <><strong>Turbopack</strong> 打包模块 (parse → transform → bundle), 是 webpack 的替代。<strong>Turborepo</strong> 编排 monorepo 任务 (build / test / lint 的依赖图 + 缓存), 不打包任何东西。同公司、名字像、用途完全不同。本站两者都用。</> }, en: { title: <>≠ Turborepo</>, desc: <><strong>Turbopack</strong> bundles modules (parse → transform → bundle); it replaces webpack. <strong>Turborepo</strong> orchestrates monorepo tasks (a dependency graph + cache over build / test / lint) and bundles nothing. Same company, similar name, completely different jobs. This site uses both.</> }, code: <code>{c('// Turbopack: a bundler')}{'\n'}{p('$')} {f('next')} dev          {c('// bundles modules')}{'\n'}{c('// Turborepo: a task runner')}{'\n'}{p('$')} {f('turbo')} typecheck    {c('// runs npm scripts across packages')}</code> },
  ],
  whyCards: [
    { icon: '⚡', zh: { title: <>Fast Refresh 快约 10x</>, desc: <>函数级缓存让改一行只重算受影响节点。Next 官方称 Fast Refresh 比 webpack 快约 10 倍, 大项目改组件几乎瞬时, 不再有 "改一行等两秒" 的 webpack 体感。</> }, en: { title: <>~10× faster Fast Refresh</>, desc: <>Function-level caching means a one-line edit only recomputes affected nodes. Next claims Fast Refresh is ~10× faster than webpack; editing a component in a large app is near-instant, with none of webpack's "edit, wait two seconds" feel.</> }, code: <>{c('// ▲ Next.js 16 (Turbopack)')}{'\n'}{c('// ✓ Compiled in 41ms')}</> },
    { icon: '⌗', zh: { title: <>大项目不卡</>, desc: <>dev 仍打包 + lazy bundling, 上万模块的应用不会被原生 ESM 的几百并发请求拖垮。这是 Turbopack 相对 Vite 在超大单体上的核心卖点。</> }, en: { title: <>No stalls on large apps</>, desc: <>Bundling in dev plus lazy bundling means a tens-of-thousands-of-modules app isn't dragged down by native ESM's hundreds of concurrent requests. This is Turbopack's core selling point over Vite on very large monoliths.</> }, code: <>{c('// only the visited route compiles')}{'\n'}{c('// memory stays bounded as the app grows')}</> },
    { icon: '⚙', zh: { title: <>零配置内建 Next</>, desc: <>不用装、不用配, <code>next dev</code> 直接就是 Turbopack。CSS / CSS Modules / Sass / 静态资源 / TS / JSX 全部开箱即用, 没有 webpack 时代那一堆 loader 配置。</> }, en: { title: <>Zero-config, built into Next</>, desc: <>Nothing to install or configure — <code>next dev</code> is just Turbopack. CSS / CSS Modules / Sass / static assets / TS / JSX all work out of the box, without webpack's pile of loader config.</> }, code: <>{c('// package.json')}{'\n'}{p('"dev"')}: {s('"next dev"')}  {c('// that\'s it')}</> },
    { icon: '⌬', zh: { title: <>统一依赖图省一遍活</>, desc: <>client / server / edge 共一张模块图, 跨环境共享的模块只算一次。webpack 要跑多个 compiler 再拼 bundle, 这部分重复计算在 Turbopack 里被消掉。</> }, en: { title: <>Unified graph avoids double work</>, desc: <>Client / server / edge share one module graph; modules shared across environments are computed once. Webpack ran multiple compilers and stitched bundles — that duplicated work is eliminated in Turbopack.</> }, code: <>{c('// shared util compiled once,')}{'\n'}{c('// reused across client + server bundles')}</> },
    { icon: '⛯', zh: { title: <>Rust 跑满多核</>, desc: <>引擎用 Rust 写, 解析 / 转换 / 打包并行铺到所有 CPU 核。SWC (同样 Rust) 处理 TS / JSX 转换, 比 Babel 快一个量级。冷启动与重建都因此显著缩短。</> }, en: { title: <>Rust saturates all cores</>, desc: <>The engine is Rust; parsing / transforming / bundling fan out across every CPU core. SWC (also Rust) handles TS / JSX transforms an order of magnitude faster than Babel. Cold start and rebuilds both shrink noticeably.</> }, code: <>{c('// parallelized across cores via Rust')}</> },
    { icon: '◷', zh: { title: <>文件系统缓存跨重启</>, desc: <>Turbopack 的 filesystem cache (dev 默认开、build opt-in) 把构建产物落盘, 关掉 dev server 再开不用从头编。大项目热启动比冷启动快得多。</> }, en: { title: <>Filesystem cache across restarts</>, desc: <>Turbopack's filesystem cache (on by default in dev, opt-in for build) persists build artifacts to disk, so restarting the dev server skips compiling from scratch. Warm starts on large apps are far faster than cold.</> }, code: <>{c('// experimental.turbopackFileSystemCacheForDev: true')}{'\n'}{c('// (default in Next 16)')}</> },
    { icon: '⎈', zh: { title: <>loader 兼容, 平滑迁移</>, desc: <>webpack <strong>loader</strong> 大多直接可接 (<code>turbopack.rules</code>), 从 webpack 迁过来不必重写资源处理。只是 webpack <strong>plugin</strong> 用不了 —— 这条边界要提前知道。</> }, en: { title: <>Loader-compatible, smooth migration</>, desc: <>Most webpack <strong>loaders</strong> plug in directly via <code>turbopack.rules</code>, so migrating from webpack doesn't require rewriting asset handling. Only webpack <strong>plugins</strong> don't apply — a boundary to know up front.</> }, code: <>{p('turbopack')}: {'{ '}{p('rules')}: {'{ '}{s('"*.svg"')}: [{s('"@svgr/webpack"')}] {'}'} {'}'}</> },
    { icon: '⊕', zh: { title: <>跟着 Next 一起走</>, desc: <>Turbopack 是 Next 的内核, 不单独发行。RSC、Server Actions、App Router 的打包细节由它处理。用 Next 16 就在用 Turbopack, React 团队的新原语在这里第一时间被正确打包。</> }, en: { title: <>Tracks Next.js</>, desc: <>Turbopack is Next's core, not shipped separately. The bundling details of RSC, Server Actions, and the App Router are its job. Using Next 16 means using Turbopack, and React's newest primitives are correctly bundled here first.</> }, code: <>{c('// RSC / Server Actions bundled by Turbopack')}</> },
  ],
  adopters: [
    { name: 'Next.js', href: 'https://nextjs.org', highlight: true, zhNote: 'Turbopack 的宿主, 16 起默认内核', enNote: "Turbopack's host — the default core since v16" },
    { name: 'Vercel', href: 'https://vercel.com', highlight: true, zhNote: '出品方, Koppers 在此主导开发', enNote: 'Maker — Koppers leads development here' },
    { name: 'OpenAI', href: 'https://openai.com', zhNote: 'ChatGPT 等 Next 前端默认走它', enNote: 'ChatGPT and other Next frontends default to it' },
    { name: 'Notion', href: 'https://notion.so', zhNote: 'Next 营销 / 文档站', enNote: 'Next marketing / docs site' },
    { name: 'TikTok', href: 'https://tiktok.com', zhNote: 'Web 端 Next 应用', enNote: 'Web frontend on Next' },
    { name: 'Twitch', href: 'https://twitch.tv', zhNote: '部分页面 Next 渲染', enNote: 'Parts of the site rendered with Next' },
    { name: 'Nike', href: 'https://nike.com', zhNote: 'Vercel showcase 长期案例', enNote: 'Long-standing Vercel showcase case' },
    { name: 'Hulu', href: 'https://hulu.com', zhNote: '流媒体 Next 前端', enNote: 'Streaming Next frontend' },
    { name: 'Audible', href: 'https://audible.com', zhNote: 'Amazon 旗下 Next 前端', enNote: 'Amazon-owned Next frontend' },
    { name: 'Linear', href: 'https://linear.app', zhNote: '营销站 + 文档 Next', enNote: 'Marketing site + docs on Next' },
    { name: 'Washington Post', href: 'https://washingtonpost.com', zhNote: '部分内容线用 Next', enNote: 'Parts of its content runs Next' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本站 client-next dev 打包 + HMR 全 Turbopack', enNote: 'This site — client-next dev bundling + HMR all on Turbopack' },
  ],
  outlook: [
    { tag: <>HOT · 2025-10</>, hot: true, big: true, zh: { title: <>Next 16 设为默认内核</>, body: <><p>Next 16 (2025-10-21 GA) 把 <code>next dev</code> 与 <code>next build</code> 默认都切到 Turbopack, webpack 退到 <code>--webpack</code> opt-out。dev Fast Refresh 快约 10x, 生产 build 快 2-5x。</p><p>更深一层:Turbopack 三年从 "有争议的 alpha demo" 走到 "用 Next 就在用、不需要知道它存在" 的默认。Turbo engine 那套函数级增量缓存终于在真实大项目上被验证。接下来一年重点从 "证明能用" 转向 "补齐 webpack 仍领先的边角"。</p></> }, en: { title: <>Next 16 makes it the default core</>, body: <><p>Next 16 (GA 2025-10-21) switches both <code>next dev</code> and <code>next build</code> to Turbopack by default, with webpack demoted to a <code>--webpack</code> opt-out. Dev Fast Refresh is ~10× faster; production builds 2-5× faster.</p><p>The deeper point: over three years Turbopack went from "a controversial alpha demo" to "the default you use whenever you use Next, without needing to know it exists." The Turbo engine's function-level incremental cache is finally proven on real large projects. The next year's focus shifts from "prove it works" to "close the edges where webpack still leads."</p></> } },
    { tag: 'FS-CACHE', big: true, zh: { title: <>文件系统缓存转正</>, body: <><p>Turbopack 的 filesystem cache 把构建产物落盘, 关掉 dev server 再开不用从头编。Next 16 里 dev 端默认开, build 端 (<code>turbopackFileSystemCacheForBuild</code>) 仍 opt-in。</p><p>这是 "Turbopack 不只是 dev 快, 而是冷热构建都快" 的关键拼图。build 端转默认后, CI 与本地的二次构建都会显著缩短 —— 也让 Turbopack 跟 webpack 的 disk cache 在生产场景正面对齐。</p></> }, en: { title: <>Filesystem cache graduates</>, body: <><p>Turbopack's filesystem cache persists build artifacts to disk so restarting the dev server skips compiling from scratch. In Next 16 it's on by default for dev; the build side (<code>turbopackFileSystemCacheForBuild</code>) is still opt-in.</p><p>This is the key piece for "Turbopack isn't just dev-fast, it's fast cold and warm." Once the build side defaults on, second builds in CI and locally shrink markedly — putting Turbopack head-to-head with webpack's disk cache in production scenarios.</p></> } },
    { tag: 'PLUGINS', zh: { title: <>webpack plugin 缺口</>, body: <><p>Turbopack 支持 webpack <strong>loader</strong> 但不支持 webpack <strong>plugin</strong>。依赖 plugin 系统集成的第三方工具 (某些分析器 / 注入器) 暂时迁不过来, 只能找 Turbopack 兼容替代或继续用 <code>--webpack</code>。一个兼容层或等价机制是社区呼声最高的待办。</p></> }, en: { title: <>The webpack-plugin gap</>, body: <><p>Turbopack supports webpack <strong>loaders</strong> but not webpack <strong>plugins</strong>. Third-party tools that integrate via the plugin system (certain analyzers / injectors) can't migrate yet — you find a Turbopack-compatible alternative or stay on <code>--webpack</code>. A compatibility layer or equivalent mechanism is the community's most-requested item.</p></> } },
    { tag: 'STANDALONE', zh: { title: <>脱离 Next 独立用</>, body: <><p>今天 Turbopack 只作为 Next 的内建内核存在, 不能像 Vite / esbuild 那样独立装来打任意项目。官方文档已提到 "standalone 用法将来可能需要 loader config" —— 把 Turbopack 做成框架无关的通用打包器是长期方向, 但远未到。</p></> }, en: { title: <>Standalone use outside Next</>, body: <><p>Today Turbopack exists only as Next's built-in core; you can't install it standalone to bundle arbitrary projects the way you can Vite / esbuild. The docs already note "standalone usage will likely require a loader config" — making Turbopack a framework-agnostic general bundler is a long-term direction, but far off.</p></> } },
    { tag: 'RUST', zh: { title: <>跟 Turborepo 共享后端</>, body: <><p>长期方向:Turbopack 跟同公司的 Turborepo 共享同一份 Rust 写的依赖图 / 缓存内核。两者用途完全不同 (前者打包模块, 后者编排任务), 但底层 "算输入 hash + 命中就重放" 的增量逻辑同源。共底层意味着一边的优化两边同时受益 —— 也是这两个名字像的产品唯一真正的交集。</p></> }, en: { title: <>Shared backend with Turborepo</>, body: <><p>Long-term: Turbopack shares a Rust dep-graph / cache kernel with the same company's Turborepo. Their jobs are entirely different (bundle modules vs orchestrate tasks), but the underlying "hash inputs, replay on hit" incremental logic is shared. A common backend means a win on one side lands on both — and it's the only real intersection between these two similarly-named products.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本站主工作区 <code>core/packages/client-next</code> 是 <strong>Next.js 16 App Router + React 19 + Turbopack</strong>。<code>next dev</code> 跑在 <code>http://127.0.0.1:3000/</code>, dev 阶段的打包与 HMR 就是 Turbopack —— 改一行组件 Fast Refresh 不刷页面、不丢路由 state, 几十毫秒内界面更新。这一切零配置, <code>package.json</code> 里就一句 <code>"dev": "next dev"</code>。</p>
        <p>这是本站 bundler 的<strong>第二代</strong>。退役的 <code>packages/client</code> (Vite SPA, 现仅本地回滚兜底, 见 <code>/code/stack/vite</code>) 用的是 Vite + webpack 那一代。2026-05 的 Phase 4 把整站从 Vite SPA 切到 Next 16, dev 这一侧的打包器也随之从 Vite / webpack 换成 Turbopack。两代 bundler 解决同一个问题 (大项目改一行怎么秒级更新), 选的路不同:Vite dev 不打包走原生 ESM, Turbopack dev 仍打包但缓存到函数级。本站 ~128 个页面默认 SSG, dev 下 Turbopack 的 lazy bundling 只编你正访问的那条路由, 没点开的页面根本不进图。</p>
        <p>诚实说清生产构建:本站的 <code>next build</code> 在 Next 16 默认走 Turbopack, 这一侧的文件系统缓存 (<code>turbopackFileSystemCacheForBuild</code>) 仍是 opt-in, 没主动开 —— CI 每次冷构建, 没到要靠它省时间的体量。dev 端的文件系统缓存是 Next 16 默认开的, 关掉 dev server 再开不用从头编。要退回 webpack 只需 <code>next build --webpack</code>, 但没理由这么做。</p>
        <p>一个反复要澄清的点:本仓库的 monorepo (<code>core/</code> 下 5 个 workspace 包) 任务编排走的是 <strong>Turborepo</strong> (<code>turbo build</code> / <code>turbo typecheck</code>, 见 <code>/code/stack/turbo</code>), 跟本页的 <strong>Turbopack</strong> 是<strong>两个不同的东西</strong>。Turbopack 打包模块 (Next 内核), Turborepo 编排任务 (pnpm + Turborepo 跑全 workspace 的 build / typecheck)。同公司 Vercel、名字像、用途完全不同。本站两个都用, 一个在 Next 里默默打包, 一个在命令行串任务。</p>
      </>
    ),
    en: (
      <>
        <p>This site's primary workspace <code>core/packages/client-next</code> is <strong>Next.js 16 App Router + React 19 + Turbopack</strong>. <code>next dev</code> runs at <code>http://127.0.0.1:3000/</code>, and the dev-side bundling and HMR are Turbopack — edit one component and Fast Refresh updates the UI in tens of milliseconds without a reload or route-state loss. All zero-config; <code>package.json</code> just has <code>"dev": "next dev"</code>.</p>
        <p>This is the site's <strong>second bundler generation</strong>. The retired <code>packages/client</code> (a Vite SPA, now only a local rollback fallback — see <code>/code/stack/vite</code>) was the Vite + webpack generation. Phase 4 (2026-05) cut the whole site from a Vite SPA to Next 16, and the dev-side bundler moved from Vite / webpack to Turbopack along with it. Both generations solve the same problem (how a large app updates in milliseconds after a one-line edit) via different paths: Vite skips bundling in dev and serves native ESM, while Turbopack still bundles in dev but caches at the function level. This site's ~128 pages are SSG by default, and in dev Turbopack's lazy bundling only compiles the route you're visiting — pages you never open never enter the graph.</p>
        <p>To be honest about production builds: this site's <code>next build</code> defaults to Turbopack on Next 16, and the build-side filesystem cache (<code>turbopackFileSystemCacheForBuild</code>) is still opt-in and not enabled here — CI does a cold build each time, below the scale where it'd pay off. The dev-side filesystem cache is on by default in Next 16, so restarting the dev server skips compiling from scratch. Falling back to webpack is just <code>next build --webpack</code>, but there's no reason to.</p>
        <p>A point that constantly needs clarifying: this repo's monorepo (five workspace packages under <code>core/</code>) is task-orchestrated by <strong>Turborepo</strong> (<code>turbo build</code> / <code>turbo typecheck</code> — see <code>/code/stack/turbo</code>), which is a <strong>different thing</strong> from this page's <strong>Turbopack</strong>. Turbopack bundles modules (Next's core); Turborepo orchestrates tasks (pnpm + Turborepo running build / typecheck across the workspace). Same parent (Vercel), similar names, completely different jobs. This site uses both — one quietly bundling inside Next, one threading tasks at the command line.</p>
      </>
    ),
  },
  links: [
    { label: 'Turbopack docs (nextjs.org)', href: 'https://nextjs.org/docs/app/api-reference/turbopack' },
    { label: 'GitHub · vercel/next.js (turbopack)', href: 'https://github.com/vercel/next.js/tree/canary/turbopack' },
    { label: 'The Turbopack vision', href: 'https://vercel.com/blog/the-turbopack-vision' },
    { label: 'Next.js 16 announcement', href: 'https://nextjs.org/blog/next-16' },
    { label: 'Turbopack moving homes (Vercel)', href: 'https://vercel.com/blog/turbopack-moving-homes' },
  ],
};

export default TURBOPACK;
