import type { StackTool } from '../_lib/stack_tool_types';
import { v, f, p, c } from '../_lib/stack_tool_types';

// ─── Windows ──────────────────────────────────────────────────────────────────

export const WINDOWS: StackTool = {
  slug: 'windows',
  name: 'Windows',
  version: '11 25H2',
  since: '1985-11',
  group: 'dev',
  accent: '#0078D4',
  bright: '#4CA0E0',
  glyph: '▦',
  floats: ['NT kernel', 'Win32', 'NTFS', 'registry', 'WSL2', 'PowerShell', 'DirectX', 'Hyper-V', 'PE/COFF', 'HAL', 'CSRSS', 'WDDM'],
  zh: {
    tagline: '桌面操作系统 + NT 内核 + Win32 生态',
    role: '本仓库的主开发机就是它。每一行代码在 Windows 11 Pro 上写, pwsh 做 shell, 127.0.0.1:3000 跑 dev。',
    heroSub: <>从 1985 年套在 MS-DOS 上的一层图形外壳, 到 1993 年 Dave Cutler 团队从零写出的 <strong>NT 内核</strong>, 再到今天装在十几亿台设备上的 Windows 11。它不是一个东西, 是两条血脉:消费线 (1.0 → 95 → 98 → ME) 和 NT 线 (NT 3.1 → 2000 → XP → 11), XP 把两条合一, 之后所有 Windows 都是 NT。</>,
    whatDesc: <>Windows 是一个<strong>抢占式多任务、虚拟内存、微内核混合架构</strong>的桌面操作系统。底层是 NT 内核 (ntoskrnl.exe) + 硬件抽象层 (HAL), 上面是 Win32 子系统 / 注册表 / NTFS 文件系统 / 图形栈 (DWM + DirectX)。它最值钱的资产不是内核本身, 而是<strong>三十年向后兼容</strong> —— 1995 年编译的 Win32 程序今天大概率还能跑。这条兼容性铁律是它桌面统治力的根。</>,
    historyDesc: <>从 1985 年 11 月 Windows 1.0 (一层 DOS 上的图形 shell), 到 2025 年 9 月 Windows 11 25H2, 四十年。中间最大的几个分水岭:1990 年 3.0 让 Windows 真正起飞、1993 年 NT 3.1 引入现代内核、1995 年 95 把开始菜单和 32 位带给消费者、2001 年 XP 统一两条产品线、2009 年 7 修复 Vista、2015 年 10 转向"Windows as a Service"、2016 年 WSL 把 Linux 装进 Windows、2024 年 Copilot+ PC 把 NPU 推进 OS。</>,
    conceptsTitle: 'NT 内核 + 子系统',
    conceptsDesc: <>表面是开始菜单和窗口, 底层是一个设计精巧的混合内核。核心模型:NT executive 提供 object manager / 进程线程 / 虚拟内存 / IO, 上面挂多个"子系统" (Win32 / 过去的 POSIX / 今天的 WSL2)。注册表 / NTFS / PE 格式 / DirectX 都是围绕这套架构长出来的。</>,
    whyDesc: <>2026 年选 Windows 做开发机, 不是因为它"对开发者最友好" (Unix 那套工具链原生在 macOS / Linux 上更顺), 而是因为<strong>它是用户在的地方</strong> + WSL2 抹平了 Linux 工具链的鸿沟。桌面占有率七成以上, 加上 DirectX / 硬件兼容 / 三十年软件库, 换它的成本远大于忍它的痛点。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>桌面 / 笔记本市场份额长期 70% 以上。从政府 / 银行 / 医院的内网终端, 到游戏玩家 (DirectX + 几乎所有 PC 游戏的首发平台), 到企业 Active Directory 域, 到本仓库这台开发机。NT 内核还撑着 Xbox 和 Azure 的部分基础设施。</>,
    cuberootDesc: <>本仓库 <code>RuiminYan/cuberoot.me</code> 的主开发机就是 Windows 11 Pro。全程 pwsh 7 做 shell, Next dev 绑 <code>127.0.0.1:3000</code> (绕开 Windows Chrome IPv6 解析 localhost 的坑), 换行符锁 LF (<code>.gitattributes</code> + <code>core.autocrlf=false</code>)。本地 PG 走 docker, 缺的 Unix 命令 (<code>handle.exe</code> / <code>fd</code> / <code>jq</code>) 单装补齐。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>25H2 是 enablement package, 大动作在 Copilot+ PC —— NPU 算力进 OS, 本地小模型跑 Recall / Click to Do / 实时字幕。WSL2 在 2025 年 5 月开源, Windows 与 Linux 工具链的边界越来越模糊。同时 Windows 10 在 2025-10-14 终止支持, 推着一波硬件 (TPM 2.0 要求) 和系统迁移。</>,
  },
  en: {
    tagline: 'Desktop operating system + NT kernel + Win32 ecosystem',
    role: "This repo's main dev machine. Every line is written on Windows 11 Pro — pwsh as the shell, dev on 127.0.0.1:3000.",
    heroSub: <>From a 1985 graphical shell layered over MS-DOS, to the <strong>NT kernel</strong> Dave Cutler's team wrote from scratch in 1993, to today's Windows 11 on well over a billion devices. It isn't one thing but two bloodlines: the consumer line (1.0 → 95 → 98 → ME) and the NT line (NT 3.1 → 2000 → XP → 11). XP fused them; every Windows since is NT.</>,
    whatDesc: <>Windows is a <strong>preemptive multitasking, virtual-memory, hybrid-kernel</strong> desktop OS. At the bottom: the NT kernel (ntoskrnl.exe) plus a hardware abstraction layer (HAL); above it the Win32 subsystem, the registry, the NTFS file system, and the graphics stack (DWM + DirectX). Its most valuable asset isn't the kernel — it's <strong>thirty years of backward compatibility</strong>. A Win32 binary built in 1995 will very likely still run today. That compatibility law is the root of its desktop dominance.</>,
    historyDesc: <>From Windows 1.0 in November 1985 (a graphical shell over DOS) to Windows 11 25H2 in September 2025 — forty years. The biggest watersheds: 3.0 (1990) made Windows take off; NT 3.1 (1993) introduced the modern kernel; 95 brought the Start menu and 32-bit to consumers; XP (2001) unified the two product lines; 7 (2009) fixed Vista; 10 (2015) shifted to "Windows as a Service"; WSL (2016) put Linux inside Windows; Copilot+ PC (2024) pushed the NPU into the OS.</>,
    conceptsTitle: 'NT kernel + subsystems',
    conceptsDesc: <>The surface is a Start menu and windows; underneath is a carefully designed hybrid kernel. The core model: the NT executive supplies the object manager / processes-threads / virtual memory / I/O, with several "subsystems" hung above it (Win32, the former POSIX, today's WSL2). The registry, NTFS, the PE format, and DirectX all grew around this architecture.</>,
    whyDesc: <>Picking Windows as a dev box in 2026 isn't because it's "the most developer-friendly" (the Unix toolchain runs more natively on macOS / Linux) — it's because <strong>that's where the users are</strong>, and WSL2 erased the Linux-toolchain gap. With 70%+ desktop share plus DirectX / hardware compatibility / a thirty-year software library, the switching cost dwarfs the pain.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Desktop / laptop share has sat above 70% for years. From government / bank / hospital intranet terminals, to gamers (DirectX, plus the launch platform for nearly every PC title), to enterprise Active Directory domains, to this repo's dev machine. The NT kernel also underpins Xbox and parts of Azure's infrastructure.</>,
    cuberootDesc: <>The main dev machine for <code>RuiminYan/cuberoot.me</code> is Windows 11 Pro. Shell is pwsh 7 throughout; Next dev binds <code>127.0.0.1:3000</code> (sidestepping the Windows-Chrome quirk where it resolves localhost over IPv6); line endings are locked to LF (<code>.gitattributes</code> + <code>core.autocrlf=false</code>). Local PG runs in docker, and the missing Unix commands (<code>handle.exe</code> / <code>fd</code> / <code>jq</code>) are installed to fill the gaps.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>25H2 is an enablement package; the real action is Copilot+ PC — NPU compute moves into the OS, with local small models powering Recall / Click to Do / live captions. WSL2 was open-sourced in May 2025, blurring the line between the Windows and Linux toolchains. Meanwhile Windows 10 reached end of support on 2025-10-14, forcing a wave of hardware (TPM 2.0 requirement) and system migrations.</>,
  },
  heroStats: [
    { num: '11', unit: ' 25H2', zh: <>当前稳定版 <em>2025-09-30 · build 26200</em></>, en: <>current stable <em>2025-09-30 · build 26200</em></> },
    { num: '40', unit: 'y', zh: <>从 1985 至今 <em>桌面统治力 30 年</em></>, en: <>since 1985 <em>30 years of desktop dominance</em></> },
    { num: '~30', unit: 'y', zh: <>Win32 向后兼容 <em>1995 的二进制大概率还能跑</em></>, en: <>of Win32 backward compat <em>a 1995 binary likely still runs</em></> },
    { num: '70', unit: '%+', zh: <>桌面 / 笔记本份额 <em>长期第一</em></>, en: <>desktop / laptop share <em>top for years</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>Windows 不是一个东西, 是两条血脉缝在一起的产物。1985 年 11 月发布的 Windows 1.0 只是套在 MS-DOS 上的一层图形外壳 —— 没有重叠窗口 (专利顾虑, 只能平铺), 实质是 DOS 之上的一个程序。真正让它起飞的是 1990 年的 3.0:虚拟内存、保护模式、像样的 GUI, 一年卖出上千万份, 微软第一次相信图形界面有商业价值。</p>
        <p>另一条线 1988 年才开始:微软挖来 DEC 的 Dave Cutler (VMS 内核的主设计师) 从零写一个现代操作系统内核, 即 NT (New Technology)。NT 3.1 (1993) 带来抢占式多任务、虚拟内存、NTFS、子系统架构 —— 这是今天 Windows 仍在跑的内核基础。两条线并行十年:消费者用 95 / 98 / ME (DOS 血统, 不稳但兼容性好玩游戏), 企业用 NT 4.0 / 2000 (稳但兼容性差)。</p>
        <p>2001 年 XP 把两条线合一 —— 消费者第一次拿到 NT 内核的稳定性, 同时保住向后兼容。此后所有 Windows 都是 NT:Vista (2007, 安全模型大改但口碑崩) → 7 (2009, 修好 Vista, 史上最受好评的一代) → 8 (2013, 平板赌注失败) → 10 (2015, "最后一个 Windows", 转 SaaS 模式) → 11 (2021, 重做 UI + TPM 2.0 硬性要求)。中间 2016 年 WSL 把 Linux 系统调用翻译层装进 Windows, 2024 年 Copilot+ PC 把 NPU 算力推进 OS, 2025 年 9 月 25H2 是当前稳定版。</p>
      </>
    ),
    en: (
      <>
        <p>Windows isn't one thing — it's two bloodlines stitched together. Windows 1.0, released in November 1985, was just a graphical shell over MS-DOS: no overlapping windows (patent worries forced tiling), essentially a program on top of DOS. What made it take off was 3.0 in 1990: virtual memory, protected mode, a credible GUI. It sold tens of millions in a year, and Microsoft first believed graphical UIs had commercial value.</p>
        <p>The other line began in 1988: Microsoft hired DEC's Dave Cutler (lead designer of the VMS kernel) to write a modern OS kernel from scratch — NT (New Technology). NT 3.1 (1993) brought preemptive multitasking, virtual memory, NTFS, and the subsystem architecture — the kernel foundation Windows still runs on today. The two lines ran in parallel for a decade: consumers on 95 / 98 / ME (DOS heritage, unstable but compatible enough for games), enterprises on NT 4.0 / 2000 (stable but compatibility-poor).</p>
        <p>In 2001, XP fused the two — consumers got NT-kernel stability for the first time while keeping backward compatibility. Every Windows since is NT: Vista (2007, a major security-model rework with a battered reputation) → 7 (2009, fixed Vista, the most beloved release) → 8 (2013, the failed tablet bet) → 10 (2015, "the last Windows," the pivot to SaaS) → 11 (2021, a UI redo plus a hard TPM 2.0 requirement). Along the way WSL (2016) put a Linux syscall-translation layer inside Windows, Copilot+ PC (2024) pushed NPU compute into the OS, and 25H2 (September 2025) is the current stable.</p>
      </>
    ),
  },
  history: [
    { year: '1985·11', zh: { title: <>Windows 1.0</>, desc: <>11 月 20 日发布。套在 MS-DOS 上的图形 shell, 窗口只能平铺 (重叠窗口有专利顾虑)。实质是 DOS 上一个程序, 商业上几乎没水花, 但开了图形界面的头。</> }, en: { title: <>Windows 1.0</>, desc: <>Released November 20. A graphical shell over MS-DOS; windows could only tile (overlapping ones had patent worries). Essentially a DOS program — a commercial non-event, but it opened the GUI door.</> } },
    { year: '1990·05', zh: { title: <>3.0 — 真正起飞</>, desc: <>虚拟内存、保护模式、能用的 Program Manager。一年卖上千万份, 微软第一次确信图形界面有商业价值。3.1 (1992) 加 TrueType 字体, 成为 90 年代初的标准。</> }, en: { title: <>3.0 — it takes off</>, desc: <>Virtual memory, protected mode, a usable Program Manager. Tens of millions sold in a year; Microsoft first became sure the GUI had commercial value. 3.1 (1992) added TrueType, becoming the early-'90s standard.</> } },
    { year: '1993·07', zh: { title: <>NT 3.1 — 现代内核</>, desc: <>Dave Cutler 团队从零写出的 NT 内核首发。抢占式多任务、NTFS、子系统架构、硬件抽象层。这是今天 Windows 11 仍在跑的内核血脉。</> }, en: { title: <>NT 3.1 — the modern kernel</>, desc: <>The from-scratch NT kernel by Dave Cutler's team debuts: preemptive multitasking, NTFS, subsystem architecture, hardware abstraction layer. This is the kernel lineage Windows 11 still runs on.</> } },
    { year: '1995·08', zh: { title: <>Windows 95</>, desc: <>8 月 24 日发布。开始菜单、任务栏、即插即用、32 位应用支持一次到位。排队抢购的盛况, 把 PC 带进千家万户。底层仍是 DOS 血统。</> }, en: { title: <>Windows 95</>, desc: <>Released August 24. The Start menu, taskbar, Plug and Play, and 32-bit app support all arrived at once. Midnight launch queues; it brought the PC into every home. Still DOS-lineage underneath.</> } },
    { year: '2001·10', zh: { title: <>XP — 两条线合一</>, desc: <>10 月 25 日发布。消费者第一次拿到 NT 内核的稳定性 + 保住向后兼容。生命周期长得离谱 (官方支持到 2014, 实际跑到更久), 史上影响力最大的一代之一。</> }, en: { title: <>XP — the two lines merge</>, desc: <>Released October 25. Consumers got NT-kernel stability while keeping backward compatibility. An absurdly long lifespan (official support to 2014, in practice far longer) — one of the most influential releases ever.</> } },
    { year: '2009·10', zh: { title: <>Windows 7</>, desc: <>修好 Vista 的 UAC 弹窗地狱和性能问题, 重做任务栏 (Superbar)。口碑封神, 企业升级率极高, 成为 XP 之后最被怀念的一代。</> }, en: { title: <>Windows 7</>, desc: <>Fixed Vista's UAC-prompt hell and performance, redesigned the taskbar (Superbar). Critically adored, high enterprise adoption — the most-missed release after XP.</> } },
    { year: '2015·07', zh: { title: <>Windows 10 — as a Service</>, desc: <>7 月 29 日发布, 宣传"最后一个 Windows"。转向 Windows as a Service:不再大版本买断, 改半年一次 feature update 持续滚动。重新引回开始菜单 (8 的全屏磁贴翻车后)。</> }, en: { title: <>Windows 10 — as a Service</>, desc: <>Released July 29, billed as "the last Windows." The pivot to Windows as a Service: no more big paid upgrades, instead rolling feature updates twice a year. The Start menu returns (after 8's full-screen-tiles flop).</> } },
    { year: '2016·08', zh: { title: <>WSL — Linux 装进 Windows</>, desc: <>Windows 10 周年更新引入 WSL 1, 一个把 Linux 系统调用翻译成 NT 系统调用的兼容层。开发者第一次能在 Windows 上原生跑 bash / apt / gcc, 不开虚拟机。</> }, en: { title: <>WSL — Linux inside Windows</>, desc: <>The Windows 10 Anniversary Update introduced WSL 1, a compatibility layer translating Linux syscalls into NT syscalls. Developers could run bash / apt / gcc natively on Windows for the first time, no VM.</> } },
    { year: '2019·05', zh: { title: <>WSL 2 — 真 Linux 内核</>, desc: <>5 月 6 日宣布。改用 Hyper-V 轻量虚拟机跑一个真的 Linux 内核, 完整系统调用兼容 + 接近原生的文件系统性能。WSL 1 的翻译层瓶颈被绕开。</> }, en: { title: <>WSL 2 — a real Linux kernel</>, desc: <>Announced May 6. Switches to a lightweight Hyper-V VM running a real Linux kernel: full syscall compatibility plus near-native file-system performance. WSL 1's translation-layer bottleneck is gone.</> } },
    { year: '2021·10', zh: { title: <>Windows 11</>, desc: <>10 月 5 日发布。居中开始菜单、圆角、新设计语言 (Fluent), 以及争议的硬性要求:TPM 2.0 + 较新 CPU, 把一大批旧机器挡在门外。</> }, en: { title: <>Windows 11</>, desc: <>Released October 5. A centered Start menu, rounded corners, a new design language (Fluent), and the controversial hard requirements: TPM 2.0 plus a recent CPU, locking out a large swath of older machines.</> } },
    { year: '2024·06', zh: { title: <>Copilot+ PC + NPU</>, desc: <>6 月起 24H2 在 Copilot+ PC 上 GA。把 NPU (神经处理单元, ≥40 TOPS) 算力推进 OS, 本地跑小模型驱动 Recall / Click to Do / 实时字幕 / Studio Effects。AI 第一次成为 OS 一等公民。</> }, en: { title: <>Copilot+ PC + NPU</>, desc: <>24H2 went GA on Copilot+ PCs from June. It pushes NPU compute (≥40 TOPS) into the OS, running local small models for Recall / Click to Do / live captions / Studio Effects. AI becomes a first-class OS citizen.</> } },
    { year: '2025·09', highlight: true, zh: { title: <>11 25H2 / 当前稳定</>, desc: <>9 月 30 日起推送。作为 enablement package 复用 24H2 (build 26200) 的底子, 一个开关点亮新特性。同月前后 WSL2 已开源 (5 月), Windows 10 即将 (10-14) 终止支持。</> }, en: { title: <>11 25H2 / current stable</>, desc: <>Rolling out from September 30. As an enablement package it reuses the 24H2 base (build 26200), flipping a switch to light up new features. Around the same window WSL2 was open-sourced (May) and Windows 10 nears end of support (Oct 14).</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>NT 内核 + executive</>, desc: <>核心是 <code>ntoskrnl.exe</code>:object manager 管一切内核对象, 加上进程线程调度 / 虚拟内存 / IO manager。HAL 把硬件差异藏在内核下面, 所以一份内核能跑在不同 CPU 架构上。</> }, en: { title: <>NT kernel + executive</>, desc: <>The core is <code>ntoskrnl.exe</code>: an object manager for every kernel object, plus the process/thread scheduler / virtual memory / I/O manager. The HAL hides hardware differences below the kernel, so one kernel runs across CPU architectures.</> }, code: <code>{p('PS>')} {f('Get-Process')} {p('-Name')} System{'\n'}{c('# the NT kernel runs as PID 4')}{'\n'}Handles  NPM(K)  Name{'\n'}{v('  3812')}    {v('0')}   System</code> },
    { tag: 'B', zh: { title: <>Win32 子系统</>, desc: <>应用不直接调内核, 而是调 Win32 API (<code>kernel32 / user32 / gdi32</code>)。这套 API 三十年保持兼容 —— 1995 年针对 Win32 编译的程序今天大概率还能跑, 这是 Windows 桌面统治的根。</> }, en: { title: <>Win32 subsystem</>, desc: <>Apps don't call the kernel directly — they call the Win32 API (<code>kernel32 / user32 / gdi32</code>). That API has stayed compatible for thirty years: a program compiled against Win32 in 1995 will very likely still run, the root of Windows' desktop dominance.</> }, code: <code>{c('// every Windows app, since 1995')}{'\n'}HWND h = {f('CreateWindowEx')}(...);{'\n'}{f('MessageBoxW')}(h, {v('L"hi"')}, {v('L"app"')}, {v('0')});</code> },
    { tag: 'C', zh: { title: <>NTFS 文件系统</>, desc: <>NT 3.1 带来的日志式文件系统。支持 ACL 权限、硬链接 / 符号链接 / junction、稀疏文件、压缩、加密 (EFS)、卷影副本。<code>$MFT</code> 主文件表是一切元数据的索引。</> }, en: { title: <>NTFS file system</>, desc: <>The journaling file system NT 3.1 introduced. ACL permissions, hard links / symlinks / junctions, sparse files, compression, encryption (EFS), shadow copies. The <code>$MFT</code> master file table indexes all metadata.</> }, code: <code>{p('PS>')} {f('New-Item')} {p('-ItemType')} SymbolicLink {p('`')}{'\n'}    {p('-Path')} link {p('-Target')} target{'\n'}{c('# NTFS reparse point, since NT 3.1')}</code> },
    { tag: 'D', zh: { title: <>注册表</>, desc: <>一个层级化的全局键值数据库, 取代了散落的 <code>.ini</code> 文件。<code>HKLM</code> (机器级) / <code>HKCU</code> (用户级) 是两个最常碰的根。pwsh 直接当文件系统 PSDrive 访问:<code>HKLM:\SOFTWARE\...</code>。</> }, en: { title: <>The registry</>, desc: <>A hierarchical global key-value database that replaced scattered <code>.ini</code> files. <code>HKLM</code> (machine) / <code>HKCU</code> (user) are the two roots you touch most. pwsh accesses it as a filesystem PSDrive: <code>HKLM:\SOFTWARE\...</code>.</> }, code: <code>{p('PS>')} {f('Get-ItemProperty')} {p('`')}{'\n'}    {v('HKCU:\\Environment')} {p('-Name')} Path{'\n'}{c('# read a user env var from the registry')}</code> },
    { tag: 'E', zh: { title: <>WSL2 — VM 里的真内核</>, desc: <>不是翻译层, 是一个 Hyper-V 轻量虚拟机跑真的 Linux 内核。完整系统调用兼容 + 接近原生的 IO。<code>\\wsl$\</code> 让 Windows 与 Linux 文件系统互访。2025 年 5 月已开源。</> }, en: { title: <>WSL2 — a real kernel in a VM</>, desc: <>Not a translation layer — a lightweight Hyper-V VM running a real Linux kernel. Full syscall compatibility plus near-native I/O. <code>\\wsl$\</code> bridges the Windows and Linux file systems. Open-sourced May 2025.</> }, code: <code>{p('PS>')} {f('wsl')} {p('--list')} {p('--verbose')}{'\n'}  NAME      STATE    VERSION{'\n'}* {v('Ubuntu')}    Running  {v('2')}</code> },
    { tag: 'F', zh: { title: <>PowerShell</>, desc: <>面向对象的 shell —— 管道里流的是 .NET 对象不是文本。PowerShell 7 基于 .NET 跨平台 (Win / macOS / Linux), 是 PowerShell Core (2018) 和 Windows PowerShell 5.1 的合流继任。本仓库全程用 pwsh 7。</> }, en: { title: <>PowerShell</>, desc: <>An object-oriented shell — the pipeline carries .NET objects, not text. PowerShell 7 is cross-platform on .NET (Win / macOS / Linux), the successor merging PowerShell Core (2018) and Windows PowerShell 5.1. This repo uses pwsh 7 throughout.</> }, code: <code>{p('PS>')} {f('Get-ChildItem')} {p('|') } {f('Where-Object')} {'{'} {v('$_')}.Length {p('-gt')} {v('1MB')} {'}'}{'\n'}{c('# objects flow through the pipe, not strings')}</code> },
    { tag: 'G', zh: { title: <>DirectX</>, desc: <>一组多媒体 API:Direct3D (3D 图形) / DirectCompute / DirectStorage / DirectML。它是 PC 游戏的事实标准图形层, 也是 Windows 区别于其他桌面 OS 的硬护城河 —— 几乎所有 AAA 游戏先发 Windows。</> }, en: { title: <>DirectX</>, desc: <>A multimedia API set: Direct3D (3D graphics) / DirectCompute / DirectStorage / DirectML. The de-facto graphics layer for PC gaming and Windows' hard moat against other desktop OSes — nearly every AAA title launches on Windows first.</> }, code: <code>{c('// Direct3D 12 command queue')}{'\n'}{f('ID3D12Device::CreateCommandQueue')}(...);{'\n'}{f('ExecuteCommandLists')}(...);</code> },
    { tag: 'H', zh: { title: <>Hyper-V + 虚拟化安全</>, desc: <>Type-1 hypervisor 内建在 OS。WSL2 / Windows Sandbox / WSA 都跑在它上。现代 Windows 把内核本身放进一个虚拟化保护层 (VBS / HVCI), 用硬件虚拟化隔离 credential 和内核内存。</> }, en: { title: <>Hyper-V + virtualization security</>, desc: <>A Type-1 hypervisor built into the OS. WSL2 / Windows Sandbox / WSA all ride it. Modern Windows places the kernel itself inside a virtualization-based protection layer (VBS / HVCI), isolating credentials and kernel memory via hardware virtualization.</> }, code: <code>{p('PS>')} {f('Get-WindowsOptionalFeature')} {p('-Online')} {p('`')}{'\n'}    {p('-FeatureName')} Microsoft-Hyper-V{'\n'}State : {v('Enabled')}</code> },
  ],
  whyCards: [
    { icon: '▦', zh: { title: <>三十年向后兼容</>, desc: <>1995 年编译的 Win32 程序今天大概率还能跑。这条铁律是企业 / 政府 / 工业软件锁在 Windows 上的根 —— 它们的祖传软件没人敢重写, 而 Windows 保证它一直能跑。</> }, en: { title: <>Thirty years of backward compat</>, desc: <>A Win32 binary from 1995 will very likely still run today. That law is why enterprise / government / industrial software is locked to Windows — nobody dares rewrite legacy apps, and Windows guarantees they keep running.</> }, code: <>{c('// vc6 binary from 1998')}{'\n'}{f('app.exe')} {c('// still runs on Windows 11')}</> },
    { icon: '◧', zh: { title: <>用户在哪里</>, desc: <>桌面 / 笔记本份额七成以上。做面向普通用户的桌面软件, 第一目标平台永远是 Windows。这不是技术优劣, 是装机量决定的现实。</> }, en: { title: <>Where the users are</>, desc: <>70%+ desktop / laptop share. Building consumer desktop software, the first target is always Windows. Not a tech-merit question — an install-base reality.</> }, code: <>{c('// market share, desktop')}{'\n'}Windows {v('~71%')}  macOS {v('~16%')}  Linux {v('~4%')}</> },
    { icon: '◨', zh: { title: <>WSL2 抹平 Unix 鸿沟</>, desc: <>过去 Windows 做 web 开发的最大痛点是 Unix 工具链别扭。WSL2 装一个真 Linux 内核, bash / docker / make 原生跑, 文件系统接近原生速度。一台机器 Windows GUI + Linux 工具链。</> }, en: { title: <>WSL2 erases the Unix gap</>, desc: <>Windows web dev's biggest pain was the awkward Unix toolchain. WSL2 ships a real Linux kernel — bash / docker / make run natively at near-native FS speed. One machine: Windows GUI plus Linux tooling.</> }, code: <>{f('wsl')} {p('--install')}{'\n'}{c('// real Linux kernel, one command')}</> },
    { icon: '◩', zh: { title: <>DirectX = 游戏护城河</>, desc: <>几乎所有 PC 游戏先发 Windows, 因为 DirectX 是事实标准图形层 + 硬件驱动最全。这条护城河三十年没人攻破, 是 Windows 在消费端的硬资产。</> }, en: { title: <>DirectX = the gaming moat</>, desc: <>Nearly every PC game launches on Windows first, because DirectX is the de-facto graphics layer with the broadest driver support. A moat unbreached for thirty years — Windows' hard consumer asset.</> }, code: <>{c('// game targets')}{'\n'}Direct3D 12 {p('->')} Windows / Xbox</> },
    { icon: '◪', zh: { title: <>pwsh = 对象化 shell</>, desc: <>PowerShell 管道里流的是 .NET 对象, <code>Get-Process | Where Length -gt 1MB</code> 不用 parse 文本。比起 bash 的"全是字符串", 结构化数据处理更直接。本仓库脚本全用 pwsh 7。</> }, en: { title: <>pwsh = an object shell</>, desc: <>The PowerShell pipeline carries .NET objects — <code>Get-Process | Where Length -gt 1MB</code> needs no text parsing. More direct for structured data than bash's everything-is-a-string. This repo's scripts are all pwsh 7.</> }, code: <>{f('Get-Service')} {p('|')} {f('Sort-Object')} Status{'\n'}{c('// objects, not text columns')}</> },
    { icon: '◫', zh: { title: <>Active Directory = 企业身份</>, desc: <>AD 是企业内网身份 / 权限 / 策略的事实标准。一个域控管几万台机器的登录、组策略、软件分发。这套深度集成把大企业牢牢绑在 Windows 服务端 + 客户端上。</> }, en: { title: <>Active Directory = enterprise identity</>, desc: <>AD is the de-facto standard for enterprise identity / permissions / policy. One domain controller manages logins, group policy, and software distribution for tens of thousands of machines. That integration binds large enterprises to Windows server and client.</> }, code: <>{c('// group policy applies on login')}{'\n'}{f('gpupdate')} /force</> },
    { icon: '▤', zh: { title: <>NPU 进 OS</>, desc: <>Copilot+ PC 把 NPU (≥40 TOPS) 算力做成 OS 一等资源, 本地小模型驱动 Recall / 实时字幕 / Studio Effects, 不上云。AI 推理从"应用各自为政"变成 OS 提供的能力。</> }, en: { title: <>NPU in the OS</>, desc: <>Copilot+ PC makes NPU (≥40 TOPS) compute a first-class OS resource — local small models power Recall / live captions / Studio Effects without the cloud. AI inference shifts from "each app's own thing" to an OS-provided capability.</> }, code: <>{c('// local inference, on-device NPU')}{'\n'}Windows ML {p('->')} NPU</> },
    { icon: '▥', zh: { title: <>硬件兼容广度</>, desc: <>从二十年前的打印机到最新显卡, Windows 的驱动库覆盖面没有对手。装一台新机插上各种外设大概率即插即用 —— 这是 OEM 生态三十年共建的结果, 也是迁出 Windows 最现实的阻力。</> }, en: { title: <>Hardware compatibility breadth</>, desc: <>From a twenty-year-old printer to the newest GPU, Windows' driver library has no rival in breadth. Plug peripherals into a fresh machine and they mostly just work — the product of a thirty-year OEM ecosystem, and the most real barrier to leaving Windows.</> }, code: <>{c('// plug-and-play since 95')}{'\n'}{f('pnputil')} /enum-devices</> },
  ],
  adopters: [
    { name: 'Enterprise / Active Directory', zhNote: '企业内网身份 + 组策略 + 软件分发的事实标准', enNote: 'De-facto standard for enterprise identity, group policy, software distribution' },
    { name: 'Government / banking / hospitals', zhNote: '内网终端与祖传软件深度绑定 Win32 兼容性', enNote: 'Intranet terminals and legacy apps locked to Win32 compatibility' },
    { name: 'PC gaming', href: 'https://store.steampowered.com', highlight: true, zhNote: '几乎所有 PC 游戏首发平台, DirectX 是图形护城河', enNote: 'Launch platform for nearly every PC title; DirectX is the moat' },
    { name: 'Xbox', href: 'https://www.xbox.com', highlight: true, zhNote: '主机系统跑 NT 内核的定制变体', enNote: 'The console OS runs a custom variant of the NT kernel' },
    { name: 'Steam (Valve)', href: 'https://store.steampowered.com', zhNote: '最大 PC 游戏分发平台, 主力客户端在 Windows', enNote: "Largest PC game store; its core client lives on Windows" },
    { name: 'Adobe Creative Cloud', href: 'https://www.adobe.com', zhNote: '专业创意软件的主力桌面平台之一', enNote: 'A primary desktop platform for professional creative software' },
    { name: 'AutoCAD / SolidWorks', zhNote: '工业 / 工程 CAD 软件几乎独占 Windows', enNote: 'Industrial / engineering CAD software is almost Windows-exclusive' },
    { name: 'Office desktop suite', href: 'https://www.microsoft.com/microsoft-365', zhNote: 'Word / Excel / PowerPoint 桌面版的原生家园', enNote: 'The native home of desktop Word / Excel / PowerPoint' },
    { name: 'Bloomberg Terminal', zhNote: '金融行业终端长期绑定 Windows 客户端', enNote: 'Finance-industry terminal long bound to its Windows client' },
    { name: 'Schools / labs', zhNote: '教育机房与公共终端的默认装机系统', enNote: 'The default image for school labs and public terminals' },
    { name: 'Steam Deck (contrast)', href: 'https://www.steamdeck.com', zhNote: '反例 — 用 Linux + Proton 翻译 DirectX, 证明护城河可被侵蚀', enNote: 'A counter-example — Linux + Proton translating DirectX, proving the moat is erodible' },
    { name: 'Microsoft Azure', href: 'https://azure.microsoft.com', zhNote: 'NT 内核技术也撑着部分云基础设施', enNote: 'NT kernel tech also underpins parts of the cloud infrastructure' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本仓库 — 主开发机就是 Windows 11 Pro, pwsh 做 shell', enNote: 'This repo — main dev machine is Windows 11 Pro, pwsh as the shell' },
  ],
  outlook: [
    { tag: <>HOT · 2024-2026</>, hot: true, big: true, zh: { title: <>Copilot+ PC: NPU 进 OS</>, body: <><p>Copilot+ PC 把 NPU (神经处理单元, ≥40 TOPS) 做成操作系统的一等算力资源。本地小模型驱动 Recall (语义化操作历史) / Click to Do / 实时字幕 / Studio Effects, 推理不上云。Windows ML 给应用一个统一接口调 NPU。</p><p>这是 Windows 二十年来对 OS 角色最大的一次重定义 —— 从"运行应用的平台"变成"提供 AI 能力的平台"。同时 Recall 的隐私争议 (本地截图建索引) 也暴露了把 AI 塞进 OS 的边界问题, 微软被迫加了加密 + 显式 opt-in。</p></> }, en: { title: <>Copilot+ PC: NPU in the OS</>, body: <><p>Copilot+ PC makes the NPU (neural processing unit, ≥40 TOPS) a first-class OS compute resource. Local small models power Recall (semantic activity history) / Click to Do / live captions / Studio Effects, with inference staying on-device. Windows ML gives apps one interface to the NPU.</p><p>It's Windows' biggest redefinition of the OS role in twenty years — from "a platform that runs apps" to "a platform that provides AI." Recall's privacy fight (indexing local screenshots) also exposed the boundary problem of baking AI into the OS, forcing Microsoft to add encryption plus explicit opt-in.</p></> } },
    { tag: <>HOT · 2025-10</>, hot: true, zh: { title: <>Windows 10 终止支持</>, body: <><p>2025-10-14 Windows 10 官方终止支持。仍在用 10 的几亿台设备面临选择:升 11 (TPM 2.0 + 较新 CPU 硬性门槛挡掉一批旧机) / 买 ESU 延保 / 换硬件。这是近十年最大规模的一次被动系统迁移, 也把"硬件够不够格升 11"推到台前。</p></> }, en: { title: <>Windows 10 end of support</>, body: <><p>On 2025-10-14 Windows 10 reached official end of support. The hundreds of millions of devices still on 10 face a choice: upgrade to 11 (the hard TPM 2.0 + recent-CPU gate excludes many older machines) / buy ESU / replace hardware. The largest forced migration in a decade, putting "is my hardware eligible for 11" front and center.</p></> } },
    { tag: <>OPEN</>, zh: { title: <>WSL2 开源</>, body: <><p>2025-05-19 微软把 WSL 的大部分代码开源。Windows 与 Linux 工具链的边界越来越模糊 —— 开发者在一台 Windows 机器上拿 Windows GUI + 真 Linux 内核, 文件系统接近原生。对"Windows 还是 macOS 做开发机"这个老问题, WSL2 把天平往 Windows 拉了一截。</p></> }, en: { title: <>WSL2 goes open source</>, body: <><p>On 2025-05-19 Microsoft open-sourced most of WSL. The line between the Windows and Linux toolchains keeps blurring — on one Windows machine you get the Windows GUI plus a real Linux kernel at near-native FS speed. On the old "Windows or macOS as a dev box" question, WSL2 nudges the scale toward Windows.</p></> } },
    { tag: <>ARM</>, zh: { title: <>Windows on ARM 成势</>, body: <><p>Copilot+ PC 多数跑 Snapdragon X (ARM64)。Prism 模拟器让 x64 应用在 ARM 上跑得够快, 加上原生 ARM 版应用越来越多, "Windows = x86" 这个三十年的等式第一次真正松动。续航和能效是 ARM 笔记本的主战场。</p></> }, en: { title: <>Windows on ARM gains traction</>, body: <><p>Most Copilot+ PCs run Snapdragon X (ARM64). The Prism emulator runs x64 apps fast enough on ARM, and with growing native-ARM app counts, the thirty-year "Windows = x86" equation genuinely loosens for the first time. Battery life and efficiency are where ARM laptops compete.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>本仓库 <code>RuiminYan/cuberoot.me</code> 的主开发机是一台 Windows 11 Pro。几乎每一行代码在它上面写, shell 全程用 pwsh 7 (PowerShell 7+, 基于 .NET 跨平台, 跟老的 Windows PowerShell 5.1 是两个东西)。主工作区 <code>core/packages/client-next</code> (Next.js 16 App Router + React 19) 的 dev server 绑死 <code>127.0.0.1:3000</code> 而不是 localhost —— Windows 下 Chrome 会优先把 localhost 解析成 IPv6 <code>::1</code>, 跟 Next dev 默认监听不匹配, 直接绑 IPv4 回环绕开这个坑。</p>
        <p>换行符是 Windows 开发的经典陷阱:Windows 默认 CRLF, Unix 工具链和 Git 期望 LF。本仓库锁死 LF —— <code>.gitattributes</code> 配 <code>* text=auto eol=lf</code> + 二进制类型标 binary, 全局 <code>core.autocrlf=false</code>。这样无论谁在哪台机器 clone, 落盘都是 LF, 不会出现"整个文件 diff 但其实没改"的换行噪音。</p>
        <p>Windows 缺的 Unix 命令单装补齐:<code>handle.exe</code> (Sysinternals, 查谁锁着文件句柄) / <code>fd</code> (替 find) / <code>jq</code> (解析 JSON) 都进 PATH。两个高频实战坑:一是 <code>git mv DIR</code> 报 Permission denied, 八成是 LSP / Vite 的 file watcher 抓着目录句柄, 用 <code>handle.exe</code> 查到 PID 再 kill 就放开了;二是 npm 的 shim 没有 <code>.exe</code> 后缀触发 libuv ENOENT, 绕法是用 <code>csc.exe</code> (随 .NET 自带) 编一个 C# wrapper 把调用转过去。</p>
        <p>还有一个 Windows Next dev 专属的孤儿进程坑:关窗口或 Ctrl+C 不一定干净退出, 可能留一个孤儿 <code>node.exe</code> 还在服旧的 chunk。判断方法是改 globals / layout / next.config 后看浏览器加载的 chunk hash 变没变 —— 没变就是孤儿进程在作祟, 杀掉重起。本地 PG 走 docker pg13 容器 (端口 5433), 推生产前在容器里把 schema / migrations / load.sql 跑一遍验证。后端 Hono server 部署在 <code>api.cuberoot.me</code> (Node 22 + pm2 + PG 13), CI 走 GitHub Actions, 但写代码这一端始终是这台 Windows 机器 + Claude Code CLI。</p>
      </>
    ),
    en: (
      <>
        <p>The main dev machine for <code>RuiminYan/cuberoot.me</code> is a Windows 11 Pro box. Nearly every line is written on it, with pwsh 7 as the shell throughout (PowerShell 7+ on cross-platform .NET — a different thing from the old Windows PowerShell 5.1). The dev server for the main workspace <code>core/packages/client-next</code> (Next.js 16 App Router + React 19) binds to <code>127.0.0.1:3000</code> rather than localhost — on Windows, Chrome prefers resolving localhost to IPv6 <code>::1</code>, which doesn't match what Next dev listens on, so binding the IPv4 loopback directly sidesteps the trap.</p>
        <p>Line endings are a classic Windows-dev trap: Windows defaults to CRLF, while the Unix toolchain and Git expect LF. This repo locks LF — <code>.gitattributes</code> sets <code>* text=auto eol=lf</code> plus binary markers for binary types, and globally <code>core.autocrlf=false</code>. That way, whoever clones on whatever machine writes LF to disk, with no "the whole file diffs but nothing actually changed" line-ending noise.</p>
        <p>Missing Unix commands are installed to fill the gaps: <code>handle.exe</code> (Sysinternals, finds who holds a file handle) / <code>fd</code> (a find replacement) / <code>jq</code> (JSON parsing) all on PATH. Two frequent battle scars: first, <code>git mv DIR</code> throwing Permission denied is usually an LSP / Vite file watcher holding the directory handle — find the PID with <code>handle.exe</code>, kill it, and the lock releases; second, npm's shim lacking a <code>.exe</code> suffix triggers a libuv ENOENT — the workaround is compiling a C# wrapper with <code>csc.exe</code> (bundled with .NET) to forward the call.</p>
        <p>There's also a Windows-specific Next-dev orphan-process trap: closing the window or Ctrl+C doesn't always exit cleanly, sometimes leaving an orphaned <code>node.exe</code> still serving stale chunks. The tell is to edit globals / layout / next.config and check whether the browser's loaded chunk hash changed — if it didn't, an orphan process is at fault; kill it and restart. Local PG runs in a docker pg13 container (port 5433), where schema / migrations / load.sql get dry-run before pushing to prod. The Hono backend server deploys to <code>api.cuberoot.me</code> (Node 22 + pm2 + PG 13), CI runs on GitHub Actions — but the authoring end is always this Windows machine plus the Claude Code CLI.</p>
      </>
    ),
  },
  links: [
    { label: 'Windows 11 release info · Microsoft Learn', href: 'https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information' },
    { label: 'Windows dev docs', href: 'https://learn.microsoft.com/en-us/windows/' },
    { label: 'WSL docs', href: 'https://learn.microsoft.com/en-us/windows/wsl/' },
    { label: 'PowerShell on GitHub', href: 'https://github.com/PowerShell/PowerShell' },
    { label: 'Sysinternals (handle / procexp)', href: 'https://learn.microsoft.com/en-us/sysinternals/' },
    { label: 'Windows Subsystem for Linux (open source)', href: 'https://github.com/microsoft/WSL' },
  ],
};

export default WINDOWS;
