import type { StackTool } from '../_lib/stack_tool_types';
import { v, f, p, c } from '../_lib/stack_tool_types';

// ─── WSL2 ─────────────────────────────────────────────────────────────────────

export const WSL2: StackTool = {
  slug: 'wsl2',
  name: 'WSL2',
  version: '2.7.3',
  since: '2016-08',
  group: 'dev',
  accent: '#16A085',
  bright: '#22C3A0',
  glyph: '⧈',
  floats: ['Linux kernel', 'Hyper-V VM', 'WSLg', 'systemd', '\\\\wsl$', 'virtio', '9P', 'interop', 'cgroups', 'wsl.conf', 'GPU compute', 'pico process'],
  zh: {
    tagline: 'Windows 里跑一个真 Linux 内核',
    role: '不在主开发流程里 (本仓库走 Windows 原生 pwsh), 但 Docker Desktop 的引擎默认跑在 WSL2 的轻量 VM 里 —— 本地那个 PG13 容器其实就坐在 WSL2 的 Linux 内核上。',
    heroSub: <>WSL 是 Windows Subsystem for Linux 的缩写, Windows 里跑 Linux 的官方方案。它有两代:<strong>WSL 1</strong> (2016) 是把 Linux 系统调用翻译成 NT 系统调用的兼容层, <strong>WSL 2</strong> (2019 宣布 / 2020 GA) 推倒重来, 改用一个 Hyper-V 轻量虚拟机跑微软自己维护的<strong>真 Linux 内核</strong>。完整 syscall 兼容 + 接近原生的文件系统性能, 一台 Windows 机器同时拿到 Windows GUI 和真 Linux 工具链。</>,
    whatDesc: <>WSL 2 不是模拟器, 也不是翻译层, 而是一个<strong>轻量 utility VM</strong>:开机即起、按需启动、几乎无感。里面跑的是微软基于上游主线维护的 Linux 内核 (源码在 <code>microsoft/WSL2-Linux-Kernel</code>, 随 Windows Update / Microsoft Store 发)。各个发行版 (Ubuntu / Debian / Kali) 作为容器跑在同一个 VM 里, 共享内核 / 网络 / CPU / 内存, 但各有自己的 PID / mount / user / cgroup namespace。它最值钱的不是"能跑 Linux", 而是<strong>无缝</strong>:<code>\\wsl$\</code> 互访文件、<code>wsl.exe</code> 跟 <code>explorer.exe</code> 互调、Linux 进程能直接启 Windows 程序反之亦然。</>,
    historyDesc: <>从 2016 年 3 月 Build 大会上"Bash on Ubuntu on Windows"的惊艳亮相, 到 2025 年 5 月整个项目开源, 不到十年。关键分水岭:2016 年 WSL 1 翻译层首发、2019 年 WSL 2 换真内核、2020 年 WSL 2 GA 成默认、2021 年 WSLg 让 Linux GUI 应用直接画到 Windows 桌面、2022 年加 systemd + 脱离 Windows 版本走 Microsoft Store、2023 年镜像网络 / 自动内存回收, 直到 2025 年开源。</>,
    conceptsTitle: '真内核 + utility VM',
    conceptsDesc: <>表面是一行 <code>wsl</code> 命令进 bash, 底层是一台精心调过的轻量虚拟机。核心模型:Hyper-V 起一个 utility VM 跑真 Linux 内核, 发行版作容器挂进去, virtio / 9P / virtiofs 做设备和文件桥接, interop 层把 Windows 和 Linux 两个世界缝在一起。</>,
    whyDesc: <>2026 年在 Windows 上做要碰 Linux 内核特性 (Docker / 容器 / Linux-only 工具链) 的 web / 后端开发, WSL2 基本是头号选择 —— 但不是全民默认: 纯原生 JS 工具链 (Node / pnpm) 在 Windows 上也跑得很顺, 未必进 WSL2 (本站自己就是)。它绕开了 WSL 1 翻译层的两个硬瓶颈 (syscall 不全 + Linux FS 性能差), 用真内核换来 Docker / strace / mmap / inotify 全部能用。Docker Desktop 干脆把它当后端引擎, 这一步把整个容器生态从 Windows 拉进了 WSL2。</>,
    adoptersTitle: '谁在用',
    adoptersDesc: <>几乎所有"在 Windows 上写 Linux 软件"的人。Docker Desktop 拿它当后端、VS Code 的 Remote-WSL 把编辑器一半塞进 Linux、Canonical / Kali 把发行版上架 Microsoft Store, 再到无数 Node / Python / Go 后端开发者把项目放进 WSL2 的 Linux FS 跑。</>,
    cuberootDesc: <>本仓库不直接在 WSL2 里写代码 (主流程是 Windows 原生 pwsh + Claude Code), 但 WSL2 在底下默默承重 —— 本地那个 PG13 docker 容器的引擎就跑在 WSL2 的 utility VM 里。</>,
    outlookTitle: '当下与前景',
    outlookDesc: <>2025 年 5 月开源是最大转折:内核 / 命令行 / 网络栈大部分代码进了 <code>microsoft/WSL</code>, 社区能直接改。近一年的迭代 (2.7.x) 集中在网络:virtiofs 目录挂载、virtio 走 IPv6、VirtioProxy 模式的 DNS 隧道。镜像网络 + 自动内存回收让它越来越像一台"隐形"的 Linux 机器。</>,
  },
  en: {
    tagline: 'A real Linux kernel running inside Windows',
    role: "Not in the main dev flow (this repo is Windows-native pwsh), but Docker Desktop's engine runs inside the WSL2 lightweight VM by default — the local PG13 container actually sits on the WSL2 Linux kernel.",
    heroSub: <>WSL stands for Windows Subsystem for Linux, the official way to run Linux on Windows. It has two generations: <strong>WSL 1</strong> (2016), a compatibility layer translating Linux syscalls into NT syscalls, and <strong>WSL 2</strong> (announced 2019, GA 2020), a clean-slate rewrite that runs a Microsoft-maintained <strong>real Linux kernel</strong> inside a lightweight Hyper-V VM. Full syscall compatibility plus near-native file-system performance: one Windows machine, both the Windows GUI and a real Linux toolchain.</>,
    whatDesc: <>WSL 2 is not an emulator and not a translation layer — it's a <strong>lightweight utility VM</strong>: starts on demand, near-invisible. Inside runs a Linux kernel Microsoft maintains from the upstream mainline (source at <code>microsoft/WSL2-Linux-Kernel</code>, shipped via Windows Update / the Microsoft Store). Distributions (Ubuntu / Debian / Kali) run as containers inside that one VM, sharing the kernel / network / CPU / memory but each with its own PID / mount / user / cgroup namespace. Its real value isn't "it runs Linux" — it's the <strong>seamlessness</strong>: <code>\\wsl$\</code> bridges the file systems, <code>wsl.exe</code> and <code>explorer.exe</code> call each other, and a Linux process can launch a Windows program and vice versa.</>,
    historyDesc: <>From the "Bash on Ubuntu on Windows" reveal at Build in March 2016 to the whole project going open source in May 2025 — under a decade. The watersheds: the WSL 1 translation layer shipped in 2016; WSL 2 swapped in a real kernel in 2019; WSL 2 went GA as the default in 2020; WSLg drew Linux GUI apps straight onto the Windows desktop in 2021; 2022 added systemd and decoupled WSL from the OS version onto the Microsoft Store; 2023 brought mirrored networking and auto memory reclaim — through to open source in 2025.</>,
    conceptsTitle: 'Real kernel + utility VM',
    conceptsDesc: <>The surface is one <code>wsl</code> command into bash; underneath is a carefully tuned lightweight VM. The core model: Hyper-V boots a utility VM running a real Linux kernel, distributions mount in as containers, virtio / 9P / virtiofs bridge devices and files, and the interop layer stitches the Windows and Linux worlds together.</>,
    whyDesc: <>For the kind of web / backend dev on Windows in 2026 that touches Linux kernel features (Docker / containers / Linux-only toolchains), WSL2 is the front-runner — though not a universal default: a pure native JS toolchain (Node / pnpm) runs fine on Windows and need not enter WSL2 (this very site is that case). It sidesteps WSL 1's two hard bottlenecks (incomplete syscalls + poor Linux-FS performance), trading the translation layer for a real kernel where Docker / strace / mmap / inotify all just work. Docker Desktop simply adopts it as the backend engine — a move that pulled the whole container ecosystem off Windows and into WSL2.</>,
    adoptersTitle: 'Who uses it',
    adoptersDesc: <>Nearly everyone "writing Linux software on Windows." Docker Desktop uses it as the backend, VS Code's Remote-WSL puts half the editor inside Linux, Canonical / Kali ship distributions on the Microsoft Store, and countless Node / Python / Go backend developers keep their projects on the WSL2 Linux FS.</>,
    cuberootDesc: <>This repo doesn't author code inside WSL2 (the main flow is Windows-native pwsh + Claude Code), but WSL2 quietly bears load underneath — the local PG13 docker container's engine runs inside the WSL2 utility VM.</>,
    outlookTitle: 'Now and next',
    outlookDesc: <>The May 2025 open-sourcing is the biggest turn: most of the kernel / CLI / networking stack landed in <code>microsoft/WSL</code>, and the community can now patch directly. The last year of releases (2.7.x) centers on networking: virtiofs directory mounts, IPv6 over virtio, DNS tunneling for VirtioProxy mode. Mirrored networking plus auto memory reclaim make it feel ever more like an "invisible" Linux box.</>,
  },
  heroStats: [
    { num: '2.7.3', zh: <>当前稳定版 <em>2026-04-25</em></>, en: <>current stable <em>2026-04-25</em></> },
    { num: '2', zh: <>当前架构 <em>真 Linux 内核 + Hyper-V VM</em></>, en: <>current architecture <em>real Linux kernel + Hyper-V VM</em></> },
    { num: '~10', unit: 'y', zh: <>从 2016 WSL 1 至今 <em>2020 年 WSL 2 GA</em></>, en: <>since WSL 1 in 2016 <em>WSL 2 GA in 2020</em></> },
    { num: '2025', unit: '·05', zh: <>WSL 开源 <em>Build 2025</em></>, en: <>WSL open-sourced <em>at Build 2025</em></> },
  ],
  intro: {
    zh: (
      <>
        <p>WSL 解决的是一个具体痛点:Windows 是用户和企业在的地方, 但现代 web / 后端 / 云开发的工具链 (bash / docker / make / 各种 Linux-only 命令) 天生长在 Unix 上。过去要么开虚拟机 (重、慢、文件互访别扭), 要么双系统 (切来切去), WSL 想抹平这条鸿沟。它在 2016 年 3 月的 Build 大会上以"Bash on Ubuntu on Windows"亮相, 当场引爆开发者 —— 微软第一次把一个完整的 Linux 用户空间装进 Windows。</p>
        <p>第一代 WSL 1 的做法是<strong>翻译层</strong>:在 NT 内核上加一个 <code>lxss.sys</code> 子系统, 用 pico process 把 Linux 系统调用实时翻译成 NT 系统调用。优点是轻、跟 Windows 文件系统贴得近;缺点也致命 —— 系统调用覆盖不全 (很多 Linux 程序直接挂)、Linux 文件系统操作慢得离谱 (每个 syscall 都要翻译)。Docker 这类深度依赖内核特性的东西在 WSL 1 上基本跑不起来。</p>
        <p>2019 年 5 月 Build 大会上微软宣布 WSL 2, 整个架构推倒重来:不再翻译, 而是用 Hyper-V 起一个<strong>轻量 utility VM</strong> 跑一个微软自己维护、基于上游主线的<strong>真 Linux 内核</strong>。代价是放弃"贴着 Windows FS"换来完整 syscall 兼容 + 接近原生的 Linux FS 性能。2020 年 5 月随 Windows 10 v2004 GA 并成为默认。此后 WSLg (2021, GUI 应用) / systemd (2022) / 脱离 Windows 版本上架 Microsoft Store (2022) / 镜像网络 (2023) 一路补齐, 直到 2025 年 5 月整个项目<strong>开源</strong>, 当前稳定版 2.7.3。</p>
      </>
    ),
    en: (
      <>
        <p>WSL solves a concrete pain: Windows is where users and enterprises are, but the modern web / backend / cloud toolchain (bash / docker / make / endless Linux-only commands) was born on Unix. The old options were a full VM (heavy, slow, awkward file sharing) or dual-boot (constant switching). WSL aims to erase that gap. It debuted at Build in March 2016 as "Bash on Ubuntu on Windows" and electrified developers on the spot — Microsoft put a complete Linux user space inside Windows for the first time.</p>
        <p>The first generation, WSL 1, used a <strong>translation layer</strong>: an <code>lxss.sys</code> subsystem on the NT kernel that used pico processes to translate Linux syscalls into NT syscalls in real time. Upsides: lightweight, tightly coupled to the Windows file system. The downsides were fatal too — incomplete syscall coverage (many Linux programs simply crashed) and absurdly slow Linux file-system operations (every syscall had to be translated). Things deeply dependent on kernel features, like Docker, basically couldn't run on WSL 1.</p>
        <p>At Build in May 2019, Microsoft announced WSL 2, a clean-slate rearchitecture: no translation, but a <strong>lightweight utility VM</strong> via Hyper-V running a <strong>real Linux kernel</strong> Microsoft maintains from the upstream mainline. The cost was giving up "hugging the Windows FS" in exchange for full syscall compatibility plus near-native Linux-FS performance. It went GA with Windows 10 v2004 in May 2020 and became the default. WSLg (2021, GUI apps) / systemd (2022) / decoupling from the OS version onto the Microsoft Store (2022) / mirrored networking (2023) filled in the rest, through to the whole project going <strong>open source</strong> in May 2025. The current stable is 2.7.3.</p>
      </>
    ),
  },
  history: [
    { year: '2016·03', zh: { title: <>Build 2016 亮相</>, desc: <>"Bash on Ubuntu on Windows"在 Build 大会上首次演示, 当场引爆。微软第一次把一个完整的 Linux 用户空间装进 Windows, 开发者社区炸锅。</> }, en: { title: <>The Build 2016 reveal</>, desc: <>"Bash on Ubuntu on Windows" was first demoed at Build, electrifying the room. Microsoft put a complete Linux user space inside Windows for the first time, and the developer community erupted.</> } },
    { year: '2016·08', zh: { title: <>WSL 1 — 翻译层首发</>, desc: <>随 Windows 10 周年更新 (1607) 发布。<code>lxss.sys</code> 子系统用 pico process 把 Linux 系统调用实时翻译成 NT 系统调用。能跑 bash / apt / gcc 不开虚拟机, 但 syscall 不全 + FS 慢。</> }, en: { title: <>WSL 1 — the translation layer ships</>, desc: <>Shipped in the Windows 10 Anniversary Update (1607). The <code>lxss.sys</code> subsystem used pico processes to translate Linux syscalls into NT syscalls in real time. It ran bash / apt / gcc with no VM, but syscalls were incomplete and the FS was slow.</> } },
    { year: '2017·10', zh: { title: <>出 beta + 多发行版</>, desc: <>Fall Creators Update (1709) 把 WSL 从 beta 转正, 并让 Ubuntu / Debian / openSUSE / Kali 等多个发行版直接上架 Microsoft Store, 一键安装切换。</> }, en: { title: <>Out of beta + multi-distro</>, desc: <>The Fall Creators Update (1709) graduated WSL out of beta and put Ubuntu / Debian / openSUSE / Kali and more directly on the Microsoft Store for one-click install and switching.</> } },
    { year: '2019·05', zh: { title: <>WSL 2 — 换真内核</>, desc: <>5 月 6 日 Build 大会宣布。架构推倒重来:Hyper-V 轻量 VM 跑微软维护的真 Linux 内核, 完整 syscall 兼容 + 接近原生 FS 性能。WSL 1 的两个硬瓶颈被绕开。</> }, en: { title: <>WSL 2 — a real kernel</>, desc: <>Announced May 6 at Build. A clean-slate rearchitecture: a lightweight Hyper-V VM running a Microsoft-maintained real Linux kernel, full syscall compatibility plus near-native FS performance. WSL 1's two hard bottlenecks are gone.</> } },
    { year: '2019·06', zh: { title: <>首个 Insider 预览</>, desc: <>WSL 2 在 Windows Insider build 18917 放出第一个预览版, 开发者第一次摸到真内核的 Docker / 完整 syscall。</> }, en: { title: <>First Insider preview</>, desc: <>WSL 2 landed its first preview in Windows Insider build 18917 — developers first got hands on real-kernel Docker and full syscalls.</> } },
    { year: '2020·05', zh: { title: <>WSL 2 GA + 成默认</>, desc: <>随 Windows 10 version 2004 正式 GA, 并成为新装发行版的默认架构。WSL 1 仍可并存, 可按发行版逐个切换。</> }, en: { title: <>WSL 2 GA + default</>, desc: <>Went GA with Windows 10 version 2004 and became the default architecture for newly installed distributions. WSL 1 can still coexist, switchable per distribution.</> } },
    { year: '2020·09', zh: { title: <>GPU 计算</>, desc: <>预览开放 GPU passthrough —— CUDA / DirectML 在 WSL2 里跑机器学习负载, 把 Windows 显卡借给 Linux 用。</> }, en: { title: <>GPU compute</>, desc: <>Preview opened GPU passthrough — CUDA / DirectML running machine-learning workloads inside WSL2, lending the Windows GPU to Linux.</> } },
    { year: '2021·04', zh: { title: <>WSLg — Linux GUI 应用</>, desc: <>引入 WSLg, 用内建的 Wayland / X 服务器 + RDP 把 Linux 图形应用直接画到 Windows 桌面, 音频也打通。随 Windows 11 (2021-10) GA。</> }, en: { title: <>WSLg — Linux GUI apps</>, desc: <>Introduced WSLg, using a built-in Wayland / X server + RDP to draw Linux graphical apps straight onto the Windows desktop, with audio piped through. GA with Windows 11 (Oct 2021).</> } },
    { year: '2022·09', zh: { title: <>systemd 支持</>, desc: <>WSL 2 加入 systemd 支持 (<code>wsl.conf</code> 里开)。snap / systemctl / 依赖 systemd 的服务终于能在 WSL2 里正常跑, 跟真 Linux 发行版的差距进一步缩小。</> }, en: { title: <>systemd support</>, desc: <>WSL 2 added systemd support (toggled in <code>wsl.conf</code>). snap / systemctl / systemd-dependent services finally run properly inside WSL2, narrowing the gap with real Linux distros.</> } },
    { year: '2022·11', zh: { title: <>WSL 1.0 — 脱离 Windows 版本</>, desc: <>WSL 作为独立的 Microsoft Store 应用 GA, 不再绑死 Windows 版本更新。<code>wsl --install</code> 一行装好, 更新走 Store 独立滚动。</> }, en: { title: <>WSL 1.0 — decoupled from the OS</>, desc: <>WSL went GA as a standalone Microsoft Store app, no longer tied to Windows version updates. <code>wsl --install</code> sets it up in one line, with updates rolling independently via the Store.</> } },
    { year: '2023·11', zh: { title: <>WSL 2.0 — 网络与资源</>, desc: <>带来镜像网络模式 (mirrored, 跟主机共享网络栈)、DNS 隧道、自动内存回收 (autoMemoryReclaim)、稀疏 VHD 磁盘。WSL2 的"隐形机器"体验大幅改善。</> }, en: { title: <>WSL 2.0 — networking & resources</>, desc: <>Brought mirrored networking (sharing the host's network stack), DNS tunneling, auto memory reclaim (autoMemoryReclaim), and sparse VHD disks. The "invisible machine" experience improved substantially.</> } },
    { year: '2025·05', zh: { title: <>WSL 开源</>, desc: <>5 月 19 日 Build 2025, 微软把 WSL 的大部分代码 (命令行 / 网络 / 文件互访) 开源进 <code>microsoft/WSL</code>。社区第一次能直接 PR 改 WSL 本体。</> }, en: { title: <>WSL goes open source</>, desc: <>On May 19 at Build 2025, Microsoft open-sourced most of WSL (CLI / networking / file interop) into <code>microsoft/WSL</code>. The community could PR against WSL itself for the first time.</> } },
    { year: '2026·04', highlight: true, zh: { title: <>2.7.3 / 当前稳定</>, desc: <>4 月 25 日发布的当前稳定版。2.7.x 系列集中在网络:virtiofs 目录挂载 (不只整卷)、virtio 走 IPv6、VirtioProxy 模式的 DNS 隧道。开源后社区迭代节奏明显加快。</> }, en: { title: <>2.7.3 / current stable</>, desc: <>The current stable, released April 25. The 2.7.x line centers on networking: virtiofs directory mounts (not just whole volumes), IPv6 over virtio, DNS tunneling for VirtioProxy mode. Post-open-source, the community cadence picked up noticeably.</> } },
  ],
  concepts: [
    { tag: 'A', zh: { title: <>WSL 1 vs WSL 2</>, desc: <>两种完全不同的架构。WSL 1 是 NT 内核上的翻译层 (轻、贴 Windows FS、syscall 不全);WSL 2 是 Hyper-V VM 里的真内核 (重一点、Linux FS 快、syscall 全)。每个发行版可独立切换。</> }, en: { title: <>WSL 1 vs WSL 2</>, desc: <>Two entirely different architectures. WSL 1 is a translation layer on the NT kernel (light, hugs the Windows FS, incomplete syscalls); WSL 2 is a real kernel in a Hyper-V VM (a bit heavier, fast Linux FS, complete syscalls). Each distribution switches independently.</> }, code: <code>{p('PS>')} {f('wsl')} {p('--set-version')} Ubuntu {v('2')}{'\n'}{c('# convert a distro to the WSL 2 architecture')}</code> },
    { tag: 'B', zh: { title: <>轻量 utility VM</>, desc: <>WSL 2 不是传统重型虚拟机, 而是一个按需启动、动态分配内存、几乎无感的 utility VM。所有发行版共用<strong>一个</strong> VM 和内核, 各自只是里面的容器。</> }, en: { title: <>Lightweight utility VM</>, desc: <>WSL 2 isn't a traditional heavyweight VM — it's an on-demand, dynamically-allocated, near-invisible utility VM. All distributions share <strong>one</strong> VM and kernel; each is just a container inside it.</> }, code: <code>{p('PS>')} {f('wsl')} {p('--list')} {p('--verbose')}{'\n'}  NAME      STATE    VERSION{'\n'}* {v('Ubuntu')}    Running  {v('2')}</code> },
    { tag: 'C', zh: { title: <>真 Linux 内核</>, desc: <>跑的是微软基于上游主线维护的真内核, 源码在 <code>microsoft/WSL2-Linux-Kernel</code>, 随 Windows Update / Store 发版。可以自己编译换内核 (<code>.wslconfig</code> 指 <code>kernel=</code>)。</> }, en: { title: <>A real Linux kernel</>, desc: <>It runs a real kernel Microsoft maintains from the upstream mainline; source lives at <code>microsoft/WSL2-Linux-Kernel</code>, shipped via Windows Update / the Store. You can compile and swap your own (<code>kernel=</code> in <code>.wslconfig</code>).</> }, code: <code>{v('$')} {f('uname')} -r{'\n'}{v('6.x')}-microsoft-standard-WSL2</code> },
    { tag: 'D', zh: { title: <>文件系统互访</>, desc: <>Windows 侧用 <code>\\wsl$\Ubuntu\</code> 访问 Linux FS;Linux 侧用 <code>/mnt/c</code> 访问 Windows 盘。关键坑:跨 FS 操作慢, 项目要放进 Linux FS (<code>~/</code>) 而不是 <code>/mnt/c</code>, 否则丢掉 WSL 2 的性能优势。</> }, en: { title: <>File-system interop</>, desc: <>From Windows, reach the Linux FS via <code>\\wsl$\Ubuntu\</code>; from Linux, reach Windows drives via <code>/mnt/c</code>. The key trap: cross-FS operations are slow — keep projects on the Linux FS (<code>~/</code>), not <code>/mnt/c</code>, or you lose WSL 2's performance edge.</> }, code: <code>{v('$')} {f('cd')} ~/project   {c('# fast: native Linux FS')}{'\n'}{v('$')} {f('cd')} /mnt/c/...  {c('# slow: 9P across the bridge')}</code> },
    { tag: 'E', zh: { title: <>interop 互调</>, desc: <>Linux 进程能直接启 Windows 程序 (<code>explorer.exe .</code> / <code>code .</code>), Windows 也能 <code>wsl &lt;cmd&gt;</code> 进去跑 Linux 命令。两边 <code>$PATH</code> 默认共享, 一条命令穿过边界。</> }, en: { title: <>interop</>, desc: <>A Linux process can launch Windows programs directly (<code>explorer.exe .</code> / <code>code .</code>), and Windows can run Linux commands via <code>wsl &lt;cmd&gt;</code>. The two <code>$PATH</code>s are shared by default — one command crosses the boundary.</> }, code: <code>{v('$')} {f('explorer.exe')} .   {c('# open Linux cwd in Windows Explorer')}{'\n'}{v('$')} {f('code')} .           {c('# launch VS Code Remote-WSL')}</code> },
    { tag: 'F', zh: { title: <>systemd + wsl.conf</>, desc: <>2022 年起可在 <code>/etc/wsl.conf</code> 打开 systemd, snap / systemctl / 依赖 init 的服务才能跑。<code>wsl.conf</code> 还管自动挂载、interop 开关、默认用户、网络模式等每发行版配置。</> }, en: { title: <>systemd + wsl.conf</>, desc: <>Since 2022 you can enable systemd in <code>/etc/wsl.conf</code>, so snap / systemctl / init-dependent services run. <code>wsl.conf</code> also governs per-distro config: automount, the interop toggle, default user, network mode, and more.</> }, code: <code>{c('# /etc/wsl.conf')}{'\n'}[{p('boot')}]{'\n'}{p('systemd')} = {v('true')}</code> },
    { tag: 'G', zh: { title: <>WSLg — GUI 应用</>, desc: <>内建一个 Wayland / X 服务器 + PulseAudio + RDP 管道, 把 Linux 图形应用 (gedit / GIMP / IDE) 直接画到 Windows 桌面, 还能开声音。装好即用, 不用自己配 X server。</> }, en: { title: <>WSLg — GUI apps</>, desc: <>A built-in Wayland / X server + PulseAudio + RDP pipe draws Linux graphical apps (gedit / GIMP / an IDE) straight onto the Windows desktop, audio included. It just works — no hand-configured X server.</> }, code: <code>{v('$')} {f('sudo')} apt install gimp{'\n'}{v('$')} {f('gimp')}   {c('# window appears on the Windows desktop')}</code> },
    { tag: 'H', zh: { title: <>GPU 计算</>, desc: <>WSL2 能把 Windows 的 GPU passthrough 给 Linux 用 —— CUDA / DirectML / OpenCL 跑深度学习训练和推理, 不用双系统。这让 Windows 成了能跑 Linux ML 栈的开发机。</> }, en: { title: <>GPU compute</>, desc: <>WSL2 can pass the Windows GPU through to Linux — CUDA / DirectML / OpenCL run deep-learning training and inference with no dual-boot. It turns Windows into a dev box that can run the Linux ML stack.</> }, code: <code>{v('$')} {f('nvidia-smi')}   {c('# Windows GPU, visible inside WSL2')}</code> },
  ],
  whyCards: [
    { icon: '⧈', zh: { title: <>真内核 = 完整 syscall</>, desc: <>WSL 1 翻译层撑不住的东西 —— Docker / strace / mmap / inotify / 各种内核特性 —— 在 WSL 2 的真内核上全部能用。这是从"能跑大部分 Linux 程序"到"能跑全部"的质变。</> }, en: { title: <>Real kernel = full syscalls</>, desc: <>What the WSL 1 translation layer couldn't carry — Docker / strace / mmap / inotify / assorted kernel features — all works on WSL 2's real kernel. The qualitative jump from "runs most Linux programs" to "runs all of them."</> }, code: <>{f('strace')} ./app   {c('// works on WSL 2, broke on WSL 1')}</> },
    { icon: '◧', zh: { title: <>接近原生 FS 性能</>, desc: <>在 Linux FS 里 (<code>~/</code>) git / npm install / 编译比 WSL 1 快几个数量级。前提是项目别放 <code>/mnt/c</code> —— 跨 FS 走 9P 桥, 那是性能黑洞。</> }, en: { title: <>Near-native FS performance</>, desc: <>Inside the Linux FS (<code>~/</code>), git / npm install / compiles run orders of magnitude faster than WSL 1. The catch: don't keep projects on <code>/mnt/c</code> — cross-FS goes over the 9P bridge, a performance black hole.</> }, code: <>{f('npm')} install   {c('// fast in ~/, crawls in /mnt/c')}</> },
    { icon: '◨', zh: { title: <>一键安装</>, desc: <><code>wsl --install</code> 一行装好默认发行版 + 内核 + 平台特性, 几分钟进 bash。不用配虚拟机、不用挂 ISO、不用调网络。WSL 脱离 Windows 版本走 Store 独立更新。</> }, en: { title: <>One-command install</>, desc: <><code>wsl --install</code> sets up the default distro + kernel + platform features in one line — into bash in minutes. No VM config, no ISO mounting, no network tuning. WSL updates independently via the Store, decoupled from the OS version.</> }, code: <>{f('wsl')} {p('--install')}{'\n'}{c('// distro + kernel + features, done')}</> },
    { icon: '◩', zh: { title: <>Docker Desktop 的后端</>, desc: <>Docker Desktop on Windows 默认用 WSL2 引擎 —— 容器跑在 WSL2 的 utility VM 里, 共享内核, 启动快、资源省。这一步把整个容器生态从 Windows 拉进了 WSL2。</> }, en: { title: <>Docker Desktop's backend</>, desc: <>Docker Desktop on Windows uses the WSL2 engine by default — containers run inside the WSL2 utility VM, sharing the kernel, starting fast and sipping resources. This pulled the whole container ecosystem into WSL2.</> }, code: <>{c('// docker engine -> wsl2 backend')}{'\n'}{f('docker')} run postgres:13</> },
    { icon: '◪', zh: { title: <>一台机器两个世界</>, desc: <>interop 让 Windows GUI 和 Linux CLI 在一台机器无缝共存:Zed / 浏览器 / Office 在 Windows, bash / docker / 编译链在 Linux, <code>\\wsl$\</code> 互访文件。不用切系统、不用两台机器。</> }, en: { title: <>One machine, two worlds</>, desc: <>interop lets the Windows GUI and Linux CLI coexist seamlessly on one machine: Zed / browser / Office on Windows, bash / docker / the compile chain on Linux, files bridged via <code>\\wsl$\</code>. No system switch, no second box.</> }, code: <>{f('code')} .   {c('// Windows editor, Linux project')}</> },
    { icon: '▤', zh: { title: <>动态资源回收</>, desc: <>WSL 2.0 起支持 <code>autoMemoryReclaim</code> + 稀疏 VHD:空闲时把内存还给 Windows、磁盘按需收缩。早期"VM 吃满内存不放"的抱怨被治住, 体验更接近"隐形"。</> }, en: { title: <>Dynamic resource reclaim</>, desc: <>Since WSL 2.0, <code>autoMemoryReclaim</code> + sparse VHDs: idle memory returns to Windows, the disk shrinks on demand. The early "the VM hogs memory and never lets go" complaint is tamed, closer to "invisible."</> }, code: <>{c('// .wslconfig')}{'\n'}[{p('experimental')}]{'\n'}{p('autoMemoryReclaim')} = {v('gradual')}</> },
    { icon: '▥', zh: { title: <>开源可改</>, desc: <>2025 年开源后, 命令行 / 网络 / 文件互访的代码进了 <code>microsoft/WSL</code>, 社区能直接发 PR 改 bug、加特性。从"微软单方面给"变成"大家一起修"。</> }, en: { title: <>Open source, hackable</>, desc: <>After open-sourcing in 2025, the CLI / networking / file-interop code landed in <code>microsoft/WSL</code> — the community can PR bug fixes and features directly. From "Microsoft hands it down" to "everyone fixes it together."</> }, code: <>{c('// github.com/microsoft/WSL')}{'\n'}{f('gh')} pr create</> },
    { icon: '▦', zh: { title: <>GPU + ML 栈</>, desc: <>GPU passthrough 让 CUDA / DirectML 在 WSL2 里跑训练和推理。想在 Windows 机器上做 Linux-first 的机器学习开发, 不用双系统也不用云。</> }, en: { title: <>GPU + the ML stack</>, desc: <>GPU passthrough runs CUDA / DirectML training and inference inside WSL2. For Linux-first machine-learning dev on a Windows box — no dual-boot, no cloud needed.</> }, code: <>{f('python')} train.py   {c('// CUDA via WSL2 passthrough')}</> },
  ],
  adopters: [
    { name: 'Docker Desktop', href: 'https://www.docker.com/products/docker-desktop/', highlight: true, zhNote: 'Windows 版默认用 WSL2 引擎, 容器跑在它的 utility VM 里', enNote: 'The Windows edition uses the WSL2 engine by default; containers run in its utility VM' },
    { name: 'VS Code (Remote-WSL)', href: 'https://code.visualstudio.com/docs/remote/wsl', highlight: true, zhNote: '把编辑器后端塞进 Linux, 在 Windows UI 里直接改 WSL2 里的代码', enNote: 'Puts the editor backend inside Linux, editing WSL2 code from the Windows UI' },
    { name: 'Ubuntu / Canonical', href: 'https://ubuntu.com/wsl', zhNote: 'WSL 上最主流的发行版, 官方上架 Microsoft Store', enNote: 'The most common WSL distribution, officially on the Microsoft Store' },
    { name: 'Kali Linux', href: 'https://www.kali.org/docs/wsl/', zhNote: '安全测试发行版, win-kex 给 WSL 一个完整桌面', enNote: 'The security-testing distro; win-kex gives WSL a full desktop' },
    { name: 'Rancher Desktop', href: 'https://rancherdesktop.io', zhNote: 'k8s / 容器开发工具, 同样以 WSL2 为 Linux 后端', enNote: 'A k8s / container dev tool that also uses WSL2 as its Linux backend' },
    { name: 'Podman Desktop', href: 'https://podman-desktop.io', zhNote: 'Docker 的无守护进程替代, Windows 上跑在 WSL2 机器里', enNote: "Docker's daemonless alternative, running in a WSL2 machine on Windows" },
    { name: 'JetBrains IDEs', href: 'https://www.jetbrains.com', zhNote: 'IDEA / PyCharm 等支持把解释器 / 工具链指向 WSL2', enNote: 'IDEA / PyCharm and others can point interpreters / toolchains at WSL2' },
    { name: 'Node / Python / Go devs', zhNote: '海量后端开发者把项目放 WSL2 Linux FS 跑, 绕开 Windows 路径坑', enNote: 'Countless backend devs keep projects on the WSL2 Linux FS, dodging Windows path traps' },
    { name: 'GitHub Codespaces (contrast)', href: 'https://github.com/features/codespaces', zhNote: '反例 — 把同一个痛点搬到云端容器, 跟 WSL2 各解一半', enNote: 'A counterpoint — moves the same pain into cloud containers, solving the other half' },
    { name: 'cuberoot.me', highlight: true, zhNote: '本仓库 — 不直接在 WSL2 写代码, 但 Docker Desktop 的 PG13 容器跑在它的 VM 里', enNote: "This repo — doesn't author code in WSL2, but Docker Desktop's PG13 container runs in its VM" },
  ],
  outlook: [
    { tag: <>OPEN · 2025-05</>, hot: true, big: true, zh: { title: <>WSL 开源</>, body: <><p>2025-05-19 Build 2025, 微软把 WSL 的大部分代码 —— 命令行 (<code>wsl.exe</code>)、网络栈、文件互访 —— 开源进 <code>microsoft/WSL</code>。这是项目近十年最大的一次转向:从"微软单方面发版"变成社区能直接 PR 改 bug、加特性、审代码。</p><p>开源前内核 (<code>WSL2-Linux-Kernel</code>) 早就公开, 但 WSL 本体 (调度 / 网络 / interop) 一直闭源。这次补齐让整个栈透明, 也解释了 2.7.x 系列迭代节奏明显变快 —— 社区贡献进来了。</p></> }, en: { title: <>WSL goes open source</>, body: <><p>On 2025-05-19 at Build 2025, Microsoft open-sourced most of WSL — the CLI (<code>wsl.exe</code>), networking stack, and file interop — into <code>microsoft/WSL</code>. The biggest turn in the project's near-decade: from "Microsoft ships unilaterally" to a community that can PR bug fixes, features, and code review directly.</p><p>The kernel (<code>WSL2-Linux-Kernel</code>) had long been public, but WSL itself (scheduling / networking / interop) stayed closed. Filling that gap made the whole stack transparent and explains why the 2.7.x cadence visibly sped up — community contributions arrived.</p></> } },
    { tag: <>NET · 2.7.x</>, hot: true, zh: { title: <>网络栈持续打磨</>, body: <><p>近一年的版本集中在网络:virtiofs 支持挂载单个目录而不只整卷、virtio 通道走 IPv6、VirtioProxy 模式的 DNS 隧道。配合更早的镜像网络模式 (mirrored, 跟 Windows 共享网络栈), WSL2 的网络体验从"另一台机器"往"跟主机同一张网"收敛。</p></> }, en: { title: <>Networking keeps getting polished</>, body: <><p>The last year of releases centers on networking: virtiofs mounting individual directories rather than whole volumes, IPv6 over the virtio channel, DNS tunneling for VirtioProxy mode. Together with the earlier mirrored networking (sharing the Windows network stack), WSL2's network experience converges from "another machine" toward "the same network as the host."</p></> } },
    { tag: <>RESOURCE</>, zh: { title: <>越来越"隐形"</>, body: <><p>自动内存回收 + 稀疏 VHD + 按需启动, WSL2 早期"VM 吃内存不放、磁盘只涨不缩"的抱怨被一一治住。方向很明确:让这台 Linux 机器在资源占用上无限接近"不存在", 平时感觉不到, 要用时秒起。</p></> }, en: { title: <>Ever more "invisible"</>, body: <><p>Auto memory reclaim + sparse VHDs + on-demand boot — the early complaints ("the VM hogs memory and never lets go, the disk only grows") are being addressed one by one. The direction is clear: make this Linux machine asymptotically close to "not there" in resource footprint — unnoticed at rest, instant on demand.</p></> } },
    { tag: <>AI</>, zh: { title: <>本地 AI / GPU 工作负载</>, body: <><p>GPU passthrough + 完整 CUDA 栈让 WSL2 成了 Windows 上跑 Linux-first AI 开发的主力。随着本地推理 (LLM / 扩散模型) 越来越常见, "Windows 当桌面 + WSL2 跑 ML 栈"会是相当一部分开发者的默认配置, 而不用碰云或双系统。</p></> }, en: { title: <>Local AI / GPU workloads</>, body: <><p>GPU passthrough + a full CUDA stack make WSL2 the workhorse for Linux-first AI dev on Windows. As local inference (LLMs / diffusion models) grows common, "Windows as the desktop + WSL2 for the ML stack" becomes the default for a sizable slice of developers — no cloud, no dual-boot.</p></> } },
  ],
  cuberoot: {
    zh: (
      <>
        <p>说实话, 本仓库 <code>RuiminYan/cuberoot.me</code> 不在 WSL2 里写代码。主开发流程是 Windows 11 Pro 原生 + pwsh 7 + Claude Code, 主工作区 <code>core/packages/client-next</code> (Next.js 16 + React 19) 的 dev server 直接在 Windows 侧跑 <code>127.0.0.1:3000</code>。缺的 Unix 命令 (<code>jq</code> / <code>fd</code> / <code>handle.exe</code>) 是单装 Windows 原生版补齐, 而不是绕进 Linux。这是有意的选择:整条 Node / pnpm / Turbo 工具链在 Windows 上已经够顺, 没必要为了用 bash 把整个项目搬进 WSL2 的 Linux FS。</p>
        <p>但 WSL2 在底下默默承重。本地数据库走 docker pg13 容器 (端口 5433, 推生产前在里面 dry-run schema / migrations / load.sql), 而 <strong>Docker Desktop on Windows 默认就是 WSL2 后端</strong> —— 那个 PG13 容器的引擎其实跑在 WSL2 的 utility VM 里, 共享着 WSL2 维护的那个 Linux 内核。所以即便没主动开 <code>wsl</code> 命令, 每次 <code>docker run</code> 都在用 WSL2。</p>
        <p>这正好印证了 WSL2 的定位:它最好的状态是<strong>隐形</strong>。开发者不需要知道容器跑在哪个 VM、哪个内核上, 只要 <code>docker</code> 命令能用、PG 能连、性能够快就行。WSL2 把"在 Windows 上要用 Linux 内核特性 (容器 / cgroups / overlayfs)"这件事变成了一个不用想的基础设施。如果哪天本仓库真要在 Windows 上跑某个 Linux-only 的工具链 (比如某个只在 Linux 编得过的 native 依赖), WSL2 就是那条现成的逃生通道, 一行 <code>wsl --install</code> 即到位。</p>
      </>
    ),
    en: (
      <>
        <p>Honestly, this repo (<code>RuiminYan/cuberoot.me</code>) doesn't author code inside WSL2. The main flow is native Windows 11 Pro + pwsh 7 + Claude Code, with the dev server for the main workspace <code>core/packages/client-next</code> (Next.js 16 + React 19) running on the Windows side at <code>127.0.0.1:3000</code>. The missing Unix commands (<code>jq</code> / <code>fd</code> / <code>handle.exe</code>) are filled by installing native Windows builds, not by detouring into Linux. That's deliberate: the whole Node / pnpm / Turbo toolchain is already smooth on Windows, so there's no need to move the project into the WSL2 Linux FS just to get bash.</p>
        <p>But WSL2 quietly bears load underneath. The local database runs in a docker pg13 container (port 5433, where schema / migrations / load.sql get dry-run before pushing to prod), and <strong>Docker Desktop on Windows is WSL2-backed by default</strong> — that PG13 container's engine actually runs inside the WSL2 utility VM, sharing the Linux kernel WSL2 maintains. So even without typing a <code>wsl</code> command, every <code>docker run</code> is using WSL2.</p>
        <p>That neatly proves WSL2's positioning: it's at its best when <strong>invisible</strong>. A developer doesn't need to know which VM or kernel the container runs on — only that <code>docker</code> works, PG connects, and it's fast enough. WSL2 turns "I need Linux kernel features on Windows (containers / cgroups / overlayfs)" into infrastructure you never think about. And if this repo ever genuinely needs a Linux-only toolchain on Windows (say a native dependency that only compiles on Linux), WSL2 is the ready-made escape hatch — one <code>wsl --install</code> away.</p>
      </>
    ),
  },
  links: [
    { label: 'WSL docs · Microsoft Learn', href: 'https://learn.microsoft.com/en-us/windows/wsl/' },
    { label: 'Compare WSL 1 vs WSL 2', href: 'https://learn.microsoft.com/en-us/windows/wsl/compare-versions' },
    { label: 'WSL on GitHub (open source)', href: 'https://github.com/microsoft/WSL' },
    { label: 'WSL2 Linux kernel source', href: 'https://github.com/microsoft/WSL2-Linux-Kernel' },
    { label: 'WSL open-source docs site', href: 'https://wsl.dev' },
    { label: 'Docker Desktop WSL 2 backend', href: 'https://docs.docker.com/desktop/wsl/' },
  ],
};

export default WSL2;
