/**
 * Canonical algorithm lists for Timer-only trainers that do not yet have a
 * database-backed shared JSON source. Web and Mobile must consume these
 * through `trainer-scramble.ts`; host apps must not copy these lists.
 *
 * Case ids for these historical Timer lists remain the algorithm string. That
 * preserves the existing Solve.caseId contract while moving ownership to the
 * runtime-neutral shared package.
 */

export const COLL_ALGS: readonly string[] = [
  "R U2 R' U' R U R' U' R U' R'",
  "F R U R' U' R U R' U' R U R' U' F'",
  "R U R' U R U' R' U R U2 R'",
  "R U2 R2 U' R2 U' R2 U2 R",
  "F R U R' U' R U R' U' R U R' U' F'",
  "R' U' R U' L U' R' U L' U2 R",
  "R U2 R' U' R U R' U2 R' F R F'",
  "F R U R' U' R U' R' U' R U R' F'",
  "R' F R U2 R U2 R' F' U' R U' R'",
  "R U2 R' U2 R' F R2 U R' U' F'",
  "R2 D' R U2 R' D R U2 R",
  "R2 D R' U2 R D' R' U2 R'",
  "R U R' U R' F R F' R U2 R'",
  "R U2 R' U' R U R' U' R U' R'",
  "R U' L' U R' U' L",
  "R' U' R U' R' U2 R2 U R' U R U2 R'",
  "R U R' U R U2 R'",
  "R U R' U' R' F R2 U R' U' F'",
  "R U2 R' U' R U R' U' R U' R'",
  "F R U R' U2 R U' R' U F'",
  "F R U' R' U R U R' F'",
  "R U R2 U' R' F R U R U' F'",
  "F R' F' R U2 R U2 R'",
  "F R U R' U' R U R' U' F'",
  "R U2 R' U' R U R' U' R U' R'",
  "R' U' R U' R' U R' D' R U R' D R2",
  "R U' L' U R' U L",
  "R' U R U2 R D R' U' R D' R2",
  "R U R' U R U2 R'",
  "L' U R U' L U R'",
  "F R' F' R U2 R U2 R'",
  "R U R' U R U' R' U R U2 R'",
  "R U R' U' R' F R F' R U R' U R U2 R'",
  "R U R' U' R U R' U' R U R' U R U2 R'",
  "R' U' R U' R' U2 R",
  "L F' L' U' L U F U' L'",
  "R' F R U' R' U' R U R' F' R U' R'",
  "R U2 R' U' R U R' U' R U' R'",
  "R U R' U R' F R F' R U' R' U R U2 R'",
  "R' U' R U' R' U R U' R' U2 R F R U R' U' F'",
] as const;

export const CMLL_ALGS: readonly string[] = [
  "R U' R' U R U2 R' U' R U R' U' R U' R'",
  "F R U' R' U' R U R' F' R U R' U' R' F R F'",
  "R U R' U R U' R' U R U2 R'",
  "F R U R' U' R U R' U' R U R' U' F'",
  "R U2 R' U' R U R' U' R U' R'",
  "R U R' U L' U R U' R' L",
  "F R U R' U' R U R' U' R U R' U' F'",
  "R' U' R' F R F' R U' R' U2 R",
  "R U2 R' U' R U R' U2 R' F R F'",
  "F R U R' U' R U' R' U' R U R' F'",
  "R U2 R2 F R F' R U2 R'",
  "r U' r2 D' r U r' D r2 U r'",
  "R2 D R' U2 R D' R' U2 R'",
  "R2 D' R U2 R' D R U2 R",
  "R' U' R U' R' U2 R",
  "R U R' U R U2 R'",
  "F R2 D R' U R D' R2 U' F'",
  "r U' r2 D' r U' r' D r2 U r'",
  "R U R' U' R' F R F'",
  "L' U' L U L F' L' F",
  "F R' F' R U R U' R'",
  "R U R' U R' F R F' R U2 R'",
  "r' U r U2 r' L' U R' U' M",
  "R U2 R' U' R U R' U' R U' R'",
  "F R U' R' U' R U R' F'",
  "F R' F' R U R U' R'",
  "R U2 R' U' R U R' U' R U' R'",
  "R' U2 R U R' U R",
  "R U2 R D R' U2 R D' R2",
  "R U R' U' R' F R F'",
  "R U R' U R U2 R'",
  "L' U2 L U2 L F' L' F",
  "F R' F' R U2 R U2 R'",
  "R U R' U' R' F R2 U R' U' F'",
  "R U R' U R' F R F' R U2 R'",
  "R U R' U R U' R' U R U2 R'",
  "R' U' R U' R' U2 R",
  "F' r U R' U' r' F R",
  "R U2 R D R' U2 R D' R2",
  "F R U R' U' R U R' U' F'",
  "R U2 R2 F R F' U2 R' F R F'",
  "R' U' R U' R' U R U R' U R U2 R'",
] as const;

export const EG1_ALGS: readonly string[] = [
  "R2 U' B2 U2 R2 U' R2",
  "R2 U R2 U2 F2 U R2",
  "R U R' U R U2 R'",
  "F R U R' U' R U R' U' F'",
  "F R U' R' U' R U R' F'",
  "R U2 R' U' R U' R'",
  "R U R' U R U2 R'",
  "R U R' U' R' F R F'",
  "F R' F' R U R U' R'",
  "R U' R F2 R' U R'",
  "F R U R' U' F'",
  "R U2 R' U' R U R' U' R U' R'",
  "R U R' F' R U R' U' R' F R2 U' R'",
  "R' U' R U' R' U2 R",
  "F R U' R' U R U R' F'",
  "R2 U R' U' R' F2 R U' R'",
  "R U R' U' R' F R F'",
  "F R U R' U' F'",
  "R2 F2 R U2 R U2 R' F2 R' F'",
  "R U R' U R U2 R' U2 R U2 R'",
  "R U' R' U' F2 U' R U R' U F2",
  "F R' F R2 U' R' U' R U R' F2",
  "F R' F' R U2 R U2 R'",
  "R' F R F' R' F R F' R U R'",
  "R U2 R' U' R U R' U' R U' R'",
  "R U2 R2 F R F' R U2 R'",
  "F R U' R' U R U2 R' U' F'",
  "R' U' R' F R F' U R",
  "R U R' U R U2 R'",
  "L' U2 L U L' U' L",
  "F R' F' R U2 R U2 R'",
  "R U R' U' R' F R2 U R' U' F'",
  "R U R' U R' F R F' R U2 R'",
  "R U R' U R U' R' U R U2 R'",
  "R' U' R U' R' U2 R",
  "L F' L' U' L U F U' L'",
  "F' L F L' U2 L' U2 L",
  "R' U' R U R F2 R F2 R'",
  "R' U' R U' R' F R U R' U' F' U R",
  "R' U' R U' R' U R U' R' U2 R",
] as const;

export const EG2_ALGS: readonly string[] = [
  "R2 F2 R2",
  "R2 U' R2 U2 F2 U' R2",
  "R2 U R2 U2 F2 U R2",
  "F2 U' R2 U2 R2 U' F2",
  "F R' F' R U2 R U2 R'",
  "R' U' R U' R F R' F' R U' R'",
  "R U R2 F R F' R U2 R'",
  "R U R' U R U2 R' F R U R' U' F'",
  "R' F R F' R U2 R' U' R U' R'",
  "F R U' R' U R U' R' U R U R' F'",
  "R U2 R' U' R U' R'",
  "R U R' U R U2 R'",
  "F R U R' U' F'",
  "R' F R F' R U2 R'",
  "R' F2 R F R' F R",
  "R2 U' R2 F2 U R2 U2 F2",
  "R U R' U' R' F R2 U R' U' F'",
  "R U R' U R U2 R'",
  "F R U R' U' R U R' U' F'",
  "R' U' R U' R' U2 R",
  "R2 F2 R' U' R U' R' F2 R'",
  "R U' R' U R U R' U' R U' R'",
  "F R U' R' U R U R' F'",
  "R' F2 R U R' F2 R",
  "R U R2 F R F' R U2 R'",
  "F R' F' R U2 R U2 R'",
  "R U2 R' U' R U R' U2 R' F R F'",
  "R' U' R' F R F' U R",
  "R U R' U R U2 R'",
  "L' U2 L U2 L F' L' F",
  "F R' F' R U2 R U2 R'",
  "R U R' U' R' F R2 U R' U' F'",
  "R U R' U R' F R F' R U2 R'",
  "R U R' U R U' R' U R U2 R'",
  "R' U' R U' R' U2 R",
  "L F' L' U' L U F U' L'",
  "F' L F L' U2 L' U2 L",
  "R' U' R U R F2 R F2 R'",
  "R' U' R U' R' F R U R' U' F' U R",
  "R' U' R U' R' U R U' R' U2 R",
] as const;
