export enum ColorCode {
  Black = '#000000',
  DarkGray = '#404040',
  Gray = '#808080',
  Silver = '#BFBFBF',
  White = '#FFFFFF',
  Yellow = '#FEFE00',
  Red = '#EE0000',
  Orange = '#FFA100',
  Blue = '#0000F2',
  Green = '#00D800',
  Purple = '#A83DD9',
  Pink = '#F33D7B',
  Transparent = 'transparent',
  // Extended palette (PHP V0.6.6 — see _php_reference/index.php $ZERO/$FOREST/...)
  Zero = '#1B1B1B',
  Forest = '#006600',
  LPink = '#FF99FF',
  Cream = '#EEE8AA',
  Cyan = '#88DDFF',
  Navy = '#3375B2',
  Tan = '#885500',
}

export enum ColorName {
  Black = 'black',
  DarkGray = 'darkGray',
  Gray = 'gray',
  Silver = 'silver',
  White = 'white',
  Yellow = 'yellow',
  Red = 'red',
  Orange = 'orange',
  Blue = 'blue',
  Green = 'green',
  Purple = 'purple',
  Pink = 'pink',
  Transparent = 'transparent',
  // Extended palette
  Zero = 'zero',
  Forest = 'forest',
  LPink = 'lpink',
  Cream = 'cream',
  Cyan = 'cyan',
  Navy = 'navy',
  Tan = 'tan',
}

export enum ColorAbbreviation {
  Black = 'n',
  DarkGray = 'd',
  Gray = 'l',
  Silver = 's',
  White = 'w',
  Yellow = 'y',
  Red = 'r',
  Orange = 'o',
  Blue = 'b',
  Green = 'g',
  Purple = 'm',
  Pink = 'p',
  Transparent = 't',
  // Extended palette (PHP V0.6.6)
  Zero = 'z',
  Forest = 'f',
  LPink = 'i',
  Cream = 'e',
  Cyan = 'c',
  Navy = 'v',
  Tan = 'a',
}
