/** `.tmp/best2x2/import.json` → 0104_best_2x2_algs.sql。 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('.', import.meta.url));
const REPO = resolve(HERE, '../../..');
const input = resolve(REPO, process.argv[2] ?? '.tmp/best2x2/import.json');
const output = resolve(REPO, process.argv[3] ?? 'core/packages/server/migrations/0104_best_2x2_algs.sql');
const data = JSON.parse(readFileSync(input, 'utf8'));

const q = (value) => value == null ? 'NULL' : `'${String(value).replaceAll("'", "''")}'`;
const j = (value) => `${q(JSON.stringify(value))}::jsonb`;

const lines = [
  '-- Best 2x2 Algs: merge 17 Google Sheet tabs into the 2x2 formula library.',
  '-- Generated by jobs/alg-build/gen_best2x2_sql.mjs.',
  '-- Source formulas failing state validation stay in docs/best-2x2-algs-port.md, not in alg_cases.',
  '',
];

for (const set of data.sets) {
  lines.push(`INSERT INTO alg_sets (puzzle, set_slug, source, scraped_at) VALUES ('2x2', ${q(set.slug)}, ${q(set.source)}, NOW())`);
  lines.push(`ON CONFLICT (puzzle, set_slug) DO UPDATE SET source = EXCLUDED.source, scraped_at = EXCLUDED.scraped_at;`, '');
}

for (const set of data.sets.filter((item) => !item.existing)) {
  lines.push(`DELETE FROM alg_cases WHERE puzzle = '2x2' AND set_slug = ${q(set.slug)};`);
}
// Existing sets are kept in place so their IDs/progress keys survive. Only the sheet cases that
// do not have an existing row are rebuilt, making the data migration safe to rehearse locally.
for (const set of data.sets.filter((item) => item.existing)) {
  const insertedNames = set.cases.filter((c) => !c.existingName).map((c) => c.name);
  if (!insertedNames.length) continue;
  lines.push(`DELETE FROM alg_cases WHERE puzzle = '2x2' AND set_slug = ${q(set.slug)}`);
  lines.push(`  AND name IN (${insertedNames.map(q).join(', ')});`);
}
lines.push('');

for (const set of data.sets) {
  lines.push(`-- ${set.sheet} -> ${set.slug}`);
  for (const c of set.cases) {
    if (c.existingName) {
      lines.push(`UPDATE alg_cases SET position = ${c.position}, setup = ${q(c.setup)}, sticker = ${j(c.sticker)}, algs = ${j(c.algs)}`);
      lines.push(`WHERE puzzle = '2x2' AND set_slug = ${q(set.slug)} AND name = ${q(c.existingName)};`);
    } else {
      lines.push(`INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)`);
      lines.push(`VALUES ('2x2', ${q(set.slug)}, ${c.position}, ${q(c.name)}, ${q(c.subgroup)}, ${q(c.setup)}, ${j(c.sticker)}, ${j(c.algs)});`);
    }
  }
  lines.push('');
}

lines.push('DO $best2x2$');
lines.push('DECLARE got INTEGER;');
lines.push('BEGIN');
for (const set of data.sets) {
  lines.push(`  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = '2x2' AND set_slug = ${q(set.slug)};`);
  lines.push(`  IF got <> ${set.cases.length} THEN RAISE EXCEPTION '${set.slug}: expected ${set.cases.length} cases, got %', got; END IF;`);
}
lines.push('END');
lines.push('$best2x2$;');
lines.push('');

writeFileSync(output, lines.join('\n'), 'utf8');
console.log(`写入 ${output} (${lines.length} 行,${data.stats.mergedActive} 条合并公式)`);
