/** Complete SQ1 EP from the Pk Feng DOC fixture -> 0187 data migration. */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { serverMigrationPath } from './server-migration-path.mts';

interface SourceNote { zh: string; en: string }
interface SourceAlg { alg: string; setup: string; source: 'cuberoot'; note?: SourceNote }
interface SourceCase {
  position: number;
  numericName: string;
  name: string;
  parity: 'no-parity' | 'parity';
  sourceCell?: string;
  setup: string;
  algs: SourceAlg[];
}
interface Fixture {
  schemaVersion: number;
  source: { title: string; file: string; sha256: string };
  naming: { layerOrder: string[]; layerNames: Record<string, string>; note: string };
  cases: SourceCase[];
}

function invariant(value: unknown, message: string): asserts value {
  if (!value) throw new Error(message);
}

const fixturePath = fileURLToPath(new URL('./fixtures/sq1-ep-pkfeng.json', import.meta.url));
const fixture = JSON.parse(readFileSync(fixturePath, 'utf8')) as Fixture;
const output = serverMigrationPath(process.argv[2] ?? '0187_sq1_ep_pkfeng_complete.sql');
const expectedOrder = ['0', '1', '2', '3+', '3-', '4+', '4-', '7', '+', '//'];

invariant(fixture.schemaVersion === 1, `unsupported fixture schema ${fixture.schemaVersion}`);
invariant(JSON.stringify(fixture.naming.layerOrder) === JSON.stringify(expectedOrder), 'unexpected numeric layer order');
invariant(fixture.naming.layerNames['+'] === 'H', 'standalone + must map to H');
invariant(fixture.cases.length === 100, `expected 100 cases, got ${fixture.cases.length}`);
invariant(new Set(fixture.cases.map(item => item.numericName)).size === 100, 'numeric names must be unique');
invariant(new Set(fixture.cases.map(item => item.name)).size === 100, 'English names must be unique');
invariant(fixture.cases.every((item, index) => item.position === index), 'positions must be contiguous');
invariant(fixture.cases.filter(item => item.parity === 'no-parity').length === 50, 'expected 50 no-parity cases');
invariant(fixture.cases.filter(item => item.parity === 'parity').length === 50, 'expected 50 parity cases');
invariant(fixture.cases.flatMap(item => item.algs).length === 118, 'expected 118 source algorithms');
invariant(fixture.cases[0]?.numericName === '0.0', 'first case must be 0.0');
invariant(fixture.cases[0]?.sourceCell === 'LC' && fixture.cases[0]?.algs.length === 0, '0.0 must preserve LC without a fake alg');

const payload = fixture.cases.map(item => ({
  position: item.position,
  numericName: item.numericName,
  name: item.name,
  parity: item.parity,
  sourceCell: item.sourceCell,
  setup: item.setup,
  algs: item.algs,
}));
const pretty = JSON.stringify(payload, null, 2);
const source = `${fixture.source.title}; ${fixture.source.file}; sha256:${fixture.source.sha256}`.replaceAll("'", "''");

const sql = `-- Complete SQ1 EP from SQ1棱顺序全公式（Pk锋版）.
-- Generated by jobs/alg-build/gen_sq1_ep_pkfeng_sql.mts.
-- Source SHA-256: ${fixture.source.sha256}

INSERT INTO alg_sets (puzzle, set_slug, source, scraped_at)
VALUES ('sq1', 'ep', '${source}', NOW())
ON CONFLICT (puzzle, set_slug) DO UPDATE
SET source = EXCLUDED.source, scraped_at = EXCLUDED.scraped_at;

-- CubingApp contributed this non-canonical duplicate. It is the only existing
-- row outside the complete 10 x 10 naming matrix, so reuse its id for 0.0.
WITH moved AS (
  SELECT subgroup, subgroup || '|Ua & Ua' AS old_key, subgroup || '|Solved / Solved' AS new_key
  FROM alg_cases
  WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = 'Ua & Ua'
), copied AS (
  INSERT INTO alg_case_marks (wca_id, puzzle, set_slug, case_key, status, updated_at)
  SELECT marks.wca_id, marks.puzzle, marks.set_slug, moved.new_key,
         marks.status, marks.updated_at
  FROM alg_case_marks AS marks
  CROSS JOIN moved
  WHERE marks.puzzle = 'sq1' AND marks.set_slug = 'ep' AND marks.case_key = moved.old_key
  ON CONFLICT (wca_id, puzzle, set_slug, case_key) DO UPDATE
  SET status = CASE
        WHEN EXCLUDED.updated_at >= alg_case_marks.updated_at THEN EXCLUDED.status
        ELSE alg_case_marks.status
      END,
      updated_at = GREATEST(alg_case_marks.updated_at, EXCLUDED.updated_at)
)
DELETE FROM alg_case_marks AS marks
USING moved
WHERE marks.puzzle = 'sq1' AND marks.set_slug = 'ep' AND marks.case_key = moved.old_key;

WITH moved AS (
  SELECT subgroup || '|Ua & Ua' AS old_key, subgroup || '|Solved / Solved' AS new_key
  FROM alg_cases
  WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = 'Ua & Ua'
), copied AS (
  INSERT INTO alg_case_srs (
    wca_id, puzzle, set_slug, case_key, due, ivl, ease, reps, lapses, streak, hist, reviewed_at
  )
  SELECT srs.wca_id, srs.puzzle, srs.set_slug, moved.new_key,
         srs.due, srs.ivl, srs.ease, srs.reps, srs.lapses, srs.streak, srs.hist, srs.reviewed_at
  FROM alg_case_srs AS srs
  CROSS JOIN moved
  WHERE srs.puzzle = 'sq1' AND srs.set_slug = 'ep' AND srs.case_key = moved.old_key
  ON CONFLICT (wca_id, puzzle, set_slug, case_key) DO UPDATE
  SET due = CASE WHEN EXCLUDED.reviewed_at >= alg_case_srs.reviewed_at THEN EXCLUDED.due ELSE alg_case_srs.due END,
      ivl = CASE WHEN EXCLUDED.reviewed_at >= alg_case_srs.reviewed_at THEN EXCLUDED.ivl ELSE alg_case_srs.ivl END,
      ease = CASE WHEN EXCLUDED.reviewed_at >= alg_case_srs.reviewed_at THEN EXCLUDED.ease ELSE alg_case_srs.ease END,
      reps = CASE WHEN EXCLUDED.reviewed_at >= alg_case_srs.reviewed_at THEN EXCLUDED.reps ELSE alg_case_srs.reps END,
      lapses = CASE WHEN EXCLUDED.reviewed_at >= alg_case_srs.reviewed_at THEN EXCLUDED.lapses ELSE alg_case_srs.lapses END,
      streak = CASE WHEN EXCLUDED.reviewed_at >= alg_case_srs.reviewed_at THEN EXCLUDED.streak ELSE alg_case_srs.streak END,
      hist = CASE WHEN EXCLUDED.reviewed_at >= alg_case_srs.reviewed_at THEN EXCLUDED.hist ELSE alg_case_srs.hist END,
      reviewed_at = GREATEST(alg_case_srs.reviewed_at, EXCLUDED.reviewed_at)
)
DELETE FROM alg_case_srs AS srs
USING moved
WHERE srs.puzzle = 'sq1' AND srs.set_slug = 'ep' AND srs.case_key = moved.old_key;

WITH moved AS (
  SELECT subgroup || '|Ua & Ua' AS old_key, subgroup || '|Solved / Solved' AS new_key
  FROM alg_cases
  WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = 'Ua & Ua'
)
UPDATE alg_chain_orders AS orders
SET case_keys = (
  SELECT COALESCE(jsonb_agg(to_jsonb(key) ORDER BY first_ord), '[]'::jsonb)
  FROM (
    SELECT CASE WHEN item.value = moved.old_key THEN moved.new_key ELSE item.value END AS key,
           MIN(item.ord) AS first_ord
    FROM jsonb_array_elements_text(orders.case_keys) WITH ORDINALITY AS item(value, ord)
    GROUP BY 1
  ) AS unique_keys
)
FROM moved
WHERE orders.puzzle = 'sq1' AND orders.set_slug = 'ep';

WITH moved AS (
  SELECT subgroup || '|Ua & Ua' AS old_key, subgroup || '|Solved / Solved' AS new_key
  FROM alg_cases
  WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = 'Ua & Ua'
)
UPDATE trainer_rooms AS rooms
SET keys = (
      SELECT COALESCE(jsonb_agg(to_jsonb(CASE WHEN value = moved.old_key THEN moved.new_key ELSE value END) ORDER BY ord), '[]'::jsonb)
      FROM jsonb_array_elements_text(rooms.keys) WITH ORDINALITY AS item(value, ord)
    ),
    queue = (
      SELECT COALESCE(jsonb_agg(to_jsonb(CASE WHEN value = moved.old_key THEN moved.new_key ELSE value END) ORDER BY ord), '[]'::jsonb)
      FROM jsonb_array_elements_text(rooms.queue) WITH ORDINALITY AS item(value, ord)
    )
FROM moved
WHERE rooms.puzzle = 'sq1' AND rooms.set_slug = 'ep';

WITH moved AS (
  SELECT subgroup || '|Ua & Ua' AS old_key, subgroup || '|Solved / Solved' AS new_key
  FROM alg_cases
  WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = 'Ua & Ua'
)
UPDATE alg_preferred_algs AS preferred
SET items = (
  SELECT COALESCE(jsonb_object_agg(
    CASE
      WHEN entry.key LIKE moved.old_key || '::%' THEN moved.new_key || substring(entry.key FROM length(moved.old_key) + 1)
      ELSE entry.key
    END,
    entry.value
  ), '{}'::jsonb)
  FROM jsonb_each(preferred.items) AS entry(key, value)
)
FROM moved
WHERE preferred.puzzle = 'sq1' AND preferred.set_slug = 'ep';

UPDATE alg_cases
SET name = 'Solved / Solved', position = 0, setup = '', standard = NULL, algs = '[[]]'::jsonb
WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = 'Ua & Ua';

WITH payload AS (
  SELECT $sq1_ep_pkfeng$${pretty}$sq1_ep_pkfeng$::jsonb AS body
), items AS (
  SELECT value AS item FROM payload, jsonb_array_elements(body)
)
UPDATE alg_cases AS cases
SET position = (items.item->>'position')::integer,
    setup = items.item->>'setup',
    sticker = '{"kind":"raw","tag":"sqcube","attrs":{}}'::jsonb,
    algs = jsonb_build_array(
      COALESCE(items.item->'algs', '[]'::jsonb) ||
      COALESCE((
        SELECT jsonb_agg(
          CASE
            WHEN existing.entry ? 'setup' THEN existing.entry
            ELSE existing.entry || jsonb_build_object('setup', cases.setup)
          END
          ORDER BY existing.ord
        )
        FROM jsonb_array_elements(COALESCE(cases.algs->0, '[]'::jsonb)) WITH ORDINALITY AS existing(entry, ord)
        WHERE NOT EXISTS (
          SELECT 1
          FROM jsonb_array_elements(COALESCE(items.item->'algs', '[]'::jsonb)) AS imported(entry)
          WHERE regexp_replace(imported.entry->>'alg', '\\s', '', 'g') = regexp_replace(existing.entry->>'alg', '\\s', '', 'g')
        )
      ), '[]'::jsonb)
    )
FROM items
WHERE cases.puzzle = 'sq1' AND cases.set_slug = 'ep' AND cases.name = items.item->>'name';

WITH payload AS (
  SELECT $sq1_ep_pkfeng$${pretty}$sq1_ep_pkfeng$::jsonb AS body
), items AS (
  SELECT value AS item FROM payload, jsonb_array_elements(body)
)
INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)
SELECT 'sq1', 'ep', (items.item->>'position')::integer, items.item->>'name', 'Additional',
       items.item->>'setup', '{"kind":"raw","tag":"sqcube","attrs":{}}'::jsonb,
       jsonb_build_array(COALESCE(items.item->'algs', '[]'::jsonb))
FROM items
WHERE NOT EXISTS (
  SELECT 1 FROM alg_cases
  WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = items.item->>'name'
);

DO $$
DECLARE got integer;
BEGIN
  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'ep';
  IF got <> 100 THEN RAISE EXCEPTION 'SQ1 EP expected 100 cases, got %', got; END IF;

  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name LIKE '% / %';
  IF got <> 50 THEN RAISE EXCEPTION 'SQ1 EP expected 50 no-parity cases, got %', got; END IF;

  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name LIKE '% & %';
  IF got <> 50 THEN RAISE EXCEPTION 'SQ1 EP expected 50 parity cases, got %', got; END IF;

  SELECT COUNT(DISTINCT position) INTO got
  FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'ep' AND position BETWEEN 0 AND 99;
  IF got <> 100 THEN RAISE EXCEPTION 'SQ1 EP positions are not the complete 0..99 range'; END IF;

  IF EXISTS (SELECT 1 FROM alg_cases WHERE puzzle = 'sq1' AND set_slug = 'ep' AND name = 'Ua & Ua') THEN
    RAISE EXCEPTION 'SQ1 EP non-canonical Ua & Ua row remains';
  END IF;
END $$;
`;

writeFileSync(output, sql, 'utf8');
console.log(`wrote ${output}: 100 cases, 50 + 50 parity split, 118 imported algorithms`);
