-- PostgreSQL schema for recon_db (生产真实 schema 的 PG 等价版,2026-05-06 实测对账)
-- 设计原则: 最保守翻译,server 代码 0 改动
--   tinyint(1)         → SMALLINT  (不转 BOOLEAN,jsonToRow 仍写 0/1)
--   longtext+json_valid → TEXT     (server 代码已经用 JSON.parse 兜底,沿用)
--   int unsigned (epoch) → BIGINT  (PG 无 UNSIGNED,BIGINT 安全)
--   datetime           → TIMESTAMP (无 TZ,跟 MariaDB datetime 等价)
--   timestamp DEFAULT current_timestamp() → TIMESTAMP DEFAULT NOW()
--
-- alg_submissions 是新表,MariaDB 上从未存在,这次随迁移一起上线。

-- ── 1. recons (主表,2064 行) ──
CREATE TABLE recons (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  official        SMALLINT NOT NULL DEFAULT 1,
  event           VARCHAR(20) NOT NULL DEFAULT '3x3',
  method          VARCHAR(20),
  date            DATE,
  comp            VARCHAR(200),
  comp_wca_id     VARCHAR(100),
  country         VARCHAR(100),
  round           VARCHAR(20),
  solve_num       SMALLINT,
  person          VARCHAR(100),
  person_id       VARCHAR(20),
  person_country  VARCHAR(10),
  raw_time        NUMERIC(8,3),
  exec_time       NUMERIC(8,3),
  memo_time       NUMERIC(8,3),
  average         NUMERIC(8,2),
  value           VARCHAR(20),
  regional_single_record    VARCHAR(20),
  regional_average_record   VARCHAR(20),
  ao_type                   VARCHAR(50),
  regional_aoxr_record      VARCHAR(20),
  recon           TEXT,
  solution        TEXT,
  optimal_scramble TEXT,
  wca_scramble    TEXT,
  caption         TEXT,
  note            TEXT,
  stm             SMALLINT,
  tps             NUMERIC(5,2),
  oll             VARCHAR(100),
  pll             VARCHAR(100),
  oll_short       VARCHAR(50),
  pll_short       VARCHAR(50),
  free_pair       SMALLINT,
  y_rot           SMALLINT,
  regrip          SMALLINT,
  lockup          SMALLINT,
  cross_type      SMALLINT,
  cross_stm       SMALLINT,
  f2l             SMALLINT,
  ll              SMALLINT,
  s_move          SMALLINT,
  cross_color     CHAR(1),
  created_at      BIGINT,
  added_by        VARCHAR(100),
  added_by_id     VARCHAR(20),
  cube            VARCHAR(100),
  reconer         VARCHAR(100),
  reconer_id      VARCHAR(20),
  group_id        VARCHAR(10),
  recon_date      DATE,
  video_url       TEXT,
  alternatives    TEXT
);
CREATE INDEX idx_date ON recons(date);
CREATE INDEX idx_comp ON recons(comp);
CREATE INDEX idx_person_id ON recons(person_id);
CREATE INDEX idx_person ON recons(person);
CREATE INDEX idx_added_by_id ON recons(added_by_id);

-- ── 2. comments ──
CREATE TABLE comments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recon_id    INTEGER NOT NULL,
  author_id   VARCHAR(20) NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  content     TEXT NOT NULL,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT,
  pinned      SMALLINT NOT NULL DEFAULT 0,
  parent_id   INTEGER
);
CREATE INDEX idx_recon_id ON comments(recon_id);
CREATE INDEX idx_parent ON comments(recon_id, parent_id, created_at);

-- ── 3. edits (current snapshot) ──
-- fields 用 JSONB 以支持 server 端 jsonb || 合并(原 MariaDB 用 JSON_MERGE_PATCH)
CREATE TABLE edits (
  solve_id  VARCHAR(50) PRIMARY KEY,
  fields    JSONB NOT NULL,
  edited_at BIGINT
);

-- ── 4. edit_history (audit log) ──
CREATE TABLE edit_history (
  id              VARCHAR(50) PRIMARY KEY,
  solve_id        VARCHAR(50) NOT NULL,
  before_snapshot TEXT,
  after_fields    TEXT,
  edited_by       VARCHAR(100),
  edited_at       BIGINT
);
CREATE INDEX idx_eh_solve_id ON edit_history(solve_id);
CREATE INDEX idx_eh_edited_at ON edit_history(edited_at);

-- ── 5. wca_users ──
CREATE TABLE wca_users (
  wca_id            VARCHAR(20) PRIMARY KEY,
  name              VARCHAR(200),
  avatar_url        TEXT,
  access_token      TEXT,
  refresh_token     TEXT,
  token_expires_at  TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── 6. cubing_attempts_cache ──
CREATE TABLE cubing_attempts_cache (
  slug       VARCHAR(64) NOT NULL,
  event      VARCHAR(8) NOT NULL,
  round      VARCHAR(2) NOT NULL,
  person_id  VARCHAR(16) NOT NULL,
  attempts   TEXT NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (slug, event, round, person_id)
);

-- ── 7. wca_results_cache ──
CREATE TABLE wca_results_cache (
  comp_id    VARCHAR(64) NOT NULL,
  wca_event  VARCHAR(8) NOT NULL,
  payload    TEXT NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (comp_id, wca_event)
);

-- ── 8. wca_scrambles_cache ──
CREATE TABLE wca_scrambles_cache (
  comp_id    VARCHAR(64) PRIMARY KEY,
  payload    TEXT NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── 9. train_results ──
CREATE TABLE train_results (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     VARCHAR(20),
  alg_set_id  VARCHAR(50),
  case_id     VARCHAR(100),
  time_ms     INTEGER,
  correct     SMALLINT,
  created_at  TIMESTAMP
);

-- ── 10. timer_sessions ──
CREATE TABLE timer_sessions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wca_id      VARCHAR(20) NOT NULL,
  session_id  VARCHAR(50) NOT NULL,
  puzzle_id   VARCHAR(20) NOT NULL,
  solves      TEXT NOT NULL,
  updated_at  BIGINT NOT NULL,
  CONSTRAINT uk_user_session_puzzle UNIQUE (wca_id, session_id, puzzle_id)
);
CREATE INDEX idx_ts_wca_id ON timer_sessions(wca_id);

-- ── 11. alg_submissions (NEW — never existed in MariaDB) ──
CREATE TABLE alg_submissions (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  puzzle       VARCHAR(20) NOT NULL,
  set_slug     VARCHAR(100) NOT NULL,
  case_name    VARCHAR(128) NOT NULL,
  alg          TEXT NOT NULL,
  notes        TEXT,
  author_id    VARCHAR(20) NOT NULL,
  author_name  VARCHAR(100) NOT NULL,
  created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_alg_set ON alg_submissions(puzzle, set_slug);
