-- PostgreSQL schema for cuberoot_db (生产真实 schema 的 PG 等价版,2026-05-06 实测对账)
-- 设计原则: 最保守翻译,server 代码 0 改动
--   tinyint(1)         → SMALLINT  (不转 BOOLEAN,jsonToRow 仍写 0/1)
--   longtext+json_valid → TEXT     (server 代码已经用 JSON.parse 兜底,沿用)
--   int unsigned (epoch) → BIGINT  (PG 无 UNSIGNED,BIGINT 安全)
--   datetime           → TIMESTAMP (无 TZ,跟 MariaDB datetime 等价)
--   timestamp DEFAULT current_timestamp() → TIMESTAMP DEFAULT NOW()
--
-- alg_submissions 是新表,MariaDB 上从未存在,这次随迁移一起上线。

-- ── 1. recons (主表,2064 行) ──
CREATE TABLE recons (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  official        SMALLINT NOT NULL DEFAULT 1,
  event           VARCHAR(20) NOT NULL DEFAULT '3x3',
  method          VARCHAR(20),
  date            DATE,
  comp            VARCHAR(200),
  comp_wca_id     VARCHAR(100),
  country         VARCHAR(100),
  round           VARCHAR(20),
  solve_num       SMALLINT,
  person          VARCHAR(100),
  person_id       VARCHAR(20),
  person_country  VARCHAR(10),
  raw_time        NUMERIC(8,3),
  exec_time       NUMERIC(8,3),
  memo_time       NUMERIC(8,3),
  average         NUMERIC(8,2),
  value           VARCHAR(20),
  regional_single_record    VARCHAR(20),
  regional_average_record   VARCHAR(20),
  ao_type                   VARCHAR(50),
  regional_aoxr_record      VARCHAR(20),
  recon           TEXT,
  solution        TEXT,
  optimal_scramble TEXT,
  wca_scramble    TEXT,
  caption         TEXT,
  note            TEXT,
  stm             SMALLINT,
  tps             NUMERIC(5,2),
  oll             VARCHAR(100),
  pll             VARCHAR(100),
  oll_short       VARCHAR(50),
  pll_short       VARCHAR(50),
  free_pair       SMALLINT,
  y_rot           SMALLINT,
  regrip          SMALLINT,
  lockup          SMALLINT,
  cross_type      SMALLINT,
  cross_stm       SMALLINT,
  f2l             SMALLINT,
  ll              SMALLINT,
  s_move          SMALLINT,
  cross_color     CHAR(1),
  created_at      BIGINT,
  added_by        VARCHAR(100),
  added_by_id     VARCHAR(20),
  cube            VARCHAR(100),
  reconer         VARCHAR(100),
  reconer_id      VARCHAR(20),
  group_id        VARCHAR(10),
  recon_date      DATE,
  video_url       TEXT,
  alternatives    TEXT
);
CREATE INDEX idx_date ON recons(date);
CREATE INDEX idx_comp ON recons(comp);
CREATE INDEX idx_person_id ON recons(person_id);
CREATE INDEX idx_person ON recons(person);
CREATE INDEX idx_added_by_id ON recons(added_by_id);

-- ── 2. comments ──
CREATE TABLE comments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recon_id    INTEGER NOT NULL,
  author_id   VARCHAR(20) NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  content     TEXT NOT NULL,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT,
  pinned      SMALLINT NOT NULL DEFAULT 0,
  parent_id   INTEGER
);
CREATE INDEX idx_recon_id ON comments(recon_id);
CREATE INDEX idx_parent ON comments(recon_id, parent_id, created_at);

-- ── 3. edits (current snapshot) ──
-- fields 用 JSONB 以支持 server 端 jsonb || 合并(原 MariaDB 用 JSON_MERGE_PATCH)
CREATE TABLE edits (
  solve_id  VARCHAR(50) PRIMARY KEY,
  fields    JSONB NOT NULL,
  edited_at BIGINT
);

-- ── 4. edit_history (audit log) ──
CREATE TABLE edit_history (
  id              VARCHAR(50) PRIMARY KEY,
  solve_id        VARCHAR(50) NOT NULL,
  before_snapshot TEXT,
  after_fields    TEXT,
  edited_by       VARCHAR(100),
  edited_at       BIGINT
);
CREATE INDEX idx_eh_solve_id ON edit_history(solve_id);
CREATE INDEX idx_eh_edited_at ON edit_history(edited_at);

-- ── 5. wca_users ──
CREATE TABLE wca_users (
  wca_id            VARCHAR(20) PRIMARY KEY,
  name              VARCHAR(200),
  avatar_url        TEXT,
  access_token      TEXT,
  refresh_token     TEXT,
  token_expires_at  TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── 6. cubing_attempts_cache ──
CREATE TABLE cubing_attempts_cache (
  slug       VARCHAR(64) NOT NULL,
  event      VARCHAR(8) NOT NULL,
  round      VARCHAR(2) NOT NULL,
  person_id  VARCHAR(16) NOT NULL,
  attempts   TEXT NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (slug, event, round, person_id)
);

-- ── 7. wca_results_cache ──
CREATE TABLE wca_results_cache (
  comp_id    VARCHAR(64) NOT NULL,
  wca_event  VARCHAR(8) NOT NULL,
  payload    TEXT NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (comp_id, wca_event)
);

-- ── 8. wca_scrambles_cache ──
CREATE TABLE wca_scrambles_cache (
  comp_id    VARCHAR(64) PRIMARY KEY,
  payload    TEXT NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ── 9. train_results ──
CREATE TABLE train_results (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     VARCHAR(20),
  alg_set_id  VARCHAR(50),
  case_id     VARCHAR(100),
  time_ms     INTEGER,
  correct     SMALLINT,
  created_at  TIMESTAMP
);

-- ── 10. timer_sessions ──
CREATE TABLE timer_sessions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wca_id      VARCHAR(20) NOT NULL,
  session_id  VARCHAR(50) NOT NULL,
  puzzle_id   VARCHAR(20) NOT NULL,
  solves      TEXT NOT NULL,
  updated_at  BIGINT NOT NULL,
  CONSTRAINT uk_user_session_puzzle UNIQUE (wca_id, session_id, puzzle_id)
);
CREATE INDEX idx_ts_wca_id ON timer_sessions(wca_id);

-- ── 11. alg_submissions (NEW — never existed in MariaDB) ──
CREATE TABLE alg_submissions (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  puzzle       VARCHAR(20) NOT NULL,
  set_slug     VARCHAR(100) NOT NULL,
  case_name    VARCHAR(128) NOT NULL,
  alg          TEXT NOT NULL,
  notes        TEXT,
  author_id    VARCHAR(20) NOT NULL,
  author_name  VARCHAR(100) NOT NULL,
  created_at   TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_alg_set ON alg_submissions(puzzle, set_slug);

-- ── 共用 trigger 函数:更新 updated_at(alg_sets / alg_cases / 以后表也可复用) ──
CREATE OR REPLACE FUNCTION trg_set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── 12. alg_sets (公式集元数据,代替 alg_*.json 的 file-level 字段) ──
-- 41 行 (puzzle, set_slug),从 core/packages/shared/data/alg_*.json 的 41 个文件导入。
CREATE TABLE alg_sets (
  puzzle      VARCHAR(20) NOT NULL,
  set_slug    VARCHAR(50) NOT NULL,
  source      TEXT,
  scraped_at  TIMESTAMPTZ,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (puzzle, set_slug)
);
CREATE TRIGGER alg_sets_updated_at BEFORE UPDATE ON alg_sets
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ── 13. alg_cases (单个 case,代替 JSON cases[] 数组里的每一条) ──
-- 不加 (puzzle, set_slug, name) UNIQUE: ZBLS Geng 86 cases 跟标准 case 重名。
-- 顺序由 position 列保证(从 JSON 数组下标导入)。
CREATE TABLE alg_cases (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  puzzle      VARCHAR(20) NOT NULL,
  set_slug    VARCHAR(50) NOT NULL,
  position    INTEGER NOT NULL,
  -- 显示名(F2L 改成字母 A+/A-/...,其它 set 维持 speedcubedb 原名)。
  name        VARCHAR(128) NOT NULL,
  -- 业务编号(F2L 1..41 = CFOP 文献规范编号);其它 set NULL。跟 position(排序键)解耦。
  number      SMALLINT,
  subgroup    VARCHAR(64) NOT NULL DEFAULT '',
  setup       TEXT NOT NULL DEFAULT '',
  standard    TEXT,                             -- 1lll/zbll 没有 standard
  sticker     JSONB NOT NULL,                   -- polymorphic { kind: 'face'|'f2l'|'raw', ... }
  algs        JSONB NOT NULL,                   -- 2D AlgEntry[][]
  ori_names   JSONB,                            -- F2L 才有(string[],4 个 orientation 名)
  trainer_key VARCHAR(32),                      -- ZBLS 才有
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY (puzzle, set_slug) REFERENCES alg_sets(puzzle, set_slug) ON DELETE CASCADE
);
CREATE INDEX idx_alg_cases_set ON alg_cases(puzzle, set_slug, position);
CREATE TRIGGER alg_cases_updated_at BEFORE UPDATE ON alg_cases
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ── 14. colpi_words (盲拧字母对图像协作数据库 /memo/colpi) ──
-- 初始 ~11.8k 词镜像自 bestsiteever.net/colpi (Roman Strakhov),submitter_wca_id=NULL 即上游来源。
-- 本站登录用户提交的新词:submitter_wca_id 填本人 WCA ID。
-- 用户能 PATCH/DELETE 自己的词;admin (ADMIN_WCA_IDS) 能改/删任何词包括上游。
CREATE TABLE colpi_words (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pair                VARCHAR(8)  NOT NULL,           -- 2 字符 (含 'ʧ' 多字节字母)
  word                VARCHAR(128) NOT NULL,          -- 已大写化 (英文) / 原样 (中文等)
  category            VARCHAR(16) NOT NULL,           -- unspecified|object|person|action|place|other
  language            VARCHAR(8)  NOT NULL DEFAULT 'en', -- ISO 2~3 letter, 上游 41 codes (af/ar/bg/ca/cz/da/de/en/es/eu/fa/fi/fr/gu/he/hi/hr/hu/id/it/ja/kr/lt/mk/ms/nl/no/pl/pt/ro/ru/se/sk/sl/th/tr/uk/uz/vi/zh/zu)
  offensive           BOOLEAN NOT NULL DEFAULT FALSE, -- 上游 wlOffensive 标记
  submitter_wca_id    VARCHAR(20),                    -- NULL = 上游镜像
  submitter_name      VARCHAR(128),
  submitter_country   VARCHAR(8),                     -- ISO2 (如 'US') 用于显示国旗
  note                TEXT,                           -- 用户解释 word 与 pair 的对应 (e.g. word=苹果 note=APPLE)
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- 跨语言可能撞同串 (e.g. "AS" 在 en 和 es 都是合法词),unique 必须含 language
CREATE UNIQUE INDEX uq_colpi_words_pair_word_lang ON colpi_words(pair, word, language);
CREATE INDEX idx_colpi_words_pair ON colpi_words(pair);
CREATE INDEX idx_colpi_words_language ON colpi_words(language);
CREATE INDEX idx_colpi_words_submitter ON colpi_words(submitter_wca_id) WHERE submitter_wca_id IS NOT NULL;
CREATE INDEX idx_colpi_words_recent ON colpi_words(created_at DESC) WHERE submitter_wca_id IS NOT NULL;
CREATE TRIGGER colpi_words_updated_at BEFORE UPDATE ON colpi_words
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ── 15. colpi_votes (本站用户对词的赞/踩,聚合分数用于排序) ──
CREATE TABLE colpi_votes (
  word_id       BIGINT NOT NULL REFERENCES colpi_words(id) ON DELETE CASCADE,
  voter_wca_id  VARCHAR(20) NOT NULL,
  dir           SMALLINT NOT NULL CHECK (dir IN (-1, 1)),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (word_id, voter_wca_id)
);
CREATE INDEX idx_colpi_votes_word ON colpi_votes(word_id);

-- ── 16. nav_sites (/site 魔方网址导航) ──
-- 旧 client/src/pages/sites/data/sites.ts 字符串 id 不带,自增 BIGINT;group 改 group_id 避关键字。
CREATE TABLE nav_sites (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id    VARCHAR(20)  NOT NULL,
  position    INTEGER      NOT NULL,
  name        VARCHAR(200) NOT NULL,
  name_en     VARCHAR(200),
  name_zh     VARCHAR(200),
  url         TEXT         NOT NULL,
  alt_urls    JSONB,
  author      VARCHAR(200),
  desc_en     TEXT,
  desc_zh     TEXT,
  youtube     TEXT,
  tags        JSONB,
  status      VARCHAR(20),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_nav_sites_group_pos ON nav_sites(group_id, position);
CREATE TRIGGER nav_sites_updated_at BEFORE UPDATE ON nav_sites
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
