-- 0027_article_report — 社区长文举报 / 审核入口 (untrusted 内容防滥用)。
-- runner 自动包事务,勿写 BEGIN/COMMIT。

-- ── 25. article_report (读者举报已发布文章;admin 在 /article/admin/reports 审核)
CREATE TABLE article_report (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id      BIGINT NOT NULL REFERENCES article(id) ON DELETE CASCADE,
  reporter_wca_id VARCHAR(20) NOT NULL,
  reason          TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- 同一举报人对同一篇只占一行 (再次举报 → ON CONFLICT 更新理由/时间),防刷计数。
CREATE UNIQUE INDEX uq_article_report_dedupe ON article_report (article_id, reporter_wca_id);
CREATE INDEX idx_article_report_article ON article_report (article_id);
