-- 全量 WCA 比赛打乱镜像（源：WCA developer dump 的 scrambles 表，~305 万行 / 15k+ 场）。
-- 支撑：/scramble/gen 指定任意比赛秒出（不再首次回源 WCA API、不看 WCA 限流脸色）
--       + /timer 随机真实打乱池（按 event 采样）。
-- 扁平行直接对应前端 WcaScrambleRow[]，端点 SELECT 后把 is_extra 转 boolean 即可，无嵌套组装。
-- 数据不入 migration（量太大）：首灌走 mysql -B 导出 → scp → \copy；日更走 CI 增量 append。
CREATE TABLE IF NOT EXISTS wca_scrambles (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competition_id VARCHAR(32) NOT NULL,
  event_id       VARCHAR(6)  NOT NULL,
  round_type_id  VARCHAR(1)  NOT NULL,
  group_id       VARCHAR(3)  NOT NULL,
  is_extra       SMALLINT    NOT NULL DEFAULT 0,
  scramble_num   INT         NOT NULL,
  scramble       TEXT        NOT NULL
);
-- 指定比赛：按 competition_id 取全场。随机池：按 event_id 采样。
CREATE INDEX IF NOT EXISTS idx_wca_scr_comp  ON wca_scrambles(competition_id);
CREATE INDEX IF NOT EXISTS idx_wca_scr_event ON wca_scrambles(event_id);
