-- 0064_user_accounts.sql — 内部账号体系 (Plan A):内部 uid 为唯一身份 + 多身份绑定 + 验证码。
--
-- 背景:此前身份唯一源是 WCA OAuth(wca_id 直接当主键,散布全栈)。为让「没有 WCA / 没参过赛」
--       的用户也能注册,并为 App(Apple/Google/微信)铺路,引入内部账号:
--         app_users        — 一个真人一行,内部数字 id 为唯一身份主键
--         auth_identities  — (provider, provider_uid) 一条身份一行,多条指向同一 app_users
--         auth_codes       — 邮箱/手机验证码(只存 sha256 哈希,不存明文)
-- 兼容:业务表仍保持 wca_id 键不动(801 处零改动)。requireAuth 返回的 wcaId 变为「归属键」——
--       绑了 WCA 就是真 wca_id(现有数据零迁移),没绑就是合成 `u<uid>`(与真 WCA id 天然不撞)。
--
-- Runner (ops/bin/apply_migrations.sh) 每个文件独立 BEGIN/COMMIT + ON_ERROR_STOP=1 —— 本文件禁写
-- BEGIN;/COMMIT;。已应用的 migration 被 _schema_migrations 的 sha256 锁死,部署后禁改本文件。
-- trg_set_updated_at() 已存在于库中(schema.pg.sql 定义一次),这里直接引用,勿重复定义。

-- ── 账号:一个真人一行 ──
CREATE TABLE app_users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name  VARCHAR(200) NOT NULL DEFAULT '',
  avatar_url    TEXT,
  wca_id        VARCHAR(20),                       -- 便捷镜像:绑定 WCA 后填真 wca_id(与 wca identity 同步);未绑为 NULL
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
-- wca_id 存在时唯一(一个 WCA 账号只能绑一个内部账号);NULL 不参与唯一。
CREATE UNIQUE INDEX uq_app_users_wca ON app_users(wca_id) WHERE wca_id IS NOT NULL;
CREATE TRIGGER app_users_updated_at BEFORE UPDATE ON app_users
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ── 身份:一条登录方式一行,多条指向同一 app_users ──
CREATE TABLE auth_identities (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT       NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  provider      VARCHAR(16)  NOT NULL,             -- email | phone | wca | apple | google | wechat | alipay
  provider_uid  VARCHAR(320) NOT NULL,             -- lower(email) | phone(E.164) | wca_id | oauth sub
  verified_at   TIMESTAMPTZ,                        -- 该身份被验证的时间(email/phone 走验证码即验证)
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_auth_identity UNIQUE (provider, provider_uid)  -- 同一 (provider,uid) 全局唯一 → 防两个账号绑同一身份
);
CREATE INDEX idx_auth_identities_user ON auth_identities(user_id);

-- ── 验证码:邮箱/手机,只存哈希 ──
CREATE TABLE auth_codes (
  id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel      VARCHAR(8)   NOT NULL,              -- email | phone
  target       VARCHAR(320) NOT NULL,              -- lower(email) | phone(E.164)
  purpose      VARCHAR(16)  NOT NULL DEFAULT 'login',  -- login(注册/登录) | link(登录态下绑定新身份)
  code_hash    TEXT         NOT NULL,              -- sha256(pepper:channel:target:code) — 明文永不落库
  expires_at   TIMESTAMPTZ  NOT NULL,
  attempts     INT          NOT NULL DEFAULT 0,    -- 校验失败次数;达上限即作废(防爆破)
  consumed_at  TIMESTAMPTZ,                         -- 成功核销或被新码顶掉的时间;非空即失效
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_auth_codes_lookup ON auth_codes(channel, target, created_at DESC);

-- ── 回填:现有 wca_users → app_users + wca identity(existing 365d token 无 uid,靠此表 + refresh 升级)──
-- wca_users.wca_id 是 PK,无重复;wca_users 无 created_at,用 updated_at 兜底。
INSERT INTO app_users (display_name, avatar_url, wca_id, created_at, updated_at)
SELECT COALESCE(name, ''), avatar_url, wca_id, COALESCE(updated_at, NOW()), COALESCE(updated_at, NOW())
FROM wca_users;

INSERT INTO auth_identities (user_id, provider, provider_uid, verified_at, created_at)
SELECT u.id, 'wca', u.wca_id, NOW(), u.created_at
FROM app_users u
WHERE u.wca_id IS NOT NULL;
