-- 0066_forum.sql — 论坛(/forum):分类 → 子版 → 主题 → 回帖 + 反应,结构对标 speedsolving.com。
--
-- 背景:站点新增社区论坛。两级结构(forum_categories 只是标题分组,不可导航;forum_forums 才是
--       发帖目的地),主题/回帖软删除(is_deleted,保 postNo 稳定),反应一人一帖一条(可换 kind)。
--       作者键沿用全站归属键 ownerKey(真 wca_id 或合成 u<uid>),与 comments.author_id 同语义。
--       子版计数(threadCount/postCount)不做反规范化,查询时 LATERAL 现算;
--       主题上保留 reply_count/view_count/last_post_* 缓存列(排序与列表页需要)。
--
-- Runner (ops/bin/apply_migrations.sh) 每个文件独立 BEGIN/COMMIT + ON_ERROR_STOP=1 —— 本文件禁写
-- BEGIN;/COMMIT;。已应用的 migration 被 _schema_migrations 的 sha256 锁死,部署后禁改本文件。
-- trg_set_updated_at() 已存在于库中(schema.pg.sql 定义一次),这里直接引用,勿重复定义。

-- ── 分类:仅作首页分组标题,不可导航 ──
CREATE TABLE forum_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        VARCHAR(64)  NOT NULL UNIQUE,
  name_en     VARCHAR(100) NOT NULL,
  name_zh     VARCHAR(100) NOT NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ── 子版:发帖目的地 ──
CREATE TABLE forum_forums (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id  BIGINT       NOT NULL REFERENCES forum_categories(id) ON DELETE CASCADE,
  slug         VARCHAR(64)  NOT NULL UNIQUE,
  name_en      VARCHAR(100) NOT NULL,
  name_zh      VARCHAR(100) NOT NULL,
  desc_en      VARCHAR(300) NOT NULL DEFAULT '',
  desc_zh      VARCHAR(300) NOT NULL DEFAULT '',
  icon         VARCHAR(40)  NOT NULL DEFAULT '',   -- lucide 图标名,客户端映射组件
  admin_only   BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = 仅管理员可发主题(公告版)
  sort_order   INT          NOT NULL DEFAULT 0
);
CREATE INDEX idx_forum_forums_cat ON forum_forums(category_id, sort_order);

-- ── 主题 ──
CREATE TABLE forum_threads (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forum_id              BIGINT       NOT NULL REFERENCES forum_forums(id) ON DELETE CASCADE,
  title                 VARCHAR(200) NOT NULL,
  author_id             VARCHAR(32)  NOT NULL,     -- ownerKey:真 wca_id 或 u<uid>
  author_name           VARCHAR(200) NOT NULL,
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  last_post_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  last_post_author_id   VARCHAR(32),
  last_post_author_name VARCHAR(200),
  reply_count           INT          NOT NULL DEFAULT 0,  -- 不含首帖
  view_count            INT          NOT NULL DEFAULT 0,
  is_pinned             BOOLEAN      NOT NULL DEFAULT FALSE,
  is_locked             BOOLEAN      NOT NULL DEFAULT FALSE,
  is_deleted            BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_forum_threads_list ON forum_threads(forum_id, is_pinned DESC, last_post_at DESC)
  WHERE NOT is_deleted;
CREATE TRIGGER forum_threads_updated_at BEFORE UPDATE ON forum_threads
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ── 帖子(含首帖;软删除保 postNo 稳定)──
CREATE TABLE forum_posts (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id   BIGINT       NOT NULL REFERENCES forum_threads(id) ON DELETE CASCADE,
  author_id   VARCHAR(32)  NOT NULL,
  author_name VARCHAR(200) NOT NULL,
  content     TEXT         NOT NULL,               -- 原始 markdown,渲染端净化
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  edited_at   TIMESTAMPTZ,
  is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_forum_posts_thread ON forum_posts(thread_id, id);
CREATE TRIGGER forum_posts_updated_at BEFORE UPDATE ON forum_posts
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- ── 反应:一人一帖一条,换 kind 走 upsert ──
CREATE TABLE forum_reactions (
  post_id     BIGINT       NOT NULL REFERENCES forum_posts(id) ON DELETE CASCADE,
  author_id   VARCHAR(32)  NOT NULL,
  author_name VARCHAR(200) NOT NULL,
  kind        VARCHAR(16)  NOT NULL,               -- like | love | haha | wow | sad
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  PRIMARY KEY (post_id, author_id)
);

-- ── 举报:一人一帖一条(重复举报 upsert 换理由);resolved_at 空 = 待处理 ──
CREATE TABLE forum_reports (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id       BIGINT       NOT NULL REFERENCES forum_posts(id) ON DELETE CASCADE,
  reporter_id   VARCHAR(32)  NOT NULL,             -- ownerKey
  reporter_name VARCHAR(200) NOT NULL,
  reason        VARCHAR(500) NOT NULL,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  resolved_at   TIMESTAMPTZ,
  UNIQUE (post_id, reporter_id)
);
CREATE INDEX idx_forum_reports_open ON forum_reports(created_at DESC) WHERE resolved_at IS NULL;

-- ── 种子:6 分类 + 15 子版(对标 speedsolving.com 结构,双语)──
INSERT INTO forum_categories (slug, name_en, name_zh, sort_order) VALUES
  ('announcements', 'Announcements',    '公告区',   10),
  ('beginners',     'Help & Beginners', '新手区',   20),
  ('general',       'General',          '综合讨论', 30),
  ('competitions',  'Competitions',     '比赛区',   40),
  ('videos',        'Videos',           '视频区',   50),
  ('community',     'Community',        '社区',     60);

INSERT INTO forum_forums (category_id, slug, name_en, name_zh, desc_en, desc_zh, icon, admin_only, sort_order) VALUES
  ((SELECT id FROM forum_categories WHERE slug = 'announcements'), 'site-announcements', 'Site Announcements', '站点公告',
   'Site updates and important notices (admin posting only)', '站点更新与重要通知(仅管理员发帖)', 'Megaphone', TRUE, 10),
  ((SELECT id FROM forum_categories WHERE slug = 'beginners'), 'help', 'Cubing Help & Questions', '新手求助',
   'Beginner questions and help — no question is too basic', '新手提问与入门求助,任何问题都欢迎', 'HelpCircle', FALSE, 10),
  ((SELECT id FROM forum_categories WHERE slug = 'beginners'), 'tutorials', 'Guides & How-tos', '教程与指南',
   'Tutorials, guides and learning resources', '教程、指南与学习资源分享', 'BookOpen', FALSE, 20),
  ((SELECT id FROM forum_categories WHERE slug = 'general'), 'speedcubing', 'General Speedcubing Discussion', '速拧综合讨论',
   'General discussion of speedcubing technique, methods and community', '速拧技术、方法与社区综合讨论', 'MessageSquare', FALSE, 10),
  ((SELECT id FROM forum_categories WHERE slug = 'general'), 'hardware', 'Hardware', '硬件区',
   'Cubes and equipment: releases, reviews, tuning and collections', '魔方硬件:新品、评测、调校与收藏', 'Box', FALSE, 20),
  ((SELECT id FROM forum_categories WHERE slug = 'general'), 'software', 'Software', '软件区',
   'Timers, solvers, simulators and other cubing software', '计时器、求解器、模拟器等软件讨论', 'MonitorSmartphone', FALSE, 30),
  ((SELECT id FROM forum_categories WHERE slug = 'general'), 'blind', 'Blindsolving', '盲拧讨论',
   'Blindsolving methods, memo systems and algorithms', '盲拧方法、记忆方案与公式讨论', 'EyeOff', FALSE, 40),
  ((SELECT id FROM forum_categories WHERE slug = 'general'), 'theory', 'Puzzle Theory & FMC', '理论与 FMC',
   'Puzzle theory, group theory and fewest moves research', '魔方理论、群论与最少步(FMC)研究', 'Sigma', FALSE, 50),
  ((SELECT id FROM forum_categories WHERE slug = 'general'), 'progression', 'Cubing Progression', '进步日志',
   'Personal progression threads and practice logs', '个人进步日志与练习记录', 'TrendingUp', FALSE, 60),
  ((SELECT id FROM forum_categories WHERE slug = 'competitions'), 'wca-comps', 'Official WCA Competitions', 'WCA 官方比赛',
   'Discussion of official WCA competitions', 'WCA 官方比赛的讨论与约伴', 'Trophy', FALSE, 10),
  ((SELECT id FROM forum_categories WHERE slug = 'competitions'), 'forum-comps', 'Forum Competitions', '论坛赛',
   'Unofficial competitions run by the forum', '站内举办的线上比赛', 'Swords', FALSE, 20),
  ((SELECT id FROM forum_categories WHERE slug = 'videos'), 'videos', 'Video Gallery', '视频分享',
   'Share and discuss cubing videos', '魔方视频分享与讨论', 'Video', FALSE, 10),
  ((SELECT id FROM forum_categories WHERE slug = 'videos'), 'records', 'Record Solves', '纪录视频',
   'Record solve videos and discussion', '官方纪录视频与讨论', 'Medal', FALSE, 20),
  ((SELECT id FROM forum_categories WHERE slug = 'community'), 'off-topic', 'Off-Topic', '闲聊灌水',
   'Anything not about cubing', '魔方之外的闲聊', 'Coffee', FALSE, 10),
  ((SELECT id FROM forum_categories WHERE slug = 'community'), 'introductions', 'Member Introductions', '新人报到',
   'Introduce yourself to the community', '新成员自我介绍', 'Hand', FALSE, 20),
  ((SELECT id FROM forum_categories WHERE slug = 'community'), 'site-feedback', 'Site Feedback', '站点反馈',
   'Bug reports and suggestions for this site', '本站问题反馈与功能建议', 'MessageCircleWarning', FALSE, 30);
