-- 站内通知。目前由 recon 另解 / 评论 / 回复触发,收件人 = 管理员 + 被回复者。
-- user_key / actor_key 语义同 comments.author_id:绑了 WCA = 真 wca_id,没绑 = `u<uid>`(shared/account.ts ownerKey)。
-- 未读 = read_at IS NULL。邮件由 utils/notify.ts 旁路发送,不写本表以外的状态。
CREATE TABLE IF NOT EXISTS notifications (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_key    VARCHAR(20)  NOT NULL,
  kind        VARCHAR(32)  NOT NULL,   -- recon_alt | recon_comment | recon_reply
  actor_key   VARCHAR(20)  NOT NULL DEFAULT '',
  actor_name  VARCHAR(100) NOT NULL DEFAULT '',
  title       VARCHAR(200) NOT NULL DEFAULT '',
  excerpt     TEXT         NOT NULL DEFAULT '',
  link        TEXT         NOT NULL DEFAULT '',
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  read_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_unread
  ON notifications (user_key, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_notifications_recent
  ON notifications (user_key, created_at DESC);
