-- 0073_page_notices.sql — 每页顶部管理员通知条 (page_notices)
-- 用途:管理员在任意页顶部挂一段文本(维护中 / WIP / 已知 bug 等),让用户知情。
-- admin 行内编辑,public GET 短缓存;server/routes/page_notices.ts。
-- path 为匹配模式:精确 `/scramble/stats`、前缀 `/recon/*`、全站 `/*`(已 strip lang 前缀)。

-- 防御性:trg_set_updated_at 只在 schema.pg.sql 里定义。CREATE OR REPLACE 让已有此
-- 函数的 prod 是 no-op,也让 fresh local PG 单独 apply 本 migration 时自洽。
CREATE OR REPLACE FUNCTION trg_set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE page_notices (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path         TEXT         NOT NULL UNIQUE,
  level        TEXT         NOT NULL DEFAULT 'info' CHECK (level IN ('info','warning','maintenance')),
  body_en      TEXT         NOT NULL DEFAULT '',
  body_zh      TEXT         NOT NULL DEFAULT '',
  enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
  dismissible  BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_page_notices_enabled ON page_notices(enabled) WHERE enabled;
CREATE TRIGGER page_notices_updated_at BEFORE UPDATE ON page_notices
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
