-- 0091_pattern_examples.sql — /scramble/pattern/search 的示例预设 (pattern_examples)
-- 用途:管理员自行维护「示例」一排按钮,点一下把整个图案编辑器载入该预设。
-- 之前 4 个示例硬编码在 page.tsx 的 EXAMPLES 常量里,改一次要发一次版;搬进 DB 后
-- 管理员在页面上就能加/改/删/排序。server/routes/pattern_examples.ts。
--
-- q = 页面 ?q= 的同一份编码(单一源,存的就是可分享的 URL 参数):
--   45 位 [0-5] 格子色类(5 个图案 × 9 格,GRAY=5) + '-' + 5 × 2 位十六进制面分配位掩码
--   (bit0..5 = U R F D L B)。校验正则见路由 Q_RE。
-- continuous 一并存,因为「图案连续」是预设语义的一部分(同一图案开关它结果集不同)。

CREATE TABLE pattern_examples (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position    INTEGER      NOT NULL DEFAULT 0,
  name_zh     VARCHAR(60)  NOT NULL,
  name_en     VARCHAR(60)  NOT NULL,
  q           TEXT         NOT NULL,
  continuous  BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_pattern_examples_position ON pattern_examples(position);
CREATE TRIGGER pattern_examples_updated_at BEFORE UPDATE ON pattern_examples
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

-- 种子 = 原先硬编码的 4 个(图案 1 分配到全六面 → 掩码 3f,其余 4 个图案全灰未分配)。
-- 结果数已实测:棋盘 3、六点 1、十字 2、条纹 8,均瞬时完成。
INSERT INTO pattern_examples (position, name_zh, name_en, q, continuous) VALUES
  (0, '棋盘', 'Checkerboard', '010101010555555555555555555555555555555555555-3f00000000', FALSE),
  (1, '六点', 'Six spots',    '000010000555555555555555555555555555555555555-3f00000000', FALSE),
  (2, '十字', 'Crosses',      '101000101555555555555555555555555555555555555-3f00000000', FALSE),
  (3, '条纹', 'Stripes',      '012012012555555555555555555555555555555555555-3f00000000', FALSE);
