-- Import CubingApp beginner last-layer sets and supplement 4x4 PLL Parity.
-- Generated by packages/alg-build/gen_cubingapp_beginner_ll_sql.mts.
-- Upstream: CubingApp commit 613a49885dc618023368e5f0c2a25024b8c7e9a5 (MIT).

INSERT INTO alg_sets (puzzle, set_slug, source, scraped_at) VALUES
  ('3x3', '2-look-oll', 'https://cubingapp.com/algorithms/2-Look-OLL; https://github.com/spencerchubb/cubingapp/commit/613a49885dc618023368e5f0c2a25024b8c7e9a5', NOW()),
  ('3x3', '2-look-pll', 'https://cubingapp.com/algorithms/2-Look-PLL; https://github.com/spencerchubb/cubingapp/commit/613a49885dc618023368e5f0c2a25024b8c7e9a5', NOW()),
  ('4x4', 'pll-parity', 'https://speedcubedb.com/a/4x4/PLLParity; https://cubingapp.com/algorithms/4x4-PLL-Parity; https://github.com/spencerchubb/cubingapp/commit/613a49885dc618023368e5f0c2a25024b8c7e9a5', NOW())
ON CONFLICT (puzzle, set_slug) DO UPDATE SET source = EXCLUDED.source, scraped_at = EXCLUDED.scraped_at;

WITH payload AS (SELECT $cubingapp_2look_oll$[
  {
    "position": 0,
    "name": "Bar",
    "subgroup": "Edges",
    "setup": "F U R U' R' F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "oell",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "F R U R' U' F'",
          "source": "cubingapp",
          "note": {
            "en": "F sexy F'",
            "zh": "F 性感转动 F'"
          }
        }
      ]
    ]
  },
  {
    "position": 1,
    "name": "L shape",
    "subgroup": "Edges",
    "setup": "F R U R' U' F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "oell",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "F U R U' R' F'",
          "source": "cubingapp",
          "note": {
            "en": "F inverse sexy F'",
            "zh": "F 反性感转动 F'"
          }
        }
      ]
    ]
  },
  {
    "position": 2,
    "name": "Sune",
    "subgroup": "Corners",
    "setup": "R U2' R' U' R U' R'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R U R' U R U2 R'",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 3,
    "name": "Antisune",
    "subgroup": "Corners",
    "setup": "R U R' U R U2' R'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R U2 R' U' R U' R'",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of Sune",
            "zh": "小鱼的逆公式"
          }
        }
      ]
    ]
  },
  {
    "position": 4,
    "name": "H OLL",
    "subgroup": "Corners",
    "setup": "R U2' R' U' R U R' U' R U' R' U'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "U R U R' U R U' R' U R U2 R'",
          "source": "cubingapp",
          "note": {
            "en": "Double Sune with cancellation",
            "zh": "双小鱼，消去重复转动"
          }
        }
      ]
    ]
  },
  {
    "position": 5,
    "name": "T OLL",
    "subgroup": "Corners",
    "setup": "F R' F' r U R U' r'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "r U R' U' r' F R F'",
          "source": "cubingapp",
          "note": {
            "en": "Sexy sledge with wide moves",
            "zh": "性感转动接 Sledge，使用宽层转动"
          }
        }
      ]
    ]
  },
  {
    "position": 6,
    "name": "L OLL",
    "subgroup": "Corners",
    "setup": "r U R' U' r' F R F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "F R' F' r U R U' r'",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of T OLL",
            "zh": "T OLL 的逆公式"
          }
        }
      ]
    ]
  },
  {
    "position": 7,
    "name": "Pi OLL",
    "subgroup": "Corners",
    "setup": "R' U2 R2 U R2' U R2 U2' R'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R U2 R2' U' R2 U' R2' U2' R",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 8,
    "name": "U OLL",
    "subgroup": "Corners",
    "setup": "R' U2' R' D' R U2' R' D R2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R2 D' R U2 R' D R U2 R",
          "source": "cubingapp"
        }
      ]
    ]
  }
]$cubingapp_2look_oll$::jsonb AS body),
items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))
UPDATE alg_cases AS c
SET position = (items.item->>'position')::integer, name = items.item->>'name', subgroup = items.item->>'subgroup',
    setup = items.item->>'setup', sticker = items.item->'sticker', algs = items.item->'algs'
FROM items
WHERE c.puzzle = '3x3' AND c.set_slug = '2-look-oll' AND c.name = items.item->>'name';

WITH payload AS (SELECT $cubingapp_2look_oll$[
  {
    "position": 0,
    "name": "Bar",
    "subgroup": "Edges",
    "setup": "F U R U' R' F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "oell",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "F R U R' U' F'",
          "source": "cubingapp",
          "note": {
            "en": "F sexy F'",
            "zh": "F 性感转动 F'"
          }
        }
      ]
    ]
  },
  {
    "position": 1,
    "name": "L shape",
    "subgroup": "Edges",
    "setup": "F R U R' U' F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "oell",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "F U R U' R' F'",
          "source": "cubingapp",
          "note": {
            "en": "F inverse sexy F'",
            "zh": "F 反性感转动 F'"
          }
        }
      ]
    ]
  },
  {
    "position": 2,
    "name": "Sune",
    "subgroup": "Corners",
    "setup": "R U2' R' U' R U' R'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R U R' U R U2 R'",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 3,
    "name": "Antisune",
    "subgroup": "Corners",
    "setup": "R U R' U R U2' R'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R U2 R' U' R U' R'",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of Sune",
            "zh": "小鱼的逆公式"
          }
        }
      ]
    ]
  },
  {
    "position": 4,
    "name": "H OLL",
    "subgroup": "Corners",
    "setup": "R U2' R' U' R U R' U' R U' R' U'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "U R U R' U R U' R' U R U2 R'",
          "source": "cubingapp",
          "note": {
            "en": "Double Sune with cancellation",
            "zh": "双小鱼，消去重复转动"
          }
        }
      ]
    ]
  },
  {
    "position": 5,
    "name": "T OLL",
    "subgroup": "Corners",
    "setup": "F R' F' r U R U' r'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "r U R' U' r' F R F'",
          "source": "cubingapp",
          "note": {
            "en": "Sexy sledge with wide moves",
            "zh": "性感转动接 Sledge，使用宽层转动"
          }
        }
      ]
    ]
  },
  {
    "position": 6,
    "name": "L OLL",
    "subgroup": "Corners",
    "setup": "r U R' U' r' F R F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "F R' F' r U R U' r'",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of T OLL",
            "zh": "T OLL 的逆公式"
          }
        }
      ]
    ]
  },
  {
    "position": 7,
    "name": "Pi OLL",
    "subgroup": "Corners",
    "setup": "R' U2 R2 U R2' U R2 U2' R'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R U2 R2' U' R2 U' R2' U2' R",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 8,
    "name": "U OLL",
    "subgroup": "Corners",
    "setup": "R' U2' R' D' R U2' R' D R2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": "",
      "mask": "ocll",
      "scheme": "FFFF00,404040,404040,404040,404040,404040"
    },
    "algs": [
      [
        {
          "alg": "R2 D' R U2 R' D R U2 R",
          "source": "cubingapp"
        }
      ]
    ]
  }
]$cubingapp_2look_oll$::jsonb AS body),
items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))
INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)
SELECT '3x3', '2-look-oll', (item->>'position')::integer, item->>'name', item->>'subgroup', item->>'setup', item->'sticker', item->'algs'
FROM items
WHERE NOT EXISTS (SELECT 1 FROM alg_cases WHERE puzzle = '3x3' AND set_slug = '2-look-oll' AND name = item->>'name');

WITH payload AS (SELECT $cubingapp_2look_pll$[
  {
    "position": 0,
    "name": "Matching Corners (aka Headlights)",
    "subgroup": "Corners",
    "setup": "R2' B2' R F R' B2' R F' R",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "R' F R' B2 R F' R' B2 R2",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 1,
    "name": "No Matching (aka No Headlights)",
    "subgroup": "Corners",
    "setup": "F R' F' R U R U' R' F R U' R' U R U R' F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 2,
    "name": "Ua perm",
    "subgroup": "Edges",
    "setup": "M2' U' M U2' M' U' M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U M U2 M' U M2",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of Ub perm",
            "zh": "Ub perm 的逆公式"
          }
        },
        {
          "alg": "R U' R U R U R U' R' U' R2",
          "source": "cubingapp"
        },
        {
          "alg": "U2 R U R' U R' U' R2 U' R' U R' U R",
          "source": "cubingapp",
          "note": {
            "en": "AUF adjusted to match the case diagram",
            "zh": "调整 AUF，使公式与情况图一致"
          }
        }
      ]
    ]
  },
  {
    "position": 3,
    "name": "Ub perm",
    "subgroup": "Edges",
    "setup": "M2' U M U2' M' U M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U' M U2 M' U' M2",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of Ua perm",
            "zh": "Ua perm 的逆公式"
          }
        },
        {
          "alg": "R2' U R U R' U' R3 U' R' U R'",
          "source": "cubingapp"
        },
        {
          "alg": "U2 R' U R' U' R' U' R' U R U R2 U2",
          "source": "cubingapp",
          "note": {
            "en": "AUF adjusted to match the case diagram",
            "zh": "调整 AUF，使公式与情况图一致"
          }
        }
      ]
    ]
  },
  {
    "position": 4,
    "name": "H perm",
    "subgroup": "Edges",
    "setup": "M2' U M2' U2' M2' U M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U' M2 U2 M2 U' M2",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 5,
    "name": "Z perm",
    "subgroup": "Edges",
    "setup": "U2' M U2' M2' U2' M U M2' U M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U' M2 U' M' U2 M2 U2 M' U2",
          "source": "cubingapp"
        }
      ]
    ]
  }
]$cubingapp_2look_pll$::jsonb AS body),
items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))
UPDATE alg_cases AS c
SET position = (items.item->>'position')::integer, name = items.item->>'name', subgroup = items.item->>'subgroup',
    setup = items.item->>'setup', sticker = items.item->'sticker', algs = items.item->'algs'
FROM items
WHERE c.puzzle = '3x3' AND c.set_slug = '2-look-pll' AND c.name = items.item->>'name';

WITH payload AS (SELECT $cubingapp_2look_pll$[
  {
    "position": 0,
    "name": "Matching Corners (aka Headlights)",
    "subgroup": "Corners",
    "setup": "R2' B2' R F R' B2' R F' R",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "R' F R' B2 R F' R' B2 R2",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 1,
    "name": "No Matching (aka No Headlights)",
    "subgroup": "Corners",
    "setup": "F R' F' R U R U' R' F R U' R' U R U R' F'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 2,
    "name": "Ua perm",
    "subgroup": "Edges",
    "setup": "M2' U' M U2' M' U' M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U M U2 M' U M2",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of Ub perm",
            "zh": "Ub perm 的逆公式"
          }
        },
        {
          "alg": "R U' R U R U R U' R' U' R2",
          "source": "cubingapp"
        },
        {
          "alg": "U2 R U R' U R' U' R2 U' R' U R' U R",
          "source": "cubingapp",
          "note": {
            "en": "AUF adjusted to match the case diagram",
            "zh": "调整 AUF，使公式与情况图一致"
          }
        }
      ]
    ]
  },
  {
    "position": 3,
    "name": "Ub perm",
    "subgroup": "Edges",
    "setup": "M2' U M U2' M' U M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U' M U2 M' U' M2",
          "source": "cubingapp",
          "note": {
            "en": "Inverse of Ua perm",
            "zh": "Ua perm 的逆公式"
          }
        },
        {
          "alg": "R2' U R U R' U' R3 U' R' U R'",
          "source": "cubingapp"
        },
        {
          "alg": "U2 R' U R' U' R' U' R' U R U R2 U2",
          "source": "cubingapp",
          "note": {
            "en": "AUF adjusted to match the case diagram",
            "zh": "调整 AUF，使公式与情况图一致"
          }
        }
      ]
    ]
  },
  {
    "position": 4,
    "name": "H perm",
    "subgroup": "Edges",
    "setup": "M2' U M2' U2' M2' U M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U' M2 U2 M2 U' M2",
          "source": "cubingapp"
        }
      ]
    ]
  },
  {
    "position": 5,
    "name": "Z perm",
    "subgroup": "Edges",
    "setup": "U2' M U2' M2' U2' M U M2' U M2'",
    "sticker": {
      "kind": "face",
      "us": "",
      "ub": "",
      "uf": "",
      "ul": "",
      "ur": ""
    },
    "algs": [
      [
        {
          "alg": "M2 U' M2 U' M' U2 M2 U2 M' U2",
          "source": "cubingapp"
        }
      ]
    ]
  }
]$cubingapp_2look_pll$::jsonb AS body),
items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))
INSERT INTO alg_cases (puzzle, set_slug, position, name, subgroup, setup, sticker, algs)
SELECT '3x3', '2-look-pll', (item->>'position')::integer, item->>'name', item->>'subgroup', item->>'setup', item->'sticker', item->'algs'
FROM items
WHERE NOT EXISTS (SELECT 1 FROM alg_cases WHERE puzzle = '3x3' AND set_slug = '2-look-pll' AND name = item->>'name');

-- Five source formulas were canonical state/text matches in the audited production baseline.
-- Prepend only the 17 missing formulas; keep every existing parity alternative and case id.
WITH payload AS (SELECT $cubingapp_4x4_pll_parity$[
  {
    "position": 0,
    "name": "OPP Parity",
    "existing": true,
    "algs": [
      [
        {
          "alg": "2R2 U2 2R2 Uw2 2R2 Uw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "2R2 U2 2R2 Uw2 2R2 Uw2"
  },
  {
    "position": 1,
    "name": "Adj Parity",
    "existing": true,
    "algs": [
      [
        {
          "alg": "R' U R U' 2R2 U2' 2R2 Uw2' 2R2 Uw2' U' R' U' R",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "R' U R U' 2R2 U2 2R2 Uw2 2R2 Uw2 U' R' U' R"
  },
  {
    "position": 2,
    "name": "CwO",
    "existing": false,
    "algs": [
      [
        {
          "alg": "m2 U m2 U m' U2 m2 U2 m' U 2L2 U2 2L2 Uw2 2L2 Uw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "m2 U m2 U m' U2 m2 U2 m' U 2L2 U2 2L2 Uw2 2L2 Uw2"
  },
  {
    "position": 3,
    "name": "CcwO",
    "existing": false,
    "algs": [
      [
        {
          "alg": "Uw2 2L2 Uw2 2L2 U2 3Rw' Rw2 R' U2 m2 U2 m' U m2 U m2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "Uw2 2L2 Uw2 2L2 U2 3Rw' Rw2 R' U2 m2 U2 m' U m2 U m2"
  },
  {
    "position": 4,
    "name": "W",
    "existing": false,
    "algs": [
      [
        {
          "alg": "R' U R' U' R' U' R' U R U Rw2 U2 2R2 Uw2 2R2 Uw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "R' U R' U' R' U' R' U R U Rw2 U2 2R2 Uw2 2R2 Uw2"
  },
  {
    "position": 5,
    "name": "Pj",
    "existing": false,
    "algs": [
      [
        {
          "alg": "R U R' U' R' F R2 U' R' U' R U R' F' U' 2L2 U2 2L2 Uw2 2L2 Uw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "R U R' U' R' F R2 U' R' U' R U R' F' U' 2L2 U2 2L2 Uw2 2L2 Uw2"
  },
  {
    "position": 6,
    "name": "Ba",
    "existing": true,
    "algs": [
      [
        {
          "alg": "x' Rw2 U2 Rw2 Uw2 2R2 Uw2 F 3Rw U' R U2 L' U R'",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "x' Rw2 U2 Rw2 Uw2 2R2 Uw2 F 3Rw U' R U2 L' U R'"
  },
  {
    "position": 7,
    "name": "Bb",
    "existing": false,
    "algs": [
      [
        {
          "alg": "U x Rw2 U2 Rw2 Uw2 2R2 Uw2 B 3Rw' U R' U2 L U' R",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "U x Rw2 U2 Rw2 Uw2 2R2 Uw2 B 3Rw' U R' U2 L U' R"
  },
  {
    "position": 8,
    "name": "Ca",
    "existing": false,
    "algs": [
      [
        {
          "alg": "U2 Uw2 2R2 Uw2 2R2 U2 Rw2 F R U R U' R' F' R U2 R' U2 R",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "U2 Uw2 2R2 Uw2 2R2 U2 Rw2 F R U R U' R' F' R U2 R' U2 R"
  },
  {
    "position": 9,
    "name": "Cb",
    "existing": false,
    "algs": [
      [
        {
          "alg": "U R' U2 R U2 R' F R U R' U' R' F' Rw2 U2 2R2 Uw2 2R2 Uw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "U R' U2 R U2 R' F R U R' U' R' F' Rw2 U2 2R2 Uw2 2R2 Uw2"
  },
  {
    "position": 10,
    "name": "Da",
    "existing": false,
    "algs": [
      [
        {
          "alg": "R' U L' U2 R U' 3Rw B Rw2 U2 Rw2 Uw2 2R2 Uw2 x'",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "R' U L' U2 R U' 3Rw B Rw2 U2 Rw2 Uw2 2R2 Uw2 x'"
  },
  {
    "position": 11,
    "name": "Db",
    "existing": false,
    "algs": [
      [
        {
          "alg": "R U R' F' R U R' U' R' F R2 U' R' u2 2R2 u2 2R2 U2 2R2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "R U R' F' R U R' U' R' F R2 U' R' u2 2R2 u2 2R2 U2 2R2"
  },
  {
    "position": 12,
    "name": "Ka",
    "existing": false,
    "algs": [
      [
        {
          "alg": "U 3Lw' U R' D2 R U' R' D2 x' Rw2 U2 2R2 Uw2 2R2 Uw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "U 3Lw' U R' D2 R U' R' D2 x' Rw2 U2 2R2 Uw2 2R2 Uw2"
  },
  {
    "position": 13,
    "name": "Kb",
    "existing": false,
    "algs": [
      [
        {
          "alg": "U' 3Rw U' L D2 L' U L D2 x' Lw2 U2 2L2 Uw2 2L2 Uw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "U' 3Rw U' L D2 L' U L D2 x' Lw2 U2 2L2 Uw2 2L2 Uw2"
  },
  {
    "position": 14,
    "name": "M",
    "existing": false,
    "algs": [
      [
        {
          "alg": "U2 Rw2 F2 U2 2R2 U R' U' R U R' D R D' R F2 U Rw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "U2 Rw2 F2 U2 2R2 U R' U' R U R' D R D' R F2 U Rw2"
  },
  {
    "position": 15,
    "name": "Pa",
    "existing": false,
    "algs": [
      [
        {
          "alg": "R U R' F' R U R' U' R' F R2 U' R' U' 2R2 U2 2R2 u2 2R2 u2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "R U R' F' R U R' U' R' F R2 U' R' U' 2R2 U2 2R2 u2 2R2 u2"
  },
  {
    "position": 16,
    "name": "Pb",
    "existing": true,
    "algs": [
      [
        {
          "alg": "2R2 U2 2R2 u2 2R2 u2 R U R' F' R U R' U' R' F R2 U' R'",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "2R2 U2 2R2 u2 2R2 u2 R U R' F' R U R' U' R' F R2 U' R'"
  },
  {
    "position": 17,
    "name": "Diag C",
    "existing": true,
    "algs": [
      [
        {
          "alg": "F R U' R' U' R U R' F' U' 2R2 U2 2R2 u2 2R2 u2 U' R U R' U' R' F R F'",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "F R U' R' U' R U R' F' U' 2R2 U2 2R2 u2 2R2 u2 U' R U R' U' R' F R F'"
  },
  {
    "position": 18,
    "name": "Q",
    "existing": false,
    "algs": [
      [
        {
          "alg": "z Rw2 Uw2' R2' Uw2' F R U R' U' R U R' U' R U R' U' F' U2' R2 Uw2' Rw2' z'",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "z Rw2 Uw2 R2 Uw2 F R U R' U' R U R' U' R U R' U' F' U2 R2 Uw2 Rw2 z'"
  },
  {
    "position": 19,
    "name": "Sa",
    "existing": false,
    "algs": [
      [
        {
          "alg": "F R U' R' U' R U R' F' R U R' U' R' F R F' U' 2R2 U2 2R2 u2 2R2 u2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "F R U' R' U' R U R' F' R U R' U' R' F R F' U' 2R2 U2 2R2 u2 2R2 u2"
  },
  {
    "position": 20,
    "name": "Sb",
    "existing": false,
    "algs": [
      [
        {
          "alg": "F R U' R' U' R U R' F' R U R' U' R' F R F' 2R2 U2 2R2 u2 2R2 u2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "F R U' R' U' R U R' F' R U R' U' R' F R F' 2R2 U2 2R2 u2 2R2 u2"
  },
  {
    "position": 21,
    "name": "X",
    "existing": false,
    "algs": [
      [
        {
          "alg": "Rw2 F2 U2 Rw2 F' U' R' U R U' R' U R U' R' U R F R2 U2 F2 Rw2",
          "source": "cubingapp"
        }
      ]
    ],
    "canonicalKey": "Rw2 F2 U2 Rw2 F' U' R' U R U' R' U R U' R' U R F R2 U2 F2 Rw2"
  }
]$cubingapp_4x4_pll_parity$::jsonb AS body),
items AS (SELECT value AS item FROM payload, jsonb_array_elements(body))
UPDATE alg_cases AS c
SET algs = jsonb_build_array(
  COALESCE((
    SELECT jsonb_agg(source.entry ORDER BY source.ord)
    FROM jsonb_array_elements(COALESCE(items.item->'algs'->0, '[]'::jsonb)) WITH ORDINALITY AS source(entry, ord)
    WHERE (items.item->>'existing')::boolean = false
      AND NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(COALESCE(c.algs->0, '[]'::jsonb)) AS existing(entry)
      WHERE regexp_replace(existing.entry->>'alg', '\s', '', 'g') = regexp_replace(source.entry->>'alg', '\s', '', 'g')
    )
  ), '[]'::jsonb) || COALESCE(c.algs->0, '[]'::jsonb)
)
FROM items
WHERE c.puzzle = '4x4' AND c.set_slug = 'pll-parity' AND c.name = items.item->>'name';

DO $cubingapp_beginner_ll_counts$
DECLARE got BIGINT;
BEGIN
  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = '2-look-oll';
  IF got <> 9 THEN RAISE EXCEPTION '3x3/2-look-oll: expected 9 cases, got %', got; END IF;
  SELECT SUM(jsonb_array_length(algs->0)) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = '2-look-oll';
  IF got <> 9 THEN RAISE EXCEPTION '3x3/2-look-oll: expected 9 algorithms, got %', got; END IF;
  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = '2-look-pll';
  IF got <> 6 THEN RAISE EXCEPTION '3x3/2-look-pll: expected 6 cases, got %', got; END IF;
  SELECT SUM(jsonb_array_length(algs->0)) INTO got FROM alg_cases WHERE puzzle = '3x3' AND set_slug = '2-look-pll';
  IF got <> 10 THEN RAISE EXCEPTION '3x3/2-look-pll: expected 10 algorithms, got %', got; END IF;
  SELECT COUNT(*) INTO got FROM alg_cases WHERE puzzle = '4x4' AND set_slug = 'pll-parity';
  IF got <> 22 THEN RAISE EXCEPTION '4x4/pll-parity: expected 22 cases, got %', got; END IF;
  SELECT SUM(jsonb_array_length(algs->0)) INTO got FROM alg_cases WHERE puzzle = '4x4' AND set_slug = 'pll-parity';
  IF got <> 57 THEN RAISE EXCEPTION '4x4/pll-parity: expected 57 algorithms, got %', got; END IF;
END
$cubingapp_beginner_ll_counts$;
