CREATE TABLE recon_videos (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_wca_id   VARCHAR(20) NOT NULL,
  storage_key    VARCHAR(80) NOT NULL UNIQUE,
  mime           VARCHAR(40) NOT NULL
                   CHECK (mime IN ('video/mp4', 'video/webm', 'video/quicktime')),
  size_bytes     BIGINT NOT NULL CHECK (size_bytes BETWEEN 1 AND 209715200),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_recon_videos_owner_created
  ON recon_videos(owner_wca_id, created_at DESC);
