-- CubePB port: public PB profiles, current records, history and leaderboards.

CREATE TABLE pb_profiles (
  owner_key  VARCHAR(20) PRIMARY KEY,
  is_public  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER pb_profiles_updated_at BEFORE UPDATE ON pb_profiles
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TABLE pb_records (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_key     VARCHAR(20) NOT NULL REFERENCES pb_profiles(owner_key) ON DELETE CASCADE,
  event_id      VARCHAR(20) NOT NULL CHECK (event_id IN (
    '333', '222', '444', '555', '666', '777', '333oh', 'clock', 'minx',
    'pyram', 'skewb', 'sq1', '333bf', '444bf', '555bf', '333fm', '333mbf'
  )),
  record_type   VARCHAR(8) NOT NULL CHECK (record_type IN ('single', 'mean', 'average')),
  set_size      INTEGER NOT NULL,
  result_value  INTEGER NOT NULL CHECK (result_value > 0),
  happened_on   DATE NOT NULL,
  cube_name     VARCHAR(120) NOT NULL DEFAULT '',
  comments      VARCHAR(1000) NOT NULL DEFAULT '',
  is_current    BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (
    (record_type = 'single' AND set_size = 1) OR
    (record_type = 'mean' AND set_size = 3) OR
    (record_type = 'average' AND set_size IN (5, 12, 50, 100, 1000))
  ),
  CHECK (event_id <> '333mbf' OR (record_type = 'single' AND set_size = 1))
);

CREATE UNIQUE INDEX uq_pb_records_current
  ON pb_records(owner_key, event_id, record_type, set_size)
  WHERE is_current;
CREATE INDEX idx_pb_records_owner_history
  ON pb_records(owner_key, event_id, record_type, set_size, happened_on DESC);
CREATE INDEX idx_pb_records_leaderboard
  ON pb_records(event_id, record_type, set_size, result_value, happened_on)
  WHERE is_current;

CREATE TRIGGER pb_records_updated_at BEFORE UPDATE ON pb_records
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
