-- Supporter claim lifecycle: public claimed marker, private evidence snapshot,
-- review history, and reversible account ownership.

ALTER TABLE sponsors
  ADD COLUMN claimed_by_user_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
  ADD COLUMN claimed_at TIMESTAMPTZ;

CREATE INDEX idx_sponsors_claimed_by_user
  ON sponsors(claimed_by_user_id)
  WHERE claimed_by_user_id IS NOT NULL;

CREATE TABLE sponsor_claims (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sponsor_id          BIGINT NOT NULL REFERENCES sponsors(id) ON DELETE CASCADE,
  user_id             BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  status              VARCHAR(16) NOT NULL
                      CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled', 'revoked')),
  claimant_note       VARCHAR(500),
  profile_snapshot    JSONB NOT NULL
                      CHECK (jsonb_typeof(profile_snapshot) = 'object'),
  reviewed_by_user_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
  review_note         VARCHAR(500),
  reviewed_at         TIMESTAMPTZ,
  cancelled_at        TIMESTAMPTZ,
  revoked_by_user_id  BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
  revocation_note     VARCHAR(500),
  revoked_at          TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_sponsor_claims_active_sponsor
  ON sponsor_claims(sponsor_id)
  WHERE status IN ('pending', 'approved');
CREATE INDEX idx_sponsor_claims_user ON sponsor_claims(user_id, created_at DESC);
CREATE INDEX idx_sponsor_claims_status ON sponsor_claims(status, created_at);
CREATE TRIGGER sponsor_claims_updated_at BEFORE UPDATE ON sponsor_claims
  FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
