-- Give every membership a stable public ID. Revocation keeps the row so reactivation keeps the same ID.
ALTER TABLE memberships
  ADD COLUMN vip_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX uq_memberships_vip_number ON memberships(vip_number);
