/**
 * Worker-backed non-WCA puzzle scrambles for the timer (FTO / Kilominx /
 * Redi / Master Pyraminx).
 *
 * Every one of these is generated by csTimer — we do not ship a scrambler of
 * our own for them. FTO/Redi keep the legacy vendored worker; Kilominx/Master
 * Pyraminx use the runtime-neutral @cuberoot/puzzle-solvers provider shared by
 * Web and Mobile. Both adapters run off the timer input thread and expose the
 * same small per-generator queue contract:
 *
 *   - `take*()` (what the dispatcher calls) pops a ready scramble and kicks off a
 *     background top-up. It returns '' when the queue is dry — a *loading*
 *     placeholder, never a fake or wrong-puzzle scramble.
 *   - `nextNonWcaScramble()` awaits a real one; SoloView calls it to fill that
 *     placeholder in and shows a spinner meanwhile (same shape as the WCA pool).
 *
 * FTO costs 1-3 s per scramble and Master Pyraminx ~5 s cold, so keeping a
 * couple queued is what makes the hand-off after a solve feel instant.
 */

import type { EventId } from '../types';
import {
  CSTIMER_NONWCA_TIMER_EVENTS,
  CSTIMER_NONWCA_TIMER_KEYS,
  isCstimerNonWcaTimerEvent,
} from '@cuberoot/puzzle-solvers/cstimer-nonwca';
import { cstimerWorkerScramble, warmCstimerWorker } from './cstimer_worker';
import {
  _resetSharedCstimerNonWcaPool,
  nextSharedCstimerNonWcaScramble,
  prefetchSharedCstimerNonWcaScramble,
  takeSharedCstimerNonWcaScramble,
} from './cstimer-nonwca-shared-pool';

export interface CstimerScrambleSpec {
  /** csTimer scrambler key, passed verbatim to `scrMgr.scramblers[key]`. */
  key: string;
  /** csTimer's 2nd argument. Random-state generators ignore it; random-move generators use it. */
  length?: number;
}

/**
 * Timer EventId → csTimer scrambler key. Every entry here is random-state
 * (IDA* solve of a uniformly random state, inverted), i.e. the same class of
 * scramble WCA uses for the official events.
 *
 * Adding one: pick a key that exists in `public/scramble_module.js`
 * (`Object.keys(scrMgr.scramblers)`), add the EventId + EVENTS entry in
 * ../types.ts, an APPEND_EVENTS entry in _shell/SoloView.tsx, the csTimer
 * scrType in ../storage/{import,export}_cstimer.ts, and a case in
 * tests/timer_nonwca_scramble.test.ts.
 */
const CSTIMER_KEYS: Partial<Record<EventId, CstimerScrambleSpec>> = {
  fto:      { key: 'ftoso' },
  gear:     { key: 'gearso' },
  ivy:      { key: 'ivyso' },
  redi:     { key: 'rediso' },
};

// Gear and Ivy keep their csTimer keys above for import/export compatibility
// and oracle tests, but their production generators now live in
// @cuberoot/puzzle-solvers and are consumed by both Web and Mobile.
const NON_WCA: Partial<Record<EventId, CstimerScrambleSpec>> = {
  fto: CSTIMER_KEYS.fto,
  redi: CSTIMER_KEYS.redi,
};

/** All Timer events whose asynchronous source is csTimer-derived. */
export const NON_WCA_EVENT_IDS: ReadonlyArray<EventId> = Object.freeze([
  ...(Object.keys(NON_WCA) as EventId[]),
  ...CSTIMER_NONWCA_TIMER_EVENTS,
]);

/** The csTimer spelling kept for import/export and oracle compatibility. */
export function cstimerKeyForEvent(event: EventId): string | null {
  if (isCstimerNonWcaTimerEvent(event)) return CSTIMER_NONWCA_TIMER_KEYS[event];
  return CSTIMER_KEYS[event]?.key ?? null;
}

/** Does this event need the csTimer worker to produce a scramble? */
export function isNonWcaEvent(event: EventId): boolean {
  return NON_WCA[event] !== undefined || isCstimerNonWcaTimerEvent(event);
}

/** How many scrambles to keep queued ahead of the user. */
const TARGET = 2;

const queues = new Map<string, string[]>();
const inFlight = new Map<string, number>();

/** 生成参数本身就是队列身份,防止同一项目的不同专项类型串队。 */
function queueKey(spec: CstimerScrambleSpec): string {
  return `${spec.key}|${spec.length ?? 0}`;
}

function queueOf(spec: CstimerScrambleSpec): string[] {
  const id = queueKey(spec);
  let q = queues.get(id);
  if (!q) { q = []; queues.set(id, q); }
  return q;
}

/** Kick off background generation until the queue reaches TARGET. */
function topUp(spec: CstimerScrambleSpec, label = spec.key): void {
  const id = queueKey(spec);
  const q = queueOf(spec);
  const running = inFlight.get(id) ?? 0;
  const want = TARGET - q.length - running;
  for (let i = 0; i < want; i++) {
    inFlight.set(id, (inFlight.get(id) ?? 0) + 1);
    void cstimerWorkerScramble(spec.key, spec.length ?? 0)
      .then((s) => { if (s) queueOf(spec).push(s); })
      .catch((err) => { console.warn(`[timer] ${label} scramble failed:`, err); })
      .finally(() => { inFlight.set(id, Math.max(0, (inFlight.get(id) ?? 1) - 1)); });
  }
}

/** 同步消费任意 csTimer worker 队列；空串表示仍在异步生成。 */
export function takeCstimerScramble(spec: CstimerScrambleSpec): string {
  const s = queueOf(spec).shift() ?? '';
  topUp(spec);
  return s;
}

/** 预热任意 csTimer worker 队列。 */
export function prefetchCstimerScramble(spec: CstimerScrambleSpec): void {
  warmCstimerWorker();
  topUp(spec);
}

/** 等待任意 csTimer worker 队列的一条真实打乱。 */
export async function nextCstimerScramble(spec: CstimerScrambleSpec, label = spec.key): Promise<string> {
  const queued = queueOf(spec).shift();
  if (queued) { topUp(spec, label); return queued; }
  try {
    const s = await cstimerWorkerScramble(spec.key, spec.length ?? 0);
    topUp(spec, label);
    return s;
  } catch (err) {
    console.warn(`[timer] ${label} scramble failed:`, err);
    return '';
  }
}

/**
 * The synchronous generator registered with the scramble dispatcher. Returns a
 * queued scramble, or '' while the engine is still working (SoloView renders a
 * spinner and fills it in via `nextNonWcaScramble`).
 */
export function takeNonWcaScramble(event: EventId): string {
  if (isCstimerNonWcaTimerEvent(event)) {
    return takeSharedCstimerNonWcaScramble(event);
  }
  const spec = NON_WCA[event];
  return spec ? takeCstimerScramble(spec) : '';
}

/** Start the engine + fill the queue for `event` ahead of demand. */
export function prefetchNonWca(event: EventId): void {
  if (isCstimerNonWcaTimerEvent(event)) {
    prefetchSharedCstimerNonWcaScramble(event);
    return;
  }
  const spec = NON_WCA[event];
  if (spec) prefetchCstimerScramble(spec);
}

/**
 * Await one real scramble for `event`. Prefers the queue, otherwise asks the
 * worker directly. Resolves to '' only when the engine is unavailable.
 */
export async function nextNonWcaScramble(
  event: EventId,
  signal?: AbortSignal,
): Promise<string> {
  if (isCstimerNonWcaTimerEvent(event)) {
    return nextSharedCstimerNonWcaScramble(event, signal);
  }
  const spec = NON_WCA[event];
  return spec ? nextCstimerScramble(spec, event) : '';
}

/** Test/util hook: drop all queues. */
export function _resetNonWcaQueues(): void {
  queues.clear();
  inFlight.clear();
  _resetSharedCstimerNonWcaPool();
}
