export type SupportedLanguage = 'en' | 'zh';

export const COPY = {
  en: {
    actionFailed: 'That did not work. Your existing data was kept.',
    ao5: 'ao5',
    ao12: 'ao12',
    best: 'Best',
    checking: 'Checking',
    comment: 'Comment',
    corruptDetail: 'CubeRoot will not replace invalid data. Import a valid backup to recover.',
    corruptTitle: 'Local data needs attention',
    data: 'Data',
    dataCount: 'solves stored on this device',
    delete: 'Delete',
    deleteConfirm: 'Delete this solve?',
    dnf: 'DNF',
    emptyHistory: 'Your solves will appear here after you stop the timer.',
    exportData: 'Export backup',
    exportSuccess: 'Backup prepared.',
    fullSite: 'Full website',
    fullSiteDetail: 'Open the complete CubeRoot site when you need tools that are not bundled in the app.',
    history: 'History',
    holdTime: 'Hold to start',
    holdToArm: 'Hold to start',
    importData: 'Import backup',
    importConfirm: (incoming: number, current: number) => `Import ${incoming} solves and replace the current ${current}? You can undo this once from Settings.`,
    importSuccess: 'Backup imported.',
    importTooLarge: 'This backup is larger than 10 MB and was not opened.',
    inspection: 'Inspection',
    keepHolding: 'Keep holding',
    language: 'Language',
    light: 'Light',
    newScramble: 'New scramble',
    noInspection: 'Off',
    offline: 'Offline',
    online: 'Online',
    openFullSite: 'Open cuberoot.me',
    privacy: 'Privacy policy',
    penalty: 'Penalty',
    releaseToStart: 'Release to start',
    save: 'Save',
    seconds15: '15 seconds',
    settings: 'Settings',
    support: 'Support',
    solves: 'Solves',
    system: 'System',
    tapToStop: 'Tap to stop',
    theme: 'Theme',
    timer: 'Timer',
    timerHint: 'Touch and hold, then release. Press Space when using a keyboard.',
    title: 'CubeRoot',
    undoImport: 'Undo last import',
    undoImportConfirm: 'Restore the data from before the last import?',
    undoImportSuccess: 'Previous data restored.',
    version: 'Version',
    dark: 'Dark',
  },
  zh: {
    actionFailed: '操作失败，原有数据已保留。',
    ao5: 'ao5',
    ao12: 'ao12',
    best: '最佳',
    checking: '检查中',
    comment: '备注',
    corruptDetail: 'CubeRoot 不会覆盖无效数据。请导入有效备份进行恢复。',
    corruptTitle: '本地数据需要处理',
    data: '数据',
    dataCount: '条记录保存在本机',
    delete: '删除',
    deleteConfirm: '确定删除这条记录吗？',
    dnf: 'DNF',
    emptyHistory: '停表后，记录会显示在这里。',
    exportData: '导出备份',
    exportSuccess: '备份已准备好。',
    fullSite: '完整网站',
    fullSiteDetail: '需要 App 尚未内置的工具时，再打开完整 CubeRoot 网站。',
    history: '记录',
    holdTime: '启动按住时间',
    holdToArm: '按住开始',
    importData: '导入备份',
    importConfirm: (incoming: number, current: number) => `将导入 ${incoming} 条记录并替换当前 ${current} 条记录。可在设置中撤销一次，确定继续吗？`,
    importSuccess: '备份已导入。',
    importTooLarge: '备份超过 10 MB，未打开。',
    inspection: '观察时间',
    keepHolding: '继续按住',
    language: '语言',
    light: '浅色',
    newScramble: '换一个打乱',
    noInspection: '关闭',
    offline: '离线',
    online: '在线',
    openFullSite: '打开 cuberoot.me',
    privacy: '隐私政策',
    penalty: '罚时',
    releaseToStart: '松开开始',
    save: '保存',
    seconds15: '15 秒',
    settings: '设置',
    support: '联系支持',
    solves: '次数',
    system: '跟随系统',
    tapToStop: '轻触停止',
    theme: '主题',
    timer: '计时',
    timerHint: '触摸并按住，松开开始。连接键盘时可用空格键。',
    title: 'CubeRoot',
    undoImport: '撤销上次导入',
    undoImportConfirm: '恢复到上次导入前的数据吗？',
    undoImportSuccess: '已恢复导入前的数据。',
    version: '版本',
    dark: '深色',
  },
} as const;

export function preferredLanguage(): SupportedLanguage {
  return navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en';
}
